### ISSUE TITLE
Will this contain the Nvidia ClayMoreDual Miner fix?

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#1]
Will this contain the ClayMoreDual fix for nvidia provided by @DillonN  ?

https://github.com/nicehash/NiceHashMiner/pull/985

**Comment by DillonN** [comment]
Yes it will

**Comment by billmcilhargey** [comment]
Perfect  Thanks been waiting to try this fix out (officially, rather than the test build I did compiling the code :) )  +1
