### ISSUE TITLE
Worker Name Restrictions

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#10]
Comparing Legacy to NiceHashMiner2  any reason for the Worker Name Restrictions?

For instance I can have more than 7 characters on NHM2 but not NHM Legacy

**Comment by DillonN** [comment]
Right now the 7 character limit is carried over from previous NHM versions. I will coordinate and see what can be done about it.

**Comment by billmcilhargey** [comment]
Ok

To add to this request - in the GUI box

Could you restrict the textbox to xx characters to prevent more than 7.

Also in .NET Framework you can restrict the other characters that you don't allow too.

Here is an expression that may help for the field (suggestion but feel free to modify anyway you like)

https://stackoverflow.com/questions/20223484/c-sharp-textbox-with-only-letters-and-numbers

But don't remove the field check when you click start as someone could modify their config incorrectly too

**Comment by DillonN** [comment]
Yeah something I will look into at the same time

**Comment by DillonN** [comment]
Worker names have been extended to 15 chars
