### ISSUE TITLE
Bad Access

### ISSUE THREAD

**Issue by corkyslurp** [nicehash/NiceHashMiner#100]
Stratum connection failed: faild to connect to x15.usa.nicehash.com port 3339: Bad access on the GPU
Stratum connection failed: failed to connect to scryptjanenf16.usa.nicehash.com port 3348: Bad access on the CPU
Please help fix this

**Comment by theLosers106** [comment]
Could you give a screenshot of the problem? While you're at it, try using a different server, eg. Europe - Amsterdam.

**Comment by corkyslurp** [comment]
Ive already tried all 4 servers, and went back to the USA, Heres a screenshot of the problem, after retrying a couple of times.
![screenshot_1](https://cloud.githubusercontent.com/assets/19316009/15230431/966163be-1863-11e6-96d2-71a9c578c6c4.png)

**Comment by corkyslurp** [comment]
Can you give me an idea for making it work???

**Comment by corkyslurp** [comment]
NVM fixxed it. IT couldnt go through my firewall xD

**Comment by theLosers106** [comment]
NVM? So is it resolved now? I would like to know what did you do to make it work as other users might have the same problem in the future and it could help them.. (:

**Comment by BaalMcKloud** [comment]
seems like his firewall blocked the connection to the mining server

**Comment by corkyslurp** [comment]
My norton called the things trojans, which is now a problem, causing it to crash(I think). I just had to make an exception to the firewall.

**Comment by theLosers106** [comment]
Ok then.. I'll be closing this issue now..
