### ISSUE TITLE
0xc000007b error in EthDcrMiner64

### ISSUE THREAD

**Issue by andzur** [nicehash/NiceHashMiner#100]
![przechwytywanie2](https://user-images.githubusercontent.com/29987133/28756125-baf5635c-7568-11e7-9227-78b7bb77320d.PNG)

Only Claymore dual has a problem - other miner working ok.
Any ideas?

**Comment by DillonN** [comment]
It looks like ClaymoreDual is unable to open on your computer. Do you have a 64 bit OS? There may also be a disk problem - you could try running chkdsk

**Comment by nicehashdev** [comment]
This looks like an issue with OpenCL.dll (being 32bit version instead of 64bit). Copy 64bit version of OpenCL.dll into the folder where you have claymore miner.

You can read more about OpenCL.dll mess here: https://github.com/nicehash/excavator/issues/1

**Comment by andzur** [comment]
OpenCL.dll was the problem.
Copy 64bit version and problem is solved.
Thnx
