### ISSUE TITLE
Nicehash freezing, virtual memory errors

### ISSUE THREAD

**Issue by hallrandyg** [nicehash/NiceHashMiner#1000]
setup:
4 - GeForce GTX 1070s
3.96 GB ram
60 GB SSD
CPU G4400 @ 3.30 GHz

Nicehash is freezing after 10 minutes or so.  I have received CUDA error Driver 719 and if I open Legacy, it automatically say virtual memory is too low.  I'm a noob and have no idea what it should be set to.  Any help would be greatly appreciated.

**Comment by nerdatwork** [comment]
Technically your virtual memory should be total of physical and graphics memory of all cards. So 4GB ram + 4x (size of 1070s) = X. Set this size as your virtual memory. You can google how to set virtual memory for your operating system.
