### ISSUE TITLE
ETH: Job Timeout, disconect, retry in 20 sec...

### ISSUE THREAD

**Issue by domingomartinezt** [nicehash/NiceHashMiner#1001]
I have windows 10, and the following hardware, and version of nicehash legacy

![error2](https://user-images.githubusercontent.com/25778801/36355570-2d4dafec-14b3-11e8-8cc7-bb3d17ec977e.png)

After one or four hours I'm getting this error, that doesn't allow to continue mining.

![error](https://user-images.githubusercontent.com/25778801/36355582-5213c820-14b3-11e8-8137-ecbb35c71bbd.png)

Some of you know how to solve this issue? I'm having a hard time with this error.

Best.

**Comment by krowawo** [comment]
same thing for me, since yesterday in all dagger servers (decred,sia....)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.
**OR**
Most likely a bug in Claymore miner
