### ISSUE TITLE
Issue with ETHEREUM pool not connecting (NHML 1.8.1.8)

### ISSUE THREAD

**Issue by krowawo** [nicehash/NiceHashMiner#1003]
- The ethereum server doesn't connect (also in dual mining Decred, Sia, Pascal... not working)
- This issue started since 17/02/2018 before that everything was fine
- log file attached.
- I lunched the miner alone with another pool and everything worked fine, but with Nicehash pool it doesn't work.
- NHML version= 1.8.1.8, Windows 10 x64, the cards available:
     3* GTX 1070
     1* GTX 1080
     1* GTX 1080 TI
     1* GTX 1060
     2* AMD RX580

The NHML doesn't connect and also doesn't switch from ETH to another pool that works, so i had to disable all Dagger algorithm to make use of my cards.

<img width="960" alt="rig" src="https://user-images.githubusercontent.com/27871670/36357672-9b237b48-1501-11e8-99c9-65441cb687dc.png">

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1735169/log.txt)

**Comment by tusharantal** [comment]
How did u solve this issue i am facing the same problem ?

**Comment by krowawo** [comment]
i didnt change anything, i switched to another miner until it was fixed  (1 week), i think it was a stratum connection problem

**Comment by alimashhdi** [comment]
ali.8859
