### ISSUE TITLE
Can't connect to EU server since 16/02/2018

### ISSUE THREAD

**Issue by krowawo** [nicehash/NiceHashMiner#1004]
Since 16/02/2018 the EU server doesn't connect for me, i have been using it everyday since it has the lowest latency for me.
Now i have to switch to other servers (US, Asia, Brazil) all work fine except the EU.

- I tried to connect and mine DAGGER and Equihash on the EU server but it didn't connect.
- log file attached.
- NHML version 1.8.1.8, Windows 10 x64, the cards available:
3* GTX 1070
1* GTX 1080
1* GTX 1080 TI
1* GTX 1060
2* AMD RX580

I tried to connect with this algorithm and here are the results:
Equihash: not working
DAGGER: not working
Cryptonight: working
Lyra2rev2: working

<img width="957" alt="eu" src="https://user-images.githubusercontent.com/27871670/36357788-6108bd2c-1503-11e8-9650-40f8f16d970c.png">

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1735189/log.txt)

**Comment by dadoremix** [comment]
right now .. i have also problem with ETH @nicehash Eu server, and all others
Socket error, closed

**Comment by krowawo** [comment]
i tried everything, reinstalling new version of windows, changing my internet (tried with 4G and ADSL), using Nicehash miner (for Nvidia), i always get the same error with Equihash and Ethereum.
The problem is that i asked my friend if it works with him and it does, everything work fine with him, so why it doesn't connect with me !!! (all this happened 4 days ago)

**Comment by dadoremix** [comment]
blocking from nicehash?
i trying today hive os .. linux minig
and windows .. 
now, not working also, and my firend say .. working fine .. WTF

**Comment by kaos-1** [comment]
use a proxy?

**Comment by krowawo** [comment]
me too, tried another btc wallet not working, tried with wifi and lan same problem !!!
@kaos-1 i tried using VPN and i got the same result.

**Comment by dadoremix** [comment]
after 4-5 hours .. working again all

**Comment by krowawo** [comment]
@dadoremix good for you, but it doesn't for me, i have to switch to another pool @nicehash please fix this soon.
