### ISSUE TITLE
rx580 gpus not detected by legacy miner 1.8

### ISSUE THREAD

**Issue by romahowa** [nicehash/NiceHashMiner#1007]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by romahowa** [comment]
i can't get running the amd legagy miner 1.8.1.8
on win10 64bit pro.
virtual mem is 130gb
10 rx580 8gb (samsung mem) mounted and properly configured because rig runs very stable with latest cast-xmr with a good 10500h/s

latest amd driver from feb 2018

error in amd detection software:
please advice

regards
romain

**Comment by krowawo** [comment]
at least post a screenshot maybe we can help you, also did you try DDU and fresh install AMD driver?

**Comment by carricha** [comment]
yes DDU and reinstall of AMD driver latest, from november, from december ...
always same error from AMDOpenClDeviceDectection.exe
as written above: rig runs fine with latest cast-xmr mining software with 10500H/s with 10 Rx580 8gb
under w10

![screenshot_20180219-203813](https://user-images.githubusercontent.com/5019815/36394858-7fe2b1e0-15b6-11e8-8d14-b6d5192e5e58.png)

**Comment by mves001** [comment]
10× rx580? On windows 10-64-bit? 8 GPU is a limit as far as I know. You would have to use linux for that but nhml is not available on linux.

**Comment by mves001** [comment]
http://www.gandalph3000.com/cast_xmr/cast-xmr-optimized-cryptonight-miner-for-rx-vega/

"nicehash support will automatically disabled if more then 8 GPUs are used. Otherwise search space could be exhausted to early and the GPUs search in overlapping nonce ranges."

**Comment by romahowa** [comment]
no 8gpu limit is only with amd blockchain driver from aug 2017...new
adrenaline driver from dec 2017 or feb 2018 supports up to 12 gpus... now
running on win10 64 pro 130gb virtual ram and cast-xmr with
forced-compute-mode and patched bios... 12600h/s (lucky samsung mem :-) )

it appears that nh miner does not support more than 8gpus :-(

On 21 Feb 2018 8:51 am, "mves001" <notifications@github.com> wrote:

10× rx580? On windows 10-64-bit? 8 GPU is a limit as far as I know. You
would have to use linux for that but nhml is not available on linux.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nicehash/NiceHashMinerLegacy/issues/1007#issuecomment-367240911>,
or mute the thread

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
