### ISSUE TITLE
mining score problem

### ISSUE THREAD

**Issue by anwar01740** [nicehash/NiceHashMiner#1008]
My hardware are new bought was 29/01/2018 AMD CPU Ryzen 7 1700X @ 4.00GHz. This is complete new pc. 1st 2  week i was get satoshi as mention your profitable score. But right now, profitable satoshi score not match my mining score :( It's to much down.
Also i just add 2 card ( 4gb gtx 1050 ti oc version) new gpu. Both are same problem. score & mining huge missmass.

Any advice please..
![bug1](https://user-images.githubusercontent.com/36644802/36394633-6927982a-15df-11e8-903d-d6b93cca67c8.png)

**Comment by S74nk0** [comment]
Issue not related to client. Issue related to market/price fluctuation. Closing
