### ISSUE TITLE
Shows my cards mining...but is reporting 0 hashpower...$0/day

### ISSUE THREAD

**Issue by pnew311** [nicehash/NiceHashMiner#1009]
Everything seems to be working except the fact that there is no hash power being generated by my 4 RX 560s. It also shows 0 shares/0 rejected. In the GUI it shows that I'm producing $ via my CPU but nothing on my GPUs. Thanks in advance.

Windows 10
mobo: asus z270-a prime
cpu: g3900
gpu: rx560 x 4

AMD Cards available: 4
GPU #0: Baffin (Radeon RX 560 Series), 4096 MB available, 14 compute units (pci bus 2:0:0)
GPU #0 recognized as Radeon RX 460/560
GPU #1: Baffin (Radeon RX 560 Series), 4096 MB available, 14 compute units (pci bus 3:0:0)
GPU #1 recognized as Radeon RX 460/560
GPU #2: Baffin (Radeon RX 560 Series), 4096 MB available, 14 compute units (pci bus 5:0:0)
GPU #2 recognized as Radeon RX 460/560
GPU #3: Baffin (Radeon RX 560 Series), 4096 MB available, 14 compute units (pci bus 6:0:0)
GPU #3 recognized as Radeon RX 460/560
POOL/SOLO version
GPU #0: algorithm ASM
GPU #1: algorithm ASM
GPU #2: algorithm ASM
GPU #3: algorithm ASM
Total cards: 4
ETH: Stratum - connecting to 'daggerhashimoto.eu.nicehash.com' <159.8.13.248> port 3353
DUAL MINING MODE ENABLED: ETHEREUM+DECRED
 DCR: Stratum - connecting to 'decred.eu.nicehash.com' <169.51.33.8> port 3354
ETH: nicehash stratum mode
"-allpools" option is set, default pools can be used for devfee, check "Readme" file for details.
Watchdog enabled
Remote management (READ-ONLY MODE) is enabled on port 4003
 DCR: Stratum - Connected (decred.eu.nicehash.com:3354)

ETH: Stratum - Connected (daggerhashimoto.eu.nicehash.com:3353)
 DCR: Authorized
ETH: Authorized
ETH: 02/19/18-16:04:19 - New job from daggerhashimoto.eu.nicehash.com:3353
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s, GPU3 0.000 Mh/s
 DCR - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0
 DCR: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s, GPU3 0.000 Mh/s
Setting DAG epoch #170...
ETH: 02/19/18-16:04:30 - New job from daggerhashimoto.eu.nicehash.com:3353
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s, GPU3 0.000 Mh/s
 DCR - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0
 DCR: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s, GPU3 0.000 Mh/s
 DCR: 02/19/18-16:04:33 - New job from decred.eu.nicehash.com:3354
ETH: 02/19/18-16:04:48 - New job from daggerhashimoto.eu.nicehash.com:3353
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s, GPU3 0.000 Mh/s
 DCR - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0
 DCR: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s, GPU3 0.000 Mh/s
ETH: 02/19/18-16:05:00 - New job from daggerhashimoto.eu.nicehash.com:3353
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s, GPU3 0.000 Mh/s
 DCR - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0
 DCR: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s, GPU3 0.000 Mh/s

**Comment by Crypto-Lord** [comment]
What's your virtual memory set to? Have you also tried 1 GPU at a time?

**Comment by pnew311** [comment]
Its now set to 16000 MB. Still giving me problems. I'm trying to run it while disabling 1 algo at a time.

**Comment by Crypto-Lord** [comment]
Are you over clocking at all?
What's your power supply?
Also try only 1 GPU at a time

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

**Comment by MudasarSabir** [comment]
╔════════════════════════════════════════════════════════════════╗
║                Claymore's Dual GPU Miner - v15.0               ║
║              ETH + DCR/SIA/LBC/PASC/BLAKE2S/KECCAK             ║
║                       Supercharged Edition                     ║
╚════════════════════════════════════════════════════════════════╝

ETH: 1 pool is specified
Main Ethereum pool is eth.2miners.com:2020
AMD OpenCL platform not found
Be careful with overclocking, use default clocks for first tests
Press "s" for current statistics, "0".."9" to turn on/off cards, "r" to reload pools, "e" or "d" to select current pool, "x" to select GPU
CUDA initializing...

NVIDIA Cards available: 1
CUDA Driver Version/Runtime Version: 10.1/8.0
GPU #0: GeForce 920M, 2048 MB available, 2 compute units, capability: 3.5  (pci bus 1:0:0)
Total cards: 1

All GPUs are 2GB...3GB, miner is completely free in this case, developer fee will not be mined at all.
See Readme for details.


You can use "+" and "-" keys to achieve best ETH speed, see "FINE TUNING" section in Readme for details.

ETHEREUM-ONLY MINING MODE ENABLED (-mode 1)
ETH: eth-proxy stratum mode
"-allpools" option is set, default pools can be used for devfee, check "Readme" file for details.
"-allcoins" option is set, default pools will be used for devfee, check "Readme" file for details.
Watchdog enabled
Remote management (READ-ONLY MODE) is enabled on port 3333

ETH: Stratum - connecting to 'eth.2miners.com' <51.89.96.115> port 2020 (unsecure)
ETH: Stratum - Connected (eth.2miners.com:2020) (unsecure)
ETH: Authorized
Setting DAG epoch #317(3.48GB)...
ETH: 02/21/20-19:44:05 - New job from eth.2miners.com:2020
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s
ETH: 02/21/20-19:44:12 - New job from eth.2miners.com:2020
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s
Setting DAG epoch #317 for GPU0
Create GPU buffer for GPU0
CUDA error - cannot allocate big buffer for DAG. Check readme.txt for possible solutions.
ETH: 02/21/20-19:44:17 - New job from eth.2miners.com:2020
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s
GPU 0 failed
Setting DAG epoch #317 for GPU0
GPU 0, CUDA error 11 - cannot write buffer for DAG
GPU 0 failed
ETH: 02/21/20-19:44:24 - New job from eth.2miners.com:2020
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s




I have same issue with my graphic card, my graphic card show  but did not work. Help me!
