### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by corkyslurp** [nicehash/NiceHashMiner#101]
Whenever i mine over night, I check it in the morning, and it says the programs not responding. I really would like to make a couple of bucks (in a year with my pc xD)

**Comment by theLosers106** [comment]
Could you send the logfile to nhm@nicehash.com .. thanks.. (:

**Comment by theLosers106** [comment]
It seems that your driver crashed.. Did you overclock your cards? If not, you might need to play around with the intensity as it might be too high for your cards..

**Comment by corkyslurp** [comment]
they came Overclocked. ill under clock it to find out.But now it tries to mine neoscrypt, which the miner wont mine for some reason, so my GPU is not doing anything.

**Comment by corkyslurp** [comment]
nvm it went back to X15

**Comment by theLosers106** [comment]
you could go to the settings page and add -i to something like 10 or something and start going upwards till it crashes.

**Comment by nicehashdev** [comment]
Please, use latest NHM version and enable DisableWindowsErrorReporting in settings. NHM will be able to restart your miner whenever it crashes.
