### ISSUE TITLE
Keccak algorith not working

### ISSUE THREAD

**Issue by SamadKhan123** [nicehash/NiceHashMiner#101]
Hello guys i am having issues with NHML keccak algorithm not working it shows retry in 30 seconds and i sitched off keccak please help.

**Comment by nicehashdev** [comment]
This may happen when all orders are full. Unfortunately, nobody dared to put unlimited bottom order for low price (hint for buyers - do this and you may profit $$$). This is nothing NHML can do about it, but if you wish to prevent this from happening, just disable keccak.

**Comment by JeanneRSA** [comment]
Hi guys i need some help with NHML i am having trouble with keccak it works fine for the first minute but then the profit just drops down on algo so i am swiching of would like to keep it running but it is killing my profit daily

**Comment by linlinooi** [comment]
@nicehashdev what do you mean by "to put unlimited bottom order for low price (hint for buyers - do this and you may profit $$$)"? I'm having the same problem too the keccak algorithm just keep on retrying. Sorry for asking this stupid question, I'm a newbie here.
