### ISSUE TITLE
when will it give me the old balance?!?!?

### ISSUE THREAD

**Issue by Userisalreadytaken** [nicehash/NiceHashMiner#1010]
Original Old Balance: | 0.00040112 BTC
-- | --
Reimbursed pending: | 0.00004011 BTC
Reimbursed by now: | 0.00000000 BTC
Still to repay: | 0.00036101 BTC

It didnt said any others things more then that (sry for my bad english)

**Comment by Crypto-Lord** [comment]
This is a forum for **NiceHashMinerLegacy**. You'll want to take your question to the Nicehash reddit forum linked below:

https://www.reddit.com/r/NiceHash/

**Comment by S74nk0** [comment]
Issue not related to client. Write to support@nicehash.com
