### ISSUE TITLE
Multi CPU is still not working

### ISSUE THREAD

**Issue by aracila** [nicehash/NiceHashMiner#1013]
Hi, I know this was discussed and reported as fixed, but it is still not working, at list for me.
I have dual Xeon setup, and then I lunch 1 CPU it is mining at 300 H/s, but when I lunch both CPU it is showing that both of them running but the hash rate is half on each. 
![1](https://user-images.githubusercontent.com/12886351/36463050-4dedd932-1695-11e8-876c-71f6f5766305.png)
![2](https://user-images.githubusercontent.com/12886351/36463058-57db529e-1695-11e8-9b2a-630aef029a1b.png)

Please help.

**Comment by crmaxx** [comment]
It's works in "1.8.2.0 Pre-release 2"

**Comment by aracila** [comment]
For some reason 1.8.2.0_Pre xmrig mining is very low. It is working but on 2 CPUs it is slower that one CPU in 1.8.1.8. Huge pages are enabled.
![1](https://user-images.githubusercontent.com/12886351/36488429-6dd2a64a-16f1-11e8-9a9c-62488e452ac4.png)
![2](https://user-images.githubusercontent.com/12886351/36488430-6de58d64-16f1-11e8-9044-58c289c064cc.png)

**Comment by crmaxx** [comment]
I talk only about new Xmr-Stak miner in 1.8.2.0 Pre-release 2

**Comment by aracila** [comment]
Ah, I see now. 
Yes i can confirm that new one is working on both CPUs and gives me total of 460H/s
Thanks!
![2](https://user-images.githubusercontent.com/12886351/36489410-f253377a-16f3-11e8-80fa-145401bd3726.png)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
