### ISSUE TITLE
Cannot establish SSL/TLS connection

### ISSUE THREAD

**Issue by pavel4840** [nicehash/NiceHashMiner#1014]
Somewhere after 12 hours of normal operation of the mining I get the following lines in red:
Cannot establish SSL/TLS connection
Stratum - Cannot connect  to cryptonight.eu.nicehash.com port 33355
DevFee:  Stratum - Failed to connect, retry in 20 sec...
What is the reason for such lines? What should I do in this case?

**Comment by cmoore159** [comment]
My AMD 7770 Is doing the same thing this morning. I hope someone can find a fix.

**Comment by pavel4840** [comment]
After 12 hours of successful mining I get the following screen:
![_nicehash](https://user-images.githubusercontent.com/36538280/36968327-53ce6816-2073-11e8-81a9-d7686c9cbdba.jpg)
