### ISSUE TITLE
Will not benchmark anything......

### ISSUE THREAD

**Issue by annern55** [nicehash/NiceHashMiner#1015]
So I'm trying to benchmark all equihash algos and cryptonight, but only cryptonight sgminer is working.....
And none of the equihash benchmarks will run, and benchmarking takes fking hours even with quick on!?!? Like comeon, and not enough with that, my benchmark settings are deleting itself so this is the third time I am trying to benchmark and it takes hours each time... jesus please help

**Comment by techman05** [comment]
Do them piece by piece if you can. I think I've been ignoring sgminer  since it seemed to be an issue in the last release with device id issues.

That loosing benchmarks on fail is a big pain. I hope theres a better way to store them on each completion.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
