### ISSUE TITLE
HD 7990 only one gpu working

### ISSUE THREAD

**Issue by TDPort** [nicehash/NiceHashMiner#1016]
I am running an AMD HD 7990, it has two gpu's on one board. They are showing up as radeon 280x in the run window, but only one will run at a time. 

If both open one will register but show zero hashrate. 

If I try to simultaneously mine with my CPU it also shows OpenCL but works separately fine. It will run for a few minutes, show a memory usage warning, and then when it shuts down it shows error #87 

I am new to nicehash and mining. I would appreciate any help. Thank you.

**Comment by OrnelasVLK** [comment]
Did you have any solution?

**Comment by Simaex** [comment]
Try radically lower intensity. Windows tend to use one GPU for screen output and so less resources are available. Another option is to set your output to different GPU, say internal grafics if available. In this case you can fully utilize you HD7990 for mining.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
