### ISSUE TITLE
Excavator for Neoscrypt

### ISSUE THREAD

**Issue by brenosabino** [nicehash/NiceHashMiner#1017]
Could you add the latest excavator server from nicehash miner 2 to this miner? It works better in neoscrypt for me on a 1070ti.

**Comment by wikimeza** [comment]
I totally agree, I just opened an issue about the same.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Neoscrypt not relevant anymore
