### ISSUE TITLE
Update excavator and add more excavator algos to NHML

### ISSUE THREAD

**Issue by wikimeza** [nicehash/NiceHashMiner#1018]
I wish that next version of NHML includes the latest excavator miner 1.4.4 or newer instead of the 1.1.4 that has been there since the beginning, also to include the keccak, neoscrypt, lyra2REv2 and blake2s, because them are faster than the ccminer included in NHML, specially the neoscrypt excavator. All of them are already in NHM2 is just porting them to NHML. I look forward to see this soon. Thanks in advance.
![2018-02-21 2](https://user-images.githubusercontent.com/36720572/36519201-cd1e58fc-174f-11e8-9867-efc7ba75bbb5.png)
![2018-02-21 3](https://user-images.githubusercontent.com/36720572/36519202-cde19be6-174f-11e8-9eff-65752c8b7531.png)

**Comment by bruvv** [comment]
it will not it's nicehash miner v2 exclusive (this for antivirus protection)

**Comment by S74nk0** [comment]
Issue not related to nhm/nhml. Issue is related to discontinued nhm2 client
