### ISSUE TITLE
GetSummary exception: (...) refused it 127.0.0.1:400x

### ISSUE THREAD

**Issue by andzur** [nicehash/NiceHashMiner#102]
Getting the following msg in console of NHML:

[19:36:08] [ClaymoreDual-MINER_ID(1095)-DEVICE_IDs(1,2,3)] No connection could be made because the target machine actively refused it 127.0.0.1:4003

and similar with ccminer, ewbf, ...

Miners are working OK.

Is it a problem?

**Comment by DillonN** [comment]
This can happen when miners are starting up, it's nothing to worry about. Basically NHML is trying to contact the miner to get speed info, but the miner is not yet ready for connections so it is denied. Once the miner is finished starting up the messages should stop.

**Comment by andzur** [comment]
Thnx for info
