### ISSUE TITLE
Syntax to disable cooldown check timer?

### ISSUE THREAD

**Issue by Mindanser** [nicehash/NiceHashMiner#1022]
I've seen the following text several times, "Advanced option to disable the cooldown checker, if it is causing problems"

But nowhere do I see where and how to actually add that to a config file.   What is the syntax, and what file does it go in?

**Comment by BIG1** [comment]
Did u solve this?
What is really cooldown??

**Comment by Mindanser** [comment]
Hey Big1,

No, I didn't solve this. No one answered the question.

I believe cooldown was created to prevent overheating of the CPU. However, I've asked in various places, but never gotten the actual syntax. I'm planning to search the actual code to see if it's in there.

Cheers,
Eric

**Comment by BIG1** [comment]
Ok.
I stopped using nicehash program. I downloaded the newest miner and mining directly to my nicehash address.
Working perfect

**Comment by Mindanser** [comment]
Which miner are you using instead? CPUMiner-multi?

**Comment by BIG1** [comment]
Claymore. I never used cpu to mine.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

This feature is implemented.
Set `"CoolDownCheckEnabled": false,` in `General.json`
