### ISSUE TITLE
Socket was closed remotely

### ISSUE THREAD

**Issue by BIG1** [nicehash/NiceHashMiner#1023]
Keep getting socket was closed remotely (by pool)
ETG: Connection lost, retry in 20 sec...
Socket was closed remotely (by pool)
DCR: Connection lost, retry in 20 sex...

And if I wait the window close and it starts mine again...with the same errors...

What is doing this?
I hadnt this issue when mining with 1 gpu. I have now connected 13 amd radeon 570 gpu.

**Comment by BIG1** [comment]
Started mining with 7gpu. Still the same issue.
Logfile attached.
7x radeon 570 8gb (memstrap), no OC.

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1753491/log.txt)

**Comment by BIG1** [comment]
What is MAX cool time exceeded. RESTARTING?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.
**OR**
Your user account is/was temporary banned (write to support@nicehash.com to check)
