### ISSUE TITLE
NMHL - support for Intel Core i7-960 - 8M Cache, 3.20 GHz, 4.80 GT/s Intel QPI ?

### ISSUE THREAD

**Issue by allstarfxmaster** [nicehash/NiceHashMiner#1024]
Hello, 

Is it possible to support [Intel® Core™ i7-960 Processor](https://ark.intel.com/products/37151/Intel-Core-i7-960-Processor-8M-Cache-3_20-GHz-4_80-GTs-Intel-QPI), under this link there are  all specifications for it.  Currently I'm even not able to see it on my Devices list on NHML.

**Comment by S74nk0** [comment]
Device is not supported
