### ISSUE TITLE
Idle mode not working after manually stopping the miner

### ISSUE THREAD

**Issue by pavo1** [nicehash/NiceHashMiner#1025]
When I manually start and stop the miner, the idle mode no longer works. Ideally, I would like the idle mode to start my miner but not stop it if I become active again - light tasks like web browsing are not a problem while mining. Then, when gaming, I would manually stop the miner. Currently, I often forget to start the miner again (and idle mode stops working after manually switching it) so I end up with my pc running idle all day.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
