### ISSUE TITLE
Not sure whats going on with the 1080

### ISSUE THREAD

**Issue by Crypto-Lord** [nicehash/NiceHashMiner#1026]
![weird](https://user-images.githubusercontent.com/28488696/36631900-5e97b52c-194d-11e8-92a5-62e121199400.png)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1754547/log.txt)

**Comment by allstarfxmaster** [comment]
I had same issue when I putted in ExtraLaunchParemeters intensity bigger than 24.

**Comment by Crypto-Lord** [comment]
Haven't tweaked any ExtraLaunchParameters, whats the default parameters set to?

**Comment by allstarfxmaster** [comment]
Ok. Now I see a problem. Read this troubleshooter document provided on NH website. You need to take off AMD card. You can use only one type of card for mining on you PC/rig, like only NVidia or pnly AMD. 

https://miner.nicehash.com/guides/NHM_troubleshooter_en.pdf

**Comment by Crypto-Lord** [comment]
That could be an issue but I've also been running both AMD & nVidia since June 2017 with minimal problems. This was the first time this issue arose, now it's mining as usual.

**Comment by nerdatwork** [comment]
@Crypto-Lord Its too much overclocking. It has nothing to do with mixed up miners with amd or nvidia. Use stock settings without any undervolt or overcocking. I too face this issue. CCminer should restart if it gets stuck in a loop.

https://github.com/nicehash/NiceHashMinerLegacy/issues/865

**Comment by S74nk0** [comment]
OC issue unable to help
