### ISSUE TITLE
Btc balance not update

### ISSUE THREAD

**Issue by serh39** [nicehash/NiceHashMiner#1027]
![image](https://user-images.githubusercontent.com/24960808/36640018-88f094b2-1a4a-11e8-8188-ee2d5b31b390.png)
![image](https://user-images.githubusercontent.com/24960808/36640023-a7220542-1a4a-11e8-84d7-8a6dded44101.png)

**Comment by millereh** [comment]
+1

**Comment by allstarfxmaster** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/issues/1012

**Comment by serh39** [comment]
Thank you for @allstarfxmaster
