### ISSUE TITLE
Add - Claymore's NeoScrypt AMD GPU Miner. v1.0

### ISSUE THREAD

**Issue by KJHgf34** [nicehash/NiceHashMiner#1029]
Add - Claymore's NeoScrypt AMD GPU Miner. v1.0

**Comment by nerdatwork** [comment]
I second that. Miners should be updated as soon as possible. Claymore 11 is released ages ago and yet no release from NHML :(

**Comment by puithove** [comment]
I'd like to see this too, adds another option for my AMD cards.

**Comment by jmhickman** [comment]
Yes, please add this.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

NeoScrypt not relevant anymore
