### ISSUE TITLE
Same GPUs  - different mining capabilties.

### ISSUE THREAD

**Issue by JS-88** [nicehash/NiceHashMiner#1030]
I was running one AMD 290X card for a while, but recently added another of the exact same brand and model. When running a benchmark, and exploring what algorithms were applicable to this card in the Legacy miner, it seems the second one (or the first one, I can't tell how they're numbers) is applicable to fwer algorithms than when it was running as a single card previously - why is this?

**Comment by S74nk0** [comment]
This is possible. Same GPU models can yield different performance based on your rig hardware setup most likely. 

This is something you will need to figure out on your own.

Issue related to rig hardware setup
