### ISSUE TITLE
NHML-1.8.1.9 crashing/closing for no apparent reason.

### ISSUE THREAD

**Issue by inventorAdam5** [nicehash/NiceHashMiner#1031]
When trying to bench mark my GPU, the program will suddenly close without warning. I have tried running the benchmark with and without 3rd party miners, to no avail.
Build ->https://pcpartpicker.com/user/inventorAdam5/saved/h6W7YJ
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1760021/log.txt)

**Comment by inventorAdam5** [comment]
updated drivers, works now.

**Comment by inventorAdam5** [comment]
Crashing... again.
reinstalled gpu drivers, reinstalled NHML 1.8.1.9
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1772486/log.txt)
Log from running the miner once until it crashed a few minuets later.

**Comment by inventorAdam5** [comment]
Restarted computer, deleted log.txt, started mining, waited till it crashed after about 30-40 minuets, uploaded new log file below.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1772626/log.txt)

**Comment by majekqwert** [comment]
I have the same problem. Usually the restart is carried out in between 40-60 min. Cooling appears in the logs. Cards have a temperature of max 63, fans max 55%.

**Comment by inventorAdam5** [comment]
Found a fix, took a bit of work to get it set up though.
http://jkcrypto.com/automatically-restart-mining-if-stopped/#Part_4_How_to_Automatically_restart_Mining_Rig_in_case_of_FreezeHang
Also, just a heads up, the shortcuts included in the download will need to be changed manualy by right clicking them and going to properties.

The **bold** parts need to be changed to the correct path.

For target: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -f **C:\Users\Adam\Desktop\Miner**\MinerMonitor\jkcrypto-minermon.ps1

For path: **C:\Users\Adam\Desktop\Miner**\MinerMonitor

The "script auto restart" shortcut can be deleted and corrected by creating a shortcut to the autorestart.bat file.
Hope this helps.
