### ISSUE TITLE
How can i control intensity in equihash?

### ISSUE THREAD

**Issue by zalaca** [nicehash/NiceHashMiner#1033]
I have try this comand "miner --intensity 1 1" on extra parametres but doest work at all,any help?Thank you

**Comment by ww40** [comment]
I'm also encountering issues, if i set "miner --intensity 1 1" in extra launch parameters for EWBF equihash i get around 94% gpu usuage, if i try "miner --intensity 32 64" I get 100% gpu usuage. I'm looking at limiting my gpu usuage using this parameterto set it at around 50% GPU usuage. My second card is running at 100% which is fine.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Use Extra launch parameters. For now this page https://github.com/nicehash/NiceHashMinerLegacy/wiki/%5BObsolete%5D-Algorithm-ExtraLaunchParameters. The concept is the same but with mine plugins the paths are slightly different.
