### ISSUE TITLE
Please update to dstm 0.6.0

### ISSUE THREAD

**Issue by pducharme** [nicehash/NiceHashMiner#1034]
@DillonN Please update Legacy to dstm 0.6.0.  Thanks!

**Comment by kaos-1** [comment]
There are no performance improvements.

**Comment by MaKCuMyC** [comment]
you can do it yourself.

**Comment by pducharme** [comment]
I know, but I feel that it should contains the latest release in the 3rdParty ZIP ;)

**Comment by MaKCuMyC** [comment]
God bless and we will see it in next release.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
