### ISSUE TITLE
Bitcoin exchange rate on display

### ISSUE THREAD

**Issue by g5-freemen** [nicehash/NiceHashMiner#1036]
Maybe it possible to add showing the bitcoin exchange rate in NHML ?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

This feature is implemented 
![image](https://user-images.githubusercontent.com/1517233/60584820-81328780-9d8e-11e9-9f3f-7c3e62a44994.png)
