### ISSUE TITLE
Nicehash Miner Speed is NA

### ISSUE THREAD

**Issue by CryptoGuruYT** [nicehash/NiceHashMiner#1037]
First Issue:
I have successfully benchmarked the system, but when I try to mine it shows a speed of NA and never actually pulls up the miner. I am using Nicehash 1.8.1.5 and have 5 RX 580 8gb cards installed. Why is this and how do I fix this?

Second Issue:
I am using this older version of Nicehash because the newer one(s) get stuck on downloading miners. I found that the way to fix this is to manually put the bin and 3rd party bin folders in the miner, but when I do this nicehash simply deletes it and tries to download anyways.

Help with either or both issues is appreciated.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
