### ISSUE TITLE
Bitdefender AV shows TROJAN GENERIC please have AV company whitelist

### ISSUE THREAD

**Issue by Idea4u** [nicehash/NiceHashMiner#1038]
Hello I have a simple request, please speak with AV companies about having files in your download whitelisted due to the fact of them showing up as a virus. If the crypto mining community is to trust the files to be downloaded then the AV companies should also trust these files. Not everyone is willing to download something when a program they trust states the files are a virus. Yeah I COULD turn off AV but is it the safest of things to do? Yeah I could download something that has a virus signature BUT SHOULD someone download a file with a virus signature is it truly the wisest thing to do? Also wouldn't it be best for the company as a whole to appear trustworthy? Can someone be scared off by a company which looks possibly malicious, in my opinion I would have to say YES. Can a company request their software files to be whitelisted so they do not make AV programs say "HEY DONT TRUST THIS" I would have to think so.... if AV programs didn't list the software as a virus would more people trust it, hence giving the company more hashing power, thus making the company more of a leader in the industry? I would really have to think that if nicehash would like to gain more they would do more to address this issue. Thank you for your time

**Comment by Idea4u** [comment]
https://www.bitdefender.com/submit/

**Comment by luongk** [comment]
NHM 2.0 is designed to be AV safe.  The likelihood of the antivirus companies whitelisting miners is fairly low, given that they are often involved in trojan horse attacks.

**Comment by Crypto-Lord** [comment]
AV companies blacklist mining programs for the vast majority of non-mining users that may unsuspectingly download software with malicious mining software. Your best and probably only bet would be to whitelist the mining programs within the AV program itself.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

All miners software closed or open source is marked flagged by AV software. Malware authors frequently bundle miner software. Use it at your own risk.
