### ISSUE TITLE
NiceHash Miner Legacy 1.8.1.9 Cannot Execute ERROR 

### ISSUE THREAD

**Issue by Tweest** [nicehash/NiceHashMiner#1039]
Not sure if this is happening to any of you. NHML worked for 1-2 days before giving me this error message. Any help will be appreciated, thank you. 
![hvjh](https://user-images.githubusercontent.com/36751265/36766607-707d5d14-1beb-11e8-9881-3721e235ff76.JPG)

**Comment by luongk** [comment]
That looks like a WinRAR error, not NHML?
