### ISSUE TITLE
Claymore performance went from 29mh/s to 4 mh/s on all 6 xrx580 8gb graphic cards

### ISSUE THREAD

**Issue by Arcandel** [nicehash/NiceHashMiner#104]
Claymore performance went from 29mh/s to 4 mh/s on all 6 xrx580 8gb graphic any idea why it only went windows update ;/

**Comment by scavern** [comment]
Latest AMD graphics driver could have caused this.

**Comment by DillonN** [comment]
As @scavern said this might have been caused by a driver update from Windows Update. Sometimes WU can even give you older drivers than what you had installed if Windows wrongly believes they're newer.

**Comment by adem4ik** [comment]
It is a good practice for any miner to disable WU for drivers and to use manual upgrading instead.
