### ISSUE TITLE
NiceHash Miner Legacy 1.8.1.9 - EWBF miner window is not hiding

### ISSUE THREAD

**Issue by allstarfxmaster** [nicehash/NiceHashMiner#1041]
@DillonN 
I have checked on "Hide mining Windows" on settings tab. When NHML is starting to mine EWBF miner window is not hiding, else windows are hiding.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
