### ISSUE TITLE
Check All Profitability goes to non-working API site

### ISSUE THREAD

**Issue by McFly99** [nicehash/NiceHashMiner#1042]
When in the Legacy app, on the Devices/Algorithms tab, if you click Check All Profitability - it sends you to a broken page on the NiceHash API site. DNS is on OpenDNS,.. so I think it's simply where the link is going...

Pinging www.nicehash.com [104.17.61.220] with 32 bytes of data:
Reply from 104.17.61.220: bytes=32 time=16ms TTL=60

Pinging api.nicehash.com [104.17.60.220] with 32 bytes of data:
Reply from 104.17.60.220: bytes=32 time=18ms TTL=60

**Comment by S74nk0** [comment]
This is removed.
