### ISSUE TITLE
It's dSTm, not dTSm miner, also there's a new version (v0.6) available, please update

### ISSUE THREAD

**Issue by balazscsabarobert** [nicehash/NiceHashMiner#1043]
Official post from the developer: [[ANN] dstm's ZCash / Equihash Nvidia Miner v0.6 (Linux / Windows)](https://bitcointalk.org/index.php?topic=2021765.0)
 
Please update accordingly because apparently everybody uses Equihash algorithm and so far dstm's miner has higher hashrate than Excavator or even EWBF's miner.

Thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
