### ISSUE TITLE
Nichehash Memory Alloc & Socket error

### ISSUE THREAD

**Issue by donaldduck1** [nicehash/NiceHashMiner#1044]
Hey All,

New to mining. I have been using the Nicehash version 2.0.1.11 app for about a week on my computer with an I5 2.9ghz cpu and the OS is Windows & 64 bit PRO and it was running fine but then slowly it was getting the socket error as well as the memory alloc error more and more and now it will not mine anything. I have researched and tried all the fixes out there for instance I did the virtual memory increase to 16gb, also did the lock page file where you add your user and group and that had no effect. I also tried the RAMMAP app with no success. I have even tried to uninstall and reinstall the nicehash app and the didn't work either.

So as of now I have tried all the solutions I can find with no fix at hand. Any one have a TRUE fix for this issue?

RAMMAP fix.
https://docs.microsoft.com/en-us/sysinternals/downloads/rammap

Lock page file fix.
https://github.com/nicehash/NiceHashMiner/issues/652

And this one.
https://www.youtube.com/watch?v=suFMBuLgpFw&t=312s

Thank
DD1

**Comment by S74nk0** [comment]
Issue not related to nhm/nhml client. Issue is related to discontinued nhm2 client.
