### ISSUE TITLE
NH Legacy does no  connect to ETH, X11 (recconect problem)

### ISSUE THREAD

**Issue by mskrapi1980** [nicehash/NiceHashMiner#1045]
Hello. I have problem with NH legacy 1.8.1.9 
I mining with no problem to 0,003BTC and now i have always reconnect to eth mining.
if I mining equihash the problem does not occur
Change to another server nothing change.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client
**OR**
Networking issue on your ISP side or ISP is blocking our services
**OR**
Used miner isn't compatible with NiceHash protocol
**OR**
Your user account is/was temporary banned (write to support@nicehash.com to check)
