### ISSUE TITLE
How to update 3rd party?

### ISSUE THREAD

**Issue by BIG1** [nicehash/NiceHashMiner#1046]
Hi.
How to update the 3rd party miners?

Can I edit the .config file of 3rd party miners and nicehash will be using them? I need to set OC and undervolt settings.

**Comment by bruvv** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/wiki/Setting-Environment-Variables-for-specific-miners

**Comment by BIG1** [comment]
But can we paste stuff from the claymore config there?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Adding new miner plugins.
https://github.com/nicehash/NiceHashMinerLegacy/wiki/Plugins
