### ISSUE TITLE
Unable to get profitability data

### ISSUE THREAD

**Issue by PBJellytime** [nicehash/NiceHashMiner#1049]
I have a looping powershell script for my miner that restarts NHML and various other programs if it detects its not working, however sometimes on restart the popup about "unable to retain profitability data" window appears and prevents NHML from restarting until manual intervention.  

Is there anyway to remove the popup?  Its not a massive issue as the powershell script keeps restarting until it succeeds, just quality of life improvement for automated mining really

The issue appears to be on the nicehash end and usually resolves itself within a few minutes

**Comment by inventorAdam5** [comment]
I'm having the same issue. NHML 1.8.1.9 closing, but then I use a batch file to restart it when it closes, only for that to be defeated by that popup until the program closes itself allowing the cycle to continue again.

**Comment by inventorAdam5** [comment]
Maybe a batch file that checks GPU load or temp. If it drops below a certain amount, restart NHML.exe.

**Comment by PBJellytime** [comment]
That's what mine does, monitors gpu temp thresholds and restarts the miner if it gets three warnings

**Comment by francescocmazza** [comment]
Same here

**Comment by taxiaguilas** [comment]
Yo tengo el mismo problema desde el martes y tengo la versión 1.8.1.9. La única forma que hay para que funcione es usando un VPN. Entonces si mina pero la descarga va muy lenta. Me está minando 5 euros día cuando estaba sacando casi 9 con un rig de 6 gráficas RX 470 8gb. Me pueden ayudar

**Comment by inventorAdam5** [comment]
Found a fix, took a bit of work to get it set up though.
http://jkcrypto.com/automatically-restart-mining-if-stopped/#Part_4_How_to_Automatically_restart_Mining_Rig_in_case_of_FreezeHang
It tests network connection, GPU Temp, and a few other things.
Also, just a heads up, the shortcuts included in the download will need to be changed manualy by right clicking them and going to properties.

The **bold** parts need to be changed to the correct path.

For target: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -f 
**C:\Users\ _____\Desktop\Miner**\MinerMonitor\jkcrypto-minermon.ps1

For path: **C:\Users\ _____\Desktop\Miner**\MinerMonitor

The "script auto restart" shortcut can be deleted and corrected by creating a shortcut to the autorestart.bat file.
Hope this helps.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client
**OR**
Networking issue on your ISP side or ISP is blocking our services
