### ISSUE TITLE
Settings window cropped too small to use at lower resolutions

### ISSUE THREAD

**Issue by malventano** [nicehash/NiceHashMiner#105]
1024x768. See photo.
![nicehash-bug](https://user-images.githubusercontent.com/29584411/28813471-60c82ac2-7667-11e7-99d2-3081cf37293a.png)

**Comment by malventano** [comment]
In addition to this issue, if the NiceHash window is at the top of the screen, the Settings window will be drawn with its title bar above the clickable range of the screen (so the window can not be dragged/moved).

**Comment by DillonN** [comment]
Thanks @malventano, this will be fixed in the next update. For now as a workaround you can use ALT+S to save the settings.

**Comment by JerryC564** [comment]
You are luckier than me, I can't even see the buttons. Please fix it @DillonN 
![20170802141409](https://user-images.githubusercontent.com/28459583/28893007-2799f88a-778d-11e7-90ca-1bf2f35cb7fa.png)

**Comment by DillonN** [comment]
Please see [this comment](https://github.com/nicehash/NiceHashMinerLegacy/issues/72#issuecomment-319896598)
