### ISSUE TITLE
Add PhoenixMiner

### ISSUE THREAD

**Issue by microtechies** [nicehash/NiceHashMiner#1050]
https://bitcointalk.org/index.php?topic=2647654.0
Just a suggestion,
I have tried PhoenixMiner on my rigs & I'm getting a better hash rate and it has a lower dev fee compared to Claymore.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Feature implemented
