### ISSUE TITLE
How to increase threads on AMD Ryzen Threadripper 1950X 16-core Processor.

### ISSUE THREAD

**Issue by fugzibogs** [nicehash/NiceHashMiner#1051]
To anyone that can help me,

As you can see from the two screenshots I took, I am currently mining with one of the CPUs that is recognized. However, when you look at the terminal, only 12 of the 16 threads are utilized. How do I increase the 12 to 16 threads?

![screenshot 1](https://user-images.githubusercontent.com/34175643/36877243-322b5c9e-1d87-11e8-95b6-e0643c2d4980.PNG)
![screenshot 2](https://user-images.githubusercontent.com/34175643/36877246-36c66cbc-1d87-11e8-8df7-002394e22151.PNG)

**Comment by g5-freemen** [comment]
try to change file NHML\internals\MinerOptionPackage_Xmrig.json
      "Type": "Xmrig_threads",
      "ShortName": "-t",
      "LongName": "--threads=",
      "Default": null,
      "FlagType": 1,

change       "Default": null,
to
      "Default": "16",

also u can try to increase CPU usage to max
    {
      "Type": "Xmrig_maxusage",
      "ShortName": "--max-cpu-usage=",
      "LongName": "--max-cpu-usage=",
      "Default": "75",
      "FlagType": 1,
      "Separator": ""

change 75 to 100

also 
in settings you can add text "--threads=16" to XMRIG extra launch (can remember exactly)

**Comment by g5-freemen** [comment]
...but not always increasing number of threads increasing speed. On my Core i7-8700k six cores (12 threads), but best speed on 6 threads. Try different values.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

https://github.com/nicehash/NiceHashMinerLegacy/wiki/Xmr-Stak
