### ISSUE TITLE
NiceHashMinerLegacy

### ISSUE THREAD

**Issue by Boris172** [nicehash/NiceHashMiner#1052]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by Boris172** [comment]
Hello, why is the balance not moving in the miner window? The balance stood for a long time, two days ago, and shows the amount of miner that mines at the moment more than the website, why? On the website the balance is moving, this program is buggy? Mines only this algorithm is already 1130 minutes, as it should be? Is that what it's supposed to be?
 
Здравствуйте, почему баланс не движется в окне майнера?
 
Баланс давно встал, два дня назад и в майнере показывает сумму, которая майница в данный момент больше, чем на сайте, почему?
 
На сайте баланс движется, это программа глючит?
 
Майнит только этот алгоритм уже 1130 минут, так и должно быть?
 
Все так и должно быть?

**Comment by Boris172** [comment]
Hello, why is the balance not moving in the miner window? The balance stood for a long time, two days ago, and shows the amount of miner that mines at the moment more than the website, why? On the website the balance is moving, this program is buggy? Mines only this algorithm is already 1130 minutes, as it should be? Is that what it's supposed to be?

**Comment by Boris172** [comment]
Mines only this algorithm Equihash is already 1130 minutes, as it should be? Is that what it's supposed to be?

**Comment by bruvv** [comment]
https://github.com/nicehash/NiceHashMinerLegacy#-how-to-report-bugs-and-issues

**Comment by shemue575** [comment]
good afternoon I'm doing mining and I see the balance and the amount of dollars but as the amount goes up the next day returns to the initial balance and is lost in the day

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.

Some users were payed out and unpaid balance reset to 0.
