### ISSUE TITLE
Daggerhash showing single GPU hasrate, even though 3x GPU's are active!!???

### ISSUE THREAD

**Issue by GHray** [nicehash/NiceHashMiner#1053]
I've been running NHLM on 2x rigs, each with 3x GTX 970 4GB GPU's for over a year now.
Win7x64 with Nvidia drivers v390.77. NHLM v 1.8.1.8
Systems are watercooled and OC'd (1430Mhz core and 4000Mhz memory) and running those OC settings stable and consistently for over 2 years. Mined in ETH pools before.

When Ethash was still profitable, back in the day, before Equihash came overtook it, I was getting 25MH/s off each card, for a total of 75MH/s per rig = 150MH/s on both rigs.
Then with Ethash difficulty increasing, NHLM started mining Equihash/X11/Scrypt etc instead for most of last year.
ETH  price hike end 2017 then started switching my miners back to mining Daggerhashimoto,  but instead of getting the combined hashrate of all 3 cards it only seems to show the hashrate of a single card of around 22MH/s (Obv difficulty and DAG has slowed things down a bit). Does this on Ethminer and Claymore.

I've rerun Benchmarks in Precise mode many times, and it gives me 22MH/s for each card.

Start mining however, can see all 3 cards active and 100% utilised, yet the rates for GPU#1, GPU#2, GPU#3 together only amounts to 22MH/s, rather than 66.

When I drop the clocks to default, it gives same behaviour, yet only around 9 to 13MH/s, which is obvious. So it's not overclocking that's confusing the miners.

Anybody have any idea what could be wrong?

It's been doing this over the last 3 or 4 versions of NHLM and I've tested with numerous older versions of Nvidia drivers too.

All other algorithms perform as expected, with combined hashrate of all 3 cards.
Equihash = 320 Sols/s per card = 960 Sol/s per rig
Nist = 33 MH/s per card = 99MH/s per rig
X11 = 8 MH/s per card = 24MH/s per rig.

Please help.

Thanks
Ray

**Comment by blue-yu** [comment]
GTX 970 can't mine ether anymore due the DAG size. GTX 970 has 2GB+ memory bug :( You can test it yourself by forcing lower DAG epoch in benchmark...

**Comment by GHray** [comment]
@blue-yu 

Thanks for the reply.
I have the GTX970 4GB versions. I can see that the full DAG (currently 2.36GB) is fully loaded onto each card.
As far as I could research, the only known memory "bug" with GTX970 4GB cards is that only 3.5GB is fast VRAM, and the last 0.5GB is slower. DAG is not near that size yet.....
How do I force lower DAG epoch in benchmarking please??

Thanks

**Comment by blue-yu** [comment]
Yes, I know that 3.5gb it problem, but somehow in mining 2bg is limit :( I You are using clay eth miner try "-benchmark 50" - it is creating dag epoch 50 for benchmark. Try to google a little more about the issue, and maybe You will came across solution with genoil miner and opencl instead of cuda. That didn't work for me, so I gave up in favor of zec mining...

**Comment by GHray** [comment]
Yeah, I've been mining ZEC and other Equihash based coin since ETH, but profits not that great anymore....
WhatToMine indicates Ethash as the top performer recently, so keen to get back onto that.
Just installed Win10 on my 2nd rig as I saw a post on here somewhere of somebody solving the same problem with Win10 drivers. So far getting the same result but need to keep experimenting

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
