### ISSUE TITLE
balance

### ISSUE THREAD

**Issue by LuckyGeniusss** [nicehash/NiceHashMiner#1054]
Why does the program not reflect the balance?
http://prntscr.com/ilvro8

**Comment by bruvv** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/issues/1042
https://github.com/nicehash/NiceHashMinerLegacy/issues/1049

**Comment by nivong** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/issues/1049

**Comment by LuckyGeniusss** [comment]
http://prntscr.com/im9z7j

**Comment by Defektt** [comment]
нашли решение?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.
