### ISSUE TITLE
2.0.1.11 Keeps crashing

### ISSUE THREAD

**Issue by LertuZUES** [nicehash/NiceHashMiner#1055]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by bruvv** [comment]
@DillonN can we have an extra mod who is just able to close all these nonsense issues?

**Comment by Crypto-Lord** [comment]
@HyperBlueCore This github forum is for **NiceHashLegacy Miner** only. Your going to want to take whatever issue is to the appropriate NHM 2.0.** github/reddit forums. You won't find help here.

**Comment by DillonN** [comment]
@HyperBlueCore, this forum is for NHML only. For problems with NHM2 please open a ticket here: https://www.nicehash.com/support
