### ISSUE TITLE
这个是什么原因？

### ISSUE THREAD

**Issue by aid188** [nicehash/NiceHashMiner#1056]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given
![qq 20180303135414](https://user-images.githubusercontent.com/37008682/36931105-638bdcb4-1eea-11e8-9857-2ebf2c32f0e1.jpg)

**Comment by bruvv** [comment]
https://github.com/nicehash/NiceHashMinerLegacy#-how-to-report-bugs-and-issues

**Comment by Crypto-Lord** [comment]
How much RAM do you have? And what's your virtual memory set to?

**Comment by nerdatwork** [comment]
Use English while reporting and this github is ONLY FOR NHML. Try contacting support for nicehash miner

**Comment by S74nk0** [comment]
Issue not related to nhm/nhml client. Issue is related to discontinued nhm2 client.
