### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by LertuZUES** [nicehash/NiceHashMiner#1059]
I keep getting this Cuda error in both versions
https://media.discordapp.net/attachments/410917504001507329/419736996949393420/unknown.png
so it doesnt load the gpu

**Comment by UselessGuru** [comment]
Replace the dll with the original version (usually found in c:\Program Files\NVIDIA Corporation\NVSMI\)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
