### ISSUE TITLE
Miner does not see the Internet.

### ISSUE THREAD

**Issue by muskat007** [nicehash/NiceHashMiner#1061]
Good afternoon. Tell me what's the problem?
1. Program NHML version 1.8.1.9 as seen in the photo with the problem 1 benchmark works and passes the tests. But if you specify several algorithms in the test, the program simply closes and disappears from the field of view. Without notifications and warnings. (Usually, Windows shows that the program does not respond and offers to close or close but notify that the program is hung.
2. Benchmark passed one algorithm (finally), now another problemma is visible on the photo problemma 2. Writes a message that there is no Internet. How not? Benchmark then went? before it was another and another iron, the program also flew, so that problem in windows and iron disappears. I found out from my colleagues in the shop the same thing, but they somehow looked for the problem solution, but this is not an option. Many ways to try, only more expensive time to lose.
3. As you can see in the photo problem 3, there is a connection with the server, since the price of bitcoin is shown.
 4. Miner beta - algorithms are not available for the benchmark.
Why is there no way to safely run equipment into work? tell me when problemma will be solved? Thank you.
PS: version of Miner 2 and above is not possible to pass the benchmark, all algorithms are unavailable.
![1](https://user-images.githubusercontent.com/37041100/36945943-d98b642e-1fbd-11e8-8e53-8dcf10c324dc.PNG)
![2](https://user-images.githubusercontent.com/37041100/36945944-d9af920e-1fbd-11e8-90a3-03740ebfe9f5.PNG)
![3](https://user-images.githubusercontent.com/37041100/36945945-d9cf1d4a-1fbd-11e8-91b0-172e17d7ec68.PNG)
![4](https://user-images.githubusercontent.com/37041100/36945946-d9f1a5f4-1fbd-11e8-8485-08aed3c52f81.PNG)

**Comment by haidertech** [comment]
i have same issue with my all rigs in my farm 
its 200 gpu with same problem and i try to fix it but no way 
now i gust looking >>>>>

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client
**OR**
Networking issue on your ISP side or ISP is blocking our services
