### ISSUE TITLE
1.8.1.9 AMD Adrenalin drivers recognized?

### ISSUE THREAD

**Issue by HardKnox30** [nicehash/NiceHashMiner#1062]
I have had to resort to the older AMD drivers so it will be seen by the miner. Does the latest version of MinerLegacy recognize the current AMD Adrenalin Drivers?

**Comment by Crypto-Lord** [comment]
I'm running Adrenalin 18.2.1 with my vega for a week or 2 now and haven't had any issues with mining.

**Comment by CARLUCES88** [comment]
Yes, he recognizes them perfectly.
undo all old drivers, reboot and then reinstall the last driver

**Comment by GoldenAnt** [comment]
btw Adrenalin released today new software driver updates 18.3.1 that fix my problem

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Driver issue
