### ISSUE TITLE
Helppp

### ISSUE THREAD

**Issue by KittyCatGamersDiscord** [nicehash/NiceHashMiner#1063]
Hello whenever i run the miner it just sits there doing nothing i've done a benchmark etc.

**Comment by CARLUCES88** [comment]
The Benchmarks are fine?

**Comment by KittyCatGamersDiscord** [comment]
I got what its doing now It's not picking up my gpus i have a AMD and Intel Please help

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
