### ISSUE TITLE
Hello. Nhml does not see the Asus rx580 strix. Only the processor sees it. The map is new, with the latest drivers.

### ISSUE THREAD

**Issue by FoBos105** [nicehash/NiceHashMiner#1064]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given
![read](https://user-images.githubusercontent.com/37082596/36991747-de89fc86-20d2-11e8-9975-2aff0cddc7f4.png)
![read](https://user-images.githubusercontent.com/37082596/36991811-16193a54-20d3-11e8-8ee4-5f469a20527b.png)

**Comment by CARLUCES88** [comment]
Surely the hardware installation is not correct

**Comment by FoBos105** [comment]
What should I do?

**Comment by francescocmazza** [comment]
Missing OpenCL driver, I guess. Please check if your card has opencl enabled.

**Comment by Joshwaa2010** [comment]
Use DDU to clean all the old AMD drivers out then reinstall new drivers. This generally is a good idea when putting a new gpu in an already running system.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
