### ISSUE TITLE
RESTARTING FALLED: ERROR 87

### ISSUE THREAD

**Issue by CARLUCES88** [nicehash/NiceHashMiner#1065]
I am currently mining with three AMD RX 580 8GB video cards
Using nicehash miner legacy 1.8.1.9
My Rig stays stuck / hung presenting this error whenever it is being mined
I need your help to be able to determine the cause of this error

![thumbnail_img-8950](https://user-images.githubusercontent.com/37084508/36995367-3a316d56-208a-11e8-9aba-0b4b7640d2ed.jpg)

**Comment by GoldenAnt** [comment]
I have 2 AMD RX 580 8GB video cards and have same issue

**Comment by CARLUCES88** [comment]
You have installed afterburner?

**Comment by GoldenAnt** [comment]
yes i'm using afterburner to regulate fan speeds, somehow i was not able from adrenaline.
and i had two RX 580 from gigabyte so bought one more from msi and win 10 start crashing when run test.
Using nicehash miner legacy 1.8.1.9 so I updated adrenaline with new drivers 18.3.1 version just released and that fixed win crash

**Comment by francescocmazza** [comment]
Looks like HW faliure, imho.

**Comment by CARLUCES88** [comment]
What?

**Comment by Crypto-Lord** [comment]
Getting the same error constantly with my vega 64. Multiple mining windows open and had to restart multiple times as the original mining window wouldn't close & prevented any mining on the Vega. Happens   while running any claymore_dual

**Comment by immune2ice** [comment]
I am having the same issue.  Multiple miners bring opened, some miners going to 0 hash rate, etc.

Any fixes?

**Comment by n2dzone** [comment]
having same problem, on for about 90 seconds and then off for 30 seconds anybody have any suggestions.

**Comment by Tenukitime** [comment]
Same issue here.  MSI RX580 Armor MKII.

**Comment by hyas1312** [comment]
ok thats bad xd


2018-05-26 7:43 GMT+02:00 Tenukitime <notifications@github.com>:

**Comment by n2dzone** [comment]
problem went away when I put a monitor on the system and quit using team viewer

now been running for full day with no stops anybody else been using team viewer?

**Comment by chrisfarley11** [comment]
It is team viewer.  Team viewer uses a lot of resources and if your motherboard is at max and you login from somewhere else it will hang one of your miners which will crap the whole thing out.  My suggestion, Ultra VLC I think is what it is called.  This is an alternate way to remote in.  Additionally if you are quick you can avoid it, if you login with team viewer immediately stop mining and then just before you log off start it again.  If you hit the start button and immediately close out of team viewer it doesn't seem to have an issue but if you continue to mine and watch through team viewer it will freeze up.

**Comment by chrisfarley11** [comment]
Additionally team viewer requires you have a monitor hooked in, if not you just see black from the remote.  So keep a monitor plugged in if you are going to use team viewer.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
