### ISSUE TITLE
Not starting hang on Skip AMD message..

### ISSUE THREAD

**Issue by michalss** [nicehash/NiceHashMiner#1067]
Once i start the Legacy this is all i can see, simply stuck on skip amd crap message and thats it, then i have to kill it from taks manager. I have 12GPU in it BTW.. 

[image](https://user-images.githubusercontent.com/1000729/37047070-365c8f0e-216a-11e8-98bc-c13dfbc56981.png)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
