### ISSUE TITLE
nicehash opencl fail after windows 10 update assistant alive

### ISSUE THREAD

**Issue by hooiyam81** [nicehash/NiceHashMiner#1069]
im runing of win10 for 6 gpu mining. once win10 update assistant start auto updated will just fine on 5 gpu and 1 gpu will lost function. 
already done disable update assistant but nicehash still cant run fine with 6 gpu. either 1 of 6gpu will lost connect and restart program 
any solution ???

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
