### ISSUE TITLE
6th card half speed?

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner#107]
Hello,

On my rig i have 6 cards, 2 x 480s and 4 x 470s
Windows 10, 8 gig ram, 60gb SSD.
miner v1.8.0.2

For some reason my 6th card mines at half the speed... Any ideas? Benchmark was standard and all the speed are the same

**Comment by DillonN** [comment]
Does it run at half speed for every algorithm or is it only one?

**Comment by undefy** [comment]
for every algorithm. 
UPDATE: I did a precise bench mark over night for all gpus and the 6th gpu (470) turned up all the algorithms @ 1/2 speed. HOWEVER when i started mining i disabled dagger/sia combo and worked fine for while i.e. full speeds on all cards.

**Comment by DillonN** [comment]
Could you post your log file for when you run with the daggersia enabled? Also when you run do you see any other mining windows open other than what NHML says it is using?
