### ISSUE TITLE
SMA no internet connetion 

### ISSUE THREAD

**Issue by haidertech** [nicehash/NiceHashMiner#1071]
both of nicehash software have problems with network >>and iam connected to the internet 
![untitled](https://user-images.githubusercontent.com/37213727/37207202-c938eb32-2350-11e8-90f9-de905aa4cd7b.png)

**Comment by haidertech** [comment]
please help me

**Comment by nerdatwork** [comment]
Try using 1.8.1.9 instead of 1.8.2.0 pre 2

**Comment by taxiaguilas** [comment]
Yo tengo el mismo problema desde el martes y tengo la versión 1.8.1.9. La única forma que hay para que funcione es usando un VPN. Entonces si mina pero la descarga va muy lenta. Me está minando 5 euros día cuando estaba sacando casi 9 con un rig de 6 gráficas RX 470 8gb. Me pueden ayudar por favor
![img-20180309-wa0010](https://user-images.githubusercontent.com/37253473/37247442-4d68b7be-24bb-11e8-98e6-e203ad732bba.jpeg)
![20180310_045402](https://user-images.githubusercontent.com/37253473/37247443-4d934cf4-24bb-11e8-868c-b1e7fd9466ec.jpg)
![20180310_190414](https://user-images.githubusercontent.com/37253473/37247444-4db72606-24bb-11e8-9167-d7b07042cec4.jpg)
![20180310_004119](https://user-images.githubusercontent.com/37253473/37247445-4dd82734-24bb-11e8-84b8-081efaa60943.jpg)
![Uploading IMG-20180310-WA0010.jpg…]()
![Uploading 20180310_001509.jpg…]()
![Uploading 20180310_190444.jpg…]()
![Uploading 20180310_190430.jpg…]()
![Uploading IMG-20180310-WA0008.jpeg…]()
![Uploading 20180310_004107.jpg…]()
![Uploading IMG-20180310-WA0006.jpeg…]()
![Uploading 20180310_001617.jpg…]()

**Comment by taxiaguilas** [comment]
Yo tengo el mismo problema desde el martes y tengo la versión 1.8.1.9. La única forma que hay para que funcione es usando un VPN. Entonces si mina pero la descarga va muy lenta. Me está minando 5 euros día cuando estaba sacando casi 9 con un rig de 6 gráficas RX 470 8gb. Me pueden ayudar por favor

**Comment by taxiaguilas** [comment]
I have the same problem since Tuesday and I have version 1.8.1.9. The only way there is for it to work is by using a VPN. So if mine but the download is very slow. It is mining 5 euros a day when I was taking almost 9 with a rig of 6 RX 470 8gb graphics. Can you help me, please

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client
**OR**
Networking issue on your ISP side or ISP is blocking our services
