### ISSUE TITLE
difference between profits miner and site !

### ISSUE THREAD

**Issue by redav1** [nicehash/NiceHashMiner#1072]
Hello
Sorry for the language I am french ^^

Here I contact you because there is a big difference between your profit site and my nicehash miner legacy 1.8.1.9

For a GTX 1070 card I would say that all is well these coherant

But for two GTX 1070 if made custom setting and in DEVICE (2) - POWER (400) - EQUIHASH (1000 / s)
I should hit (5.39 €) off the touchdown (2.62 €)

I mine well with the 2 cards
Can you tell me why?

Here are some photos at the time I write this message
![20180309_003334_003](https://user-images.githubusercontent.com/37217520/37212060-438007c4-23ae-11e8-94cf-a3f310f84d37.jpg)
![20180309_003425](https://user-images.githubusercontent.com/37217520/37212061-43a0f272-23ae-11e8-93c5-b3ea1ed47a16.jpg)
![20180309_003433](https://user-images.githubusercontent.com/37217520/37212062-43b9f592-23ae-11e8-96ce-1c5c4e9cca1d.jpg)

Looking forward to your reply cordially

**Comment by xiaoyaoyang** [comment]
The 1000sol/s is your two card total. You are supposed to input hashrate for a single card there. So try to put 500sol/s on the website, and keep everything else the same

**Comment by redav1** [comment]
Ok but the thing that does not stick these my friend has a GTX 1080 8go with a hashrate of 550sol / s and it touches 3.60 € JUST with a card and I touch 2.20 € with a hashrate of 1000sol / s with both card

Earlier I had the € 3.00 for a card and € 6.00 with both these remained 5min and then down to 2.20 € immediately!

So there is a problem, it would take 2 years just to pay back the graphics card

It could come from my configuration? (i5 3570k; 2 GTX 1070; HDD 320go; 8GB ram; 600W corsair)

Thank's for your answer. Best regards

**Comment by xiaoyaoyang** [comment]
The profit changes is normal, because the profit depend on the market. As long as your hashrate remains stable, you are fine.
With your set up, I am expecting 0.0003 BTC/day, which is exactly what you are seeing right now. Another thing is you should focus on BTC/day not EUR/day..

Conclusion: You are all good. Mining profit sucks.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Issue related to market/price fluctuation
