### ISSUE TITLE
excavator ?

### ISSUE THREAD

**Issue by besta04** [nicehash/NiceHashMiner#1073]
i think using excavator for nvidia for lyra, neoscript, and nist5 is way faster hashrate. Maybe you can add excavator miner to legacy?

**Comment by nerdatwork** [comment]
excavator is there in NHM so doubt if legacy will include that.

**Comment by g5-freemen** [comment]
NHML just contains old excavator version, why not update it?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

excavator is currently on hold. We didn't include excavator in nhml due to AV flagging our software.
