### ISSUE TITLE
Wrong miner cryptonight NHML-1.8.1.7-1.8.1.8-1.8.1.9-1.8.1.10

### ISSUE THREAD

**Issue by ISPITATEL** [nicehash/NiceHashMiner#1075]
![](https://user-images.githubusercontent.com/36195415/35861135-4dec15bc-0b4f-11e8-882f-7e88f07bf966.jpg)
**# the wrong miner is loaded**
ccminer 8.18 Klaust do not dig the cryptonight algorithm...
for cryptonight at Klaust exists ccminer-cryptonight 3.0 latest

great work guys...

**Comment by DillonN** [comment]
Sorry, the ccminer_cryptonight for old cards was inadvertently replaced with klaust. Fixed now with new bins, you can download it [here](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.8.1.7/bin_1_8_1_7.zip) or delete the bin folder and NHML will automatically download it
