### ISSUE TITLE
Request enable/disable all devices

### ISSUE THREAD

**Issue by AtlAntA118** [nicehash/NiceHashMiner#1076]
Right click an algo. "Enable/Disable for all devices" option.

Thank you

**Comment by Meatball13** [comment]
Would like this as well.  For those of us with multi GPU rigs it's very time consuming to go in anytime you want to update the algo's mined or benchmarked, and click through every single GPU and then select/deselect algo's for mining/benchmarking.

Please implement something where you can select or deselect an algo/miner for mining and benchmarking on one screen and have it applied to all GPU's in the system.
