### ISSUE TITLE
socket was closed by pool

### ISSUE THREAD

**Issue by housammi** [nicehash/NiceHashMiner#1077]
Dear sir / 
i cant mining by this message : 
**socket was closed by pool**

is spit of i reinstall every thing form first 
and now i mine miningpoolhub.com
i close the firewall and aniverus

without any problem

**Comment by mySebbe** [comment]
i hade the same problems on EU Server, switched to US was resolving this issue. I think there is something wrong with the EU Servers.

**Comment by housammi** [comment]
thank u for your reply 
but i chose every server  ,  every one but  i field

**Comment by tusharantal** [comment]
I am facing the same problem any solutions ?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client
**OR**
Networking issue on your ISP side or ISP is blocking our services
**OR**
Your user account is/was temporary banned (write to support@nicehash.com to check)
**OR**
Used miner isn't compatible with NiceHash protocol
