### ISSUE TITLE
Profit discrepancy

### ISSUE THREAD

**Issue by TDPort** [nicehash/NiceHashMiner#1078]
Hello,
I am having a profit discrepancy issue.
It's been sketchy since the market crash and some virus issues, but the latest is I upgrade to NHML v1.8.1.10 and my hashrate in the miners is under what it was on one GPU by 10-30 sols/s. The second gpu on that card is about the same.(aprox 540 sols/s down to 510-30sols/s)
But on the site it keeps fluctuating to very low numbers. My daily with them was $2.70-3.29 a week ago for a month.
Now my daily is fluctuating between $1.05 and 2.26. The site does not show the same hashrates as my miners do.
My cpu crypto is also down from .35-.40 daily to .16-.21 which seems a lot of loss for just market conditions.
Any help would be much appreciated. Thank you!
#

**Comment by khaotekmetalcraft** [comment]
It's called rape, brother.  Welcome to the club.  How does it feel?

**Comment by TDPort** [comment]
I've spent most of my life stopping rapists. But nowadays they are getting so good they get away with it, then accuse victims and witnesses of it and get believed by retards. But yeah, this is ridiculous. They won't answer legit questions about it either. Won't even say what the math behind the vanished profits are or point in a direction for resolving any issues messing it up.

**Comment by TDPort** [comment]
I've spent most of my life stopping rapists. But these days they are so good at it they get away with it then accuse innocent people and victims and witnesses of things not remotely true to cover it up. They won't even answer legit questions to what's wrong, the math behind it, or how to fix any potential theft issues or virus etc. My profits are gone to the point of ridiculous. Any people out there with experience or skills that might help, I would appreciate it!

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

All miners software closed or open source is marked flagged by AV software. Malware authors frequently bundle miner software. Use it at your own risk.

Issue related to market/price fluctuation
