### ISSUE TITLE
GPU 1080ti not detected

### ISSUE THREAD

**Issue by koalana** [nicehash/NiceHashMiner#108]
Yesterday my miner stopped detecting my GPU

**Comment by adem4ik** [comment]
Can you provide some more information? Like what was changed before miner stopped to work? May be you have updated drivers or installed newest version of NHML?

**Comment by Sifontes** [comment]
![screenshot_20170805-015455](https://user-images.githubusercontent.com/21142027/28993326-a1666162-7981-11e7-8134-256b49064fb1.png)
Same issue here, especially when mining equihash on EWPF miner. Have to restart pc in order to get detected.
