### ISSUE TITLE
When will 1.8.2 come out?

### ISSUE THREAD

**Issue by peteraclausen** [nicehash/NiceHashMiner#1080]
I keep waiting for the production release of 1.8.2 to come out.  You know, the version with multi-threaded bench-marking and re-sizable benchmark window.

I was hoping that 1.8.1.9 would have been followed by 1.8.2.0, but instead 1.8.1.10 came out.

Is development of 1.8.2.x dead?  My rigs have a lot of GPU's and not having multi-threaded bench-marking is a show stopper for me.

**Comment by thel3lue** [comment]
@DillonN 1.8.2.x dead?

**Comment by peteraclausen** [comment]
@DillonN

Please, can we get an update on 1.8.2 development.  Multithreaded benchmarking is a must on large rigs as it otherwise take forever to do a proper Precise benchmark.  At the very least, incorporate this feature into the 1.8.1.x branch.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
