### ISSUE TITLE
Profitability Algorthim Issue

### ISSUE THREAD

**Issue by khaotekmetalcraft** [nicehash/NiceHashMiner#1081]
For latest release:

I have two identical cards in my main desktop, 2x EVGA 980 SC2.  I mine Nicehash for fun on idle to blow some pennies on shit coin.  I am noticing the issue is also cropping up on my rigs running identical cards, 1080's, 70's, 60's, Ti's the like...

EXAMPLE SCENARIO:

The switcher is assigning { card.0 } to Equihash and paying (shit) ~1.15/day and assigning the second { card.1 } which has identical performance characteristics, +/- thermal characteristics of the case, to DaggerHashimoto, which is paying (bigger load of shit) ~0.22c/day.

What gives?  I don't, just like everyone else that uses this service, G.A.F. what load your servers have, people want to mine the most profitable coin, period.  Why is it forcing my cards to mine algorithms 100% of the time that are in upwards of 10x less profitable than the most profitable coin currently?

This isn't a "flummox", it's straight bullshit.

Also, your CPU affinity defaults for XMRIG / xmr-stak are either broke A.F., miss configured or just nonexistent.  People are losing out on a lot of hashing power by not assigning to core.  I manually have to set XMRIG and XMRStak's affinity to gain in upwards of 100+ hashes a second.  I never used to have to with older versions of Legacy.

Don't even get me started on your non-legacy version of the software, that's just junk.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
