### ISSUE TITLE
NH Legacy is "mining" but profitability shows as 0

### ISSUE THREAD

**Issue by geekymojo** [nicehash/NiceHashMiner#1083]
I'm having this problem with 4 other servers. It is very weird, as you can see in the first image, NiceHash is mining on the computers. But when I go to check my miners in the NH monitor, profitability shows 0 even though miners are showing up on the monitor. All firewall/antivirus are shut off, opened all related ports and nothing is being blocked, and I've only managed to get it partially working when using a VPN (as soon as the VPN saturates, it will stop working). Do you have any other insight as to what it could be?
![untitled2](https://user-images.githubusercontent.com/37371129/37411278-d6e382de-2778-11e8-938b-82b4f724905c.png)

![untitled](https://user-images.githubusercontent.com/37371129/37411253-c5d2bc6c-2778-11e8-92fa-fef1fa7e52cb.png)

**Comment by g5-freemen** [comment]
it's OK, just look for CryptoNight algo unpaid balance changes or not

more interesting is a low hash speed (VERY LOW)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
