### ISSUE TITLE
NHM Legacy 1.8.1.10 showing inaccurate BTC/day for Claymore Dual

### ISSUE THREAD

**Issue by jaymoeco** [nicehash/NiceHashMiner#1084]
NHM Legacy 1.8.1.10 showing inaccurate BTC/day for Claymore Dual mining.  BTC/day in the benchmark and settings tab are showing 10x the profit they should be in some of the Dual mining settings.  Mainly seems to be Dagger/Sia, Dagger/Decred and Dagger/pascal.  As a result, it is getting locked on one of those three algorithms even though others may be more profitable.  Getting way better (and more stable) results with 1.8.2.0-pre2.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
