### ISSUE TITLE
DaggerDecred speed discrepancy between v1.8.1.8 and v1.8.1.10 on R9 Fury

### ISSUE THREAD

**Issue by virtakar** [nicehash/NiceHashMiner#1085]
I just downloaded v1.8.1.10 and started benchmarking my GPU. This moment the only algorithm used is DaggerDecred using Claymore v10.6, and when benchmarking there is a somewhat important difference between the hashing speed of v1.8.1.8 and v1.8.1.10, while the Claymore version is the same.

Screenshot attached, v1.8.1.8 on the left and v1.8.1.10 on the right. Log files attached as well.

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1814484/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1814485/log.1.txt)
![capture](https://user-images.githubusercontent.com/17980657/37451454-d3253840-2831-11e8-9fdb-c247b1b1c08a.PNG)

**Comment by S74nk0** [comment]
This is an issue with all benchmarks that are done via mining. They depend on the job/order and will be different. 

Will close this issue please refer to related issue https://github.com/nicehash/NiceHashMinerLegacy/issues/1524

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
