### ISSUE TITLE
stratum_recv_line failed

### ISSUE THREAD

**Issue by bitcoinvsalts** [nicehash/NiceHashMiner#1086]
I use:

` ./cpuminer -a cryptonight -o stratum+tcp://cryptonight.usa.nicehash.com:3355 -u 35p2upCSNYur1UFoCZMZCwxFHjP89xfKtu -p x`

I am getting this error today:

`stratum_recv_line failed`

but everything was working fine yesterday. Any idea why?

**Comment by fortking** [comment]
It is usually on the pool side of things. Try using xmrig.

**Comment by bitcoinvsalts** [comment]
I did not know I could use xmrig to mine on nicehash. Can I really?

**Comment by fortking** [comment]
Yes, it is built into nicehashminerlegacy.

**Comment by fortking** [comment]
Or you can download it manually and edit “config.json” in notepad and change threads, url, etc

**Comment by fortking** [comment]
If you download xmrig, put this into config.json. I added your wallet and url

{
    "algo": "cryptonight",  // cryptonight (default) or cryptonight-lite
    "av": 0,                // algorithm variation, 0 auto select
    "background": false,    // true to run the miner in the background
    "colors": true,         // false to disable colored output    
    "cpu-affinity": null,   // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
    "cpu-priority": null,   // set process priority (0 idle, 2 normal to 5 highest)
    "donate-level": 1,      // donate level, mininum 1%
    "log-file": null,       // log all output to a file, example: "c:/some/path/xmrig.log"
    "max-cpu-usage": 100,    // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.  
    "print-time": 60,       // print hashrate report every N seconds
    "retries": 5,           // number of times to retry before switch to backup server
    "retry-pause": 5,       // time to pause between retries
    "safe": false,          // true to safe adjust threads and av settings for current CPU
    "syslog": false,        // use system log for output messages
    "threads": null,        // number of miner threads
    "pools": [
        {
            "url": “cryptonight.usa.nicehash.com:3355", // URL of mining server
            "user": "35p2upCSNYur1UFoCZMZCwxFHjP89xfKtu",                        // username for mining server
            "pass": "x",                       // password for mining server
            "keepalive": true,                 // send keepalived for prevent timeout (need pool support)
            "nicehash": true                  // enable nicehash/xmrig-proxy support
        }
    ],
    "api": {
        "port": 0,                             // port for the miner API https://github.com/xmrig/xmrig/wiki/API
        "access-token": null,                  // access token for API
        "worker-id": null                      // custom worker-id for API
    }
}

**Comment by bitcoinvsalts** [comment]
thanks @fortking
