### ISSUE TITLE
Здравствуйте у меня отображается нулевой баланс

### ISSUE THREAD

**Issue by Iufius** [nicehash/NiceHashMiner#1087]
вот я сделал полный скриншот подскажите что мне делать
![default](https://user-images.githubusercontent.com/29072940/37552511-810956a6-29bf-11e8-8bb5-01b3aefa71a2.jpg)
Здравствуйте у меня почему-то отображается нулевой баланс хотя раньше показывал баланс нормально

у меня стоит виндовс 10 64 бит и установлены все обновления и защитник виндовс у меня отключен и на сайте NiceHash тоже баланс не меняется

**Comment by g5-freemen** [comment]
Процессор слишком слабый скорее всего + попробуйте в настройках (последняя вкладка) выбрать ТОЛЬКО xmrig для процессора
или покажите полный скриншот где видно что майнер работает (при нажатии Старт запускается чёрное окошко xmr-stak или xmrig для процессора)

**Comment by Defektt** [comment]
тоже самое только с 2 видеокартами, до этого майнили отлично!) Не знаю что делать, не нашли решение проблемы?

**Comment by Iufius** [comment]
нет
