### ISSUE TITLE
NHLM doesn't seem to support some extra launch parameters

### ISSUE THREAD

**Issue by Mystere** [nicehash/NiceHashMiner#109]
[02:34:49] [ExtraLaunchParametersParser] Cannot parse "auto", not supported, set to ignore, or wrong extra launch parameter settings
[02:34:49] [ExtraLaunchParametersParser] ExtraLaunch params "--cuda-schedule=auto" for device UUID GPU-38f31aff-8e95-341d-a6dc-9b909aa21bc9

Is this a general --parameter issue?  Or is it because it's a non-numeric value?

**Comment by DillonN** [comment]
Hello @Mystere, which miner are you trying to use the parameter with?

**Comment by Mystere** [comment]
All of the ccminer algorithms.  I checked, their help commands, and they all support the parameter, but NHML seems to not understand it, and drops it.  I've tried both with and without the =

**Comment by DillonN** [comment]
NHML only passes handpicked parameters, to prevent passing parameters that interfere with NHML interacting with the miner. 

Currently for generic ccminer the only parameter available is `-i` or intensity, but if you need this parameter I could look into adding it in the future?

You can see current supported parameters in [ExtraLaunchParameters.cs](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/Miners/Parsing/ExtraLaunchParameters.cs)

**Comment by Mystere** [comment]
Well, it's not NEEDED per se.. it just helps with startup time.  Without it, lots of algorithms take a while to get all gpu's working.  Sometimes, in the cases of short runs, you don't even get all the gpu's firing before it switches to another algo.

Not a big deal though, just an annoyance.

I should note, however, that the error message is a bit misleading.  It implies that the parameter value is unsupported, not that the parameter itself is.

**Comment by DillonN** [comment]
As to the error message, NHML parses the params by first splitting parameters and their values, and then looking for a supported parameter. Once it finds this parameter and if it's supported (e.g. `-i`), it will mark the next block as a value for that parameter (if said param takes a value). The reason it is showing "auto" as unsupported, is because the previous check was an unsupported param so it is still looking for supported params not values (and `auto` is not a supported param)

**Comment by Mystere** [comment]
@DillonN  - This issue is starting to become more important.  Particularly with the Nist5 miner.  For some reason, it can take a LONG time for this miner to spin up all the GPU's.  You can identify this because it doesn't show the text regarding setting the intensity for all GPU's.  Eventually, it sorts itself out (usually, I've seen it fail to) but it can take several minutes before all cores are running.

Specifying --cuda-schedule=auto fixes the problem.  I tried adding a MinerOptionPackage json file parameter, but it doesn't seem to be recognized.  

This really shouldn't be that difficult to add, can you please add this to the next release?

**Comment by DillonN** [comment]
Added in commit 5ecf53d
