### ISSUE TITLE
NiceHashMinerLegacy NHML-1.8.1.10

### ISSUE THREAD

**Issue by Iufius** [nicehash/NiceHashMiner#1091]
Здравствуйте у меня стоит виндовс 10 64 бит и установлены все обновления и защитник виндовс у меня отключен и при запуске майнера NiceHashMinerLegacy NHML-1.8.1.10  у меня появляется вот такое окно скришот я прикреплю 
![default](https://user-images.githubusercontent.com/29072940/37645358-49da745e-2c2f-11e8-81f2-1d4f07f8a268.jpg)
 подскажите это нормально или нет

**Comment by xroot88** [comment]
Попробуйте другой сервер (не Гонконг)

**Comment by Iufius** [comment]
не всё равно тоже самое

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Please write in English next time
