### ISSUE TITLE
If profitability server is unavailable at system startup and autostart mining is selected, even if internet connection is established, miner never starts.

### ISSUE THREAD

**Issue by oherman** [nicehash/NiceHashMiner#1092]
I have a mining rig that's programmed to bounce back after a power outage. It doesn't when I reboot or power interruptions happen at 1/12ths of the time.

Sometimes I let the system reboot for maintenance, and leave it open for it to initialize, then hours later, I realized it didn't start mining and only an error dialog approximately saying 'profitability server could not be reached, try again later.' (i forgot what it exactly says though)

Is there something that can be done to make it so it rechecks for a certain interval when autostart mining is enabled?

**Comment by nerdatwork** [comment]
Yes its very annoying when you think your pc should be mining and then BAM that annoying pop up.

**Comment by nickollasaranha** [comment]
Would like to know if anyone got this issue fixed.

**Comment by chianghiong** [comment]
If you are using Nicehash Legacy.
Try the following step:
 1) Turn off the Auto Start Mining, Run with Windows in the Setting.And close the Nicehash Legacy.
 2) Restart the rig and then turn back on the Auto Start Mining, Run with Windows in the Setting. And start mining for 1 to 2 min. Close the Nicehash Legacy, and restart the rig.

Then it should be okay.......

**Comment by nickollasaranha** [comment]
@chianghiong I'm not trying to fix the profitability error, I just want the miner to auto retry after n amount of time, like an option "Retry for profitability server after 30 seconds" or something.
