### ISSUE TITLE
Build project error with VS2015

### ISSUE THREAD

**Issue by Whisperd130** [nicehash/NiceHashMiner#1093]
When I using visual studio 2015 to build this code.
There are lots of errors in project NiceHashMinerLegacy.
`1>------ Skipped Build: Project: MessageBoxManager, Configuration: Debug Any CPU ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: NiceHashMinerLegacy, Configuration: Debug Any CPU ------
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(38,42,38,51): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\ExchangeRateAPI.cs(52,75,52,90): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Algorithm.cs(74,64,74,70): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\MiningSession.cs(568,86,568,92): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(38,51,38,52): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Algorithm.cs(77,89,77,104): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(38,51,38,52): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Algorithm.cs(92,86,92,92): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Algorithm.cs(96,107,96,122): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(64,17,64,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(64,17,64,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(65,16,65,16): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(78,10,78,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(148,41,148,45): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(148,45,148,46): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(148,45,148,46): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(180,50,180,54): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(180,111,180,112): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(180,111,180,112): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(271,46,271,55): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(271,55,271,56): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(271,55,271,56): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(291,46,291,55): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(291,55,291,56): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(291,55,291,56): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(310,42,310,51): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(310,83,310,84): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmsListView.cs(310,83,310,84): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(75,38,75,47): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(75,47,75,48): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Miners\Equihash\Dtsm.cs(93,54,93,59): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(75,47,75,48): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Miners\Prospector.cs(222,57,222,66): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(96,14,96,14): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(115,42,115,51): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(115,51,115,52): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(115,51,115,52): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(133,75,133,80): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(142,84,142,98): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs(163,51,163,54): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(11,17,11,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(11,17,11,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(12,16,12,16): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(16,10,16,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(23,17,23,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(23,17,23,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(24,16,24,16): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(35,10,35,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs(95,49,95,54): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(23,46,23,50): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(23,50,23,51): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(23,50,23,51): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(42,17,42,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(42,17,42,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(43,16,43,16): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(56,10,56,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(62,17,62,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(62,17,62,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(63,16,63,16): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(76,10,76,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(83,17,83,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(83,17,83,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(84,16,84,16): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(88,10,88,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(163,45,163,52): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(163,52,163,53): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(163,52,163,53): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(171,44,171,47): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(171,47,171,48): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(171,47,171,48): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(193,78,193,85): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(193,85,193,86): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(193,85,193,86): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(227,45,227,49): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(227,72,227,76): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(227,76,227,77): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(227,76,227,77): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(230,70,230,77): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(230,77,230,78): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs(230,77,230,78): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\Field.cs(10,17,10,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\Field.cs(10,17,10,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\Field.cs(11,16,11,16): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\Field.cs(18,10,18,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\Field.cs(22,17,22,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\Field.cs(22,17,22,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\Field.cs(23,16,23,16): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Components\Field.cs(30,10,30,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(201,42,201,49): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(201,93,201,94): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(201,93,201,94): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(530,85,530,89): error CS1003: Syntax error, ':' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(530,90,530,91): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(531,107,531,108): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(531,107,531,108): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(533,77,533,81): error CS1003: Syntax error, ':' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(533,82,533,83): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(533,96,533,97): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(533,96,533,97): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(535,79,535,83): error CS1003: Syntax error, ':' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(535,93,535,94): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Benchmark.cs(535,94,535,101): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Settings.cs(23,17,23,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Settings.cs(23,17,23,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Settings.cs(23,30,23,30): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Settings.cs(24,25,24,27): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Settings.cs(24,25,24,27): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\Form_Settings.cs(25,10,25,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Globals.cs(33,61,33,64): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\Grouping\MiningDevice.cs(162,54,162,60): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\Grouping\MiningDevice.cs(166,67,166,76): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\Parsing\ExtraLaunchParametersParser.cs(542,61,542,70): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\ethminer\MinerEtherum.cs(139,51,139,59): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\Grouping\MinerPaths.cs(275,53,275,57): error CS1003: Syntax error, ':' expected
2>E:\[NHML]\\NiceHashMiner\Miners\Grouping\MinerPaths.cs(275,72,275,74): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Miners\Grouping\MinerPaths.cs(275,72,275,74): error CS1525: Invalid expression term '=='
2>E:\[NHML]\\NiceHashMiner\Miners\Grouping\MinerPaths.cs(275,100,275,101): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Miners\Grouping\MinerPaths.cs(275,100,275,101): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Miners\MiningSession.cs(571,85,571,94): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\Ccminer.cs(102,100,102,103): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Switching\NHSmaData.cs(175,41,175,44): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\Sgminer.cs(202,57,202,63): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Utils\Helpers.cs(25,61,25,67): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Forms\TextBoxKeyPressEvents.cs(10,35,10,42): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\TextBoxKeyPressEvents.cs(11,46,11,47): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\TextBoxKeyPressEvents.cs(11,46,11,47): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Forms\TextBoxKeyPressEvents.cs(25,35,25,42): error CS1026: ) expected
2>E:\[NHML]\\NiceHashMiner\Forms\TextBoxKeyPressEvents.cs(25,42,25,43): error CS1002: ; expected
2>E:\[NHML]\\NiceHashMiner\Forms\TextBoxKeyPressEvents.cs(25,42,25,43): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Utils\Helpers.cs(263,47,263,53): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Utils\Helpers.cs(268,48,268,54): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Utils\CommandLineParser.cs(14,59,14,68): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Utils\CommandLineParser.cs(22,53,22,56): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\Miner.cs(559,76,559,77): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(39,17,39,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(39,17,39,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(41,10,41,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(45,17,45,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(45,17,45,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(47,10,47,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(51,17,51,19): error CS1043: { or ; expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(51,17,51,19): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs(53,10,53,10): error CS1513: } expected
2>E:\[NHML]\\NiceHashMiner\Stats\NiceHashStats.cs(173,101,173,104): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Miners\XmrStak\XmrStakAMD.cs(129,52,129,57): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\\NiceHashMiner\Devices\ComputeDeviceManager.cs(404,87,404,93): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\NiceHashMiner\Miners\Xmrig.cs(82,56,82,69): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\NiceHashMiner\Miners\Xmrig.cs(87,61,87,72): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\NiceHashMiner\Switching\AlgorithmSwitchingManager.cs(127,58,127,64): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\NiceHashMiner\Devices\ComputeDeviceManager.cs(566,92,566,93): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\NiceHashMiner\Devices\ComputeDeviceManager.cs(575,97,575,99): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\NiceHashMiner\Devices\ComputeDeviceManager.cs(639,81,639,87): error CS1003: Syntax error, ',' expected
2>E:\[NHML]\NiceHashMiner\Devices\ComputeDeviceManager.cs(1078,80,1078,91): error CS1003: Syntax error, ',' expected
========== Build: 0 succeeded, 1 failed, 5 up-to-date, 1 skipped ==========
`

`            switch (_algorithmOption)
            {
                case AlgorithmBenchmarkSettingsType.SelectedUnbenchmarkedAlgorithms  **when !isBenchmarked && algorithm.Enabled**:
                    return true;
                case AlgorithmBenchmarkSettingsType.UnbenchmarkedAlgorithms **when !isBenchmarked:**
                    return true;
                case AlgorithmBenchmarkSettingsType.ReBecnhSelectedAlgorithms **when algorithm.Enabled:**
                    return true;
                case AlgorithmBenchmarkSettingsType.AllAlgorithms:
                    return true;
            }`
The code above with the error "A local or parameter named 'algorithm' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter".

`        public bool IsMining
        {
            get => _isMining;
            set
            {
                if (value)
                {
                    _isMining = true;
                    listViewDevices.CheckBoxes = false;
                }
                else
                {
                    _isMining = false;
                    listViewDevices.CheckBoxes = true;
                }
            }
        }`
The code above with the error "Only assignment, call, increment, decrement, and new object expressions can be used as a statement".

What happened here?
Should I change it to VS2013?
Or what I need to set up?

**Comment by Whisperd130** [comment]
Are these C# code needed C#7??

**Comment by g5-freemen** [comment]
E:\[NHML]\ - it's a path to NHML ?
Remove [ and ], think it can help
U must rename folder like this E:\NHML\

**Comment by Whisperd130** [comment]
Sorry about that. That just a long path.

**Comment by Whisperd130** [comment]
And for these errors.
I just change my VS to 2017. Then all errors gone.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Issue related to users build environment
