### ISSUE TITLE
AMD A8 APU mining

### ISSUE THREAD

**Issue by AE001** [nicehash/NiceHashMiner#1096]
I have and AMD A8 5500 processor with Radeon HD 7560D integrated GPU.
The benchmark results for the GPU is show in attachment 1.
However, when I run the GPU to mine on Equihash (Claymore), the hash speed remains zero with the mining screen showing data as per attachment 2.
When I run it on Equihash (Optiminer) the mining screen starts and closes and no mining takes place.
Finally, when I run it on Skunk (Prospector), the mining rate is very slow, which contradicts the benchmark results.
Please note that all the benchmarks were ran in Precise mode.

Please guide as to what might be the problem?
![image](https://user-images.githubusercontent.com/33860753/37726278-d30e1bcc-2d56-11e8-931a-fc1f2ea4a92a.png)

![image](https://user-images.githubusercontent.com/33860753/37726304-e15fd6ca-2d56-11e8-90d7-6c94448ea1ca.png)

**Comment by S74nk0** [comment]
Integrated GPUs aren't supported.
