### ISSUE TITLE
Bug in benchmark BTC/day values for DH

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner#1097]
Hi,

There is a bug in the benchmark window's BTC/day column - for algorithms DaggerSia, DaggerPascal and DaggerDecred the values are too high, so the miner doesn't switch to Equihash.

See screenshot:
![image](https://user-images.githubusercontent.com/25568030/37733602-ee3a2854-2d48-11e8-9acf-c270651c1692.png)

**Comment by jaymoeco** [comment]
I reported this same issue over a week ago and have seen no responses.

**Comment by giosal** [comment]
#1084 true

**Comment by giosal** [comment]
@DillonN @S74nk0 any news?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
