### ISSUE TITLE
Cryptonight v7 update

### ISSUE THREAD

**Issue by francescocmazza** [nicehash/NiceHashMiner#1098]
Hello Dillon,
The V7 hard fork for cryptonight is coming in a few days. I've heard on twitter that NHML will be updated to the new algo. Do you have an idea on when you will be ready for that? Can I suggest implementing XMRig miner? Apart from a slight performance increase compared to stak-xmr, their latest version is already compatible with V7.

Thank you

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Cryptonight v7 is not relevant anymore
