### ISSUE TITLE
Пилообразный график доходности

### ISSUE THREAD

**Issue by Alexus6** [nicehash/NiceHashMiner#1099]
Добрый день.
Имею два рига, с различными видеокартами. 
Смущает большие перепады графика доходности. Слушком уж он пилообразный. 
Это нормально? Можно как-то понизить его провалы?
![nice](https://user-images.githubusercontent.com/32474525/37814112-101fbc3a-2e8a-11e8-8673-dc882f87d87a.jpg)

**Comment by Cabbanis** [comment]
nais inglish

**Comment by serh39** [comment]
нет, перейди на китайский пул

**Comment by UselessGuru** [comment]
Please write in English. Thank you!

**Comment by S74nk0** [comment]
Please write in English.

Issue not related to nhm/nhml client. Write to support@nicehash.com.
