### ISSUE TITLE
ETH Share Rejected

### ISSUE THREAD

**Issue by sabaruddin** [nicehash/NiceHashMiner#110]
keeps happening even I manually updated with latest claymore_dual v9.8 and switch to another server location

**Comment by DillonN** [comment]
When you watch the miner window does it give you a reason why the shares are rejected? 

Rejected shares can happen for a variety of reasons, but most common are a poor connection to the pool or hardware instability (overclocks/undervolts/failures). A small percentage of rejected is not abnormal, especially when dual mining claymore dual

**Comment by sabaruddin** [comment]
60% rejected, also happened on my team's farm. but after 11.30 pm last night they are running smooth. thanks DillonN
