### ISSUE TITLE
Cannot allocate big buffer for DAG

### ISSUE THREAD

**Issue by milkcoins** [nicehash/NiceHashMiner#1102]
Mining is not on all graphics cards.

This is a log for GeForce GTX 1060 3GB for DaggerPascal (Claymore's Miner v10.6):

`Setting DAG epoch #177 for GPU0`
`Create GPU buffer for GPU0`
`CUDA error - cannot allocate big buffer for DAG. Check readme.txt for possible solutions.`
`Quit, please wait...`

**Comment by rrivv** [comment]
Same issue. Used memory of GPU - 2.5 of 3 GB. 
Increasing virtual memory to 30 GB didnt't help.
Helped adding `-eres 0` at algo settings.

win 10 1709 Enterprise / Nvidia 391.01

It is not working for ETC (dag epoc #186)

**Comment by rrivv** [comment]
It seems its a win 10 bug
https://social.technet.microsoft.com/Forums/en-US/15b9654e-5da7-45b7-93de-e8b63faef064/windows-10-does-not-let-cuda-applications-to-use-all-vram-on-especially-secondary-graphics-cards?forum=win10itprohardware

btw, built-in Ethminer works fine

**Comment by milkcoins** [comment]
@rrivv thanks for the research! I temporarily turned off Claymore's Miner for GTX 1060 3GB. I'm going to change the mining software, the pool or the operating system soon.

**Comment by DinosaurDad423** [comment]
Trying to offer some help as I spent many hours on this.  My 3gb 1060's stopped after a reboot yesterday.  -eres doesn't fix it anymore, and I like Win10.  

Here's an alternative solution:  http://blockchainllama.com/?p=62

**Comment by UselessGuru** [comment]
The DAG has grown too big to fit into 3GB cards. These cards are now perfect paperweights if you want to mine 'normal' ethash. You can still mine other algorithms with it.

**Comment by rrivv** [comment]
Current Ethereum DAG file is less than 2.5GB, so 3GB cards are still perfect for Ethereum mining and even for dual mining. But not on win 10 )

**Comment by S74nk0** [comment]
Issue related to old unsupported GPUs. Check https://investoon.com/tools/dag_size for minimum RAM requirements.

We will implement feature to check free active RAM to not switch on GPUs with less active RAM.
