### ISSUE TITLE
update miners xmrig nheq sg prospector zm klaust claymore dual to latest

### ISSUE THREAD

**Issue by professor-jonny** [nicehash/NiceHashMiner#1104]
the below miners are updated could these be patched into nicehash legacy ?
xmrig 2.5.0
nheqminer_5c
sgminer 5.6.1
prospector 0.13 alpha
zm_0.6
ccminer KlausT 8.21
claymore dual 11.5
xmr-stack-cpu to xmr-stak-win64

**Comment by g5-freemen** [comment]
You forget Excavator miner, but looks like we never see update

**Comment by nerdatwork** [comment]
Prolly Dillon is not getting paid on time :(

**Comment by professor-jonny** [comment]
I patched them all in I could manually myself except for prospector and xmr-stack-win64 both these will need coding changes as their config setups are different to the older versions.

**Comment by g5-freemen** [comment]
Same thing about new Excavator miner

**Comment by nerdatwork** [comment]
Besides Dagger and pascal what is profitable for Nvidia anyway

**Comment by professor-jonny** [comment]
they need xmr to be updated for the pow change upstream. and the likes of prospector is multi algro and cpu/gpu now be nice to bench and compare.

**Comment by nerdatwork** [comment]
Officially nicehash was the only pool confirming support for new and old xmr algos so the devs must be trying to code it together but I see no "commits" for a real long time. Hate NHML being treated as unwanted child.

**Comment by JCarangoH** [comment]
@nerdatwork I think you should see the 'cd-tuner' branch, he is pushing commits like no future ahead...

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
