### ISSUE TITLE
Doesn't see temps for radeon rx 560v2[rx460]

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#1109]
I have 2 gpus and only one identifies its temp. Any idea if there is a fix for this. Being v2 of the 560 maybe they cheaped out and didn't put a sensor in it.

Thanks

**Comment by ghost** [comment]
rx560 don't work on algorithm CryptoNight! WHY??? WTF NICEHASH

**Comment by S74nk0** [comment]
AMD driver issue or GPU not connected to monitors.
