### ISSUE TITLE
Unable to get profitability data

### ISSUE THREAD

**Issue by Atari2600l** [nicehash/NiceHashMiner#1110]
Why this happend every time my PC restart? this version is 1.8.1.10 is supposed this issue was solved. Regards...

**Comment by Spareo** [comment]
I have the same issue, it pops up and usually I miss out on a few hours of mining because of it. Is there a way to disable this check?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.
