### ISSUE TITLE
Не работает майнер CryptoNight с AMD rx560

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1119]
У меня три карты. GTX1060 и две AMD rx560. 1060 работает стабильно, а на AMD не запускается CryptoNight. 1 раз из 10 запускается и работает но потом вырубается спустя какое-то время. На пулах rx560 работают нормально, сразу всё работает но на найсхеше глючит ужасно. Запускаю без разгона, антивир отключен, драйвера последние. Алгоритмы менял в найсхеше но не помогает. При любом алгоритме глючит. В чем проблема?

**Comment by clan4el** [comment]
Попробуй разные версии насхеша, если и там такое то проблема в твоих видюхах видимо.

**Comment by ghost** [comment]
как может быть проблема в видюхах если на пулах работают без проблем. Только с найсом глюки происходят и только на одном алгоритме CryptoNight, сейчас даже бенчмарк нельзя пройти [скриншот](https://pp.userapi.com/c845321/v845321289/1cf51/-pUPD-67RMQ.jpg)

**Comment by clan4el** [comment]
скачай 1.8.1.10 версию, в общих настройках ничего на вкладке устройства и алгоритмы поставь галку на CryptoNight и пропиши руками скорость своей видюхи. Сохрани и запусти майнер,

**Comment by UselessGuru** [comment]
Please write in English. Thank you!
