### ISSUE TITLE
CryptonightV7 support and 0% devfee in Claymore Cryptonote miner 11.3

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner#1125]
Please, update NHM Legacy to support CryptonightV7 with new 11.3 version of Claymore Cryptonote miner.

**Comment by YuriyNa** [comment]
Поддерживаю. Очень долго нет обновления NHML, и майнеры надо обновить.

**Comment by cxcxcxcxc** [comment]
Please, update NHM Legacy to support CryptonightV7 with new 11.3 version of Claymore Cryptonote miner.

**Comment by klausGermany** [comment]
yes please we are waiting for this

**Comment by kaos-1** [comment]
@DillonN

**Comment by adem4ik** [comment]
check https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.0

**Comment by UnclWish** [comment]
> check https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.0

No Claymore CN miner 11.3 for V7.

**Comment by cxcxcxcxc** [comment]
По этой ссылке с оф. сайта ловится вирус

**Comment by UnclWish** [comment]
> По этой ссылке с оф. сайта ловится вирус

90% майнеров определяются антивирусами как вирусы или вредоносные программы. Пора бы такие вещи уже знать.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
