### ISSUE TITLE
NHM legacy don't start when the internet returns --- NHMlegacy no inicia cuando vuelve el internet

### ISSUE THREAD

**Issue by ccooppss** [nicehash/NiceHashMiner#1128]
Venezuela is one of the largest communities (according to the current record, about 355,000 people) of crypto-miners because a solution to mitigate the growing inflation in which the country lives, since the national currency literally devaluates daily.
recently I am actively using NHMLegacy to take control of gpu miners since it is a much more stable tool than others that I have tried, but I have encountered an inconvenience, in Venezuela there are many problems with electricity which causes many blackouts, and when this happens, the internet is slow to come back, and software can not connect to the profit calculation server and it never starts, I have to go back and start it manually, sometimes I lose a day of mining because I'm traveling , and I could not go back to restart the software. someone to give me a solution?

------------------------------------------------------------------------------------------------------

Venezuela es una de las comunidades más grandes (segun el registro actual, unas 355000 personas) de crypto-mineros debido a que una solución para mitigar la creciente inflacion en la que vive el pais, ya que la moneda nacional literalmente se devalua a diario. 
recientemente estoy utilizando de forma activa NHMLegacy para llevar el control de mineros gpu ya que es una herramienta mucho mas estable que otras que he probado, pero me he encotrado con un inconveniente, en Venezuela hay muchos problemas con la electricidad lo cual ocaciona que se suciten muchos apagones, y cuando esto sucede, el internet tarda en volver, y software no se puede conectar con el servidor de calculo de profit y no inicia nunca, tengo que volver e inicarlo manualmente, aveces hasta pierdo 1 dia de minado porque ando de viaje,  y no pude volver para  reiniciar el software. alguien que me brinde una solucion??

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

This should be fixed in the latest release
