### ISSUE TITLE
Lower hashrate on XMR Stak using NHlegacy Alpha

### ISSUE THREAD

**Issue by McDevilbird** [nicehash/NiceHashMiner#1129]
I tested XMR Stak with and without NH mining on cryptonightV7 and i loose about 10% when using NH. I copied the settings to the xmr folder in the bin folder.
When i run the miner directly i get 2900 hs/s on 6 rx 550s. Via NH i get 2600 hs/s.
Same miner, same settings. I even updated to the newest xmr release. 2.4.2 no change.

**Comment by Smeagol001** [comment]
havve you really checked in the miner wiondow or just the value that the nicehash client is  reading  strange values sometimes

**Comment by McDevilbird** [comment]
Yes i compared it to the miner window.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
