### ISSUE TITLE
Please disable DaggerHashimoto for GTX970

### ISSUE THREAD

**Issue by blue-yu** [nicehash/NiceHashMiner#1130]
GTX970 can't mine ETH, so please disable it from NHML just like You did for GTX750TI.

BR...

**Comment by pbuva** [comment]
You cant turn them off in settings.

**Comment by Crypto-Lord** [comment]
Are you using Windows 10?

**Comment by blue-yu** [comment]
I know that I can turn them off, but every time new version comes out, I have to do it all over again. Same situation was with 750ti long time ago.

I am using Win7. Why do You ask?

**Comment by Crypto-Lord** [comment]
Was just wondering if it was due to the dag size. But anyways do you copy your config folder over from the last version of the miner to the new? It should keep all the values you had before and keep algos you have selected/deselected.

**Comment by blue-yu** [comment]
Anyhow, I don't want to troll anymore, so I repeat my message - can ETH be disabled for GTX970?

**Comment by Simaex** [comment]
@blue-yu Actually ETH is running on GTX970 without major problems. Performance is not great but you have benchmarks to select algo wich is optimal at any given moment. As long as you can disable any algo youself no need to enforce your preferences to other users.

**Comment by blue-yu** [comment]
Problem is that benchmark is using old small DAG file size and give me 21-22 result, but actual dag file 180+ is causing problems
