### ISSUE TITLE
XMR Starts mining without interaction

### ISSUE THREAD

**Issue by DetonationEMS** [nicehash/NiceHashMiner#1131]
XMR Started mining on its own.. I closed nice-hash miner and it continued to mine.. I was unable to end the task of the miner. I was forced to reboot the system.. Happened twice now.. 1.9.0.0 -Alpha
FX-8370
GTX 750 ti
GTX 670

New install less than 2 hours..

**Comment by tinkermade** [comment]
Similar problem where XMR console window persistently re-opens after clicking "Stop" on Nicehash GUI and closing the console window.  The work-around is killing the NiceHashLegacyMiner.exe task in Task Manager.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
