### ISSUE TITLE
Computer crash when running claymore miner with rx 570 and 580 in same computer

### ISSUE THREAD

**Issue by NuMiner** [nicehash/NiceHashMiner#1132]
Been trying to figure out why my computer keeps crashing whenever i try to run the daggerhashimoto or daggerdecred in the claymore miner with both of my cards at the same time using the Legacy software. 

I can use claymore miner to mine ethereum on my computer without issue. But when I attempt to use the legacy software it crashes. I can use both cards at the same time if i use different 3rd party software within the legacy miner. i.e one card mining using claymore miner and one using zcash miner.

I am using driver version 18.2.3.

Hope you can help

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
