### ISSUE TITLE
Cryptonightv7 cuda miner in 1.8.1.11

### ISSUE THREAD

**Issue by AtlAntA118** [nicehash/NiceHashMiner#1133]
Hello, i noticed this miner is missing when compared to 1.9. Is there ia reason for that? It works like a charm (not profitable though) on 1.9.

**Comment by DeDamis** [comment]
I am missing CryptoNightV7 miners in this version (1.8.1.11) too.

**Comment by luky76** [comment]
same for me

**Comment by ghost** [comment]
admin nicehash SUCK IDIOT
