### ISSUE TITLE
Seems like no work avail for cpu in ".11"

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#1135]
Hopefully that's a bug and will be fixed. My cpu was disabled in the list and nothing to benchmark for it.

**Comment by luky76** [comment]
same for me

**Comment by maciver** [comment]
same on all 3 of my computers the CPU isnt doing anything and nothing at all in benchmark list...
![bench](https://user-images.githubusercontent.com/9095081/38884956-e1353268-4236-11e8-96e4-b05bc3f9c510.jpg)

**Comment by serjeg3** [comment]
то же самое

**Comment by serjeg3** [comment]
зачем отключили CPU? "Удалить CryptoNight (оригинал) и Nist5" ЗАЧЕМ? и как включить?

**Comment by sersanchus** [comment]
It didn't show any algorithms for cpu for me neither.

**Comment by ghost** [comment]
Hello, i have the same problem with i5-8400 @ 2.8GHz (6 core). No algorithm to select.

CPU working well on NiceHash v2.0.2.2 Beta

**Comment by peteycrack420** [comment]
me too on my i7 4770k   download 2.02.2  and shows up there  i have both running

**Comment by serjeg3** [comment]
я поставил 1.9.0.0 там работает  i7 4770k

**Comment by peteycrack420** [comment]
i have it overclocked to 4.9 and liquid cooled

**Comment by peteycrack420** [comment]
version 1.9  thats not up yet that i can see

**Comment by peteycrack420** [comment]
i see it now

**Comment by serjeg3** [comment]
сколько баксов даёт разогнанный i7 4770k?

**Comment by serjeg3** [comment]
у меня маленький разгон 3.9

**Comment by ghost** [comment]
@serjeg3 Use english.
@peteycrack420 nicehash miner 1.9. aplha have some bugs and going to crash everytime when benchmarks run.

**Comment by techman05** [comment]
Its more like my pc crashes[regardless of version] but I've had it[1.9 because it has cpu mining] running since last Wednesday and no burps. My only gripe is it mines my cards separately even though its listing the same coin type.

**Comment by ghost** [comment]
![miner crap](https://user-images.githubusercontent.com/38539203/39276238-8fd31f62-48e8-11e8-8a1d-ddd7878d614a.png)
Nicehash crash, it opens so many consoles and stop running

Edit:
It's v1.9 Alpha

**Comment by techman05** [comment]
I somehow haven't had that yet🤔. Wow!

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
