### ISSUE TITLE
RX560 почему не меняются алгоритмы?

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1137]
Заметил, что алгоритмы не хотят сами менятся. Например: работает даггер потом перестает и дро*ится то запускается и сразу закрывается. Писал ранее о подобной проблеме, можете найти. Проблема оказалась в том, что даггер когда вырубается то алгоритм не меняется на криптонайт или экихеш.  Так же смена алгоритма не происходит и при других выбранных. Даггер тут не причем. Поибень и с другими алгоритмами, один запускается другой нет. Через время например даггер работает потом вырубается, спустя какое то время он снова работает. Криптонайт тоже самое, получается так что майнер запускает консоль ( черное окно ) и потом сразу закрывает. На пулах карты работают, на найсхеше почти не работают . Почему не меняются алгоритмы ?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Please write in English
