### ISSUE TITLE
WHY  rx560 don't work on new miner 1.9.0.0 cryptonightV7 ???

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1139]
HELP
I have 2 rx560 4gb
Driver  (last)
Miner 1.9.0.0
Start miner  and nothing!
Miner cryptonightv7 open and close! WHY ?

**Comment by ghost** [comment]
заебись я написал. Может поймут

**Comment by ghost** [comment]
хоть бы одна сволочь написала, что ESET NOD работает втихую и пиздит файлы найсхеша. Столько майнеров и никто не сказал об этом. Кто не знает знайте. Антивир если он отключен то он не отключается полностью. Он всё равно работает и удаляет майнеры но потихому без оповещений. СУКА

**Comment by Enelar** [comment]
Well, first of all nobody is obligated to help you. It's nice act of will. It's open source, and you free to use it. It is a common practice to pay for support tho. Then your case is rare, nobody using antiviruses on mining rigs - cause they slowing down PC, and there is no way to protect miners itself. I assume you store your money far away from miner, so just monitor daily income, and you'll spot any viruses.

Next, yes, its common knowledge that antiviruses treat mining software as botnet payload. Nobody ever could assume from your origin message that:
A) you're using windows
B) you have NOD

And finally, it was less than day until first response. You're spoiled, we are not your servants.
Have a great day.
