### ISSUE TITLE
GPU Temps

### ISSUE THREAD

**Issue by michael-mml** [nicehash/NiceHashMiner#114]
1.8.0.2 causes my temps to max out, while the same configuration on 1.8.0.0 drops the temps by at least 5; on the same algorithm, default decri value

**Comment by DillonN** [comment]
When testing this did you run any other algorithms first? I have found that some miners can disable the temp limits on my 1080 Ti through the way they access hardware, which causes it to run much hotter. The temp limit doesn't work again until a restart. If you are running one of these miners before testing the ClaymoreDual temperatures perhaps this could be the reason?

**Comment by ChriscomIT** [comment]
@MLCoco And as well please don't forget to keep ambient temps in mind as this can cause different temps too.

**Comment by michael-mml** [comment]
@DillonN I will test it by disabling the other algorithms and let you know
@ChriscomIT I performed both tests on the same day

**Comment by michael-mml** [comment]
Seems like it was the other algorithms affecting the temp limit. Disabling those worked. Thanks @DillonN
