### ISSUE TITLE
1.8.1.11 Chrome virus deteced

### ISSUE THREAD

**Issue by o-Epictetus-o** [nicehash/NiceHashMiner#1141]
I just downloaded the latest release 1.8.1.11 with the latest version of Chrome for Windows and the download states  Failed - Virus detected.

Edit: Just downloaded with Brave browser and after unzipping Windows Defender pops up showing this. Trojan:Win32/Spursint.F!cl

**Comment by hwasiti** [comment]
Yeah for me too. I think there are a lot of confused windows users on this. It would be great to put a notice on the download page on why this is happening in the last few version releases.

**Comment by S74nk0** [comment]
Use it at your own risk. All miner software is flagged because it is frequently bundled with malware.
