### ISSUE TITLE
Add Cast XMR for Cryptonightv7

### ISSUE THREAD

**Issue by Trigger30** [nicehash/NiceHashMiner#1143]
Would be great if you guys add cast xmr and claymore for the Cryptonightv7 algo. They are more optimized than xmr-stak. Thanks

**Comment by Trigger30** [comment]
Would be great if you guys add cast xmr and claymore for the Cryptonightv7 algo. They are more optimized than xmr-stak. Thanks

**Comment by Quake4** [comment]
Try MindMiner. Its support cnv7.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Cryptonightv7 is not supported anymore
