### ISSUE TITLE
Some problem here

### ISSUE THREAD

**Issue by NameUnavailable** [nicehash/NiceHashMiner#115]
So just realised at some point nicehash is trying to mine.. but the instance keeps opening and shutting down restarting all the time. but it can work for days and have no problem and can work for hours and crash depending of what it mines i guess i dont know.. it happens to crash when this happens but when we restart computer it works fine for as long as that dosent happen.

![untitled2](https://user-images.githubusercontent.com/30479416/28949682-67a0d8fe-788c-11e7-9df7-fd252b26e8ec.jpg)

**Comment by DillonN** [comment]
Hello @NameUnavailable, could you please post which devices you have on the system as well as the log file `\logs\log.txt` for when you try this?

**Comment by NameUnavailable** [comment]
1x Gtx 1080 a8g and 5x gtx 1070

id like to specify that the gpu that is crashing upon that error is a 1070.

would it make it easier to find what you need if i posted the log file right after the problem happens?  or is right now fine?

**Comment by DillonN** [comment]
The sooner from the problem the better, if it's too far after it may not be in the log anymore.

**Comment by NameUnavailable** [comment]
new error 

![untitled3](https://user-images.githubusercontent.com/30479416/28952411-0852036a-789f-11e7-9180-dea6d9103048.jpg)

**Comment by NameUnavailable** [comment]
here is the log file 

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1199113/log.txt)

**Comment by ChriscomIT** [comment]
Had it some minutes before as well. I send logs tomorrow.

**Comment by DillonN** [comment]
There is an issue with the same issue as that I believe, #101. You can check the answer there

@ChriscomIT do you have the first issue or second?

**Comment by NameUnavailable** [comment]
excellent will upload log file when the first problem comes up again thanks

**Comment by ChriscomIT** [comment]
@DillonN I have the second issue. Sorry forgot this was already explained by Nicehashdev before (had a conversation about this in one of the issues lately). Seems it was the "no orders" available issue. My fault.
