### ISSUE TITLE
Thank you DillonN

### ISSUE THREAD

**Issue by PrinceOfParallax** [nicehash/NiceHashMiner#1150]
Hi Guys, I love NHM, and enjoy the Legacy tools, Can we work on implementing things like the multigpu benchmarking, or at least and option for it.

Also can we work a way for card that have bench marked to work/run. its hard for me to benchmark and keep my rigs going, I have 5 rigs all with 12 or 13 cards in them, and it makes it a task when I need to update NHML - I know I can move the configs over, and I do, but when many/most of the miners/algos are updated, or a major driver revision comes out I really like to re-benchmark so I get a better idea of performance gains, the thing that sucks is for me for have NHM benchmark all 188 (Sometimes more) a rig can be down for 6 hours or more.

That's not so bad, if I can go to work and come home toa machine that is running, and I know I can sometimes set it to "Start mining after Benchmark" - but can we change the behavior of this check box so it starts mining and DOES NOT pop up about failed or non-benchmarked algos?

I've got other ideas, about using the miners while running to write a small dump file that can calibrate/correct your benchmarks but that's a pipe dream.

or 

Have a script that will  allow you to:

Upgrade NHLM and copy your config over.
Open a copy and disable one of the cards. Start the rest mining.
Open a second copy and disable all but the one disabled card in the first copy. Start that one card benchmarking.

Once that card is done, close the benchmark window, stop the miners on first copy, enable newly benched card and disable the next. On the second copy disable newly benched card and enable next. Rinse/repeat.

Once all are benched, stop mining and close first copy. Then close second copy. The restart NHML and enable all cards.

 I like this trick but I've tried it in the past, and the second copy ended up I think over writing the configuration files of the new benchmarks.

Thanks for taking time to even read this.

**Comment by dadoremix** [comment]
or set generic bench results for cards
and we dont need benchmark at all

or, if you have 4-6-13 rx580 cards .. bench 1 cards and that is

**Comment by techman05** [comment]
Pre 2 I think mined as it benchmarked so you shouldn't loose time doing them. The item wasn't listed in the 1.9 version so maybe there were complications😩😩👾..
