### ISSUE TITLE
No algoritm to benchmark after miner download

### ISSUE THREAD

**Issue by rpgallan** [nicehash/NiceHashMiner#1154]
In the most of times, theres nop algorithm to bench after miners download on legacy.
When legacy shows the algorithms, bench freezes all the time
sometimes legacy didnt show any of my rx580
i tryed in 3 diferents MB, win up to date

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
