### ISSUE TITLE
Issue with SLI 

### ISSUE THREAD

**Issue by Rokk001** [nicehash/NiceHashMiner#1155]
Hi

Since last nVidia Driver Update I have the problem that NiceHash Legacy is only mining with 1 of 2 GTX1080TI Cards, although both cards are selected and enabled in NiceHash.
Nicehash is showing me both cards and both are enabled and selected in NiceHash but when I start mining, only Card1 will mine and Card2 does nothing.
After disabling SLI in nVidia Settings, Nicehash is running normal and mining with both cards.

I'm not shure is this an Nicehash or Driver issue, but I want to commit it - I'm using Nicehash Miner Legagy v1.8.1.11 and the nVidia driver 397.31-desktop-win10-64bit-international-whql

thanks and regards
CMZ

**Comment by Crypto-Lord** [comment]
Completely normal if you have SLI or Crossfire(AMD) enabled.
Always disable SLI & Crossfire when mining.

**Comment by S74nk0** [comment]
What @Crypto-Lord wrote... 

Closing issue

**Comment by pedroadelino** [comment]
> Completely normal if you have SLI or Crossfire(AMD) enabled.
> Always disable SLI & Crossfire when mining.

OBRIGADO!
