### ISSUE TITLE
1.8.1.11 opens too much sgminer.exe consoles

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1157]
Hello,
i would like to report error with opening too many sgminer.exe consoles. After 10 hours minig, nicehash legacy 1.8.1.11 opens so many consoles and system stop mining and stop working.

I'm using 
Nicehash v2 with GPU 4xGTX1060 + GPU 1xGTX1070 + CPU i5-8400
and
Nicehash 1.8.1.11 with GPU AMD HD6970

Nicehash v2 works without any problems.

Screenshot of desktop:
![39276238-8fd31f62-48e8-11e8-8a1d-ddd7878d614a](https://user-images.githubusercontent.com/38539203/39542230-471e6334-4e48-11e8-9689-32183ef61bb7.png)

**Comment by Sav87** [comment]
A problem in the code that will not be fixed

**Comment by ghost** [comment]
thats great news :D so i can throw amd gpu to trash :D
