### ISSUE TITLE
CryptonightV7 more than 70% reject shares

### ISSUE THREAD

**Issue by maggie1307** [nicehash/NiceHashMiner#1159]
Hi,
I changed my rigs to mine CryptonightV7 and I get more than 70% rejected shares. The reason is Share above target. I use Cast XMR 1.0.0 for Windows 64. Rigs are with AMD RX Vega 56. Can I do something to change this efficiency?

Regards.

**Comment by beachiemon** [comment]
I am getting the same results with cryptonightv7 claymore left it on for a bit 100% rejected "Share above target". xmrstak seems to work fine but it is set to workload 8 of 32 and is very slow. hardware is vega 64 on windows 10.

**Comment by styelz** [comment]
Same issue here too on my RX570s 100% rejected.

`GPU0 t=45C fan=55%
XMR: 06/06/18-19:56:55 - SHARE FOUND - (GPU 0; share value 0x0000003b)
Share rejected (313 ms)!
{"id":4,"jsonrpc":"2.0","error":{"code":1,"message":"Shareabovetarget."}}`

@beachiemon you can modify the workload from 8 to 32 by editing the bin\xmr-stak\amd.txt file. I tried this but it just slows the speed down. Changing the intensity to 1000 helped a  lot.

**Comment by styelz** [comment]
I was able to resolve this issue on my rig by installing the latest AMD Adrenalin 18.5.2 drivers. If you were using the old Aug23 driver previously you can set an option in the new AMD settings panel under Gaming, Global Properties and change GPU Workload from "Gaming" to "Compute" to get same mining speed from this new driver.

**Comment by maggie1307** [comment]
There is no GPU Workload toggle in AMD 17.30.1029 CrimsonReLive driver.

**Comment by styelz** [comment]
@maggie1307 yes I know that, you need to upgrade to the v18.5 driver.

**Comment by naitsirhc007** [comment]
Please verify that your BAT be like this

cast_xmr-vega --algo=1 -S cryptonightv7.usa.nicehash.com:3363 -u 3ARbZgGckTxxxxxxxxxxxxxxxxxxxxx2v5phR6ba.Rig01 %* -G 0,1,2,3,4,5,6,7


its very important --algo=1  the old configuration was --algo=-1

change that and my miner is ok NOW.

Bye

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
