### ISSUE TITLE
Signing and Publish script

### ISSUE THREAD

**Issue by kenman345** [nicehash/NiceHashMiner#116]
Hey, I'm new but wanted to test a build for myself and maybe make a pull request once I'm done. I was wondering why/how to use the signing script to sign Nicehash Miner now that I believe my changes are nearly complete. Can anyone help me?

**Comment by DillonN** [comment]
@kenman345 you can ignore the script and make a pull request here to submit your changes. Thanks for contributing!

**Comment by kenman345** [comment]
I will make the pull request once I finish testing. I made a small addition of IFTTT integration allowing the miner to report to you when it is no longer profitable or starting back up after not being profitable.

**Comment by kenman345** [comment]
@DillonN I am having trouble with my conditional text field (based off the status of a checkbox) loading the settings menu properly. It contains the proper data and if you use the checkbox it will enable or disable the field but on loading the settings it is always disabled even though the value is in there and the checkbox is checked.

Would you like to take a look at it Or should I make a pull request and you can sort it out in between? Otherwise, my integration with IFTTT works well I just get notifications when I hit "stop mining" when it is in the not profitable state and restart things.  Someone with your ability could probably spot the fix as I just now use a boolean when it deems the software profitable or not and switch it after the first time it hits that code path. I think I need to reset that boolean before restarting but not sure where to put that. Maybe in the stop mining code reset the bool? I havent gotten into debugging too far.

**Comment by kenman345** [comment]
Made the pull request. Let me know what you think.
