### ISSUE TITLE
Nhml 1.9.0.0

### ISSUE THREAD

**Issue by clizmax** [nicehash/NiceHashMiner#1163]
why in the version of nhml 1.9.0.0 alpha at the start of the program pops up the window "can not get nicehash profit data". this began to appear when version 1.9.0.1 was released. especially if you did so ??
and I do not want to switch to the new version, because Miner xmrig was removed, it yields 6 times more than xmr-stak ... return everything as it was, please

**Comment by underway113** [comment]
NHML v1 always behave like that. (if im not wrong, i was using from 1.7.6.3 until now 1.9.0.1) 
so yeah, you should update to the latest version to get rid that error.

until now still no fix from dev

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
