### ISSUE TITLE
1.9.0.1   Lyra2REv2 - 4 rigs crash on benchmark

### ISSUE THREAD

**Issue by pbuva** [nicehash/NiceHashMiner#1164]
Hi, on 4 rigs  1.9.0.1   Lyra2REv2 benchmark freeze rig

**Comment by rogerbay** [comment]
Once I run it crash die down gone, please check and let us know.

**Comment by Sleinous** [comment]
same

**Comment by b22ri22an** [comment]
<img width="426" alt="capture" src="https://user-images.githubusercontent.com/39003224/39662049-30a01d4e-502a-11e8-96b1-1f94b1165568.PNG">
Also crashing on 1.9.0.1

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
