### ISSUE TITLE
Crashes on window 10 64 - nhm_windows_1.9.0.1.zip

### ISSUE THREAD

**Issue by rogerbay** [nicehash/NiceHashMiner#1165]
nhm_windows_1.9.0.1.zip crashes every time I run it. Please check and let us know.

**Comment by ww40** [comment]
I'm running Windows 10 64bit and I've not encountered this issue.

**Comment by underway113** [comment]
i'm running nh 1.9.0.1 smoothly. no problem at all. just miscalculate benchmark for +Blake2s . (i don't know is it my graphics card or the nh)

(running Windows 10 64bit)

**Comment by Sleinous** [comment]
same problem here insta crash when benching

**Comment by b22ri22an** [comment]
<img width="426" alt="capture" src="https://user-images.githubusercontent.com/39003224/39662143-48dc1650-502b-11e8-866d-e0bc66725591.PNG">
crashing on startup when attempting to detect GPU

**Comment by chinard** [comment]
Same problem, crashes during benchmark.
app just closes, no error, nothing interesting in logs.
went back to 1.8.1.11 things run just fine

**Comment by Geesu** [comment]
Same. Mine crashes the second benchmarking starts.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
