### ISSUE TITLE
1.9.0.1 seems less profitable

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#1173]
With just gpus on 1.8.0.11 I saws 2.50ish U.S.D and now with CPU/GPU on 1.9.0.1 I'm getting about 1.10+-.

Did the difficulty spike over the last 48 hrs or is something up. I'm going to miss another repayment from the drop in estimated pay.

**Comment by dadoremix** [comment]
watch coins, and not $/day

**Comment by AtlAntA118** [comment]
Just wait a few hours. It will come back up.

**Comment by techman05** [comment]
This seems to be the case. I always had the thought that once the dag file knows what your capable of that was the expectation number[work value per day]. At least moving to 1.9.0.1 supposedly cut down on fee to claymore,so that should mean more nich hash work done🤔👍.

**Comment by AtlAntA118** [comment]
My theory about this is that if you upgrade to a newer version you (obviously) disconnect for a while. When reconnecting you are probably assigned to a slightly lower paying hashing order. Im guessing this is done to ensure the highest paying orders are getting the most stable hashrates of miners that are connected stable for a long time. Just a theory though.

**Comment by PBJellytime** [comment]
I'm finding the same, with 1.9.0.1 i'm getting about 0.72 mBTC per day but on 1.8.x.x i'm getting 0.74 mBTC per day.  It seems to be selecting a single algo on 1.8.x.x but multiple algos on 1.9.0.1.  Now that should be based on profitability shouldn't it?  I've not entered any amounts into the kw/h field so this shouldn't be affecting it. Oh and i rebenchmarked both versions

**Comment by PBJellytime** [comment]
On two different rigs but both exactly the same build albeit different model GTX 1060s 6GB

Hopefully the screenshots are there, but as you can see very similar hashrates yet 1.9.0.2 is yielding about 16% less than 1.8.1.10

![image](https://user-images.githubusercontent.com/36086338/40563792-ff20529a-605d-11e8-95ab-08ed4a66bc8b.png)

![image](https://user-images.githubusercontent.com/36086338/40563796-04dc8744-605e-11e8-9c86-d4b07c3d0113.png)

**Comment by dadoremix** [comment]
That is not problem with miner
Or version of nicehash app

Try again old nicehash and you see that is the same profit btc/day

You are selling power, and someone is paying for that
Price is on market +/-, its not fixed

25.05.2018., u 21:53, korisnik PBJellytime <notifications@github.com> je napisao:

**Comment by PBJellytime** [comment]
I did wonder if that might be the issue, the disparity between contracts, thanks for confirming

**Comment by Novicracker** [comment]
I also found this to be true.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
