### ISSUE TITLE
Unable to get nicehash profitability data

### ISSUE THREAD

**Issue by Swaps1313** [nicehash/NiceHashMiner#1176]
![attels](https://user-images.githubusercontent.com/39056335/39703497-e5a32708-5210-11e8-9e81-ac804823943b.png)
After restarting or opening, Nicehash opens error
"Unable to get nicehash profitability data" and waits for action. After Pressing Ok and Start, it mines. It is not network issue, since the same happens in two different locations and providers already for two days. At lieast you can make some changes in future releases, so Nicehash runs with old values or restarts

**Comment by underway113** [comment]
what version do u use?

**Comment by underway113** [comment]
@DillonN could u fix this error. i think this bug is from long while a go (using NHML from 1.7.6.3 until now 1.9.0.1)
thanks

**Comment by Swaps1313** [comment]
Version 1.8.0.11 and on one rig 1.9.0.1, the same error.
Already about two days every Nicehash starting gets this error even on two different locations and ISP

**Comment by Swaps1313** [comment]
Sorry, seems like it is fixed in 1.9.0.1, updated all rigs to 1.9.0.1 and now no more error, with 1.8 versions still get error.

**Comment by bradfox2** [comment]
This is still an issue on 1.9.0.1.  Please reopen.   NHML will not resume mining after a remote power cycle.  There needs to be a recheck of connectivity after the warning dialog is displayed.

**Comment by XerxesNagato** [comment]
i have this erroe in the lates version, any help please ?

**Comment by S74nk0** [comment]
@XerxesNagato this is a temporary backend issue or a problem with your ISP
