### ISSUE TITLE
4x GTX 1060 Mining Rig powering (NiceHash Errors)

### ISSUE THREAD

**Issue by DRiccardi92** [nicehash/NiceHashMiner#1177]
Hello,
Im Using Nicehash Miner Legacy to mine eth and equihash. 

heres my configuration

Intel i3 4150 
8gb ram
4x GTX 1060 3gb
850W PSU EVGA GQ 
asrock h97 pro4 (4x pcie)

Since im using 3 risers for the other 3 gpus (one is in the mobo directly) im getting invalid shares frequently and sometimes a whole gpu crashes and stops mining. 

Im powering the board with an additional molex to power the pcie slots.

My PSU has following cables:

3x PCI-E strains with 6x pcie 6+2 pins (powering 4 cards, 2 of them share a 6pin strain. 

2 strains of sata cables (3 each) (using 1 strain to power 1 gpu and the sdd) (the other strain powers 2 other risers) the 4th gpu is powered by the mobo directly (x16 slot)

1 strain of molex cables (3 molex pins) one is powering the mobo as mentioned above.

the risers do have molex to sata connectors.

should i power the other 2 risers with the molex cable instead or keep them powered by molex to sata as it is at the moment?

MSI Afterburner config for eth:

65% 
+800 Mem
60 fan speed

power draw at the wall (350-360 watts) getting 98mh/s stable

do i risk a fire or is it safe to use like that? 

also, it seems like my cards cant handle even further mem clock with the risers. before that, i could overclock them to +900 easily, now +800 is the limit (one of the 4 cards can do 760 only) or is that caused by the power limit? 

3x GPU 4600Mhz memory
1x GPU 4556Mhz MEmory
many questions, sorry Smiley 

Edit: I've got the option to plug in a second PSU with 560 Watts (Thermaltake) it provides 2x 6+2 Pin and 3 sata strains with 3 sata connectors each. 
Should I go for that? Or is that too much? I would power 2 cards with the second PSU then. Just need to know, dont have a connector for 2 PSU's so far. But I would buy one if neccessary.

**Comment by PBJellytime** [comment]
Sounds like you are too overclocked to me, i'm running 12 GTX 1060 6gb and 150 core 750 mem oc is the best i've got to run stable

**Comment by DRiccardi92** [comment]
You was right, I downclocked 2 of my cards to 780 and 760 Mem, now everything is stable since about 24hrs. Also i was able to lower my power limit. Im at 60-70w per card now :)

**Comment by PBJellytime** [comment]
Excellent, don't forget to close the issue ;)

**Comment by heyboy31** [comment]
PBJellytime, i have a little question for you,

i'm using 11 GTX 1060 6gb with 4G physical RAM, and when i start nicehash, sometime when the algorithm switch, i've CUDA error (but it's happen 1time per week only).

Do you thing the physical RAM can be the problem or not ? because i'm trying to find some answer on internet but i can't and i don't know if i need to buy 8G RAM or if 4G is enough.

Thank you for your answer :)

**Comment by PBJellytime** [comment]
I've not tested physical ram, I run 8gb and I've had that error before and it was down to not enough vram. Try increasing your vram, start at 32000 and go up from there.  I think it was the neoscrypt algo that caused it for me
