### ISSUE TITLE
Benchmarking and Autostart following closed issue #429

### ISSUE THREAD

**Issue by fairfax777** [nicehash/NiceHashMiner#1178]
Following the guidance of closed issue #429, all unbenchmarked miners have been unchecked, however, the autostart feature is unable to proceed because of because of the warnings. 

![benchmarks unchecked](https://user-images.githubusercontent.com/7015299/39775450-e59cfa98-52cb-11e8-9a34-7d459e64c5cb.jpg)
![benchmark warning](https://user-images.githubusercontent.com/7015299/39775466-f2b68726-52cb-11e8-8299-feb49fcd20fd.jpg)

**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
