### ISSUE TITLE
Not found GPU

### ISSUE THREAD

**Issue by Blackwaterxxx** [nicehash/NiceHashMiner#1180]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1985683/log.txt)
Could you please help me.
Nicehash does not find the gpu ,although the under windows is recognized.
Drivers are all up to date.
 log.txt
	Win32_VideoController detected:
		Name Intel(R) HD Graphics 3000
		Description Intel(R) HD Graphics 3000
		PNPDeviceID PCI\VEN_8086&DEV_0112&SUBSYS_844D1043&REV_09\3&11583659&0&10
		DriverVersion 9.17.10.4459
		Status OK
		InfSection iSNBD0
		AdapterRAM 2210398208
	Win32_VideoController detected:
		Name Radeon RX 580 Series
		Description Radeon RX 580 Series
		PNPDeviceID PCI\VEN_1002&DEV_67DF&SUBSYS_95881682&REV_E7\4&80E7924&0&0008
		DriverVersion 23.20.15017.3010
		Status OK
		InfSection ati2mtag_Polaris10DS
		AdapterRAM 4293918720

what can i do that nicehash displays the map
![20180424_101839](https://user-images.githubusercontent.com/38688792/39796097-d529bc1c-5354-11e8-83c5-20db66169f67.jpg)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
