### ISSUE TITLE
New system build Asus b350+ rx580 error 0xc000007b No GPU FOUND

### ISSUE THREAD

**Issue by Horsetoothless** [nicehash/NiceHashMiner#1181]
Have used GPU card successfully in other machines RECENTLY, know it works, just downloaded 18.2.1  software driver. Only unknown new item is the Asus B350+ motherboard with Ryzen 7 cpu.
![nicehash startup error](https://user-images.githubusercontent.com/31786763/39791741-e7f1def8-5302-11e8-9aa9-770b94e09c6c.PNG)

**Comment by Novicracker** [comment]
This is a Driver issue. Uninstall your video drivers. Download the latest
Drivers and them Run the program again.

Use Display Driver Uninstaller to uninstall your Drivers. ( Make sure you
are in SAFE MODE for the uninstall Hold shift when clicking Restart WIN 10
)
US-West Coast
<http://www.guru3d.com/files-get/display-driver-uninstaller-download,9.html>,
US-East Coast
<http://www.guru3d.com/files-get/display-driver-uninstaller-download,19.html>,
EU-UK
<http://www.guru3d.com/files-get/display-driver-uninstaller-download,14.html>

**Comment by Horsetoothless** [comment]
Did uninstall with above and reinstalled same error code , board does mine
on this system had it on ETN at MPH last night.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
