### ISSUE TITLE
Disconnection issues 

### ISSUE THREAD

**Issue by karneychen** [nicehash/NiceHashMiner#1182]
anyone getting  disconnects from using nice hash legacy (1.9.0.1)
![image](https://user-images.githubusercontent.com/39111771/39795569-b7096ce0-5305-11e8-8ad4-dba9eafcfe1e.png)

**Comment by ewislon1** [comment]
Go back to 18.2.1. I was getting lots of problems mining and going back to the old softwares fixed it. Install it here https://support.amd.com/en-us/download

**Comment by karneychen** [comment]
doesnt help much i went back and still got issues

**Comment by McFly99** [comment]
I asked for help from NiceHash support, they pointed me here. I see this issue on Claymore 10.0 and NHML 1.9.0.1 across anything using Dagger, but other algo's work... AV, Firewall, no IPS, no filtering. Spanned across three PCs, Ubuntu and Windows 10.

I can ping the DNS for what it's using... I don't think NH support takes possible issues seriously and points people here... Sure seems like a problem with blocking, DNS updates, or filtering on the head end in my case.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
