### ISSUE TITLE
Nvidia recomended driver warning with Nvidia detection disabled

### ISSUE THREAD

**Issue by tiagoefreitas** [nicehash/NiceHashMiner#1183]
I have Nvidia detection disabled because that card is not used for mining.

I get a warning on NHML startup saying the Nvidia driver is older than 362.61, that prevents the mining from starting automatically when the computer restarts.

With Nvidia detection disabled, it should also disable driver detection.

**Comment by nerdatwork** [comment]
Have you disabled the setting "Show driver version warning" from settings ?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
