### ISSUE TITLE
DO NOT UPDATE TO 18.4.1

### ISSUE THREAD

**Issue by damperl** [nicehash/NiceHashMiner#1184]
If you are mining using NHML 1.9.0.1 or any other of the miners, do not update your driver to 18.4.1 it will mess up everything with mining. I was getting no shares, no hashes, and the miner would keep restarting every few seconds. Stay on 18.2.1 because nicehash is compatible with that.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
