### ISSUE TITLE
Not found 13 amd gpu

### ISSUE THREAD

**Issue by tiagowski** [nicehash/NiceHashMiner#1185]
Hello

I am having problems using 13 gpu amd rx 580 4gb (6) / 8gb (7) cards in nicehash.

If I only connect 9 cards, they appear in the list, if I turn on it, there are none in the list to select.

I usually mine for single claymore.

Driver: version 18.4.1
Motherboard: ASUS B250 Mining Expert
Miner: Nicehash v1.9.0.1

How can we solve this problem?

Thank you

**Comment by ewislon1** [comment]
I was having lots of problems mining on 18.4.1 I would go back to 18.2.1. You can install 18.2.1 here- https://support.amd.com/en-us/download/desktop?os=Windows+10+-+64

**Comment by tiagowski** [comment]
This is not a driver problem but nice, as I use claymore usually with 13 gpu.

I can not change the cards for Computing in this old driver as it presents a bug in the AMD application preview.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
