### ISSUE TITLE
Chrome blocking download/Windows Anti Virus blocking

### ISSUE THREAD

**Issue by yada-yoda** [nicehash/NiceHashMiner#1186]
1.9.0.1 is being blocked for download by Chrome and Windows Anti-Virus is blocking it from running

**Comment by underway113** [comment]
yes, all the NHML version behave like this. just allow it.

**Comment by ivanfremn** [comment]
That is not true, the previous version doesnt trigger any virus warning, but 1.9.0.1 does, I am not using the new one because of that reason.

PD: Actually 1.8 is now triggering the warning too, that's weird, it never happened before.

**Comment by Crypto-Lord** [comment]
At one point it wasn't flagging every version of the NHML, but the last few versions it's been getting a flag. Nothing to be concerned about, just have to manually allow the download and make exclusions in whatever AV software your running.

**Comment by snowcrawl** [comment]
It is necessary to click "save as", then add it to a folder which you have already added to your security exclusion list.  Also, then add the newly unzipped Nicehash legacy folder your to your list of threat exclusions.  Then when the download has finished, you need to go into the download section of Chrome and sepecify that you want to keep the "dangerous" file.   Another work around would be to download it using a different browser.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
