### ISSUE TITLE
REQ: Plz add auto start mining delay for xx seconds.

### ISSUE THREAD

**Issue by lmlim** [nicehash/NiceHashMiner#1187]
Hi NH team,

I have a small request on NHML options, ie add "delay xx seconds" in the already in exist option auto start mining. also be able to stop/cancel the count down timer before it actually start mining. ( count down in start button maybe???) 

sometimes i do not want it to start mine right after NHML launched or start w/ windows.

thanks.

===Martin

**Comment by abixalmon** [comment]
Go to C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp

Create a Startup File
```MINE.BAT```

```BAT
TIMEOUT /t 30
START C:\Users\UserName\Desktop\NHML\NiceHashMinerLegacy.exe
EXIT
```

**Comment by lmlim** [comment]
@abixalmon thanks... it works.

**Comment by nerdatwork** [comment]
If it worked then please close this thread. @lmlim
