### ISSUE TITLE
1.9.01 Legacy ExtraLaunchParameters for CryptoNightV7 XmrStak

### ISSUE THREAD

**Issue by yada-yoda** [nicehash/NiceHashMiner#1188]
Have you come across in v1.901 legacy that CryptonightV7 takes over the normal Cryptonight XrmStak and Xmrig and wiped your parameters? I copied over my old config and it did not transfer over. Was curious if the intensity extra launch parameter still works of "--threads=1" and since "less threads" is no longer an option but "power consumption" is, curious what you have down for those as I don't want my CPU at 100% all the time.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
