### ISSUE TITLE
not detect any amd rx580 gpu

### ISSUE THREAD

**Issue by namnguyendsn** [nicehash/NiceHashMiner#1191]
in windows 10 64bit build 1709 system.
i have tried several amd driver ( 17.11.4, 17.11.2, 17.11.1, 17.10.1, 17.10.3, and blockchain beta driver) but nicehash still not detect any card.

i tried compare my logs with run ok log like image here. (left hand is run ok,)
![image](https://user-images.githubusercontent.com/5857744/40287970-f9bc6e76-5ceb-11e8-82bf-eeb13fe5da63.png)
 
![image](https://user-images.githubusercontent.com/5857744/40288006-30e5bd08-5cec-11e8-8476-5b01f6684f83.png)

i don't know why. pls help

many thank
sorry for my english

**Comment by Callah91** [comment]
Have you disabled AMD detection in the "settings" page?
Did older Versions of Nicehash find Your AMD GPUs without an issue? If so please try and delete the "config" file and run the newest Version of Nicehash Legacy "as is" to identify if there is a settings issue.

**Comment by namnguyendsn** [comment]
thank for reply.
i dowloaded lastest nicehash and used all default setting.
i tried both nicehash 1.8.5 and lasted version, nothing change.

update. in Update history-> Driver update has
"advanced micro devices, Inc. driver update for radeon rx 580"

i think the rootcause here, but i don't know how to remove it

**Comment by CheroulamNab** [comment]
Pretty much the same issue my RX 580 wont show up also. My CPU shows up fine but my RX 580 just refuses to show. I am tried rolling back drivers and such and the same issue is present.

**Comment by Creativenauts** [comment]
same issue, rx 580's not showing...

**Comment by namnguyendsn** [comment]
use DDU and uninstall intel graphic driver.

done

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
