### ISSUE TITLE
Issue of windows 1.9.0.1 (double-triple mining, gpu has not detected)

### ISSUE THREAD

**Issue by ALTERNATIVAArtem** [nicehash/NiceHashMiner#1193]
Пожалуйста, помогите решить проблемы, возникают на разных ПК:
1 проблема: Периодически двоятся окна майнинга на версии 1.9.0.1 после чего скорость майнинга падает и иногда происходят вылеты в BSOD, после остановки приложения, задвоившееся окно не закрывается, даже если закрыть майнер полностью. Как устранить данную проблему?
2 проблема: Еще 1 проблема, иногда после перезапуска ПК не обнаруживается видеокарта и майнинг запускается только на ЦП, версия так же 1.9.0.1, на старых версиях такое тоже было.

===================================

Please help to solve problems, arise on different PCs:
1 problem: Periodically the windows of mining are split in version 1.9.0.1 after which the speed of mining falls and sometimes departures to BSOD, after the application is stopped, the docked window does not close, even if the miner is completely closed. How to fix this problem?
2 problem: Another problem, sometimes after restarting the PC, the video card is not detected and the run is only run on the CPU, the version is also 1.9.0.1, on older versions this was also.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
