### ISSUE TITLE
more than the sum of their parts (gpus on cryptonightv7) whats going on?

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#1195]
i was swapping cards around today........

i noticed that my gtx7704gb and my gtx 6602gb both running xmrstak v7 together was getting between 65-80p a day.

the gtx770 4gb by itself only earns 30p a day on xmrstakv7 b itself
the gtx660 only earns 15a day by itself.

whats going on here?

**Comment by jimmyhackers** [comment]
too add to this confusion my cpu (3770k) did about 30-40p a day by itself. the gtx770-30-40p  day by itself. together (linked with xmrstackv7) they are doing £1.20-£130.

im happy its doing it but im still not sure why its doing it

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
