### ISSUE TITLE
CPU and GPU do not work together in Legacy 1.9.0.1

### ISSUE THREAD

**Issue by Leonyxtested** [nicehash/NiceHashMiner#1196]
Good, I'm having problems using two GPUs, both are AMD, when I put them to work only one mine but intermittently and the other one stops, the same thing happens if I put the CPU and a GPU, the CPU does not work and the GPU intermittently. I reinstalled the drivers but it still doesn't work. I leave you with all the system information, the software version is Legacy 1.9.0.1.

Radeon Software Version - 18.4.1
Radeon Software Edition - Adrenalin
Graphics Chipset - Radeon RX 560 Series
Memory size - 4096 MB
Memory Type - GDDR5
Central clock - 1216 MHz
Windows version - Windows 10 (64 bit)
System memory - 8 GB
CPU Type - AMD Ryzen 3 1300X Quad-Core Processor

The second GPU:

Graphics Card Manufacturer - Powered by AMD
Graphics Chipset - AMD Radeon R7 200 Series
Bus Type - PCI Express 3.0
BIOS version - 015.048.000.050
Memory size - 2048 MB
Memory Type - DDR3
Memory clock - 800 MHz
Central clock - 780 MHz
Total memory bandwidth - 25 GByte/s
Memory bit rate - 1.60 Gbps

Configuration version of Radeon - 2018.0425.4.41502
Driver Pack Version - 18.10.01.05-180424a-327684E-RadeonSoftwareAdrenalin
Supplier - Advanced Micro Devices, Inc.
2D driver version - 8.1.1.1.1634
Direct3D® Version - 9.14.10.01334
OpenGL® Version - 6.14.10.13521
OpenCL™ Version - 24.20.11001.5003
AMD Mantle version - 9.1.10.0254
API Version AMD Mantle - 102400
AMD Audio Driver Version - 10.0.1.6
Vulkan™ Driver Version - 2.0.20
Vulkan™ API Version - 1.1.70

If you need more information, I'd be happy to give it to you, thank you.

**Comment by kaiserc** [comment]
I have the same problem and Other have also https://www.reddit.com/r/NiceHash/comments/8l6sql/cant_mine_since_win_10_update/
I not so sure if its the windows update but I'm earning half as much. Ryzen 1700 & RX 480 8GB. My CPU continuously mines but my GPU mines for a short while then goes straight down to 0 h/s,  it then mines again or sometimes restarts the miner.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
