### ISSUE TITLE
OpenCL issues after Windows Update

### ISSUE THREAD

**Issue by foriegninsect2** [nicehash/NiceHashMiner#1199]
After the new windows update my 5 XFX 4GB RX570 are not reconciled by nicehash. If I run three it will detect them. Four cards and I start running into lag issues. I I add a fifth the cards are not recognized at all. I am in GEN2 in my bios and it was working with no issues prior to the windows update. PLease help!?!?!

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
