### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner#12]

**Comment by billmcilhargey** [comment]
Yes Thank YOU!~!!!

There is no good spot to add this but this is what a lot of the advanced miners have been waiting for!!!!!!!


So while this form will show issues (as thats the point) know we gladly appreciate the work contributed to this software (and nice hash services)!!!!!!

**Comment by navjack** [comment]
yeah, this should be an open issue for a while so we can all send our thanks! :-P

**Comment by DillonN** [comment]
Thanks everyone for the support!

**Comment by tmslacker** [comment]
I wanted to show Appreciation to the Developers and the Supporting Community!  Let's Make Money, have Fun and Make this a Project to Talked About!

**Comment by billmcilhargey** [comment]
Yes!  One way to help is spread the word!  the more people that use it the more fees go to NiceHash and hopefully they spread down the wealth to the developers/contributors too :)

As of the initial release:
Also just to document it looks like each miner included in the 3rd party and regular bins all benchmark (using Precise)!  (does not necessarily mean each one fully mines, but if a user reports that one doesn't benchmark and a new miner hasn't been released then might be an issue with the user's pc)

**Comment by tmslacker** [comment]
I've used NiceHash for 9ish Months.  I post only for myself.  I do not mind sharing my take to help the developers and contributors.  Where can we gift coin to support the team that supports us?  Much Love Dave!

**Comment by Cryptominer937** [comment]
Thanks DillonN this miner is far more stable that the V2 releases I have lost over 3 days of mining on V2 due to excavator server bugs but V1.8 is rock solid and actually a little more profitable.

**Comment by francescocmazza** [comment]
Yes, thank you!!

**Comment by tmslacker** [comment]
You get an update and you get an update!  It nice to see updates again.

**Comment by tmslacker** [comment]
Thank You for help with my build question!  Nice!  DillonN!
