### ISSUE TITLE
Miner will only engage 1 GPU if 2 selected by default. checkmarks need to be disabled  and enabled again for it to work

### ISSUE THREAD

**Issue by ferdreyfus** [nicehash/NiceHashMiner#1200]
# Only one GPU of 2 total selected will start mining (GPU 1) when starting from not mining, or autostarting the computer.

### Version Legacy v1.9.0.2

In order for both GPUs to start Mining Lyra2RE v2, the GPU that was working is deselected, mining process then has to start, then stop, then select the GPU previously unselected, and then both GPUs start working.

2x ASUS 1070ti Cerberus-
FX 6300 Processor
LAtest Version Windows 10 

Nvidia Drivers 397.64

**Comment by Novicracker** [comment]
this sounds like a driver issue. I would uninstall the drivers and do a
clean install. make sure to uninstall them in safe mode. and use Display
driver uninstaller.

**Comment by ferdreyfus** [comment]
Suggested solution worked. thanks.
