### ISSUE TITLE
ADL power error code in debug console during benchmarking, no error following benchmarking

### ISSUE THREAD

**Issue by M3dicine** [nicehash/NiceHashMiner#1203]
Hello,

Hardware: 1600x CPU, Vega 56 GPU
Software: WIN10 Home 64bit, version 1803, AMD Driver version 18.3.4

I was getting this repeating error code in the debug console after updating to NHML 1.9.0.2 from 1.9.0.1: "[ADL] ADL power getting failed with code -1" during the benchmarking process only.

I did not experience crashing or any other known issue during benchmarking, and the "code -1" was not present following benchmarking.  It seems related to the AmdComputeDevice.cs file & related to the following code:

        public override double PowerUsage
        {
            get
            {
                var power = -1;
                if (_adlContext != IntPtr.Zero && ADL.ADL2_Overdrive6_CurrentPower_Get != null)
                {
                    var result = ADL.ADL2_Overdrive6_CurrentPower_Get(_adlContext, _adapterIndex2, 1, ref power);
                    if (result == ADL.ADL_SUCCESS)
                    {
                        return (double) power / (1 << 8);
                    }
                    if (result != ADL.ADL_NOT_SUPPORTED)
                    {
                        // Don't alert if not supported
                        Helpers.ConsolePrint("ADL", "ADL power getting failed with code " + result);
                    }
                }

                return power;

**Comment by Perseverate** [comment]
See AMD Driver Library error codes.
https://github.com/GPUOpen-Tools/common-lib-amd-ADL/blob/master/include/adl_defines.h
