### ISSUE TITLE
GetSummary exception: No connection could be made because the target machine actively refused it 127.0.0.1:4000

### ISSUE THREAD

**Issue by vietpham87** [nicehash/NiceHashMiner#1205]
I got Exception while running Nichehash 19.0.2 , for more details please refer to log file below.
Claymore cannot run and it's make computer hangs and restart. I try to change API port but the exception still occurred. 

[Nicehash.log](https://github.com/nicehash/NiceHashMinerLegacy/files/2042214/Nicehash.log)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
