### ISSUE TITLE
Помогите решить ошибку ccminer.exe 0xc000007b

### ISSUE THREAD

**Issue by Rogvold2la** [nicehash/NiceHashMiner#1207]
Помогите решить ошибку ccminer.exe 0xc000007b при запуске майнера в найсе LYRA2rev2

**Comment by Rogvold2la** [comment]
![unnamed](https://user-images.githubusercontent.com/39773163/40733092-8a5f305a-643d-11e8-9581-36ad5298fd2b.jpg)

**Comment by anvk77** [comment]
Мне помогло установи vc_redist.x86.exe 2015 ну или 2013 мне помог 2015,лира 32 битная

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

New version has this fixed.

Please use English on GitHub
