### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by SirHanck** [nicehash/NiceHashMiner#121]
Hello, there is a problem with nicehash not connecting, it starts normal but then when it tries to start the mining windows they shut down or hang trying to reconnect.
this issue started today around 12:00 GMT,
I have a gtx 1070 and a gtx 660 that were working through the morning till noon, I was using the 1.8.0.2 when the problem started, then I tried the new 1.8.1.0 pre2 but the same problem occured.
this log is from v1.8.0.2
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1200537/log.txt)

this log is from v1.8.1.0 pre2
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1200526/log.txt)

can you look into this please?

**Comment by SirHanck** [comment]
Ok, changing the server from Europ to USA seems to have solved the problem, did anyone else have a similar issue or am I the only one?

**Comment by DillonN** [comment]
From your logs it looks like the right location is being passed to the miners, so for whatever reason they were unable to connect to NH servers. Hopefully sticking with a different server helps, but if you get it again in the future you can try without your firewall to see if it's blocking (then make exceptions). 

Was there any specific error in the mining windows that would suggest what was causing the connection to not work?

**Comment by SirHanck** [comment]
I am having a problem with my internet connection dropping many times today, some repairs are going on from the ISP, could that cause the server to reject the mining?
I am going to keep using the USA server for now, and no there were no error messages, the mining windows just restart (what I could read from them before they shut was something like "trying to connect"), Thank you anyway.

**Comment by SGTxGRIND** [comment]
I have a similar issue but with the 1.8.1.0-Pre4 version, on my main rig the benchmarking went fine and then i changed P0 state and restarted. Can't detect my internet connection. Unchecked P0 state and restarted and still cant find my connection. I also restarted my pc to no avail.

**Comment by DillonN** [comment]
@SGTxGRIND do you mean NHML itself won't connect? Could you post your log.txt?

**Comment by SGTxGRIND** [comment]
It magically fixed itself when i got gome from work. I couldnt connect to
the profitability servers thus preventing me from minimg most of the day
