### ISSUE TITLE
Save benchmark results after each algo completes

### ISSUE THREAD

**Issue by pomeara** [nicehash/NiceHashMiner#1210]
Hello,

I would like to request that after each algorithm completes it is saved rather than waiting until the end of all benchmarking.

I have on many occasions had the benchmarking crash for one reason or another and then had to run all the benchmarks again!

Many thanks - great software let's keep it improving!

**Comment by underway113** [comment]
Agreed. Takes time to benchmark from start again. if something error

**Comment by pomeara** [comment]
Update ... while running the new miner on my 5 systems two became unresponsive and I've had to start all over again!!!

I am in the habit of just stopping the benchmarking after it's done several algos, closing it and re-opening it as this has burnt me so many times

**Comment by pomeara** [comment]
Just updated and after crashing I have to run ALL algos again!!!! 

PLEASE, Can you save the bench-marking results after each algo so when a crash happens you dont have to run ALL benchmarks again.

**Comment by paulh69** [comment]
it would help if results were saved after each algorithm, if it crashes it probably hasn’t saved anything.  AMD devices are a real pain, they always get new IDs if the driver is updated or reinstalled.  At least nvidia can be moved to different slots or pulled without the need to repeat benchmarks.  
But probably not, they make all their profit from the benchmarking.  

How about it collects benchmark data and use defaults for each device without the need to run local benchmarks.  Or ask the developers, they must know the number of clock cycles between instructions to get exact benchmarks to the microsecond.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
