### ISSUE TITLE
Lyra2z CPU miner (cpuminer-opt) using all threads

### ISSUE THREAD

**Issue by mschemerii** [nicehash/NiceHashMiner#1214]
Using Nicehash Miner Legacy 1.9.0.3 with CPU mining Lyra2z on my Ryzen 1700X (8 cores/16 threads).
The miner is using 16 threads for mining.
I have added the option of "-t 8" to set this to 8 threads for better performance, but the miner still starts 16 threads. This makes my computer nearly unusable and loud (CPU cooler kicks in HARD).

How do I set this to only use 8 threads?

**Comment by LigerXT5** [comment]
Just inputting my 10cents, I've noticed the same thing on my i7 8700k. Caught me off guard hearing my CPU fan kick in. Had to take that miner off the list. Assuming mschemerii is doing the same as me, I let my computer mine while I'm not using the computer, same with my wife's.

I haven't started looking at how to cut back the thread usage yet, just updated late last night.

**Comment by pawelantczak** [comment]
Did you guys figure out how to limit cores number?

**Comment by LigerXT5** [comment]
I have not. I've been a tad tied up to look around.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
