### ISSUE TITLE
Extra Launch Parameters

### ISSUE THREAD

**Issue by davidskog** [nicehash/NiceHashMiner#1215]
'Extra Launch Parameters'? Can you see my attached screenshot? How is the syntax for this? It doesn't work, I can see in Task Manager that the command line for starting this miner does not include my extra parameters! Should I add a space or...? Pls help!

![elp](https://user-images.githubusercontent.com/23310270/40833719-03baacde-658f-11e8-8048-bd1ac7c1fb0c.jpeg)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
