### ISSUE TITLE
[Feature] Set times not to mine

### ISSUE THREAD

**Issue by LigerXT5** [nicehash/NiceHashMiner#1216]
I've been thinking of doing the following in TaskScheduler, however I thought a feature request would be a good start before I move to that.

My electric company is doing this (annoying) thing called Smart Hours, where between 2pm and 7pm, the cost of electricity is about two to sometimes three times higher. This is during the summer, starting today.

I was going to setup something in task scheduler to force close NHML if caught running between 2-7pm, and launch it when it is not. I would rather the miner to know times to allow mining, or not mining, what ever is easier, and let it run in the background.

I have mine set with the normal electricity cost per hour, but with the fluctuating costs in the middle of the day, it makes it troubling.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
