### ISSUE TITLE
CUDA Error Message

### ISSUE THREAD

**Issue by xozus1** [nicehash/NiceHashMiner#1217]
Getting an error in .3 that I did not see in .2:

Error gpu 4: <C:/Users/Dillion/source/repos/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:312

Thoughts?

**Comment by Kastor83** [comment]
I'm getting something similar on an Nvidia rig if I select any combination of more than one GPU.  Rig has 6 cards, 4 Pascal, 2 Volta.  AMD rigs don't seem to be effected.  Had no problems benching the algo.  The miner  \bin\xmr-stak\xmr-stak.exe  is looking for a path on Dillon's machine.  The path doesn't seem to be in any user adjustable config files.

Specific error: [CUDA] Error gpu 1: <C:/Users/Dillon/source/repos/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:312  

**Suggestion: reduce value of attribute 'threads' in the NVIDIA config file.**

**Comment by Kastor83** [comment]
Correction - not an inherent Nvidia issue.  I have a rig with same hardware using 1070s instead of Titans and I'm not getting the error there.  Maybe a driver or Win10 build# issue?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
