### ISSUE TITLE
Lyra2z CPU benchmarking fails for Intel Core i5-3470

### ISSUE THREAD

**Issue by qwertydog** [nicehash/NiceHashMiner#1219]
[Log_GEN-8ee6520528daff25052a38c67405c94ea1f5d736b8652ad2d302e2c73b0d0b00_cpuminer_Lyra2z.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2064714/Log_GEN-8ee6520528daff25052a38c67405c94ea1f5d736b8652ad2d302e2c73b0d0b00_cpuminer_Lyra2z.txt)

NHML version: 1.9.0.3
Windows version: Windows 10.0.17134 Build 17134
CPU: Intel Core i5-3470

CPU Benchmarking fails for new Lyra2z miner using cpuminer-opt with CPU Intel i5-3470

Intel i5-3470 is Ivy Bridge generation and doesn't support AVX2

Fixed benchmarking by deleting the existing cpuminer.exe, then renaming cpuminer-avx.exe to cpuminer.exe

Probably need to query which CPU features are supported and then rename the relevant miner (e.g. in my case cpuminer-avx.exe) to cpuminer.exe

**Comment by nazzier5463** [comment]
Mine too, i have various version of i7 cpu, some of then wont benchmarks for lyra2Z. The program freeze after failed to benchmarks

**Comment by leshiy-gr** [comment]
I have same problem

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
