### ISSUE TITLE
ccminer - blake2s crashes after 1min

### ISSUE THREAD

**Issue by utc99** [nicehash/NiceHashMiner#122]
After lunch ccminer blake2s algorithm works for about 1 minute, shows speed and looks good, and then it crashes and NHML app starts showing abnormal payouts and does not recover until manual relaunch. Same on NHML 1.8.0.2 and 1.8.10.0 pre 3.
![blake1](https://user-images.githubusercontent.com/26816096/28994124-4009c316-79cf-11e7-8e20-a98c304ab8af.JPG)
![blake2](https://user-images.githubusercontent.com/26816096/28994129-44f141b0-79cf-11e7-8f13-076f18a82b7e.JPG)

Log shows errors:
[2017-08-05 10:43:40] [INFO] [NVAPI] Load get failed with status: EXPECTED_PHYSICAL_GPU_HANDLE
[2017-08-05 10:43:40] [INFO] [NVAPI] Temp get failed with status: EXPECTED_PHYSICAL_GPU_HANDLE
[2017-08-05 10:43:40] [INFO] [NVAPI] Tach get failed with status: EXPECTED_PHYSICAL_GPU_HANDLE

I would prefer to run this on some weak gpus it would be great to fix this

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1202263/log.txt)

**Comment by UselessGuru** [comment]
This could be caused by high intensity. Try lowering it. To to this go to 'Settings' -> 'Devices/Algorythms' -> 'Blake2s' and add an 'extra launch parameter' "--intensity=n" (where n can be set from 1 (low) to 31 (high)).

**Comment by utc99** [comment]
Yes you are right, it's because of incorect default intensity
