### ISSUE TITLE
v1.9.0.3 Legacy bin file missig .exe

### ISSUE THREAD

**Issue by DanielCorzo** [nicehash/NiceHashMiner#1220]
v1.9.0.3 Legacy bin file missig .exe file
I spent hours setting this up and running all aspects in precise mode, then when the system rebooted it did not have an executable file on it.  Neither did the previous version as well so I'm back to using v1.8.1.10

**Comment by peteycrack420** [comment]
i had that problem before   i got so tired of it i just reinstalled windows

**Comment by nazzier5463** [comment]
@DanielCorzo have you check your AV quarantine ? Try to check Window Defender quarantine, always blocked nicehash files.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
