### ISSUE TITLE
Lyra2z on AMD

### ISSUE THREAD

**Issue by deeppurple1968** [nicehash/NiceHashMiner#1221]
ENG (Google translate):

How to make the Lyra2z algorithm work on my AMD FX-8300 processor? I can not even pass the benchmark. The benchmark does not even have time to start, the message pops up: "Not all tests were successful, try to restart the benchmark for algorithms that have not passed it, or Cancel to disable these algorithms."

RUS:
Как заставить алгоритм Lyra2z работать на моём процессоре AMD FX-8300? Я даже не могу пройти бенчмарк. Бенчмарк даже не успевает начаться, выскакивает сообщение: "Не все тесты прошли удачно. Попробуйте перезапустить бенчмарк для алгоритмов, непрошедших его, либо Отмените для отключения этих алгоритмов."

**Comment by Simaex** [comment]
Check cpuminer directory. Check what cpuminerXXX-XXX.exe is the best for your CPU. Rename it to cpuminer.exe and enjoy.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
