### ISSUE TITLE
Lyra2z CPU miner and CryptoNightV7 can actually running simultaneously on Hyper thread CPU

### ISSUE THREAD

**Issue by indoorsNB** [nicehash/NiceHashMiner#1222]
I test running Xmr-Stak and Lyra2z at the same time on my Ryzen 1700, the Lyra2Z speed reduces to 0.300 MH/s but the cryptoNightv7 speed is still around 350h/s. I set Cryptonight to 1,3,5,7,9,11,13,15 core and the Lyra2Z as default
On 1,3,5,7,9,11,13,15 the lyra2Z speed is very low but on the 0,2,4,6,8,10,12,14 they still have a very high speed.
Is this possible to add a "Lyra2z+cryptoNightv7"?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
