### ISSUE TITLE
1.8.x & 1.9.x - not work skunk (ccminer) algo

### ISSUE THREAD

**Issue by leshiy-gr** [nicehash/NiceHashMiner#1224]
Benchmark passed, OK, speed is measured. But if you run - a constant restart with a short interval of time, in the window of the miner you see the text that the wrong parameter skunk. The help of the miner says that really skunk is not among the supported algorithms. But in fact the benchmark passes, maybe there is another miner used?
in log - 
 Starting miner [pid(3624)|bin(bin\ccminer_decred\ccminer.exe)] --algo=skunk

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
