### ISSUE TITLE
Lyra2RE v2 faster miner ?

### ISSUE THREAD

**Issue by cervajz1** [nicehash/NiceHashMiner#1225]
Hi, there is about 5% better performance with ccminer from alexis78.
I have with my setting on 1070Ti  44MHs with default nanashi version, but 46MHs with Alexis version.

For now i copy alexis ccminer.exe to folder with nanashi and it works, but some newer algos like Lyra2z, which using same file dont work, because alexis doesnt support them.

In these days is Lyra2RE more profitable then others, so is there posibility that in new version will be use faster miner ? (alexis78 or other which is faster ?)

**Comment by MaKCuMyC** [comment]
palginmod is little faster.

**Comment by AtlAntA118** [comment]
alexis78 is a lot slower on my 1080ti. Palgin is even slower than that. 55mh/s against 69mh/s.  This one gives me the best results, https://github.com/Nanashi-Meiyo-Meijin/ccminer_v2.2_mod_r2/releases

YMMV though

**Comment by cervajz1** [comment]
Thanks for tips guys. I tested all this miners, On 1070 and 1070ti is Alex78 best. Palgin and nanashi are 4-5MHs slower. Nanashi has other problem on some pools with "stale shares". Rigs report cca 700MHs, but pool and nicehash show 500MHs. With other miners this problem is gone and pool/NH reports right hashrate.

**Comment by AtlAntA118** [comment]
You are right. I tested the latest of the alexis78 ccminer. Now with the 1.0 version im hashing signifaicantly faster than the included ccminer. Im mining with 1x1080ti and 5x1070ti and 6x 1070 and the difference is pretty big. Thanks for pointing me in the right direction.

@DillonN Perhaps you can include this miner as an alternative for the nanashi miner? The best results are to be had with the 1.0 miner for lyra2rev2. https://github.com/nemosminer/ccminerAlexis78/releases

**Comment by S74nk0** [comment]
Not relevant anymore
