### ISSUE TITLE
Issue with Faulting module name: SSLEAY32.dll, 

### ISSUE THREAD

**Issue by minethecoins** [nicehash/NiceHashMiner#1227]
Faulting application name: ZecMiner64.exe, version: 0.0.0.0 . It will stay on for about 10 min and crash.  I did some updates recently. I did increase the paging file size to 10000 megabytes. Also power outage caused IRQ blue screen error 5 days ago. Thanks for helping out.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

ZecMiner64.exe is not relevant anymore
