### ISSUE TITLE
Watchdog errors on RX580.

### ISSUE THREAD

**Issue by murthydevarakonda** [nicehash/NiceHashMiner#1228]
Hello, I am running on 1.9.0.3 with two RX580 GPUs.  I am currently using blockchain drivers by AMD for these GPUs. I have been receiving watch errors on both GPUs and system crashing every couple minutes.  Windows complain about driver power state failure.  I rebuilt the whole system but still see the same issues.  I want to file a bug on this.  Please let me know what other information you need to look into this bug.  I checked the logs under log folder and nothing was noted about the hang and reboot.

**Comment by styelz** [comment]
Hi @murthydevarakonda you can upgrade from the BETA AMD drivers to their latest 18.5 driver now.. They have added an option on the AMD Settings panel under Gaming ->> Global Settings, to allow you to change the GPU Workload from "Gaming" to "Compute". This gives the same mining speeds as the BETA Blockchain driver, which is pretty cool. Anyway, see if that fixes your issue...

**Comment by murthydevarakonda** [comment]
Hello, thanks for the reply.  I tried the latest drivers with the setup mentioned above also.  I still see the issues.  I tried standalone ethminer and the system did not crash.  Do you think something changed in Nicehash or Windows 10 or AMD drivers to introduce these crashes?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Looks like AMD driver issue
