### ISSUE TITLE
cryptonightv7.eu.nicehash.com:33363 direct?

### ISSUE THREAD

**Issue by dadoremix** [nicehash/NiceHashMiner#1229]
HI 
can someone help
i want mine direct with claymore 11.3 miner 
to cryptonightv7.eu.nicehash.com:33363 SSL connection

but on site of nicehash i find only these
cryptonightv7.eu.nicehash.com:3363 adress
and there is high ping
on 33363 port via nicehash app .. is normal ping, but if i put that adresss in my config, not working

config is here

-xpool cryptonightv7.eu.nicehash.com:33363
-xwal 35bjUBvwQRnDX2E4H9xTkBwWYZwHbyKU2H.Asus
-xpsw x
-pow7 1
-tt 55
-fanmin 35
-fanmax 90
i try also with

-xpool stratum+tcp://cryptonightv7.eu.nicehash.com:33363

3363 port is unsecure
33363 port not working 
but is working if i run via nicehash app

**Comment by nazzier5463** [comment]
As far i know, mining doesnt need high speed internet, as long youre connected, youre good to go, your hardware is determine your profit, not your ping or internet speed.

**Comment by ibiza007** [comment]
-xpool stratum+ssl://cryptonightv7.hk.nicehash.com:33363

**Comment by dadoremix** [comment]
TNX

2018-06-11 21:22 GMT+02:00 ibiza007 <notifications@github.com>:

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
