### ISSUE TITLE
NHML doesn't start with 6 AMD + 6 nVidia cards at Win10 x64

### ISSUE THREAD

**Issue by hashbolic** [nicehash/NiceHashMiner#1231]
I have a rig with 12 GPUs (6 AMD + 6 nVidia. m/b Biostar TB250-PRO BTC, os Windows 10 x64 1603 LTSB, RAB 8Gb, swap about 80 Gb - works flawlessly with any miners. 
Just tried NHML 1.9.0.3 and few older versions - it doesn't start. Nothing happens - no errors, anything. Tried to start from cmd console - the same result, but it made config and log folders. I tried to disable detection both AMD and nVidia cards in the config. In log.txt - strings about languages and so on and no any errors.
How can I get any clue what is wrong?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
