### ISSUE TITLE
how can I choose the number of cores of CPU to be used in (nhm_windows_1.9.0.3)

### ISSUE THREAD

**Issue by MuriloGava** [nicehash/NiceHashMiner#1233]
I need help!!

how can I choose the number of cores of CPU to be used in (nhm_windows_1.9.0.3) ""xmrig.exe"" ?

Ex: local...  folder \configs\benchmark_GEN- ........
"AlgorithmSettings": [
    {
      "Name": "XmrStak_CryptoNightHeavy",
      "NiceHashID": 30,
      "SecondaryNiceHashID": -1,
      "MinerBaseType": 15,
      "MinerName": "",
      "BenchmarkSpeed": 321.2125,
      "SecondaryBenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": "",
      "Enabled": true,
      "LessThreads": 2,
      "PowerUsage": 0.0
    },

*"LessThreads": 2,*... a value, greater than 0 (1 = leave 1 thread unused, 2 = 2 leave 2 threads unused, etc.). 

in the previous version worked, in xmr-stak-cpu.exe 
but now directly activates the * xmrig.exe * miner that does not accept the configuration

**Comment by professor-jonny** [comment]
edit the cpu.txt in the folder with xmr executables, the below will set four cores in operation as an example.

```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0},
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1},
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2},
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3},

],
```

xmrig is totally different

**Comment by MuriloGava** [comment]
**professor-jonny... thanks!**
xmr-stak_heavy end xmr-stak accept this configuration. cpu.txt...
but **xmrig** does not find the place to configure.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
