### ISSUE TITLE
NHML 1.9.0.3: Lyra2Rev2 benchmark fails on Titan V

### ISSUE THREAD

**Issue by chara1ampos** [nicehash/NiceHashMiner#1236]
The benchmark for Lyra2Rev2 and other algorithms fail (terminate) on the Titan V.
This did not happen with earlier versions (1.8.x.x) of NHML.

Specifications:
NHML 1.9.0.3
Windows 10
Nvidia Titan V

**Comment by nazzier5463** [comment]
update nvidia driver

**Comment by chara1ampos** [comment]
I have the latest drivers

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
