### ISSUE TITLE
[Feature] Show GPU PCI-E bus on nicehash's legacy main GPU list 

### ISSUE THREAD

**Issue by grassoosvaldo** [nicehash/NiceHashMiner#1237]
Nicehash legacy should show the current pcie-bus for each GPU into the main list (settings and benchmark)
it's an useful feature to
- to detect gpu problems and isolate
- disable due to malfunction or use custom configurations (allowed but not easy to find the correct card) 
- select some cards to mine something different (not necessary at all)
- currently it's hard to differentiate between cards 

E.G.
GPU#1 Radeon RX 580 Series (bus 1:0:0)

however, right now, you could see the same information in claymore-miner but gpu indexation is not direct (e.g Claymore's GPU0 (bus 1.0.0) its associated to GPU#8 from nicehash miner main list)

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMiner/commit/c8896f4bc49c74023286da742fe9e7b064114c60) implements this feature.

Will close issue on next release.

**Comment by grassoosvaldo** [comment]
Great!
