### ISSUE TITLE
detected 3 CPU instead one

### ISSUE THREAD

**Issue by phant** [nicehash/NiceHashMiner#1238]
![2018-06-11_11-51-50](https://user-images.githubusercontent.com/805222/41216660-ac2ba88c-6d6e-11e8-8db2-ccb940605ff8.png)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2088937/log.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
