### ISSUE TITLE
NHML 1.9.0.3 attempting to create miner instance while there are active instances

### ISSUE THREAD

**Issue by BrianTheDreamer** [nicehash/NiceHashMiner#1239]
I have 2 GPU's in my gaming rig. GTX 1060 and GTX970. After mining for a while (~6 hours), NHML would try to create a zcash miner (zm) instance for both GPU, but would fail due to "cudaMalloc failed" error, most probably because the GPU's are actively mining another algo. The failed zm will close, but would try again and again, looped indefinitely. Stopping the miners via the Stop button will stop the other miners but not the looped zm instance. The only time it will stop is closing the NHML entirely.

Screenshot: 
https://www.dropbox.com/s/b1h9gjx8xvlkz1v/Screenshot%202018-06-12%2014.59.04.png?dl=0

Windows 7 64-bit Ultimate SP1
GTX 1060 (6GB) and GTX 970
Nvidia Driver Version 398.11
NHML 1.9.0.3

Update: GTX 970 seems to be causing the error. I rolled back its driver to older version and problem seems to not occurring anymore so far. But I still think the indefinitely looped restart mechanism of the miner is in NHML. Sorry I can't help with finding where it is in the codes. I understand that the gpu's/driver has to be in perfect condition so if this is so minor/isolated case, we can close this issue.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
