### ISSUE TITLE
sgminer benchmarking issue

### ISSUE THREAD

**Issue by scavern** [nicehash/NiceHashMiner#124]
When benchmarking an algo for the first time, sgminer generates a binary for the gpu.  Sometimes the benchmark will fail because of the time required to generate the binary. If the benchmark is run again it will run as normal because the  binary has already been created.

Can the benchmark for sgminer be configured to run twice in the event that it fails the first time?

I think Nicehash2 got around this by actually running it twice.

Thanks

**Comment by DillonN** [comment]
Thanks for pointing this out, I will look into it
