### ISSUE TITLE
Hashes drop in half

### ISSUE THREAD

**Issue by chuckforis** [nicehash/NiceHashMiner#1240]
Hello NiceHash,
I have a problem with nicehash all my AMD GPUs, in all algorithms DaggerHashimoto solo and dual mining. The problem is that the hashes drop in half all of the cards. For example my RX 580 from 30 Mh/s that it was drops down to 17 Mh/s. Also my Vega 64 from 42 Mh/s drops down to 22 Mh/s after about a minute i begin the mining or when making bechmarking the cards.
My parameters/specifications:
-NiceHash Legacy v. 1.9.0.1, v. 1.9.0.3
-Server EU
-ASUS ROG STRIX 580 8GB, GIGABYTE VEGA 64 8GB
-Windows 10 Pro x64
Also tryed manually with Claymore Miner v. 11.7 on the NiceHash servers with the following settings in the bat file mono and dual mining:

Mono Mining Settings:
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

EthDcrMiner64.exe -epool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 -ewal MyNiceHashWallet -epsw x -esm 3 -allpools 1 -estale 0 -platform 1

Dual Mining Settings:
 setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

EthDcrMiner64.exe -epool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 -ewal MyNiceHashWallet -epsw x -esm 3 -allpools 1 -estale 0 -dpool stratum+tcp://blake2s.eu.nicehash.com:3361 -dwal MyNiceHashWallet -dpsw x
-platform 1
Same error.
[NH.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/2095034/NH.zip)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
