### ISSUE TITLE
CryptoNight (XmrStak) crash after stop

### ISSUE THREAD

**Issue by UAVXP** [nicehash/NiceHashMiner#1241]
CryptoNight (XmrStak) is working fine, but when I stop mining - it crashes my video driver.
I have Sapphire NITRO R7 360 2048GB - https://www.techpowerup.com/gpudb/b4394/sapphire-nitro-r7-360

**Comment by UAVXP** [comment]
Oh, and also the CryptoNight Heavy one doing it too

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
