### ISSUE TITLE
Some bugs version 1903

### ISSUE THREAD

**Issue by Giulio1974** [nicehash/NiceHashMiner#1244]
Please i have found this ( that for me is a bugt ) :
- In che Claymore cryptonigt v7 setting , the miner do not take the extraparameter
- When you setting consumation watt for vga and set also the current cost , in the mining application global rate now report the ( Rewards-cost = profit rate) and i think is not correct , maybe is better show the correct daily rate and add a the profit rate in another part ... on the web the rate it is always the same if you put or not the current cost show alway the Rewards and not the profit

Giulio

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
