### ISSUE TITLE
Issue with 1.9.0.3 XMRIG Terminates on Bench 1950x. 2nd gpu benches but doesnt mine...

### ISSUE THREAD

**Issue by papaskyfox** [nicehash/NiceHashMiner#1246]
I just wiped my computer fresh and started getting my normal things put together. Download Nicehash Legacy, got my benchs going but on my CPU XMRIG terminates without even trying. I have locked pages enabled higher vram and I can't seem to fix it. 

Also, my 2nd 1080ti doesnt seem to mine after it benches. It shows "One gpu" mining eventhough both are checked. I even tried it on only one algo, samething. NHLM Was working great before I wiped the pc. 

Any suggestions?

1950x
1080ti (2)
64GB RAM
64GB Virtual memory.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
