### ISSUE TITLE
Issue with AMD RX 480 and Legacy Miner 1.9.0.3

### ISSUE THREAD

**Issue by Frustrat** [nicehash/NiceHashMiner#1247]
Hi guys.       

First, the nature of the problem: I added a new RX480 to my desktop. I   installed the latest drivers and the latest legacy miner. Once I started   benchmarking it, the whole system crashed. I did this repeatedly, it crashed   every time. I tried running individual benchmarks, it crashed again.      

My system:       CPU: Intel Core i7-6800K @3.4 GHz (no overclock)   RAM: 24 GB of DDR4 (2x8 + 2x4)   MB: Alienware 0FRTKJ   Primary GPU: GeForce 1080, 8 GB (no overclock)   Secondary GPU: AMD RX480, 8 GB (the new addition, no overclock)   OS: Win10 x64 Home Edition   PSU: 1500 Watt   HDD: SanDisk Ultra 2 960 GB SSD   All drivers fully updated.      

I saw on Reddit some posts from 2016 and 2017 that people had the same   problem and, at some point, someone from Nicehash said they were working on   it. I also saw some advice regarding this problem, disabling all algorithms   except DaggerHashimoto and Equihash, while disabling the AMD optimisations in   the settings. I tried this, it didn’t work. So far, I haven’t been able to   either benchmark it or use it for mining. To clarify, the card works well   when not mining. I tried watching HD videos and gaming at full settings on it   and it has no problem.

**Comment by Frustrat** [comment]
SOrry for the bold part, I am new here and may have messed some formatting :(

**Comment by ScorpiosConsulting** [comment]
Having the same issue here on some of my mining rigs. 
Windows 10 Pro 64 bit Version 1803 Build 17134.112
Intel Celeron CPU G1840 @2.80GHz
8.00 GM Memory
5x AMD RX570 Drive Version 24.20.11016.4 (Tried various version of AMD Drivers currently on 18.5.1)
Tried to go back to previous version of NiceHash (1.9.01, 1.8.1.11, 1.8.1.4) without success

[log_bak.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2135416/log_bak.txt)

**Comment by ScorpiosConsulting** [comment]
Latest Windows update appears to have fixed the issue for me.
Just updated to latest CU for Windows 10 OS Build 17134.137 
and NH is detecting my AMD GPUs again.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
