### ISSUE TITLE
usd/day not showing up in nichhash legacy 1.9.0.3

### ISSUE THREAD

**Issue by gysnst2** [nicehash/NiceHashMiner#1248]
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by dark8899** [comment]
Same here!

**Comment by littlerigbibtrouble** [comment]
Same for me on 2 different computer. Start yesterday the 16 June 2018.

**Comment by mjbrocko** [comment]
same on 3 pc for me

**Comment by CryptoBen2018** [comment]
I just installed NH Legacy v1.9.0.3 yesterday, fresh clean windows 10 pro 64 bit build (yesterday, 16 June), and also see the USD/Hour is not working in the main window under "Group/Device Rates:"  I have played around with different settings, but I am mining Equihash algorithms for the moment.  We may need another update...Let me know if I can help with the troubleshooting at all.  I am getting the mBTC/Hour rate and the Speed just fine, but the USD/Hour on the right side is showing 0.00 for all of my Mining Devices.

**Comment by littlerigbibtrouble** [comment]
I was set in CAD (Canadian dollar) also on the NH web site. I reverted to USD on the web site and it reappeared but only on the site.

**Comment by falcon24c** [comment]
Same here. It was working fine for USD until 06/16/2018. The website is also not displaying the USD/Day, but is showing the correct USD balance.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
