### ISSUE TITLE
GTX1050 and 1060 crashing, only when both cards are mining

### ISSUE THREAD

**Issue by Krolow93** [nicehash/NiceHashMiner#125]
Hi!
First post so please understand if i forget to mention something.

The problem I'm having is that after mining for a little while my gtx 1060 will crash and be unresponsive. 
The crash will make my screen flash black and then NHML wont be able to mine on gtx 1060 or 1050. If i restart NHML at this point i will get a warning about old drivers and only the gtx 1050 will be found. It will start mining on the 1050 after the restart. 
I get the same problem with all versions from 1.8.0.1 and upp including 1.8.10 pre3. I get the exakt same problem with 1.7.5.13 and with 2.0.0.11. 
The only difference betwen the versions is that nicehash 2.0.0.11 will manage to get the 1050 runing again on its own and just stop mining on the 1060.

Sometimes it can run for seweral hours, other times it will crash within minutes. 
I always have to restart the pc for the graphics drivers to restore.

Specs

- CPU I7-6700K
- Motherboard Asus Z170-A 
-GPU (1st slot) Gigabyte GTX 1060 WF 2X 3GB
-GPU (2nd slot) Gigabyte GTX 1050 WF OC 2GB
- Virtual memory is sett to 17000-20000MB sice
- Locked pages is enabled

What i have tried:
Uppdated bios to the latest version, 
Tried different versions of graphics drivers, currently running latest. 
Tried reinstaling Windows 10 x64. 
Tried different versions of Nicehash and NicehashLegacy

Attatching Log file and a screnshot of the claymore window runing the gtx1060 right at crash
Also a screnshot of the debug window just after a crash

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1202596/log.txt)
![namnlos2](https://user-images.githubusercontent.com/30755866/28997978-707c8b26-7a21-11e7-9b99-05a5d41aea85.png)
![namnlos](https://user-images.githubusercontent.com/30755866/28998013-dc804e66-7a21-11e7-8d0f-e25677deceee.png)

Am i missing something or what is happening? 
Soo far i have only managed to see it crash if both cards are running at the same time.

**Comment by DillonN** [comment]
Hello @Krolow93, from what I can tell your 1060 is causing the drivers to become unstable and crash. When this happens, it can cause mining to not work until a reboot, and NHML will have an issue detecting card on startup. 

The crashes can be caused by many things, most commonly an unstable overclock/undervolt. There may also be hardware problems with the card or other components (notably power supply). 

Do you get the crashes if you use your 1060 to mine with other miners other than ClaymoreDual?

**Comment by Krolow93** [comment]
Hi @DillonN , That’s about what I expected as well.

I should mention that it used to be stable with all algorithms (except EWBF) until I did a reinstall of windows 10 x64, and changed boot drive to a m.2 nvme ssd from a normal sata ssd. Not that it should affect this from what I know.

My first guess was that my overclock was not working any more since I upgraded from sata ssd to m.2 . Therefore I went back to stock settings on everything for a few days but it continued anyway.
My PSU should not be the problem, I am running a Corsair RM750X that is about 6 months old, and what I understand there should still be power left with my two cards mining at max. And it also used to work

After some further testing this is what I have found out so far:
All tests are with the I7 mining in the background on its own
If the 1060 runs on its own, (all algorithms enabled) it will usually be running ClaymoreDual and it is rock solid. I haven’t tried to run it without ClaymoreDual disabled but I think I remember seeing it crash during another algorithm, I will have to investigate this
If the 1050 runs on its own it’s the same thing, no crashes and it will usually be running Equihash excavator (EWBF will make the 1060 “run out of DAG memory”). The 1050 is rock solid on it’s own ass well.
If I lock the 1050 to Equihash and let the 1060 do its thing it will crash, normally within an hour or two
I have tried locking the 1050 to Lbry with the 1060 mining mainly ClaymoreDual and for 24h now it has been rock solid again plus another 24h with my normal overclock to both cards. So I am suspecting one or more algorithms are crashing the drivers. But I don’t know why it would start now and not before the last reinstall.

I will try running the 1050 with all enabled (except EWBF, since I have the same problem as in #76 )
and running the 1060 with ClaymoreDual disabled to see what happens. 
Ofc with stock speeds on both cards

**Comment by Krolow93** [comment]
I tried runing without ClaymoreDual like you sugested and that made it stable aswell so i think you @DillonN had the right idea from the begining.
I have now updated NHML to 1.8.1.0 and it apears to have solved whatever was the problem from the begining.
I still cant run EWBF on 1050 tho but I'm hoping that can be solved in the future aswell

**Comment by Krolow93** [comment]
Allright, I was wrong
Uppdating NHML to 1.8.1.0 did not solve the problem, this is the latest log from when it crashed.
I might be wrong but does it not say that something is wrong with the cpu or am I reading the log wrong? This log is when runing all algorithms enabled except EWBF on 1050.

[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1220958/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1220959/log.txt)

I will try to run it again without ClaymoreDual but I would really like to get it functional
Any ideas of what more to try?

**Comment by Krolow93** [comment]
@DillonN  I think you had the right idea from the start about hardvare.
It apears that the 1060 that was causing issues had gone bad after les than 3 months. 
When I tried running the pc of it the whole screen was full of artifacts and the screen would freze instantly.
I have sent it back for warranty, and I am expecting to hear back about it in the next couple of weeks. 

I will therefore close this issue (or atleast try to, if i fail feel free to do it for me)

In the event that the issue precist when I get a replacement I will just start a new issue since it will be on another version of your software anyway
