### ISSUE TITLE
[Feature] advanced startup features

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner#1250]
ENG:
 in the settings -> device tab and algorithms, I would like to have two fields when selecting each algorithm - in these fields you can add commands (or command files). Two fields - one before running the algorithm's mining, the second after the completion of this algorithm's completion. These fields can be used for example for overclocking (at least I would use) through third-party utilities. For example, for eth mining on nvidia, it's best to overclock the GPU processor and reduce the memory frequency of the GPU - you can make one command through Nvidia Inspector. I tried to use the startup options built into the miners to overclock the GPU - but this does not always work correctly.

RUS:
в настройках -> вкладка устройства и алгоритмы хотелось бы иметь два поля при выборе каждого алгоритма - в этих полях иметь возможность добавлять команды (или командные файлы). Два поля - одно перед запуском майнинга алгоритма, второе после завершения майнинга этого алгоритма. Эти поля можно будет использовать например для разгона (по крайней мере я бы использовал) через сторонние утилиты.  Например для майнинга eth на nvidia лучше всего выставлять разгон процессора GPU и снижать частоты памяти GPU - можно сделать одной командой через Nvidia Inspector. Я пробовал использовать встроенные в майнеры опции запуска для разгона GPU - но это не работает всегда корректно.

**Comment by paulh69** [comment]
it may be possible to use MSI Afterburner profiles but not sure how reliable it would be if automated in some way

**Comment by foxwarernd** [comment]
there must be separate lines for running third-party programs on each algorithm for overclocking

**Comment by TaylorJayM** [comment]
This would be great. Then you can run different profiles in afterburner or OverdriveNTool based on what algo you're running.
