### ISSUE TITLE
Nvidia drivers being corrupted by NHLM and NHMV2  OR ?

### ISSUE THREAD

**Issue by Horsetoothless** [nicehash/NiceHashMiner#1254]
Current system is currently mining ok with windows 10, I7, on biostar  tb250 btcpro, rx560 main  display,
2, GTX 1050 pony cards, rx460, rx470, and does ok for hours , many configurations, NHLM and NHMV2 
used, but have had several blue screen crashes,video tdr fail Nvidiamkm.sys errors.
Sometimes corrupting the Nvidia driver files so they are seen as outdated or not there, 
reinstall  drivers to fix, 3 versions tried so far,397.55, 397.64, and 398.11 
all have been re clean installed several times! Will be trying to get some algo information as seems to occur at switching times.

Run away miner seen several times tries to restart  miners after stop commands and manual close windows. and extra excessive miners.

**Comment by paulh69** [comment]
nvidia drivers going away is usually overheating due to stuck fans or failed card or possibly algorithm is drawing too much power from the PCIE slots

**Comment by mves001** [comment]
Check pcie power cables and USB cables on risers ASAP !!! Also, possible PSU power shortage.
