### ISSUE TITLE
Got many rejected shares with XMR-STAK ....

### ISSUE THREAD

**Issue by electricdelicate** [nicehash/NiceHashMiner#1255]
.... and my RX Vega 64 and RX 480. Not due to overclocking failures but because of  "Job not found" and invalid nonce reasons. I lost with that always up to 5% of my shares. At least according the message. 
A counter test with CAST XMR looks very much better, with this I lost under 1% of my shares with even higher hashrates.

Use already the newest Legacy Miner 1.0.9.3 and that issue was already there in the older versions before. 

Is that normal?

![unbenannt](https://user-images.githubusercontent.com/40469299/41758131-e94490aa-75e6-11e8-9b71-00461448e02a.JPG)

**Comment by borzaka** [comment]
I have an extended statistics with XMR-STAK: #1257

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
