### ISSUE TITLE
Keccak miner keep on retry

### ISSUE THREAD

**Issue by linlinooi** [nicehash/NiceHashMiner#126]
I have attached a screenshot on this post
![untitled](https://user-images.githubusercontent.com/30762402/28999873-e8a72f06-7a8b-11e7-836c-7d736f3f5dfa.png)

**Comment by p1r473** [comment]
@nicehashdev can you set Keccak's "paying" in the API when no orders are placed to 0 so it will switch to something when Keccak has no orders ? If no orders, it should be paying 0 in the API

**Comment by p1r473** [comment]
Or @dillonn make it switch when there is no orders? Or switch algo when you get this error?

**Comment by ChriscomIT** [comment]
@DillonN @p1r473 Yeah thought about the same. Would be great if that's possible.

**Comment by 3zero2** [comment]
This needs to be looked into in my opinion. Has been happening to me as well.

**Comment by p1r473** [comment]
@DillonN @nicehashdev can you set Keccak's "paying" in the API when no orders are placed to 0 so it will switch to something when Keccak has no orders ? If no orders, it should be paying 0 in the API make it switch when there is no orders? Or switch algo when you get this error?
