### ISSUE TITLE
X16r

### ISSUE THREAD

**Issue by AtlAntA118** [nicehash/NiceHashMiner#1260]
Hi, i just noticed that the algo page for x16r went live on the nicehash website. Are you going to add the enemy miner as well or cant you because its closed source? Is there any way to add the miner myself to nhml?

**Comment by dadoremix** [comment]
also for amd cards need miner

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
