### ISSUE TITLE
fx-8150 shows on website but no actual earns seem to add to my total.

### ISSUE THREAD

**Issue by stressless99** [nicehash/NiceHashMiner#1261]
I just setup legacy on my PC and finally got it to use 7/8 cores on my FX-8130. It shows it is hashing cryptonight 7v at about 350 H/s and mBTC of 4000'ish. My problems is the website nicehash.com shows it as a active worker and even what algorithm is it using but the payout amount doesn't change after over a day. I reinstalled and still I don't see updates on the site. What can I do to fix this? I verified this as this wallet is a new wallet and has been at 1500 totale for 3 days.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
