### ISSUE TITLE
The link is not found about "1.9.0.4/bin_1_9_0_4.zip"

### ISSUE THREAD

**Issue by 55five** [nicehash/NiceHashMiner#1262]
The latest code about "MinersDownloadManager.cs" is bellow.
But the link "http://github.com/NiceHash/NiceHashMinerLegacy/releases/download/1.9.0.4/bin_1_9_0_4.zip" cannot found.

namespace NiceHashMiner.Utils
{
    public static class MinersDownloadManager
    {
        public static DownloadSetup StandardDlSetup = new DownloadSetup(
            "http://github.com/NiceHash/NiceHashMinerLegacy/releases/download/1.9.0.4/bin_1_9_0_4.zip",
            "bins.zip",
            "bin");

        public static DownloadSetup ThirdPartyDlSetup = new DownloadSetup(
            "https://github.com/NiceHash/NiceHashMinerLegacy/releases/download/1.9.0.4/bin_3rdparty_1_9_0_4.zip",
            "bins_3rdparty.zip",
            "bin_3rdparty");
    }
}

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
