### ISSUE TITLE
Lyra2REv2 crash on amd rx480

### ISSUE THREAD

**Issue by billkabb** [nicehash/NiceHashMiner#1263]
Hi i have problem minining Lyra2REv2 with my RX480 and the miner crash .. LyclMiner works great so in a feature version it would be great if i could use LyclMiner instead of ccminer for amd cards

**Comment by muratia** [comment]
Same problem here

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

**Comment by muratia** [comment]
Today I have built the app with some changes and then it could load all the CPU, and AMD graphics cards. Initially could not start hashing with. AMD cards but after some jolting it started.

Mit Freundlichem Grüßen / Kind regards

Ahmet Murati
Software developer & Translator
E-mail: ahmet.murati@live.com
E-mail: ahmetmurati@gmail.com
Handy: +49 1525 1332622

________________________________

**Comment by muratia** [comment]
AMD cards are not mining

**Comment by S74nk0** [comment]
@muratia please open a new issue. Provide detailed explanation and logs so it will be easier to pinpoint the issue.
