### ISSUE TITLE
1.9.0.4 - x16r

### ISSUE THREAD

**Issue by iNDULG3NC3** [nicehash/NiceHashMiner#1265]
[2018-07-02 09:19:10][31m Unknown algo parameter 'x16r'[0m
Try `ccminer --help' for more information.
*** ccminer 2.2.4 for nVidia GPUs by tpruvot@github ***
    Built with VC++ 2013 and nVidia CUDA SDK 9.0 64-bits

  Originally based on Christian Buchner and Christian H. project
  Include some kernels from alexis78, djm34, djEzo, tsiv and krnlx.

BTC donation address: 1AJdfCpLWPNoAMDfHF1wD5y8VgKSSTHxPo (tpruvot)

[2018-07-02 09:21:16][31m Unknown algo parameter 'x16r'[0m
Try `ccminer --help' for more information.

**Comment by paulh69** [comment]
in addition, tried replacing it with the 2.3.0 release but it does not appear to benchmark correctly comes up with something like 20MH but only manages 8-9MH and drops of steadily to 3-4MH

**Comment by luky76** [comment]
2 xgtx 1070
1x gtx 1080

cant benchmark
app stop working when try to do it

**Comment by lmlim** [comment]
benchmark fails on my nvidia 1060s and 1070s, works fine on AMDs.

**Comment by luky76** [comment]
is more profitable the x16 r algo ?

**Comment by paulh69** [comment]
is it even possible to benchmark x16r ccminer 2.3.0 doesn't seem to manage a consistent hash rate?  nicehashminer still freezes solid and has to be killed in task manager when attempting to retry failed benchmarks

**Comment by AtlAntA118** [comment]
yeah doesnt work

**Comment by mves001** [comment]
Yes, not working. Benchmark either fail, get nhml into unresponsive state or nhml simply crash completely.
1060 cards.

**Comment by foxwarernd** [comment]
download from - https://github.com/tpruvot/ccminer/releases
and replace nhm_windows_1.9.0.4\bin\ccminer_tpruvot\ccminer.exe from downloading file "ccminer-x64.exe"

**Comment by paulpoco** [comment]
@foxwarernd do I delete ccminer.exe and copy ccminer-x64.exe from the download and then rename that to ccminer.exe?

That link is 2.3?  does that matter?

**Comment by foxwarernd** [comment]
yes

**Comment by paulpoco** [comment]
I got 2.4 confused with 2.3 because the first post said  "ccminer 2.2.4".

**Comment by AtlAntA118** [comment]
I posted a tutorial on how to add the enemy miner for x16r. Its really easy. https://www.reddit.com/r/NiceHash/comments/8vkg85/how_to_fix_x16r_on_nicehash_legacy_miner_and_also/

**Comment by mves001** [comment]
Replaced tpruvot... winrar have issues and can't properly unpacked archive. Used total commander instead. Next, benchmark showed 12.5 MH/S per 1060 card... mining speed is 5.5 MH/s per card...

**Comment by foxwarernd** [comment]
bench x16 is lying. you need to run the mining, see how much it really produces and drive speed manually

**Comment by paulh69** [comment]
not really worth the effort - rate varies so much sometimes it's 20, 12 or 3.9

**Comment by paulh69** [comment]
NOTE FOR MINERS: The X16R hashing algorithm consists of 16 hashing algorithms operating in chain fashion with ordering dependant on the last 8 bytes of the hash of the previous block. This means that miners will see substantial differences when checking for hashing speeds (because different hashing algorithms have different hashing speeds). This is normal behaviour and does not have any effect on the profitability.

exactly, benchmarking not possible.  its only profitable for nicehash

**Comment by paulpoco** [comment]
I have 2 1070s overclocked.  What hashrate do I fill in?  I let it run with X16R enabled but my mBTC/Day went from 0.38 to 0.20 with that enabled?

**Comment by nazzier5463** [comment]
My rig 1070 1080Ti reboot everytime after try to mine x16r, other algo works fine.. any idea why ?

**Comment by ChillerN8** [comment]
So does is think X16R is most profitable when it is not actually?  Or should I let my rig stay on nicehash mining X16R and never switch?

**Comment by nazzier5463** [comment]
@ChillerN8 I dont think so. I disable it for now.

**Comment by DTG123** [comment]
after reading all the issues X16R is pure shit right now.

**Comment by gysnst2** [comment]
I tried it last night for the first time.  July bench mark was 38 and 8 on 2 cards togestger at first I was mining at 45 the it dropped to 16. Omg horrible.  Still a decent profit but it should have been more then double

**Comment by dadoremix** [comment]
are you try x16r run on rx580 gpu?
what setup core/ram clock ?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
