### ISSUE TITLE
unspecified launch failure lyra2rev

### ISSUE THREAD

**Issue by jpsagenes** [nicehash/NiceHashMiner#1266]
I need help! My miner stops randomly when I mine lyra2rev showing unspecified launch failure. I searched about this error and they are talking about bat file and changing the --plimit but sadly I cant find the file on nicehash legacy miner files. Anyone having the same problem too? thanks!

**Comment by mves001** [comment]
Probably way to overclocked GPU. Also, you do using MSI afterburner? Set there power limit and overclocking.

**Comment by foxwarernd** [comment]
such I had when I screwed the powerlimit. return the nominal frequencies of the video card or reduce the intensity of the manner -i (in additional parameters)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
