### ISSUE TITLE
Not all miners are downloading during setup. (bin/xmrig/xmrig.exe doesn't exist!)

### ISSUE THREAD

**Issue by DTG123** [nicehash/NiceHashMiner#1267]
Updated to, and setup the latest client as I have in the past. There are a few miners that dont seem to like being installed so it tells me that there are miners missing and proceeds to restart and re-d/l the same miners each time I launch legacy.  The few miners that do work start out with negative hash rates and never reach the same levels as they did in 1.9.0.3. 

I have tried to upload the log.txt, but it wont let me. 

so here is the paste bin > https://pastebin.com/embed_js/zjfE8MxK

**Comment by nerdatwork** [comment]
Check your antivirus. You can download bin.zip and 3rdpartybin.zip separately and extra them.

**Comment by DTG123** [comment]
AV is off for mining usually. Ok so how do you stop the client from checking for miner updates and installing them? 

EDIT: Testing CPU miners out,  XMR-STAK (CryptoNightV7) miner is one of them (or all) that is redownloading everytime I open the client, it wipes configuration and you are forced to reconfigure. The other CPU (amd 9370) miners wont benchmark. 
Edit to Edit: The odd thing is that the San Jose service location fails to benchmark, but setting it to Amsterdam works(benchmarks) just fine? 

Edit2: GPU mining: not sure how to edit tpuroot/ccminer settings, tried the replace as suggested in another thread, no improvement there, deleted bin and 3rd party folders, as soon as those are dont downloading again, restart miner and its the same thing, missing initialization files.  No matter what miner I try to use, each and every one of them start out with negative rates, stop and restart does the same thing too. 

From the debug console on start up. 

> [05:51:13] [NICEHASH] Setting environment variables
> [05:51:13] [NICEHASH] Trying to enable/disable Windows error reporting
> [05:51:13] [NICEHASH] Current DontShowUI value: 1
> [05:51:13] [NICEHASH] Setting register value to 0.
> [05:51:13] [MinersExistanceChecker] bin/xmrig/xmrig.exe doesn't exist! Warning
> [05:51:13] [MinersExistanceChecker] bin/xmrig/xmrig.exe doesn't exist! Warning
> [05:51:13] [MinersExistanceChecker] bin/xmrig/xmrig.exe doesn't exist! Warning

...

**Comment by TaylorJayM** [comment]
Mine is doing this as well. Every time I reboot it seems this happens. If I run 1.9.0.3 it starts fine every time so I doubt it's an anti-virus thing.

**Comment by DTG123** [comment]
I said I dont use A/V when mining.  


Well apparently I have 2 miners confused there, the title is true the **bin/xmrig/** folder is empty. 
Xmr-stak (folder) miner is what I appear to be using to do the CPU mining testing.  I have to edit the cpu.txt to use all core/threads everytime the NH .4 loads.

**Comment by DTG123** [comment]
yep and because of that one miner, it redownloads ALL the miners.

**Comment by undert03** [comment]
for me the problem was with bin\xmrig\xmrig.exe and every time i would manually extract it from the bin.zip to that directory it would get deleted when i reopened NHLM. So what i did since i don't use xmrig.exe I just make a blank text file and renamed it to xmrig.exe and that fixed the popup every time i opened NHLM

**Comment by DTG123** [comment]
that worked. Now if the client just gets fixed properly.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
