### ISSUE TITLE
AMG GPU not detecting in legacy anymore

### ISSUE THREAD

**Issue by imprezala** [nicehash/NiceHashMiner#1268]
Machine was working fine with 5x 580s and 1x 570 on 1.9.0.3
after I updated to 1.9.0.4 no gpus are detected. Sometimes it will say video controller not working but usually no error messages

I used display driver uninstall in safe mode still no luck. I patched drivers for 570 already, no ! in device manager, msi afterburner detects all 6 cards

I tried to go back to 1.9.0.3 it worked once after restart it also does not detect any gpus anymore.. My last resort is reformat but i wish I didn't need to. I really do not see how this problem happened

thank you

**Comment by mrfishbsme** [comment]
My rx560 works with
Amd uninstall
Guru 3d amd 18.2.1
Nh 1.9.0.4
Check w10 update

**Comment by shafaatabdin** [comment]
patch it again and restart the PC. Maybe the patching is gone. If still the problem remains then use DDU in safe mode to uninstall the driver and restart. After that reinstall the crimson beta  Blockchain compute driver and restart. After restart patch it again and restart. Now try NHM 1.9.0.3. I think it'll work.

**Comment by imprezala** [comment]
I just reformatted and started from scratch it is working now.
