### ISSUE TITLE
(X16R) aes_cpu_init out of memory (only for 1080ti) gtx970' are fine

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#1270]
im getting this error with X16R "aes_cpu_ini_out of memory"

but only for my 1080ti. the two 970's on the same rig in the same minign algo window are "fine"

my current virtual memory is set to 32gb and i have 8gb (4x2gb) of ram in the machine.

will i need to up this? and if so to what value?

thanks
jim

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
