### ISSUE TITLE
How to X16 Algorithms Manual Benchmarks

### ISSUE THREAD

**Issue by nazzier5463** [nicehash/NiceHashMiner#1273]
From the note 1.9.0.4
**_Note: X16R runs multiple different algorithms randomly, so hashrate may fluctuate. Currently the ccminer benchmark runs on a single one of these, so if you see long term hashrates lower than benchmarked, manually change the speed in settings (future update will benchmark a more expected workload). See manually benchmarking for details_**

I was wondering how to manually, not exactly "how to". I got 2 GPU and both getting 
respectively 34MH/s & 17MH/s each card. When mining, I got only 18MH/s~22MH/s. I wish I can manually benchmarks this algo and the question is what value (H/s) each card should I put ? Should be lower or higher than current benchmarks ?

**Comment by paulh69** [comment]
doesn't seem worth the effort, over several hours it only manages about 1/3rd of the "benchmarked" rate.  seem they benchmark the fastest variant rather than all the slow ones

**Comment by gysnst2** [comment]
some information from the devs on how to change the speeds would be nice.  seams like the potential to bring in some coming is their but with only receiving 1/2 to 1/3 of the hashrate its not worth the time
