### ISSUE TITLE
X16r only getting half hashrate

### ISSUE THREAD

**Issue by tdkavngr** [nicehash/NiceHashMiner#1274]
I finally got it to benchmark but when I start mining, its only gets half of the hashrate I get on the first benchmark. How to fix pls

**Comment by ChillerN8** [comment]
Same here, I thought maybe it was mining the least profitable algo instead of the most, but what you said makes more sense.  Had to go back to .3 because of this issue.

**Comment by mesouug** [comment]
Same issue here. Benchmark speed is 21MH on 1070 but real speed is 9MH. It doesn't depends on hardware 1050ti, 1060, 1070, 1070ti both show twice as much on benchmark. I've disabled X16R for now.

**Comment by paulh69** [comment]
it needs to use 1/3rd of the benchmark hashrate some variants are much lower

**Comment by UselessGuru** [comment]
Same here.

As a workaround I reduced the X16R hashrate via config dialog.

**Comment by gysnst2** [comment]
I have the same issue X16 becomes super slow. I start out at recommended hash rate maybe!! then its cut in half.

**Comment by Victorsueca** [comment]
Can confirm, It's happening here too, using a GTX 1060 6GB.
The hashrate during actual mining is half or less than the benchmark results.

As stated by 1.9.0.4 release notes:

> X16R runs multiple different algorithms randomly, so hashrate may fluctuate. Currently the ccminer benchmark runs on a single one of these, so if you see long term hashrates lower than benchmarked, manually change the speed in settings (future update will benchmark a more expected workload). See manually benchmarking for details

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
