### ISSUE TITLE
X16R with NHML crash, bat file works How to fix this??

### ISSUE THREAD

**Issue by moops44** [nicehash/NiceHashMiner#1276]
If i start Mining with X16R algo , the miner repeatly restarts
but when i edit the example.bat file with the NH Stratum and my BTC Adress
then start it outside NH it works

https://www.youtube.com/watch?v=mKVsla49-0o

**Comment by dadoremix** [comment]
i have also problem with 1.9.0.5 nicehash
x16r cant run benchmark
fail .. precise also fail
rx580 gpu

**Comment by Bige086** [comment]
I was able to get them to work by running them one at a time without any other cpus/gpus bench marking

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
