### ISSUE TITLE
Gpu not detecting for rx 580 8Gb

### ISSUE THREAD

**Issue by Irondog1981** [nicehash/NiceHashMiner#1277]
Hi witch gpu driver works with the New version of Miner Legacy  19.04

I tried old one new one nothing works need some help😄

**Comment by nazzier5463** [comment]
Read the release **NOTE**

**Comment by Irondog1981** [comment]
Driver 18.2 is not working....

**Comment by Irondog1981** [comment]
Nazzier what do you mean??

**Comment by nazzier5463** [comment]
Try to use DDU uninstall your current driver n reinstall 18.2 or earlier

**Comment by mrfishbsme** [comment]
Amd uninstall
Guru 3d amd 18.2.1
Nh 1.9.0.4
Check w10 update

**Comment by namnguyendsn** [comment]
fucking intel.
just use DDU and uninstall intel graphic driver
done

**Comment by Irondog1981** [comment]
Thx Mr.Fish it was the gpu driver works know with18.2.1
