### ISSUE TITLE
Overclocking Profile for Each Algorithm

### ISSUE THREAD

**Issue by vpcm126ag** [nicehash/NiceHashMiner#1278]
Dear Team,

I would like to have overclocking profile for Each algorithm in NHML. Let say when any algorithm change, NHML also change overclocking setting set by user.

ie. when ETH algo selected then my core: -50, memory clock: +800
equihash algo selected then my core: +150, memory: +500
And so on for each algorithm.

This feature will enhance profit for all user as well as Nicehash as it allows user to get most out of it.

I am not sure if similar third party implementation is there or not. Also if it is not feasible then please guide me how I can achieve this. Please add this feature in NHML

Thanking you for your time.

**Comment by nazzier5463** [comment]
Wrong section

**Comment by vpcm126ag** [comment]
@nazzier5463 **Why Wrong Section. 
"this issue tracker is for NiceHashMinerLegacy bugs/feature requests"**

**Comment by foxwarernd** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/issues/1250

**Comment by foxwarernd** [comment]
there must be separate lines for running third-party programs on each algorithm for overclocking

**Comment by zayarcho** [comment]
@foxwarernd 
there must be separate lines for running third-party programs on each algorithm for overclocking
How to write and explain details for beginner.Thanks

**Comment by foxwarernd** [comment]
I just think it's obvious - to make these options in nh, as well as output the temperature in the nh launcher, as well as to be able to receive notifications via telegram. BUT unfortunately, nobody here owes anything to anyone - so we can only hope that maybe someone will do it
