### ISSUE TITLE
Keccek share rejected and socket closed.

### ISSUE THREAD

**Issue by shafaatabdin** [nicehash/NiceHashMiner#1280]
![sample](https://user-images.githubusercontent.com/39776122/42465572-271d2a14-83ce-11e8-877b-c872cd6c2341.jpg)
Plz address this issue. I was mining with no issue for 1 month. Now keccek server rejecting the share. i have tried NHM 19.0.4 also. but the result is same. I think something happened to the server or pool. The same setting was working fine 2 days ago. I am using win 10 and AMD blockchain compute driver.Thanks in advance.
@DillonN

**Comment by nazzier5463** [comment]
Same goes here
[https://www.reddit.com/r/NiceHash/comments/8ww9jd/getting_rejected_shares_on_keccak/](url)

Not to worry, not only you, mine too have same prob.
Btw got some improvement on X16 miner, should delete bin folder and let nicehash redownload again.

**Comment by shafaatabdin** [comment]
So when will it be fixed @nazzier5463 @DillonN ?

**Comment by paulh69** [comment]
keccek hashrate seems to be exceeding the capability of GPUs now

**Comment by nazzier5463** [comment]
Wait it fixes or screw keccak 😁

**Comment by shafaatabdin** [comment]
![untitled](https://user-images.githubusercontent.com/39776122/42524276-d9f211b8-8491-11e8-8ba5-5ab161921e99.jpg)
Now it is getting a lot of rejected shares. When will it be fixed @DillonN ?

**Comment by maurezen** [comment]
Seeing the same, about 50% shares for keccak on eth/keccak dual.

**Comment by SpyShadow117** [comment]
@nazzier5463 @DillonN
Fix this issue by updating the 3rd party miner "claymore_dual" with "Claymore's Dual Ethereum+Decred_Siacoin_Lbry_Pascal_Blake2s_Keccak AMD+NVIDIA GPU Miner v11.9" in a update.
