### ISSUE TITLE
Issue with 1.9.0.4 and rx580

### ISSUE THREAD

**Issue by enterprise-psi** [nicehash/NiceHashMiner#1281]
System has 1 gtx970 and 1 rx580 8gb.
win 10 1709

Suddenly the hashrate on the rx580 drops to zero.  Across all algos
Rebooting does not fix it.
Reinstall drivers.   Every time i first run again the pixel patcher then reboot.
Now nicehash does not detect the rx580 and the process AMDOpenCLDeviceDetection.exe keeps using cpu and is stucked.

tried drivers Blockchain, 17.10.1,18.5.2, 18.6.1   nothing
reinstall all the visual c++ again nothing.
THis is a remote rig, last resort will be to go there and reinstall windows. 

Any ideas much appreciated.

**Comment by enterprise-psi** [comment]
Even gpu-z shows that the rx580 has no openCL capability!? 

![capture](https://user-images.githubusercontent.com/41045176/42496687-876cbff4-842f-11e8-8031-61b467e81bf0.PNG)

**Comment by enterprise-psi** [comment]
Update: by removing and reinstaling the intel hd 510 drivers, i got openCL back, the card **is** detected by nicehash , but again im getting zero hashrate on all algos.

**Comment by Simaex** [comment]
It is a bug of Intel HD drivers. Uninstall Intel driver using DDU, do not install it again. Intel grafics will be ok with basic windows drivers. You may need to remove and install once more you AMD driver if you AMD OpenCL library was also broken by Intel OpenCL that is the cause of the problem.

**Comment by enterprise-psi** [comment]
So in my despair, i attempted restoring the original bios of the gpu,  and now i cannot remotely log in. So i have to drive over there tomorrow :(

**Comment by enterprise-psi** [comment]
@Simaex  that didnt work, I DDU everything, and reinstalled only AMD driver, redid pixel patcher and nothing.

**Comment by enterprise-psi** [comment]
I am closing the issue, cause turns out the card is dead. On 3 different computers, when plugged on a monitor, it BSOD
