### ISSUE TITLE
Issue with keccak

### ISSUE THREAD

**Issue by sedde** [nicehash/NiceHashMiner#1282]
Hello devs, so for the past 3 days, while dual mining on nicehash on both daggerhashimoto and keccak algorithms with 580's, the keccak shares started getting rejected at a 80%+ rate.

I am using claymore 11.8 and it was working fine, then one day it got like this.

NH staff told me to post the error here, and see if i can get help.

Can anyone shed some light to this thing ?

**Comment by nazzier5463** [comment]
Everyone having same problem as you

**Comment by DaBudet** [comment]
+1
nhml (1.9.0,1, 1.9.0.3)
Radeon R9 Fury Series
share rejected & on the site in the statistics keccak 0 mh / s
during the week
![default](https://user-images.githubusercontent.com/3769765/42532281-0b03a670-848f-11e8-9f8f-f6b955b5abcb.jpg)

**Comment by ChillerN8** [comment]
Yup same here, I had to switch back to NiceHash Miner 2 instead of Legacy :(

**Comment by nazzier5463** [comment]
@ChillerN8 Nicehash Miner 2 tu doesnt reject keccak share ?

**Comment by BruceONeel** [comment]
The problem solved. Just update your Claymore dual Etherium miner to 11.9 version. Copy and replace files in ...\nhm_windows_1.9.0.4\bin_3rdparty\claymore_dual

**Comment by shafaatabdin** [comment]
![42465572-271d2a14-83ce-11e8-877b-c872cd6c2341](https://user-images.githubusercontent.com/39776122/42725095-00075f50-87a0-11e8-89fc-b777127b9fda.jpg)

Same issue I addressed before you but no solution yet.

**Comment by Joshwaa2010** [comment]
Claymore has been updated. Download 11.9 and replace in 3rd party folder.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
