### ISSUE TITLE
Starting at 27 Mh and then go down up to 14 Mh

### ISSUE THREAD

**Issue by AS555** [nicehash/NiceHashMiner#1283]
![nice](https://user-images.githubusercontent.com/41069468/42518504-443f987c-8462-11e8-9d33-c8f47e30c955.PNG)

Hello,

Sometimes I start mining with Nicehash at 27Mh and than, 10 or 30 min later my hash rate go down up to 15Mh. Sometimes it startet directly at 15 Mh. 

![11111111](https://user-images.githubusercontent.com/41069468/42519628-bba37936-8464-11e8-9409-fc7e3aff8d49.PNG)

What is wrong?

I use Radeon Nitro Plus 580 4Gb on Windows 7 64bit i7 4cores 8Gb RAM and 16 GB virtual memory  
Nicehash Miner Legacy 1.9.0.4 Claymore dual

![unbenannt2231](https://user-images.githubusercontent.com/41069468/42519738-fdc8f066-8464-11e8-8f6c-9aac60a6cc47.PNG)

Thank you!!!

**Comment by nazzier5463** [comment]
ethermine.org is nicehash server too ? I thought nicehash only mining their pool

**Comment by shafaatabdin** [comment]
This is devfee mining. so don't worry. You are not getting the income of devfee. It is the developer fee mining time don't bother for it. if you see the mining speed is again up to 27+Mh after devfee stop mining then it's okey for you. BTW what is your memory clock and did you mod the BIOS?

**Comment by nazzier5463** [comment]
I never see devfee mining before on nicehash or mybe i just missed it. That its! His card doing 2 jobs, am I right ?

**Comment by AS555** [comment]
I make 1 jobs, only ETH. Speed go down its usual, but not up ))) I have no mod the BIOS because of warranty and I set memory and downvolt as -cclock 1150 -cvddc 910 -mclock 2150 -mcddc 925

**Comment by AS555** [comment]
![2222222](https://user-images.githubusercontent.com/41069468/42522448-681202e0-846b-11e8-858f-c6c49c58c413.PNG)

**Comment by shafaatabdin** [comment]
Start duel mining etherium+Keccek and set dcri value -dcri 9 for the card I think it'll be solved And if it still doesn't solve inform us. And you'll get more for duel mining.

**Comment by AS555** [comment]
Than a I have no 27 Mh 100%, I have try and it works at 13Mh + Keccek only +30W more power

**Comment by shafaatabdin** [comment]
![untitled](https://user-images.githubusercontent.com/39776122/42523787-9b38af5a-8490-11e8-8dc7-5035ba7e4247.jpg)
Look at my stats. Its running now and I've given the live stats. GPU1 is ROG Strix RX 580 8GB

**Comment by AS555** [comment]
Do you have a mod BIOS?

**Comment by shafaatabdin** [comment]
yes I have. You do one thing uninstall the adrenalin driver using DDU in safe mode and install bolckchain compute driver. And then try.

**Comment by TaylorJayM** [comment]
First off you should be running it under windows 10. Then you can put it into compute mode. Second you can flash a bios and then flash it back if you have problems. I have a 570 nitro+ and it does 30.7 all day without dropping.

**Comment by ttugrad** [comment]
TaylorJayM, I'm using the same cards even with the mods and weather I'm using the block chain or the latest drivers in compute I'm only getting 25.xx  Mind if I pick your brain on what you're doing or what I'm not doing?

**Comment by TaylorJayM** [comment]
This is the bios i use. Not sure if there is a lot you can copy out of it because it's a 570 VS 580.
https://sites.google.com/view/taylormining/home

If you want to send me your bios file i could take a crack at modding it.

**Comment by ttugrad** [comment]
Thanks TalorJayM,  
I'm just using the standard copy the 1:/2:1500 strapppings up the chain.   I see where you took some and place them at diff mhz  I'll give it a shot and see what happens :)  It would prob work i have one rx570 8gb in my home pc and 6 rx570 4gb on my rig.  The 8 gb is a little diff, it doesn't have but one set of strappings 0:xxxx not 1:xxxx and 2:xxxx  using compute and the latest drivers.  it seems to not matter if i use the block chain drivers still get the same results of 25 Mh/s on the rig /card and 24Mh/s on the home pc thanks for sharing I'll send you a donation.

**Comment by AS555** [comment]
@ttugrad cards in computing mode? I had sometimes 25 Mh on stock bios, did you saw bios switch at the card?

**Comment by ttugrad** [comment]
@AS555 With the stock bios I was getting about 19Mh  I am using nicehash but I've set up on other pools and got about the same as well.

**Comment by TaylorJayM** [comment]
You have a display plugged in to the card right? When there is no display in mine it does about 16mh.

**Comment by ttugrad** [comment]
@TaylorJayM   I have a 2 displays on my home machine that I use but not in my rig that has 6 cards.  right now with the mod I have and setting to compute I get 25Mh/card.  Interesting that a display will up the hashrate.

**Comment by TaylorJayM** [comment]
@ttugrad Ya i'm not sure why it does this even when using compute mode but when i switched from the HDMI on my motherboard to the rx570 the hashrate doubled. My nvidia cards don't have this issue though.

**Comment by AS555** [comment]
So i have update to windows 10 and still have a some trouble with nicehash legacy miner

**Comment by TaylorJayM** [comment]
Trouble like how?

**Comment by AS555** [comment]
"Starting at 27 Mh and then go down up to 14 Mh" but now it works well on adrenalin 18.2.1 driver

**Comment by TaylorJayM** [comment]
Does it go back up to 27 after the devfee mining is done or does it stay at 14?

Also my settings are below for a 570.
![screen](https://user-images.githubusercontent.com/39247304/43374519-149d7366-937e-11e8-9d6e-0d97bb3fa275.jpg)

**Comment by AS555** [comment]
it works well on 29Mh constantly with adrenalin 18.2.1 
how many mV you have when it works? I make it so
![gihub](https://user-images.githubusercontent.com/41069468/43383941-d12dfa88-93dc-11e8-8ad3-92679f5a97b8.PNG)

**Comment by TaylorJayM** [comment]
910mV. I normally use OverdriveNTool though.
