### ISSUE TITLE
Rx 570 windows freeze

### ISSUE THREAD

**Issue by ethminerrx570** [nicehash/NiceHashMiner#1284]
Hi, 

I've got 3 rx 570 Msi gaming x, one of them is run with pci riser. After I install Windows 10 everything is work fine, but about one week later the system starts freezing when I run NHML.
The problem starts when the cmd window stop working (no error message) and the NHML opens another and another... when 4 windows are open the system freeze. (No bsod). 
If only one Cmd window stop working the problem is the same if I close the NHML.

I don't really know what cause the problem.
Maybe the windows updates? (Because after the clean install the system works fine.)

**Comment by dark8899** [comment]
Same here when I stop one of cmd windows (the one of the card that manage
windows interface) the pc freeze and reboot. Only happen with 1.9.0.4 nhml

**Comment by ethminerrx570** [comment]
Hi!

I increased the starting virtual memory to 20 GB, no problem until ~ 1 day.
But later the NHML starts opening more  and more Claymore cmd panel. The system don't freeze but you can't close none. 
If the problem won't be solved I have to change NHML sadly, because that's just not acceptable.

**Comment by ethminerrx570** [comment]
Hi,

Anybody found a working solution?
Freeze again when I try to close one of the 64 Claymore dual miner window.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
