### ISSUE TITLE
2nd card fails on cryptonight when mining with 2 cards. Works correctly with only one.

### ISSUE THREAD

**Issue by taylorje762** [nicehash/NiceHashMiner#1285]
I recently updated to legacy v1.9.0.4 and now I can't mine with both of my gpus on the same algorithms.
I run 2 R9 270x cards typically on  CryptoNightV7 (claymore) and they typically do well. I have tried uninstalling and reinstalling nicehash, as well as amd drivers, and updating windows. As I have not found a solution i hope that this picture below will find me some help. thank you in advance.

![nice hash legacy problems](https://user-images.githubusercontent.com/41165220/42649323-3f154eb6-85be-11e8-8f9d-cec03d196b31.PNG)

**Comment by nerdatwork** [comment]
have you tried running any other monero miner ? Do they give out errors too ?

**Comment by taylorje762** [comment]
This CryptoNightV7 (XmrStak) works.

![nicehashlegacy](https://user-images.githubusercontent.com/41165220/42761310-fd2a4e46-88c1-11e8-96fa-f70cea098f21.PNG)

and CrypotNightHeavy works.

![cryptoningth heavy](https://user-images.githubusercontent.com/41165220/42761433-5b8dd34a-88c2-11e8-949c-2b257b914577.PNG)


However on Equihash the window opens to show work progress and immediately closes with one card and with two cards activated.

**Comment by taylorje762** [comment]
These are the mining algorithms that work on both GPU-0 and GPU-1 together and separately:
Keccak (sgminer)
Decred (sgminer)
Lbry (sgminer)
Equihash (Claymore)
Pascal (sgminer)
X11gost (sgminer)
Sia (prospector)
Skunk (prospector)
CryptoNightV7 (XmrStak)
CryptoNightHeavy (XmrStak)
X16R (sgminer)

These algorithms only work on one GPU at a time:
CryptoNightV7 (claymore)

These algorithms don't work on either GPU-0 or GPU-1:
Equihash (optiminer)

I hope this helps isolate the issue.

**Comment by taylorje762** [comment]
Cryptonight 7 (Xmr Stak) no longer works

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
