### ISSUE TITLE
No Extra Launch parameters options on GUI NiceHashMinerLegacy 

### ISSUE THREAD

**Issue by tzchenmail** [nicehash/NiceHashMiner#1286]
hello!
### See a lot people can use Extra Launch Parameters on GUI
![3nqef5e](https://user-images.githubusercontent.com/41238990/42726794-cbb2f5a2-87cc-11e8-8c83-e927409bc9aa.png)

### my pc screenshot below here
![02](https://user-images.githubusercontent.com/41238990/42726795-cbee0fb6-87cc-11e8-986e-440da284d556.png)
![03](https://user-images.githubusercontent.com/41238990/42726796-cc18c1ca-87cc-11e8-99e1-413193a4cd6e.png)

![01](https://user-images.githubusercontent.com/41238990/42726732-c1b321cc-87cb-11e8-9430-f764265d20d7.png)

**Comment by DTG123** [comment]
from my search, there is nothing definitive how to use the extra launch parameters, my guess is elitists are keeping those secrets to themselves.

**Comment by nerdatwork** [comment]
@tzchenmail Which miner are you using, which algo are you trying to set extra launch params for ?

**Comment by tzchenmail** [comment]
Hi @nerdatwork !
i write extra launch params  to   \configs\benchmark_GPU-XXXXX.json  for  eth claymore_dual  miner
it work very good

When try or test  params, Get two thing 
1th. change params must use txt editor
2th. NiceHashMinerLegacy should  restart(close and open) again to reload  "extra launch params:"
 i feel slow & wait some time

**if can use "NiceHashMinerLegacy GUI" to change params is very good**

**Comment by ghost** [comment]
Extra Launch parameters options works well for Claymore Dual Miner but the same parameters for Claymore CryptoNote Miner don't work. Logs says what each parameter can't parsed.
If I start Claymore CryptoNote Miner directly with config.txt it's work perfectly.
Tested for this bug on NHML 1.9.0.{3-6} and 1.9.1.0. Same problem.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
