### ISSUE TITLE
Command Line Options

### ISSUE THREAD

**Issue by SpyShadow117** [nicehash/NiceHashMiner#1288]
Adding command line options for use with batch scripts, like an option to begin mining upon launch. I understand there is a setting to auto start mining every time the application is opened but this way if a user open the application, it would only mine if the user tells it.

Example
start NiceHashMinerLegacy.exe /?
Launch Parameters
/m begin mining upon launch

start NiceHashMinerLegacy.exe /m

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
