### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by ChillerN8** [nicehash/NiceHashMiner#1289]
Setting window is set too small and I can not save settings or scroll down to the save setting area.
Do you know where I can adjust the widow size?  I couldn't find it in the JSON config file, but it must be there somewhere.

Thanks,
Nate

**Comment by Jfro416** [comment]
Ya same issue with 1.9.0.5... tried adjusting monitor settings to see if anything would adjust with no luck...

**Comment by Goorath** [comment]
Same with mee. 1.9.0.4 saves ok, save window is there but 1.9.0.5 lacks it.. Next time yoo release new program, it would bee nice to check its functionality..

**Comment by ChillerN8** [comment]
I am not pointing fingers here because I know NHML is not even maintained by NiceHash.  I am just hoping someone with my coding skills can show me where to adjust the window size settings.  I took an into to JSON course and I remember learning about this ability, but can not find it on the config.json file. Thanks in advance!

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
