### ISSUE TITLE
How do you change the intensity for EWBF Equihash?

### ISSUE THREAD

**Issue by freedomtacos** [nicehash/NiceHashMiner#129]
Using the parameters for regular equihash doesn't seem to affect EWBF miner at all, how do you increase or reduce intensity using EWBF extra parameters?

**Comment by UselessGuru** [comment]
Use "--intensity n" where n is any number from 1 - 64 (e.g. "--intensity 32"). 

Note: Unlike other miners there is space between the --parameter and the value

miner --server europe.equihash-hub.miningpoolhub.com --user Minigpool.User --pass x --port 20570 --peg **--intensity 32**

+-------------------------------------------------+
|         EWBF's Zcash CUDA miner. 0.3.4b         |
+-------------------------------------------------+
INFO: Current pool: europe.equihash-hub.miningpoolhub.com:20570
INFO: Selected pools: 1
INFO: Solver: Auto.
INFO: Devices: All.
INFO: Temperature limit: 90
INFO: Api: Disabled
\---------------------------------------------------
INFO: Target: 0001000000000000...
INFO: Detected new work: 2294
INFO: Target: 0010000000000000...
CUDA: Device: 0 GeForce GTX 1080 Ti, 11264 MB **i:32**
INFO: Detected new work: 2295
CUDA: Device: 0 Selected solver: 0
...

**Comment by DillonN** [comment]
@UselessGuru is correct `--intensity <n>` in the extra launch params for the device you wish to change will work

**Comment by KrzysztofC** [comment]
I entered:
--intensity 60
under settings in EWBF under Extra Launch Parameters, but it get's ignored, intensity is always 64 when it launches
What am I doing wrong?
Using NiceHash legacy 1.8.1.0
This is what I see in benchmark json file:
    {
      "Name": "EWBF_Equihash",
      "NiceHashID": 24,
      "SecondaryNiceHashID": -1,
      "MinerBaseType": 13,
      "MinerName": "",
      "BenchmarkSpeed": 536.713333333333,
      "SecondaryBenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": "--intensity 60",
      "Enabled": true,
      "LessThreads": 0
    },

**Comment by Thunder7ga** [comment]
I am experiencing this same thing.  No matter the setting I put on the --intensity (with the space) <#>, it just uses 100% GPU.

**Comment by HaTaX2** [comment]
Had the same issue with the intensity setting on a Nvidia GTX 1070, no matter what I chose it pegged out at 100% and caused some interference with normal desktop use.  After setting it to '--intensity 1' it now sits around 90% use and I don't notice an impact when using the system.  FWIW, even going with 5 it still acted like it was set to 64. Seems that switch could use a little tweaking within the miner itself, the values given don't seem to scale at all.

**Comment by nardeas** [comment]
For me on GTX970 the intensity doesn't do anything at all. It's always 100%

**Comment by RodAus** [comment]
Also here no difference 1 or 64 on 1070 ,EWBF 3.4b. I can see when will stat to mining the new intensity but still same speeds. 
Always GPU 0 is the trouble maker.

**Comment by ivifag** [comment]
Same problem here gtx 1070 intensity in whatever the value I choose always running 100% usage

**Comment by iFA88** [comment]
Yep, same problem here with `--intensity 1`, uses all resources..

**Comment by smoochy** [comment]
I do have the same issue. Running Awesome Miner. I can see the intensity setting is show in the cmd window, but the gpu usage is still at 100%, no matter which one I set.

**Comment by n0n0n0n0** [comment]
same problem here!

**Comment by fseminario** [comment]
same problem here on 1070 and 1060. 1, 16, 32, or 64 doesn't make a difference...

**Comment by jcbergerson** [comment]
I had success with using --i 64 i placed it before --pec 1

**Comment by iFA88** [comment]
I think --i 64 is the default and also we need lower intensity :)

**Comment by jcbergerson** [comment]
Yes, “—intensity 64 64 64 48 64 48”is how I have to set my rig to. My 4th and 6th card are more stable with these settings.

My rig: (6) Nvidia GeForce GTX 1070 FE’s on MSI z270 Gaming Pro Carbon MB, xubuntu 16.04

**Comment by iFA88** [comment]
Hmm.. You have right!
I have tried to set with `-i` but that doenst work.
This really sets the intensity to 1:
```
miner --intensity 1 1
```
Also different:
```
miner --intensity 32 64
```
That works!
Its seems the `-i` parameter has some bugs.
I have two 1080 Ti ext. waterforce, they do 1450 sol/s for zcash :)

**Comment by jcbergerson** [comment]
Perfect, I'm glad it works for yah!

JC
_______________________________________________________________________________________________________________
My rig: (6) NVidia GeForce GTX 1070 FE’s on MSI z270 Gaming Pro Carbon MB, xubuntu 16.04. My Second Rig: (3) PNY GeForce GTX 1070 OC on older MB, xubuntu 16.04.

**Comment by ww40** [comment]
I'm also encountering issues, if i set "miner --intensity 1 1" in extra launch parameters for EWBF equihash i get around 94% gpu usuage, if i try "miner --intensity 32 64" I get 100% gpu usuage. Anyone know how to limit my gpu usuage using this parameter? I was looking for around 50%
