### ISSUE TITLE
useing hyperthreading

### ISSUE THREAD

**Issue by jjaomni** [nicehash/NiceHashMiner#1291]
cpu miner does not use hyperthreading with my intel cpus.

**Comment by foxwarernd** [comment]
now in the miners on cpu it is important how much the cache is of the third level. for example, take the processor i7 3770 it has 4/8 cores and the L3 cache 8Mb - for each thread of the liner you need from 2Mb cache - this means that there will be only 4 threads!

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
