### ISSUE TITLE
Benchmark failed ;(

### ISSUE THREAD

**Issue by nicozito1** [nicehash/NiceHashMiner#1292]
I have problems when doing. Once selected the graphics cards and the algorithms, when I start, the computer freezes completely to the point that I must turn it off because it lasts as long as I want until I turn it off

**Comment by foxwarernd** [comment]
1) do not run the test entirely. run say 2 tests at a time. so you can determine on what crashes
2) get here files log from "nhm_windows_1.9.0.5\logs"

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
