### ISSUE TITLE
PC shutdown during benchmarking

### ISSUE THREAD

**Issue by DawieKabouter** [nicehash/NiceHashMiner#1293]
Please help.

Everytime I start to benchmark, the PC outomatically shuts down.

I have no idea how to resolve this issue

**Comment by foxwarernd** [comment]
1) do not run the test entirely. run say 2 tests at a time. so you can determine on what crashes
2) get here files log from "nhm_windows_1.9.0.5\logs"

**Comment by DawieKabouter** [comment]
Hi,

I have tried benchmarking one algo at a time, but still the pc restarts after running for about a minute.

**Comment by z-satin** [comment]
hihi

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
