### ISSUE TITLE
REQ: Add PhoenixMiner for ETH Single Mining

### ISSUE THREAD

**Issue by dhonasan** [nicehash/NiceHashMiner#1294]
Please add PhoenixMiner to NiceHashMinerLegacy for single ETH Mining because it could get bigger hashrates than Claymore

**Comment by nazzier5463** [comment]
Yes i agree

**Comment by hindiantoro** [comment]
+1

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
