### ISSUE TITLE
Bottom part of NHML missing

### ISSUE THREAD

**Issue by coa100** [nicehash/NiceHashMiner#1296]
Hello NiceHash, I got a problem with your miner. I tried changing the settings but there is no bottom part (see the picture) and I can't save my settings. Tried redownloading the nhm a couple of times and installed it on 2 different partitions and I still get the same result, I've sent a message to your facebook page and the person who was talking to me gave me multiple solutions for that problem but none of them worked and in the end they just told me to select all the settings I need and then click on the BTC address and press shift+tab 5 times and then enter because that will save the options, they also told me to come here to file that issue so I will do it. See the picture below to see my issue
![nhm settings](https://user-images.githubusercontent.com/41618767/43127818-aeb77980-8f30-11e8-8339-9504c17f408b.PNG)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2222807/log.txt)

**Comment by nazzier5463** [comment]
#1295

**Comment by kostiani** [comment]
у меня точно так же..

**Comment by DTG123** [comment]
@coa100 by chance have you changed windows default font size? if not try using a smaller font to see if this fixes that.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
