### ISSUE TITLE
missing save button

### ISSUE THREAD

**Issue by pavel4840** [nicehash/NiceHashMiner#1297]
Installed the program NiceHash Miner Legacy v.1.9.0.5
I go to Settings -> Devices / Algorithms
I set manually the speed of aglorhythm.
But there are no buttons to save and exit.
![default](https://user-images.githubusercontent.com/36538280/43193548-f685fa56-9008-11e8-9269-81bc686c5735.jpg)

**Comment by shafaatabdin** [comment]
I am having the same issue here. @DillonN Plz resolve the issue.

**Comment by grazcata** [comment]
same thing

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
