### ISSUE TITLE
Nicehash miner 1.9.0.5 unstable.

### ISSUE THREAD

**Issue by shafaatabdin** [nicehash/NiceHashMiner#1298]
The NHM 1.9.0.5 and claymore 11.9 seems to be unstable in win 10 and blockchain beta driver for AMD. It works max 48 hours and after that it hangs by opening multiple claymore windows and I  have to power off the PC to set it back to work again. Plz @DillonN fix it up and release a stable update asap.

**Comment by Lifeisvirtual** [comment]
Yet another issue with 1.9.0.5. This is the error I'm getting now...

ETH: Stratum - Cannot connect to daggerhashimoto.eu.nicehash.com:3353
ETH: Stratum - Failed to connect, retry in 20 sec...
 B2S: Stratum - Cannot connect to blake2s.eu.nicehash.com:3361
 B2S: Stratum - Failed to connect, retry in 20 sec...

yesterday it was only the Blake2s timing out but today I noticed both Eth and Blake timing out.

**Comment by nerdatwork** [comment]
@shafaatabdin My 1.9.0.5 wont detect my AMD at all. It only detects Nvidia like wth. I haven't selected DO NOT detect AMD still it wont detect. You didn't face any such issue ?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
