### ISSUE TITLE
1.9.0.4 and 1.9.0.5 the Equihash(OptiminerAMD) Algorithm crashes.

### ISSUE THREAD

**Issue by LexLampard** [nicehash/NiceHashMiner#1299]
1.9.0.4 and 1.9.0.5 the Equihash(OptiminerAMD) Algorithm crashes. Starts and turns off immediately, and so cyclically. Radeon R270 2GB.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
