### ISSUE TITLE
GUI Request - In Benchmark Screen

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#13]
In the GUI there are two dialog boxes, one  up top to select Devices and one below to select algorithms for the selected device.

When you select a device and then select an algorithm the highlighted device you are on is deselected.  While this technically doesn't cause any issues, visually, its hard to keep track of which device I have currently selected

Suggestion:  Keep the selection up top selected when selected algorithms down below

**Comment by DillonN** [comment]
I will look into this

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

We will be working on a complete GUI re-design.
