### ISSUE TITLE
Cryptonight(ccminer) doest show up on benchmark

### ISSUE THREAD

**Issue by utc99** [nicehash/NiceHashMiner#130]
GPU miner - Cryptonight(ccminer) doest show up on benchmark, how can it be added?
Running ccminer(cryptonight) manually works fine.

![ccminer](https://user-images.githubusercontent.com/26816096/29021779-52fdaef0-7b6f-11e7-8d35-4e8b084f9304.JPG)

More detailed info in comments below.

**Comment by ChriscomIT** [comment]
Just select CPU !!!! :D :D :D

**Comment by utc99** [comment]
ccminer is an GPU miner, which also can mine CryptoNight, which is good for some my equimpment..

**Comment by ChriscomIT** [comment]
Ah ok I see misunderstood it then as your initially explanation was very short.
For me its there just fine. Maybe your hardware isn't capable of mining CN. Did you try standalone mining already to see if it works there?
<img width="451" alt="crypto" src="https://user-images.githubusercontent.com/2799553/29040551-bcd4c382-7baf-11e7-885d-e67839c9793d.PNG">

**Comment by utc99** [comment]
Yea, as I wrote, running ccminer(cryptonight) manually works fine. I'll update the post to be more clear. Too add, tried some really old versions of nhm, 6-12 months old, they had CryptoNight(ccminer) in benchmark and worked fine, if this works good for some equipment, dont see the reasons to remove it.

**Comment by ChriscomIT** [comment]
Which version of NHML is u using as of now which don't have CN for you? Latest stable or new 1.8.1.0pre4 ?

**Comment by utc99** [comment]
None of those - latest stable Nhm1.7.5.3(or which is it now), stable nhml 1.8.0.2, nor the nhml pre 4

**Comment by ChriscomIT** [comment]
Ok, maybe u want to give latest stable 1.8.0.2 a try?

**Comment by utc99** [comment]
Tried that too, no good

**Comment by luongk** [comment]
This behaviour is the same on my system - Cryptonight (ccminer) is available on my GTX980, but not on my 1080ti.

**Comment by ChriscomIT** [comment]
Guys, did u already tried 1.8.1.0pre4 as it should have some improvements regarding this? Not saying it will fix it but its worth a try.

**Comment by utc99** [comment]
The problem persists in:
NHML-1.8.1.0-Pre1 - NHML-1.8.1.0-Pre4
NHML-1.8.0.2
NHM-1.7.5.13 (has even less miners for this hardware available)
NHM-2.0.0.11 - does not even see GPU at all, and I dont like that all install program cr@p, i like miners to be lunched without installation, so i wouldnt even use that one.

Tried random old version of NHM:
NiceHashMiner_v1.7.3.6 - has much more algorithms for weak hardware, 4 algorithms for CPU, and lots of for GPU(ofcourse lots of them are not profitable), and it has a working ccminer(CryptoNight), which even runs 10-20% faster thant runing it manually from NHML 1.8.0.2 folder.

![nhm-old](https://user-images.githubusercontent.com/26816096/29085943-8f76dd9c-7c79-11e7-8c17-d64fb86f9105.JPG)

**Comment by DillonN** [comment]
Certain algorithm/miner combinations are disabled for different generations of NVIDIA GPUs, either because they do not run correctly or are very unprofitable (to reduce clutter). In this case, CN through ccminer does not launch on SM6.x GPUs (Pascal) and was considered unprofitable for SM2.1 GPUs (like the 720M). 

@utc99 do you find that CN is profitable on your GPU compared to other algorithms? I do not have every generation to test with so if you post how well these older algorithms compare I can re-look into it

**Comment by utc99** [comment]
Well i checked more, there are currently two algorithms that mine almost the same for me- decred and blake2s, crypto also gives the same profit, yet it really has a long windows between found shares, so it's really might not be worth it to turn that on one, comparing to others, mining time would split into 3 equal parts if crypto would be enabled, but total profit practically wouldn't change. I'm closing this one.
