### ISSUE TITLE
When autoselect server is checked change server when unable to connect to pool

### ISSUE THREAD

**Issue by fritzr4** [nicehash/NiceHashMiner#1300]
On Jul 28 2018 multiple NiceHash pools experienced a DDOS attack that caused an unable to connect error on affected pools.  When restarted NHM2 autoselects the pool that is unable to accept connections because it is the fastest connection.

The feature I would like added is: When autoselect pool is checked, stop mining and autoselect a pool that is accepting connections when the currently selected pool stops accepting connections.

Related change request.  If on startup a pool is unable to connect do not allow autoselect to choose that pool.  When restarted during the DDOS attack NHM2 automatically selected the fastest pool ... one that was unable to connect.

The current workaround is to uncheck the automatic selection and manually switch to each available pool to find one that is still working.  Not a problem for those with 1 or 2 machines, a serious problem for those with a large number if machines.

**Comment by nerdatwork** [comment]
This is not for NHM2 issues. Contact support to file a ticket. This section is only for NHMLegacy.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
