### ISSUE TITLE
Half of AMD cards not mining

### ISSUE THREAD

**Issue by nnewsum** [nicehash/NiceHashMiner#1301]
I have been mining for a couple of months with nicehash legacy miner on a couple of AMD RX480 and RX580 graphics cards.  Earlier this month the computer stopped mining with nicehash legacy miner.  I have reinstalled graphics drivers, tried different versions of nicehash legacy miner.  The only way I can mine is with unplugging two of the graphics cards from the motherboard.  I have switched them around aka plugged half into the motherboard and then tried a different set. And all of the graphics cards will mine just not at the same time with nicehash legacy miner.  The computer shows all the graphics cards drivers are installed and working at the same time. It is just nicehash legacy that can't seem to mine with them all at one time like it did for a couple of months before having this error.

It does seem that nicehash legacy miner is sending error reports.  Is it possible to find a solution to this problem?

**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by nerdatwork** [comment]
You can delete text starting from **NOTE this issue track** from your post

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
