### ISSUE TITLE
Include CryptoDredge_0.8.0 for Lyra2rv2

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner#1302]
Gives faster hash rate with around 10% boost on 1070Ti and 1% dev fee. My 5 1070Ti's went from 245 to 291 for lyra

**Comment by angelbbs** [comment]
CD already added in https://github.com/angelbbs/NiceHashMinerLegacy/releases

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
