### ISSUE TITLE
Which incompatibility with AMD?

### ISSUE THREAD

**Issue by electricdelicate** [nicehash/NiceHashMiner#1304]
Since few Legacy releases is appeared this in the Release Notes:
**There is an incompatibility with later AMD drivers and the newest Windows feature update (1803).**

Which kind of issues occur with this Windows Update and Driver? Crashes? Lower hashrates? Not correct working miners?

Best,

**Comment by nerdatwork** [comment]
NHML won't detect AMD cards is one such issue.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
