### ISSUE TITLE
MH / s speed problem in mining

### ISSUE THREAD

**Issue by macoes** [nicehash/NiceHashMiner#1305]
Hello good day. I have a problem with mining.
I extracted previously with 50,071 MH / s per 1080 gtx video plate and now I am extracting each plate 8093.47 KH / s per mine.
I wanted to know if there is a configuration to re-mine as before.
Thank you very much, I hope your answer.
I attached the images, so you can see the problem.
![look at the photo](https://user-images.githubusercontent.com/42039950/43597436-6eb60e9e-9658-11e8-9c45-e9dacd0a6710.jpg)

![minado very good](https://user-images.githubusercontent.com/42039950/43597351-33af19a8-9658-11e8-9772-ddf8548e1025.jpg)

**Comment by nerdatwork** [comment]
X16r has bunch of algorithm in it. Some are slow, some are fast and some are medium. You will get variable speed for each algo. There is nothing wrong with your setup.

**Comment by macoes** [comment]
there will be a configuration to work with some faster algorithm

**Comment by nerdatwork** [comment]
I dont understand.

**Comment by macoes** [comment]
can be configured to use another algorithm faster.
Can you change the algorithm to mine faster?

**Comment by macoes** [comment]
can be configured to use another algorithm faster

**Comment by nerdatwork** [comment]
Do you want more money or less money ?

**Comment by macoes** [comment]
is possible....? I would like to earn more money

**Comment by nerdatwork** [comment]
Its NOT possible so leave your settings as they are. Trust me its mining the right way.

**Comment by macoes** [comment]
And if I work with algorritmo lyra2rev2 it will not mine faster and pay more?

**Comment by nerdatwork** [comment]
Nicehash pays you for the CURRENT top paying algo. If Lyra is pays more NHML will mine LYRA if X16 pays more it will mine it. Don't worry about speed if its mining X16. Just make sure all your cards are working at settings you set.

**Comment by macoes** [comment]
I'm asking all this because before, nicehash paid me every two days and now he pays me every four days, I want him to pay me back as before.

**Comment by dark8899** [comment]
Before they pay every 6$ now es every 8$. Something like that

**Comment by macoes** [comment]
they pay me every 2 days and now they pay me every 4 days I want them to be like before they pay me every 2 days
