### ISSUE TITLE
Vega 56 not mining X16R in nicehash. 

### ISSUE THREAD

**Issue by merwynv** [nicehash/NiceHashMiner#1306]
i have 4 vega 56 running cryptonight v7. but i cant even start to benchmark x16r. 
soon after i start benchmark it says "try precise" if i continue nicehash hangs.
i found some similar topics about x16r on nvidia cards. 
someone pls tell me details on how to make my vega mine x16r.

thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
