### ISSUE TITLE
AMD RX 580 8go not recognized by NiceHash

### ISSUE THREAD

**Issue by 851d229** [nicehash/NiceHashMiner#1308]
Hi everyone,
I know there is other posts like this one, but doesn't seem to got a resolve on this one:

I have just bought my new mining equipement, here is a summary:
Board Gigabyte H110-Da3
Intel i7-7700k
Windows 10 x64
3x AMD Radeon RX 580 ARMOR 8G OC Graphics Card 

The NiceHash "Profitability calculator" informed me that these AMD cards could be ok for me to make coins.  I've installed NiceHash, but it is just don't recognized the AMD card...  I have installed the driver on windows, the most recent driver Adrenaline 18.7.1 (could it be the issue?).  

Is everybody knows what I need to know to get all this working ?

thank you !

**Comment by nerdatwork** [comment]
**Note:** There is an incompatibility with later AMD drivers and the newest Windows feature update (1803). If you are having issues rollback to drivers 18.2.1 or earlier (blockchain drivers work too)

**Comment by z-satin** [comment]
hihi, I went through same issue.

**Comment by nickt5174** [comment]
Having the same problem here, tried 18.2.1 with the same result.  Using Legacy Miner 1.9.0.6 
Running 6 Powercolor RX580 8g cards and the miner does not detect them.  I have tried a few different driver versions with the same result.

**Comment by z-satin** [comment]
i can tell you is that, it's not the amd driver.

**Comment by nerdatwork** [comment]
@z-satin @nickt5174 are you guys using Windows 10 ?

**Comment by z-satin** [comment]
yes, window 10, amd r9 200, r9 300, rx 580.

**Comment by nerdatwork** [comment]
Does blockchain driver help ?

**Comment by z-satin** [comment]
it is not amd driver. NHLM is harder to get it going with 6 gpu compare to etherium software. there are issues with benchmark after the window see them all

**Comment by Bige086** [comment]
Mine werent being detected until I had a monitor hooked up. Maybe try that?

**Comment by 851d229** [comment]
The blockchain driver has resolved the issue.
