### ISSUE TITLE
Add PhoenixMiner 3.0c for ETH 

### ISSUE THREAD

**Issue by pbuva** [nicehash/NiceHashMiner#1309]
Can you add PhoenixMiner_3.0c for ETH pls?
I got better hash with 1080 and 1060 with this miner.
https://bitcointalk.org/index.php?topic=2647654.0

Or better, how can i add this miner? :)

**Comment by dadoremix** [comment]
you can use only that miner
start.bat you edit like that

REM
REM Example bat file for starting PhoenixMiner.exe to mine ETH
REM

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

REM IMPORTANT: Replace the ETH address with your own ETH wallet address in the -wal option (Rig001 is the name of the rig)
 PhoenixMiner.exe -pool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 -wal 35bjUBvwQRnDX2E4H9xTkBwWYZwHbyKU2H.Asus -pass x -proto 4 -stales 0 -tmax 55
pause

-tmax is temperature 55 for my rx580 cards, you can delete

**Comment by pbuva** [comment]
Yes, i use this miner for 5 day now, but i miss the nicehash profitability switching ability if is not included in NHML,

**Comment by dadoremix** [comment]
you are not missing anything
other crypto are too low

2018-08-07 17:10 GMT+02:00 pbuva <notifications@github.com>:

**Comment by nazzier5463** [comment]
@dadoremix u meant ETH wallet address ? When i paste my nicehash wallet, i got pool rejected

**Comment by dadoremix** [comment]
Are you mining at nicehash pool?
External or internal btc adress

08.08.2018., u 18:32, korisnik nazzier5463 <notifications@github.com> je napisao:

**Comment by nazzier5463** [comment]
@dadoremix i copy your setting and its work now. I just curious can I use nicehash wallet ?

**Comment by dadoremix** [comment]
Yes you can
Btc external wallet
Or like i use.. internal nicehash btc wallet
And tranfer to coinbase for free

08.08.2018., u 18:59, korisnik nazzier5463 <notifications@github.com> je napisao:

**Comment by nazzier5463** [comment]
@dadoremix hello again. can you help me how to add second pool (nicehash) in case the first pool down ?

**Comment by dadoremix** [comment]
see pool.txt file
i have backup to ethermine.org

**Comment by nazzier5463** [comment]
[log20180822_101438.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2308948/log20180822_101438.txt)
@dadoremix can u help, why this miner auto stop (mining windows closed) after mining few hours ? And i have to start miner again.

**Comment by dadoremix** [comment]
Over clocking problem?
What say log file?

22.08.2018., u 07:19, korisnik nazzier5463 <notifications@github.com> je napisao:

**Comment by dadoremix** [comment]
Ou.. i see your log now
Nvidia 1080ti ... only one?
Temp is 70’c
And claymore is stable?
I have 7x rx 580 sapphire nitro +
I do not have experience with nvidia cards

22.08.2018., u 07:19, korisnik nazzier5463 <notifications@github.com> je napisao:

**Comment by nazzier5463** [comment]
@dadoremix I just add another 1080ti but still the same. It just stopped and idling my rig. Claymore is stabil with nicehash but few hashrate dropped.
[log20180822_174407.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2312379/log20180822_174407.txt)

**Comment by ImmortalJ** [comment]
I too would like to see the addition of PhoenixMiner to NHML. Seems to be just as fast as Claymore but with a lower fee.

**Comment by dadoremix** [comment]
1% vs 0,65% .. not big difference
And one is working and one is not working good for someone .. 1080 nvidia .. ask dev for fix

**Comment by nazzier5463** [comment]
Seem dev of phoenix miner very quiet since early of this year. Now im using claymore from RWTeam with 0.5% fee. Im using for a quite longtime since problem with pheonix. Works fine with nicehash, just replace the file in claymore folder.

**Comment by ImmortalJ** [comment]
@dadoremix I know it's not a huge difference, but it's nice to have options. Not requesting that it be added to replace Claymore, just an option to enable it for those of us who want to use it.

**Comment by nazzier5463** [comment]
Unfortunately, nicehash never give us option to choose which miner we want to use. Nowadays, a lot of new miner popup and nicehash still not doing any move.

**Comment by ImmortalJ** [comment]
@nazzier5463 That is not exactly true. For example in the benchmark there are two different miners for CryptoNightV7 (xmrstak and claymore), you can choose which one you want to use by disabling the one you don't. I see no reason why they couldn't add more alternative miners using the same method.

**Comment by dadoremix** [comment]
if you mine only one algo .. you set custom setting
dont use nicehash .. 
i have like that
Phoenix 3.0c and config for nicehash pool .. eth btc adress and worker name .. that all 
uptime 24/7

but last 7 days i have problems with pool .. 2x at day remote closed socket bla bla .. and my miner go to second pool to backup .. ethermine.. after 30 min .. switch back
But i dont know why .. to many power at pool ? and no work to do ?

**Comment by dadoremix** [comment]
after 1m .. i can say
claymore is better than phoenix
phoenix every day lost conection to nicehash pool and use my backup ethermine
but i start again claymore .. rock stable and not switching pools

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
