### ISSUE TITLE
benchmark issue

### ISSUE THREAD

**Issue by NameUnavailable** [nicehash/NiceHashMiner#131]
we just added a new 1070 and run the benchmarks, at Sia it won't  complete

![missing](https://user-images.githubusercontent.com/30479416/29098629-65599ca8-7c6e-11e7-8046-d755bd960560.jpg)

**Comment by DillonN** [comment]
This version of ccminer depends on the Universal C Runtime, which is included in Windows 10 and available from Windows Update for older versions. You can try running Windows updates, or manually download the package [here](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows)
