### ISSUE TITLE
Will NHML mining the ethash algorithm on GTX 1060 3gb maps after the DAG file exceeds 3gb?

### ISSUE THREAD

**Issue by 3DPrinter-UA** [nicehash/NiceHashMiner#1311]
Good afternoon.
Will NHML mining the ethash algorithm on GTX 1060 3gb maps after the DAG file exceeds 3gb?
The etash algorithm has many different currencies.
In December, on the basic currency of the DAG broadcast, the file will no longer fit into the video card's memory.
But at the same time the card can extract other currencies, for example ETP
Despite this, NHML does not check the memory capacity of the card and is persistently trying to extract the currency that does not fit into the card ...
Do you plan to add to NHML the definition of the amount of video memory and adjust the algorithms and currency for this memory card volume?

**Comment by nerdatwork** [comment]
Ask this question to the miner you use example Claymore. NHML is just an interface to sell your hashrate to get paid in BTC. Go to Claymore's bitcointalk page.

**Comment by 3DPrinter-UA** [comment]
NHML itself chooses the currency for mining. I can not control it. I can choose an algorithm, but I can not select a currency.
You can mine ETH at 1066 and ETP at 1063.
The user can not adjust this without special settings.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
