### ISSUE TITLE
Amount of mBTC is rounded off to 3 digits

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner#1312]
If rest of the digits are not going to be shown why show the amount up to 5 digits after decimal. If amount is 0.848392. NHML shows it as 0.84800 

This is a minor discrepancy but it is very annoying when everything we do is for money.

**Comment by S74nk0** [comment]
@nerdatwork I am unable to replicate this issue with one of the latest versions. Please open new issue if you are experiencing this with 1.9.1.6 and up.
