### ISSUE TITLE
RX 580 8G problems

### ISSUE THREAD

**Issue by AE001** [nicehash/NiceHashMiner#1313]
What is the best amd driver version for mining with RX 580?
The version specified in troubleshooting section (v 15.7.1) is not supported by RX 580.

**Comment by anazz20** [comment]
There is a newer one for block chain only for the newer cards, wouldn't try gaming with them. Search for block chain amd driver, it comes up first as the older ones, like my 290x version is way down below.

**Comment by dadoremix** [comment]
try 18.2.1

**Comment by 851d229** [comment]
yes the blockchain driver will help you

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
