### ISSUE TITLE
Nicehash Miner Legacy cause screen freeze on Windows10. AMD R9 390 cards

### ISSUE THREAD

**Issue by rgymdm** [nicehash/NiceHashMiner#1314]
I'm preparing to mine using my R9 390 cards. OS version is Windows 10 1703. After installing the system, win10 automatically detected my graphics card and installed the driver. Driver version of my R9 390 is 
22.19.677.257. Every time I tried to benchmark the screen would froze, and the screen also freezes whenever I manually active an algorithm in NHM Legacy to mine. Is this a driver conflict problem?

**Comment by rgymdm** [comment]
There's no overclock btw

**Comment by z-satin** [comment]
i have same issue with amd red devil rx580 8gb. The screen went blank after so many bench mark tests. After I tried out with different amd drivers version. it's still the same.

**Comment by nickt5174** [comment]
I am also having that same random freeze up issue with Legacy miner, hopefully the 1.9.0.6 fixes that

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
