### ISSUE TITLE
Run with windows doesn't work

### ISSUE THREAD

**Issue by Jacobknight** [nicehash/NiceHashMiner#1315]
run with windows automatically unchecks itself after saving,

**Comment by nazzier5463** [comment]
@Jacobknight have you found solution?

**Comment by nazzier5463** [comment]
**SOLUTION**
1. Hold the windows key+R and bring up the run dialog box and type in "regedit" and hit enter

2. Navigate to this registry key location:
"hkey_local_machine\software\wow6432node\microsoft\windows\currentversion\run"

3.  Right click on the right side of the panel and go to New->String value and that will create a new string value that you can rename to the name of the program you want to run ("Real Temp" in my case)

4.  Double click your new string value and under where it says "value data" type/paste in the dialog box the path to the program (copying it from the desktop shortcut is the easiest) . In my case, my Real Temp is in: "C:\Real Temp\RealTemp.exe"

5.  That's it!  You're done.  And now you can restart your PC to check and see that the desired program now starts up automatically with Windows 10!

`SOURCE: https://answers.microsoft.com/en-us/windows/forum/windows_10-start-winpc/windows-10-startup-programs-not-launching/34202a37-fdeb-48e9-a3fd-7e06a49d735e`

**Comment by StronkMan** [comment]
crontab or task scheduler?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
