### ISSUE TITLE
1.9.1.0 Alpha Reporting

### ISSUE THREAD

**Issue by DillonN** [nicehash/NiceHashMiner#1316]
Hello, please leave reports/comments for 1.9.1.0 in this thread.

When reporting a bug remember to attach your `logs\log.txt` file.

**Comment by foxwarernd** [comment]
The column width settings in the main window are not saved. there is no possibility to see the consumption of watt / hour and the cost of electricity at the current work - it would be nice at home

**Comment by foxwarernd** [comment]
In the main window, the name of the group does not change when the algorithm is switched

**Comment by StronkMan** [comment]
1. When algo switches, hashrate && mBTC/day doesn't update for each device. and name of the algo group itself doesn't update.

*Power reports works fine, but rightclick on cards->show power info doesn't feel intuitive, maybe group the switch with Electricity Cost? in Setting->Main

**Comment by psychonz** [comment]
When mining over the past couple of days, the Rate has been negative. I am also fairly sure that my balance has been gradually reducing. I have gone back and tried the previous version and the problem doesn't happen.



[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2357989/log.txt)
![negative_address_blank](https://user-images.githubusercontent.com/543987/45172624-fa8a4800-b259-11e8-8fef-f62c39351895.jpg)

**Comment by PBJellytime** [comment]
Running on two rigs, one of them doesnt update the Algo from Neoscrypt when it returns to a different Algo and on the other the power details sometimes show cost and sometimes doesn't.  I havent worked out what causes it stop to calculating the power cost yet

**Comment by KadarMarine** [comment]
You may decide this isn't any of your concern; but Houston I have a problem...

I have developed a "RigMinder" program that consist of a Rig "client", and a monitoring "server"; where each rig is running the client program, and reporting back to the server (see below).
![image](https://user-images.githubusercontent.com/7789961/45931676-3fdb9480-bf3f-11e8-9a20-8167c2428ec6.png)

The client is also responsible for dealing with errors which helps to keep the rigs mining; and I don't need to monitor any Remote Desktop Windows. The Server alerts me if a Rig goes off line, etc.

My system relies on being able to access the text label windows from within the NHL Worker Displays. This is pretty easy to do.

While I have tried my best, I have not been able to access the text from within the SysListView32 window (using the LVM_GETITEMTEXTW message). I can read my own sample ListView, but not yours. I don't know why.

In effect my "RigMinder" program will become useless with this new NML display format.

I am open to suggestions.

One solution would be to leave the current worker displays active, but then hide them from view by placing them underneath another Window control (such as the SysListView32 window) . As long as the "Visible" property is set to "true"; I will still be able to access the data that they provide.  

Alternatively, the Worker data could be printed to "stdout". It's likely I that could create a pipe thread to read and parse the Worker data from there. I have already done this with the Nvidia-SMI utility. Note that maintaining the current output format would be greatly appreciated:)

More info on the "RigMinder" is available on request.

Best regards.

**Comment by DTG123** [comment]
so how do you enable the power columns? and where does it show which miner is being used?

**Comment by PBJellytime** [comment]
> You may decide this isn't any of your concern; but Houston I have a problem...
> 
> I have developed a "RigMinder" program that consist of a Rig "client", and a monitoring "server"; where each rig is running the client program, and reporting back to the server (see below).
> ![image](https://user-images.githubusercontent.com/7789961/45931676-3fdb9480-bf3f-11e8-9a20-8167c2428ec6.png)
> 
> The client is also responsible for dealing with errors which helps to keep the rigs mining; and I don't need to monitor any Remote Desktop Windows. The Server alerts me if a Rig goes off line, etc.
> 
> My system relies on being able to access the text label windows from within the NHL Worker Displays. This is pretty easy to do.
> 
> While I have tried my best, I have not been able to access the text from within the SysListView32 window (using the LVM_GETITEMTEXTW message). I can read my own sample ListView, but not yours. I don't know why.
> 
> In effect my "RigMinder" program will become useless with this new NML display format.
> 
> I am open to suggestions.
> 
> One solution would be to leave the current worker displays active, but then hide them from view by placing them underneath another Window control (such as the SysListView32 window) . As long as the "Visible" property is set to "true"; I will still be able to access the data that they provide.
> 
> Alternatively, the Worker data could be printed to "stdout". It's likely I that could create a pipe thread to read and parse the Worker data from there. I have already done this with the Nvidia-SMI utility. Note that maintaining the current output format would be greatly appreciated:)
> 
> More info on the "RigMinder" is available on request.
> 
> Best regards.

If you get it fixed you should definitely sell that program, looks much nicer than my bodged together powershell script :p

**Comment by KadarMarine** [comment]
> If you get it fixed you should definitely sell that program, looks much nicer than my bodged together powershell script :p

I've just released NhlRigMinder v1.5 (04/22/19):
https://kadarmarine-ftp.sharefile.com/d-sdbf8bd0130c4decb

Update includes numerous fixes and improvements. Server is stress tested to 63 "Zombie Rig" clients.

New Wake on LAN (WoL) options provide more complete automation.

Requires Windows XP or better running on an IBM based PC.

Best regards.

**Comment by DTG123** [comment]
[https://i.imgur.com/5p7pNUj.png](url)

[wont let me drag and drop]

dont know how to add add columns 


Blake2s(ccminer) and Skunk (ccminer) will not start mining. X16R and Lyra2REv2 both (ccminer) works just fine.
