### ISSUE TITLE
AMD old gpu not detected

### ISSUE THREAD

**Issue by danialtaghaddos** [nicehash/NiceHashMiner#1317]
Hello, 
I have a rather old AMD GPU and wanted to test mining on it (to learn basics and buy a new one).
Legacy Miner say "No Devices were detected". I dug up the error in AMDOpenCLDeviceDetection file

General info :

Device : ATI HD 4670 (RV730)
OS : Windows 7 x64
Driver version : 13.7 (latest official release)
AMD SDK : 3.0

Here's the error

> AMDOpenCLDeviceDetection::QueryDevices() exception: clGetDeviceInfo

and full debug log file for **check_all_AMD.bat**

> 
> AMDOpenCLDeviceDetection::QueryDevices() exception: clGetDeviceInfo
> [20:35:04] CL Platform vendor: Advanced Micro Devices, Inc.                    
> [20:35:04] CL Platform name: AMD Accelerated Parallel Processing                    
> [20:35:04] CL Platform version: OpenCL 1.2 AMD-APP (937.2)                    
> [20:35:04] Platform devices: 1                    
> [20:35:04] 	0	ATI RV730                    
> [20:35:04] Number of ADL devices: 1                    
> [20:35:04] ATI ADL Overdrive5 API found.                    
> [20:35:04] ATI ADL Overdrive6 API found.                    
> [20:35:04] Found 2 logical ADL adapters                    
> [20:35:04] ADL index 0, id 60704592 - BIOS partno.: 113-AB80701-100, version: 011.022.003.006, date: 2009/05/04 22:07                    
> [20:35:04] GPU 0 assigned: iAdapterIndex:0 iPresent:1 strUDID:PCI_VEN_1002&DEV_9490&SUBSYS_02761043&REV_00_4&39043ADE&0&0008A iBusNumber:1 iDeviceNumber:0 iFunctionNumber:0 iVendorID:1002 name:ATI Radeon HD 4600 Series                    
> [20:35:04] ADL index 1, id 60704592 - BIOS partno.: 113-AB80701-100, version: 011.022.003.006, date: 2009/05/04 22:07                    
> [20:35:04] GPU 0 ATI Radeon HD 4600 Series hardware monitoring enabled                    
> [20:35:04] ADL GPU 0 is Adapter index 0 and maps to adapter id 60704592                    
> [20:35:04] GPU 0 BIOS partno.: 113-AB80701-100, version: 011.022.003.006, date: 2009/05/04 22:07                    
> [20:35:04] Failed to ADL_Overdrive5_FanSpeedInfo_Get                    
> [20:35:04] Failed to ADL_Overdrive5_FanSpeed_Get for default value                    
> [20:35:04] 1 GPU devices max detected                    
> [20:35:04] Specified platform that does not exist                    
> [20:35:04] clDevicesNum returned error, no GPUs usable                    
> [20:35:04] 0 GPU devices max detected                    
> [20:35:05] Specified platform that does not exist                    
> [20:35:05] clDevicesNum returned error, no GPUs usable                    
> [20:35:05] 0 GPU devices max detected                    
> [20:35:05] CL Platform vendor: Advanced Micro Devices, Inc.                    
> [20:35:05] CL Platform name: AMD Accelerated Parallel Processing                    
> [20:35:05] CL Platform version: OpenCL 1.2 AMD-APP (937.2)                    
> [20:35:05] Platform devices: 1                    
> [20:35:05] 	0	ATI RV730                    
> [20:35:05] Number of ADL devices: 1                    
> [20:35:05] ATI ADL Overdrive5 API found.                    
> [20:35:05] ATI ADL Overdrive6 API found.                    
> [20:35:05] Found 2 logical ADL adapters                    
> [20:35:05] ADL index 0, id 60704592 - BIOS partno.: 113-AB80701-100, version: 011.022.003.006, date: 2009/05/04 22:07                    
> [20:35:05] GPU 0 assigned: iAdapterIndex:0 iPresent:1 strUDID:PCI_VEN_1002&DEV_9490&SUBSYS_02761043&REV_00_4&39043ADE&0&0008A iBusNumber:1 iDeviceNumber:0 iFunctionNumber:0 iVendorID:1002 name:ATI Radeon HD 4600 Series                    
> [20:35:05] ADL index 1, id 60704592 - BIOS partno.: 113-AB80701-100, version: 011.022.003.006, date: 2009/05/04 22:07                    
> [20:35:05] GPU 0 ATI Radeon HD 4600 Series hardware monitoring enabled                    
> [20:35:05] ADL GPU 0 is Adapter index 0 and maps to adapter id 60704592                    
> [20:35:05] GPU 0 BIOS partno.: 113-AB80701-100, version: 011.022.003.006, date: 2009/05/04 22:07                    
> [20:35:05] Failed to ADL_Overdrive5_FanSpeedInfo_Get                    
> [20:35:05] Failed to ADL_Overdrive5_FanSpeed_Get for default value                    
> [20:35:05] **1 GPU devices max detected**                    
> [20:35:05] Specified platform that does not exist                    
> [20:35:05] clDevicesNum returned error, no GPUs usable                    
> [20:35:05] 0 GPU devices max detected                    
> [20:35:06] Specified platform that does not exist                    
> [20:35:06] clDevicesNum returned error, no GPUs usable                    
> [20:35:06] 0 GPU devices max detected                    
> 

The GPU supports OpenCL but OpenCL C 1.0. I had no chance with _xmr-stak_, _smrig_ and _Claymore_ as there are basic C language differences between the versions of OpenCL.
Looks like this command is not supported in OpenCL C 1.0

>  static const **__constant** uint

Are there any chances that this issue is resolved by NHMLegacy?

**Comment by nazzier5463** [comment]
I dont think they will make for you such an update for an older GPU. I got Nvidia GT-9500 nicehash not support either. So move on brothers, buy new gpu or used if u really want to know how mining work. I already bought used gpu. Go get it bro!

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
