### ISSUE TITLE
X16R is the wrong choice

### ISSUE THREAD

**Issue by milkcoins** [nicehash/NiceHashMiner#1318]
NHML (v.1.9.0.6) chooses X16R algorithm. However, it is the most not profitable. See screenshots. On the first screenshot all algorithms are on. On the second screenshot X16R is turned off.

![X16R](https://i.imgur.com/0e6Bdt3.png)
![DaggerHashimoto](https://i.imgur.com/sC60Mg8.png)

*KwhPrice = 0.0
Windows 10 2016 LTSB

**Comment by foxwarernd** [comment]
Check the speeds that were set for testing. Most likely, it is necessary to reduce the speed of the X16R algorithm to match real indicators

**Comment by nazzier5463** [comment]
Yeah dont let computer do all your work

**Comment by milkcoins** [comment]
Hmm... I usually trust benchmark.

**Comment by nazzier5463** [comment]
@milkcoins check out this 

> https://reddit.app.link/KlRIvvQTFP

 if you want find out more about x16r.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
