### ISSUE TITLE
AMD Rizen Threadripper 1950x - 50% LOADS

### ISSUE THREAD

**Issue by valxarmov** [nicehash/NiceHashMiner#1319]
AMD Rizen Threadripper 1950x - 50% LOADS -- How to make the work was 100%?

**Comment by foxwarernd** [comment]
Almost all modern processor miners use a level 3 cache for the processor. your processor has 32 mb cache - for one thread you need 2 mb - the total is 16 threads. you have 16 cores and 32 in the hyper-thread - the task manager turns out to show 50% load. it should be

**Comment by valxarmov** [comment]
when I drop any other currency by other miners all 100% but with a nicehash processor in the rest

**Comment by valxarmov** [comment]
What can I do to make the processor 100%

**Comment by dasGiggler** [comment]
Nhlm splits it into 2 groups of 8.  You can edit the config to make it do all 16 but it doesn't make a difference.  If both are reading 50, 50%+50%=100%. 
You can only use the 16 physical cores for the reasons foxwarernd explained.  You should be able to get around 1.2k H/s.  If you have a good CPU cooling solution you can over clock it and get more but watch your CPU temps.  I would not let it get about 70° c.

**Comment by valxarmov** [comment]
AMD Rizen Threadripper 1950x 16-core processor with 32 threads. Perhaps the miner loads only real 16 cores from this and a load of 50%.

Dear developers, tell me how to make work 100% ???????????

**Comment by dasGiggler** [comment]
1.  Have you read and do you understand the other comments?
2.  If there is an issue you need to provide more information to show what it is.  
If your issue is that nhlm only shows a 50% load number you are not understanding how it works.  If there is a nother problem please do explain.  For example tell us what your H/s is at.

**Comment by valxarmov** [comment]
https://imgur.com/UrPGUT5   SCREEN!!!!!!!!

**Comment by dasGiggler** [comment]
The newer version of nhlm has a better user interface, that might give you better info. 
If you want to see the H/s of your CPU Disable your 2 580s and run nhlm for 15 min or so. If you are getting close to 1.2k you are using 100% of your CPU l3 cache.  To increase hashing rate you would have to up your core clock speed, but then you would have to see if the cost of energy for more volts is worth it.  You should want a ratio of  the highest hash rate using the lowest amount of energy.  Unless you get free energy then just watch your temps.

**Comment by valxarmov** [comment]
https://imgur.com/Sm0nN3E  50% works half

**Comment by dasGiggler** [comment]
that is closer to 75%.  to get it working better you need to reconfigure cpu.txt.   go to your nicehash 1.9.0.6 folder then "bin" folder then "xmr-stack" folder.  there you will find cpu.txt file.  at the bottom of the text file it should read 
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 16 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 18 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 20 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 22 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 24 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 26 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 28 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 30 },

],

depending on your memory you might get better performance with all the "no_prefetch" : false.

is your cpu water cooled?

**Comment by valxarmov** [comment]
is your cpu water cooled?   - YES

**Comment by valxarmov** [comment]
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 16 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 18 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 20 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 22 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 24 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 26 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 28 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 30 },

],

**Comment by valxarmov** [comment]
Exactly as you wrote in the file cpu.txt

**Comment by dasGiggler** [comment]
It might be a driver issue.  Do not rely on Windows to update all of your drivers.  Check for a new and up to date motherboard bios and driver's.  I have also found that it runs more stable if using the "local" memory setting in the AMD master settings.

**Comment by valxarmov** [comment]
https://imgur.com/AdczHiH   that's how bad it works only NiceHash!!! I've done 100 tests already. Any CPU Miner works 100% but not yours!

**Comment by valxarmov** [comment]
https://imgur.com/P73hmEl   
**I give even more information!**

**Comment by valxarmov** [comment]
**NEW TEST  Nicehash 1.9.1.0 ALPHA**

https://imgur.com/1gHj7dF

**Comment by dasGiggler** [comment]
It is saying 50% because it it only using 16 physical cores. It will not use the other 16 theoretical threads.   If you want to up your hash rate you need to check that your motherboard's bios and driver's are up to date.  You also need to check all the other drivers.  If they are all up to date try using AMD's master software.

**Comment by GilHacco** [comment]
Listen carefully valxarmov. You ARE using 100% of your CPU power. Windows' display is only telling you what percentage of threads you are using, you don't have to use 32 threads to use all of the CPU's power.

If you want, you can disable SMT in bios, then windows will say you are using 100%. But it doesn't matter.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
