### ISSUE TITLE
Bitdefender detects Gen:johnnie threat

### ISSUE THREAD

**Issue by EvilMonkeyTurds** [nicehash/NiceHashMiner#132]
Other antivirus also detecting threats within this.   What is the deal?

**Comment by pducharme** [comment]
Most mining software are 'flaged' as a threat.  I think it goes back to BitCoin mining when it was minable with CPU/GPU years ago, and someone created a BotNet of mining PC (trojan) by hiding mining software inside the trojan to profit with it at large scale.

**Comment by EvilMonkeyTurds** [comment]
Don't think so, but yes it is also detected as bitcoin miner by online file scanners but I always ignore than one.  It is finding Gen:johnnie.xxxxx not bitcoinminer.
