### ISSUE TITLE
Низкая мощность

### ISSUE THREAD

**Issue by Phil2777** [nicehash/NiceHashMiner#1320]
Здравствуйте, подскажите четыре RX 570 копают только по 20000-24000 тысячи, а раньше было около 60000, что может быть? Даже когда курс еще меньше был, а щас подрос копает также(((

**Comment by RavenouseAnimal** [comment]
как то тоже за последнее время упала добыча, изза радика запустил вместо "полноценного" "легаси"
i7+1050Ti+r7 200 = типа 0.5бакса в мес, хотя в логах только последняя от 10 центов в сутки! приносит
пробовал цпу и жирафа на 2.0.2.6 а радика на легаси оставить, так через какоето время легаси вместо радика лезет в память жирафа, выбивая екскаватор

**Comment by BoB4uK45** [comment]
Опирайся на курсы альтов к битку, а не на курс битка к доллару. Логично, что копая на дагер хашимото эфир по 0.04 битка ты будешь получать меньше чем когда он стоит 0.07. 
Никто не будет платить за майнинг эфира больше битков чем он стоит.

**Comment by RavenouseAnimal** [comment]
про курс все понятно
но запустив тот же xmr-stak из папки nhml получил результат в 10!! раз выше
тоже самое и с excavator, никаких ошибок с сокетом
в итоге сейчас запустил xmr-stak , молотит тяжелую монеру на 0.5КН суммарно (проц+1050+R7 200)
при использовании этого алгоритма, еще заметил, результат не всегда до найса доходит..то сокет отвалится, то еще что, а тут за сутки 100%

**Comment by valxarmov** [comment]
У меня проблема тоже но чуть в другом обратите внимания у вас процессор работает на все 100% при майнинге? У меня на 50%

**Comment by RavenouseAnimal** [comment]
работать ,то работает..но
при работе с nhml радеон вроде как задействован, но как показывает практика система уверена что "копает" 1050
а если все запустить на "стеке" работают все трое(проц и две видяхи)
но такое ощущение что в пол силы, хотя аида так же показывает загрузку 100%
если проц загружен не на 100%, то в конфиге ручками можно выставить affinity на каждое ядро..но прибавку это даст мизерную

**Comment by S74nk0** [comment]
Please write in English on GitHub. 

Closing issue
