### ISSUE TITLE
Can not mining with power consumation switch features if profit go under 0

### ISSUE THREAD

**Issue by Giulio1974** [nicehash/NiceHashMiner#1321]
Minimum mining profit fetures can not disable , even if you set 0 mining stop when profit is less the 0
and is correct , but if i whant to mining with power consumation switch even if the profit go under 0 can not.

So the problem is : Mining at the best algo on the best profit even if in that moment profit go down 0
Solution : possibility to set minimum mining profit negative or possibility to disable this featurs with flag

Thank you

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMiner/commit/956df5f1b64308e06043d7f066153c121715fdb7) implements this feature.

Will close issue on next release
