### ISSUE TITLE
AMD Radeon RX 580 8gb OC Overclocking

### ISSUE THREAD

**Issue by 851d229** [nicehash/NiceHashMiner#1322]
Hi everyone,

I don't saw any post on this one.  I have 3 RX 580 8gb OC and I've started to mine with the most recent NiceHash version.  I have installed the Afterburner app and tried some parameters but I'm not sure what is the most optimal parameters to have to optimize the Hashrate.  Right now, I hit about 2$ per day,  and I'm not sure the parameters or well configured.  Also, do you recommend update the bios of these cards?

**Comment by taweeza** [comment]
ใช่

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

At the moment we cannot provide you with Overclocking (OC) support. NiceHash Miner will try different algorithm settings that can be set via the Extra Launch Parameters and that do not require administrator privileges and system restarts/reboots. 

Please open issues for feature requests and/or bug reports. For support contact support@nicehash.com
