### ISSUE TITLE
Nicehash Miner 1.9.0.5 with .6 hotfix is showing profitable but unpaid balance not incrementing.

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1324]
Hey all.. 

Fresh windows 10 install with updates, and latest NVIDIA driver for K80s.  Have good hashrate in CMD window, and Legacy GUI says i am profitable, yet, unpaid balance not incrementing.  The Nicehash dashboard is also showing no hashes for this worker, and unpaid balance and worker stats are not moving.

Not sure what to check at this time.  I have tried different locations as well, with the same results.

Any ideas ?? 

**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by ghost** [comment]
i have tried now to upgrade my cuda version to 9.2.  No good still.  I have also downloaded ccminer directly, and, still the same.  I started an older setup with older GRID GPU just to test.  That server has registered all relevant information and is cranking along (well everything is relevant).  Still have the same results on this new server.  It registers, but, no Hash Value and unpaid balance does not increment. Any Suggestions ?

**Comment by ghost** [comment]
it is only happening with Lyra2Z as i get hashes recorded with other algorithms when running ccminer on those.. if this is a newbie thing, please let me know ....

**Comment by ghost** [comment]
Going to try Lyra2z on a different mining pool and then try different wallet, etc..

**Comment by S74nk0** [comment]
Issue related to old nhm build/version. Please update to latest version and open a new issue for bugs or features.
