### ISSUE TITLE
Let us disable Nvidia stats (NVML and NVAPI queries)

### ISSUE THREAD

**Issue by KOTzulla** [nicehash/NiceHashMiner#1327]
Create checkbox in setting to disable updating of Nvidia gpu stats, nvidia driver lagging so much when you query GPU stats (temp, fan, etc.) if you have many GPUs. Please.

**Comment by StronkMan** [comment]
Using power monitoring in GPU monitor tools causes micro stutter. [2110289/2049879]

the issue had been opened for 2 months since 398.XX

**Comment by S74nk0** [comment]
Duplicates https://github.com/nicehash/NiceHashMinerLegacy/issues/1602
