### ISSUE TITLE
Everytime when i start the NHML, missing files

### ISSUE THREAD

**Issue by kenjioneway** [nicehash/NiceHashMiner#1328]
When I start up, I get an image error every time.

Antivirus is set to exclude.

why?

![default](https://user-images.githubusercontent.com/42944745/44998043-5c924580-afed-11e8-8c0b-a6dd06a364d2.jpg)

**Comment by foxwarernd** [comment]
option two: 1) antivirus 2) broken drive. check

**Comment by kenjioneway** [comment]
thx.

but i did both.

if i stop NHML, mining files are exist.
but when i start, the alert shows.
and i click Yes, 'bin' directory vanish. 
and re-download.

**Comment by kenjioneway** [comment]
resolved.

sorry, i didn't check windows defender.

**Comment by nazzier5463** [comment]
please close this issue. thank you

**Comment by DTG123** [comment]
I reported this before. The xmrig folder is empty even after you download the miners. 

As was suggested to me, make a text file, blank should work, save as xmrig.exe and put in that folder.

**Comment by thomaswburrows85** [comment]
im having the same issue, i have multiple versions of this software saved in one folder and is in my exclusions and no anti virus at this time

**Comment by nazzier5463** [comment]
> im having the same issue, i have multiple versions of this software saved in one folder and is in my exclusions and no anti virus at this time

check WIndows Security > Virus & Threat Protection. Add your exclusion, needed for AV & Windows Security

**Comment by thomaswburrows85** [comment]
So I found out if I turn my real time protection off it works

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 16, 2019 at 12:28 AM, nazzier5463<notifications@github.com> wrote:   

im having the same issue, i have multiple versions of this software saved in one folder and is in my exclusions and no anti virus at this time


check WIndows Security > Virus & Threat Protection. Add your exclusion, both needed for AV & Windows Security
