### ISSUE TITLE
Nvidia vGPU cards not detected correctly

### ISSUE THREAD

**Issue by UserMonkey** [nicehash/NiceHashMiner#133]
When using NVidia vGPU (GRID K2) the underlying vGPU's aren't detected. (e.g. K260q). Parsing through the GRID card directly to a VM is detected.

NiceHashLegacyMiner does complain that the drivers are old and should be updated however, these are currently the most up to date drivers according to the Nvidia website.

Log file is attached.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1210382/log.txt)

**Comment by DillonN** [comment]
The CUDA API is returning that there are no CUDA-capable devices present, which is usually caused by an improper driver version - hence the warning. I'm not too familiar with GRID devices, but there are a couple things you can try that might work

Try running some miners manually. If they fail with no CUDA devices then the problem is with CUDA not working on your GPU

You can try different drivers which may better support CUDA, as well as looking through related settings in the NV control panel

If you're connecting with Remote Desktop Protocol that may interfere with CUDA as well

**Comment by UserMonkey** [comment]
Miners run manually also failed with no CUDA errors.

I installed the CUDA 8.x tool kit and the driver that come with that but still the same error is reported.

I can open the NV Control Panel and when I look at system info it shows the device is CUDA capable for 3.0 and tell me how many CUDA core are available among other things.

I have installed vnc for remote access as Remote Desktop does apparently cause issues, without vnc the NV Control panel wasn't available. 

I'm guessing the next step is to probably install visual studio on the machine so I can run the NV device-query program in debug and find what it doesn't like.

**Comment by gridk2** [comment]
Did you find a solution to this problem?
I have the same issue using two Nvidia Grid k2 cards installed on a Cisco UCS server. (using full pass-through to a win 10 VM).
The current hash rate for ETH is only 1,4-1,9 MH per card.

**Comment by UserMonkey** [comment]
No solution as yet.
I have installed visual studio and can compile the device-query program, but as expected it just says no CUDA device when run. 
This CUDA stuff is all new to me so working out exactly where the problem is might take me a while.

**Comment by gridk2** [comment]
For me is detecting the cuda cores but the Hash rate is very low (ETH 1,9 MH).

**Comment by UserMonkey** [comment]
Have been in contact with Nvidia. The card will work in pass-through mode, performance won't be great since they are old, etc.

When it come to vGPU GRID cards can't do CUDA.  The user guide for version 4 states the following:
1.5. GRID vGPU features

This release of GRID vGPU includes support for:

    DirectX 12, Direct2D, and DirectX Video Acceleration (DXVA)
    OpenGL 4.5
    NVIDIA GRID SDK (remote graphics acceleration)

CUDA and OpenCL are supported on these virtual GPUs:

    GRID M60-8Q
    GRID M10-8Q
    GRID M6-8Q
    GRID M60-8A
    GRID M10-8A
    GRID M6-8A

Version 5 doesn't support the GRID K1 and K2 cards anymore. However the replacements for these the P4, P40 and P100 do.
