### ISSUE TITLE
getting socket was closed remotely by pool

### ISSUE THREAD

**Issue by tusharantal** [nicehash/NiceHashMiner#1330]
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by tusharantal** [comment]
hello... i am getting socket was closed remotely by pool from last few days now .... whichever service location i try i get the same error.... i am facing this error on daggerhashimoto algorithm....when i uncheck daggerhashimoto other algos work fine.... i am posting a pic along....i hope you provide me with a resolution asap...
![screenshot 6](https://user-images.githubusercontent.com/43071446/45227441-1f280380-b2de-11e8-931c-076062ce4bf8.png)

**Comment by foxwarernd** [comment]
post your log file here

**Comment by foxwarernd** [comment]
Tried to change location?

**Comment by tusharantal** [comment]
Yes i have tried changing all server locations still getting same error.... I flushed dns it worked for few days but now i am facing the same problem again ...and even dns flushing is not working

**Comment by S74nk0** [comment]
Issue related to old nhm build/version. Please update to latest version and open a new issue for bugs or features.
