### ISSUE TITLE
ExtraLaunchParameters for Claymore CryptoNote Miner is not working

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1331]
Can you guys fix annoying bug in the NHML with ExtraLaunchParameters for Claymore's CryptoNote Miner?
This section in GUI not working for this miner.
Logs says what parameters can't parsed. Claymore Dual Miner with ExtraLaunchParameters works perfectly.
Tested on 4 rigs with NHML 1.9.0.{3-6} and 1.9.1.0.

**Comment by S74nk0** [comment]
Issue related to old nhm build/version. Please update to latest version and open a new issue for bugs or features.
