### ISSUE TITLE
50% hashrates increase posible with Cryptodredge and T rex

### ISSUE THREAD

**Issue by vyncy** [nicehash/NiceHashMiner#1332]
Cryptodredge and t rex are new revolutionary miners because they increase hashrates of some algos like for example lyra2z,lyra2rev2 and cryptheavy by 50% or even more on some cards.

T rex is really good at x16r, increase around 30%

So I guess these should be implemented ASAP in NHML

**Comment by angelbbs** [comment]
Already implemented in NHML Fork Fix 9.1

**Comment by nazzier5463** [comment]
@angelbbs any plan for ethlargement implemention ?
and please update readme because download link (release page) redirected to here, not NHML Fork Fix release pages.

**Comment by Balzhur** [comment]
@angelbbs implemented but do not work. Phoenix, CryptroDredge and hsrneoscrypt seem to be banned by NH:
```
[20:31:39] INFO  - Selected pool: cryptonightheavy.eu.nicehash.com:3364
[20:31:39] INFO  - Selected algo: CryptoNightHeavy
[20:31:39] INFO  - Intensity set to 6
[20:31:39] INFO  - CCminer TCP API: server started on 127.0.0.1:4005
[20:31:39] INFO  - Start user session
[20:31:39] ERROR - cryptonightheavy.eu.nicehash.com:3364: Connection was closed by pool
[20:31:39] INFO  - Reconnecting after 15 seconds
```

**Comment by Joshwaa2010** [comment]
Yes please add CryptoDredge to NHML for Lyra2rev2.

**Comment by angelbbs** [comment]
Already added in NHML Fork. https://github.com/angelbbs/NiceHashMinerLegacy/releases

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
