### ISSUE TITLE
NiceHash 1.9.1.0 Alpha shows the wrong values. 

### ISSUE THREAD

**Issue by deeppurple1968** [nicehash/NiceHashMiner#1333]
NiceHash 1.9.1.0 Alpha shows the wrong values. 
When you start nicehash it shows everything correctly, but after a while it shows incorrectly:
![bug](https://user-images.githubusercontent.com/15851040/45958539-586fab80-c020-11e8-843a-9a53e95929cd.PNG)
In this case, HD7950 works on CryptoNigth v7 and RX580 on Dagger Hashimoto, however NiceHash shows both of them as CryptoNyght V7

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
