### ISSUE TITLE
Not Clearing non-active algo in NHML 1.9.1.0a

### ISSUE THREAD

**Issue by SuperBartimus** [nicehash/NiceHashMiner#1335]
It seems that when NHML moves on to new algos and there's nothing mining the current one, it leaves reference to the one it left by showing the Algo name and its total, but no GPUs.  This doesn't seem to occur with CPU mining from what I can tell.  Can we get this cleaned up so that it only shows the currently active algos?
Example:
![radmin_2018-10-04_09-58-15](https://user-images.githubusercontent.com/22985127/46483087-78d7fc80-c7bc-11e8-9c68-035f68102887.png)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
