### ISSUE TITLE
when is next nhml update comming?

### ISSUE THREAD

**Issue by tusharantal** [nicehash/NiceHashMiner#1336]
it has been a while since a new nhml update ... when is update comming and what is expected from update?

**Comment by alimashhad** [comment]
سلام 
من بااین مید که بتوانم در محیط گیت هاب .در فضای ابری ماین کنم وارد هاب شدم البته که ان موضوع از اطلاعت کم من نتیجه میشود

**Comment by PhoenixAdageyudi** [comment]
translation... lol 


Hello 
Mead, however I can in my GitHub cloud In mine I got into a hub of information, of course, that that is the result of my low

**Comment by PhoenixAdageyudi** [comment]
my guess is that the bear market is destroying shitcoins and NH is losing a lot of revenue.. may be this is causing them to scale back on development which would be a disaster move.. also i would imagine competition from other like platforms is compounding this...

they need to either step up and get things rolling to maintain or regain the lead in this market, find another way to generate revenue and pivot from this, or hopefully not but continue to stagnate until they lose a client base 

check out the activity its not exactly encouraging

https://github.com/nicehash/NiceHashMinerLegacy/graphs/commit-activity

**Comment by DTG123** [comment]
NH has a shit exchange rate, didnt know running negative was a thing. I'm not mining so NH can pay back their debt, I'm mining for myself!

**Comment by Balzhur** [comment]
Guys, there is a [Fork of NHML](https://github.com/angelbbs/NiceHashMinerLegacy/releases/tag/Fork_Fix_9.5) with new miners (xmrig for CNv8, CryptoDredge for skunk, T-Rex for x16) and even embedded overclocking scripts for each miner (optional).

**Comment by DTG123** [comment]
> 
> 
> Guys, there is a [Fork of NHML](https://github.com/angelbbs/NiceHashMinerLegacy/releases/tag/Fork_Fix_9.5) with new miners (xmrig for CNv8, CryptoDredge for skunk, T-Rex for x16) and even embedded overclocking scripts for each miner (optional).

and who are you???  sorry not downloading anything from a link to a sketchy russian language page. dont know you, dont see any credentials, NOPE not blindly following it.

**Comment by Balzhur** [comment]
@DTG123, first, there is english AND russian at that "sketchy" page. Second, credential are on that page for it's a fork (google it) of NHML. And third - there is always a choice, one can follow the link, analyze a code difference if being paranoid and decide whether to use it or not. Or one can stick to using NHML and lose profit due to outdated miners... Or move to some other pool/miner...

The beauty of open source - if DillonN is not willing to update - there will be others who are. I, for one, trying to help and improve NHML with overclock scripts for different algo and GPU, what about you? Some random guy without a single repo on github? move along.

**Comment by Bige086** [comment]
> 
> 
> @DTG123, first, there is english AND russian at that "sketchy" page. Second, credential are on that page for it's a fork (google it) of NHML. And third - there is always a choice, one can follow the link, analyze a code difference if being paranoid and decide whether to use it or not. Or one can stick to using NHML and lose profit due to outdated miners... Or move to some other pool/miner...
> 
> The beauty of open source - if DillonN is not willing to update - there will be others who are. I, for one, trying to help and improve NHML with overclock scripts for different algo and GPU, what about you? Some random guy without a single repo on github? move along.

Testing your fork, its pretty great. Just wondering how you get paid for adding all those 3rd party miners? Is there an additional fee?

**Comment by Balzhur** [comment]
@Bige086 , it's not my work (I only nagged the dev to pass algo name and devices list to his overclock scripts so I can overclock my cards differently for different card/algo combination. These changes are committed but not available yet in a binary release, work great for my self-compiled version, though).

Regarding the additional miners - I do not use any but T-Rex and Cryptodredge cause for my Nvidia cards those are most profitable at the moment, so cannot say for whole lot of them, but those two have 1% dev-fee as many other 3rd party miners in original NHML have.

As far as I know the dev (angelbbs) had implemented his own dev-fee during benchmarking and ONLY during benhchmarking. I'm using that project for more than two month and I do not see any dev-fee or suspicious activity.

**Comment by niask11** [comment]
@Balzhur And when this version with OC profiles capabilities will be released? I'm rather interested in it too...

**Comment by Balzhur** [comment]
@niask11, I can only guess :) So far he did new binary release approximately once a week, so I'd say in a few days...

**Comment by Bige086** [comment]
> 
> 
> @niask11, I can only guess :) So far he did new binary release approximately once a week, so I'd say in a few days...

Well fantastic work, to say the least.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
