### ISSUE TITLE
X16r Not working for amd

### ISSUE THREAD

**Issue by fortking** [nicehash/NiceHashMiner#1338]
I did some digging because the X16r in the NHML 1.9.0.5 ever since X16r was released, has never worked. I did some digging myself and have found that the nicehash miner adds a variable that completely makes the miner fail and quit on the spot. I can manually remove that variable in my own .bat and it works just fine. 

My .bat: 

set GPU_FORCE_64BIT_PTR=0
set GPU_USE_SYNC_OBJECTS=1
set GPU_MAX_ALLOC_PERCENT=100
set GPU_SINGLE_ALLOC_PERCENT=100
set GPU_MAX_HEAP_SIZE=100

```
sgminer.exe -k x16r -o stratum+tcp://x16r.usa.nicehash.com:3366 -u 3EKNRcB6xa1SLWErmvSVdEic7FLRcXd26h -p x -X 256 -d 0
pause
```

here is what the miner is creating: 

`--gpu-platform 1 -k x16r --url=stratum+tcp://x16r.usa.nicehash.com:3366 --userpass=3EKNRcB6xa1SLWErmvSVdEic7FLRcXd26h.PC -p x --api-listen --api-port=4000 --device 0`

The culprit is the --gpu-platform. 

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2471458/log.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
