### ISSUE TITLE
Feature request:  Pause on battery power option

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#1339]
Just wondering if there can be a power state option so if My computer sees it self on battery for a certain amount of minutes/seconds that the miner will stop  till power is on for a certain amount of time.  I'd like to  try and keep my computer on as long I can before the battery backup shuts the pc down.

Thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
