### ISSUE TITLE
Creators Update Broke for Me

### ISSUE THREAD

**Issue by JakeHillion2** [nicehash/NiceHashMiner#134]
The windows 10 creator's update forced itself upon me the other day, and ever since I have been having this issue with NiceHash. With the new algorithms added in the latest version, it now occurs on benchmarking whereas before it occurred only on startup.

[http://prntscr.com/g6924y](http://prntscr.com/g6924y)

**Comment by drkskwlkr** [comment]
@JakeHillion2 Ye olde #32 rears its ugly head again?

**Comment by DillonN** [comment]
Windows Update can mess with the drivers, I've made a [Wiki page](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Troubleshooting#opencl) for this now with some more info and fixes/workarounds
