### ISSUE TITLE
Prospector Miner Update Please?

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner#1344]
Hello, 

The Prospector miner has been updated and there is performance increase.
Please can nhm be enhanced to run the latest version of this miner.

I have tried to replace the prospector.exe with a later version and the latest version, but it is not starting.
I can not work out why.

I was told this must be undated by the nicehash developers, please

Thanks

Regards

**Comment by S74nk0** [comment]
Issue related to old nhm build/version. Please update to latest version and open a new issue for bugs or features.
