### ISSUE TITLE
Errors in HTML v1.9.0.7

### ISSUE THREAD

**Issue by GeoSkyLands** [nicehash/NiceHashMiner#1345]
Available 4 graphics card Radeon RX 460 (1-c 4 GB RAM, Asustek, not overclocked; 3-2 GB RAM, MSI, overclocked), motherboard Gigabyte 970A-DS3P, CPU AMD FX 6100, RAM 4 GB, BP 400W, NHML v1.9.0.7, Windows 10 version.
1st question: when using the pool (4 graphics cards) CryptoNightV8 does not display the mining progress (on the chart and the balance does not increase). Viewing the result in the process window gives 0% of the progress, and on the graphics cards gives "error receiving data." The result does not depend on the number of connected cards or CPU.
2nd question: in the formation of a pool of 4 graphics cards for CryptoNightHeavy losing "extreme" map ("map not found"). It was necessary on 3 graphics cards (1-c 4 GB of RAM; 2 - with 2 GB of RAM) to start production of CryptoNightHeavy, and on the last - CryptoNightV7.
3rd question: when connecting to the pool of graphics cards on the processor computer is cut down. Consumption of each card is around 45-50 W (maybe a little more) that is around 200-220 W, the CPU is 95 W. Seems to have stock, and cut down the PC like the CPU is overheating. And kind of sin that the PSU is weak, but still decided to tell you something for something in this bundle is affected.

**Comment by S74nk0** [comment]
Issue related to old nhm build/version. Please update to latest version and open a new issue for bugs or features.
