### ISSUE TITLE
Skunk losing connection every 1.5 hours for 3 minutes while still mining

### ISSUE THREAD

**Issue by cheetah1042** [nicehash/NiceHashMiner#1346]
I have 3 rigs AMD rx 570 4gb + 1 rig 1080ti evga

I unchecked all expept Skunk, because even if it's making more profit than x16r and dagger - it's mining them. 

But the mining isn't soft like on other algos and have problem which I see like temp ban for my AMD rigs. 
Every 1.5hours they lose connection and after trying around 150 seconds to reconnect - restart the miner automatically and start mining again with no problems. If I restart ot manually it starts mining ok earlier. This problem don't happen to 1080ti rig. The miner thinks it's still mining and it's losing the same amount of electricity but didn't send any shares in the same time it is showed it's offline and the graph is experiencing bottom as expected.

https://prnt.sc/lcjl2v
https://prnt.sc/lcchms
https://prnt.sc/lb2i0d
https://prnt.sc/ldc3bl

I saw there is an xnsub option and tried to ad #xnsub option to the config file it is loading, but even if I save the file after loading - it's again without this add to the server's link. I guessed if I add it it will be subbed anddd won't lose connection like the 4rd rig which is subbed and I have no idea why 3 rigs are not and 4rd is subbed.

I guess it's finding too often shares and it's flooding with them and getting some kind of temp ban, but I'm a noob so I need help about this.

Thank you for your suggestions!

**Comment by S74nk0** [comment]
Issue related to old nhm build/version. Please update to latest version and open a new issue for bugs or features.
