### ISSUE TITLE
Keeping up with more profitable Algo

### ISSUE THREAD

**Issue by SuperBartimus** [nicehash/NiceHashMiner#1350]
Is the NHML team going to implement anymore new algos any time soon?
Finding algos like [X22i](https://suqa.org/file/2018/10/x22i-proof-of-work-algorithm.pdf) are (at the time of this posting) more profitable than most anything else.  Also, X22i is ASIC, FPGA **and** Quantum resistant.  In other words, NHM(L) needs more GPU favorable algos.

Just think that NH should think a lot about the little people too, lest we all start selling our hardware... especially after the recent value plunge in crypto.  If there's more of us mining, there's more revenue for NH.

**Comment by angelbbs** [comment]
Use nicehash miner legacy fork fix. It contains new and modern miners. More profitable with existent algorithms

**Comment by nerdatwork** [comment]
@SuperBartimus Just so you know there is no such thing as "asic/fpga" resistant algo.

**Comment by greg121078** [comment]
@angelbbs  Hello where do you find these fix legacy???

**Comment by angelbbs** [comment]
@greg121078 https://github.com/angelbbs/NiceHashMinerLegacy/releases
