### ISSUE TITLE
Include mkxminer V4 Lyra2Z

### ISSUE THREAD

**Issue by winmkx** [nicehash/NiceHashMiner#1351]
Hello!
mkxminer version 4 dropped support for Lyra2rev2 (because of ASICs out there) but added support for Lyra2Z. Which is the best for AMD cards:
Vega64: 7.4MHs
RX 580: 3.7MHs
RX 480: 3.5MHs
R9 390: 1.8MHs

Please add mkxminer V4 with Lyra2Z.
Any questions / requirements - please let me know.

PS: mkxminer also has API support now.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Feature implemented this is teamredminer
