### ISSUE TITLE
Claymore Dual Opens but never starts hashing (AMD)

### ISSUE THREAD

**Issue by MeatThePyro** [nicehash/NiceHashMiner#1356]
Running 8 AMD cards, everything benchmarked. I ran Claymore dual from the folder in the NHML files, and it started fine, set the DAG, and started hashing within about 15 seconds.
When I open up the GUI and hit the start button (already finished benchmarking everything), it puts all of my cards on Claymore dual, the DAG never builds, and after about a minute of hashing at 0.000 for all cards, the GUI opens a new claymore instance and closes the last one. 

I have tried disabling all claymore dual mining options, and the cards mine other algos just fine.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
