### ISSUE TITLE
NiceHash Miner Legacy v1.9.0.9 does not detect Radeon RX 580 GPU

### ISSUE THREAD

**Issue by RolandoWin** [nicehash/NiceHashMiner#1357]
Receive a cordial greeting.
NiceHash Miner Legacy v1.9.0.9 does not detect my Gigabyte Radeon RX 580 8GB Video Card, I would appreciate if you can help me solve the problem.
Thank you very much for your attention!
![nicehash-2018-12-12_03-18-56](https://user-images.githubusercontent.com/44470326/49920665-00a34c80-fe79-11e8-9e95-df1125eb9183.png)
![software radeon 2018-12-13_01-48-40](https://user-images.githubusercontent.com/44470326/49920748-5841b800-fe79-11e8-900e-660245a8508f.png)
![hardware radeon - 2018-12-13_01-47-58](https://user-images.githubusercontent.com/44470326/49920750-5bd53f00-fe79-11e8-8420-65eb9bb6f2e9.png)

**Comment by foxwarernd** [comment]
need log from nhm\logs

**Comment by zcomputerwiz** [comment]
Make sure you have the latest version of the AMD driver and have set compute mode.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
