### ISSUE TITLE
ESET NOD32

### ISSUE THREAD

**Issue by Blisk** [nicehash/NiceHashMiner#1358]
Whenever I try to start nicehash NOD32 popsup.
Why don't you just rename that file in nicehash so NOD32 will not detect it???
I have no problem with claymore or cgminer or sgminer with NOD32, but nicehash is always blocked.
I think renaming name of files will solve alot.
![2018-12-23 13_08_11-eset nod32 antivirus](https://user-images.githubusercontent.com/2773050/50383459-20761400-06b4-11e9-8807-3595b31e874f.png)

**Comment by S74nk0** [comment]
@Blisk Whitelist the whole nhm path.
