### ISSUE TITLE
Crashes while gaming on GPU1

### ISSUE THREAD

**Issue by niknewb** [nicehash/NiceHashMiner#136]
Sorry for posting here, I don't know if this is a miner issue but I'm really bored with this thing.So basically i have 2 GPUs( 1080TI) and while I'm gaming I turn off NHML on GPU1 and let it work on GPU2 only (cpu isn't involved). Just 5-15 minutes after any game will crash(in the best case scenario, sometimes it crushes the entire pc).
P.S Tested with and without OC. Same thing for both cases. Right now I'm using NHML 1.8.1.0- Pre3(this thing, however, seems to appear on NHM 2.0.0.11 as well.
P.P.S My setting are almost fully default. I've only selected "Hide mining windows" and "Minimize mining windows"
P.P.P.S I'm on latest windows 10 16257 build with nvidia 385.12 drivers installed.
Any advice or tips on which causes this issue is greatly appreciated. Thanks!

**Comment by adem4ik** [comment]
Check the RAM and vRAM memory usage during mining and gaming.

Anyway you may try to increase page file size in your OS.

**Comment by niknewb** [comment]
Thank for your reply. My paging file is already set to 32GB. Any more suggestions what can I do with these crashes? :(

**Comment by DillonN** [comment]
It does sound like RAM could be a problem, are you able to observe memory usage while gaming and see how high it gets during the crash (with e.g. Afterburner OSD)? Also make sure you do not have SLI enabled as it would cause this (although you would probably get issues while just mining if SLI were enabled)

**Comment by niknewb** [comment]
Thanks for the answer. Ram usage in okay, around 7-8GB\12GB( in BO3, for example). Sli always has been disabled.I have now set even 50GB swap file and it still crashes... Don't even know what to do, probably I will have to stop mining while gaming since I have absolutely no idea how to deal with this
EDIT: I've got a pretty interesting error right now when game crashed once again. My videocard driver crashed completely and windows said something like: "Driver failed to start. Using microsoft basic display driver". I guess my nvidia driver just freezes if I launch miner and games together. Idk why...

**Comment by Cryptominer937** [comment]
The mining software may not be selecting the one that is your primary video card as GPU1 your primary Graphics card could be GPU2, Or the issue could be Overclock.

**Comment by DillonN** [comment]
@Cryptominer937 I thought of that too but I think you'd notice that the framerate is very low and/or VRAM usage is higher

@niknewb Is it just one miner type that runs to cause the crash or do any of them do it?

**Comment by Cryptominer937** [comment]
If Eth or Zec is being mined there would be minimal FPS drop but it would cause Driver crashing due to GPU Ram overflow.

**Comment by niknewb** [comment]
Thanks everyone for replying. 
@DillonN  I will try different miners tomorrow.
I also think about full clean driver re-installation using DDU and slightly older 384.94 WHQL driver because I guess the issue is on my side

**Comment by Outofit08** [comment]
I had this issue as well but only when I play Fortnite. Once with another game. I suggest you restart your computer run both cards at default no overclock then run NH then run your game and test that out. It worked for me. Also after the recent update on Fortnite i haven't had any crashes both cards overclocked 
+130Mhz 
+400 MHZ mem both 1080ti SLI disabled.

**Comment by niknewb** [comment]
@DillonN Crashes on most algos here with Black Ops 3 (can't test them all, too much) . Without mining software it can run for hours with no problems whatsoever. I also noticed some extreme slowdowns sometimes, game just starts running at like 1-2 fps for few seconds, sometimes it recovers after this and continuous with normal framerate and sometimes it just drops to 0-1 fps and crashes shortly after( i guess this happens when miner is switching algos, but I'm not 100% sure) . I tried selecting only one algo (Lyra2rev2) and it is slightly more stable but still crushes the game in the end( it just takes more time to occur).  
@Outofit08 I'm pretty sure I've tried running them on default- same effect. This is extremely weird why could it possible crush my PC if I have plenty of Ram and tons of swap with GPU2 pretty much isolated...  I have even tried clean installing all latest drivers with DDU- no effect once again.

**Comment by DillonN** [comment]
@niknewb I don't play BO3 but from what I hear it is a very demanding game in VRAM. I know you said you monitored RAM usage but could you try monitoring VRAM usage? Hitting the VRAM cap would give exactly the behaviour you're getting (smooth framerates with frequent dips to very low framerates, with possible crashing eventually). At the VRAM cap the game will frequently need to load textures that are cached on your system RAM, a slow process that causes framerate to go to pretty much 0 until it's done. It does sound bizarre that you could hit the VRAM cap on an 11GB card but BO3 uses up to 10GB on its own.

Also @Outofit08's suggestion is good, I too have 2 1080 Tis and I find that some OC settings don't fully go away until after a restart.

**Comment by niknewb** [comment]
@DillonN thanks for your suggestion. I will try monitoring vram usage. BO3 is indeed extremely hungry game and when I was play without mining i noticed that this game fills up vram to almost 11GB just in minutes after starting playing it... But again, the most interesting part which gives me headaches is why it won't crush in hours  without miner while starting miner on a second GPU will just wreck everything. I guess there is  still a dependence between main GPU (GPU1)  vram\GPU usage and miner stability?
P.S I will also try limiting Vram usage via game cfg and report back if it will fix something

**Comment by niknewb** [comment]
I will close that issue because problem has been fixed. This is one of the weirdest issues I had in my life but it was fixed by:
1)Clean install with DDU of 385.28 drivers
2)Updating NHML to 1.8.1.1 Pre3
3)Tweaking game's cfg file allowing it to use all Vram that I have
P.S I did all these 3 things at once and don't know which step fixed my crashing while both mining and gaming
P.P.S My cards are fully stable now at a pretty high overclock
