### ISSUE TITLE
-i 23 intensity extra parameter not working NHML 1.9.0.10

### ISSUE THREAD

**Issue by psynauty** [nicehash/NiceHashMiner#1367]
Trying to increase intensity of trex miner by using -i 23 on extra launch parameters but it gets ignored and default of 20 is used instead

**Comment by Splongie** [comment]
I have the same problem. Haven't found a way to get it to work. 
A fix was listed in an update so that the trex miner command line parameters would work but it didn't help.

**Comment by Pashted** [comment]
same here with extra parameter --intensity for gminer 1.45. nhml 1.9.0.23.
the interesting thing is that the parameter --templimit works fine

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
