### ISSUE TITLE
New T-Rex miner released (Minor x16r improvements)

### ISSUE THREAD

**Issue by anazz20** [nicehash/NiceHashMiner#1368]
New T-Rex miner released, minor x16r improvements, https://github.com/trexminer/T-Rex/releases

Add algos: x16rt (Veil), sha256q (Pyrite)
Minor performance improvements for x16r, bcd, x22i and other x16-like algorithms
Multiple web monitoring page improvements
Switch between multiple config files dynamically (put your *.config files into the miner directory)
Dark theme
Linux watchdog is now available. Download at https://github.com/trexminer/T-Rex-Watchdog/releases
Bug fixes:

cURL/SSL compatibility issue on newer Linux distros (Ubuntu 18, Debian 9)
Miner wouldn't start if NVML wasn't installed

**Comment by serh39** [comment]
> New T-Rex miner released, minor x16r improvements, https://github.com/trexminer/T-Rex/releases
> 
> Add algos: x16rt (Veil), sha256q (Pyrite)
> Minor performance improvements for x16r, bcd, x22i and other x16-like algorithms
> Multiple web monitoring page improvements
> Switch between multiple config files dynamically (put your *.config files into the miner directory)
> Dark theme
> Linux watchdog is now available. Download at https://github.com/trexminer/T-Rex-Watchdog/releases
> Bug fixes:
> 
> cURL/SSL compatibility issue on newer Linux distros (Ubuntu 18, Debian 9)
> Miner wouldn't start if NVML wasn't installed

WTF?

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
