### ISSUE TITLE
Suggestion: Bigger "Save and close" button to make space for RU translation

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#137]
Currently we use "**Сохранить**" in ru.lang for "**Save and close**" button translation. But it is not the proper one. The translation is so short because there is not enough space for the full string "**Сохранить и выйти**".

So my suggestion is too make "**Save and close**" button width same as "**Close without Saving**".
![image](https://user-images.githubusercontent.com/4707112/29163969-17d140a0-7dcf-11e7-9b5d-bccc1b91f587.png)

Here is the comparison of the lengths, so it should be enough for the proper RU translation:
```
Сохранить и выйти
Close without Saving
```

**Comment by DillonN** [comment]
This should be done in commit 280f542be4df01b5c987ed1da52f254c69f1f7e8

**Comment by adem4ik** [comment]
Thanks for improvement!
