### ISSUE TITLE
BEAM mining, so many rejected shares on AMD & nVidia 

### ISSUE THREAD

**Issue by electricdelicate** [nicehash/NiceHashMiner#1372]
Since few hours I got almost only rejected shares with booth miner because invalid nonce on AMD and nVidia. 
![grafik](https://user-images.githubusercontent.com/40469299/52125725-aed3a300-262d-11e9-9b79-22ed8690bd8d.png)
Can anybody confirm that?

**Comment by Frageron** [comment]
Yeah, i got same problem from time to time. Like 10 minutes it accepting all and then 5-10 minutes rejecting all with same message.

![untitled](https://user-images.githubusercontent.com/30486776/52130017-cd18bd80-2684-11e9-857c-0541559f3d4a.png)

**Comment by electricdelicate** [comment]
hmmmm .... official statement minutes ago:
https://twitter.com/NiceHashMining/status/1091349078842265600

And what is with the B-Miner (AMD) issue?

**Comment by electricdelicate** [comment]
No more rejected shares since hours, problem whitout new miner solved?

**Comment by rainbowfc** [comment]
am i the only one getting rejected shares with AMD GPU' s? I use Bminer.. anyone solved this problem?

**Comment by underway113** [comment]
still get rejected shares BMiner and GMiner

**Comment by electricdelicate** [comment]
in confirm that, since few hours the rejected shares back again.
Whats wrong Nicehash?

**Comment by xtrime-ru** [comment]
All my shares became rejected since 2.5 hours ago.

**Comment by Oink70** [comment]
Just decided to disable Beam (gminer & bminer) and back to daggerhashimoto. Let Nicehash fix their mess first.

**Comment by Splongie** [comment]
GMiner have done an update and fixed nicehash issues.

Link to v 1.28
https://bitcointalk.org/index.php?topic=5034735.0

I just copied and pasted its contents into the gminer folder  of nicehash.

**Comment by underway113** [comment]
> GMiner have done an update and fixed nicehash issues.
> 
> Link to v 1.28
> https://bitcointalk.org/index.php?topic=5034735.0
> 
> I just copied and pasted its contents into the gminer folder of nicehash.

works for me, thanks m8. didn't notice GMiner already solve the problem

**Comment by Splongie** [comment]
Not a problem. 
I just got home not long ago and realised I had 13k rejects and 3k accepted shares so did some research.
I like to go to the forums where the miners post updates and just update the 3rd party miner folders for nicehash where i can.
Sometimes get better performance.
Can do the same with the trex miner at the moment too.
Best of luck

**Comment by WitchCraft3r** [comment]
SOLVED REJECTED SHARES FOR BEAM 
update gminer 
https://mega.nz/#F!2GQl0AaR!_YzlNiVNNOUbEqYwz40E8A

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
