### ISSUE TITLE
AMD Vega 56 Beam mining

### ISSUE THREAD

**Issue by rainbowfc** [nicehash/NiceHashMiner#1374]
I have a rig with full of AMD Vega 56 Cards. In nicehash online it says Beam is most profitable for my cards. I have downloaded NHM Legacy 1.9.0.11 . But it still tries to mine DASH not Beam. Are AMD GPU still not compatible to mine  BEAM with NHM? or is there a way to force NHM to mine Beam with my AMD GPU' s?

BR,

**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by rainbowfc** [comment]
Seems like i fixed the problem. Now i can mine with NHM Legacy using Bminer Beam. But now i got too many rejected shares. Seems like miner is not compatible with Server.

**Comment by angelbbs** [comment]
https://github.com/angelbbs/NiceHashMinerLegacy/releases

**Comment by rainbowfc** [comment]
i could not find Beam algorithm for AMD Vega card in this version Fork 12 test 2. and there is no bminer in it too..

**Comment by angelbbs** [comment]
3 miners for you Vega... teamredminer, lyclminer and wildrig miner

**Comment by rainbowfc** [comment]
thank you very much!

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
