### ISSUE TITLE
fyi...  something got changed. switching back to v10

### ISSUE THREAD

**Issue by mrfishbsme** [nicehash/NiceHashMiner#1376]
1.9.0.12 
does not see any of my radeon 270/280/290   gpus
on driver 18.10.1

1.9.0.11
gpus work fine
on driver 18.10.1
cpu backend is disabled

1.9.0.10
gpus work fine
on driver 18.10.1
cpus work fine

any help appreciated.

**Comment by S74nk0** [comment]
Hi @mrfishbsme  can you please try the following:
  - double click on `check_all_AMD.bat` it will generate the file `debug_all_out_AMD.txt` upload that file here or copy and paste its content if you cannot upload it.
  - another thing try deleting `OpenCL.dll` in the root directory of nhml and run it.
  - last thing I would ask you to try is to copy `NiceHashMinerLegacy.exe` from *1.9.0.12* into  *1.9.0.11* run it and report if it can see your AMD GPUs. 

Regarding this 

> cpu backend is disabled

It is disabled by default when there are no detected GPUs on a clean install.  Are you not able to enable it?

**Comment by mrfishbsme** [comment]
#1   here is debug.
#2   *** Deleting opencl.dll in root appears to fix my issues.  also, cpu works too!  ***
#3    I did not try suggestion #3.

Here is capture of xmrstak running properly.   V12 working Good!

Thanks. issue resolved.

[v12-xmrstak-all good.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2830306/v12-xmrstak-all.good.txt)

[debug_all_out_AMD.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2830239/debug_all_out_AMD.txt)
