### ISSUE TITLE
Bug with 1080ti and 1080

### ISSUE THREAD

**Issue by valeriy-efimov** [nicehash/NiceHashMiner#1378]
Hi
I have some problem with this devices
![image](https://user-images.githubusercontent.com/5989188/52332532-91268500-2a03-11e9-8f20-23ed8a9c88cd.png)

when i try to test
![image](https://user-images.githubusercontent.com/5989188/52332624-d8147a80-2a03-11e9-97c8-d8d300bcdad6.png)
hen starts testing another card! 1080 not 1080ti and vice versa
![image](https://user-images.githubusercontent.com/5989188/52332658-fd08ed80-2a03-11e9-981d-1274675c760e.png)
but if start other algorithms working  1080ti 

and this
![image](https://user-images.githubusercontent.com/5989188/52333671-83263380-2a06-11e9-8693-6dca26cfd940.png)

PLS FIX THIS

**Comment by Oink70** [comment]
Looks like the same bug as in https://github.com/nicehash/NiceHashMinerLegacy/issues/1373.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
