### ISSUE TITLE
Failed to Initialize Miner GMiner GrinCuckaroo29

### ISSUE THREAD

**Issue by underway113** [nicehash/NiceHashMiner#1382]
![image](https://user-images.githubusercontent.com/17544780/52681934-53c87700-2f70-11e9-8fbc-6976b13301cb.png)

I can mine Beam (Gminer) but not GrinCuckaroo29 (GMiner) 
i have 5x GTX 1060 6Gb
and using Windows 10

is there any walkaround ?
Thanks

**Comment by zarovavelilya** [comment]
I have the same trouble with my GTX 1060 6 Gb on Win10. I don't know what the purpose of these issue. Please help us!

**Comment by fdoving** [comment]
I think you might be victim of this issue: 
https://www.daz3d.com/forums/discussion/120541/vram-available-for-rendering-on-windows-10-systems-update-gtx-1080-ti/p3

Windows 10 reserves like 20%-ish of the VRAM on every single card, even if not connected to display.

I think grincuckaroo29 requires about 5.6G of VRAM with gminer.

**Comment by zarovavelilya** [comment]
Thanks a lot for info ((

**Comment by teckel12** [comment]
For me, GrinCuckaroo29 nor Beam are even listed as Algorithms for Nvidia 1060 6GB nor AMD RX 570.

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
