### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by Stels1999** [nicehash/NiceHashMiner#1393]
Вот что пишет: Подробная информация об использовании оперативной (JIT) отладки вместо данного диалогового окна содержится в конце этого сообщения. ************** Текст исключения ************** System.OverflowException: Переполнение в результате выполнения арифметической операции. в System.Windows.Forms.ListView.GetDisplayIndex(ListViewItem item, Int32 lastIndex) в System.Windows.Forms.ListViewItem.get_Index() в System.Windows.Forms.ListViewItem.get_StateImageIndex() в NiceHashMiner.Forms.Components.DevicesListViewEnableControl.ListViewDevicesItemChecked(Object sender, ItemCheckedEventArgs e) в System.Windows.Forms.ListView.OnItemChecked(ItemCheckedEventArgs e) в System.Windows.Forms.ListView.WmReflectNotify(Message&amp; m) в System.Windows.Forms.ListView.WndProc(Message&amp; m) в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) ************** Загруженные сборки ************** mscorlib Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll ---------------------------------------- NiceHashMinerLegacy Версия сборки: 1.9.0.13 Версия Win32: 1.9.0.13 CodeBase: file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/Desktop/nhm_windows_1.9.0.13/NiceHashMinerLegacy.exe ---------------------------------------- System.Windows.Forms Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll ---------------------------------------- System Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll ---------------------------------------- System.Drawing Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll ---------------------------------------- Newtonsoft.Json Версия сборки: 12.0.0.0 Версия Win32: 12.0.1.22727 CodeBase: file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/Desktop/nhm_windows_1.9.0.13/Newtonsoft.Json.DLL ---------------------------------------- NiceHashMinerLegacy.Common Версия сборки: 1.0.0.0 Версия Win32: 1.0.0.0 CodeBase: file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/Desktop/nhm_windows_1.9.0.13/NiceHashMinerLegacy.Common.DLL ---------------------------------------- System.Runtime Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll ---------------------------------------- System.Xml Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll ---------------------------------------- System.Management Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll ---------------------------------------- System.Core Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll ---------------------------------------- System.Numerics Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll ---------------------------------------- System.Runtime.Serialization Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll ---------------------------------------- System.Data Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll ---------------------------------------- log4net Версия сборки: 1.2.15.0 Версия Win32: 1.2.15.0 CodeBase: file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/Desktop/nhm_windows_1.9.0.13/log4net.DLL ---------------------------------------- System.Configuration Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll ---------------------------------------- MessageBoxManager Версия сборки: 1.0.0.0 Версия Win32: 1.0.0.0 CodeBase: file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/Desktop/nhm_windows_1.9.0.13/MessageBoxManager.DLL ---------------------------------------- NiceHashMinerLegacy.Extensions Версия сборки: 1.0.0.0 Версия Win32: 1.0.0.0 CodeBase: file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/Desktop/nhm_windows_1.9.0.13/NiceHashMinerLegacy.Extensions.DLL ---------------------------------------- System.Collections Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll ---------------------------------------- System.Linq Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll ---------------------------------------- ManagedNvml Версия сборки: 8.0.22.0 Версия Win32: 8.0.22 CodeBase: file:///C:/Users/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9/Desktop/nhm_windows_1.9.0.13/ManagedNvml.DLL ---------------------------------------- mscorlib.resources Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll ---------------------------------------- System.Windows.Forms.resources Версия сборки: 4.0.0.0 Версия Win32: 4.7.2053.0 built by: NET47REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll ---------------------------------------- ************** Оперативная отладка (JIT) ************** Для подключения оперативной (JIT) отладки файл .config данного приложения или компьютера (machine.config) должен иметь значение jitDebugging, установленное в секции system.windows.forms. Приложение также должно быть скомпилировано с включенной отладкой. Например: &lt;configuration&gt; &lt;system.windows.forms jitDebugging=&quot;true&quot; /&gt; &lt;/configuration&gt; При включенной отладке JIT любое необрабатываемое исключение пересылается отладчику JIT, зарегистрированному на данном компьютере, вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
