### ISSUE TITLE
Can't startup NiceHashMinerLegacy

### ISSUE THREAD

**Issue by almartins** [nicehash/NiceHashMiner#1394]
Video cards: 3x GTX 1080ti + 1x 1080,
driver: 418.91,
OS: Windows 7 64bit

Assinatura do problema:
  Nome do Evento de Problema:	APPCRASH
  Nome da aplicação:	NiceHashMinerLegacy.exe
  Versão da aplicação:	1.9.0.13
  Carimbo de Data/Hora da Aplicação:	5c65b58f
  Nome do Módulo com Falhas:	KERNELBASE.dll
  Versão do Módulo com Falhas:	6.1.7601.21772
  Carimbo de Data/Hora do Módulo com Falhas:	4e211f48
  Código de excepção:	e0434352
  Desvio de Excepção:	000000000000cacd
  Versão do SO:	6.1.7601.2.1.0.256.48
  ID de Região:	2070
  Informações Adicionais 1:	2413
  Informações Adicionais 2:	2413de213f38e5efe700010a55469627
  Informações Adicionais 3:	4939
  Informações Adicionais 4:	49399afe0dc89904a6b278462c185ad7

**Comment by nazzier5463** [comment]
1. [https://www.microsoft.com/en-us/download/details.aspx?id=30653](url)
2. [https://www.microsoft.com/en-us/download/details.aspx?id=40784](url)

Install both.

**Comment by almartins** [comment]
Done n. 1 solve the problem, NiceHashMinerLegacy is running now. Do I have to do n.2 ?

Em 18/02/2019 03:31, nazzier5463 <notifications@github.com> escreveu:

  1.  https://www.microsoft.com/en-us/download/details.aspx?id=30653<url>
  2.  https://www.microsoft.com/en-us/download/details.aspx?id=40784<url>

Try 1 & 2.

**Comment by nazzier5463** [comment]
There is no need. Happy mining.

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
