### ISSUE TITLE
Motherboard destroyed/burned/obliterated (Actually not, PCIE connector on the PSU burned)

### ISSUE THREAD

**Issue by ibmua** [nicehash/NiceHashMiner#1396]
Seems like a night of mining with 275w Asus Nvidia 1080Ti destroyed/burned my motherboard. Now whenever I provide a more or less decent load on a GPU, monitors just shut down and that's it until I manually turn off power to the mobo, wait a bit and turn it back on - then Windows can load normally again.

https://www.nicehash.com/miner/34V3hUHEEzHJywsfMb5adwSUxRrhc9W2dk

**Comment by InjectedPie** [comment]
rma

**Comment by nazzier5463** [comment]
which part or location on motherboard ? I'm thinking psu problem as you describe

**Comment by ibmua** [comment]
Yes, indeed @nazzier5463 was right, the 750w platinum PSU is what died, luckily the mobo is okay. I'll try to return the PSU per guarantee. =) Moral of this story: gotta have a really powerful PSU to run this thing. NVidia recommends min 600w PSUs for 250w 1080 ti. This one was 275w, but a 750w PSU died. I guess it should be 900w min for this one. It's important to also note that, at least most, PSUs get their actual power ratings lower the hotter they get.

**Comment by ibmua** [comment]
Actually, the PSU didn't really died. The connector between PCIE cable and PSU burned on both the cable and PSU. When I plugged a different PCIE cable into a different port it worked fine. But having spent a day on that crap, I'm going to try to send the PSU back in hope that seller will at least, maybe, fix that port and send a new cable.
