### ISSUE TITLE
GrinCuckaroo29 won't run on GTX 1060 6GB

### ISSUE THREAD

**Issue by teckel12** [nicehash/NiceHashMiner#1397]
Running NiceHash Miner Legacy v1.9.0.13.  Looking NiceHash stats, these two cards are only mining GrinCuckaroo29 and Beam, but neither are listed as Algorithms?

**Comment by nazzier5463** [comment]
do you have picture its not showing ?

**Comment by teckel12** [comment]
Upgraded to v1.9.0.14 and now they're listed.  But, GrinCuckaroo29 won't benchmark nor run on my 1060 6GB.  I believe it's confused because I also have AMD cards.  It gives a red error, but closes too quickly for me to read.

**Comment by teckel12** [comment]
Found the benchmark log, says:

```
12:09:45 Failed to initialize miner on GPU0: GIGABYTE GeForce GTX 1060 6GB:
12:09:45 No devices for mining
```

**Comment by pavelhr** [comment]
same problem here:

18:54:47 Failed to initialize miner on GPU0: NVIDIA GeForce GTX 1060 6GB: 
18:54:47 No devices for mining

**Comment by nazzier5463** [comment]
> Found the benchmark log, says:
> 
> ```
> 12:09:45 Failed to initialize miner on GPU0: GIGABYTE GeForce GTX 1060 6GB:
> 12:09:45 No devices for mining
> ```



> same problem here:
> 
> 18:54:47 Failed to initialize miner on GPU0: NVIDIA GeForce GTX 1060 6GB:
> 18:54:47 No devices for mining

What miner ? It is Gminer ?

**Comment by nazzier5463** [comment]
> > Found the benchmark log, says:
> > ```
> > 12:09:45 Failed to initialize miner on GPU0: GIGABYTE GeForce GTX 1060 6GB:
> > 12:09:45 No devices for mining
> > ```
> 
> > same problem here:
> > 18:54:47 Failed to initialize miner on GPU0: NVIDIA GeForce GTX 1060 6GB:
> > 18:54:47 No devices for mining
> 
> What miner ? It is Gminer ?

**It is Gminer**. Try to manually update Gminer to v1.32.
1. Download here > [https://github.com/develsoftware/GMinerRelease/releases/download/1.32/gminer_1_32_minimal_windows64.zip](url)
2. Extract the zip file
3. Copy miner.exe from extracted folder
4. Go to nicehash folder > bin_3rdparty > gminer (paste here inside gminer folder, it will replace old version)
Run nicehash see what happen.

p/s v1.33 is out but I get slower hashrate compare to last version. This is why I recommend v1.32.

**Comment by teckel12** [comment]
I get the same with v1.3.2:
```
+----------------------------------------------------------------+
|                          GMiner v1.32                          |
+----------------------------------------------------------------+
Algorithm:          Cuckaroo 29 "Grin"
Stratum server:     
  host:             stratum://grincuckaroo29.usa.nicehash.com:3371
  user:             AbCdEfGhIjKlMnOpQrStUvWxYz12345678.AtticMiner
  password:         x
Power calculator:   on
Color output:       on
Watchdog:           off
API:                http://127.0.0.1:4000
Log to file:        off
Selected devices:   GPU0
Temperature limits: 90C 
------------------------------------------------------------------
07:48:15 Failed to initialize miner on GPU0: GIGABYTE GeForce GTX 1060 6GB: 
07:48:15 No devices for mining
```

I also ran gminer manually and get the same result.  Ran several older versions with same result.  Ran v1.19 which gave a slightly different error, "out of memory".  Did some research and it seems GMiner doesn't work on Windows 10.  Which sounds crazy as everyone should be running Windows 10.  Anyway, not sure how everyone else is running the GrinCuckaroo29 algorithm.

**Comment by nazzier5463** [comment]
Did you increase your vram ?

**Comment by teckel12** [comment]
@nazzier5463 I've got 16GB of RAM. I got a different miner running instead via the command line. No reason to run the NiceHash front-end anyway.

**Comment by teckel12** [comment]
Why are people even running GrinCuckaroo29?  It's easily 30-40% lower return than mining ETH.  Makes no sense.  This trouble getting GrinCuckaroo29 running and it's not nearly worth it.  Confused...

**Comment by orlee** [comment]
Update to last version of your NVIDIA drivers. Solved the problem here
