### ISSUE TITLE
NiceHash Miner Legacy missing Cryptonight v8

### ISSUE THREAD

**Issue by teckel12** [nicehash/NiceHashMiner#1398]
So Cryptonight v8 is included in NiceHash Miner 2 which is discontinued and they say NiceHash Miner Legacy is 50% more profitable.  Yet, NiceHash Miner Legacy doesn't include the Cryptonight v8 algorithm?  This makes NiceHash Miner Legacy about half as profitable compared to NiceHash Miner 2, totally in the wrong direction as stated.

I really don't understand what's going on with NiceHash Miner Legacy.  All the current algorithm are missing, yet people are clearly using them.  Very confused...

**Comment by nazzier5463** [comment]
Everything fine here.. Check your windows defender and AV.
`[https://drive.google.com/file/d/1BtaOD4v6EWMqSDWveuIkk4URS8exJYZ8/view?usp=sharing](url)`

**Comment by nazzier5463** [comment]
![nce](https://user-images.githubusercontent.com/39856005/52926284-1bf67080-3370-11e9-8202-9be0184dbf23.png)
Everything fine here. Check your windows defender and AV.

**Comment by teckel12** [comment]
@nazzier5463 I have Windows Defender allowing the entire NiceHash directory. These algorithms don't even show. It's like because I was running an older version and upgraded, it still only lists the older algorithms. The first time I ran the latest release it did do the process of downloading algorithms, but they're not listed.

**Comment by luc1an24** [comment]
Have you downloaded latest release from download page?https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.13

**Comment by nazzier5463** [comment]
> @nazzier5463 I have Windows Defender allowing the entire NiceHash directory. These algorithms don't even show. It's like because I was running an older version and upgraded, it still only lists the older algorithms. The first time I ran the latest release it did do the process of downloading algorithms, but they're not listed.

You said you're running an older version and upgraded ? Dont upgrade from old one, just download from below, extract and run .exe from extracted folder. Just ignore older version

> Have you downloaded latest release from download page?https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.13

**Comment by teckel12** [comment]
@nazzier5463 @luc1an24 I guess what I mean was I was running an older version, downloaded v1.9.0.13 and copied all the files on top of my existing folder.  So I'm running the latest release, and the first time I ran it, it had a progress meter as it downloaded algorithms.

What it's sounding like is that NiceHash doesn't work correctly if you don't completely wipe the old config/settings.  Not tested yet, but sounds like it's possible, and would be an oversight as most people wouldn't want to run all new benchmarks and recreate their settings for each release.

**Comment by teckel12** [comment]
Upgraded to **v1.9.0.14** and Cryptonight v8 is now listed.  I would, however, suggest that NiceHash update all their download links to:

https://github.com/nicehash/NiceHashMinerLegacy/releases/latest

The way they're doing it now, they need to update the links each time there's a new release.  Also, historical pages that are not updated will keep pointing to an old release.  Using the above link, can insure all links always point to the latest release.
