### ISSUE TITLE
error during benchmark prevents start of mining when benchmark is complete

### ISSUE THREAD

**Issue by CreamyG31337** [nicehash/NiceHashMiner#14]
It has cost me a lot of money over the years when I install a new card and let it benchmark overnight or whatever, making sure to check the box to start mining when benchmarking is complete. It pretty much never starts because any time a benchmark fails, it just sits there asking if it should retry the failed benchmarks. Please either have this dialog bypass after a timeout or just skip it entirely when the box to start mining was checked.

**Comment by navjack** [comment]
oh yeah i'd love that little annoyance to go away. default to re-run the benchmark automatically in precise mode and if it fails again timeout the dialog box and just start mining with that one algo disabled but maybe like have a little red text show up in the main nicehash window saying that this has occurred and maybe the user should check it out

**Comment by CreamyG31337** [comment]
yeah feel free to just do a basic fix and close this -- but there's a lot of ways to improve the logic if you want!

**Comment by DillonN** [comment]
Interesting I didn't think about this, thanks for the idea I will look into it

**Comment by CreamyG31337** [comment]
Yeah, another idea for this benchmark screen is to make it non modal so that you can benchmark while mining -- it's pretty common to have like 6 video cards and having 5 idle so 1 can benchmark is a bit silly. I tried to run a 2nd instance of nicehash in this case but it crashed. I'm guessing the 2 instances would be overwriting the config files of each other. Maybe nicehash shouldn't really allow 2 instances launched from the same path if this isn't tested properly. Anyways, it's just something for you to think about if you're looking at enhancing the benchmarking sometime.
