### ISSUE TITLE
cannot get current temperature, error 999 internal drive

### ISSUE THREAD

**Issue by akocart07** [nicehash/NiceHashMiner#140]
how to fix this... it occurs when i added my 5th gpu...

running 4 1050ti 
and 780ti

psu 650watt truerated. 
when it was 4 gpu only it runs ok.. but when i added 1 more 1050ti im getting this error
cannot get current temperature, error 999 internal drive
cannot get current temperature, error 999 internal drive
cannot get current temperature, error 999 internal drive
cannot get current temperature, error 999 internal drive
cannot get current temperature, error 999 internal drive
cannot get current temperature, error 999 internal drive

it freeze sometimes restarts

**Comment by DillonN** [comment]
Error 999 indicates something wrong with your drivers or hardware. Make sure you've tried disabling any overclocks and the card you're adding isn't unstable, and that your PSU can handle all cards. Do you see this error in a miner window or NHML logs?

**Comment by akocart07** [comment]
im running it stock

**Comment by akocart07** [comment]
and i see this error in miner window

**Comment by akocart07** [comment]
i can always see the error at NHML logs

**Comment by akocart07** [comment]
please any solution on this?

**Comment by DillonN** [comment]
This isn't something that can be fixed from NHML
