### ISSUE TITLE
NiceHashMinerLegacy Gpu fail

### ISSUE THREAD

**Issue by jonatanjrb** [nicehash/NiceHashMiner#1402]
since yesterday the mining by the video card is only at zero and is restarting the hdmi and does not mine anything the cpu is good already updated and I did a new benchmark and at the time of the benchmark works but at the time of mining nothing

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
