### ISSUE TITLE
NHML 1.9.0.14 Does not detect devices (GTX 1080ti video card) when reloading farm 

### ISSUE THREAD

**Issue by 5000VID** [nicehash/NiceHashMiner#1405]
I have a farm with Win10 and 6 GTX 1080ti video cards. Recently installed NHML 1.9.0.14, and before that 1.9.0.12 there was a problem - it does not detect the device (GTX 1080ti video card) when the farm is rebooted. You have to manually close the running application and start it again, then everything works. Previously, there was no such problem with NHML 1.9.0.10

**Comment by mozEvil** [comment]
same problem

**Comment by ghost** [comment]
same

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
