### ISSUE TITLE
sgminer_zcoinofficial issue

### ISSUE THREAD

**Issue by Ryunori** [nicehash/NiceHashMiner#1406]
**error when trying to benchmark MTP algorithm**

as seen in the log

[2019-02-20 11:07:33] [INFO] [PATHS] Path bin\sgminer_zcoinofficial\sgminer.exe not found, using defaults

**Comment by noonway** [comment]
same 1.9.0.15

**Comment by S74nk0** [comment]
Sgminer-MTP doens't work with NiceHash. This is removed in newer versions:

https://github.com/nicehash/NiceHashMinerLegacy/blob/master/src/NiceHashMinerLegacy/Devices/Algorithms/DefaultAlgorithms.cs#L133

Closing issue related to old version.
