### ISSUE TITLE
Version 1.8.1.0 Not starting with windows

### ISSUE THREAD

**Issue by Paul-Trasca** [nicehash/NiceHashMiner#141]
Because of different dirvers conflict in my pc i restart windows from 4 to 4 hours. This version is not autostart nicehash miner. 1.8.0.2 worked perfectly

**Comment by DillonN** [comment]
When you check the run at startup box, does it stay checked after you save the changes then go back to the settings page? Also if you could post your logs while doing this I may be able to help more

**Comment by 3zero2** [comment]
Does not auto start here either. Next time I need to restart I will send in the logs whilst switching on and off the option. 

I know that the option stays enabled when I save settings and reopen.

**Comment by DillonN** [comment]
If you could send your logs soon after a restart that would be great. I suspect the issue isn't with NHML being set to launch, but with which directory it is launched in by Windows causing it to silently crash (an issue I fixed before that may be popping up again).

**Comment by p1r473** [comment]
I use Startup Delayer as it allows you to set a delay before launching programs http://www.r2.com.au/page/products/show/startup-delayer/

**Comment by Paul-Trasca** [comment]
Yeah, it's about locations. I unzipped miner in /downloaded/ windows directory. Now is in c: and it's working
