### ISSUE TITLE
Abnormal increase of RAM memory usage

### ISSUE THREAD

**Issue by tukpedro** [nicehash/NiceHashMiner#1410]
After aprox. 6h of mining, I've noticed that NicHashMiner 1.9.0.15 was using 11GB of RAM memory. I stopped and close NiceHash. Could anybody help solve this situation? Thanks

**Comment by unk2** [comment]
MPT algorithm consumes all memory over time. Need fix it.

**Comment by ghost** [comment]
I have the same issue 👎

**Comment by tukpedro** [comment]
it's a pity because MPT is the most profitable algorithm :(

**Comment by github12101** [comment]
Same here, confirming. Had to increase swapfile to 50GB (8x 1070Ti), 12GB physical RAM installed.
Now with 1.9.0.16 MTP is disabled by default to mitigate this issue.

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
