### ISSUE TITLE
1.9.0.15 MTP "no kernal image is available for execution on this device"

### ISSUE THREAD

**Issue by mavericknoob** [nicehash/NiceHashMiner#1412]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2893705/log.txt)

![untitled](https://user-images.githubusercontent.com/20135196/53240092-99f99680-3652-11e9-91c2-65c8cabcc11c.jpg)

**Comment by mavericknoob** [comment]
![untitled](https://user-images.githubusercontent.com/20135196/53240340-56535c80-3653-11e9-95f0-808d868a7c13.jpg)

**Comment by wxprofessor** [comment]
I received the same error message on my box with dual 970s... perhaps they don't run with cuda 10? Not sure... 🤔

**Comment by buxy-xyz** [comment]
same issue here. 
some friends of mine run into the same problem.

edit: solved.

**Comment by lukesnc** [comment]
> same issue here.
> some friends of mine run into the same problem.
> 
> edit: solved.

How did you fix it? I can't seem to find anything online. I have a GTX 980 Ti just in case that affects anything

**Comment by Goodkevin1** [comment]
> same issue here.
> some friends of mine run into the same problem.
> 
> edit: solved.

how?

**Comment by buxy-xyz** [comment]
> 
> 
> > same issue here.
> > some friends of mine run into the same problem.
> > edit: solved.
> 
> how?

by increasing the virtual memory size.

**Comment by lukesnc** [comment]
> > > same issue here.
> > > some friends of mine run into the same problem.
> > > edit: solved.
> > 
> > 
> > how?
> 
> by increasing the virtual memory size.

I increased my virtual memory from system managed to 8gb and that didn't work. I tried increments all the way up to even 60gb of virtual ram, but it still isn't working. Any ideas? I've only got 1 980 Ti, Windows 10 64-bit and latest Nvidia driver

**Comment by Goodkevin1** [comment]
> > > > same issue here.
> > > > some friends of mine run into the same problem.
> > > > edit: solved.
> > > 
> > > 
> > > how?
> > 
> > 
> > by increasing the virtual memory size.
> 
> I increased my virtual memory from system managed to 8gb and that didn't work. I tried increments all the way up to even 60gb of virtual ram, but it still isn't working. Any ideas? I've only got 1 980 Ti, Windows 10 64-bit and latest Nvidia driver

same but a 970 instead of a 980

**Comment by SK-Crow** [comment]
Did anyone get this working?

**Comment by mavericknoob** [comment]
> 
> 
> Did anyone get this working?

No

**Comment by jake5253** [comment]
I have found a work-around.

First things first, head over to [https://github.com/zcoinofficial/ccminer/releases](https://github.com/zcoinofficial/ccminer/releases) and download the latest version of _ccminer.exe_ (1.1.17 at time of writing).
Open your NHLM folder and navigate to` ..\bin\ccminer_mtp\`
Rename (or move or delete) the original ccminer.exe to `ccminer-1.1.12-djm34.exe`
Copy/Paste the new version you downloaded into that folder. Ensure the file is named _ccminer.exe_
Open NHLM and go into `Settings`
Click the _Devices/Algorithms_ tab
Select your GPU in the top box
In the lower box scroll down to and select _MTP (ccminer)_
In the Extra Launch Parameters box on the right, add `-i 12`

You may need to play with that number.  I'm using a 980Ti and found 12 to be most stable for me.
If you'd like to fiddle around and find the magic stable number for _your GPU_, try the following in a command line:
`..\nhm_windows_1.9.0.20\bin\ccminer_mtp\ccminer.exe -a mtp -o stratum+tcp://mtp.eu.nicehash.com:3374 -u <your_nh_addr.TESTING> -i 12`

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
