### ISSUE TITLE
Why do new windows of miners open, but old ones do not close?

### ISSUE THREAD

**Issue by MozartAndrey** [nicehash/NiceHashMiner#1414]
Why do new windows of miners open, but old ones do not close? Several of the simultaneously running miners "hang" the Windows 7 system. Please correct this error. This error is massive. Thank!!! 

Warum öffnen sich neue Fenster der Bergleute, aber alte schließen sich nicht? Mehrere gleichzeitig ausgeführte Miner legen das Windows 7-System auf. Bitte korrigieren Sie diesen Fehler. Dieser Fehler ist massiv. Danke!!! 

Почему открываются новые окна майнеров, а старые не закрываются? Несколько одновременно запущенных майнеров "вешают" систему Окна 7. Пожалуйста исправьте эту ошибку. Эта ошибка носит массовый характер. Спасибо!!!

**Comment by almartins** [comment]
Same here:
"
Why do new windows of miners open, but old ones do not close? Several of the simultaneously running miners "hang" the Windows 7 system. Please correct this error. This error is massive. Thank!!!
"
After 8 haours, many windows open and system become slow and have to be hard reseted.

**Comment by ghost** [comment]
I have the same issue.

**Comment by noescape69** [comment]
Same here. I'm under W7 pro. Actually, it's with Gminer.

**Comment by alexmatveev25** [comment]
Same Here.  I am confused.  W10+GTX1060\GTX1070

**Comment by MozartAndrey** [comment]
Someone has found a solution to the problem?
At the moment in the settings, I include only one algorithm. But this is not a solution.

It makes sense for everyone to write about this problem to the support service: support@nicehash.com

**Comment by Shaverdoff** [comment]
i'll already make tikect to support. they found problem and resolverd it on next release... now in 19.0.16 problem still exist

**Comment by almartins** [comment]
Tonight aprox. 3:00 GMT my miners had the same problem inclusive with 19.0.016 version but is occurred much less with 19.0.016.

**Comment by Shaverdoff** [comment]
> 
> 
> Tonight aprox. 3:00 GMT my miners had the same problem inclusive with 19.0.016 version but is occurred much less with 19.0.016.

i have that in 1.9.0.15 already.

**Comment by MozartAndrey** [comment]
Need to write to technical support. It is necessary to specify the type of video card, Windows, build style number, screenshots ...
Support service: support@nicehash.com

**Comment by Shaverdoff** [comment]
![default](https://user-images.githubusercontent.com/43804710/53630079-ab313d00-3c28-11e9-836c-1f02395f099e.png)
this is no longer what gate does not climb ... we are sort of like we are paying the commission for mining and commission for withdrawal ... is it not for free that Nicehash interacts with us ... when to wait for the fix release ??

**Comment by MozartAndrey** [comment]
News:
NiceHash Miner Legacy 1.9.0.17 is now available for download.
Changes and fixes:
GMiner disable native watchdog and change closing logic (fixes multiple GMiner windows)...

Works for everyone?

**Comment by Shaverdoff** [comment]
> 
> 
> News:
> NiceHash Miner Legacy 1.9.0.17 is now available for download.
> Changes and fixes:
> GMiner disable native watchdog and change closing logic (fixes multiple GMiner windows)...
> 
> Works for everyone?

i update my miners Tonight and whole looks good!

**Comment by almartins** [comment]
One machine running without problems by 10 H. Will change another two miners to ....017 to confirme.

**Comment by noescape69** [comment]
I Update yesterday, and it seems to be good.

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
