### ISSUE TITLE
[Feature] Set electricity cost for each hour of 24 hours 

### ISSUE THREAD

**Issue by Lenchik** [nicehash/NiceHashMiner#1416]
My electric company has three different prices for electricity which give 5 electricity cost zones:
7:00–9:59 price1, 10:00–16:59 price2, 17:00–20:59 price1, 21:00–22:59 price2, 23:00–6:59 price3.
Would be great to set electricity cost in NiceHashMinerLegacy's settings in some sort of table like:

Hour | Electricity cost (/[kWh](https://en.wikipedia.org/wiki/Kilowatt_hour))
------------ | -------------
00:00–00:59 | x.xxxx
01:00–01:59 | x.xxxx
... | ...
23:00–23:59 | x.xxxx

As far as I understood minimum profit setting, which applied as threshold after calculating (`mining result` – `electricity cost`}, this per hour setting (described above) can also be a solution for the #1216.

**Comment by github12101** [comment]
I feel this would be overcomplication.

Why don't you calculate average for your every 24hour period? You are paying a fixed amount of kWh daily if you mining the same thing over 24h period. Calculate your average rate, that will solve it.

**Comment by Lenchik** [comment]
Mining at average price is not profitable most of time (for me). But setting this per hour prices allows (in my dreams for now) NiceHashMinerLegacy to either select most profitable algo at profitable time or turn on mining if some buyer at nicehash site changed algo profitability at some time of day.
Moreover, would be great to add some minimum power (or background consumption) used by system (again in kWh) that is used when computer is on but is not mining. This power consumption should be added to consumption of GPUs whe claclulating for profitability. These 30-80 Wh would be negligible with big rigs of high end videocards on electricity greedy algos, but would be important in calculations for PC with one GPU and NiceHashMinerLegacy working as background process.

**Comment by github12101** [comment]
I see your point now.
Well, if Nicehash devs would implement that, then you're golden.

Another workaround for you is:
Create 3 profiles of NHML (3 folders). Disable NHML on startup
Create 3 tasks in your Windows Scheduler to reboot your PC, 3 minutes before your tariff change
Create 3 tasks in your Windows Scheduler to run NHML profile number 1, 2 and 3 (depending on time a day) when tariff changes (3 minutes after reboot, just to be sure you're fully booted up)

Each NHML profile would store your energy settings, and it would automatically start correct profile when tariff changes.

Problem solved:)

The more advanced solution would be to run 1 script, which would kill NHML process and it's children processes and start a new one, each time tariff changes, that way you don't need to reboot.

It's completely doable.

**Comment by Dohtar1337** [comment]
Moved to idea backlog. Closing to clean the issues.
