### ISSUE TITLE
GUI always crashing

### ISSUE THREAD

**Issue by Piranhagus** [nicehash/NiceHashMiner#1417]
The nicehash miner GUI keeps crashing after mining at random times, never stays up, ever. However, some of the 3rd party miners are able to keep running and I get paid. So at least there is that. With the gui crash, though, the miner cannot switch algos or perform any other functions, and I am therefore locked into whichever algo I begin mining with; I can only see the mining log window of the 3rd party miner. 

I have tried running in different compatibility modes, adjusting gpu settings, etc, but the problem seems to be with the GUI stability. I never had these issues ever with the NHMv2. This issue is native to the NHML for some reason. 

Setup:
Win 10
Ryzen 1600x
16gb 3200 RAM
1080 ti
1080

**Comment by F1Rumors** [comment]
I found this to be a problem with the new MTP miner ... that is unstable and it appears to interact badly with the GUI, crashing it. Try disabling that algorithm...

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
