### ISSUE TITLE
What can we use instead of NHML? Help Please 🤠✝

### ISSUE THREAD

**Issue by wxprofessor** [nicehash/NiceHashMiner#1419]
Can someone please help! I have three boxes that I've run NHM V2 on for.. like a long time.. and it always just WORKS. Of the three boxes, NHML "kind of" works on one, and absolutely does not on others.

1 box. single zotac gtx 1080 -- kind of works
2 box. dual SLI MSI gtx 1080ti -- complete failure
3 box. dual gtx (founders) 970s in SLI -- complete failure

to repeat.. NHM v2 works on all three boxes flawlessly... does anyone know something else as stable as NHM that I can use since they are discontinuing it?

looks like some of the windows versions that were running have been discontinued :/ ... who to trust? I know nicehash was hacked and everything, but that happens.. just trying to stay loyal but looks like i'm out of luck :/

**Comment by nazzier5463** [comment]
Remove SLI, make it single each card.

**Comment by mavericknoob** [comment]
Turn off SLI when mining, for starters. Also make sure you have Microsoft Visual C++ Redistributable 2013, and Microsoft .NET Framework 2.0 on all the PCs.
What OS are you running on the 3 boxes?

**Comment by wxprofessor** [comment]
All three boxes are windows 10... turned SLI off, it did not work.... 

If someone tells me that it NHML should work with gtx 970 i will try installing on that box again when a new release is out... currently NHM v 2 is working perfectly on all three boxes 👽  I wrote official NHM support, and they said they are switching to NHML because it is more profitable, but it is NOT more profitable, if it does not  work 👀👽

**Comment by PBJellytime** [comment]
You'll need to provide more information if you want some help, screenshots, logfiles etc.  Does it load up, does it start then fail?? NHML works well, but sometimes can be flakey on different boxes with different algos.  I have different issues with both my rigs running identical hardware setups so its a bit of troubleshooting to solve the problems each time

**Comment by wxprofessor** [comment]
I did @PBJellytime , both in Github, and in Nicehash support 🙂 Of course, it is not realistic to think that everyone would read all of my posts 🤠✝ So instead, I solved the issues on my own, and provided a readme that helped with at least the GTX 9XX version of my boxes, and posted it for others to read in case they may have similar issues: https://github.com/nicehash/NiceHashMinerLegacy/issues/1434  After Googling to solve the various problems, It seems there might be more profitable options than NiceHash, I was simply trying to remain loyal 🙂 Of course loyalty is often one way 😎👍

**Comment by PBJellytime** [comment]
Glad you got it fixed and good job on sharing the knowledge.
