### ISSUE TITLE
benchmark fails because it cannot find msvcr120.dll file

### ISSUE THREAD

**Issue by mikellpp** [nicehash/NiceHashMiner#142]
Version 1.8.1.0 some benchmarks cannot proceed because they fail to find msvcr120.dll file. This file is in the NHML-1.8.1.0 folder.

**Comment by DillonN** [comment]
You may need to copy the .dll into the folders of the failing miners. A program that depends on `msvcr120.dll` will only find it if it is in the exact same directory, or installed to system root. If you wish to just install them globally you can find links [on the wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Troubleshooting#msvcp)

**Comment by mikellpp** [comment]
I had to put it into the EWBF AND EthDec directories.

**Comment by mikellpp** [comment]
I had to put it into the EWBF AND EthDec directories.
