### ISSUE TITLE
Hey people! What are you doing?

### ISSUE THREAD

**Issue by GOSEF** [nicehash/NiceHashMiner#1420]
Latest version of nicehash are working bad.
After rig restart they can't find GPU (windows 7 64bit + 6 pcs 1080ti).
After manual restart GPU are founded and start mining. But in several hours nicehash stopped.
There are several copies of gminer, very hard rig's working, but zero profit for me...

Hey people! What are you doing?

**Comment by almartins** [comment]
Same problems here with ... 015 version :(.

**Comment by alexmatveev25** [comment]
I have the same problem. The miner shows the profitability of 0, the miner window cyclically restores, in the notifications the error "the application is blocked access to the graphics hardware". I'm confused.

**Comment by GOSEF** [comment]
Update from 26/02/2019
Version 1.9.0.16 + win7 64bit + 6 x 1080ti. There were several restarts. All the time GPU was detected correctly. Thanks a lot!!!
But in some time you can see this sutuation:

![2019-02-26_11-34-26](https://user-images.githubusercontent.com/7315784/53399603-5a69dc00-39bd-11e9-8027-be85f72528b7.png)

**Comment by PBJellytime** [comment]
have you turned off allow multiple instances in the settings?

**Comment by GOSEF** [comment]
Of course I turned  it off. But I think that this point is related to the program but not to the miner.

**Comment by GOSEF** [comment]
The situation is repeating. There are around 99 copies of gminer are running:
![2019-02-28_21-36-36](https://user-images.githubusercontent.com/7315784/53590009-dfade600-3ba1-11e9-8fd2-5522df6342a7.png)
![2019-02-28_21-38-48](https://user-images.githubusercontent.com/7315784/53590020-e4729a00-3ba1-11e9-9009-f5588f79ffbb.png)

**Comment by S74nk0** [comment]
We have changed GMiner code in the latest release.
https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.17

If the problem is not present in the v1.9.0.17 anymore please close this issue.

**Comment by ghost** [comment]
I am Also Facing The Issue Still In New Version Also 
I have 12 GPU NVIDIA 1080Ti,  Motherboard Gigabyte B250 FINTECH 12 Gpu Slot ,  i3 6600 3.70GHz  ,8GB Ram & windows 10.1
&
6 GPu NVIDIA 1080ti ,Gigabyte GA-h110M-h LGA 1151 Motherboard , 8 GB Ram , i7 7700 K Unlocked,
Windows 10.1
Both My Rigs CPU Usage Is at 100% & Multiple Mining windows are Opening Automatically after Intervals of time & Crashing The WIndows with BLUESCREEN Error
Kindly Help

**Comment by GOSEF** [comment]
The version 1.9.0.17 works just fine for me!
