### ISSUE TITLE
NHML saying Nvidia driver is too old even when i updated it

### ISSUE THREAD

**Issue by codingSince9** [nicehash/NiceHashMiner#1424]
When i open the miner it registers the CPU but not the GPU rtx 2070.
First i downloaded the latest official nvidia driver and installed it, but NHML said that the driver is too old and that i should update it.
I downloaded DDU and did a clean install of the newest official nvidia driver, but again NHML says the driver is too old.
Picture: 
![image](https://user-images.githubusercontent.com/45716849/53368385-e2fa6500-3948-11e9-9aa6-c1b36dd80ec2.png)

The driver currently installed is: 419.17

Edit: I downloaded the latest version of NHML 1.9.0.16 (was using 1.9.0.15).
The latest version doesn't even give me an error box, but just exits the program

**Comment by PBJellytime** [comment]
Just a guess but does NHML support the RTX 2070 yet?

**Comment by codingSince9** [comment]
> 
> 
> Just a guess but does NHML support the RTX 2070 yet?

Its on their profitability calculator : https://www.nicehash.com/profitability-calculator#nvidia-rtx-2070;USD;0.1;1;160;0;a8=1.2;a20=38;a31=1.2;a32=4.2;a33=23;a34=0.88;a36=55;a37=22;a38=6.5;a40=60;a41=2.6

**Comment by PBJellytime** [comment]
Try downloading the angelbbs fork and see if that works

**Comment by codingSince9** [comment]
Tried it out but still doesn't work

**Comment by PBJellytime** [comment]
Any log files from the logs folder?

**Comment by codingSince9** [comment]
For NHML v 1.9.0.15 - bunch of Bench_GPU, GPU_lost, log1 and log
For v 1.9.0.16 - log
To clarify. One time NHML accepted the GPU, but the computer started glitching after the benchmarks. In the end the computer was completely frozen, so i had to shut it down by holding the power button

**Comment by PBJellytime** [comment]
Upload the log.txt file into here

**Comment by codingSince9** [comment]
v. 1.9.0.16 - [log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2906976/log.txt)
v. 1.9.0.15 - [log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2906981/log.txt)

**Comment by PBJellytime** [comment]
So the 1.9.0.16 file can't seem to find the bin folder with the miners in it, but also it seems to be detecting your driver as DriverVersion 25.21.14.1917 sometimes which appears to be the same driver but a different naming convention and sometimes the correct one DriverVersion 419.17.  Try downloading the latest nvidia cuda toolkit, remove everything again using DDU and install the cuda 10 toolkit and drivers, at least thats what I'd try.  I'm also intrigued why your bin folder appears to be missing, is there an AV program running?

**Comment by codingSince9** [comment]
I will try your recommended steps, and will report after completion.
Yes ESET NOD32 Antivirus is running.

**Comment by PBJellytime** [comment]
You'll need to add an exception for the folder in your AV if you haven't already

**Comment by codingSince9** [comment]
I have added exceptions to both the previous and the latest version of NHML.

**Comment by codingSince9** [comment]
> 
> 
> So the 1.9.0.16 file can't seem to find the bin folder with the miners in it, but also it seems to be detecting your driver as DriverVersion 25.21.14.1917 sometimes which appears to be the same driver but a different naming convention and sometimes the correct one DriverVersion 419.17. Try downloading the latest nvidia cuda toolkit, remove everything again using DDU and install the cuda 10 toolkit and drivers, at least thats what I'd try. I'm also intrigued why your bin folder appears to be missing, is there an AV program running?

So i ran DDU, then installed cuda 10 toolkit, then installed driver 419.17, and all seems to be working.
Thank you for your help.
