### ISSUE TITLE
gminer won't close

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#1427]
to elaborate on the title.

g minor isn't closing, i have to x it manually.

clicking stop also doesnt close the gminer algo

**Comment by GOSEF** [comment]
Does it look like this?
https://github.com/nicehash/NiceHashMinerLegacy/issues/1420

**Comment by S74nk0** [comment]
We have changed GMiner code in the latest release.
https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.17

If the problem is not present in the v1.9.0.17 anymore please close this issue.

**Comment by jimmyhackers** [comment]
will do buddy....just gotta spend another hour benchmarking the new version......:P

**Comment by jimmyhackers** [comment]
it works so far... good job
