### ISSUE TITLE
When dual mining eth + xxx, second coin always has (target) rejection rate1-4%

### ISSUE THREAD

**Issue by lmlim** [nicehash/NiceHashMiner#143]
Hi,

I need help on reducing/eliminating rejection rate of second coin in dual mining.
According to the "interactive history chart", I believe the highest rejection is "target".
the second, some "stale" shares, then the third, there are very few "duplicates".

This happened to all, decred,sia,pascal,and lbry.

changing -dcri value does not matter much since it is not incorrect shares?

**Comment by 3zero2** [comment]
I have noticed this as well. Will be monitoring this issue.

**Comment by DillonN** [comment]
ClaymoreDual does give some errors when dual mining. Dual mining is stressful on the card and 1-4% is normal. Unfortunately it seems to be a problem with the ClaymoreDual miner itself so I don't think it can be fixed from NHML side (if anyone has ideas they'd be welcome).
