### ISSUE TITLE
nicehash miner 1.9.0.17 cannot detect AMD GPU card

### ISSUE THREAD

**Issue by benhard123** [nicehash/NiceHashMiner#1431]
My application cannot detect any amd card while in previous version it can detect my card, my amd card are Radeon RX560 and Vega 8
<img width="430" alt="capture 2" src="https://user-images.githubusercontent.com/37661885/53679646-a5f3f100-3d01-11e9-8d84-47f2ccec8892.PNG">
<img width="430" alt="capture" src="https://user-images.githubusercontent.com/37661885/53679647-a68c8780-3d01-11e9-9b53-b183bd6b0147.PNG">

**Comment by galaxytek** [comment]
1.9.0.17 also doesn't detect 750ti card, but it detects 1060 cards.
In log file it says 750ti is detected but skipped.

**Comment by mrfishbsme** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/issues/1376#issuecomment-460407470

deleting opencl.dll appears to fix it. 
this worked for me. v17 is running so far.

cheers!

**Comment by TwoSeven59** [comment]
I am the same with an AMD 7700  (and using minor version 1.9.1.5) this has been an issue for a long time.

It detects the card, starts running the benchmarks, then reports 'not all benchmarks succeeded'  Also when I select start, it puts the card under disabled.

Logfile shows the card detected, but under Enabled Devices for Mining, only the CPU is listed.
