### ISSUE TITLE
CPU Usage 100% 

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1432]
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by abhishekminer** [comment]
I am Also Facing The Issue Still In New Version Also 
I have 12 GPU NVIDIA 1080Ti,  Motherboard Gigabyte B250 FINTECH 12 Gpu Slot ,  i3 6600 3.70GHz  ,8GB Ram & windows 10.1
&
6 GPu NVIDIA 1080ti ,Gigabyte GA-h110M-h LGA 1151 Motherboard , 8 GB Ram , i7 7700 K Unlocked,
Windows 10.1
Both My Rigs CPU Usage Is at 100% & Multiple Mining windows are Opening Automatically after Intervals of time & Crashing The WIndows with BLUESCREEN Error

**Comment by ghost** [comment]
I am Also Facing 100 % Usage Of CPU ISSUE
I have 12 GPU NVIDIA 1080Ti,  Motherboard Gigabyte B250 FINTECH 12 Gpu Slot ,  i3 6600 3.70GHz  ,8GB Ram & windows 10.1
&
6 GPu NVIDIA 1080ti ,Gigabyte GA-h110M-h LGA 1151 Motherboard , 8 GB Ram , i7 7700 K Unlocked,
Windows 10.1
Both My Rigs CPU Usage Is at 100% & Multiple Mining windows are Opening Automatically after Intervals of time & Crashing The WIndows with BLUESCREEN Error

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
