### ISSUE TITLE
DUAL GTX 970 -- NHML 1.9.0.17 Fix? I Don't Know, but it is working so far 🙂👽✝ 

### ISSUE THREAD

**Issue by wxprofessor** [nicehash/NiceHashMiner#1434]
NiceHash forced me to use NHML :)  So I threw it on one of my old boxes, an Area 51-R2, with dual gtx 970s. The first thing that happened was this:
"All CUDA-Capable devices are busy" with an Error 3 on restart... this happened repeatedly.

![image](https://user-images.githubusercontent.com/5704029/53688786-35f06580-3d17-11e9-9382-e9717a991b27.png)

I did some googling and found different opinions on what should be done, so I mashed them all together... Here is what I tried and is working so far, I made a graphic to help those that may be having similar problems...  I basically think of it as Nvidia GPU Optimization for mining (on 9xx series at least.. I haven't tried this on my 1080tis yet) ... so Open Nvidia Control Panel and:

![image](https://user-images.githubusercontent.com/5704029/53688777-08a3b780-3d17-11e9-804f-11b0cfe39646.png)

1. Choose the "Manage 3D settings option"
2. Under the "Global Settings" tab, make sure that CUDA-GPUs "All" is selected
3. Next choose the DSR Factoroption, and you will notice various settings.. mine ranged from 1.20x (native resolution) to 4.00x (native resolution). I checked them all. DSR-Factor stands for "Dynamic Super Resolution" -- what it does is tell the Nvidia card that you want your PC to render a game at a higher resolution than your monitor can support, then downsample that to the display's native size. So by choosing "all" my "thought" is that I am telling Nvidia to "do the best you can do" -- I have no idea if that is right or not :)
4. Select the "Optimize for Compute Performance" option, and turn that on :) Nvidia defines this option as "This setting is intended to provide additional performance to non-gaming applications that use large CUDA address spaces and large amounts of GPU memory when run on graphics cards based on second-generation Maxwell GPUs. Graphics cards based on other architectures do not utilize this setting."

So after doing all of the above, NHML has been running on the box the entire time I have been typing this without error. Below is a screenshot of Trex running... An admin may wish to stickie this for other users that may have been struggling to get their cards working on NHML. This is the first time these cards have worked with legacy... I had always run NHv2 :)

![image](https://user-images.githubusercontent.com/5704029/53688758-c7aba300-3d16-11e9-9997-5e2fd7daab4f.png)

Good Luck! :)

http://GoodFriar.com/  🙂👽✝

**Comment by pandus19** [comment]
Great tips! If you're looking for an alternative to NiceHash or just a reliable crypto mining app, try Kryptex.

Kryptex is a Windows app that pays you for the computing power of your PC. 

It will automatically calculate your earnings every month before you start and you can earn as much as $150 per month. Cashout via bitcoin or your local currency with their free online Visa card.

Click the link below to join Kryptex and start earning now:
http://scrnch.link/kryptex
