### ISSUE TITLE
Add support for NBMiner.

### ISSUE THREAD

**Issue by nebutech-admin** [nicehash/NiceHashMiner#1436]
Hi,
    I am the developer of [NBMiner](https://github.com/NebuTech/NBMiner).
    From v20.0, NBMiner support mining Grin29 & Grin31 on nicehash.
    v21.0 provide similar hashrate compared to latest bminer and gminer.
    Please add support for NBMiner on NiceHash Legacy, means a lot to us.
    
    Thanks

**Comment by DillonN** [comment]
Hey thanks for reaching out. I'm checking out your miner now and working on integrating it!

**Comment by DillonN** [comment]
@nebutech-admin, there appears to be a watchdog in your miner. This can cause problems with NHML because it is unable to close the miner when switching. Is it possible you can add an option to disable the watchdog so that the miner only runs in one process?

**Comment by nebutech-admin** [comment]
@DillonN Add -RUN to cmd option to disable watchdog

**Comment by DillonN** [comment]
@nebutech-admin thanks! Also could you tell me if your indexing is by CUDA ID (CCMiner-like) or by PCIe bus ID (GMiner/Claymore-like)?

**Comment by nebutech-admin** [comment]
@DillonN  PCIe ID
same with nvidia-smi output

**Comment by nebutech-admin** [comment]
@DillonN 
Also,
To set environment variable
CUDA_DEVICE_ORDER = PCI_BUS_ID
can force program that use  CUDA ID equals to those use PCIe ID

**Comment by DillonN** [comment]
@nebutech-admin thanks for the tip, we are looking into that. 

Implementation of your miner is done - #1439

**Comment by DillonN** [comment]
@nebutech-admin sorry one more thing for the final implementation. 

Do you have GPU requirements in your miner? GMiner for example requires roughly 5.6GB VRAM for grin29 and 7.4 for grin31, I'd assume this would be the same? Also, GPU compute capability requirements? Thanks

**Comment by nebutech-admin** [comment]
@DillonN 
At least 5G for Grin29 & AE, 8G for Grin31.
Only support 10 series cards mining Grin & AE for now. (CC 6.1)

**Comment by S74nk0** [comment]
@nebutech-admin **NBMiner** is added https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.18. Thanks for reaching out.

We will close this issue now.

**Comment by nebutech-admin** [comment]
@DillonN New version v21.1 released with Improvement on Grin29 and support for mining Grin29 Grin31 on Turing cards.
If you plans to drop a new release, don't forget to upgrade out miner.
Thanks.

**Comment by S74nk0** [comment]
@nebutech-admin So we can enable this new miner on SM/CC 7.5?

**Comment by nebutech-admin** [comment]
@S74nk0 Yes. Support 60, 61, 62, 70, 75.

**Comment by S74nk0** [comment]
@nebutech-admin Perfect. Consider it done.

**Comment by nebutech-admin** [comment]
Oops, 62 is a mistake, supports 60, 61, 70, 75.

**Comment by Giff15** [comment]
cancelar

[https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif]<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>  Livre de vírus. www.avast.com<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.

**Comment by ghost** [comment]
Thank you

‏‫من الـ iPhone الخاص بي‬

‫في 14‏/03‏/2019 الساعة 4:27 م، كتب/كتبت ‏nebutech-admin ‏<notifications@github.com<mailto:notifications@github.com>>:‬


@S74nk0<https://github.com/S74nk0> Yes. Support 60, 61, 62, 70, 75.

**Comment by S74nk0** [comment]
Updated in latest [version](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.19)

**Comment by nebutech-admin** [comment]
@S74nk0 Hi, New version 23.3 added with support for mining Aeternity (CuckooCycle) on Nicehash.

**Comment by nebutech-admin** [comment]
@S74nk0 @DillonN 

Hi, 2 questions related to upcoming fork of Grin on 7.17.

- When do you plan to update NHML to support the fork? 
- Will NHML automatically switch the miner to the new `cuckarood` algo when the fork happens? Or is this depends on miner itself to do the auto-switch?

Thanks ahead, preparing for the new miner right now.

**Comment by S74nk0** [comment]
Hi @nebutech-admin. I am not able to answer this question at the moment. Can you please write to my email in the future stanko@nicehash.com. Or if you don't prefer email please open a new issue instead. 

Thanks.
