### ISSUE TITLE
gtx660 not detected anymore?

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#1438]
not detecting my gtx660 anymore :(

is it to old

**Comment by jimmyhackers** [comment]
here is the log file 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2938112/log.txt)

**Comment by jimmyhackers** [comment]
i have latest drivers.... tried reinstalling...still no detection

**Comment by jimmyhackers** [comment]
any word on this?

**Comment by S74nk0** [comment]
@jimmyhackers there was a mistake that removed all GPUs with SM minor 0 version in your case SM3.0.

This version fixes the problem.
https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.18

Although with the new upcoming miners SM 3.0 version will most likely not be supported. SM 5.0 is becoming the new minimum.

Closing issue...

**Comment by jimmyhackers** [comment]
thanks for the help. new version works great....

for future reference????  are gtx970's sm5.0 complatible?
