### ISSUE TITLE
1.8.1.0 - .NET Framework 3.5 Still Needed

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#144]
On a fresh installed computer when I launched NiceHash and launched the Nvidia p0 state it asked to install the 3.5 Framework feature in Windows 10

It seems like nvidia p0 state is still using the old framework?  Or maybe something else still is?

**Comment by DillonN** [comment]
Yes nvidiasetp0state.exe still needs to be updated

**Comment by DillonN** [comment]
@computeronix the projects were updated to .NET 4.5 for 1.8.1.1 pre-release 2, I'm watching for any bugs but it looks like 3.5 won't be needed anymore

**Comment by billmcilhargey** [comment]
perfect thank you!
