### ISSUE TITLE
ugggh...   NHv18 / xmr-stak - doesn't play well with amd

### ISSUE THREAD

**Issue by mrfishbsme** [nicehash/NiceHashMiner#1443]
nhv17 runs great. no issues with XMR-stak
all cpus and gpus mine!   awesome!
amd 18.10.1 drivers
This combination runs for days!

now nhv18 not so much.
i cannot keep all cards mining.  1 or 2 drop  very quickly
tried various drivers no diff.
Also, system very slow to respond when mining....   is it the interleaving?  can this be turned off?
I have a few cards that never mine no matter how many restarts
Something is not stable with the newer version of xmr-stak.

Here are log files from v17 and v18.

Hope this helps.

Cheers!
[v18.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/2948073/v18.zip)
[v17.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/2948074/v17.zip)

**Comment by vishal12212001** [comment]
for me also same Its keep restart some time its crash also . and  hash rate come lower also now. @ same cards.

**Comment by S74nk0** [comment]
@mrfishbsme @vishal12212001 please try out new [version](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.19) with updated xmr-stak. Close issue if the problem is resolved for you.

**Comment by vishal12212001** [comment]
@S74nk0 
Its downloaded and going to test today.
let you know result how its working now.

**Comment by mrfishbsme** [comment]
v19 looks good so far.

a few amd cards do not like for some reason???   see cap and debug #2

here are debugs from each machine.

also, the machine with cap and debug #3 is slower than the machine with cap #1 and debug #1.
(it should be faster)

hope this helps with code.

Thanks for support!


[debug.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/2973199/debug.zip)
