### ISSUE TITLE
Feature Request: GUI Always on Top Option

### ISSUE THREAD

**Issue by Meatball13** [nicehash/NiceHashMiner#1447]
Please build an option into the Settings to allow a user to choose to have the NHML GUI always on top of miner windows.  Often when checking a machine, I just want to see the current status, but need to minimize miner windows that have popped up over top of the main GUI or click on the GUI in the task bar to see it.

I know it's minor, but just be nice to always have that sitting front and center.

**Comment by AtlAntA118** [comment]
Yes please! I have several machines running and they do an automatic reboot every 24 hours and thus the windows arent where i put them. Always on top would make it a lot less annoying to do a quick status check.

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMinerLegacy/commit/c5d48aa1232fa46eddc98f267392931ede2d13b8) implements this feature. Will close this issue on next release

**Comment by S74nk0** [comment]
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)
