### ISSUE TITLE
Perflib

### ISSUE THREAD

**Issue by dnev3000** [nicehash/NiceHashMiner#145]
With v1.8.1.0 i get several perflib items in event viewer. Does not happen with 1.8.0.2.

**Comment by DillonN** [comment]
@hovedmannen could you try the steps on the bottom of [this](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Rig-Stats-Monitoring) Wiki page?

**Comment by dnev3000** [comment]
Thanks, that seems to get rid of them. Do i need to do this after each restart?

**Comment by DillonN** [comment]
You should only have to do it if the registry corrupts again, shouldn't happen too often

**Comment by dnev3000** [comment]
Ok, thanks for the assitance!

**Comment by DillonN** [comment]
No problem!
