### ISSUE TITLE
Team Red Miner v0.4.1

### ISSUE THREAD

**Issue by WCROOK82** [nicehash/NiceHashMiner#1451]
https://github.com/todxx/teamredminer/releases

**Comment by mgasparic** [comment]
We would like to add this miner, but we have trouble integrating it. For the benchmark purposes, we need to run this process as hidden and apparently there are some issues with that.

**Comment by S74nk0** [comment]
@WCROOK82 New [version](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.19) fixes this issue. 

Closing issue.
