### ISSUE TITLE
Update TT-Miner to 2.1.15 Nvidia GPU Miner With Improved MTP Support and Performance

### ISSUE THREAD

**Issue by Gurkan1977** [nicehash/NiceHashMiner#1453]
The latest TT-Miner Version 2.1.15 comes with improved support and performance for ZCoin (MTP algorithm) mining on NiceHash and that makes it attractive for use on NiceHash at the moment where MTP is among the most profitable algorithms. The expected performance is up to about 3.5 MH/s for GTX 1080 Ti and stability wise things seem good, though direct mining of ZCoin might also be worth it long term. It is interesting to note that other popular miners with MTP support are still lacking support for NiceHash mining, so the latest TT-Miner might still be the best option you have, not to mention that performance wise it could also be currently the fastest miner for MTP thanks to the latest optimizations.

**Comment by S74nk0** [comment]
@Gurkan1977 We have updated *TT-Miner to 2.1.17* in new [version](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.19). 

Closing issue.
