### ISSUE TITLE
TTMiner hashrate misreported on benchmark

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1455]
The hashrate in NHML for TT-Miner (since being added until today with its newly released version 2.1.17), is reported in kH/s instead of MH/s (pics 1 & 2). This requires manual adjustment to show the correct hashrate for the switching algorithm. TT-Miner reports the correct hashrate and the correct hashrate shows up in the NHML main window. In addition, the TT-miner hashrate intermittently shows as zero in the NHML main window (pic 3). Both these problems appear on 2 different rigs.

![tt-miner showing kH](https://user-images.githubusercontent.com/3432351/54378687-d7e84a00-4655-11e9-8045-b5fd9f98df09.PNG)

![tt-miner showing kH 2](https://user-images.githubusercontent.com/3432351/54378703-ddde2b00-4655-11e9-9cda-e608c2945db6.PNG)

![tt-miner showing zero hashrate](https://user-images.githubusercontent.com/3432351/54379038-a3c15900-4656-11e9-986f-bab2b1654796.PNG)

Thanks!

**Comment by S74nk0** [comment]
@jwesolo New [version](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.19) fixes this issue. 

Closing issue.
