### ISSUE TITLE
NHML not parsing ExtraLaunchParameters for Phoenix Miner

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1459]
Trying to put extra parameters for Phoenix Miner:
-clkernel 3 -gt 28 (for each card)
With -clkernel 3 and latest version 4.1c my 6 x RX588 rig can reach 195 MH/s, but NHML not parsing this parameter (-clkernel 1 by default).
Every time when NHML change algorithm to DaggerHashimoto Phoenix Miner start auto-tuning. Need few minutes before reaching effective hashrate. It is very uncomfortable. And again, NHML not parsing manually specified -gt value in ExtraLaunchParameters section. A waste of time when switching to DaggerHashimoto with auto-tuning.

**Comment by luc1an24** [comment]
You should try with **-clKernel** instead of **-clkernel** since extra launch parameters are case sensitive
