### ISSUE TITLE
Since NHML 1.9.0.15 and onward, the software does not correctly assign the order of video cards attached to my laptop. I have a built in video card, CPU and two external 1080GTX on thunderbolt 3 ports.

### ISSUE THREAD

**Issue by Doomeous** [nicehash/NiceHashMiner#1462]
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by Doomeous** [comment]
All the versions since 1.9.0.15 and onward can see all my hardware on all my laptops, but the software does not assign them correctly. It jumbles them up when you hit run and I have to watch which ones are actually working on MSI Afterburner. 1.9.0.14 sees them and actually uses them correctly, but something afterward in the software versions isn't working correctly. I'll drop the most recent version log showing the detections.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2974755/log.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
