### ISSUE TITLE
1.8.10 features support for external wallets

### ISSUE THREAD

**Issue by utc99** [nicehash/NiceHashMiner#147]
Would be nice to try new features if that would work for external wallet.
Could be option like:

*I dont care about secrecy of my computer temperature and it could be public..
*or field in Nhml for a pass key, which is needed by nicehash web to access those additional features, and it would give a privacy, and an ability to use these features for all other users which dont use nh wallet

I think this could be done and not that terribly hard, and lots of people would really appreciate it

Is anything like this being planed? This divides the comunity when part of it gets some nice features while others dont

**Comment by nicehashdev** [comment]
No, there are no plans, because we plan to add extra features to this matter and I am sure you wouldn't want others to be able to remotely restart your rigs or shut down devices ;)

**Comment by utc99** [comment]
I sill believe that there could be found a solution not leaving half of comunity behind this.

**Comment by lxblink** [comment]
I agree with @utc99. May be there is some way to attach new BTC address to the account.

**Comment by utc99** [comment]
If this is not in the plans, maybe it should apear in them, it can be achieved in multiple ways, sad to see that nobody is even trying

**Comment by utc99** [comment]
And why this topic was closed by force, could you add your thoughts about it @DillonN ?

**Comment by nicehashdev** [comment]
I closed this issue because it is not related to NHML but rather to NH service. Whatever is done regarding remote view/control of rigs is question for NH and not NHML. NHML is (just like NHMv2) only utilizing the protocol provided by NH.

**Comment by utc99** [comment]
All people who uses nhml are nh customers who uses their pools and provides hashing power, they earn profit from us by selling that hash power, and discriminating some of them becouse they use their own secure wallets and nh chooses not even consider improvments to deliver those features for them is very ignorant and very bad behavior. Why would you want to do that? Its a comunity, work together, dont divide

**Comment by nicehashdev** [comment]
We have no plans to change this for now. In any case, it would not be a simple solution and would require a lot of backend (re)work. We may add something in the future, but no promises.

**Comment by utc99** [comment]
First step is to want to make a change and deliver better quallity experience for everyone, I hope this will go trough, and we will be able to finally test it, good luck.
