### ISSUE TITLE
One Nvidia GPU 1070 not mining

### ISSUE THREAD

**Issue by larrycox** [nicehash/NiceHashMiner#1472]
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by larrycox** [comment]
I am running nicehash legacy v 1.9.0.19 with Windws 10 I have 4 nvidia 1070s and all 1070s show as mining but the Asus GPU 4 is not mining. I hope that you can assist me
![screenshot](https://user-images.githubusercontent.com/40632464/55094693-c3bd3780-50ae-11e9-8905-668a7876aaec.jpg)
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3014315/log.1.txt)
Larry Cox

**Comment by larrycox** [comment]
Thanks for that I closed it by mistake

**Comment by S74nk0** [comment]
Hi @larrycox. Extract this [device_detection_gminer_test.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/3014446/device_detection_gminer_test.zip) to v1.9.0.19 root directory and run it. This will generate `device_detection_gminer_test_output.txt` and in the console you will see `"COPY BELOW:"` please mark and copy everything below that line and post the file and copied text here.
![image](https://user-images.githubusercontent.com/1517233/55097133-87440880-50bb-11e9-8184-3f5b26547d52.png)

**Comment by larrycox** [comment]
Thank you I have appended the files.
I think I may have solved the problem  I think I need 16GB of RAM not 8GB.
[device_detection_gminer_test_output.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3017159/device_detection_gminer_test_output.txt)
