### ISSUE TITLE
Hi. i cant test grincuckatoo31    on nbminer

### ISSUE THREAD

**Issue by RfoRfoRfo** [nicehash/NiceHashMiner#1476]
gtx 1070 and gtx 1080 - stock seting or oc its this same error - terminated

**Comment by RfoRfoRfo** [comment]
nbminer 21.4 this same err.

**Comment by luc1an24** [comment]
Hi
if you are using Win10 you need to have at least  10GB Card which neither of these 2 cards are.
This is the reason the cuckatoo31 algorithm isn't running.
