### ISSUE TITLE
Error CL_MEM_OBJECT_ALLOCATION_FAILURE 

### ISSUE THREAD

**Issue by mrfishbsme** [nicehash/NiceHashMiner#1477]
Error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clEnqueueNDRangeKernel for kernel 0.

v20
radeon 18.10.1

i get the following error when i enable gpu #1.

I tried different cards/cables/slots. still same error.

I disable gpu #1 and no issue.

any help is appreciated.

cheers!

Here are files.
[xmr-stak-dbug.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3026025/xmr-stak-dbug.txt)
[device_detection_test_output.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3026026/device_detection_test_output.txt)

[xmr-stak-dbug-no-gpu-1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3026033/xmr-stak-dbug-no-gpu-1.txt)

**Comment by techman05** [comment]
I think I'm seeing that too but I thought it was something with the benchmarking. If you read the log I think the allocation failure is listed because the nice hash miner not being run as an admin.

**Comment by mrfishbsme** [comment]
thanks for responding.
i do run as admin.
i notice that when i benchmark xmrstak-R is not selected by default.
I believe they are not ready for amd cards. or older cards are getting phased out.
I installed a simple gpu in slot 1 and dont mine with it.
the rest of the cards mine as normal.
simple work around.

Hope this helps others.
