### ISSUE TITLE
sg-miner, xmr-stak

### ISSUE THREAD

**Issue by YuriyNa** [nicehash/NiceHashMiner#1479]
sg-miner and xmr-stak do not work with amd in rigs. Why do you include them in the assembly? There are other miners who work and much more profitable than these.

**Comment by S74nk0** [comment]
@YuriyNa These are popular open source miners. If you have a suggestion on adding new miners name them and we might add them in future releases.

**Comment by YuriyNa** [comment]
Here are the miners:
https://github.com/andru-kun/wildrig-multi/releases/
https://bitcointalk.org/index.php?topic=4724735.0
https://www.srbminer.com/download.html
You also added a GMiner, but for some reason did not add Cuckaroo29 support for AMD.

**Comment by S74nk0** [comment]
[WildRig](https://github.com/nicehash/NiceHashMinerLegacy/tree/master/src/Miners/WildRig) is implemented and will be added. [LolMinerBeam](https://github.com/nicehash/NiceHashMinerLegacy/tree/master/src/Miners/LolMinerBeam) as well. SRBMiner isn't compatible with nicehash and was giving lots of rejected shares. We will re-check SRBMiner and implement it if it is compatible now.
