### ISSUE TITLE
CudaDeviceDetection.exe System Error

### ISSUE THREAD

**Issue by Loveistheair** [nicehash/NiceHashMiner#148]
When I try to start the miner I get an error 

CudaDeviceDetection.exe System Error

Running the program is not possible because the computer does not exist

api-ms-win-crt-runtime-l1-1-0.dll

How to remove this error, someone can help?
<img width="388" alt="2017-08-12_181452" src="https://user-images.githubusercontent.com/30957034/29241818-2c892e88-7f8a-11e7-80c1-d48b22bb36d4.png">

**Comment by DillonN** [comment]
Hello @Loveistheair, please see #131 which was the same issue but for a miner exe. I'll add info to the wiki for future reference
