### ISSUE TITLE
Feature request: Ability to rename cards under Devices

### ISSUE THREAD

**Issue by VicePrez** [nicehash/NiceHashMiner#149]
Would be nice to rename a card under Devices - both in the main window and in Settings - > Devices/Algorithms. I find myself having difficulty diagnosing issues with cards of the same model.

**Comment by DillonN** [comment]
Thanks for the suggestion @VicePrez, I will look into this

**Comment by VicePrez** [comment]
Cheers

**Comment by S74nk0** [comment]
![image](https://user-images.githubusercontent.com/1517233/164676571-8f15f1ff-191c-468e-9eba-4f3d30215fbf.png)
