### ISSUE TITLE
Chrome Says It Is Dangerous

### ISSUE THREAD

**Issue by hi1213345446231** [nicehash/NiceHashMiner#1496]
Chrome Says It Is Dangerous And Wont Download

**Comment by luc1an24** [comment]
NiceHash Miner Legacy is usually flagged by AV (anti-virus) software. This is normal, as almost every mining software on the market is blacklisted by AV. Just make an exception in your AV software to enable the proper operation of NHML or in your case allow zipped file to be downloaded and then add exception. Here is also help article for this matter: https://www.nicehash.com/help/my-browser-antivirus-software-reports-nhm-as-a-virus
