### ISSUE TITLE
Update guide not correct

### ISSUE THREAD

**Issue by Stufman** [nicehash/NiceHashMiner#1497]
Hi,

The text for upgrading NiceHash Legacy is not correct:(https://github.com/nicehash/NiceHashMinerLegacy/wiki/Getting-Started#-upgrading)

It says that you should copy the CONFIGS folder to the already installed Legacy folder. But there is no CONFIGS folder in the newest downloaded files (nhm_windows_1.9.0.20)

So I couldn't follow the update guide, had to reinstall from scratch again.

**Comment by GrannyCryptomaster** [comment]
You must copy only the CONFIGS folder from the old install folder to the new install folder.
It's very clearly explained. In the new folder you don't have many folders that are created by the first run of the n..h..m..l....exe. There is no Configs folder also. So if you have the old folder, NHML 1.9.0.19, and the new folder, NHML 1.9.0.20, you take the Configs folder from NHML 1.9.0.19 and put it in NHML 1.9.0.20. And then run the nhml....exe. At the first run of the new version, with the old Configs folder in it,  it will give you some attention messages... you must press Yes, and let it restart and download/reconstruct the things that are specified there... You can get that message 2-3 times. After all downloading and upgrading is done it will remain in the GUI or start mining, if you have the parameter set to automaticaly start mining.

**Comment by Stufman** [comment]
> You must copy only the CONFIGS folder from the old install folder to the new install folder.
> It's very clearly explained. In the new folder you don't have many folders that are created by the first run of the n..h..m..l....exe. There is no Configs folder also. So if you have the old folder, NHML 1.9.0.19, and the new folder, NHML 1.9.0.20, you take the Configs folder from NHML 1.9.0.19 and put it in NHML 1.9.0.20. And then run the nhml....exe. At the first run of the new version, with the old Configs folder in it, it will give you some attention messages... you must press Yes, and let it restart and download/reconstruct the things that are specified there... You can get that message 2-3 times. After all downloading and upgrading is done it will remain in the GUI or start mining, if you have the parameter set to automaticaly start mining.

I can't belive how I couldn't understand that.. Wow. It's totally logical when I read it now.. My bad. And thanks for the explanation. The brain is not always in top shape :D

**Comment by luc1an24** [comment]
Closing the issue. Problem was solved.
