### ISSUE TITLE
internet connection failure during startup prevents use of application

### ISSUE THREAD

**Issue by CreamyG31337** [nicehash/NiceHashMiner#15]
I see this happen sometimes if I'm using wifi -- nicehash starts and says that it failed to get the SMA data or whatever and press OK to continue or press something else to exit or whatever. 
I verify that the connection is working, then I hit OK, but Nicehash refuses to continue. I have to hit whatever the other button is and restart it, then it works fine. 
I've seen people complain about issues with the connection before, I'm not sure if this is related or not, but it definitely can cause confusion. I guess if the WiFi is slow to connect it will also block the mining from starting if say there was a power outage and the computer comes back online before the router, Nicehash is just going to sit there forever. 
I assume you can duplicate this easily and it's not something weird on my end -- let me know if not.

**Comment by DillonN** [comment]
Right now, NHML will check on startup for a connection to NH servers. If it can't connect (times out, firewall, etc) it will try again in another second. If you click OK to open NHML it will then check once every 2 minutes.

This isn't the most ideal setup, and there are currently plans to overhaul the NHML to NH connection.

**Comment by billmcilhargey** [comment]
I also noticed and if I hit no sometimes it still continues checking other pieces rather than immediately quitting

**Comment by koraybilgi** [comment]
Wifi or not, if internet drops out for a period of time and comes back online, Nicehash does nothing until the user clicks one of the buttons. It's a big issue especially for remote machines.

Could you at least make it optional to display the warning messagebox. And let the app try to connect every 2 minutes in background?

Thx.

**Comment by kevinmilesM** [comment]
Here is the fix - https://www.youtube.com/watch?v=QjNLVNANOrU
