### ISSUE TITLE
Miner(s) changing GPU settings automatically - UPDATE

### ISSUE THREAD

**Issue by pedrojs-sapo** [nicehash/NiceHashMiner#1515]
Hi

I have an Update on this "problem".
The problem is "really" with NiceHash. Now I'm sure.

Since my Power Supply can't handle all GPU's at 100% TDP, I use MSI Afterburner to
keep GPU Power on 80%. Since NiceHash changes GPU settings daily and automatically to 100% TDP, I was getting RIG shutdowns daily.

I like NiceHash a lot but I had to do something because I was loosing money.

Three days ago I started using CUDO Miner. Same "philosophy" as Niceash and also uses 3rd Party Miners.
Its is now 3 days since I'm using CUDO and GPU settings didn't change at all and the Rig is up and running :-).

Could you please try to solve this problem?
I'd like to use NiceHash but I can't till this "bug" is solved.

Thanks

Pedro JS

**Comment by rkresha** [comment]
Might be worth adding this update to the original issue (#1480) and closing this one out.

**Comment by pedrojs-sapo** [comment]
Update added to first issue (#1480)
