### ISSUE TITLE
Dual mining ETH + Decred

### ISSUE THREAD

**Issue by higi** [nicehash/NiceHashMiner#1518]
there is missing parameter after: -dcoin should be -dcoin dcr

EthDcrMiner64.exe -di 0 -platform 1  -dcri 30  -epool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 -ewal 3MHRjv8ntVcBjvSzZb9BKfj6HJd9ECMjvd.inp -mport 127.0.0.1:-4000 -esm 3 -epsw x -allpools 1 -dcoin  -dpool stratum+tcp://decred.eu.nicehash.com:3354 -dwal 3MHRjv8ntVcBjvSzZb9BKfj6HJd9ECMjvd.inp -dpsw x -dbg -1

**Comment by S74nk0** [comment]
@higi Use version [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4).

Closing issue.
