### ISSUE TITLE
blake2s gpu mining problem

### ISSUE THREAD

**Issue by TuSuNaMi** [nicehash/NiceHashMiner#152]
Hello, if I selected blake2s mining on my program i give following problem. 

GPU NVIDIA GRID K1 on Virtual Machine program see GPU card no problem but.

https://drive.google.com/open?id=0B46zbIw1eOxwNTdqdlFqeWZxMTg

Thanks

**Comment by utc99** [comment]
I have the same problem, lowering intensity seems to fix it,  yet on one machine it still apears after some time. --intensity=27
