### ISSUE TITLE
NHLM stuck on "getting NiceHash SMA Information", stops responding.

### ISSUE THREAD

**Issue by SomethingNew88** [nicehash/NiceHashMiner#1522]
When I launch NHLM v1.9.0.20, it gets stuck on "getting NiceHash SMA Information", and simply stops responding. I am not sure how to resolve this issue. Rebooting hasn't worked. Running it while all other things are closed hasn't worked. Not sure what to do.

**Comment by S74nk0** [comment]
You cannot access the following endpoint https://nhmws.nicehash.com/v2/nhm. This is a networking issue on your side. There is nothing we can do about this. 

Closing issue.
