### ISSUE TITLE
Wrong GPU enumeration at Benchmark and normal run on mixed systems

### ISSUE THREAD

**Issue by electricdelicate** [nicehash/NiceHashMiner#1526]
Unfortunately since few versions, the enumeration seems to be wrong. The Benchmark takes for example the wrong card for measuring the hash speed of dagger hashimoto with the phoenix miner. I see that directly with MSI Afterburner, which runs in backround. The same with the real run and this issue crashed my entire system if 2 miner want to use the same card at the same time ... :(

And as already wrote, this is since the last x versions, please fix that, the fork fix for example do not have this issue at all.

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3178648/log.txt)

**Comment by S74nk0** [comment]
There was a mistake in ClaymoreBase plugin. Please try https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.2 and close this issue if the problem is resolved.

**Comment by S74nk0** [comment]
Issue fixed in Alpha version 1.9.1.2+.

Closing.
