### ISSUE TITLE
Can't save manual benchmarks in the settings of 1.9.1.1

### ISSUE THREAD

**Issue by mrMad-Cat** [nicehash/NiceHashMiner#1527]
The problem goes as it is in the title. No meter in which order I enable, disable algos, enter new data, press "save and close settings". The data is simply not saved. This is a problem with x16 CCminer for NVidia (which benches for 1080ti as 35MH, but works more like at 13-15), didn't try with other algos. I also noticed that when I clear benches and then start mining and then stop it - there are again new benches saved in the settings as if I lunched auto benchmarking, though I haven't.
It was somewhat tricky in previous versions, but now it looks like impossible to save manual benchmarks.

**Comment by S74nk0** [comment]
Please try https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.2. If this version fixes the *bug* please close the issue.

**Comment by mrMad-Cat** [comment]
Now all is ok. Thnx!
