### ISSUE TITLE
All the windows and tables resizes need to be saved (especialy for high res monitors)

### ISSUE THREAD

**Issue by mrMad-Cat** [nicehash/NiceHashMiner#1528]
It has always been a problem for NHML, but for 1.9.1.1 it is even a bigger one. The program does not remember user settings for resized windows and columns. This is an issue in general for all the parts: benchmarks , settings, main window, etc.
In fact this issue can be divided into few subproblems:
1) On 4k monitor with 300% scaling this is even a bigger problem because program is definitely not set for such scaling and it acts very weird so you can't even see any numbers and data before you start moving borders.
2) All the miners' windows can have their own settings of positioning, sizes and font size. And it is great. Only this settings are lost in every update. So there is no sense in setting this as it is lost very soon. I would also suggest NHML could save this settings.
3) I would also suggest that NHML could be auto-sized more adequately from the beginning. The main window should be sized so that all the GPUs and their data are visible when it is opened and when it is mining, without any scrolling (if the screen's resolution permits it). When you open benchmarks - again it could be great you could see as much of algos and GPUs as the heights of your resolution permits. It would also be great to see more than 4 GPUs in the upper section. All the same goes for settings window with all that algos and GPUs.
4) The box with GPUs in the benchmarking window is not resizable so we can see only 4 at once. Would be great to make it user resizable.
5) Columns of the tables in the benchmarking, mining, settings etc. need to be manually resized every time. Definitely could be useful to save their width.
6) All the above mentioned user resizing, as mentioned in the beginning, should be auto-saved.
7) There is a problem when the main NHML windows is too high, when you open settings or benchmarks - the header of these windows becomes unreachable for user to close or move them.

**Comment by S74nk0** [comment]
@mrMad-Cat Currently GUI features are on the hold and are lowest priority but we are considering to re-implement the GUI with WPF.

**Comment by mrMad-Cat** [comment]
I found a partly solution with a shareware program WindowManager ( http://www.desksoft.com/WindowManager.htm ). It can remember all the position, sizes and states of all the windows including Settings, Benchmarks etc. and restore them automatically. I definitely like the end result. Will work till it's an option in NHML.

**Comment by S74nk0** [comment]
We are working on a new GUI implementation that should fix these problems.

**Comment by mrMad-Cat** [comment]
It is nice to hear because situation with 1.9.1.5 looks even worth.
![Screenshot (8)](https://user-images.githubusercontent.com/47658445/60370620-c4dc6880-99ff-11e9-8821-a9a6ed91a59a.png)
