### ISSUE TITLE
using integrated graphics for performance gains?

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#153]
noob here.

i have an old dell xps 630i gpu mining away with a gtx 660 (cpu is too pants to mine with)
i plan on adding another gtx 770 4gb to it, hopefully mismatched cards run fine on the same rig for mining?

im wondering however.......as my cpu is free in this rig....if i plug my monitor into the integrated graphics and use that to render the screen/display....will this free up some extra gpu power for mining?

i ask because i noticed some weird quirk on my main gaming pc (triple monitors) that im also gpu mining with the gtx 770.

if left to go to standby (3 screen are off) my mining rate increases. have one two or three screen on reduces this proportionately. (losing over 1mh out of 8)

seeing as most people (i assume) would be running the screen off the gpu that they will be mining with and this has to be on/rendered during the benchmarks. Couldnt this also add further benchmark innacuracies and potential loses in mining?

am i onto something here?
thanks in advance for the advice
jim

**Comment by DillonN** [comment]
Using integrated graphics can help with mining performance if you are close to the card's VRAM limit and the displays you use take up too much VRAM

There shouldn't be any problems with not having displays plugged into the GPUs in regards to mining/benchmarking

**Comment by streaml1ne555** [comment]
Using integrated definitely helps. It can help you overclock a bit more without running into driver crashes. It can also reduce power use slightly since some cards can save some power when they don't have to drive a display.

**Comment by jimmyhackers** [comment]
thanks for the info....being the dingle i am i didnt check the older pc (xps 630i).....it has no intergrated graphics.  however it has two full 16xpcie slots and one pciex4.

would running a "thrid" rubbish low power card like a 8400gs i have lying about in the x4pcie socket with a riser just to render the screen be worth it?

bear in mind i check on this rig  once a day then leave it alone so screen rendering time is about 5 mins in every 24 hours.

**Comment by streaml1ne555** [comment]
If the power budget is acceptable that could work. Two things I've run into is that sometimes turning on the monitor will cause a driver crash for me. You may want to use a different brand video card so you're not interfering with the Nvidia driver in any way. Bear in mind my issue is probably because I have a high strung overclock and it doesn't happen often. The other thing I've noticed that helps with display driver crashing when a monitor is involved is to turn off the display sleep in Power Options in the Windows control panel.

**Comment by jimmyhackers** [comment]
thanks for the info. 
mine seems ok with display sleep, ive put it down to two minutes. i figure the sooner my monitors turns themselves off the more power i save. plus the quicker my pc ramps up its mining rate.

im getting a newer card soon. meaning my current 770 will go into an older machine with a 660. hopefully their drivers wont have conflicting issues.

**Comment by jimmyhackers** [comment]
ive recently got a 1080ti so my gtx770 has gone into my older pc with the gtx660.

i kept the 660 as the screen rendering gpu. the gtx770 was hashing about 50% quicker than it was in my main rig.

annoyingly the psu died with sparks n smoke an hour into running (getting better one 2morrow)

anyway... a 50% increase is rather a substantial. can anyone else confirm this with their hardware please?

**Comment by streaml1ne555** [comment]
I haven't seen 50% gains, more like 5%. Were the driver versions the same between both systems? Both the same Windows version? Someone reported a 50% loss in perf when running on 1703 Windows (probably driver related on the newer Windows ver).

**Comment by jimmyhackers** [comment]
same driver,OS, etc etc.
 only difference is its not rendering a monitor while benchmarking.

also nicehash install folder is on an 60gb ssd instead now. it was on 2x 750gb in raid0. 
would an ssd over a hdd make much difference?

also the cpu was a 3700k that was also mining at the time.
now its an e6600 processor thats to pants to mine with.

**Comment by jimmyhackers** [comment]
got a new £20, 700w power supply (that smelt funny and shut down twice in an hour)
returned said power supply after an hour for a £50, 700w psu (that is working)

before the first psu went poof the gtx770 was hashing at about 14.5mh/s
its now decided to hash at a steady 10.5-11mh/s. 
in the old rig it wouldn't go past 9.5mh/s

not quite 50% anymore :(. closer to %10-15 thats not bad though either.

what ever magic the original (deadpsu) had, i let it go in the form of its "magical smoke"
