### ISSUE TITLE
Form_Loading Error

### ISSUE THREAD

**Issue by paininflictor** [nicehash/NiceHashMiner#1532]
![issue](https://user-images.githubusercontent.com/50700475/57845958-22468e00-77a1-11e9-847a-cf23096f6ff5.png)

**Comment by Maas1337** [comment]
Got it too. unable to use *:21

**Comment by Skuritas** [comment]
I have the same Problem.

**Comment by tiztrain** [comment]
Same. Using a gtx 1080ti

**Comment by buziyborni** [comment]
i have the same error how do i fix it

**Comment by S74nk0** [comment]
Please try https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.22 it should fix this issue.

**Comment by buziyborni** [comment]
thanks it works
