### ISSUE TITLE
1.9.1.2 amd not showing hash in nhlegacy window

### ISSUE THREAD

**Issue by sephir69** [nicehash/NiceHashMiner#1533]
![Untitled](https://user-images.githubusercontent.com/2382268/58049937-0aae3300-7b1c-11e9-9220-356346b75a1c.png)
not sure if it's switching to most profitable algo anymore either,  if i disable cryptonight it will show hash and stats for claymore when running

**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by S74nk0** [comment]
@sephir69 Your issue is related to #1545. It is just a GUI bug you are hashing the most profitable algorithm. This is fixed in [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4).

Closing issue.
