### ISSUE TITLE
bin_3rdparty.zip wrong link

### ISSUE THREAD

**Issue by moops44** [nicehash/NiceHashMiner#1534]
On the latest  Release 1.9.0.22 on Github the "bin_3rdparty.zip" file rediricts to the nhm_windows_1.9.0.21.zip file pls fix :)

**Comment by S74nk0** [comment]
This is on purpose. With [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4) and onward all miner plugins will be downloaded separately.
We will add a section to the Wiki that will describe how to manually install plugins in case of failure.

Closing issue.

**Comment by moops44** [comment]
@S74nk0  You dont understand the Issue

Go to this Site 
https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.22

and download the file called " bin_3rdparty.zip "
Then tell me thats the right Link to the 3RDPARTY Miners
