### ISSUE TITLE
what is the right way to upgrade?

### ISSUE THREAD

**Issue by salighie** [nicehash/NiceHashMiner#1537]
With every new release, it seems, we need to go through the initial setup and benchmarks.

What is the proper way to upgrade to the next version, without losing all benchmark information, mining settings etc?

**Comment by LStratos** [comment]
I like to know this question as well

**Comment by F1Rumors** [comment]
The instructions state you should copy the config directory from the old installation to the new installation before you start the app for the first time.  This will carry the old benchmarks to the new location and it has worked reliably for me.  BE aware that you should re-bench any miners that change version, and it is not a good idea when changing a higher order version!

See the [wiki page](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Getting-Started#-upgrading).

**Comment by salighie** [comment]
thanks
