### ISSUE TITLE
Performance of NBminer in v1.9.1.2 is half that of v1.9.0.22

### ISSUE THREAD

**Issue by F1Rumors** [nicehash/NiceHashMiner#1539]
I fired up the new alpha v1.9.1.2 and after benchmarking, kicked it off to do its thing.  For mining Grin31 the hash rate was about half the hash rate for the same miner under v1.9.0.22

Switching back to the old version restored the old has rate.

This is repeatable - happens every time I try it... I have not spent time looking at the other algorithms.

**Comment by F1Rumors** [comment]
Given a week has passed with no response, I ask - is this actually the correct route for reporting issues?

**Comment by luc1an24** [comment]
@F1Rumors Thank you for your submit.
This is correct route to report issues, but since GitHub is used only by developers the response time is really slow. The main address to report issues is support email: support@nicehash.com

But don't worry we check each issue and we are already in contact with the developer of NBMiner, since the last version has some issues with Grin31.
Thank you for your patience!

**Comment by S74nk0** [comment]
@F1Rumors this issue isn't related to NHML. Check out this [answer](https://github.com/nicehash/NiceHashMinerLegacy/issues/1548#issuecomment-498624650).

Closing issue.

**Comment by F1Rumors** [comment]
Sorry, the answer does not explain why this is unrelated NHML.  Let me express this differently: running _the NBMiner miner_ was yielding _half_ the hashrate when launched from the alpha version 1.9.1.2 of NHML compared to the legacy version 1.9.0.22 of NHML.  I did not change anything other than the version of NHML that was launched, as far as I am aware.

This indicates that NBMiner, as set up, installed or launched from the alpha NHLM was not operating in the same league as the same miner in the original NHML - rebooting and firing up the other version of NHML reliably produced the same results.

**Comment by F1Rumors** [comment]
I should mention: under alpha version 1.9.1.4 the hashrate is the same as the 1.9.0.22 version, so whatever the issue was, it is **resolved**.  This issue is correctly closed!
