### ISSUE TITLE
skunk hits nicehash which time to import NHML? 

### ISSUE THREAD

**Issue by Avalonis** [nicehash/NiceHashMiner#154]
Dear  DillonN,
can you fast as possible the skunk algo into NHML, because its a heavy impact to earn coins. Equi gives me round on the 1080 TI 2,70 € atm its ok, but skunk will give me give 6,14 € atm . 

I have testet with https://github.com/krnlx/ccminer-skunk-krnlx but i earned only booos oder rejetects from nice hash.

my start bat. 
ccminer -a skunk -o stratum+tcp://skunk.eu.nicehash.com:3362 -u adress.skunk 

have anyone any idea to mine it on NH or any hint for the start bat.

It would be great if you could integrate it.

greetings Avalon

**Comment by navjack** [comment]
it works just fine with the one linked here
https://github.com/signatumd/releases/blob/master/ccminer-2.2-skunk.zip

ccminer-x64.exe -a skunk -o stratum+tcp://skunk.usa.nicehash.com:3362 -u xxx.xxx

**Comment by DillonN** [comment]
This is being worked on

**Comment by Avalonis** [comment]
Thanks in advance DillonN for your work, :) 

@navjack I become only booo's with "reject : share above target's " any idea or tweak in the settings?

**Comment by luongk** [comment]
@Avalonis I'm having the same issue - just rejected shares.

**Comment by Avalonis** [comment]
Dear friends
This miner are functionable :) happy mining

https://github.com/tpruvot/ccminer/releases

https://github.com/tpruvot/ccminer/releases/download/v2.2-tpruvot/ccminer-x64-2.2.7z

Bye Avalon

**Comment by DillonN** [comment]
@Avalonis @luongk there was an update to NH servers that should have solved the rejected share issues

**Comment by Avalonis** [comment]
Ok then , thanks for the info, i will test now serverals miners to see wich is the best.

**Comment by luongk** [comment]
@DillonN Thanks dude, looking forward to the next release!

**Comment by adem4ik** [comment]
Just a small note on my benchs on Nvidia GTX 1060 6GB

12 MH/s: https://github.com/signatumd/releases/blob/master/ccminer-2.2-skunk.zip 
17 MH/s: https://github.com/palginpav/ccminer/releases/tag/1.1.1
19 MH/s: https://github.com/tpruvot/ccminer/releases/download/v2.2-tpruvot/ccminer-x64-2.2.7z

**Comment by luongk** [comment]
@adem4ik Agreed, significantly better hashrate on the tpruvot fork on my 1080ti + 980 - thanks for the heads up

**Comment by JCarangoH** [comment]
This 3rd party miner is good for AMD cards:

Prospector - https://bitcointalk.org/index.php?topic=2033185.0

Also can mine xmr in cpu but not tryed currently, with Rx 470 GPU goes for 16.8 MH/s and i think it can push more, only binary file is available

**Comment by DillonN** [comment]
@JCarangoH thanks I have been looking at prospector, might consider adding it as a new 3rd party miner (it does have 1% devfee though)

@adem4ik thanks for that info. Have you tried krnlx fork https://github.com/krnlx/ccminer-skunk-krnlx? There are no releases posted but you can find a compiled version [here](http://cryptomining-blog.com/8989-new-ccminer-skunk-krnlx-fork-with-faster-skunkhash-performance/)

**Comment by Avalonis** [comment]
the krnlx, give me arround 40-45 mh (1080ti Palit GeForce GTX 1080 Ti GameRock Premium)AB 80% +80 cpu + 499 ram and the tpruvot gives me around 53 mh (round about ~230 W) stable

**Comment by DillonN** [comment]
@Avalonis Ok I will look at making tpruvot the default

There is now a pre-release up that has Skunk support for NVIDIA (default is krnlx but you can just paste over `ccminer_krnlx\ccminer.exe` with another fork if you like)

https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.1.1-Pre1

**Comment by JCarangoH** [comment]
@DillonN After 4 attempts testing prospector, i had an average of half-hour of mining before crashing, seems to use all the RAM to perform, I realized checking task manager on performance tab, almost 7,8 - 7,9 of RAM usage with the miner running, so the miner it's still not optimized for ram usage, but i did plenty get 18.6 MH/s with stock clocks and modded BIOS.

**Comment by Avalonis** [comment]
ok testet with my rig, krnlx give round 150 mh and the tpruvot round 180 - 186 ... but you might added extra start params "--cpu-priority=4" if not you take 180 litle later under 180 with the param its starting at 186 und go down to 183

**Comment by navjack** [comment]
doing great now on my 980ti and 1080ti with the tpruvot ccminer. 31mh and 58mh respectively. 
EDIT: oh and -i 27 for the 1080ti and -i 25 for the 980ti
EDIT AGAIN SORRY: Power Target +127% +350ram for about 2088mhz core and 5355mhz ram on an evga 1080ti ftw3 & gigabyte 980ti xtreme locked at 1520mhz and 5000mhz ram with bios mod

**Comment by DillonN** [comment]
@JCarangoH it seems to be working well enough for me, but it may need more than average RAM (around 0.5GB on one card here). Problem is I don't have any new cards to try and it's not profitable on older cards (290x, Fury X)

**Comment by navjack** [comment]
i have an rx480... i'd test it but i'm not thinking it'd be worth it. estimated profit more then 0.0005 BTC/day? cuz thats what i'm making on daghash

**Comment by DillonN** [comment]
@navjack I think it is decently profitable for Polaris cards (400 and 500 series), around 5x higher than I was seeing on 290x

**Comment by navjack** [comment]
this algo is def a perfect fit for big maxwell and big pascal

**Comment by Avalonis** [comment]
if i take in the 16 mh for one rx470 it give me atm  1,70 € , i have a 470 and 570 stock bios .. thy give me 3,19 € so 2x1,70 are 3,40 . its is bettter than dagger/decret atm, how much watt ... but need a exe to test , i have no windows compiling software.

**Comment by DillonN** [comment]
@Avalonis there is no source yet for NHML prospector, still working on it. Hopefully can have it for pre-release 2 in a couple of hours

**Comment by JCarangoH** [comment]
@DillonN @navjack My VRAM doesnt full more than 0.5GB, but is fullfilling the system RAM all the way.

**Comment by navjack** [comment]
![image](https://user-images.githubusercontent.com/7362750/29298570-cc5ab780-8136-11e7-8399-e1f2b87542cb.png)

thats using the tpru

**Comment by ChriscomIT** [comment]
@navjack Whats your CPU OC (core clocks and ring clocks)??? And how many threads do u utilize in NHML settings? I am wondering cause with i7-5930k I only get max 360H/s with all software optimizations enabled.

**Comment by Avalonis** [comment]
@navjack at what clock are the gpu ? ram can i see but gpu are not there?

**Comment by navjack** [comment]
@Avalonis from my previous message

> EDIT AGAIN SORRY: Power Target +127% +350ram for about 2088mhz core and 5355mhz ram on an evga 1080ti ftw3 & gigabyte 980ti xtreme locked at 1520mhz and 5000mhz ram with bios mod

@ChriscomIT HA! 4.6ghz core @ 4.4ghz cache and i use process lasso to manually set the affinity. mining is on 7 threads.

**Comment by ChriscomIT** [comment]
@navjack Ok thanks. I have to crank up my cache clocks then. Yeah, long time since I used ProcessLasso but I might give it a try again.

**Comment by navjack** [comment]
yeah i come from a gaming/overclocking background and really not a mining background. so power efficiency isn't something i look for. i just push my hardware to its limits :D

**Comment by ChriscomIT** [comment]
@navjack Same for me but I am into mining now as well like gaming/OCing since the last year. But wanted my PC running 110% stable the last month so I did set back everything in bios despite the core clocks. But I forgot what cache clock I had set. Your values seem pretty good btw. Do you run this stable 24/7?

**Comment by navjack** [comment]
yeah, when i'm not mining i can play games (if i don't want money LOL) or mess around in cinema4d as a hobby. my 2nd rig is a ryzen 1800x @ 3.95ghz with an rx480 and 980ti in it. now that ryzen REALLY kicks-butt on cpu mining

**Comment by JCarangoH** [comment]
@DillonN Testing now this one:

sgminer fork: https://github.com/signatumd/releases/blob/master/sigt-miner.zip

this one with -I d, it set to 16 and get to 12.67 MH/s, no system RAM overloaded, keeps steady at 2.0gb, increased by steps to -I 22 for a 15.MH/s speed. this one seems more stable

EDIT: i pushed to 24 and got crashed, for me i think -I 23 is the max, if Prospector didnt had the system RAM issue definitely is the best choice at this moment for AMD Signatum mining

**Comment by adem4ik** [comment]
@DillonN on GTX 1060 6GB
krnlx: 17.8 MH/s
tpruvot: 18.5 MH/s

both seems stable

**Comment by DillonN** [comment]
@adem4ik thanks, looks like consensus is tpruvot so that will be used in next prerelease

@JCarangoH I tried that sgminer but had a lot of trouble getting it working in NHML, Have you tried raising your page file setting for Prospector?

**Comment by JCarangoH** [comment]
@DillonN  I have 2 Hard drives and each one has 8GB minimum and 16GB maximum page file setting, i can't/don't know to set this in the miner :/

**Comment by DillonN** [comment]
1.8.1.1 Pre-release 2 is up with Prospector support https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.1.1-Pre2

@JCarangoH not sure why it would be running at max memory then, hopefully now that it is in NHML we can see if others are having the issue

**Comment by 3zero2** [comment]
Skunk on tpruvot only gives me 50.62MH/s on an a Titan Xp. On 1080TI it's giving me 55MH/s.

I'm at a loss why the Titan Xp is not faster. Anyone with any ideas please?
