### ISSUE TITLE
Captcha Error, please try again

### ISSUE THREAD

**Issue by JamieVangeysel** [nicehash/NiceHashMiner#1543]
After starting NHM2 since it has been a while it told me to use the legacy miner NHML so I did. Thanks for this message!

I am however stuck on the login screen and god knows why there is a captcha field. I gave up after re-entering my credentials and 2FA key for over 5 minutes and just used the bitcoin address to get started. which leads to my first issue/question?
- Why clear all fields? (leave the username)
- Why the captcha field? (added benefits are non-existent)

I know this should not be an issue for most after logged in and Maybe I'm just used to better-implemented security and rate limiting measures or maybe for some arbitrary reason is this thing case sensitive I don't know.

Also when downloading miners, why is the GUI blocked? do this in a separate Thread or maybe even a background worker?

Pretty sure I'm just pissed since this started off quite frustrating but nonetheless maybe worth to look at this criticism.

**Comment by S74nk0** [comment]
Thank you for your insight. New Alpha version already have requested improvements e.g. [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4).

Closing issue.
