### ISSUE TITLE
PhoenixMiner Daggerhashimoto no stats in NHML (1.9.1.x)

### ISSUE THREAD

**Issue by mrMad-Cat** [nicehash/NiceHashMiner#1545]
It was a problem with 1.9.1.1 and continues with 1.9.1.2.
PhoenixMiner with Daggerhashimoto does not pass stats to NHML. As you can see, all is working but in the NHML lower window there is no info on what all the GPUs are working. As a result there is no profitability info.
![NHML_issue_nostats](https://user-images.githubusercontent.com/47658445/58627159-2913eb80-82df-11e9-8561-16bf1347dd74.png)

**Comment by luc1an24** [comment]
@mrMad-Cat  Thank you for your report.
We are working on this issue and it will be fixed in one of upcoming Alpha releases.

**Comment by S74nk0** [comment]
Fixed in [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4).

Closing issue.
