### ISSUE TITLE
Upgrade Claymore Dual to 9.8

### ISSUE THREAD

**Issue by candrews** [nicehash/NiceHashMiner#155]
Claymore dual miner 9.8 has been released: https://github.com/nanopool/Claymore-Dual-Miner/releases/tag/v9.8

**Comment by adem4ik** [comment]
afaik it's already updated to 9.8 in https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.1.0 but dunno where from

**Comment by DillonN** [comment]
Yes it's already updated to 9.8, the version posted by Claymore
