### ISSUE TITLE
v1.9.14 alpha Win10 issues

### ISSUE THREAD

**Issue by Dycast** [nicehash/NiceHashMiner#1552]
After install into normal location (bypassed from security) had numerous reports of 'Application was blocked from accessing graphics device' - after quick research this was resolved by running System File Checker and DISM Tools via cmd prompt and a reboot.

After that everything seems to work - have been mining for 36+ hrs only stopping twice by my own request for short periods.

I have noticed Load %, Temp and RPM all show, however Global rate, amt/Day, Balance and Speed do not show, although appear to be doing similar to v1.9.0.22 which I was using up until switching to this one.

Running Win10 64bit developers w/ AMD Rx580 8gb and all latest drivers

Thanks for the continued work! Hope this helps a little

**Comment by vishal12212001** [comment]
I have same problem now in @ v1.9.0.23 its crashed my win 10 with code watchdog Error 
now its Stop working

**Comment by Snarf2948** [comment]
I am having the same issue.

 

HP z800

96GB Ram,

10TB Drive

 

Nvidia 1070

RX580

 

 

When I am mining although I have all CPUs enabled and both video cards it only opens two command windows.  The RX580 appears to never be mining.  I have tried to filter the alogrythems it mins and crashes with but now it just doesn’t mine at all.  When it does I get a BSOD with the Watchdog error and a Wattman.

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.
