### ISSUE TITLE
benchmarking terminated

### ISSUE THREAD

**Issue by pgoblin** [nicehash/NiceHashMiner#1553]
when I am trying to benchmark, everything but Zhash(Gminer) is terminated. I have run it precise, ive checked for missing dll files, and ive updated my drivers. 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3264513/log.txt)

**Comment by Rakly3** [comment]
There's no reason to mine it with GPU anyway, don't worry about it.
You need ASIC machines worth $30k to be competitive there.
