### ISSUE TITLE
i have two problem about nicehashminer

### ISSUE THREAD

**Issue by liranscu** [nicehash/NiceHashMiner#156]
1.  i have 1080ti card,why the nicehashminerlegacy cant work at the Keccak , my card just work at Lbry ,Lyra2REv2 and Equihash. It never work at Keccak.
2. why i use softwear to overlock my GPU, the speed is still so slow. At the same clock ,i use other softwear to mine,like ZEC,my speed can get 760sol/s, but the nicehashminer just have 620 why ?
thank u

**Comment by liranscu** [comment]
i use the Profitability calculator on the website, it told me the most Profitable algorithm is Keccak , but my card never work on it

**Comment by DillonN** [comment]
The profitability calculator can show what's most profitable over a certain period of time, which may be what you're looking at. NHML mines whatever is most profitable at that instant and Keccak may not be as high as it has been over the last couple days

If you still think Keccak isn't activating you need to post your `\logs\log.txt` file so I can see what's going on

As to overclocking many miner programs respond to overclocking in different ways and may get unstable quicker, resulting in lower profits

**Comment by navjack** [comment]
i've had issues where sometimes the benchmark never runs... so just do a manual run and enter in the correct number

**Comment by liranscu** [comment]
thank u very much ,guys, i sove these two problems now ,thank u

**Comment by drkskwlkr** [comment]
> i sove these two problems now 

Good, then be kind and close your issue ;)
