### ISSUE TITLE
1.9.0.23 not connecting after some time running. Restarting computer solves the problem for about an hour. Windows 10.

### ISSUE THREAD

**Issue by AmnesiaBR** [nicehash/NiceHashMiner#1562]
NiceHash Miner Legacy 1.9.0.23 doesn't start mining and miners windows keep showing 'connection timed out' or 'couldn't establish socket connection' depending on which miner is trying to connect.

After a fresh restart, NiceHash works correctly for a few hours and then stops being able to connect. Updated GPU drivers to latest Game Ready driver and it didn't help. Logs attached.

**Comment by AmnesiaBR** [comment]
Log: https://www.dropbox.com/s/nvm9sdytuu20kdp/log.1%20-%20Copy.txt?dl=0

**Comment by S74nk0** [comment]
Please use [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) this issue should be fixed in that version. If the issue still exists please open a new issue.

Closing
