### ISSUE TITLE
Crashes on window 10 64 - nhm_windows_1.9.0.23.zip

### ISSUE THREAD

**Issue by keturakis69** [nicehash/NiceHashMiner#1564]
after picking address on opening nicehash, and ok first box, nicehach window opens for about 3 sec, like its starting then the window just closes..
older version run fine. cant get nhm_windows_1.9.0.23 to run

**Comment by luc1an24** [comment]
hi @keturakis69 please use [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4). It is being actively developed and should have less issues and it will replace the old 1.9.0.xx versions completely.

**Comment by S74nk0** [comment]
@keturakis69 use [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5). All versions below 1.9.1.x are using the old nhm code/core and this is obsolete.

Open a new issue if this is still present with version 1.9.1.5.

Closing
