### ISSUE TITLE
in 1.9.0.21 to 1.9.0.23 versions wrong detecting drivers version and not detecting graphic card GT 520 1.9.0.4 version is ok no issue

### ISSUE THREAD

**Issue by galibusagar** [nicehash/NiceHashMiner#1568]
**NOTE:- in 1.9.0.21 to 1.9.0.23 versions wrong detecting drivers version and not detecting graphic card GT 520 1.9.0.4 version is ok no issue
my drivers of nvidia graphic card GT 520 is also up to date i also tried uninstalled using revo uninstaller all drivers and re installed cleanly but no use.
and also re downloaded nicehash freshly but problem not solved.
finally i checked old version 1.9.0.4 is working fine with graphic card.
all details attached please find the attaches.
thanks for advance.
![1 9 0 23 gt520 detection issue](https://user-images.githubusercontent.com/42814419/59960523-0f815080-94e7-11e9-9870-6ef9dd4082d1.jpg)

![1 9 0 4 detection ok](https://user-images.githubusercontent.com/42814419/59960527-1f009980-94e7-11e9-9838-e24d861b1cc5.jpg)

![nvidia 391 35 latest drivers](https://user-images.githubusercontent.com/42814419/59960533-3475c380-94e7-11e9-96de-85eaa544291f.jpg)

**Comment by galibusagar** [comment]
recently i also checked 1.9.1.4 same issues coming.

**Comment by S74nk0** [comment]
@galibusagar **GeForce GT 520** is not supported. 3.0+ are supported, we will probably set the minimum to 5.0+. For reference check https://en.wikipedia.org/wiki/CUDA.
Closing
