### ISSUE TITLE
TeamRedMiner is not passed Extra Launch Parameters

### ISSUE THREAD

**Issue by TheGoddessInari** [nicehash/NiceHashMiner#1569]
Windows 10.0.18362.175, NHML v1.9.0.23.

NHML doesn't pass along the extra launch parameters to the TeamRedMiner in the code.

**Comment by vasyapupkin1** [comment]
Also on DaggerHashimoto(Claymore): -tstop -tstart -tt -ttli

**Comment by luc1an24** [comment]
hi @TheGoddessInari and @vasyapupkin1  please use [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4). It is being actively developed and should have less issues and it will replace the old 1.9.0.xx versions completely. The external launch parameters are also updated and reimplemented there, so if you will still problems with them, please re-open this issue.

**Comment by vasyapupkin1** [comment]
Also on DaggerHashimoto(Claymore) in  1.9.1.4.

**Comment by luc1an24** [comment]
@vasyapupkin1 the parameters you stated (-tstop -tstart -tt -ttli) are implemented in 1.9.1.4.
Are you setting them for each card-algorithm pair inside Settings?

**Comment by S74nk0** [comment]
Original issue related to 1.9.0.23. Please use [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5).

If this isn't fixed in [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) open a new issue.

Closing
