### ISSUE TITLE
NBminer doesn't start minimized when "Minimize Mining Windows" is checked

### ISSUE THREAD

**Issue by qwertydog** [nicehash/NiceHashMiner#1570]
Nicehash miner legacy v1.9.0.23

Windows 10.0.18362 Build 18362 x64

**Comment by S74nk0** [comment]
Please use [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5). This setting depends on miner binary implementation and might not work for every miner.

Closing
