### ISSUE TITLE
crashes on any newer than Legacy 1.9.0.13

### ISSUE THREAD

**Issue by macangel** [nicehash/NiceHashMiner#1572]
I haven't tried ALL versions of NiceHash Legacy since 1.9.0.13, I've taken a couple of months off of mining for some personal problems. I went to get back into it today and tried 1.9.1.4 and 1.9.0.23 and both crashed my system during benchmarking. One froze, the other I came back to find my computer restarted and going through the event viewer, I found the nvlddmkm error. I remember I had this problem before. Switching from the new version to Legacy, I made it to 1.9.0.13 (I'm pretty sure, almost positive. I'm installing it now). And any release after that I'd get crashes. I've tried reformatting, changing drivers using DDU, etc.

Core i7 6850k @ 4.4GHz (only GPU mining though)
MSI X99S MPower
32GB RAM 3400
two Asus Strix-OC 1080ti in SLI
Corsair HXi 1200Watt power supply

I put on a custom fan curve in MSI Afterburner to increase the fan speed. I have tried it on default settings as well as lowering the power limit to 80%, which is where I had it running before with x.x.x.13.
I mine part time, game the rest of the time. No other issues with any of the settings, including OC settings that I turn on for gaming profiles.

**Comment by seso1129** [comment]
hey
I have 7 Zotac 1080 on PCI, and for recent 2 days I have the same problem, and many of algorithm dosnt work on my cards. Even on 1.9.0.13!
what do you think? which algorithm do you have a problem with and now you are using which one?
best

**Comment by macangel** [comment]
> 
> 
> hey
> I have 7 Zotac 1080 on PCI, and for recent 2 days I have the same problem, and many of algorithm dosnt work on my cards. Even on 1.9.0.13!
> what do you think? which algorithm do you have a problem with and now you are using which one?
> best

I'm not sure which algorithm, I don't sit around and just watch it. I thought I had it running okay last night. It was for a few hours, but I noticed this morning that my computer had restarted. And looking at the Event Viewer, I got several NVLDDMKM errors. I'm still trying to go through the errors. When the computer restarted it gave me a 0x00000133 error, which Google says is different than NVLDDMKM.

**Comment by S74nk0** [comment]
These issues seem to be related to particular miner binaries and not to NiceHashMiner Legacy code. We cannot fix closed source miners and troubleshooting these kind of problems is left to the user.

I would suggest to test each miner and algorithm one by one and disable all algorithms/miners that crash on your system.

Closing issue not related to NiceHashMiner Legacy code

**Comment by seso1129** [comment]
You say don't know which algorithm!!? Means you run nicehash miner on any possible algorithms? Means you tick all benchmarked algorithms and start ? Is it possible? I run only one algorithm, such as "beam(gminer)" , and start nicehash mining!
