### ISSUE TITLE
Improper reporting of RX570 in 1.9.1.4

### ISSUE THREAD

**Issue by wolfecs** [nicehash/NiceHashMiner#1576]
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by wolfecs** [comment]
Though it is successfully mining, the GUI for NHML is reporting 0 for my RX 570 card.
see attached screen clipping
<img width="1434" alt="nhml1914error" src="https://user-images.githubusercontent.com/52292686/60296627-c153bf00-98e3-11e9-969f-16689600c194.PNG">

Win 10 Pro 64 bit
NHML 1.9.1.4 (do not have problem in 1.9.0.23)
Using Lyrav3RE
Reports fine with Phoenix miner (DaggerHashimoto)

**Comment by wolfecs** [comment]
Further testing, it appears to be a teamredminer issue

**Comment by luc1an24** [comment]
Hi @wolfecs 
Thank you for reporting this issue. In the upcoming Alpha release the miner will be updated to 0.5.2 along with updated API retrieving code, which brings many fixes.
If you will still experience similar issues in the new version please reopen this issue.
Closing issue, fixed in the new release.
