### ISSUE TITLE
nicehash 1.9.1.5 [ERROR] [ApplicationStateManager.Init] Exception: An item with the same key has already been added.

### ISSUE THREAD

**Issue by benhard123** [nicehash/NiceHashMiner#1577]
i have problem with nicehash v1.9.1.5 so i cannot start mining and cannot do benchmarking
here is the log file
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3339669/log.txt)

**Comment by benhard123** [comment]
ok i already solve the problem, i only need copy OpenCL.dll from OpenCL folder to root folder now everything is working

**Comment by Giff15** [comment]
não quero mais receber e-mail
obrigado

**Comment by Giff15** [comment]
não quero mais recebe e-mail

**Comment by S74nk0** [comment]
@benhard123 I have re-open this issue. Can you please send the logs when everything works

**Comment by ringosss** [comment]
I'm also have a problem with initial start HWM 1.9.1.5.  I just downloaded the new 19.1.5 version and when I start it, there are no algos in the miner, not in the benchmark, not in the mining sections. 
Then i copy OpenCL.dll from OpenCL folder to root folder and now everything is working as benhard123 wrote.

**Comment by benhard123** [comment]
here's the log file when everyhing is working
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3342894/log.txt)

**Comment by S74nk0** [comment]
Zip package updated [nhm_windows_1.9.1.5.zip](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.1.5/nhm_windows_1.9.1.5.zip) with fixed multiple AMD platforms detection. This fixes:
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1603
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1579
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1577

Plese download new package.

Closing
