### ISSUE TITLE
Version 19.1.5 all algos missing

### ISSUE THREAD

**Issue by GrannyCryptomaster** [nicehash/NiceHashMiner#1579]
I just downloaded the new 19.1.5 version, I copied the configs dir from the old version that I was runnig, and when I start it, there are no algos in the miner, not in the benchmark, not in the mining sections. I have 4x GTX 1060 3GB, 1 Radeon RX570 4GB and 1 Radeon RX580 4GB. I deleted the configs and restarted. Again, no algos in the miner. What the heck is happening?

**Comment by nickt3** [comment]
I had the same thing... No Algos are showing in 1.9.1.5.

**Comment by nickt3** [comment]
Should have said in 19.1.5

**Comment by YoandyRey** [comment]
Algos are on holidays 🤣, sorry i have to lmao otherwise im gonna cry 😢, also having same issue.

**Comment by GrannyCryptomaster** [comment]
19.1.4 works... I recommend using that version.

**Comment by nickt3** [comment]
It does but I get better returns on previous versions.
I have 2 ribs that are 6x 580s, one 6x 1080ti.

**Comment by wolfecs** [comment]
Having same issue, never downloads miners

**Comment by djpags** [comment]
no algos here too and error message

**Comment by S74nk0** [comment]
It would be helpful to give us more information regarding this issue. It would be best if you could please close NiceHashMiner Legacy and run the `CreateLogReport.exe` this will create  `_archive_logs.zip`. Post this here or send it to stanko@nicehash.com

**Comment by S74nk0** [comment]
<img width="942" alt="CreateLogReport" src="https://user-images.githubusercontent.com/1517233/60394694-db321380-9b28-11e9-820b-b2b3ec56ca07.PNG">

**Comment by ringosss** [comment]
> I just downloaded the new 19.1.5 version, I copied the configs dir from the old version that I was runnig, and when I start it, there are no algos in the miner, not in the benchmark, not in the mining sections. I have 4x GTX 1060 3GB, 1 Radeon RX570 4GB and 1 Radeon RX580 4GB. I deleted the configs and restarted. Again, no algos in the miner. What the heck is happening?

You can try to copy OpenCL.dll from OpenCL folder to root folder and start it again. Its work for me.  [https://github.com/nicehash/NiceHashMinerLegacy/issues/1577]

**Comment by S74nk0** [comment]
Zip package updated [nhm_windows_1.9.1.5.zip](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.1.5/nhm_windows_1.9.1.5.zip) with fixed multiple AMD platforms detection. This fixes:
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1603
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1579
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1577

Plese download new package.

Closing
