### ISSUE TITLE
nicehash wallet or external wallet

### ISSUE THREAD

**Issue by navjack** [nicehash/NiceHashMiner#158]
i know this really isn't the place to ask this but early tomorrow morning is when i get paid to my external wallet and that means i COULD change my wallet. i'd like to hear from you guys what you think is the best method in terms of minimizing loss to fees.
my thinking is that nicehash dosen't want to penalize anyone using either method so in the end they break even, so i use the external wallet since its smarter to have control over your earnings that way in a controlled fashion.
i'm curious, what does @DillonN use?

**Comment by ChriscomIT** [comment]
I am going to change to NH wallet today. Overall it seems like slightly higher fees but much more freedom for me. Well, I really don't think the fee will be higher at all when I determine all cost like Nicehash fee and transaction fees and so on for external wallet.

At all long story short. I am theoretically only seeing improvements switching to NH wallet. But I can report back my experience after some days of real usage.

**Comment by p1r473** [comment]
https://new.nicehash.com/images/uploads/Sellers_Fees_001.xls

**Comment by DillonN** [comment]
@navjack I use the NiceHash wallet since I find it has lower fees when you include the transaction fees from sending from a personal wallet

However this is more a NiceHash topic and not a NHML issue so I am closing this
