### ISSUE TITLE
v1.9.1.5, Some miner don´t work on mixed system ...

### ISSUE THREAD

**Issue by electricdelicate** [nicehash/NiceHashMiner#1581]
Unfortunately another failure again ...
Some miner do not work respective cannot work correctly. In my case, Claymore and XMR-Stak do not find hardware, the other miner work properly.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/3341466/log.txt)

**Comment by S74nk0** [comment]
@electricdelicate plese follow these links instructions
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1579#issuecomment-507021196
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1579#issuecomment-507021225

It will be easier pinpoint the problem.

**Comment by electricdelicate** [comment]
Done!
[_archive_logs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/3342736/_archive_logs.zip)
