### ISSUE TITLE
Removal of miners in 1.9.1.5 has rendered some of my boxes unable to mine.

### ISSUE THREAD

**Issue by grichter** [nicehash/NiceHashMiner#1584]
Over the course of the 1.9.1.x development more and more of my older/lower powered machines have been forced to stop mining because there are no miner plugins available that don't crash. Avermore was the last stable core for one of the machines, for another I have it held at like 6 versions back because all the miners in all the newer versions crash and get terminated during benchmark.

Can we have a way to manually pull and activate disabled/removed plugins?

**Comment by S74nk0** [comment]
@grichter please state what miners and algorithms are profitable for these rigs you mentioned. We or anybody can create an external plugin that knows some C#. If you state what GPUs, miners and algorithms you require we will provide an external plugin for it.

**Comment by grichter** [comment]
They are stable and profitable running avermore doing x16r on older amd r7 and r9 series GPUs. At the moment I have them held at the last release of nhm to include avermore.

**Comment by GFreedomX** [comment]
Could we add X16R for those old HD and R9 GPUs?

**Comment by S74nk0** [comment]
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)
