### ISSUE TITLE
With 1.9.0.23 i have this problem with grincuckaroo29 Bminer for 7 cards of Zotac 1080, and grincuckaroo29 gminer even dont run at all!!

### ISSUE THREAD

**Issue by seso1129** [nicehash/NiceHashMiner#1586]
[INFO] [2019-06-30T08:55:28+04:30] Bminer: When Crypto-mining Made Fast (v15.5.3-747d98e)
[INFO] [2019-06-30T08:55:28+04:30] Detecting platform
[INFO] [2019-06-30T08:55:42+04:30] Watchdog has started.
[INFO] [2019-06-30T08:55:42+04:30] Starting miner on 7 devices
[INFO] [2019-06-30T08:55:42+04:30] Free memory 6671.65 MB available on device (#0). Selecting normal solver.
[INFO] [2019-06-30T08:55:42+04:30] Starting the management API at 127.0.0.1:4002
[INFO] [2019-06-30T08:55:42+04:30] Operating in the thread safe mode for GPU 0
[INFO] [2019-06-30T08:55:42+04:30] Starting miner on device 0...
[INFO] [2019-06-30T08:55:42+04:30] Connected to grincuckaroo29.usa.nicehash.com:3371
[INFO] [2019-06-30T08:55:42+04:30] Started miner on device 0
[INFO] [2019-06-30T08:55:42+04:30] Free memory 6769.4 MB available on device (#1). Selecting normal solver.
[INFO] [2019-06-30T08:55:42+04:30] Operating in the thread safe mode for GPU 1
[INFO] [2019-06-30T08:55:42+04:30] Starting miner on device 1...
[INFO] [2019-06-30T08:55:43+04:30] Started miner on device 1
[INFO] [2019-06-30T08:55:43+04:30] Free memory 6769.4 MB available on device (#2). Selecting normal solver.
[INFO] [2019-06-30T08:55:43+04:30] Operating in the thread safe mode for GPU 2
[INFO] [2019-06-30T08:55:43+04:30] Starting miner on device 2...
[WARN] [2019-06-30T08:55:43+04:30] Get error: End of file, resetting in 5 seconds
[INFO] [2019-06-30T08:55:43+04:30] Started miner on device 2
[INFO] [2019-06-30T08:55:43+04:30] Free memory 6769.4 MB available on device (#3). Selecting normal solver.
[INFO] [2019-06-30T08:55:43+04:30] Operating in the thread safe mode for GPU 3
[INFO] [2019-06-30T08:55:43+04:30] Starting miner on device 3...
[INFO] [2019-06-30T08:55:43+04:30] Started miner on device 3
[INFO] [2019-06-30T08:55:43+04:30] Free memory 6769.4 MB available on device (#4). Selecting normal solver.
[INFO] [2019-06-30T08:55:43+04:30] Operating in the thread safe mode for GPU 4
[INFO] [2019-06-30T08:55:43+04:30] Starting miner on device 4...
[INFO] [2019-06-30T08:55:44+04:30] Started miner on device 4
[INFO] [2019-06-30T08:55:44+04:30] Free memory 6769.4 MB available on device (#5). Selecting normal solver.
[INFO] [2019-06-30T08:55:44+04:30] Operating in the thread safe mode for GPU 5
[INFO] [2019-06-30T08:55:44+04:30] Starting miner on device 5...
[INFO] [2019-06-30T08:55:44+04:30] Started miner on device 5
[INFO] [2019-06-30T08:55:44+04:30] Free memory 6769.4 MB available on device (#6). Selecting normal solver.
[INFO] [2019-06-30T08:55:44+04:30] Operating in the thread safe mode for GPU 6
[INFO] [2019-06-30T08:55:44+04:30] Starting miner on device 6...
[INFO] [2019-06-30T08:55:44+04:30] Started miner on device 6
[INFO] [2019-06-30T08:55:48+04:30] Connected to grincuckaroo29.usa.nicehash.com:3371
[WARN] [2019-06-30T08:55:48+04:30] Get error: End of file, resetting in 5 seconds
[INFO] [2019-06-30T08:55:53+04:30] Connected to grincuckaroo29.usa.nicehash.com:3371
[WARN] [2019-06-30T08:55:54+04:30] Get error: End of file, resetting in 5 seconds
[INFO] [2019-06-30T08:56:12+04:30] [GPU 0] Speed: 5.40 G/s Fidelity 2.554 Temp: 34C Fan: 74% Power: 58W 0.09 G/J
[INFO] [2019-06-30T08:56:13+04:30] [GPU 1] Speed: 5.40 G/s Fidelity 0.556 Temp: 21C Fan: 75% Power: 52W 0.10 G/J
[INFO] [2019-06-30T08:56:13+04:30] [GPU 2] Speed: 5.20 G/s Fidelity 0.818 Temp: 20C Fan: 0% Power: 52W 0.10 G/J
[INFO] [2019-06-30T08:56:13+04:30] [GPU 3] Speed: 5.40 G/s Fidelity 0.808 Temp: 24C Fan: 75% Power: 49W 0.11 G/J
[INFO] [2019-06-30T08:56:14+04:30] [GPU 4] Speed: 5.40 G/s Fidelity 1.070 Temp: 24C Fan: 75% Power: 51W 0.11 G/J
[INFO] [2019-06-30T08:56:14+04:30] [GPU 5] Speed: 5.40 G/s Fidelity 0.787 Temp: 27C Fan: 74% Power: 51W 0.11 G/J
[INFO] [2019-06-30T08:56:14+04:30] [GPU 6] Speed: 5.20 G/s Fidelity 0.000 Temp: 22C Fan: 74% Power: 53W 0.10 G/J
[INFO] [2019-06-30T08:56:15+04:30] Total 37.40 G/s Accepted shares 0 Rejected shares 0
[INFO] [2019-06-30T08:56:24+04:30] Connected to grincuckaroo29.usa.nicehash.com:3371
[WARN] [2019-06-30T08:56:25+04:30] Get error: End of file, resetting in 5 seconds

**Comment by luc1an24** [comment]
Hi @seso1129 
I would suggest trying the new [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) version. The 1.9.1.x versions are being actively developed and a lot of issues is already fixed there.
If you will experience same issue in the new version, please create a new issue.
