### ISSUE TITLE
1.9.1.5 - add removed option "hide mining window"

### ISSUE THREAD

**Issue by allstarfxmaster** [nicehash/NiceHashMiner#1587]
on previous versions it was very useful, please add removed option "hide mining window"

**Comment by S74nk0** [comment]
@allstarfxmaster this option is not removed. 
![hide_minimize_miner_option](https://user-images.githubusercontent.com/1517233/60394307-5c39dc80-9b22-11e9-94a7-99df1717899a.PNG)

**Comment by allstarfxmaster** [comment]
on 1.9.1.5 this option if off, but I found it on General.json 
![miner](https://user-images.githubusercontent.com/36789242/60629555-78759c00-9df6-11e9-8afa-6f8f7233e041.jpg)

![ConfigGeneral-json](https://user-images.githubusercontent.com/36789242/60629609-a9ee6780-9df6-11e9-95e9-326734def4e5.jpg)

**Comment by Pandora-Verse** [comment]
This option is still missing in the GUI, as of 1.9.2.9.

**Comment by S74nk0** [comment]
@Virosa 
![image](https://user-images.githubusercontent.com/1517233/61438652-398c2e00-a940-11e9-9523-1c1535693448.png)

**Comment by Pandora-Verse** [comment]
@S74nk0 Look at the 1.9.1.5 screenshot above yours, the Setting -> Advanced Panel has been changed.

Here is one from 1.9.2.9, the current version, it is different than yours:
https://i.imgur.com/DIDrZqR.png

**Comment by kotenok2000** [comment]
3.0.5.6
![Снимок экрана (1)](https://user-images.githubusercontent.com/8822292/104163857-1f81bd80-5408-11eb-9932-fb3caff1db23.png)
