### ISSUE TITLE
Problem with 1.9.1.5 - (missing miner bins after download)

### ISSUE THREAD

**Issue by seso1129** [nicehash/NiceHashMiner#1593]
![IMG_20190701_163359](https://user-images.githubusercontent.com/52235140/60435266-532e3580-9c1e-11e9-99ef-0bdcfcd4937f.jpg)
Here's my problem with 1.9.1.5
This will not be done, in no time!! 1_2_3 hours, at all.

**Comment by S74nk0** [comment]
Whitelist your nhm installation path. This is AV blocking the download.

**Comment by seso1129** [comment]
Means I have to delete all other versions from this installation address?

**Comment by S74nk0** [comment]
Or you can download and extract it manually. https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.1.5/miner_bins_urls.json this is the link to the miner bins. Download archive and extract it to `{nhm_path}\miner_plugins\XmrStak\bins`

**Comment by S74nk0** [comment]
@seso1129 I am not sure what do you mean by deleting all versions?

**Comment by seso1129** [comment]
I put the nhm 1.9.1.5 folder on my desktop, and install and run it, not an specific address! 
So I have 1.9.0.23 on my desktop either, you mean I have to delete the last version from my desktop?

**Comment by luc1an24** [comment]
Hi @seso1129 
You don't have to delete anything. You just whitelist your 1.9.1.5 folder on the desktop.
If you don't have external anti-virus program, this is done in Windows Defender Security Center otherwise in your external anti-virus program.

**Comment by seso1129** [comment]
Hey @luc1an24

No change! Disabling my windows defender don't change anything.

**Comment by luc1an24** [comment]
Interesting... Are you able to manually download Xmr-Stak from https://github.com/nicehash/xmr-stak/releases/download/nhm-2.10.5/xmr-stak_2.10.5_495625c.7z ?
If the file gets deleted as soon you save it or you aren't able to download it at all, this is AV issue.
But if you are able to download and save it please put the miner files from that zip to `{nhm_path}\miner_plugins\XmrStak\bins` and launch the nhml.
Please inform me about the findings!

**Comment by seso1129** [comment]
@lu1an24

I can download all miner manually, and put them in bins folders, and disabled my windows defender, but still doesn't work.
Either in 1.9.1.4.

**Comment by S74nk0** [comment]
@seso1129 please post logs regarding this issue.

**Comment by qergo** [comment]
The whole problem in the miner, he does not load it there is not already checked himself. All have one problemma.      https://tradeproject.de/download/Miner/TT-Miner-2.2.5.zip

**Comment by qergo** [comment]
Write it to another place I bless it from there.

**Comment by mhsh0001** [comment]
I also have the same problem and it occurs from 1.9.1.4 version, before that everything was alright, btw, I do not have any AV.
also, previous version does have "bin" files and "3rd-party" folder separately but this version doest not have any!

**Comment by S74nk0** [comment]
Please try replacing [NHM.MinersDownloader.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/3353589/NHM.MinersDownloader.zip)

NHM.MinersDownloader.dll
NHM.DeviceMonitoring.pdb
NHM.MinersDownloader.dll.config

And report back if this fixed the problem

**Comment by mhsh0001** [comment]
the problem still exists the same. it just got stock on unzipping XmrStak 100%...

**Comment by mhsh0001** [comment]
problem solved. internet provider blocked one of miners ip address...

**Comment by luc1an24** [comment]
@mhsh0001 could you tell me which link was blocked?

**Comment by luc1an24** [comment]
@seso1129 @qergo @mhsh0001 If you will still have problems with downloading please try to replace `miner_mins_urls.json` file with one of following: 

- https://github.com/nicehash/MinerDownloads/releases/download/v1.0/miner_bins_urls.7z
- https://github.com/nicehash/MinerDownloads/releases/download/v1.0/miner_bins_urls.zip

If downloading doesn't work with 7zip file then try with zip

**Comment by chillware** [comment]
I also have similar problem with 1.9.1.5, i get a warning that there missing files at every launch of nicehash. I click yes to download missing files, NH relaunches and starts to download, however it just comes up w/ the same warning. I have to click no to continue to mine. I upgraded from 1.9.0.23, not sure if the issue was present in 1.14. I have 4 rigs, all have the same issue. No AV, defender long been disabled.

![image](https://user-images.githubusercontent.com/17019900/60611095-52121b00-9d7a-11e9-840d-921bc1b27782.png)

**Comment by chillware** [comment]
Looks like its failing to download the ewbf zhash miner..

![image](https://user-images.githubusercontent.com/17019900/60613264-6efd1d00-9d7f-11e9-8e75-ff530cb02a45.png)

**Comment by seso1129** [comment]
thanks to all, I have changed my internet provider and the problem of downloading miners is solved now.
Nicehash downloaded all miner and I do benchmark my cards, but the new problem is the login to pools!!
in no algorithm, miner wont able  to login to the pool, I will open a new issue.

**Comment by luc1an24** [comment]
@chillware have you tried all troubleshooting tips from above?
If you did and still doesn't work please provide logs so I can troubleshoot what goes wrong here.

**Comment by S74nk0** [comment]
Issue is related to ISP geo-blocking. We will mirror all non GitHub miner links to point to GitHub instead of original links.

**Comment by S74nk0** [comment]
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)

**Comment by seso1129** [comment]
1.9.1.6 and 1.9.2.6 are totally a big masses. Downloading miner takes
toooooooooo long.

**Comment by joseortiz3** [comment]
If ISP's really are geo-blocking, do we need to use a VPN when first initializing NiceHash?

**Comment by S74nk0** [comment]
@joseortiz3 The miner downloads shouldn't be a problem with geo-blocking anymore. We mirrored/moved all the miners to GitHub instead of relying on the original sources so geo-blocking shouldn't be an issue. Mainly MEGA is blocked.

**Comment by seso1129** [comment]
In later version, this issue has been solved.
