### ISSUE TITLE
High cpu on 1.9.1.5

### ISSUE THREAD

**Issue by mato777** [nicehash/NiceHashMiner#1594]
I see that when I start the new miner I get 100% cpu.  The miner gets about 25% of the cpu and System appears with the rest 75%.  If I shutdown the app, the cpu goes to 6%.  I have a 10 gtx 1070 rig working.

**Comment by S74nk0** [comment]
@mato777 plese follow these links instructions
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1579#issuecomment-507021196
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1579#issuecomment-507021225

It will be easier pinpoint the problem.

**Comment by mato777** [comment]
![image](https://user-images.githubusercontent.com/10453322/60448466-09ccee80-9bfc-11e9-8ee6-58061ba5fcec.png)

**Comment by mato777** [comment]
[_archive_logs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/3346351/_archive_logs.zip)
