### ISSUE TITLE
Feature request: power cost field in settings

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1596]
Hello,

I'd like to be able to see my after-power profit on main screen but I don't want it taken into account for algorithm switching. Could you add a checkbox to settings to break out this function from the field where, if you enter an amount, it is used for switching?

Thanks!

**Comment by S74nk0** [comment]
@jwesolo Can you please explain why would you want this feature? Give us one or more use cases where this would be beneficial

**Comment by jwesolo** [comment]
@S74nk0 Hi, thanks for your reply.

I want to choose profitability only on the basis of how much buyers are paying for my hashing power. I do not use power cost as a factor in algorithm switching because I do not necessarily sell bitcoin at the same price as when I am mining (i.e. when prices are low ). My goal is to maximize the amount of BTC I earn.

However, it would be nice to see, at a glance, how much I am making at current price after power costs. The new miner GUI already shows power cost (with current power usage) and profit/day in fiat after power costs; I'd just like a number to be there without using it for switching. It's not an absolutely necessary piece of information to display, but neither is daily profit in USD or other fiat currency, since I hold BTC until prices are high and current daily profits are essentially meaningless. Seeing the power cost/day information would increase my awareness about how much mining costs me in power.

I hope I was able to explain my thinking clearly. Please let me know if you have any questions. Thanks again!

**Comment by S74nk0** [comment]
Ok makes sense. This was implemented today for this issue https://github.com/nicehash/NiceHashMiner/issues/1321. Now we will close this issue on the next release  and I will mark it as duplicate.

So you will be able to mine even if the current profit is negative and by default it will mine regardless of profit but you will be able to see the estimated power cost and potential negative profit.

![image](https://user-images.githubusercontent.com/1517233/60726989-22f7d700-9f3d-11e9-8fdf-93f8ae97989f.png)

![image](https://user-images.githubusercontent.com/1517233/60727057-49b60d80-9f3d-11e9-953d-ec17f4d62da8.png)

Will close issue on next release

**Comment by jwesolo** [comment]
Thanks! One question, though, since the other issue #1321 was slightly different. The new setting will still mine if not profitable, which is good. However, will it still be taking power cost into account for switching? I want to mine whatever is paying the most BTC without taking power cost into account. I just want to be able to see how much I'm spending in power when I look at the GUI instead of $0.

**Comment by S74nk0** [comment]
@jwesolo Ok I see. No it will take profit into account. We will keep your issue open and remove duplicate. Maybe we land this feature in the next release.
