### ISSUE TITLE
v1.9.1.5 unpaid balance/BTC price info not updating

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1597]
Hello,

Since upgrading to 1.9.1.5, the wallet balance and BTC price in the bottom status bar are updating only rarely. The balance showing right now, for example, has been the same for 2 days. The BTC price stays the same for many hours despite it fluctuating on the exchanges.

Thanks!

**Comment by jwesolo** [comment]
I mean unpaid balance, not wallet balance.

**Comment by ThiagoSF7** [comment]
I am also facing the same problem

**Comment by S74nk0** [comment]
I am unable to reproduce this issue with any of the miner clients. On every `[INFO] [SOCKET] Received: {"method":"balance","value":"x.yy"}` the GUI indicator updates immediately. 

Do you have rejected shares and therefore no balance updates? 
I am assuming this has something to do with the backend temporarily not sending `"method":"balance"`  messages.

I will close this issue now. If you can show that the balance indicator is frozen after receiving `{"method":"balance","value":"x.yy"}` and the balance doesn't match `x.yy` (scaled or not) re-open this issue or open a new one.

![image](https://user-images.githubusercontent.com/1517233/60566615-b24b9180-9d67-11e9-963f-e3822f7f894c.png)

**Comment by jwesolo** [comment]
The word "balance" does not appear in my log.txt or log.1.txt. The unpaid balance currently shown on the client GUI is from several days ago. The software and system have been restarted several times since that balance was accurate.

If the backend is not sending this information, who needs to be told? Could it be related to the platform change? Have you tried reproducing this using US servers?

Thanks again for your help!

**Comment by jwesolo** [comment]
I don't think I have the ability to reopen this issue...if you don't respond I'll create a new one in the morning. Thanks.

**Comment by S74nk0** [comment]
@jwesolo `The word "balance" does not appear in my log.txt or log.1.txt.` this means that you are only getting this message on login. Please write your BTC address here or email it to support@nicehash.com with the link of this github issue.

**Comment by jwesolo** [comment]
I'm going to wait until after the switch to the new platform and will send the info if the problem persists. Thanks again for your help.

**Comment by vanmald** [comment]
I am also seeing this issue.  Not too concerned about it since I monitor my mining machines remotely so having the information at the bottom of the NHML isn't important to me.  But... if you need someone else to verify the fix, I would be happy to help.  Both of my mining machines exhibit this issue.

**Comment by dark8899** [comment]
This problem is it's related? v1.9.2.6 ![nowk2](https://user-images.githubusercontent.com/27753859/60749255-39b22400-9f65-11e9-9555-60b76bcf2681.png)

**Comment by jwesolo** [comment]
For the first red underline, I believe that was because on the new platform they had 1 BTC = 1 USD for the time being (just as a placeholder). You want to look a few lines higher (the line ending in 176.140381). That's the line that gives the exchange rates (USD would be set to 1).

I'm not sure what the "operation not supported" error is that you're getting in the log. Might be one of the new platform features not fully implemented yet?

Also, the new platform is now disabled due to problems...go back to old platform (1.9.1.6) and old mining wallet until they tell us to switch back to new.

**Comment by justyouraveragejoe1** [comment]
I'll test the new version, but on 1.9.15 I also had this issue when I restart the program the price and btc amount update properly though.

**Comment by mchybowski-rtbh** [comment]
@jwesolo - same issue on 1.9.27 (exactly the same output in debug console/log)

**Comment by S74nk0** [comment]
Issue related to back-end. Back-end issues are resolved now.
Closing
