### ISSUE TITLE
Can new algos be added on existing miners using only config files?

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1598]
Hello,

There are a number of miners with existing plugins which use Nicehash-supported algorithms but are not set up to do so. For example, T-Rex supports MTP. Can support for this be added by modifying the config files only? I've tried doing this in past and it did not work but perhaps with the new plugin system it is more modular.

Thanks!

**Comment by luc1an24** [comment]
This can be done by changing plugin code and building new plugin (dll).
This can be done by everyone with some knowledge of C#.
If you would like to see some specific algorithms added please tell me and I will try to add them in one of the upcoming releases.

**Comment by S74nk0** [comment]
@jwesolo This depends on the miner plugin implementation. With the current API version this was not done but when we tackle urgent tasks we will consider adding this feature so users can enable/disable algorithms on specific miners. 
As for now what @luc1an24 wrote and he might help you with this.

**Comment by jwesolo** [comment]
I do know C#, I just don't really have the time to review the code and figure out how to do this. I don't have any specific algos/miners in mind, I'd just like to have the full capability of the miners available to me. Was hoping for a quick solution since most of the info on miners, their supported algos, and command line arguments seem to all be defined in the various JSON files. Thanks for the response! :)

**Comment by S74nk0** [comment]
It is not that difficult. Here are already implemented [miner plugins](https://github.com/nicehash/NiceHashMinerLegacy/tree/master/src/Miners). If you would like to add an algorithm check out `public Dictionary<BaseDevice, IReadOnlyList<Algorithm>> GetSupportedAlgorithms(IEnumerable<BaseDevice> devices)` method and inside you return what algorithms are supported for what device (based on devices parameters).  BMiner example https://github.com/nicehash/NiceHashMinerLegacy/blob/master/src/Miners/BMiner/BMinerPlugin.cs#L37-L84. 
Here is the place algorithms are **added** after that you need to handle that `AlgorithmType` inside the `IMiner` implementation of the class. For BMiner it is here https://github.com/nicehash/NiceHashMinerLegacy/blob/master/src/Miners/BMiner/BMiner.cs#L31-L42. 
**As you see adding algorithms to existing miner plugins code is 2 lines of code per Algorithm** (unless new algo requires special run command line)

**Comment by jwesolo** [comment]
I'll take a look at it when I get a chance. Thanks for the info!

**Comment by grichter** [comment]
I know zero C#, but I'm not afraid to stab with a copy of visual studio.

If there was a quick and dirty write up on how to copy the example template over and modify it to enable additional miners, algos and hardware I would happily stab in my little fork to see what I can make.
