### ISSUE TITLE
devfee and best profit calculation ?

### ISSUE THREAD

**Issue by toonsmil** [nicehash/NiceHashMiner#16]
Can you subtract the "devfee" during the benchmarks (or during best profit calculation) , for example for "claymore dual", subtract 2% on the eth speed (or on BTC / DAY ?) for the calculation of the best profit ?

In some cases :
"3rdparty" > "all"
but
"3rdparty - devfee" < "something else"

it has to be more profitable to use another miner

**Comment by billmcilhargey** [comment]
heres a list of fees to keep track (also feel free to correct any that are wrong)

Claymore CryptoNote - 2% (https://bitcointalk.org/index.php?topic=638915.0)
Claymore Dual - 1% for Etherum only & 2% for Dual mode (https://bitcointalk.org/index.php?topic=1433925.0)
Claymore ZCash - 2% for SSL and 2.5% for non-SSL  (https://bitcointalk.org/index.php?topic=1670733.0)

EWBF CUDA Zcash - 2% (https://bitcointalk.org/index.php?topic=1707546.0)

OptiminerZcash - 2.5% (https://github.com/Optiminer/OptiminerZcash) ** Note From Developer: "All shown hash rates are net rate, i.e., with fee deducted. What you see is what YOU get!"

**Comment by DillonN** [comment]
DevFees are already subtracted during benchmarking (except for Optiminer, which I believe is already subtracted)
