### ISSUE TITLE
Multiple error logs when enabling idle mining with unbenchmarked algos

### ISSUE THREAD

**Issue by lmuhl** [nicehash/NiceHashMiner#160]
Enabling "Start Mining when Idle" while there are still unbenchmarked algorithms causes the error dialog to show up multiple times:

![image](https://user-images.githubusercontent.com/7623511/29318671-68c17f7e-81d1-11e7-8d96-0ab5e3b79deb.png)

**Comment by DillonN** [comment]
Thanks for reporting, I will look into this

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
