### ISSUE TITLE
The "Check my stats online!" label is no more a clickable URL like in NHML 1.9.0.x

### ISSUE THREAD

**Issue by gitusr-gcar** [nicehash/NiceHashMiner#1600]
The "Check my stats online!" label is no more a clickable URL in 1.9.1.5 like it was in NHML 1.9.0.x.
This should open a browser window pointing to the URL: https://www.nicehash.com/miner/<Bitcoin_Address>

**Comment by jwesolo** [comment]
Works for me.

**Comment by S74nk0** [comment]
@gitusr-gcar please write to support@nicehash.com.
