### ISSUE TITLE
Feature Request:  Turn off Nicehash Power and other GPU settings

### ISSUE THREAD

**Issue by frazier345** [nicehash/NiceHashMiner#1602]
Please make a version that we can turn off your power and any other settings for our GPUs.  PrecisionX fights with NiceHash 1.9.1.5 for control of my cards, both programs go into "not responding" in Windows 8.1 Pro and freeze the system which then doesn't mine and I have to do a hard reset.  Have to go back to 1.9.0.23  I don't need NiceHash to run my settings on my cards.  I know what my cards can do and want them to do.

**Comment by prettycode** [comment]
Yeah, can we get that `PowerLimitsEnabled` property in `DeviceMonitorNVIDIA.cs` to be set via config, pretty please? Default it to `true` if you want, but let me override it with a `false` from a .json file. 👍

**Comment by S74nk0** [comment]
We will implement this feature.

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMinerLegacy/commit/6d435d028f51af677c48a4dbc057cf02f24329d7) adds this feature we will close this issue on next release.
![image](https://user-images.githubusercontent.com/1517233/60654870-14ca8d80-9e4d-11e9-934a-3e63ea0cdeb7.png)

**Comment by S74nk0** [comment]
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)

**Comment by BigShadex** [comment]
@S74nk0  Ill give this a go
