### ISSUE TITLE
No algorithm found in Benchmark

### ISSUE THREAD

**Issue by XerxesNagato** [nicehash/NiceHashMiner#1603]
Hi there, i have a problem when there is no algorithm in the software (1.9.1.5), and when i click on start, it says: Unable to get profitability data. If you are connected to internet, ty again later.
and it shows that i have two graphiques, while i have only one
help please
![Untitled2](https://user-images.githubusercontent.com/12681937/60500078-9be2fe80-9cb1-11e9-81ee-d77ff87e952b.png)
![Untitled1](https://user-images.githubusercontent.com/12681937/60500080-9be2fe80-9cb1-11e9-8821-00670919c813.png)

**Comment by S74nk0** [comment]
@XerxesNagato Do you have 2 or 1 RX570 on your system?

**Comment by XerxesNagato** [comment]
@S74nk0 I have only one, idk why it shows 2

**Comment by S74nk0** [comment]
@XerxesNagato can you please replace these 2 files int the root path of the program. 
[NHM.DeviceDetection.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/3349351/NHM.DeviceDetection.zip)

Replace NHM.DeviceMonitoring.dll and NHM.DeviceMonitoring.pdb. Please report back if this fixed the problem.

**Comment by XerxesNagato** [comment]
Bro you saved my day, this worked, it shows one rx and i got algorithms, Thank you so much @S74nk0

**Comment by S74nk0** [comment]
Zip package updated [nhm_windows_1.9.1.5.zip](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.1.5/nhm_windows_1.9.1.5.zip) with fixed multiple AMD platforms detection. This fixes:
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1603
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1579
  - https://github.com/nicehash/NiceHashMinerLegacy/issues/1577

Plese download new package.

Closing
