### ISSUE TITLE
Feature Request: add MTP for T-Rex miner and update ccminerMTP

### ISSUE THREAD

**Issue by dhonasan** [nicehash/NiceHashMiner#1606]
Please add MTP for T-Rex Miner specifically for RTX 2060 and GTX 1070 since it has higher hashrate than TT-Miner.

also update ccminerMTP please since it has highest hashrate

**Comment by S74nk0** [comment]
We will add MTP for T-Rex Miner, ccminerMTP is not compatible with NiceHash protocol. We will close this issue on next release.

**Comment by S74nk0** [comment]
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)
