### ISSUE TITLE
v1.9.1.5 GMiner don´t work on AMD

### ISSUE THREAD

**Issue by electricdelicate** [nicehash/NiceHashMiner#1607]
And the next issue, on my regular PC with AMD RX590 the GMiner wont´t start at all.
Not the benchmark run and not the mining. No failure message, just no start.
[_archive_logs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/3353267/_archive_logs.zip)
![1](https://user-images.githubusercontent.com/40469299/60563036-57f80400-9d5a-11e9-8aca-62d69ec8fc45.JPG)
![2](https://user-images.githubusercontent.com/40469299/60563041-5b8b8b00-9d5a-11e9-86e4-51a2a5e66c80.JPG)

**Comment by ThiagoSF7** [comment]
A similar issue is happening with me with my amd vega 64, what i did was down grade to and older and better version and now is running very good and im doing 30% more profits

**Comment by electricdelicate** [comment]
Downgrade to an older Nicehash version?

**Comment by ThiagoSF7** [comment]
Yes use an older version the last good version is the v1.9.0.23

**Comment by S74nk0** [comment]
@electricdelicate GMiner plugin is missing the naive pcie bus id mappings for AMD. That is why this doesn't work on a AMD only system as it doesn't cross reference it with the miner and this is the **bug**.

If you replace the plugin this should fix the problem. 
[GMiner.zip](https://github.com/nicehash/NiceHashMiner/files/3359644/GMiner.zip)

Builds for releases [1.9.1.6](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.6) and [1.9.2.6](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.6) were re-uploaded with this fix (`GMiner.dll` is updated) (new users will not experience this issue).

We will close this issue with the next release.
