### ISSUE TITLE
Setting the electricity cost in the settings disables my Nvidia GTX 1070 from running.

### ISSUE THREAD

**Issue by ugjackal** [nicehash/NiceHashMiner#1609]
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

Bug:

If you set the "Electricity Cost" setting on version 1.9.1.5 the GPU fails to main and goes to a disabled state.

**Comment by luc1an24** [comment]
Hi @ugjackal 
Did you also set Minimum Profit? This could cause graphic card not being profitable enough and would keep it disabled.
If not please provide logs so we can easier pinpoint the problem.

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMinerLegacy/commit/431483d5694d72f51a3f00a60f47e2787731fd5c) fixes this bug. The fix will be in the next up-coming release.

**Comment by S74nk0** [comment]
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)
