### ISSUE TITLE
Error on Particular Pool EQUIHASH(EWBF)

### ISSUE THREAD

**Issue by gurdeepsingh0735** [nicehash/NiceHashMiner#161]
I am not able to mine EQUIHASH(EWBF) pool. Unable to take benchmark
Currently I am using GTX 1060 & GTX 1070 but still i am not able to access this pool.

**Comment by DillonN** [comment]
If I understand you, you're trying to benchmark Equihash (EWBF) but it is failing? Could you post your `\logs\log.txt` file?

Also have you tried [manually benchmarking](https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Getting-started#manualbenchmarking)

**Comment by jimmyhackers** [comment]
after a regular benchmark.....retest any that failed etc with a precise benchmark and then a quick one. sometimes these two other benchmarking methods may return a result .

 although bear in mind, if you pc has trouble/instability running a benchmark its probably best not to set it to run that algo constantly
