### ISSUE TITLE
NHML 1.9.1.5 cant detect my GPU

### ISSUE THREAD

**Issue by GFreedomX** [nicehash/NiceHashMiner#1613]
Hi NH support,
I am having this issue at the moment
NHML1.9.1.5. was about to detect my 6 X RX470 GPU
but after I install the 7th RX470, the NHML1.9.1.5 cannot detect any of my GPU and my CPU
I check the older version NHML 1.9.0.23 it can detect all my GPU and work fine.
The GPU is an XFX RX470 4GB GPU

I have another mix rig when running an RX470 to mine using the NHML 1.9.1.5  in the command prompt it said its an R9 380 mining.  when I try it on the NHML 1.9.0.23 everything was fine.

Can anyone advise?

**Comment by GFreedomX** [comment]
> NHML1.9.1.5. was about to detect my 6 X RX470 GPU
but after I install the 7th RX470, the NHML1.9.1.5 cannot detect any of my GPU and my CPU
I check the older version NHML 1.9.0.23 it can detect all my GPU and work fine.
The GPU is an XFX RX470 4GB GPU

For this issue i managed to resolve it by remove the whole folder and extract a new one
i believe it's the config files in the config folder that was corrupted. removing the whole files will let the program detect the gpu again.
please note with this you will need to redo all the benchmark again

**Comment by S74nk0** [comment]
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)

This is probably **multiple AMD platforms detection**

**Comment by S74nk0** [comment]
@GFreedomX Please close issue if this is fixed.
