### ISSUE TITLE
Wrong GPU enumeration for PhoenixMiner AMD

### ISSUE THREAD

**Issue by dhonasan** [nicehash/NiceHashMiner#1615]
I have mixed GPU rig. When I tried to benchmark my Vega 56 seems there's wrong enumeration, i see that it uses -platform 1 to select only AMD card. But it uses -di 5 instead of -di 0. That's why, I can't benchmark since they said no GPU selected

![Screenshot_20190704-200415](https://user-images.githubusercontent.com/32080588/60668953-5aac4380-9e97-11e9-9fbb-0d97320819d1.jpg)
[log20190704_195621.txt](https://github.com/nicehash/NiceHashMiner/files/3359414/log20190704_195621.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3359420/log.txt)

**Comment by S74nk0** [comment]
@davidhonasan We will fix this asap.

**Comment by luc1an24** [comment]
@davidhonasan Could you please replace the files in nhml directory with the ones in the following zip package.
[MinerPluginToolkitV1.zip](https://github.com/nicehash/NiceHashMiner/files/3359475/MinerPluginToolkitV1.zip)
Please try it and inform us of how it goes

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMiner/commit/cc96956bc1192ec4bb77ac649e7e493c435d287f) fixes this issue. The device mappings is done with the default platform and setting the platform parameter later will choose wrong GPU on mixed systems.

@davidhonasan thanks for pointing this out. 

Builds for releases [1.9.1.6](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.6) and [1.9.2.6](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.6) were re-uploaded with this fix (`MinerPluginToolkitV1.dll` and `Phoenix.dll` were updated) (new users will not experience this issue).

We will close this issue with the next release.

**Comment by dhonasan** [comment]
i see it's been fixed with removing -platform 1, i also tried the zip from luc1an24 and it works well. now i can benchmark and mine my vega. thanks
