### ISSUE TITLE
Benchmarking/Minining GPU Spike to full power + freeze

### ISSUE THREAD

**Issue by Jfro416** [nicehash/NiceHashMiner#1616]
During benchmarking on 1.9.1.6 (.5 prior), approx. half way through benchmarking in precise mode, the GPU allocated #0 or #1 runs its fan 100% and the unit freezes. I attempt to open any of the AMD software for the units (RX570 & 580) and those are also not functioning.

The only way to stop this from happening is a hard/power switch shut down of the rig. A windows shutdown wont reset the unit or stop the GPU's from running.

Currently running 1.9.0.23 without issue. No prior versions did this as well. No logs are showing any errors.

Thanks :)

**Comment by S74nk0** [comment]
@Jfro416 we have updated the miner binaries from 1.9.0.23 on wards. 1.9.0.23 uses older miner binaries and I suppose those work well with your system. 

Issues that are related with system crashes with specific miner+algorithm and GPU is outside of our reach and you will have to figure out what combination(s) is/are causing problems for your rig and disable those.

Issue related to users rig setup
**OR**
Used miner isn't compatible with NiceHash protocol or hardware
