### ISSUE TITLE
v1.9.1.5 Power usage incorrect on GUI vs miner

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1617]
I'm not sure if this is an NHM issue or an NVML/NVIDIA issue but wanted to make you aware of it. Sometimes after running for a while, the GPU status goes away. This has been going on for a long time. Today, however, I noticed something new. I'm still on v1.9.1.5 until after the platform switch but I imagine the issue persists. The power usage shown in GUI is over 100x what the miner says it is. I don't think this is related to the power settings issue. Thanks and take care!

![nicehash power usage](https://user-images.githubusercontent.com/3432351/60696233-710fca80-9eaa-11e9-93fc-c3d0eeb84200.png)

**Comment by luc1an24** [comment]
@jwesolo thanks for reaching out. It is indeed a bug in plugin implementation and will be fixed asap.
Stay tuned for the new releases.

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMiner/commit/da7472c22feb73678a69d5049024310e722b8d4d) fixes this issue (T-Rex, NBMiner and GMiner have this issue).

Will close issue on next release or on next miner plugins update.
