### ISSUE TITLE
Version 1.9.1.5 Restoring default values on Afterburner

### ISSUE THREAD

**Issue by BigShadex** [nicehash/NiceHashMiner#1619]
Been using version 1.9.0.23 for over a month now with no issues, switched to the updated 1.9.1.5 just yesterday and have had my afterburner settings reset to default and max power 4 times in the space of 24 hours.... 

Not ideal when they are running at 80 degrees for hours on end. Wont be using this again until confirm fix.

**Comment by S74nk0** [comment]
@BigShadex [1.9.1.6](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.6) and [1.9.2.6](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.6) allow you to disable this. 

https://github.com/nicehash/NiceHashMiner/issues/1602#issuecomment-508407884
