### ISSUE TITLE
1.9.1.5 Extra Launch Parameters not passed to TeamRedMiner 

### ISSUE THREAD

**Issue by tommyprevatt** [nicehash/NiceHashMiner#1624]
NHML 1.9.1.5 (cannot test on newer versions for reasons I will submit into another issue. Based on the readmes though, this issue shouldn't be fixed in newer version).
Windows 10 v1803
GPU: MSI Vega 56

The "Extra Launch Parameter" does not work for TeamRedMiner. For example, putting "--cn_config=L14*14:CBB" in the box does nothing. I also tried other options like --debug. 

The Extra Launch Parameters works for other mining software like Phoenix, but not TeamRedMiner. 
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3362709/log.txt)

**Comment by S74nk0** [comment]
@tommyprevatt This particular option is not enabled by default.

You can still enable this yourself by editing `MinerOptionsPackage.json`. 

For example:
```
{
  "use_user_settings": true, // set to true to use your custom settings
  "general_options": [
    {
      "type": "OptionWithSingleParameter",
      "id": "teamRedMiner_initStyle",
      "short_name": "init_style=",
      "long_name": null,
      "default_value": "1",
      "delimiter": null
    },
    {
      "type": "OptionWithMultipleParameters", // I assume this is per GPU
      "id": "teamRedMiner_cn_config",
      "short_name": "--cn_config", // your new flag to support 
      "long_name": null,
      "default_value": "-1",
      "delimiter": ","  // values probably separated by comma
    }
  ],
  "temperature_options": [
    {
      "type": "OptionWithSingleParameter",
      "id": "teamRedMiner_tempLimit",
      "short_name": "temp_limit=",
      "long_name": null,
      "default_value": "85",
      "delimiter": null
    },
    {
      "type": "OptionWithSingleParameter",
      "id": "teamRedMiner_tempResume",
      "short_name": "temp_resume=",
      "long_name": null,
      "default_value": "60",
      "delimiter": null
    }
  ]
}
```

I am not familiar with TeamRedMiner myself but if you can give suggestions what flags we should add to be supported by default on the next plugin release

**Comment by S74nk0** [comment]
MinerOptionsPackage.json is located in `nhm_path\miner_plugins\TeamRedMiner\internals`

**Comment by tommyprevatt** [comment]
This works for me. Is there a document detailing this information that I missed somewhere? I would love to look into all the documentation.

**Comment by S74nk0** [comment]
@tommyprevatt docs are still work in progress

**Comment by rexsllemel** [comment]
Not working on latest nicehash (windows). I test it with simple command "--eth_epoch=374" and "--eth_4g_max_alloc=374" as well as "--restart_gpus --uac"

Also, still Nicehash ELP not passed to TeamRedMiner.

TRM Version 0.8.1
