### ISSUE TITLE
1.9.2.6 Extra Launch Parameters not working for Phoenix

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1626]
Extra Launch Parameters not working for Phoenix Miner "-clkernel 3". Always start with default value "-clkernel 1".

**Comment by S74nk0** [comment]
@cyberunknown send the logs please

**Comment by ghost** [comment]
[log20190705_193440.txt](https://github.com/nicehash/NiceHashMiner/files/3369308/log20190705_193440.txt)
![Screenshot](https://user-images.githubusercontent.com/13589802/60826053-83e61000-a1c6-11e9-81fd-fcdc93983ef8.png)

**Comment by luc1an24** [comment]
Hi @cyberunknown 
Current implementation of extra launch parameters is case sensitive.
The implemented flag is `-clKernel` (like in the documentation of Phoenix miner). 
We will consider implementing case insensitive option for extra launch parameters parser.
Not a bug, closing issue.

**Comment by ghost** [comment]
`-clKernel 3` not working too. Reopen issue please. This is a bug.

**Comment by luc1an24** [comment]
If you want to use this or any single value parameter you have to pass it to each card-algorithm through Extra Launch Parameters box.

If you put that parameters to only one field it will use it only on this card.
If I misunderstood your case please correct me.

**Comment by S74nk0** [comment]
@cyberunknown please provide nhm logs when starting Phoenix.

**Comment by ghost** [comment]
Here is the logs:
[nhm_log.txt](https://github.com/nicehash/NiceHashMiner/files/3372979/nhm_log.txt)
[phoenix_log.txt](https://github.com/nicehash/NiceHashMiner/files/3372980/phoenix_log.txt)

I'm wrote `-clKernel 3 -gt 13` in the ELP field on **each** card. Only `-gt 13` was parsed.

**Comment by S74nk0** [comment]
@cyberunknown We are unable to reproduce this. Did you change anything the `nhm\miner_plugins\Phoenix\internals\MinerOptionsPackage.json` file? Can you upload this file as well please?

**Comment by ghost** [comment]
One week ago i've changed this file when trying to find reason why not all extra parameters parsed. Only today I found out what ELPs for Phoenix is case sensitive.
So with original `nhm\miner_plugins\Phoenix\internals\MinerOptionsPackage.json` `-clKernel 3` is now parsed.

Sorry. My mistake.

**Comment by S74nk0** [comment]
@cyberunknown thanks for replying we will update the Wiki and README.md of the project as it is non existent at the moment and the old documentation is almost entirely obsolete. 

Users should be informed but we didn't manage to get around the docs. We will update all documentation until the end of this week.
