### ISSUE TITLE
1.9.2.6 No MTP algo miners

### ISSUE THREAD

**Issue by vanmald** [nicehash/NiceHashMiner#1627]
After upgrading to 1.9.2.6 from 1.9.1.5, I lost all MTP mining options.  Did anyone else experience this?  I have T-rex for Lyra2Z and X16R but not for MTP.  1.9.1.6 stated that T-Rex was adding MTP.

**Comment by jwesolo** [comment]
On reddit they say it's too cumbersome to manage that algorithm.

https://www.reddit.com/r/NiceHash/comments/c9h7r7/wheres_mtp_in_the_1926/

**Comment by jwesolo** [comment]
Also issue #1623

**Comment by vanmald** [comment]
Admins, please close this issue that I opened (duplicate).  I understand that this was a decision made to not support MTP for now.  I have experienced the "mining lost" issue so it make sense.  I hope these issues can be worked out at some point.

**Comment by vanmald** [comment]
Closing issue. Just noticed I can do this myself.
