### ISSUE TITLE
1.9.2.6 Selects USA location instead of Europe at start

### ISSUE THREAD

**Issue by vasyapupkin1** [nicehash/NiceHashMiner#1628]
All locations are correctly selected, except Europe

**Comment by jwesolo** [comment]
According to https://www.nicehash.com/news/important-transition-to-a-new-nicehash-platform Europe has not been enabled on new platform yet.

**Comment by vasyapupkin1** [comment]
If select manually - seems like it works

**Comment by S74nk0** [comment]
This was expected during the mining transition phase as we were gradually migrating miners.
