### ISSUE TITLE
v1.9.2.6 #1399 anti-hacking message in gminer still happening

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1629]
I have never had the problem described in #1399 but with v1.9.2.6 it is now happening to me. I have made no changes to antivirus settings and the mining directories remain excluded from antivirus interference. Thanks!

**Comment by taticahladni** [comment]
Same issue here. After struggling to start 19.1.7 , older 19.0.23 started to shut down for the same reason. I am unable to turn on any version of new miner. I will open new issue for that. I have to start 2-3 miners at once just to get it unstuck.

**Comment by dsarfati** [comment]
Has anyone else been able to solve this. Running into the same issues
