### ISSUE TITLE
1.9.2.6 / 1.9.1.6 diasappearing hashrate on daggerhashimoto

### ISSUE THREAD

**Issue by vasyapupkin1** [nicehash/NiceHashMiner#1632]
When mining on DaggerHashimoto(ClaymoreDual) hashrate appears for about 30-40 secs then become 0 on every card for about 10-15 secs. Miner still works and shows hashrate as usual.
![004](https://user-images.githubusercontent.com/29598026/60741930-00cd7b80-9f74-11e9-8b2f-aafadfeee8e2.jpg)

**Comment by muratia** [comment]
Same here but I am mining on old platform

**Comment by jwesolo** [comment]
This happens to me with TT-Miner. I thought I had mentioned it in another issue but I can't find it.

**Comment by Jfro416** [comment]
Same issue on new 1.9.2.9. I feel it is reducing the overall profitability. The rate also goes to 0 on the NH rig miner web platform.
Viewing the mining window there is no obvious flux in the hash rate. All lines are running normally.
![HashRate 0 Out](https://user-images.githubusercontent.com/41505204/61531175-26a85500-aa37-11e9-994b-db6ecad0e58b.png)
