### ISSUE TITLE
How to upgrade to 1.9.2.6 preserving bechmarking from 1.9.1.5?

### ISSUE THREAD

**Issue by diginice** [nicehash/NiceHashMiner#1633]
When I upgrading 1.9.0.X versions, I could move configs folder to retain benchmarking for all cards.
For 1.9.1.5 I rerun all benchmarks. Is there a way to upgrade to 1.9.2.6 preserving benchmarks?
1.9.1.5 does not have configs folder anymore.

**Comment by jwesolo** [comment]
You can move the 1.9.1.5 config folder. It will preserve some of the benchmarks but I had to redo a few of them. I think they reorganized some of the miner plugins so the software doesn't see them as the same thing as before.

**Comment by diginice** [comment]
> You can move the 1.9.1.5 config folder.
Thank you. I see now that the configs folder still there, so the old method of upgrading by moving configs still works.
