### ISSUE TITLE
Algo's mining on the wrong GPU 1.9.2.6

### ISSUE THREAD

**Issue by AmnesiaBR** [nicehash/NiceHashMiner#1634]
Hi, [this print](https://www.dropbox.com/s/llmc3nplit9n5v6/nicehash2.png?dl=0) shows the problem happening in my rig. If any more info is needed please reply and I will gladly provide it.

**Comment by S74nk0** [comment]
New version with updated ClaymoreDual plugin. Reopen if problem still exists

### Differences beetween versions 1.9.1.7 and 1.9.2.7 
| Feature:   |      [1.9.1.7](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.1.7/nhm_windows_1.9.1.7.zip)      |  [1.9.2.7](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.2.7/nhm_windows_1.9.2.7.zip) |
|----------|:-------------|:------|
| Name |    NiceHash Miner Legacy   |   NiceHash Miner |
| Platform |    Old Platform   |   New Platform |
| External plugins |  NO | YES |
| NVIDIA TDP Settings | NO |   YES (enabled by default)  |
| Username login | YES |   NO  |

Besides the aforementioned differences everything else is identical.
