### ISSUE TITLE
Ratio for GrinCuckaroo29 using GMiner is extremely low in 1.9.2.6.

### ISSUE THREAD

**Issue by vanmald** [nicehash/NiceHashMiner#1635]
Ratio for GrinCuckaroo29 using GMiner is extremely low in 1.9.2.6 compared to 1.9.1.5.  Which one is correct?  Difference is 15038 vs 144.

According to whattomine.com, GrinCuckaroo29 should be the 2nd more profitable and right now in 1.9.2.6, it shows as one of the lowest profitable coins.

**Comment by prettycode** [comment]
There aren't a lot of buyers on the new platform yet, so profitability is (much) lower, currently, for those mining to it.

**Comment by S74nk0** [comment]
Issue related to market/price fluctuation 

Closing
