### ISSUE TITLE
v1.9.2.6 seemingly mining without payment 

### ISSUE THREAD

**Issue by dark8899** [nicehash/NiceHashMiner#1636]
It has been active for several hours and there is no pending payment or profitability calculation. sometimes the global ratio appears again sometimes not. v1.9.2.6 (New Plataform Active and Wallet adress set)
![minindontwk](https://user-images.githubusercontent.com/27753859/60749102-459ce680-9f63-11e9-84b0-639fb6517631.png)

**Comment by hazemhagrass** [comment]
I have the same issue. Any updates!!

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner/issues/1637#issuecomment-509116317

From [notice](https://www.nicehash.com/news/important-transition-to-a-new-nicehash-platform)

> Miners, please note that you can start mining on the new platform immediately once we start the transition! Your entire current unpaid mining balance will be transferred to your account on the new platform at the end of the transition period.

> 

>
