### ISSUE TITLE
1.9.2.6 - No login request at startup

### ISSUE THREAD

**Issue by vanmald** [nicehash/NiceHashMiner#1637]
With the new 1.9.2.6, there is no login request.  I am guessing that is why we don't automatically see the bitcoin address and balance amounts displaying at all.

**Comment by S74nk0** [comment]
@vanmald The balance amount was not being displayed due to the mining transition (this was explained in the transition [notice](https://www.nicehash.com/news/important-transition-to-a-new-nicehash-platform)). Login is sent only if you have valid BTC set.
