### ISSUE TITLE
NHML Crashing Video Drivers if multiple GPUs are present

### ISSUE THREAD

**Issue by Superdeuxd** [nicehash/NiceHashMiner#1641]
I have a 6 GPU Nvidia Rig (2 1080's, 1 1070, 3 1060's) that mined on NHML x.x.x.23 without issue until one day the system crashed.  Upon reboot, it recognized all GPUs but when mining started, would crash the video drivers.  The MOBO recognizes all GPUs, Win10 recognizes all GPUs, Afterburner and Nvidia Inspector recognize all GPUs - UNTIL NHML starts... As soon as it starts, the video drivers crash and all but one GPU are recognized by Afterburner and Inspector.

So...

I updated everything.  Video Drivers, NHML, CUDA, Win10, etc.

Same problem.

I've run as Admin

Same problem.

I assumed that maybe something in Windows got corrupted.  I formated the SSD and did a full fresh install.

Same Problem

Maybe BIOS issue.  Updated and verified all settings

Same Problem

Maybe a hardware problem?  Each GPU will install and mine perfectly and stable if it is the ONLY GPU installed.  Any PCIe Slot, using any riser, using any power connector, in any combination.  As soon as I try to add another GPU, Same Problem as soon as NHML tries to start.

Windows error reporting refers to an issue with a CSLID and requiring taking ownership and modifying some registry settings.  I've done that. 

Same Problem

I'm at my wit's end.  I cannot get this rig running again.

**Comment by vasyapupkin1** [comment]
Probably different miners trying to use one card. Try each algo for each card and see in log wich card is used.

**Comment by Superdeuxd** [comment]
I thought that too.  So I tried leaving 2 cards installed, but disabling one in NHML.  As soon as I start the benchmark for the second one, the Video Drivers crash and revert to the default Windows video drivers effectively crashing the system.

**Comment by Superdeuxd** [comment]
So, here's a possible clue...

I rolled back Nvidia drivers to several older versions.  All were met with the same end result.  Crash. All at basically the same point in NHML launch.  I don't think it's the Nvidia drivers.

On a whim, I plugged in a GTX970 I had laying around.  It was found, installed, benchmarked, and is running just fine with one of the 1080's.  So, the two cards are running now.  If i plug in any of the others (1080, 1070, or 1060) Boom, Crash.

I know the 970 has a different architecture and I'm wondering if Windows and how it utilizes the Nvidia drivers is the issue. But I have no idea where to begin looking, nor am I finding much guidance on the almighty Google.

**Comment by Superdeuxd** [comment]
Fun new observation.  NHML seems to be recognizing both the 1080 and 970 as "GPU0" and profitability is garbage.  Basically 30% of where profitability should be.  T-Rex is running for the 1080 and ClaymoreDual for the 970 (Daggerhashimoto)

If I start NHML with just the 1080 running, profitability is right where it should be.  If I then start mining the 970, Profitability jumps up to what it should be for a short period, then crashes by over half.  If I deactivate the 970, profitability for the 1080 jumps back up.

**Comment by Superdeuxd** [comment]
A follow up to the last post.

when I disable the 1080, and enable the 970 in NHML, the ClaymoreDual miner fires up as though the 970 is doing the mining, HOWEVER, looking at Nvidia Inspector, the 1080 is the GPU actually doing the mining!  WTF! the 970 has 0% load and 30 Deg Temp!

What is going on?!

**Comment by luc1an24** [comment]
Hi @Superdeuxd 
Thank you for reaching out.
Could you please append the logs so it will be easier to pinpoint the issue.
Thank you.

**Comment by Superdeuxd** [comment]
There are two "log" files in the log folder.  "log" and log.1"  Which should I post?

**Comment by Superdeuxd** [comment]
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3368102/log.1.txt)

[log.txt](https://github.com/nicehash/NiceHashMiner/files/3368106/log.txt)

**Comment by Superdeuxd** [comment]
UPDATE

Good news with NHML 1.9.1.7 - The 1080 and 970 are now operating properly.  Hashrates are as expected.  They are living a life of peace and harmonious mining.

The not so good news.  I got frisky and tried to start adding in GPUs.  The first one I grabbed was the 1070.  Windows boots.  Card found.  Driver Installed.  Device Manager says all is good.  Nvidia Inspector says all is good.  Afterburner says all it good.  Booted NHML and it shows up along with the 1080 and 970.  I proceed to benchmark. BOOM!  Video driver crashed the second it started benchmarking.

Attached is the windows event viewer error if anyone cares to see.  I thought I had ownership set, so I'm not sure where to go from here.  

![event viewer](https://user-images.githubusercontent.com/52608197/60851899-1aaccf80-a1bb-11e9-924d-66e18c41e994.JPG)

**Comment by Superdeuxd** [comment]
You wanted a Log, you got a log!

I cleared the logs out.  Plugged in the 1070.  Waited for everything to recognize all three cards (1080, 1070, & 970) Tried to benchmark the 1070 and think I captured the crash.  PLEASE tell me this is helpful and you can point me in the direction of what is going very very wrong!


[log.txt](https://github.com/nicehash/NiceHashMiner/files/3375293/log.txt)

**Comment by Superdeuxd** [comment]
Another Log

Since the 1070 wasn't benchmarking, I plugged in a1060.  Somehow it benchmarked and is currently mining!  Here's a copy of that log.  Again, I cleared the logs before starting NHML.


[log.txt](https://github.com/nicehash/NiceHashMiner/files/3375378/log.txt)

**Comment by Superdeuxd** [comment]
Another Log

I now have a 1080, 970, and TWO 1060's going.  I have another 1060 laying around, I may plug it in just to see if I can get 3 to run before I try the other 1080 or 1070 again...  Anyway, here's the log

[log.txt](https://github.com/nicehash/NiceHashMiner/files/3375584/log.txt)

**Comment by Superdeuxd** [comment]
Well, my enthusiasms were cut short when I woke up this morning.  System was crashed again.  Looking at device manager shows the Video Drivers tanked at around 12:25am.  Here are logs and System Event Logs
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3377148/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3377149/log.1.txt)
![Event viewer 2](https://user-images.githubusercontent.com/52608197/60964644-74a3b700-a2d9-11e9-9682-1cf9d914350c.JPG)

Then, at about 6,  This windows event was logged:

![event viewer 3](https://user-images.githubusercontent.com/52608197/60964668-81280f80-a2d9-11e9-946d-912eaef39cc3.JPG)

**Comment by Superdeuxd** [comment]
Soooooo.... No ideas then?

**Comment by luc1an24** [comment]
Hi @Superdeuxd
Sorry for no response, I was out of the office.
It looks that device drivers crashes and then system crashes too.
The new version of NHM [1.9.2.11](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.2.11/nhm_windows_1.9.2.11.zip) fixes the problem, but has a bug that can cause NHM to freeze.
You can try the 1.9.2.10 version in the meantime while we are fixing that bug and tell me if the system is still crashing.
Of course you can try the latest 1.9.2.11 version which has issue with driver crashing fixed, but if the NHM freezes at the startup, use the *2.10 one.
