### ISSUE TITLE
Nicehash Miner 1.9.2.6 "Error Status"

### ISSUE THREAD

**Issue by jasonr93** [nicehash/NiceHashMiner#1647]
Switching to the new platform i get "error" in the status column. When i switch back to the previous version i get no errors and mine without issues. Running Nvidia 1080's.

**Comment by luc1an24** [comment]
Hi @jasonr93 error status can be shown because of various reasons (no algo able to mine, etc.)
Could you please send logs?
Thanks

**Comment by jasonr93** [comment]
Hello. Today i decided to try again and mining was working. However mining is now disabled for the new platform for now. I'm guessing till everything is situated with the new platform, there may be issues.

**Comment by Diberkati** [comment]
I've installed a new Gigabyte NVIDIA GT710 and getting a status error that disables start. Why is that?
