### ISSUE TITLE
GPU #0: no kernel image is available - MTP

### ISSUE THREAD

**Issue by hugoburguete** [nicehash/NiceHashMiner#1648]
This issue seems to be persisting in the new version (v1,9,1,5).

Googling around suggested that it might be because my GPU is getting old and the CUDA version is no longer supported.

GPU: Geforce GTX 950
Log:
[2019-07-07 16:32:16] Starting on stratum+tcp://mtp.eu.nicehash.com:3374
[2019-07-07 16:32:16] NVML GPU monitoring enabled.
[2019-07-07 16:32:16] NVAPI GPU monitoring enabled.
[2019-07-07 16:32:16] 1 miner thread started, using 'mtp' algorithm.
[2019-07-07 16:33:37] Stratum difficulty set to 1 (0.00000)
[2019-07-07 16:33:37] GPU #0: Intensity set to 16, 65536 cuda threads
Step 1 : Compute F(I) and store its T blocks X[1], X[2], ..., X[T] in the memory
Step 2 : Compute the root F of the Merkle hash tree

Followed by an ending stream of messages saying:
GPU #0: no kernel image is available for execution on the device

_Originally posted by @jakubsuchybio in https://github.com/nicehash/NiceHashMiner/issues/1465#issuecomment-506978629_

**Comment by campmdabt** [comment]
Same for GTX 980

**Comment by howion** [comment]
Same for GTX 960

**Comment by brandadaniel** [comment]
GTX970 same error on nhm 1.9.1.7 with ccminer :
[2019-07-14 09:54:36] GPU #0: no kernel image is available for execution on the device

**Comment by viniflix** [comment]
Same for GTX940MX

**Comment by S74nk0** [comment]
Issue not related to nhm but ccminer MTP fork. Your GPUs aren't supported SM6.0+ will work with this miner.

**Comment by campmdabt** [comment]
If that's the case, please remove the ccminer mtp algorithm from unsupported cards.

**Comment by S74nk0** [comment]
@campmdabt [done](https://github.com/nicehash/NiceHashMiner/commit/423c14e79d2b909c4081125681a65a5bede977f7)
