### ISSUE TITLE
Changes not saving / not automatically restarting

### ISSUE THREAD

**Issue by camwilmot** [nicehash/NiceHashMiner#1650]
Anybody else having issues since 1.9.2.6 not saving changes and not automatically restarting when changes are made? I change the currency, that saves. However, if I change anything else such as autostart mining, the changes in that section do not save. And when I save the changes, it asks to restart, and previous versions it would restart and continue mining, now it does not.

And when I do restart, it asks to accept the agreements every time.

**Comment by Nicheuji** [comment]
Same for 1.9.2.7
1.9.1.7 seems to be working okay.

**Comment by S74nk0** [comment]
Where are you extracting the program? Does the user have write privileges on that path? Is some other program holding the file handles?

**Comment by Nicheuji** [comment]
> Where are you extracting the program? Does the user have write privileges on that path? Is some other program holding the file handles?

I've been extracting to the same place (D:\Downloads) for many versions of NHML already. Should we be extracting to somewhere specific?

**Comment by vasyapupkin1** [comment]
Try to do next: 
1 Start nicehash and open settings
2 Rename General.json to General.json.back
3 Change settings in Nicehash settings as you wish. Click Save and close in Nicehash settings. Nicehash wil write new General.json. If no new General.json than Nicehash can not write to location.
4 Compare General.json and General.json.back

**Comment by camwilmot** [comment]
One rig seemed to be a read only issue with the folder. Another rig it didn't matter if I set as not read only and moved the folder somewhere else. I tried deleting general.json while in NH, still didn't work. For now, on that rig, I have manually edited the general.json file.

All rigs have an issue that the AUD rate per day etc is not displaying anything, just 0.00
