### ISSUE TITLE
Add user delay when switching algo's

### ISSUE THREAD

**Issue by blacktigersoftware** [nicehash/NiceHashMiner#1652]
Just saw this happen, running 1.9.1.5.  Switching from phoenixminer to nbminer caused a massive lag/reset on computer/display.  Had performance monitor and resource monitor going, saw a 4+ gig committed memory went out (phoenix miner) and 6+ gig of new committed memory going in (nbminer).  This caused a massive 10+ gig of memory moving around.  If there were a 1 to 2 second delay between switching algo's this would probably fix this and many other problems.   Didn't you used to be able to run a script between switching algo's?.

**Comment by S74nk0** [comment]
@blacktigersoftware the user delay is still present (it is 1s = mandatory 500ms before start and variable 500ms after stop). You can change the after stop value  

>  Didn't you used to be able to run a script between switching algo's?.

No this was never the case. But we are considering including this in the plugin system. This would be useful feature for power users.

We will investigate if the default delay if it is big enough.
