### ISSUE TITLE
Whats wrong with GrinCuckaroo29?

### ISSUE THREAD

**Issue by seso1129** [nicehash/NiceHashMiner#1654]
![image](https://user-images.githubusercontent.com/52235140/60883243-ed196200-a25e-11e9-83c8-6b3ce8444c23.png)

**Comment by vasyapupkin1** [comment]
first check nbminier version. current is 23.3
try europe location

**Comment by S74nk0** [comment]
issue related to back-end. Back-end issues are resolved.

**Comment by seso1129** [comment]
Ur right.
