### ISSUE TITLE
1.9.2.7 are these benchmarked algorithms real?? 

### ISSUE THREAD

**Issue by seso1129** [nicehash/NiceHashMiner#1656]
![IMG_20190709_171659](https://user-images.githubusercontent.com/52235140/60889111-864f7500-a26d-11e9-9d72-2d415f0ba39a.jpg)
Almost nothing!!

**Comment by vasyapupkin1** [comment]
almost all is lower than normal for 1080

**Comment by CommunityJoshua** [comment]
Is this your normal pc?  or just for mining?  I mean with this many graphics cards you should easily use the NiceHashOS. Then all the hardware power 💪 is going into mining and not into dumb windows processes…

**Comment by seso1129** [comment]
@communityJoshua this of is just for mining, you say I have to run Nicehash OS? Is it more profitable?

**Comment by CommunityJoshua** [comment]
I dont know if its more profitable… it came new with the new nicehash platform… i havent used the OS yet but you can download it online at your dashboard when clicking on "download miner or add asic"

**Comment by S74nk0** [comment]
@seso1129 The benchmarks are not deterministic because they require actual mining to measure the speeds. We are working on a solution to make bench-marking deterministic.

**Comment by seso1129** [comment]
Thanks, but rewards are very low actually:/
