### ISSUE TITLE
Bypass internet connection prompt

### ISSUE THREAD

**Issue by fefsf** [nicehash/NiceHashMiner#166]
Please enable the ability to remove the no internet connection prompt. This will be helpful for the times in which the power is lost for a rig farm, and when the power is restored the PCs auto start up but by the time NHML starts the internet connection hasnt been established yet.  Although i know users can implement some type of delay, its possible the internet connection may not establish itself for several minutes if not longer, and having the prompt prevent mining until a user clicks a button inst necessary IMO.  Having NHML keep checking for internet in the background every 30 seconds or so  and resume mining when detected would be great.

**Comment by gpcola** [comment]
There's an option to disable that popup in 1.8.1.1. Try the pre-release 
https://github.com/nicehash/NiceHashMinerLegacy/releases

**Comment by fefsf** [comment]
Thanks for the information. What does the app do if no internet connection is initially detected?

**Comment by fefsf** [comment]
![image](https://user-images.githubusercontent.com/20034137/29431734-00db2ac6-8367-11e7-85d2-2b5a8d6eb004.png)


Looks like the original problem remains when this option is checked. User must be present to continue

**Comment by gpcola** [comment]
My apologies. I thought this was the functionality it added, but haven't gotten around to testing it yet myself.

**Comment by DillonN** [comment]
The new option disables the message that no internet connection was found, but mining is still unable to start if profitability data has not been received at least once. NHML does not know which algorithm to start mining since it has no idea which will pay the most

**Comment by fefsf** [comment]
@DillonN That makes sense, what I was suggesting was making the profitability check able to re-check automatically without user input, that way whenever a miners internet comes back online mining can resume. As it stands now, if my power comes back online and my internet comes online 15 minutes later, no mining can start at all because I would need to manually log into my machines to acknowledged the profitability data prompt. 

As far as I know, if internet is lost temporarily while a miner is already mining, it will display a red error similar to "NO INTERNET DETECTED", however, it will keep trying in the background ( and i assume will keep checking profitability). This feature should simply be extended to when NHML is initially opened as well, instead of requiring user interaction with the prompt.

**Comment by sebeksd** [comment]
I have same issue always when I did enable "auto start mining". So even if internet connection is present and I launch NHML the message "Unable to get NiceHash profitability data. If you are connected to internet, try again later." appears. 
I think this problem should be fixed first before adding any other options. 
I did some debugging and it seams that first tries of getting SMA data fail or takes to long. When app shows and message is displayed I can close message window and press start without any further problem.
I did made a little workaround making autostart functionality to be delayed about 4 seconds from main window loading progressbar and it worked.
You can see my workaround here https://github.com/sebeksd/NiceHashMinerLegacy/commit/453cebafd92e875f5b3d059f7309faf7c620bcb4

**Comment by Ketoman** [comment]
This was fixed for me in v1.8.1.2, I got the message every almost every time I started nicehash, now I don't get it at all.

**Comment by fefsf** [comment]
@ketoman Yes but what happens if your internet connection  isn't established before nicehash starts?

**Comment by sebeksd** [comment]
@fefsf To be sure this doesn't happen to me I disabled "Run with windows" and I added NHML to windows schedule to run 30s after login to windows . Of course this is not bulletproof solution but in could help in some situations.

**Comment by Ketoman** [comment]
fefsf, if it really can't connect, it retires for a while, then displays the error.

I count it doing a retry for 16 iterations (retries), then it stops and displays the error.  So if it really does have a connection problem, it will still pause with the error.  I didn't try this on the previous version to see what it does, this is from the upgraded version 1.8.1.2 that I am running now.  Again, the old version got stuck here all the time, the new version seems much better to me.

This is the log output:

[21:54:26] [SOCKET] Connection closed: An error has occurred while connecting.
09/05/2017 21:54:27|Debug|WebSocket.sendHttpRequest|A request to the server:
                          GET /v2/nhm HTTP/1.1
                          User-Agent: websocket-sharp/1.0
                          Host: api.nicehash.com
                          Upgrade: websocket
                          Connection: Upgrade
                          Sec-WebSocket-Key: 2Bc0x/TgiQZDmkKgh684WQ==
                          Sec-WebSocket-Version: 13
09/05/2017 21:54:28|Debug|WebSocket.sendHttpRequest|A response to this request:
                          HTTP/1.1 520 Origin Error
                          Date: Wed, 06 Sep 2017 03:54:27 GMT
                          Content-Type: text/html; charset=UTF-8
                          Transfer-Encoding: chunked
                          Connection: keep-alive
                          Set-Cookie: __cfduid=d15675e623d59c81009879d1cd2f5b7771504670066; expires=Thu, 06-Sep-18 03:54:26 GMT; path=/; domain=.nicehash.com; HttpOnly
                          Expires: Thu, 01 Jan 1970 00:00:01 GMT
                          Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
                          Pragma: no-cache
                          X-Frame-Options: SAMEORIGIN
                          Server: cloudflare-nginx
                          CF-RAY: 399e7cad1e724fc3-DEN
09/05/2017 21:54:28|Fatal|WebSocket.connect|Not a WebSocket handshake response.
09/05/2017 21:54:28|Debug|WebSocket.closeHandshake|Was clean?: False
                            sent: False
                            received: False
[21:54:28] [SOCKET] Connection closed: An error has occurred while connecting.
[21:54:29] [NICEHASH] Bitcoin rate get
[21:54:29] [NICEHASH] The remote server returned an error: (520) Origin Error.
[21:54:29] [ExchangeRateAPI] UpdateAPI got NULL
[21:54:29] [NICEHASH] Current Bitcoin rate: 0.00
[21:54:29] [NICEHASH] Setting environment variables
[21:54:29] [NICEHASH] Trying to enable/disable Windows error reporting
[21:54:29] [NICEHASH] Current DontShowUI value: 1

**Comment by edi** [comment]
It would make sense for us to be able to disable this check because there are a lot of miners who only mine one algorithm ... so my rigs are stuck doing nothing while there is a power outage and the internet takes longer than few minutes to restore ...

Any way to disable this, knowing it wont fetch the "profitability" given I'm not interested in it ?
