### ISSUE TITLE
Not updating the mBTC /day - Eur/day 

### ISSUE THREAD

**Issue by ThiagoSF7** [nicehash/NiceHashMiner#1667]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by X-miner** [comment]
My feedback: in all my 3 rigs the mBTC/day is tracked, the EUR/day is NOT working , the mBTC balance is tracked, the EUR balance is NOT working.
![Cattura](https://user-images.githubusercontent.com/52356302/61167993-167c0b80-a547-11e9-8a2f-bed3c60973c1.PNG)

**Comment by S74nk0** [comment]
Duplicate https://github.com/nicehash/NiceHashMiner/issues/1677.
