### ISSUE TITLE
Not Updating the stats of the GPUs Hash Rate etc

### ISSUE THREAD

**Issue by ThiagoSF7** [nicehash/NiceHashMiner#1668]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by X-miner** [comment]
My feedback: in 1 only of my 3 rigs using NB Miner for GCuckatoo 31 in a 2080Ti i receive at the start the message:  failed to initialize NVML so the main info of the GPU status are not being showed however the GPU is mining perfectly with good hashrate and temperature status.

**Comment by S74nk0** [comment]
@ThiagoSF7 please elaborate when opening issues. I am not sure what you mean with this. If it is related to https://github.com/nicehash/NiceHashMiner/issues/1677 please close this.
