### ISSUE TITLE
SKUNK parameter missing

### ISSUE THREAD

**Issue by fefsf** [nicehash/NiceHashMiner#167]
![image](https://user-images.githubusercontent.com/20034137/29427353-68213866-833e-11e7-9d90-de95fec01e8d.png)

I get this error on latest build. I can resolve this by manually replacing the ccminer file with a working version.

**Comment by DillonN** [comment]
ccminer_trpruvot was updated with support for Skunk in the new build. You cannot just copy the bin folder over you need to let NHML download the newest versions
