### ISSUE TITLE
Constantly giving this error (print screen)

### ISSUE THREAD

**Issue by ThiagoSF7** [nicehash/NiceHashMiner#1670]
![Captura de Ecrã (1)](https://user-images.githubusercontent.com/52469894/61161701-f4f63200-a4fc-11e9-8d7c-6fa4abf122b1.png)

**Comment by vasyapupkin1** [comment]
Try to ping daggerhashimoto.eu-new.nicehash.com at the same time to check if network is stable.

**Comment by S74nk0** [comment]
DNS resolve issue... Networking issue on users ISP side or ISP is blocking our services. 
Closing
