### ISSUE TITLE
translation issue | english

### ISSUE THREAD

**Issue by CommunityJoshua** [nicehash/NiceHashMiner#1673]
![grafik](https://user-images.githubusercontent.com/21293543/61178776-f99e1180-a5f4-11e9-9b0d-67b356c099de.png)
after i clicked on "Eable NVIDIA power mode settings!" i got this Dialog:
![grafik](https://user-images.githubusercontent.com/21293543/61178778-ff93f280-a5f4-11e9-99d0-ac3d351cd3b9.png)
I think it should be called "Click yes if you wish to run NiceHash Miner as Administrator"

**Comment by grichter** [comment]
Could also use "want to run"

**Comment by S74nk0** [comment]
@CommunityJoshua thanks for pointing this out. I guess the I was tired :) and wrote gibberish. We will fix this in the next release.
