### ISSUE TITLE
All Lyra Algos not mining in AMD VEGA 64

### ISSUE THREAD

**Issue by ThiagoSF7** [nicehash/NiceHashMiner#1675]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by S74nk0** [comment]
@ThiagoSF7 this is probably related to this PR https://github.com/nicehash/NiceHashMiner/pull/1672. 
[1.9.2.9](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.9) and [1.9.1.9](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.9) includes this. Now we are relying on device name to determine the GCN version and this is quite error prone. Until we find a better solution device name is our only fallback method.

Please try [1.9.2.9](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.9) and close this issue if it works.
