### ISSUE TITLE
nhml v1.9.1.7 is actually running as v1.9.1.5

### ISSUE THREAD

**Issue by modderchris** [nicehash/NiceHashMiner#1676]
simple the current version(v1.9.1.5) is claiming a new one exists (v1.9.1.7) but the download zip for the latest version is for v1.9.1.5(claimed v1.9.1.7) but is labeled everywhere as v1.9.1.7(actually v1.9.1.5) and the constant flashing "important new version is available" is starting to get annoying when I have tried the link 3 times in the past few weeks
![Capture](https://user-images.githubusercontent.com/18231501/61194672-053f1600-a691-11e9-8b63-0abeea0ff2d8.PNG)
please note that I seperate the cpu/gpu instances for seperate" idle start" options but the update is always copied with overwrites to BOTH folders (although I should just make a batch to do it for me....I am so lazy)

**Comment by ahelguerrero** [comment]
The latest legacy version is [1.9.1.8](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.8).

**Comment by S74nk0** [comment]
@modderchris I cannot reproduce this. I am not sure what do you mean exactly? Do you copy over nhm and the miner aren't updated?

**Comment by modderchris** [comment]
well the zip file is downloaded from the update link provided by clicking
the link inside of the program, unzipped, copied to the CPU/GPU folders and
any conflicts are "overwritten" with the files from the download
I can create a video of the process I do every update that always change
the notification and version and will link it in soon

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by modderchris** [comment]
lol it was fixed just after I posted this

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
