### ISSUE TITLE
No mBTC/day

### ISSUE THREAD

**Issue by DualByte** [nicehash/NiceHashMiner#1677]
The mBTC/day will not change even when miner is started

**Comment by Jfro416** [comment]
Same issue on new platform. (1.9.2.8). Old is working normally. Perhaps it is due to the transition period? Been monitoring via the web interface which updates in real time without issues so far.

**Comment by S74nk0** [comment]
This is backend issue and it is fixed now. Closing

**Comment by yabba88** [comment]
My Nice hash miner v 1.9.2.9 shows my Global Rate BALANCE at 0.0080  mBTC .08 

Question how often will I get transfers to my bitcoin address xxxxx    if I am getting approximately 0.0080  mBTC .08 daily. 

How do I know if my wallet is setup to go directly to my coin base account? or are the BTC funds going direct to my Nice hash Wallet..
Thanks for the anticipated replies. Cheers Alan
