### ISSUE TITLE
Nicehash 1.9.2.8 stuck at start

### ISSUE THREAD

**Issue by wareck** [nicehash/NiceHashMiner#1679]
Hello
I try several time to start the new nicehash software and always freeze when I start.
If I was half an hour, it start to download miner but still freeze at the beginning

![2](https://user-images.githubusercontent.com/5462099/61279794-15511580-a7b7-11e9-98f2-b31211922963.png)

I try to made it from source and take the realease = same issue
I shutdown firewall / anti-virus without any effect

reagards
wareck

**Comment by ZIF77** [comment]
![InkedСнимок_LI](https://user-images.githubusercontent.com/52971340/61310801-ae0a8400-a7fd-11e9-84b7-6e4e8eb6624b.jpg)
![InkedСнимок1_LI](https://user-images.githubusercontent.com/52971340/61310810-b19e0b00-a7fd-11e9-8bd9-9863124ce911.jpg)
Как такое может быть?

**Comment by vasyapupkin1** [comment]
Rate - is not constant. And almost all hashpower buyers still on old platform.

**Comment by vasyapupkin1** [comment]
> 
> 
> Hello
> I try several time to start the new nicehash software and always freeze when I start.
> If I was half an hour, it start to download miner but still freeze at the beginning
> 
> ![2](https://user-images.githubusercontent.com/5462099/61279794-15511580-a7b7-11e9-98f2-b31211922963.png)
> 
> I try to made it from source and take the realease = same issue
> I shutdown firewall / anti-virus without any effect
> 
> reagards
> wareck

If problem in downloading, find miner_bins_urls.json. Try to access/download  links in it manually.
