### ISSUE TITLE
Miner shuts down with no errors

### ISSUE THREAD

**Issue by Shaamaan** [nicehash/NiceHashMiner#168]
Everything was working fine until yesterday. Now, when I start mining, the NHM client just stops (doesn't look like it even opens the miner console) and is gone without any errors.

Here's the log file:
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1233359/log.txt)

**Comment by DillonN** [comment]
I'm not seeing any errors in your log. It seems like it is crashing when trying to launch claymore_dual, are you able to get it to work if you disable all the ClaymoreDual algorithms?

**Comment by Shaamaan** [comment]
After some more fiddling around with everything (reinstalling VC Redist, pulling hairs out, etc) it turned out it's Kaspersky. Despite having the folder where NHM resides as an exception, Kaspersky straight up killed the process in the latest (2018) version. I've reverted back to version 2017 and NHM is working again.
