### ISSUE TITLE
Nicehash 1.9.2.8 freezes and system not responding after a while

### ISSUE THREAD

**Issue by 0xBAADF00D** [nicehash/NiceHashMiner#1680]
**I have a 19 mixed card rig (16 NVIDIA P106-100 and 13 RX 580). After about 20 minutes mining with TeamRedMiner the GUI is freezing (mining is still going on!) and NiceHashMiner is increasing the thread count until windows is no more responding (up to 220-230 threads).**

"Manually mining" with TeamReadMiner on console or by NHM with Claymore is no problem.

Updating the display driver didn't help.

**Comment by S74nk0** [comment]
@0xBAADF00D Could you please provide logs? Or more info regarding this.

**Comment by 0xBAADF00D** [comment]
@S74nk0 Not so easy: Following a screenshot shortly before Windows gets stuck:
![Screenshot](https://user-images.githubusercontent.com/52955609/61649084-0a175180-acb1-11e9-92e8-b5031dfaba6f.png)

Also attached the today's logs. The only errors I can find are those of them:
`[2019-07-22 18:00:26] [ERROR] [NVAPI] Tach get failed with status: EXPECTED_PHYSICAL_GPU_HANDLE`

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3418413/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3418414/log.txt)

**Comment by 0xBAADF00D** [comment]
@S74nk0 Not so easy: Following a screenshot shortly before Windows gets stuck:
![Stuck](https://user-images.githubusercontent.com/52955609/61649907-b9085d00-acb2-11e9-94db-4b3b39f44a21.png)

Also attached the today's logs. The only errors I can find are those of them:
`[2019-07-22 18:00:26] [ERROR] [NVAPI] Tach get failed with status: EXPECTED_PHYSICAL_GPU_HANDLE`

[log.txt](https://github.com/nicehash/NiceHashMiner/files/3418449/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3418450/log.1.txt)

**Comment by 0xBAADF00D** [comment]
@S74nk0 Not so easy: following a screenshot shortly before Windows gets stuck:
![Stuck](https://user-images.githubusercontent.com/52955609/61650195-7004d880-acb3-11e9-99d5-c1a048fdfcaa.png)

Also attached the today's logs. The only errors I can find are those of them:
`[2019-07-22 18:00:26] [ERROR] [NVAPI] Tach get failed with status: EXPECTED_PHYSICAL_GPU_HANDLE`

[log.txt](https://github.com/nicehash/NiceHashMiner/files/3418479/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3418480/log.1.txt)
