### ISSUE TITLE
Nicehash 1.9.2.8 unstable - dies after starting CuckooCycle gminer

### ISSUE THREAD

**Issue by F1Rumors** [nicehash/NiceHashMiner#1681]
Crashed twice now after running for a while.  Same log entries both times:

		MOST PROFITABLE ALGO: CuckooCycle_GMiner, PROFIT: 0.000067235799

[2019-07-14 12:15:41] [INFO] [MiningManager] Mine always regardless of profit
[2019-07-14 12:15:41] [INFO] [MiningManager] PrevStateProfit 0.00026715043614819, CurrentProfit 0.000282002456140566
[2019-07-14 12:15:41] [INFO] [MiningManager] Will SWITCH profit diff is 0.0555942195210848, current threshold 0.04

AFTER this, the logfile stops reporting the lines after "always mine" that report the profit statement and whether or not to switch.

I am going to disably CuckooCycle for now & see if stability improves.

**Comment by S74nk0** [comment]
@F1Rumors what GPU is this? Is is primary GPU? How much free GPU RAM does it have? Sounds like the GPU doesn't have enough RAM

**Comment by F1Rumors** [comment]
Good question. The 1070TI might be the problem, specifically, if memory is
tight. Let me turn it back on for the Titan cards and see if it behaves, as
they have enough memory to handle grin31...

**Comment by S74nk0** [comment]
@F1Rumors We have a feature in the works regarding this. Previously most algorithms weren't really resource intensive (most of them at least). We plan to add an extra step before switching to check if the algorithm has enough system resources. Currently this is missing and such feature would prevent a miner restart loop.

**Comment by F1Rumors** [comment]
That is a great idea!
