### ISSUE TITLE
[Write build instructions] Nicehash will not populate device fields if Radeon 5700XT is installed.

### ISSUE THREAD

**Issue by PrinceOfParallax** [nicehash/NiceHashMiner#1685]
Current version of NH will not see my Radeon.

**Comment by S74nk0** [comment]
@PrinceOfParallax can you run `device_detection_test.bat` in nhm root? Now if **OpenCL.dll** is in the root run it twice so we can see the difference in the output and paste **device_detection_test_output.txt** here

**Comment by S74nk0** [comment]
If **OpenCL.dll** is in the root path delete it and then run `device_detection_test.bat`

**Comment by ahelguerrero** [comment]
Same thing here. My device wouldn't be show up when compiling the code. I found that DeviceDetectionPrinter.exe did not existed, so I had to run that program first and then the NH program. That seem to solve my problem. You could try it. Never tried the above.

**Comment by S74nk0** [comment]
@ahelguerrero when building for **release** always rebuild the whole solution. NiceHashMiner client is composed of multiple projects and pre_compiled dll's (https://github.com/nicehash/NiceHashMiner/tree/master/pre_compiled_libs) that get copied on post build events (they might not get triggered). If any dependency is missing it will not work and this is especially the case with `DeviceDetectionPrinter.exe` as it relies on pre_compiled_libs

**Comment by ahelguerrero** [comment]
Ohhhh that may solve some of the issues I have. hehehe

**Comment by PrinceOfParallax** [comment]
Also resolved mine - thank you.

**Comment by S74nk0** [comment]
We will write build instructions in the docs regarding all the build flags and how to ensure a proper build. Until we have this keep issue open.
