### ISSUE TITLE
1.9.1.9 no GrinCuckarood29 

### ISSUE THREAD

**Issue by vasyapupkin1** [nicehash/NiceHashMiner#1686]
1.9.1.9 no NBMiner with Cuckarood29 for 1080, 1070, 1060 but 1.9.2.9 it has
![002](https://user-images.githubusercontent.com/29598026/61400304-a835a100-a8d8-11e9-9df3-5caba14422a1.jpg)
![001](https://user-images.githubusercontent.com/29598026/61400306-a8ce3780-a8d8-11e9-9ddf-d6033fd13257.jpg)

And other algos/miners slightly different

**Comment by Nicheuji** [comment]
![image](https://user-images.githubusercontent.com/29155732/61422807-e31eef80-a93f-11e9-80fa-72013ce5d7c5.png)
Only the new platform (1.9.2.9) has it.

**Comment by vasyapupkin1** [comment]
So how to mine it on old platform?

**Comment by S74nk0** [comment]
@vasyapupkin1 There is no support for GrinCuckarood29 on the old platform. You can't.

Here are algorithm differences for old and new platform https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/Mining/Plugins/SupportedAlgorithmsFilter.cs#L14-L32.

MTP is not supported on the new platform GrinCuckarood29  is not supported on the old one.

I will close this issue.
