### ISSUE TITLE
How can I change XmrStak CPU mining settings for new platform Nicehash

### ISSUE THREAD

**Issue by SallehHedrah** [nicehash/NiceHashMiner#1688]
Hello, I have issue with the new platform Nicehash miner, normally I play games on my computer most of the time while running Nicehash miner at the same time. My problem is the latest version of miner which is NiceHash Miner **v1.9.2.8** make my game lag, i still currently using NiceHash Miner **v1.9.0.23** which does not lag my game/only a very small lag with it, I notice the new version used up to 55%+ cpu usage **full 8 cores** while the old version only use below 29% cpu usage **only 4 cores**, how can I change the setting to make it run 4 cores or any number that I want on the latest version of Nicehash. I'm sorry if my English is a little bad. My current system is Ryzen 7 2700x and GTX 1060 6GB. Below is the screenshot of the the miners with task manager open. I show u all the snapshot i can get from the setting i saved. For some reason the files I edit on **cpu_0** back to default setting ( which use all 8 cores ) every time i start the mining. I have been trying to solve this matter for almost a week by now still didn't get any solution, I hope I could get a help from here I will be happy and hopefully for those who have same issue with me could find the solution here. thank you

![1](https://user-images.githubusercontent.com/48820282/61584858-f4573e80-ab81-11e9-87dd-7515ec19263d.png)
Old Version NiceHash v1.9.0.23

![2](https://user-images.githubusercontent.com/48820282/61584863-03d68780-ab82-11e9-89e6-5f2710cff0ab.png)
New Version niceHash v1.9.2.8

I tried to edit files inside the NiceHash config setting , I prefer using core number 1,3,6 and 7

![3](https://user-images.githubusercontent.com/48820282/61584870-0e911c80-ab82-11e9-89ac-9a681e9fb343.png)
config1

![4](https://user-images.githubusercontent.com/48820282/61584874-1486fd80-ab82-11e9-9480-ffa285737728.png)
config 2

![5](https://user-images.githubusercontent.com/48820282/61584880-1bae0b80-ab82-11e9-9bb1-7d6844a58ac4.png)
![6](https://user-images.githubusercontent.com/48820282/61584883-1e106580-ab82-11e9-9e20-69276ce0f3b4.png)
![7](https://user-images.githubusercontent.com/48820282/61584885-210b5600-ab82-11e9-8dec-3d8ff1d8abd3.png)

**Comment by SallehHedrah** [comment]
can anyone help me please? Ive been trying to get help sicne last week.. I cant take this anymore :(

**Comment by grichter** [comment]
Sadly I suspect fixing it will require you to build a custom compile with an altered plugin dll as those control the content of the individual miner configuration files.

Alternatively you can manually configure an independent copy of xmrstak or xmrig to run independently as an unmanaged rig - just use the asic details for the stratum info and edit the rest to suite your needs. I do this myself for some older machines that are no longer supported by the miners included with nicehash but that remain stable and profitable for me under xmrig.

**Comment by S74nk0** [comment]
@SallehHedrah can you compare xmr-stak settings between nhm versions? nhm 1.9.0.23 has a **bug** with xmr-stak generation it will generate xmr-stak settings for **CryptoNightHeavy** and this algorithm uses half of CPUs than **CryptoNightR** for example. So nhm 1.9.0.23 will mine **CryptoNightR** with **CryptoNightHeavy** settings and this is not the most optimal setting while the new version generates these settings correctly. So this is how my settings look.

![image](https://user-images.githubusercontent.com/1517233/61779200-8a989800-ae00-11e9-956c-dcfc8969c810.png)

I am not sure what is not working with xmr-stak settings template? I have tested this and it works  whatever setting I set in the template it will use it. So you are either changing these templates while nhm is running (this will not work on each change nhm needs to be restared) or you are not familiar how xmr-stak settings work. 

To me it looks like you want the same settings from 1.9.0.23, so check that and set it to the template. Or just set `"affine_to_cpu" : false` and let the OS use your threads on any core that can do work (this will reduce lag and miner performance). Lastly some of the GPU miners are also CPU intensive those could be lagging your PC while gaming.
