### ISSUE TITLE
1.8.1.1 pre3-проблемы

### ISSUE THREAD

**Issue by Jonni1986** [nicehash/NiceHashMiner#169]
![default](https://user-images.githubusercontent.com/31125809/29449770-c127b892-8404-11e7-8019-96332c8a711f.png)
Выбивает майнер каждые 5-10 минут! В чём проблема?

**Comment by Jonni1986** [comment]
ошибка 87

**Comment by CryptoFire24** [comment]
What is this i dont speak that language i am getting the same error

**Comment by drkskwlkr** [comment]
@CryptoFire24 It is an overclocking problem. The OP wrote in #157 that the problem disappeared for him as soon as he decreased memory clock by 50 MHz. Why he decided to say everything in Russian I have no idea :)

**Comment by CryptoFire24** [comment]
Ahhh thank you! I have mine ovclocked lmao by 400mhz... thank you much i had no idea
