### ISSUE TITLE
Error under status 

### ISSUE THREAD

**Issue by funnyme158** [nicehash/NiceHashMiner#1694]
Im getting a error message under status. I am using a RX 5700 XT. It shows Algorithms 8 Enabled 3 and Benchmarked 0 . How do I fix this and get it to start mining

**Comment by Superdeuxd** [comment]
Click "Stop All" on the right side of the miner.  

Click "Benchmark"

Select your GPU and enable all algorithms

Check the box that says "Start Mining After Benchmark"

Click "Start Benchmark"

**Comment by funnyme158** [comment]
perfect thanks

**Comment by luc1an24** [comment]
Help was provided.
If you need any additional help please open a new issue.

**Comment by Yashraj19** [comment]
Using a Radeon 7670M graphics card says algo 4 enabled 4 and benchmarked 4 but gpu doesn't work

**Comment by sifr360** [comment]
this is bullshit
