### ISSUE TITLE
Only two algorithms are shown as available.

### ISSUE THREAD

**Issue by odkarakac** [nicehash/NiceHashMiner#1696]
GPU: MSI armor GTX 1080
Windows 10 64 1903
Only Trex miner / Lyra2Z X16R algorithms ara shown in ui.

**Comment by S74nk0** [comment]
@odkarakac can you specify what nhm version are you running? What NVIDIA drivers are installed?

**Comment by CatDonIO** [comment]
nhm_windows_1.9.0.20 - https://imgur.com/a/w6SJOiG
nhm_windows_1.9.1.11 - https://imgur.com/a/zKfaFtD
NVIDIA drivers installed

**Comment by luc1an24** [comment]
Hi @boba1088 
We removed a lot of algorithms because they were unprofitable.
Could you also provide the version of NVIDIA drivers you are using?
A lot of miners require the latest drivers to be installed. If they are not the algorithms for these miners will be filtered out.
