### ISSUE TITLE
Feature Request: .Net Framework 4.7 upgrade

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#17]
Since .NET Framework is native on Windows 10 and a lot of the miners kind of work really well on the latest build of Windows 10

Could you upgrade the code to .NET Framework 4.6 (all other previous versions of 4.5.x and 4.x are end of life as of 2016 (except for 4.5.2))

The nice thing is .NET Framework 4.5 tried to be as backwards as possible so hopefully you can retarget the code and that is it (there might need to be some minor code changes but hopefully thats it)

3.5 SP1 is still valid until Server 2016 is end of life (wont be for a while)

.NET Framework 3.5 SP1: Beginning with .NET Framework 3.5 Service Pack 1 (SP1) the .NET Framework is defined as a component instead of an independent product. So, support for .NET Framework 3.5 SP1 is driven by the Lifecycle Policy of the Windows operating system (that is, when Windows is in the Mainstream Support phase or Extended Support phase, so are its components). When a product such as Windows reaches the end of support, so do its related components. .NET Framework 3.5 SP1 is supported on Windows Vista SP2, Windows 7 SP1, Windows Server 2008 SP2, Windows Server 2008 R2 SP1, Windows 8.1 Update, Windows Server 2012, Windows Server 2012 R2, Windows 10, and Windows Server 2016 according to the end of support date for each operating system.

https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework

**Comment by billmcilhargey** [comment]
Well digging further heck if you can get it up to 4.7 that would be optimal ** although there are a lot more changes in 4.6 and 4.7 so may be more difficult but worth a shot as time permits?

**Comment by DillonN** [comment]
The idea has been to support older OSes, e.g. Windows XP/Server 2003 which cannot use .NET Framework 4.5 and up

EDIT: The project's overall targeting may be changed. During this I will look at upgrading to 4.5 since many miners don't support older OSes anyway

**Comment by billmcilhargey** [comment]
ok sounds great, saw the edit as I was going to note users should not be running XP and Windows 7 SP1 should be used (but for mining really Windows 10 Creators Update should be the true build at some point)

Especially with all the enhancements and fixes Nvidia and AMD (and the mining programs) have implemented targeting Windows 10

But anyways sounds cool, I am updating this to target 4.7 (if possible) as 4.7 targets Windows 10 Creators update and later  but don't feel like you have to use this version

**Comment by billmcilhargey** [comment]
lol ran across this in the language files

"NET45_Not_Intsalled_msg": "NiceHash Miner Legacy requires .NET Framework 4.5 or higher to work properly. Please install Microsoft .NET Framework 4.5"

**Comment by abdwyer** [comment]
I agree that framework should be retargeted to at least 4.5, supporting Win7+. Nvidia does not offer XP/Vista drivers for 10 series cards, and support from AMD seems to have ended at R9 series.  I can't make a good argument to keep support for XP/Vista in.

Retargeting seems to have no adverse effects, and allows the elimination of the Net20_backport code hacks.

**Comment by billmcilhargey** [comment]
All true!  Most of the miners, algorithms, and the latest drivers are all targeted for Windows 10 anyways and seem to work best in the latest build of Windows 10

**Comment by DillonN** [comment]
I have upgraded to 4.5 in the sma_socket branch (a new feature coming soon). I didn't say anything because NHM has had problems in the past with 4.5, but for the moment the plan is the main branch will be updated when this feature is merged.

**Comment by billmcilhargey** [comment]
Ok nice!  excited to see what that branch is all about once released!

Thanks!

Will close this out since it has been implemented (just in a later branch)

https://github.com/nicehash/NiceHashMinerLegacy/commits/sma_socket
