### ISSUE TITLE
only 1 out of 6 GTX 1060 is benchmarked

### ISSUE THREAD

**Issue by unicornioPT** [nicehash/NiceHashMiner#170]
i am running 6 Gigabyte gtx 1060 (model P106-100) on a AsRock H110 Pro BTC+ .
Windows 10 is updated.
All drivers are updated.
Win 10 "sees" 6 Nvidia gtx 1060 GPU.
---------
Legacy sees/identifies my 6 gtx 1060.
Benchamarking is fine for 1st GPU only.

Remaining GPUs :  the benchmark gets either Terminated or fails...

**Comment by DillonN** [comment]
Are you able to mine on the other GPUs? Since they would likely have the same performance you can copy the benchmarks from your first GPU (right click in the device screen)
