### ISSUE TITLE
why i cant create account on nicehash?

### ISSUE THREAD

**Issue by haiquan00** [nicehash/NiceHashMiner#1701]
hi there
when i try to create new account on nicehash, all items were fill, but when i click "create account", nothing hapeen, none error message prompt and none response from the web page.
i access the website in China.

Ocean

**Comment by GOSEF** [comment]
Try register here:
https://new.nicehash.com/my/register
If u meet the same problem, then try to change your browser 2 latest chrome or latest ie or latest firefox.

**Comment by luc1an24** [comment]
Hi @haiquan00 
If the issue still occurs please contact our support team (support@nicehash.com).

Not related to NHM.
Closing issue.
