### ISSUE TITLE
problem nicehash miner

### ISSUE THREAD

**Issue by Wetik21** [nicehash/NiceHashMiner#1704]
Nicehash miner 1.9.2.10 and the previous don't display the temperature and the loading of the nvidea card. In the miner this information is available. What could be the problem?

**Comment by luc1an24** [comment]
Hi @Wetik21 
Thank you for reaching out.
This is probably the driver issue. Could you please try the new [1.9.2.11](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.2.11/nhm_windows_1.9.2.11.zip) version and if that doesn't work send the logs.
The new version has implemented recovering of NVIDIA device monitoring on driver crash, so this could be the fix for your case.

Reopen the issue and send logs if the issue persist.

**Comment by Wetik21** [comment]
Now, miner doesn't load
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3482161/log.txt)

**Comment by ahelguerrero** [comment]
Oof.

**Comment by Wetik21** [comment]
The driver has already been reinstalled, nothing helped.

**Comment by ahelguerrero** [comment]
I was about to suggest that, but it seems some kind of other error. Is the driver updated?

Edit: Is your gpu new?

**Comment by luc1an24** [comment]
Hi @Wetik21
It appears that this is a bug we are already working on - some cards have problem with NVAPI.
Could you please run `CreateLogReport.exe` and send me the archived logs?
You can send them to `domen.kirnkrefl@nicehash.com` so no personal data will be public.
We will try our best to fix that issue as soon as possible.
Thank you for your patience.

In the meantime please use one of the older versions - where stats doesn't work but at least NHM doesn't freeze.

**Comment by Wetik21** [comment]
sent

**Comment by luc1an24** [comment]
Thank you for help
We will try to fix this bug asap!

**Comment by Ganriber** [comment]
I have a similar problem, cards ASUS MINING-P106-6G, using NiceHash Miner 1.9.2.10, the driver costs 431.60. Just me the temperature is visible, but does not display the rpm of the coolers. Go to NiceHash Miner 1.9.2.11 not, during the initialization of the monitoring devices, the program hangs! How can I contribute to the solution of this problem?

**Comment by luc1an24** [comment]
@Ganriber
Could you please run CreateLogReport.exe and send me the archived logs?
You can send them to domen.kirnkrefl@nicehash.com so no personal data will be public.
We have a clue where the problem is, so we just need to fix it.
I hope we will manage to fix it next week.

**Comment by Ganriber** [comment]
> @luc1an24 
> Could you please run CreateLogReport.exe and send me the archived logs?
> You can send them to [domen.kirnkrefl@nicehash.com](mailto:domen.kirnkrefl@nicehash.com) so no personal data will be public.
> We have a clue where the problem is, so we just need to fix it.
> I hope we will manage to fix it next week.

I sent you an e-mail.

**Comment by Ganriber** [comment]
@luc1an24
Tried to put 1.9.2.12, the problem persists, when loading the application hangs on the item "Initializing device monitoring", then it can only be closed through the application Manager!

**Comment by sangdrax8** [comment]
Still waiting on this fix, and now Beam is only available in versions that the bug persists in.

**Comment by Ganriber** [comment]
Great! Someone earns on a new algorithm, and we with NiceHash sit and waiting for...

**Comment by luc1an24** [comment]
Hi @Ganriber 
Thank you for your concern.
We are working on a fix, but this is a problem with NVIDIA API (NVAPI) and we don't have fix yet.
You can still mine BeamV2 directly with downloaded GMiner or LolMiner.
If you would like I can send you command line commands to miner BeamV2.
To mine other algorithms I suggest using 1.9.2.10 until this issue is fixed. 
Because of API issues some stats will be shown as 0's but at least you will be able to mine (with algorithm switching on).

Thank you for your patience as we are doing our best to fix this ASAP!

**Comment by Ganriber** [comment]
@luc1an24 For myself, I still found the decision to use ForkFix17, although he did not cause me confidence. But at the moment it is the most simple and convenient solution. I look forward to solving the problem in your app so that you can use it again.

**Comment by Wetik21** [comment]
with my problem that to run NiceHash miner 2.12 you need to fix general.json in disabledevicestatusmonitoring on “true”

**Comment by Ganriber** [comment]
> with my problem that to run NiceHash miner 2.12 you need to fix general.json in disabledevicestatusmonitoring on “true”

Thank you! It really works, but unfortunately in this case we lose the ability to control the temperature and speed of the fans.

**Comment by sangdrax8** [comment]
> with my problem that to run NiceHash miner 2.12 you need to fix general.json in disabledevicestatusmonitoring on “true”

Wow, How was this not the suggested work around.  I didn't realize this was a setting in the json.  At least I can start it now.

**Comment by ToxicYeah** [comment]
Please let us know when the "Initalizing device monitoring" bug for v1.9.2.12 is fixed. 

Your moderating and responsiveness is greatly appreciated. I do understand it's often thankless work.

**Comment by Ganriber** [comment]
There is another solution to this problem, you can take the NHM file.DeviceMonitoring.dll from version 1.9.2.10. In this case, even telemetry graphics cards will work!

**Comment by cryptheo** [comment]
> with my problem that to run NiceHash miner 2.12 you need to fix general.json in disabledevicestatusmonitoring on “true”

for rookies, can you tell me how can we do that?

**Comment by Wetik21** [comment]
> > with my problem that to run NiceHash miner 2.12 you need to fix general.json in disabledevicestatusmonitoring on “true”
> 
> for rookies, can you tell me how can we do that?

Open “general.json” with notepad, find line “disabledevicestatusmonitoring” and change “false” on “true”

**Comment by cryptheo** [comment]
it worked well done, appreciated

**Comment by S74nk0** [comment]
New version is released [new platform](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.13) or [old platform](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.13). Please update to one of these builds and report if the problem is still present.
