### ISSUE TITLE
GrinCuckatoo31 NBminer

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner#1706]
Hi
I am getting very bad hashrates with the latest nicehash version. I moved over to the new platform yesterday and installed the new software. Now on GrinCukatoo31 NBminer I am only getting 0.568G/s where I used to get 1.4G/s. GTX 1080Ti Founders edition.
Is there something I should change or should I rather go back to the old nicehash?

**Comment by Johann1982** [comment]
When I run NiceHash Miner Legacy v1.9.0.20 with GrinCuckatoo31 I get 1.440 G/s. I even tried copying the NBminer from 3rd party folder to the new nicehash NBminer folder. For some reason nhm 1.9.2.10 only gets around 0.5 G/s. Something in the new nicehash does not work properly.

**Comment by S74nk0** [comment]
@Johann1982 can you please try [1.9.1.10](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.10) and report back the performance. [1.9.1.10](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.10) runs on the old platform as well.

**Comment by Johann1982** [comment]
@S74nk0 I have tried 1.9.1.10 and it also gives very low hashrates with NBminer GrinCuckatoo31. Legacy 1.9.0.20 runs at full hashrate of 1.4G/s

**Comment by S74nk0** [comment]
@Johann1982 is this your primary GPU?

**Comment by Johann1982** [comment]
@S74nk0 No, I use the Intel HD Onboard plugged into my monitor as I sometimes use the pc for other work. Mining makes everything sluggish. The 1080ti is running on its own. Yesterday I did connect the monitor to the 1080ti and disabled the onboard to test, but that didn't make any difference.

**Comment by S74nk0** [comment]
@Johann1982 please send the logs of 1.9.1.10 or 1.9.2.10 when running NBMiner.

**Comment by Johann1982** [comment]
@S74nk0 
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3457569/log.txt)

**Comment by S74nk0** [comment]
@Johann1982 The start command looks good. I will test 1.9.1.10 and 1.9.0.22 side by side with the 1080Ti and check if I can reproduce this I will be using the same miner binaries.

Does the performance drop if you are mining with 1.9.0.22 and have 1.9.1.10 opened?

**Comment by Johann1982** [comment]
@S74nk0 Funny enough, my other pc with a Zotac 1080ti runs fine with the new nicehash. It is just my founders edition one that does not like the new nicehash.
Checked just now, performance stays the same when I open 1.9.2.10
