### ISSUE TITLE
Add Phoenix 4.5c

### ISSUE THREAD

**Issue by PrinceOfParallax** [nicehash/NiceHashMiner#1707]
New version is out and appears to support the algos better.

**Comment by luc1an24** [comment]
Hi @PrinceOfParallax 
Could you please give me a link to the miner?
The latest Phoenix miner I heard about is 4.5c, which is already added in [1.9.2.11](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.2.11/nhm_windows_1.9.2.11.zip) version.

**Comment by PrinceOfParallax** [comment]
You are correct I was still on .10 - miner dint alert me a newer version was out.
