### ISSUE TITLE
Please stop old platform support!

### ISSUE THREAD

**Issue by GOSEF** [nicehash/NiceHashMiner#1709]
Please make a release of FINAL "old platform".
Concentrate on "new" one. Every day have to check which platform is more profitable...
PS. Whether it makes sense to wait for Nicehash client for HiveOS?

**Comment by luc1an24** [comment]
As Andrej [stated](https://www.reddit.com/r/NiceHash/comments/cmo8ft/when_is_old_nicehash_being_shut_down_current/ew3nnxb/) the transition is planned to be completed in the first week of September.
Please stay tuned on our social channels for live updates.

NiceHashOS is already available to be downloaded from the [new platform](https://www.nicehash.com/)

If you have any additional questions/requests please reopen the issue or create a new one.
