### ISSUE TITLE
Feature Request: add SRBMiner for Cryptonight R (Vega 56)

### ISSUE THREAD

**Issue by dhonasan** [nicehash/NiceHashMiner#1710]
Please add SRBMiner as it has lower mining fees than teamredminer and significantly faster in my case.
SRBMiner: https://bitcointalk.org/index.php?topic=3167363.0

**Comment by luc1an24** [comment]
Hi @davidhonasan 
The addition of SRBMiner is already in progress but is currently on pause
I hope it will be added soon.
