### ISSUE TITLE
1.9.2.10 mining but not appearing on website

### ISSUE THREAD

**Issue by yearight** [nicehash/NiceHashMiner#1711]
Gminer in this case, in the "user" part of the mining window doesn't add my "worker name" to the address like it did before. My mining address is there and correct, but the is a bunch of jibberish after and not my rig name.
Eg. user: "mining address"."worker name"
It looks right in the json file. I am mining to an external wallet.

Do I have to mine to the new address then transfer it to my external ones?
If so, what about my old repayment program balances?

[log.txt](https://github.com/nicehash/NiceHashMiner/files/3473640/log.txt)

**Comment by luc1an24** [comment]
Hi @yearight
To see your mining rig on the new dashboard (new.nicehash.com) you will have to mine on the internal address. Dashboard only support address of registered users (internal address) so if you mine to external address it won't be shown there.

The old balance will be transferred to the new system.
Please read the following post:
https://blog.nicehash.com/post/new-nicehash-platform-now-live-updates
