### ISSUE TITLE
1.9.2.11 will not start

### ISSUE THREAD

**Issue by WyvernZ** [nicehash/NiceHashMiner#1712]
After downloading and making sure nothing goes to quarantine the application request's acceptance to terms and conditions but afterward will close down and nothing will happen. I've checked that nothing is being blocked, the legacy miner is closed down and the system is restarted and the application is opened as administrator. But I everything stops at after the acceptance of terms.

**Comment by luc1an24** [comment]
Hi @WyvernZ 
Could you please provide us with the logs?
Thank you very much!

**Comment by ags167** [comment]
I got same issue...
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3486294/log.txt)

**Comment by luc1an24** [comment]
Hi @ags167
According to your log `nhm_windows_1.9.2.11\translations.json` file is missing.
Could you please retry downloading NHM and whitelisting it in the anti-virus?
Please inform me of your success!

**Comment by ags167** [comment]
found the issue. When launching nhm avast antivirus moved many of the files into quarantine and when moving them back it didnt always take the parent folder with it so to fix this i downloaded nhm and launched it. got antivirus to move the files back. then downloaded nhm again without opening it and merged the two folders so the missing files where back. This solved the problem for me

**Comment by luc1an24** [comment]
Good to hear that.
Closing the issue, solved.
