### ISSUE TITLE
error in cudaprogram.cu 173 out of memory

### ISSUE THREAD

**Issue by vasy701** [nicehash/NiceHashMiner#1715]
What could be a cuda error in cudaprogram.cu 173 out of memory 4 gb card? 16 operational, 48 virtual memory.

==
Что может быть, ошибка cuda error in cudaprogram.cu 173 out of memory карты 4 гб? 16 оперативной, 48 виртуальной памяти.

![2019-08-09](https://user-images.githubusercontent.com/53948065/62793969-573a5680-baec-11e9-8ffd-1eb84f35cdfa.png)
![2019-08-09 (2)](https://user-images.githubusercontent.com/53948065/62794045-805ae700-baec-11e9-89a9-69eececde436.png)

**Comment by vasy701** [comment]
A similar story, in the new version of nhm_windows_1.9.2.10, they threw a miner with a virus there, it miners profit coins unnoticed with you, it creates a rig (Sneezy_f731df86 - Unmanaged rig) it is visible in the new version of Nice's website, and since he is trying load a dag file into a 4 gb card an error occurs, the memory is not rubber.
switched to the old version, it’s stable there, I’ll test.
![image](https://user-images.githubusercontent.com/53948065/62821008-bfd61180-bb86-11e9-8ce7-59a65659bb5d.png)


==

Примерно такая история , в новой версии nhm_windows_1.9.2.10, туда они закинули майнер с вирусом он майнит профитные монеты незаметно вместе с тобой, он создает риг (Sneezy_f731df86 - Unmanaged rig) его видно в новой версии сайта Найса, а так как он пытается загрузить в 4 гб карту свой даг файл происходит ошибка, память ведь не резиновая.
перешел на старую версию, там стабильно вроде, буду тестить.

**Comment by luc1an24** [comment]
Hi @vasy701 
Thank you for reaching out.
DaggerHashimoto needs at least 3GB of free active memory. Windows 10 takes quite a lot of memory from card which can cause memory shortage.
Try to disable DaggerHashimoto and use other algorithms that doesn't need that much memory.
You could also try and install windows 7 which doesn't use that much of gpu memory.
Please tell me if there is something else I can help you with.

**Comment by vasy701** [comment]
I took the Phoenix folder with nhm_windows_1.9.1.7 and replaced it with nhm_windows_1.9.2.10 - the problem disappeared !!!

The Phoenixn hm_windows_1.9.2.10 folder is a virus that did not allow mining !!

Взял папку Phoenix с nhm_windows_1.9.1.7 и заменил её в nhm_windows_1.9.2.10 -- проблемма исчезла!!! 

Папка Phoenixn hm_windows_1.9.2.10 - это вирус который не давал майнить!!

**Comment by luc1an24** [comment]
The Phoenix folder from 1.9.1.7 is same as the one that comes with 1.9.2.10
So there should be no difference. 
Also their sha hash is same.

Phoenix miner was updated in 1.9.2.11

Are you mining to new platform address with 1.9.2.x version of NHM? If not this is the reason for "Unmanaged rig". Also mining directly with miner will cause "Unmanaged rig".

If you still experience issues please tell me.

**Comment by vasy701** [comment]
IMPORTANT! Versions of PhoenixMiner prior to 4.2 support only the DAG era up to 265. Both ETC and ETH have already reached the 266 era. To ensure smooth operation, please upgrade to 4.5

ВАЖНО! Версии PhoenixMiner до 4.2 поддерживают только DAG эпоху вплоть до 265. И ETC, и ETH уже достигли эпохи 266. Чтобы обеспечить бесперебойную работу, пожалуйста, обновите программу до 4.5

**Comment by vasy701** [comment]
Checked PhoenixMiner 4.5 the same error, returned with PhoenixMiner 4.2 with 1.9.1.7

Проверил PhoenixMiner 4.5 ошибка такая же, вернул с  PhoenixMiner 4.2 с 1.9.1.7

**Comment by Twigho** [comment]
Hi, 
Did you try with the option "-gser 0" or 1 maybe

**Comment by vasy701** [comment]
I tried PhoenixMiner 4.5 -gser 0 and 1, the error remained, right now, in general, the minuscule yield on the Air is ridiculous and does not drip because of this))

![2019-08-13](https://user-images.githubusercontent.com/53948065/62935506-c1027b00-bde0-11e9-9b7d-54b23c3a81d1.png)


Пробовал PhoenixMiner 4.5 -gser 0 и 1, ошибка осталась, щас вообще, смешно минусовая доходность на Эфире и не капает из за этого))

**Comment by luc1an24** [comment]
The negative profitability is our issue and we are already fixing it.
This is only visual bug and you are still awarded for your shares.
You can check NiceHash dashboard and you will see that you are being awarded for your work.

*EDIT* Negative profitability is fixed

**Comment by Twigho** [comment]
umm, sorry i realize that you said an error. I wanted you to try "-gser 2". (To be specified for each card)
And a second thing:
- Be sure to turn off Afterburn. (You can OC with "-powlim -20 -cclock +100 -mclock +950")
And can you try "-mode 1 -clKernel 1 -lidag 3 -gser 2 -nvf 0"
"gser 2" option will load the DAG one by one. This is slower but more stable.

**Comment by Seaninnh** [comment]
Did this just get completely overlooked? WHAT VIRUS and how do we remove it? I did see this Sneezy window open at one point.

"A similar story, in the new version of nhm_windows_1.9.2.10, they threw a miner with a virus there, it miners profit coins unnoticed with you, it creates a rig (Sneezy_f731df86 - Unmanaged rig) it is visible in the new version of Nice's website"

**Comment by vasy701** [comment]
went to the pool, I’ll sit there, it’s unrealistic to catch glitches for a week, why there are none)

![2019-08-17 (1)](https://user-images.githubusercontent.com/53948065/63214101-6ee98e80-c12d-11e9-998d-a1244f9c03c8.png)



ушел на пул, посижу там, нереально ловить глюки неделю, там почему их нет)

**Comment by Twigho** [comment]
Yep, NHM looks like shifting sands...

**Comment by vasy701** [comment]
It seems that I found a cant in myself. The Asus GeForce GTX 1050 Ti video card does not want to work on the Phoenix miner, and an error occurs for it, I will figure it out further.

Вроде нашел косяк у себя Видеокарта Asus GeForce GTX 1050 Ti не хочет на майнере Phoenix работать, и за нее ошибка возникает, буду думать дальше.

**Comment by vasy701** [comment]
Installed, fixed launch error nhm_windows_1.9.2.12) while plowing, working, I will observe)

Установил, исправил ошибку запуска nhm_windows_1.9.2.12) пока пашет, работает, буду наблюдать)

![2019-08-19](https://user-images.githubusercontent.com/53948065/63240885-10c2c580-c26b-11e9-954b-c643128309b9.png)

**Comment by zahar12342** [comment]
![IMG_20210325_193927](https://user-images.githubusercontent.com/81379000/112510025-17e47a80-8da2-11eb-92eb-2336a6d9b9c2.jpg)
Подскажите как решить пожалуйста

**Comment by vasy701** [comment]
все, эфир не майнит, майни другую монету

  
>Четверг, 25 марта 2021, 19:42 +03:00 от zahar12342 ***@***.***>:
> 
> 
>
>Подскажите как решить пожалуйста
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Василий Рыженьков
