### ISSUE TITLE
set temp. limit

### ISSUE THREAD

**Issue by theptipteacharsripaitoon** [nicehash/NiceHashMiner#1716]
How can i set temperature and intensity of nhm 1.9.2.11.  Last version I still can set maximum temp by using MSI afterburn.

**Comment by luc1an24** [comment]
Hi @tham2539 
Thank you for reaching out.
You can do that on miner basis with [Extra Launch Parameters](https://github.com/nicehash/NiceHashMiner/blob/master/doc/ExtraLaunchParameters.md).

You can also enable Device Power Mode settings inside NiceHash Miner -> Settings -> Advanced -> uncheck `Disable Device Power Mode Settings`. This will allow NHM to set Power Modes.

But if you wan't to manually set both temp and intensity then Extra Launch Parameters are the right way to go.

**Comment by Twigho** [comment]
Salut tham2539
For extra launch parameters, you can look in your NHM / miner_plugins / "miner_name" / bins folder, you will see a readme file with the commands listed.
Good luck!

**Comment by theptipteacharsripaitoon** [comment]
I already change "use_user_settings": false to true. But the temperature still above in my afterburn.
And where can i set the temperature. I'm new here.

**Comment by Twigho** [comment]
I told you to add the temperature via Extra Launch Parameters. (settings / Devicesalgorithms / your gpu / an_algorithm and on the right bottom you have Extra parameters)
For example: For NbMiner the command is "-t 80" for the temp limit (here 80deg). or NBMiner is "-temperature-limit 80" or something like that. This varies according to the Miners. But the commands are written in their readme.
You have to write them for each gpu and for each algo ...: /
The new platform hates Afterburn ... Maybe a kernel love story ...
