### ISSUE TITLE
Language is switching after every 'Save and close'

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#1718]
Preconditions: NHM v1.9.2.11

1) Open Settings and set Russian language (or anything else apart from English)
2) Click on 'Save and close'
3) Open Settings window once more
4) Click on 'Save and close' (w/o changing UI language)

Result: UI is partially in English.
Expected result: UI is still in Russian.

Here is a short video of such behaviour: https://youtu.be/VbnjKRnrFIg

**Comment by luc1an24** [comment]
Thank you for reporting this bug.
It is similar to the #1719 and we will fix them in a batch.
