### ISSUE TITLE
Right click tray menu entries aren't translateable

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#1719]
**Preconditions:** NHM v1.9.2.11, 'Minimize to tray' is enabled

1) Minimize NHM window
2) Perform right mouse click on the tray icon

**Result:** Untranslateble 'Show' and 'Quit'
**Expected result:** 'Show' and 'Quit' are available for translation via `translations.json`

Screenshot:
![image](https://user-images.githubusercontent.com/4707112/62867244-e8dfd900-bd23-11e9-9413-cbaefef2101b.png)

**Comment by luc1an24** [comment]
Thank you for reporting that bug
We will add it to our backlog and fix it as soon as possible.

**Comment by adem4ik** [comment]
The issue isn't fixed in 1.9.2.13. Steps:

1) Add those strings into `translations.json`
`    "Show": {`
`      "ru": "Показать",`
`    },`
`    "Quit": {`
`      "ru": "Выход",`
`    },`
2) Switch UI language to Russian
3) Enable `Minimize to tray`
4) Minimize NHM window
5) Perform right mouse click on the tray icon

**Comment by adem4ik** [comment]
I think this issue was closed by mistake, it isn't fixed yet in 1.9.2.14.

**Comment by adem4ik** [comment]
@S74nk0 May be it is better to remove "Close on next release" flag until it's gonna be fixed?
