### ISSUE TITLE
Issue with Asus Stix GTX 970 for dagger hashimoto algorithm

### ISSUE THREAD

**Issue by crypto-miner** [nicehash/NiceHashMiner#172]
Hi,

i am using asus stix gtx 970 graphic card for dagger hashimoto algorithm. after benchmark for me its getting around 4.5 Mh/s but in some forums and in nicehash profitability calculator for dagger hashimoto  its showing around 22 Mh/s. as i tried with new drivers and also with cd drivers. but still getting same issue. plz help me how to resolve the issue.

**Comment by nicehashdev** [comment]
Unfortunately, due to limitations of WDDM on Windows 10, DaggerHashimoto is limited in performance to about the speed you are stating. If you wish to mine Dagger with full speed using Windows, then you have to use Windows 8 or Windows 7.
