### ISSUE TITLE
It freezes at the start of 1.9.2.11 Зависает при старте 1.9.2.11

### ISSUE THREAD

**Issue by vasy701** [nicehash/NiceHashMiner#1720]
It freezes at the start of 1.9.2.11 and then after 2 minutes it starts and freezes.

![2019-08-12](https://user-images.githubusercontent.com/53948065/62869685-be951800-bd31-11e9-8ecb-38deb29c5e92.png)
![2019-08-12 (1)](https://user-images.githubusercontent.com/53948065/62869698-c48af900-bd31-11e9-8f60-07ffafc3e49b.png)

[log.txt](https://github.com/nicehash/NiceHashMiner/files/3492756/log.txt)

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3492757/log.1.txt)

Зависает при старте 1.9.2.11 и потом через 2 минуты запускается и зависает.

**Comment by luc1an24** [comment]
Hi @vasy701 
Thank you for reporting this bug.
Because it was already reported I will close this issue.
Please follow the original post for any bug fix related information.
Closing, duplicate #1704
