### ISSUE TITLE
SGminerAvemore returning payout negative btc Nicehash 1.9.2.11

### ISSUE THREAD

**Issue by muratia** [nicehash/NiceHashMiner#1721]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by Twigho** [comment]
Idem with Phoenix miner, when I use extra launch and disable power gestion option is cheched. But considering the website it seems ok.
![IMG_20190813_030042 1](https://user-images.githubusercontent.com/52711806/62909395-bc0be000-bd7c-11e9-9d7f-6a6fe197f255.jpg)

**Comment by luc1an24** [comment]
Hi @Twigho and @muratia 
Could you tell me more about how to get negative rate?
What extra launch parameters do you use?
Do you use "Electrical cost"?

Thank you for your feedback!

It would be also helpful if you could provide me with logs

**Comment by muratia** [comment]
In Settings of the Nicehash app electric cost is 0.000 because I do not pay electric bill so still it calculating negative btc. While XmrStack is running normal

**Comment by muratia** [comment]
I checked from version 1.9.2.6 till 1.9.2.9 all do return negative rate at SgminerAvemore.

**Comment by luc1an24** [comment]
Could you send me logs?

**Comment by muratia** [comment]
[2019-08-13 10:21:01] [INFO] [MiningManager] Current device profits:
	Profits for CPU-5ff98139-fb34-57c3-8130-0043b2b60a4b (CPU#1 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz):
		PROFIT = 0.000001304084	(SPEED = 3.15000e+001		| NHSMA = 4.13995e+001)	[CryptoNightR_XmrStak]
		MOST PROFITABLE ALGO: CryptoNightR_XmrStak, PROFIT: 0.000001304084

	Profits for AMD-dcdca391-d9f2-5340-bb4d-6202c922a78c (AMD#1 AMD Radeon R5 M200 Series (pcie 9)):
		PROFIT = -0.000004009217	(SPEED = 4.15100e+005		| NHSMA = -9.65844e-003)	[X16R_SGminerAvemore]
		MOST PROFITABLE ALGO: X16R_SGminerAvemore, PROFIT: -0.000004009217

**Comment by muratia** [comment]
Yesterday I did precise benchmark and nothing changed

**Comment by luc1an24** [comment]
We have some problems with NHSMA value of X16R and DaggerHashimoto.
We are trying to fix them. In the mean time don't worry, your hashes are being paid.
Thank you for your patience!

**Comment by Twigho** [comment]
It works now ! thx

**Comment by luc1an24** [comment]
@muratia @Twigho This bug is fixed.
Please check and reopen the issue if the bug is still present.
Closing, fixed.

**Comment by muratia** [comment]
Let me check again because I was doing something with the laptop

**Comment by muratia** [comment]
It is fine now.
