### ISSUE TITLE
"Unable to generate NiceHash Miner rig ientifier"

### ISSUE THREAD

**Issue by cerberus69** [nicehash/NiceHashMiner#1723]
Good Morning to All,

I am new to this world and would like to introduce myself as someone trying to setup a basic CPU+GPU based miner using the NiceHash OS. I have downloaded the OS and it is installed onto a bootable USB memory stick, I have also amended the configuration file with my details.

When I boot from the USB stick I get the following message and then the login screen comes up in red text:

"Unable to generate NiceHash Miner rig identifier!"

Can anyone help, please go easy with me, this might be a simple fix

**Comment by luc1an24** [comment]
Hi @cerberus69 
Thank you for reaching out. This repository is used for NiceHash Miner, so we can't help you.
If you need help about NHOS please contact our support team: support@nicehash.com

If you will need any help with NHM in the feature feel free to open a new issue.
Closing, not related to NHM.
