### ISSUE TITLE
Updating nicehash Обновление nicehash

### ISSUE THREAD

**Issue by vasy701** [nicehash/NiceHashMiner#1724]
Do a nicehash update through the program itself, and not through the site? tired already download archives 100 times)

Сделайте обновление nicehash через саму программу, а не через сайт? устал уже 100 раз архивы скачивать)

**Comment by grichter** [comment]
So write a management script to auto update your rigs.. :p

**Comment by S74nk0** [comment]
We will add the [installer](https://github.com/nicehash/NiceHashMiner/tree/master/installer) with the next upcoming release and future releases. The zip packages will work as they work now. Installations via the installer will use the updater when the new version is available. At first user intervention (click on the GUI button) will be required. We will probably introduce an option for complete auto-updates. 

We will close this issue with the next release.

**Comment by S74nk0** [comment]
new version is released. Closing
