### ISSUE TITLE
Different column names "Temp (°C)" vs "Temp (C)"

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#1728]
NHM v1.9.2.12

1) Start mining

Result: Device list has the column `Temp (°C)`, while Algorithms' list shows `Temp (C)`
Expected result: Device list and Algorithms' list show the same column name `Temp (°C)`.

![image](https://user-images.githubusercontent.com/4707112/63120870-412d0a00-bfb4-11e9-8ce6-a826dc97c21d.png)

**Comment by luc1an24** [comment]
Hi @adem4ik 
Thank you for reporting this bug.
It is already fixed and will be released with the new version of NHM.
Leave open until new release.
