### ISSUE TITLE
xmr-stak-cpu has been updated

### ISSUE THREAD

**Issue by streaml1ne555** [nicehash/NiceHashMiner#173]
Not so much an issue as an improvement request: 

https://github.com/fireice-uk/xmr-stak-cpu/releases

Lists some minor performance improvements. Not sure what version is integrated with NHML, but it does not list a version number which the newest version does. This yields about 7-8 H/s better performance on my Ryzen 1700x

**Comment by 3zero2** [comment]
@streaml1ne555 I guess you can just download the new version and replace the binary.

**Comment by streaml1ne555** [comment]
Tried that, does not work because there are new variables and for whatever reason NHML overwrites the config file every time you start it.

**Comment by ChriscomIT** [comment]
Yeah overwriting the config file is just how NHML works as it has its own config for that. @DillonN will probably look into this and update. I would also be super happy to see the new version as I am mining on CPU as well.

**Comment by SaintPistachio** [comment]
Why are the gpu miners for xmr not used in nicehash?

**Comment by streaml1ne555** [comment]
DillonN is looking into adding the pascal version. There is another issue listed here with the GPU CryptoNight stuff in it.

**Comment by DillonN** [comment]
xmr-stak-cpu has been deprecated and replaced with xmr-stak
