### ISSUE TITLE
No stats foe BeamV2 (LolMiner) in V 1.9.2.12

### ISSUE THREAD

**Issue by Maui73** [nicehash/NiceHashMiner#1731]
Hi,

i missed the mining-stats for the BeamV2 on LolMiner in V 1.9.2.12 (see screenshot).

greatings, Maui

![NHM](https://user-images.githubusercontent.com/54157942/63132929-244c0300-bfc3-11e9-8457-2501ba03ba85.jpg)

**Comment by luc1an24** [comment]
Hi @Maui73 
Thank you for reaching out.
If you wait a little bit do speeds display or stay 0?
Also is GMiner (Beam2) having the same problems?
Thank you for your help.

**Comment by Maui73** [comment]
Hi luc1an24,

 

the display stand 0.

 

 

With GMiner the speed is showing (but i had no benchmark results in my first benchmark-test - precise, all algorithm - in reason of this i had used the LolMiner ...)

 

Thank you,

 

Maui


Gesendet: Freitag, 16. August 2019 um 09:11 Uhr
Von: "luc1an24" <notifications@github.com>
An: nicehash/NiceHashMiner <NiceHashMiner@noreply.github.com>
Cc: Maui73 <schens@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [nicehash/NiceHashMiner] No stats foe BeamV2 (LolMiner) in V 1.9.2.12 (#1731)


Hi @Maui73
Thank you for reaching out.
If you wait a little bit do speeds display or stay 0?
Also is GMiner (Beam2) having the same problems?
Thank you for your help.

**Comment by luc1an24** [comment]
Interesting.
Could you please send me the logs?
The LolMiner API data receiving was fixed with that release so there shouldn't be any 0's shown.
Thank you for your help.

**Comment by Maui73** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3527563/log.txt)
Hi luc1an24,

here are the logfiles you need ...

Thanks

**Comment by Maui73** [comment]
![LolMiner](https://user-images.githubusercontent.com/54157942/63898396-2073a400-c9f9-11e9-9d61-e3909abe334e.jpg)
Hi luc1an24,

in V 1.9.2.13 the stats are shown for LolMiner ... i close this ticket.

thanx, Maui
