### ISSUE TITLE
Stuck on initializing device monitoring (1.9.2.11 and 1.9.2.12)

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1732]
On NHM 1.9.2.11 and 1.9.2.12 my 6 GPU rig of both AMD and Nvidia cards will get stuck on initializing device monitoring and freeze. 1.9.2.10 and earlier versions works fine. Happy to send logs if needed as I hope it can get sorted out ASAP so I can use the newer miners.

**Comment by luc1an24** [comment]
Hi @mcatley 
Thank you for reporting this bug.
I think that you are referencing to the one already reported in #1704 but I would like to see your logs as well.
Thank you for your help!

**Comment by ghost** [comment]
Ok, do you suggest I mine directly using GMiner to Nicehash stratums as I mine currencies like Beam which now don't work on the older miner? Can I send the logs to an email or do they not contain personal info?

**Comment by luc1an24** [comment]
If you would like to miner the new Beam then mine directly if you are experiencing freeze.
We will probably fix this issue next week but can't say for sure.
Logs contain your BTC address. If you worry about that then send them to domen.kirnkrefl@nicehash.com otherwise you can post them here.

**Comment by ghost** [comment]
I emailed them. Thanks

**Comment by luc1an24** [comment]
Same issue as #1704 
Closing issue, duplicated.
Follow #1704  for fix info.
