### ISSUE TITLE
the nicehash miner 1.9.2.12 and also 11 not communicating to site 

### ISSUE THREAD

**Issue by regchanuk** [nicehash/NiceHashMiner#1734]
ok the nicehash miner 1.9.2.12 and also 11 not communicating to site seems to say my miner is offline all the time now not sure but its mining away as i see it please does any one have any issues with this please

**Comment by regchanuk** [comment]
im now on latest version not sure if site is slow or slowing down

**Comment by hpalex** [comment]
I have the same problem - mining is active, but dashboard indicates that there are NO active rigs - NHM 1.9.2.12

**Comment by regchanuk** [comment]
as far as i can tell its the whole site  having problems i was running vesion 11 previously before i checked for update today
i was only 3 days behind

**Comment by regchanuk** [comment]
ok not sure if site was under mantanace or lagging behind seems like site is working as its should after a while

**Comment by mikepred** [comment]
This has nothing to do between the interaction of the site and the local application. I am only referring to the window showing the details in GUI of the local application.

**Comment by luc1an24** [comment]
Hi @regchanuk and @hpalex 
Thank you for reporting this.
It was indeed issue on our site but it is fixed now.

If you continue experiencing this issue please contact our support team: support@nicehash.com

Closing, fixed/not related to NHM.
