### ISSUE TITLE
Power Settings No Permission.

### ISSUE THREAD

**Issue by ahelguerrero** [nicehash/NiceHashMiner#1735]
I can't seem to adjust the power because I have no permission.
Here are the logs.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3512353/log.txt)

**Comment by luc1an24** [comment]
Hi @ahelguerrero
Thank you for reaching out.
To set power mode for NVIDIA cards you have to run NHM as admin (elevated permissions).
If you have done so and still experience issues please tell us.

Have a nice mining!

**Comment by ahelguerrero** [comment]
Yeet. It works now.
