### ISSUE TITLE
Rig Details Disappear When Clicking "Check my stats online"

### ISSUE THREAD

**Issue by mikepred** [nicehash/NiceHashMiner#1736]
When I click on "Check my stats online!" -> The bottom half of the window showing rig details disappears. I have to click on the same link again which sometimes shows the bottom half again, but not always. Doesn't seem consistent.

**Comment by regchanuk** [comment]
check my report below https://github.com/nicehash/NiceHashMiner/issues/1734

**Comment by regchanuk** [comment]
for me it shows offline and disappears

**Comment by mikepred** [comment]
I am only referring to the GUI. When I click on the link to check my stats, which opens website, the Hash GUI drops the rig details outside of view. The only way I can make it be seen again is by clicking on that same hyperlink - sometimes more than once.

**Comment by regchanuk** [comment]
hmm i think its related but cant tell i seen somthing similar but oh well my info never showed untill it  came online

**Comment by mikepred** [comment]
This is only in reference to the standalone GUI application. The website shows the rig as active, that is not the issue. The details of hashrate/etc within the GUI disappears when I click on the link to open the website. Sometimes if I click the link again, then the window re-appears. This is 100% within the standalone application.

**Comment by regchanuk** [comment]
ok no robs now they are under maintanace on their site

**Comment by luc1an24** [comment]
Hi @mikepred 
Thank you for reaching out.
Could you tell me a little bit more about this problem.
Which version of NHM are you using.
In which state is the application when this happens (minning, benchmarking, stopped)?
If you have any steps on how to reproduce this issue please tell me since I am unable to do it on my own.

Thank you for your help!

**Comment by mikepred** [comment]
1.9.2.12. Doesn't matter if running or stopped. Not in benchmark mode.  The GUI is typically split in half, the top half shows the enabled/disabled devices. The bottom half shows the details of the coin mined. When I click on "Check my stats online!" -> the bottom half of the GUI disappears but the application continues to function. If I click on the same hyperlink again, opening another browser window, sometimes the bottom half window re-appears.

**Comment by mikepred** [comment]
Issue continues to persist on v1.9.2.19. If I click on "Check my stats online!" -> I lose visibility of the rig details in the bottom half of the GUI. Does anyone else not experience this?

**Comment by Mortuus-Medicus** [comment]
![image](https://user-images.githubusercontent.com/10358658/72889831-e17c1d00-3d10-11ea-8a6c-5f5e48cedfe1.png)

Same issue here, I pressed "Check my stats online!" and the bottom part where you can see additional stats disappeared.

EDIT: I'm running version v1.9.2.21
