### ISSUE TITLE
Earnings down?

### ISSUE THREAD

**Issue by Seaninnh** [nicehash/NiceHashMiner#1737]
My earnings have dropped significantly in the past 3 weeks. I am running 3 rigs with 2 GPUs each, totaling 9 devices mining. I was making more than 0.00002000 closer to 0.00003000 per deposit. 

Now I'm lucky to make 0.00001500.

Is this a bug or is this by design? It doesn't seem worth the electricity at this point.

**Comment by grichter** [comment]
Sadly that's just the way the market crumbles sometimes. Especially with things like Litecoin recently hitting a halving point, nicehash moving over to a new platform and buyers not following very quickly,  and of course, international political uncertainties particularly around crypto currency regulations.

**Comment by luc1an24** [comment]
Hi @Seaninnh 
Thank you for reaching out.
We are unable to influence your earnings, only buyers can.
As @grichter said, there are a lot of variables why earnings can go down or up.

Again thank you for reaching out and I hope we answered your question.

Closing, not related to NHM.
