### ISSUE TITLE
Multi set for launch parameters

### ISSUE THREAD

**Issue by HyperCriSiS** [nicehash/NiceHashMiner#174]
Hi,

can you please add the possibility to set the launch parameters for several GPUs at once?

Thanks and regards,
Hyper

**Comment by drkskwlkr** [comment]
@HyperCriSiS You can easily do that yourself by copy/pasting the settings for one miner to all others. These are stored inside the `configs/` subfolder as separate `.json` files prefixed as `benchmark_GPU-`.

Each benchmark file has a separate section for every miner, and inside there is a `ExtraLaunchParameters` line which you can replicate. If your GPUs are identical, you can save time by copy/pasting across all relevant files the entire contents of the file for the GPU you've configured by hand except `DeviceUUID`.
