### ISSUE TITLE
P106-100 Support?

### ISSUE THREAD

**Issue by daemon6** [nicehash/NiceHashMiner#1746]
When I try to mine with my Asus P106-100 (on versions after 1.9.0.23) it repeatedly opens up mining windows one right after another. As stated, it does this on all versions after 1.9.0.23 and it works fine on that version. Multiple drivers have been tried to no avail. Using latest drivers presently. Can any help be given on this issue? -Thx

**Comment by github12101** [comment]
Screenshot?
Logs?
