### ISSUE TITLE
Auto mining not working NHM v1.9.2.12

### ISSUE THREAD

**Issue by shaneo257** [nicehash/NiceHashMiner#1753]
Hi Team,

I'm currently experiencing an issue where the auto start whilst idle is not working on NHM v1.9.2.12.

I have tried to change the settings to start after no input, or when my computer is locked, and it doesn't work.

**Comment by CDrosos** [comment]
I have the same problem too

**Comment by CDrosos** [comment]
In the latest version is working again for me. I have use the installer version to install it. Previously i had the application folder on the windows documents folder, maybe this was creating the problem

**Comment by scscgit** [comment]
I also tried to use the "Start Mining When Idle with the default "Input Timeout" of 60s, and it didn't start for the entire day. Was this feature even tested? And why can't you add some sort of count-down on the GUI, so that we get the immediate feedback? :)

**Comment by CDrosos** [comment]
I think i have find what is going on, if you press save settings the auto start mining works, if you restart then it doesnt work until you save them again, and it happens in all versions. 1.9.2.16 doesnt work
