### ISSUE TITLE
Please add MTP algorithm on the new platform

### ISSUE THREAD

**Issue by EVGENY1777** [nicehash/NiceHashMiner#1756]
Hello! Please add MTP algorithm on the new platform. With respect.
P.S. And do, please, normal hashrate on DaggerHashimoto+Keccak instead of 10 MH on Clamore Dual

**Comment by vanmald** [comment]
Bump.  I have been mining outside of Nicehash to continue mining MTP.  As a workaround, is it possible to use the Nicehash wallet (BTC) and mine using 2miners.com NH pool using a 3rd party miner like TRex?  Doing this, will BTC be deposited into the NH BTC wallet?
