### ISSUE TITLE
XMRig mines disabled CPU when supposed to be mining GPU

### ISSUE THREAD

**Issue by damonlynch** [nicehash/NiceHashMiner#1758]
**NHM version 1.9.2.12
XMRig plugin 1.1**
_Windows 10 1903 64 bit with latest updates
Ryzen 3900X,  32 GB RAM, 1080 Ti, 1070._

I had _disabled_ mining on my CPU (but I had previously benchmarked the CPU). Yesterday I updated some plug-ins on NHM 1.9.2.12. XMRig may have been one of them (I don't recall).

NHM chose to mine XMRig CryptoNightR on the 1070, which then started mining on the CPU, leaving the 1070 idle. Attached is a screenshot exhibiting the behaviour today:
![NHM-bug-2019-08-27-112127](https://user-images.githubusercontent.com/1749868/63784890-59a6f980-c8bd-11e9-9c4d-3fa77a16d0d7.png)

Upon noticing this (hard not to when your CPU is suddenly running at 100%!) I enabled CPU mining overnight. However, NHM would still select the 1070 to mine XMRig CryptoNightR, which would again mean the CPU would mine XMRig CryptoNightR and the 1070 would be idle.

So I tried to disable XMRig CryptoNightR on the 1070, but this would also immediately disable it on the CPU too.

Enabling both the CPU mining and XMRig CryptoNightR will result in XMRig CryptoNightR being counted as earning twice what it really is (once for the 1070, and once for the CPU). See attached screenshot:
![NHM-bug-2019-08-27-111853](https://user-images.githubusercontent.com/1749868/63784390-945c6200-c8bc-11e9-928e-d0502219361e.png)

As an aside, with CPU mining enabled and XMRig CryptoNightR  disabled, the CPU will happily mine XmrStak, and the 1080 Ti and 1070 will mine as expected.

Attached are the log files with NHM in different configurations regarding what is enabled / disabled.
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3546943/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3546944/log.txt)

**Comment by luc1an24** [comment]
Hi @damonlynch
Thank you for reporting this bug.
It is fixed now, so feel free to update **XMRig** plugin.
