### ISSUE TITLE
Please update tpruvot ccminer to latest x86-2.2 version

### ISSUE THREAD

**Issue by man55** [nicehash/NiceHashMiner#176]
This latest version is just wonderful. The highest speed at Skunk algo on 10xx nvidia cards.
And finally, an adequate start on 6+ nvidia card rigs with low/middle-end CPU.

https://github.com/tpruvot/ccminer/releases

Thank you!

**Comment by 3zero2** [comment]
Version 2.2 is what NHML 1.8.1.1pre4 is using.

**Comment by man55** [comment]
Yes, you're right, really.
I understood the reason. I had to delete bin folders before unpacking the new version. Usually I unpack the new version on top of the old one to save all the settings and benchmarks. Otherwise, the NHML does not update the miners.
