### ISSUE TITLE
I can't run nhm_windows_1.9.2.12 in system tray

### ISSUE THREAD

**Issue by Gungking2** [nicehash/NiceHashMiner#1760]
I can't run nhm_windows_1.9.2.12 in system tray
when I check run with windows and min to tray
it not work
because when my windows is start NHM still run on normal
Please Fix it

**Comment by S74nk0** [comment]
@Gungking2 just to be clear you want NiceHash Miner to start minimized when "Minimize To Tray" is enabled? 
Having these two enabled runs nhm on Windows system startup and it minimizes nhm to tray only when close is clicked. It is not intended to start minimized.

**Comment by Gungking2** [comment]
My old verions it can auto run and min to tray

1.9.0.10  


** when I create Nhm short cut (start in min mode) **  uncheck auto run in nhm program
new nhm short cut in start up folder
when my windows start 
nhm run in system tray  but nhm can't start mining (idle mode)

**Comment by S74nk0** [comment]
@Gungking2 can you please send your config file? So again:
  - nhm starts on windows?
  - it is visible?
  - it has idle mining enabled?
  - and you have autostart mining enabled?

**Comment by Gungking2** [comment]
{
  "ConfigFileVersion": {
    "Major": 1,
    "Minor": 9,
    "Build": 2,
    "Revision": 12,
    "MajorRevision": 0,
    "MinorRevision": 12
  },
  "hwid": "0-Z1+JnqEzvlanapozZdEQeQ",
  "agreedWithTOS": 4,
  "SwitchSmaTimeChangeSeconds": {
    "Lower": 34,
    "Upper": 55
  },
  "SwitchSmaTicksStable": {
    "Lower": 2,
    "Upper": 3
  },
  "SwitchSmaTicksUnstable": {
    "Lower": 5,
    "Upper": 13
  },
  "MainFormSize": "1000, 415",
  "Language": "en",
  "DisplayCurrency": "THB",
  "DebugConsole": false,
  "BitcoinAddress": "38AK2L882P9y9fTZTcikfLohFhQaSpYwVZ",
  "WorkerName": "SERVER",
  "TimeUnit": 1,
  "ServiceLocation": 0,
  "AutoStartMining": false,
  "HideMiningWindows": true,
  "MinimizeMiningWindows": true,
  "MinimizeToTray": true,
  "SwitchProfitabilityThreshold": 0.05,
  "MinerAPIQueryInterval": 5,
  "MinerRestartDelayMS": 500,
  "AutoScaleBTCValues": true,
  "StartMiningWhenIdle": true,
  "IdleCheckType": 0,
  "MinIdleSeconds": 10,
  "LogToFile": true,
  "LogMaxFileSize": 1048576,
  "ShowDriverVersionWarning": true,
  "DisableWindowsErrorReporting": true,
  "ShowInternetConnectionWarning": true,
  "NVIDIAP0State": false,
  "ApiBindPortPoolStart": 4000,
  "MinimumProfit": 0.0,
  "MineRegardlessOfProfit": true,
  "IdleWhenNoInternetAccess": true,
  "RunScriptOnCUDA_GPU_Lost": false,
  "AllowMultipleInstances": true,
  "UseIFTTT": false,
  "IFTTTKey": "",
  "Use3rdPartyMiners": 2,
  "CoolDownCheckEnabled": true,
  "KwhPrice": 0.0,
  "UseSmaCache": true,
  "ShowPowerColumns": false,
  "ShowDiagColumns": true,
  "RunFirewallRulesOnStartup": false,
  "UseEthlargement": false,
  "RigGroup": "",
  "RunAtStartup": false,
  "GUIWindowsAlwaysOnTop": false,
  "DisableDeviceStatusMonitoring": false,
  "DisableDevicePowerModeSettings": true,
  "ShowGPUPCIeBusIDs": false
}

**Comment by adinetech** [comment]
Change "RunAtStartup": false, as "RunAtStartup": true,

**Comment by adinetech** [comment]
@Gungking2 Does it helped you ?
