### ISSUE TITLE
"Cancelling per user request." can't be translated

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#1762]
**Preconditions:**
- NHM v1.9.2.13
- translation is presented in **translations.json** as:
`    "Cancelling per user request.": {`
     ` "ru": "Отмена по запросу пользователя."`
 `   },`
- UI is in Russian language 

1. Open "Benchmark" window
2. Press "Start" to start benchmark and then "Stop"

**Result:** `Cancelling per user request.` isn't translated.
**Expected result:** `Cancelling per user request.` is replaced by `Отмена по запросу пользователя.`

![image](https://user-images.githubusercontent.com/4707112/63872483-d4136e80-c9ce-11e9-9219-cbe82ef8fa7b.png)

**Comment by luc1an24** [comment]
Thank you for report.
It will be fixed in the next release.
