### ISSUE TITLE
Some strings aren't shown as translated, while they are presented in translations.json

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#1764]
NHM 1.9.2.13, Russian language

Here is just a list:
1. `Speeds`, translation - https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/translations.json#L2477
![image](https://user-images.githubusercontent.com/4707112/63873746-31102400-c9d1-11e9-97cb-3d03957f6a45.png)

2. `General` - https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/translations.json#L1271 ,
`Advanced` - https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/translations.json#L329 ,
`Devices/Algorithms` - https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/translations.json#L892
![image](https://user-images.githubusercontent.com/4707112/63873896-80eeeb00-c9d1-11e9-866c-2e3f20e6df27.png)

3. `Session Lock` - https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/translations.json#L2276 ,
`Input Timeout` - https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/translations.json#L1466
![image](https://user-images.githubusercontent.com/4707112/63874082-e0e59180-c9d1-11e9-892e-59dbd87a870a.png)

4. `Power usage (W):` - https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/translations.json#L2034 ,
`Extra Launch Parameters` - https://github.com/nicehash/NiceHashMiner/blob/master/src/NiceHashMiner/translations.json#L1187
![image](https://user-images.githubusercontent.com/4707112/63874285-4fc2ea80-c9d2-11e9-8391-97de13ddac70.png)

**Comment by adem4ik** [comment]
It might be similar to https://github.com/nicehash/NiceHashMiner/issues/1762

**Comment by luc1an24** [comment]
The bug fix will be available with the next release
