### ISSUE TITLE
miniZ PlugIn (BeamV2 and ZHash) is crosslinked with 2 GPUs (V 1.9.2.13)

### ISSUE THREAD

**Issue by Maui73** [nicehash/NiceHashMiner#1765]
Hi,

the miniZ-PlugIn seams to be crosslinked between two GPUs ... the GTX 1660 Ti is enabled but the GTX 1050 Ti works (same problem in benchmark).
The stats also is not shown.

Thanx, Maui

![MiniZ BeamV2](https://user-images.githubusercontent.com/54157942/63899369-e99f8d00-c9fc-11e9-9efb-257f6e3e2fa9.jpg)

**Comment by luc1an24** [comment]
Hi @Maui73
Could you please try plugin version 1.3
This issue was fixed in that version.
If you are already using that version please try to reinstall it.
If the problem still persists please inform me.

**Comment by Maui73** [comment]
hi luc1an24,

V 1.3 was installed, but afer reinstall it works fine :-)

Thank You,

Maui
