### ISSUE TITLE
Stuck Trying To Download Miners 1.8.1.1 Pre-release 4

### ISSUE THREAD

**Issue by nemosminer** [nicehash/NiceHashMiner#177]
1.8.1.1 Pre-release 4 does the same. I've white listed it in Bitdefender, run it as administrator. What is wrong with your software? i have disabled all AV and FireWall still gets Stuck.... be Nice to try you software if it worked...... it looks great

You still have not answered the question, or provided any solutions.

https://ibb.co/iAL3U5

i tried leaving it for a few hours to see if it would start download but it doesn't  then you can't close legacy either you have to task manger and end task, to get it to exit....

i have tried it on multiple computers....   and even gone back to 1.8.1.0 its doing the same thing....

Any help be Much Appreciated

**Comment by airdropfaucet** [comment]
Any chance you figured this out?  I have been looking everywhere for the solution to this, and was extremely disappointed to see this closed without an answer :/

Any help would be truly appreciated
