### ISSUE TITLE
!!!_DaggerHashimoto + Keccak algorithm. Hashrate 10-12 MH

### ISSUE THREAD

**Issue by EVGENY1777** [nicehash/NiceHashMiner#1770]
![DH+Keccak for GitHub1](https://user-images.githubusercontent.com/23138776/63981604-7cf1c480-cac8-11e9-91d5-2a9a4678a2a4.jpg)
1-9-2-13 - nothing has changed... Claymore 15.0

**Comment by github12101** [comment]
Not a bug. It's specific to your hardware, or to Claymore, which is 3rd party miner.
