### ISSUE TITLE
how to enable claymore's straps and rxboost in NHM 1.9.2.13?

### ISSUE THREAD

**Issue by agisubagio** [nicehash/NiceHashMiner#1771]
As subject, I use Windows 10 and NHM 1.9.2.13, how to enable claymore's straps and rxboost?

**Comment by EVGENY1777** [comment]
same as before: - rxboost 1 -strap 1 in the advanced settings

**Comment by agisubagio** [comment]
> same as before: - rxboost 1 -strap 1 in the advanced settings

where is it exactly? i couldn't find it.

**Comment by agisubagio** [comment]
> same as before: - rxboost 1 -strap 1 in the advanced settings

ok thanks... I just found it.
