### ISSUE TITLE
установка

### ISSUE THREAD

**Issue by vitaliti1** [nicehash/NiceHashMiner#1774]
майнер не устанавливается

**Comment by qergo** [comment]
С русским языком не устанавливается, не меняйте язык и все будет нормально. Хочу баунти.

**Comment by vitaliti1** [comment]
это при загрузке с английским языком 02.09.2019, 19:12, "qergo" <notifications@github.com>:С русским языком не устанавливается, не меняйте язык и все будет нормально. Хочу баунти.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sanek42** [comment]
Заебали,  как отписаться от этой хуйни,  целый день всякая поебень приходит.  Заблокируйте нахуй мой аккаунт
