### ISSUE TITLE
Unable to mine on GPU [Device: Alienware M11X]

### ISSUE THREAD

**Issue by PvtSec** [nicehash/NiceHashMiner#1775]
The GPU is Nvidia 335M
It doesn't detect the GPU in the laptop
The laptop is Alienware M11X with Nvidia 335m GPU

**Comment by S74nk0** [comment]
Mobile hardware is not supported Laptops. Also CUDA Compute capability version must be at least 3.0 and higher ([yours is 1.2](https://en.wikipedia.org/wiki/CUDA)). 

Hardware not supported.
