### ISSUE TITLE
Stuck at downloading Miner

### ISSUE THREAD

**Issue by djokerslime** [nicehash/NiceHashMiner#178]
i dl the 1.8.1.1 pre 4 its opening fine but its stuck at the Downloading miner thing,

**Comment by M0DCRAL3R** [comment]
@djokerslime tried "run as administrator"? Or download the bin and 3rd party bin from release page

**Comment by ghost** [comment]
Have the same problem. Tried run as administrator, didn't work. tried downloading the 3rd party bin and extracted to nicehash folder didn't work. even tried to roll back to pre release 3 and now even that won't work. 

For all that's worth , I figured I am not gonna waste my time testing while mining come to a complete halt.  Lucky for me I have nicehash miner 2 installed, so I am using that for now.

**Comment by DillonN** [comment]
Please keep pre-release related issues in #157. You can download both bin.zip and bin_3rdparty.zip from a recent comment there
