### ISSUE TITLE
1.9.2.11 - 1.9.2.13 Miners will not start minimized.  

### ISSUE THREAD

**Issue by tommyprevatt** [nicehash/NiceHashMiner#1780]
Tried this on 1.9.2.11 - 1.9.2.13, have to assume it's still a problem in the just released 1.9.2.14 as it's not in the changelog. 

Even after selecting the setting to start miners minimized, they continue to pop up in your face upon starting.

**Comment by tommyprevatt** [comment]
confirmed still an issue in 1.9.2.14.

**Comment by github12101** [comment]
Confirmed in 1.9.2.14.

**Comment by luc1an24** [comment]
Hi @tommyprevatt and @pioruns
We are unable to start Xmr-Stak and LolMiner in that way but other miner windows should be minimized.
Could you tell me which miners are causing problems?

**Comment by tommyprevatt** [comment]
teamredminer and Phoenix miner. Those are really the only miners my system uses with my cards. The Hide Mining Windows option works, but not the minimized option. Seems petty, but I like to be able to see the windows, but I also don't want them popping up all the time.

**Comment by luc1an24** [comment]
Could you tell me which version of Windows are you using?

**Comment by tommyprevatt** [comment]
Windows 10 Pro, 10.0.17134 Build 17134. I can run a Windows update later just to make certain it's not something resolved by that, but this issue has persisted for a while, so I doubt that will resolve.

**Comment by luc1an24** [comment]
This is not that old windows build so this shouldn't be the case.
Edit: Ah now I see
These 2 miners also do not start minimized.
We will check it out but probably won't be able to do much since they do not seem to "listen" process starting commands.
Will keep this issue open until this is fixed or confirmed that we are unable to fix it

**Comment by Macroshaft** [comment]
Have been avoiding this issue by using 1.9.2.13. And then randomly yesterday the miner uninstalled itself/nicehash off my computer, but was still mining..? Either way, after I restarted my pc, I had to update to the newest miner. Now my mining windows never start minimized, even though my settings are checked.

**Comment by SammyDeM** [comment]
Miners will not start minimized also in version 3.7.0
