### ISSUE TITLE
[1.9.2.14] XmrStak CPU affinity?

### ISSUE THREAD

**Issue by Pieliker96** [nicehash/NiceHashMiner#1781]
Hardware: Ryzen 5 3600 + RX 570

Is there a way to reduce the number of threads XmrStak uses? Reason being that I need a thread free to run my GPU mining algorithm or else hash rate suffers immensely.

I've tried editing cpu_0.txt in the config files, but it gets overwritten every time NiceHash starts. I tried editing it and changing it to readOnly, but that seems to prevent XmrStak from running altogether.

I see the "extra launch parameters" field, but every command I've tried to restrict the thread count or affinity hasn't worked. My current solution is setting the affinity through Task Manager, although this is cumbersome and annoying as it has to be done every time XmrStak is started.

**Comment by S74nk0** [comment]
@Pieliker96 https://github.com/nicehash/NiceHashMiner/blob/master/doc/Plugins/PluginDocs/XmrStak.md#intensity. You should change `cached_AlgorithmName_CPU.json` file as the `cpu_0.txt` gets generated from it.
