### ISSUE TITLE
Установщик

### ISSUE THREAD

**Issue by YuriyNa** [nicehash/NiceHashMiner#1789]
Добавьте в установщик возможность выбора места установки программы. По умолчанию устанавливается в скрытую папку, где майнеры жрет антивирус.

**Comment by luc1an24** [comment]
Hi @YuriyNa
We decided not to allow custom install paths.
We are discussing to change updater download path to the root of installed program (AppData/Local/Programs/NiceHash Miner). That would probably fix the Antivirus programs to block/delete updater (currently downloaded to temp folder).
If you have any other questions/suggestions feel free to contact us.
