### ISSUE TITLE
Malware within NiceHash

### ISSUE THREAD

**Issue by edgarhsanchez** [nicehash/NiceHashMiner#1790]
How about not adding malware inside the NiceHash installer?  Thanks

**Comment by ImmortalJ** [comment]
Care to elaborate? I'm guessing it's a false positive, a lot of mining software triggers false positives because they are included within malware packages.

**Comment by S74nk0** [comment]
@edgarhsanchez Please elaborate what malware is inside the installer?

**Comment by Pretuer** [comment]
Yeah I'm confused I re-downloaded my software about 24h ago whats the problem?

**Comment by tommyprevatt** [comment]
I would be floored if NiceHash put malware inside the installer. However, most mining software will flag as malware since it is often used that way by BotNets. I have to unpack all of my mining software into a seperate folder which I have flagged by my scanners to not scan. I periodically do a manual scan just to make sure everything is safe.

**Comment by joh723** [comment]
Что Вы на это скажите? 
![111](https://user-images.githubusercontent.com/55224226/64754311-39736d80-d540-11e9-8a5a-e5c01f75a83c.png)

**Comment by luc1an24** [comment]
If you see same message as @joh723 please check out the following section of our documentation:
[Miner flagged by anti virus](https://github.com/nicehash/NiceHashMiner/blob/master/doc/Troubleshooting.md#nicehash-miner-legacy-or-included-miners-are-being-flagged-by-anti-virus)

**Comment by edgarhsanchez** [comment]
I'll setup a secure environment this weekend to test it and see what is causing the installer to get flagged for malware.  Before I spend hours trying to solve this are we sure there isn't adware being added to the installer?  Sometimes those get flagged as having malware and then the primary application starts getting flagged along with the adware.

**Comment by luc1an24** [comment]
We are not attaching any malware / adware to the installer or zip.
It is great idea to check that out for yourself.
Please post your findings here.

**Comment by S74nk0** [comment]
@edgarhsanchez I can provide the exact build dependencies with nsis sources and you can try building the installer yourself. Test if it reports it as malware

**Comment by funkybunchesofoat** [comment]
Trojan:Win32/DefenseEvasion!BV
What is this for if not specifically to allow malware?
It's from the uninstaller.

**Comment by KennyLm** [comment]
Damn this Nicehash.exe installer is infected with a trojan called DefenseEvasion.... Please all be aware, all your BTC mined might be gone one day.. Better secure it and delete Nicehash.exe

**Comment by KennyLm** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/57063693/67634292-1e737780-f8ba-11e9-97e7-3d048164b41c.jpg)

**Comment by dongdongmao** [comment]
![Capture](https://user-images.githubusercontent.com/7736453/102880055-b56b9d80-4485-11eb-8802-bf3a9c5728e9.PNG)
what a miner....

**Comment by kikithelion** [comment]
> Care to elaborate? I'm guessing it's a false positive, a lot of mining software triggers false positives because they are included within malware packages.

Win64:AdwareX-gen [Adw]
