### ISSUE TITLE
Where is GPU parameters in NHML 1.9.2.12 - 1.9.2.14? 

### ISSUE THREAD

**Issue by MSukharev** [nicehash/NiceHashMiner#1796]
It were very useful in NHML 1.9.1.14, I think it is not hard to return this parameters in the next release. 
Thank You for new NHML!

![NHML](https://user-images.githubusercontent.com/21043139/64771138-24ee9f80-d557-11e9-9e17-75364ca18ac1.jpg)

**Comment by luc1an24** [comment]
Hi @MSukharev
It is still possible to have these numbers visible.
Please right click on the already displayed stats and enable "`Show Power Info`"
![Screenshot (23)](https://user-images.githubusercontent.com/38202823/64778164-d1328500-d55b-11e9-8c03-1f676251ff70.png)

If you still experience this issue please reopen the ticket.
