### ISSUE TITLE
Unable to translate Unicode character \uD996 at index 6 to specified codepage

### ISSUE THREAD

**Issue by artasek** [nicehash/NiceHashMiner#1799]
As in the title.
This error occurs when starting 1.9.2.14.

the details are:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD996 at index 6 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at NHM.Common.Logger.LogGroupTextType(String grp, String text, LogType type) in D:\Programming\NiceHashMiner\src\NHM.Common\Logger.cs:line 41
   at NiceHashMiner.Stats.NiceHashStats.SendMinerStatus(Boolean sendDeviceNames) in D:\Programming\NiceHashMiner\src\NiceHashMiner\Stats\NiceHashStats_production_new.cs:line 476
   at NiceHashMiner.ApplicationStateManager.<InitializeManagersAndMiners>d__98.MoveNext() in D:\Programming\NiceHashMiner\src\NiceHashMiner\ApplicationStateManager\ApplicationStateManager.Init.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NiceHashMiner.Form_Main.<Form_Main_Shown>d__17.MoveNext() in D:\Programming\NiceHashMiner\src\NiceHashMiner\Forms\Form_Main.cs:line 308
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NiceHashMiner
    Assembly Version: 1.9.2.14
    Win32 Version: 1.9.2.14
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/NiceHashMiner.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NHM.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/NHM.Common.DLL
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/log4net.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MinerPluginToolkitV1
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/MinerPluginToolkitV1.DLL
----------------------------------------
NHM.UUID
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/NHM.UUID.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.8.5.0
    Win32 Version: 1.8.19031.1
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/BouncyCastle.Crypto.DLL
----------------------------------------
Ethlargement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/Ethlargement.DLL
----------------------------------------
MinerPlugin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/MinerPlugin.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.2.23222
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
CCMinerMTP
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/CCMinerMTP.DLL
----------------------------------------
CCMinerTpruvot
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/CCMinerTpruvot.DLL
----------------------------------------
SgminerAvemore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/SgminerAvemore.DLL
----------------------------------------
SgminerGM
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/SgminerGM.DLL
----------------------------------------
XmrStak
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/XmrStak.DLL
----------------------------------------
GMiner
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/GMiner.DLL
----------------------------------------
NBMiner
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/NBMiner.DLL
----------------------------------------
Phoenix
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/Phoenix.DLL
----------------------------------------
TeamRedMiner
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/TeamRedMiner.DLL
----------------------------------------
TRex
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/TRex.DLL
----------------------------------------
ClaymoreDual14
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/ClaymoreDual14.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/MessageBoxManager.DLL
----------------------------------------
NHM.DeviceMonitoring
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/NHM.DeviceMonitoring.DLL
----------------------------------------
NHM.DeviceDetection
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/NHM.DeviceDetection.DLL
----------------------------------------
ManagedNvml
    Assembly Version: 8.0.22.0
    Win32 Version: 8.0.22
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/ManagedNvml.DLL
----------------------------------------
PInvokeDelegateFactoryInternalAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/NHM.DeviceMonitoring.dll
----------------------------------------
MinerPluginLoader
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/kop4/Desktop/nhm_windows_1.9.2.14/MinerPluginLoader.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

How to fix it?

**Comment by S74nk0** [comment]
@artasek Is you language set to English? If you go to the root of nhm installation and delete `translations.json` file and run the program does it still crash?
