### ISSUE TITLE
Unable to Benchmark all Algorithms with Asus Strix GTX 970

### ISSUE THREAD

**Issue by crypto-miner** [nicehash/NiceHashMiner#180]
Hi,

I am using Asus Strix GTX 970 rig and its unable to Benchmark all Algorithms. Getting 0.000 MH/s for most of Algorithms. as i am using Windows 7 Enterprise OS. and my nvidia drivers also up to date also using nicehash miner 1.6.1.4. once check the below screenshot. how can i resolve the issue.

![benchmark screenshot](https://cloud.githubusercontent.com/assets/17754262/17641520/1b93a198-6141-11e6-997a-10e78ac3bbcb.jpg)

**Comment by S74nk0** [comment]
Hi @crypto-miner. Can you please post the log file? Also what driver version is installed? Are the benchmarks terminating or stuck?

**Comment by nicehashdev** [comment]
Use latest version and reopen if issue persists.
