### ISSUE TITLE
Nicehash 1.9.2.14 fails to connect to mining pools. 

### ISSUE THREAD

**Issue by campuzar** [nicehash/NiceHashMiner#1801]
I have 10 mining rigs all set up the same using the latest nicehash miner software.  3 of my rigs went down and each of them are reporting that the login failed to connect to the mining pool.  The mining rigs are running GrinCuckarood29 (NBMinder), GrinCuckaroo31 (NBMinder), BeamV2 (GminerCUDA9.0).  This has happened several times before in which random rigs go down with similar errors after running fine for days and while nothing has changed other rigs running exact same settings and algorithms continue to work just fine.  Eventually after several hours sometimes the failing connections begin to work and mining continues.

**Comment by Maas1337** [comment]
same here, 

errors: Invalid BTC Address
all user mining pools are unavailable

**Comment by S74nk0** [comment]
Please contact support. Sounds like you are banned.
