### ISSUE TITLE
1.9.2.14 - various miner crashes

### ISSUE THREAD

**Issue by Jibbler1976** [nicehash/NiceHashMiner#1802]
After several hours of mining, I'm finding the new miner crashed in many ways. Here I'm getting an error about an invalid BTC address. 

![Invalid BTC address](https://user-images.githubusercontent.com/55397704/64965544-34c5f680-d86b-11e9-9d5d-4f006924649c.jpg)

Here, the rig shows that it is mining, but there are zero solutions, and the console screen is flashing black and failing to run. 

![NiceHash Miner v1 9 2 14 crashed](https://user-images.githubusercontent.com/55397704/64965594-51622e80-d86b-11e9-86fe-d1c65ccee53f.jpg)

I have 7 GPUs, six 1070 and one 1080, with no overclocking.  Previous versions of NHM were stable for me.

**Comment by Jibbler1976** [comment]
Worth mentioning, these are two DIFFERENT types of crash.  I probably should have made two threads. If you need additional information, I can provide it.

**Comment by louis-baker** [comment]
i try bminer it's ok,but nbminer or gminer wrong

**Comment by geshanet** [comment]
On different algorithms, writes that the BTC address is not correct.

**Comment by Jibbler1976** [comment]
Well, the BTC address is correct, and verified by copying and pasting from the website.  Right now I'm not making any money, so it is not a bug which is misreporting, it is completely broken. 

EDIT - This issue is resolved.  The miner was down.  It is OK to close this thread.

**Comment by luc1an24** [comment]
Issue resolved. Closing issue.
