### ISSUE TITLE
benchmark error

### ISSUE THREAD

**Issue by crosbycruz** [nicehash/NiceHashMiner#1805]
I am trying to benchmark the GPU Nividia GeForce 940 and I keep getting not all benchmarks finished successfully. the cpu mines but the gpu just says error. I updated the drivers and still nothing how do I fix this??

**Comment by S74nk0** [comment]
You probably mean **NVIDIA GeForce 940M**? Is this a laptop?

**Comment by crosbycruz** [comment]
yes it is

**Comment by S74nk0** [comment]
@crosbycruz laptops are not supported. I would advise you not to mine on laptops/mobile hardware.
