### ISSUE TITLE
It says no supported items were found but i have a gtx 560 TI and it said some older cards may work do you know how to fix it 

### ISSUE THREAD

**Issue by cbroo133** [nicehash/NiceHashMiner#1806]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by S74nk0** [comment]
**GeForce GTX 560 Ti** is not supported (CC 2.1). GPU too old. CC 3.0 might work but CC 6.1 is probably bare minimum for NVIDIA GPUs. 

https://en.wikipedia.org/wiki/CUDA
