### ISSUE TITLE
Nicehash fails to benchmark. I have the program registered as an exception in Bitdefender, but do I need to track down and list every single .exe file in the directory to make it actually do something?

### ISSUE THREAD

**Issue by dinicthis** [nicehash/NiceHashMiner#1807]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by dinicthis** [comment]
![image](https://user-images.githubusercontent.com/30636661/65281769-305a4180-dae8-11e9-95c4-9d473acddf21.png)

Here is a picture of the application after it tires then gives up on minning. NHM2 worked FAR better.

**Comment by dinicthis** [comment]
Other than uninstalling bitdefender, is there any way to make this work? It seems to block access without notifying that access is blocked.

**Comment by S74nk0** [comment]
@dinicthis please send the logs folder.

**Comment by grichter** [comment]
Exempt the whole folder where nicehash is and all contents from any antivirus/antimalware. Mining software notoriously trips this stuff with false positives.
