### ISSUE TITLE
Enabling CPU mining causes GPU to operate at 0%

### ISSUE THREAD

**Issue by damonlynch** [nicehash/NiceHashMiner#1809]
Ryzen 9 3900X, 1080 Ti, 1070 on Windows 10 64 bit with NHM 1.9.2.14

Enabling CPU mining initially appears to work without issue. The CPU mines in addition to the GPUs. However, after some hours, one of the GPUs does not mine its selected algorithm, i.e. the GPU is running at 0%. In my case, it's the 1080 Ti.

I do not know what is causing this problem — it's difficult to diagnose because it can take some hours to appear.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/3637313/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3637314/log.1.txt)

**Comment by OlivFreitas** [comment]
The same goes for my 1080 ti
I thought my GPU was damaged !!
I updated drivers, reinstalled, changed slots / cables and ... nothing

Now it's wait because I don't know what to do.
