### ISSUE TITLE
RX560 2GB mining

### ISSUE THREAD

**Issue by hovorkaondra** [nicehash/NiceHashMiner#1810]
Hi, 
i am trying to mine with RX560 2gb by Sapphire and NH miner cant find my GPUs, only CPU. In PC i normály see that everything is okey with card.  I am using 1.9.2.14 NH miner. 

I am doing something wrong or 2GB cards are not supported?

Thanks for the answer.

**Comment by Winjeen** [comment]
Hello friend. Unfortunately, as far as I've checked, it's nigh impossible to earn more than the price of electricity, as most chains wouldn't even work with 2g cards.

**Comment by S74nk0** [comment]
Support of your GPU depends on the miner/algorithm combination. 2GB is on the lower end so I would say your GPU is most likely not supported with most of the current relevant miners/algorithms
