### ISSUE TITLE
NiceHash Miner v1.9.2.14-Downloading GMinerCuda9.0+

### ISSUE THREAD

**Issue by CallMePro777** [nicehash/NiceHashMiner#1812]
I have installed NiceHash Miner v1.9.2.14. However, dowloading plugins just has cost me almost a day. Worsestill, the process dowmloading GMinerCuda9.0+ has stuck at 9% completed for 10 hours. And it seems that there is no problem with my internet, otherwise, I could not post this issue .

**Comment by alpturedi** [comment]
Yeah same

**Comment by S74nk0** [comment]
Please provide logs.
