### ISSUE TITLE
Error with mining

### ISSUE THREAD

**Issue by CozyLlama** [nicehash/NiceHashMiner#1818]
I just downloaded the miner and when I try to start the miner says error on my GPU and CPU and doesn't tell me what the error is i've restarted the miner and pc and nothing. please help

**Comment by S74nk0** [comment]
Please provide logs.

**Comment by GaneshDoiphode** [comment]
I have encountered the same problem.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3883435/log.txt)
![image](https://user-images.githubusercontent.com/43588320/69493323-85655b80-0e7b-11ea-857c-945c72777539.png)

AMD Radeon 8850m on dell 5537.  
(amateur to mining, so for any solutions please provide code or screenshots)
