### ISSUE TITLE
Feature Request: show temps in GUI

### ISSUE THREAD

**Issue by bonifacio123** [nicehash/NiceHashMiner#182]
It would be nice to view the GPU temps in the NHML GUI - for example:

Mining Devices {GPU#2} 58C
or
Mining Devices {GPU#1 GPU#2} 60C 58C

Thank you

**Comment by DillonN** [comment]
Will look into doing this

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

This feature is implemented now
