### ISSUE TITLE
Não consigo resolver o erro do nicehash

### ISSUE THREAD

**Issue by hugotipro** [nicehash/NiceHashMiner#1825]
Quando executo o nicehash ele dar o seguinte erro:
![como resolver o erro do nicehash](https://user-images.githubusercontent.com/56043232/65986583-84571580-e45a-11e9-9ecd-af97791c2dd5.PNG)
gostaria de saber como resolver o problema agradeço desde ja

When I run nicehash it gives the following error:
I would like to know how to solve the problem thank you in advance..

**Comment by S74nk0** [comment]
Please specify what kind of hardware are you running nhm on? This looks like your PC isn't compatible.

**Comment by hugotipro** [comment]
intel core celeron 2.5Ghz dual core 2Gb ram a friend of mine ran nicehash on a computer with the same settings as my pc

**Comment by S74nk0** [comment]
Your PC is not compatible with the latest nhm. Closing

**Comment by hugotipro** [comment]
I'm pretty sure my machine is compatible, because as I said I saw a machine with the same settings as my running.

**Comment by hugotipro** [comment]
My main suspicion is Opencl, because that is the error it causes.
I also saw a 1.60ghz machine with 4 ram running, I think something related to the driver, because the Intel HD graphics drive is generic and is the original of the error.
