### ISSUE TITLE
Issues downloading updates/New feature request

### ISSUE THREAD

**Issue by jdr360** [nicehash/NiceHashMiner#183]
Always having issues downloading any updates from GitHub. Unable to download NHML-1.8.1.1.zip or bin.zip. Both always say network failed. I don't have a problem downloading bin_3rdparty.zip

Might want to build into NHML and NHM, self downloading and updating feature where user can select which version or parts to download. Like how most virus protection apps do, one section can download and update the app it's self, while other section can download and update virus definitions.

For both NHML and NHM, have one section for the main program and other for 3rdparty updates.

**Comment by jdr360** [comment]
Anyone home!!! Has anyone looked into this yet????

**Comment by EtaYorius** [comment]
Same, every time i try to download that version i get  a Connection Error or Something about permission.

**Comment by jdr360** [comment]
EtaYorius - Are you able to download anything from GitHub? I'm able to download the bin_3rdparty.zip for 1.8.1.1 but not the bin.zip or NHML-1.8.1.1.zip. The NHML-1.8.1.1.zip get to the end of the download, then I get Network Failed error. The bin.zip gets to about 27% downloaded then fails. I did however get the NHML-1.8.1.1.zip to complete. I first had to do a complete shutdown of my PC for 5 minutes to ensure a complete cold fresh restart. Then after logging in, I completely disabled my anti virus software. Then I had to use Internet Explorer (Not Chrome or Edge, as they seam to block it) to download the NHML-1.8.1.1.zip. Uncompress the file, to a new folder, then run NiceHashMinerLegacy.exe as ADMIN. Let it complete it's downloading, along with the 3rdparty if you like. Then do all Benchmarks, one at a time, I had issues selecting all at once. Configure NHML the way you like but don't run it yet. Once all that is complete. Shut it down, turn your Anti Virus software back on and reboot. You should be good to go or at least that's how it worked for me.

**Comment by EtaYorius** [comment]
Your trick to momentarily stop Antivirus and using IE worked fine. thank you!

**Comment by DillonN** [comment]
Downloading big files from Github can be finicky but NHML will automatically retry for when those errors happen. There are no plans to change the bin downloading system since users should be comfortable dealing with AV/FW exceptions and outside errors
