### ISSUE TITLE
NHM 1.9.2.15 Reset the Algorithms/Enabled/Benchmarked at each restart

### ISSUE THREAD

**Issue by gitusr-gcar** [nicehash/NiceHashMiner#1830]
I downloaded the .ZIP version of NHM 1.9.2.15 for Windows, extracted in its own directory and excluded this directory from Windows Defender.
Every time I start the NHM application I have to reload all the mining plugins because the list of Algorithms/Enabled/Benchmarked is reset to 0/0/0.
Then I have to execute the benchmark again so I can start mining and everything goes fine until I exit the application and reopen again.

I also tried to set as read-only the three config files in the "nhm\configs" directory after before restarting the application, but the Algorithms is always reset and I only see the following information in the log:

[2019-10-05 17:32:42] [ERROR] [InternalConfigs] Error occured while writing file settings to D:\temp\mining\nhm_windows_1.9.2.15\configs\device_settings_CPU-b576dd0d-a7a3-5ffc-a211-3adb58e2495e.json: Access to the path 'D:\temp\mining\nhm_windows_1.9.2.15\configs\device_settings_CPU-b576dd0d-a7a3-5ffc-a211-3adb58e2495e.json' is denied.
[2019-10-05 17:32:42] [ERROR] [InternalConfigs] Error occured while writing file settings to D:\temp\mining\nhm_windows_1.9.2.15\configs\device_settings_AMD-1635fd4b-23d4-5e9d-9843-dc0c59ad95e5.json: Access to the path 'D:\temp\mining\nhm_windows_1.9.2.15\configs\device_settings_AMD-1635fd4b-23d4-5e9d-9843-dc0c59ad95e5.json' is denied.
[2019-10-05 17:32:42] [ERROR] [InternalConfigs] Error occured while writing file settings to D:\temp\mining\nhm_windows_1.9.2.15\configs\General.json: Access to the path 'D:\temp\mining\nhm_windows_1.9.2.15\configs\General.json' is denied.

Any hint?

Regards

**Comment by grichter** [comment]
At first glance it looks like a permissions problem in the configs folder. Might want to verify that something stupid with permissions didn't happen at some point during your setup.

**Comment by gitusr-gcar** [comment]
Hi grichter, thank you for the answer, but I don't think so.

Like with all the previous versions, I simply unzipped the Windows version of NHM 1.9.2.15 into a subdirectory of the d:\temp\mining folder.
The error that you see in my previous message is because I manually set the config file to "read-only" after having reloaded and benchmarked all the plugins, for the _nth_ time. Mine was just a try to force the two configuration files to not being overwritten with the default (empty) values because I also enabled the "debug log files" in the NHM settings but nothing evident is reported.

In fact, what I'm asking is why, at the startup, the NHM application rewrite those two JSON config files (**device_settings_AMD-1635fd4b-23d4-5e9d-9843-dc0c59ad95e5.json** and **device_settings_CPU-b576dd0d-a7a3-5ffc-a211-3adb58e2495e.json**) even if they are present in the '<nhm>/configs' subdirectory, so resetting the value of the "PluginAlgorithmSettings" JSON tag to an empty string?

Am I the only one with this issue (confirm that it didn't happen until 1.9.2.14)? 
Should I try using the "Windows Installer" version"?

Regards

**Comment by grichter** [comment]
Unfortunately my rigs are back on .9 and .11 as they changed how plugins work and i have not been well enough to get my management scripts updated. I don't use the distribution zip internally - I use a .7z that is comprised of the nhm and all plugins, automatically gathered by a powershell script.

**Comment by dfretyhg** [comment]
Did you ever find a solution? I'm having the same issue still in 1.9.2.16

**Comment by gitusr-gcar** [comment]
Hi @dfretyhg, unfortunately not, so I had to go back to .14 in order to be able to continue using NHM and save the list of benchmarked algorithms.
