### ISSUE TITLE
I can't solve the nicehash error

### ISSUE THREAD

**Issue by hugotipro** [nicehash/NiceHashMiner#1835]
![65986583-84571580-e45a-11e9-9ecd-af97791c2dd5](https://user-images.githubusercontent.com/56043232/66670499-5464fa80-ec30-11e9-80c4-9489febe7d73.png)
When I run nicehash it gives the following error:
I would like to know how to solve the problem thank you in advance.
intel core celeron 2.5Ghz dual core 2Gb ram a friend of mine ran nicehash on a computer with the same settings as my pc.
My main suspicion is Opencl, because that is the error it causes.
I also saw a 1.60ghz machine with 4 ram running, I think something related to the driver, because the Intel HD graphics drive is generic and is the original of the error.
![erro2](https://user-images.githubusercontent.com/56043232/66671130-c25df180-ec31-11e9-9924-f3e5ff552b27.PNG)

**Comment by xielaoda516** [comment]
![image](https://user-images.githubusercontent.com/57080924/68068741-461f7f80-fd93-11e9-8daf-49b419333030.png)

**Comment by xielaoda516** [comment]
怎么回事？请教

**Comment by knoelle119** [comment]
Does anyone solve this issue already? Ii need help too im having the same issue... Anyone?

**Comment by AcVerdant** [comment]
I think it might be because you do not have a GPU (graphic card) installed. I have exactly the same issue with another PC.
