### ISSUE TITLE
hang on getting nicehash profitability data

### ISSUE THREAD

**Issue by paulh69** [nicehash/NiceHashMiner#184]
seems to hang on starting if it can't get nicehash profitability data, does not appear to retry?

**Comment by streaml1ne555** [comment]
This coincided with the web services being down for maintenance a few hours ago. I had the same problem and as soon as nicehash.com was back up, NHML worked when I started it. It definitely did not retry, but mine did not hang, it just popped an error dialog after about 30 seconds and then loaded the interface with no BTC rates/wallet data.

**Comment by DillonN** [comment]
It will retry silently once every second for around 20-30s if it is unable to connect then pop an error that it cannot connect
