### ISSUE TITLE
Incorrectly identifying graphics card

### ISSUE THREAD

**Issue by WyvernZ** [nicehash/NiceHashMiner#1841]
NiceHash version 1.9.2.15 is incorrectly identifying one of my graphics cards. I have an RX 590 and an RX 580 in my system; Windows and AMD settings recognize this but the newer version of NiceHash says that there are two RX 590s. This is resulting in a "dead GPU" error for the RX 580 card. Is there any way to refresh the program or manually change this?

**Comment by ghost** [comment]
Same here, nicehash (1.9.2.15) is detecting my radeon 520 as R5 M330.

I think this might be related https://www.reddit.com/r/NiceHash/comments/7o5zsz/fixed_nicehash_miner_legacy_detection_exe_for/

**Comment by WyvernZ** [comment]
I think that solves the mystery, thank you!
