### ISSUE TITLE
NH 1.9.2.15  amd cards stop mining after a few minutes, xmrstak

### ISSUE THREAD

**Issue by mrfishbsme** [nicehash/NiceHashMiner#1843]
NH 1.9.2.15 on US server
RADEON 19.10.1
4X R9 280 CARDS

System start mining. temps look good. after a few minutes all cards stop mining.

Is there a issue here? Am I getting booted from pool? Does NH or xmrstak not like these cards?
It seems suspicous that all 4 cards drop at the same time.

**Comment by klausiau** [comment]
I am experiencing the same issue
2 x Nivida GTX 1070Ti
2 x Radeon RX580
the RX580 stop mining after maybe 20min, when I terminate my remote login session into my mining PC.  Checked with version 1.9.1.14 worked before, but have the same problem now too.

**Comment by S74nk0** [comment]
Please provide logs.

**Comment by labsy** [comment]
Hi,
I am having the same problem on versions 1.9.2.14, .15 and .16. Mines for few minutes, then stops, program seizes, no errors, no logs in Antivirus...even with Antivirus on pause or stop, same problem.
The only significant ERROR in logs is:

`[ERROR] [CheckAndSwapInstalledExternalPlugins] Could not find a part of the path 'C:\Users\MyUserName\AppData\Local\Programs\NiceHash Miner\plugins_packages'.`

**EDIT/UPDATE**
**SOLVED! It was NOD32/ESET Antivirus. Exclusions did not help, I needed to disable it for miner to work properly.**

**Comment by Maybemine** [comment]
I cannot even start mining... (made a new thread about it w/ logs) Although I did find that most of the issues I was having was with Norton 365.. blocking NHM completely, I solved that so.. idk
