### ISSUE TITLE
No DaggerHashimoto algorithm for P104-100?

### ISSUE THREAD

**Issue by dhonasan** [nicehash/NiceHashMiner#1849]
As the title said, there is no DaggerHashimoto algorithm for NVIDIA P104-100 when it's the best algo for p104-100, please add it. Thanks
![image](https://user-images.githubusercontent.com/32080588/67951347-e5226b00-fc1d-11e9-899a-7f2075f58061.png)

**Comment by S74nk0** [comment]
@davidhonasan you can enable this yourself. Update the miner plugin to the current latest version. After that you need to create an empty `unsafe_limits` file within the plugin that supports DaggerHashimoto and restart NiceHash Miner. This will disable the RAM requirements limitations that is filtering your GPUs. 

For example if you want to disable limits for **Phoenix Miner Plugin** in `NHM_PATH\miner_plugins\f5d4a470-e360-11e9-a914-497feefbdfc8` create the `unsafe_limits` file and on the next NiceHash Miner you should have **DaggerHashimoto available for Phoenix Miner Plugin**. The same process applies for any Miner Plugin. 

If you are not sure how to create this file open the command prompt and type `copy nul unsafe_limits` this will create the file. It is important that the file doesn't have an extension (e.g. *.txt).

Please report back your success with this process.

**Comment by rivalsec** [comment]
@S74nk0 I tried with 3.0.0.1 did not work ,I also tried with version 1.9.2.21, the result is the same, after restarting the folder with the plugins are deleted, and the plugins do not work
