### ISSUE TITLE
Adding Signatum Miner? 

### ISSUE THREAD

**Issue by pducharme** [nicehash/NiceHashMiner#185]
Can you add Signatum mining?

**Comment by streaml1ne555** [comment]
I believe the latest release of Legacy includes this (skunk). What I'm wondering is if there are extra launch  parameters for it to tune.

**Comment by juanfpina** [comment]
There is a cpu miner on the website, I am using it right now to mine to the nicehash pool using the address that the gpu miner uses. I'm only getting ~500 kH/s though. You can use -i on the gpu miner in the latest version to change intensity if you are getting validation errors or something.

**Comment by pducharme** [comment]
thanks.  I didn't know that Skunk == Signatum :)
