### ISSUE TITLE
Scheduled mining times

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner#1853]
Would it be possible to add a mining schedule to nicehash? I run my rigs of solar and it would be nice to have them start mining in the mornings and stop in the late afternoon. Any way of implementing such a feature?

**Comment by wallaceaskew** [comment]
There's a task scheduler built in to Windows.  Here ya go!
https://www.technig.com/windows-10-task-scheduler/

**Comment by Johann1982** [comment]
@wallaceaskew Yes, I know, but if I use that it closes nicehash and it shows my rig is offline. I would like it if nicehash had its own internal schedule.

**Comment by Maybemine** [comment]
I can see the use for this... there are times when I am away from home for long periods, and to have a schedule to mine would be very nice.

**Comment by Durishn** [comment]
I'm also interested in using this feature should it be implemented

**Comment by IshisMAD** [comment]
lol me too

**Comment by Nunak** [comment]
me too

**Comment by Kyranwalker94** [comment]
me too

**Comment by Creyes23** [comment]
me too

**Comment by solomani** [comment]
Same, I use solar so would like a scheduler, currently doing this manually.  Task scheduler doesn't kill the app properly, it just relaunches immediately.

**Comment by The-Ant-Forge** [comment]
+1 for a play/pause scheduler...  
can even be a cron script format plenty of generators online so no need for fancy UI at first

**Comment by supachailllpay** [comment]
+1 to set the schedule for each device. It could be a cron format, just one plain text field will be enough.

**Comment by nonlinearsugar** [comment]
+1 for a play/pause+power scheduler.

**Comment by tomas-cabaj** [comment]
me tooo

**Comment by samywee** [comment]
Me too. Please implement. Much required. Best would be have the scheduler in web-interface, so that we can control all miners on a schedule from the web-ui.

**Comment by leicao-me** [comment]
Me too

**Comment by elric667** [comment]
Love to have a scheduler built-in because when I use windows schedule to kill the product and start it again It stops at wanting to optimize my cards and will not start without input.  So a Scheduler would be nice.

**Comment by leicao-me** [comment]
> Love to have a scheduler built-in because when I use windows schedule to kill the product and start it again It stops at wanting to optimize my cards and will not start without input.  So a Scheduler would be nice.

I use QuickMiner's OCTUNE to optimize the card in the background(stop quickminer's mining), and use nicehashminer to mine, so task scheduler only kills nicehashminer not OCTUNE

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
