### ISSUE TITLE
CUDA error in CudaProgram.cu:373 : out of memory (2)

### ISSUE THREAD

**Issue by WillianSalceda** [nicehash/NiceHashMiner#1857]
Phoenix Miner 4.7c Windows/msvc - Release build
-----------------------------------------------

CUDA version: 10.0, CUDA runtime: 8.0
Available GPUs for mining:
GPU1: GeForce GTX 1050 Ti (pcie 2), CUDA cap. 6.1, 4 GB VRAM, 6 CUs
Nvidia driver version: 441.12
Eth: the pool list contains 1 pool (1 from command-line)
Eth: primary pool: daggerhashimoto.br.nicehash.com:3353
Starting GPU mining
Eth: Connecting to ethash pool daggerhashimoto.br.nicehash.com:3353 (proto: Nicehash)
GPU1: 30C 30% 36W
GPUs power: 35.6 W
Eth: Connected to ethash pool daggerhashimoto.br.nicehash.com:3353 (172.65.195.159)
Listening for CDM remote manager at port 4000 in read-only mode
Eth: Subscribed to ethash pool
Eth: Worker 3KbfgWhzLi4QrM6METY3aAzAA1NBhWj7j9$0-FfPFLHLcjVWIwstHKh8jHw authorized
Eth: New job #79ff35a2 from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
GPU1: Starting up... (0)
GPU1: Generating ethash light cache for epoch #296
Eth: New job #b158f306 from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Eth: New job #7f4f2f7d from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Light cache generated in 2.6 s (20.7 MB/s)
**GPU1: Allocating DAG (3.33) GB; good for epoch up to #298
CUDA error in CudaProgram.cu:373 : out of memory (2)
GPU1: CUDA memory: 4.00 GB total, 3.30 GB free
GPU1 initMiner error: out of memory**
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
Eth: New job #831b4fb4 from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Eth: New job #e68b5bc2 from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
Eth: New job #f7f9bd07 from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Eth: New job #be9671bf from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
GPU1: 30C 30% 36W
GPUs power: 35.6 W
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
Eth: New job #40399f1d from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Eth: New job #c947cfff from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Eth: New job #9a1e3f7f from daggerhashimoto.br.nicehash.com:3353; diff: 8590MH
Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00

*** 0:00 *** 11/7 17:13 **************************************
Eth: Mining ETH on daggerhashimoto.br.nicehash.com:3353 for 0:00
Eth: Accepted shares 0 (0 stales), rejected shares 0 (0 stales)
Eth: Incorrect shares 0 (0.00%), est. stales percentage 0.00%
Eth: Average speed (5 min): 0.000 MH/s

Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00

**Comment by luc1an24** [comment]
Hi @WillianSalceda 
Thank you for reaching out.
The reason your gpu is unable to mine daggerhashimoto because it doesn't have enough memory.
It hash 3.30 GB free memory but current DAG SIZE is over this number. So if you would still want to mine this algorithm install Windows 7, since it doesn't take that much memory as Windows 10. Or just start mining another algorithm.

I hope my answer was helpful, if you still have any questions please reopen the issue.

**Comment by vogemah** [comment]
@luc1an24 
Hello, thank you for the explanation above about out of memory problem. I have exactly the same. Now the second option you mentioned is that i could consider mining another algorithm. How do I change the algorithm and which other can I mine?

**Comment by jennylisa1** [comment]
Yes, which other can we mine?
