### ISSUE TITLE
not working at all windows 7 64bit

### ISSUE THREAD

**Issue by peteycrack420** [nicehash/NiceHashMiner#1858]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by peteycrack420** [comment]
previous version works just fine

**Comment by luc1an24** [comment]
Hi @peteycrack420 
Thank you for reaching out.
What do you mean with "not working"? It doesn't start or one of the miners doesn't behave well?
Could you please append the logs so we can easier find out where is the issue?
Thank you very much for your help.

ps: Could you also tell us what setup do you have?

**Comment by peteycrack420** [comment]
i run as admin hit yes nothing   even tried and updated drivers   previous version works just fine   and i tried he zip, exe and updater

**Comment by almartins** [comment]
Hi 
I have 3 miners running windows 7 64 bits. Two of then are running fine "nhm_windows_1.9.2.16" but the the third does not run. After downloading the "zip" package and extracting it, I run "NiceHashMiner.exe" and the box with the title: "NiceHashMiner has stopped working" appears. The rest of the error information is:
"
Assinatura do problema:
  Nome do Evento de Problema:	APPCRASH
  Nome da aplicação:	NiceHashMiner.exe
  Versão da aplicação:	1.9.2.16
  Carimbo de Data/Hora da Aplicação:	d76cf090
  Nome do Módulo com Falhas:	KERNELBASE.dll
  Versão do Módulo com Falhas:	6.1.7601.21772
  Carimbo de Data/Hora do Módulo com Falhas:	4e211f48
  Código de excepção:	e0434352
  Desvio de Excepção:	000000000000cacd
  Versão do SO:	6.1.7601.2.1.0.256.48
  ID de Região:	2070
  Informações Adicionais 1:	7878
  Informações Adicionais 2:	787854380ac502069a277b7321ff9e3f
  Informações Adicionais 3:	a65c
  Informações Adicionais 4:	a65c7c969a1cb5782c1145207cef3c4d
"
Sorry but it's Portuguese language. There is no log file

**Comment by peteycrack420** [comment]
i dont even get a error non the windows 7 it acts like its going to open then never does

**Comment by S74nk0** [comment]
Please try this build https://github.com/nicehash/NHM_MinerPluginsDownloads/releases/download/commit_b6e0bfb/Release_TESTING_1.9.2.16_LOCK2.zip. It is based of https://github.com/nicehash/NiceHashMiner/tree/master-nhmws_refactor branch. Please report back if this works for you

**Comment by almartins** [comment]
Hi S74nk0,
This build is running much better, but after import my config folder from 1.9.1.15 and re-start all GPUs status is "Error", but is a steep ahead.

**Comment by Panchzz** [comment]
Hello, I jsut posted this issue: https://github.com/nicehash/NiceHashMiner/issues/1865
Looks similar to this one,

> Please try this build https://github.com/nicehash/NHM_MinerPluginsDownloads/releases/download/commit_b6e0bfb/Release_TESTING_1.9.2.16_LOCK2.zip. It is based of https://github.com/nicehash/NiceHashMiner/tree/master-nhmws_refactor branch. Please report back if this works for you

I Tested this zip. NiceHashMiner loads just fine but I still can't  mine because no algorithms available for my device so, it's not a solution. (CPU mining pays 10% of the VPS server fee, that's an acceptable reason to cpu mine for 0.3 usd a month)
