### ISSUE TITLE
update broke Windows miner

### ISSUE THREAD

**Issue by DouglasGMoore** [nicehash/NiceHashMiner#1859]
how can i roll back the update? I know not to trust developers but i went for the update anyway. My bad.
Immediately after i installed the newest update. My miner went bonkers. If i try to mine with my gpu's it only tries to mine equihash. It never connects, but it keeps trying over and over and over again.  errors pop up when i quit and try to restart mining.

**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by luc1an24** [comment]
Hi @DouglasGMoore 
I am sorry to hear that the new update doesn't work for you.
Could you provide us with more info about your setup? Some logs would also be really useful.
If you could attach the screenshot of the miner windows when the error occurs it would help us to determine if the issue is with the miner or within the NHM.
Could you also tell us what kind of errors pop up?

Thank you for all the help!

**Comment by S74nk0** [comment]
Please try this build https://github.com/nicehash/NHM_MinerPluginsDownloads/releases/download/commit_b6e0bfb/Release_TESTING_1.9.2.16_LOCK2.zip. It is based of https://github.com/nicehash/NiceHashMiner/tree/master-nhmws_refactor branch. Please report back if this works for you

**Comment by brNX** [comment]
Hi,
I was having the same issues (1080 and 1050 combo, where the 1050 sat idle), that build fixed it for me

Cheers
