### ISSUE TITLE
Optiminer and claymore (equihash) not working together

### ISSUE THREAD

**Issue by torsrex** [nicehash/NiceHashMiner#186]
Hey! 
I'm running 2xamd radeon hd 7850. The optiminer algorithm for equihash is best for one of them, whereas the claymore algorithm for equihash is the better for the other one of them. However, when mining starts, it forces both cards to use optiminer. If it's disabled for one of the cards, that card resorts to mining using a different algorithm (in this case claymores cryptonight miner).

**Comment by drkskwlkr** [comment]
NHML uses the individual benchmark results to determine profitability & select a miner for each GPU. You can manually edit the score for the card+algo combination you don't want (e.g. make it look 100x less productive), and NHML will no longer assign work to this combo.

**Comment by torsrex** [comment]
If you look at this image, you can see that for this gpu, optiminer benchmarks higher than claymore.![image](https://user-images.githubusercontent.com/1499173/29494516-65266c88-85ac-11e7-9b89-8bfc42ee78d7.png)

For this gpu, claymore benchmarks higher than optiminer (due to different overclock settings etc). 
![image](https://user-images.githubusercontent.com/1499173/29494519-7e6b2fd0-85ac-11e7-9124-1ad86a6139f9.png)

But when I click start, the NiceHash miner forces both cards to use optiminer 
![image](https://user-images.githubusercontent.com/1499173/29494541-eb01dc3e-85ac-11e7-88cd-073c21e170a5.png)

However, if I go and disable optiminer for the card that benches higher using claymore, everything works as it should and it launches the appropriate miners. It's not that big of an issue, but more like a minor bug.

**Comment by DillonN** [comment]
NHML uses an averager between two identical cards to prevent benchmark noise from causing over-switching. Most of the time this is beneficial but if your cards are not so identical (e.g. maybe one is watercooled) then it can cause this problem. I'll look into an option to disable this behvaiour

**Comment by lmlim** [comment]
yes, 1 from 4 of my gtx 1060 6gb has different benchmark results as well. 
i think it has different base/boost/ram clock because of from different brand.
