### ISSUE TITLE
1.9.2.16 Constant Benchmarking on stop/start of the Miner (Win10)

### ISSUE THREAD

**Issue by Svyatk0** [nicehash/NiceHashMiner#1860]
In the latest 1.9.2.16 as well as the previous few releases i am seeing constant benchmarking on when i start/stop of the miner (Win10). 
Is this a new feature ? as it takes a very longtime to complete, and isnt necessary.

**Comment by S74nk0** [comment]
@Svyatk0 please provide logs.

**Comment by TheDarkTiger** [comment]
I know it's old but it still append on recent versions.
To prevent this, verify that you don't have any failed benchmark checked on your benchmark window.
Else, it will, indeed, try to benchmark it at every start.

**Comment by Svyatk0** [comment]
Thanks @TheDarkTiger this did the trick.
I have had lots of unbenchmarked algos, so it was taking absolute age everytime. 
Unticking these (since they dont seem to benchmark anyway) fixes the problem.

**Comment by TheDarkTiger** [comment]
Welcome.
