### ISSUE TITLE
NVidia Graphics card won't run

### ISSUE THREAD

**Issue by HeliosTXG** [nicehash/NiceHashMiner#1861]
I've been using Nicehash for about a week now, mostly just have it running on my computer while I'm at work, but now for some reason my GPU won't work with the program. Whenever I try to benchmark it, or nicehash runs the benchmark when it starts working, it tries for a minute and then ends with just "error," and no explanation. When I look at the benchmarking screen it says there are about 7 miners/programs it hasn't been benchmarked with, do I just keep trying to manually benchmark until all of them have been done?

**Comment by S74nk0** [comment]
Please specify your GPU model. Are you running NiceHash Miner on a Laptop?

**Comment by RicardoHunter** [comment]
hi, i have a laptop with a mx 150 and have same problem!

**Comment by HeliosTXG** [comment]
I am using a desktop, using an Nvidia GeForce 1660ti GPU. I have since fixed it, when you go to the benchmark screen, just uncheck any benchmarks that did not complete for the graphics card, apparently NHM tries to benchmark everything that is checked on there before mining, and if the benchmark fails, it doesn't start mining.
