### ISSUE TITLE
1.9.2.16 won't initiate (1.9.2.15 Works Fine)

### ISSUE THREAD

**Issue by Panchzz** [nicehash/NiceHashMiner#1865]
System Specs:

XEON CPU E7-4880 v2 @ 2.5Ghz (1 CORE)
1GB RAM
WINDOWS SERVER 2012 Standard
(Cheapest SSD VPS from rackeo.cl)

Logs:
No log generated (NHM crash before logging anything)

Bug:
1.9.2.16 NMH won't start application when opening executable. (Both Zip and Installer)
 
Tested 1.9.2.16 at my:
Celeron N3350 ; Ryzen 2200g
Both at Windows 10 Fully updated, no errors

Upgrading OS not a solution

Partial solution:
Don't upgrade from 1.9.2.15 to 1.9.2.16

Personally I beleave this is a minor bug since upgrading isn't YET mandatory. I'm worried about future versions of the NHM

**Comment by S74nk0** [comment]
@Panchzz please try the latest version https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.17

**Comment by Panchzz** [comment]
> @Panchzz please try the latest version https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.17

1.9.2.17 Working just fine.

Thanks for the quick fix. Happy mining,.
