### ISSUE TITLE
 Add algorithms please to the program?

### ISSUE THREAD

**Issue by vasy701** [nicehash/NiceHashMiner#1866]
Add algorithms please to the program ?, HavenProtocol (XHV)
CryptoNightHaven BitTube (TUBE)
CryptoNightSaber is not bad in terms of profitability.
https://whattomine.com/coins
===============
Добавьте алгоритмы пожалуйста в программу?, HavenProtocol(XHV)
CryptoNightHaven BitTube(TUBE)
CryptoNightSaber по доходности неплохие.
https://whattomine.com/coins

**Comment by luc1an24** [comment]
Hi @vasy701 
Could you please these requests to our support team (support@nicehash.com)?
Since this is not NHM issue I will close it.
