### ISSUE TITLE
Suggestion: Checkbox select all/none in Benchmark list and Devices/Algorithms

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#187]
I think that would be really handy to have a global checkbox for Benchmark alorylithms and Devices/Algorithms tab. It is around 20 miners in those lists on my GTX 1060 6GB and it comes very hard to select/deselect all the algorithms by checking/unchecking every item.
![2017-08-20_022335](https://user-images.githubusercontent.com/4707112/29490527-34fb7186-8550-11e7-982c-8166bc5a8935.png)

**Comment by toonsmil** [comment]
try right click on one algo ;)

**Comment by adem4ik** [comment]
wow, thanks! that's a kind of magic.

@DillonN feel free to close the topic.

**Comment by MonaxDK** [comment]
I also did not immediately found out about right click. I think it's a good idea to make a checkbox.
