### ISSUE TITLE
Please include support for RandomX on XMRig

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1870]
Hi,

I noticed that you've added support for RandomX on XMR-Stak for the next release. I realize that you may not be finished but I just wanted to mention that at least one person would like to see XMRig supported as well.

Thanks! :)

**Comment by luc1an24** [comment]
Hi @jwesolo 
Thank you for reaching out.
Support for algorithm is ready, we are just waiting for fork.
