### ISSUE TITLE
Cannot start device type there is no config

### ISSUE THREAD

**Issue by WCROOK82** [nicehash/NiceHashMiner#1872]
Cant benchmark randomX on ryzen 1700 cpu, vega fe and gtx 960 all have no config error
![error](https://user-images.githubusercontent.com/39251462/69892930-cddba980-12bf-11ea-947d-b1d5d40d08ae.png)

**Comment by Panchzz** [comment]
This is happening too at my Ryzen 2200g, both my VPS instances at rackeo, vultr, and celeron N3350.

I dont think its a plugin issue

EDIT: RYZEN 2200G now supports randomx cpu mining
EDIT2: Now I tested at Celeron N3350 Its mining fine randomx
EDIT3: Both Vultr and Rackeo VPS instances can now mine randomX

**Comment by wallaceaskew** [comment]
I'm running dual Xeon E5-2609 v2 and having this issue.
