### ISSUE TITLE
NiceHash Miner does not minimize miners Windows

### ISSUE THREAD

**Issue by lexa26** [nicehash/NiceHashMiner#1873]
Hi, everybody
if in the NiceHash Miner 1.9.2.18 settings you put a tick next to minimize Windows, save the settings and start mining, the Windows are not minimized if you add a check mark hide Windows, the Windows are not hidden and are not minimized if you remove the check mark minimize Windows, leaving hide Windows, the Windows will be hidden
Something must have broken in the window minimization mechanism
In NiceHash Miner 1.9.2.14 everything works

**Comment by joseortiz3** [comment]
Agreed. Pretty annoying.
