### ISSUE TITLE
1.9.2.17 1.9.2.18 force win stuck

### ISSUE THREAD

**Issue by sbminimalistics** [nicehash/NiceHashMiner#1874]
1.9.2.17 1.9.2.18 both versions hang rigs (win7 and win10) while benchmarking with default mining algorithms on.
GPUs in use: 1060, 1070, 1070ti.
Only hard restart helps.

**Comment by jaga2580** [comment]
I have the same issue on my rig
Win10
2 x GTX1070Ti and 1 x GTX970 

Hangs when starting benchmarking. Requires hard restart
I have reverted back to v1.9.2.16

**Comment by S74nk0** [comment]
Can you please be more specific with 'Hangs'.
  - Does it cause a system restart?
  - Does the system become unresponsive?
  - Does the system BSOD?

**Comment by jaga2580** [comment]
Hi Stanko
In answer to your questions:

- no the system does not restart
- yes totally unresponsive. No keyboard or mouse movement. Cntl-Alt-Del
does nothing.
- no it does not BSOD. Within about 15 seconds of the benchmark starting,
the screen just totally freezes and I have to force a restart via button
push

Hope this helps...Alan
