### ISSUE TITLE
i have a 11 gpu's rig, 2 nvidia gtx 950 4gb and 8 Amd rx 750. every time i launch the nhm application it works fine , but after hour or two it hangs the pc completely, i updated my nhm version  to the last one and it does the same no matter what version i use. any help please? i use win 10 64 Bit

### ISSUE THREAD

**Issue by Marooooooooo** [nicehash/NiceHashMiner#1878]
i have a 11 gpu's rig, 2 nvidia gtx 950 4gb and 8 Amd rx 750. every time i launch the nhm application it works fine , but after hour or two it hangs the pc completely, i updated my nhm version to the last one and it does the same no matter what version i use. any help please? i use win 10 64 Bit

**Comment by S74nk0** [comment]
@Marooooooooo can you send the logs please. Please describe the "hangs the pc completely" does it BSOD or does NiceHash Miner program become unresponsive or does the whole system become unresponsive?

**Comment by Marooooooooo** [comment]
i don't think it's BSOD, actually i remotely login to that machine, i don't know what happens, but the pc hangs only after while from running the NHM.
i copied the last punch of admin logs to my pc, hope it will help.

**Comment by Snake-AU** [comment]
I'm having the same issue. The whole machine freezing, often gets stuck when benchmarking for the first time. I've uninstalled and reinstalled a few times and its still happening. What I did pickup was 100 mem utilisation, so I think there is a memory leak or over allocation of data to RAM.
