### ISSUE TITLE
When NHML deciding which algo to run...

### ISSUE THREAD

**Issue by lmlim** [nicehash/NiceHashMiner#188]
Hi,

I am curious if NHML put dev fee into consideration when deciding which algo to run.

for example, deciding between say dual mining claymore and equihash(excavator), say it is only 1% difference, but claymore charges 2% and excavator is free. which algo will NHML run?

i am sure there may be a couple more scenarios that have similar problems.

In any case, should i increase "profitability threshold" higher? (i am setting it at 1% now, i also turned off intermittent spiking price algos, eg x11gost)

 
Thanks.

**Comment by adem4ik** [comment]
Hello. I've used both Claymore Dual standalone and NHML's Claymore, and I think NHML doesn't care about dev fee. I think NHML should decrease Claymore shown speed by 2% in order to get real speed & and BTC/day.

**Comment by Nicheuji** [comment]
I don't mind the dev fees but it would be nice to know my exact profits.
@DillonN Would you consider adding this feature to NHML?

**Comment by luongk** [comment]
My understanding is that the numbers that NHML/Nicehash report are net profitability (i.e. after dev fees are taken into account).

**Comment by DillonN** [comment]
NHML does take devfee into account for switching by subtracting it during benchmark. Displayed speed during mining is not affected but it will on the NiceHash miner stats webpage.
