### ISSUE TITLE
PhoenixMiner ELP on last GPU not parsed

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#1880]
Starting from NiceHash Miner 1.9.2.18 PhoenixMiner ExtraLaunchParameters section on last GPU (if 6 cards on rig, then on 6th, if 4 cards, then on 4th etc.) of rig not parsing parameters e.g. -clKernel, -gt etc.
Checked on multiple rigs with various GPUs.
ELPs parsing correctly on NiceHash Miner <=1.9.2.17.

**Comment by S74nk0** [comment]
@cyberunknown Can you please double check that the flags are present for each Device/Algorithm pair. If you don't mind upload the `device_settings_UUID.json` files for me to check. I suspect that the issue is with the settings. 

The source code for ELP parsing is identical between these versions. This logic wasn't modified for the last 10 versions for sure. I have checked from **1.9.2.9** to **1.9.2.19** this is identical. 
All these are identical
**1.9.2.9**
https://github.com/nicehash/NiceHashMiner/blob/1.9.2.9/src/Miners/MinerPluginToolkitV1/MinerBase.cs#L126
**1.9.2.19**
https://github.com/nicehash/NiceHashMiner/blob/1.9.2.19/src/Miners/MinerPluginToolkitV1/MinerBase.cs#L126
If you change the version in the URL (between `/blob/1.9.2.19/src/`) you will see it is exactly the same. 

The packaged **MinerPluginToolkitV1.dll** (here the parsing happens) is identical from **1.9.2.16** to **1.9.2.19**:
```
$ sha1sum.exe MinerPluginToolkitV1.dll
e36e2dbfa751e925d40e369f0fd9978fc7601aed *MinerPluginToolkitV1.dll
```

If

> ELPs parsing correctly on NiceHash Miner <=1.9.2.17

I can only suspect that the settings are missing these flags. Please send the settings so we can check if this is the problem. If the settings check out then I will investigate the issue further.

**Comment by ghost** [comment]
Here is the device_settings_*.json
[device_settings.zip](https://github.com/nicehash/NiceHashMiner/files/3921929/device_settings.zip)
All necessary flags enabled.

**Comment by S74nk0** [comment]
@cyberunknown can you also send the logs please. Run nhm start mining and send me the logs after so I can check the parsers output.

**Comment by ghost** [comment]
Here is the logs from PhoenixMiner and NiceHash Miner.
[log20191204_180512.txt](https://github.com/nicehash/NiceHashMiner/files/3922024/log20191204_180512.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/3922025/log.1.txt)

Maybe this help you to find a bug: I replaced PhoenixMiner.exe 4.8c from 1.9.2.19 with 4.7c binaries from 1.9.2.17 and now all parsed correctly)))

**Comment by S74nk0** [comment]
@cyberunknown thanks for the logs and feedback. We will investigate this further.

**Comment by ghost** [comment]
Ok thanks. But here is the another thing:

from PhoenixMiner log:

> 2019.12.04:18:05:12.676: main Phoenix Miner 4.8c Windows/msvc - Release build
> 2019.12.04:18:05:12.676: main Cmd line: **-di 012345** -epool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 -ewal 3PshQogdusjEttiFpRAsWtt1GHv3gSU6pC$0-aysgEc4JtVSsoG6u-jaFyw -esm 3 -epsw x -allpools 1 -mi 13,13,13,13,13,13 -gt 46,40,40,35,44,41 -clKernel 3,3,3,3,3,3 -wd 0 -amd -mport 127.0.0.1:-4000 
> 2019.12.04:18:05:14.344: main OpenCL driver version: 18.5.1
> 2019.12.04:18:05:14.368: main Available GPUs for mining:
> 2019.12.04:18:05:14.368: main GPU1: Radeon RX 580 Series (pcie 1), OpenCL 2.0, 8 GB VRAM, 36 CUs
> 2019.12.04:18:05:14.368: main GPU2: Radeon RX 580 Series (pcie 3), OpenCL 2.0, 8 GB VRAM, 36 CUs
> 2019.12.04:18:05:14.368: main GPU3: Radeon RX 580 Series (pcie 4), OpenCL 2.0, 8 GB VRAM, 36 CUs
> 2019.12.04:18:05:14.368: main GPU4: Radeon RX 580 Series (pcie 5), OpenCL 2.0, 8 GB VRAM, 36 CUs
> 2019.12.04:18:05:14.368: main GPU5: Radeon RX 580 Series (pcie 6), OpenCL 2.0, 8 GB VRAM, 36 CUs
> 2019.12.04:18:05:14.368: main GPU6: Radeon RX 580 Series (pcie 7), OpenCL 2.0, 8 GB VRAM, 36 CUs
> 2019.12.04:18:05:14.370: main ADL library initialized
> 2019.12.04:18:05:15.696: main Eth: the pool list contains 1 pool (1 from command-line)
> 2019.12.04:18:05:15.696: main Eth: primary pool: daggerhashimoto.eu.nicehash.com:3353
> 2019.12.04:18:05:15.696: main Starting GPU mining

I'm think this parameter `-di` is for Claymore's Miner and I don't find this in Readme.txt of PhoenixMiner but NiceHash Miner always start by default with him.

Here is the quote from PhoenixMiner's **ReleaseNotes.txt**:

> PhoenixMiner 4.8c
> -----------------
>  - **Added command-line option -gbase** to set 0-base or 1-based GPU indexes **(the default is 1)**
>    **With -gbase 1 (the default), the first GPU is GPU1**, then GPU2, etc. With -gbase 0
>    the first GPU is GPU0, second - GPU1, etc. Note that this also changes the indexes
>    that are used with all command line options that accept GPU indexes (e.g. -gpus)
>    as well as these used with the interactive commands on the miner shell window

So... NiceHash Miner always launch the miner with `-di` starts `0`, but PhoenixMiner don't understands this Claymore's parameter (I'm guess 😄) and starting from version 4.8c uses `-gbase 1` by default.

Quote from Claymore's Dual Ethereum GPU Miner **Readme.txt**:

> **-di**    GPU indexes, default is all available GPUs. For example, if you have four GPUs "-di 02" will enable only first and third GPUs (#0 and #2).
>    You can also turn on/off cards in runtime with "0"..."9" keys and check current statistics with "s" key.
>    For systems with more than 10 GPUs: use letters to specify indexes more than 9, for example, "a" means index 10, "b" means index 11, etc; also "a", "b", and "c" keys allow you to turn on/off GPU #10, #11 and #12 in runtime.

Or... `-di 012345` conflict with `-gbase 1` starting from 1.9.2.18.

**Comment by luc1an24** [comment]
Hi @cyberunknown 
Because of your help we managed to find the issue with the indexing.
New release of Phoenix miner has changed the way gpus are indexed.
This is fixed now, so please update the plugin and everything should work as expected.

Thank you again!
