### ISSUE TITLE
Profitability Calculator

### ISSUE THREAD

**Issue by FatShady2017** [nicehash/NiceHashMiner#189]
Hi!

My screen says I am earning 12usd/day but when I check on the online profitability it just says 7usd/day.
Is this a possible bug? which is the correct one? Tried to way for hours for the web to sync data but to no avail?

Thanks

**Comment by streaml1ne555** [comment]
I believe the online calculator is based on the past 30 days. I've noticed this behavior as well.

**Comment by liranscu** [comment]
the Profitability Calculator is not correct , it give us a beautiful hope ,but not the true ,big different

**Comment by DillonN** [comment]
It shows average over the past 30 days which is most useful info, and you can look at different values on the page for other time periods. Regardless this is not a NHML issue
