### ISSUE TITLE
Extra launch parameters not recognized by XmrStakRx

### ISSUE THREAD

**Issue by dandrea2** [nicehash/NiceHashMiner#1891]
In the Benchmark window, Extra Launch Parameters has "--noTest" to skip the startup test, but whenever XmrStakRx starts, it still does the test.  This is with NiceHash Miner 1.9.2.19 and XmrStakRx plugin 4.1 (binary 1.0.2-rx).  Noticed there was a plugin update to 4.3 (same binary version) and applied it, but it still ignores the setting.

Benchmark:
![image](https://user-images.githubusercontent.com/25312549/70768196-b83b9a80-1d29-11ea-9420-7df98f998019.png)

The command window:
![image](https://user-images.githubusercontent.com/25312549/70768215-cd182e00-1d29-11ea-9861-c8475a11ce32.png)

**Comment by luc1an24** [comment]
Hi @dandrea2 
Thank you for reaching out. We updated the plugin with the fix.
Please update it in your plugins page.

Have a nice mining!
