### ISSUE TITLE
[Suggestions to improve UX] OC profiles, benchmarking crashes, improving stability, and other quality of life improvements

### ISSUE THREAD

**Issue by scscgit** [nicehash/NiceHashMiner#1895]
I would like to make a suggestion for a major improvement of the user experience of the client. First I'd like to make sure if there are enough people who share my mining stability issues, considering that I've suffered from them countless times as a long term user. I believe we should strive for the best possible framework before the next price bubble comes along with currently unknown miners, drivers and hardware, which will be even more unstable in a diverse environment focused on optimization and overclocking. I believe some of these features could even be implemented by a community as long as we agree on the specification.

* `Benchmark profiles for overclocking (CPU/GPU)` - There is currently only one profile, yet an average user most likely keeps tweaking OC parameters like clock or memory. Not only does the algorithm efficiency differ, but so does the stability. A naïve approach would be to push the memory clock to the stable maximum and to then run the benchmark. I bet thousands of people implicitly follow the same mistake before they realize that different algos have different requirements. The current implementation never lets us to use the best OC along with algo-switcher, so we are forced to use conservative values, which reduces NiceHash profits. Benchmark profiles would prevent endless benchmark resets, let us disable unstable algos, prevent the user-unfriendly implicit corruption of benchmarks (whenever we forget about previous OC settings / run benchmarks under a load / experiment with new algos), and would support further development of features like applying a third party OC profile (which some miners already support) (this feature could even enable auto-profile-switching based on some algo weights, but I'd be fine manually switching between profiles like test, several algo-specific max performances, and power saving). There's one related issue: https://github.com/nicehash/NiceHashMiner/issues/29.

[Now, the most important feature]

* `Benchmark crashing algorithms` - I've lost track of how many times my OS has **crashed during the benchmark process**, or even worse, **during/after the switch** to a different algorithm. I believe those two scenarios should be treated **separately**. Whenever a process of benchmarking the algorithm is interrupted, it should be **explicitly marked as unsafe**, probably with some counter of how many times the same issue has occurred. Of course, it should first apply some **basic elimination method** right after multiple algorithms ran at once. Imagine this as a part of a setup with auto-start. If you leave your computer to benchmark some set of overclock settings, it could safely gather data from dozens of algorithms and mark all the unstable ones without any supervision. Instead, it currently forces every user to spend literally dozens of hours by fighting your software whenever any little detail doesn't feel deterministic. When it comes to the second scenario, it's obvious that no user would prefer their crashing algorithm to keep trying after, let's say 10 attempts? All I'm asking for is a checkbox along the lines of "**Automatically apply elimination method and suspend an algorithm after it crashes several times**". Something like "**suspended**" could, by the way, be another alternative to "**error**" and "**disabled**". The current implementation literally forces me to write my own notes into notepad about which algorithm on which gpu is disabled due to errors, so I can distinguish it from those disabled by default. I hope I'm not alone :) By the way as a motivation, an obvious major use-case is that this can naturally occur on some GPU whenever any miner gets updated.

* `Be explicit about which algorithms apply overclock` - As it stands, for example when I change my GPU core value to the minimum in order to save energy, sometimes I check the MSI Afterburner and notice that my power usage is back up. This can even be fatal if someone sets up an under-dimensioned power source. We need some kind of guarantee in an algo-switching environment.

* `Try to proactively help users detect unexpected overclock changes` - If possible, it would be great if you could come up with a means to prevent running miner processes under a dangerous environment. For example, after the PC restarts, some app like MSI Afterburner may incorrectly reset the OC settings, and there could be users who would prefer the miner not to run in those circumstances.

* `Per-algorithm guidelines` - There currently isn't any very user friendly way to find out about all the conditions and, let's say, reference baselines. For example, I've tried RandomX on my computer with 4GB RAM, only to find out that my OS had frozen, as it usually is with many algos. Luckily I found out about the larger RAM requirement and after equipping another 4GB, it's finally mining. I understand that there's some requirement to constantly research everything when you are a miner, but please, try to make our life easier if it's possible :) There should be usually either some whitelist, or at least a blacklist for GPUs/features. And more importantly, the abstract list of algorithms doesn't really hint upon whether it's even worth using it. The [profitability calculator](https://www.nicehash.com/profitability-calculator) is probably the only relevant tool, at least to find out if there's any huge trend we may be missing :) For example, if nothing else, I think that a very interesting metric would be "approximate % of users currently using this algorithm", and it would be also quite easy to research the compatibility if a GPU-specific usage were reported. That's just one idea, but nothing beats a brief official guideline.

* `Reference benchmarks and their payrates` - Honestly, why do we even strictly have to go through the effort of benchmarking everything if most of us use the most standardized CPUs and GPUs? I mean, wouldn't it be neat if we were provided a visual feedback like "91% of a reference mining rate" on top of our benchmark values? At least we'd instantly notice if something went horribly wrong. And I don't understand why can't we be always provided the "expected payrate" per algorithm. That's basically the first information every new user seeks for their instant gratification :) If you provide some interface that supports a community-driven spreadsheet, you wouldn't have that much responsibility over accurate data (of which I believe you have planety, but let's not waste bandwidth by invoking your API every time). This would also implicitly mean that there's no longer any reason not to alert user when he forgets to install the most efficient miner :)

* `Run benchmark for an outlier detection (or at least schedule a benchmark refresh later)` - There is currently only one set of measured values, which doesn't mean anything to the user in relative terms. There's always some risk of benchmark not being 100% trustworthy, so I'd prefer the option of a dry run which only serves to double-check if any value drifts by a large percentage from a baseline.

* `Along with proactive OS crash measurement, there's a further need to prevent corruption of config files` - There's a long-lasting issue of your client (and many other apps on Windows) that when OS crashes (usually when it happens during startup), sometimes the config file gets corrupted and some data disappers on the next run - usually it's the miner name and address, which obviously creates huge issue of a downtime, or worse, completely losing critical settings and/or benchmarks. I don't see why this shouldn't be of a high priority - of course, power users can set up their own scripts to extract the config zip, but it's just annoying to always remember to back up changes.

* `Seriously force PC to restart whenever a miner gets stuck` - I don't care if it has to be some direct CPU instruction to force a BSOD, but there are situations when a miner gets stuck (usually after algo switch), often in a way that the OS seems responsive, but the old cmd window stays open, and when I click to close that window, then most of the system apps stop responding. Detection of these situations should be included in the `Benchmark crashed algorithms` process. I guess it could be as simple as **checking for the title of the open process as a string**, and not letting the second miner start until the first one was closed? After all, it should be just an optional feature anyway. There are situations where a hardware watchdog really helps, but I hope someone can also come up with a proper alternative solution.

* `GPU sometimes disappears from NiceHash in spite of being detected under Device Manager` - I found that as a solution (other than reinstalling the driver using stuff like DDU and praying) I could often just go to the Device Manager, select to update the driver, select from the list of installed drivers, update it using the same driver, and restart. However, I haven't seen similar stories from other people. If anyone else has the same issue, then it should be addressed.

* `After reinstalling GPU physically or as a driver, sometimes benchmark data gets lost (a new id gets generated)` - maybe try to ask user to assign the previously used values of a same GPU type right after this happens? After all, it's a shame that GPUs don't provide something unique like a MAC address, it hurts even more when you also lose the OC values this way.

* `Restart a miner if it has unsufficient hashrate / under some dynamic condition` - I've had an issue on my Intel CPU a long time ago, such that the miner would sometimes start incorrectly and become slow. I haven't had this issue recently, so it isn't that important, but it could be addressed if anyone has a use-case for it.

* `Allow multi-selection (CTRL or SHIFT) in the list of GPU benchmarks` - Please. Also the ESC key could close the Benchmark/Settings/Plugins windows.

* `LessThreads doesn't seem to work` - Maybe you could update the documentation, or even better, add it to the GUI.

* `In the future you could also think about integrating some sandbox approach` - We obviously can't run the miners on our main work computers due to security concerns - antiviruses are so irresponsible with their "all or nothing" approach, so we either completely whitelist an unknown executable, or it gets killed because it's a known miner. No middle ground such that the app isn't let to do anything actually dangerous. I believe it wouldn't be unreasonable to use software like Sandboxie to explicitly disable file access except one directory, and to possibly apply some additional protective measures. I would like to see any initiative in this direction.

**Comment by Dohtar1337** [comment]
Thanks for the extensive feedback!

Most of these features won't be implemented due to internal reasons.

But I did put the "DRY BENCHMARK RUN" to the idea backlog. 

Some features are already somewhat implemented like restarting the miner.
