### ISSUE TITLE
Feature Request: Default Miners for Nvidia - Select All

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#19]
I have the Nvidia 1080 Tis and various miners (especially the new dual ones) are unchecked by default

Any reason to not check them all by default (I checked them all and they all benchmarked).  Anything I am missing? :)

**Comment by DillonN** [comment]
They were left unchecked for the sake of inexperienced users since these algos may be more troublesome. Now that NHML is geared toward experienced users only, I don't see any issue with enabling these by default

**Comment by MonaxDK** [comment]
It would also be nice to add the "select all" checkbox to quickly enable / disable all algorithms.

**Comment by DillonN** [comment]
As of 56c15c0 the dual algorithms are now enabled by default. Some others are still left disabled as they are experimental.

@MonaxDK you can select/deselect all by right clicking in the algorithm list

**Comment by billmcilhargey** [comment]
Ok thank you!  was going to mention two are left unchecked and everything else is checked

Thanks! closing this up
