### ISSUE TITLE
XMRig RandomXmonero Error

### ISSUE THREAD

**Issue by KirimoarOld** [nicehash/NiceHashMiner#1904]
I'm trying to mine on a Ryzen 1700 CPU, but always getting the following error:

_Error occured while getting API stats: Error converting value {null} to type 'System.Double'. Path 'hashrate.highest', line 58, position 23._

 I'm not using any extra launch parameters.

When launching with _.\xmrig.exe -a rx/0 -o randomxmonero.eu.nicehash.com:3380 -u YOUR_BTC_ADDRESS --http-enabled -http-port=4000 --nicehash --log-file=output.txt_ the output.txt says nothing especially, the miner just closes.

` * ABOUT XMRig/5.3.0 MSVC/2019

    * LIBS libuv/1.34.0 OpenSSL/1.1.1d hwloc/2.1.0

    * HUGE PAGES permission granted

    * 1GB PAGES unavailable

    * CPU AMD Ryzen 7 1700 Eight-Core Processor (1) x64 AES

    L2:4.0 MB L3:16.0 MB 8C/8T NUMA:1

    * MEMORY 4.5/15.9 GB (28%)

    * DONATE 5%

    * ASSEMBLY auto:ryzen

    * POOL #1 randomxmonero.eu.nicehash.com:3380 algo rx/0

    * COMMANDS hashrate, pause, resume

    * HTTP API 127.0.0.1:49541

    * OPENCL disabled

    * CUDA disabled

    [2019-12-25 10:46:03.076] net use pool randomxmonero.eu.nicehash.com:3380 172.65.194.253

    [2019-12-25 10:46:03.077] net new job from randomxmonero.eu.nicehash.com:3380 diff 132962 algo rx/0 height 1996535

    [2019-12-25 10:46:03.077] msr to write MSR registers Administrator privileges required.

    [2019-12-25 10:46:03.077] rx init dataset algo rx/0 (8 threads) seed 8fd8d3ee74547743...

    [2019-12-25 10:46:03.083] rx allocated 2336 MB (2080+256) huge pages 100% 1168/1168 +JIT (6 ms)

    [2019-12-25 10:46:06.276] rx dataset ready (3193 ms)

    [2019-12-25 10:46:06.277] cpu use profile rx (8 threads) scratchpad 2048 KB

    [2019-12-25 10:46:06.493] cpu READY threads 8/8 (8) huge pages 100% 8/8 memory 16384 KB (215 ms)`

However, with the default config.json and URL ""url": "donate.v2.xmrig.com:3333",", it works and keeps running.

Any ideas?

**Comment by luc1an24** [comment]
Hi @Kirimoar 
It looks like some config issue
Could you try to put our url (randomxmonero.eu.nicehash.com:3380) in the config and use your own btc address?
If you tried any other method in the mean time please do tell.

**Comment by KirimoarOld** [comment]
Hi,

i tried it with the URL and the btc-address, and after that it says "unknown algo", as it is not set. When I set the algo to "rx/0" then, and the same happens again.

Most of the time it just closes after some seconds, sometimes 1 or even 2 shares are even accepted, but then it closes again. I also tried disabling "OP-Cache" in BIOS, tried other OC-Settings of the CPU and a BIOS-Update, but nothing helped.

Any other ideas?

**Comment by KirimoarOld** [comment]
xmrig version 5.5.0 has been released, and it seems that the problem was fixed with it. (it even says "#1465 Added fix for 1st-gen Ryzen crashes." in the release notes.)

Therefore, please integrate version 5.5.0 into Nicehash, then it hopefully works again as expected.

**Comment by luc1an24** [comment]
Thank you for your help.
I will integrate the version into NHM as soon as possible.

**Comment by luc1an24** [comment]
Hi @Kirimoar 
The new xmrig is updated as plugin to Xmrig version 5.5.0
Have a nice mining
