### ISSUE TITLE
Nicehash error amd mot benchmarking on one gpu

### ISSUE THREAD

**Issue by lucky2213** [nicehash/NiceHashMiner#1905]
hey so im running a gtx 1060 4gb and rx 570 8gb card and the 1060 is mining just fine but the 570 is showing the status as error and not benchmarking ether. Anybody have a clue on how to fix it? Any help would be great and much apercaited 

![2019-12-26](https://user-images.githubusercontent.com/52269880/71495957-19796880-2816-11ea-939f-6ad9864a0a06.png)

**Comment by luc1an24** [comment]
Xmr-stak is not very fond of AMD cards. 
Please choose another miner that is used for AMD cards - claymore, gminer, xmrig...

**Comment by luc1an24** [comment]
Closing issue, can't do much here since of the incompatibility between miner and gpu.
