### ISSUE TITLE
NBMiner use a wrong card....

### ISSUE THREAD

**Issue by Twigho** [nicehash/NiceHashMiner#1912]
Hello,
Setup : 1080ti, 1070 (x2)

When I bench 1080ti with NBMiner Algo : Result is instant "NONE"
When I bench a 1070 with NBMiner Algo : NBMiner use 1080Ti  NOT 1070 

It is a second post about this. This problem exist since NHM 1.9.2.19 (minimum) 

Obviously, I perform some clean install of NMH and drivers...

GL

**Comment by suxxer1** [comment]
+1

**Comment by luc1an24** [comment]
Hi @Twigho and @suxxer1 
Thank you for reaching out.
Could you please send us your configuration/device/log report created by "CreateLogReport.exe" (program in root folder)

This will help us troubleshoot the problem.
Thank you!

**Comment by suxxer1** [comment]
"DeviceDetectionPrinter.exe cuda p" 
{"NvmlLoaded":true,"NvmlLoadedFallback":false,"CudaDevices":[{"DeviceID":0,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-4d1dc73b-3606-3b3d-c2dd-e810fd19efbc","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":856560738,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":1},{"DeviceID":1,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-941d0b66-c844-a857-874c-474579f92cd0","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":855774306,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":3},{"DeviceID":2,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-f04ed507-5d4c-11c2-a514-059464b2478d","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":855774306,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":4},{"DeviceID":3,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-9d13e753-a2a6-62cb-d61e-9b9bfcf3357a","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":856560738,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":6},{"DeviceID":4,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-16e1585e-b5fb-5aa0-57de-b7adee15de78","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":856560738,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":8}],"DriverVersion":"416.34","ErrorString":""}
 
"DeviceDetectionPrinter.exe ocl p" 
{"Platforms":[{"PlatformNum":0,"PlatformVendor":"NVIDIA Corporation","PlatformName":"NVIDIA CUDA","Devices":[{"DeviceID":0,"BUS_ID":1,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""},{"DeviceID":1,"BUS_ID":3,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""},{"DeviceID":2,"BUS_ID":4,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""},{"DeviceID":3,"BUS_ID":6,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""},{"DeviceID":4,"BUS_ID":8,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""}]}],"Status":"OK","ErrorString":""}
 
"copy .\OpenCL\OpenCL.dll .\OpenCL.dll" 
 
"DeviceDetectionPrinter.exe cuda p" 
{"NvmlLoaded":true,"NvmlLoadedFallback":false,"CudaDevices":[{"DeviceID":0,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-4d1dc73b-3606-3b3d-c2dd-e810fd19efbc","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":856560738,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":1},{"DeviceID":1,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-941d0b66-c844-a857-874c-474579f92cd0","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":855774306,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":3},{"DeviceID":2,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-f04ed507-5d4c-11c2-a514-059464b2478d","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":855774306,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":4},{"DeviceID":3,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-9d13e753-a2a6-62cb-d61e-9b9bfcf3357a","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":856560738,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":6},{"DeviceID":4,"VendorName":"MSI","DeviceName":"GeForce GTX 1070","SM_major":6,"SM_minor":1,"UUID":"GPU-16e1585e-b5fb-5aa0-57de-b7adee15de78","DeviceGlobalMemory":8589934592,"pciDeviceId":461443294,"pciSubSystemId":856560738,"SMX":15,"VendorID":5218,"HasMonitorConnected":0,"pciBusID":8}],"DriverVersion":"416.34","ErrorString":""}
 
"DeviceDetectionPrinter.exe ocl p" 
{"Platforms":[{"PlatformNum":0,"PlatformVendor":"NVIDIA Corporation","PlatformName":"NVIDIA CUDA","Devices":[{"DeviceID":0,"BUS_ID":1,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""},{"DeviceID":1,"BUS_ID":3,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""},{"DeviceID":2,"BUS_ID":4,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""},{"DeviceID":3,"BUS_ID":6,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""},{"DeviceID":4,"BUS_ID":8,"_CL_DEVICE_NAME":"GeForce GTX 1070","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":8589934592,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"416.34","_CL_DEVICE_BOARD_NAME_AMD":""}]}],"Status":"OK","ErrorString":""}
 
"del .\OpenCL.dll"
