### ISSUE TITLE
1.9.2.15 1.9.2.20 no supported devices , 3.0.0.0 Alpha does not start  . 2.0.3.1 beta work fine

### ISSUE THREAD

**Issue by SyavaK** [nicehash/NiceHashMiner#1918]
win 7 x64 4gb ram 5xGeForce GTX 1060 6GB

![2020-01-11_22-16-46](https://user-images.githubusercontent.com/19762395/72210192-7c2e5d80-34c0-11ea-8cd7-08e077cc3f3f.jpg)
![2020-01-11_22-16-00](https://user-images.githubusercontent.com/19762395/72210194-7f294e00-34c0-11ea-9c20-6f922be78b47.jpg)

device_detection_test_output.txt

`"DeviceDetectionPrinter.exe cuda p" 
{"NvmlLoaded":true,"NvmlLoadedFallback":false,"CudaDevices":[{
"DeviceID":0,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-2d290fc9-c9b3-af88-aff6-598133289c48","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":1,"pciBusID":1
"DeviceID":1,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-e4ad636c-45b9-cbce-911d-2088fea16135","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":0,"pciBusID":2
"DeviceID":2,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-c56d8a1e-4c50-bdb7-2630-26c60d3585c3","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":0,"pciBusID":3
"DeviceID":3,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-72e92a8d-4381-b124-7cc2-4a4db501df68","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":0,"pciBusID":4
"DeviceID":4,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-204d9198-a46d-2bb6-a0c8-50396c211c8f","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":0,"pciBusID":5}],"DriverVersion":"441.08","ErrorString":""}
 
"DeviceDetectionPrinter.exe ocl p" 
{"Platforms":[{"PlatformNum":0,"PlatformVendor":"NVIDIA Corporation","PlatformName":"NVIDIA CUDA","Devices":[{
"DeviceID":0,"BUS_ID":1,"_CL_DEVICE_NAME":"GeForce GTX 1060 6GB","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":6442450944,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"441.08","_CL_DEVICE_BOARD_NAME_AMD":""
"DeviceID":1,"BUS_ID":2,"_CL_DEVICE_NAME":"GeForce GTX 1060 6GB","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":6442450944,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"441.08","_CL_DEVICE_BOARD_NAME_AMD":""
"DeviceID":2,"BUS_ID":3,"_CL_DEVICE_NAME":"GeForce GTX 1060 6GB","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":6442450944,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"441.08","_CL_DEVICE_BOARD_NAME_AMD":""
"DeviceID":3,"BUS_ID":4,"_CL_DEVICE_NAME":"GeForce GTX 1060 6GB","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":6442450944,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"441.08","_CL_DEVICE_BOARD_NAME_AMD":""
"DeviceID":4,"BUS_ID":5,"_CL_DEVICE_NAME":"GeForce GTX 1060 6GB","_CL_DEVICE_TYPE":"GPU","_CL_DEVICE_GLOBAL_MEM_SIZE":6442450944,"_CL_DEVICE_VENDOR":"NVIDIA Corporation","_CL_DEVICE_VERSION":"OpenCL 1.2 CUDA","_CL_DRIVER_VERSION":"441.08","_CL_DEVICE_BOARD_NAME_AMD":""}]}],"Status":"OK","ErrorString":""}
 
"copy .\OpenCL\OpenCL.dll .\OpenCL.dll" 
 
"DeviceDetectionPrinter.exe cuda p" 
{"NvmlLoaded":true,"NvmlLoadedFallback":false,"CudaDevices":[{
"DeviceID":0,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-2d290fc9-c9b3-af88-aff6-598133289c48","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":1,"pciBusID":1
"DeviceID":1,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-e4ad636c-45b9-cbce-911d-2088fea16135","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":0,"pciBusID":2
"DeviceID":2,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-c56d8a1e-4c50-bdb7-2630-26c60d3585c3","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":0,"pciBusID":3
"DeviceID":3,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-72e92a8d-4381-b124-7cc2-4a4db501df68","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":0,"pciBusID":4
"DeviceID":4,"VendorName":"ASUS","DeviceName":"GeForce GTX 1060 6GB","SM_major":6,"SM_minor":1,"UUID":"GPU-204d9198-a46d-2bb6-a0c8-50396c211c8f","DeviceGlobalMemory":6442450944,"pciDeviceId":469962974,"pciSubSystemId":2246119491,"SMX":10,"VendorID":4163,"HasMonitorConnected":0,"pciBusID":5}],"DriverVersion":"441.08","ErrorString":""}
 
"DeviceDetectionPrinter.exe ocl p" 
UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.

 
"del .\OpenCL.dll" 
`

**Comment by N8Thrasher** [comment]
NHM 3.0 not working on my PC either, nothing appears but saw it on task manager briefly then gone. logs doesnt say anything.

**Comment by hexthat** [comment]
I didnt even know there was a Version 2. For me it just went from 1.9.2.22 to 3.0.0.3.... Like wow who decided to skip version 2?

**Comment by SyavaK** [comment]
UPDATE
3.0.0.4 = no supported devices
3.0.0.5 = work fine
