### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by sorg111** [nicehash/NiceHashMiner#192]
![f2](https://user-images.githubusercontent.com/29475386/29504989-22dea7d2-864c-11e7-8a90-a22643346802.jpg)

**Comment by sebeksd** [comment]
Similar or same issue to #166

**Comment by Spoob** [comment]
Similar behavior. A couple of days as it began. I have a restart from time to time due to problems with the power supply. At startup, the client can not receive data from the server. Experienced, I found that this is how 1.8.1.0 and 1.8.1.1 behave. If you use an older version, for example 1.8.0.2 - it connects stably without problems. She's older, but better than not.
A similar topic is in the neighborhood

**Comment by sorg111** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/releases NHML-1.8.1.1.zip for win 7 x64  solved the problem
thank you all for the help

**Comment by Spoob** [comment]
1.8.0.2 does not solve the problem. When restarting, it can also stand and wait for the solution to report that there is no Internet connection. But the connection is there. I connect remotely
I tried today to reinstall 1.8.1.1 - does not help

**Comment by Spoob** [comment]
![screenshot_2017-08-21-07-21-57-922_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/29872738/29509127-d4776296-865f-11e7-9519-a40e445f1afe.png)
![screenshot_2017-08-21-07-21-30-208_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/29872738/29509128-d4775a08-865f-11e7-8afd-baf183d3d0c9.png)

**Comment by DillonN** [comment]
This error pops up when NHML cannot connect to the NH servers which can be because the server is under maintenance, internet problems, or FW blocking NHML. 

@Spoob in your first screenshot it looks like the error box popped up behind the NHML window

**Comment by Spoob** [comment]
In fact, when loading, the progress indicator stops as in the second picture (getting the information of the NH SMA). If you try to close the NH window hangs. In the top of the window it is written that the program does not respond.
If the NH is removed from the processes and run again, it can connect normally. But it happened that I could not connect several races in a row. While the older version (up to 1.8.1.0) is connected to a lot more stable.
