### ISSUE TITLE
Correct way of writing Extra Launch Prameters ? (Claymore)

### ISSUE THREAD

**Issue by zakblacki** [nicehash/NiceHashMiner#1920]
This may sound stupid, but I'm little confused over the commands to write. 
For example in Claymore we just have to put "--strap=1" or "--donate-level=1"
Do we have to include the " -- " or the " = " and can we use space ? Here is what I'm trying to add in my parameters 
--donate-level=1 enable_ht=true --strap=1 -cclock 1150 -cvddc 900 -mclock 2100 -mvddc 900
I'm I doing it wrong ?

**Comment by khayto** [comment]
curious about this too, was trying to set dual intensity for NBminer ethckb and im getting nowhere, im starting to think the extra launch parameter field just doesnt work lol. ive tried all i can think of.
di 5
di = 5
di=5
-di 5
-di=5
-di = 5
--secondary-intensity 5
--secondary-intensity=5
--secondary-intensity = 5
secondary-intensity 5
secondary-intensity=5
secondary-intensity = 5

none worked.

on a side note imnt surprised, its been over 2 years and not a single iteration of nicehash miner has worked properly for me. Back to rainbow.

**Comment by zakblacki** [comment]
For claymore its only one " -"  without " = " and space so for example -strap 1 works fine basically you need put the miner parameters commands as written in their docs.
