### ISSUE TITLE
Incorrect syntax for Phoenix Miner

### ISSUE THREAD

**Issue by milkcoins** [nicehash/NiceHashMiner#1922]
Correct:
`-gpus 0123456789abcdef`

Wrong:
`-gpus 01234567891112131415`

Wake up, @S74nk0!

**Comment by luc1an24** [comment]
Hi @milkcoins 
Thank you for reaching out.
Fixed plugin is ready to be downloaded.
Please head to plugin section and update it.

Have a nice mining!

**Comment by milkcoins** [comment]
Fixed in Phoenix plugin version 5.2. Thanks.
