### ISSUE TITLE
NHMiner v1.9.2.21 - half of the algos wont benchmark the other just about works.   

### ISSUE THREAD

**Issue by Svyatk0** [nicehash/NiceHashMiner#1924]
Hey guys, 

Not sure whats happening but with each release i am seeing more and more issues and less and less miners working and benchmarking. Firewalls are set correctly, nothing else is blocking the miners. I am seeing constant restarts, connection errors,  Object reference errors etc. and not so much mining these days. 

Happy to provide the logs, but wanted a general opinion if this is just me or others are getting the same treatment.

**Comment by taticahladni** [comment]
Same situation here. I noticed that in plug-ins, there was update to the Gminer, that enabled some of the algs but the problem persists, we can not use main algos and the dual claymore that is working with Blake is turning on just the dagger alg, Blake is refused by the pool, for some reason. I spent all night trying to find the solution and only after i noticed the update, in the morning, few algs started to work.
