### ISSUE TITLE
Restart miner every 5-10-15-30 minutes (without change algo)

### ISSUE THREAD

**Issue by pro-peller** [nicehash/NiceHashMiner#1928]
Hello NHML version is 19.2.21
Every 5-10-15-30 minutes permanent restart miner.
Algorithm not changed.
Bug use case (6x1660Ti work on Cuckaroom), GMiner 1.94
Please fix this bug.

**Comment by S74nk0** [comment]
@pro-peller You can update the GMiner plugin to version **6.2**. **6.2** uses **GMiner 1.95** it should give you a performance increase for **Cuckaroom** algorithm.  Plugin version **6.2** has the API timeout set to 1h15m (this means if the miner doesn't return a response within this time it will restart the miner). If you wish to completely disable the API timeout checker you can do this in the plugin internal settings (https://github.com/nicehash/NiceHashMiner/blob/master/doc/Plugins/InternalSettings/MinerApiMaxTimeoutSettings.md). 

Turn off NiceHash Miner change the settings in ` ~/AppData/Local/Programs/NiceHash Miner/miner_plugins/1b7019d0-7237-11e9-b20c-f9f12eb6d835/internals/MinerApiMaxTimeoutSetting.json` set `use_user_settings` to `true` and `enabled` to `false`. This will disable the checker for GMiner plugin on the next NiceHash Miner start.
```
{
  "use_user_settings": true,
  "enabled": false,
  "general_timeout": "01:15:00",
  "timeout_per_algorithm": {},
  "timeout_per_device_type": {}
}
```
Closing issue
