### ISSUE TITLE
Nicehash Miner 1.9.2.22 is missing miner plugins

### ISSUE THREAD

**Issue by wallaceaskew** [nicehash/NiceHashMiner#1935]
Nicehash Miner 1.9.2.22 is missing miner plugins. In the miner_plugins folder, I'm only seeing the VC_REDIST_x64_2015_2019 and Ethlargement folders.  I copied all remaining folder from 1.9.2.21 and ran into other issues.

**Comment by peteycrack420** [comment]
either  does cuckoo algo  it worked 3 hours ago after the update go to turn it on and the cmd open closes on and off

**Comment by S74nk0** [comment]
@wallaceaskew the pre-installed plugins were missing from the 1.9.2.22 packages. They are included now. Re-install 1.9.2.22 or just manually install miner plugins you want to mine with.

@peteycrack420 please open a new issue regarding your case and we will resolve it there. 

Closing issue
