### ISSUE TITLE
About NHM 3.0.0.2 beta...

### ISSUE THREAD

**Issue by Twigho** [nicehash/NiceHashMiner#1936]
Hello,
- NiceHashMiner.exe on root folder work only one time...
- You must use the executable of the "app_3.0.0.2" folder to be able to use.
- Ethlargement not working when "Run Ethlargement" is checked, with 1080Ti and PhoenixMiner
- After clicking "Start Benchmark" the button stay "Start Benchmark"...
- And a recurrent issue since a few releases : NBminer use a wrong card. (cf other posts)

**Comment by S74nk0** [comment]
3.0.0.3 should have most of these fixed except "NBminer use a wrong card". For the NBminer issue we will push a new plugin update
