### ISSUE TITLE
Status: Error

### ISSUE THREAD

**Issue by mattiasgp40** [nicehash/NiceHashMiner#1938]
I had version 1.9.2.19 that worked fine with a gtx1070TI, update to version 1.9.2.22 and now it has the "status error" in the GPU section, in the main nicehash window, I'm going to benchmark, and it doesn't appear no mining algorithm on the list, I still start the benchmark and says that "a benchmark is not necessary" "current benchmark options already set, nothing needs to be done".

**Comment by kibabiba** [comment]
I have the same problem.

**Comment by S74nk0** [comment]
This was an issue with nhm 1.9.2.22 not shipping with default preinstalled plugins. Manual plugin installation resolves the issue or just download the latest version with the latest preinstalled miner plugin packages. 

Closing issue. Solved in new NiceHash Miner versions
