### ISSUE TITLE
Версия 1.9.2.22 постоянный бенчмарк

### ISSUE THREAD

**Issue by YuriyNa** [nicehash/NiceHashMiner#1944]
При каждом перезапуске программы запускается бенчмарк, хотя все алгоритмы протестированы.

**Comment by S74nk0** [comment]
@YuriyNa Please write in English. Please confirm that your Windows user has write permissions where NiceHash Miner is installed or package is extracted.

**Comment by YuriyNa** [comment]
Each time the program is restarted, the benchmark is launched, although all the algorithms are tested. The same is with version 3.0.0.4, a constant re-benchmark when starting the Cuckaroom algorithm program.

**Comment by S74nk0** [comment]
@YuriyNa This sounds like your user doesn't have permissions to write to the path. Please post the logs. Also on what path is NHM installed?

**Comment by YuriyNa** [comment]
The default setting, the problem is with only one algorithm. Two different rigs, the behavior is the same.
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/4154049/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/4154050/log.txt)
