### ISSUE TITLE
Version 2 is missing. Why skip it completely?

### ISSUE THREAD

**Issue by hexthat** [nicehash/NiceHashMiner#1949]
Where are version 2 of nicehash in the releases? Who decided to skip it?

**Comment by jwesolo** [comment]
There was a version 2 but they scrapped it a number of months ago for a number of reasons. I'm sure they chose to go from 1 to 3 now to avoid confusion with the old product.

**Comment by S74nk0** [comment]
@hexthat like @jwesolo pointed out we already had Version 2 out that was using a completely different software stack and our proprietary excavator miner only. Both excavator and NiceHash Miner 2 have been discontinued. 
We have restored NiceHash Miner Legacy back to original NiceHash Miner name, and we have gradually made improvements to the core and with the new GUI we have decided to change the major version to 3 (to avoid confusion with the discontinued version 2)

Closing issue
