### ISSUE TITLE
v3.0.0.3 NHM starts mining upon completion of benchmarking

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1954]
When benchmarking finishes, NHM immediately begins mining. This is not the desired behavior. There used to be a checkbox for this but I cannot find it now. Please reimplement this option or point out where it has been moved to.

Thanks!

**Comment by lordzardos** [comment]
I agree.... I do not like the current behavior when benchmarking (from the benchmarking tab) where it starts mining when a card's benchmarking is done.

**Comment by Dohtar1337** [comment]
Moved to idea backlog. Closing to clean the issues.
