### ISSUE TITLE
v3.0.0.3 Profitability in FIAT per device in Devices tab

### ISSUE THREAD

**Issue by erictardif** [nicehash/NiceHashMiner#1957]
It would be useful to know the profitability in fiat for each devices that is currently mining. We only see the total for all devices in the top of Devices tab.

I use that information for example my CPU and older GPUs to easily detect when profits are too small.
I would then disable mining on those temporarily or even decide to sell GPUs that have became not enough profitable.

So with v3, if i want to know that, i have to disable all devices but 1 and mine with it for a bit.
And would have to iterate through all the devices that i want to be informed on.

An option toggle to add this info in the Devices tab would be great, even if disabled by default,

Thanks for considering.

**Comment by jwesolo** [comment]
+1 Missed this one in my collection of requests yesterday. The new version should show, at the very least, all the information that was available in the old version.
