### ISSUE TITLE
nicehash V3.xx dose not work

### ISSUE THREAD

**Issue by Nacobo** [nicehash/NiceHashMiner#1959]
nicehash V3.xx dose not work at all or open a window when executed, had to revert to v1.9.2.22.

**Comment by ewlad751043** [comment]
same problem

**Comment by S74nk0** [comment]
Please make sure that you have  https://dotnet.microsoft.com/download/dotnet-framework 4.7.2 or 4.8 installed. 

Close this issue if framework installation fixes your problem.

**Comment by S74nk0** [comment]
Please try https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.0.4 for Windows 7. This version should be compatible with Windows 7.

If you are using Windows 7 and this fixes your problem please close this issue.

**Comment by Nacobo** [comment]
after new relese it worked
