### ISSUE TITLE
Always benchmark after update the new version + [Suggestion] Auto Server

### ISSUE THREAD

**Issue by underway113** [nicehash/NiceHashMiner#196]
i wanna ask, is it possible to bring the old benchmark data to new version. so miner dont have to always benchmark after download updated/newer version.

Second,  just for suggestion feature in next version. could you make auto server.. 
sometimes i use Server China, and suddenly its down temporarily. Nicehash just want to reconnect to same server (China). 
it's better to connect to other server with small ping , in my case Server Japan.

thanks for ur help and attention 👍

**Comment by drkskwlkr** [comment]
> is it possible to bring the old benchmark data to new version. so miner dont have to always benchmark after download updated/newer version.

Of course it is possible. Just extract new version over old version and keep the contents of the `configs` subfolder, or copy `configs` from the old version to the new if you don't want to overwrite. The benchmarks for each GPU and CPU are stored there as separate .json files.

**Comment by underway113** [comment]
@drkskwlkr okay, pardon me, i forgot to read the wiki.. appreciate that for ur answer
