### ISSUE TITLE
Connection refused in log

### ISSUE THREAD

**Issue by yearight** [nicehash/NiceHashMiner#1961]
Hi.
1 of my AMD cards (R380) on the same rig shows as mining and show profit in the program. On the website it shows mining hashrate in rig manager, but never a profit, unpaid balance or accepted speed in history and stats. 
I've tried different algos, and stopped it from mining to see if my payouts dropped and they didn't. 
Looking in the log shows the connection refused error.
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/4143326/log.1.txt)

**Comment by S74nk0** [comment]
@yearight this sound like an issue with the service and not NHM Client. Please contact for help (https://www.nicehash.com/support). 

Closing issue not relater to NHM Client.
