### ISSUE TITLE
NHM v3.0.0.3 running as elevated task is invisible

### ISSUE THREAD

**Issue by mrMad-Cat** [nicehash/NiceHashMiner#1962]
**In short:**
While running NHM v3.0.0.3 as an elevated task it runs in "invisible mode" (it can be seen together with the miner plugins only in the list of apps in the Task manager), but you can't open it, only kill the apps.

**Proposal:**
Fix this and additionally make some changes so it can be finally autostarted with admin privileges without user prompt.

**More info:**
NHM always had problem that it required administrative privileges for some features (like automatically setting the Nvidia P2 state or running the Eth...Pill). In a normal safe Win10 environment running a program in such state trigs a user prompt. This means that every time the PC is rebooted it waits for user to push the button before NHM can be started. So the popular community way of coping with this was:
- turning off autostart with Windows in the NHM settings
- creating an elevated task with highest privileges to run cmd.exe to run NHM
- putting a shortcut to the windows startup directory to run this elevated task plus using the same shortcut to lunch NHM instead of the original shortcut.

With NHM v3.0.0.3 this works, program starts and mines ok, but with one serious drawback: it is not visible, there is no indication that it is running, no window opened, no tray icon, nothing. Only in the task manager we can see NHM and its miners working. It is surely a nice thing for some child who wants to mine discreetly on a powerful PC of his elder sister, but other than that it is totally a bug.

**Comment by AmnesiaBR** [comment]
Had the same problem, what I learned from this report is that if your Nicehash isn't opening when launched delete the config file to disable it being launched as an elevated task. Location: 'C:\Users\<username>\AppData\Local\Programs\NiceHash Miner\configs\'.

**Comment by mrMad-Cat** [comment]
Sorry, don't understand what you are suggesting. I don't know of any config file to lunch as elevated task that can be deleted. I'm talking about task manager and cmd elevated task. And I need it to lunch as elevated task because there is no other way to lunch it properly without compromising Windows security.

**Comment by mrMad-Cat** [comment]
Found the solution. The task was set to be run even without user logon. So it makes it behave in stealth mode for some reason. When I switched to "run only when user is logged in" it became visible.
So now I suggest you make fixes to NHM so there is no need in elevated tasks and it is always run with administrative privilages.

**Comment by mrMad-Cat** [comment]
Guys, please, finally. Make nicehash autostart with admin privileges (without user prompt) so we don't have to dance with elevated tasks and bat files.
Additional problem with elevated tasks is that you can't use autoupdate, as when the app closes the update never starts. So to update app I have to manually start this process, and only opening original NHM.exe
