### ISSUE TITLE
NHM 3.0.0.x - copy settings

### ISSUE THREAD

**Issue by Miiichal** [nicehash/NiceHashMiner#1965]
Please give us back the possibility to **COPY settings from previously benchmarked** devices to another...

**Comment by mesouug** [comment]
As temp workaround I copy paste benchmarked json in config directory. But this is very inconvenient.

**Comment by Miiichal** [comment]
Hello, there is no this function in new versions... copy across config files is not a system solution :) its functional, but not comfort :) This issue was set as "enhancement", but still not implemented...
Thanx a lot :)

**Comment by Miiichal** [comment]
Hello again, this function is selected as "enhancement", but due the many versions is **STILL NOT IMPLEMENTED**
Its about 1 year of waiting for this...
Temporary solution with copy from config directory is inconvenient :(

**Comment by Miiichal** [comment]
THIS HAS STILL NOT BEEN IMPLEMENTED BACK

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHM updates and see if the next release solves the issue for you.
