### ISSUE TITLE
v3.0.0.4 "Devices Mining" box stays in light mode when dark mode is on

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1967]
The "Devices Mining" box on the Device tab stays light green text on white background when dark mode is enabled. I assume that this is a bug.

Also, I'm curious why dark mode has a dark blue background on one computer and black on another. Do any system settings affect it?

Thanks!

**Comment by S74nk0** [comment]
@jwesolo This is this via TeamViewer? I will make the Theme settings change force a program restart this should load all Dark Theme styles on program init. 

Regarding the background color... the designer decided on what color to set :). If it looks different on different monitors this is more likely related to the monitor settings, calibration...

**Comment by jwesolo** [comment]
No, this is in standard Windows.

I like both the dark blue and the black...I will say that the blue background gives a little more definition to the NHM window with a black desktop background (and maybe that's why the difference occurs? the system where NHM appears black has the default Windows background). They are most definitely different colors because on one system the color is the same as the black background of the miner console windows and on the other is is definitely a medium-dark blue.

**Comment by jwesolo** [comment]
Here's a visual since this bug is still open. This is on Windows 10 Pro, no Teamview or any kind of remote connection; this is on the system console. Windows theme settings: default app mode set to Dark in Personalization->Colors; background set to black.

![NHM Main Window v3 0 0 5](https://user-images.githubusercontent.com/3432351/74560477-41d73680-4f2c-11ea-9fc5-da75b37ed580.JPG)
