### ISSUE TITLE
3.0.0.4 not available some objects menu

### ISSUE THREAD

**Issue by OlegXON** [nicehash/NiceHashMiner#1968]
It works stably, but non active buttons Device. Bencmark, Plugins
I want install Plugins. How without menu?

**Comment by S74nk0** [comment]
@OlegXON can you please post a screenshot? I am not sure what is your issue about.

**Comment by OlegXON** [comment]
I have 15 rigs
Windows 7
Some normal work. some not
![01](https://user-images.githubusercontent.com/60650554/73742684-a25cbb80-4755-11ea-8d1a-c47e7bedfb13.png)
![02](https://user-images.githubusercontent.com/60650554/73742685-a25cbb80-4755-11ea-93c1-257e33490823.png)
On screenshot cursor on Menu Benchmark
1 - change color - Work
2 - not change color- Menu not active and not pressed

**Comment by S74nk0** [comment]
Switching Tabs doesn't work?

**Comment by S74nk0** [comment]
Is this via Team Viewer?

**Comment by OlegXON** [comment]
> Switching Tabs doesn't work?
Not wotk
> Is this via Team Viewer?
Nearly. Anydesk

**Comment by OlegXON** [comment]
Hot keys?

**Comment by S74nk0** [comment]
This sounds more like a rendering issue with the RDP software Anydesk. NiceHash Miner uses software rendering instead of hardware accelerated rendering (GPU). I suspect this doesn't trigger a re-draw of the screen. I am personally not familiar with Anydesk but I would assume it has some "screen refresh" command. 
Can you try refreshing the screen via Anydesk?

**Comment by OlegXON** [comment]
> Can you try refreshing the screen via Anydesk?
I dont no how

**Comment by OlegXON** [comment]
Local tried
Connected monitor, mouse, keyboard to computer. Also not worked
This is not the Anydesk trouble

**Comment by OlegXON** [comment]
Work Menu - Start/Stop, Worker name. View Status Online. Settings. Notificatins
Not work Menu - Dashboard, Device. Benchmark, Plugins

**Comment by OlegXON** [comment]
NiceHash Keyboard shortcuts?

**Comment by S74nk0** [comment]
> Local tried
Connected monitor, mouse, keyboard to computer. Also not worked
This is not the Anydesk trouble

What is the Windows version that NiceHash Miner works on and what is the version where this issue occurs?

With Windows version I am referring to the build number (https://www.google.com/search?q=windows+build+numbers). 
What are the differences between these systems?

**Comment by OlegXON** [comment]
Windows 7, Service Pack 1 | 6.1 | 7601 | 2011-02-22
no differences
equally

**Comment by almartins** [comment]
Same here in 3 machines with Windows 7, Service Pack 1.
Two are ok and in one switching tabs can't be selected "Device", "Benchmark", "Plugins" !!

**Comment by S74nk0** [comment]
This issue is under investigation.

**Comment by S74nk0** [comment]
Please try this build https://github.com/nicehash/NiceHashMiner/releases/download/3.0.0.4/nhm_windows_3.0.0.4-x64_net48.zip and report if this works. Keep in mind you will need to install NET48 runtime

**Comment by OlegXON** [comment]
Thnx
Its work

**Comment by S74nk0** [comment]
Released version that fixes this issue. https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.0.5

Closing...
