### ISSUE TITLE
3.0.0.4 silently wont load - event view says d3d9 error

### ISSUE THREAD

**Issue by lilmidnit** [nicehash/NiceHashMiner#1969]
3.0.0.4 silently wont load - event view says d3d9 error. I have attempted to reinstall directx but there was no change in the error. The app should at least report the error to the user - additionally should add instructions in the docs to fix the problem. I have not yet been able to fix the problem.

Faulting application name: NiceHashMiner.exe, version: 3.0.0.4, time stamp: 0x98af28cf
Faulting module name: d3d9.dll, version: 10.0.18362.387, time stamp: 0xc808fce5
Exception code: 0xc0000409
Fault offset: 0x000000000003e223
Faulting process id: 0x2780
Faulting application start time: 0x01d5db6e90aabf38

**Comment by lilmidnit** [comment]
Tried it on 3 of my miners, same error on all machine. Some machines are nvidia, some are amd. All windows 10 machines with latest updates.

19.2.22 works.

**Comment by EWPetersen** [comment]
Also having this issue, as well on 3.0.0.7, still cant use this upgrade as it silently crashes to desktop.  1.9.2.22 works as well:

Faulting application name: NiceHashMiner.exe, version: 3.0.0.7, time stamp: 0x8e013a07
Faulting module name: d3d9.dll, version: 10.0.18362.387, time stamp: 0xc808fce5
Exception code: 0xc0000409
Fault offset: 0x000000000003e223
Faulting process id: 0x1d44
Faulting application start time: 0x01d6110854f7667e
Faulting application path: C:\Users\lmc\AppData\Local\Programs\NiceHash Miner\app_3.0.0.7\NiceHashMiner.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 425b6927-fa53-4bae-9dcc-a703ce87ca91
Faulting package full name: 
Faulting package-relative application ID:
