### ISSUE TITLE
Not able to install plugins

### ISSUE THREAD

**Issue by FrankS71** [nicehash/NiceHashMiner#1970]
Hi, Im not able to install plugins. The plugins are downloaded and extracted but the install button is still there. NHM 3.0.3, 3.0.4 and 1.9.2.12 and newer. Can this be a language issue? Using norwegian Windows 10 Edu.

Log entry for every plugin i try: [MinerPluginHost] Error occured while loading dll files: Could not load file or assembly '19968 bytes loaded from MinerPluginLoader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with the wrong format.

**Comment by S74nk0** [comment]
This is more like an issue with 32bit and 64bit binary compatibility. I assume Windows is 64 bit otherwise NiceHash Miner wouldn't start. But not all miner plugins are 64bit so this is most likely the issue. Our testing Rigs work without problems with the dll's. I will provide 64bit dll's for testing with your machine. I would appreciate the feedback. I will provide the download link with instructions in the next comment.

**Comment by FrankS71** [comment]
Ok, thank you! Yes i have 64bit Windows. After testing there where two plugins that installed properly. The two plugins are cpuminer-opt and CryptoDredge. All other where downloaded and extracted but not "installed".

**Comment by S74nk0** [comment]
@FrankS71 [Here](https://github.com/nicehash/NiceHashMiner/releases/download/3.0.0.4/nhm_windows_3.0.0.4-x64.zip) is 3.0.0.4 with all dll's built with x64. This package also has all the latest miner plugins bundled in the `plugins_packages` folder (this folder is bundled with every NiceHash Miner release), so if some of the plugins are not preinstalled that you wish to use to manually install them you would create the **UUID** named folder inside `miner_plugins` folder and extract the dll inside it. For GMiner for example it would be `nhm_path\1b7019d0-7237-11e9-b20c-f9f12eb6d835`. 

Please provide feedback if this package and miner dll's work on your system.

**Comment by FrankS71** [comment]
Hi again. I have tried you build but it has the same behavior. It download and extract the miner plugins but the NHM app don`t detect them. Again the only plugins correctly installed are cpu-opt and CryptoDredge.

![nhm](https://user-images.githubusercontent.com/51756378/74013268-56478c00-498c-11ea-9f9d-7b6d7a05aff9.jpg)
![xmrstakrx](https://user-images.githubusercontent.com/51756378/74013272-56e02280-498c-11ea-926c-5b321eb0f2d8.jpg)

[log.txt](https://github.com/nicehash/NiceHashMiner/files/4169681/log.txt)

**Comment by S74nk0** [comment]
@FrankS71 Here is a new test-buid https://github.com/nicehash/NiceHashMiner/releases/download/3.0.0.4/nhm_windows_3.0.0.4-x64_net48.zip.

If you can please try this version. Keep in mind that the online plugins will not work with this only the preinstalled ones and the packaged plugins will (like I described in [the previous comment](https://github.com/nicehash/NiceHashMiner/issues/1970#issuecomment-582952989)).

We have detected that NET45 is causing crashes and issues in some cases where the newer NET472+ do not.

**Comment by luc1an24** [comment]
Inactive thread, therefore closing issue.

**Comment by Paranoid-OS** [comment]
Sorry to necromance this
I just wanted to tell you that I had the same problem, and

> Here is a new test-buid https://github.com/nicehash/NiceHashMiner/releases/download/3.0.0.4/nhm_windows_3.0.0.4-x64_net48.zip.
> 
this worked

But then it auto-updated, and the plugins broke again, with them still failing to install

**Comment by Paranoid-OS** [comment]
Okay, after it auto-updated, I deleted it and unzipped the file above, and tried again, but after that, it didn't work
The error says that I have missing binaries with all the miners, and that I have to upgrade NiceHash.
I deleted all nicehash related folders, and it didn't work, so please advise

**Comment by LucaColombi** [comment]
hello,

have similar issue, plugins installs in folder but error initializing, only some installs and are recognized

moreover, GPU benchmarks and mining fails with all available plugins and algorithms (not known if related issue)

executed as administrator:

seems to install:
![image](https://user-images.githubusercontent.com/4623982/92917643-f982e700-f42e-11ea-9106-3df5c36c6440.png)

but fails:
![image](https://user-images.githubusercontent.com/4623982/92917730-0acbf380-f42f-11ea-9826-b31619df4d95.png)

GPU mining fails:
![image](https://user-images.githubusercontent.com/4623982/92917879-2cc57600-f42f-11ea-83c8-65b53ab1f3db.png)

available benchmarks fails:
![image](https://user-images.githubusercontent.com/4623982/92918635-e4f31e80-f42f-11ea-88b6-b5945a162d32.png)


I have generated an error log with ID:
b58be66e-a98f-487e-a38d-549f576527bc

**Comment by LucaColombi** [comment]
> Inactive thread, therefore closing issue.

please reopen issue @luc1an24 , seem still not working

**Comment by christyjoy555** [comment]
Watch this video and it will definitely help you...

https://www.youtube.com/watch?v=fgmxNuNuVPo

**Comment by christyjoy555** [comment]
> Hi, Im not able to install plugins. The plugins are downloaded and extracted but the install button is still there. NHM 3.0.3, 3.0.4 and 1.9.2.12 and newer. Can this be a language issue? Using norwegian Windows 10 Edu.
> 
> Log entry for every plugin i try: [MinerPluginHost] Error occured while loading dll files: Could not load file or assembly '19968 bytes loaded from MinerPluginLoader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with the wrong format.

>Watch this video and it will definitely help you...

https://www.youtube.com/watch?v=fgmxNuNuVPo

**Comment by davidkrider** [comment]
Deactivating real-time protection (as per the video) does not fix the problem for me.
