### ISSUE TITLE
Cannot mine on my dual xeon e5-2609 v2

### ISSUE THREAD

**Issue by wallaceaskew** [nicehash/NiceHashMiner#1972]
Will not benchmark.  CrytonightR works fine.

**Comment by wallaceaskew** [comment]
Getting read error end of file on XMR rig for randomx and XMR Stak RX.

**Comment by wallaceaskew** [comment]
If I go back to version 1.9.2.22 and run a "Precise" benchmark then I am good to go.

**Comment by luc1an24** [comment]
Hi 
Thank you for reaching out and your patience.
Dual CPU's are currently unsupported within the NHM.
If you have any questions, feel free to open a new issue.
Have a nice day!
