### ISSUE TITLE
Profitability switching to the same algorithm over and over

### ISSUE THREAD

**Issue by TiiStyle** [nicehash/NiceHashMiner#1973]
Hi,

I didn't look through the code but I experience the following issue while using NHM normally:

When I mine (algorithm not specific) then NHM often restarts the miner without a obvious reason or problem.
The restart frequency also varies and can be from up to several hours before switching legit due to profitability up to switching every 15 minutes to the same algorithm over and over again without restarting or closing NHM meanwhile.

I figured out that this happens more frequent when the displayed profitability ("Devices" tab) of the mined algorithm per device is lower than the displayed profitability of the benchmarks ("Benchmark" tab) per device.

Therefore I have to think that this problem is related to an issue with the profitability algorithmics.

Additional issue that arises through the first issue:
Due to the more frequent switching of algorithms I pay the dev-fee of the miner more often.
The dev-fee often is paid the first time after 10-20 minutes after starting the miner.
If my miner now switches every 20 minutes after paying the fee I will pay the fee 3 times an hour instead of once per hour.

### Additional information:

I already started noticing this problem in NHM Version 3.0.0.3.

Current NHM Version: 3.0.0.4

OS: Windows 10 Pro
OS Version: 1809
OS Build: 17763.973

GPUS involved:
GPU#1 NVIDIA GeForce GTX 1080
GPU#2 ASUS GeForce GTX 980

In case further information is required please leave a note.

Kind regards

Tii

**Comment by S74nk0** [comment]
@TiiStyle I suspect this to be an issue with the API timeout checker and not with the switching. If you provide the logs I will be able to assert the situation. 
To completely disable the API timeout checking this setting can be disabled in the `nhm_path\configs\General.json` file and set `"CoolDownCheckEnabled": false,`.
This will completely disable API checks and will not restart miners due to unsuccessful API readings. This feature is to prevent miner stagnation but we are considering deprecating this feature since it was more relevant 2 years ago when miners were vastly less stable.

**Comment by MuzTank** [comment]
> @TiiStyle I suspect this to be an issue with the API timeout checker and not with the switching. If you provide the logs I will be able to assert the situation.
> To completely disable the API timeout checking this setting can be disabled in the `nhm_path\configs\General.json` file and set `"CoolDownCheckEnabled": false,`.
> This will completely disable API checks and will not restart miners due to unsuccessful API readings. This feature is to prevent miner stagnation but we are considering deprecating this feature since it was more relevant 2 years ago when miners were vastly less stable.

This solved the issue (at least in mine) - however, need to restart NH to be working

**Comment by TiiStyle** [comment]
It seems that this did solve my issue as well.
Algo switching seems to be working correct now.

Thank you @S74nk0

**Comment by luc1an24** [comment]
Fixed issue, therefore closing!
