### ISSUE TITLE
3.0.0.4 autoupdates - unable to switch off

### ISSUE THREAD

**Issue by Miiichal** [nicehash/NiceHashMiner#1974]
When i make a decision to "**switch off**" autoupdates in the main settings of the program, updates of every algo is still enabled. When i put autoupdate of every algo to the "off position", so next start of the NHM are they turned on again...

So in main settings are autoupdates disabled, bud the switcher on algos is still in ON position...

**Comment by S74nk0** [comment]
Released version that fixes this issue. https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.0.5

Closing...
