### ISSUE TITLE
Mining XMR with Xmrig sometimes will display "read error: end of file" on NiceHash Miner 3.0.0.4

### ISSUE THREAD

**Issue by ch155260** [nicehash/NiceHashMiner#1975]
Mining will stop when Xmrig display "read error: end of file",sometimes change mining pool will be fix but sometimes can't,  the issue happened photo as below.
[https://imgur.com/60rpICd](url)

I have a lot of machine have same issue, all cpu mining will be happened.

**Comment by jwesolo** [comment]
See my comment on other issue, seems related:

https://github.com/nicehash/NiceHashMiner/issues/1956#issuecomment-581559967

**Comment by wallaceaskew** [comment]
I'm having the same issue. If I go back to version 1.9.2.22 and run a "Precise" benchmark then I am good to go.
