### ISSUE TITLE
Toggling off "allowmultipleinstances" prevents NiceHash from starting (3.0.0.4)

### ISSUE THREAD

**Issue by PlanetVaster** [nicehash/NiceHashMiner#1977]
If you toggle off the setting "allowmultipleinstances" nicehash miner won't start anymore. I had to manually go into the configs/General.json file and set it back to true to be able to boot nicehash miner. I'm using 3.0.0.4 specifically but my guess is all versions of NHM 3 are affected. My guess is NHM sees the only instance of itself as a second instance when booting and kills its own process.

**Comment by shanevw73** [comment]
I had the same issue and had to do the same to get it to start.

**Comment by joseortiz3** [comment]
I can confirm this issue. It's real. Weirdly, launching NHM twice, the first time crashing, resulted in my `General.json` getting completely reset.

**Comment by S74nk0** [comment]
Released version that fixes this issue. https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.0.5

Closing...
