### ISSUE TITLE
Claymore miner started with option: -di 012334, just 5 card using

### ISSUE THREAD

**Issue by robi772** [nicehash/NiceHashMiner#1978]
Claymore miner started with option: -di 012334 , on 6 card rig. Just 5 card using
Version is 3.0.0.4

**Comment by luc1an24** [comment]
Hi
Could you please send us some logs?
This can be done by using ´CreateLogReport.exe´
If you don't want to share it here you can send it to our support team and they will forward it to us.
Thank you.

**Comment by luc1an24** [comment]
inactive thread, therefore closing
