### ISSUE TITLE
Temp and mining info not showing for multi GPU's

### ISSUE THREAD

**Issue by manicmisfit** [nicehash/NiceHashMiner#1979]
I have been mining with 7 ATI cards prior to 3.0.0.4 and everything worked fine under ver 1.9.2.21. I removed the cards to clean the fans and install 3.0.0.4. I reinstalled one card at a time to re-benchmark for ver 3.0.0.4. i started with only 1 card RX570 and everything worked fine and i could see the temp and mining info for that card. When i installed a second  card all my mining and temp info went away. I added 5 more cards and still no temp or mining info for each card. All my cards are RX570/RX470. I use the Blockchain Beta driver from AMD/ATI. All the cards are mining, it just wont show the temp info for each card.

**Comment by rick1jamesB** [comment]
I am having the same issue with 2 rigs.
It will show the stats if I only  have 4 cards but when  I add card #5 all the stats disappears
*Octominer riseless motherboard
*windows 10 64
*Rx580 8gb
*Latest Amd driver  20.1.3
*NiceHash miner. 3.0.0.5
Thank you guysin advance for your time and commitment.

**Comment by cneagoe1973** [comment]
Hi guys,
I have 4 Rigs with the same configuration (6 RX580 8Gb) and the temp and rpm are null.
When you have time please fix this.
thank you for all your work !

**Comment by rick1jamesB** [comment]
> Hi guys,
> I have 4 Rigs with the same configuration (6 RX580 8Gb) and the temp and rpm are null.
> When you have time please fix this.
> thank you for all your work !

What kind of motherboard do you have?

**Comment by rick1jamesB** [comment]
> I have been mining with 7 ATI cards prior to 3.0.0.4 and everything worked fine under ver 1.9.2.21. I removed the cards to clean the fans and install 3.0.0.4. I reinstalled one card at a time to re-benchmark for ver 3.0.0.4. i started with only 1 card RX570 and everything worked fine and i could see the temp and mining info for that card. When i installed a second card all my mining and temp info went away. I added 5 more cards and still no temp or mining info for each card. All my cards are RX570/RX470. I use the Blockchain Beta driver from AMD/ATI. All the cards are mining, it just wont show the temp info for each card.

What kind of motherboard do you have?

**Comment by cneagoe1973** [comment]
RIG 1 :
Gigabyte Z370 HD3P-CF  Bios F7 04/03/2018

RIG 2:
Gigabyt  H110-D3A-CF  Bios F25d  03/09/2018

RIG 3 :
ASRock   H81 Pro BTC R2.0  Bios  P1.20  07/22/2014

RIG 4 :
ASRock   H81 Pro BTC R2.0  Bios P1.20  07/22/2014

**Comment by manicmisfit** [comment]
ASUS B250 Mining Expert. Running Windows 10 Enterprise. Not sure of the BIOS ver or date. I'm not at the Rig location right now.

**Comment by rick1jamesB** [comment]
@manicmisfit  I have that bord as well and I have 1660ti on it with no issues.
As far as the bios that bord can update from the bios. Easy.

**Comment by rick1jamesB** [comment]
I asked you guys about the motherboard because I was thinking it was the issue but from the look of things it's not a MOBO issue 😕

**Comment by rick1jamesB** [comment]
@manicmisfit & @cneagoe1973  were you guys able to find a solution? I am thinking about trying another miner just to see if this will help

**Comment by brandadaniel** [comment]
I'm having same issue with 3xAMD RADEON VII on ASRock H110 Pro BTC+.
NiceHashMiner v3.0.0.6
When I installed first card it did showed, but after I installed second card, there was no TEMP, no LOAD, no RPM display.
 It does mining fine tho.

**Comment by m3scott** [comment]
Same issue, 3 XFX GTR RX580's, 1 XFX GTS RX580 and 2 Sapphire Nitro+ RX580's.  Motherboard is a ASRock BTC+ H110 Pro.  

Temps and hashrate were showing with 4 GPU's, now nothing with all 6 finally added in.  
NiceHashMiner v3.0.0.7. and .6

**Comment by rick1jamesB** [comment]
Anyone figure out how to fix this?

**Comment by ppriorfl** [comment]
I am having same problem - it reports temp for Nvidia cards on mixed rig, but my two AMD Radeon VII cards do not report temp

**Comment by prototypic** [comment]
Same issue:
- ASUS B250 Mining Expert
- 7 XFX RX580

Already disabled integrated graphics in BIOS.
All settings display properly in AMD app, but no settings display in NHM.
Mining works perfectly fine, but it would be nice to see temp and fan in mobile app.

**Comment by ddm-j** [comment]
Big issue same same. 

5x Radeon VII with ASUS B250. No ability to disable onboard, but set primary graphics to one of the cards - still no resolution.

**Comment by luc1an24** [comment]
Hi everyone
We made some changes and created a test build with fix
Please check it out and report if this fixes your problem
https://github.com/nicehash/NiceHashMiner/releases/download/3.0.2.0/nhm_windows_3.0.2.0_amd_adl_odn.zip
Have a nice mining!

**Comment by rick1jamesB** [comment]
Going to test this in a few

**Comment by rick1jamesB** [comment]
> Hi everyone
> We made some changes and created a test build with fix
> Please check it out and report if this fixes your problem
> https://github.com/nicehash/NiceHashMiner/releases/download/3.0.2.0/nhm_windows_3.0.2.0_amd_adl_odn.zip
> Have a nice mining!

Hi this in fact works all my 8 cards(temp/Rpm /lode) are showing up in the miner and the web interface.
However the temp is showing up in the 1000s
Example: 
GPU 1 Temp 60000c
GPU 2 Temp 58000c
GPU 3  Temp 58000c

Going to restart this and see if that will fix it 
No that didn't help fix the problem.. 

Hey its a lot better than  not having the information 
Thank you guys 
Here is a picture of what it looks like now 
![15928393975368200374181054103698](https://user-images.githubusercontent.com/60081939/85305294-dcb3c480-b47a-11ea-885d-3a616c17b64b.jpg)

![15928392548794948757884332587483](https://user-images.githubusercontent.com/60081939/85305061-85155900-b47a-11ea-9d9a-014ed473c8ec.jpg)

**Comment by ddm-j** [comment]
@luc1an24 for me, 5x Radeon VII w/ ASUS B250, now instead of "--" where temp and load go there is 0degrees and 0% respectively.

**Comment by rick1jamesB** [comment]
> @luc1an24 for me, 5x Radeon VII w/ ASUS B250, now instead of "--" where temp and load go there is 0degrees and 0% respectively.

Did you try uninstalling the old miner and installing the one they gave us?

**Comment by ddm-j** [comment]
@rick1jamesB Clean uninstall, download test build, unzip, run as admin --> Temp: 0, Load: 0%, RPM: --
However, nicehash does pick up the load on my CPU

**Comment by ddm-j** [comment]
@rick1jamesB did this fix solve your problems in the long term? Maybe I just didn't uninstall properly?
@luc1an24 anything I can do to help find the issue?

**Comment by nieXas** [comment]
![image](https://user-images.githubusercontent.com/25354111/107882890-80635080-6ef4-11eb-9714-4686c0c5fd4d.png)
mobo tb250-btc

**Comment by applifaction** [comment]
I do have the same problem. Is there a possitiblity to read a Logfile for further information?

![image](https://user-images.githubusercontent.com/9271838/109312904-e1215000-7847-11eb-922a-f70e1fd8eb47.png)

lolMiner displays the temperature: 

![image](https://user-images.githubusercontent.com/9271838/109314579-d23b9d00-7849-11eb-8e60-d90d02cc40c5.png)

**Comment by jrodrigv** [comment]
I can confirm this happens as well mixing RTX 3070 + RX 6800. The RX 6800 temperature temp/ load readings are not working

**Comment by illSaya** [comment]
I can confirm, no temperature and fan speed on my RX 6800

![Screenshot (3)](https://user-images.githubusercontent.com/82008922/113650124-fe8bda00-968f-11eb-9185-00e39513d09b.png)

**Comment by mingcxb** [comment]
![image](https://user-images.githubusercontent.com/13451371/117963175-9e551b80-b352-11eb-8c59-b9d3791b95dd.png)
I have the same problem, how do I fix it?

**Comment by mingcxb** [comment]
![image](https://user-images.githubusercontent.com/13451371/117963427-f2600000-b352-11eb-8460-ebc303b8aa5e.png)
I have the same problem. how do I fix it?

**Comment by Dohtar1337** [comment]
@mingcxb This seems to be the issue with AMD drivers. We are aware of it. There is nothing you can do.

**Comment by Drumsticks** [comment]
I'm experiencing the same issue on all of my AMD cards.  @Dohtar1337, if you are aware of it, does this mean a fix will be coming?  With this ticket marked as closed, it doesn't seem too reassuring, but I am hoping!

**Comment by MrJake222** [comment]
Any updates on this one? Also having problems with Debian rig and 3x RTX2060
