### ISSUE TITLE
Cuda error in func 'quak-bake512_cpu_setBlock_80

### ISSUE THREAD

**Issue by bonifacio123** [nicehash/NiceHashMiner#198]
NHML v1.8.1.1

GPU: Nvidia 1080 & 1070

Algorithm: X11Ghost

When NHML launches X11Ghost I see this message:

Cuda error in func 'quark_blake512_cpu_setBlock_80' at line 547 : an illegal memory access was encountered.

I've disabled X11Ghost for now. Is there a place where these errors are captured? I did a screen capture since the message doesn't stick around too long.

Thanks

**Comment by Mystere** [comment]
Typically that's either an overclock issue (sometimes even underclock).  Or your rig is not supplying enough power to the Gpu's (typically due to fault risers, or inadequate cabling)

**Comment by bonifacio123** [comment]
That's something I haven't considered. Perhaps you can provide commentary on my current Afterburner settings:

Booth the 1070 and 1080 have these settings:
Power Limit: 61
Temp Limit: 83
Core Clock: +100
Memory Clock: +738
Fan: 70

Thank you

**Comment by bonifacio123** [comment]
Also, rig is consuming 350W with a Corsair 750W power supply. No risers being used.

**Comment by Mystere** [comment]
That's a pretty agressive memory clock.  Try scaling it back a bit.  Core clock should be fine.  Some cards don't like a power limit that low.. so maybe try bumping that up too if nothing else works.  Also, 2 high power cards drawing power from the PCIe bus.  some motherboards have a connetor for extra PCIe power, if you have that use it.

**Comment by bonifacio123** [comment]
Mystere, thanks for taking the time to help. I've done some research into the various options available in Afterburner. Here are some links that may help others in the future:

GPU Tools and GPU Memory Clock: Real and Effective Speeds Demystified
[http://www.geeks3d.com/20100613/tutorial-gpu-tools-and-gpu-memory-clock-real-and-effective-speeds-demystified/](url)

GTX 1070 OC Guide
[http://www.overclockersclub.com/guides/gtx_1070_overclocking_guide/2.htm](url)

GTX 1080 OC Guide
[http://www.overclockersclub.com/reviews/nvidia_geforcegtx_1080_overclocking/](url)
