### ISSUE TITLE
Cannot set extra parameters in new version 3.0.0.4

### ISSUE THREAD

**Issue by minerlady49** [nicehash/NiceHashMiner#1980]
I am unable to set extra parameters for plugins (specifically XMRIG) in the newest version of NH Miner. Please advise.

**Comment by luc1an24** [comment]
Hi @minerlady49 
Thank you for reaching out.
What have you tried so far?
Did you checked the [docs](https://github.com/nicehash/NiceHashMiner/blob/master/doc/Plugins/InternalSettings/ExtraLaunchParameters.md)?

**Comment by luc1an24** [comment]
No response - closing.
Feel free to create a new issue if the problem still persists.
