### ISSUE TITLE
Program update

### ISSUE THREAD

**Issue by YuriyNa** [nicehash/NiceHashMiner#1985]
Add the program update button manually (auto-update does not work correctly, the program simply closes, the update starts after the program is restarted manually), as well as support for other languages, and not the only English.

**Comment by WiseEagle** [comment]
I join, My miner is updated for an hour

**Comment by shanevw73** [comment]
My NHM updated from 3.0.0.4 to 3.0.0.5, however my miners did not. I had to manually update them from the plugins tab.
