### ISSUE TITLE
Nicehash miner 3 and bsod  

### ISSUE THREAD

**Issue by meh-cih** [nicehash/NiceHashMiner#1986]
I am getting multiple bsods related to driver issues (tdr failure nvlddmkm. sys) while using nicehash miner 3 (3003, 3004 and 3005), the only solution I found is to use nh miner 1.9.2.22   
- I have done a clean install of drivers (with ddu)
- sfc scannow
- regitry cleanning

**Comment by luc1an24** [comment]
Hi @meh-cih 
Thank you for your patience.
Does that still happens with the latest version (3.0.2.0)?
Have a nice day!
