### ISSUE TITLE
Rig name update

### ISSUE THREAD

**Issue by qpPeW** [nicehash/NiceHashMiner#1988]
We go into the settings, change the name of the rig, go back to the dashboard and see the old name.
We go back to the settings and see that the name is nevertheless ripe, but on the dashboard page it shows the old one, it will be updated only after the program is restarted.

**Comment by luc1an24** [comment]
Hi 
Thank you for your patience.
This is fixed now.
If you have any questions feel free to ask.
Have a nice day!
