### ISSUE TITLE
Missing some Algorithm!!?

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#199]
Hey guys we hope you add 
Zclassic(ZCL) and Zencash(ZEN) To benchmark

**Comment by Mystere** [comment]
That's not how NiceHash works.  You don't benchmark a coin.  You benchmark an algorithm. 

ZCL and ZEN both use the Equihash algorithm, therefore the hashrates are the same for all Equihash coins that might get mined by buyers (you aren't mining individual coins in NiceHash).

**Comment by ghost** [comment]
Aha thx for that .
