### ISSUE TITLE
Crash 3.0.0.5

### ISSUE THREAD

**Issue by birdsum** [nicehash/NiceHashMiner#1993]
![EC47C2D0-9B61-45A2-BD24-48F58D6A6141](https://user-images.githubusercontent.com/35085781/74844317-dd6b0b80-535f-11ea-8848-e8cbd8ec29fb.jpeg)

Crash when mining grin31 with gminer.

**Comment by luc1an24** [comment]
Hi @birdsum 
Thank you for reaching out.
There is not enough info for us to help you.
Could you please give us logs created by `CreateLogReport.exe`?
If you want you can send them to our customer support and they will forward them to us.

Have a nice day!
