### ISSUE TITLE
Nicehash 3.0.0.5 benchmark is always lower then the 1.9.x.x series benchmark. 

### ISSUE THREAD

**Issue by GSUcoiners** [nicehash/NiceHashMiner#1994]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by GSUcoiners** [comment]
I run 15 rigs and tried to update several to Nicehash 3.0.0.5. Same benchmarks, same rigs but keep getting lower benchmarks with 3005 and lower profits. Have to step back to 1.9.2.22.  Nice new interface but slower.  Maybe using extra resources to run 3005, better release a few more 19xx and keep testing the 3xxx. My Rigs are a mix of GPU (nvidia and amd) and CPU (intel and amd) miners. 
All run Win7.  Latest drivers, Average 10% loss using 3005.   Will use 1.9.2.22 for now.  Nicehash always figures it out so Keep up the good work....

**Comment by almartins** [comment]
Same here and I had stability issues on my rigs - nvidias 1080 mainly on Dagger Hashimoto algo - Windows 7 64bits, AMD cpu).
Back to  1.9.2.21 for now.

**Comment by peteycrack420** [comment]
i can nevr get Dagger Hashimoto algo to work right

**Comment by luc1an24** [comment]
Hi everyone
We fixed quite some things since that release.
Could you please try a new one?
Have a nice mining!
If you have any questions or problems with the new versions please feel free to open a new issue.
