### ISSUE TITLE
When will the compiled release appear?

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner#2]
When will the compiled release appear? Thank you in advance for your response!

**Comment by DillonN** [comment]
It's still under development, but should be ready soon. Please stay tuned!

**Comment by DillonN** [comment]
It's out now https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.0.0

**Comment by billmcilhargey** [comment]
Nice work!
