### ISSUE TITLE
Cryptonight algo missing

### ISSUE THREAD

**Issue by rpglord** [nicehash/NiceHashMiner#200]
It doesn't seem cryptonight shows up as usable algo on any gpu I tried, I am currently using 1060 gtx. It only shows as available for cpu mining, I am wondering is this some kind of a bug on my end or intended behavior ? 
Monero is very popular coin and has risen 50% in value in last few days, I hope we will be able to mine it on our gpu's with nicehash ?

**Comment by Mystere** [comment]
I believe NH only provides a CPU miner for cryptonight.

**Comment by drkskwlkr** [comment]
@Mystere I thought so myself as well until today when I saw with my own eyes NiceHash mining CryptoNight on my GTX970 for a small amount of time. Probably with the rise of Monero @rpglord mentionds there will be more folks interested in buying hashrate and putting orders.

**Comment by rpglord** [comment]
I just found comment from Dillon in other closed issue that cryptonight is not working on pascal gpu, however this is not true anymore atleast, I just run it outside nicehash program with ccminer software and it works fine with no problems, I will let it run for awhile

**Comment by adem4ik** [comment]
Yes, I was surprised too when found CryptoNight available among algorymths inside Megaminer on my GTX 1060 6GB, and it seems like quite profitable considering the fact that the card stays quite and cold while eating not too much watts (with some core downvolting involved).
![2017-08-21_232016](https://user-images.githubusercontent.com/4707112/29534562-8369910e-86c7-11e7-9a3f-bc6c870b19cc.png)

**Comment by Mystere** [comment]
Yeah, I have all Pascal cards.  Now that I think about it, i did try to run my 650 and it only had Cryptonight.. my CPU had better hashrates than that card did.

**Comment by ChriscomIT** [comment]
@rpglord Yes you right. Maybe @Dillon need to check this as there are indeed some Pascal GPUs which it runs on if not all.

**Comment by adem4ik** [comment]
Just in case, I've ran it for a 5-6 hours and the miner seems quite stable on GTX1060 6GB.

**Comment by rpglord** [comment]
I ran it for few hours with no problems too

**Comment by DillonN** [comment]
Cryptonight on Pascal was not working correctly but it seems it does in newer versions of ccminer. Will look at adding it in for that
