### ISSUE TITLE
3.0.0.5 hangs the machine

### ISSUE THREAD

**Issue by VadimEv** [nicehash/NiceHashMiner#2003]
System: NVIDIA mixed(retail+miner cards), 1.9.2.x worked just fine with power setting disabled, in-miner monitoring enabled.
Updated/rebenched to 3.0.0.5. IF monitoring disabled with afterburner ( 4.6.0 used with 436.30 driver) works fine, ELSE: enabling in-miner monitoring hangs the NVML in 15-20 mins, only hard reset helps. 
Something clearly broken in 3.0.0.5 here.
Another issue - constant notification that windows defender exception failed - it is disabled in group policy, how to turn this off once and for all?

**Comment by luc1an24** [comment]
Hi
Thank you for your patience.
Could you please check it again?
It should be fixed now.
Also an option is added to notifications where you can disable selected one for good.
If you have any questions, please contact us.
Have a nice day!

**Comment by VadimEv** [comment]
Sorry for delay, I updated some time ago, as well as reinstalled OS completely, now everything working fine.
