### ISSUE TITLE
Wrong profitability reported

### ISSUE THREAD

**Issue by VadimEv** [nicehash/NiceHashMiner#2009]
Screenshot says it all.  3 almost identical cards, even hashrate is the same. However profitability differs a lot.
![nhm3005nug1](https://user-images.githubusercontent.com/10043733/77182658-2e485e00-6ade-11ea-90b3-0d040f035ceb.png)

**Comment by luc1an24** [comment]
Hi @VadimEv 
Thank you for reporting this issue.
Could you please confirm that it was fixed?
Thank you!

**Comment by VadimEv** [comment]
@luc1an24 currently it's running on 3.0.1,0 and everything seems fine. Profitability reported correctly.
