### ISSUE TITLE
NiceHash Crashes and deletes itself

### ISSUE THREAD

**Issue by hardtogetcoin** [nicehash/NiceHashMiner#2012]
My cpu (AMD Ryzen 5 1400) was not benchmarking so i decided to close the app and run it as admin, it started downloading a couple of miners and crashed i tried relaunching it and the desktop shortcut didnt work, so i went into file explorer and saw nothing of nicehash. it was deleted. it deleted itself im tired of this happening and i want this bug fixed NOW.

**Comment by luc1an24** [comment]
Hi 
NHM gets deleted by AV.
Please check the following article about how to prevent AV from deleting NHM:
https://www.nicehash.com/support/mining-help/nicehash-miner/is-nicehash-miner-a-virus
Have a nice day!
