### ISSUE TITLE
App v. 3.0.0.6 does not use the cost of electricity in profitability calculating.

### ISSUE THREAD

**Issue by aliandwa** [nicehash/NiceHashMiner#2014]
App v. 3.0.0.6 does not use the cost of electricity in profitability calculating.  The value of current profitability in fiat currency does not change from the value of the assigned cost of electricity.

**Comment by luc1an24** [comment]
Hi
This was implemented so now you can select net or gross profitability.
Closing the issue since it is fixed.
Have a nice day!
