### ISSUE TITLE
3.0.0.7 is not showing any window when started

### ISSUE THREAD

**Issue by adminant** [nicehash/NiceHashMiner#2016]
When I start unzipped nhm 3.0.0.7 it shows no window but only icon at app panel. I can right click and move invisible window, but can't accept agreement and can't start program. Windows 7 pro, .Net 4.8.

**Comment by adminant** [comment]
For those who experience the same difficulties - it is due to unupdated W7SP1. After installing all microsoft pending updates it's ok

**Comment by luc1an24** [comment]
Issue was fixed by updating OS.
Closing issue.
