### ISSUE TITLE
App v 3.0.0.7 Needs enhancement to re-benchmark without restarting.

### ISSUE THREAD

**Issue by GSUcoiners** [nicehash/NiceHashMiner#2019]
You have to restart each time you want to re-benchmark.  On multi card rigs with a mix of cards a re-benchmark -Just this Benchmark Now Option - would be good, with out having to close the app and restart the app each time for each missed benchmark.  It can take several re-benchmarks on certain tough algorithms to get a good benchmark. An option to rerun just that benchmark without restarting   the app would be great.  Thanks

**Comment by jwesolo** [comment]
I second this 1000%.

Just don't deactivate the benchmark button at the bottom when benchmarking is completed. Everything else is controlled by the switches.

Also #1954 .

I really miss the better control over everything we had with 1.9.x.

Thanks.

**Comment by Dohtar1337** [comment]
Moved to backlog as a BUG
