### ISSUE TITLE
hash rate dropped 50%

### ISSUE THREAD

**Issue by ZINCyy** [nicehash/NiceHashMiner#202]
Hello,
I am using NHMLv1.8.1.0 and after I updated windows last night to their "creators version" my hash rate across all alg. dropped by 50%. as far as i can tell that is the only variable that changed. any help is much appreciated

**Comment by streaml1ne555** [comment]
Try reinstalling your GPU drivers/gpu overclock software. Also any OS tweaks you made before (not that these would cut speed in half) will probably need to be redone. Windows has a habit of resetting settings on version changes. You could roll back if you're feeling adventurous...

**Comment by ZINCyy** [comment]
I think thats the best option, its just so strange everything dropped exactly 50%. is there a way to run a gpu health check?

thanks for the response streaml1ne555

**Comment by streaml1ne555** [comment]
You could run benchmarks and compare to other results for the same hardware, things like 3DMark, SiSoft Sandra, etc. Also check with tools like MSI Afterburner or HWInfo64 to make sure there aren't issues with GPU/CPU temperatures that might lead to throttling.

**Comment by ZINCyy** [comment]
after painfully rolling back the windows update the issue was resolved.
