### ISSUE TITLE
NiceHash Miner won't stop updating!

### ISSUE THREAD

**Issue by TASblast1993** [nicehash/NiceHashMiner#2021]
Fairly new to mining, but I now a decent amount.  I have the most recent NiceHash Miner and have mined with it, but it now shows "NiceHash Miner Starting Update"  and won't budge.  Please help.

**Comment by luc1an24** [comment]
Hi @TASblast1993 
Thank you for reaching out.
Is this issue still happening to you?
If it is please forward me the logs so I can help you further.
Thank you.

**Comment by TASblast1993** [comment]
I fixed it, but now it's happening again and I don't remember what I did.  How do I find the logs?

**Comment by joseortiz3** [comment]
I also experience 3.0.0.7 updating forever. I haven't mined in a week because of the issue. And furthermore the current 3.0.0.8 release is flagged by Windows as a virus, which prevents me from downloading.

**Comment by luc1an24** [comment]
@TASblast1993 
You can create a zip package of logs and you setup information by using our log packager.
You can do that via [NHM](https://www.nicehash.com/blog/post/how-to-create-a-log-report-with-nicehash-miner) or by manually launching "CreateLogReport.exe" file in your installation path.

@joseortiz3 
Could you also forward your logs?
NiceHash Miner is usually flagged by AV (anti-virus) software. This is normal, as almost every mining software on the market is blacklisted by AV. Just make an exception in your AV software to enable the proper operation of NHM.

**Comment by joseortiz3** [comment]
I temporarily disabled Windows Defender and the infinite update finished almost immediately

**Comment by luc1an24** [comment]
@joseortiz3 
Thank you for your feedback. That was probably AV blocking the update.
I am glad that this is fixed now for you.

**Comment by luc1an24** [comment]
Fixed, therefore closing issue
