### ISSUE TITLE
Please reenable NBMiner

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#2024]
I see that you have updated the code for version 9.0 of the NBMiner plugin...please release it. Currently, NHM says to update NHM as the NBMiner 9.0 plugin is not compatible.

Thank you.

**Comment by luc1an24** [comment]
Hi @jwesolo 
Thank you for reaching out.
Please re-download latest NHM since this is a bug within the previous build.
Re-downloading NHM will fix this problem for you.
Have a nice day!
If this doesn't fix issue for you  please reopen ticket.
