### ISSUE TITLE
 Change the installation path of NiceHash Измените путь установки NiceHash

### ISSUE THREAD

**Issue by vasy701** [nicehash/NiceHashMiner#2027]
Change the installation path of NiceHash to the NiceHash folder, otherwise my .bat script does not see the path of the NiceHash folder and does not start. Измените путь установки NiceHash на папку NiceHash, а то у меня скрипт .bat не видит путь папки NiceHash и не запускается.
![image](https://user-images.githubusercontent.com/53948065/78634229-f18dac80-78bc-11ea-817e-6886541091bc.png)

**Comment by luc1an24** [comment]
Hi @vasy701 
Thank you for reaching out.
We won't do that. Have you tried to put installation path in the quotation mark like: "installation_path"?
This should fix the problem with the path.

If you have any questions feel free to reopen this one or create a new issue.
Have a nice day!

**Comment by vasy701** [comment]
"Installation_path" does not work.

  
>Среда, 15 апреля 2020, 9:17 +03:00 от luc1an24 <notifications@github.com>:
> 
> 
>Hi  @vasy701
>Thank you for reaching out.
>We won't do that. Have you tried to put installation path in the quotation mark like: "installation_path"?
>This should fix the problem with the path.
>If you have any questions feel free to reopen this one or create a new issue.
>Have a nice day!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Василий Рыженьков

**Comment by luc1an24** [comment]
Could be there any other issues with the script since this is the fix for paths with spaces in it (for .bat files)?

**Comment by vasy701** [comment]
No, I change the folder, it starts normally.   
>Пятница, 17 апреля 2020, 9:00 +03:00 от luc1an24 <notifications@github.com>:
> 
> 
>Could be there any other issues with the script since this is the fix for paths with spaces in it (for .bat files)?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Василий Рыженьков
