### ISSUE TITLE
Feature request: selected device remain highlighted

### ISSUE THREAD

**Issue by MonaxDK** [nicehash/NiceHashMiner#203]
It would be nice to make the selected device remain highlighted in blue when the focus is switched to the algorithms list. Now it's not very convenient, it's not always clear which device is selected.
This is certainly not the highest priority feature, but we want to make NHML perfect, right? :)

**Comment by DillonN** [comment]
Yes this has been an issue for a while, I will get around to it at some point but there are other features higher on the list!

**Comment by 619Srt** [comment]
well without that being fixed we can't mine?
