### ISSUE TITLE
mBTC prefix!

### ISSUE THREAD

**Issue by cyberpay** [nicehash/NiceHashMiner#2036]
is there a possibility to change BTC denomiation prefix milli (mBTC) in nicehash miner?

**Comment by nathsmaR** [comment]
Okey

**Comment by luc1an24** [comment]
Hi @cyberpay 
Thank you for reaching out.
There is a possibility to change from BTC to mBTC and vice versa in settings.
Got to Settings tab -> Advanced -> Check/Uncheck 'Autoscale BTC Values'
This will change format in which BTC rates are reported.

If you have any questions, feel free to reopen or create a new issue.
Have a nice day!
