### ISSUE TITLE
Error during benchmark for GPU

### ISSUE THREAD

**Issue by fmartinot** [nicehash/NiceHashMiner#2041]
The benchmark of all algorithms for GPU (AMD Radeon R7 M340), except one (Eaglesong) don't work. I already tried to uninstall my AV, reinstall NiceHash,... note that for the CPU, they benchmark well.
I also tried to do one benchmark a time, to change it to precise mode, but nothing worked.

**Comment by luc1an24** [comment]
Hi @fmartinot 
Thank you for reaching out.
Your GPU doesn't have enough memory for other memory heavy algorithms.
You can try to manually benchmark them (more about manual benchmarks in the [docs](https://github.com/nicehash/NiceHashMiner/blob/master/doc/Advanced/ManualBenchmarking.md)).

If you have any questions, feel free to ask.
Have a nice day!

**Comment by fmartinot** [comment]
Hi @luc1an24 
Thank you for your anwer, I'll try to benchmark manually then.

Have a nice day too !

**Comment by luc1an24** [comment]
Hi @fmartinot 
Have you solved the issue? Did you managed to manual benchmark some more algorithms?
If this is so please close the issue.

**Comment by fmartinot** [comment]
Hi @luc1an24 
Yes I tried to benchmark manually as you said but they still fail

**Comment by luc1an24** [comment]
Hi @fmartinot 
New benchmark process was introduced to the NHM.
Could you please try to benchmark algorithms again?
Have a nice day!
