### ISSUE TITLE
Need help to identify what causes the crash.

### ISSUE THREAD

**Issue by lmlim** [nicehash/NiceHashMiner#205]
Hi,

I need help identifying what causes the crashed. 1 of my rig crashed at ~23:53
i looked at the log files (log.txt and log1.txt), there are some errors several minutes prior to crash as well ~23:06.
i am not sure what when wrong.

an error just before the crash is:
[ADL] ADL fan getting failed with error code -1

anyway log files attached.

thank you.

**Comment by lmlim** [comment]
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1240377/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1240378/log.txt)

sorry logs did not show up on first post...

**Comment by MonaxDK** [comment]
Regardless of the log files, the most common cause of crash is overclocking. On Nvidia, it is easy enough to determine which of the cards failed. In general, the frequency is reset to the default on the failed card. Try to reduce the frequency.

**Comment by DillonN** [comment]
What exactly do you mean by crash? The entire PC shuts down?

It looks like the AMD Display Library is unable to get fan speed, if fan speed normally works it may be an instability issue. Otherwise certainly try without any overclocking.

**Comment by lmlim** [comment]
the PC freezes completely....  yes i did do some oc and under volt.

on 3x gtx 1070 (Power limit 65%), core +150, mem +750
on 1x r9 290x (core -81mv), cooler has been replaced with AIO liquid cooler.
on 2x gtx 1060 PL 90%, mem +700

this config has been stable for weeks. it started to freeze this past couple of days, after running several hours. 
PCI-E has been switched back to gen1 in BIOS, was trying with gen2.

thanks for replying.

**Comment by DillonN** [comment]
It sounds like something may be unstable, you could try mining with one card at a time to track down if any in particular are causing problems

**Comment by lmlim** [comment]
thanks MonaxDK and DillonN.
I am tracking it now...
