### ISSUE TITLE
NHML loads the CPU

### ISSUE THREAD

**Issue by deeppurple1968** [nicehash/NiceHashMiner#2050]
NHML at startup and for some time after it almost does not load the processor, but after some time (somewhere in half an hour or an hour) starts to load  processor 55-60% stably. Despite the fact that in previous versions 1.9 this was not. What is the reason? Windows 10 Pro x64, AMD Athlon II X2 250, RX588x5

**Comment by almartins** [comment]
Same here CPU load always near 100% which turn very difficult access miner remotely.
Windows 7 64 bits. 
Some times one or two GPU are stopped saiyng minning but no load and temp are low!! 
I'm returning to 1.9.2.21 which is running well with me.

**Comment by foxwarernd** [comment]
which file puts a load on the processor? (if you look through the task manager?)

**Comment by foxwarernd** [comment]
> NHML при запуске и какое-то время после него практически не загружает процессор, но через некоторое время (где-то через полчаса или час) начинает стабильно загружать процессор на 55-60%. Несмотря на то, что в предыдущих версиях 1.9 такого не было. Какова причина? Windows 10 Pro x64, AMD Athlon II X2 250, RX588x5


For many miners, there is also a load on the CPU - that is, mining goes on the GPU, but the results are checked on the CPU before sending to the pull. Very noticeable for weak CPUs and video cards over 3

**Comment by luc1an24** [comment]
Hi @deeppurple1968  and @almartins 
Thank you for reaching out.
As @foxwarernd stated some miners are using CPU for help - this can be then managed through extra launch parameters.
Could you tell us which miners are causing that so we can help you setting them?
Have a nice day!
