### ISSUE TITLE
The Application is not showing my GPU as a device

### ISSUE THREAD

**Issue by DankerWanker** [nicehash/NiceHashMiner#2051]
I have a RTX 2060 inside of my pc and NiceHash is not showing it as a device please help.

**Comment by ghost** [comment]
The same thing happens to me, but with a GTX 580

**Comment by gypsypathtech** [comment]
Same thing happens on my rig--nine 1080ti and one 1080. 3.0.0.7 will work, but the app tries to update automatically, which causes the same problem again.

EDIT: I thought it would work, but the app crashes and then shows no algorithms available if I try to use all 10 GPUs at one time.

**Comment by potikoutlaw** [comment]
same here using 2x 5700xt 1x 580 AMD cards !!!!!
