### ISSUE TITLE
VIRUS DETECTED !

### ISSUE THREAD

**Issue by ronaldrotte** [nicehash/NiceHashMiner#2053]
When I attempted to install the software my Anti-Virus detected virus from your software's file ! Would you explain why this happened ?

**Comment by scscgit** [comment]
It's well known that the third party mining tools, which need to be downloaded from other providers as NiceHash doesn't develop their own mining algorithms, are flagged by most anti-virus software. Have you been too lazy to read even the main [NiceHash README.md page](https://github.com/nicehash/NiceHashMiner)? Of course, you haven't even said which AV did you use, which file was flagged, or even what was the virus name (so we can assume it may even be a "PUP", "Mining Tool", or even some "Not-A-Virus" detection).

**Comment by khayto** [comment]
its literally explained a few lines down in the release tab... maybe try reading.
