### ISSUE TITLE
Linux appimage

### ISSUE THREAD

**Issue by AlexandreMarkus** [nicehash/NiceHashMiner#2055]
Would be nice to have a Linux version of this application

**Comment by tv0ll** [comment]
Was about to use Nicehash today upon a recommendation, but not having native linux miner software support killed that.

**Comment by DreadKnight** [comment]
Wow, no linux version in 2021, while it's been constantly asked for since half a decade now, oh well...

**Comment by AgenttiX** [comment]
Official Linux support would indeed be great, as we could then use our powerful Linux workstations for mining when they're not in other use. For the time being [nuxhash](https://github.com/YoRyan/nuxhash) might be a suitable alternative, but at least for me it crashes at launch.
