### ISSUE TITLE
Not Mining with Right GPU

### ISSUE THREAD

**Issue by jgonzis** [nicehash/NiceHashMiner#2056]
I have in my system:

2 1070
3 1070TI
1 RX580
1 Intel HD630 (that is not detected)

When I start to mine if I click on of the 1070, the miner Claymore and other start mining with one 1070 TI. Also it says is mining the 1070. I can see easy is mining the 1070 TI because the load is 100% in the 1070 TI.

[2020-05-06 11:17:29] [ERROR] [70984aa0-7236-11e9-b20c-f9f12eb6d835-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4,0)] Exception Referencia a objeto no establecida como instancia de un objeto.

If I launch all all work ok, except 1 of the 1070,... Of course if I launch it the Claymore or other manually it Works perfect the all the system

**Comment by jgonzis** [comment]
11:43:25:775	30c8	NVIDIA Cards available: 5 
11:43:25:776	30c8	CUDA Driver Version/Runtime Version: 10.2/8.0
11:43:25:790	30c8	GPU #0: GeForce GTX 1070 Ti, 8192 MB available, 19 compute units, capability: 6.1  (pci bus 8:0:0)
11:43:25:792	30c8	GPU #1: GeForce GTX 1070 Ti, 8192 MB available, 19 compute units, capability: 6.1  (pci bus 10:0:0)
11:43:25:793	30c8	GPU #2: GeForce GTX 1070, 8192 MB available, 15 compute units, capability: 6.1  (pci bus 12:0:0)
11:43:25:795	30c8	GPU #3: GeForce GTX 1070 Ti, 8192 MB available, 19 compute units, capability: 6.1  (pci bus 14:0:0)
11:43:25:795	30c8	Total cards: 4

**Comment by luc1an24** [comment]
Hi @jgonzis 
Thank you for reaching out and your patience.
Could you confirm that this issue is fixed?
Thank you and have a nice mining!
