### ISSUE TITLE
Enhance the nicehash update process, it's killing my rig

### ISSUE THREAD

**Issue by DarkMoose92** [nicehash/NiceHashMiner#2058]
In mining, I use only three miners: Phoenix, NBminer and Gminer.

Each time Nicehash is updated, it updates itself, and then installs other miners and launches a benchmark on new algorithms on all video cards at once. What for? Because of this, my rig with video cards hangs. After this, I can not enter the rig via remote access and I must physically reboot it.

Please make Nicehash NOT update other miners after updating the shell.

**Comment by S74nk0** [comment]
@DarkMoose92 this is a legitimate case. We can add a feature to whitelist/blacklist certain miners. 
The reason we have default miners is so when new algorithms come out we include these miners as well. 
But opting out of this is a valid use case and probably more people would want such a feature. 
We will include this in one of the upcoming releases

**Comment by S74nk0** [comment]
Keep issue open until feature is implemented and released.

**Comment by DarkMoose92** [comment]
> @DarkMoose92  We can add a feature to whitelist/blacklist certain miners.

Or you can even do this with a configuration file.

Let Nicehash keep a list of loaded miners. When updating the shell, the new version of Nicehash let it look at this list and download / install only those miners that are on this list.

If there is a new profitable algorithm on the miner that the user deletes, then the user himself must install this miner and run the benchmark.

If the user decides which miners he wants to remove, then he is experienced enough to follow the news and new algorithms.

Just my ideas) I apologize for my English.

**Comment by fritzr4** [comment]
To add to the suggestion of DarkMoose92

Add a checkbox that allows advanced users to disable the automatic benchmarking of algos that are not selected for use when an update keeps the previous settings

If the checkbox is checked, then the update will leave new algos UNselected.  In this situation it will be the user's responsibility to check the update information and select new algos that they want to test to see if they are compatible with the user's rig.

An informational tooltip explicitly explaining this behavior should be added to the checkbox that enables it.

**Comment by MSukharev** [comment]
Yes, to make possibility for user to choose miners for himself may reduce time for upgrade and benchmarking. I support this proposal.
More of this, sometimes any miners crashes some types of GPUs, and users prohibites this miners (lolMiner crashes my Vega cards, for ex.)

**Comment by ddm-j** [comment]
x2 on this. Was mining excellently until the last update. Relaunch and benchmark of all algos seems to have fried one of my Radeon VIIs (already a sensitive card). Not sure if that was related but was mining fine until the auto-update.

System instability since last update as well. Will be reverting.
