### ISSUE TITLE
Freeze app

### ISSUE THREAD

**Issue by Prajwalz12** [nicehash/NiceHashMiner#2059]
The nhm app freezes after log in.

**Comment by luc1an24** [comment]
Hi @pyruvate12 
Thank you for reaching out.
What exactly happens?
Could you send logs?

Thank you

**Comment by sitting444** [comment]
https://github.com/nicehash/NiceHashMiner/issues/2059#issue-613711663

**Comment by sitting444** [comment]
https://github.com/nicehash/NiceHashMiner/issues/2059#issue-613711663

**Comment by luc1an24** [comment]
We would need logs to see what exactly is happening.
Please check this post on how to send logs: https://www.nicehash.com/blog/post/how-to-create-a-log-report-with-nicehash-miner
Thank you for your help!
