### ISSUE TITLE
1.8.1.1 - NHML with gf1050 break second NHML with 1060

### ISSUE THREAD

**Issue by leonik3** [nicehash/NiceHashMiner#206]
When first start program NHML 1.8.1.1 with gf 1050 2GB (usually Equihash), then do something on another gf card (1060 3GB, which is first on NHML list). I can see this on MSI Afterburner, because gpu core on some seconds grows to 1500MHz. After that no one of Dagger Claymore algorithms works on 1060. There is an error. On NHM 1.7.5.13 there was not any problems, because this version does not contain this Claymore algorithms.

> 
CUDA error - cannot allocate big buffer for DAG. Check readme.txt for possible solutions.
GPU 0 failed
Setting DAG epoch #139 for GPU0
GPU 0, CUDA error 11 - cannot write buffer for DAG
GPU 0 failed
>

**Comment by DillonN** [comment]
Claymore is finicky with DAG generation and having other miners running that take up RAM can cause it to fail. Especially with lower VRAM cards (3GB is now on the lower edge of what is usable). You can try increasing your page file size

**Comment by leonik3** [comment]
I already have 32 GB page file size set manually (and 8GB RAM). There is another cards 1060 3gb in this rig. Only first card has problems. I think NHML (not Claymore) sometimes use first card even when work with another card (and take memory of this first card and it's not enough for mining on this first card).

**Comment by DillonN** [comment]
If you could post your `\logs\log.txt` file when this happens I could tell you if that is the case

**Comment by leonik3** [comment]
I made a video for this error. You can see usage of cpu and memory from 4 different cards. Most interested are from first card A and third card E (1050).
[https://youtu.be/yUjqNe6yQJw](https://youtu.be/yUjqNe6yQJw)

Here are the logs. The test started at 20:25, and the first error of card "A" occurred after 16 minutes about 20:41.
[log - A - 1060.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1273244/log.-.A.-.1060.txt)
[log - B - 1060.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1273243/log.-.B.-.1060.txt)
[log - C - 1060.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1273242/log.-.C.-.1060.txt)
[log - E - 1050.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1273245/log.-.E.-.1050.txt)

**Comment by leonik3** [comment]
Hi DillonN,
did you see already this video and these logs ?

**Comment by leonik3** [comment]
Now I know that there is an identical situation when there are 2 NV 1060 3GB cards. If the second card first launches Equihash, the first one can not start Dagger Claymore. There is identical error. If I close the second card with Equihash, the first one starts without error.

**Comment by DillonN** [comment]
See comment on #308
