### ISSUE TITLE
all algos are unprofitable after updating to 3.0.0.9

### ISSUE THREAD

**Issue by bormoley1983** [nicehash/NiceHashMiner#2060]
After automatic update and succesful benchmark I have all algos Unprofitable and btc values 0 while having original algos values set up as supposed to
Start mining button unavailable,
mine regardless of proffit turned on but do not work
Nothing helps,

How can I just dismiss unprofitable and enable mining any algo?

**Comment by Zephryn100** [comment]
I got the same problem please help as all my mining rigs are now unable to mine.

**Comment by gonz9** [comment]
Same here none of my rigs are mining . Help please!!

**Comment by Zephryn100** [comment]
I just created a log report for a bug and it fixed itself

**Comment by mcsjohn** [comment]
Same here. Also benchmark for KAWPOW fails every time. All algos appear twice for each GPU. GMinerCUDA9.0 files fail to download - there is notification about it and at each NH restart tries to download again.

**Comment by Zephryn100** [comment]
go to settings and go to the bottom and report the bug.  Mine auto fixed after that.

**Comment by mcsjohn** [comment]
> go to settings and go to the bottom and report the bug. Mine auto fixed after that.

Helps just for starting the mining. Other issues are still here

**Comment by gonz9** [comment]
Yeah it's mining now but if I restart the computer Everytime I open nicehash miner it's starts to download everything

**Comment by mcsjohn** [comment]
I have managed to fix all above issues after stopping NH, deleting miner_plugins and plugins_packages folders and then starting it again. But, this triggers also benchmark for all algos and devices.

**Comment by luc1an24** [comment]
Hi everyone
Thank you for reaching out
This issue was fixed so now should all work fine.

If you still experience this issue please reopen the thread.
Have a nice day!

**Comment by MognoKhan** [comment]
I am facing this issue. How to fix it?
