### ISSUE TITLE
Gminercuda 9.0 continue to reinstall

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#2064]
Gminercuda9.0+ keeps trying to install if for any reason I need to close the application and re-open.  I have the location   not being followed by my anti virus and no other messages from my pc to say otherwise.

Thanks

**Comment by SK-Crow** [comment]
I'm having this issue as well.  I have the C:\Users\me\AppData\Local\Programs\NiceHash Miner\ directory excluded in Windows Defender and it's still an issue.  I've allowed "Threat Blocked" messages entirely, and this continues with Windows Defender disabled.  I don't use any other anti-virus.
![image](https://user-images.githubusercontent.com/1341176/81524273-8a7d7080-931e-11ea-9a54-f1c3b62b63c9.png)

**Comment by akeadey** [comment]
Same problem here. 

1. Verified Exclusion is setup properly
2. Turned off real-time virus protection 
3. Turned off firewall

Still getting the notification

**Comment by akeadey** [comment]
Did a clean install and all the errors/notification went away

**Comment by techman05** [comment]
Got help on facebook on the matter. They told me to uninstall the plugin and reinstall it in the app. The few plugins that weren't installing properly are now up to date and not showing as available to install.

Do note though that the nicehash app was still warning me of files missing but I cleared the message since I think this quick fix fixed my issue.

Get TypeApp for Android<http://www.typeapp.com/r?b=15857>
On May 11, 2020, at 11:10 AM, akeadey <notifications@github.com<mailto:notifications@github.com>> wrote:

Did a clean install and all the errors/notification went away

**Comment by luc1an24** [comment]
Hi
Thank you for your report.
As this is already fixed I will close the issue.
If same thing will happen in the future please open a new one.
Have a nice mining!
