### ISSUE TITLE
[enhancement]  Last used miner (help to find miner crashing pc issue)

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#2070]
Is there a possibility to put some ai in to know when a miner goes off when its usually going to know if something had just started and it went down. I keep trying to go into the nice hash history and see if there is a last active indicator but at the moment it seems there is none. Thanks

**Comment by luc1an24** [comment]
Hi @techman05 
Thank you for reaching out and sorry for slow response.
We are unable to get info about PC crash beforehand so we can't tell you.
But there is realtime info on web so you can set a notification there if rig becomes inactive.
if you have any other questions feel free to ask!
Have a nice mining.
