### ISSUE TITLE
Auto updating is not working

### ISSUE THREAD

**Issue by Basiimov** [nicehash/NiceHashMiner#2071]
Auto-updating is not working on NiceHash version 3.0.0.9 -> 3.0.1.0.

What is causing the issue?

I've disabled AV and Firewall and it's not working.

See attached image for proof .

![Naamloos](https://user-images.githubusercontent.com/33926498/82123152-1e748f80-9798-11ea-8193-bf828609d165.png)

**Comment by luc1an24** [comment]
Hi @Basiimov 
Thank you for your patience.
Could you confirm that this issue is not happening anymore?
Thank you!

**Comment by modderchris** [comment]
same issue seems the auto update is broken as 3.0.2.0 still has the infinite loop and never completes an update
and obviously @Basiimov  we can't verify the issue is resolved if it is still bugged
