### ISSUE TITLE
NHM Version 3.0.1.0 will not start for me

### ISSUE THREAD

**Issue by ZaronDS** [nicehash/NiceHashMiner#2073]
I have had this issue with every version of NHM version 3 and on. I am running Windows 10 64bit on a 12 card mining rig, and I have made certain to give exclusions for all folders containing NHM in windows defender. I download a fresh copy of the zip, extract to the excluded folder, double click the exe, and what you see in the attached pic is what I get, with the logs in the background. No setup window, no asking me to agree, nothing, Just straight to crash. I am at a loss.
![Crash](https://user-images.githubusercontent.com/65836891/82743438-4d52ae80-9d20-11ea-96e3-abbf28a98622.JPG)

**Comment by S74nk0** [comment]
I am really sorry to hear that. 
Please try this https://github.com/nicehash/NiceHashMiner/releases/download/3.0.1.0/nhm_windows_3.0.1.0_tmp_test_fix.zip link and report back if this solves the issue.

**Comment by ZaronDS** [comment]
Thanks for your reply! Well, I tried that zip, and it was almost the same result, except this time the log didn't complain about the TOS being different.
![Crash](https://user-images.githubusercontent.com/65836891/82937022-4efcbc00-9f44-11ea-85c7-c585ab6c27e1.JPG)

**Comment by ZaronDS** [comment]
I would also like to add that NHM v1.9.2.22 runs just fine, and I have the correct Visual C++ 2013 redist installed and Windows 10 has .NET 4.5 built in. I have a few windows services disabled but I don't think they should affect this.

**Comment by ZaronDS** [comment]
any further test things for me to try?

**Comment by luc1an24** [comment]
Hi @ZaronDS  
Thank you for your patience
Could you please try to install [Microsoft Visual C++ Redistributable 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) and [Microsoft .NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer)?
These are latest libraries we are depending on so this could be the case.

**Comment by ZaronDS** [comment]
I just tried using those and it didn't help.

**Comment by luc1an24** [comment]
@ZaronDS Thank you for your patience.
We are still finding out what is going on.
Could you please send us event viewer messages? Tutorial for this step is here: https://www.nicehash.com/blog/post/how-to-send-windows-event-logs
Thank you and we will try to find the fix soon.

**Comment by ZaronDS** [comment]
So I checked the event viewer after trying to run NHM 3.0.1.0 and I did find something that looked like a lead. There were several errors in there all talking about d3d9.dll they all looked like this...
Log Name:      Application
Source:        Application Error
Date:          6/26/2020 11:36:58 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      MiningRig1
Description:
Faulting application name: NiceHashMiner.exe, version: 3.0.1.0, time stamp: 0xca903466
Faulting module name: d3d9.dll, version: 10.0.18362.387, time stamp: 0xc808fce5
Exception code: 0xc0000409
Fault offset: 0x000000000003e223
Faulting process id: 0x2d44
Faulting application start time: 0x01d64c4d5b4a4952
Faulting application path: C:\Users\Administrator\Desktop\NiceHash Miner 3 Eth\app_3.0.1.0\NiceHashMiner.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: f9d7f25d-b382-419f-9a22-3e89c61596f2
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-06-27T06:36:58.878949900Z" />
    <EventRecordID>40747</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MiningRig1</Computer>
    <Security />
  </System>
  <EventData>
    <Data>NiceHashMiner.exe</Data>
    <Data>3.0.1.0</Data>
    <Data>ca903466</Data>
    <Data>d3d9.dll</Data>
    <Data>10.0.18362.387</Data>
    <Data>c808fce5</Data>
    <Data>c0000409</Data>
    <Data>000000000003e223</Data>
    <Data>2d44</Data>
    <Data>01d64c4d5b4a4952</Data>
    <Data>C:\Users\Administrator\Desktop\NiceHash Miner 3 Eth\app_3.0.1.0\NiceHashMiner.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\d3d9.dll</Data>
    <Data>f9d7f25d-b382-419f-9a22-3e89c61596f2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by ZaronDS** [comment]
At long last I have figured out what the problem is. I have been connecting to my rig from my main PC via Remote Desktop Connection. Apparently RDC does not support DirectX, which is a shame. I did not know that until now. I mean, if I am making a mining rig as cheap as possible I thought it was a great way to save money by connecting to my rig via the network and logging in with RDC instead of buying another monitor, mouse, and keyboard. And it worked well enough until Nicehash started using DirectX. So, apps that use DirectX just up and crash when I try to launch them from an RDC connection. So, the problem was not a bug in NiceHash, but rather a limitation of RDC I was not aware of. Now I just need to find another solution to remote connect to my rig that actually works with DirectX. Thanks for your time looking into this and your patience! I will close this issue now.

**Comment by luc1an24** [comment]
Hi @ZaronDS 
Thank you for your feedback.
We were able to pinpoint the problem with it.
Could you please try the following build that should fix the issue: https://github.com/nicehash/NiceHashMiner/releases/download/3.0.4.3/nhm_windows_3.0.4.3_sw_rend.zip

Thank you!
