### ISSUE TITLE
cannot get the two new plugins to install correctly nicehash miner 3.0.2.0

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#2078]
i install the plugin and it says it is installed, i click install and it installs and says installed but then i look up at the new message it was installed and click more info it says "New version of "plugin" was not installed". i found a way around it last time a bunch of new plugins were available but i cant remember for the life of me. i tried administrator mode. also i have the OHC drivers installed and i cant seem where to instal the not OHC drivers. by the way, i love your work,huge fan.thank you.

**Comment by luc1an24** [comment]
Hi @zspeiser 
Thank you for reaching out.
I am glad that you like our work :)
Please check this blog post: https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
It should help you install new drivers

Could you also post your log.txt since there should be more info, why plugin was not installed.
Thank you

**Comment by ghost** [comment]
here is my log file. it should be at the very end cause i just tried it again.
also i installed the "standard" nvidia drivers just to notice that the gamer ready drivers are the exact same as the standard for my card. any advice?
[log.txt](https://github.com/nicehash/NiceHashMiner/files/4795971/log.txt)

**Comment by luc1an24** [comment]
Hi @zspeiser 
This log doesn't show anything plugin installation. 
Could you try to remove and install plugin?
Maybe there was an issue with plugin release.

**Comment by Paranoid-Dev** [comment]
@luc1an24 I have the same problem, but with all the plugins
Could you perhaps provide a separate version with all the plugins preinstalled?

**Comment by luc1an24** [comment]
Hi @Paranoid-OS 
This sounds like the AV issue.
Please disable AV during the download/installation phase.
If this doesn't work try to download them manually and check if you succeed.
If you are then this is not AV issue and we can troubleshoot some more.
Have a nice day!

**Comment by Paranoid-Dev** [comment]
@luc1an24 I have 0 AV running
I even have Windows defender disabled permanently by the Group policy maker

How can I manually download them?

**Comment by luc1an24** [comment]
Could you post screenshot of your "Plugins" tab and "Benchmarks" tab?
Go to github of one plugin that has troubles downloading and then download their release.
If you post screenshots we will have more understanding what is happening.

**Comment by Paranoid-Dev** [comment]
![image](https://user-images.githubusercontent.com/62641568/91714082-f33a7280-ebc5-11ea-9fd6-bad45ab445ad.png)
(before install attempt)

![image](https://user-images.githubusercontent.com/62641568/91714143-12d19b00-ebc6-11ea-819e-2b73e0239e38.png)
(after install attempt)

![image](https://user-images.githubusercontent.com/62641568/91714167-1c5b0300-ebc6-11ea-958e-acbf29b5f9c8.png)
(error message after install attempt)

![image](https://user-images.githubusercontent.com/62641568/91714213-3399f080-ebc6-11ea-9f66-21b0087c40b0.png)
(benchmark tab after install attempt)

I'm not sure what to do after downloading manually from Github. What to do after manually downloading?

![image](https://user-images.githubusercontent.com/62641568/91714407-9ee3c280-ebc6-11ea-8326-52bca376e449.png)
(plugin folder looks like this, if this is of any help)

**Comment by luc1an24** [comment]
https://github.com/develsoftware/GMinerRelease/releases/tag/2.22
Try to download latest release of GMiner. Just download it and tell me if you are able to do that.

I would expect that "bins" folder in plugin folder (the one from screenshot) is empty => inside version folder there are no .exe files?

**Comment by Paranoid-Dev** [comment]
![image](https://user-images.githubusercontent.com/62641568/91714621-1fa2be80-ebc7-11ea-9da9-689b5c42e758.png)
It seems okay to me

**Comment by Paranoid-Dev** [comment]
> https://github.com/develsoftware/GMinerRelease/releases/tag/2.22
> Try to download latest release of GMiner. Just download it and tell me if you are able to do that.

Okay, so should I replace what's in the **bins** folder with this?

**Comment by luc1an24** [comment]
I just figured it out
The GPU is the problem. It has 2GB of memory and no algorithms are suitable for it.
Theoretically you could mine ZHash with it but since it is primary card Windows 10 uses about 500mb of its memory and therefore making the card non-supported for algorithm.

I will check if there is any algorithm that has no ram requirements

**Comment by Paranoid-Dev** [comment]
Oh, okay
The mining calculator had GTX 960 on it, which is also 2GB(at least, some models), so I thought it was okay
Thanks for your help

And one can mine lyra2v2 lyra2v3 equihash144 equihash96 ubiqhash etc with a 2GB card

**Comment by luc1an24** [comment]
I checked and the lowest requirement is 2GB
But as I said windows takes quite a lot of memory from card.
You should try mining with NHOS (https://www.nicehash.com/nhos-mining)
This is mining OS meaning that it should be able to mine those algos on your card.

I hope I was helpful, 
Have a nice day!

**Comment by Paranoid-OS** [comment]
Windows uses 0.3GB on my PC when idle.
I can mine from a pool with the algos mentioned above.
So could you make it possible to at least download the plugins?

![image](https://user-images.githubusercontent.com/62641568/91721028-099afb00-ebd3-11ea-92c9-217fec0e2ca9.png)
And also, XMRstakRX failing to install too seems to suggest that this isn't a "GPU lowest requirement" related problem. Isn't XMRstakRX runnable on CPUs?

**Comment by Paranoid-Dev** [comment]
@luc1an24 You seem to be right, as installing CPU-algo plugins worked.
However, since I can actually mine using the miners you provide as plugins at pools, I think I have enough Vram.
![image](https://user-images.githubusercontent.com/62641568/91790760-7ef6e200-ec4c-11ea-9630-b7439a9ca667.png)
(mining with eqihash144 with miniz)
Can you change the plugins install script so that it at least installs? even if it won't run

**Comment by Paranoid-Dev** [comment]
@luc1an24 GTX 950 can do 220MH/s with the keccak algorithm with ccminer using less than 400mb of Vram, which I see you have (https://www.nicehash.com/algorithm/keccak)
So can't you at least enable downloads for low end hardware, even if you think they won't run?
I'm sure people with more outdated hardware have the same issue

**Comment by luc1an24** [comment]
Hi @Paranoid-OS 
We have these filters for stability purposes.
If you think that you will be able to mine on this GPU you can still start miner manually.
Download wanted miner and redirect it to NH stratum - you can find ports and urls here (https://www.nicehash.com/algorithm)
If you will need any help say so and I will try to help you.

For example if you would like to mine ZHash on miniZ start miniZ miner with cmd with following command:
`./miniZ.exe --par=144,5 --server=zhash.eu.nicehash.com --port=3369 --user=yourNICEHASHbtcAddress --telemetry=anyPort (4000/4001/4002...) --pers=auto`

**Comment by Paranoid-Dev** [comment]
Thank you
So you're saying I can use NiceHash without using https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.4.3 ?
I'll give it a try, thanks
