### ISSUE TITLE
benchmark not work

### ISSUE THREAD

**Issue by suxxer1** [nicehash/NiceHashMiner#2079]
I can't pass no one benchmark, errors any time
![Безымянный3](https://user-images.githubusercontent.com/44575252/84360283-815c1980-abd2-11ea-9b64-905de8f8a093.jpg)

**Comment by luc1an24** [comment]
Hi @suxxer1 
Thank you for reaching out.
Could you please forward your logs so we can find out what went wrong?
Thank you!

**Comment by NTikKho** [comment]
Me too 
When  i chose to benchmarck  DaggerHashimoto Only  It stops after 5 seconds 
amd#1 RX580 4G
Status error

ALGORITHM STATUS No Benchmark

**Comment by suxxer1** [comment]
problem solved, the problem was with the windows firewall
