### ISSUE TITLE
Feature request: after algo switch run bat file

### ISSUE THREAD

**Issue by Avalonis** [nicehash/NiceHashMiner#208]
Hi all,

it would be great after every algo switch run on bat file, for Afterburner settings. The thing is that temporaly one of my gpu on one rig restore (killing) the AB settings. It would be realy nice to restore the clocked with the a file.

second idea are for every algo a single bat file too manage the best AB settings for the best effecient

**Comment by DillonN** [comment]
Thank you I'll look into this

**Comment by Avalonis** [comment]
Great Thanks,

Unfortunately I have no option for a comando line command for the "MSI Afterburner" found. 

But there are short cuts in the "nvidiainspector" which can restore the all clocks at the command line.

**Comment by RAlvarez66** [comment]
This would be great Dillon. Right now I'm using another miner because you need more than one Afterburner profile (OC memory, OC core, a bit of both, etc) to achieve the best speed for different algos.

**Comment by Alien-Tretech** [comment]
Any news? still much needed

**Comment by S74nk0** [comment]
this is possible and here is the description https://github.com/nicehash/NiceHashMiner/issues/2597#issuecomment-1018562403
