### ISSUE TITLE
1 GPU stopped but signed as mining - V 3.0.2.0

### ISSUE THREAD

**Issue by almartins** [nicehash/NiceHashMiner#2081]
After some hours mining I found one GPU stopped but market as mining. See pictures attached;
![1 GPU stopped](https://user-images.githubusercontent.com/47713632/84629520-59c2c500-aee2-11ea-96db-d6b57e20279b.png)
![1 GPU stopped_2](https://user-images.githubusercontent.com/47713632/84629527-5d564c00-aee2-11ea-9d26-e5509b9d3e1b.png)

After I stopped and start again that rig all ok:
![1 GPU stopped_3](https://user-images.githubusercontent.com/47713632/84629587-7828c080-aee2-11ea-9678-65f0baac8721.png)

Windows 7 Pro 64 bits

**Comment by luc1an24** [comment]
Hi @almartins 
Thank you for reaching out.
Could you send me the logs from that time? So I can see why the GPU was marked as active and more importantly why it stopped mining.
Thank you!

**Comment by almartins** [comment]
Hi,
Logs from that time.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/4822258/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/4822259/log.1.txt)

**Comment by luc1an24** [comment]
@almartins 
Thank you for the logs
It seems like something was wrong with the GPU: `NVML failed with code GPUIsLost.`
Do you have any different OC settings for GPUs?
It is strange since it should stop the card if it went dead.
Does this still happen?
If so please check if you get "No available algorithms" notification.
It could be possible that the card was unstable and all algorithms got disabled.
Thank you

**Comment by almartins** [comment]
Hi  luc1an24,

That rig has 4 cards (3 1080Ti and 1 1080)  all differents brands and  yes have different OCs. The problem always is occoring to the 1080 one and is not frequent. Some days dont  occor. To make it run only have to stop the card and start it again.The log I sent are from yesterday so still is happen.

B. regards
________________________________
De: luc1an24 <notifications@github.com>
Enviado: 24 de junho de 2020 13:04
Para: nicehash/NiceHashMiner <NiceHashMiner@noreply.github.com>
Cc: almartins <almartins@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nicehash/NiceHashMiner] 1 GPU stopped but signed as mining - V 3.0.2.0 (#2081)


@almartins<https://github.com/almartins>
Thank you for the logs
It seems like something was wrong with the GPU: NVML failed with code GPUIsLost.
Do you have any different OC settings for GPUs?
It is strange since it should stop the card if it went dead.
Does this still happen?
If so please check if you get "No available algorithms" notification.
It could be possible that the card was unstable and all algorithms got disabled.
Thank you

**Comment by almartins** [comment]
Hi,
The problem is different now, the card is mining but information about load, temperature, profitability are missing
![image](https://user-images.githubusercontent.com/47713632/86329257-cd343880-bc3d-11ea-87fd-4b88552297fb.png)

[log.1 - Cópia.txt](https://github.com/nicehash/NiceHashMiner/files/4862613/log.1.-.Copia.txt)
[log - Cópia.txt](https://github.com/nicehash/NiceHashMiner/files/4862614/log.-.Copia.txt)

**Comment by MSukharev** [comment]
I have a similar problem. One of the six cards (Vega 56) shows zero speed. After rebooting the system, it works fine for a while. After 20-40 minutes again zero speed. I banned the work of this card in NHM, launched the second NHM, 5 cards in the first one have been working without problems for a week, one card in the second one also works non-stop. 
First NHM named Worker2, second Worker3. When I check mining on the NiceHash site, it shows sometime Worker2, sometime Worker3. But common speed is all-right.

**Comment by luc1an24** [comment]
Hi @almartins 
We are working on better NVIDIA monitoring at the moment, so stay tuned for upcoming releases.
@MSukharev are you using the latest version of NHM (3.0.4.0)?
Also in which language is windows OS installed on your system?
Thank you

**Comment by MSukharev** [comment]
Hi! When I have using NHM 3.0.3 I get Errors with all the cards in my rig (screenshots added) 
![Errors304](https://user-images.githubusercontent.com/21043139/88146150-258aa480-cc04-11ea-8396-4e9eab4172a6.png)
![Errors304b](https://user-images.githubusercontent.com/21043139/88146161-26bbd180-cc04-11ea-92f7-821b38b07f00.png)
Then I go back to NHM 1.9.2.22 and all work right. Now I try NHM 3.0.4.0 and it works. But I get system restarts every few hours. 
Now I have set power -20% for all Vega cards by AMD Settings and system restarts only one time per day. 
Language of OS installed is Russian.
Thank You for answer!
