### ISSUE TITLE
Windows 10 Unknown Provider

### ISSUE THREAD

**Issue by spaced-out-factory** [nicehash/NiceHashMiner#2083]
When I use the installer Windows 10 gives me a warning of an unknown provider.

**Comment by luc1an24** [comment]
Hi @zachdyer 
Thank you for reaching out!
This message is shown, because we are not signing our NHM anymore.
Since we are using 3rd party miners we cannot guarantee for their code.
If you have any questions, feel free to ask.
Have a nice day!

**Comment by moayadalsaleh** [comment]
Dears,

Hope you are doing well , so do you guarantee that no data will be leaked from my PC other than whatever is required for mining ?

**Comment by luc1an24** [comment]
Hi @moayadalsaleh 
I can guarantee for the NHM code. But since we are using 3rd party miners (most of them are closed source) we can't guarantee their behaviour.
Thank you for understanding.
