### ISSUE TITLE
No algorithms in Nicehash miner V.3

### ISSUE THREAD

**Issue by worldlife2** [nicehash/NiceHashMiner#2084]
Hi, 

Nicehash miner (V.3.0.2.0) won't show any enabled or benched algorithms. 

Six weeks ago NH was working great with 2 rigs (6x gtx1080Ti and 2x gtx1080). Sudden stability issues with the update made me switch to mine other algos. 
I went to update  NH to latest version today, and all listed enabled and benched algos were missing in first rig. After hitting start benchmark, a red error on status appears. Tried reinstalling drivers, with no luck. Copied the NH folder from 2nd rig, also no luck.

**Comment by luc1an24** [comment]
Hi @worldlife2 
Thank you for reaching out.
What do you mean by "missing algos"?
Could you please screenshot your benchmark page?
Also if you could retry benchmark process and attach log.txt it would be great help.
Thank you!
