### ISSUE TITLE
Nicehash Wont Work On Windows 7

### ISSUE THREAD

**Issue by Githseb** [nicehash/NiceHashMiner#2085]
Whenever I try to open NHM after downloading it, the app deletes itself. I try to redownload the app again and it always deletes itself.

**Comment by luc1an24** [comment]
Hi @Githseb 
Thank you for reaching out.
The most possible reason for this is that your AV is deleting program.
Please check this article and inform us about the results:
https://www.nicehash.com/support/mining-help/nicehash-miner/my-broswer-antivirus-software-reports-nhm-as-a-virus
Also make sure that you put exception into firewall for the NHM directory.
If you have any questions, feel free to ask!
