### ISSUE TITLE
Benchmark - Algorithms View - Green Highlight dissappears

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#21]
During a benchmark test an algorithm turns green when completed its benchmark.  However if you switch between devices then the green disappears.

I am not sure if this was intended but my guess is it should stay green during the entire benchmark run and then once the entire test is complete then since those are established benchmarks then the green highlight can go away.

**Comment by CreamyG31337** [comment]
yeah similar issue with the settings screen -- if I'm trying to copy the benchmark results from one card to another it doesn't keep the card highlighted once you click on the algo so I can't really verify i'm clicking things correctly. (okay i think I meant to write this on #13 lol sorry)

**Comment by DillonN** [comment]
I have noticed this too. At the moment interface updates are secondary to features/speeds so it will probably be fixed later.

**Comment by DillonN** [comment]
"When you uncheck a miner algorithm in the benchmark screen the blue highlight stays rather than going to grey

If you check an algorithm thats grey it highlights blue

The blue does disappear once you hit start however"
