### ISSUE TITLE
No supported devices

### ISSUE THREAD

**Issue by ABoyNamedTom** [nicehash/NiceHashMiner#2102]
I have attached my log file, every time I try to open NHM it throws up the "No supported devices" error. I have a 560Ti and a pentium g2030.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/4906187/log.txt)

**Comment by luc1an24** [comment]
Hi @ABoyNamedTom 
Thank you for reaching out.
Your devices are sadly not supported by NHM
For CPU mining you would need a modern CPU with SSE2 support
and for NVIDIA mining any NVIDIA GPU with Compute capability (SM) 3.0 or newer

If you have any questions, feel free to ask!
Have a nice day :)
