### ISSUE TITLE
MinerReservedPorts.json config, remote manager

### ISSUE THREAD

**Issue by Archtersim** [nicehash/NiceHashMiner#2104]
nicehash run claymore miner with -mport 127.0.0.1:-4000, how can i change 127.0.0.1 or e.t.c?

**Comment by luc1an24** [comment]
Hi @Archtersim 
Thank you for reaching out.
As of Claymore documentation you can't change IP only port => we have nothing to do with the IP of monitoring server
Here is documentation for mport flag:
> -mport   remote monitoring/management port. Default value is -3333 (read-only mode), specify "-mport 0" to disable remote monitoring/management feature.
   Specify negative value to enable monitoring (get statistics) but disable management (restart, uploading files), for example, "-mport -3333" enables port 3333 for remote monitoring, but remote management will be blocked.
   You can also use your web browser to see current miner state, for example, type "localhost:3333" in web browser.
   Warning: use negative option value or disable remote management entirely if you think that you can be attacked via this port!
   By default, miner will accept connections on specified port on all network adapters, but you can select desired network interface directly, for example, "-mport 127.0.0.1:3333" opens port on localhost only.

If you have any questions, feel free to ask!
Have a nice day!

**Comment by Archtersim** [comment]
_Hi @luc1an24 ,thank you for comment!

Its about nicehash. im trying to run claymore miner from nicehash with specify mport. for example i need -mport 4100. nicehash run it with default -mport 127.0.0.1:-4000. i found a way to change mport, but not completly. here are code of "MinerReservedPorts.json"
{
  "use_user_settings": true,
  "uuid": "c9abdb10-94eb-11ea-a64d-17be303ea466",
  "name": "ClaymoreDual",
  "algorithm_reserved_ports": {
        "DaggerHashimoto": [4100],
        "DaggerHashimoto+Decred": [4110],
    }
}
and ive got -mport 127.0.0.1:-4100, its only local. but im need -mport 4100, or atleast -mport -4100. after all i`m trying to run remotemanager (ethman)_

**Comment by luc1an24** [comment]
I am not sure that you are setting the code inside file right. Please check this article: https://github.com/nicehash/NiceHashMiner/blob/master/doc/Plugins/InternalSettings/MinerReservedPorts.md
For example if you would like to set port to 5100 you would do something like this:

> {
>   "use_user_settings": true,
>   "algorithm_reserved_ports": {
> 	"DaggerHashimoto": [5100]
>   }
> }

Please inform me if you will be successful!

**Comment by Archtersim** [comment]
@luc1an24  its doing the same for me. 127.0.0.1:-5100 in that case

**Comment by luc1an24** [comment]
Oh I see the problem now
Well we disabled remote management for security reasons. If you know some programming you can rebuild Claymore Plugin with the following change in ClaymoreBase:
>protected override string MiningCreateCommandLine()
 >       {
 >          _apiPort = GetAvaliablePort();
 >          return CreateCommandLine(_username) + $" -mport 127.0.0.1:{_apiPort}";
>        }

Then you will be able to enable remote management.
If you would need some help with rebuilding feel free to ask.

**Comment by Archtersim** [comment]
it works! @luc1an24 , thank a lot, Im very appreciate it (i receive necessary -mport 4100)
