### ISSUE TITLE
NiceHash Miner 3.0.0.4 Crazy Memory Utilizations, Can't Close

### ISSUE THREAD

**Issue by kimpurcell** [nicehash/NiceHashMiner#2109]
NiceHash is using over 50% of my physical memory (32GB total)!!

The memory utilitization keeps increasing as I keep the miner on longer.
Also, when I click "X" to close the miner, it won't kill / release the memory allocated!
I tried closing via the system tray icon "Close" menu item as well, which doesn't go away still.

The only way I can kill it is via Task Manager.

Please help!
![Screenshot 2020-07-19 12 50 50](https://user-images.githubusercontent.com/17389179/87881413-bf611000-c9be-11ea-91a6-9bdf18ecca39.png)

**Comment by kimpurcell** [comment]
When I kill the process, it just gets relaunched again. Weird!

**Comment by luc1an24** [comment]
Hi @kimpurcell 
Thank you for reaching out. Did you mean NHM 3.0.4.0 version?
What kind of Gpu's  do you have in your system?
If you are launching installed NHM (not zip one) there is NiceHash Miner Launcher which restarts NHM, so you should kill that one first.
Could you send us some logs so we can check if if some error is causing this over usage?
Thank you!

**Comment by kimpurcell** [comment]
Yes, 3.0.4.0 version. 2080 Ti. Yeah, I’ve noticed there are two nicehash processes, I’m assuming one of them is the launcher.
How do I get the logs?

**Comment by luc1an24** [comment]
Go to the installation root c:/Users/USER/AppData/Local/Programs/NiceHash Miner -> there you will run the "CreateLogReport.exe" which will generate .zip file and then you will post it here or send it via email to domen.kirnkrefl@nicehash.com

**Comment by Dohtar1337** [comment]
Memory leak by NVIDIA drivers. Disable Device monitoring in advanced settings.
