### ISSUE TITLE
KAWPOW is dead*

### ISSUE THREAD

**Issue by milkcoins** [nicehash/NiceHashMiner#2113]
*for mining on GPU with 3GB of memory on Windows 10.

**Comment by luc1an24** [comment]
Hi @milkcoins 
Thank you for reaching out and for informing us about the increased dag size.
Which Win version are you using?
We tested on Win10 and it really is over with 3gb cards on kawpow, but what about win7?
Have a nice day

**Comment by milkcoins** [comment]
> Which Win version are you using?

Windows 10 Enterprise LTSC.

> but what about win7?

Did you test it on Windows 7? Has the video memory enough?

**Comment by luc1an24** [comment]
No I did not since we don't have such system available for testing, maybe you could ask on our reddit or discord fellow miners about their experience.
I have seen a post  about this topic so you mind check it out: https://www.reddit.com/r/gpumining/comments/hz1g7t/gtx_1060_3gb_help/
Have a nice day

**Comment by luc1an24** [comment]
Hi @milkcoins 
we have discontinued kawpow mining on 3gb cards
Thank you for information!
Have a nice day
