### ISSUE TITLE
support tpruvot ccminer2.2 with cryptonight.

### ISSUE THREAD

**Issue by Mystere** [nicehash/NiceHashMiner#212]
There seems to be a pretty good interest in Monero mining, and the current implementation in 1.8.1.1 is ccminer_cryptonight and is not supported on pascal cards.

I suggest you switch to tpruvot ccminer2.2 which has a much better cuda cryptonight algorithm.  Since you already have this miner, it shouldn't be much to switch this and add support for pascal cards, correct?

**Comment by adem4ik** [comment]
Already discussed here https://github.com/nicehash/NiceHashMinerLegacy/issues/200 Dillon said that he "Will look at adding it in for that". I guess you may close your topic.

**Comment by DillonN** [comment]
Yes I'll get this in, going to close this though for clutter reasons
