### ISSUE TITLE
VideoControllers (GPUs) are detected but AMDdetector is Zero

### ISSUE THREAD

**Issue by Guche132** [nicehash/NiceHashMiner#2123]
Hi, I'm having issue with the latest nicehash miner(3.0.4.2), GPUs are not detected in the interface.
Installed the latest drivers(already used DDU) for AMD -Radeon 20.7.2
Windows 10 Pro version 1903

using 6 RX 570 4gb

Also attached the log file.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/5012524/log.txt)

**Comment by luc1an24** [comment]
Hi @Guche132 
Thank you for reaching out
We have tried same settings and gpus are detected.
Which motherboard are you using?
There could be option that you have 4g decoding disabled in the bios.
Does claymore for example detect your gpus if you run it directly?
Have a nice day!

**Comment by Guche132** [comment]
hi @luc1an24 ,
Im using Asus b250 mining expert.
The 4g decoding is enabled in the bios

**Comment by luc1an24** [comment]
Does device manager detects your cards?
Please check that first.
What happens if you start some 3rd party miners by hand?
Do they find your GPUs?
Thank you!

**Comment by Guche132** [comment]
@luc1an24 , found out the problem was my windows OS so I reverted it back. GPUs are now detected but benchmarking fails for Claymore

**Comment by luc1an24** [comment]
Good to hear that detection works now!
Most possible reason for that kind of behavior would be that Dag file is too big to miner Dagger via Claymore with 4gb cards
Does it benchmarks on Phoenix?
Have a nice day

**Comment by Guche132** [comment]
@luc1an24 , working fine on Phoenix, just that 1 gpu always fails.

**Comment by luc1an24** [comment]
Ok
Do you use Extra Launch Parameters?
There is an option: "-dagrestart" which could help you on mining dagger algo.

**Comment by Guche132** [comment]
@luc1an24 ,

it working now on my end, just need to update the phoenix miner but it seems like theres an issue in connecting to the pool.
just tried all locations available and after some time, the issue occurs

![image](https://user-images.githubusercontent.com/69118937/90318380-aff3c900-df62-11ea-9782-d9078bf1c8f2.png)

**Comment by Guche132** [comment]
Hi @luc1an24 ,
its now working but 1 gpu always goes 0mh/s after a while around 8-10hrs.
it works after doing benchmarking again.
do you know a fix or some extra parameters to fix this?

**Comment by luc1an24** [comment]
Hi @Guche132 
What does web report?
Is the card mining and 0's are shown or the gpu hangs?
In both ways we can't do much since this is hardware related.
There is also no watchdog parameter which could help with this.

**Comment by Guche132** [comment]
I see. Okay thank you very much. :)
