### ISSUE TITLE
I can only mine with my cpu, cant mine with gpu for some reason

### ISSUE THREAD

**Issue by SSsulaiman** [nicehash/NiceHashMiner#2127]
I can only mine with my cpu (which is horrible for profit), why can't i mine with my gpu?
![nhm ](https://user-images.githubusercontent.com/59779042/89672611-9f51ac00-d8ed-11ea-8301-71d72e4e4df6.png)

**Comment by SSsulaiman** [comment]
Please reply, i will reply to you as soon as possible!

**Comment by luc1an24** [comment]
Hi @SSsulaiman 
As I can see you are running NHM on a laptop.
We do not support laptop GPUs and therefore the GPU is not enabled.
Also it only has 2GB of RAM which wouldn't be profitable for you at all.
If you have any questions, feel free to ask!
Have a nice day!
