### ISSUE TITLE
Updated to Nicehash 3.0.4.2 but GPU status now is "Error" - NVidia Quadro M5000

### ISSUE THREAD

**Issue by faith1001** [nicehash/NiceHashMiner#2128]
Hello there,

I have updated to Nicehash 3.0.4.2 but now I find that my GPU status is stated as "Error" in the Nicehash miner app and I am unable to use it to mine anymore. My GPU model is Nvidia Quadro M5000. However, my CPU is mining ok. Please help. Thanks!

**Comment by luc1an24** [comment]
Hi @faith1001 
Thank you for reaching out.
Could you please provide me some more information about the issue?
Could you try to reopen the program and restart benchmarking process?
Most of the time the problem with failed benchmarks/mining is with Anti-Virus program blocking the miners.
If this is not AV problem please share your logs with me or support team on email.
Have a nice day!

**Comment by faith1001** [comment]
Hi @luc1an24 
Thanks for responding.
Yes, I have restarted the PC and also the program.  GPU still shows as "Error" in the Nicehash Miner app and also there is nothing to benchmark for GPU. I do not think it is an AV issue as it was doing fine all along. Include here is the log file (and a couple of other snapshots) which hopefully can shade some light on this matter. Thank you.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/5054679/log.txt)

![1](https://user-images.githubusercontent.com/69380820/89856100-e5975b80-dbca-11ea-972c-78d22e135ae5.JPG)

![2](https://user-images.githubusercontent.com/69380820/89856109-eb8d3c80-dbca-11ea-9dc9-6f348945e921.JPG)

**Comment by luc1an24** [comment]
As I can see no plugins or valid algorithms are detected for your GPU.
Therefore you should check if there are any plugins installed in the first place (head to plugins tab and check for installed plugins).
Please inform me of your findings.

**Comment by faith1001** [comment]
Hi @luc1an24 
Great! So that was the problem. Thanks for the helpful advise. Appreciate it!

**Comment by panpodziemia100** [comment]
Hi, 
I have this same problem
![obraz](https://user-images.githubusercontent.com/79572796/108980563-15501180-768c-11eb-8c4b-4559332f5032.png)

**Comment by stewie2000** [comment]
I have the same problem too but my gpu isn’t showing

**Comment by swainy79** [comment]
panpodziemia

> Hi,
> I have this same problem
> ![obraz](https://user-images.githubusercontent.com/79572796/108980563-15501180-768c-11eb-8c4b-4559332f5032.png)

Did you get a resolution to this issue, im having the same issue. Cheers

**Comment by arafatrajput** [comment]
My gtx1650 4gb not mining in nice hash please help me
My cpu mining but gpu not mining
