### ISSUE TITLE
nicehash 3.0.4.2

### ISSUE THREAD

**Issue by twk2741** [nicehash/NiceHashMiner#2129]
After updating to nicehash 3.0.4.2 version, it is no longer possible to mine Daggerhashimoto with ClaymoreDual, and the miner is stuck due to multiple GPU errors.

The cause is unknown. Although we have not updated Windows since 2019, the situation is the same even with the miners that have recently updated Windows.

The miner is using RX570 4G such as HIS, ASUS, and SAPPHIRE.

Since it is written through a translator, there may be a mistranslation.
Oh and, nvidia products are well mined.

Please advise me I want to solve the problem quickly and mine.

 
![캡처1](https://user-images.githubusercontent.com/69386768/89708157-a3de9900-d9af-11ea-9c89-7106a5eacfc5.PNG)

![캡처2](https://user-images.githubusercontent.com/69386768/89708316-fa000c00-d9b0-11ea-9352-3b33ee4c54ea.PNG)

![캡처3](https://user-images.githubusercontent.com/69386768/89708318-fb313900-d9b0-11ea-8aba-161fa313ee2e.PNG)

**Comment by luc1an24** [comment]
Hi @twk2741 
Thank you for reaching out.
Size of DAG file has reached a value where some 4gb cards are not mining well anymore.
I would recommend you to use Phoenix miner which requires less memory for generating dag files.
Also check extra launch parameters if there is anything you could use to continue mining (different generating of dag file maybe)
If you have any questions feel free to ask!
Have a nice day!

**Comment by jabteles** [comment]
Hi @luc1an24 , I also have this issue with GTX 1650 with 4GB dedicated VRAM and I understand the limitation, what I can't understand is why I can successfully generate DAG with Integrated AMD Radeon RX Vega 10 with 512MB dedicated VRAM , the only thing I see here is that this card has 7GB **shared** VRAM (but also my 1650 has) and it shows "AMD#1 AMD Radeon(TM) RX Vega 10 Graphics 6.1GB)" in the NiceHash window. Maybe it is this "fake" 6.1GB ram that let the minner generate the DAG? The true is that it can generate! Maybe there is a way we can pass the shared memory as a "fake" dedicated VRAM to the miner, or let it create DAG on the shared memory and like this we can again mine with the 4GB cards like 1650? PS: Yes, it's a laptop, but for me it's profitable with the 1650 and I'm also using to learn.

**Comment by backwerd** [comment]
this is an issue with claymore not nicehash

**Comment by twk2741** [comment]
Thanks for commenting @luc1an24. That's an inevitable problem. T.T

**Comment by twk2741** [comment]
Mining is really hard. Thanks for commenting @jabteles! I now close mining. Everyone be rich.

**Comment by twk2741** [comment]
Thanks for leaving the comment @ backwerd
