### ISSUE TITLE
how can i remove a ALGORITHM

### ISSUE THREAD

**Issue by liranscu** [nicehash/NiceHashMiner#213]
like X11Gost, this one is only the Momentary high profit, only in 10 s , so i dont want my minners switch to this ALGORITHM, how can i set ,i have already remove the enabled mark at settings/devices/Algorithms , but the minner still work on X11Gost . 
thanks for all replay~~~~~

**Comment by lmlim** [comment]
make sure you didn't miss any of x11gost miner variants as well...

i uncheck all i don't want, and i will browse profit calculator once in a while to see i might miss hot algos, and then add those hot algos.

**Comment by DillonN** [comment]
Like @lmlim said make sure you have all X11Gost algorithms unchecked (there are probably two).

**Comment by liranscu** [comment]
@DillonN @lmlim thx guys , i will to check again
