### ISSUE TITLE
No supported devices -Nicehash -pl help

### ISSUE THREAD

**Issue by saroja9117** [nicehash/NiceHashMiner#2132]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by luc1an24** [comment]
Hi @saroja9117 
Thank you for reaching out.
Could you please forward the logs?
Also tell me more about your configuration.
Which Gpus do you use.
Thank you

**Comment by saroja9117** [comment]
Hi..

Thanks for ur reply..
Can u plz guide me how to collect the logs and how to check GPU config...

**Comment by luc1an24** [comment]
Hi
In settings tab you select "General" and then scroll to the bottom where you will find "Generate Log Report". This will generate log report on your desktop which you will forward to my email address: domen.kirnkrefl@nicehash.com
This will give me info about your configuration and why your gpus are not detected

**Comment by saroja9117** [comment]
hi..

sorry am still not able to find generate log report.. plz help
GPU snapshot enclosed

**Comment by luc1an24** [comment]
1) Go to General settings
![image](https://user-images.githubusercontent.com/38202823/90505442-ebed8080-e152-11ea-9e48-f1eb19ed2c3a.png)
2) Scroll to the end of inner page and click "Create a log report"
![image](https://user-images.githubusercontent.com/38202823/90505528-0e7f9980-e153-11ea-8c23-d5bde9a870cb.png)

3) This will push the log to our server and modal window will show you uuid which you can send to me so I can find the log.

If you have any problems please tell me.

**Comment by saroja9117** [comment]
Hi..

Thanks for ur reply.. Enclosed is the snapshot..
Once i open nicehash miner, i will get this error and not able to proceed
further..
Am not able to go Settings also..

**Comment by luc1an24** [comment]
Hi @saroja9117 
I didn't receive any snapshot
Which error is displayed?

If you are unable to create log report via program you can also do it manually by:
=> If you are using installed version:
1) Go to your install root folder: AppData/Local/Programs/NiceHash Miner
2) Run "CreateLogReport.exe"
3) Send me generated (tmp._archive_logs.zip) zip file

=> If you are using zip version:
1) Go to your root folder (wherever you put NiceHash files)
2) Run "CreateLogReport.exe"
3) Send me generated (tmp._archive_logs.zip) zip file

Also you can tell me which GPUs you have in system

**Comment by saroja9117** [comment]
Hi..

Pf the log report..

**Comment by luc1an24** [comment]
Hi @saroja9117 
You don't have supported devices in your rig as stated in the warning.
These are requirements:
For CPU mining a modern CPU with SSE2 support
For AMD mining any AMD GPU with OpenCL support
For NVIDIA mining any NVIDIA GPU with Compute capability (SM) 3.0 or newer

Since we can't detect any of supported devices NHM won't let you through.
If you have any questions, feel free to ask!
Have a nice day!

**Comment by saroja9117** [comment]
Thanks for ur reply..

Can u plz let me know what are the hardware & software requirements for
starting a Mining rig plant at home...
From where can i get that resources from India..

Thanks

**Comment by luc1an24** [comment]
These are requirements:
For CPU mining a modern CPU with SSE2 support
For AMD mining any AMD GPU with OpenCL support
For NVIDIA mining any NVIDIA GPU with Compute capability (SM) 3.0 or newer

For any other questions, feel free to ask.

**Comment by taxi258** [comment]
can you please tell me is it possible to mining with gpu ati mobility radeon hd 2600 xt

**Comment by uzair820** [comment]
no supported devices problem
