### ISSUE TITLE
NHM 1.9.2.22 wont automine unless reapply settings is done.

### ISSUE THREAD

**Issue by Dolyfin** [nicehash/NiceHashMiner#2134]
Using NHM Legacy automine setting. With it set to input Timeout it will not autostart mining at idle unless I click setting, then either close settings or click save and close. Same issue with Session Lock.

**Comment by luc1an24** [comment]
Hi @Dolyfin 
NHM Legacy is no longer supported. Therefore I suggest you to use our latest [miner](https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.4.2) .
This is working in the latest release.
Have a nice day.

Closing issue, not related to NHM.
