### ISSUE TITLE
3.0.4.3 unable to install pheonix

### ISSUE THREAD

**Issue by backwerd** [nicehash/NiceHashMiner#2139]
autoupdate killed the pheonix plugin

and when i try to install it

i get notificaton it wasnt installed

followed the documentation on how to fix missing miners 

doesnt work

**Comment by backwerd** [comment]
![image](https://user-images.githubusercontent.com/69851367/90512014-3e5a7d00-e112-11ea-96e6-1f94056a9b74.png)

**Comment by luc1an24** [comment]
Hi @backwerd 
This seems like Anti-Virus program issue.
Did you create exception? Also try to disable AV for the time of downloading (then you can enable it again).
Please inform me about findings

**Comment by PetrNovotnyGS** [comment]
The same, disabled Windows Defender, plugin downloads but will not install Phoenix or Claymore.

**Comment by backwerd** [comment]
plugin is there i can see it

and i have no av to exclude

**Comment by backwerd** [comment]
same issue with claymore

**Comment by Grrizz** [comment]
Same issue here...

**Comment by backwerd** [comment]
also daggerhashimoto for srbminer and TeamRedMiner is no longer an option

**Comment by backwerd** [comment]
![image](https://user-images.githubusercontent.com/69851367/90521582-8e8c0c00-e11f-11ea-817d-0b74b4e8a386.png)

**Comment by Guche132** [comment]
same here as well.

**Comment by backwerd** [comment]
missing for NBMiner as well

![image](https://user-images.githubusercontent.com/69851367/90522090-27bb2280-e120-11ea-8a9c-d201a63dd0a6.png)

**Comment by Grrizz** [comment]
I've rolled back to the last version (and disabled auto-updating), works fine and also doesn't have the new memory limit on daggerhashimoto (I think that may be at least one of the issues people are seeing).

Release notes: Set minimum GPU memory for KAWPOW to 4GB and DAGGERHASHIMOTO to 5GB

**Comment by PetrNovotnyGS** [comment]
Also rolled back to 3.0.4.2 and works fine.

**Comment by backwerd** [comment]
i rolled back as well to 3.0.4.2 and pheonix 11.2

**Comment by backwerd** [comment]
i was able to update pheonix to 11.4 from with 3.0.4.2

**Comment by luc1an24** [comment]
Oh you have 4gb GPUs.
Right, with the new release we disabled 4GB gpus on DaggerHashimoto because of stability.

Closing the issue.

**Comment by backwerd** [comment]
I dont have any stability issues with Phoenix guess ill stick with 3.0.4.2

**Comment by luc1an24** [comment]
Hi @backwerd 
There is still a way to miner Phoenix on newest versions.
Please check the following post: https://www.nicehash.com/blog/post/how-to-remove-vram-limit-in-nicehash-miner
I hope this will help you running latest versions and still mining dagger.
Have a nice day!
