### ISSUE TITLE
Nicehash just closes, what could it be ? 

### ISSUE THREAD

**Issue by rpglord** [nicehash/NiceHashMiner#214]
Lately I have experiencing problem of nicehash just closing randomly. I would leave it mining overnight for example and when I wake up, program is not running any more. There is no any kind of error or anything.
Most importan thing is that graphics drivers DO NOT crash. I know this because everytime graphic driver crash, it will reset the gpu / memory clocks. This does not happen, everything remains the same, which means drivers don't crash. Nicehash just disappears like I wasn't even left it running !
I tried reverting any oc on the card, didn't help. Tried only leaving one algorithm disabling all others ( I left daggersia ) didn't help. Tried running just daggerhashimoto didnt help.

I really need help here, don't know whats going on ? Does this mean my card has gone bad and I need to RMA it ? Its strange because when that happens, either drivers will crash, or windows, which is not happening here.

I have 1060 gtx 3gb windows 10 pro autoupdates are turned on. 8gb ddr3, i2500 cpu

**Comment by rpglord** [comment]
Forgot to mention that I tried witcher 3 for few hours to see if something is up with my card, and had no issues or problems whatsoever.
Also this is not the case of my pc restarting without me realizing it, I left other programs open and they were there, just not nicehash.
This is what windows logs say : 
"The program nicehashminerlegacy.exe version 1.8.1.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel."
Could it be that this is some rare nicehash bug or something ? Thats why I wrote it here, it just seem strange to be hardware related, but anything is possible I guess

**Comment by jimmyhackers** [comment]
other than that making sure autoupdates isnt restarting your computer which you said isnt the case (but it was for me in windwos 7).

i would suggest checking your firewall settings incase its blocking a program.
or maybe you have "hibernate" enabled so after a while your hdd shuts down and you stop mining.

**Comment by rpglord** [comment]
No unfortunately its not that according to windows logs, nicehash stops responding and is then closed...

**Comment by DillonN** [comment]
Hello @rpglord, please post your `logs\log.txt` file after this happens to help track down what is happening before NHML closes

**Comment by rpglord** [comment]
I will as soon as it crashes again, thanks for the help !

**Comment by rpglord** [comment]
Ok here is the log file, it doesn't seem to be anything out or ordinary in there. Is there some kind of debug mode or something I need to turn on ? 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1249713/log.txt)

**Comment by rpglord** [comment]
Just wanted to add that in last few days I have done some extensive testing on my gpu, gaming, benching, stability tests, you named it, this run for hours every day and overnight, and I can say confidently there is nothing wrong with my card.

So this does seem to be some kind of bug with nicehash, quite rare it seems since nobody else is complaining ?

**Comment by DillonN** [comment]
@rpglord it doesn't look like anything is going wrong from the logs, it does look like it is maybe crashing in the middle of profit calculations. I can look closely at this since I am going to be working on that area soon anyway

When this does happen, is the miner window still open for you?

**Comment by rpglord** [comment]
Hello,no miner window is not open because I have it hidden always, it can't be something related to that can it ? Also I minimize nicehash gui window, and when I tried to restore it, it just dissapears. I could run it with mining window open if that is relevant ? 
Also I tried nicehash beta last few days, didn't have any problems, so this does again point out to some bug with legacy, if my hardware was faulty it would crash in nicehash beta too, right ?

**Comment by DillonN** [comment]
If you could try with leaving the windows open that would help, at least to track down whether it's related or how exactly it is crashing

**Comment by rpglord** [comment]
Ok sure thing I will leave miner window open and will report what happens :)

**Comment by rpglord** [comment]
It seems to be the drivers, we always miss the most obvious :)
It seems there is some incompability between nvidia drivers 382 and nhml, I upgraded to latest 385 and it's been 5 days now no single crash.
I will still keep an eye out on this, but it seems drivers solved the problem

**Comment by KOSSTA** [comment]
Здравствуйте при запуске NHML.1.8.0.2  через несколько секунд синий экран и перезагрузка компа

**Comment by Nox55** [comment]
@DillonN I am also having this issue. Mining windows DO stay open. It seems the mining is still taking place because my balance continues to accumulate normally. I just did a clean install of windows 10 on a new Nvme SSD and fresh installs of everything obviously and it's still happening.
