### ISSUE TITLE
NiceHash GPU1# Error Status and not working + Error during benchmark

### ISSUE THREAD

**Issue by hiro1o1** [nicehash/NiceHashMiner#2140]
![image](https://user-images.githubusercontent.com/69919090/90672157-85ae4e00-e277-11ea-802f-97463c6d95e6.png)

**Comment by hiro1o1** [comment]
Gpu not been used

**Comment by luc1an24** [comment]
Hi @hiro1o1 
Thank you for reaching out.
It seems like no supported plugins are installed for your GPU card.
Also you are using laptop which is really not ideal for mining and therefore we don't support it.
If you have any questions, feel free to ask.
Have a nice day!

**Comment by hiro1o1** [comment]
Okay thanks

**Comment by luc1an24** [comment]
Closing issue
