### ISSUE TITLE
NiceHash GPU1# Error Status and not working + Error during benchmark

### ISSUE THREAD

**Issue by vignakke** [nicehash/NiceHashMiner#2141]
nicehash version: 3.0.4.3
windows 10
gpu: ASUS GeForce RTX 2080 TI (11gb)
![image](https://user-images.githubusercontent.com/69920044/90676626-9b624a00-e25c-11ea-97c5-00049ee04a7c.png)
i tried downgrading the version but it still doesn't work,
however it worked correctly before the update

(I tried to install several drivers)

**Comment by vignakke** [comment]
**I add that of course everything worked fine before this damn update**

**Comment by luc1an24** [comment]
Hi @vignakke 
Thank you for reaching out.
This looks like a) AV issue b) driver issue
Please check if you did some driver update or windows update lately.
If this is not the case this is probably AV issue

**Comment by vignakke** [comment]
> Hi @vignakke
> Thank you for reaching out.
> This looks like a) AV issue b) driver issue
> Please check if you did some driver update or windows update lately.
> If this is not the case this is probably AV issue
hi,
my antivirus is off and i alredy checked my driver

**Comment by luc1an24** [comment]
Then please create a log report and forward it to our support team or me .
We will look into the issue.

**Comment by vignakke** [comment]
> Then please create a log report and forward it to our support team or me .
> We will look into the issue.

done, 
[tmp._archive_logs.zip](https://github.com/nicehash/NiceHashMiner/files/5103044/tmp._archive_logs.zip)

**Comment by vignakke** [comment]
and when I run a miner (without going through nicehash) it gives me a different user of my mining address
I feel like it's mining for someone else.
![image](https://user-images.githubusercontent.com/69920044/90771873-322e1580-e2f4-11ea-8758-08917af6dbcb.png)

**Comment by luc1an24** [comment]
Hi @vignakke 
1) Information retrieved from logs doesn't say much why benchmarks failed, but looking at the screenshot there could be possibility that your firewall is blocking any communication with miner api -> we are retrieving benchmark data from miner api.
So there are 2 options:
a) Find out if/why is firewall blocking miners -> allow miner communication on first time prompt
b) Manually benchmark all algorithms (start miner and write speeds to the configs inside benchmark section) 

2) To start mining directly with miner you have to define BTC address (with program arguments) on launching the miner.

**Comment by vignakke** [comment]
> Hi @vignakke
> 
> 1. Information retrieved from logs doesn't say much why benchmarks failed, but looking at the screenshot there could be possibility that your firewall is blocking any communication with miner api -> we are retrieving benchmark data from miner api.
>    So there are 2 options:
>    a) Find out if/why is firewall blocking miners -> allow miner communication on first time prompt
>    b) Manually benchmark all algorithms (start miner and write speeds to the configs inside benchmark section)
> 2. To start mining directly with miner you have to define BTC address (with program arguments) on launching the miner.

I don't understand, my firewall is disabled 
I will try one last time if it does not work I will give up, thank you for your help

**Comment by tobias54654ewr** [comment]
das liegt an dem Letzten Update keine ahnung ob die da was auf die karte flashen  könnte ich mir aber vorstellen Nvidea ist raus
