### ISSUE TITLE
the file was blocked from downloading

### ISSUE THREAD

**Issue by junyiwang810** [nicehash/NiceHashMiner#2146]
nhm_windows_3.0.4.3.exe was blocked because it could harm you device

**Comment by be4ndr** [comment]
I have the same.
Google Chrome blocked and Norton Antivirus messaged that it not recommends to keep this file.

**Comment by luc1an24** [comment]
hi
NiceHash Miner is usually flagged by AV (anti-virus) software. This is normal, as almost every mining software on the market is blacklisted by AV. Just make an exception in your AV software to enable the proper operation of NHM.
