### ISSUE TITLE
Problem connecting to daggerhashimoto pool with Phoenix Miner RX 5700 XT

### ISSUE THREAD

**Issue by signorinileandro** [nicehash/NiceHashMiner#2149]
Hello, I'm having this problem ONLY with Phoenix miner, I'm being able to mine kawpow and others. Already tried a lot of things, disabling totally Windows Defender, disabling Firewall, reinstalling NH Miner, reinstalling Phoenix Miner even installing old AMD drivers and nothing worked.
Here I leave the logs:

2020.09.01:23:49:54.033: main Phoenix Miner 5.1c Windows/msvc - Release build
2020.09.01:23:49:54.033: main Cmd line: -pool ssl://eu1.ethermine.org:5555 -pool2 ssl://us1.ethermine.org:5555 -wal 0x008c26f3a2Ca8bdC11e5891e0278c9436B6F5d1E.Rig001 
2020.09.01:23:49:54.033: main No CUDA driver found
2020.09.01:23:49:54.565: main OpenCL driver version: 20.4.1-2
2020.09.01:23:49:54.570: main Available GPUs for mining:
2020.09.01:23:49:54.570: main GPU1: AMD Radeon RX 5700 XT (pcie 10), OpenCL 2.0, 8 GB VRAM, 40 CUs
2020.09.01:23:49:54.571: main ADL library initialized
2020.09.01:23:49:55.091: main Eth: the pool list contains 2 pools (2 from command-line)
2020.09.01:23:49:55.091: main Eth: primary pool: ssl://eu1.ethermine.org:5555
2020.09.01:23:49:55.091: main Starting GPU mining
2020.09.01:23:49:55.091: main Matched GPU1 to ADL adapter index 0 (method 1)
2020.09.01:23:49:55.097: main GPU1: AMD driver 20.4.2
2020.09.01:23:49:55.097: main GPU1: Created ADL monitor for adapter 0; overdrive version: 8 (8)
2020.09.01:23:49:55.097: main GPU1: using AMD driver ver 20.4.2
2020.09.01:23:49:55.227: wdog Starting watchdog thread
2020.09.01:23:49:55.589: main Eth: Connecting to ethash pool ssl://eu1.ethermine.org:5555 (proto: EthProxy)
2020.09.01:23:49:55.590: main GPU1: 34C 21% 12W
GPUs power: 12.0 W
2020.09.01:23:49:55.611: eths Eth: Connected to SSL ethash pool eu1.ethermine.org:5555 (172.65.207.106)
2020.09.01:23:49:55.630: eths Eth: Send: {"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x008c26f3a2Ca8bdC11e5891e0278c9436B6F5d1E.Rig001"]}

2020.09.01:23:49:55.780: eths Eth: Received: {"id":1,"jsonrpc":"2.0","result":true}
2020.09.01:23:49:55.780: eths Eth: Send: {"id":5,"jsonrpc":"2.0","method":"eth_getWork","params":[]}

2020.09.01:23:49:55.795: main Listening for CDM remote manager at port 3333 in read-only mode
2020.09.01:23:49:55.931: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x485263b4233e4bef79aaa2c4c09ed446495619513b15bcb4e05e035a49d2883b","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a59"]}
2020.09.01:23:49:55.931: eths Eth: New job #485263b4 from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:49:55.932: GPU1 GPU1: Starting up... (0)
2020.09.01:23:49:55.932: GPU1 GPU1: Generating ethash light cache for epoch #359
2020.09.01:23:49:57.065: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x6bdb142219b8ee672cf1e2f9caa926c23f326a7eae454c788c98d7f88b394217","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5a"]}
2020.09.01:23:49:57.065: eths Eth: New job #6bdb1422 from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:49:58.008: GPU1 Light cache generated in 2.1 s (29.3 MB/s)
2020.09.01:23:49:58.645: GPU1 GPU1: Free VRAM: 7.922 GB; used: 0.063 GB
2020.09.01:23:49:58.645: GPU1 GPU1: Allocating DAG (3.82) GB; good for epoch up to #361
2020.09.01:23:49:58.654: GPU1 GPU1: Generating DAG for epoch #359
2020.09.01:23:49:58.676: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x33912304d3b0a83a7f9f6a204ba7f05a9da178c9763d2a5ec3969561daae43bc","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5a"]}
2020.09.01:23:49:58.676: eths Eth: New job #33912304 from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:50:00.660: GPU1 GPU1: DAG  12%
2020.09.01:23:50:00.693: main Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
2020.09.01:23:50:02.185: GPU1 GPU1: DAG  24%
2020.09.01:23:50:03.705: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0xbfade2095911f6313530e9ef98aa4f99466d98a0e889356f2b2ffd01148a3c0b","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5a"]}
2020.09.01:23:50:03.705: eths Eth: New job #bfade209 from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:50:03.710: GPU1 GPU1: DAG  35%
2020.09.01:23:50:05.345: GPU1 GPU1: DAG  47%
2020.09.01:23:50:05.631: eths Eth: Send: {"id":5,"jsonrpc":"2.0","method":"eth_getWork","params":[]}

2020.09.01:23:50:05.770: main Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
2020.09.01:23:50:05.781: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0xbfade2095911f6313530e9ef98aa4f99466d98a0e889356f2b2ffd01148a3c0b","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5a"]}
2020.09.01:23:50:05.984: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0xd6768e9faebce70b7499eee0f701167c1a77b29da88433a9405fefce240a77a4","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5b"]}
2020.09.01:23:50:05.985: eths Eth: New job #d6768e9f from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:50:06.143: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0xd8a06cdf6ef44f578c6c5d3ad3a33780cc432def56aaad679efb42104f49c8b0","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5b"]}
2020.09.01:23:50:06.143: eths Eth: New job #d8a06cdf from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:50:06.854: GPU1 GPU1: DAG  59%
2020.09.01:23:50:07.083: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x1c552c93cb031c9abb8472431f9f543f005767dd091891344317a659dde0fd72","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5c"]}
2020.09.01:23:50:07.083: eths Eth: New job #1c552c93 from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:50:07.651: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0xe15c39cef0d9943fb9e5ae6e8b1b1befa3f366da85ffdb4d689420ce29d121ed","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5c"]}
2020.09.01:23:50:07.651: eths Eth: New job #e15c39ce from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:50:08.375: GPU1 GPU1: DAG  70%
2020.09.01:23:50:09.986: GPU1 GPU1: DAG  82%
2020.09.01:23:50:10.862: main Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
2020.09.01:23:50:11.344: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x1da673274509c1d0830114214c3d326badc572266a3790b72e6b84a6c215b68a","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5c"]}
2020.09.01:23:50:11.344: eths Eth: New job #1da67327 from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:50:11.516: GPU1 GPU1: DAG  93%
2020.09.01:23:50:12.501: GPU1 GPU1: DAG generated in 13.8 s (281.4 MB/s)
2020.09.01:23:50:12.503: GPU1 GPU1: Using Ethash OCL kernels (gfx1010; -clkernel 1)
2020.09.01:23:50:12.503: GPU1 GPU1: no -gt value specified, switching to auto-tune
2020.09.01:23:50:12.503: GPU1 GPU1: starting auto-tune process
2020.09.01:23:50:15.317: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x94a112550ee67f43a14d2ec00332437b6e231ebdeda8afa41224b7c9449db649","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5c"]}
2020.09.01:23:50:15.317: eths Eth: New job #94a11255 from ssl://eu1.ethermine.org:5555; diff: 4000MH
2020.09.01:23:50:15.636: eths Eth: Send: {"id":5,"jsonrpc":"2.0","method":"eth_getWork","params":[]}

2020.09.01:23:50:15.636: eths Eth: Send: {"id":6,"jsonrpc":"2.0","method":"eth_submitHashrate","params":["0x2fc6880","0x6d63bc76c9a63b08fcac8faea7a3de662ae7c2c6a53b3d567efdcd5c40a0630d"]}

2020.09.01:23:50:15.787: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x94a112550ee67f43a14d2ec00332437b6e231ebdeda8afa41224b7c9449db649","0xc1dbf14bc84f90759c7c94280874014180ae6af9d9768eda2fc1b7c2725c85f4","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xa47a5c"]}
2020.09.01:23:50:15.963: main Eth speed: 50.096 MH/s, shares: 0/0/0, time: 0:00
2020.09.01:23:50:15.968: unkn Quitting...
2020.09.01:23:50:15.968: unkn GPU1 auto-tune process aborted
2020.09.01:23:50:16.852: wdog Stopping watchdog thread
2020.09.01:23:50:16.852: main Exit code: 0

Anybody else has such issues?
Is there any fix?

**Comment by luc1an24** [comment]
Hi @signorinileandro 
According to Phoenix logs your are not using NHM to mine.
Please use NHM for mining.
Have a nice day.
