### ISSUE TITLE
Check my stats online

### ISSUE THREAD

**Issue by puipui91** [nicehash/NiceHashMiner#215]
I would like to ask when i click on check my stats online using nicehash miner legacy i will open the internet explorer and everything seems alright but I am unable to view next payout date. 

I have tried using internet explorer, chrome and firefox and its still the same. Any solution please

**Comment by luongk** [comment]
You need to mine for a longer period.  Projected payout is worked out on your mining over a period of time, if you have only commenced mining it won't have any data to work from.

**Comment by puipui91** [comment]
i mine for about  a week already still nothing

**Comment by luongk** [comment]
That seems unusual.  Can you take a screenshot or link to your miner URL?

**Comment by puipui91** [comment]
some said i need to wait till next month

**Comment by DillonN** [comment]
If you have had profit for the last hour it should show projected payout. If you could post a screenshot or URL like @luongk suggested I could help more

**Comment by puipui91** [comment]
![untitled](https://user-images.githubusercontent.com/31278366/29659228-21418e0c-88f0-11e7-9c51-27c2fee5d868.png)
this is what is show only (unknown)

**Comment by nicehashdev** [comment]
@puipui91 can you let us know your OS and browser that you use (+version)?

If you know how to use debugging tools of your browser, could you check out if you get script crash? Thanks.

**Comment by puipui91** [comment]
how?

**Comment by nicehashdev** [comment]
Depends on browser. Usually browsers have this functionality on right click anywhere on page. Then select something like "Inspector". Then press F5 to reload page and see if there are any errors printed out.

**Comment by puipui91** [comment]
no error i think

**Comment by puipui91** [comment]
windows 10 and google chrome?

**Comment by luongk** [comment]
It's not a browser issue, the issue is his hashrate is too low for nicehash to predict his next payment.

**Comment by puipui91** [comment]
gtx 1070 card also too low?

**Comment by VanceAnce** [comment]
have the some problem after the nhm v2 update 
have about 6 workers and enough hash rate to be shown ... 

question is - how useful is nhml anymore ?

meaning is to mine with lower equipment - but if equipment isnt recognized anymore .....

is an i3 or rx550 card enough or better swap to other iners than nhm and nhml ?
