### ISSUE TITLE
DaggerHashimoto (Phoenix) is not supported for NVIDIA GTX 1050Ti, When i install Phoenix from plugins, i got error notification New version of Phoenix was not installed, please fix my problem, Thank you

### ISSUE THREAD

**Issue by johnmary82** [nicehash/NiceHashMiner#2152]
![Phonix error](https://user-images.githubusercontent.com/70707343/92126098-638f0100-ee1d-11ea-8d89-d41519d1f8dd.jpg)
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by luc1an24** [comment]
Hi @johnmary82 
Thank you for reaching out.
This looks like AV issue. This is normal, as almost every mining software on the market is blacklisted by AV.
If you disable your AV while downloading the wanted plugin it should work as expected.
Have a nice day!

**Comment by peteperil** [comment]
I also get this error message "New version of phoenix is not installed".

I have complete removed and reinstalled NiceHash Miner v3.0.4.3.

I have tried reinstalling the phoenix miner plugin several times.
The last time I had my antivirus disabled, just to be sure.

I have documented the process and attached files with this post.
![NHM_01_PluginsFolder_Phoenix_Uninstalled](https://user-images.githubusercontent.com/38616059/92471491-4faa1d00-f1d8-11ea-84ed-cba4ffbccf93.png)
![NHM_02_PluginsMenu_Phoenix_Uninstalled](https://user-images.githubusercontent.com/38616059/92471494-4faa1d00-f1d8-11ea-9fac-aeeb16b33194.png)
![NHM_03_PluginsMenu_Phoenix_Installing](https://user-images.githubusercontent.com/38616059/92471495-5042b380-f1d8-11ea-9989-a04d639355eb.png)
![NHM_04_PluginsMenu_Phoenix_Installed](https://user-images.githubusercontent.com/38616059/92471496-5042b380-f1d8-11ea-880b-88d3c411bde9.png)
![NHM_05_PluginsFolder_Phoenix_Installed](https://user-images.githubusercontent.com/38616059/92471497-50db4a00-f1d8-11ea-83b8-0586bbd2c88d.png)
![NHM_06_BenchmarksMenu_Phoenix_Installed](https://user-images.githubusercontent.com/38616059/92471498-50db4a00-f1d8-11ea-8c2f-ffd299d111c1.png)
![NHM_06_NotificationsMenu_Phoenix_Installed](https://user-images.githubusercontent.com/38616059/92471500-50db4a00-f1d8-11ea-8adc-310c8184934e.png)
[log - copy-after-reinstall.txt](https://github.com/nicehash/NiceHashMiner/files/5188024/log.-.copy-after-reinstall.txt)
[log - copy-before-reinstall.txt](https://github.com/nicehash/NiceHashMiner/files/5188025/log.-.copy-before-reinstall.txt)

**Comment by peteperil** [comment]
You can see that after installing all the files appear where you would expect them. But the miner is not shown available in the benchmark folder. And under the notifications the message says "New version of phoenix is not installed". Even while under plugins the miner is listed as 'installed'.
Also, after closing NiceHash Miner and opening it again, under plugins the phoenix miner is no longer listed as installed. The files are still there, but it's not 'installed' any more.

**Comment by NaNonnI** [comment]
Same!
