### ISSUE TITLE
NiceHash OS the fan speed does not correspond

### ISSUE THREAD

**Issue by ElWilly27** [nicehash/NiceHashMiner#2153]
Hello
I need help
I have 4 Radeon RX 580 boards on an Asusu B250 motherboard with NiceHash OS version: '1.2.0'
some boards take a lot of temperature, and the fan speed does not correspond to it. I guess the system confuses and crosses the fan settings
In the example below you can see that the PCI 0c00 board is reversing the fan setting with 0d00.

What can I do to correct this fault?

Thank you.

**Example and data:**
=====================================================================

NiceHash OS version:  '1.2.0'
Miner version:        '3.0.4.12'
Miner running:         YES

Rig id:               '0-Mb4u5xxxxxxxxxxxxxxxxxxeg'
Btc address:          '368223nMZCuEeGa4HCxxxxxxxxxxxxxxxxxxxxxm'
Worker name:          'RIG1_ASUSB250'
Group name:           ''

   DEVICE NAME:          DEVICE VENDOR:                BUS NUMBER:
0  Radeon RX 580 Series  Advanced Micro Devices, Inc.  9
1  Radeon RX 580 Series  Advanced Micro Devices, Inc.  12
2  Radeon RX 580 Series  Advanced Micro Devices, Inc.  13
3  Radeon RX 580 Series  Advanced Micro Devices, Inc.  11

Every 2.0s: sensors                             2020-09-04 22:46:22

amdgpu-pci-**0c00**
Adapter: PCI adapter
vddgfx:       +1.03 V  
fan1:         **845 RPM**  (min =    0 RPM, max = 3200 RPM)
edge:         **+73.0 C**  (crit = +94.0 C, hyst = -273.1 C)
power1:      123.13 W  (cap = 124.00 W)

amdgpu-pci-0900
Adapter: PCI adapter
vddgfx:       +1.06 V  
fan1:        2271 RPM  (min =    0 RPM, max = 3200 RPM)
edge:         +62.0 C  (crit = +94.0 C, hyst = -273.1 C)
power1:      123.10 W  (cap = 124.00 W)

amdgpu-pci-**0d00**
Adapter: PCI adapter
vddgfx:       +1.02 V  
fan1:        **2528 RPM**  (min =    0 RPM, max = 3200 RPM)
edge:         **+52.0 C**  (crit = +94.0 C, hyst = -273.1 C)
power1:      123.16 W  (cap = 124.00 W)

amdgpu-pci-0b00
Adapter: PCI adapter
vddgfx:       +1.03 V  
fan1:        1640 RPM  (min =    0 RPM, max = 3200 RPM)
edge:         +54.0 C  (crit = +94.0 C, hyst = -273.1 C)
power1:      123.09 W  (cap = 124.00 W)

asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM

**Comment by S74nk0** [comment]
@ElWilly27 for NiceHash OS please write to our support. This repository and issues should relate to NiceHash Miner only.
