### ISSUE TITLE
is it possible to add a feature that can send out email or push notification when the temprature of GPUs drop below some certain degree?

### ISSUE THREAD

**Issue by acewong7** [nicehash/NiceHashMiner#2154]
Hello, I've been using NICEHASH MINER for the past two years, due to some reasons(connection closes, no algorithm available etc.) the miner stays idle for a long time but there is no way to know untill I log back in. Becasue in such case, there is no notication or email from nicehash becasue it is not rig error, nor rig goes offline. 

The only way to fix this is to change server location or close nicehash miner and reopen it. But I never know when this case can happen so I have to keep checking my rigs status, like the load percentage or the GPU's temperature. 

It will be so nice to get a notification if the GPU's temperature drops below a certain degree say 70 Celsus (if the idle case I mentioned above happens, the miner rig's GPU temperature will be like 40 Celsus or lower), nicehash can send out an email or push notification on the APP (just like the "get notified when rigs go offline" way in the current system) to let me know something is wrong with the miner so I will be able to fix it ASAP.

**Comment by Dohtar1337** [comment]
Won't fix/include. This feature or bug might already be fixed or added. Or might not be included due to internal reasons.
