### ISSUE TITLE
download blocked by chrome

### ISSUE THREAD

**Issue by colinuch** [nicehash/NiceHashMiner#2155]
I tried to download it but google chrome blocked it because it was "dangerous"

**Comment by anazz20** [comment]
Welcome to the new Chrome. If anti-virus blocks it, usually chrome will also.
https://support.google.com/chrome/answer/99020?co=GENIE.Platform%3DDesktop&hl=en

**Comment by alejandrofm** [comment]
There is an advice in the documentation, you can
ignore and download, try another browser or add an exception to the AV
