### ISSUE TITLE
Mining windows steal focus

### ISSUE THREAD

**Issue by luongk** [nicehash/NiceHashMiner#216]
I appreciate there is an option for the mining windows to start minimised, but is it possible for them to be set to launch in a window (so I can see/monitor what is going on) but without stealing focus?

**Comment by Mystere** [comment]
Since these are standard console windows, it's probably not possible with a significant amount of work.. just a guess though

**Comment by grantemsley** [comment]
Should be pretty easy to do actually.

You can do it from the command line by running:

`start /min cmd.exe`

Replace cmd.exe with whatever miner you want to run.  It starts with the window minimized, and without stealing focus.

**Comment by Mystere** [comment]
@grantemsley  The author specifically said he didn't want them to start minimized.

**Comment by DillonN** [comment]
Yeah the only exposed options here are minimized or hidden - launching non-minimized and not stealing focus would be much more trouble
