### ISSUE TITLE
Rx 5700 xt problems i have 8x rx 5700xt 8gb all of them mins dager claymore for about 10min at 50mh each then the mining goes offline for no reason 

### ISSUE THREAD

**Issue by stephanwolmarans** [nicehash/NiceHashMiner#2160]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by S74nk0** [comment]
@stephanwolmarans please clarify what do you mean with 

> offline
?

Is the miner offline in the rig manager? Is it the Claymore miner process closed? Something else?
Please provide detailed/specific/precise information. Create a log report or write to our support channel.

**Comment by Maybemine** [comment]
I Have a 5700 XT GPU and an AMD 3900, and I cannot get Nicehash 30.4.4 (lastest) to run any benchmark at all. it attempts to run it, but all fail. any suggestions would be great
