### ISSUE TITLE
when benchmark ZHash algo with lolminer, the application miss --pers param pass to lolminer

### ISSUE THREAD

**Issue by oyjj614** [nicehash/NiceHashMiner#2163]
I has tested the lolminer v1.06, it end with promt me need --pers param. I pick the params from nicehashMiner like follow(the user info below is masked by me, don't care):
--algo EQUI144_5 --pool zhash.eu.nicehash.com:3369 --user **********--tls 0 --apiport 4000 --disablewatchdog 1 --devices 0

**Comment by luc1an24** [comment]
Hi @oyjj614 
Thank you for reaching out.
This is fixed with the new plugin update.
Head to plugins section, update lolMiner and it should work
Have a nice day!
