### ISSUE TITLE
Nicehash uses the CPU at idle

### ISSUE THREAD

**Issue by chara1ampos** [nicehash/NiceHashMiner#2164]
When I launch Nicehash 3.0.4.3, it uses 14% of my 28 core/56 thread CPU (around 10 threads) at idle, and turbo boosts my CPU, even when I am not mining at all. It appears that Nicehash is secretly using my CPU for mining to someone else's wallet. This is very sketchy. **Please address immediately**.

**Comment by S74nk0** [comment]
@chara1ampos we have reduced CPU/GPU rendering with https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.4.4 release. Please report back if this version still has high CPU usage.
