### ISSUE TITLE
1070 gtx doesn't detect monitor, no image

### ISSUE THREAD

**Issue by alejandrofm** [nicehash/NiceHashMiner#2170]
Have 2 ZOTAK 1070 GTX (AMP and Extreme)
This is the detection log:
`{"CudaDevices":[{"DeviceGlobalMemory":8511881216,"DeviceID":0,"DeviceName":"GeForce GTX 1070","HasMonitorConnected":0,"SMX":15,"SM_major":6,"SM_minor":1,"UUID":"GPU-8411b8d3-5eb0-2f82-39e7-b6b91b828e4a","VendorID":4318,"VendorName":"NVIDIA","pciBusID":1,"pciDeviceId":461443294,"pciSubSystemId":0},{"DeviceGlobalMemory":8513978368,"DeviceID":1,"DeviceName":"GeForce GTX 1070","HasMonitorConnected":0,"SMX":15,"SM_major":6,"SM_minor":1,"UUID":"GPU-34a7c32d-108e-0376-884d-3ac4fdd23792","VendorID":6618,"VendorName":"Zotac","pciBusID":6,"pciDeviceId":461443294,"pciSubSystemId":339024346}],"DriverVersion":"450.57","ErrorString":""}`
The screen just go blank, Linux, booting via NHOS but this log is after the boot process and belongs to NHS.
Thanks!

**Comment by S74nk0** [comment]
@alejandrofm for NHOS please open issues https://github.com/nicehash/NHOS/issues. 

Closing issue not related NiceHash Miner
