### ISSUE TITLE
decice_detection.exe system error

### ISSUE THREAD

**Issue by ItsYaBoyBanana** [nicehash/NiceHashMiner#2184]
The program can't start because OpenCL.dll is missing.
This happened after installing NHM 3.0.5.1
The past versions worked fine, how do I fix it?

**Comment by S74nk0** [comment]
@ItsYaBoyBanana download the package https://github.com/nicehash/DeviceDetection/releases/tag/v2.1 extract and run `device_detection.bat` it will produce `device_detection.txt` file upload the file or its contents here. 

You can try copying OpenCL.dll inside the `app_x.y.z.r` folder. It is inside OpenCL this might work for you
