### ISSUE TITLE
NiceHash not starting on boot

### ISSUE THREAD

**Issue by itekreps** [nicehash/NiceHashMiner#2187]
Can not get nicehash to load on startup for some reason. Checked on settings. Didn't work. Tried task scheduler and it works when you run to test but not on boot. Tried adding to startup (shell:startup) didn't work. Changed settings to run program as administrator. 
Msi afterburner loads fine on boot.

**Comment by Stas-Buzunko** [comment]
the same here. have 8 pc and none of them have nicehash starting on boot

**Comment by war3zlod3r** [comment]
I still have this issue with the latest build only 1/9 machines actually runs it on boot
