### ISSUE TITLE
NHML 1.8.1.0 Graphics cards not detected

### ISSUE THREAD

**Issue by thebritishtwit** [nicehash/NiceHashMiner#219]
Hi 

Sorry if this has previously been reported.

I have been using NHML 1.8.1.0 for about a week without issues, has been extremely stable. I upgraded to the crypto drivers AMD drivers for my 5 AMD cards (2 x 480 and 3 x 580). After successful install I ran NHML and got the error message that no cards were detected (including my 1070) however if i run an older version of NHML (1.7.5.13) the system pick up the cards without issues and mines as per normal.

All cards are available in Dev manager.

Please confirm if you require any more information. Logs attached.

[Nicehash logs.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1246976/Nicehash.logs.txt)

**Comment by ilkanaydin** [comment]
Hello there,

I had the same problem. I downloaded and installed version 8.1 of windows from Microsoft. I downloaded and installed the latest version of my drivers and improved it. We recommend that you try it.

**Comment by Olegik-ah** [comment]
Hello! It's your mistake in HHML settings.
UNcheck in settings
"Disable detection of NVIDIA"
and
"Disable detection of AMD"
![2017-08-24_01-18-24](https://user-images.githubusercontent.com/31293967/29641140-cc2d8ac2-886a-11e7-96e5-532e537ad7d4.png)

**Comment by DillonN** [comment]
As @Olegik-ah said it looks like you have detection disabled in the settings, from the logs

**Comment by thebritishtwit** [comment]
Hi 

Apologies for being stupid.

Who knew enabling that option would allow the cards to be detected.

Thanks
