### ISSUE TITLE
NiceHash security, virus, false positive?

### ISSUE THREAD

**Issue by Zakiyo1** [nicehash/NiceHashMiner#2194]
Usually the chrome dowload would get blocked at first and you would have to confirm it but now it also blocks it even after I  authorized it and it says virus detected. On the windows side it would usually be reported as a potentially undesirable software and now it is reported as a trojan. Has the download been infected ?

**Comment by BeepBoopSpace** [comment]
Having the same issue - did you follow through anyways?

**Comment by Zakiyo1** [comment]
> Having the same issue - did you follow through anyways?

No I switched to NiceHash OS
