### ISSUE TITLE
nicehash 3.0.5.1 only detecting 1 CPU. AMD 1950X

### ISSUE THREAD

**Issue by gysnst2** [nicehash/NiceHashMiner#2195]
im not sure if this is a bug or i am missing something.. 
I had stopped using nicehash along time ago. yesterday i had time to get the miner back up and running.  I remember in the past seeing much higher cpu mining hash rates.  that when it had dawned on my the current version of nicehash 3.0.5.1 is only reporting 1 cpu 16 cores. and machine  is running at 50%.  is their a setting i cannot find to enable more then one CPU.  I know in the older versions I had the option for 2 CPU's 

AMD Ryzen Threadripper 1950X 16-Core Processor
RandomXmonero: 4.32725048 kH/s
Status
Mining
Load
53%
RPM
--

**Comment by Dohtar1337** [comment]
Won't fix/include. This feature or bug might already be fixed or added. Or might not be included due to internal reasons.
