### ISSUE TITLE
NHM_windows_3.0.5.1.exe won't run.

### ISSUE THREAD

**Issue by nathanshunk** [nicehash/NiceHashMiner#2198]
I recently tried to install NHM using the EXE installer file, and Windows says the file cannot run. no other information is given to the situation. 

NHM has previously worked on my machine. 
I am on Windows OS Build: 18363.1198

**Comment by danstiner** [comment]
I got it to work by opening the "virus & threat protection" panel, expanding App:NiceHashMiner, clicking see details to verify the detection was for "potentially unwanted behavior" and not something more sinister, then changing the action to "allow on this device". Then I tried the exe installer again and it worked.

This is mentioned on the site: https://www.nicehash.com/support/mining-help/nicehash-miner/my-broswer-antivirus-software-reports-nhm-as-a-virus

Bypassing virus protection is of course a "do so at your own risk" situation, good luck.

![image](https://user-images.githubusercontent.com/52513/100129713-be416300-2e36-11eb-9f0e-0725459978bf.png)
