### ISSUE TITLE
not priority Feature Request : benchmarking all (checked) cards at same time

### ISSUE THREAD

**Issue by toonsmil** [nicehash/NiceHashMiner#22]
because with a lot of algo 👍 that take a long time for one card (multiplied by xx cards = a very long time)
and when we mine , we use all cards at same time

but maybe is not possible because it must launch xx benchmarks sessions (??) at same time for xx cards to have a result for each card ?

**Comment by billmcilhargey** [comment]
whoops looks like this can be merged https://github.com/nicehash/NiceHashMinerLegacy/issues/19

**Comment by toonsmil** [comment]
sorry , maybe my english is too bad , i want say :
now when benchmarking start :
time 0 : GPU0 => algo_0 
time 1 : GPU0 => algo_1
...
time (i don't know) : GPU1 => algo_0 (again algo_0 , like time 0)
time (i don't know + 1) : GPU1 => algo_1 (like time 1)
...
time ww : GPUxx => algo_yy

total time = xx X yy
--------------------------------------------------------------------------------------------
my request :
time 0 : algo_0 => GPU0 and GPU1 and GPUxx (all GPU at same time , but a result for each GPU)
time 1 : algo_1 => GPU0 and GPU1 and GPUxx (all GPU at same time , but a result for each GPU)
...
time ww : algo_yy => GPU0 and GPU1 and GPU xx (all GPU at same time , but a result for each GPU)

total time = only yy (because all GPU at same time)

**Comment by DillonN** [comment]
I believe what you're saying is to have the benchmarks for different GPUs run in parallel with each other? This is something I will look in to, thanks.

**Comment by francescocmazza** [comment]
Thank you toonsmill, always wanted to ask it too :) +1 :)

**Comment by adrivansoft** [comment]
I have a couple of rx 4xx and 5xx on one rig but I only benchmark 1 GPU then copy the settings of gpu#1 towards the other GPUs by right clicking on the cards in benchmark.

Then again your suggestion is best when you have different combinations of gpu brands and models in one rig.

**Comment by fefsf** [comment]
Benchmaking all 6 of my GPUs at once will be frickin sweet

**Comment by ChriscomIT** [comment]
But that's some frickin hell lot of work too. Nevertheless +1

**Comment by MonaxDK** [comment]
I do the benchmark manually, launching the algorithm on all the same cards, then divide the result by the number of cards and enter the average value for each card. In this way, I get more accurate card performance values. I have different frequencies on different cards, but they all work together on the same algorithm, so it does not matter that one is a little faster and the other slower, the overall speed is important. It would be nice to add a function to make it automatic.

**Comment by DillonN** [comment]
This was implemented in 1.8.2.0-pre2
