### ISSUE TITLE
V1.8.1.1 Profitability not matching with NiceHash Profitability   

### ISSUE THREAD

**Issue by swapongn** [nicehash/NiceHashMiner#220]
Suppose I have 5 Rigs. As per V1.8.1.1 Profitability of these suppose .00150000+.00120000+.0099000+.00086000+.00045000=.00500000BTC/day But finally got .00390000 BTC/day from from new.nicehash.com without any issue ( the amount I shown, just an example).
Is it problem new nicehash new website setup or the Profitability in Legacy 1.8.1.1 not correct? 
Please check this issue and let us know actually where is the problem and how to fix it?

**Comment by Mystere** [comment]
Your comment makes very little sense to me. 

Profitability on the NH website is based on PAST data, and does not predict FUTURE results.

**Comment by maxgamurar** [comment]
I think user it talking about profitabilty from nhlm and what he sees when checking it using Check profits from that app which leads to NH website

**Comment by swapongn** [comment]
@maxgamurar, Think, you are on right way to understand my question.

**Comment by ChriscomIT** [comment]
Profitability in the application is correct. The profitability changes the whole day. Sometimes a lot sometimes less. The value shown in the application is just the momentary value but it can go higher or lower in the timeframe of 24h. At the end of the day (after 24h), you see what you got awarded at all based on the respective pay rate for the shares you submitted and the given profitability at the time you submitted them.

**Comment by swapongn** [comment]
@ChriscomIT , Thank you for your comment. 
I know that the profitability in the app change many times in 24 hours and the daily paying amount is an average of all profitability of within 24 hours. But my concern that I checked few times in hole 24 hours but some time could not match between my "monitoring" amount and the actual payed amount. So, I am queries...

**Comment by DillonN** [comment]
There is a relevant area in the [wiki](https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Troubleshooting#profitdisc) to this
