### ISSUE TITLE
 nhmws. please check your internet connection not connected v.3.0.5.1

### ISSUE THREAD

**Issue by medvedaction** [nicehash/NiceHashMiner#2203]
nhmws. please check your internet connection not connected

**Comment by anazz20** [comment]
NiceHash domain is currently unreachable due to a security breach on domain registrar GoDaddy! Do not open any links that might be suspicious! We are still investigating and will keep you informed!

**Comment by medvedaction** [comment]
and why does someone work and someone doesn't?
https://wampi.ru/image/R70U6Uy

**Comment by S74nk0** [comment]
@medvedaction we have just made a temporary release:

https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.5.2

This is a temporary release until we resolve our domains.

**Comment by S74nk0** [comment]
@medvedaction the temporary release is removed. We have resolved issues with domains

**Comment by medvedaction** [comment]
thank you, everything is fine!

**Comment by Kryp7o** [comment]
@S74nk0 hello. my nicehash.com website still doesn't load and my mining rigs are not mining. do i need to download again nicehash miner 3.0.5.1 zip file and do the whole setup again? please help

**Comment by shura133** [comment]
Привет, как устранить проблему с подключением к интернету? Пробывал разные варианты, но по прежнему не запускается майнинг.

**Comment by Kryp7o** [comment]
![Untitled](https://user-images.githubusercontent.com/74674829/99568984-c2a1f200-29d8-11eb-986d-443f01fa9c2f.png)

**Comment by Kryp7o** [comment]
this is what i get^ even after reinstalling the miner. help

**Comment by shura133** [comment]
> это то, что я получаю ^ даже после переустановки майнера. Помогите

точно такая же проблема , один в один

**Comment by Kryp7o** [comment]
someone help us solve this issue so we can mine again. i do have internet connection to my rigs, i checked and the internet is good 100% it opens webpages for example, but the miner does not mine. I am not a big tech person, so please find a solution for the masses, either an update to this miner or an updated download for example nicehash miner 3.0.5.x ... and let us know when it is ready for download. please and thank you.

**Comment by medvedaction** [comment]
https://wampi.ru/image/R7HceDJ  reinstalling a new version 3,0.5.3

**Comment by Elkoss** [comment]
Same problem here... This morning all worked fine and now nhmws can't connect. Check internet connection. Well, I have internet connection. Any solution available?

**Comment by Kryp7o** [comment]
![Untitled](https://user-images.githubusercontent.com/74674829/99584966-5a5e0b00-29ee-11eb-8413-6d476448cd04.png)
same issue even with the version 3.0.5.3

**Comment by medvedaction** [comment]
yes and all benchmark error

**Comment by rpm-github** [comment]
Since my DNS wasn't updated yet, I was able to resolve this issue by adding 2 lines to my hosts file. The first line was the pool from https://pastebin.com/BvC1AYx0
The second line was
104.17.254.46 nhmws.nicehash.com

**Comment by Kryp7o** [comment]
how does a DNS 'update' ? and where do i go to add these lines?
a question from a non-tech savy person
i use nicehash because it is easy and i don't need to know too much about computers...but now nicehash is getting too complicated.

**Comment by clarejor** [comment]
also having this issue with 3.0.5.3 and many benchmark errors from a 2070 super

**Comment by S74nk0** [comment]
GoDaddy hack 2020 related issue... now is resolved closing.

**Comment by sandisuhirman** [comment]
brother what is the solution of this problem. i've same problem nhmws not connected.

thanks

**Comment by symut** [comment]
yeah, i am waiting for the solution too

**Comment by gonzobrains** [comment]
> GoDaddy hack 2020 related issue... now is resolved closing.

What does this mean?

**Comment by gonzobrains** [comment]
I am getting this issue on one rig.  Everything else can connect on that machine (ping, web browser, etc.).  This is an intermittment issue, meaning it eventually connects but doesn't stay connected all day, even with firewall disabled.

**Comment by nikitaselang** [comment]
The same issue with some adjusments.
When I recieve "Not connected to NHWMS. Please check your internet connection" string in the main window of NiceHash Miner, the Excavator is still running and mining. At the same time, datchboard of nicehash.com displays the rig is offline (but accepted speed is not null and profitability is reasonable).

**Comment by trusteddev1409** [comment]
I have the same error.
I have clone the git repo and build it on my own. 

When I build and run it, I get the same error with the above one.
Can you tell me how to fix it?

**Comment by trusteddev1409** [comment]
I have the same error.
I have clone the git repo and build it on my own. 

When I build and run it, I get the same error with the above one.
Can you tell me how to fix it?

**Comment by symut** [comment]
> yeah, i am waiting for the solution too

I solve this problem with downgrade nhmws version
