### ISSUE TITLE
WanaCry Ransomware Virus Detected From Norton (Version 3.0.5.3)

### ISSUE THREAD

**Issue by IsaacLK** [nicehash/NiceHashMiner#2205]
Idk what just happened norton just started going off with trojans and wanacry can someone help.

**Comment by Zakiyo1** [comment]
I've had this problem too. I suggest you switch to NiceHash OS

**Comment by Dohtar1337** [comment]
Norton is known to interfere with NiceHash Miner. Make sure that you are downloading the NHM from the official source, then do this: 
https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-to-norton-antivirus-exclusion
