### ISSUE TITLE
Set mining times

### ISSUE THREAD

**Issue by tuppers360** [nicehash/NiceHashMiner#2206]
Is there a way of including the option to mine only during specific times?

Currently say if your electricity cost between 4pm and 7pm was 20 pence per kwh but outside of this it was 10 pence, is there a way to avoid the costly period without manually stopping and starting?

Thanks

**Comment by nathsmaR** [comment]
Ready

**Comment by Dohtar1337** [comment]
Won't fix/include. This feature or bug might already be fixed or added. Or might not be included due to internal reasons.
