### ISSUE TITLE
No Supported Devices | NHM 3.0.5.3 | RX 590

### ISSUE THREAD

**Issue by aemee** [nicehash/NiceHashMiner#2210]
Have the following outdated hardware:

```
- i7-3770
- RX 590
- NHM 3.0.5.3
- W10 Pro 1909
```

Fresh install to try it out, on first run, greeted with No Supported Devices.
Double checked specs and they should be good.
Updated gpu drivers just to be safe.
Still getting this error. Log attached.

Not sure if this is a user error or hardware incompatibility.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/5579801/log.txt)

**Comment by S74nk0** [comment]
@aemee it looks like the detector executable is missing:

`[2020-11-22 23:30:40] [ERROR] [DeviceDetectionPrinter] threw Exception: 'The system cannot find the file specified'. ReadData ''`

Did you install via the installer or zip archive or did you build the project yourself?

**Comment by aemee** [comment]
> 
> 
> @aemee it looks like the detector executable is missing:
> 
> `[2020-11-22 23:30:40] [ERROR] [DeviceDetectionPrinter] threw Exception: 'The system cannot find the file specified'. ReadData ''`
> 
> Did you install via the installer or zip archive or did you build the project yourself?

Installer. A/v was disabled and I still don't see any files flagged/deleted by a/v.
Will try redownloading the installer and zip and see how it goes.

**Comment by aemee** [comment]
A/V exclusions was set properly and nothing was being quarantined by it.
I just redownloaded the installer this morning and it seems to be working fine now.

I have no idea what was causing the problem or solved it but thank you for the help either way.
All that's left is to find a way to have NHM mine a specific algo and server.
