### ISSUE TITLE
NHM v3.0.5.3 keeps terminating without warning or error.

### ISSUE THREAD

**Issue by Devianthail** [nicehash/NiceHashMiner#2211]
Hello.

So, first off, I am new to the mining scene so that might be the issue off the bat.
I downloaded the latest version of NiceHash Miner, v3.0.5.3, and I am running:
-Windows 10 64x bit
-Intel Core i7-8700K @ 3.7GHz
-ASUS GeForce GTX 1080 Ti 11Gb
-Corsair Vengeance Pro 32 Gb (don't know if this is relevant)

Issue:
The application keeps terminating after about 10-15 min of use. I do not receive a warning or errors the next time it is started.
I have updated every driver I can think of and I have made allowances within my firewall settings.
I then tried to restore all default settings within the application to see if one of my settings was the cause, but no luck.
I could really use the help, as this is a activity I have been interested in for awhile now, and I dont want my first attempt to be a disaster.

Log files included
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/5581524/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/5581527/log.txt)

**Comment by S74nk0** [comment]
I am unable to see what could be the problem from the logs. Since this sounds like NiceHash Miner crashed if you can please provide Windows Event viewer information for NiceHash Miner.

**Comment by JohnTurkey** [comment]
YES! I am having the SAME exact Problem. I am running a godly setup for mining. 50 Bitcoin per hour! lol jk, but it's a good PC. But yes, Every time after I launch it, everything RANDOMLY crashes. EVERYTIME. I thought it was maybe my driver or something, but nope. everything is running smoothly. Please help fix this bug! I want to get back to mining!

**Comment by S74nk0** [comment]
@Devianthail, @JohnTurkey are you overclocking your GPUs?

**Comment by JohnTurkey** [comment]
Negative!

**Comment by Devianthail** [comment]
> I am unable to see what could be the problem from the logs. Since this sounds like NiceHash Miner crashed if you can please provide Windows Event viewer information for NiceHash Miner.

Sorry for the wait, I have the Event viewer files for when the application is started, but i did not see any files after the crash.

[Event viewer logs.zip](https://github.com/nicehash/NiceHashMiner/files/5598599/Event.viewer.logs.zip)

**Comment by NikolaKamchev** [comment]
Been having the same problems over the last few days after I updated to the latest version however it seems to happen when I leave my pc to run during the night as when I wake up, the program has been closed and my gpu isn't under any load. I think I'll have to go back to the legacy version for now :/

**Comment by greyphilosophy** [comment]
This sounds like the problem I've been having all day with Nicehash OS 1.2.7. My rig was running very consistent for months, but today it crashes after about 15 minutes, if it restarts at all. Now it's run for 18 minutes which is a bit of a record, but none of the GPUs are showing in the dashboard, just the hashrate. 
![image](https://user-images.githubusercontent.com/35280617/103853507-13da7380-5063-11eb-9a95-9f9e90eb6766.png)
