### ISSUE TITLE
Typo on wiki page - "pagafile"

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#222]
Page: https://github.com/nicehash/NiceHashMinerLegacy/wiki/Ethminer-Tips

Fourth item: "_you need to have enough RAM or virtual memory if you are running multicard setup; on 6 card setup virtual memory (pagafile) needs to be at least than 32 GB;_"

It should be "pagefile", not "pagafile".

**Comment by DillonN** [comment]
Thanks, fixed now
