### ISSUE TITLE
no supported devices on nicehash

### ISSUE THREAD

**Issue by Mallu01** [nicehash/NiceHashMiner#2223]
Hello. im completely new to crypto mining and need some help.

i have downoalded nicehash and made an account but when i start application, it says no supported devices found. i have as cpu amd ryzen 5 3600, and as gpu rtx 2060

**Comment by luc1an24** [comment]
Hi @Mallu01 
Thank you for reaching out and sorry for slow response.
This looks like driver issue.
Could you please update drivers to the latest version?
Also could you please pin the logs so we can see what is happening there.
Thank you!

Also be sure to check for this:
https://github.com/nicehash/NiceHashMiner/issues/2216
