### ISSUE TITLE
Cross-test video cards RX570 + 1080ti

### ISSUE THREAD

**Issue by Spoob** [nicehash/NiceHashMiner#223]
Earlier this was observed when using NH from another person, everything was sad there. On the version from Dillon all ok. But now I noticed that when testing sia and skunk (prospector) in the benchmark is not involved RX570. Instead, it works 1080 and the test results are different.
![clipboard02](https://user-images.githubusercontent.com/29872738/29659646-9c9dfdc0-88c7-11e7-89a4-ccbd9af02acd.jpg)
![clipboard03](https://user-images.githubusercontent.com/29872738/29659647-9c9f9018-88c7-11e7-8a1d-5084b629eebc.jpg)
![clipboard04](https://user-images.githubusercontent.com/29872738/29659648-9c9ff620-88c7-11e7-91fd-4a43207292ce.jpg)
The upper 2 graphs refer to the radiones. The picture shows that during the test I do not participate.

**Comment by Spoob** [comment]
What is interesting is that when testing another RX570, the test is exactly the one that is being tested

**Comment by DillonN** [comment]
If I understand, you are benchmarking on a 570 and instead the 1080 is what is being used?

The indexing for Prospector relies on a workaround that isn't the most stable, and this may be changed soon. Are you able to post your `\logs\log.txt` file as well as the output of running `prospector list-devices` in the directory with prospector.exe (`\bin_3rdparty\prospector`)

**Comment by Spoob** [comment]
When testing one of the RX570, 1080 is switched on instead. Naturally, the result of the test corresponds to 1080, and not the RX570.
I'll look at the files and try to show.

**Comment by Spoob** [comment]
looked in the folder  (\bin_3rdparty\prospector), found there only such files in the picture, and \bin_3rdparty\prospector\logs\log.txt is missing
![clipboard02-](https://user-images.githubusercontent.com/29872738/29891728-c82ff72e-8dd4-11e7-9f41-f58ac890dacd.jpg)

**Comment by DillonN** [comment]
Should be fixed now
