### ISSUE TITLE
Missing option --kernel for TRex in MinerOptionsPackage.json

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/NiceHashMiner#2231]
Missing option "--kernel" for TRex in MinerOptionsPackage.json.
Because of this, the option is ignored in "Extra Launch Parameters"

**Comment by luc1an24** [comment]
Hi @EvgeniyKorepov 
This is fixed with the new plugin update.
Please update it to version 15.7
Thank you for your patience and happy mining!
