### ISSUE TITLE
Error showing mining, error report bug.

### ISSUE THREAD

**Issue by fhorst1** [nicehash/NiceHashMiner#2238]
![Screenshot_20201211_084233_com nicehash metallum](https://user-images.githubusercontent.com/15360140/101850923-42ad1900-3b8d-11eb-8834-9b4024cb8f86.jpg)
![Screenshot_20201211_084324_com nicehash metallum](https://user-images.githubusercontent.com/15360140/101850931-45a80980-3b8d-11eb-95d4-4d15ec308f64.jpg)

 Even on Windows I receive errors
![16076515090966033098239981238340](https://user-images.githubusercontent.com/15360140/101851467-2eb5e700-3b8e-11eb-93cd-5bea81dc91a2.jpg)

Mining goes OK, I receive payment and the  nicehash miner works like it should.
(Version 3.0.5.5)

![16076516789882630066240085330965](https://user-images.githubusercontent.com/15360140/101851722-ad128900-3b8e-11eb-8a5b-83ef4c89b10f.jpg)

Strange.
Windows 10, Chrome browser.

The app, android 10

When I try different browser, I get 2FA error??

I can disable it, without issues,my authy works OK.

**Comment by anazz20** [comment]
Same thing for me, since around I think 9am EST. So 12 hours ago, just thought it had to deal with the other stuff going on. I know the app had an update that said something to the effect it had to do with a certificate?

**Comment by fhorst1** [comment]
![16076528241352938741405650658709](https://user-images.githubusercontent.com/15360140/101852883-34f99280-3b91-11eb-98de-c1ac425c0538.jpg)
As I'm typing on my mobile, taking a picture is the easiest screenshot :-)

New browser window (chrome incognito) works (after I disabled 2FA, otherwise I couldn't login)

**Comment by fhorst1** [comment]
![16076529922963136032719852170190](https://user-images.githubusercontent.com/15360140/101853087-a3d6eb80-3b91-11eb-8659-d5da48801c62.jpg)

Google chrome version: 87.0.4280.88

**Comment by fhorst1** [comment]
I have version 2.6
![Screenshot_20201211_092446_com android settings](https://user-images.githubusercontent.com/15360140/101853764-c0275800-3b92-11eb-9a53-d7d5a5015403.jpg)
It didn't update yet 

Latest version appear to be:
![Screenshot_20201211_092346_com android vending](https://user-images.githubusercontent.com/15360140/101853803-d208fb00-3b92-11eb-990b-677c89d3ad55.jpg)

I will try the update, keep you posted


Edit after installation:
Full install??
Need to log in again and do all the notification settings again?

Anyway..
Still the same:
![Screenshot_20201211_092924_com nicehash metallum](https://user-images.githubusercontent.com/15360140/101854171-90c51b00-3b93-11eb-82d3-2fc988377c64.jpg)

**Comment by anazz20** [comment]
I just checked mine, I'm in Android 11, app version 2.7. Still getting the error, but yes can see wallet, and notifications.

**Comment by anazz20** [comment]
New version that fixed it just got released for Android.

**Comment by S74nk0** [comment]
Issue resolved. Closing ...
