### ISSUE TITLE
But sometimes 1 gpu does not work

### ISSUE THREAD

**Issue by ilkanaydin** [nicehash/NiceHashMiner#224]
<img width="913" alt="ekran resmi 2017-08-24 13 04 03" src="https://user-images.githubusercontent.com/31144876/29660966-5b26ae06-88cb-11e7-80bc-8743793b4f85.png">
Hello

I have 3 display cards working. But sometimes 1 gpu does not work. It goes on when it happens, but my earnings are falling. It gives a red error to the console. Restart is need. In such cases, can we make a .bat file of your choice run?

**Comment by Avalonis** [comment]
Easely check, Install MS Afterburner look at your gpu's, if this happends one of your gpu's are off (disconect) it happens when to hot or too much overclocked or hardware defekt, than you must reboot hole system. 
Loosing a gpu is tempuraly happens after a algo switch, you can play with timings to wait for new begin the mining after switch, temporaly help this a little bit

**Comment by ilkanaydin** [comment]
Well I'm checking it already. I just want an .bat file that automatically restarts the program when it disfunctions like that. So the system will automatically restart and will run properly again

**Comment by Olegik-ah** [comment]
It's hardware issue. Not ccminer or NHNL. GPU driver hangs... To solve it:
1. Check your power supply voltage (12V and 5V) using a tester
2. Check risers
3. Use latest NVIDIA drivers (remove previously installed drivers via DU)
4. Downclock GPU (mem and chip). Start from stock clock settings
Doing this - you will solve your problem.

If you dont want to solve this issue completely - you can only reboot your PC when error occurs:
1. Check system event log. 99% when issue occurs you will see error 13 or 14 source nvlddmkm. If no - search any other error in system event log
2. Open task scheduler and create new task:
2.1. Tab "General": Name - "reboot, checkbox "run with highest privileges"
2.2 Tab "Triggers" - New - Begin task "on an event", Log - "System", Source - "nvlddmkm", event Id - "13" or "14" - as you find on step 1, checkbox "Enabled"
2.3 Tab "Actions" - New - Action "start a program", program/script "shutdown", arguments "/r /t 0"

That's all:) Your PC will reboot when GPU driver hangs

**Comment by DmitryDMR** [comment]
bad idea. with error 13 or 14 very, very often resetting gpu and memory clocks to the default values, but not videocard disconnecting.
you can use devcon x64 utilities with command "devcon_x64 restart =display", and after use "MSIAfterburner.exe" -Profile1" command

**Comment by ilkanaydin** [comment]
@Olegik-ah  I made exactly like you said but didn't work . is there any way to check log file and restart ? (task scheduler)

@DmitryDMR  When it gives an error nothing chhanges in devices manager . it doesn't delete the gpu .

**Comment by Olegik-ah** [comment]
@ilkanaydin Did you check your system event log? Did you find the error in evetlog preceding the GPU disconnect?

**Comment by ilkanaydin** [comment]
@Olegik-ah  Thanks! i found event log. Now task nvlddmkm dont respond and restart.

**Comment by Olegik-ah** [comment]
Dont understand you. Issue solved?

**Comment by ilkanaydin** [comment]
Yes solved.
