### ISSUE TITLE
NiceHash Miner Download Problem

### ISSUE THREAD

**Issue by ElZinco** [nicehash/NiceHashMiner#2240]
![CaptureNHOS](https://user-images.githubusercontent.com/41454632/101992710-0bf90080-3c6a-11eb-8fed-5672e17784b3.PNG)
I'm a newbie and not really tech-savvy and have a problem installing my nicehash miner software on my windows pc. I get the error message of "This app can't run on my PC" everytime I click on the downloaded installer after downloading it from the official nicehash github installer files. I previously had nicehash miner on my pc but didn't use it for a while, hence the reason for it being outdated, I tried downloading the newest version and the problem happens. I also tried downloading the nicehash updater also found on the same github forum as the installer though it finishes installing it just closes the installer and feels like nothing happened. Furthermore, below is my current windows software information.

Edition	Windows 10 Pro
Version	20H2
Installed on	‎14/‎11/‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by luc1an24** [comment]
Hi @ElZinco 
Thank you for reaching out and sorry for slow response.
This seems like AV issue since NHM should work on your machine.
Have you tried to disable AV for the time of downloading NiceHash Miner?
This should fix the case but if not please update me.
Have a nice day!

**Comment by ElZinco** [comment]
Its ok it just fixed itself, thank you for response.

**Comment by luc1an24** [comment]
Great to hear everything works now.
Have a nice day!
