### ISSUE TITLE
NHM3 3.0.5.6 and .NET Framework v4

### ISSUE THREAD

**Issue by Arty941** [nicehash/NiceHashMiner#2246]
Hello!

I installed the NiceHash Miner. On start the program I see a dialog box about require .NET Framework v4. However I use Windows 10 20H2 with the Framework installed . I tried to install the .NET Framework from Microsoft but the installer informed me that a newer Framework version is already intslled.

See attachments below.

**NhmVersion:** test on 3.0.5.5 and 3.0.5.6
**WinVersion:** MS Windows 10 64-bit 20H2 build 19042.685
**Hw:** NVIDIA GeForce GTX 1060 6GB Driver version: 27.21.14.5206 (452.06); development date: 12.08.2020 DirectX version: 12 (FL 12.1)
**Currently installed "classic" .NET Versions in the system:**
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084

![2020-12-17 (1)](https://user-images.githubusercontent.com/22405739/102475593-1997f700-406b-11eb-9c0f-b0b8303e66f1.png)
![2020-12-17](https://user-images.githubusercontent.com/22405739/102475595-1a308d80-406b-11eb-8af4-b334d403c986.png)

**Comment by Arty941** [comment]
So, Microsoft must die! They developed a framework that may break without repair way. Microsoft built it into the OS, so you can't reinstall it, you can't overwrite the files, and all the recovery methods suggested by the developers won't do anything. In that case, I just changed the accesses to the framework files and transferred them from another computer. Everything works fine now.

**Comment by Michaela813** [comment]
I apologise for that I'm so sorry but thank you so much! 🙏😇
