### ISSUE TITLE
miniZ - unable to update (1.6x)

### ISSUE THREAD

**Issue by Miiichal** [nicehash/NiceHashMiner#2247]
**Unable tu update to version 1.6x** via internal updater - button for update functional, but no progress bar. Update wont start.

NHM 3.0.5.6
Windows 10 20H2, 16GB RAM
Across all my rigs (4-6 GPUs in rig) - no matter what cards - i have RTX 2070, 2070S, 2080, 2080S, 3060Ti

**Comment by IronWalnut** [comment]
I'm seeing this error too

**Comment by luc1an24** [comment]
With the miniZ team we are working on a fix.

**Comment by luc1an24** [comment]
This issue is now fixed and miniZ should download correctly from now on.
