### ISSUE TITLE
changing to x11gost+others randomly

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#225]
ive noticed for a while now on both my gtx770 and 660.....that every now n then i think nicehash decides that x11gost is more profitable. it switches over to x11gost (and sometimes others) from daggerhashimoto or cyrptonight for all of 1 or 2 minutes at a time. 

it then realises it was better off back on dagger or crypto and switches back. annoyingly it appears by the time it all gets setup on the new algo its not profitable anymore. 

im guessing this is due to fluctuating exchange rates?  it seems rather counter productive.

am i best of leaving it as it is? or should i deselect the algos that are interupting normal operation?

thanks in advance for the help/advice
jim

**Comment by luongk** [comment]
It's due to buyers setting honeypot orders (orders that pay significantly better than the market) in order to drive more miners to that algorithm before cancelling (dropping the miners onto lower rates).  

I haven't bothered turning off those algorithms, but if it's an issue it probably doesn't hurt.

**Comment by lmlim** [comment]
those are tricky bastard kinna "steal" a couple minutes of your GPU time every now and then by luring you in with very short time price spike.
it is setup in a very orderly timed manner that they will get "cheap" a couple minutes of your GPU time before you switched back. 
I think these buyer(s) have some sort of affiliation to the coin they are manipulating.

I hope this can be avoided by some sort of rules in placing order eg min time elapsed, or min amount of BTC, or high cancellation fees if less than certain amount of time....

For Now, i would just uncheck all those "bogus" algos, and browse profit calculator once in a while to check what hot algos i might miss, then add those algos back.

cheers.

**Comment by adem4ik** [comment]
@lmlim
![image](https://user-images.githubusercontent.com/4707112/29684173-0d8094c6-8922-11e7-99d9-f09a8138b576.png)
I'm quite sure that is what you need. Also you can tune up **Switch Profitablity Thershold**

**Comment by DillonN** [comment]
This is currently being worked on, thanks for posting
