### ISSUE TITLE
System.IndexOutOfRangeException on Launch

### ISSUE THREAD

**Issue by andrewexton373** [nicehash/NiceHashMiner#2250]
Hello,

I attempted to launch NiceHashMiner 3.0.5.6 and was able to get it to launch once, however I've been unable to get it to launch again even with a fresh download of the 3.0.5.6 zip. When trying to launch the application it appears nothing happens. When trying to launch runnhasadmin I see a powershell prompt open and close rapidly with a System.IndexOutOfRangeException. Upon futher investigation in the Windows Event Viewer I've found: 

`Application: runnhmasadmin.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at runnhmasadmin.Program.Main(System.String[])`

Any ideas what might be causing the issue?
Let me know if there's any other useful information I could provide.

**Comment by S74nk0** [comment]
If you want to run NiceHash Miner as Administrator you should right click and run it as Administrator. `runnhmasadmin.exe` is a helper program to execute programs in Administrator mode from NiceHash Miner itself. I guess the naming can be misleading and why one would try running it. We will rename this and put it inside the `tools` folder and remove it from the root of the application. 

Closing

**Comment by andrewexton373** [comment]
Ahhh haha that's my bad. I appreciate the quick support!
