### ISSUE TITLE
PLUGINS Benchmark: Failed due to command lines incorrectly programmed in NHM.

### ISSUE THREAD

**Issue by bitlite** [nicehash/NiceHashMiner#2251]
- The issue has not already been reported.
Could not find it.

- **Relevant log files are included (generally `\logs\log.txt`).**
[log - Copy.txt](https://github.com/nicehash/NiceHashMiner/files/5719588/log.-.Copy.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/5719589/log.1.txt)

- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
Ran script from logs manually and confirmed issues with command line scripts.

- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
Improperly programmed NHM commands confirmed.

- Specifications of setup such as NHM version, Windows version, and hardware are included.
NHM: 3.0.5.6
Windows 10
CPU: A10-6800
GPU: RX 580 8GB MSI Armor

After scouring the log files, I noticed that the command lines to launch the crypto coins mining are broken.  Please revise and update the codes to make sure it works with all cryptos provided in the plugin section.

**Comment by luc1an24** [comment]
Hi @bitlite 
Thank you for reaching out.
Could you please specify which launch commands are incorrect?
Thank you!
