### ISSUE TITLE
"Error during Benchmark" in EVERY algorithm.

### ISSUE THREAD

**Issue by AcruxOk** [nicehash/NiceHashMiner#2252]
I was trying to benchmark all the algorithms to start mining, but i don't have any clue of what is happening. 

I make the manual benchmark, precise benchmark, reinstalled the drivers of the GPU and the APU, but nothing.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/5726076/log.txt)

Specs:
NHM v3.0.5.6
Windows 10, x64, Version 2004, Build 19041.685.
ASUS GeForce 1060 6gb (Laptop)
Intel I7-8750H CPU 2.20GHz

**Comment by AcruxOk** [comment]
Update: I tried updating windows to 20H2, same issue.

**Comment by AcruxOk** [comment]
Fixed using specific settings and changing the server to brazil. 

Maybe the servers USA and EU are the issue in this case.

**Comment by Michaela813** [comment]
Thank you so much!
