### ISSUE TITLE
Trojan/MSIL.CoinMiner.m found in installer

### ISSUE THREAD

**Issue by dongdongmao** [nicehash/NiceHashMiner#2253]
nhm_windows_3.0.5.6

![Capture](https://user-images.githubusercontent.com/7736453/102880834-e8faf780-4486-11eb-897b-4114a78a8910.PNG)

**Comment by dongdongmao** [comment]
![Uploading Capture.PNG…]()

**Comment by dongdongmao** [comment]
refer to https://www.microsoft.com/security/blog/2018/03/13/invisible-resource-thieves-the-increasing-threat-of-cryptocurrency-miners/

**Comment by Caleb642** [comment]
Are you sure that maybe, just maybe... you are downloading a coin miner...

**Comment by dongdongmao** [comment]
> Are you sure that maybe, just maybe... you are downloading a coin miner...

It comes with nicehash windows installer for sure. And seems like they say "All miners are detected as viruses. Please add the binary as an exception." which is the most interesting part. I don't think we can get an answer here.

**Comment by S74nk0** [comment]
I will quote the release notes section.

> **Important guidelines for using NHM:**
> 
> 1. NiceHash Miner is usually flagged by AV (anti-virus) software. This is normal, as almost every mining software on the market is blacklisted by AV. Just make an exception in your AV software to enable the proper operation of NHML.
> 
> 2. You may have to add an exception in your browser to enable NHM download. [Learn how](https://www.nicehash.com/help/my-browser-antivirus-software-reports-nhm-as-a-virus) OR download password protected zip archive [link](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/3.0.5.6/nhm_windows_3.0.5.6_pw.zip).
> 
> 3. We cannot guarantee for every 3rd party miner code thus you agree to use it at your own risk.
> 
> 4. We suggest you don’t use cryptocurrency wallets or have any access to any cryptocurrency, sensitive or important data on the same computer where you use NHM. NiceHash will never ask or use your private keys, but we cannot guarantee the same for the 3rd party miners included in NHM now or any time in the future.
> 
> 5. Add an exception to Windows Defender for the NiceHash Miner folder (after you unzip the package).

This issue/question was raised and answered many times. We can only guarantee for the software developed by us [NiceHash Miner](https://github.com/nicehash/NiceHashMiner) and our miner plugin [excavator](https://github.com/nicehash/excavator). All other 3rd party mining software is closed source and we cannot examine and vouch for those. Miners are bundled with malware and this is one of the main reasons it is flagged. 

Closing issue.
