### ISSUE TITLE
Suggestion: Add xmrig for cpu mining

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#226]
Found quite solid cpu miner of XMR: https://github.com/xmrig/xmrig
They have released a new version with nicehash support a few days ago: https://github.com/xmrig/xmrig/releases/tag/v2.3.0

Dev fee is configurable @ https://github.com/xmrig/xmrig/blob/master/src/donate.h#L40

I have only tested it on my old **i5-2320 sandy bridge** CPU and compared with **xmr-stuck-cpu** with fairly the same configs - 3 threads and 75% cpu usage:
**xmrig:** 183 H/s
**xmr-stuck-cpu:** 171 H/s

UDP: I have also tested on another cpu - Intel Core i5-4570
**xmrig:** 221 H/s
**xmr-stuck-cpu:** 199 H/s

Also devs suggest to use msvc builds, but my benching has shown that there is no real difference in hash rates between msvc and gcc on my CPU.

Here is the config for example:
>{
>    "algo": "cryptonight",
>    "av": 0,
>    "background": false,
>    "colors": true,
>    "cpu-affinity": null,
>    "cpu-priority": null,
>    "donate-level": 1,
>    "log-file": null,
>    "max-cpu-usage": 75,
>    "print-time": 60,
>    "retries": 5,
>    "retry-pause": 5,
>    "safe": false,
>    "syslog": false,
>    "threads": null,
>    "pools": [
>        {
>            "url": "cryptonight.eu.nicehash.com:3355",
>            "user": "wallet.worker",
>            "pass": "x",
>            "keepalive": false, 
>            "nicehash": true
>        }
>    ]
>}

**Comment by drkskwlkr** [comment]
> Found quite solid cpu miner of XMR

Looks interesting indeed. I also had a look at the Nvidia GPU XMR miner by same developer but it seems to be a bit slower than tpruvot ccminer for Maxell/Pascal, or I can't get the blocks/threads right for my cards for optimum performance. Have you looked into it?

**Comment by utc99** [comment]
This one really seems giving up to 10% better hashrate, tested on 5+ machines, i3-i7

**Comment by Olegik-ah** [comment]
Tested 2 days on dual xeon e5-2687w. Seems good miner. 75% load = 820h/s

**Comment by DillonN** [comment]
Thanks for posting, I will look into this

**Comment by Nicheuji** [comment]
@DillonN Just wondering. Why wasn't this added to 1.8.1.2?

**Comment by dinicthis** [comment]
Can we just mine with it pointed at nicehash's servers and it throws in with our software in the nicehash package?
I found some comment from the monero pool here regarding nicehash:
https://minemonero.pro/en/#!/help/getting_started, but you need a monero wallet, which I wanted to avoid, instead piggybacking my mining power into my nicehash interface.

**Comment by dinicthis** [comment]
I tried xmrig and my hashrate went from about 240 to about 270.
So, it is superior to what nicehash presently has, from what I've seen.
But, the can't-rid-of-it-5% donation built in erases quite a bit of that. I tried setting it to zero in the config file, but nope, it was right back to 5% when I ran it.

**Comment by Nicheuji** [comment]
@dinicthis Just edit the config.json to connect to a cryptonight nicehash pool (along with your nicehash wallet). As for the donation level, the lowest you can go is 1%. If you set it to 0% then it'll automatically change that to 5%, unless you build it yourself then you can set the donation level to 0

**Comment by dinicthis** [comment]
I did that, Nich.
It is working fine at about 200H/s, evidently?. Not really sure how great that is, profit-wise, but it's just a non-Ryzen CPU, after all.
![image](https://user-images.githubusercontent.com/30636661/30254016-50dd7ea6-9646-11e7-9eda-c9041735daa6.png)

**Comment by quinnman2017** [comment]
I am using an intel i5-5200U but I am only getting around 39H/s I live on the east coast of the united states and I am using the pool usxmrpool.com which is based in the west coast US could this be the reason for such low hash rate?

**Comment by sampollard** [comment]
@quinnman2017 the network traffic shouldn't be an issue, either that's just the hashrate you'll get with that CPU or there's a bunch of L3 cache misses. That model only has 3MB of L3 cache so you may only be able to run 1 or 2 processes. My single core performance is about 40 H/s. Maybe try messing around with the `--cpu-affinity` or `--av` flags?

**Comment by sampollard** [comment]
I pointed xmrig at stratum+tcp://cryptonight.usa.nicehash.com:3355 and it appears to accept my shares, both on the client and on the web interface.

```
[2017-09-27 23:07:52] accepted (2/0) diff 80000 (69 ms)
[2017-09-27 23:08:17] speed 2.5s/60s/15m 254.5 257.2 n/a H/s max: 261.3 H/s
[2017-09-27 23:08:42] new job from cryptonight.usa.nicehash.com:3355 diff 80000
```

By the way, I'm running Linux with an AMD FX-6300 (no overclock) and with the following settings I'm getting about 250 H/s.
```xmrig --algo=cryptonight --url=stratum+tcp://cryptonight.usa.nicehash.com:3355 --userpass=[wallet]:x```

**Comment by adem4ik** [comment]
@quinnman2017 imo it is better to post such issues not related directly to NHML itself on https://github.com/xmrig/xmrig/issues

**Comment by adem4ik** [comment]
Btw it is suggested to use `"keepalive": false,` with nicehash.com: https://github.com/xmrig/xmrig/issues/97

I've updated example config in the 1st post

**Comment by dinicthis** [comment]
xmr in nicehash seems to be behaving okay but not getting 270 tgat's for sure.

**Comment by adem4ik** [comment]
I think I can close this issue as xmrig support added since 1.8.1.4 version.
