### ISSUE TITLE
AMD drivers keep timing out/crashing Radeon VII

### ISSUE THREAD

**Issue by armstrongdicksmasher** [nicehash/NiceHashMiner#2262]
3900x Radeon VII asus P-Prime x570 mobo, 32gigs 3200mhz ram Teamgroup, 850w corsair psupply

AMD display drivers hard crash every time i try to turn on nicehash, i initially got it working fine with a default gpu setting + extra fan speed, but it was gonna melt my gpu, over 100+ degrees junction constantly, i tried a single massive underclock recommended to me via https://miningchamber.com/gpu-mining/radeon-vii-mining-overclocks/ which worked, ONCE, but i got very poor performance and wanted to scale it up a bit, i tried that, and i have been hard crash looping ever since. All combinations of gpu tuning i try causes the same constant display crashing or even black screen crashes my pc, from stock to partial undervolts to heavy undervolts. 

My gpu still plays games fine when i switch it over to my default settings on the gpu (although it's always been kinda unstable for gaming, probably hardware related, its a frankenstein gpu at its heart) , i dont do CPU mining and dont want to.

It sometimes seems to work a bit during all this display crashing, but it's wildly unstable and i'd be stupid to keep trying like this. Any ideas?

12d62632-3f20-4969-9493-8b8030b4d14e

**Comment by Panthium** [comment]
same issue, start Nicehash, but don't start miner.
do into Benchmark tab, and disable NBminer KAWPOW and Nicehash will mine without locking up.
My VII card is at 83-84 deg.C mining DaggerHashmoto

**Comment by troyrichrod** [comment]
I underclock and overvolt my gpu clock. Max out vram and fans. Push -20% power thru it and sometimes it fails, but thats just the chance you take with NiceHash being they dont like hardware overclocking on our side.
<img width="1270" alt="Screenshot 2021-01-02 233302" src="https://user-images.githubusercontent.com/65886226/103472494-d371b180-4d53-11eb-966d-9ec3b0d0ace1.png">

**Comment by armstrongdicksmasher** [comment]
> same issue, start Nicehash, but don't start miner.
> do into Benchmark tab, and disable NBminer KAWPOW and Nicehash will mine without locking up.
> My VII card is at 83-84 deg.C mining DaggerHashmoto

Thanks!! worked like a charm, only problem is now my gpu is back to doing what it did at first, running at 100+degrees.... guess ill tinker with it some more.

Edit: got it working smoothish after some underclocks, -15% max freq, -10% power draw, fans cranked, still outputs 75-77MH's, ~78c junction temp, 60c gpu temp. Won't be great long term, but it's not worth water-cooling or opening it up and using thermal paste etc, im not tech savvy enough to do it without screwing it up.
