### ISSUE TITLE
3.0.5.6 RX 580 8GB not appear anymore into device list.

### ISSUE THREAD

**Issue by JeromePrunier** [nicehash/NiceHashMiner#2263]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by JeromePrunier** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/5759510/log.txt)

**Comment by JeromePrunier** [comment]
![3056_error](https://user-images.githubusercontent.com/43646209/103447337-d9826800-4c57-11eb-9aa9-0fb8d05c702e.PNG)

**Comment by JeromePrunier** [comment]
![3056_error](https://user-images.githubusercontent.com/43646209/103447354-2bc38900-4c58-11eb-8e01-976c3acc2f67.PNG)

**Comment by S74nk0** [comment]
@JeromePrunier inside the root folder of NiceHash Miner inside the latest app folder run `device_detection.bat` and post back the generated file `device_detection.txt`. When did the device detection stopped working? 
![image](https://user-images.githubusercontent.com/1517233/103533110-d3290180-4e8c-11eb-8010-349e66e57c9c.png)
