### ISSUE TITLE
Radeon RX5700 GPU Temp/Load not detected

### ISSUE THREAD

**Issue by littlejab** [nicehash/NiceHashMiner#2266]
Windows 10 20H2
Ryzen 5 3500 + AMD Radeon RX 5700
NHM Version 3.0.5.6
![image](https://user-images.githubusercontent.com/14092359/103670567-50976380-4fac-11eb-9d14-2d82452fb1dc.png)

**Comment by littlejab** [comment]
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/5771390/log.1.txt)

**Comment by nanthanwa** [comment]
Same as Radeon RX 5500 XT 8GB.

**Comment by luc1an24** [comment]
Hi
Thank you for reaching out.
We are aware of the issue with the new AMD cards and have a plan to fix this.

**Comment by live75bird** [comment]
Hello - newbie to mining.  Experiencing same with AMD 5600 XT 6GB

![image](https://user-images.githubusercontent.com/78627834/107104519-a5b2d900-67e7-11eb-850b-558cf0545849.png)

**Comment by jeremyfry** [comment]
@luc1an24 Any update on this?

**Comment by Optamizm** [comment]
> Hi
> Thank you for reaching out.
> We are aware of the issue with the new AMD cards and have a plan to fix this.

Any update?

**Comment by Optamizm** [comment]
> Hi
> Thank you for reaching out.
> We are aware of the issue with the new AMD cards and have a plan to fix this.

Any update?
