### ISSUE TITLE
NiceHash GPU error

### ISSUE THREAD

**Issue by bbigka** [nicehash/NiceHashMiner#2269]
![image](https://user-images.githubusercontent.com/77138812/103977016-db45b180-51aa-11eb-8371-4a7447166980.png)
I'm new to use NiceHash and I have an error on the mining plase help me to solve this problem.

**Comment by bbigka** [comment]
my gpu also running lower than 10%

**Comment by luc1an24** [comment]
Hi @bbigka 
Thank you for reaching out.
For the first thing I will ask you to update drivers to the latest version, since drivers are the problem in the most cases.

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/benchmark-error-in-nicehash-miner
