### ISSUE TITLE
NHML and MSI Afterburner Prifiles

### ISSUE THREAD

**Issue by mishajet** [nicehash/NiceHashMiner#227]
Добавьте возможность в NiceHash Miner Legacy для каждого алгоритма указывать профиль (от 1 до 5) для MSI Afterburner, чтобы можно было использовать заранее заготовленные профили разгона/андервольтинга.
Т.е. нужно чтобы перед каждым запуском батника (.bat) были бы вот такие 2 строчки:

"C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" -Profile1 
timeout /t 1

И потом только бы указывался сам майнер уже с вашими параметрами биржи!!

Чтобы это всё где-то в опциях программы можно было добавлять и настраивать по своему усмотрению.
Ну или просто чтобы была возможность пользователю указывать что-угодно до строчки майнера с вашими параметрами биржи

Очень этого не хватает!!!! Пожалуйста, обратите на это внимание.!
Заранее спасибо!!

**Comment by Spoob** [comment]
А зачем тебе этот бред? сделай афтерьбернер в автозапуске с применением нужного профиля. или тебе надо под каждый алгоритм свой разгон?

**Comment by mishajet** [comment]
> или тебе надо под каждый алгоритм свой разгон?

ДА! Ведь уже описал это в первом посте!

**Comment by Spoob** [comment]
да уш. то еще извращение. не проще сделать один разгон стабильный для всего чем так извращаться и ловить глюки потом не понятно откуда?

**Comment by mishajet** [comment]
Кому как! Мне проще и эффективней настроить карты под конкретный алгоритм. При переключении профилей у меня глюков не наблюдается.

**Comment by adem4ik** [comment]
Разработчик англоговорящий, и вряд ли он поймёт ваше пожелание.

Developer is English speaker, he won't understand your suggestion anyway.

**Comment by DillonN** [comment]
Move to #208, running bat on switch would allow AB switching
