### ISSUE TITLE
GTX 1070, Excavator, wrong detected

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/NiceHashMiner#2270]
Win 10 Pro x64, driver 460.89
NHM generate config:
```
[
	{"time":0,"commands":[
		{"id":1,"method":"subscribe","params":["nhmp-ssl.eu.nicehash.com:443","382bkNMNYWRvWKMQ4K25XMraJcybRf8qsv$0-qK-S27u+RVK2CqlhxAU4Aw"]}
	]},
	{"time":1,"commands":[
        {"id":1,"method":"algorithm.add","params":["daggerhashimoto"]}
    ]},
	{"time":2,"commands":[
		{"id":3,"method":"worker.add","params":["daggerhashimoto","NVF-5a7ceca5-a72a-5e52-b72b-8d2688017b38"]},
		{"id":3,"method":"worker.add","params":["daggerhashimoto","NVF-586ea8a0-757f-5b11-b0cc-99354494a996"]}
	]}
]
```
When mining starts, nothing happens. Video cards are idle

If I replace the weird graphics card IDs with 0 and 1 and run from the command line everything works fine :
```
[
	{"time":0,"commands":[
		{"id":1,"method":"subscribe","params":["nhmp-ssl.eu.nicehash.com:443","382bkNMNYWRvWKMQ4K25XMraJcybRf8qsv$0-qK-S27u+RVK2CqlhxAU4Aw"]}
	]},
	{"time":1,"commands":[
        {"id":1,"method":"algorithm.add","params":["daggerhashimoto"]}
    ]},
	{"time":2,"commands":[
		{"id":3,"method":"worker.add","params":["daggerhashimoto","0"]},
		{"id":3,"method":"worker.add","params":["daggerhashimoto","1"]}
	]}
]
```
The rest of the miners work without problems.

I am attaching the launch result \NHM3\app_3.0.5.6\device_detection.bat
[device_detection.txt](https://github.com/nicehash/NiceHashMiner/files/5786702/device_detection.txt)

**Comment by S74nk0** [comment]
@EvgeniyKorepov this is indeed an issue with the excavator plugin, we will add better integration with one of the upcoming releases of the plugin. But it seems this issue is caused by an internal driver error. Can you re-install NVIDIA drivers and try again? 
`NVF-5a7ceca5-a72a-5e52-b72b-8d2688017b38` these are our internal NVIDIA fallback ids and these are deterministically generated when NVIDIA drivers don't work properly.

**Comment by EvgeniyKorepov** [comment]
Reinstalling drivers with a "clean install" solved the problem )

P.S.
Initially there was Windows 7 Pro, after upgrading to Win 10 using Media Creation Kit and installing the latest drivers (also with "Clean Install") - an error occurred.
It is strange that another driver reinstallation solved the problem. Windows ways are inscrutable )))

P.P.S.
As a result, one of the video cards does not show the fan speed)))) But this is no longer such a big problem)

**Comment by S74nk0** [comment]
Please post the logs regarding the fan speed issue. We will take a look. 
I will re-open the issue until we release the updated excavator plugin as this NVIDIA driver edge case issue shows a bug in the plugin. 

Sorry for the slow replies.

**Comment by EvgeniyKorepov** [comment]
Fan speed is not an issue with the excavator or the NHM3. All other utilities also do not show the tachometer of one of the two video cards. Although the cooler speed is shown correctly in percentage, it is confirmed by visual observation of the coolers.
![image](https://user-images.githubusercontent.com/35364901/104445836-aec6d680-55aa-11eb-9938-ffb1a0e67f0f.png)
