### ISSUE TITLE
Do you support ARM architecture on Ubuntu 18 ?

### ISSUE THREAD

**Issue by mink007** [nicehash/NiceHashMiner#2272]
I am trying nicehash on Jetson AGX Xavier which is ARM based with Ubuntu 18.
Do you support ARM platform?

**Comment by luc1an24** [comment]
Hi @mink007 
Thank you for reaching out.
NiceHash Miner is made only for Windows machines.
If you would like to mine on any other machine please check out NHOS available on: https://www.nicehash.com/download-center
Have a nice day!

**Comment by mink007** [comment]
I think nicehash shld think about supporting ARM architectures as there are ARM based systems that has emerged recently. Its only going to go up. Thank you
