### ISSUE TITLE
AMD Ryzen XMRig/rxmonero hashrate drop fix - cannot apply to NHM

### ISSUE THREAD

**Issue by therealsummoner** [nicehash/NiceHashMiner#2273]
Hi,
with the original XMRig launch options "--cpu-priority 0", the CPU hashrate occasionally drops, but there is a fix for this, however i don't see any way to apply this to NHM:

[https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide](https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide)
> The only known workaround for this is to unpin threads from cores like this (example for Ryzen 5 3600):
> "rx": [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
> In general, just edit your config.json and replace each core number with -1 in the "rx" array in config.json.

If i use "--cpu-priority 2", hashrate is ok, but the pc is not really usable anymore outside mining and everything lags.
Is there a way to do this, or can this option to be implemented in some way?
TiA!

**Comment by luc1an24** [comment]
Hi @therealsummoner 
Thank you for reaching out!
This can be done by adding --config=yourConfig.json to your Extra Launch Parameters for this algorithm. You can set them in Benchmark Tab under settings for specific algorithm
Here is also a doc about Extra Launch Parameters for help:
https://github.com/nicehash/NiceHashMiner/blob/master/doc/Plugins/InternalSettings/ExtraLaunchParameters.md

If you need any help, please let me know!
