### ISSUE TITLE
Nvidia GeForce  765M

### ISSUE THREAD

**Issue by Alexander1414x** [nicehash/NiceHashMiner#2277]
NiceHash latest Version

Benchmark doesnt find from NVIDIA Ge Force GTX 765M
https://prnt.sc/wljxhr

Problem with mining GPU

[log.txt](https://github.com/nicehash/NiceHashMiner/files/5800209/log.txt)

**Comment by S74nk0** [comment]
Mobile/Laptop hardware is not supported.
