### ISSUE TITLE
Plz, plz, plz : we need a Linux version (for 7 and more GPUs)

### ISSUE THREAD

**Issue by propergol** [nicehash/NiceHashMiner#228]
Hello, unless I did miss something Windows 10 only support 6-7 GPUs max, and so if you have more you simply can't use Nicehash and all the optimizations that come with it :(

Linux doesnt have this limitation.

More and more mobo manufacturer are releasing boards that support more than 10 GPUs.

We dont need something fancy with a beautiful interface and so on. NO.
A "simple" script that check profitability to switch from an algo to an other in command line.

Is there any change devs here would release such Linux version of Nicehash.

Thanks and sorry for posting this here, since I know this is a request BUT can also sounds like a bug... :)

**Comment by fefsf** [comment]
People have managed more than 7 GPUs on windows 10 already. Also, both AMD and NVIDIA are going to release driver updates that will allow a substantially increased amount of GPUs to be supported in windows

**Comment by propergol** [comment]
to get more than 7 GPUs you need to mix AMD and Nvidia and I want to use Nvidia only :)
Regarding driver update, I have read things on AMD side but not Nvidia yet.
Anyway do you know when both brand plan to release those drivers?

**Comment by fefsf** [comment]
I dont know exactly when the drivers will come out, but now  that a mining board with 19 pcie slots is coming out it wont be long. As far as having more than 7 GPUs with NVIDIA only, you can. On a ZCASH mining group im in people have had 8+ GPUS working in windows 10 with NVIDIA using the Asus Z270-A PRIME board.

**Comment by Pruxa-sun** [comment]
Using 8 Nvidia 1070 on Windows 10 without any troubles. But sometimes miner doesn't load last GPU correctly, it works 10% slower than others, miner restart fixes the problem.

**Comment by Singman33** [comment]
Face it, Nicehash will never ever release a Linux version. I've made for myself a script to use their API and do everything Nicehashminer is doing (and even better), it's not really complicated.

**Comment by rbj325** [comment]
Give it 6-12 months and all the functionality NiceHash Miner is using in .Net Standard will be cross platform on .Net Core and porting the miner to Linux will be fairly straightforward.

**Comment by kentdbarker** [comment]
I am running 8 RX 480 on a TB250-BTC PRO and it works fine, but it will not recognize the 9th GPU.  It has 12 GPU Pcie connectors.  Booting windows 10 without a GPU driver will show more than 8 cards in device manager with the yellow exclamation by the driver, but then loading  the driver will bluescreen the windows boot if there are more than 8 GPU.  So it seems windows if fine with it, but the driver is not.

**Comment by Ketoman** [comment]
I am running 8 RX 480 on a TB250-BTC PRO and it works fine, but it will not recognize the 9th GPU. It has 12 GPU Pcie connectors. Booting windows 10 without a GPU driver will show more than 8 cards in device manager with the yellow exclamation by the driver, but then loading the driver will bluescreen the windows boot if there are more than 8 GPU. So it seems windows if fine with it, but the driver is not.

**Comment by propergol** [comment]
Thanks for confirming we are back to post 1 :D

**Comment by tomrus88** [comment]
Yeah Linux version would be nice, even if it's just console app. Now with .NET Core/Standard it should not be hard to create. Just move most of logic into class library and reuse it for both Linux and Windows.

**Comment by giantpune** [comment]
@Singman33 any change you could share your script?  It would save the rest of us having to reinvent the wheel figuring out all their endpoints and whatnot.

**Comment by DillonN** [comment]
There are currently no plans for Linux support. Will let you know if that changes..
