### ISSUE TITLE
No app associated with running the NHM.exe?

### ISSUE THREAD

**Issue by GrotesqueGames** [nicehash/NiceHashMiner#2282]
Fresh account, fresh download. No troubles with AV or install. Go to run as admin and I get [this](https://imgur.com/a/RIQvT8K)
No idea. Haven't seen anyone else ask about it. So wondering if I can get some help? Thanks.

**Comment by aertist** [comment]
i'm having this same problem. Do you got any solution?

**Comment by GrotesqueGames** [comment]
Yes, I had to follow the directions to turn off Windows Defender and it works perfectly now. 
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Jan 19, 2021, 03:15 by notifications@github.com:

**Comment by Dohtar1337** [comment]
Check this: https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion
