### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by bnzSup** [nicehash/NiceHashMiner#2284]
So I'm pretty new to mining and I started using nicehash. I know this question might get asked a lot, but windows keeps saying that some plugins folders (NBminer) is a Trojan. I googled it a bit and found out that windows just keeps giving false positives. But I haven't found any related directly to this Trojan:Win32/Vigorf.A just wanted to know if I can add the nice hash folder to the exception list safely.

**Comment by scr1ble** [comment]
Same question....

**Comment by twist84** [comment]
I was getting the same message from windows defender but I figured out a work around, if you copy the contents of the latest `nhm_windows_3.0.5.6.zip` from the github releases into `C:\Users\<User>\AppData\Local\Programs\NiceHash Miner` it should fix the issue.

**Comment by iodev** [comment]
just tell us why it triggers ... we are mostly just curious

**Comment by Dohtar1337** [comment]
Check this: https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion

**Comment by kenaitian** [comment]
No matter what I have done to exclude Nicehash from the Norton 360 anti-virus software, it still blocks it whereby stating that Nicehash experiences too many crashes and that it will close itself. :-(

![Capture3](https://user-images.githubusercontent.com/63857624/121417915-6c76ab00-c938-11eb-88b2-669fa4ce69fe.PNG)
![Capture2](https://user-images.githubusercontent.com/63857624/121417916-6c76ab00-c938-11eb-8688-42d9f6d2f981.PNG)
![Capture1](https://user-images.githubusercontent.com/63857624/121417919-6d0f4180-c938-11eb-97cb-4fa0351e6618.PNG)
![Norton360-ExcludeConfirmation](https://user-images.githubusercontent.com/63857624/121417920-6d0f4180-c938-11eb-8e0c-6d89cc6aa898.PNG)
![Norton360-ThreatDetected](https://user-images.githubusercontent.com/63857624/121417921-6d0f4180-c938-11eb-819f-062d3564829b.PNG)
![Norton360-FileInsight-Blocked](https://user-images.githubusercontent.com/63857624/121417922-6d0f4180-c938-11eb-89cc-e823241111fe.PNG)
![Capture6](https://user-images.githubusercontent.com/63857624/121417923-6d0f4180-c938-11eb-9287-7d744dccaa52.PNG)
![Capture5](https://user-images.githubusercontent.com/63857624/121417924-6d0f4180-c938-11eb-80e4-584d3bb9d3d5.PNG)
![Capture4](https://user-images.githubusercontent.com/63857624/121417925-6da7d800-c938-11eb-9cf9-5fbfbb4d24c4.PNG)
