### ISSUE TITLE
updating files failed

### ISSUE THREAD

**Issue by regchanuk** [nicehash/NiceHashMiner#2288]
- **Relevant log files are included (generally `\logs\log.txt`).**

ok first off new install both .zip and exe do same thing excempted files and still not working 

updating excavator was not installed error and multiple times tried to update this but failed

![image](https://user-images.githubusercontent.com/46360316/104919098-9cbfac00-598d-11eb-9dd0-bf201b43c2f4.png)
![image](https://user-images.githubusercontent.com/46360316/104919130-a77a4100-598d-11eb-9fc3-1e9637197d63.png)
![image](https://user-images.githubusercontent.com/46360316/104919161-b3660300-598d-11eb-8c2f-064dd8927758.png)

**Comment by regchanuk** [comment]
same message for every miner being installedseems like its not being installed
![image](https://user-images.githubusercontent.com/46360316/104919838-d218c980-598e-11eb-949b-9872767cfa42.png)

**Comment by regchanuk** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/5830368/log.txt)
 here is my logs

**Comment by regchanuk** [comment]
![image](https://user-images.githubusercontent.com/46360316/104920733-253f4c00-5990-11eb-8ef3-8cae86c01213.png)

**Comment by regchanuk** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/5830403/log.txt)
 heres a log related to above installs

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion
