### ISSUE TITLE
No supported devices found

### ISSUE THREAD

**Issue by nomirobin** [nicehash/NiceHashMiner#2289]
I downloaded the newest version of NiceHash
When starting NiceHash it says i should either " login " or " enter bitcoin adress manually "
When i press login, the pop up disappears and restarts itself. When i press enter bitcoin adress manually it says no supported devices found.

I have a Intel(R) Xeon(R) CPU E5520 @ 2.27GHz 2.26 GHz (2 processor)
8 GB Ram
My Graphics Card: nvidia quadro fx 580

What must i do to so that my pc can find the device?

**Comment by S74nk0** [comment]
Compute capability version 5.2+ gaming GPUs are supported and non gaming GPUs might work but aren't officially supported (for reference https://en.wikipedia.org/wiki/CUDA).  Minimum recommended version is 6.0. With new GPUs older GPUs quickly fall behind and aren't competitive for mining.
No new miner supports your GPU and therefore it is not supported.
