### ISSUE TITLE
Asking about Payouts setting.?

### ISSUE THREAD

**Issue by Yerr0r** [nicehash/NiceHashMiner#229]
how i can change my payout plan so i can make Nicehash legacy send balance to my wallet when it Reached 0.05 bitcoin to above not not 0.01 this option Available or not .!

**Comment by ChriscomIT** [comment]
NOT available! Use Nicehash wallet if u need a more flexible payout plan. You can withdraw from it every 0.002BTC (don't forget the 0.0005BTC fee). 

And as well here is the wrong place to ask such question. This place is about the Nicehash miner application development not about the Nicehash service or any kind of help forum. Please just submit questions related to bug reports, submit bug reports at all or feature enhancements. But please don't ask questions related to the service only not about the application.

THANKS IN ADVANCE!
