### ISSUE TITLE
Ability to report on a specific rig's earnings

### ISSUE THREAD

**Issue by goofygrin** [nicehash/NiceHashMiner#2290]
I'd love in the Hicehash web ui/mobile app to see a particular rig's earnings for some period of time (daily/weekly/monthly/yearly) so that I can accurately track revenue/cost.

Right now I'm having to download the csv and munge the data to try and back into it which is painful and I'm not sure the data is accurate.

**Comment by Dohtar1337** [comment]
For now, we will not implement this
