### ISSUE TITLE
Ability to pass in a command file for Excavator

### ISSUE THREAD

**Issue by goofygrin** [nicehash/NiceHashMiner#2291]
Right now the command file for Excavator is generated at run time.  It would be nice to be able to either add to or override those commands so that I can have Excavator control my overclock settings so that I can work around the DAG cache bug in Excavator.

Right now I'm running Excavator manually so I am losing some visibility/tracking in the Nicehash UIs.

**Comment by goofygrin** [comment]
Looks like I can pass in "-c commandfile.json" in the additional parameters and it will override what Nicehash passes in... this feels like a "happy accident" rather than expected behavior though.

**Comment by S74nk0** [comment]
@goofygrin we can add an option to override the commandfile.json TEMPLATE as this file determines what GPUs to use and location to mine. How many GPUs does your rig have?

**Comment by Dohtar1337** [comment]
Please read this: https://github.com/nicehash/NiceHashMiner/tree/master/src/Miners/Excavator
