### ISSUE TITLE
Open nicehash after install cause error

### ISSUE THREAD

**Issue by movitran** [nicehash/NiceHashMiner#2294]
I have some problem after install nicehash after that open it cause error like picture
![error](https://user-images.githubusercontent.com/1176170/105341121-4d89ad80-5c11-11eb-97a0-6fc56b29862b.jpg)

**Comment by S74nk0** [comment]
@movitran Are you running NiceHash Miner inside a virtual machine? Can you download our [device_detection](https://github.com/nicehash/DeviceDetection/releases/download/v2.1/device_detection_x64_signed.zip) and run the script `device_detection.bat` that will generate `device_detection.txt` and post it here?

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
