### ISSUE TITLE
Ability to use command line arguments to stop/start mining 

### ISSUE THREAD

**Issue by wyx087** [nicehash/NiceHashMiner#2295]
Please add an ability to use command line argument to stop/start mining. 

I've got a little mining helper program that attempts to match mining GPU power against excess solar production (using nvidia-smi.exe). When solar drops too much, the little program would use taskkill to end NHM task tree. This is inelegant and resume mining is slow because NHM has to cold start each time. 

So it would be great to be able to control NHM easily, and most importantly, locally just buy running NiceHashMiner.exe (or another EXE) with arguments to quickly start or stop mining.

**Comment by alizeyni** [comment]
Ok

**Comment by alizeyni** [comment]
Ok

**Comment by SweetBabyCheesus** [comment]
I was also looking for this. Are there any news about this?

**Comment by Dohtar1337** [comment]
You can do this with QuickMiner/excavator
https://github.com/nicehash/NiceHashQuickMiner

**Comment by wyx087** [comment]
I may have missed it. I don't see any documentation for either QuickMiner or Miner on how to control start/stop mining via command-line? 

For example, how do I control the miner via my C or batch code: 
C: `system("NiceHashQuickMiner.exe --stop"); `
or 
BATCH: `start "" NiceHashQuickMiner.exe --start`

**Comment by Dohtar1337** [comment]
@wyx087 pardon me, I meant Excavator: https://github.com/nicehash/excavator/tree/master/api
