### ISSUE TITLE
Help me choose my Bitcoin wallet

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#23]
Redirect to the new nicehash site
https://new.nicehash.com/help/how-to-create-the-bitcoin-addresswallet

I am opening a ticket with Nice Hash to have them update this page to include NiceHash wallet instructions too

NiceHash wallet is very reasonable now (under certain circumstances) with the fees!

**Comment by DillonN** [comment]
For the moment all links are to www.nicehash.com, since the idea is that new.nicehash.com will eventually move to nicehash.com (we want to avoid broken links on any version)

**Comment by billmcilhargey** [comment]
makes sense; do note that the link already doesn't work if for example new becomes www becuase the concept of ?faq does not exists.

So at some point this link will potentially fail regardless of what is decided

**Comment by DillonN** [comment]
Thanks I'll be keeping an eye on it, for now we're sticking to the old links though!
