### ISSUE TITLE
Why does V1.8.1.1 not take into account the income of CryotoNight?

### ISSUE THREAD

**Issue by djets** [nicehash/NiceHashMiner#230]
Why does V1.8.1.1 not take into account the income of CryotoNight? (CPU AMD Ryzen 7 1700)
There is not even a section of income on this algorithm on the website of the miner's statistics.

**Comment by djets** [comment]
![p1](https://user-images.githubusercontent.com/31355415/29727352-29d951de-89dc-11e7-8a3f-5d54c5f100ad.PNG)
![p2](https://user-images.githubusercontent.com/31355415/29727355-2c0756b8-89dc-11e7-9c87-b7df96ebcd88.PNG)
![p3](https://user-images.githubusercontent.com/31355415/29727356-2d9e2b0a-89dc-11e7-9e96-fcf22a8acacf.PNG)

**Comment by djets** [comment]
![p3](https://user-images.githubusercontent.com/31355415/29727427-7fb8190a-89dc-11e7-9736-cf2cc8c3c6bb.PNG)
![p1](https://user-images.githubusercontent.com/31355415/29727429-7fb98cae-89dc-11e7-9944-b3709685db01.PNG)
![p2](https://user-images.githubusercontent.com/31355415/29727428-7fb98592-89dc-11e7-809a-6e93299f740b.PNG)

**Comment by ChriscomIT** [comment]
When did you start mining CN and when did you take the screenshot? Did you wait at least 5 minutes after start mining CN? Sometimes it can even be around 8 or 10 minutes for CN algorithm depending on when the first share is submitted. This depends on your hash rate and the corresponding workload which have to be calculated/solved.

**Comment by adem4ik** [comment]
Just in case check that **"wallet_address":** in NHML-1.8.1.1\bin\xmr-stak-cpu\config_0.txt is yours

**Comment by djets** [comment]
> Just in case check that "wallet_address"
Thank you. Exactly what is needed. I manually changed config_0.tht for more efficient use ryzen7 cores and forgot to change wallet_address. And since you have to put this attribute on the file "read-only", so that NHML does not change it, then, respectively, the wallet was left by default.

**Comment by DillonN** [comment]
Looks like the issue is resolved, I'll close
