### ISSUE TITLE
CPU Temp & Fan Speed not displaying

### ISSUE THREAD

**Issue by cosmin8905** [nicehash/NiceHashMiner#2301]
Note that the fan speed and temperature are failing to be displayed on the NiceHash GUI

I'm running v3.0.5.6 NiceHash Miner version and Online NiceHash Miner
NiceHash GUI is running with admin privs 
My CPU is an AMD Ryzen 5 3600

![image](https://user-images.githubusercontent.com/30837545/105919603-f2d2c600-6003-11eb-8a87-f7dc530e79f1.png)

**Comment by Vinni2K00** [comment]
I saw on Reddit that they confirmed it being a known issue and that they are working on it, but that was like 3 months ago and still no solution has been found

**Comment by Dohtar1337** [comment]
CPU does not show temp in NHM

**Comment by Kick4U2** [comment]
Why is this closed?  It still is an issue.
