### ISSUE TITLE
Nicehash local error - can't run rig

### ISSUE THREAD

**Issue by RykNasty** [nicehash/NiceHashMiner#2303]
Hello, 
I am having trouble running my rig on Nicehash. It looks like it is recognizing my GPU and CPU but just says "Error Occurred - Please Inspect Locally." 
![Screenshot (12)](https://user-images.githubusercontent.com/78063552/105939138-d049a880-6015-11eb-90ca-584a18378f53.png)

The application also opens up however it doesn't load the rig either.
![Screenshot (13)](https://user-images.githubusercontent.com/78063552/105939204-f53e1b80-6015-11eb-813f-905e9059cc21.png)

Here is a screenshot of the program as well.
![Screenshot (14)](https://user-images.githubusercontent.com/78063552/105939262-19016180-6016-11eb-8286-31e791496d26.png)

I allowed the downloads and made them exceptions with my anti-virus software. Any help would be appreciated, thanks.

**Comment by BIitzkrieg** [comment]
you update to windows 20H2? I started having the same error after updating the other day. nothing useful in the nicehash log output.

**Comment by RykNasty** [comment]
I did update to 2OH2.

**Comment by Fusseldieb** [comment]
Yep, a friend of mine also upgraded to 20H2 and all benchmarks do fail. The CMD that should pop up doesn't anymore. 

On my rig (2004) it still works...
