### ISSUE TITLE
Could Power Mode be set during mining only?

### ISSUE THREAD

**Issue by mercurycc** [nicehash/NiceHashMiner#2306]
I use all the PCs at home for idle mining. When mining starts the GPU fans will spin up like crazy and the noise is way too high.

The power mode setting available on the web interface is a really nice capability for me to still get a decent return while reducing the noise level.

However, the power setting is applied all the time, even when the system isn't mining. That slows down everything else that uses the GPU unnecessarily.

While you could argue I could just switch the power mode back manually, it is inconvenient. It is especially problematic when I want to apply power mode to a PC of someone else in the household since they won't tell me when they need the PC.

So it would be nice if the power mode setting is only applied during mining, and revert back to 100% when mining pauses, especially for idle mining.

**Comment by Dohtar1337** [comment]
Wont fix/include. This feature or bug might already be fixed or added. Or might not be included due to internal reasons.
