### ISSUE TITLE
Benchmark fails on Asus Radeon RX 6800 XT LC

### ISSUE THREAD

**Issue by BodyDub** [nicehash/NiceHashMiner#2309]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by BodyDub** [comment]
Only three algorithms out of 18 work. You cannot mine Ether! Please correct. The algorithms themselves cannot identify the video card.
https://i.imgur.com/hg9aU2g.jpg

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/5909373/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/5909375/log.txt)

NiceHash 3.0.5.6
CPU:           AMD Ryzen 7 3800X (Matisse, MTS-B0)
               3900 MHz (39.00x100.0) @ 4042 MHz (40.50x99.8)
Motherboard:   ASUS ROG STRIX X570-E GAMING
BIOS:          3402, 01/13/2021
Chipset:       AMD X570 (Bixby)
Memory:        16384 MBytes @ 1996 MHz, 20-19-19-39
               - 8192 MB PC17000 DDR4 SDRAM - Patriot Memory (PDP Systems) 4000 C19 Series
               - 8192 MB PC17000 DDR4 SDRAM - Patriot Memory (PDP Systems) 4000 C19 Series
Graphics:      ASUS ROG STRIX LC RX 6800 XT GAMING OC
               AMD Radeon RX 6800 XT, 16384 MB GDDR6 SDRAM
Drive:         XPG GAMMIX S11 Pro, 2000.4 GB, NVMe
OS:            Microsoft Windows 10 Professional (x64) Build 19042.746 (20H2)

**Comment by Dohtar1337** [comment]
This issue is related to the GPU drivers or unsupported miners.
