### ISSUE TITLE
API setup

### ISSUE THREAD

**Issue by acamurez** [nicehash/NiceHashMiner#231]
Hi , i have searched all over the NL folders to change my API adress from default to my machine adress , i would like to port foward it and able it to open the miner state with my mobile data or other network . I noticed i can only change the port in general . How do i make this work? I learned , i need to change the default ewbf api from 127.0.0.1:4000 to my machine ip adress XXX.XXX.X.XXX:4000 , then port foward it  in my router , after that i will be able to open the miner state from anywhere.. note: I only use one algorithm which is equihash(ewbf)

**Comment by Olegik-ah** [comment]
Hi! I think its not possible using NHML. But you can use only miner (ewbf) with config/bat...

**Comment by DillonN** [comment]
NHML binds to localhost for security reasons, at the moment the only way to monitor hashrates is through the web stats page (clicik "Check my stats online!")
