### ISSUE TITLE
All Benchmarks Failed RTX2060

### ISSUE THREAD

**Issue by lpasoft** [nicehash/NiceHashMiner#2314]
I have followed the instructions to add the exceptions in windows defender and firewall (I have even tried disabling both completely), but all benchmarks always fail.

I have tried benchmarks with gpu (RTX2060) and CPU (4800H) and all benchmarks fail.

I have updated all the plugins and tried running the benchmarks 1 by 1 or all at once, but the result is always the same.

NicehashMiner version: v3.0.6.0 (I tried with v3.0.5.6 also)
OS: Windows 10 Pro 20H2
AMD Ryzen 7 4800H with Radeon Graphics  2.90 GHz
16GB Ram
Nvidia RTX 2060 (Laptop)
Nvidia drivers version: 461.40

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/5928212/log.1.txt)

**Comment by BIitzkrieg** [comment]
I believe it may be a 20H2 issue, I started having the same problems once I upgraded.

**Comment by Dohtar1337** [comment]
Please try this https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
