### ISSUE TITLE
Nice Hash crashing

### ISSUE THREAD

**Issue by noobminer346** [nicehash/NiceHashMiner#2316]
I am currently mining on a pc with a 2080 super, and it is running the latest drivers (461.4) which I have removed and reinstalled, and NiceHash will open and mine for up to Id say a minute, then crash immediately. It starts with Nicehash itself then the miner closes after a couple of seconds. I have tried releases (3.0.5.5)(3.0.5.6)(3.0.6.0) and they have all done the same thing. I downloaded them with my antivirus turned off so I have no I idea what the issue is, I was running Kryptex just fine for about 7 hours. I have done everything I can think of.

OS: Windows 10 Home
Intel I9-10850k @5.0ghz
32GB Ram
Nvidia RTX 2080s
Nvidia drivers version: 461.40

**Comment by S74nk0** [comment]
Please provide logs. You can upload the files here int this thread.
Or if you can Event logs to see the stack trace.

**Comment by MrSmore** [comment]
I've experienced this same issue. I've been trying to figure out the cause for weeks now.
I've reinstalled nice hash, windows fresh installed, drivers updated, .net and c++ updated.
I ran it with all settings on/off, antivirus on and off installed with everything off/on, and Nice hash will crash instantly or last a few minutes but always crashes.
I want to use this, but man, it's been a real pain in the butt.
How would I go about getting the logs? I have submitted a ticket and have been trying to get this fixed but with no luck and also I'm not receiving errors when it crashes, it just closes out.

**Comment by Pasquk2** [comment]
The problem I found is if "auto update installed plugin" is selected. Just try to unselect and try again.
This problem occurs to me in my rig with Asus b250 mining expert board with intel processor. While in the other rig with AMD processor don't have any problems with this option "on".

**Comment by MrSmore** [comment]
> The problem I found is if "auto-update installed plugin" is selected. Just try to unselect and try again.
> This problem occurs to me in my rig with Asus b250 mining expert board with intel processor. While in the other rig with AMD processor don't have any problems with this option "on."

It still crashes on me, Heck it crashes and then leaves a mining window still active.

**Comment by Pasquk2** [comment]
This is my nicehash app settings.
I've tried to change language to english, but doesn't take effect at all. Sorry.
Don't hide and don't minimize options.

![Captura de pantalla 2021-02-09 095001](https://user-images.githubusercontent.com/11651504/107338995-74bef680-6abc-11eb-8d63-ece0761ee618.png)

**Comment by Brickson95** [comment]
Same issue here and I've tried everything that I've found... if anyone finds anything please let us know! I can upload logs later if it helps.

**Comment by MrSmore** [comment]
For the most part, I got mine working. It does still crash at times but not as bad.
I currently use webroot, Malwarebytes and turn off some features. I kept scanning until I allowed all the correct files through for it to work.
Try running it without any security programs on and see if it crashes. If it doesn't, turn them back on and slowly turn off some features until the crashing stops.

**Comment by Brickson95** [comment]
I use Webroot as well and the problem persists even if i turn it completely off... Idk what else to do so at this point I am looking into other miners.

**Comment by Brickson95** [comment]
it's GUI, then miner... I could even record it happening if it helps.

**Comment by MrSmore** [comment]
Yeah, I also had that same issue with it crashing with webroot & Malwarebytes off. Actually, My miner is starting to crash again as well at times.
You might have already done so, but.
GPU drivers up to date.

Under Webroot Try These
Have webroot keep scanning and allow any files it detects regarding NiceHash.
Scan Settings: Uncheck Detect Potentially Unwanted Applications.
Shield: Block threats automatically if no user is logged in.
Firewall: I turned off my browser extension & set it to Allow all processes to connect to the internet unless explicitly blocked.

Try these.

**Comment by Brickson95** [comment]
This helped a bit. now it runs for about 30 minutes before crashing. I'll just have to keep tweaking settings I guess... I really appreciate your help!

**Comment by Brickson95** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/6361865/log.txt)
here's the log if that helps at all.
