### ISSUE TITLE
Loginbrowser hangs, unable to login 

### ISSUE THREAD

**Issue by xantari** [nicehash/NiceHashMiner#2318]
Unable to login on one miner rig. Loginbrowser form just hangs.

how to login? 

Logs not indicating anything helpful....

**Comment by ghost** [comment]
I'm having the same issue due to reinstalling the application.

**Comment by sandeep2601** [comment]
When I updated the app, it installed correctly, but it hangs on the Login Browser(attached the screenshot below).

![login browser hangs](https://user-images.githubusercontent.com/34654040/107187884-b55f3700-6a0c-11eb-9d0b-e02ff53a430c.PNG)

**Comment by diederikus** [comment]
i have the same problem, and after several starts i don't even get the loginbrowser  screen anymore.

**Comment by casing123** [comment]
Im having the same problem. does anyone know whats going on?

**Comment by luxabc** [comment]
I'm having exactly the same issue... someone look into this please...

**Comment by xantari** [comment]
Have more details on why it's crashing. It appears this program uses the integrated windows .net web viewer control. And it's crashing.

Faulting application name: wwahost.exe, version: 10.0.19041.789, time stamp: 0x9bbd7506
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
Exception code: 0xc0000409
Fault offset: 0x000000000010bd5c
Faulting process id: 0x8f0
Faulting application start time: 0x01d7075370737ee1
Faulting application path: C:\Windows\System32\wwahost.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4a2e4b18-4230-40f5-ad24-95355e989e25
Faulting package full name: Microsoft.Win32WebViewHost_10.0.19041.423_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: DPI.SystemAware

Fault bucket 1979378660451409038, type 5
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.Win32WebViewHost_10.0.19041.423_neutral_neutral_cw5n1h2txyewy
P2: praid:DPI.SystemAware
P3: 10.0.19041.789
P4: 9bbd7506
P5: KERNELBASE.dll
P6: 10.0.19041.804
P7: 0e9c5eae
P8: 000000000010bd5c
P9: c0000409
P10: 0000000000000007

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2223.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2281.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2292.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER22A0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER22C0.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Win32W_b9a9e99a283ebb0ff0a34fd72722ee150c437_bf8e90fe_d9cba746-7b9b-4451-88cf-de7c9f885f70

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4a2e4b18-4230-40f5-ad24-95355e989e25
Report Status: 268435456
Hashed bucket: 54c1d56c471d8d9c7b782a678c31dc8e
Cab Guid: 0

**Comment by xantari** [comment]
Related issue details: https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/32

And here: https://stackoverflow.com/questions/51854862/wpf-c-sharp-webview-doesnt-show-any-page-on-win-10
