### ISSUE TITLE
core no compatible devices found

### ISSUE THREAD

**Issue by DEPSTRCZ** [nicehash/NiceHashMiner#2319]
Autodetect detected my gpu only..
I have intel i3 8100
And Geforce Gtx 1650super
And only 3days old drivers.
But aplication said core / no compatible devidces found

**Comment by WangShuo-DaHeng** [comment]
My device is GTX1650
Meet the same problem.
No matter how many times I tried it always said that "no compatible devidces found"

**Comment by sangaman** [comment]
Same problem here. GeForce GTX 1650 Super. Both with old drivers and with the newest 461.72 game ready drivers I get `core | no compatible devices found` and no GPU mining. I even tried using the DDU tool to do a clean uninstall of the drivers and then reinstall the latest according to instructions I found from nicehash, but it didn't help.

**Comment by sangaman** [comment]
Apparently QuickMiner doesn't support cards with less than 4 GB VRAM: https://www.reddit.com/r/NiceHash/comments/lsrjey/troubleshooting_geforce_gtx_1650_super_not/got45b6?utm_source=share&utm_medium=web2x&context=3

**Comment by Snazzie** [comment]
980ti here same issue

**Comment by Arson199** [comment]
1050 Ti too

**Comment by GODDINOANSH** [comment]
1060
too

**Comment by akinncar** [comment]
1050 TI same

but 2 months ago I achieved ran quick miner on my machine, this issue is after re-install.

**Comment by pentel** [comment]
1050 TI is not supported. 
https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware

need more than 6GB of vram.
https://github.com/nicehash/NiceHashQuickMiner/wiki

**Comment by HFAsif** [comment]
may be the problem in windows defender security is so powerfull in newer build u can not of windows defender ,  as i know windows build 10500 can run it on gtx 1650 , please someone try it and let me know if it works , i can sure it will works

**Comment by PKryptoZ** [comment]
Not using Windows Defender and still dont recognize the GPU - GTX 1650
