### ISSUE TITLE
Add Worker name when mouse-over in taskbar

### ISSUE THREAD

**Issue by johanrydstrom** [nicehash/NiceHashMiner#2321]
As a NiceHash User running multiple instances of NiceHash
When hovering the NiceHash icon in Windows Tray
I would like to be able to identify which worker the Tray icon is connected to.

Current behavoiur:
- NiceHash Miner
![image](https://user-images.githubusercontent.com/1448669/107370259-06d9f580-6ae3-11eb-982f-3412ca97fe4f.png)

Suggested behaviour:
- NiceHash Miner: `<Worker name>`

**Comment by Dohtar1337** [comment]
Moved to idea backlog. Closing to clean the issues.
