### ISSUE TITLE
Ethlargment Urls points to github page that is no longer available --> Unable to Enable as a result

### ISSUE THREAD

**Issue by Briteguy** [nicehash/NiceHashMiner#2323]
When enabling this feature, the file is unable to be downloaded and thus the program states that the files are missing. I found the url it is fetching from and this no longer exists. Is there an update?

{
  "use_user_settings": false,
  "bin_version": null,
  "bin_path": null,
  "bins_urls": [
    "https://github.com/nicehash/NiceHashMinerTest/releases/download/1.9.1.5/Ethlargement.7z"
  ],
  "bins_package_pwd": null
}

**Comment by bantman33** [comment]
Experiencing same issue. Downloaded NiceHash start of January, no longer updating ethenlargment pill no matter what people do. 

Have videos of me cranking 50MH with my 1080ti yesterday. Big facepalm on reinstall. Please fix ASAP.

**Comment by S74nk0** [comment]
please use the latest pre-release:

https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.6.1
