### ISSUE TITLE
There are missing files from last Miners Initialization...error! How to stop it appear?

### ISSUE THREAD

**Issue by JamesDeen74** [nicehash/NiceHashMiner#233]
Hi, folks!

Please help.

I have three separate machines running three cards (390, 390x, 1070), with Windows 7/10 on them.

The one  with 1070 starts NH 1.8.1.1 with no problem at all. No errors, so I just press Start and it goes mining.

Comp's with 390/390x on board cant start NH with no errors. Always there is: "There are missing files from last Miners Initialization..." press Yes or No to reinstall Miner, and when I press No, there is another "Harware change detected..." with Yes or No to start miner. I tried to manually download and put all the files to NH directory, tried to allow NH to automatically install what he wanted. But when I allow auto update NH freezes at 99.96% with no luck to proceed. I have to terminate it manually.

What's wrong and what can I do to solve this errors and why they appear only on this machines?

**Comment by adem4ik** [comment]
I've got similar case when I have updated older version of NHML by overwritting it with newer bins. The only thing that helped me is fresh download and isntall.

Also there might be corrupted files on your HDD/SDD. So you can try to perform Windows' "System file check".

**Comment by JamesDeen74** [comment]
You're right! It helped! No annoying errors anymore! Thanks!)
