### ISSUE TITLE
Updating miners manualy?

### ISSUE THREAD

**Issue by bovcan** [nicehash/NiceHashMiner#2332]
Can we update 3rd party miners manualy?
For example on 3.0.6.0 there is Srbminer v 0.6.0 but there is already version 0.6.6

**Comment by alexjn1984** [comment]
I've been having trouble installing SRBMiner, it downloads 6 but fails to install fully.  Tried the manual plugin instructions but still could not get 6.6 working.

**Comment by a4jp-com** [comment]
I can't see SRBMiner in the list here.

**Comment by a4jp-com** [comment]
I can see it now after a reinstall but the update button doesn't work...

**Comment by bovcan** [comment]
srbminer is in plugin section, you have to DL it by yourself but it is 0.6.0 version.
I downloaded 0.6.6 version and I extract it to 0.6.0 folder. It is working w/o issue.
