### ISSUE TITLE
MX250

### ISSUE THREAD

**Issue by Water-blue7** [nicehash/NiceHashMiner#2338]
![image](https://user-images.githubusercontent.com/60252035/108582570-2852a100-736f-11eb-9ea3-9904fdaa4831.png)
Is it because my graphics card is too low-level, so I can't mine?

**Comment by krgouveia** [comment]
I'm having the same error, my graphics card is a GeForce MX150.

**Comment by Dohtar1337** [comment]
These GPUs are not supported
