### ISSUE TITLE
GTX 980ti: core: no compatible devices found

### ISSUE THREAD

**Issue by HerzogVonWiesel** [nicehash/NiceHashMiner#2340]
Hi there, I have updated my drivers, disabled the optimization in the Nvidia Control Panel as stated in the doc but the error still shows up at startup, what can I do?
Thank you in advance!

**Comment by felipegmotta** [comment]
I'm having the same problem with a 2060.

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/benchmark-error-in-nicehash-miner
