### ISSUE TITLE
Nicehash site error - can't open in site rig

### ISSUE THREAD

**Issue by Guima001** [nicehash/NiceHashMiner#2347]
Hello I started using nicehash but I started showing the error of the messages below about not finding and rig, when trying to add it again it asks you to reinstall the program and it's done but the problem continues even with the program reinstalled, and I can't add my equipment, it has an option called clean installation plus my fear and that I lose what I have done so far what should I do?

![rig](https://user-images.githubusercontent.com/33711230/109520902-76605680-7a8b-11eb-8844-3239e214002e.PNG)
![site](https://user-images.githubusercontent.com/33711230/109520908-78c2b080-7a8b-11eb-9f2a-e0ad1bfc90d2.png)

**Comment by Dohtar1337** [comment]
Make sure that you are using the same BTC address as for your NH account
