### ISSUE TITLE
NiceHash No Longer Benchmarks or Mines after "Maintenance"

### ISSUE THREAD

**Issue by ddelella** [nicehash/NiceHashMiner#2349]
Issue:
After the most recent "maintenance" I attempted to bring a new mining rig online.  Only a few (3/24) benchmarks completed without errors.  All these were working before the "maintenance".  I tried disabling all cards and benchmarking one at a time.  Same results.  I also tried on my desktop which has a 1060 3GB GPU and got similar results.  The only benchmarks which seem to pass are ones which measure in Sol/s.  

OS: Windows 10 64-bit (19042.746)
NiceHash Miner: 3.0.5.6
Plugin: All, latest as of 3/1/2021
Processor: Intel Celeron G3930
HDD: 128GB SSD
RAM: 8GB Corsair Vengence
Motherboard: B250 Mining Expert
GPU:
1. NVIDIA RTX 2060
2. NVIDIA RTX 2060 Super
3. NVIDIA RTX 3060ti
4. NVIDIA RTX 3070

Included is the log for benchmarking attempt made on the RTX 3070.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/6065310/log.txt)

**Comment by suretma** [comment]
I've got the same issue today all day.

OS: Windows 10 64-bit (19042.746)
NiceHash Miner: 3.0.5.6
Plugin: All, latest as of 3/1/2021
Processor: AMD 5600X
HDD: 500GB SSD
RAM: 16GB GSkill Ripjaw 3200
Motherboard: Asrock B550
GPU: Radeon 6800
