### ISSUE TITLE
Suggestion: Add Neoscrypt mining by ccminer_tpruvot

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#235]
There is possibility to mine NeoScrypt using ccminer 2.2 by tpruvot. Tested it on my GTX 1060 GTX:
ccminer_tpruvot: **710** kH/s
NHML's ccminer: **496** kH/s
![image](https://user-images.githubusercontent.com/4707112/29743102-e4ceee1c-8a9b-11e7-9b97-c3615e0b374e.png)
![image](https://user-images.githubusercontent.com/4707112/29743089-a23bbe40-8a9b-11e7-8ab9-d12c89ff4cb8.png)

That's noticeable performance difference, so it would be really great if you could enable Neoscypt mining by ccminer_tpruvot.

**Comment by DillonN** [comment]
Thanks for posting, I'll look into this

**Comment by DillonN** [comment]
Should be in as of commit fe387b81727c6a85400e3a06f5b4b97217d10656. I changed the path for Maxwell cards too so if anyone has a 900 series and finds it gives lower hashrates please leave a comment. Otherwise should be in the next release

**Comment by propergol** [comment]
a question : are you only adding tpruvot's NeoScrypt?
I ask because his Cryptonight algo (Monero) is working pretty well on my GTX1060s with more than 550H/s and for some reasons use less power than most of other algos for other coins.

**Comment by adem4ik** [comment]
afaik CryptoNight via ccminer_tpruvot is already implemented in https://github.com/nicehash/NiceHashMinerLegacy/commit/39c0804093f5fd909f667630f30415a731f031d9 after discussion in https://github.com/nicehash/NiceHashMinerLegacy/issues/200 but the stable version with this change wasn't released yet

**Comment by propergol** [comment]
ah ok :D my bad :)

**Comment by luongk** [comment]
@DillonN Looks fine to me - on my 980 GTX the tpruvot fork yields ~690 kH/s vs ~650 kH/s for the current ccminer (less of a difference, but definitely not worse).

**Comment by RobertKoval** [comment]
Alexis78 better for neoscrypt. 1.2 Mh (1070 , OC undervolt).
