### ISSUE TITLE
Hi, Im new to hash miner

### ISSUE THREAD

**Issue by lucasgozzi** [nicehash/NiceHashMiner#2350]
Im having this problem:
 No compatible devices found!
![image](https://user-images.githubusercontent.com/25513169/109664005-7aec4400-7b4b-11eb-9bcb-ae3a8d3a6a25.png)

GEFORCE GTX 1060
![image](https://user-images.githubusercontent.com/25513169/109664420-df0f0800-7b4b-11eb-8f68-d6c70ceb2f3c.png)

Can someone help me troubleshoot?

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
