### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by DiabTD** [nicehash/NiceHashMiner#2351]
20210302 18:30:20 T-Rex NVIDIA GPU miner v0.19.11  -  [CUDA v11.10 | Windows]
20210302 18:30:20 r.9c70a63f2290
20210302 18:30:20
20210302 18:30:20 WARN: Can't load NVML library, dlopen(126): failed to load nvml.dll,dlopen(126): failed to load C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll
20210302 18:30:20 WARN: NVML error, code 12
20210302 18:30:20 WARN: Can't initialize NVML. GPU monitoring will be disabled.
20210302 18:30:20 NVIDIA Driver version N/A
20210302 18:30:20 CUDA devices available: 5
20210302 18:30:20
20210302 18:30:20 WARN: DevFee 1% (ethash)
20210302 18:30:20
20210302 18:30:20 URL : stratum2+tcp://stratum-dev.eu.nicehash.com:3353
20210302 18:30:20 USER: 39gXkzCYEpPXcC9FpUfJjhHeF7jEnJL6nN$0-kBtPzQbtCl6+coHvtW3+Vg
20210302 18:30:20 PASS:
20210302 18:30:20
20210302 18:30:20 WARN: NVML is disabled. You won't see GPUs stats.
20210302 18:30:20
20210302 18:30:20 WARN: Built-in watchdog has been disabled!
20210302 18:30:20 Starting on: stratum-dev.eu.nicehash.com:3353
20210302 18:30:20 ERROR: No connection, retry after 10 seconds
20210302 18:30:20 ApiServer: HTTP server started on 127.0.0.1:4003
20210302 18:30:20 ---------------------------------------------------
20210302 18:30:20 For control navigate to: http://127.0.0.1:4003/trex
20210302 18:30:20 ---------------------------------------------------
20210302 18:30:20 WARN: GPU #3(000600): GeForce GTX 1070, intensity set to 22
20210302 18:30:20 WARN: GPU #4(000200): GeForce GTX 1060 6GB, intensity set to 22
20210302 18:30:30 ERROR: No connection, retry after 10 seconds

 on NiceHASH
 
 PLEASE ANYHELP?

**Comment by elaske** [comment]
Well, I've experienced recently an NVML.dll issue as well. That specifically was most easily solved by unpacking your driver installer content again, going to C:\NVIDIA\International\<something that I can't remember>\nvml.dl_, `nvml.dl_` is the zipped version of the file. Extract it over to C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll and it will work again.

As far as the retry / connection issue I'm not sure.

**Comment by Dohtar1337** [comment]
You are connecting to Starting on: stratum-dev.eu.nicehash.com:3353, which is stratum for devs only, do not use it. Reinstall NHM
