### ISSUE TITLE
NHM 3.0.6.2 periodic freezes

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/NiceHashMiner#2352]
NHM 3.0.6.2 periodic freezes. 
the application interface is frozen. It can only be treated by deleting the task in the task manager and restarting it. The frequency of the error is once every 2-3 days

![image](https://user-images.githubusercontent.com/35364901/109779601-28785980-7c17-11eb-91b4-54e5db840ed5.png)

![image](https://user-images.githubusercontent.com/35364901/109780403-0a5f2900-7c18-11eb-8a8a-802fe24366f4.png)

logs : 
```
[2021-03-03 11:20:05] [INFO] [MiningManager] Mine always regardless of profit
[2021-03-03 11:20:05] [INFO] [MiningManager] PrevStateProfit 0.000307513672253786, CurrentProfit 0.000307513672253786
[2021-03-03 11:20:05] [INFO] [MiningManager] Will NOT switch profit diff is 0, current threshold 0.02
[2021-03-03 11:20:32] [ERROR] [CPUDIAG] System.InvalidOperationException: Не удается загрузить данные имени счетчика, поскольку в реестре обнаружен недопустимый индекс "".
   в System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   в System.Diagnostics.PerformanceCounterLib.get_NameTable()
   в System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   в System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   в System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   в System.Diagnostics.PerformanceCounter.InitializeImpl()
   в System.Diagnostics.PerformanceCounter.Initialize()
   в System.Diagnostics.PerformanceCounter.NextSample()
   в System.Diagnostics.PerformanceCounter.NextValue()
   в NHM.DeviceMonitoring.DeviceMonitorCPU.get_Load()
[2021-03-03 11:20:57] [INFO] [SwitchingManager] Normalizing profits
No algos affected (either no SMA update or no algos higher
```

**Comment by EvgeniyKorepov** [comment]
RESOLVE:
1. Run CMD as administrator
2. Run `C:\windows\system32\lodctr /r` or `C:\windows\SysWOW64\lodctr /r`

You should receive a message :
`Info: Successfully rebuilt performance counter setting from system backup store` (English)
or
`Сведения: Параметры счетчиков производительности заново созданы из системного хранилища архивов` (Russian)

**Comment by Unruly1212** [comment]
hello how are you

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
