### ISSUE TITLE
Phoenix miner source from mega.nz doesn't work

### ISSUE THREAD

**Issue by Paquito86** [nicehash/NiceHashMiner#2354]
I reinstalled Nicehash deleting all the data, and when trying to Benchmark Phoenix Miner, I got an error, after investigating a bit into the program I realised that the mega.nz link doesn't work, so Phoenix Miner cannot be downloaded.

I hope you can fix this soon.

**Comment by tangobravo5656** [comment]
I have the complete plugin I just dont know how to give it to u, google drive ?

**Comment by tangobravo5656** [comment]
I gotta the same issue as u, and I find the complete phoenix miner plugin on my other computer,I paste it in the folder ,and it worked!!

**Comment by tangobravo5656** [comment]
Now I have uploaded it,here u go
https://github.com/tangobravo5656/Phoenix-Miner-plugin-for-NicehashMiner

**Comment by Paquito86** [comment]
Just download it, put it on the Nicehash folder and it's working perfectly. Thank you very much!

**Comment by Paquito86** [comment]
@tangobravo5656 Nicehash has asked to stop using Phoenix Miner as they considered it unsafe. I analyzed the files you posted. Here you have the link: [Kaspersky Threat Intelligence Portal AC16869AC8546FDADE606E2BB9519C2A67208839A84F066CE209B49B02ABD0A9](https://opentip.kaspersky.com/AC16869AC8546FDADE606E2BB9519C2A67208839A84F066CE209B49B02ABD0A9/)
I consider Phoenix Miner safe to use as the analysis only detected miner related things.

Here you can read the Nicehash official post: [https://www.nicehash.com/blog/post/stop-using-phoenix-miner-immediately](https://www.nicehash.com/blog/post/stop-using-phoenix-miner-immediately)

If we keep using this 'safe' version and we don't change it, I think there's no risk.

**Comment by tangobravo5656** [comment]
I  kinda agree with u,but on second thoughts this plugin is not open source,so I  think maybe it's best if we take the advise.

**Comment by Paquito86** [comment]
For my GPU Phoenix Miner is the best. I get higher profits when using it and about 2-3 MH/s more (per GPU) compared to NBMiner. I'm not going to update anything so I think I'm safe. I take the risk.

**Comment by elaske** [comment]
@Paquito86 I tried dropping it in there and NiceHash decided to completely clear out the folder of all things Phoenix, it's odd. 

@nicehashdev should probably switch from the Mega links to their official sources: https://github.com/PhoenixMinerDevTeam/PhoenixMiner/releases/

The mudslinging going between the two parties seems to imply they won't though: https://bitcointalk.org/index.php?action=profile;u=1522040;sa=showPosts;start=0

**Comment by Paquito86** [comment]
@elaske Until this gets resolved I'm going to use an old version of PhoenixMiner to keep my computer safe.
