### ISSUE TITLE
Update or Install in Plugins not working, even after full reinstall.

### ISSUE THREAD

**Issue by a4jp-com** [nicehash/NiceHashMiner#2359]
Update or Install in Plugins not working, even after full reinstall.
Windows 10
NiceHash Miner Version: 3.0.6.2

Any idea on how to get the install buttons to work?

**Comment by Dohtar1337** [comment]
Most likely issue related to antivirus https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion
