### ISSUE TITLE
Need new/updated alt coins(other than eth) miners fast... :-)

### ISSUE THREAD

**Issue by lmlim** [nicehash/NiceHashMiner#236]
Hi Dillon,

In the event of falling eth prices into the abyss, we will need new/updated alt coins miners(GPU/CPU) asap. :-)

adem4ik had a couple of suggested miners to add on the other posts. thanks to him.

Hopefully you can make this as a priority.
Thanks.

Cheers ;-)

**Comment by DillonN** [comment]
Yes the others are being looked at, I'll close this though since there are issues for those already open
