### ISSUE TITLE
Error on XMRig

### ISSUE THREAD

**Issue by eduardokenj** [nicehash/NiceHashMiner#2360]
I got that error on my miner (and yes i put the adress and the user correct as generate in stratum generator): 
![image](https://user-images.githubusercontent.com/7385867/111016586-95b18a80-838d-11eb-9b51-9082ebf8eee3.png)
And in NH Miner v3.0.5.6 i got this error:
![image](https://user-images.githubusercontent.com/7385867/111016616-be398480-838d-11eb-90c0-fe0896d11119.png)

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/benchmark-error-in-nicehash-miner

Make sure that defender did not delete the miner https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion
