### ISSUE TITLE
XMrig 6.8.1 **trojan**

### ISSUE THREAD

**Issue by u67890678** [nicehash/NiceHashMiner#2363]
![Screenshot 2021-03-14 003208](https://user-images.githubusercontent.com/80322852/111060997-ca891480-8455-11eb-8ce1-2cc16b3b55c4.png)

**Comment by Dohtar1337** [comment]
This was a known issue where the defender deleted XMRig files https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion
