### ISSUE TITLE
NiceHash Not Detecting GPU

### ISSUE THREAD

**Issue by jodeysalazar** [nicehash/NiceHashMiner#2365]
Nicehash seems unable to detect my GPU. I get the "No Cuda Device Found" error on every miner I've tried. I have a GTX 1080 running Win 10, have downloaded CUDA 9,10 & 11, changed suggested BIOS settings and even tried rolling back to previous versions of Nvidia drivers going back 2 years, it just won't recognize my GPU. It shows up just fine in Device manager but nothing works. I've attached the devicedetection.bat logs. Thanks in advance.

Bug ReportID: 
ef8433ce-5c4b-4f69-b998-6fa7ec550389

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/6139609/log.1.txt)

**Comment by Dohtar1337** [comment]
Please follow this guide https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
