### ISSUE TITLE
980 Ti Benchmark failing

### ISSUE THREAD

**Issue by rebyul** [nicehash/NiceHashMiner#2367]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given
[log.txt](https://github.com/nicehash/NiceHashMiner/files/6148695/log.txt)

The benchmark is erroring with v3.0.6.2 and stable v3.0.5.6.
Antivirus has been turned off the the installed folder marked for exclusion.
Anything you'd like me to try?

**Comment by Pugan667** [comment]
same issue here for the 980 FE, even not being detected with Nvidia QuickMiner. Already updated to the latest drivers using GeForce Experience.

**Comment by anazz20** [comment]
> same issue here for the 980 FE, even not being detected with Nvidia QuickMiner. Already updated to the latest drivers using GeForce Experience.

From the Nicehash blog post:
NiceHash QuickMiner only works on Windows 10 x64 (any edition) with NVIDIA graphic cards that are at least GeForce series 1000 with a minimum of 6 GB of VRAM.

**Comment by Pugan667** [comment]
> > same issue here for the 980 FE, even not being detected with Nvidia QuickMiner. Already updated to the latest drivers using GeForce Experience.
> 
> From the Nicehash blog post:
> NiceHash QuickMiner only works on Windows 10 x64 (any edition) with NVIDIA graphic cards that are at least GeForce series 1000 with a minimum of 6 GB of VRAM.

that explains why it wasn't being detected using QuickMiner, thanks! But still couldn't figure out why benchmarking is failing in normal NiceHash Miner :(

EDIT: It was the default algorithm chosen which was DaggerHashimoto, you can install others from the plugins menu :)
