### ISSUE TITLE
v1.8.1.1 Does not support Nvidia Driver 385.41

### ISSUE THREAD

**Issue by Simmons572** [nicehash/NiceHashMiner#237]
I will attach a photo.

I have reinstalled the driver several times, and the issue still persists.

![image](https://user-images.githubusercontent.com/15789121/29747284-e9e4df5c-8ac2-11e7-8702-c28138b70f54.png)

**Comment by streaml1ne555** [comment]
Probably a bug, but did you try DDU to uninstall your existing driver before reinstalling the latest one?

**Comment by niknewb** [comment]
It does support 385.41. I'm running 2x 1080ti with this driver for almost a week already

**Comment by DmitryDMR** [comment]
...and I'm running on win 7 and win 10 too

**Comment by Simmons572** [comment]
Interesting. I will try running DDU again..

**Comment by DillonN** [comment]
This warning can appear if NHML cannot access CUDA interface properly. Do you have "Optimize compute performance" turned on in the NV control panel?

**Comment by Simmons572** [comment]
It appears I had to do a safemode uninstall of the driver using DDU.  Thanks for the assistance everyone, it appears to be functioning properly now.

**Comment by DillonN** [comment]
Glad it's working @Simmons572 I'll close this now.
