### ISSUE TITLE
Continious switching DAG epochs

### ISSUE THREAD

**Issue by SilentWarrior1** [nicehash/NiceHashMiner#2371]
Greetings. 
Using latest stable NM version. Mining eth with Phoenix miner (yes, the official 5.5с with equal hash checksums)
And often get epoch switch from actual ETH to epoch 0. (Some other ppl told me that this is ZIL mining.
This could be several times for an hour, and re-creating DAG for actual eth epoch bothers me a lot.
Is there a way to stop switching for mining ZIL? (or whatever this is)
![notepad++_StJ7HpqrNm](https://user-images.githubusercontent.com/18610520/111680207-456d7900-8822-11eb-9927-626bb54aa273.png)

**Comment by SilentWarrior1** [comment]
any... suggestions?

**Comment by bovcan** [comment]
I saw this happeneing to me on srbminer too.  I reboot the nhm and it was fine.

**Comment by SilentWarrior1** [comment]
> I reboot the nhm

this doesn't help at all. Btw, i tried to use .bat file instead of NHM software and switching epochs (or dual mining or whatever this is) occurs as it was with using NHM software.
tried to switch to MoreEpochs mod v1.9 for [Claymore ETH miner 15] (it has topic on bitcointalk.org) and... the same situation.
