### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by khor0** [nicehash/NiceHashMiner#2372]
Hi,

I'm looking forward to implement some sort of program to send managed rig reports to check NiceHash's website and Mobile App.

Is it documented and free to use? I think I found something [arround here](https://github.com/nicehash/NiceHashMiner/blob/41ef03f90087bd389ba4d04ebf2837337f29b99f/src/NHMCore/Nhmws/NHWebSocket.cs#L25). 

Unfortunately, I've never messed around with this kind of RPC, but i'd like to help with this integration with regular Linux distribuitions.

EDIT: And are we allowed (due to licensing) to implement something around this RPC?

**Comment by alkaris2** [comment]
There is the NHOS but I don't know what the OS is trying to offer with the software that already exists.

Is the Linux OS running the Windows EXE distribute? Or is it running its own native application? This is what's not clear on Nice Hash's site or their Support Pages.

If NiceHash OS is providing it's own native linux application, why isn't it available separately like the Windows EXE distribute or telling us what software they're using? I need to know what the NHOS provides that the single stand-alone application does or doesn't have.

**Comment by khor0** [comment]
> There is the NHOS but I don't know what the OS is trying to offer with the software that already exists.
> 
> Is the Linux OS running the Windows EXE distribute? Or is it running its own native application? This is what's not clear on Nice Hash's site or their Support Pages.
> 
> If NiceHash OS is providing it's own native linux application, why isn't it available separately like the Windows EXE distribute or telling us what software they're using? I need to know what the NHOS provides that the single stand-alone application does or doesn't have.

Nice point you made there. Probably it's closed source, that's why there's no repository available. Still, this doesn't mean that we can't reverse-engineer this repo's RPC to use in Linux. That's what my issue is mainly about.
