### ISSUE TITLE
Ethpill support for P104-100

### ISSUE THREAD

**Issue by jperrela** [nicehash/NiceHashMiner#2373]
Could you enable ethpill for P104-100 cards?

**Comment by S74nk0** [comment]
@jperrela you can add support for these GPUs manually by editing the `\miner_plugins\Ethlargement\internals\EthlargementSettings.json`.

change it to:
```
{
  "use_user_settings": true,
  "supported_device_names": [
    "1080",
    "1080 Ti",
    "Titan Xp",
    "TITAN Xp",
    "P104",
    "P100"
  ],
  "supported_algorithms": [
    20
  ],
  "ignore_miner_uuids": []
}
```
This will add support but I don't think it will increase mining performance.  Let me know if it does
