### ISSUE TITLE
Nicehash miner plugin Ethlargement not install

### ISSUE THREAD

**Issue by f00x** [nicehash/NiceHashMiner#2381]
I have already used [instruction](https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion?lang=ru)
However, this does not save me seeing an error in the log every time I run
Programs\NiceHash Miner\miner_plugins\Ethlargement\bins\11.1\miner_bins.7z 
0 byte
### logs
```
[2021-03-24 18:04:14] [INFO] [NICEHASH] nvidiasetp0state returned error code: 1
[2021-03-24 18:04:14] [INFO] [MinerPluginsManager] Downloading missing files for Ethlargement-Ethlargement
[2021-03-24 18:04:15] [ERROR] [MinerPluginsManager] Installation of Ethlargement failed: $Удаленный сервер возвратил 
ошибку: (404) Не найден.
```
 ### \NiceHash Miner\miner_plugins\Ethlargement\internals\MinersBinsUrlsSettings.json
```
{
  "use_user_settings": false,
  "bin_version": null,
  "bin_path": null,
  "bins_urls": [
    "https://github.com/nicehash/NiceHashMinerTest/releases/download/1.9.1.5/Ethlargement.7z"
  ],
  "bins_package_pwd": null
}
```

**Comment by S74nk0** [comment]
please use this [version ](https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.6.3)
