### ISSUE TITLE
помогите решить проблему.. захотел начать майнить у меня 1050 ti но почему то выдает такую ошибку

### ISSUE THREAD

**Issue by zahar12342** [nicehash/NiceHashMiner#2382]
помогите решить проблему.. захотел начать майнить у меня 1050 ti но почему то выдает такую ошибку.. после все начинается заново

![8rex9tBWxuU](https://user-images.githubusercontent.com/81379000/112607224-0777e280-8e2a-11eb-8ddc-c5952be34751.jpg)

2021.03.25:18:27:34.848: main Phoenix Miner 5.5c Windows/msvc - Release build
2021.03.25:18:27:34.848: main Cmd line: -pool ssl://eu1.ethermine.org:5555 -pool2 ssl://us1.ethermine.org:5555 -wal 0x9721d0645913ff71Ee1f2bF3db3574c6D6748BCD.mypc 
2021.03.25:18:27:35.053: main CUDA version: 11.0, CUDA runtime: 8.0
2021.03.25:18:27:35.073: main No OpenCL platforms found
2021.03.25:18:27:35.073: main Available GPUs for mining:
2021.03.25:18:27:35.074: main GPU1: GeForce GTX 1050 Ti (pcie 6), CUDA cap. 6.1, 4 GB VRAM, 6 CUs
2021.03.25:18:27:35.154: main NVML library initialized
2021.03.25:18:27:35.187: main Nvidia driver version: 457.51
2021.03.25:18:27:35.759: main Eth: the pool list contains 2 pools (2 from command-line)
2021.03.25:18:27:35.759: main Eth: primary pool: ssl://eu1.ethermine.org:5555
2021.03.25:18:27:35.760: main Starting GPU mining
2021.03.25:18:27:35.911: wdog Starting watchdog thread
2021.03.25:18:27:36.248: main Eth: Connecting to ethash pool ssl://eu1.ethermine.org:5555 (proto: EthProxy)
2021.03.25:18:27:36.249: main GPU1: 29C 45% 37W
GPUs power: 36.7 W
2021.03.25:18:27:36.493: main Listening for CDM remote manager at port 3333 in read-only mode
2021.03.25:18:27:36.574: eths Eth: Connected to SSL ethash pool eu1.ethermine.org:5555 (172.65.207.106)
2021.03.25:18:27:36.964: eths Eth: Send: {"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x9721d0645913ff71Ee1f2bF3db3574c6D6748BCD.mypc"]}

2021.03.25:18:27:37.127: eths Eth: Received: {"id":1,"jsonrpc":"2.0","result":true}
2021.03.25:18:27:37.127: eths Eth: Send: {"id":5,"jsonrpc":"2.0","method":"eth_getWork","params":[]}

2021.03.25:18:27:37.290: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0xbd81554fc09f07cf8024451b32093299ce64b5be5f366a5d99909431b2a5411f","0x3ba1ec7dd7e5aad3c65bafbe04baad8cc72d5157dbce5701db30c476f182011f","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xb8c45f"]}
2021.03.25:18:27:37.290: eths Eth: New job #bd81554f from ssl://eu1.ethermine.org:5555; diff: 4000MH
2021.03.25:18:27:37.292: GPU1 GPU1: Starting up... (0)
2021.03.25:18:27:37.292: GPU1 GPU1: Generating ethash light cache for epoch #403
2021.03.25:18:27:40.215: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x41d7cb3975d158c6ff27a448aaa01466ef5e430b547711629e803e0b0c5bbf36","0x3ba1ec7dd7e5aad3c65bafbe04baad8cc72d5157dbce5701db30c476f182011f","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xb8c45f"]}
2021.03.25:18:27:40.215: eths Eth: New job #41d7cb39 from ssl://eu1.ethermine.org:5555; diff: 4000MH
2021.03.25:18:27:41.136: GPU1 Light cache generated in 3.8 s (17.3 MB/s)
2021.03.25:18:27:41.437: main Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
2021.03.25:18:27:41.463: GPU1 GPU1: Allocating DAG (4.16) GB; good for epoch up to #405
2021.03.25:18:27:41.465: GPU1 CUDA error in CudaProgram.cu:388 : out of memory (2)
2021.03.25:18:27:41.465: GPU1 GPU1: CUDA memory: 4.00 GB total, 3.30 GB free
2021.03.25:18:27:41.465: GPU1 GPU1 initMiner error: out of memory
2021.03.25:18:27:41.465: wdog Fatal error detected. Restarting.
2021.03.25:18:27:44.224: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x9e027f4e1d4d019c814c17cfc06ba74d0cabed295efcbaf2d429379cd359622d","0x3ba1ec7dd7e5aad3c65bafbe04baad8cc72d5157dbce5701db30c476f182011f","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xb8c45f"]}
2021.03.25:18:27:44.224: eths Eth: New job #9e027f4e from ssl://eu1.ethermine.org:5555; diff: 4000MH
2021.03.25:18:27:46.601: main Eth speed: 0.000 MH/s, shares: 0/0/0, time: 0:00
2021.03.25:18:27:46.965: eths Eth: Send: {"id":5,"jsonrpc":"2.0","method":"eth_getWork","params":[]}

2021.03.25:18:27:47.130: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x9e027f4e1d4d019c814c17cfc06ba74d0cabed295efcbaf2d429379cd359622d","0x3ba1ec7dd7e5aad3c65bafbe04baad8cc72d5157dbce5701db30c476f182011f","0x0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba","0xb8c45f"]}

**Comment by Alexxxks** [comment]
Ошибка - out of memory , не хватка памяти ! Попробуй NiceHashQuickMiner

**Comment by zahar12342** [comment]
> Ошибка - недостаточно памяти, не хватка памяти! Попробуй NiceHashQuickMiner

просто поменять программу для майнинга?

**Comment by Alexxxks** [comment]
да,удали полностью и установи вот эту https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.4.5.5 , она автоматически все настроит

**Comment by zahar12342** [comment]
> да, удали полностью и установи вот эту https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.4.5.5 , она автоматически все настроит

спасибо большое

**Comment by Alexxxks** [comment]
и еще попробуй сразу увеличить фаил подкачки, так чтоб он был равен общей памяти гпу или можно немного больше
