### ISSUE TITLE
CPU mining drops to .3KH/s on most of my CPUs randomly and often.

### ISSUE THREAD

**Issue by sittingmongoose** [nicehash/NiceHashMiner#2383]
Running version 3.0.6.3, on newest windows 10, with newest miner plugins.  I have noticed over the last few days that most 6/8 of my cpus have this issue.  They are all on different machines.  They will be mining fine, then all of a sudden drop to .3kh/s.  For example my 5950x goes from 17.5kh/s to .3kh/s.  I also have a 160af, 1800x, e3-1231v3, e5-2678v3, 6600k that experience this.  My 3900x and 5600x do not.  None of the cpus are overheating.  Restarting the computer does not fix the problem.  I can stop and start the miner and it will resume its normal speeds but after some time they all get stuck back at .3kh/s.  None of the computers are being used at all except for mining when this happens.  There are no problems running in the background.  When this happens, GPU mining continues to work as expected.  Running xmrig stand-alone using nanopool I get expected hashrates.

**Comment by bovcan** [comment]
aha, yup I noticed this problem too, but it goes to normal speed after some time. Strange behaviour.

**Comment by GrafZarik** [comment]
I have the same problem. I have 3950x and usually 16.28 kH/s, but often it happens 0.58 kH/s

**Comment by Michaela813** [comment]
hello everyone! i"m sorry for all the trouble i"ve been causing you guys when it comes to my gadgets and problems you encounter. it's still pandemic and locked down here in my country ,philippines. i just had problems with my IT so need to find one so i don't messed up my gadgets, I'm so sorry for all the trouble i know my fault on depending too much with my IT. i feel bad when i read conversations through html codes i just dont know how to answer them and the proper way to respond. anyway thanks for your patience and dedication to your job.I was really shocked and amazed while reading it and trying to understand your conversation and i realised how stressful it is! so from then on i said tp myself i really salute these people and learn to value and thanked you guys for existing and patiently doing and making and helping the whole world too much a better and convenient place, i really appreciate all you guys who loved to be in this field,more power and may god bless you all!B safe everyone!

**Comment by Dohtar1337** [comment]
Does the issue persist?

**Comment by GrafZarik** [comment]
> Does the issue persist?

Yes. Not often but sometimes it happens.

**Comment by Dohtar1337** [comment]
Must be XMRIG issue not NHM. Closing
