### ISSUE TITLE
Improve suggestions/errors in NiceHashMiner

### ISSUE THREAD

**Issue by tmontney** [nicehash/NiceHashMiner#2385]
I am struggling with a 980ti and Windows. GUI just says "error" when I try to mine on it. Here are some things I noticed throughout:

- No where in the GUI does it explain why the slot is in "error". This should include a "show more details" to help the user troubleshoot.
- When the GPU slot is in error, no [ERROR] lines are visible in the log file. This seems like something very important to log.
- Notifications states "DCH drivers detected". "More Info" isn't much help. A link to https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers (or similar instructions) should be listed. Perhaps some kind of built-in utility to fix it on-the-spot. (Properly running DDU did not make the notification go away.)
- Under Plugins, Excavator said it had an update from 15.9 to 15.11. When updated, I get a notice that says that Excavator was not updated. When I checked Plugins, it showed Excavator was at 15.11. This should also says **why** the plugin was not updated.

**Comment by Dohtar1337** [comment]
Thank you for your feedback!

**Comment by Dohtar1337** [comment]
Noted on PRD
