### ISSUE TITLE
Low mining speed on gtx 1060 6gb gainward

### ISSUE THREAD

**Issue by Fio1337** [nicehash/NiceHashMiner#2388]
Passed all plugins benchmarks. I chose DaggerHashimoto Excavator as the best, but the mining speed is about 15-16 MH / s. I watched tests on the Internet and calculating the profitability on the site. Everywhere around 19-21. What could be the problem?
![Screenshot_1](https://user-images.githubusercontent.com/76091074/113529569-f24f4080-95ed-11eb-8d39-7476f1869d96.png)

**Comment by Beriktabe** [comment]
Use msi afterburner 
![изображение](https://user-images.githubusercontent.com/15926217/113692802-990f0c00-96d6-11eb-8496-cf226720c2ac.png)
and everything will be fine, i have 1060 6gb too, without mem boost it is 14-16mh/s

**Comment by Fio1337** [comment]
With this setting, the image is crumbled into artifacts, I have to restart the pc. I'll try to find something else on the Internet. But thanks anyway.

**Comment by Beriktabe** [comment]
try to use +600 mem and -150 clock

**Comment by Fio1337** [comment]
Я так понимаю ты русский, поэтому буду писать так. Поставил сначала было не плохо минут 10, но потом пропал сигнал видяхи, не выдерживает видать нагрузки. Максимум +400 к памяти. С даунвольтом естественно

**Comment by Cor-net** [comment]
Попробуй NiceHash QuickMiner, у меня лучше с ним стало. Он тайминги на видюхе выставляет, как раз для серии Pascal
![изображение](https://user-images.githubusercontent.com/74053627/115348191-fb7a0900-a1ba-11eb-8bab-c3b9f1c5f299.png)

**Comment by Fio1337** [comment]
Не особо помог квикмайнер. Скорость даже в разгоне не особо поменялась. Ты менял какие то настройки? Или поставил его как есть и не трогал?

**Comment by Cor-net** [comment]
![изображение](https://user-images.githubusercontent.com/74053627/115667770-e209c600-a34e-11eb-9633-b6466178216e.png)
В настройках рига на сайте выбери "Эффективный".
У меня уже ручной выставлен, я чуть чуть настроил по своему после этого.
Там главное в разделе «Adjust memory timings» настроить у меня дефолтные «"FAW=28","REFRESH_LO=3","REFRESH=7","RRD=7"» работают

**Comment by Dohtar1337** [comment]
not a NHM issue but QM
