### ISSUE TITLE
Nicehash miner and Geforce 3060 with 470.05 beta driver

### ISSUE THREAD

**Issue by zztop007** [nicehash/NiceHashMiner#2389]
Nicehash miner doesn't seen to work very well with 470.05 beta driver?
Many of the miners cant benchmark and crash, not even when manually updated.

No problem with excavator but Im after profit switching. 
Mixed W10 rigg with 3060, 3070, 1660 and 1060 6gb.

**Comment by zztop007** [comment]
Do you work on NH Miner at all. 
Quick Miner is nice and works like a Charm but I need to get profit switching going.

**Comment by Dohtar1337** [comment]
Does the issue persist?

**Comment by Dohtar1337** [comment]
No response. Closing.
