### ISSUE TITLE
Ethash - no response from mining pool, disconnected. HELP!!

### ISSUE THREAD

**Issue by HiatoQuantico** [nicehash/NiceHashMiner#2394]
help me please. I have a 5500 xt rx. Yesterday yesterday I was mining normal, now I'm having problems connecting to the pool.

<img width="520" alt="Capturar2" src="https://user-images.githubusercontent.com/82190632/114172530-26877180-990c-11eb-9528-2831ae291b41.PNG">

**Comment by HiatoQuantico** [comment]
https://github.com/ethereum-mining/ethminer/issues/1539 

help me, is that it? But I don't know how to do this command, I wanted to study that too. Can someone help me?

**Comment by tapiten** [comment]
The other day I got a similar error, but I solved it by changing the network connection of my computer from wireless to wired. 
I hope this helps you.

**Comment by bcw2235** [comment]
I am having this same issue with multiple miners not connecting with my RX580's.  Seems odd as the Nvidia cards are connecting fine from the same rig.

**Comment by Minearm-RPM** [comment]
So do I.
