### ISSUE TITLE
v1.8.1.1 Criptonight on nVidia mising

### ISSUE THREAD

**Issue by lukasmagi** [nicehash/NiceHashMiner#240]
Criptonight scrip is onece again popular for mining on VGAs ...but now its gone from this version

can you add please some ? for example XMR-STACK-NVIDIA
https://github.com/fireice-uk/xmr-stak-nvidia
or some else.

Thx  Lukas

**Comment by pducharme** [comment]
Yes, please add it, it is back to be good payout :)

**Comment by DillonN** [comment]
Cryptonight for Pascal GPUs will be available in the next update

**Comment by pducharme** [comment]
Great news @DillonN !  Any idea if you'll go with the Pre1, Pre2, etc. or you'll go straight to 1.8.1.2 ?

**Comment by DillonN** [comment]
I try to reserve Pre-release versions for when there are major changes that could impact other setups I can't test for. For versions that are mostly additions or minor modifications (like this one should be), no pre-release is necessary.

After all, NHML is targeted toward advanced users that are able to disable new features if buggy, and report issues so they can be fixed quickly
