### ISSUE TITLE
Feature request: allow arbitrary parameters in "extra launch parameters"

### ISSUE THREAD

**Issue by Jimmy-Z** [nicehash/NiceHashMiner#2400]
Currently only those defined in that JSON file are allowed, may I ask why is there such a restriction in the 1st place?

related: #2322 #2399

**Comment by nialllo** [comment]
I'd like  - - enable-gpu to NBMiner since otherwise NBMiner just terminates when running on APU and cannot be run from nicehash miner. Adding it to the JSON just gets ignored at run time and overwritten at start up.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
