### ISSUE TITLE
Why Not Add Support GPU on XMrig ?

### ISSUE THREAD

**Issue by emperinter** [nicehash/NiceHashMiner#2401]
# Reason
- I try to use XMRig alone  and it can be running on GPU,It is not support on this SoftWare.
- I try to config for myself,but it can not be montiored By Nicehash.

# Image
- Nicehash
![image](https://user-images.githubusercontent.com/20177836/114656299-69888100-9d20-11eb-8f27-629567aec9b5.png)

- My config 
![image](https://user-images.githubusercontent.com/20177836/114656279-5e355580-9d20-11eb-93ea-b0d6b67c0714.png)

**Comment by emperinter** [comment]
![image](https://user-images.githubusercontent.com/20177836/114656580-f0d5f480-9d20-11eb-9770-172e3c2a3f70.png)

**Comment by bovcan** [comment]
they could add more support for cpu mining as well.

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner/blob/master/doc/UserPlugins/README.md
