### ISSUE TITLE
Nvidia Quadro M1200 not supported anymore?

### ISSUE THREAD

**Issue by Hrisson** [nicehash/NiceHashMiner#2402]
I updated from Nicehash from 3.0.5.6 to 3.0.6.3.

It seems my Nvidia Quadro M1200 is not recognized anymore. It is not displayed in the list of available GPU in Nicehash software anymore.
I tried to update to 3.6.0.4 and update to the last Nvidia drivers, but same problem :-(.

Going back to 3.0.5.6 fixed the issue. However i have lost all my pluging and it is not possible to download it again due to uncompatibility with Nicehash 3.0.5.6.
![image](https://user-images.githubusercontent.com/82522995/114728179-ddb92980-9d0c-11eb-8b89-e27467d85ccb.png)

**Comment by Balajims88** [comment]
me too facing same problem with my Nvidia 840M 4GB card.

**Comment by andrew-stclair** [comment]
Same issue here with GeForce 930MX

it was there until i updated to 3.0.6.5 but it's now gone
