### ISSUE TITLE
3.0.6.4 crash with rx580

### ISSUE THREAD

**Issue by Moustachauve** [nicehash/NiceHashMiner#2403]
When using 3.0.6.4 on windows with my rx580, the nicehash window itself will crash (becomes transparent with only the border around it) and my worker will stop showing as active in the nicehash mining rig page, but the CLI window of the miner (nbminer) is still open and mining happily at full hash rate

**Comment by Jimmy-Z** [comment]
I'm also running 3.0.6.4 on a rx580, I don't have this problem though.

**Comment by Moustachauve** [comment]
I don't know. I reverted to 3.0.6.3 and I don't have the issue.
