### ISSUE TITLE
Update t-rex

### ISSUE THREAD

**Issue by zztop007** [nicehash/NiceHashMiner#2404]
Please update miners to latest version

**Comment by Miiichal** [comment]
**totally agree**
its not only about T-rex, but Nicehash is really slow in updates...
MiniZ - 1.7x4
Trex - 0.20
TTMiner - 6.2.0

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner/tree/master/doc/UserPlugins
