### ISSUE TITLE
Nicehash miner's Excavator setting for 1080Ti ?

### ISSUE THREAD

**Issue by tumsd923** [nicehash/NiceHashMiner#2405]
[What is Excavator ?](https://www.nicehash.com/blog/post/what-is-excavator)

Now I'm using Phoenix miner with --straps 2 and getting around 44 mh

And I saw hashrate table from the above link that 1080Ti can get 44-ish mh as well.
So, I wanna try out but I'm still not sure about the setting.

Do I need to use with ETHPill to reach that hashrate or the Excavator will automatically detect and adjust for me ?

**Comment by gingertrol** [comment]
New version of excavator is doing the same thing as ethpill, so there will be no improvement using ETHpill at the same time
