### ISSUE TITLE
Any higher than 3056 version

### ISSUE THREAD

**Issue by peteycrack420** [nicehash/NiceHashMiner#2409]
if i try to install anything thing higher than 3 0 5 6  version   shit dont work  update drivers  dont work  clean install dont work  i have been using nicehash for a long time  and have tried it on 3 diffrent rigs

**Comment by DoNotResuscitate** [comment]
Same here, I have a 1070. Any higher than 3.0.5.6 and it comes with no predownloaded plugins, when I try to download a plugin it says failed, IDK what's up.
