### ISSUE TITLE
RX 480 not showing in devices

### ISSUE THREAD

**Issue by WireShock** [nicehash/NiceHashMiner#241]
I downloaded the regular nicehash 2.0 then it redirected me to the legacy version. I've tried uninstalling my rx 480 via device manager and then I reinstalled drivers, but I still cannot get it to recognise my GPU. I'm relatively new to mining.

![image](https://user-images.githubusercontent.com/18351536/29772922-dee13980-8bf2-11e7-835c-03579ec8a727.png)

![image](https://user-images.githubusercontent.com/18351536/29772651-a4ab3a6e-8bf1-11e7-98f8-d35c55192c8a.png)

**Comment by luongk** [comment]
Can you post your log file?  Is AMD detection disabled in settings?

**Comment by kentdbarker** [comment]
I had this problem once a few versions ago, I unzipped another copy of nicehash, ran the benchmark, and everything was back to normal.  I'm not sure of the root cause of the problem, I suspect a .json file was messed up somewhere.

**Comment by kentdbarker** [comment]
I had this problem once a few versions ago, I unzipped another copy of nicehash, ran the benchmark, and everything was back to normal. I'm not sure of the root cause of the problem, I suspect a .json file was messed up somewhere.

**Comment by DillonN** [comment]
@WireShock as @luongk said your log file is needed to help
