### ISSUE TITLE
Nicehash Intell WIFI ax200 dropping connection and slowing down.

### ISSUE THREAD

**Issue by icodes42** [nicehash/NiceHashMiner#2411]
https://user-images.githubusercontent.com/57429290/115136002-a333e300-9fd1-11eb-898a-5a115936a152.mp4

This is a video of my new laptop which is a Gigabyte 15g XC 3070 which has an Intel WIFI AX200 card in it. NiceHash on this rig will crash my WIFI sometimes while using the laptop and mining, which requires me to restart it. NiceHash usually just slows down my connection speed, seeing as I leave it running while I'm at work it hasn't crashed my wifi unless I'm doing something else that is internet intensive.

I also have another laptop a MSI GP63 Leopard 1070 which has an Intel wifi AC9560 card, and this has no problems at all, other than dropping 10 - 30 Mbps while mining.

I have seen some people posting about it causing interference from the video card being located too close to the wifi card. Which makes no sense seeing as I have another laptop that works fine. I have even tried switching the AX200 into AC wifi only but, it still slows my internet down

I bought a TP-link AC1300 USB dongle it's like my other laptop, it only drops 10 - 30 Mbps. I also directly connected the dongle to the laptop next to the GPU and it still works fine.

I'm guessing NiceHash isn't optimized with the new AX WIFI standard cards.

**Comment by gingertrol** [comment]
Nicehash miner has nothing to do with network and wifi cards, it uses standard way to communicate with servers and should not affect the bandwidth drastically as described. The bandwidth needed for mining is minimal. My assumption is that mining increases load on cpu and gpu. If the network drivers depend on cpu resources this can be the reason. You can try to run something cpu or gpu intensive and start speed measure and will get probably the same result.
