### ISSUE TITLE
P106-90 incorrect available algorithms

### ISSUE THREAD

**Issue by Jimmy-Z** [nicehash/NiceHashMiner#2412]
Running 3.0.6.4, NBMiner and TRex plugin installed.

It only show Octopus for TRex and BeamV3 for NBMiner.

Octopus should not be listed available since this GPU only has 3GB VRAM.

Doesn't list KAWPOW, which should be available, it works if I run the miner from command line.

BeamV3 works however it's not as profitable currently.

In PluginSupportedAlgorithmsSettings.json, KAWPOW(52) is listed as requiring 4GB VRAM, which is simply not true. however, I tried to edit this file and reduce that value to 3GB, but it seems nhm will simply overwrite this file upon starting.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
