### ISSUE TITLE
Kawpow error with RX 550 4 GB

### ISSUE THREAD

**Issue by KrisKok13** [nicehash/NiceHashMiner#2415]
Hello. I need help with kawpow miner. Error with benchmark all the time. How to fix this please?
It mining with now with lolminer Beam V3 but very slow.
Kawpow is NBminer. Thanks for your help.

**Comment by mauler2025** [comment]
The same issue for RX 570 4GB of mine.

**Comment by Matheuslw** [comment]
Same with RX 460 4 GB

**Comment by morrisseybr** [comment]
Same error, RX550 4GB. Any news?

**Comment by suumcuiquey** [comment]
NBMiner - Kawpow перестал работать на rx 480 4gb

**Comment by cshoppos** [comment]
same here with RX 580 4GB . Please reinstate functionality.

**Comment by cshoppos** [comment]
i forgot - used nicehash miner version 3.0.6.5

**Comment by Edu3020** [comment]
Same here... 3x rx 550 4gb, got benchmark error on every miner with kawpow ._. 

Lateast version of nice hash.. and tryed up old versions too.

**Comment by CaioCOp1la** [comment]
Got benchmark errors on RX 460 & rx 550 4Gb, if try out nicehash idk but works fine!
