### ISSUE TITLE
Nice Hash Miner completely blocked by Windows Defender

### ISSUE THREAD

**Issue by mishmanners** [nicehash/NiceHashMiner#2417]
There is no longer a way to restore or allow false positives through AV.

I had all the Nice Hash Miner folders added to exclusions, and all the *.exe files were added to "allowed threats" and now that list is completely empty.

Nice Hash miner opens, but I cannot start mining as I cannot install any of the Plugins.

Please help! I have tired everything and nothing works.

**Comment by mishmanners** [comment]
This all worked fine for me before the new update.

**Comment by mishmanners** [comment]
I also tried installing various versions, none of which worked. Also tried with Quick Miner, also doesn't work.

**Comment by 2T1N** [comment]
This happened to me as well, and my GPU started registering as over heating. No CPU mining & GPU overheats.

**Comment by mauler2025** [comment]
Cryptojacking is the act of hijacking a person's computer to secretly mine cryptocurrency. 

Because cryptojacking requires increasing processing power to mine cryptocurrencies like Bitcoin, miners are discovering new ways to wield that processing power. One such way is to borrow it from thousands of unwitting internet users.

**Comment by V8por5m1n3R** [comment]
If you are running Windows 10 and only using Windows Defender:
1. Close all Nicehash instances and miners
2. Start PowerShell_ISE.exe as an Administrator
3. Open the following PowerShell script; download from https://github.com/V8por5m1n3R/Mining-AV-Exceptions
4. Change this line to match the folder you launch Nicehash from: $RootFolder = "C:\CCMN\Miners" # Replace this with the path to your Nicehash folder
5. Consider removing miners from the $MFLJ variable that you are NOT using
6. Run the script
7. A reboot may not be necessary, but is recommended before restarting Nicehash

If a script is needed to remove excluded process from Windows Defender, I will work a generic one out for the community (~60 mins of work)

https://github.com/V8por5m1n3R/Mining-AV-Exceptions

If it helps, please donate to my cause of helping all Nicehash miners - addresses at bottom of the post linked above.

**Comment by mishmanners** [comment]
Okay let me try this.
