### ISSUE TITLE
mining not being reported

### ISSUE THREAD

**Issue by asulwer** [nicehash/NiceHashMiner#2420]
mining not being reported to nicehash site?  been running for a week and nothing that the miner has done is being reported

nicehash states the amount i am mining a day
![image](https://user-images.githubusercontent.com/7673412/116014508-780d4d00-a5ea-11eb-954a-27fd2da97fee.png)

but site states zero and my wallet hasnt increased
![image](https://user-images.githubusercontent.com/7673412/116014459-41373700-a5ea-11eb-8e05-23aa4a184af2.png)

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
