### ISSUE TITLE
Processador ryzen 5 3600 ERRO NICEHASH

### ISSUE THREAD

**Issue by lojao22** [nicehash/NiceHashMiner#2421]
Ola. Boa noite.
Comecei a usar NiceHash recente. Sou novato no ramo de mineração.
Meu processador esta dando "ERRO" no NICEHASH. ryzen 5 3600
Placa de video rx 580 8GB funciona normal.
Algúem tem alguma dica por favor. Obrigado.

**Comment by Noth-Shian** [comment]
Speak english pls

**Comment by lojao22** [comment]
my Ryzen 5 3600 processor is giving ERROR in the BENCHMARK. Can you help me ?

**Comment by Edu3020** [comment]
Esquece mineração por CPU velho.. especialmente se sua placa mãe for muito básica, isso por que os incomes são muito baixo vai só gastar seu hardware por meros centavos, deixa só a placa de vídeo minerando mesmo.
