### ISSUE TITLE
NiceHash launches a invisible cmd.exe that's do nothing for NHM

### ISSUE THREAD

**Issue by TuTAH1** [nicehash/NiceHashMiner#2427]
What is cmd.exe is needed for? I found that after ~a day of launch, the cmd.exe causes internet problems – if I kill cmd.exe while internet problems, the internet instantly works normally, and nothing wrong with NiceHash happens. If I just close NiceHash Miner, the cmd.exe never appeared

**Comment by SomethingGettingWrong** [comment]
Im having this exact issue! I end up resetting my pc to make it work again for awhile. Then upon discovering this. I am now succesfuly doing the same Thankyou! this is a replicatable problem!

**Comment by Dohtar1337** [comment]
Please provide more information like a screenshot and logs

**Comment by Dohtar1337** [comment]
No response. Closing.
