### ISSUE TITLE
Every time I restart my computer NiceHashMiner is removed.

### ISSUE THREAD

**Issue by mishmanners** [nicehash/NiceHashMiner#2429]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given.

I've added exclusions to Windows Defender, I've tried allowing false positives, but every single time I restart the computer, NiceHash Miner no longer works as Windows Defender views it as a threat. The only way to allow it is to uninstall all versions of NiceHash, reinstall, readd the exclusions to Windows Defender, and this works about 50% of the time.

Please help, I don't know what to do anymore.

**Comment by mishmanners** [comment]
Basically what happens is all the miners are deleted, NiceHash Miner opens, but can't install any of the miners themselves. They are all blocked, therefore you can't mine anything.

**Comment by V8por5m1n3R** [comment]
If you are running Windows 10 and only using Windows Defender:
1. Close all Nicehash instances and miners.
2. Start PowerShell_ISE.exe as an Administrator
3. Open the following PowerShell script; download from https://github.com/V8por5m1n3R/Mining-AV-Exceptions
4. Change this line to match the folder you launch Nicehash from: $RootFolder = "C:\CCMN\Miners" # Replace this with the path to your Nicehash folder
5. Consider removing miners from the $MFLJ variable that you are NOT using
6. Run the script
7. A reboot may not be necessary, but is recommended before restarting Nicehash

If a script is needed to remove excluded process from Windows Defender, I will work a generic one out for the community (~60 mins of work)

https://github.com/V8por5m1n3R/Mining-AV-Exceptions

If it helps, please donate to my cause of helping all Nicehash miners - addresses at bottom of the post linked above.

**Comment by mishmanners** [comment]
Exclusions were added... NiceHashMiner still doesn't work...

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion
