### ISSUE TITLE
there have one problem about the oc

### ISSUE THREAD

**Issue by liranscu** [nicehash/NiceHashMiner#243]
when i use one 1080ti to mine ,the core will be reach 1950+hz , but when i use two or three 1080ti to mine with NHML, the core only reach between 1800 -1900, the memory and the tdp is the same , three 1080ti cards are same(evga sc 2) , and the tempture is only 50-60, why ?i have changed the soft to overlock , they are still have the problem . why ?
thank u

**Comment by Olegik-ah** [comment]
Its not NHML issue. You must ask this question in overclockers forum...
But i think 90% is weak power supply or thin wires from the PSU to the GPU. Check 12V line using tester at the 8pin GPU connector, when all cards are plugged in and mining is running. I think it will be 11.4 or less...
Replace PSU or replace wires

**Comment by liranscu** [comment]
@Olegik-ah thank u ,the psu is not the problem , i know it (1500W and 92% ) , the the tdp i use 100%,  and one 1080ti card is only 250W(many time its below 250W) , the wires is also not the problem , because i use the same psu on another mechine have 6 cards of 1070, but it can be the right overclocks . so i dont know why it will happended .

**Comment by Olegik-ah** [comment]
pls, use tester:) You will see everything yourself:)

**Comment by liranscu** [comment]
i really dont know how to test and dont have some tester

**Comment by DillonN** [comment]
This is normal behaviour of Pascal GPUs, clocks will start to drop around low 60C and power throttling happens quite early as well. You can try raising the power limit in OC software (above 100%). If using Afterburner you can see performance limit reasons in the graphs

This is not a NHML issue however so I will close this
