### ISSUE TITLE
Ethlargement "NOT COMPATIBLE" even with newest update

### ISSUE THREAD

**Issue by markaabo** [nicehash/NiceHashMiner#2430]
Nicehash Miner says in the plugins screen that Ethlargement "NOT COMPATIBLE Update NiceHash Miner" even tho my NiceHash miner is the newest version...

Screenshots:
![Notcompatibel](https://user-images.githubusercontent.com/68380434/117374370-573bd600-aecd-11eb-9b45-62924da06487.PNG)
![Version](https://user-images.githubusercontent.com/68380434/117374373-57d46c80-aecd-11eb-953d-c8d8884f3d33.PNG)

Log:
[log.txt](https://github.com/nicehash/NiceHashMiner/files/6437972/log.txt)

**Comment by maxsalmela** [comment]
I also have this same problem, can't go at full speed since the update due to ETHlargement being incompatible. big problem, please fix!

**Comment by Stas-Buzunko** [comment]
wtf, updated to latest nicehash and now i get this error

rolled back to 3.0.6.3 and it's there

**Comment by angrrath** [comment]
I have this same issue with 10 different plugins!! 
Excavator
nbminer
xmrig
lolminer
cryptodredge
gminercuda9.0=
miniz
nanominer
ttminer
zenemy

I have reinstalled to the latest Nicehash program, with no luck. 

I have it as an exception in firewall and anti virus.....
Does anyone have any ideas at all? My Hashrate is pathetic on a 3070

**Comment by nikander100** [comment]
still an issue also downloaded the standalone ethlargement and didnt have any effect


> I have this same issue with 10 different plugins!!
> Excavator
> nbminer
> xmrig
> lolminer
> cryptodredge
> gminercuda9.0=
> miniz
> nanominer
> ttminer
> zenemy
> 
> I have reinstalled to the latest Nicehash program, with no luck.
> 
> I have it as an exception in firewall and anti virus.....
> Does anyone have any ideas at all? My Hashrate is pathetic on a 3070

also @angrath the pill doesnt work on 3070, only 1080, 1080ti and titan

**Comment by nikander100** [comment]
from testing it does work even though saying it isnt compatible however i was getting an average of 2mh/s lower compared to the standalone ethlargementpill.

**Comment by Dohtar1337** [comment]
Won't fix/include. This feature or bug might already be fixed or added. Or might not be included due to internal reasons.
