### ISSUE TITLE
Windows 10 blocks my NiceHash program

### ISSUE THREAD

**Issue by Letanca** [nicehash/NiceHashMiner#2433]
Well I have problem that stupid Defender is blocking exe file for NiceHash miner. I tryed everything that I know - I'm somhere between angry and wery pissed.

**Comment by andriysurzhenko** [comment]
Did you try to disable it?

**Comment by Edu3020** [comment]
try gpedit.msc method.

**Comment by anazz20** [comment]
> try gpedit.msc method.
 As far as I know, that still only works on windows 10 pro, but if you know of a way to get it into 10 home properly, as I tried long ago.

https://www.windowscentral.com/how-permanently-disable-windows-defender-windows-10?amp

Yet, after build
https://docs.microsoft.com/en-us/answers/questions/234111/can39t-disable-windows-defender-by-using-group-pol.html

Some can't get it to turn off at all, including Oh Shut Up 10,
1.8.1415 – released October 7, 2020
NEW: Support for Windows 10 2009 (20H2)
FIX: It is no longer possible to deactivate Windows Defender using the registry setting, so this setting is no longer supported

I have the latest version of OSU, and it still has a limited mark on it.

Anyway, 

> Well I have problem that stupid Defender is blocking exe file for NiceHash miner. I tryed everything that I know - I'm somhere between angry and wery pissed.

You don't have any other AV program running, you have whitelisted the folder where you download nice hash to (or extract it to) before you download it?

**Comment by V8por5m1n3R** [comment]
If you are running Windows 10 and only using Windows Defender:
1. Close all Nicehash instances and miners.
2. Start PowerShell_ISE.exe as an Administrator
2. Open the following PowerShell script; download from https://github.com/V8por5m1n3R/Mining-AV-Exceptions
3. Change this line to match the folder you launch Nicehash from: **$RootFolder = "C:\CCMN\Miners" # Replace this with the path to your Nicehash folder**
4. Consider removing miners from the $MFLJ variable that you are  NOT using.
5. Run the script
6. A reboot may not be necessary, but is recommended before restarting Nicehash.

If a script is need to remove excluded process from Windows Defender, I will work a generic one out for the community (~30 mins of work)

https://github.com/V8por5m1n3R/Mining-AV-Exceptions

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion
