### ISSUE TITLE
What about macOS?

### ISSUE THREAD

**Issue by UnixCro** [nicehash/NiceHashMiner#2435]
Why is there no way to be able to run NiceHash on macOS? Instead, NHOS is offered for every PC. But NHOS works anything but reliable and destroys my components. In the JSON file, I set the fan speed to full load.

NiceHash OS almost never turns the fan even if I don't write anything about the fan in JSON. I can also stop the miner on the website and unfortunately I had to do that several times because my GPU reached over 90 degrees and NHOS did not want to start the fan. It even went so far that the mainboard switched off all of its components for protection. 

In the NiceHash app you can also select whether "LOW" "MEDIUM" "HIGH". Mine was set to "LOW" by the way. 

Fix that! Thank you

**Comment by Dohtar1337** [comment]
Not NHM issue
