### ISSUE TITLE
Nothing work on one of my cumputer

### ISSUE THREAD

**Issue by RoadtoPrepa** [nicehash/NiceHashMiner#2437]
My setup:
Gigabyte rx5700xt (21.5.1 driver version)
ryzen5 3600
Asus tuf b450 gaming plus

My issue is that when i try to install nicehash nothing append. I mean if i download the .exe and run it, a window ganna pop and then diseaper instantly. I tried to get the .zip but:

-For older version than 3.0.6.4: i succeed to lunch the app i download the plugin, but when the main page comes it ask me to restart NHM, i do and then nothing append... i tried a lot of time and nothing append

-For older version than 3.0.6: i succeed to install the app everything is good but when i lunch the benchmark all plugin put an error and it's said that the nhm version is too old and i must upgrade it.

-For the 3.0.6.5 version, just when i de-zip the file and tried to lunch "NiceHashMiner.exe" nothing append...

Thank for your help.

**Comment by fagidgfoyi** [comment]
My setup:
Gigabyte rx5700xt (21.5.1 driver version)
ryzen5 3600
Asus tuf b450 gaming plus

My issue is that when i try to install nicehash nothing append. I mean if i download the .exe and run it, a window ganna pop and then diseaper instantly. I tried to get the .zip but:

-For older version than 3.0.6.4: i succeed to lunch the app i download the plugin, but when the main page comes it ask me to restart NHM, i do and then nothing append... i tried a lot of time and nothing append

-For older version than 3.0.6: i succeed to install the app everything is good but when i lunch the benchmark all plugin put an error and it's said that the nhm version is too old and i must upgrade it.

-For the 3.0.6.5 version, just when i de-zip the file and tried to lunch "NiceHashMiner.exe" nothing append...

Thank for your help.
