### ISSUE TITLE
Nothing work on my cumputer

### ISSUE THREAD

**Issue by RoadtoPrepa** [nicehash/NiceHashMiner#2438]
My setup:

- Gigabyte rx5700xt (21.5.1 driver version)
- ryzen5 3600
- Asus tuf b450 gaming plus

My issue is that when i try to install nicehash nothing happend. I mean if i download the .exe and run it, a window ganna pop and then diseaper instantly. I tried to get the .zip but:

-For older version than 3.0.6.4: i succeed to launch the app i download the plugin, but when the main page comes it ask me to restart NHM, i do and then nothing happend... i tried a lot of times and nothing happend

-For older version than 3.0.6: i succeed to install the app everything is good but when i launch the benchmark all plugin put an error and it's said that the nhm version is too old and i must upgrade it.

-For the 3.0.6.5 version, just when i de-zip the file and tried to launch "NiceHashMiner.exe" nothing happend...

ps: i tried on my second cumputer (1050mobile 2Gb, i5 7300hq), and everything gone well...

Thank for your help.

**Comment by Edu3020** [comment]
- Try check ur runtimes..
- Check if Windows defender are blocking it
- Check if DEP are enable.. if are disable it via CMD.
- Try DDU Unistaller and use previusly version of Radeon Drivers.

**Comment by Yasht2895** [comment]
@RoadtoPrepa Getting same issue. tried to restart computer and also try by installing new setup

**Comment by LoganBarr88** [comment]
same issue with me can someone help

**Comment by Dohtar1337** [comment]
Antivirus is most likely blocking something 
https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion
