### ISSUE TITLE
NiceHash STOPS mining by itself

### ISSUE THREAD

**Issue by TuTAH1** [nicehash/NiceHashMiner#2442]
I had "Launch mining while idle" enabled, and "idle mining while no connection disabled" – so, nothing should stop the mining. But after some time I see that mining was just be stopped while I was away from PC. I think that this option "Launch mining while idle" with parameter "InputTimeout" stops mining instead of starting it.
Post Scriptum. It's very likely a "Launch mining while idle" option – if I turn it off, the unexpected mining offs are stopped

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow the updates and see if the next release solves the issue for you.
