### ISSUE TITLE
bugs / improvements

### ISSUE THREAD

**Issue by salvadorjhai** [nicehash/NiceHashMiner#2443]
option "Show Internet Connection Warning" not working. I disabled this option but still getting a dialog box about internet connection.

there should also be an option to auto restart nicehash when;
1. total hashrate drops for number of x minutes ~ then will restart system still fails and if number of x retry was made.
2. missing gpu (sometimes only needs to restart nicehash instead of whole system) - this happens sometimes when connection fails. UI will show that a GPU is mining but its miner program does not show (0 hash).

**Comment by Dohtar1337** [comment]
Moved to idea backlog. Closing to clean the issues.
