### ISSUE TITLE
Someone lost out on an Eth block because of this Error. Please help!

### ISSUE THREAD

**Issue by SomethingGettingWrong** [nicehash/NiceHashMiner#2445]
![image](https://user-images.githubusercontent.com/36722911/118411728-b03d0400-b65b-11eb-890d-1e96388e590a.png)

I cant seem to figure out what the issue is with this! I have zero connection issues on ethermine directly only on nicehash!

NOT being able to turn in a 500 PH block for someone is kinda wonkers!

**Comment by argonatorUberTF** [comment]
Also I am getting rejected shares and phoenixminer is reporting in the logs as "share above difficulty."  
Why not accept it and solve the block?  There's money being left on the table for those who are in the pool.
Does the same thing in LOL miner and 
![image](https://user-images.githubusercontent.com/62854348/118412976-cf369880-b651-11eb-81e9-ee368ce72729.png)

**Comment by SomethingGettingWrong** [comment]
![image](https://user-images.githubusercontent.com/36722911/118413138-622bfe80-b663-11eb-9f75-009543fe7822.png)

**Comment by argonatorUberTF** [comment]
And nicehash is rejecting good work with a new twist on the stratum protocols. 
Using their own miner. Rejected, job not found. How can one tell a 24 billion transistor gpu to compute this and then all of sudden forget about it ?

![image](https://user-images.githubusercontent.com/62854348/118880250-80357100-b8a6-11eb-9af5-0b8bd33fc6f8.png)
