### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Jimmy-Z** [nicehash/NiceHashMiner#2447]
I run this on multiple computers, some of them experience serious memory leakage, I've seen around 2G of memory usage in task manager after days of running.

Version 3.0.6.5
Windows 10

I've switched to run miner directly because of this.

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/support/mining-help/mining-advanced-topics/memory-leak-when-mining-with-nvidia-gpus
