### ISSUE TITLE
DCH driver warning

### ISSUE THREAD

**Issue by Jimmy-Z** [nicehash/NiceHashMiner#2448]
I don't think this is working right, I have gameready driver installed, this is still popping, very annoying.

And I got normal hashrates, so I don't think I installed the wrong driver.

Version 3.0.6.5

**Comment by salvatoreboemia** [comment]
You need to install "standard" driver. Go to "advanced search nvidia"

**Comment by Jimmy-Z** [comment]
My bad, I did have DCH driver installed, but then there is the other argument: it looks like a witch hunt, nicehash claim DCH drivers have issues, I don't have any.

And nvidia says it's just the packaging:
https://nvidia.custhelp.com/app/answers/detail/a_id/4777/~/nvidia-dch%2Fstandard-display-drivers-for-windows-10-faq#:~:text=What%20is%20the%20difference%20between,NVIDIA's%20Standard%20and%20DCH%20drivers.&text=When%20directly%20comparing%20the%20two,time%20than%20the%20Standard%20package.

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
