### ISSUE TITLE
Benchmark all failed

### ISSUE THREAD

**Issue by salvatoreboemia** [nicehash/NiceHashMiner#2450]
All benchmark failed

- i formatted the whole computer
- standard non-DCH driver installed.
- totally disabled antivirus / defender / etc

I have RTX 2070 Super

i don't know what i can do further.

![image](https://user-images.githubusercontent.com/20614870/119481924-8d91a600-bd53-11eb-814c-6865f405824b.jpeg)

**Comment by poisonhand** [comment]
i am having this same problem been trying to fix for hrs. 
was benching fine but no usage on gpu. i reinstalled ncm and now failing all benches?
if you find the cause plz. update. i have tried reinstalling and keep files i tried fresh install nothing changes it.

idk if its matters but specs: 
2600x cpu
rx5700 gpu (has been flashed into a 5700XT)

**Comment by poisonhand** [comment]
so far the only clue that i have is. if i disable some plugins it allows for some to pass benchmark. also daggerhashamoto used to mine fine on here now i cant get any plugin to run dagger? idk if any of this helps.

**Comment by poisonhand** [comment]
okay so i got dagger algo working again did another fresh install (like the 10th one i did) and only have loland nbminer plugin installed all others are not installed. my hashrate is good and all seems well. idk why this worked but it did i guess for now. i will update if it stops working.

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/bloag/post/benchmark-error-in-nicehash-miner
