### ISSUE TITLE
Current profitability and mining status doesn't update

### ISSUE THREAD

**Issue by RoinujNosde** [nicehash/NiceHashMiner#2454]
NiceHashMiner version 3.0.6.5
Windows 10

Steps to reproduce:
- Open the miner (with the minimum profitability on 0)
- After it started mining, go to the settings and set the minimum to something above the current profitability.
- Click somewhere on the program's window to apply the change
- It will stop mining (the CMD window will close) but: NiceHashMiner dashboard will say "Mining" and will remain displaying the old profitability.

Log: [log.txt](https://github.com/nicehash/NiceHashMiner/files/6604724/log.txt)

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow the updates and see if the next release solves the issue for you.
