### ISSUE TITLE
Adding delay when restarting miner

### ISSUE THREAD

**Issue by jperrela** [nicehash/NiceHashMiner#2455]
Hi.

Nicehash miner is causing a BSOD (video_scheduler_internal_error) when mi Phoenix Miner Restarts. My gut feeling tells me that I could solve this by configuring a delay between the closing and relaunching of the miner, as the problem is that Phoenix remains open for a few seconds and at the same time it is relaunched in a new instance. 

The BSOD does not appear when I pause and restart manually, and Phoenix is the only one I can use. 

Is there a way of configuring this delay?

Thanks.

**Comment by Miiichal** [comment]
Advanced Settings - and the box "MinerRestartDelay"
I use about 4000ms (4sec) for delay between excavator, when they change because of profit. One of my cards is little bit slower than others, so i solved it with this way. Hope this helps...

**Comment by jperrela** [comment]
Thanks! I did not notice that setting.
