### ISSUE TITLE
Quadro k 1200

### ISSUE THREAD

**Issue by starnazzapa** [nicehash/NiceHashMiner#2457]
Hi I m having problems to make nicehash to recognise gpu quadro k 1200 I already install a p400 with no problem only installing the cuda tool kit 
I already try with the proper driver but nothing.
When I run the miner I see the gpu on lol miner in green but not on the rig panel 
Any advise
Thx

**Comment by starnazzapa** [comment]
I also have the same problem with a gigabyte gt 710 2gb

**Comment by Dohtar1337** [comment]
Your GPU is not supported.
