### ISSUE TITLE
NiceHash Miner Unable To Start Mining

### ISSUE THREAD

**Issue by warthog02** [nicehash/NiceHashMiner#2458]
I am unable to start NiceHash Miner 3.0.6.5 as the "Start Mining" button is greyed out. Windows Defender has allowed the app through.

The bug has been submitted to NHM as report #8ab6db8b-56a7-453d-906d-d1a857229f58

![NiceHash Miner 1](https://user-images.githubusercontent.com/75111955/122047115-55412d00-ce12-11eb-9d6a-2a5d9077c748.JPG)
![NiceHash Miner 2](https://user-images.githubusercontent.com/75111955/122047119-55d9c380-ce12-11eb-8f6e-0b52faa713c2.JPG)
![NiceHash Miner 3](https://user-images.githubusercontent.com/75111955/122047426-b79a2d80-ce12-11eb-82dd-c8154a151eee.JPG)

**Comment by Dohtar1337** [comment]
Disable PUA and redownload the plugins then rebenchmark them all
