### ISSUE TITLE
Workers dropped to 0 after NHM update v2.0.1.x

### ISSUE THREAD

**Issue by VanceAnce** [nicehash/NiceHashMiner#246]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [x] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [x] Specifications of setup such as NHML version, Windows version, and hardware are included.

**Comment by VanceAnce** [comment]
after the NHM update v2.0.1.x all my miners 

(3x i3, and some RX550) arent shown in the NHM landing page 
i had support contact via FB live chat and they redirected me here

im using a stable version of the miner software on github v1.3.3.x 
all are detected working, showing hashrate in the programm and even the estimated € price/day

no clue wahre i should start to solve this - all are up running fine and without troubles

**Comment by Nicheuji** [comment]
Have you tried with NHML instead?

**Comment by kenman345** [comment]
NHM 2.0.1.x is not part of this project. You should direct this issue to the github repository for that project instead. [https://github.com/nicehash/NiceHashMiner](https://github.com/nicehash/NiceHashMiner)

**Comment by luongk** [comment]
https://github.com/nicehash/NiceHashMiner2/issues is the correct repo, I think.

**Comment by VanceAnce** [comment]
thx for your answers - as i posted i tried with nhml and it doesnt work 
(that also nhm v2 doesnt work was just and additional info ;) )

so does any of you have an idea - or a similar setup (i3 550, rx550)  where it does work ?

cause i realy would like to keep it as great as it had been with nhm&nhml because ive a little amount of older pcs with those specs.

using miner v1.7.5.3 and v1.7.3.3 the nhm landing page shows income with miner 0 
mixed names - one of my 1.7.3.3. devices shown active for some seconds but restartet an 1.7.5. version .....

**Comment by VanceAnce** [comment]
ok solved roblem - seems for me doenst work the eu server even if it would be better 
-> switching to us serv solves the problem 

any ideas why and how to connect back to the eu serv
log file shows time out and connection errors

**Comment by VanceAnce** [comment]
aaand problem is back up ..... atm at UTC+01:00

tried different servers .... si there a way to backtest somehow connectivity with the landing page ?

**Comment by DillonN** [comment]
@VanceAnce 1.7.x (as well as 2.x) are not part of this repo, NHML versions all begin with 1.8. Do you have issues with 1.8.x versions and if so could you post your logs?
