### ISSUE TITLE
Dynamic naming for cloned images

### ISSUE THREAD

**Issue by curtis-arch** [nicehash/NiceHashMiner#2460]
If I am running several images based off the same initial install of NH. it seems they all end up with the same name and are consolidated to a single rig in the HN miner mgmt screens in NH online. My assumption here is that each install generates a unique ID and then all of the instances of the image then use that same ID. It would be good to have a setting to make this dynamic per instantiation of the application this way each running version of NH on the machine is addressable. The simple use case would be as follows

Setup a windows machine, install HN and set it to auto start and auto start mining. Create image of the machine. Deploy image to several workstations each with 2 graphics cards. Notice in NH it will report as a single miner and that you have just 2 cards... The pmts are working fine and the hash rate is generally fine but the optics and mgmt of each rig is not possible.

**Comment by S74nk0** [comment]
@quotient you can change your RigID for each clone by adding `extra_rig_seed.txt` file with different contents (Rig01, Rig02,...) and this will give each rig a different ID.

Closing issue. If the suggested method doesn't work for you reopen this issue.
