### ISSUE TITLE
Nicehash not working

### ISSUE THREAD

**Issue by nimmam831** [nicehash/NiceHashMiner#2463]
When i click on NiceHashMiner (worked once) it opens but login page shows white or it does not open at all.
Example:
https://youtu.be/w91dotiJilQ
NHM version: 3.0.6.5, Windows 11, i5-6600k, GeForce GTX 1050 Ti
[log.txt](https://github.com/nicehash/NiceHashMiner/files/6776900/log.txt)

**Comment by Anaverageminer** [comment]
Try reinstalling, Maybe during install it missed a few files

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
