### ISSUE TITLE
Adding Golem

### ISSUE THREAD

**Issue by figurestudios** [nicehash/NiceHashMiner#2464]
Just like you stated [here](https://discord.com/channels/809849352516141067/827983756328435722/855652830178443275) regarding supporting decentralized networks, I'd like to suggest [Golem](https://golem.network).

Golem is a decentralized and distributed marketplace where you can rent or rent out computing power. It works natively on Linux for now but will eventually get native support on Windows too. To add it, you'd have to follow these 2 steps:

- Add your own ERC-20 wallet that you get paid in. Make sure it can log in on [zkSync](https://wallet.zksync.io/).
- Setup priorities - Golem above anything else in case it needs the computing power as it will time out otherwise if something else with higher priority is using these resources.
- (Optional) utilizing Docker like [this](https://github.com/blue-notes-robot/golem-node).
- (Optional 2) making the user manually tick Golem providing?

I think it would be a great addition as it would help decentralize computing-power, and because of the fact that you can have an optional amount of resources (ATM - CPU, RAM, DISK) and charge what you want (CPU for downloading images/upload results, CPU-hour for computing - automatically multiplied by threads, START for a starting fee to use your node). There's no need for constant uptime like many other projects have. It isn't as wasteful as PoW and hosts for example [a research project](https://blog.golemproject.net/announcing-chem-golem/) on the network. Downsides would be if it updates to require forwarded ports but I'm sure you could keep a proxy server for that :)

Here's some information regarding the project:
- [Collection of applications and similar](https://github.com/golemfactory/awesome-golem).
- [Discord Server for chatting](https://chat.golem.network).
- [Provider Setup](https://handbook.golem.network/provider-tutorials/provider-tutorial).

**Comment by Dohtar1337** [comment]
Won't fix/include. This feature or bug might already be fixed or added. Or might not be included due to internal reasons.
