### ISSUE TITLE
Mining disconnected every few minutes

### ISSUE THREAD

**Issue by CompoundWave** [nicehash/NiceHashMiner#2467]
Hello, 

Every few minutes I get the following messages, and it is causing performance issues during mining. 

[04:57:55] [info] nhmp | Disconnected
[04:57:55] [warning] nhmp-ssl | read: An existing connection was forcibly closed by the remote host (10054)
[04:58:03] [info] nhmp | Disconnected
[04:58:03] [warning] nhmp-ssl | ws handshake: The I/O operation has been aborted because of either a thread exit or an application request (995)

The items above are what happens most of the time every few minutes, but I will also get this one below every so often. 

[05:40:27] [warning] nhmp-ssl | read: The semaphore timeout period has expired (121)

I am including a stripped-down version of the Excavator logs to show how often it is doing it. I took out all unrelated entries (shares accepted, etc.). 

Details:

- OS (and version): Windows 10 Pro. I have had this problem on versions 20H2 and 21H1, both fully updated. 
- Firmware: I downloaded all of the latest firmware from the computer vendor. The problem still persists. 
- GPU: Nvidia 3080
- The device has a good internet connection, and I have verified that the connection is not getting dropped due to the internet connection.
- NHM Version: 3.0.6.5 (full, not quick version. However, I did try the quick miner as well and had the same problem). 
- Excavator Version: 16.0 (latest). 
- Problem persists on multiple algorithms
- Tried connecting to different servers (Europe, USA, USA West, USA East), no change in the problem. 
[Debug (2) - Copy.txt](https://github.com/nicehash/NiceHashMiner/files/6797251/Debug.2.-.Copy.txt)

**Comment by Kick4U2** [comment]
I had a similar issue.  I now open the app with admin privileges and don’t encounter this anymore. Not certain if that is what fixed it or not.  Ran it in admin to adjust some OC settings.

**Comment by grantwoodfl** [comment]
I'm having the same issue. Did you ever find a resolution to it?

**Comment by CompoundWave** [comment]
Hello, I did not find a solution. However, the issue did appear to resolve itself. When the connection would drop the GPU fans would slow down then have to speed up when it connected again. It was annoying. I set the fans on the GPU to essentially max, so I no longer could hear when the connection dropped. After a few days of just leaving it on it, it appeared to resolve itself.
