### ISSUE TITLE
Does not show daily gains 1.8.1.1

### ISSUE THREAD

**Issue by Rerin10** [nicehash/NiceHashMiner#247]
My nicehash software is not showing the daily BTC values ​​and nor the mBTC amount, version 1.8.1.1!

**Comment by Mossiemos** [comment]
Hello , Same issue with me , using NHM legacy 1.8.1.2
Thanks

**Comment by Mossiemos** [comment]
Hi mine was solved , was some proxy issues
GL

**Comment by DillonN** [comment]
Will use new exchange soon
