### ISSUE TITLE
Profitablity keeps on dropping to 25% most of the time

### ISSUE THREAD

**Issue by MaenB** [nicehash/NiceHashMiner#2470]
I have an Nvidia gtx 1650 laptop most of the times I start mining with nicehash it starts with around 0.75$ which is normal but after a minute or two a lot of the times it drops to around 0.20$ and stays there.

**Comment by Edu3020** [comment]
- High temperature?
- Limited Power limit (probably battery limitation)
- Windows power managment (On laptops this is very sensitive)
- Invalid shares (high ping to pool)

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
