### ISSUE TITLE
AMD RX 5500 XT mines only nanominer. benchmaring to other plugins gives errors

### ISSUE THREAD

**Issue by michaliskantar** [nicehash/NiceHashMiner#2471]
Dear team,

I m trying to mine using an AMD RX 5500 XT in a W10 pro PC. Both AV and defender are stopped. The only plugin which is working is the nanominer with 7k MH/s instead of 25k about.

Attached are the benchmarking results. Please check and revert with troubleshooting actions

rgrds
Michael
![Screenshot 2021-08-14 195919](https://user-images.githubusercontent.com/80926329/129454746-ae5d7237-df27-497e-8ea5-d2f558784709.jpg)

**Comment by Edu3020** [comment]
Go in "Clear All Speeds" restart the Nh, again in benchmark tab... select only DaggerHashimoto(NBMiner) ->Go in "Custom Algo Settings" -> put custom value in "Behcmark speed (H/s)".. go home a try start mining with ur 5500xt.

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Edu3020** [comment]
For me since version 3.0.7.0 of the NH some benchmark errors no longer exist.

![Screenshot_2](https://user-images.githubusercontent.com/37988669/179027655-f3abe3ca-ffa1-4b08-bd74-75f1f056bf83.png)
