### ISSUE TITLE
Repo dead? 

### ISSUE THREAD

**Issue by kylhuk** [nicehash/NiceHashMiner#2475]
Since 6 months no pull requests were merged, many issues stay open. What's up with that?

**Comment by Nicheuji** [comment]
I think it's because they're working on https://github.com/nicehash/NiceHashQuickMiner

**Comment by xantari** [comment]
@Nicheuji Don't think it's quick miner updates either, that repo also seems to be dead. Something is going on....

**Comment by kylhuk** [comment]
@xantari that's not entirely true, they are still commiting code to Quick Miner. Nontheless, time to move funds away from NiceHash
