### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GhostShot3** [nicehash/NiceHashMiner#2476]
Sometimes i monitor my mining rig through the nicehash websites, i notice the "Connected since" resets his time sometimes on website, the question is:
Is normal?
What "Connected Since" exactly means?
![1](https://user-images.githubusercontent.com/18537420/130545140-3e8076d3-54bb-44d6-ac9d-4979bb7478a0.png)

**Comment by TimyIsCool** [comment]
the uptime of the miner/s

**Comment by GhostShot3** [comment]
How much time is mining?
