### ISSUE TITLE
Welp

### ISSUE THREAD

**Issue by TimyIsCool** [nicehash/NiceHashMiner#2478]
![image](https://user-images.githubusercontent.com/74112751/130654262-185d31cc-7621-4dbd-9afc-ea0b2063d3bb.png)
Keep getting this after i deleted the miner by manual.  Newst miner, windows 10, the nhm_windows...

**Comment by xantari** [comment]
Make sure you exit the program before attempting to run the uninstall and since you deleted files manually you are probably now in an unsupportable state.
