### ISSUE TITLE
GTX970 - No supported devices found

### ISSUE THREAD

**Issue by MonaxDK** [nicehash/NiceHashMiner#248]
When "Optimize for compute performance" is enabled in the video card settings, NHML does not detect the video card. This is written in the Troubleshooting section, but the only thing advised to do is turn off this option. When this option is turned off, the card produces about 3.5 MH in dual mode (Dagger-Lbry). On Win7 where this bug does not exist, this card generally produces 15-16MH.
Is there any solution to this problem?
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1264373/log.txt)

**Comment by luongk** [comment]
There's a solution here: https://github.com/DillonN/NiceHashMiner/issues/11

**Comment by DillonN** [comment]
There is also a section on this at the [end of the troubleshooting page](https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Troubleshooting#nosupportdev)
