### ISSUE TITLE
Lose hash power after installing Nvidea driver

### ISSUE THREAD

**Issue by Polizero** [nicehash/NiceHashMiner#2483]
Hello everybody!

My rig had 1 RX570 8 Gb minning at 28-29MH  and a RX 580 8Gb minning at 30-31MH at daggerhashimoto at NB. I just intalled a RTX 3060 TI LHR driver 471.68 knowing it´s hashpower should be lesser. But most bizarre is hashpower of RX cards dropped to 8MH tops. Seems it is software limited somehow. I tried to unistall RTX driver but nothing has changed.
  Someone can give a hint to solve it?

**Comment by Dohtar1337** [comment]
Reinstall the GPU drivers by following this guide:
https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
