### ISSUE TITLE
Not working card label after system reboot Метка не рабочей карты после перезагрузки системы

### ISSUE THREAD

**Issue by vasy701** [nicehash/NiceHashMiner#2484]
I can not understand which card hangs and does not mine and overloads the system, make sure that after the reboot you can see which card hangs, mark it somehow ??

Not working card label after system reboot Метка не рабочей карты после перезагрузки системы
==
Не могу понять какая карта зависает и не майнит и пергружает систему, сделайте чтоб после перезагрузки видно какая карта виснет, пометьте ее как нибудь??

**Comment by Dohtar1337** [comment]
Not a nicehash miner bug
