### ISSUE TITLE
No load/temp reporting for RX5700 + lolMiner plugin

### ISSUE THREAD

**Issue by QuinTeknoLife** [nicehash/NiceHashMiner#2486]
Hello all,

My friend is running an RX5700, and mining with this card works like a charm, the only issue we're running into is that the temp/load are reporting as 0C/0% while I can clearly tell that the load is not 0% but full throtle.

While troubleshooting this I've tried running lolMiner on its' own and if I do that every 10 or 20 lines it reports statistics which do include temp so I know lolMiner is capable of reporting stats.

`Statistics (02:43:09); Mining: Ethash 
Connected to: eth.2miners.com:2020 
Uptime: 0h 2m 31s 
                     GPU 0   Total
Speed (mh/s):        46.95   46.95
Pool (mh/s):          0.00    0.00
Best Share:            0.0     0.0
Shares (A/S/Hw):     0/0/0   0/0/0
Power (W):           140.7   140.7
Efficiency (mh/s/W):   0.333   0.334
Temp (deg C):           62        
Junction (deg C):       69        
Memory (deg C):         78        
Fan Speed (%):          68        
--------------------------------------------- `

I have attached NHM log.txt as well, for debugging.

![image](https://user-images.githubusercontent.com/45736890/131594779-c00ef160-8b55-428e-8e8c-a0a037891f3b.png)

[log.txt](https://github.com/nicehash/NiceHashMiner/files/7087494/log.txt)

P.S. I realize that this is more or less a duplicate of #2266 but that issue got closed without any information or whatsoever.

**Comment by S74nk0** [comment]
@QuinTeknoLife this should be fixed with the next release. Keep issue open until next release.

**Comment by bovcan** [comment]
for RX 6800 or i guess RX 6000 series is the same. Also no info on the website/dashboard.
