### ISSUE TITLE
Custom Algorithm Power Usage is Ignored by Current Profitibility

### ISSUE THREAD

**Issue by FireCulex** [nicehash/NiceHashMiner#2489]
• I can put 900000000 Power Usage (W) in Custom Algorithm settings and Current Profitability doesn't change
• change Electricity Cost and Current Profitability changes. Possibly GPU Chip Power sensor? Far less than wall meter.
• GPU idles at 30w according to control panel, System idles at 50w according to wall meter, w/ Nicehash GPU shows 90 watts, wall meter shows 200 watts.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
