### ISSUE TITLE
Question: Is the NVIDIA P0 State worth enabling?

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#25]
Anyone use NVIDIA and is it worth enabling?

Will then have to run the app as admin too

**Comment by DillonN** [comment]
It depends on your GPU - it seems for Pascal (10 series) there is no discernible difference, also Pascal GPUs can't be forced into P0 by conventional means.

**Comment by billmcilhargey** [comment]
Fair enough!  I just enabled it, adjusted my shortcut to run as administrator and then re-benchmarked everything

appears to not hurt anything and only helps  (dont mind the little extra power usage for when it needs to)

**Comment by UselessGuru** [comment]
For GTX 1080ti there is a very good reason to disable P2 state: You can overclock the memory to the max :-)
To prevent the card to fall back to P2 I use NVIDIA Prefile Infector 2.1.3.9 and set '5 - common' / 'CUDA - 
 Force P2 state' = off (not all versions can do this). Attached the corresponding setting as file - rename it to .nip.
[SetPstate0_rename2.nip.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1190398/SetPstate0_rename2.nip.txt)
