### ISSUE TITLE
Reducing usage/intensity

### ISSUE THREAD

**Issue by aganorian** [nicehash/NiceHashMiner#251]
Hello, this is not an issue but a help request.
I saw somewhere that we can reduce the way NHL uses the gpu so we can actually use our pc without stutter.

I use a 1060 6gb in my working pc and i need to use the internet and the POS program.
Thing is, everything is so slow when it comes to displaying image.
Is there any value i can use in the algorithms to decrease the intensity just enough so i can use the gpu for 2d things?

**Comment by rthomp10** [comment]
Check the box that says to mine when idle in the settings.

**Comment by aganorian** [comment]
Yes i know that option but i also know folks reduce the intensity th gpu works so it can cope with light tasks without reducing much of the hash/rate
I know DillonN posted this somewhere but i cant seem to find it

would it be the dcri values?

**Comment by jimmyhackers** [comment]
you could ad a second screen rendering gpu (something cheap/low power) or run your monitor off of intergrated gfx if you have them.

bear in mind. even if you only have one pcie x16 slot you could still run a 2nd card on a riser in a smaller pcie slot.

also. if u are cpu mining aswell as gpu mining on the same pc i dont think these methods will work.

**Comment by aganorian** [comment]
Well in my home pc i can use dual gpu for that matter but my store pc doesnt have any 2nd gpu.
If there is any parameter i can use in daggerSIA and daggerLbry please tell me, if not, then i have to endure this slugish pc

**Comment by Olegik-ah** [comment]
For any claymore dual use
-ethi X
Where -ethi 8 - max intensity, -ethi 1 - min intensity

**Comment by aganorian** [comment]
I think i found the sweet spot at intensity 3 :)
thank you, thats what i was asking for :)
just lost 1.5mh/s

**Comment by jimmyhackers** [comment]
reducing your mining load in the way you describe will reduce your profit more so than just clicking the mine when idle option (unless you spend all day on youtube vids and/or serving customers). it wont go back upto full profit unless you tell it to. meaning at (idle/not in use) ur making less than you could.

you could get a reasonable/capable 2nd hand gpu and new gpu riser off of ebay for less than £20-30.

i have a 512mb 8400gs thatll do 1080p youtube vids no probs. you can get these for about a tenner.

 get a gpu that doesnt require any extra power leads for easyness.

**Comment by aganorian** [comment]
Problem is, im constantly using the computer so idling it is not an option and I'm not very comfortable of constantly turning off the program.
Also can't spend more on it, it only makes about €0.75(profit) a day already.
Also it has gone from 80% power to 78% and it made the pc a lot more smooth and only lost 1.5mh/s meaning few cents.

I'm really happy for this workaround :)

**Comment by jimmyhackers** [comment]
75 centsprofit seems low. running it at full all day should bring in more like $1.50 a day

is ur electricity pricey?
it should only really use about 2.4kwh a day. even at 25cents a kwh u should be closer to a dollar a day profit

you could always go on the scrounge for a naff gpu off of a mate for free. ur local tip/dump might even have an old pc u can pillage something from for free.

ive experienced a 10%ish increase in hashpower from my gtx770. by benchmarking/running it while it isnt rendering a screen(the primary gpu).
