### ISSUE TITLE
GTX 1050 Ti Not Recognized 

### ISSUE THREAD

**Issue by Bajabob69** [nicehash/NiceHashMiner#2518]
I am building a new miner using intel, and GTX 1050 ti cards but NHM states there are no supported devices.

Any suggestions?

**Comment by Bajabob69** [comment]
Why ask for help if no one is going to respond...

**Comment by nimmam831** [comment]
Have you installed drivers or using old drivers? Try installing latest nvidia drivers (mine: 510.10)

**Comment by Bajabob69** [comment]
I tried using the drivers that came with the cards. 382.33 and I tried 471.? I have not tried 510.10 (where can I get 510.10)

**Comment by Bajabob69** [comment]
I keep getting NVML missing, I have pasted the NVML.dll file from Windows, System32 to
C:\Program Files\NVIDIA Corporation\NVSMI 

I also placed it into 
C:\Program Files (x86)\NVIDIA Corporation\NVSMI to see if that would work

**Comment by stopspazzing** [comment]
Latest stable driver for your card is here: https://www.nvidia.com/Download/driverResults.aspx/183364/en-us
```
Version:	496.49  WHQL
Release Date:	2021.10.26
Operating System:	Windows 10 64-bit, Windows 11
Language:	English (US)
File Size:	831.22 MB
```

I would recommend running DDU after downloading latest driver, and prevent windows from install drivers automatically until you install your nvidia drivers from installer you downloaded.

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?
