### ISSUE TITLE
view single workers data on graph?

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#252]
after clicking view my stats you get taken to the stanny screen we all know and love.

and you can play with your graphs (i love doing this) to see whats been happening etc etc

is there anyway to view just a single workers "work" on the graph?

i only have 3 workers (soon to be 4) but i imagine loads of people have a lot more than me.....and i think being able to see their work as an individual worker would be very helpful to miners for fault finding issues with "rogue" cards.

good idea? bad idea? thoughts?

**Comment by DillonN** [comment]
I don't believe this is possible currently. However this is a problem with the NiceHash service and not NHML so I will close this
