### ISSUE TITLE
Plug ins are not showing in bench mark or installing

### ISSUE THREAD

**Issue by SanLorTech** [nicehash/NiceHashMiner#2520]
I have been building Mining rigs for over a year. Recently on new rigs i install nicehash, and then go to install plug ins. I get plug in failed to install, and then if i go to benchmark no benchmarks are showing under the GPUs that are installed. 

I have a MSI Z390P-A Motherboard, and AMD RX580 8gb GPUs. I have 3 rigs I have this issue with.

Would appreciate some help.

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by myworkshed** [comment]
This has just shown up for me as well. NHM cross checks NBMiner on startup but won't load any other plugin. when i attempt to install the plugin NH just says in notifications the plugin is not installed. XMrig seems to be fine.

**Comment by Dohtar1337** [comment]
@myworkshed Have you tried disabling antivirus for couple of minutes to see if the AV is deleting the files?

What AV are you using?

**Comment by Dohtar1337** [comment]
No response. Closing.
