### ISSUE TITLE
T-rex miner

### ISSUE THREAD

**Issue by Miiichal** [nicehash/NiceHashMiner#2523]
**Please bring back the Trex miner**, cause better tuning capabilities, than Gminer or NBminer (which are now the only complex miners with more algos - i have nothing against them).
These smear campaings from Nicehash against best miners are not normal :(
Crypto community is here to work together.
Cross-out your shadow and implement Trex back.
**PLEASE**.

**Comment by amiazma** [comment]
Please! <3

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner/blob/master/doc/UserPlugins/README.md
