### ISSUE TITLE
Kawpow Algorithm is not listed in the benchmark.

### ISSUE THREAD

**Issue by Alivezoned** [nicehash/NiceHashMiner#2526]
NBMiner, TTMiner and Zenemy. 
After installing these miner plugins, Kawpow is the only algorithm that is not listed in the benchmark.
Video card used: GTX 1650 Super

**Comment by VratoK** [comment]
Same for GTX 1050 Ti

**Comment by S74nk0** [comment]
Are these systems with a single GPU? KAWPOW minimum requirement is 4GB VRAM. I am guessing that a driver update reduced the usable GPU VRAM.

If you wish to mine KAWPOW you can disable ram limit checks inside the plugin internal settings... but this might cause system crashes.

To change these settings for each plugin find and edit `PluginSupportedAlgorithmsSettings.json` and the settings `use_user_settings` and `enable_unsafe_RAM_limits` to `true`. You can see the example in the picture. Make sure that the JSON file is still valid after editing. These settings are hidden intentionally. If you encounter system crashes after tweaking the internals restore them to the last working state. 
 
![image](https://user-images.githubusercontent.com/1517233/137700480-e526cb74-a0bb-4969-93d1-28446fddafe5.png)

Closing issue
