### ISSUE TITLE
remove TELNET-API

### ISSUE THREAD

**Issue by Miiichal** [nicehash/NiceHashMiner#2529]
NH devs - plase change your plugins not to pass **--api-bind-telnet**
Thank you...

**Comment by amiazma** [comment]
Yes! The extra internal parameters are big problems for your users! :(

**Comment by Miiichal** [comment]
any comment from devs about removing this? :(

**Comment by Miiichal** [comment]
please, i BEG again for remove this
**tnank you**

**Comment by xzakly** [comment]
I have made the changes necessary to fix this, but they still haven't merge i can try to zip de trex.dll and send to you.

Shutdown nicehash and unzip this dll next to the bins and internals folder(**NiceHash Miner\miner_plugins\03f80500-94ec-11ea-a64d-17be303ea466\**) replacing the existing one.

**Comment by Miiichal** [comment]
it would be great, if we should be able to avoid this with any "fine parameter".
Till the time, the Nicehash devs will awake and remove it from the sourcecode :(

**PLEASE - REMOVE IT, really thank you :)**

**Comment by xzakly** [comment]
The problem is with the launch parameter, it's hardcoded and can't be changed.

**Comment by Miiichal** [comment]
one problem in two streams :)

https://github.com/trexminer/T-Rex/issues/859

**Comment by amiazma** [comment]
https://github.com/trexminer/T-Rex/issues/672#issuecomment-948582640

**Comment by xzakly** [comment]
and the solution

https://github.com/nicehash/NiceHashMiner/pull/2531

**Comment by Miiichal** [comment]
> and the solution
> 
> #2531

is this a really solution for the error i wrote previously?

**Comment by xzakly** [comment]
Yes.

**Comment by Miiichal** [comment]
so i have to create TRex.cs and put into the folder structure?
sry for dumb question...

**Comment by xzakly** [comment]
no, thats the source code, you need to compile and pack it into a dll, like the one i uploaded.

**Comment by Miiichal** [comment]
Its funtional workaround, cause you were really quick. Bow before you mate :)
but its not a "system" solution for everyone, because NHdevs are slow (or lazy etc... idk).
:)

**Comment by xzakly** [comment]
yes it is, and if you packed the overclock options that i added you don't even need the afterburner.

https://github.com/nicehash/NiceHashMiner/pull/2531/commits/3f0215c2562290e5b1527b93173cb54b567f2acf

well done and good mining.

**Comment by username1905** [comment]
I'm just a simple mortal... Can a pro send me the dll and tell me where to put it? Thanks in advance!

**Comment by xzakly** [comment]
[MP.TRex.zip](https://github.com/nicehash/NiceHashMiner/files/7687112/MP.TRex.zip)

unzip inside "NiceHash Miner\miner_plugins\03f80500-94ec-11ea-a64d-17be303ea466"

if you don't have trex already, you need to create "03f80500-94ec-11ea-a64d-17be303ea466" folder, and then unzip the file

**Comment by username1905** [comment]
It works! Thank you very much! You just made my day!
