### ISSUE TITLE
Is there anyway to add other mining software?

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#253]
So there is a few other miners and optimized miners that can be used that are not in NiceHash but they do support NiceHash, is there anyway I can go about manually adding them myself? Instructions please :)

**Comment by DillonN** [comment]
New miners require coding experience to add, if you know of more profitable miners please post them and under what conditions they are more profitable (algorithms/GPUs etc)

**Comment by Daimie** [comment]
https://whattomine.com/ shows Diamond (DMD) with Groestl algorithm is the most profitable at the moment for Nvidia GTX 10x0 cards.

Any way to mine this with NHML? Thanks!

**Comment by VParhom** [comment]
Groestl algorithm is not supported in NiceHash.com
see available NH pools here https://new.nicehash.com/algorithm?lang=en
