### ISSUE TITLE
3.0.6.6 continuously installs service

### ISSUE THREAD

**Issue by jamse101** [nicehash/NiceHashMiner#2533]
After updating to 3.0.6.6 I see the following service being installed approximately once every second.

"A service was installed in the system.

Service Name:  R0app_nhm
Service File Name:  C:\nhm_windows_3.0.6.6\app_3.0.6.6\app_nhm.sys
Service Type:  kernel mode driver
Service Start Type:  demand start
Service Account:  "

When I look at Computer Management / Windows Logs / System, there are thousands of Service
Control Manager messages for the above service.

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.6.7
