### ISSUE TITLE
NiceHashMiner 3.0.6.7 can not working lolminer 1.34

### ISSUE THREAD

**Issue by ZRnao** [nicehash/NiceHashMiner#2536]
Hi ,I have some problems when I was using nicehash miner.
After I updating lolminer’s version from1.32a to 1.34 , the whole Program(include lolminer and nicehash miner) work abnormally.
But when I use the same way to update nbminer and gminer , they still work normally.
Please repair lolminer1.34 , it will make lhr vga have higher hashrate.

and i found a bug in Nicehash Miner 3.0.6.7 , use lhr Cards to miner , will Recurring a message (like 123.png) , than will Sporadic crash, 

Thanks for your reading

![123](https://user-images.githubusercontent.com/93125921/138676399-f83c074d-64a4-430e-af26-4fb2cc8a7c92.png)

**Comment by S74nk0** [comment]
speed fluctuation is removed with https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.8.0
