### ISSUE TITLE
Error code 12

### ISSUE THREAD

**Issue by sandisuhirman** [nicehash/NiceHashMiner#2545]
Need help and solution

I've install 2 gpu rtx 3060 and rtx 3060ti have probllem error code 12 didnt heave enough resources. In another gpu. When i install only 1 doesnt problem all work.

I use windows 10 64bit
Ram 8 gb
Nh miner
Gpu driver newest, normal when only 1 gpu.

Bios have enable above 4G
Disable onboard graphic
Disable audio onboard

Have another setting on windows or bios when we want add more than 1 gpu?

Thanks for help

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
