### ISSUE TITLE
NiceHash hangs Cross Reference NBMiner

### ISSUE THREAD

**Issue by grilor** [nicehash/NiceHashMiner#2546]
Nicehase just started this today
Nicehas hangs on loading at "Cross Reference NBMiner" at about 50% of the bar

i have reinstalled the app same thing
i have reinstalled windows then the app same thing

i looked over the GitHub info most recent i seen was april and the thread was closed

any help would be great thanks 
[log.txt](https://github.com/nicehash/NiceHashMiner/files/7449035/log.txt)

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
