### ISSUE TITLE
Claymore's Dual Ethereum AMD+NVIDIA GPU Miner v10.0 (Windows/Linux) 

### ISSUE THREAD

**Issue by Duski78** [nicehash/NiceHashMiner#255]
Latest version is v10.0:

- added assembler kernels for ETH+LBC mining mode (AMD cards only), major speedup for LBC.
- about 1% ETH speedup for Vega cards.
- fixed issues with voltage/clocks management for latest AMD blockchain drivers (not completely).
- new GPU sorting method for NVIDIA cards. Now GPUs are sorted by physical bus index (it matches AfterBurner list of GPUs).
- for ETH+LBC mining mode maximal "dcri" value is 1000 now.
- added "-platform" option.
- added "ESTALE" option support in failover file epools.txt (see "-estale" option for details).
- several minor bug fixes and improvements.

Can you please update Claymore Miner for the next NHML Version?
Thank u so much :)

**Comment by pducharme** [comment]
Did you trial replacing the 9.8 included by this one??

**Comment by chevyroadster** [comment]
I did so far it works, i'm mining with Nvidia.

**Comment by DillonN** [comment]
Will get this added in

**Comment by pducharme** [comment]
Just to confirm @DillonN , Claymore 10.0 not in 1.8.1.2, right ?  (just want to see if I screwed my upgrade 1.8.1.1 -> 1.8.1.2)

**Comment by Nicheuji** [comment]
@pducharme It _seems_ like it since the bin folders are from 1.8.1.1

**Comment by DillonN** [comment]
@pducharme bins haven't changed in 1.8.1.2

**Comment by llang629** [comment]
Thanks for continuing to update this great software!

Can you confirm that the clocking and voltage parameters work in Linux, not just Windows? I've been changing things but not seeing much response. Thanks.
