### ISSUE TITLE
NHM 3.0.6.9 crashing on benchmark

### ISSUE THREAD

**Issue by herrjoo** [nicehash/NiceHashMiner#2552]
I have been using NHM 3.0.6.5 (without any problems but a bit lower hashrate than expected) and upgraded to 3.0.6.9 and during one benchmark my screen had weird blac kstripes and during another it just crashes my PC completely
Already tried reinstalling NHM but problems still occur
I'm using a Zotac 1080 Mini on Windows  10
[log.zip](https://github.com/nicehash/NiceHashMiner/files/7477322/log.zip)

**Comment by remotettl** [comment]
trust me, most profitable is NBminer. rest plugins for now is gona give you much lower hashrates and profits. uninstall rest of plugins and keep NBminer.
