### ISSUE TITLE
SRBMINER is not working since the last 2 versions of NICEHASH

### ISSUE THREAD

**Issue by ThiagoSF7** [nicehash/NiceHashMiner#2554]
SRBMINER is not working, always fails the benchmarks, please fix this because is the most rentable miner in NH

**Comment by ThiagoSF7** [comment]
Is anybody else facing this issue?

**Comment by WilsonRadeon** [comment]
yeap mee too, since the version 3.0.6.6 doesnt work, the version 3.0.6.5 work fine but dont see the temperature of my gpu in version 3.0.6.5, sorry for my english. Hablo mejor español

**Comment by ThiagoSF7** [comment]
Im not even using nicehash anymore, its more profitable to m ine directly now that SRB mner is not working, with SRBMINER i was able to achive 50mh with my vegas 64 now it was not going above 44mh, its a big diference if you have 10 GPUs Vega 64, it represents a 60mh loss, not cool, an it seams that nobody in Nice hash cares, so now i just stop using NH

**Comment by ThiagoSF7** [comment]
Still not working, i can benchmark in all  miners except SRBMINER, keeps saying errorbenchmarc

**Comment by ThiagoSF7** [comment]
Can someone fix this issue please? or upgrade NH?

**Comment by ThiagoSF7** [comment]
Why nobody cares?

**Comment by xzakly** [comment]
You need to disable this option for srbminer to work again.

![image](https://user-images.githubusercontent.com/92794904/142619127-6bd77485-c275-4222-8c99-2a5c396a81ee.png)

**Comment by WilsonRadeon** [comment]
thxxxx, work again but i dont know why i need a vpn for use srbminer when use the other i dont have any problem whit the conection

**Comment by xzakly** [comment]
I don't use vpn and it's working..
For some reason srbminer can't connect with nicehash trough the IP address, but can connect with url.
That option stops nicehash from converting the url to an ip.

**Comment by WilsonRadeon** [comment]
how do for connect with url? a quickly guide

**Comment by xzakly** [comment]
Nicehash does that automatically.
For me, after the update i changed this option and clicked start mining on srbminer, and it worked, did the benchmark and everything..

**Comment by WilsonRadeon** [comment]
ok i try do the benchmark again, thx

**Comment by WilsonRadeon** [comment]
nop doesnt work for me :S, if disable the option "resolve nicehash domain..." the srbminer works but i need a vpn for connect with nicehash and the other way enable the option "resolve nicehash domain..." the srbminer dont work but the other algoritms dont need the vpn for connect. Thx xzakly for the help

**Comment by WilsonRadeon** [comment]
anyway thx for the help xzakly

**Comment by bovcan** [comment]
where did Srbminer go? in version 3.0.7.2. I cant see it anymore

**Comment by Dohtar1337** [comment]
Won't fix/include. This feature or bug might already be fixed or added. Or might not be included due to internal reasons.
