### ISSUE TITLE
Benchmark screen: Status Numbers reversed

### ISSUE THREAD

**Issue by AnalogThinker** [nicehash/NiceHashMiner#2556]
Setup:
Xeon E5-2689 on X79, Windows 10 x64

This is a display issue.
In the Benchmark section, the "Benched" section fractional display format is reversed.
It shows "Total / Completed" instead of "Completed / Total"

![image](https://user-images.githubusercontent.com/67115180/141210783-e8f0cd2e-f22d-432b-a349-0540674e2d41.png)

**Comment by ame235** [comment]
can confirm this is inverted.

**Comment by Dohtar1337** [comment]
Added to backlog as a bug. Closing
