### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Chidsuey** [nicehash/NiceHashMiner#2557]
Sometime this week Nicehash stopped working for me. I've recently updated to the latest version to no avail. The window opens and when I click to login, the new window is white. If I resize the window it will say "Loading, please wait...", and nothing ever happens. If I close that window, I can eventually get Nicehash to open, but I also can't find anywhere in the menus to sign in.

**Comment by remotettl** [comment]
happened to me few times. open task manager, kill nice hash process, try agan. if problem remains, try use phone and mobile app to add new rig, just use QR code on screen before you press log in. sure, you will get new, different rig and need to rename it afterwards and change all settings, but it will work.

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
