### ISSUE TITLE
Benchmarks always run in hidden windows regardless of "Hide Mining Windows" setting

### ISSUE THREAD

**Issue by llamasoft** [nicehash/NiceHashMiner#2559]
NiceHash Miner v3.0.6.5 running on Windows 10.

When running benchmarks, the miner window is always hidden regardless of the "Hide Mining Windows" setting.  
This makes it difficult to troubleshoot why a benchmark failed.

**Comment by Dohtar1337** [comment]
This is expected behavior. Will not fix.
