### ISSUE TITLE
pool connect lost

### ISSUE THREAD

**Issue by 1morr** [nicehash/NiceHashMiner#256]
tht black box say  pool connect lost , wait 10s before try 
what is the problom?

**Comment by chevyroadster** [comment]
If you're using Brazil - Sao Paulo, it's down for the moment.

**Comment by 1morr** [comment]
Im using China - HK

**Comment by chevyroadster** [comment]
If you're mining Cryptonight (CPU), I've the same and it's normal and not related to NHML.
