### ISSUE TITLE
Benchmarks always run "Standard" benchmark type regardless of selection

### ISSUE THREAD

**Issue by llamasoft** [nicehash/NiceHashMiner#2561]
NiceHash Miner v3.0.6.9 running on Windows 10.

Regardless of what benchmark type you select on the benchmark screen, it always runs the "Standard" type instead of "Precise".  
You can verify this by modifying the `MinerBenchmarkTimeSettings.json` files to have different time values from the default.  When you run the benchmark, the `log.txt` file will show it using the "Standard" benchmark timings instead of "Precise" or "Quick".

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
