### ISSUE TITLE
"Share Above Target" Error, "DAG - Verification failed", "Rejected Share"

### ISSUE THREAD

**Issue by BGFront** [nicehash/NiceHashMiner#2565]
Hello
From the last night i am fighting this problem
![Screenshot 2021-11-19 210440](https://user-images.githubusercontent.com/75897984/142677989-21b63e35-2beb-4d7f-bd71-80d327200ff3.png)
![Screenshot 2021-11-19 205324](https://user-images.githubusercontent.com/75897984/142678014-d86b919a-83c9-4375-8636-ced8acf2792c.png)
![Screenshot 2021-11-19 210021](https://user-images.githubusercontent.com/75897984/142678024-f863b249-e46a-41d7-b89f-c0994004f344.png)
For some reason i can't mine eth, when i try dual mining eth+rvn, i am mining only the rvn. All of my shares of eth are getting rejected, 100% like in the photo.
In t-rex miner i got "Share Above Target", in NBMiner i got first "DAG - Verification failed" and then "Share Above Target" i tried to lower the memory clock and power limit but nothing has changed and with these setting i mean only memory clock - 1000 and pl from 75-82 i have been mining whole week without any problems. The card is 3080TI MSI SUPREME X. The previous day i was mining like 88-90mh with no problems. The temps were cold i mean core temp around 40 and the memory temp around 80. I tried getting more virtual memory from my ssd but nothing has changed.
:

**Comment by Dohtar1337** [comment]
If DAG generation failed, you are using too high OC settings. 

Some miners could be better optimized than others. Try lowering mem OC slightly

**Comment by Dohtar1337** [comment]
No response. Closing.
