### ISSUE TITLE
nicehash miner says that QWMI wervice is disabled but it is running

### ISSUE THREAD

**Issue by eazy27a** [nicehash/NiceHashMiner#2569]
![nicehasherror](https://user-images.githubusercontent.com/94875716/142951216-358ac096-51c7-48c4-b515-4e84cb16bc16.png)

this is the error I get when I try to run Nicehash.  Problem started when I updated to 3.06.9 but I have tried reinstalling 3.0.6.5 but now I get same error.
I have manually stopped WMI and restarted but nothing seems to help

**Comment by Dohtar1337** [comment]
Moved to Backlog.
