### ISSUE TITLE
Looking for a .NET developer!

### ISSUE THREAD

**Issue by DillonN** [nicehash/NiceHashMiner#257]
We are looking to increase the size of the NiceHash Miner Legacy development team! If you are a .NET developer and are interested in joining the team, please send an email to dillon_newell@live.ca with your credentials.

Responsibilities include providing support, implementing fixes or minor enhancements, and coordinating on large updates.

Preference is given to Russian speakers!

**Comment by adem4ik** [comment]
I've posted a link to this issue on quite popular Russian mining site - http://miningclub.info/threads/nicehash-miner-legacy.13302/page-8#post-343436

**Comment by DillonN** [comment]
@adem4ik thanks!
