### ISSUE TITLE
NBminer always mode 2

### ISSUE THREAD

**Issue by clarocha** [nicehash/NiceHashMiner#2570]
Since last NBminer auto update to 39.7 (I was already using it before) mode is stuck in mode 2 lhr 71. Even when forcing it with -lhr-mode 1 -lhr 74, continues in mode 2.

**Comment by Underc0vernerd** [comment]
Im having the same issue.

**Comment by clarocha** [comment]
Found out what the problem was... You have to had a "-" in the beginning   --lhr-mode 1 -lhr 74.

**Comment by Underc0vernerd** [comment]
You are awesome. I coped your text exactly from above and it worked perfectly.
