### ISSUE TITLE
Version rollback overnight for NBminer

### ISSUE THREAD

**Issue by gilgamesh42069** [nicehash/NiceHashMiner#2571]
I am using NHM as my mining tool. I had manually updated to NBminer v40.1 upon yesterdays release. Overnight there seems to have been a rollback to v39.7. I think I might have left an update toggle on somewhere. I have since tried to overwrite the files within the NBminer folder using this updated version but am always stuck with v39.7. I have uninstalled NHM v3.0.6.9 and tried to do the same thing, with no success. Even installing NHM v3.0.6.8 has not seen any change.

At this stage I am at a loss as to why/what happened.

Further to this I woke up to find my 3080 XC3 Ultra (LHR) was not detected, fans off but drawing full power according to my MSI afterburner settings as detected in CPUID HWMonitor. This is my secondary card and the rollback (or whatever happened) I think caused this issue. I have a 3090 Eagle as the primary which had no issues.

I am currently using the commands --lhr-mode 1 --lhr 73.2 --lhr-reduce-value 0.1 --lhr-reduce-limit 12 with locked core clock and +1300 to memory with power limited to 74% (note the -- are from the v40.1 entries). In v39.7 I fully believe locks were being missed for me, independent of the OC settings I use. As such, the power to the card would randomly drop to ~40-50% dropping the hash in half (~72->42). There was no lock occurring from the display.

![nbminer](https://user-images.githubusercontent.com/95007093/143372099-bf4bfaa2-2b77-444d-b272-968d1c91ac9b.PNG)

Any ideas how to update back to v40.1 or what might have occurred?

Thanks in advance.

**Comment by bovcan** [comment]
download nbminer and extract it to folder

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?
