### ISSUE TITLE
中国境内现在无法运行nicehash   提示网络错误，有什么解决的办法么？

### ISSUE THREAD

**Issue by guardianwolf123** [nicehash/NiceHashMiner#2573]

**Comment by rain-lg** [comment]
这个是dns污染导致的，希望社区能够添加代理功能

**Comment by guardianwolf123** [comment]
不知道什么时候能修好

**Comment by i-m-patrick** [comment]
NHMWS not connected Not connected to NHMWS.Please check your internet connection

**Comment by guardianwolf123** [comment]
> NHMWS 未连接 未连接到 NHMWS。请检查您的互联网连接

thank you!!!
