### ISSUE TITLE
NHM won't recognize 1660 (secondary GPU)

### ISSUE THREAD

**Issue by MrAntza99** [nicehash/NiceHashMiner#2574]
GeForce Experience:   (1660 is with ricer adapter, 3060 Ti directly on motherboard)
![image](https://user-images.githubusercontent.com/43236706/143615372-b8369320-dfb8-4bbf-864d-213a796490e2.png)

NHMiner won't recognize 1660 (I've used it with QuickMiner when it was main/only GPU)
![image](https://user-images.githubusercontent.com/43236706/143615315-66066495-8b6d-4b71-a47b-92acfcd5927d.png)

GeForce Drivers 496.76 and NHMiner 3.0.6.9 is just freshlydownloaded, PC restarted and seems to be up-to-date 
Plugins: https://i.imgur.com/rKxVNZm.png

Report? 4fe2eaf7-f6dd-41a1-89a7-2d83f2e2f2ab

**Comment by remotettl** [comment]
not an expert but id say its connections or power supply unit, perhaps. depends how big you have PSU and sequence of gpu. assume rtx3060 is first, and then comes 1660. try switch them around or put 1660 on motherboard and see if it works alone. then put rtx on rinser and see results. switching around always brings new info.

**Comment by Dohtar1337** [comment]
Reinstall the GPU drivers by following this guide:
https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers

Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
