### ISSUE TITLE
problema nicehash app non riconosce piu gpu Rx 580 8gb

### ISSUE THREAD

**Issue by marcello82** [nicehash/NiceHashMiner#2577]
hi all, i have a problem with nicehash program, first it worked perfectly, then suddenly it doesn't start and tells me # no supported device detected # i did the test with another miner program and the gpu rx 580 8gb works, does anyone know how to fix it, i am fine and i would like to continue using nicehash. thank you all.

salve a tutti, ho un problema con il programma nicehash, prima funzionava alla perfezione, poi all improvviso non si avvia e mi dice # nessun dispositivo supportato rilevato# ho fatto la prova con un altro programma di miner e la gpu rx 580 8gb funziona , qualcuno sa come risolvere , mi trovo bene e vorrei continuare ad usare nicehash. grazie a tutti.

**Comment by Dohtar1337** [comment]
Try this: https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
