### ISSUE TITLE
Missing Optimize button

### ISSUE THREAD

**Issue by Cocomunky** [nicehash/NiceHashMiner#2578]
Hiya! Been using NiceHash for only a couple of days, but I can't seem to get the optimize button to show up on my rig manager, as seen in the image below:  
![image](https://user-images.githubusercontent.com/24192540/145869522-1e3388d7-e13d-4226-b5d8-9f6dd92c2348.png)

I tried to use older Nvidia drivers as suggested in many places, but I get an error that they are incompatible with my version of windows (I'm upgraded to win11) and haven't been able to find any other clear solutions. Thanks!

**Comment by jasonr93** [comment]
I have the same issue, only my gpu is GeForce RTX 2080 Super. Older drivers didn't work for me either, as well as standard driver versions.
