### ISSUE TITLE
API Server Failed to Start

### ISSUE THREAD

**Issue by Hotrod369** [nicehash/NiceHashMiner#2589]
This started about a week ago. None of the 3rd party apps will start the API server. They all give me a message saying that the address is protected or the API server failed to start. However if I download the 3rd party apps and run them on nicehashes stratum they will all start the API server. I've tried rolling back nicehash to an older version but this didn't help. As I used an uninstaller app to uninstall the Nicehash miner then did a fresh clean install I lost all my benchmarks and now just get error benchmarking messages for all the apps and algos. The only other API I use that I can think of is the Jackett API for my torrents and it has not had an issue. I'm attaching the log file maybe something in it will help. Any help would be greatly appreciated.

Windows 10
AMD Ryzen 5 3600X
GTX 1660 Super connected to monitor
GTX1660ti
GTX 1050ti connected via riser
Gigabyte X470 Aorus Gaming 7 wifi motherboard
Rosewill Photon 1050 1000watt PSU

[log.txt](https://github.com/nicehash/NiceHashMiner/files/7795804/log.txt)

**Comment by xzakly** [comment]
I'm not a dev but have to tried reinstalling the drivers?

**Comment by dethknite** [comment]
From what I see in the logs.. there are NVidia errors getting power usage. I would use DDU to uninstall your NVidia drivers and then reinstall them.

Might be able to disable all the Device Monitoring settings in the Advanced Settings in NiceHashMiner as well and get by.

**Comment by Hotrod369** [comment]
Sorry, I should have come back and posted that I got it fixed. I reset my network adapter and that seems to have corrected the problem.
