### ISSUE TITLE
1.8.1.2 - Missing Preferences Text

### ISSUE THREAD

**Issue by 3zero2** [nicehash/NiceHashMiner#259]
In the latest version of NHML there is space for a new setting which has it's text missing.

![capture](https://user-images.githubusercontent.com/6965396/29998926-49244ccc-9037-11e7-9f87-5ef8a0fa0c33.PNG)

This is on an English version of Windows.

**Comment by drkskwlkr** [comment]
@3zero2 These strings are related to the newly implemented IFTTT integration. For some reason they are not merged with master.

Try to download the English language file from the [IFTTT_Integration](https://github.com/kenman345/NiceHashMinerLegacy/blob/IFTTT_Integration/NiceHashMiner/langs/en.lang) branch and the texts will show up.

@DillonN Please see above.

**Comment by DillonN** [comment]
Ah they didn't end up in the final zip, I'll put up a new zip for that

**Comment by DillonN** [comment]
This should be fixed with the new uploaded zip, thanks for reporting!
