### ISSUE TITLE
NiceHash Miner Crashes if core_clock / mem_clock is unable to be detected

### ISSUE THREAD

**Issue by lrehmann** [nicehash/NiceHashMiner#2592]
While attempting to run NiceHash Miner on a 2019 Macbook Pro 16" running Windows 10 via Bootcamp + Nvidia RTX installed in a Core X Chroma eGPU, I was unable to get the miner running. 
The initial startup of the program was crashing at "Cross Referencing" with NBMiner.
After investigating the logs, the last error presented in the file was:
 [ERROR] [NHWebSocket] Attempted to divide by zero.

While inspecting the NBMiner bin files, I located a json list of the devices, identifying the two GPUs in the system:
`{
    "devices": [
        {
            "compute_capability": 1001,
            "core_clock": 0,
            "cu_count": 24,
            "device_id": 0,
            "mem_clock": 0,
            "memory": 8176,
            "name": "AMD Radeon Pro 5500M",
            "pci_bus_id": 3
        },
        {
            "compute_capability": 86,
            "core_clock": 1665,
            "cu_count": 80,
            "device_id": 1,
            "mem_clock": 9501,
            "memory": 12287,
            "name": "NVIDIA GeForce RTX 3080 Ti",
            "pci_bus_id": 12
        }
    ]
}
`

For the AMD Radeon Pro, core_clock and mem_clock are both reading out as zero. Since this was a bit fishy to me and I suspected it was causing the software crash, I disabled the AMD Radeon card. After, I was able to get NiceHash running on just the RTX card.

I suspect there is some reference to core_clock and/or mem_clock in a denominator division argument.  Hopefully, these can be removed so the NHWebSocket doesn't crash during the startup process.

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.

Running NHM on Mac is not supported.
