### ISSUE TITLE
Overclock Parameters - NB Miner - cannot reset to default clock 

### ISSUE THREAD

**Issue by mrventerj** [nicehash/NiceHashMiner#2597]
3060 TI LHR -ETH
Parameters:
--lhr-mode 1 --lhr 75.3 --cclock @1350 --mclock 1300  --lhr-reduce-value 0.2 --fan 80

When stopping the miner, and trying to reset the core clock /memory to default with MSI afterburner, it does not reset the core clock.

The core clock is stuck at 1350, I have to reboot my PC to reset it.

Anybody know a fix or can the nicehash team add a reset parament's on pause/stop mining?

**Comment by mrventerj** [comment]
For anyone who has the same issue, CMD - with Admin, run the following: nvidia-smi -rgc
This will reset the core clock, I set it up as a .bat file. @nicehashdev, can this be worked into Nicehash?

**Comment by S74nk0** [comment]
@mrventerj you can already do this. Every plugin has a file within the internals folder a setting called `MinerCustomActionSettings.json` and here you can set arbitrary scripts before running and after running the miner. 

# Start stop calculator example 

Here is an example setting that runs a Calculator on start and stop when DaggerHashimoto is mining (this of course is just as an example to see it working).

### Under the plugins page open the internals for your selected plugin (I am using GMiner)
![image](https://user-images.githubusercontent.com/1517233/150541732-20ab2056-1913-4855-84b9-3bc5e6f276f8.png)

### Open internals
![image](https://user-images.githubusercontent.com/1517233/150542030-bfc6da37-8e35-4cef-92da-3be82146857a.png)


### Open and edit `MinerCustomActionSettings.json` 
![image](https://user-images.githubusercontent.com/1517233/150542112-86b077df-dd47-4a49-8744-0089ed13273c.png)

Settings that open the calculator before and after starting the miner. NOTE you must set `"use_user_settings"` to `true`
```
{
  "use_user_settings": true,
  "algorithm_custom_actions": {
      "DaggerHashimoto": {
          "start": "calc",
          "wait_start_exec": true,
          "stop": "calc",
          "wait_stop_exec": false
      }
  }
}
```
Settings with comments
```
{
  // use_user_settings must be true 
  "use_user_settings": true,
  // JSON object where keys is algorithm name https://github.com/nicehash/NiceHashMiner/blob/master/src/NHM.Common/Enums/AlgorithmType.cs#L55
  // and the object where you put your desired executables or bat scripts you want to run before starting or after starting the miner
  "algorithm_custom_actions": {
      // DaggerHashimoto algo name as key 
      "DaggerHashimoto": {
          "start": "calc", // start Windows calculator before running the actual miner
          "wait_start_exec": true, // this indicates if it should wait for the start script to finish executing
          "stop": "calc", // stop Windows calculator before running the actual miner
          "wait_stop_exec": false  // this indicates if it should wait for the start script to finish executing
      }
  }
}
```

If you did everything correctly you should see calculator app open when starting/stopping GMiner.


Now of course you should replace the `"calc"` text with the full path of your bat file. So for each algorithm you can make custom bat scripts. NHM passes GPU BUS IDs as parameters to the script (e.g. `33,47` would mean GPU with bus id 33 and 47 are going to be used for mining). You can add custom logic based on what devices are used.

I will write full documentation regarding this hidden feature and give more examples beyond the "Hello World" calculator example.

Please give feedback if I was clear.

EDIT:
After changing internals you must restart NiceHash Miner in order for the changes to take effect.

**Comment by LUCIOUS999** [comment]
Just run in Subnets with loops or in Sandbox. With Sandbox you can use Bash and really give your shit a power boost. And it continues without fail just use common deductions you could find on Google.

**Comment by nosstek** [comment]
I was trying example with "calc" and it's working.
But not with same "calc" in .bat file.
"nvidia-smi -rgc" is also not working. Probably due to that it needs admin rights.
Miner for sure have this rights since it is able to apply overclock.
Ideally this command should be:
"nvidia-smi -rgc & nvidia-smi -rmc"
for both core and memory overclock reset.

I wasn't able to find any command to reset fan curve.
Do you have any suggestions?

**Comment by Dohtar1337** [comment]
The comment above shows how to fix this issue. Closing
