### ISSUE TITLE
NHM crashes on startup with 2019 Apple Mac Pro (Bootcamp)

### ISSUE THREAD

**Issue by corybory** [nicehash/NiceHashMiner#2598]
NHM 3.6.9  crashes repeatedly on startup while installing plugins.  I think this may have something to do with the clock speeds on the mac being reported as 0. 

Windows 10 
GPUs: AMD ProVega 2, AMD W5700x, Nvidia GTX 1080
CPU: Xeon W3245
Ram: 96GB

**Comment by Dohtar1337** [comment]
NHM is not supported on Macs.
