### ISSUE TITLE
"miner speed fluctuation" "Miner restarted" infinite loop

### ISSUE THREAD

**Issue by darkreaper2047** [nicehash/NiceHashMiner#2601]
when mining with a Sapphire 6800XT nitro+ constantly get "miner restarted" and "Miner speed fluctuation" warnings on current version of NHM (3.0.6.8+ that I know of), the miner itself reports a stable speed until NHM closes it. Precise benchmark does nothing to solve the issue. Manual benchmark does precisely nothing to solve the problem. The miner plugins are not the issue. The algorithm is not the issue.
log is available 

Spec:
9900k
maximus hero xi
gigabyte 2080ti
sapphire 6800xt nitro+
windows 10 64-bit
NHM 3.0.6.9, plugins are updated by NHM.
[log.1 - Copy.txt](https://github.com/nicehash/NiceHashMiner/files/7894563/log.1.-.Copy.txt)

**Comment by darkreaper2047** [comment]
is it possible NHM is reporting against the accepted speed rather than the reported speed when it comes to the 6800XT?

**Comment by 09prapai** [comment]
ช้าว[37tW1zZ4Xr4UbdvgnhdyYF6Euu8XFgcTbD]() ``

**Comment by hub24f** [comment]
I use a RTX 3080 that is LHR. I always get the speed fluctuation message. The mining profit is lower (sometimes much lower) than the benchmarks. Ran the precise benchmarks several times.

**Comment by LUCIOUS999** [comment]
If your caught in a loop you need to make sure to find an algorithm in binary for xy= 0 z=1 or it creates a swarchild black hole. (Time singularity) 
If you lift the singularity off the plane even .1 it will go into perfect rotation and take you out of the 13 dimensional time lock.

**Comment by LUCIOUS999** [comment]
If z=0 the gravity of the singularity is gonna loop. X and y don't matter give it some wings to flux like 9.36936 repeating. That's the perfect DNA structure in binary to the 3rd.

**Comment by S74nk0** [comment]
this is now removed in https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.8.0
