### ISSUE TITLE
1.8.1.2 - Neoscrypt on GTX970 and 1080Ti

### ISSUE THREAD

**Issue by MonaxDK** [nicehash/NiceHashMiner#261]
Apparently, ccminer_tpruvot is not suitable for older video cards.
GTX 970, NHML 1.8.1.1
![970-1811](https://user-images.githubusercontent.com/29005588/29999608-d78caaf2-9057-11e7-8082-e83c3f93d1b4.png)
GTX 970, NHML 1.8.1.2
![970-1812](https://user-images.githubusercontent.com/29005588/29999613-04e00274-9058-11e7-8870-b1c364735d62.png)

But for 1080Ti real miracles happen :)
3x1080Ti NHML 1.8.1.1
![1080-1811](https://user-images.githubusercontent.com/29005588/29999615-17100cdc-9058-11e7-8a36-8d8bbaab9f95.png)
3x1080Ti NHML 1.8.1.2
![1080-1812](https://user-images.githubusercontent.com/29005588/29999616-1fb6a79c-9058-11e7-867a-f664ea771e87.png)

**Comment by luongk** [comment]
That wasn't my experience with my 980GTX, for what it's worth - https://github.com/nicehash/NiceHashMinerLegacy/issues/235

**Comment by rickrs** [comment]
i dont know what happned

but, 1.8.1.2 my profit is $usd/day  2.49 ( half hour test)
and  1.8.1.1 my profit is $usd/day 3.60 ( half hour test)

i checked again, same results.

i have one gtx 1080 ti 11 gb. windows 10, nvidia driver 385.28,  16 gb ram,
i7 first generation

overclock none.

**Comment by luongk** [comment]
You can't really go by USD - the price of BTC/crypto is so variable.

Has your hash rate changed?

**Comment by MaKCuMyC** [comment]
I got two EVGA GTX 980 Ti
with 1.8.1.1 I had about ~0.88 MH/s on each.
with 1.8.1.2 I have about ~0.75 MH/s on each.

please, use correct miner for NVIDIA 9xx.

**Comment by DillonN** [comment]
Sorry tpruvot is giving you less performance on 900 cards, I'll get this fixed in next version

As a workaround for now you could copy ccminer_neoscrypt over the tpruvot ccminer.exe, but that could hamper other algorithms

**Comment by MonaxDK** [comment]
Not a big problem, neoscrypt is never the most profitable algorithm on 9 series anyway.
In fact, given the difference in performance on 10 series cards, it is very interesting if other algorithms can benefit from the use of tpruvot?

**Comment by VParhom** [comment]
Gigabyte GTX 1070 G1 Gaming

i replace miner in folder NHML-1.8.1.1\bin\ccminer_neoscrypt to KlauT-ccminer v.8.13
![1811](https://user-images.githubusercontent.com/31612825/30016208-d58eccfc-915c-11e7-9ec8-e686c6db574e.jpg)

in version 1.8.1.2, I get a much smaller hash
![1812](https://user-images.githubusercontent.com/31612825/30016525-32012416-915e-11e7-8f22-a8502e4c9a91.jpg)

in version 1.8.1.2 the possibility of substitution of a miner in a folder was disabled

maybe it's worth making a customizable path to the right miner?

**Comment by adem4ik** [comment]
well Klaust's ccminer gives me better hashes too, for about 10%.

I thinks there should be multiple miners for Neoscrypt, so users can use Benchmark and NHML will choose the best solution for everyone.

**Comment by VParhom** [comment]
and add one more screenshot with ccminer-alexis78...
![alexis](https://user-images.githubusercontent.com/31612825/30037927-51460656-91c8-11e7-8fb5-643bbe828f42.jpg)

**Comment by ChriscomIT** [comment]
@adem4ik Yeah that looks like a real good solution especially with multi GPU setups in mind.

**Comment by MonaxDK** [comment]
Perhaps it is worth having the option of selecting a miner for each algorithm, not just for Neoscrypt?
Given that unexpectedly on another miner you can get 4x hash rate...

**Comment by dinicthis** [comment]
That would be great. Equihash now has a choice of a couple or maybe more? EWBF rocks, for me, 350+ sol/s on a 980.

**Comment by dinicthis** [comment]
And all these things are why we use NHML and not NHM. NHM gives you no choice but to put up with lower-profit mining. NHML allows you to choose the algo and device.

**Comment by DillonN** [comment]
In the next version, there will be .JSON files generated by NHML that you can edit to change which ccminer fork is used on each device family

Thank you for reporting faster miners though!

**Comment by VParhom** [comment]
I think it is better to make it possible for every miner to test all the algorithms available on the NH pool.

and then, according to the results of the benchmark, you will see which miner on which hardware is the best

sorry for my bad English :)

**Comment by VParhom** [comment]
Here is an example of the result of the NemosMiner-v2.1-Zpool benchmark for 2x GTX 1070
sorted by the current profitability
![nemos](https://user-images.githubusercontent.com/31612825/30148293-6e08a836-93ab-11e7-8a73-31912130406c.jpg)

**Comment by MonaxDK** [comment]
It would be fantastic if NHML had such a benchmark.
It's very difficult to manually test all the algorithms on all miners ...

**Comment by VParhom** [comment]
I do not do benchmarking of every video card on all the rigs in NHML, I do a benchmark for one video card on one of the rigs, and then I copy the results to the remaining .json files in all the rigs.

**Comment by MonaxDK** [comment]
If such a benchmark is difficult to integrate into NHML, perhaps it's worth creating a separate topic, and invite users to share the results of their benchmarks in Zpool? Thus, it will be possible to collect statistics which miners work faster on certain video cards.
Here are my results for 3x 1080Ti
![bench](https://user-images.githubusercontent.com/29005588/30215029-36c3dc3a-94b7-11e7-9cce-823b79f74e03.png)
Not all miners / algorithms have been tested, because Zpool is buggy :)
