### ISSUE TITLE
NBMiner , fluctuations detected, miner continuous restart

### ISSUE THREAD

**Issue by Francisco42506633** [nicehash/NiceHashMiner#2610]
The nicehash miner, when using nbminer with an rtx 3060 lhr, I have problems with speed fluctuations which leads to the constant restart of the miner, I tried everything recommended and nothing works, I need help.
Additionally I want to know if there is any correct OC for a 3060 lhr.
Thanks a lot

**Comment by LUCIOUS999** [comment]
Try a non-eludican array. (Non-linear)
Just find advanced algorithms that don't use the value 0. 
I know wiki has some wild ones.

**Comment by Dohtar1337** [comment]
You can ignore these fluctuation notifications. They will not restart the miner.
