### ISSUE TITLE
Not able to set power modes for all devices

### ISSUE THREAD

**Issue by Waxxx333** [nicehash/NiceHashMiner#2611]
I just started using Nicehash Miner(not Quick Miner) for the NBminer plugin day before yesterday. I had trouble changing the power presets at first, but I found [this](https://www.nicehash.com/support/mining-help/nicehash-miner/setting-tdp-power-mode-does-not-work-in-rig-manager) and after following it, I was quickly able to change the power preset to low. Today, however, when I opened my dashboard on the website, it said there was an update so I downloaded and installed it. Now I cannot adjust my power levels again. Not even following that guide. It just won't happen. I get ***"Not able to set power modes for all devices"*** and it's really aggravating me. Is there something else I should be trying ? I even tried uninstalling Nicehash Miner completely and reinstalling the older version but the older version wasn't working at all when I tried that route. Some help would be greatly appreciated. 

EDIT:
I also tried adding Nicehash as an exclusion to Winblows Defender thinking that maybe it was blocking the request to change power settings and that didn't help. #2611

**Comment by ame235** [comment]
same here on all three different rigs. this on version 3.0.7.0 (worked before)

**Comment by Waxxx333** [comment]
>  this on version 3.0.7.0 (worked before)

I followed that guide with it the day before on the previous version and it worked fine. Opened Nicehash the next day, updated NHM, went to set it up and I lost the ability to. It's frustrating me to say the least. Even more so because on Reddit, on posts that were made quite a while back, Nicehash was commenting and saying "We're working on this issue" and here we are with it again.
[6 months ago](https://www.reddit.com/r/NiceHash/comments/owdsgp/not_able_for_set_power_mode_in_all_devices/)
[1 year ago](https://www.reddit.com/r/NiceHash/comments/kyglp1/not_able_to_set_power_mode_on_all_devices/)
[3 years ago](https://www.reddit.com/r/NiceHash/comments/hm952y/unable_to_change_power_mode_to_low_or_medium)

**Comment by Dohtar1337** [comment]
Fixed

**Comment by coolguy** [comment]
Not working on Win11

**Comment by coolguy** [comment]
I followed online instruction and turned off "disable device power mode settings" on Advanced settings. It does not work.

Nicehash v3.0.8.2 on Windows 11. 

Actually, it never worked for any previous versions.
