### ISSUE TITLE
GMinerCuda9.0+ Fails to start mining

### ISSUE THREAD

**Issue by darylvaldez** [nicehash/NiceHashMiner#2613]
**OS:** Windows 11 Home 10.0.22000 Build 22000
**RTX 3070 Laptop GPU 8GB, 32 GB RAM**
**NiceHashMinerVersion:** 3.0.7.0
**GMinerCuda9.0+ Fails to start mining. Previously working when I was still in windows 10.** 
![minererror](https://user-images.githubusercontent.com/44500879/153691818-16444bba-4569-4548-be58-509a94055bcf.png)
But I've already added the from the AppData NiceHash folder in defender exclusions.

**I tried:**
Uninstalling gminer plugin, then restarting NHM then installing gminer plugin again
Adding custom algorithm settings (just the benchmark speed, and power usage)

**But so far, only excavator seems to be working.**

Fresh logs after failure to mine with gminercuda plugin:
![log1](https://user-images.githubusercontent.com/44500879/153691982-055f6d66-863a-4b1e-8697-019950ba4c2f.png)
![log2](https://user-images.githubusercontent.com/44500879/153691984-1524b300-98cf-4af3-a143-2e527f50d0bb.png)
![log3](https://user-images.githubusercontent.com/44500879/153691987-0f69673b-48d1-4591-806c-15b40f342f3b.png)
![log4](https://user-images.githubusercontent.com/44500879/153691990-cf897099-0bec-4f7f-89c5-e0c27ef93808.png)

**Comment by Dohtar1337** [comment]
Not related to NHM. Probably AV is blocking something.
