### ISSUE TITLE
My rig crashes woth this last 50 lines. Anyone that can help me?

### ISSUE THREAD

**Issue by PellePettersson** [nicehash/NiceHashMiner#2618]
=== Last 50 lines of /var/log/miner/phoenixminer/phoenixminer.log ===
2022.02.15:18:57:13.971: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x9c3be492250a98cdf11527b2f84b0e4d8d0e77a34ad4fa9a81cee9d6239f046c","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd75"]}
2022.02.15:18:57:13.971: eths Eth: New job #9c3be492 from eth.2miners.com:2020; diff: 8726MH
2022.02.15:18:57:14.139: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x10c14c4e5608886044a28a86c81f3ec617b9208198d3cf12cca141d235a0eed7","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd75"]}
2022.02.15:18:57:14.139: eths Eth: New job #10c14c4e from eth.2miners.com:2020; diff: 8726MH
2022.02.15:18:57:15.441: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x56bf85a6eb4ced3e0126d9ba85f611ff0a38be705e3644f12972f7781676c73b","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd76"]}
2022.02.15:18:57:15.442: eths Eth: New job #56bf85a6 from eth.2miners.com:2020; diff: 8726MH
2022.02.15:18:57:15.603: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0xb98d3fa444551ae7ff087fb564d555c93a17384dba56854d8c688e7f38827ef5","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd76"]}
2022.02.15:18:57:15.603: eths Eth: New job #b98d3fa4 from eth.2miners.com:2020; diff: 8726MH
2022.02.15:18:57:15.976: GPU1 Eth: GPU1: ETH share found!
2022.02.15:18:57:15.976: eths Eth: Send: {"id":4,"jsonrpc":"2.0","method":"eth_submitWork","params":["0x51fee18745c426db","0xb98d3fa444551ae7ff087fb564d555c93a17384dba56854d8c688e7f38827ef5","0x8f5c59a4324078c79ba3463f7706a304141246d3e6df6bbd6b176c45b3acfe9b"]}

2022.02.15:18:57:15.976: eths Eth: Share actual difficulty: 22.1 GH (!)
2022.02.15:18:57:16.258: eths Eth: Received: {"id":4,"jsonrpc":"2.0","result":true,"error":null}
2022.02.15:18:57:16.258: eths Eth: Share accepted in 282 ms
2022.02.15:18:57:16.450: eths Eth: Send: {"id":5,"jsonrpc":"2.0","method":"eth_getWork","params":[]}

2022.02.15:18:57:16.450: eths Eth: Send: {"id":6,"jsonrpc":"2.0","method":"eth_submitHashrate","params":["0x10ef33be","0x0fb81bb66bfec272d51f82536b183cbb02b2ab89d7e546729750376158e0554b"]}

2022.02.15:18:57:16.480: eths Eth: Received: {"id":5,"jsonrpc":"2.0","result":["0xb98d3fa444551ae7ff087fb564d555c93a17384dba56854d8c688e7f38827ef5","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd76"],"error":null}
2022.02.15:18:57:16.480: eths Eth: Received: {"id":6,"jsonrpc":"2.0","result":true,"error":null}
2022.02.15:18:57:17.146: main Eth speed: 274.074 MH/s, shares: 7/0/0, time: 0:04
2022.02.15:18:57:17.146: main GPUs: 1: 40.341 MH/s (1) 2: 30.480 MH/s (0) 3: 42.401 MH/s (1) 4: 40.814 MH/s (3) 5: 41.049 MH/s (0) 6: 40.979 MH/s (0) 7: 38.010 MH/s (0) 8: 0.000 MH/s (2)
2022.02.15:18:57:22.159: main Eth speed: 274.187 MH/s, shares: 7/0/0, time: 0:04
2022.02.15:18:57:22.159: main GPUs: 1: 40.330 MH/s (1) 2: 30.488 MH/s (0) 3: 42.397 MH/s (1) 4: 40.813 MH/s (3) 5: 41.051 MH/s (0) 6: 41.053 MH/s (0) 7: 38.056 MH/s (0) 8: 0.000 MH/s (2)
2022.02.15:18:57:22.589: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x9c00faf466baf13fbf5b3d4df51cf708e11d84ca8066bfb10e68ab4ca8d13608","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd76"]}
2022.02.15:18:57:22.589: eths Eth: New job #9c00faf4 from eth.2miners.com:2020; diff: 8726MH
2022.02.15:18:57:23.550: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x62240627b5d8da024d8aa4efc5c34b66985f004b09ce9116c7c79c02e9155462","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd77"]}
2022.02.15:18:57:23.550: eths Eth: New job #62240627 from eth.2miners.com:2020; diff: 8726MH
2022.02.15:18:57:23.695: eths Eth: Received: {"id":0,"jsonrpc":"2.0","result":["0x40b8732064a4e35ad621123eb4226223fdca783c6be5c543bdc0efc00d44dcda","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd77"]}
2022.02.15:18:57:23.695: eths Eth: New job #40b87320 from eth.2miners.com:2020; diff: 8726MH
2022.02.15:18:57:26.402: wdog GPU8 not responding
2022.02.15:18:57:26.402: wdog Thread(s) not responding. Restarting.
2022.02.15:18:57:26.451: eths Eth: Send: {"id":5,"jsonrpc":"2.0","method":"eth_getWork","params":[]}

2022.02.15:18:57:26.480: eths Eth: Received: {"id":5,"jsonrpc":"2.0","result":["0x40b8732064a4e35ad621123eb4226223fdca783c6be5c543bdc0efc00d44dcda","0x2f5eca6f1ec14b82d2fb6acb0cac48d6cef3efd632e9baf66d882afde7a64fd8","0x7e00000007e00000007e00000007e00000007e00000007e00000007e","0xd8dd77"],"error":null}
2022.02.15:18:57:26.629: hwmc GPU8: unable to get temperature - GPU is lost (15)
2022.02.15:18:57:26.629: hwmc GPU8: unable to get fan speed - GPU is lost (15)
2022.02.15:18:57:26.772: main GPU1: 64C 60% 213W, GPU2: 71C 60% 154W, GPU3: 59C 60% 234W, GPU4: 60C 61% 214W, GPU5: 53C 60% 229W, GPU6: 52C 60% 207W, GPU7: 51C 60% 177W, GPU8: 56C
GPUs power: 1427.5 W; 192 kH/J
2022.02.15:18:57:27.173: main  
2022.02.15:18:57:27.173: main *** 0:04 *** 2/15 18:57 **************************************
2022.02.15:18:57:27.173: main Eth: Mining ETH on eth.2miners.com:2020 for 0:04
2022.02.15:18:57:27.173: main Eth speed: 273.924 MH/s, shares: 7/0/0, time: 0:04
2022.02.15:18:57:27.173: main GPUs: 1: 40.266 MH/s (1) 2: 30.500 MH/s (0) 3: 42.397 MH/s (1) 4: 40.812 MH/s (3) 5: 41.043 MH/s (0) 6: 40.964 MH/s (0) 7: 37.941 MH/s (0) 8: 0.000 MH/s (2)
2022.02.15:18:57:27.173: main Eth: Accepted shares 7 (0 stales), rejected shares 0 (0 stales)
2022.02.15:18:57:27.173: main Eth: Incorrect shares 0 (0.00%), est. stales percentage 0.00% 
2022.02.15:18:57:27.173: main Eth: Maximum difficulty of found share: 88.2 GH (!)
2022.02.15:18:57:27.173: main Eth: Average speed (5 min): 283.497 MH/s
2022.02.15:18:57:27.173: main Eth: Effective speed: 225.40 MH/s; at pool: 225.40 MH/s
2022.02.15:18:57:27.173: main

**Comment by PellePettersson** [comment]
It works fine with 7 cards but crashes with 8 cards. Anyone,...please help

**Comment by TheOriginalHop** [comment]
Using Nicehash miner to mine at 2miners instead of Nicehash may be a start lol

**Comment by TheOriginalHop** [comment]
No one will help you on a Nicehash thread when you are trying to mine elsewhere.

**Comment by Dohtar1337** [comment]
Download NiceHash Miner or QuickMiner here: https://www.nicehash.com/download-center
