### ISSUE TITLE
Chrome won't download it .. 

### ISSUE THREAD

**Issue by charybds** [nicehash/NiceHashMiner#262]
Had to use Edge (shudder) to DL the zip file.
Chrome is blocking it as harmful.

**Comment by drkskwlkr** [comment]
How is that an issue?!

**Comment by reinierkors** [comment]
You can click 'Show all' to show all downloads.

And then click 'Keep dangerous file':
![download](https://i.imgur.com/vwV4G4b.png)

**Comment by DillonN** [comment]
Mining software can get flagged by antivirus since there are viruses that include it (to mine on unknowing users' PCs). This isn't an issue with NHML and if you are worried you can always build it yourself

**Comment by charybds** [comment]
I am aware of why AV sometimes flags these .. I didn't know how to keep the DL .. tyvm.
