### ISSUE TITLE
Auto Update Not Working

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#2621]
Greetings,

I have auto-update enabled on two machines and it rarely works. First, it was stuck on 3.0.6.5 until 3.0.6.9 was released, at which point it updated. Now, it is still on that version after 3.0.7.1 was released. The "Online NiceHash Miner Version" in settings->about is 3.0.6.9.

Thank you for looking into this.

**Comment by Dohtar1337** [comment]
We manually trigger the auto update. 3071 auto update is coming this week.
