### ISSUE TITLE
Automining don't start cuz of Profitability error dialog window even if all data received

### ISSUE THREAD

**Issue by Pruxa-sun** [nicehash/NiceHashMiner#264]
Start getting dialog window (Legacy 1.8.1.1) on all of my PCs with profitability error even if gets all data correctly what means that mining won't start if the systems reboots cuz u need to click on OK button in that window and then u need to press start mining. Pls fix that bug. Internet is ok and everything start working after clicking OK button and then START.
![img_2851 1](https://user-images.githubusercontent.com/31207367/30002513-b383bdce-90b3-11e7-91f5-ce64061ff125.JPG)

**Comment by DillonN** [comment]
Please try 1.8.1.2
