### ISSUE TITLE
How to fix "Not connected to NHMWS. Please check your internet connection."

### ISSUE THREAD

**Issue by trusteddev1409** [nicehash/NiceHashMiner#2651]
https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.5.1

I tried this source code to build the NiceHashMiner but still got the same error.
"Not connected to NHMWS, Please check your internet connection."
How can I fix this??

**Comment by Dohtar1337** [comment]
Probably ISP or ASUS router is blocking your connection to NHMWS. Please make try disabling ASUS firewall (AIprotection) or contact your ISP provider and ask them to whitelist nicehash.

Please let me know what your ISP provider is so we can contact them and ask them to whitelist NiceHash for all of their users.

**Comment by trusteddev1409** [comment]
@Dohtar1337 

Thanks for your comment.
I found that when I download the .exe file, it works well.
But when I download the source code and built it on my own, it got error.
Can you help me with this problem?

**Comment by trusteddev1409** [comment]
@Dohtar1337 

Thanks for your comment.
I found that when I download the .exe file, it works well.
But when I download the source code and built it on my own, it got error.
Can you help me with this problem?

**Comment by trusteddev1409** [comment]
@Dohtar1337 
Thanks very muck, it is working now.
