### ISSUE TITLE
"Miner Restart Delay" and "Switch Profitability Threshold" values ignored by Nicehash app (3.0.7.1/3.0.7.2)

### ISSUE THREAD

**Issue by Marsi4eg** [nicehash/NiceHashMiner#2657]
The Miner Restart Delay option is totally ignored for algo switching in v3.0.7.1/3.0.7.2.
It works if you press Ctrl+C in active miner window but has absolutely no effect when Nicehash app changes algo.
In previous versions it works properly.

Also the Switch Profitability Threshold option is ignored by app - no matter what value is used - Nicehash app will always change algo on minimal profit difference.

Rolled back to 3.0.6.5 and both options works perfectly there.

P.S. Miner Restart Delay option is needed for some cases when immidiate algo change doesn't allow GPUs to start correctly with new overclocking settings. Cards need a few seconds delay between algos to start properly, so it's important.

**Comment by S74nk0** [comment]
@Marsi4eg there is a bug with some settings not being updated in real time. Restarting the application will take effect. The Miner Restart Delay does work. Don't close this issue. We will close it after the next release.

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.8.0
