### ISSUE TITLE
Gminer stops running

### ISSUE THREAD

**Issue by rednikdeu** [nicehash/NiceHashMiner#2663]
Hi, after opening mine_eth.bat it runs a few lines and stops with "press any key to continue". After pressing, the cmd closes. I ve downloaded 2.91 from github so it shouldn't be a faulty software. Do you have ideas on how to solve this?
![16502721055917140552527742261268](https://user-images.githubusercontent.com/64839378/163784016-337d00c6-010c-458c-87ec-f59e4e9b1689.jpg)

**Comment by Dohtar1337** [comment]
Gminer is not supported in NHM anymore.
