### ISSUE TITLE
Not getting plugins

### ISSUE THREAD

**Issue by Virstriker** [nicehash/NiceHashMiner#2666]
I'm not getting plugins in nicehash miner software like t res miner or TT miner how to install plugin from outside of the software

**Comment by bovcan** [comment]
ask google

**Comment by S74nk0** [comment]
We dropped support for unsigned miner plugins. Non signed miners can be added manually https://github.com/nicehash/NiceHashMiner/blob/master/doc/UserPlugins/README.md.
