### ISSUE TITLE
1.8.1.2 Download

### ISSUE THREAD

**Issue by deobrien1962** [nicehash/NiceHashMiner#267]
Tried downloading the latest version (1.8.1.2) and noticed that the download links are pointing to the previous version (1.8.1.1).

Am I missing something?

Thanks

**Comment by cost82el** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.8.1.2/NHML-1.8.1.2_LangFix.zip

**Comment by drkskwlkr** [comment]
> Am I missing something?

NHML has three components:
+ the NiceHash Miner Legacy executable
+ the native miners pack
+ the 3rd party miners pack

The usual practice for a new NHML release is to bump the version of only those component that have actually been updated. When you see a new NHML executable version (e.g. 1.8.1.2) and old miner native or 3rd party binaries (e.g. 1.8.1.1) this should mean to you that the new version does not require update to the older native/3rd party miner binaries.

NHML 1.8.1.2 requires an update only to the NHML executable, hence the release notes link to older version of the other two components.

**Comment by deobrien1962** [comment]
drkskwlkr,
That's what I figured but, wasn't sure. First time (that I have noticed) that there was no version number changes on the miner packs.
