### ISSUE TITLE
New update on Excavator causes PC to crash whenever Daggerhashimoto algo is run in admin mode

### ISSUE THREAD

**Issue by faith1001** [nicehash/NiceHashMiner#2676]
Hello,

The above issue is referred. My graphic card freezes and PC reboots whenever I run Daggerhasimoto in admin mode with the newest updated Excavator. I am running on Windows 10 with Nvidia GTX 1080 gpu. No problem when it was with the older Excavator version. Please help. Thank you.

**Comment by djmnice** [comment]
can you give me more details (system used, as well as log files produced by excavator) which version are using (beside newest, just to make it is really the newest)

**Comment by faith1001** [comment]
I have two rigs running Nicehash Miner, both the same problem:
Rig 1: Nicehash version 3.0.7.2, Excavator v1.7.6.5
Rig 2: Nicehash version 3.0.6.9, Excavator v1.7.6.5

The screenshot of the excavator right before it crashes and reboots my PC is below:
![image](https://user-images.githubusercontent.com/69380820/166090890-d25ab112-1c95-4191-ac0b-d767c1a8e441.png)

Also, I cleared the log files in the logs folder before the crash. And this is the log file after the crash:
[log.txt](https://github.com/nicehash/NiceHashMiner/files/8596099/log.txt)

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
