### ISSUE TITLE
MIner "pheonix" was restared (EVERY 5 MINUTES!!)

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#2680]
1080ti, windows 10,

ive noticed that over the past week my miner has been frantically restarting. whether its NBminer or pheonix etc.
(numerous messages in the notification section)

also ive noticed my miner will start at about 42-44mh.....but will drop down to 34ish after about 20 30 minutes.

the only thing that will rasie it again is turnign my computer off and on again. (this doesnt fix the restart issue)

any ideas?

**Comment by jimmyhackers** [comment]
also.....for some reason......my display doesn't turn off anymore. this nicehash wigging out issue keeps it on.
it never used to do this before.

**Comment by jimmyhackers** [comment]
and its also not registering the "current profitability" on the main screen.
just 0.00 gbp/day
same on the website overview 0.00gbp/day , however the graph is registering income

**Comment by jimmyhackers** [comment]
ad6a8e4a-56fe-49ee-923e-e82e820585bd

here is my bug report code.

**Comment by jimmyhackers** [comment]
i have completey removed nicehash including all backup data.
reinstalled and the problem is fxed. (the miners that were buggy are not there anymore, i have 17 miners instead of 23ish)

i guess pheonix and a few others were obsolete/not supported and for some reason nicehash decided not to remove them on its auto update.

**Comment by netserver** [comment]
same here,  i go back to 3.0.6.8 and works ok...  , i need clock & mem & fun controls according to temperature in amd cards there are another miner can do this?

**Comment by Dohtar1337** [comment]
Phoenixminer is not supported in NHM anymore
