### ISSUE TITLE
NB miner window keep restarting bug after manual update

### ISSUE THREAD

**Issue by syscleaner** [nicehash/NiceHashMiner#2686]
Dear All,

I'm tying to update miner file in nicehash miner but with nbminer version 41.0 and 41.3 it is not working.

I update the file as explain in nicehash tutorial. Clear the settings, close the A.Burner etc.. Update and roll back drivers etc. 

Miner is working stand alone so it is not miner.exe.

Anyone do have same type problem? 

Also I'm not sure if it help but 

I created a bug report e1d72d93-3183-4b34-86f4-7944f61f60db

**Comment by S74nk0** [comment]
LHR NBMiner is not yet live. Here is the https://github.com/nicehash/NHM_MinerPluginsDownloads/releases/download/v17.x/NBMiner_LHR_v17.0_mptoolkitV1_NBMiner_LHR.zip plugin zip 


It is a separate plugin. Create a  `NBMiner_LHR` folder and put the dll there. 
![image](https://user-images.githubusercontent.com/1517233/167644861-23778dde-e53d-4204-aa89-dff114ce1873.png)

**Comment by S74nk0** [comment]
@syscleaner you must use the https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.8.1 for this plugin to work and it is now live 
![image](https://user-images.githubusercontent.com/1517233/167649350-bd3c5946-cee2-4078-afee-eace503abe12.png)

**Comment by syscleaner** [comment]
Well update itself seems working time being. Thank you very much.
