### ISSUE TITLE
VPN Issue with getting bitcoin values

### ISSUE THREAD

**Issue by 9812ga98sd** [nicehash/NiceHashMiner#269]
Nicehash 1.8.1.2

If you are using  Private Internet Access VPN, it never receives bitcoin exchange rate data. Please create an option to stop getting live data as in previous releases. This started in 18.0.1 I think.

**Comment by DillonN** [comment]
I do not have an issue with VPN, it may just be causing connection problems to the exchange server. I don't understand how disabling live data would help the problem though?

**Comment by 9812ga98sd** [comment]
It is stuck on "getting bitcoin exchange " then i have to disable the VPN, so it gets the prices, then enable it. If I do not do this the xx/day is always 0. It never used to do this. 

Stuck on getting bitcoin exchange data....
15 seconds.
Now 0.00 xx/day

close nicehash
Disable vpn
Start Nicehash
It now gets the exchange data
start vpn again.

I do not know why it started doing this but I think it is to do with the live data. If the exchaneg blocks the IP, I dont get xx/day values.

**Comment by Krotain** [comment]
I am also experiencing this

**Comment by DillonN** [comment]
Could you try using an older version (e.g. before 1.8.1) to see if that changes things? Nothing regarding BTC exchange data has been modified since NHML started, but if something else inadvertently changed it that could help track it down (as well as post your logs).

**Comment by 9812ga98sd** [comment]
Older versions work fine. It only started happening from 1.8.1+
Also if I start and stop it doesn;t change anything. I have to kil teh vpn, close NHM and then restart it.

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1290959/log.txt)

**Comment by 9812ga98sd** [comment]
1.8.1.3
"getting bitcoin exchange rate"... waiting... 

0.00/day rates. Same as before.
installed new directory but copied config files. No old files except config files.

**Comment by 9812ga98sd** [comment]
Now I am making 24725516892 gbp per day :-)

**Comment by DillonN** [comment]
There will be a new exchange method in next update
