### ISSUE TITLE
Nicehash need OCTuner [Feature Request]

### ISSUE THREAD

**Issue by ZexMaxwell001** [nicehash/NiceHashMiner#2695]
Now that the ETH difficulty bomb hit. Nicehash miner needs to be more efficient in its GPU use. I use Quickminer's OCTuner to mange my heat and power to the GPU. I really don't want my GPU to go balls to the walls all the time with massive power use and heat. Please have Nicehash the option for power users to fine control the miner. without OCtuner, NormalNicehash miner is 20% worse with its efficiency. Using alternative methods to limit the gpu (like EVGA PX1 or Afterburner) does not have the same features to OCtuner.

**Comment by Dohtar1337** [comment]
This request is in the backlog and is coming to the client. There are no ETAs when this will happen.
