### ISSUE TITLE
I can not see the speed of the miners in the interface

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner#27]
I can not see the speed of the miners in the interface
![default](https://user-images.githubusercontent.com/5825194/28152707-8850b364-67aa-11e7-8634-8fa74fcceb80.PNG)

**Comment by DillonN** [comment]
Thanks for posting this!

**Comment by adem4ik** [comment]
I have fixed it locally by replacing "Скорость" by "Скор." in ru.lang @ https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/langs/ru.lang#L23
![image](https://user-images.githubusercontent.com/4707112/28231551-3011c2c0-68fd-11e7-87aa-5e4be6f11686.png)

**Comment by adem4ik** [comment]
so that ru.lang change was committed https://github.com/nicehash/NiceHashMinerLegacy/commit/61ec01936231afcab15c6cc0572b8f638ad867b9 and it looks like on the screenshot above

If you're not going to change space for wording within UI you may close the issue.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

We will be working on a complete GUI re-design.
