### ISSUE TITLE
Нестабильный алгоритм unstable 

### ISSUE THREAD

**Issue by vasy701** [nicehash/NiceHashMiner#2704]
unstable algorithm
marks the unstable algorithm as the most profitable algorithm and does not mine it, although it passed the benchmark, you have to turn off all other algorithms.

Нестабильный алгоритм unstable 
помечает алгоритм unstable самый доходный алгоритм и не майнит его, хотя он прошел бенчмарк, приходится выключать все другие алгоритмы.

**Comment by Dohtar1337** [comment]
Please provide more information like a screenshot or logs.

**Comment by Dohtar1337** [comment]
No response. Closing.
