### ISSUE TITLE
feature: durining mining show log and table with profits/gpu powers

### ISSUE THREAD

**Issue by maxgamurar** [nicehash/NiceHashMiner#271]
Hi there!
It would be nice during mining to have some basic log indicating reason of switching to certain algo.
Also, I think it would be good to have a basic table listing all GPUs VS algos, profitability based on benchmark, profitability based on average of latest real hashing power and a column with checkbox to disable/enable certain algo per GPU. 
This table should be viewable and editable during mining process.

**Comment by jimmyhackers** [comment]
id like this too...

it is rather annoying having to stop nicehash from mining just to check on individual algos profits.

**Comment by gpcola** [comment]
You can enable the console to see current algo payrates and switching reason.

**Comment by maxgamurar** [comment]
The problem is that there is no control over things while mining. It would be nice to have what I described.
Even there is no way to enable console during mining :)

**Comment by DillonN** [comment]
@maxgamurar for your initial request the debug console should be sufficient, since this is a more advanced feature (seeing switching reason) it 

For your other request, it is something I have been thinking on for some time and may work it in in the future.
