### ISSUE TITLE
XMrig on Windows 10 is started without administrator rights (resulting in suboptimal tuning/hashrate)

### ISSUE THREAD

**Issue by divinity76** [nicehash/NiceHashMiner#2713]
XMrig on Windows 10 is started without administrator rights (resulting in suboptimal tuning/hashrate)
quoting xmrig errors:
```
[2022-07-04 11:41:33.065]  msr      to access MSR registers Administrator privileges required.
[2022-07-04 11:41:33.065]  msr      FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
```
and seems the difference between running xmrig as administrator and not administrator on this system is about 6% / 70 H/S, NiceHash makes Xmrig go ~1030H/s, and when i start xmrig manually as administrator, i get about ~1100H/s, CPU Intel Core i5-4570T, algorithm rx/RandomX

**Comment by S74nk0** [comment]
start NiceHash Miner with administrator rights and all miners will be started with administrator rights as well

**Comment by divinity76** [comment]
@S74nk0 then NiceHashMiner should give a clear warning at least, something along the lines of 
>Warning: running NiceHashMiner without administrator rights may result in <big>**reduced hashrate**</big>
