### ISSUE TITLE
nicehash miner: nhmws  please check your internet connection not connected v.3.0.9.1

### ISSUE THREAD

**Issue by asteffy** [nicehash/NiceHashMiner#2715]
having the same issues as people have mentioned in the thread on the below link, except my miner version is v.3.0.9.1 and the one in the thread is v3.0.5.1

https://github.com/nicehash/NiceHashMiner/issues/2203

the  error messages I get are: 

nhmws. please check your internet connection not connected

unable to retrieve plugins info please check your internet connection and try to restart nicehash miner.

my internet is connected hence I am able to send this message. I've tried reinstalling the software, rebooting the computer, flushing dns, ipconfig release and renew, turning off and on ipv4 and ipv6 interchangeably. stuck now at what else to do / try and how to fix this.

**Comment by asteffy** [comment]
went back a few versions and finally was able to fix the issue by downgrading to 3.0.8.2. No idea why that fixes it since the newest software version worked up until 7/6/22

**Comment by Tizzeristika** [comment]
Bro i can't thank you enough!!!!! wasted 4 hours and finally u helped me !

**Comment by jasonrip** [comment]
This comment help me too, thank you. For me, after reading your comment, I tried to navigate to Nicehash website but was getting blocked. Reddit blocked. I started thinking about what I had changed on my computer before this problem occurred. Suddenly it hit me that I had installed a VPN recently and set it to automatically turn on and show me in a different country. Turned it off, problem solved.

**Comment by xinghuawang123** [comment]
![3e9c9377ea22d29f3d4c3381aa74301](https://github.com/nicehash/NiceHashMiner/assets/164117256/0b795184-2032-4b16-bb73-43f2b9287674)
how can i solove this!?

**Comment by beibei0234** [comment]
我也没搞定

**Comment by yug99-k** [comment]
> ![3e9c9377ea22d29f3d4c3381aa74301](https://github.com/nicehash/NiceHashMiner/assets/164117256/0b795184-2032-4b16-bb73-43f2b9287674) how can i solove this!?

Please help i am also have this problem
