### ISSUE TITLE
EWBF cannot set solver 0

### ISSUE THREAD

**Issue by navjack** [nicehash/NiceHashMiner#272]
pretty much what the subject is. i'm unable to set solver 0 in EWBF. solver 1 works just fine but i'm trying to see which solver actually consistently is the fastest on my hardware and when i see solver 0 get chosen on auto mode it seems to be the fastest.

**Comment by DillonN** [comment]
I will look into this

**Comment by MahaonO** [comment]
I also faced this problem..
And here's temp solution: just use "null" instead "0". 
For example:

--solver null --templimit 81 --eexit 1 

Works fine on my rig

**Comment by DillonN** [comment]
Should be fixed
