### ISSUE TITLE
1080TI low hashrate with excavator in 3.0.9.1 update

### ISSUE THREAD

**Issue by mrMad-Cat** [nicehash/NiceHashMiner#2722]
In 3.0.9.1 there are no more P0 and ethPill  settings. Some "inhouse solution" in release description does no explanations.
Instead there is new "NVIDIA/CUDA use optimization profiles" without any clear explanation how it works, what it means and how it is compatible with simultaneous work of Afterburner (which is used by 90% of casual users), how it is compatible if user manually launches EthPill and/or if user sets P2 state to "off" manually (in NvidiaPrifileInspector).

Checking this option does not seem to change anything, but the hashrate for 1080ti in excavator is around 36 instead of 42-44 in previous nhm.

So, new option definitely needs more explanation in the app or link to some wiki page + needs fix or return of EthPill and P0.

**Comment by Dohtar1337** [comment]
The fix will be released with the next version of NHM.
