### ISSUE TITLE
NHM 3.0.9.1: automatic mining does not start

### ISSUE THREAD

**Issue by DarkMoose92** [nicehash/NiceHashMiner#2724]
Hello. After updating to 3.0.9.1, the bundle of settings "Run nacehash after windows boot" and "automatically start mining after enabling nicehash" stopped working.

It was before the update to 3.0.9.1:

windows started, nicehash started automatically and mining started automatically.

Now:

After starting windows, the nicehash program starts, everything is fine here. But after that, mining does not start. Nothing happens.

If I manually close and reopen nicehash myself, mining starts automatically.

~~

Everything is set correctly in the settings. In configs/general.json is also all right: "AutoStartMining": true

[log.txt](https://github.com/nicehash/NiceHashMiner/files/9244580/log.txt)

**Comment by Dohtar1337** [comment]
I just tried this and it works fine on our systems.

Can you try reinstalling the NHM? Do a uninstall first and delete all the files.

**Comment by Marsi4eg** [comment]
I also report this problem. It only reproduces itself after windows reboot. If you restart Nicehash miner manually after this - autostart mining works.

Then reboot rig, Nicehash app starts but mining doesn't. etc. etc.

P.S. it's v 3.0.9.2 and windows 7

**Comment by Dohtar1337** [comment]
Please provide me with the correct steps to reproduce the issue. I have tried it again on another PC with a bit different settings and I was not able to reproduce it.

What OS are you using? Win7, 10, or 11? @DarkMoose92?

Do you have the sign in protected with a password? Is the `"AutoStartMining": `set to `true` and `"RunAtStartup":` set to `true`?

**Comment by Marsi4eg** [comment]
"AutoStartMining": set to true and "RunAtStartup": set to true

To reproduce: just reboot the PC. After rebooting, when the Nicehash app autostarts first time - mining does not start. Only have to press Start button in Nicehash app window. If you close Nisehash app and then re-launch manually - mining will start automatically like it should.

Sign in is password-protected, but set to auto login (no ask for password) via "control userpasswords2"

**Comment by i1itione** [comment]
Are both of installer version and zip version of NHM support "run nicehash after windows boot"? Or I have to use installer version?

**Comment by Dohtar1337** [comment]
> Are both of installer version and zip version of NHM support "run nicehash after windows boot"? Or I have to use installer version?

Yes, both the zip and installer support it.

**Comment by Dohtar1337** [comment]
> "AutoStartMining": set to true and "RunAtStartup": set to true
> 
> To reproduce: just reboot the PC. After rebooting, when the Nicehash app autostarts first time - mining does not start. Only have to press Start button in Nicehash app window. If you close Nisehash app and then re-launch manually - mining will start automatically like it should.
> 
> Sign in is password-protected, but set to auto login (no ask for password) via "control userpasswords2"

I tested this again and I was not able to reproduce it. I used auto-signing in with a password and was unsuccessful.

I am closing this issue since it seems like an specific, edge case scenario that cannot be replicated easily.

**Comment by Marsi4eg** [comment]
It's not important no more, since Nicehash service began to block access on politics purpose. Shame on you and feel free to break your software even more

**Comment by DarkMoose92** [comment]
Hello!

In general, this behavior is repeated again. Nicehash autostart is enabled, mining autostart is enabled, "idle when there is no internet" setting is disabled. The Internet is available, but the first autostart of the miner does not start mining.

I tried to turn on "Mining when idle 5 seconds after the last input" - it works in general terribly. Mining may not start easily. What it depends on is not clear. The latest version is as of today. Damn, version 1.9.x worked perfectly and without complaints...
