### ISSUE TITLE
FACT0RN Blockchain addition. Integer factorization as PoW.

### ISSUE THREAD

**Issue by ReverseControl** [nicehash/NiceHashMiner#2732]
Feature Request: Can you add mining for the [FACT0RN Blockchain](https://github.com/FACT0RN/FACT0RN)? It uses integer factorization instead of hashing for PoW. This project is funded by [Coinbase](https://blog.coinbase.com/fact0rn-blockchain-integer-factorization-as-proof-of-work-pow-bc48c6f2100b) (Click to go to the Coinbase article about it) .

**Comment by Dohtar1337** [comment]
This is not related to NiceHash Miner. 

But we will keep an eye on it for future Excavator development. Thank you!
