### ISSUE TITLE
NHML 1.8.1.1 Profitability Data error

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner#274]
Always getting this error on NHML 1.8.1.1 although its not existent on the new version 1.8.1.2.
![image](https://user-images.githubusercontent.com/24593637/30037850-b539edb8-91c7-11e7-9f87-c8180cfa985c.png)

**Comment by DillonN** [comment]
This issue was mitigated in 1.8.1.2
