### ISSUE TITLE
launch paramters

### ISSUE THREAD

**Issue by bovcan** [nicehash/NiceHashMiner#2765]
How do you add some extra paramaters ot miner, like max cpu threads for xmrig, intesity?
I found this https://www.nicehash.com/blog/post/nbminer-command-lines-(extra-launch-parameters)
but dont get it anymore, any example would be nice.

**Comment by alanH1998** [comment]
Hey, if you are using the new 3.1.0.0 pre-release then check this link out. 
https://github.com/nicehash/NiceHashMiner/blob/dot_net_update/doc/Advanced/ELPTab/ELPTab.md

So for example, setting 2 threads:
![example](https://user-images.githubusercontent.com/98818732/190583847-6a0b43f8-61ac-4b1f-97df-2c9cbfb48b03.png)
You can check out the preview of extra launch parameters when you click on a specific algo.
If you still need help let me know
