### ISSUE TITLE
Generic plugin for 3rd party miners missing new ELP compatibility in NHM v3.1.0.0 

### ISSUE THREAD

**Issue by s33butler** [nicehash/NiceHashMiner#2770]
Generic plugin for 3rd party miners missing new ELP compatibility in NHM v3.1.0.0 

When following the Generic plugin that allows adding 3rd party miners, Instructions...  https://github.com/nicehash/NiceHashMiner/tree/master/doc/UserPlugins
There is no way to add ExtraLaunchParameters for 3rd party miners.

Issues:
- ExtraLaunchParameters in \NiceHash Miner\configs\device_settings_GPU.json are auto removed on NHM launch.
- Old Extra Launch Parameter settings removed from benchmark tab.
- 3rd party miners are not listed in New Extra Commands tab.
- \NiceHash Miner\miner_plugins\ExamplePlugin\Devices.json missing ability to add ELP similar to new JSON "commands": style.
- guide https://www.nicehash.com/guide/nicehash-miner-user-guide missing new settings info.
- https://www.nicehash.com/support/mining-help/nicehash-miner/what-is-nicehash-miner missing new settings info.

Thank you kindly for your time and assistance.
Keep up the great work.

**Comment by Dohtar1337** [comment]
Thanks for reaching out!

This issue will be fixed in the next release. You will need to use Extra Commands
