### ISSUE TITLE
gpu algo opening and closing/not mining

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#278]
for the past two days i have come to my computer in the morning to find the gpu algo opening and closing and not mining.
my cpu mining on the same pc though remains un interupted.

i had initially though it was malwarebyte but after uninstalling yesturday it the error remains.

**Comment by jimmyhackers** [comment]
also.....after closing the nicehash console i am unable to reopen it again unless i restart the pc. 


[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1281019/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1281020/log.1.txt)

**Comment by jimmyhackers** [comment]
i have half discovered a possible issue/reason......on all other older versions of NHLM. i have created a shortcut in the install folder then copied said shortcut to my desktop.

i was lazy with this version and just dragged and dropped the program creating a copy of it on my desktop.

hopefully when i got  sleep this evening i wont awake to find hours of wasted gpu nonhashing time

**Comment by noornaim** [comment]
i also got the same issue with legancy 1.8.1.2.. 
i try to solve this with DDU my GPU driver also no use..
up until i format back my rig and do it all over again (waste my time and money alot) but still not solve the problem.. i use version 2.0 but the profit for nvidia card was reduce alot in dual mining with excavator. should put/use claymore for dual mining for nvdia card.

**Comment by DillonN** [comment]
It looks like ccminer is crashing after NHML launches it, can you confirm that `\bin\ccminer_nanashi\ccminer.exe` exists and that you can launch it manually with the same startup command (`ccminer.exe --algo=lyra2v2 --url=stratum+tcp://lyra2rev2.eu.nicehash.com:3347 --userpass=16U3qga1E3iCXgvTX9KdrYhX7SkgJdYYzy.worker1:x  --api-bind=4004  --devices  0`) with no issues while NHML cannot?

**Comment by jimmyhackers** [comment]
thanks for the help
bin\ccminer_nanashi\ccminer.exe exsists. 
not quite sure exactly how to do said startup command.  sorry :s (i need a link to instructions) 

also do you want me wait untill the error returns and is present/happening and try this manual launch?

**Comment by DillonN** [comment]
@jimmyhackers to manually launch you can just open a command prompt window in the `\bin\ccminer_nanashi` folder and paste the command I posted in my last comment

If the problem is intermittent then wait until you are experiencing it, it could be related to hardware/driver instability (these are notorious for causing miner programs to crash on start)
