### ISSUE TITLE
OnGPULost.bat replaced during updates

### ISSUE THREAD

**Issue by dethknite** [nicehash/NiceHashMiner#2784]
I have customized my OnGPULost.bat file with additional options, and noted that it is always updated/replaced with the general one on upgrades. Several times I have forgotten to copy my modified version back after upgrades and it has bitten once again (rebooting several times during a large transcoding operation). It took me awhile to realize the issue.

It would be nice if this file is only copied when the file is missing during an update / upgrade.

**Comment by Dohtar1337** [comment]
Thanks for reaching out! 

We will not implement this feature as it is out of scope, and we have other higher priorities. We suggest you to continue copy-pasting the file upon updating.
