### ISSUE TITLE
Latest version (3.1.0.1) doesn't recognize any device in Windows 11

### ISSUE THREAD

**Issue by CabezaDePito** [nicehash/NiceHashMiner#2785]
Yesterday I updated the miner from version 3.0.9.2 to 3.1.0.1 and when a I restarted the program no device where found, not the GPU or the CPU and after a few minutes an error message appear and says that the connection with the NiceHash services time-out. Tried restarting the PC, reinstalling the program with a clean install, check the guide from the support page (antivirus and that stuff) and nothing. I roll back to 3.0.9.2 and it works flawlessly.

Setup specifications:
Windows 11 Pro - Versión 21H2 - OS compilation 22000.1098
AMD Drivers 22.10.1
Chipset Drivers v4.7.13.2243
Hardware: CPU Ryzen 7 3700x - RAM 2x8Gb 3200mhz - GPU RX 6600XT 8GB - PSU XFX 850W PRO Gold - Motherboard Asrock A520M-HDV

**Comment by object05** [comment]
We are already testing a fix for this, it will be available soon.
