### ISSUE TITLE
How to edit MinerSettings.json for adding SRBMiner to work?

### ISSUE THREAD

**Issue by i1itione** [nicehash/NiceHashMiner#2786]
I've read https://github.com/nicehash/NiceHashMiner/tree/master/doc/UserPlugins and tried adding SRBMiner but no succeed.
I think that I don't edit MinerSettings.json correctly cause it doesn't work.

<img width="379" alt="nhm_20221017001" src="https://user-images.githubusercontent.com/21694907/196054727-9fddc881-a17f-4580-93c1-658b56d59c66.png">

**Comment by object05** [comment]
Hi, 
The MinerSettings.json should look something like this (please change etchash to VerusHash):
```
{
  "init": false,
  "PluginEngine": 0,
  "use_user_settings": true,
  "devices_separator": ";",
  "algorithm_command_line": {
    "EtcHash": "--wallet {USERNAME} --pool stratum+tcp://{POOL_URL}:{POOL_PORT} --algorithm  etchash --api-enable --api-port {API_PORT} --gpu-id {DEVICES} {EXTRA_LAUNCH_PARAMETERS}"
  },
  "algorithm_command_line_ssl": {
    "EtcHash": "--wallet {USERNAME} --pool stratum+ssl://{POOL_URL}:443 --tls 1 --algorithm  etchash --api-enable --api-port {API_PORT} --gpu-id {DEVICES} {EXTRA_LAUNCH_PARAMETERS}"
  }
}
```

and also, in `internals/PluginSupportedAlgorithmSettings.json` under value `IDs` change the default value to VerusHash (or whatever else you want to mine), for my example it would be `"IDs": "EtcHash",` for every type of device

Please let me know if you have any more problems

**Comment by i1itione** [comment]
It still doesn't work, benchmark failed.

This is my MinerSettings.json (I refer to SRBMiner's start-mining-veruscoin.bat):
```
{
  "init": false,
  "PluginEngine": 0,
  "use_user_settings": true,
  "devices_separator": ",",
  "algorithm_command_line": {
    "VerusHash": "--disable-gpu --algorithm verushash --pool stratum+tcp://{POOL_URL}:{POOL_PORT} --wallet {USERNAME} --api-enable --api-port {API_PORT} {EXTRA_LAUNCH_PARAMETERS}"
  },
  "algorithm_command_line_ssl": {
    "VerusHash": "--disable-gpu --algorithm verushash --pool stratum+ssl://{POOL_URL}:443 --tls 1 --wallet {USERNAME} --api-enable --api-port {API_PORT} {EXTRA_LAUNCH_PARAMETERS}"
  }
}
````
And this is my PluginSupportedAlgorithmSettings.json:
```
{
  "use_user_settings": true,
  "enable_unsafe_RAM_limits": false,
  "default_fee": 1.0,
  "algorithm_fees": null,
  "algorithm_fees_v2": {
    "DaggerHashimoto": 1.0
  },
  "device_algorithms": {
    "CPU": [
      {
        "IDs": "VerusHash",
        "Enabled": null,
        "ExtraLaunchParameters": null,
        "NonDefaultRAMLimit": null
      }
    ],
    "AMD": [
      {
        "IDs": "DaggerHashimoto",
        "Enabled": null,
        "ExtraLaunchParameters": null,
        "NonDefaultRAMLimit": null
      }
    ],
    "NVIDIA": [
      {
        "IDs": "DaggerHashimoto",
        "Enabled": null,
        "ExtraLaunchParameters": null,
        "NonDefaultRAMLimit": null
      }
    ]
  },
  "plugin_algorithm_name": {
    "KAWPOW": "Kawpow",
    "Octopus": "Octopus",
    "DaggerHashimoto": "Ethash",
    "Autolykos": "autolykos",
    "EtcHash": "Etchash",
    "VerusHash": "verushash"
  }
}
````

**Comment by i1itione** [comment]
It seems that benchmark failed is caused by nhm can't read stats from SRBMiner.

I edited the "Speeds" value in "configs\device_settings_CPU-xxxxxxx.json" directly for marking it already benchmarked, then the mining is working, just the hashrate isn't shown at nhm.

<img width="489" alt="nhm_20221018001" src="https://user-images.githubusercontent.com/21694907/196227124-0df53e43-1470-4164-9586-7cc7baa4d95e.png">
