### ISSUE TITLE
CPU stats not updating for XMR in 1.8.1.2

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner#279]
CPU stats do not update and the relevant mBTC is also not updating for past few hours.

**Comment by DillonN** [comment]
By stats do you mean mining speed? Could you upload your log.txt file?

**Comment by nerdatwork** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1289878/log.txt)
Yes stats as in mining speed on the GUI. Also the mBTC didnt update either.

**Comment by DillonN** [comment]
The stats method for XMR will be changed in the next update so if you could try again then after it is out hopefully the problem will be gone
