### ISSUE TITLE
Unable to add space delimiter / separator for new "Extra Commands", please add support for spaces

### ISSUE THREAD

**Issue by s33butler** [nicehash/NiceHashMiner#2796]
Unable to add space delimiter / separator for new "Extra Commands", please add support for spaces

Windows 11 - NiceHash v3.1.0.2 - GMiner v3.05

Nothing happens when you press the space key, I tired the space bar, I also tried pasting a space into the field. 

![image](https://user-images.githubusercontent.com/23462191/197446972-3e322ac7-9caa-4871-af4b-b46d2f8d2672.png)

Thank you for your time and assistance, keep up the great work.

**Comment by alanH1998** [comment]
Thank you for reporting this, the problem has been addressed and will probably be fixed until the next update.
