### ISSUE TITLE
Unable to add Autolykos to GMiner algo settings config in NHM.

### ISSUE THREAD

**Issue by s33butler** [nicehash/NiceHashMiner#2799]
Unable to add Autolykos to GMiner PluginSupportedAlgorithmsSettings.json

NiceHashMiner v3.1.0.2
GMiner v3.11  - Ergo support added v3.0.6
miner_plugins ID:   e7a58030-94eb-11ea-a64d-17be303ea466
Issue:  When manually added to miner_plugins/e7a58030-94eb-11ea-a64d-17b/internals/PluginSupportedAlgorithmsSettings.json , upon starting NHM any custom changes are removed and the json reset to default.

I'm able to add others like... EtcHash and ZelHash... and the settings persist, but not Autolykos.

PluginSupportedAlgorithmsSettings.json
```
{
  "use_user_settings": true,
  "enable_unsafe_RAM_limits": false,
  "default_fee": 2.0,
  "algorithm_fees": {
    "KAWPOW": 1.0
  },
  "algorithm_fees_v2": null,
  "device_algorithms": {
    "NVIDIA": [
      {
        "IDs": "Autolykos",
        "Enabled": true,
        "ExtraLaunchParameters": null,
        "NonDefaultRAMLimit": null
      }
    ]
  },
  "plugin_algorithm_name": {
    "Autolykos": "ergo",
    "EtcHash": "etchash",
    "ZHash": "144_5",
    "ZelHash": "125_4",
    "CuckooCycle": "cuckoo29",
    "KAWPOW": "kawpow",
    "DaggerHashimoto": "ethash"
  }
}
```

Thank you for your time and assistance, keep up the great work.

**Comment by MolochBaal** [comment]
Hey, how do you added Gminer to NHM? 
I really hate the 3 available miners (nanominer=💩, lolMiner is awful and NBminer is kinda ok, but don't have fan control).

I think the algo is Autolykos2 on gminer.

**Comment by s33butler** [comment]
@MolochBaal I've always had gminer in NHM for as long as I can remember, so I'm not sure why you do not. 
Maybe check that you have it installed and enabled...  https://www.nicehash.com/guide/nicehash-miner-user-guide - section Plugins
I suppose you could add it manually as a custom user plugin, below is the guide...
https://github.com/nicehash/NiceHashMiner/tree/master/doc/UserPlugins

**Comment by MolochBaal** [comment]
Oh many thanks, didn't know about the guide, gonna try it later. Well NiceHashMiner now only support signed miners, so only 5 are available: XMRig (CPU), Excavator (ETH only), nanominer (absolute trash), lolminer (awful) and NBminer.

--
Edit: Just got GMiner working with all algorithms :)

**Comment by s33butler** [comment]
I'm guessing you could install a NHM prior to the removal and then update from there...   v[3.0.5.5] (https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.5.5) pre gminer removal.
Probably the case for any dropped plugins... I imagine there might be interest in other plugins and algorithms with ETH going PoS.  Just a heads up though, the new NHM doesn't currently support space as a delimiter #2796 so you have to control OC another way.

**Comment by MolochBaal** [comment]
> I'm guessing you could install a NHM prior to the removal and then update from there... v[3.0.5.5] (https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.5.5) pre gminer removal. Probably the case for any dropped plugins... I imagine there might be interest in other plugins and algorithms with ETH going PoS. Just a heads up though, the new NHM doesn't currently support space as a delimiter #2796 so you have to control OC another way.

Oh damn, it is working really good on my PC with only 1 gpu, I was going to update it to my rigs. Guess I should use T-Rex that uses "," as delimiter.

**Comment by alanH1998** [comment]
GMiner has been signed and will be officially supported in the next update.

**Comment by MolochBaal** [comment]
> GMiner has been signed and will be officially supported in the next update.

Oh that's great, because it works better on all algorithms than nbminer (today I worked adding it to my rigs). Only had 1 issue with gminer, when mining it keeps rebooting after 5 minutes, the solution was to disable "MinerApiMaxTimeoutSetting.json" with  

> "use_user_settings": true,
>  "enabled": false,

So, check that for the next update.

![image](https://user-images.githubusercontent.com/89867957/199424855-fddb7af2-11f2-4d3d-94db-2ba65d2565ce.png)
