### ISSUE TITLE
Okay how do I get dual miner to work!!

### ISSUE THREAD

**Issue by asmodyus** [nicehash/NiceHashMiner#28]
Okay got new version have the claymore algorithms checked how do i get to go into dual Mode?

**Comment by DillonN** [comment]
Once the dual algos are checked (e.g. DaggerSia, etc), just run the benchmark for them and it'll record the speeds (both for eth and secondary coin). NHML will auto switch to it if it's most profitable. You may need to run the benchmarks in precise since these take a long time to get started.

**Comment by asmodyus** [comment]
Oh Okay so it will only run if its profitable thank because I did the precise benchmarks like you said but I don't see anything that says it running dual in the CMD box.

**Comment by DillonN** [comment]
Yes it's not always most profitable, mainly on NVIDIA cards
