### ISSUE TITLE
Recently switched to nicehash legacy miner.But now I am not getting any shares for Cryptonight.

### ISSUE THREAD

**Issue by mailtrain13** [nicehash/NiceHashMiner#280]
I recently switched from 1.7.5.3 to nicehash legacy miner 1.8.1.2.But now I am not getting any shares from cryptonight.Also sometimes the hashrate drops very low without any reason.

**Comment by mailtrain13** [comment]
Also I am getting "Stratum - reading socket failed 10038, disconnect" this issue.

**Comment by DillonN** [comment]
Can you give more specifics (what devices you're using, log files)

**Comment by thel3lue** [comment]
same problem here mining with rx550 2gb 10min only get 3 shares 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1284034/log.txt)
here my log files

**Comment by mailtrain13** [comment]
My GPU is R7 370 2GB and my CPU is AMD Fx-6100.I am doing GPU mining only.Here is my log file.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1284660/log.txt)

**Comment by DillonN** [comment]
This is probably related to the latest difficulty increase in CN, it is causing cards to not push out shares as often. If a share is not sent in 10 min, the connection will timeout (and reconnect in around 10 seconds). This is standard behaviour for the Stratum protocol. @mailtrain13 when you see the "Stratum - reading socket failed" error does it look like it reconnects shortly after?

**Comment by mailtrain13** [comment]
![capture](https://user-images.githubusercontent.com/31704777/30262520-0e9d0f7c-96f3-11e7-9b6e-cc8f1110d2e4.JPG)

This is what I get.How can I fix it?
