### ISSUE TITLE
Unprofitable GPU mining also prevents CPU mining

### ISSUE THREAD

**Issue by NPrincen** [nicehash/NiceHashMiner#2801]
NHM version 3.1.0.2
Windows 10 Pro 64 bit 22H2
Hardware: i7-4790K CPU, 32GB RAM, Nvidia RTX3070
Settings: Mine Regardless Of Profit = Off, Electricity Cost = 0.23, Minimum Profit = 0, Display Net Profit = On or Off, Currency = USD

Benchmarked all of the algorithms and miners for the RTX3070.  Checked and they all have power usage specified from the benchmarking.  Also benchmarked CPU algorithms and miners (RandomXmonero and VerusHash).  These reported zero power usage and I left it that way.

Started the miner, and because the RTX3070 is not profitable at my electricity cost, it will not mine.  But, this also prevents the CPU from mining.  With the benchmarked power usage of zero for CPU mining, it should always run no matter what the electricity cost is.  So, GPU not being profitable prevents CPU mining.  If I disable the GPU, then the CPU will start mining right away.  As soon as I enable the GPU, the CPU stops mining.

Profitability should be independently calculated.  Every device should have its own profitability profile based on its benchmarks and should start and stop independently when they become profitable and unprofitable.

**Comment by Dohtar1337** [comment]
For now, we will not implement this. It will take some work to refactor the logic, and at the moment we have other priorities.

The feature is noted and will be revisited in the future.
