### ISSUE TITLE
Sorting of BTC/24H column with Display Net Profit = On

### ISSUE THREAD

**Issue by NPrincen** [nicehash/NiceHashMiner#2802]
NHM version 3.1.0.2
Windows 10 Pro 64 bit 22H2
Hardware: i7-4790K CPU, 32GB RAM, Nvidia RTX3070
Settings: Time Unit = Day, Mine Regardless Of Profit = Off, Electricity Cost = 0.23, Minimum Profit = 0, Display Net Profit = On, Currency = USD

When Display Net Profit = Off, the user can click on the BTC/24H column header and sort the algorithms and miners from highest to lowest revenue or lowest to highest revenue.  When setting Display Net Profit = On, the BTC/24H column correctly shows the current profitability (Thanks for fixing this!).  Clicking on BTC/24H does NOT sort the column by current profitability, as it should.  I believe it is still being sorted based on the revenue and not the profit.  Please fix this so it correctly sorts by profit.

Bonus Points:  Would like an option where the sort updates as soon as the revenue or profit numbers change (dynamic sort).  That way, we do not need to keep clicking the BTC/24H column header to resort the list every time the numbers change.  In other words, when NHM gets new data on the revenue per hash rate, then the revenue or profits are automatically updated.  With the new option turned on, it will also resort the list based on the new revenue or profit numbers.

**Comment by ShayneMichaelBacik1** [comment]
l I will properly and correctly with effect for these minor.  profits
expected and rewards granted. I have payment credentials I want to be
acknowledge for my participation in every payloads, work loan, technician
guarantees all requirements, guidelines, borders, boundaries,   and all
other problematical situations.Handled by professional Workmen.

**Comment by alanH1998** [comment]
This has been fixed and will be included in the next update.
