### ISSUE TITLE
VersusHash options don't work in Extra Commands

### ISSUE THREAD

**Issue by NPrincen** [nicehash/NiceHashMiner#2803]
NHM version 3.1.0.2
Windows 10 Pro 64 bit 22H2
Hardware: i7-4790K CPU, 32GB RAM, Nvidia RTX3070

For CPU mining, I can use Extra Commands to control the mining of RandomXmonero using Xmrig.  For instance, command line options like: --donate-level=1 --cpu-priority=2 --threads=4 work just fine and have the desired effect when benchmarking and mining.  It doesn't matter whether the delimiter is an = or a space.  The space or = delimiter is correctly interpreted by Xmrig and it just works.

For VerusHash on Nanominer, the correct way to specify an option on the command line is -cpuThreads 6.  There must be a space and another delimiter cannot be used.  Using an = delimiter results in errors in the mining window.  When I try entering the command line option above with a space, I get no error in NHM Extra Commands, but when I run the miner, I get:

Error: INIReader: LOAD: key-value delimiter not found: -cpuThreads

It appears that the space and the number behind the space are being ignored.  So, there is no way to specify options for Versus.  Please fix this so the space delimiter and the number are properly passed to the miner.

**Comment by alanH1998** [comment]
Thank you for reporting this, we seem to have a problem with nanominer extra commands in general because commands are being read from a file instead of the command line. A fix for this is comming soon

**Comment by Dohtar1337** [comment]
This will be fixed in the next release.
