### ISSUE TITLE
KAPOW BENCHMARK ERROR RTX 4090

### ISSUE THREAD

**Issue by ddourida007** [nicehash/NiceHashMiner#2804]
KAPOW BENCHMARK ERROR RTX 4090
new version of nicehash 3.1.0.2
drivers 526.47
can anyone help or seeing same issue?

**Comment by MolochBaal** [comment]
For me it's imposible to mine KawPoW algo with NiceHash + NBminer, tested with different rigs (1x 3070 FHR Zotac, and 6x 3070 FHR EVGA), different NiceHashMiner versions 3.1.0.0, 3.1.0.1 and 3.1.0.2 and different Nvidia drivers 516.94, 517.48 and 
522.25. It always crash with CUDA Error: an illegal memory access was encountered (err_no=77) or Share above target!

But I can mine only using NBminer to kawpow.auto.nicehash.com:9200 with the same OC without any issue, so my guess is NiceHashMiner is somehow conflicting with KawPoW algo since it only happen with this algo, all others are fine.

**Comment by ddourida007** [comment]
How did you set that up to mine only using NBminer to kawpow.auto.nicehash.com:9200 with the same OC without any issue?

**Comment by MolochBaal** [comment]
> How did you set that up to mine only using NBminer to kawpow.auto.nicehash.com:9200 with the same OC without any issue?

Just download NBminer (or any miner like T-Rex miner, or my fav Gminer) and edit with notepad "start_rvn.bat"

This is my config for my pc with only one 3070

> nbminer -a kawpow -d 0 -o stratum+tcp://kawpow.auto.nicehash.com:9200 -u 35NdJ3fZpw2xeQMo8ByPC3BnpZwxeRzH3C.RTX3070 -p x --log --log-no-job --platform 1 --share-check 5 --temperature-limit 80 --temperature-start 50 --cclock @1450 --mclock 1000 --fan 80
> 
> pause

**Comment by ddourida007** [comment]
I gave it a shot, give error could not load kernal for 4090, i belive not compatible yet for the 4090

**Comment by MolochBaal** [comment]
> I gave it a shot, give error could not load kernal for 4090, i belive not compatible yet for the 4090

Oh yeah, only miner that currently support 4090 is T-Rex miner 
https://github.com/trexminer/T-Rex/releases

Config should be something like this (I'm assuming overclocks, but should be around that)

> t-rex.exe -a kawpow -d 0 -o stratum+tcp://kawpow.auto.nicehash.com:9200 -u 35NdJ3fZpw2xeQMo8ByPC3BnpZwxeRzH3C.RTX4090 -p x -l log_RVN_%date%.log --gpu-report-interval 10 --validate-shares --temperature-limit 80 --temperature-start 50 --lhr-tune 0 --lock-cclock 2250 --mclock 700 --fan t:55[30-100] 
> 
> pause

**Comment by ddourida007** [comment]
nice I got it working on Kawpow, the the question when will nicehash T-Rex miner in the NiceHashMiner? 
Can we fix nicehash to have kawpow working on the 4090?

**Comment by MolochBaal** [comment]
> nice I got it working on Kawpow, the the question when will nicehash T-Rex miner in the NiceHashMiner?

I think NiceHash is not going to add miners that are not signed.

> Can we fix nicehash to have kawpow working on the 4090?

I guess you can download an old version of NiceHashMiner that included T-Rex and then update and it will keep the miner, or you can follow this guide to add a miner (I haven't tested it yet) https://github.com/nicehash/NiceHashMiner/tree/master/doc/UserPlugins

**Comment by ddourida007** [comment]
Ya i tried to add it manully it didnt work might you know the older version that supported it? I will download it.

**Comment by MolochBaal** [comment]
> Ya i tried to add it manully it didnt work might you know the older version that supported it? I will download it.

No clue, just started using nicehash a month ago, but I added GMiner with that guide with all algorithms and is working fine.

**Comment by ddourida007** [comment]
ok let me see if can find it,  I found one its so buggy, i will wait for nice hash to get back to me
i opened a support case

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/psa-nvidia-driver-526-47-issues-when-mining-or-gaming

Also, maybe NBminer has not updated the kernels yet. Please use QuickMiner latest Release candidate where 4090 is already supported
https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.6.1.0_RC
