### ISSUE TITLE
Nicehash Registry/CLI

### ISSUE THREAD

**Issue by githlp69** [nicehash/NiceHashMiner#2805]
Is there any way to accept EULA and 3rdparty through cli/registry? All I found was HKEY_CURRENT_USER\Software\8abad8e2-b957-48ed-92ba-4339c2a40e78
Is this the only Registry key, or are there more, in HKLM perhaps?

Thank you

**Comment by alanH1998** [comment]
Hi, unfortunately the only "intended" way for the user to accept the terms of service is currently through the GUI. And yes, that is the only registry.
