### ISSUE TITLE
1.8.1.2 Download binaries link incorrect

### ISSUE THREAD

**Issue by jasoncharles** [nicehash/NiceHashMiner#281]
Hi,
The download link to the binaries for 1.8.1.2 at https://github.com/nicehash/NiceHashMinerLegacy/releases/ are incorrect as they link to 1.8.1.1.

Thanks for your help
Jason

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [ ] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

**Comment by luongk** [comment]
The miners didn't change between 1.8.1.1 and 1.8.1.2, the download links are correct.

**Comment by DillonN** [comment]
As @luongk said the links are the same

**Comment by jackpot1136** [comment]
greeat to see improvement. It wasn't an error. optimizing communication
