### ISSUE TITLE
Extra Commands don't work while benchmarking

### ISSUE THREAD

**Issue by XamarinDeveloper** [nicehash/NiceHashMiner#2819]
Hi,

I need to use --proxy option on nbminer, but the extra commands don't apply on benchmark runs, so my benchmarks fail, I used a workaround by replacing the nbminer.exe file with a custom .exe file that adds the needed parameter for benchmark and then after benchmark, I used the original nbminer.exe and it works fine now, but it would be better if we could have them applied on benchmark runs as well.

**Comment by Dohtar1337** [comment]
You can manually input the benchmark values. 

We will check why the benchmarks are run without the Extra Parameters
