### ISSUE TITLE
Unable to edit JSON config regardless of whether or not NiceHash is open or not

### ISSUE THREAD

**Issue by lmaonade80** [nicehash/NiceHashMiner#282]
Every time I go in and attempt to change my JSON config (trying to assign a different miner to a particular algorithm), NHLM reverts the config file back. Nicehash is not open during my editing.

**Comment by DillonN** [comment]
Which JSON file are you editing?

**Comment by lmaonade80** [comment]
I was editing the benchmark_GPU file and the MinnerReservedPorts file to try to add a new miner to one of the existing Nicehash algos.

**Comment by DillonN** [comment]
That is not possible currently
