### ISSUE TITLE
Excavator Kawpow not benchmarking in ver 3.1.0.3

### ISSUE THREAD

**Issue by DavidStovell** [nicehash/NiceHashMiner#2829]
Benchmarking errors out with excavators kawpow algorithm.

**Comment by DavidStovell** [comment]
Problem still exists ver 3.1.0.4

**Comment by Dohtar1337** [comment]
Make sure to use the correct drivers. https://www.nicehash.com/blog/post/psa-nvidia-driver-526-47-issues-when-mining-or-gaming

**Comment by DavidStovell** [comment]
Hi, thanks for the reply.
I was still using 512.95 may be a bit too old, updated to your recommended
522.25 and that has resolved the issue.
