### ISSUE TITLE
Add the possibility of informing for example a mail if any device has ceased to generate income.

### ISSUE THREAD

**Issue by Woldemar83M** [nicehash/NiceHashMiner#283]
Can add the possibility of informing for example a mail if any device has ceased to generate income through, for example, 5 minutes?

**Comment by bonifacio123** [comment]
You may want to consider using the IFTTT feature which can have your cell phone email or text you when this condition occurs. Here's a starting point:

[https://www.greenbot.com/article/3157040/android/a-beginners-guide-to-ifttt-on-android.html](url)

**Comment by drkskwlkr** [comment]
@Woldemar83M A description of the IFTTT functionality implemented in NHML is given by the contributor himself [here](https://github.com/nicehash/NiceHashMinerLegacy/pull/117#issuecomment-326800265).

**Comment by Woldemar83M** [comment]
Thank you. IFTTT is not very convenient for me as tat only works with web site. But I need to see when NiceHashMinerLegacy lost 1 GPU (the GPU Need to restart the device), or switch algorithms every 2 seconds(restart required NiceHash). NiceHash would be better if he had corrected these errors, then well, you need to inform!

**Comment by jimmyhackers** [comment]
have a look on the appstore for nicehashviewer for your phone

it has a "miner down alert" function. its pretty nifty and gives you "some" peice of mind when your away from your rig that you can see which workers are active and what they are mining.

**Comment by Woldemar83M** [comment]
> have a look on the appstore for nicehashviewer for your phone
> it has a "miner down alert" function. its pretty nifty and gives you "some" peice of mind when your away from your rig that you can see which workers are active and what they are mining.

Thank you! Didn't know about this program, installed, tested. Used Nicehash Monitor which seems to have the same notification but it's paid, so not tried.

**Comment by DillonN** [comment]
NiceHash also has a built in notification service for when workers stop working: https://new.nicehash.com/help/workers-monitoring

It works only with NH wallets that are connected to an account you can sign in on

**Comment by Woldemar83M** [comment]
Thank you very much! But it is less advantageous to use the internal wallet.

**Comment by ChriscomIT** [comment]
Nicehash viewer is very neat also Nicehash monitor is very good but there you need to pay for the worker monitoring feature. Also, where is internal wallet less advantageous against external wallet. IMHO that's totally wrong and the absolute opposite is correct starting with the ability of detailed monitoring, lower fees overall and much more small but nice pro internal wallet features.
