### ISSUE TITLE
Does it still not support to read stats from SRBMiner (custom plugin)?

### ISSUE THREAD

**Issue by i1itione** [nicehash/NiceHashMiner#2831]
I use NHM 3.1.0.4 now, but it seems that it is still not able to read stats from SRBMiner, therefore I need to edit "MinerApiMaxTimeoutSetting.json" to disable timout settings or NHM will turn off the miner.

<img width="273" alt="nhm-20221122001" src="https://user-images.githubusercontent.com/21694907/203146156-76a916ed-b108-4dd5-abe8-f11aeb27a252.png">

But this issue doesn't affect mining work, it works just fine.

Here is the "MinerSettings.json" I used.

```
{
  "init": false,
  "PluginEngine": 0,
  "use_user_settings": true,
  "devices_separator": ",",
  "algorithm_command_line": {
    "VerusHash": "--disable-gpu --algorithm verushash --pool stratum+tcp://{POOL_URL}:{POOL_PORT} --wallet {USERNAME} --api-enable --api-port {API_PORT} {EXTRA_LAUNCH_PARAMETERS}"
  },
  "algorithm_command_line_ssl": {
    "VerusHash": "--disable-gpu --algorithm verushash --pool stratum+ssl://{POOL_URL}:443 --tls 1 --wallet {USERNAME} --api-enable --api-port {API_PORT} {EXTRA_LAUNCH_PARAMETERS}"
  }
}

**Comment by Dohtar1337** [comment]
Try changing pluginEngine to 1 or 2. Otherwise, I cannot help you since we do not officially support custom plugins.
