### ISSUE TITLE
problem with plugin compatible error

### ISSUE THREAD

**Issue by zorlars** [nicehash/NiceHashMiner#2836]
I downloaded the source code from Github. I compiled from source code. I added all the plugin packages as plugin_packages. But when I open the program, I see the error "the latest online version of this plugin not compatible with your current version of nicehash miner". I'm actually uploading the latest version of nicehash miner on github. The source code I downloaded is 3.1.0.4 but after compiling it comes out as 3.0.9.2. I see an error that the plugins are not compatible, update the nicehash miner program.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by object05** [comment]
Hi, sorry for the confusion, the 3.1.0.4 (the latest source code) is not in `master` (3.0.9.2) branch but in `dot_net_update`(3.1.0.4), we will hopefully merge it soon. This explains the incompatible plugins. I hope this solves your issues.
