### ISSUE TITLE
Miner Windows not Visible during Mining

### ISSUE THREAD

**Issue by lmaonade80** [nicehash/NiceHashMiner#285]
"Minimize Mining Windows" is not checked in the Misc. Settings however no mining windows are visible; only debug window when that option is checked.

**Comment by DillonN** [comment]
Could you post your log.txt file please

**Comment by lmaonade80** [comment]
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1288757/log.1.txt)

**Comment by DillonN** [comment]
@lmaonade80 I cannot see where you started mining, in the logs it looks like after the benchmark finished NHML just remained idle?
