### ISSUE TITLE
"Profit Normalization" robustness.

### ISSUE THREAD

**Issue by lmlim** [nicehash/NiceHashMiner#287]
Hi Dillon,

I tested and noticed that "x11gost intrusion" has been reduced greatly. although there may be a couple instances it still got thru. kudos.

however, just wondering how robust the "profit normalization" is, when it encounters the "good spike"?
for example: eth+xxx <---> zec. or eth+xxx <---> eth+yyy.

will it delay the algo switch? or it will not switch at all? 
delaying algo switch on "good spike" certainly gonna hurt profit too in the long run. 
in any case, may be can this "profit normalization" be put as an option in settings rather than enforced?

thanks.

**Comment by DillonN** [comment]
There is a page [on the wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Profit-Normalization) that explains how you can adjust the normalization values. You can find on there which values to change in which direction to increase/decrease normalization strength. If you wanted to disable it you could set `IQROverFactor` to something very high like 1000 (in the future I will make an explicit disable option)

**Comment by lmlim** [comment]
i tried to edit general.json file in ./configs directory. but i think it was overwritten everytime NHML starts.
