### ISSUE TITLE
[Request] Update GMiner to the new v3.30 that supports Octopus (Conflux)

### ISSUE THREAD

**Issue by MolochBaal** [nicehash/NiceHashMiner#2873]
Pretty much what the title says. I updated manually the new "miner.exe" and it works, but I can't make it support Octopus since "PluginSupportedAlgorithmsSettings.json" and "MinerCommandLineSettings.json" are rewrited everytime NHM is launched.

Also tried adding a new miner "GMiner Updated" but it only works on my pc with 1 gpu, on my rig with 6 rtx 3070 it crashes 5 and only the last gpu run, miner works perfectly alone (without NHM). So, for now, I have T-Rex runing on NHM to mine Octopus, normal GMiner mining 5 algos and lolMiner mining 2 algos.

Latest NHM 3.1.0.5 Win 10 22H2 19045.2728

**Comment by object05** [comment]
Hi, here is an **updated** guide for adding your own miners: https://github.com/nicehash/NiceHashMiner/tree/dot_net_update_nhmws4/doc/UserPlugins
I have tried this for your exact situation (following this guide) and i could mine on multiple gpus, so try this.

Most users forget to add a device separator to the `MinerSettings.json` so be sure to add a space (or copy the following file):
```
{
  "init": false,
  "PluginEngine": 0,
  "use_user_settings": true,
  "devices_separator": " ",
  "algorithm_command_line": {
	"Octopus": "-a octopus -s stratum+tcp://{POOL_URL}:{POOL_PORT} -u {USERNAME} --api 127.0.0.1:{API_PORT} -d {DEVICES} --watchdog 0 {EXTRA_LAUNCH_PARAMETERS}"
  },
  "algorithm_command_line_ssl": {
	"Octopus": "-a octopus -s stratum+ssl://{POOL_URL}:{POOL_PORT} -u {USERNAME} --api 127.0.0.1:{API_PORT} -d {DEVICES} --watchdog 0 {EXTRA_LAUNCH_PARAMETERS}"
  }
}
```
If you have problems with this, feel free to contact me.

**Comment by MolochBaal** [comment]
> Hi, here is an **updated** guide for adding your own miners: https://github.com/nicehash/NiceHashMiner/tree/dot_net_update_nhmws4/doc/UserPlugins I have tried this for your exact situation (following this guide) and i could mine on multiple gpus, so try this.
> 
> Most users forget to add a device separator to the `MinerSettings.json` so be sure to add a space (or copy the following file):
> 
> ```
> {
>   "init": false,
>   "PluginEngine": 0,
>   "use_user_settings": true,
>   "devices_separator": " ",
>   "algorithm_command_line": {
> 	"Octopus": "-a octopus -s stratum+tcp://{POOL_URL}:{POOL_PORT} -u {USERNAME} --api 127.0.0.1:{API_PORT} -d {DEVICES} --watchdog 0 {EXTRA_LAUNCH_PARAMETERS}"
>   },
>   "algorithm_command_line_ssl": {
> 	"Octopus": "-a octopus -s stratum+ssl://{POOL_URL}:{POOL_PORT} -u {USERNAME} --api 127.0.0.1:{API_PORT} -d {DEVICES} --watchdog 0 {EXTRA_LAUNCH_PARAMETERS}"
>   }
> }
> ```
> 
> If you have problems with this, feel free to contact me.

Wow, that was the problem, I had a comma instead of a space (since most miner use comma), thank you very much. Thats why it worked with only 1 gpu.

I followed that guide long time ago, so I learnt how to do it, but it is missing something, you have to edit config/AcceptedPlugins.json so it will let you edit the overclocks/power and enable/disable algos over NHM.

Neverless it could be great if they just update the miner :D

**Comment by object05** [comment]
Thanks for reporting this, i updated the guide on the (on the `dot_net_update_nhmws4 ` branch), and yes, we will probably make an update on GMiner soon.
