### ISSUE TITLE
MP.MiniZ.dll v16.0 causes NiceHash 3.1.0.6 to hang with perpetual "Not connected to NHMWS"

### ISSUE THREAD

**Issue by s33butler** [nicehash/NiceHashMiner#2879]
MP.MiniZ.dll v16.0 causes NiceHash 3.1.0.6 to hang with perpetual "Not connected to NHMWS"

NiceHash: version 3.1.0.6
Plugin: MiniZ
Plugin ID: eda6abd0-94eb-11ea-a64d-17be303ea466
Plugin version: 16.0
Plugin DLL: MP.MiniZ.dll

Recruitable:  Yes
Temp Resolution:  delete, move or rename  MP.MiniZ.dll  in plugin folder.
(this however removes the MiniZ plugin from NiceHash)

Thanks for your time and consideration, keep up the great work.

**Comment by alanH1998** [comment]
Hi, 
MiniZ plugin along with some others is no longer officially supported in NHM (for quite some time now). The 3.1.0.6 version only supports versions 19. 
You can still use it if you add it as a custom plugin (follow this tutorial): https://github.com/nicehash/NiceHashMiner/tree/dot_net_update_nhmws4/doc/UserPlugins

If you have any trouble importing it, let me know

**Comment by s33butler** [comment]
So it's recommended to remove any sub v19 plugins that may have been carried over though normal updating of NHM?

Perhaps a warning if sub v19 are detected that they should be removed as it may cause instability and they are no longer supported?  There is no indication they are not supported in NHM by the way.

![image](https://user-images.githubusercontent.com/23462191/233874126-96b746f1-fe23-489a-842e-cd4d1ac3565c.png)

Thanks for your time and consideration, keep up the great work.

**Comment by alanH1998** [comment]
Thank you for reporting this, you are right... The obsolete plugins should not have been shown on the list. 
The problem has been fixed, fix will be available in the next version

**Comment by s33butler** [comment]
While I'm saddened I'll have to rebuild the plugins manually, I'm still happy to have helped.  Thanks again.
