### ISSUE TITLE
Sgminer is not terribly impressive for mining Signatum. I have read that ccminer works bettererer.

### ISSUE THREAD

**Issue by dinicthis** [nicehash/NiceHashMiner#288]
I only got ten coins per 24 hours or so mining SIGT with sgminer-skunk-2.2 or whatever it's called, and the thieving "vanish and not answer emails" pool sigt.pool.mn, which I advise miners to avoid.

I have heard other say that ccminer gives big increases. Could they include it with the latest version of NHML?

i can experiment with it on sigt pool, see if they respond.

But, if it jumps from 10 coins per day to 12, that's still about 48 cents for a day of mining. Whoop de doo.

I am making about $2.50 per day with my laptop and tower going. I don't see mining Signatum at full honk doing anything but lowering my payouts for Zcash mining.

**Comment by DillonN** [comment]
ccminer tpruvot is already used in NHML for NVIDIA cards

**Comment by dinicthis** [comment]
I think SIGT  is just too cheap to bother with. And sigt.pool.mn doesn't
answer customer support questions. I avoid them now.

I made 10 SIGT per day mining it for a while but 55 cents a day failed to
impress.
