### ISSUE TITLE
Status is unknown after running over two days in NHM 3.1.0.6.

### ISSUE THREAD

**Issue by i1itione** [nicehash/NiceHashMiner#2884]
This issue doesn't happen in the NHM 3.1.0.4, and actually it is still mining (from history records), so I guess that's something wrong related with NH server and NHM 3.1.0.6?

<img width="320" alt="NHM_20230501001" src="https://user-images.githubusercontent.com/21694907/235460687-b710df59-7f7b-4c7c-a8e0-18b72c7e19c5.png">

**Comment by alanH1998** [comment]
Hi, this has been fixed for the next version and it should be available today or at most tomorrow.
