### ISSUE TITLE
Nicehash crashes on Loading Miner Plugins

### ISSUE THREAD

**Issue by som3rando** [nicehash/NiceHashMiner#2886]
Hi, recently my nicehash miner stared crashing i am unsure what caused it probably a windows update because it was running normally a few days ago.
OS and build: Windows 11 22H2 (build 25314.1010)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/11472825/log.txt)

**Comment by alanH1998** [comment]
Hi! 
The log you sent confirms there is a problem but unfortunately it gives me only a general location of it. 

Lately people are reporting NHM crash during loading (after windows updates) - because windows defender is automatically being turned on and deleting important files (so please confirm it is still off)

In any case, for starters get a clean install of the NHM.

If the problem continues, report back and i will start digging for the problem.

**Comment by som3rando** [comment]
> Lately people are reporting NHM crash during loading (after windows updates) - because windows defender is automatically being turned on and deleting important files (so please confirm it is still off)

Hi,
well I have never had windows defender off its was always on and it didn't cause any issues, i now turned it off and reinstalled NHM and it's still not working
also thanks for the quick reply

**Comment by alanH1998** [comment]
Ok so this would look like a plugin issue... It also seems to be isolated to your GPU... To find out which one is causing the problem, 
1. go to `install_directory\miner_plugins`
2. move ALL the uuid folders (for example `0e0a7320-94ec-11ea-a64d-17be303ea466`) out of the folder (save all the folders, somewhere else, you will need them)
3. run NHM with empty `miner_plugins` directory
4. if that works, add the uuid folders back one by one, and run NHM after each move
5. that should give us the cause... 

If the above fails, do the same with a clean install (before you run it for the first time) but i think the above should do...
Let me know the results, and i will try to test it on the same gpu as yours...

**Comment by som3rando** [comment]
I emptied the miner_plugins folder and tried to launch NHM and it still had the same issue stuck at 64% and starts to not respond.

**Comment by alanH1998** [comment]
We have tried to recreate your situation on 2 same gpus as yours, but unfortunately unsuccessfully. 
What i would recommend is you try to run it from the zip package (download zip, unzip it and run), just to see what happens. 
Have you updated AMD drivers recently? 
You probably dont have any other antivirus running or anything right? Sadly in most cases lately, our files are getting deleted without asking

**Comment by som3rando** [comment]
> What i would recommend is you try to run it from the zip package (download zip, unzip it and run), just to see what happens.

I have also done this, when it started bugging i uninstalled the previous NHM instance and I replaced it with the ZIP package  

>Have you updated AMD drivers recently? 

A recent windows update changed the AMD driver so I cant really update it does it thru windows updates.

>You probably dont have any other antivirus running or anything right? 

No i don't have any other antivirus

**Comment by som3rando** [comment]
I have managed to figure out what was the issue that caused the crashes, it was the AMD driver, over the last few months they have been rather buggy and unstable i assume the cause of it was the windows update mentioned above, i reinstalled the drivers and it stated working again.
Thanks you for you assistance

**Comment by alanH1998** [comment]
Thanks for posting the fix to your issue... I hope you will not have any more problems regarding this in the future :D
