### ISSUE TITLE
NHM 3.1.0.7: automatic mining does not start AGAIN (issue #2724)

### ISSUE THREAD

**Issue by DarkMoose92** [nicehash/NiceHashMiner#2887]
Hello!

The problem described in #2724 was solved without my teaching, everything was super cool until it started again...

My machine (via the task scheduler) reboots every 2 hours. Nicehash is on autorun - it starts correctly after every Windows startup. I also have mining autostart enabled when nicehash is turned on.

And here is the problem with the second point again: Windows loads, nicehash starts, mining does not start. And sometimes it starts. Just like in #2724, if I manually close and open nicehash, mining will start automatically when nicehash is loaded.

I can't understand what causes this behavior. What logs to watch, what to catch in them?

"idle when there is no internet" setting is disabled. The Internet is available, but the first autostart of the miner does not start mining.

I tried to turn on "Mining when idle 5 seconds after the last input" - it works in general terribly. Mining may not start easily. What it depends on is not clear. The latest version is as of today. Damn, version 1.9.x worked perfectly and without complaints...

**Comment by alanH1998** [comment]
Hi, sorry for your inconvenience... Thanks for reporting it, i will investigate the issue... 
Are you using any specific miner or do you have multiple selected?
As for the logs, the main one to watch is the `logs/log.txt`, but judging from your description that it happens only sometimes, i doubt it's logged.

**Comment by alanH1998** [comment]
When this situation happens (mining doesnt start), are there any gpus in error state inside NHM or the start button is greyed out?

**Comment by DarkMoose92** [comment]
> When this situation happens (mining doesnt start), are there any gpus in error state inside NHM or the start button is greyed out?

@alanH1998, Hello. The "start" button in nicehash is green at this moment and it is ready to be pressed (after pressing, mining will start correctly)

So far I have found a solution: I created a task to close and reopen nicehash a couple of minutes after Windows was launched. In my country we call it a "crutch".

I'll test it for a couple of days and write here the text for the .bat script

**Comment by alanH1998** [comment]
Thats an interesting fix... How is it so far? I think a delay could also potentially fix your problem (i cant test it because i cannot recreate the issue on my machines)... So when your computer starts, it could be overwhelmed by all the processes starting so it eats up some of them...

Since you know how to script, you could disable the NHM run on startup and start it up via a .bat file after a delay of like 20-30s, but leave the option "start mining when nhm starts" on...

If you decide to test this, let me know if it works and we can potentially add it to NHM

**Comment by DarkMoose92** [comment]
Three days have passed and my crutch is working fine.

Thanks, it's a good idea to simplify the script!

I disabled NicehashMiner autostart on Windows boot. Auto start mining when Nicehash starts - I left it enabled.

Now, when Windows starts, after 180 seconds I will start Nicehash using a script through the task scheduler.

I will keep an eye on this. I think it will work.

--

Indeed, the PC for mining is rather weak: Pentium, 8GB, slow HDD. Plus: MSI Afterburner can eat a lot of PC resources.
