### ISSUE TITLE
Fan profile dont work

### ISSUE THREAD

**Issue by hl0r0f0s** [nicehash/NiceHashMiner#2888]
In new versions 3.1.0.7 dont work fan profile for RX 480 8G and beginn MSI Afterbunrer  crash. I'm back to 3.1.0.4. Windows 10.

**Comment by hl0r0f0s** [comment]
Excavator crashed Afterburner, i turn off it.

**Comment by alanH1998** [comment]
I need more info about this situation, what are you mining, what profile exactly,...
