### ISSUE TITLE
Mining stop will often result in a few seconds of black screen

### ISSUE THREAD

**Issue by fallenguru** [nicehash/NiceHashMiner#289]
When mining stops, either because the stop button was pressed, the machine is no longer idle (in case auto-idle is active) or because algos are switched in benchmarking or live, chances are I'll get a black screen for a few seconds, the monitor acts like the signal is suddenly gone. Now, when this happens, it does recover, but the card might reset to default settings (= back up to 100% power target), it might "vanish" from the system until next reboot, or be fine ...

1x Nvidia 1070; Windows 7; no overclock (yet), just reduced power target (but also happens at 100%)

[More info available on request, I don't like to attach everything but the kitchen sink without good reason.]

EDIT: Normal algo switching is also affected, it's just less noticeable because it doesn't crash at every stop, I don't get that many switches in the first place and I might not notice them because I'm not at the screen.

**Comment by jimmyhackers** [comment]
im getting the same with my 1080ti......i thought my card was "defective" but it appears to be software issues (kinda nice to know its not just me). so far i think ive figured out switching from lyra3rev2 to another was the one that caused the "most" problems.

it made my card dissapear untill pc restart. causing much mining time loss. i have deselected ithe algo and all seems well. 
although literally while typing this is switched from equihjash to neoscript for a bit and a got a screen blackout and a driver error notification but all seems well and it continued to mine as normal. and was fine on the switch back to equihash.

**Comment by Sav87** [comment]
All problems with the restart of the graphics card driver in the wrong algorithm of the completion of the process of the miner. The error that occurs when you press the "Stop" button, switch the algorithm of the miner, and complete the benchmark algorithm.

**Comment by jimmyhackers** [comment]
ive updated my graphics card bios (not to be confused with the driver) from the palit official site.

it appears to have dropped my boost clocks max clock down.  
as this was a man refurbed/second hand card i have no idea if it was a standard bios to begin with.
ive saved the file and can post it on here if anyone who smart enough to figure it out wants to take a gander.

**Comment by ChriscomIT** [comment]
Check if your PSU is big enough. Check if the cards do not do undervolt too much when you set power target lower. Worst case would if your VRAM has some issues. BTW what driver version are you guys running? VBIOS updates are not recommended if you do not exactly know what you do. You can easily brick your card or get problems such as described here. Mostly it sounds like stability issue with your graphics cards/machines.

**Comment by fallenguru** [comment]
Yes, this could be a hardware issue, but then almost anything could, especially if it's related to stability. Then again, "It's your hardware!" is the easy way out because shifts the blame from the software to the user, who hasn't a way to prove otherwise.

But ok, I'll bite. Neither the hardware in general nor the GPU specifically does exhibit any other issues. Temps are fine (card <= 60°C, rest < 40°C), peak power draw at the wall is < 40% rated capacity. Driver is newest official (385.41), card is new with untouched BIOS. NHM2 (excavator) does run for days on end without a hitch. 

On a hunch I'd say that the problem occurs when the wrong miner (Claymore, most of all) is stopped at the wrong moment. From a cursory glance at the code it looks like miners are just killed without giving them a chance to clean up first ... FWIW, if I "turn off" the card by pressing [0] in Claymore's console first and then stop mining, it hasn't crashed yet ...

**Comment by Sav87** [comment]
This is a problem both of software and hardware. I say this as I have such a problem. I repeat it occurs only at the moment of pressing the "Stop" button or closing the window to the "red cross" window of course not every time, but it's unpleasant. There is a solution to it in the NHML code, after making the change, it works a week continuously switching algorithms.

**Comment by Sav87** [comment]
I added it to my pull request [#312](https://github.com/nicehash/NiceHashMinerLegacy/pull/312)
