### ISSUE TITLE
Feature Request: OC Profiles

### ISSUE THREAD

**Issue by jamespatt125** [nicehash/NiceHashMiner#29]
MSI Afterburner support the changing of OC Profiles via command line
Example: MSIAfterburner.exe –Profile1
Can you add an option to change MSI Afterburner Profiles when switching algorithms?

**Comment by adrivansoft** [comment]
I think there is no need because this is built into the miners. You can use params like -cclock and -mclock for OC. You can even under volt and vice versa.

**Comment by jamespatt125** [comment]
I checked a couple of miners with no luck.

ewbf-miner - can't find any OC commands
ccminer_nanashi - can't find any OC commands
claymore_dual - has OC commands but does not support NVIDIA

I still think this feature could be usefull.

**Comment by DillonN** [comment]
At the moment overclocking is not supported from within NHML. This may change in the future, or maybe an ability to launch programs when specific miners are launched (where you could use the Afterburner commands you mentioned).

**Comment by justsomedudeonthenet** [comment]
The simple generic solution here would be to let us specify pre-launch and post-launch commands in addition to command line arguments for each miner.

**Comment by DillonN** [comment]
Refer to #208 for batch file running on switch
