### ISSUE TITLE
Update benchmark values during mining / use mining values as benchmark

### ISSUE THREAD

**Issue by fallenguru** [nicehash/NiceHashMiner#290]
1) The current benchmarking model of NHML works ok as long as you assume that the speed of a given algo on a given card never changes (or only very infrequently), but with over-/under- -clocking/-volting, power limits, -dcri and other intensity tuneables, different drivers ... available, I don't think that assumption holds any more. In any case, finding the best combination of settings seems like a never-ending task when you have to re-benchmark every step of the way. Even more so because you always have to do all (remotely profitable) algos in order not to break switching.
2) At least in my case, hash rates obtained during benchmarking (even precise) and live ones aren't all that close to begin with. 

I'd like to see an option to continuously update the benchmark value(s) of an algo using a suitable rolling average of the current run. (Maybe even one to mine for a couple of minutes every day on active but deemed unprofitable algos, just to see if the data's still current.)

**Comment by lmlim** [comment]
+1
yes this is very handy, indeed.
also autotune/autofind best -dcri value for each device will be plus too.

i found out that manual benchmark is a very tedious process, even just changing 1 variable.
eg : you need 2 runs for changing -dcri, 1st for finding -dcri value by mining it, then benchmark it after putting -dcri value in.

**Comment by Singman33** [comment]
My script (under Linux) is updating the hashrate in the config file after each check of profitability. That will help a lot.

**Comment by MonaxDK** [comment]
An interesting idea, especially for older video cards, like GTX970. When mining on ClaymoreDual, the DAG epoch is constantly changing, and hash rate of the card is also changing.

**Comment by DillonN** [comment]
I can't say for sure it will be in an upcoming update but know we've been looking at this
