### ISSUE TITLE
NHM 3.1.0.8 broke the "current local profitability" on the web

### ISSUE THREAD

**Issue by MolochBaal** [nicehash/NiceHashMiner#2908]
![local profitability](https://github.com/nicehash/NiceHashMiner/assets/89867957/13f8b459-33ea-4dd3-9ef8-d9f493ecada0)

First, great job adding NEXA. IronFish could be a good addition too.

The issue is pretty much the title, only "current actual profitability" is working.

**Comment by m1buchnev** [comment]
I have faced with the same behavior since NHM **3.1.0.7**

**Comment by MolochBaal** [comment]
> I have faced with the same behavior since NHM **3.1.0.7**

Oh I update from 3.1.0.4, so I didn't notice it before. Then this bug came from previous version 3.1.0.7

**Comment by alanH1998** [comment]
Hi, thanks for reporting this bug, we are aware of it, and i hope a fix will be ready shortly

**Comment by hl0r0f0s** [comment]
Dont work buttons 'start mining' and 'stop mining' in web managment for all rigs.

**Comment by rodericklm1** [comment]
![image](https://github.com/nicehash/NiceHashMiner/assets/20000450/b6d9d58a-b3f0-4df1-a4a9-3f93bebdec6e)
![image](https://github.com/nicehash/NiceHashMiner/assets/20000450/1a5c3b12-5e78-4070-b1cc-dd84fa837dbd)
Can not install or update any plugins besides XMRig after upgrading. I have a GTX1060 and GTX1070 cards. When I click install it acts like it installs but then I get a message saying that new version was not installed.

**Comment by MolochBaal** [comment]
> Can not install or update any plugins besides XMRig after upgrading. I have a GTX1060 and GTX1070 cards. When I click install it acts like it installs but then I get a message saying that new version was not installed.

Maybe running NHM as admin will fix the issue.

**Comment by MolochBaal** [comment]
It's fixed now :)
