### ISSUE TITLE
Easier manual or even (semi)automatic tuning.

### ISSUE THREAD

**Issue by fallenguru** [nicehash/NiceHashMiner#291]
Currently, tuning is more of a hassle than it needs to be, here's a few suggestions:

- make benchmark results exportable as .csv and allow the user to label each set (sure beats having to type them into Excel by hand)
- calculate profit, not revenue. Given the marginal cost per kWh, the current power draw of the cards (some miners display that already) and the systems total power draw (could be estimated from sensors, if available [Linux] or manually input base value plus card draw; maybe even manual calibration via kill-a-watt), it's as simple as calculating BTC/d * USD/BTC - power cost. Yet it's almost impossible to do in Excel because USD/d for a given algo fluctuates too much.
- enable NH to set common card parameters, like TDP / power target, clocks ... so that a) they can be set per algo; b) they're guaranteed to be enabled when mining with a given algo starts; c) they're guaranteed to be reset to a safe base profile just before it stops.
- interactive/assisted benchmarks. Given the last two features NH could implement automatic dynamic tuning, but I'd settle for an interactive mode (like Claymore has for dcri) that lets me see the impact of changes in real time and maybe keeps track of the numbers in a "getting warmer, getting colder, best yet"-way for a given goal (max profit, max hash rate, max efficiency).

**Comment by DillonN** [comment]
Will look into this!
