### ISSUE TITLE
NiceHash wont start, stuck at 64%

### ISSUE THREAD

**Issue by Samsonait** [nicehash/NiceHashMiner#2912]
Also see:
https://www.reddit.com/r/NiceHash/comments/14z1f6c/nicehash_gets_stuck_loading_at_64/
and
https://www.reddit.com/r/NiceHash/comments/14oj8ed/nicehash_miner_stuck_on_loading_plugins_at_64/

Tried:

Multiple different versions, cleaned up appdata. Excluded the appdata\local\programs\NiceHash folder
Process whitelisted:
app_nhm.exe
NiceHashMiner.exe

But nothing, Reinstalled AMD graphic drivers but nothing.
How do i proceed to give you logs?

**Comment by alanH1998** [comment]
hi, i'm aware of this issue and investigating whats going on... honestly right now i  cant tell you whats wrong, it seems like it has to do something with the combination of amd driver 23.7.1 and at least one 5700XT or 6700XT... It seems like the update/downgrade of drivers does the trick for some people.... 
please tell me if you have the following files:
- `INSTALL_DIR/app_3.1.0.8/device_detection_opencl_adl.dll`
- `INSTALL_DIR/miner_plugins/(every_folder)/(MP.{miner}.dll)` FOR EXAMPLE `INSTALL_DIR/miner_plugins/0e0a7320-94ec-11ea-a64d-17be303ea466/MP.XMRig.dll` (please check in all folders of miner_plugins)

besides this, you can send me the tmp._archive_logs.zip folder created with CreateLogReport.exe in the install directory so i can see why its crashing

**Comment by alanH1998** [comment]
It seems i have found the reason for the crash, and it is related to the specific driver that is mentioned above... A new version will be available soon

**Comment by Samsonait** [comment]
Hi there! i just wanted to get you some info back. I have an RX 7900XT with a AMD Ryzen 9 7900X
Would you like me to give you a log file?

And every plugin folder got the DLL file and the i also got the Device detection opencl file
I also have 23.7.1 AMD

[tmp._archive_logs.zip](https://github.com/nicehash/NiceHashMiner/files/12076613/tmp._archive_logs.zip)

**Comment by alanH1998** [comment]
Thanks! so the conclusion is its not antivirus or defender or whatever this time, they changed something in the driver interface and it just stopped working... so the fix for now should be to downgrade to an older driver version, or wait for a new version of NHM which _should_ be available soon

**Comment by Samsonait** [comment]
Downgraded to 23.5.1 seems to fix the issue indeed. Thanks man! I think we can come to the conclusion that this is fixed.

**Comment by alanH1998** [comment]
Ty for your cooperation! If you have any more issues in the future, feel free to open a ticket...
