### ISSUE TITLE
wont load plugins and boot loops

### ISSUE THREAD

**Issue by ITZJOK3RII** [nicehash/NiceHashMiner#2913]
so yh click to load nice hash 3.1.0.8 and its get to 64% and crashes and reloads this continues for 3 to 4 time be fore i get the message nhm experienced too many crashes recently, therefore it close itself. see it did work till windows updated the Microsoft defender and i cant get it to roll bk the update with out reinstalling windows. any help wound be amazing plz and thank you.

**Comment by alanH1998** [comment]
Hi, please downgrade your amd drivers to something lower than 23.7.1

**Comment by alopalka** [comment]
Downgrading for driver with version <23.7.1 fixes issue
