### ISSUE TITLE
NiceHash crashes on startup

### ISSUE THREAD

**Issue by Fotomac** [nicehash/NiceHashMiner#2916]
NiceHash used to work on my laptop until I installed BitDefender on it, and now it's crashing on the splash screen every time! What happened? What can I do to fix it? Here's the relevant log file.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/12216063/log.txt)

**Comment by alanH1998** [comment]
hey, please try the 3.0.1.9 RC version, it is online already and contains a fix for this
https://github.com/nicehash/NiceHashMiner/releases/download/3.1.0.9/nhm_windows_3.1.0.9.zip
