### ISSUE TITLE
The pause button on NHM causes a spike on the video card power draw (to the max)

### ISSUE THREAD

**Issue by MolochBaal** [nicehash/NiceHashMiner#2917]
Just noticed after I added 1 more card to my rig, that if I press the pause button, the power supply will shut down because of the over power protection. And that only happen with the pause button, when the miner shut down and change algorythm it works as intended, same as the miner without NHM.

Here is a screenshot with only one card on my PC, mining kawpow with a 3070, around 145W then when I press the pause button it spikes to 220W (max TDP for a 3070).

![pause mining](https://github.com/nicehash/NiceHashMiner/assets/89867957/93e9be72-2f7c-4bb4-9ea9-8f68f5dcbce2)

Now the same, shuting down the miner (Ctrl+C) without NHM, it just goes down without a power spike

![shut down miner](https://github.com/nicehash/NiceHashMiner/assets/89867957/66d71842-0f81-482e-8b53-864976ba0ae5)

NHM 3.1.0.9, idk about previous versions, just tested with this.
Windows 10 Pro 22H2
Tested with nvidia drivers 536.67 and 528.49

**Comment by alanH1998** [comment]
Hi, i will look into it, my guess is the functionality for resetting overclocking is causing this but at the moment i am only guessing...
So if i understand correctly it goes to 100% TDP then shuts down right?

**Comment by MolochBaal** [comment]
> Hi, i will look into it, my guess is the functionality for resetting overclocking is causing this but at the moment i am only guessing... So if i understand correctly it goes to 100% TDP then shuts down right?

Hi, correct, but this only happen with the pause button, when switch algo/miner it works fine.

**Comment by alanH1998** [comment]
ok... The problem is that your gpu detects both max and default tdp values as the same thing. When NHM is closed or stopped, the values are forced to default. I will try to figure out what to do in your situation, probably something like manually disabling resets with a toggle in settings or something like that.

**Comment by MolochBaal** [comment]
> ok... The problem is that your gpu detects both max and default tdp values as the same thing. When NHM is closed or stopped, the values are forced to default. I will try to figure out what to do in your situation, probably something like manually disabling resets with a toggle in settings or something like that.

Yeah, a toggle option would be great, or just disabled it, since every miner reset the values after the close call.

**Comment by alanH1998** [comment]
do you know, by any chance how to build NHM yourself? otherwise i will need to somehow send you the test build privately, since i cannot recreate the problem and test it...

**Comment by MolochBaal** [comment]
> you know, by any chance how to build NHM yourself? otherwise i will need to somehow send you the test build privately, since i cannot recreate the problem and te

I've never compilated a big software before, just small code in C. So maybe just send me the build and I can test it and reply if it works.

**Comment by alanH1998** [comment]
can contact me on discord? it would be easier to do the talking there... 
`object_dev_NiceHash` (object98)
