### ISSUE TITLE
centralized update

### ISSUE THREAD

**Issue by coolbtc** [nicehash/NiceHashMiner#292]
Good afternoon. 

I have 20 farms (NHLM 1.8.1.2, Win 10x64). Every time a new version of the NHLM comes out, I manually update each farm. Is it possible to make the update more centralized? For example, locally on the farm store only the "config" folder, and store the folder with the working content in the local network on the SMB share( \\server\NHLM \). Then, to update the NHLM, it will be enough just to replace the contents of this network SMB folder and do not waste time updating each farm separately.

I would also like to have a tool for central monitoring of farms (current daily profit and mining algorithm, the number of GPUs running, the hashrate and temperature of each GPU, the time on the current mining algorithm, the time since the last reboot), and management (start / stop mining, reboot the farm , update of the miner)

thx.

**Comment by DillonN** [comment]
The website can be used for monitoring

You can achieve the other with symbolic links
