### ISSUE TITLE
I am using another tool for managing my video card's fans (such as MSI Afterburner) and fan speed is occasionally reset to automatic. How can I fix this?

### ISSUE THREAD

**Issue by javifly** [nicehash/NiceHashMiner#2921]
I am using another tool for managing my video card's fans (such as MSI Afterburner) and fan speed is occasionally reset to automatic. How can I fix this?

**Comment by javifly** [comment]
I'm using NiceHash Miner 3.1.0.9. I can't be like this, the power consumption is excessive, today I'll turn off the 3 rings until I find a solution...

**Comment by alanH1998** [comment]
Hi, the next version will have a toggle to disable all automatic tweaking and stuff like that

**Comment by javifly** [comment]
Great! Until then I have created a script that applies the MSI Afterburner settings every 60 seconds. So if NiceHash Miner ever increases the power consumption of the graphics cards, it only takes a few seconds to restore the settings back to the way they should be. Anyway, thank you very much for giving me a solution soon and not having to abandon this program and use other ones...
