### ISSUE TITLE
> My funds

### ISSUE THREAD

**Issue by Pyakouto** [nicehash/NiceHashMiner#2923]
> My funds

I haven't received the transaction.

__Originally posted by @Pyakouto in https://github.com/nicehash/NiceHashMiner/issues/2815#issuecomment-1310347215__

**Comment by alanH1998** [comment]
Please contact our support team here on our discord or here https://www.nicehash.com/support/my-cases

**Comment by Pyakouto** [comment]
I still did not received my transaction.
