### ISSUE TITLE
msvcr120.dll insert into claymore and ewbf miners?

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#293]
The msvcr120.dll issue is still occurring as of 1.8.1.2.  It happens on a various number of computers (all of which use Nvidia cards).

Could you add the msvcr120.dll into all the claymore 3rd party miner folders and the ewbf third party miner folder to resolve this going forward?

**Comment by riccardoruspoli** [comment]
https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Troubleshooting#msvcp

**Comment by Sav87** [comment]
Once you set the environment variable "PATH" to the folder with * .dll using SethEnvironmentVariable in the NHML code, and all the child processes will look for it there.

**Comment by billmcilhargey** [comment]
updated to the latest version of the VC++ 2017 and it resolved

Thank you!
