### ISSUE TITLE
Bugs/problems

### ISSUE THREAD

**Issue by LoNE-W0LvES** [nicehash/NiceHashMiner#2930]
UI so laggy, 
clicking someting doesn't work like stop all or start all, 
sometimes  new terminal opens but terminal is black and stopps mining (it says mining but it is 0.000000000BTC), 
can't hide terminals so annoying, can't evven work when mining that freaking terminal pops up
super not responsive GUI

**Comment by alanH1998** [comment]
Hi, can you describe what you are mining when this happens? i mean which miner
