### ISSUE TITLE
NHMWS not connected

### ISSUE THREAD

**Issue by xinghuawang123** [nicehash/NiceHashMiner#2939]
![9d0f3bd3f6a6c5ed042f1f7bb434b3f](https://github.com/nicehash/NiceHashMiner/assets/164117256/a693122c-223f-4026-b50d-969f606fbb84)
![3e9c9377ea22d29f3d4c3381aa74301](https://github.com/nicehash/NiceHashMiner/assets/164117256/5967a46a-bd71-441a-9cb4-e26ce0f7d69f)
I havetried all the way that the offcial web wrote, such as Change DNS, Trun off fire wall, and trun off the VPN. but it doesn`t work

**Comment by alanH1998** [comment]
Hi, which version are you using? and when did u start encountering this problem?

**Comment by alanH1998** [comment]
and also, which GPUS do you have and how many?
if you can take a moment and go to the `NHM directory/logs ` and open the log.txt (or all of them if you have more) and search for `bye` (this means the server-client communication was shut down)
If you have this message, let me know and we will continue with the problem

**Comment by alanH1998** [comment]
closing due to no reply, feel free to open a new issue if problems occur
