### ISSUE TITLE
XMRIG missing

### ISSUE THREAD

**Issue by PrinceOfParallax** [nicehash/NiceHashMiner#2941]
The current build on XMRIG is xmrig-6.21.2 - NHM is still using 6.8.1 (from 2020). This is causing incompatibilities with some chains and pools. Can we PLEASE update the build the miner users.

**Comment by sunshine-cid** [comment]
Two things...
1. XMRIG was removed in the latest release, which was about a month ago I believe.
2. You've always been able to 'drop in' the latest version of XMRIG by just unzipping the latest release in the XMRIG directory. Search your Nicehash directory for it's location.
2a. You can actually add XMRIG to the latest version by copying the funny-named directory with XMRIG.dll and its subfolders into the latest release.

**Comment by PrinceOfParallax** [comment]
Nope the newest version freaks out, I assume something changed with the "web" interfaces that NHM uses.

**Comment by giosal** [comment]
I had XMRig in v 3.1.0.9 but it has disappeared in v.3.1.1.0
