### ISSUE TITLE
NHM does not support modern AMD GPUs

### ISSUE THREAD

**Issue by Zenguycolorado** [nicehash/NiceHashMiner#2951]
NHM is still not supporting AMD 7000 series GPUs. Every benchmark fails. Why has this still not been fixed?

**Comment by alanH1998** [comment]
Hey man sorry for the delay, the latest AMD appear to be the issue... for now, the best solution would be to downgrade to drivers 23.12.1. I just tried with lolminer and a 7900 XT and it started working after the downgrade.

**Comment by Zenguycolorado** [comment]
Thanks for the advice but it's not worth the loss of functionality using these older drivers.

**Comment by alanH1998** [comment]
yes i agree... sorry for the inconvenience, i hope this gets fixed since it only shows when a 7000 series is present
