### ISSUE TITLE
NHM cant connect to server (ZelHash. KarlsenHash)

### ISSUE THREAD

**Issue by hl0r0f0s** [nicehash/NiceHashMiner#2953]
![Screenshot 2024-05-31 093351](https://github.com/nicehash/NiceHashMiner/assets/47705315/40a3d733-6f7b-46a9-9355-c88d625d187f)

Work only with VPN. So it blocking providers.
Very need choise proxy or choise target sever (differnent regions, like before).

**Comment by alanH1998** [comment]
hi, are you still experiencing this problem? How did the problem start, did it work before?

**Comment by hl0r0f0s** [comment]
> hi, are you still experiencing this problem? How did the problem start, did it work before?

I change DNS in my router. it fix issue.
