### ISSUE TITLE
Unable to setup Nicehashminer.

### ISSUE THREAD

**Issue by skyb180** [nicehash/NiceHashMiner#2955]
![image](https://github.com/nicehash/NiceHashMiner/assets/173194872/b7eff93d-819c-444b-86c2-7b1a2d4b5e5b)
![NiceHashMiner - Issue](https://github.com/nicehash/NiceHashMiner/assets/173194872/4e05f491-5b8b-4826-9444-513714e78a44)

Unable to setup Nicehashminer. What willbe the possible error? Need urgent help

**Comment by Polygons1** [comment]
What is your hardware?

**Comment by alanH1998** [comment]
i need some details about hardware and driver versions
