### ISSUE TITLE
Downloaded the file, but no application ;(

### ISSUE THREAD

**Issue by ggboots** [nicehash/NiceHashMiner#296]
I've downloaded the AMD file but for some reason theres no working application inside, theirs only a SLN 
file

**Comment by riccardoruspoli** [comment]
Have you downloaded from the bin.zip link?

**Comment by luongk** [comment]
@ggboots99 has downloaded the source code, not the compiled program (which is why there is an SLN file).

Download the file titled NHML-1.8.1.2_LangFix.zip

**Comment by ggboots** [comment]
I've downloaded both the source code and LangFix files, im pretty unsure of what files i should be downloading ....

**Comment by ggboots** [comment]
I've downloaded the bin.zip link but the application on that once extracted fails :(

**Comment by luongk** [comment]
You want to download NHML-1.8.1.2_LangFix.zip as it has the precompiled executable (the file is poorly named, it's not just a patch). If the exe isn't working then you have another issue (e.g. overly oppressive antivirus).
