### ISSUE TITLE
Benchmarking fails

### ISSUE THREAD

**Issue by shubell** [nicehash/NiceHashMiner#2970]
When you setup a new miner a few benchmarks fail. For example  Gminer and zelhash algorithm 
I traced the problem to the user address used in the benchmark phase. 
While benchmarking these are the used parameters for equihash125_4 
-a equihash125_4 -s stratum+tcp://34.111.218.189:9200 -u 33hGFJZQAfbdzyHGqhJPvZwncDjUBdZqjW --api 127.0.0.1:4000 -d 0 --watchdog 0

If you manually run gminer you get an error
connection error: connection closed

The problem is the address "33hGFJZQAfbdzyHGqhJPvZwncDjUBdZqjW" which is used for benchmarking.
If you replace this address with your address the miner works flawlessly. 

A workaround is to set the benchmark speed manually and the mining will work on that algorithm

**Comment by alanH1998** [comment]
this should fixed in the latest update
