### ISSUE TITLE
Good afternoon a couple of weeks ago there was a problem, the computer may hang in mining "NiceHash" NiceHash nicehash Miner 2 and legacy or miner begins to write something in red letters (server : bind failed with error : 10048 (port for remote managment is busy, use diferent -mport value)next attemp in 20sec) video card 290X 390 RX vega64

### ISSUE THREAD

**Issue by QWer6qed** [nicehash/NiceHashMiner#298]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [x] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.
I'm not one point don't know and don't know how to check, I will be glad if you tell me where to start.

**Comment by QWer6qed** [comment]
I'm not one point don't know and don't know how to check, I will be glad if you tell me where to start.

**Comment by DillonN** [comment]
Try changing the "API Bind port pool start" value in the Advanced settings tab to something different (e.g. 8085)

**Comment by QWer6qed** [comment]
explain where to do it, NiceHash only location I know where to change.
