### ISSUE TITLE
NHML-1.8.1.2_LangFix: Can't Autorun

### ISSUE THREAD

**Issue by IanJNB** [nicehash/NiceHashMiner#299]
I have downloaded and extracted NHML-1.8.1.2_LangFix.zip and can open NiceHashMinerLegacy.exe manually and it runs fine but when I reboot, the version autostarts as 1.8.1.1

I don't see a Setup.exe - how do I fix this problem please?

**Comment by luongk** [comment]
There is no setup.exe - presumably you still have 1.8.1.1 installed on your computer which is the one that's auto starting.

Remove the previous version (or rename the folder) then extract 1.8.1.2 where you had 1.8.1.1.

**Comment by DillonN** [comment]
NHML only runs portable - there is no installer. When you download a new version the Windows key to auto-launch on login still points to the old one. You can remove the old one, turn it off in startup items, or re-check "Run With Windows" in the newly downloaded version which will overwrite the old one
