### ISSUE TITLE
Claymore Dual Miner 9.7

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#3]
I am sure your aware but wanted to call it out incase you want to bundle the latest version as part of the initial release

v9.7 is out now

Latest version is v9.7:

Added ASM mode for RX460/560 cards, up to 30% speedup for second coin in dual mode.
Improved ETH speed for some Nvidia cards.
Improved speed in dual mode for Nvidia cards.
reduced initialization time.
a few minor bug fixes and improvements.
EthMan: added ability to select several rigs.
EthMan: several minor bug fixes and improvements.

https://github.com/nanopool/Claymore-Dual-Miner/releases

**Comment by DillonN** [comment]
Yes 9.7 will be included in the initial release!

**Comment by billmcilhargey** [comment]
Yea!!

**Comment by francescocmazza** [comment]
Hello. That's great, do you have an ETA for the initial release?
Thank you very much

**Comment by DillonN** [comment]
Initial release is live! https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.0.0

**Comment by billmcilhargey** [comment]
Nicely done!!
