### ISSUE TITLE
What is best way to stop mining via powershell?

### ISSUE THREAD

**Issue by CptanPanic** [nicehash/NiceHashMiner#30]
I currently have a powershell script that starts and stops mining using individual mining batch scripts.  Would like to switch to using nicehash, but would like to know if there is a programmatically way to start and stop mining?  Worst case, if I kill nicehashminerlegacy exe, will it kill child miner programs?

**Comment by billmcilhargey** [comment]
Currently NiceHashMinerLegacy.exe has no command line arguments - Feature Request here :)

However I tested the Legacy miner and if you kill the exe it keeps the child processes running ;)

**Comment by DillonN** [comment]
If you kill NHML non-gracefully it will not get a chance to shut down its miners.

However you can kill it gracefully using this powershell command: `Get-Process NiceHashMinerLegacy |   Foreach-Object { $_.CloseMainWindow() | Out-Null }`, and restart it by opening NHML and having auto-start mining checked.
