### ISSUE TITLE
UI Bug: 'Minimize Mining Windows' becomes active after re-opening Settings window

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#303]
The following issue is reproduceable as in 1.8.1.2 as in 1.8.1.3-Pre1.

**Steps to reproduce:**
1. Start NHML
2. Open Settings window
3. Enable 'Hide Mining Windows' (so 'Minimize Mining Windows' option becomes unavailable)
4. Click on 'Save and Close'
5. Re-open Settings window

**Result:** 'Minimize Mining Windows' option is available (see the attached screenshot)
**Expected result:** 'Minimize Mining Windows' option is unavailable

![image](https://user-images.githubusercontent.com/4707112/30288744-e0d9305a-973a-11e7-9b76-e6eeae3446e3.png)

**Comment by DillonN** [comment]
Thanks @adem4ik, should be fixed in most recent commit
