### ISSUE TITLE
NiceHash 1.8.1.3 pre

### ISSUE THREAD

**Issue by kabylike** [nicehash/NiceHashMiner#309]
My machines work on a dual ether and decred. 15 hours already work without any problems. Only increase rejected hash on decred.

**Comment by ChriscomIT** [comment]
Please post here #301. Thanks a lot and next time please look out for existing/open issues!!!

**Comment by kabylike** [comment]
Ok. Thanks.

**Comment by DillonN** [comment]
Thanks for the feedback!

**Comment by xnata** [comment]
Trojan:Win32/Fuery.A!cl Detected with Windows Defender Antivirus
