### ISSUE TITLE
Sort Algorithms according to their values

### ISSUE THREAD

**Issue by abbaselmas** [nicehash/NiceHashMiner#311]
![nicehash sort](https://user-images.githubusercontent.com/28142617/30362960-093ecda2-9867-11e7-8695-9510a4c5b8f1.png)
not an issue but a kind request
it would be easier to choose most profitable ones if the columns can be sorted.

**Comment by 3zero2** [comment]
+1

and also in the debug windows please.

**Comment by mrMad-Cat** [comment]
+1. Sorting all the columns would be great and very useful.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

We will be working on a complete GUI re-design.
