### ISSUE TITLE
can't get my day profit to show 

### ISSUE THREAD

**Issue by pattiz92** [nicehash/NiceHashMiner#313]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [x] The issue has not already been reported.
- [x] Relevant log files are included (generally `\logs\log.txt`).
- [x] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [x] The issue is relevant to NHML specifically and not to the NiceHash service.
- [x] Specifications of setup such as NHML version, Windows version, and hardware are included.

**Comment by pattiz92** [comment]
can't get my daily profit to show

**Comment by adem4ik** [comment]
1) Did you fill 'Bitcoin Address?
2) Did you overwrite old NHML files with newer one in order to update NHML?
