### ISSUE TITLE
Computer freezes

### ISSUE THREAD

**Issue by marcomieke** [nicehash/NiceHashMiner#314]
My computer freezes after a few hours of mining.
Using 1050Ti GPU.
I have to restart by holding start button for a few seconds and then get a reboot.
The program then runs and "online info" indicates that the computer froze several hours ago.

**Comment by Nicheuji** [comment]
Got a feeling that I'm experiencing the same with my 1060.
Only difference is my computer restarts itself

**Comment by bonifacio123** [comment]
Within Afterburner try disabling all under/over volting by settings power to 100. Disable over-clocking by setting core to 0. Disable Memory over-clocking by settings Memory Clock to 0. When I had reboot issues they were due to core overclocking. On my 1080 & 1070 they're really sensitive to core overclocking.

**Comment by marcomieke** [comment]
Thank youI shall try that !Regards


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: bonifacio123 <notifications@github.com> Date: 2017/09/14  21:47  (GMT+02:00) To: nicehash/NiceHashMinerLegacy <NiceHashMinerLegacy@noreply.github.com> Cc: marcomieke <martin@straptite.com>, Author <author@noreply.github.com> Subject: Re: [nicehash/NiceHashMinerLegacy] Computer freezes (#314) 
Within Afterburner try disabling all under/over volting by settings power to 100. Disable over-clocking by setting core to 0. Disable Memory over-clocking by settings Memory Clock to 0. When I had reboot issues they were due to core overclocking. On my 1080 & 1070 they're really sensitive to core overclocking.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nicehash/NiceHashMinerLegacy","title":"nicehash/NiceHashMinerLegacy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nicehash/NiceHashMinerLegacy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bonifacio123 in #314: Within Afterburner try disabling all under/over volting by settings power to 100. Disable over-clocking by setting core to 0. Disable Memory over-clocking by settings Memory Clock to 0. When I had reboot issues they were due to core overclocking. On my 1080 \u0026 1070 they're really sensitive to core overclocking."}],"action":{"name":"View Issue","url":"https://github.com/nicehash/NiceHashMinerLegacy/issues/314#issuecomment-329589321"}}}

**Comment by jimmyhackers** [comment]
miy 1080ti was wigging out like your is......i tried a bios update (not a driver update) from "palits" website.
check out your card manufactuers website and see if they have a bios update available

this seem to of dropped my cards "boost clock max" and stopped all the driver issues
