### ISSUE TITLE
перезапускается комп

### ISSUE THREAD

**Issue by sokol2016** [nicehash/NiceHashMiner#315]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [x] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

**Comment by sokol2016** [comment]
у меня две видео карты nvidia 1060 1070 по отдельности они в  майнере роботают,но вместе компютер перезагружается

**Comment by Sav87** [comment]
Возможно мощности блока питания недостаточно.

**Comment by sokol2016** [comment]
а до етого все роботало нормально,тоисть хватало мощьности блока

**Comment by Sav87** [comment]
Напиши подробней какая система, блок питания. Описывать надо так чтобы вопросов небыло. Чем подробнее тем быстрее решение проблемы.
