### ISSUE TITLE
claymore_dual Remote manager не работает

### ISSUE THREAD

**Issue by DoS174** [nicehash/NiceHashMiner#316]
Не работает Remote manager на claymore_dual при работе через nicehash. 
Если запустить claymore_dual вручную, то Remote manager прекрасно работает. 
Пробовал в настройках nicecash добавлять параметр "-mport -3333" для запускаемого майнера, но это не помогло

**Comment by Sav87** [comment]
NHML занимает порт управления, поэтому и неработает.

**Comment by DoS174** [comment]
Смена порта не помогла. А может можно пользоваться для сборав данных тем же портом что и NHML?

**Comment by Sav87** [comment]
Попробуй в configs\MinerReservedPorts.json указать нужный порт.
[Reserving-API-bind-ports](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Reserving-API-bind-ports-(Advanced))

**Comment by DoS174** [comment]
Спасибо. Мониторинг заработал
