### ISSUE TITLE
Display driver stopped responding and has recovered

### ISSUE THREAD

**Issue by buyungsukarno** [nicehash/NiceHashMiner#316]
CPU : FX-4350
GPU :  HIS Radeon 7790
RAM : Kingston Hyperx Fury 1866
OS : Win 10 Enterprise 64bit
Driver : AMD Radeon 16.9.2
NiceHash Miner v1.7.3.2

Display driver stopped responding and has recovered when start mining equilhash. at v1.7.3.1 working fine.

Regards.

**Comment by babytechno** [comment]
I'm having the same issue over here with the AMD Radeon 6850.

Currently using the 15.7.1 drivers.

Tried using the 16.9.2 drivers as well, but neither worked. I haven reverted to 15.7.1

**Comment by leshiy-gr** [comment]
I have the same problem, I can not even run benchmarks, the driver stops working. Excuse me, how you can see what version of the driver? Where I can get 15.7.1?  It's now the most stable? In previous versions of the program - my system has worked consistently with those drivers that now.

**Comment by dadoremix** [comment]
i have also problem with nicehash 1.7.3.2 and 1.7.3.3 ..
ati drivers stop respondig
update to last version driver, the same problem
CPU xeon E5440 and GPU ati 7850

**Comment by dadoremix** [comment]
problem is in GPU
Hash tables will use 1744.8 MB
config is not good in miner version 0.4

**Comment by S74nk0** [comment]
@dadoremix `Hash tables will use 1744.8 MB` This is correct. Closing issue as it is related to an older NHM version.
