### ISSUE TITLE
Cryptonight mining extremely slowly! 1.8.1.2

### ISSUE THREAD

**Issue by samjviana** [nicehash/NiceHashMiner#318]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [ ] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

**Comment by Nicheuji** [comment]
Try #226 . I'm getting better hash rates with that.

**Comment by samjviana** [comment]
#226 is for CPU, My issue is with an GTX 1050, it's not much ... but's something, I found that my GPU does 0.3kH/s +/-, but the miner gets only to 0.2kH/s at full load, and this still more profitable than Equihash, but the miner takes too long to found/accept an share and stays stopped and gets almost no one share, it's the most profitable algorithm but so the less profitable because takes too long to mine, so I turn it off, but maybe is an error ... I don't know
Sorry by English XD
