### ISSUE TITLE
NH LEGACY OPENCL MISSING

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner#32]
A pc with a nvidia card , cant mine 3rd party , opencl missing 

![image](https://user-images.githubusercontent.com/9946471/28188931-c429c062-681b-11e7-8456-79346d3454c2.png)

**Comment by billmcilhargey** [comment]
As workaround, copy the OpenCL.dll from C:\NHML-1.8.0.0\bin\ethminer to
C:\NHML-1.8.0.0\bin_3rdparty\claymore_dual

Since this is actually related to ClaymoreDual I am copying this over to their support forms

**Comment by billmcilhargey** [comment]
What OS are you using / running the latest nvidia drivers?
