### ISSUE TITLE
SOCKET ERROR - RECEIVE error: socket closed

### ISSUE THREAD

**Issue by mandeep148** [nicehash/NiceHashMiner#322]
hi,
im using Nicehash legacy 1.8.1.2 version, 
im doing CPU and GPU mining together, 
im not getting problem with GPU mining but CPU mining giving me this error every 5-10mins,

> [2017-09-16 11:48:34] : SOCKET ERROR - RECEIVE error: socket closed
> [2017-09-16 11:48:34] : Pool connection lost. Waiting 10 s before retry.
> [2017-09-16 11:48:43] : Connecting to pool cryptonight.in.nicehash.com:3355 ...
> [2017-09-16 11:48:44] : Connected. Logging in...
> [2017-09-16 11:48:44] : Difficulty changed. Now: 80000.

why this happening, what can i do to make it more stable..
thanks.

also wanted to know, its Cryptonight but which currency it is mining?

**Comment by streaml1ne555** [comment]
I had this problem last week and I just changed regions from US to EU and it was fine. Could be a network issue on your end, or the internet, or could be a temporary issue with Nice Hash's pool server like it was for me.

**Comment by utc99** [comment]
The issue was explained in https://github.com/nicehash/NiceHashMinerLegacy/issues/113

**Comment by DillonN** [comment]
Yes this is the same issue as #113
