### ISSUE TITLE
Claymors dual rejects

### ISSUE THREAD

**Issue by DmitryDMR** [nicehash/NiceHashMiner#324]
After update to NHML 1.8.1.3 a have 100% rejects for DCR with dual maining DaggerDecret, but not for another dual algos, for example DaggerLbry.

![dcr_reject](https://user-images.githubusercontent.com/30769434/30512869-3681a126-9b01-11e7-9a79-fbfbf9f0d59d.jpg)

**Comment by DmitryDMR** [comment]
check it again now. no more rejects. all founded shares accepted

**Comment by lmlim** [comment]
yes, i too noticed this several times a week. seems like, europe decred server is not very stable compare to usa. it has not been fixed permanently yet. it is still on going.

**Comment by Mystere** [comment]
Since it has nothing to do with NHML, I suggest closing your ticket.

**Comment by DillonN** [comment]
Yes this is a problem with either the CD software or servers, I'll close it now
