### ISSUE TITLE
UI Bug: Benchmark list colors reset to white after switching devices

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#325]
**Precondition:** there should be at least 2 devices available for mining

1) Open Benchmark window
2) Select a few algorithms for any device
3) Start Benchmark
4) Select another device in the 'Device' section, and then select back the previous one

**Result:** Colors (gree, blue, gray) reset to white
**Expected result:** Colors should stay in between switching devices

Here is an example:
- Benchmark is active on GPU:
![image](https://user-images.githubusercontent.com/4707112/30514041-17d37f1a-9b1f-11e7-9946-b178ae3c9045.png)
- Here is the look of list of algorithms after selecting CPU and then GPU
![image](https://user-images.githubusercontent.com/4707112/30514048-254de05e-9b1f-11e7-91c2-b23be2345bcb.png)

**Comment by DillonN** [comment]
Merge this with #21
