### ISSUE TITLE
UI Minor issue: Tooltip icon for Extra Launch Parameters is misplaced

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#326]
1) Open Settings
2) Go to 'Devices/Algorithms'

Result: Tooltip icon is shifted down a bit, so it covers the form below it
![image](https://user-images.githubusercontent.com/4707112/30514208-899178b2-9b21-11e7-99d1-4e8d25fe7917.png)

Imo, tooltip should be moved above for 2-3 px.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

We will be working on a complete GUI re-design.
