### ISSUE TITLE
not enough memory to put Dag into. with duel claymore only

### ISSUE THREAD

**Issue by althefirst** [nicehash/NiceHashMiner#327]
the pc. single 1070. with a fm2 amd cpu. 16bg memory
the check for disable amd is true. and i have the cpu unchecked.
when i tryided to revert back to 1812 the error is still there. it was not the there before i unziped the 1813. i have throwen away both folders and just installed the 1812. the problem still presant. have ran both 32 bit and 64 bitc++ runtime
[1812-log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1308593/1812-log.1.txt)
[1813-log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1308594/1813-log.txt)

**Comment by Crypto-Lord** [comment]
What's your virtual memory at?

**Comment by leonik3** [comment]
When first card launch EWB Equihash, then second and all next cards cant launch Dagger Claymour. I have such isuue: 
https://github.com/nicehash/NiceHashMinerLegacy/issues/308

**Comment by DillonN** [comment]
@althefirst could you post a screenshot of what ClaymoreDual looks like once it has opened, preferably showing as much of the text as possible? Also could you try running while having disable AMD detection unchecked (so that your CPU's graphics show up in the device list, but leave it unchecked)
