### ISSUE TITLE
If you see this warning often make sure you did not overclock it too much

### ISSUE THREAD

**Issue by thel3lue** [nicehash/NiceHashMiner#329]
when update to 1.8.1.3 mining few hours will get this error
mining with 1.8.1.1 is fine 
Does anyone run into the same problem?
![oc](https://user-images.githubusercontent.com/31726667/30573858-c6fa91a8-9d28-11e7-9119-40a805c39ce0.jpg)

**Comment by DillonN** [comment]
How often do you see the error? Dual mining puts a much greater stress on the system and can cause more rejects especially if any overclocking is involved.
