### ISSUE TITLE
NHML 1.8.0.0 hangs for 3+ minutes when initializing miners

### ISSUE THREAD

**Issue by italianoch** [nicehash/NiceHashMiner#33]
NHML seems to get stuck at "Querying CUDA devices" when the program starts for a good minute or so. I have the program set to auto mine at startup. The group/device rates pop up with zero values and the miner windows don't pop up until 3+ minutes after. It's also way more prone to crashes and freezes as well. This is regardless of a clean initialization (starting with a completely new config). Interestingly, the issues are gone if I start a 2nd instance of NHML. The program starts up fine and starts mining immediately. I had this issue on 1.7.6.4 as well ,and tried running the program as admin, benchmarking all algos again, disabling P0 state, etc. 1.7.6.3 works completely fine so that is what I am mainly using currently while I troubleshoot NHML.
Below is the log file for NHML
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1147165/log.txt)
Below is log file for 1.7.6.3. They are configured identically as far as I can tell.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1147166/log.txt)

**Comment by DillonN** [comment]
From what I can see ClaymoreDual is crashing on your 970. Do you have "Optimize compute performance" turned on for that in the NVIDIA Control Panel?

**Comment by italianoch** [comment]
I do. If Optimize compute performance is not selected, the hashrate for both my 970 and 1060 drops (970 is the worst at 4-5M). Checking the Force P0 state box in the settings did not change that either. 
NHML works okay once it goes through the hang-ups, but it's just odd why it takes like 5 minutes for the miners to actually start running from when I hit the start button. In your old fork, everything was super smooth, program initialized in around 6 seconds, and as soon as I hit start, within 5 seconds all miner windows are open and running.

**Comment by DillonN** [comment]
The problem with Optimize Compute performance is that it can straight up deny programs from accessing CUDA devices (which would cause hangs when launching NHML during detection, and crashes in miners that can't access hardware). It does help significantly with ethereum hashrates but the best option is to leave it disabled globally and add program-specific profiles for the ethereum miner .exe's (like ClaymoreDual). That way NHML won't have issues detecting the GPUs, and the drivers will know to lock it down once the miner has started up (NHML only accesses this on startup during detection). 

Strange that you would see benefit on your 1060, as the option is only supposed to affect Maxwell 2 GPUs (900 series)

**Comment by italianoch** [comment]
I tried starting the mining with the Nvidia cards disabled and it works like a charm. But I can't figure out why they are causing the miners to hang when NHML starts up, and when I hit start after the program is up. I've tried disabling optimize compute performance outright, only enabling for NHML, and enabling globally. Also, only enabling optimize compute performance for NHML does not improve the 970's hashrate at all, it seems enabling it globally is the only way to get it above 4-5M.

**Comment by italianoch** [comment]
For now, NHML does work for me. Just have to wait for the 3-4 minute hang for the miners to initialize so it's not a pressing issue.

**Comment by DillonN** [comment]
@italianoch since the NHML exe does not do any actual mining you shouldn't have optimize compute enabled for it. You should enable it for the miner exe files, e.g. for Claymore dual enable it for `\bin_3rdparty\claymore_dual\EthDcrMiner64.exe`. If you find having it enabled for NHML helps with your detection speed then keep it on there, but it won't help mining at all.
