### ISSUE TITLE
Hashrate reported incorrectly in Nicehash client

### ISSUE THREAD

**Issue by Kidsnd274** [nicehash/NiceHashMiner#330]
Having a weird bug where the hashrate is not being reported correctly on the Nicehash Miner (see screenshot below)
![capture](https://user-images.githubusercontent.com/1343896/30587744-d4f11546-9d66-11e7-8a3b-469877dde35d.JPG)

The mining software reports a different hashrate but the Nicehash client just sticks to 201.300 H/s.
Running

Here is my log
[log_modified.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1313867/log_modified.txt)

**Comment by DillonN** [comment]
Some miner programs do not have a standard API interface NHML can use to get speed data, so the benchmark speed is displayed (and the "**" warns you this is the case). I will make the documentation more clear on this in the future
