### ISSUE TITLE
Майнер перезагружается 

### ISSUE THREAD

**Issue by Alex300030** [nicehash/NiceHashMiner#331]
Nicehash miner legacy 1.8.1.2.....стал замечать что постоянного
 майнинга нету....помайнит минут 7-15  и поновой перезагружает
 майнер...а бывает и компьютер перезагружает....немогу понять в чем
 дело......на другой ферме все хорошо уже вот 36 часов без остановок
 работает а тут непонятно и часа не проработает как в темный экран или
 перезагрузку..
ОС Windows 10 x64 Материнская плата ASUS B150 Pro Gaming Aura
  ......Блок питания DEXP 600 W ....Видеокарта 2 шт FXF Rx 470 4 Gb
  и Asus Rx 470 8 Gb   Сегодня утром выскочила надписть в Биосе (power supply surges detected during the previous power on asus anti-surge was triggered to protect system from unstable power supply unit)  Данную функцию отключил ....вот еще не знаю что будет дальше.....Подскажите в чем может быть дело ....

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [ ] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

**Comment by ZuluDrag** [comment]
Alex300030: Проблемма в блоке питания, что тебе и Биос говорит. 600Вт маловато для 3 470 и системы. Тем более, если блок питания не имеет голд сертификата. Проблема не в софте.
You have problem with your power supply - BIOS is messaging about that too. 600W is too low for 3x 470 + m/b, specially  if power supply is not gold certified. Problem is not in software.

**Comment by Alex300030** [comment]
Всего стоят в системе Видеокарты  XFX -  1 шт  и Asus - 1 шт

**Comment by ZuluDrag** [comment]
Но Биос говорит о нестабильном блоке питания - надо пробовать его менять или проверять. Вероятно на полной нагрузке проседает питание +12В и срабатывает зашита. Проверь хотябы тестером сколько вольт на +12 линии при нагрузке...ну или замени блок питания, если есть возможность.

**Comment by Alex300030** [comment]
Я щас поставил на одной карте майнить...и честно говоря удивился что уже прошло больше часа  и майнинг стабильно работает...так что точно все дело в Блоке питания......
