### ISSUE TITLE
dagger hashimoto starts at 14MHish mh/s drop to 10MH/s sometimes 8

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#332]
bit annoying that ive noticed my gtx 770 starts mining at 14 or so MH/s but after about 10 minutes it says something about extranonce then then drops its hashrate considerably.

can anyone shed some light on this please

thanks in advance
jim

**Comment by DillonN** [comment]
@jimmyhackers which version of NHML are you using? If you are on 1.8.1.3 could you try 1.8.1.2 and see if that changes anything?

**Comment by jimmyhackers** [comment]
tis a moot point now.... cryptonight on my 770 is more profitable now :(

oh woe is life
