### ISSUE TITLE
Проблема с автозапуском майнинга

### ISSUE THREAD

**Issue by ALTERNATIVAArtem** [nicehash/NiceHashMiner#333]
У меня ПК (Windows 8.1) включается автоматически если отключился (например свет пропадал), но при автозагрузке Nicehash Legacy выскакивает табличка что интернета нет (те программа загружается раньше чем появляется сеть) и в итоге майнинг не начинается автоматом, нужно вручную. Кто знает как исправить? Раньше все работало нормально.

**Comment by KOTEHKA** [comment]
Вышла новая версия майнера 1.8.1.3 вот только загвоздка она нестабильно работает с видекартой в плане майнинга процессор все норм на криптоните. Установите ошибка исчезнет.
