### ISSUE TITLE
Always getting 'Unable to get NiceHash profitablilty data...' on every machine on version 1.8.1.2

### ISSUE THREAD

**Issue by ajmeier29** [nicehash/NiceHashMiner#335]
This problem has been seen for multiple versions. Ironically I always have to update to the latest version to relieve the issue. This issue was supposed to be resolved and obviously isnt'. Right now I have had to update to 1.8.1.3 to fix the issue. Why does this continue to happen? And yes I have already done the IPV6 fix on every machine.

**Comment by VParhom** [comment]
A similar problem.
It seems that we are to switch to the new version in a mandatory manner.
![1-8-1-3-pre](https://user-images.githubusercontent.com/31612825/30712117-90ee90a4-9f13-11e7-90da-e0a716c5bb89.jpg)

**Comment by Pruxa-sun** [comment]
Getting same error on NHM Legacy 1.8.1.3.

**Comment by trackroute** [comment]
Since I switched to NicehashMiner Legacy a couple of months ago I've honestly lost **weeks** of mining time due to machines sitting around idle with this error (all the versions of Legacy have been plagued with this issue). I'm not sure what the underlying problem is (it isn't my fibre internet connection), but I'm about ready to ditch NicehashMiner Legacy completely because of this problem.

**Comment by VParhom** [comment]
this problem appears on the second-third day after the release of a new version of NHML with the active "autostart mining"

**Comment by VParhom** [comment]
interestingly, the author will finally pay attention to our remarks and will understand that this should not be done?

**Comment by mendogas** [comment]
I have the same problem.

I am on vacation, now I need to go back 200km to my mining rig to try to fix it.
If I will not revolve this problem fast I will throw away nicehash miner...

**Comment by ajmeier29** [comment]
I agree with what @VParhom has said, it seems to happen soon after a new release. I'm fine with mentioning to upgrade, but this is ridiculous. There isn't much error detection in NH, and all the developer has to do is implement an option in the settings to not show this error message. Its gotten to the point where I had to use a raspberry pi that can reach out to the NH api and detect if a machine has gone offline, I then have it rigged to a relay that is attached to each rig's mobo and sends a reset command when one has detected its offline. 

Also, I haven't done it yet, but if I get this error message again I will create an autoit script to bypass this error message completely. For me, NH starts with the machine and starts mining, this error message would block a machine from mining until I logged in to click ok, just like the rest of you, this is NOT acceptable.

**Comment by mendogas** [comment]
ok, I have Installed newest version and now it looks all is good. 
bet because of this shit miner was not working for 2 days and I had to spend a half of the day to reach my miner rig. it sux...

After another such issue I will abandon nicehash

**Comment by ajmeier29** [comment]
why did it take so long to "reach" youre miner rig? what do you mean? Do you not have it setup so you get emails if a miner goes offline?

**Comment by 619Srt** [comment]
you can do such things? I didn't know that.
