### ISSUE TITLE
NHML-1.8.1.3 virus?

### ISSUE THREAD

**Issue by buddon** [nicehash/NiceHashMiner#336]
Hello! On the last update of the NHML-1.8.1.3 miner, an antivirus scolds! So it should be?Until today, this was not.

**Comment by pavelhr** [comment]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Tilken.B!cl

**Comment by DillonN** [comment]
Miner programs can be included in viruses to mine on victims' computers unknowingly. NHML includes many miner programs and so it itself can get flagged 

https://github.com/nicehash/NiceHashMinerLegacy#-troubleshooting there is a post in here about it

**Comment by pavelhr** [comment]
It flagged the NiceHashMinerLegacy.exe file itself.
![nhm](https://user-images.githubusercontent.com/24472264/30679538-8fbf96e8-9e9a-11e7-8512-0a92c29ca7c7.PNG)
