### ISSUE TITLE
NH Tools

### ISSUE THREAD

**Issue by bonifacio123** [nicehash/NiceHashMiner#337]
This isn't a problem report but didn't know where else to post this. I wrote some tools in PHP and wanted to share:

**nh_benchmarks.php**: Exports the calculated algo speeds to a csv file
**nh_profit.php:** HTML representation of algo profits using highcharts lib

[https://github.com/bonifacio123/nh_tools](https://github.com/bonifacio123/nh_tools)

**Comment by drkskwlkr** [comment]
Please edit your post and [fix your link](https://github.com/bonifacio123/nh_tools). Also, a brief description of how to use your tools and what to expect from them would be helpful.

**Comment by bonifacio123** [comment]
Link fixed and README.md has been updated on GitHub. Thanks!

**Comment by DillonN** [comment]
Thank you @bonifacio123, I have made a short wiki page with a link to your repository https://github.com/nicehash/NiceHashMinerLegacy/wiki/Exporting-Benchmark-Data
