### ISSUE TITLE
zip file infected with trojan:/Win32/Tilken.B!cl

### ISSUE THREAD

**Issue by sandstalker619** [nicehash/NiceHashMiner#338]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [x] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

**Comment by sandstalker619** [comment]
please respond

**Comment by DillonN** [comment]
Miner programs can be included in viruses to mine on victims' computers unknowingly. NHML includes many miner programs and so it itself can get flagged 

https://github.com/nicehash/NiceHashMinerLegacy#-troubleshooting there is a post in here about it
