### ISSUE TITLE
Mining at 0 mh/s since 1.8.1.3

### ISSUE THREAD

**Issue by FrankMycHo** [nicehash/NiceHashMiner#339]
Hi,

Since the pre-1.8.1.3 and in the official version as well, my rig is mining at 0 mh/s on all GPU (AMD and Nvidia).  My CPU is mining fine.

- I am still mining without issue on 1.8.1.2
- I uninstalled Nicehash and GPU drivers with DDU then re-install without improvements
- Nicehash app is crashing if I try to stop the miner or to kill the apps by clicking on the X (top rioght corner)
I am attaching a log file, let me know if I can help with more info.
Thanks
Frank
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1319882/log.txt)

**Comment by DillonN** [comment]
Hello @FrankMycHo, could you post a screenshot of the ClaymoreDual mining window? (try to fit as much text in as you can)

It looks like NHML is not able to connect to the ClaymoreDual instance. Have you tried leaving it for a longer time and seeing if anything useful shows up in the ClaymoreDual window? (after a couple minutes NHML will automatically restart the miner)

Also could you try running CD manually to see if the error still persists. You can do that by opening a command prompt in the `\bin_3rdparty\claymore_dual\` folder and entering `EthDcrMiner64.exe -di 2310  -epool stratum+tcp://daggerhashimoto.usa.nicehash.com:3353 -ewal 3Q5jYQSSiCAJGUcn5ZSTxVj1dgUM5nrrMp.worker1 -mport 127.0.0.1:4002 -esm 3 -epsw x -allpools 1 -dcoin lbc -dpool stratum+tcp://lbry.usa.nicehash.com:3356 -dwal 3Q5jYQSSiCAJGUcn5ZSTxVj1dgUM5nrrMp.worker1 -dpsw x -dbg -1`

**Comment by revaido** [comment]
I don't know if it's related but one of my rigs was stalled overnight and showed errors connecting and it turned out to be Windows Defender started to detect the 1.8.1.3 NiceHashLegacyMiner.exe as Trojan:Win32/Tilken.B!cl

i've just added an exclusion to the entire folder but had to copy the binary from the downloaded zip file again. 

I restarted my other rig and that showed the same problem so I guess todays Windows Defender updates are going to cause a lot of problems for people using that.

**Comment by FrankMycHo** [comment]
Hi, Here are my answers:

- Have you tried leaving it for a longer time and seeing if anything useful shows up in the ClaymoreDual window? 
--> Yes I did, NHML is restarting the miner but it still mine at 0 mh/s.

- Could you try running CD manually to see if the error still persists 
--> Will do tonight

- Windows Defender started to detect the 1.8.1.3 NiceHashLegacyMiner.exe as Trojan:Win32/Tilken.B!cl 
--> I am using Avast,  my whole folder where NHML is installed is in the exclusion list of Avast.

I will run the other tests tonight, I need to leave to work now.  Thanks for your support :)

**Comment by BogdanCarter** [comment]
Here is some extra info related to my issue. I run 1xXeon E5-2609 v2 2.5, 1xNvidia Quadro K2000, 2xAMD FirePro V7900. When I mine on 1.8.1.2 using all the devices, everything is ok. If I try to do the same on 1.8.1.3 my 2 FirePro hash at 0 (best I get 17 per card) as soon as xmr-stak-cpu 1.3.0-1.5.0 mining kicks in. As soon as you close xmr-stak-cpu 1.3.0-1.5.0 or disable mining with CPU, then FirePro V7900 hash at 200-250.

**Comment by BogdanCarter** [comment]
replacing xmr-stak-cpu with xmr-stak-cpu from 1.8.1.2, fix the issue.

...but something is still not feel right..GUI of nicehash is freezing...but miners still work.

**Comment by ZuluDrag** [comment]
BogdanCarter: Looks like new version of cpu miner takes too much resources - so no cpu resources are left for preparing jobs for GPUs in time. Just replace xmr-stak-cpu with older version or try adding parameters to mine not on all cpu cores...

**Comment by JCarangoH** [comment]
@ZuluDrag @BogdanCarter for me just have to set LessThreads from 0 to 1 and work normally again. i have a fx-6300, a R9 270x and a Rx 470 with modded bios

**Comment by FrankMycHo** [comment]
Ok, that was it.

As soon as I disable my CPU, all 5 GPUs are mining as usual.
I have an I5-4690K, what would be the extra launch parameter to use to disable some cores ?

**Comment by JCarangoH** [comment]
@FrankMycHo In Settings > Device/Algorithm, select your cpu and select the Algorithm, you will se a field named "LessThreads" which means No. of threads to disable in your cpu while mining, by default is set to 0, just try setting it to 1 and save, an then try if minning works better then

**Comment by FrankMycHo** [comment]
Thank You Guys,

Mining on 3 cores instead of 4 solves the issue without affecting Hash Rate and I can still use my CPU.
Not that the CPU is playing a huge role but still, it helps a little bit
