### ISSUE TITLE
Feature Request: Decouple GPUs when hashing same algorithm

### ISSUE THREAD

**Issue by fefsf** [nicehash/NiceHashMiner#34]
Would it be possible to enable a setting where it will always display the current hashrate/USD per day for each GPU even if they are hashing the same algorithm? On some of my mixed GPUs system, it would be nice to know what each individual card is doing even when they are all hashing the same algorithm. This could be helpful is quickly determining if there is a problem with a particular cards overclock for example. Thank you

**Comment by DillonN** [comment]
Hello @fefsf, unfortunately not every miner reports individual cards' hashrates so this may require running two separate instances of miners. At the moment there are a number of functionality features in the works that take priority over interface changes but this is something I can look in to down the road

**Comment by fefsf** [comment]
OK thank you
