### ISSUE TITLE
1.8.1.3 CPU and GPU low speed mining

### ISSUE THREAD

**Issue by zusernp** [nicehash/NiceHashMiner#342]
При одновременном майнинге на CPU и GPU в 1.8.1.3 скорость майнинга на GPU (алгоритм equihash) раза в два медленее чем в 1.8.1.2. По очереди запускаю разные версии в 1.8.1.2 всё нормально, в 1.8.1.3 скорость ниже. Если в 1.8.1.3 запускать майнинг только на GPU то скорость нормальная

With simultaneous mining on the CPU and GPU in 1.8.1.3, the speed of mining on the GPU (algorithm equihash) is two times slower than in 1.8.1.2. In turn I start different versions in 1.8.1.2 everything is normal, in 1.8.1.3 the speed is lower. If in 1.8.1.3 run only on the GPU, then the speed is normal

![1](https://user-images.githubusercontent.com/32170889/30706642-b2121c18-9f01-11e7-9e69-41d64c2367af.PNG)
![2](https://user-images.githubusercontent.com/32170889/30706643-b22522d6-9f01-11e7-895b-ce745a26bd27.PNG)

**Comment by JCarangoH** [comment]
@zusernp Maybe you want to try with set LessThreads to 1, for some reason my rig got the same issue with 1.8.1.3, i have a fx 6300 and with LessThreads in 0 hashspeeds for the cards got affected, after set LessThreads to 1 the hashspeeds went to normal

**Comment by zusernp** [comment]
@JCarangoH  If I set LessThreads to 1, the GPU is normal, but the CPU is worse. On 1.8.1.2 LessThreads = 0, while both GPU and CPU run at full speed

**Comment by lmlim** [comment]
i am not sure that this will help, but i always set cpu priority to "idle" for cpu miner.

**Comment by DillonN** [comment]
@zusernp it seems as though the new CPU miner version is using too much CPU and causing the GPU miner to run slow. You could try @lmlim's suggestion of setting the priority to idle, which will tell Windows to let the GPU miner use the CPU before the CPU miner hogs it all

I am looking into an alternative CPU miner program

**Comment by zusernp** [comment]
@lmlim @DillonN In "idle" mode it works fine, but I need it to work not only in idle mode:( Have to use 1.8.1.2

**Comment by Nicheuji** [comment]
@zusernp Have you tried XMRig?
