### ISSUE TITLE
Continuous connection errors/still not resolved

### ISSUE THREAD

**Issue by bladessss** [nicehash/NiceHashMiner#343]
From a several weeks (4-5) I have a problem with a constantly breaking connection with the server. Nicehash works good for a moment while then breaks off the connection and does not work for several hours. I'm trying to change the connection between all the servers but nothing gives. All other applications work fine (including for example MinerGate), I have a problem with only nicehash. Help:/
![cpu](https://user-images.githubusercontent.com/32190973/30734629-4c9f84d0-9f7c-11e7-85e5-91fb71e86b66.JPG)
![cpu3](https://user-images.githubusercontent.com/32190973/30734625-4c96244e-9f7c-11e7-83f4-f78a65d62c81.JPG)
![gpu](https://user-images.githubusercontent.com/32190973/30734626-4c96852e-9f7c-11e7-9748-6aed17c0e5ec.JPG)
![gpu1](https://user-images.githubusercontent.com/32190973/30734630-4ca30f42-9f7c-11e7-968d-faa5ed192970.JPG)
![gpu2](https://user-images.githubusercontent.com/32190973/30734627-4c983de2-9f7c-11e7-8966-275385bc6d89.JPG)
![gpu4](https://user-images.githubusercontent.com/32190973/30734628-4c980bba-9f7c-11e7-94f0-6a7f2e74a183.JPG)
![nh2](https://user-images.githubusercontent.com/32190973/30734631-4caaa0b8-9f7c-11e7-9d57-5648f7945b9c.JPG)
![nh3](https://user-images.githubusercontent.com/32190973/30734632-4cab351e-9f7c-11e7-8d93-bd6dad2f3608.JPG)
![nicehash](https://user-images.githubusercontent.com/32190973/30734633-4cae9eca-9f7c-11e7-9138-57fd46df3371.JPG)

**Comment by gleissonferreira** [comment]
estou com o mesmo problema !!

**Comment by DillonN** [comment]
@bladessss could you try disabling the Firewall to see if it is blocking connections to NH servers? If you are able to, could you also try changing your IP?

**Comment by bladessss** [comment]
I'm tried disable firewall and shutdown anti-virus - does not help. I can not change my IP number, it's a corporate network. I have no ideas anymore:/

**Comment by FBR4ik** [comment]
Hello. I can't establish NiceHash Miner Legacy - AMD, the antivirus is blocking Win332:Dropper-gen [Drp]. 
What me to do? Desible?

**Comment by DillonN** [comment]
@FBR4ik NHML downloads miner programs which causes it to flag, since most miner files are flagged already (many real viruses put miner programs on computers unknowingly, using up their resources)

@bladessss if you are not getting a connection in any of the miner programs it is probably a problem with your network contacting NH servers. Maybe another firewall down the line or something. Are you able to connect if you attempt to run a miner program manually?

**Comment by bladessss** [comment]
All other programs work properly... I have problem only with NiceHash. If I started for example claymore manually he works properly too. The problem is server-side NiceHash I think

**Comment by bladessss** [comment]
Can anyone help me? I can not dig up the required 0.001BTC to pay out because I have constant connection problems. I have the same problem on my computer at home and at work, ie in two different places on two quite different internet connections. Nicehush is bugged, fix this!! I'm pissed off because I'm still losing money. Lern from Minergate - I never had any problems with them on any computer!!
