### ISSUE TITLE
NHM 1.8.3 GPU mining output

### ISSUE THREAD

**Issue by doverosx** [nicehash/NiceHashMiner#345]
Hello,

NHM 1.8.3 has reduced the output from my RX580 4GB video card. When I return home, from work, I will continue using NHM1.8.2.

The issue is that you can see the client reporting high hash rate output, then the hash rate drops to a very low number and then finally to 0. If you continue watching, you'll see the output slowly return but the cyclic behaviour continues.

Looks like this:
21 -> 24 -> 17 -> 4 -> 0 -> 5 -> 17 -> 21....etc

Hardware Setup:
AMD Ryzen3 1300X@3.8GHz
Sapphire RX580 Nitro+ 4GB@1410 GPU/1950 RAM (200 over stock)

Thank you,
Brodey Dover

**Comment by DillonN** [comment]
Thanks for reporting @doverosx. I am trying to figure if this is an issue with the new ClaymoreDual version. Are you able to try copying over the old `bin_3rdparty\claymore_dual` folder over the 1.8.1.3 install and see if that changes anything? If you don't have any NVIDIA cards then the old version will work fine under 1.8.1.3

**Comment by doverosx** [comment]
Hi Dillon,

I can check this out for you when I get home from work today.

Thank you,
Brodey Dover

**Comment by doverosx** [comment]
@DillonN Unfortunately, the behaviour continued after copying over the claymore_dual miner.

**Comment by DillonN** [comment]
@doverosx thanks for checking. Are you by chance using CPU mining as well, and if so try it with that disabled? The new CPU miner uses more cycles which may not leave enough for Claymore (if this is the cause you can increase the less threads option in settings)

**Comment by doverosx** [comment]
Ahhhh, I think you're on to something.

I'll give it a shot.

**Comment by doverosx** [comment]
@DillonN The behaviour continues with 1.8.1.4 Pre 2 and with Less Threads = 1.
