### ISSUE TITLE
NML 1.8.1.3 Not Responding if Start Mining

### ISSUE THREAD

**Issue by suwecagunadi** [nicehash/NiceHashMiner#347]
always not responding if start mining and the cmd EthDcrMiner64.exe (3rdParty) is always close less than 2min. its make me confuse the previous version is work good
i think is not ready to use 
i'm using windows 10 pro 64bit 
GPU RX470 2x Core i7 3xxx Ram 10GB DDR3 
thx

**Comment by honzavalusek** [comment]
Have same issue (GTX 1070).

**Comment by gasitup** [comment]
I have tried several different versions today and the all give me trouble I am running 6 GTX 1070's on windows 10 going back to v1.7.5.13 have to re-benchmark each one wast of time

**Comment by DillonN** [comment]
As I understand you are seeing the NiceHash Miner Legacy window not respond as soon as you start mining? Are you mining with CPU, and if so, could you try and mine with CPU unchecked to see if that changes anything?

**Comment by gasitup** [comment]
for me personally it was giving me errors cuba not found or wrong pointing to something and was dropping my 6th card would just stop mining

I updated my Nvidia drivers today to the driver released 4 days ago now it seems to work 

All Versions 2.0.??? do the same thing to me they will work for a bit then it will say I am out of memory and stop working 

sucks cause 2.0.1.1 was paying more

**Comment by sriminer** [comment]
Hello DillonN,

Thanks for the nice miner.

Just want to let you know I am also facing same issue that the main nicehash miner 1.8.1.3 window goes to not responding after few hours of mining while the command windows continues to mine, I am not sure if I am loosing my sold hashes to nicehash in this way. When I try to close main window the command windows stays there and continues to mine.

I will try to mine with cpu unchecked for a day and see if this resolves as per your suggestion

**Comment by DillonN** [comment]
@sriminer as long as the miner windows are still open and running you will be getting paid for the hashes

**Comment by suwecagunadi** [comment]
Thx for suggestion i can mining now 
thx you so much

**Comment by sriminer** [comment]
@DillonN: removing cpu mining seems to have fixed the not responding issue so far. This was not there on earlier versions. Anyway thanks for the help.

**Comment by DillonN** [comment]
@sriminer you have a slightly different but similar issue to what many others are getting, that's a result of the CPU miner bin not being updated when you updated to 1.8.1.3. You can verify if you have this, after starting mining check the window for the CPU miner and it should say `xmr-stak-cpu 1.3.0-1.5.0 mining software`. If it does not then you have the old CPU miner version which isn't compatible with 1.8.1.3

This would happen e.g. if you updated to NHML by copying over the files from the .zip into the old directory, then NHML would not know if the CPU miner bin was updated or not. Recommended way of updating is to extract the .zip to a new folder and only copy over the old `configs` folder, that way the bins are always updated

If you do have the updated version then something else is going wrong, you can open a new issue and post logs that cover the incident and I'll try to help more

**Comment by sriminer** [comment]
Hi DillonN

Thanks, I just verified the version and it is 1.3.0-1.5.0. I have enabled cpu mining again and I will wait until it goes to not responding and I will revert back to you with a new thread.

Meanwhile let me know if I have to do something to enable logs?

Regards

**Comment by DillonN** [comment]
@sriminer thanks, no logs are enabled by default. The main log file is `log.txt` in the `logs` folder
