### ISSUE TITLE
Thai Language Menu 95% Translat work for Nicehash miner 1.8x

### ISSUE THREAD

**Issue by torppc** [nicehash/NiceHashMiner#348]
Thai Language Menu 95% Translat work for Nicehash miner 1.8x

PLS. put it in next version for Thai people.

Thank you.

Link fo download : https://drive.google.com/open?id=0B9uG1PXvvQZhTG9VSGdXc2UzWHM

**Comment by DillonN** [comment]
Thanks for the work @torppc, I will look it over and hopefully have it in the next version

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
