### ISSUE TITLE
Awesome Miner Monitor

### ISSUE THREAD

**Issue by RodAus** [nicehash/NiceHashMiner#349]
I'm trying to include my rigs that are using NHML in the Awesome Miner Monitor application. So I can monitor my rigs in real time. Something that using the webpage is not possible.

When I try to include the ip of the machine that is mining using NHML, the Awesome Miner application can not identify the API and port. I have tried to do this manually without success.

I have rigs with Ethos installed and I can easily include miners in Awesome Miner. Also mining only with the miner e.g. Clamore's inclusion is simple without problems.

I got in touch with the Awesome Miner devs, they told me that NHML should allow access to the API and port individually for each miner.

Awesome Miner Monitor is free and easy to include external miners, please do the test.

Please consider this a great and simple solution for large-scale mining.

PS: In fact it is time to have a linux client. So it will be possible to install more GPUs per rig and more stability. You can enter into an agreement with Ethos and offer this service.

**Comment by Sav87** [comment]
HHML dynamically specifies the ports of the API. Solution [Reserving API bind ports](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Reserving-API-bind-ports-(Advanced)). But there may be other problems

**Comment by RodAus** [comment]
@Sav87 Thanks, didn't worked. 
![capture](https://user-images.githubusercontent.com/31544552/30779692-888461ae-a13a-11e7-94d7-b44b2a570267.JPG)

**Comment by drkskwlkr** [comment]
@RodAus 
NHML binds miners to localhost (127.0.0.1) only and I think it does not allow you to override this behavior (but I will gladly accept to be wrong on this). That is why Awesome Miner can't establish a link.

You could try to get around that by using a simple proxy like [CCProxy](http://www.youngzsoft.net/ccproxy/) on your 192.168.1.13 and set it up to forward traffic on the desired port range between that interface and the localhost. If that works, you can replicate it to other rigs.

**Comment by DillonN** [comment]
@drkskwlkr is correct, NHML binds APIs to localhost for security reasons. This is hardcoded in so you would have to compile your own version to change it (e.g. [ClaymoreDual](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/Miners/ClaymoreDual.cs#L90) startup command). 

If there is a demand for an advanced option that allows external connections, it is something I can look into.

**Comment by RodAus** [comment]
The times of large-scale mining of only a single coin, will end very soon. I believe in a few months.

It is humanly impossible to manage more than 5 rigs half dozen of more profitable algorithms and 2 to 3 different miners. The combination of these factors will define what is the most profitable for that particular GPU. (take it all and multiply by 2, AMD and NVIDIA)

I see large-scale miners coming to the point of saying they do not know what they will do after ETH is no longer the top one.

Not all miners are holders. Mining tons of MH/s for an algorithm that you THINK will go up in price, for me this is ridiculous, you are relying on that? In mother Nature? What about the 3 million megawatts you spend per minute who is paying your father ?

So, the demand exists, but there is no solution in the market now. Have a Linux-based application that correctly fits with Multi-Algorithm AUTO switching with voltage/undervolt control. It will be revolutionary

The explanation to work with Linux Nicehash on the website is out of date and does not work, and is not AUTO switching .

Ethos is getting close but I think they do not know about this large-scale demand, I think nobody stopped to think of something so obvious. At several points they are not making progress, double mining, auto switching are two that they have already given up.

That's it guys, I'm not a developer. I can only contribute with the difficulties and tests. In these times of algorithmic changes nothing is certain. 

Install NS on dozens of machines okay, but manage them individually is almost impossible, A solution that I can manage and see all together like Awesome Miner allows me, in real time, will helps a lot at least some kind of monitoring.

Thanks
