### ISSUE TITLE
Getting huge amount of rejected shares on EWBF

### ISSUE THREAD

**Issue by p1r473** [nicehash/NiceHashMiner#35]
Hi, I am getting huge amount of rejected shares on EWBF on one of my machines
Lbry and Lyra2 seem to be fine, but Equihash EWBF has this issue.

What can I do?

![image](https://user-images.githubusercontent.com/9235633/28196517-2f91bf5a-681f-11e7-841d-91c5478fff1e.png)

Sadly, the machine this is happened on is on wifi (no ethernet available) but no other algorithm has the issues. Is it an internet speed issue? 

What is happening is I am noticing EWBF is hanging, so I press enter/return a bunch of times, then a wall of red rejections with 20k+ ms latency appears. But only on EWBF algorithm. And only today (was fine for last 2 days)
I have tried both San Jose and Amsterdam pool. Same issue

**Comment by DillonN** [comment]
When EWBF starts to hang, did you click on the miner CMD window? Clicking on the window can cause the running program to pause until you next hit enter. It sounds like EWBF hanging/pausing is causing the rejected shares, since they are stale by the time EWBF is able to submit them

**Comment by p1r473** [comment]
So you think the issue will go away if I just don't click the window? I have definitely had the window in the foreground. I will try to not click the window and see what happens.

**Comment by DillonN** [comment]
Yes if you click in the window you may notice that it stops and a white cursor shows up where you clicked. This pauses EWBF
