### ISSUE TITLE
API upgrade request + algorithm switcher new procedure proposition

### ISSUE THREAD

**Issue by rapra** [nicehash/NiceHashMiner#350]
Hello!
I am creating a tool to view online profitabilities from whattomine.com, NH and other pools. To get full of data I need to ask NH API a few times. After analyzing API methods I suppose, that some methods which are not used for a long time, were not developed as used methods. 
And my request: as simplemultialgo.info provides much more data that multialgo.info I suppose that multialgo.info is forgotten methos for now. My request to make that method great for making best for profitability comparator I would like to add:
- "paying" from simplemultialgo.info (= "price" from stats.global.current)
- "paying24h" from simplemultialgo.info (= "price" from stats.global.24h)

That change will make multialgoinfo less simple than simplemultialgo again, and will give more usable data.

Also I have an idea how to make autoswitch more user friendly.
For now nicehash is checking most profitable algo on timer with settable time. After it find more profitable algo, it switch immediately. It often do switch-attack from less stable algorithms. My proposition is, after adding those variables to multialgo.info, make weighted profitability for the switcher:
```
var profitWeightMax = 10;
var profitWeight = 0 ... 10;
weightedPofit = ( paying * (profitWeightMax - profitWeight) + paying24h * profitWeight ) / profitWeightMax ;
```
That method will provide fluid aggresiveness of switcher, from most aggresive and most profitable with profitWeight = 0 (current setting), for most stable and less profitable with profitWeight = profitWeightMax (= based on last 24h profitability "paying24h").

Thank you
Radek

**Comment by rapra** [comment]
I added a trackbar in my tool to visualize that weighted switcher proposal
- current situation, most profitable, shortest single-algo mining sessions
<img src="http://www.wak.net.pl/PROKREATOR/minecontrol-nh-current.PNG" />

- weight = 3/10
<img src="http://www.wak.net.pl/PROKREATOR/minecontrol-nh-3.PNG" />

- weight = 6/10
<img src="http://www.wak.net.pl/PROKREATOR/minecontrol-nh-6.PNG" />

- weight = 9/10 - most stable mining, longest single-algo sessions
<img src="http://www.wak.net.pl/PROKREATOR/minecontrol-nh-9.PNG" />

**Comment by DillonN** [comment]
@rapra, thanks for your suggestions. In 1.8.1.2 there was a profit normalization feature added that uses a short sample in an attempt to avoid the switching attacks you mentioned. It does not currently use 24h data but that is certainly something I'll look in to. You can see more details [on the Wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Profit-Normalization), and code in [NiceHashSMA.cs](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/Utils/NiceHashSMA.cs)

As for your API suggestion, it would be better directed toward the NiceHash service, this forum is for NiceHash Miner Legacy development only. As of 1.8.1.0 NHML does not use the HTTP API to get profit data

**Comment by rapra** [comment]
Thanks for a look, would you like to redirect this to the proper place @DillonN?
