### ISSUE TITLE
NicehashMiner 1.8.1.3 not starting automatically 

### ISSUE THREAD

**Issue by arc3521** [nicehash/NiceHashMiner#353]
Not starting with windows log in.. Even with "Run with windows" checked. It was fine with the previous versions.

**Comment by DillonN** [comment]
Hello @arc3521, can you check if NHML is listed as an entry in the startup items? On newer Windows versions you can check this by opening Task Manager and going to the Start-up tab

If so, could you also please attach your `log.txt` file after you've logged on (before opening NHML manually)

**Comment by arc3521** [comment]
It was listed in the start up items. But it was not working and then I found a work around. adding it manually to scheduler and un-checking the "run with windows" is making it to start with windows.. Thanks very much for replying and I hope it gets resolved in the next update.

**Comment by bruvv** [comment]
yup same issue here.
