### ISSUE TITLE
Dual mining every dcoin connection closed remotely by the pool

### ISSUE THREAD

**Issue by Ory0ne** [nicehash/NiceHashMiner#354]
I've tried to run only the claymore dual miner with batch file, the results are the same on both Nvidia or AMD. After the first found share, the miner says: 
Socket was closed remotely (by pool)
 LBC: Connection lost, retry in 20 sec... and the same with all dcoins.
Sometimes the NHM shows hashrate on the dcoin somtimes doesn't, on the website dashboard I don't see any results of the mining of the dcoins since yesterday payments on the nvidia rig(pascal), on the amd(libry) I see 2 hours of working result. I tried to ping the addresses what is working. Anyway the miner shows the connection is authorized so something is wrong when the miner wants to send the share what is never being accepted. The ethereum mining is working perfectly or zcash etc... , only in dual mode the secondary coins not. Can anybody tells me what could be the problem?
Ps.: Apologies for my poor english.

**Comment by propergol** [comment]
I guess I am having the same issue, no matter what sever I choose.

**Comment by Jakobhoss** [comment]
Same here... on AMD R9 290x 8GB and R9 290 4GB and GTX 480... it´s impossible to mine since yesterday

**Comment by Jakobhoss** [comment]
Nicehash has serious problems. I think they understimated the run on their servers and now they have a real problem with the amount of miners. I´ll leave Nicehash and will go to Coinotron. They are not completely overcrowded and I didn´t see any of these problems there... and the massive drop of BTC per algorythm makes it even worse for NH. It isn´t worth it anymore. They made Mining too easy so every one is running his funny notebook to earn some cents. If they dont solve this very very fast it will be very soon over with this pool. Just transfering my BTC from the NH wallet... just in case they get... HACKED.
Just my opinion...
