### ISSUE TITLE
github-production-release-asset-2e65be.s3.amazonaws.com     Win332:Dropper-gen [Drp]

### ISSUE THREAD

**Issue by FBR4ik** [nicehash/NiceHashMiner#356]
Hello. I can't establish NiceHash Miner Legacy - AMD, the antivirus is blocking Win332:Dropper-gen [Drp].
What me to do? Desible?

**Comment by bonifacio123** [comment]
You need to tell your antivirus software to ignore (not scan) your NHML directory. If you use Windows Defender go to "Virus & threat protection settings" and then select "Add or remove exclusions" under the "Exclusions" section. Click on the plus sign on "+ Add an exclusion", select folder, then navigate to the folder holding NHML.

**Comment by DillonN** [comment]
As explained in the readme NHML can be flagged by antivirus since it downloads miner files that are usually flagged by AV, so you have to manage exceptions
