### ISSUE TITLE
Running Nicehash overnight Often FOUND Nicehash legacy Freezed! get fine when i close mining cmd window.

### ISSUE THREAD

**Issue by mandeep148** [nicehash/NiceHashMiner#358]
hi, 
nicehash latest version 1.8.1.3
i think this issue is old,
may be related to cpu mining  and gpu mining together,
i run overnight i often found that nicehash legacy software freezed, a processing cirle keep spining with mouse and the status also freezed, when i close the mining window(CMD) software works back,
its hard to describe for me..
i hope this will fix in next version..

**Comment by DillonN** [comment]
Hello @mandeep148, are you able to post your `log.txt` file for the period of the freeze?

**Comment by mandeep148** [comment]
Will do it soon.

**Comment by mandeep148** [comment]
here text file. but i dont know when it got freezed but it is freezed when i took this text.
time probably after 17:00 , i guess its because when nicehash automatically change allogirthm to other.

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1333777/log.txt)

**Comment by DillonN** [comment]
@mandeep148 could you please try with the new pre-release, https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.1.4-Pre ?

**Comment by mandeep148** [comment]
@DillonN 
Sir iam running new release now, will tell you soon if any issue persist, i think before it was because of cpu mining, i havent got that problem since i turned it off.
