### ISSUE TITLE
Miner GUI cut off if Resolution is too low

### ISSUE THREAD

**Issue by creative2k** [nicehash/NiceHashMiner#36]
Hello!

There is a problem with the GUI, when the resolution ist too low.
On one of my Machines, i only get 640x480 after a reboot and the miner window is cut off. On machines with higher resolution, this wont happen. The Buttons are working because you can tab around but they are not visible. Can you fix this? :)
![cut_](https://user-images.githubusercontent.com/30184235/28225733-f5d694f6-68d3-11e7-9356-fe1b9c035c96.JPG)

**Comment by ChriscomIT** [comment]
Thanks for reporting! I saw some similar behavior. Should be an easy fix for Dillon.

**Comment by DillonN** [comment]
Thanks, I'll look into this. For now you can access start+stop commands with keyboard shortcuts, Alt+S for start and Alt+O for stop

**Comment by kryptekk** [comment]
Why was this closed....This is still happening Oct 16, 2017!
