### ISSUE TITLE
NHML 1.8.1.3 main windows goes unresponsive after mining for sometime

### ISSUE THREAD

**Issue by sriminer** [nicehash/NiceHashMiner#360]
Hello DillonN

I had the same issue on another mining rig, the main windows goes unresponsive after certain period of mining. I did not notice this in earlier versions of NHML. One of my mining rig is using RX 580's with latest amd driver used. The second one has 4 GTX 1070, 1 RX 470 and 1 RX 580 and using latest amd driver. Only 1070 and 580 are overclocked and 470 running on stock settings

I am attaching screenshot here for your reference. This is the second mining rig with 4 gtx 1070, 1 rx 470 and 1 rx 580. As I mentioned in another thread the other rig also had the same issue

Let me know if I can do something to fix this or if you need further information

Thanks

![2017-09-26](https://user-images.githubusercontent.com/31249729/30844511-5f6f30fc-a2a0-11e7-81a0-b423c7354f8b.png)

**Comment by DillonN** [comment]
From what I can tell it is having trouble contacting the CPU miner API. NHML currently updates the speed data on the UI thread, which can lead to the UI not responding if the speed updates get caught. This will not be the case in an upcoming release

**Comment by sriminer** [comment]
Ok thanks DillonN for your prompt response. Then I will close this thread and wait for next release

**Comment by DillonN** [comment]
@sriminer there is a pre-release up, if you would like to see if it has solved your problem

https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.1.4-Pre

**Comment by sriminer** [comment]
Hi,

I am planning to install this release and update you with my findings of any issues
