### ISSUE TITLE
Mining impossible due network lag? Are you bein ddosed?

### ISSUE THREAD

**Issue by Jakobhoss** [nicehash/NiceHashMiner#364]
I´m mining since a long time, but I´ve never seen this many problems with Nicehash as in the last days. It is impossible to mine, the connection is horrible, the latency is just ridiculous.
Every one of my rigs is not getting any shares at all. In the picture you can see a example. I don´t know what to do anymore. I´ve tried different graphics cards, switched from AMD to Nvidia and vice versa, tried anoter ISP, tried another miners, tried with WLAN and cable connection. Everything you can imagine.
THe thing is, when my miners are connected to Necehash, I even can´t get a stable internet connection and even can´t browse. There is something really wrong with the Nicehash client or server. I fear that you are being ddosed and this causes the lag. So don´t get me wrong but I think the last versions of Nicehash has either an Virus that is stealing shares (would explain the ping) or you are getting attacked from some hackers. I don´t know. I´m not getting this problems on coinotron ro ethermine so it has to be a problem from nicehash side.
So what can I do? I don´t have any idea. But I´m cautious and I´m transferring all my BTC from Nicehas to my main BTC account in case my fears are right.
Sorry Nicehash, get this fixed very soon or for me it´s over at the end of this week.

<img width="960" alt="nicceunhash" src="https://user-images.githubusercontent.com/31692666/30903458-1c7e8be2-a36f-11e7-8a96-ef9715e1ea2e.png">
<img width="960" alt="nicceunhash2" src="https://user-images.githubusercontent.com/31692666/30903482-33438a76-a36f-11e7-9b72-bfbab90aee4a.png">

**Comment by dethknite** [comment]
FYI, there have been numerous network issues across the US yesterday and today with downstream providers... perhaps you should run a few tracerts to alternate addresses and verify this is not a carrier issue.

**Comment by Jakobhoss** [comment]
After hours and hours of trying and testing I´ve found out it´s the Claymore Dual Miner which causes the lag. I don´t know why but in dual mode it kills the network connections. It seems to cause an issue with the PCI. It stresses the PCI so much that even network adapters don´t work. Funny... cause it worked fine till the weekend. OK, end of dual mining... the hashrate in single mode ist about 10% higher but, as i mentioned before only since a few days. 
The funny thing is I run my rigs on pure windows without any additional software and the maximum of security you can get. So I really think this miner is either buggy (but then the error would have occoured much earlier) or it´s malware. Don´t trust Claymore anymore, sorry. Switching to other software which I can compile for myself and know the sourcecode. 
BTW same thing with xmr_stack_cpu. Precompiled piece of ****.
Case closed. Thank you.
