### ISSUE TITLE
NICE HASH WEBSITE

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner#366]
hello

the website since yesterday reports 0 workers ...... cant track my workers and see if they are working fine or not if i cant see the workers in the website ...  can u please fix this issue

Thanks

**Comment by streaml1ne555** [comment]
NiceHash Mining Pool Monitor Phone app still shows active workers, just not the website.

**Comment by blue-yu** [comment]
Same problem here. It is not working for a few days.

**Comment by maxgamurar** [comment]
Same here

**Comment by rcsheets** [comment]
This is the repository issue tracker for the NHML software, not the NiceHash service or website.

**Comment by maxgamurar** [comment]
Indeed. But how do report website issues?

**Comment by drkskwlkr** [comment]
> Indeed. But how do report website issues?

Emailing support@nicehash.com or opening a ticket via [https://www.nicehash.com/support](https://www.nicehash.com/support) should do the trick.

**Comment by ChriscomIT** [comment]
Yeah, Facebook support is super active too.

**Comment by DillonN** [comment]
Yes this is a NH service issue, thanks for directing to the right channels @drkskwlkr and @ChriscomIT
