### ISSUE TITLE
Feedback about NHML.1.8.1.3

### ISSUE THREAD

**Issue by Blacksuu** [nicehash/NiceHashMiner#367]
Hello there a small feedback with few issue:
A. Incorect miner alocation:
In MinerPathPackage_NVIDIA_6_x.json 
          "Name": "NeoScrypt",
          "Algorithm": 8,
Replace   "Path": "bin\\ccminer_tpruvot\\ccminer.exe"
With       "Path": "bin\\ccminer_neoscrypt\\ccminer.exe"
ccminer_neoscrypt is way faster & work better vs ccminer_tpruvot at list at this algorithm at list on cuda 6.x

B. Excavator it came with a verry old version v1.1.4a what it will be nice to be replace by v1.2.11a or v1.3.0a with is last from what i see in nhm.2.0.1.1 so updating it will be good idea!!!
 - about update excavator i am try to do it my self replace excavator with new version BUT i have a problem aka when miner it try to start it generate this error & refuse to work:

Build time: 2017-07-28 11:55:16
Build number: 247
Provided startup commandline:
	"bin\excavator\excavator.exe"  -a equihash -b 20  -cd 0 0  

[20:58:08][0x000011c4][info] Log started
[20:58:08][0x000011c4][error] opencl | Failed to load AMD Display Library.
[20:58:08][0x000011c4][error] opencl | Failed to initialize the AMD Display Library (ADL).
[20:58:08][0x000011c4][info] core | Found CUDA device: GeForce GTX 1060 3GB
[20:58:08][0x000011c4][info] api | Listening on 127.0.0.1:3456
[20:58:08][0x000011c4][error] core | Failed to open command file: 0
[20:58:08][0x000011c4][info] core | Initialized!

i gues this parameter "-cd 0 0" is problem but digging in all config file i was not succeed to find how to fix 
- internals\MinerOptionPackage_excavator.json look fine
- configs\ <nothing in that file relevant
So question with file i need to modifie to fix this error ... ? aka to remove -cd 0 0 parameter from miner starting command ?

C. Last thing & most important one when nicehashminerlegacy it switch between miner application (because better income from other algorithm / coin) it have nasty habit to crash video driver because your kill command is not gentle one i guess, if i manually start any miner & close them by my hand is fine if your application it make switch it end usual crash video driver aka a better solution it will be good in future

P.s. if i try to use manually Excavator version: 1.3.0a modifie "default_command_file.json" or create new one & change in excavator+web+restart_script.bat like "SET COMMAND_FILE=nicehash.json" it end web browser say 1. Status: Fail, 2. get pool address undefined, 3. Total speed incorrect & efficiency always be 0. This is a minor issue because miner working fine only web browser it is not functional
- 1.3.0a i have it from Nhm 2.0.1.1

Cheers

**Comment by rcsheets** [comment]
This should probably be three issues, rather than one issue in three unrelated parts.

**Comment by Blacksuu** [comment]
@rcsheets  there are 4 issue to be more precise, but last one it suppose to be in other section ;) ... anyway NHML.1.8.1.3 & NHN 2.0.1.1 are develop by same fantastic ppls so in stead losing time to open 4 thread open 1 was simple, that i name title "Feedback about ..." so my be you have a point, fell free to open 4 separate one in case you have same issue ;)

P.s. new small issue: temporary file what are generated by NHN 2.0.1.1 like XXXX.tmp.node they are not clean, delete after NHN is close 

cheers

**Comment by DillonN** [comment]
@Blacksuu thanks for the feedback.

A. I will look into the differences on some setups and change the default if it's faster. Thanks for finding!

B. Excavator is intentionally not updated in NHML. The reason for this is to keep NHM2 isolated from antivirus flags. Unfortunately for the time being if you want to use the updated excavator you should use NHM2 (you are correct that you cannot drop it in the NHML install because the API has changed). 

C. Yes I'm aware of this, the killing of some processes hasn't been changed for quite some time (before NHML was the "Legacy" edition). There is a very in-depth PR #312 that aims to fix this issue, and I'm going to go over it once I get some other bug fixes out

**Comment by Blacksuu** [comment]
Hello @DillonN 

A. About NeoScrypt algorithm in case for some ppls / setup ccminer_tpruvot or ccminer_neoscrypt are better make them bouth miner to can be select from list & let ppls choose after run benchmark what is best :)
at list in my case (1 x GTX 1060 3GB) using ccminer_neoscrypt means jump from 500 (default tpruvot) to 620 with same video setting, for me change that file it was easy solution :)

B. If you want to keep Excavator 1.3 only for NHM2 fine i understand special 1.3 it want to make NHM2 be independent by anyother miner app (seen already it came with own dual mining capability with is great) at list pls update to v1.2.11a or v1.2.xx or tell me what file i need to edit to change start up condition for running excavator aka to remove "-cd 0 0" it will fix easy the problem (that in case is not hardcoded in NHML how each program start)

C. yup i see  Sav87 it try to came with solution & i think he is on good path aka ProcessHandle.EndProcces(1000) / CtrlTypes.CTRL_C_EVENT make wait more client to be close is a solution, thx for show me me that PR cheers

D. Be ware NHM2 aka Excavator 1.3 when it use to mine Equihash algorithm it use only 1 treath / worker ({"id":1,"method":"worker.add","params":["0","0"]}, with it make him lose some speed, i already find a way to split / add 1 more worker but it is messy & probabil it will mess up rest algorithm aka i edit 
General.json adding this "ExcavatorExtraStartupParameters": "-c nicehash.json -d 2 -f 2", were in nicehash.json i have customize setting for Equihash algo
- a good thing it will be to add option to add extra parameter for each algoritm it use, what i done is influence evrything :) but it working ok (already running equihash & dagger algo in this way) about this probabil it will be good to open a post in NHM2 section ... i will see

Atm i use NHM2 & NHML because NHM2 it need more algo to be add like NeoScrypt, Lybry, Dagger+Lybry my be more what i guess it will happen in time. One more thing plsss for NHM2 let ppls choose path were to install program it trigger my OCD when i see him install by default on a place what i hate & in my book is bad ... sooo pls pls give me option to choose :)

cheers

**Comment by Sav87** [comment]
use `Process.Kill()` like braking a car against a wall, like and stopped, but how will the driver feel? Whether the driver is guilty of that the motor-car manufacturer does not establish brake system.
In fact, in most cases, enough CTRL+C, somewhere else. Now I have a slightly different task in the priority, to rewrite the class of Miner and his peredvodnye under my needs.

**Comment by Blacksuu** [comment]
@Sav87 well yup you was make a nice analogies with car, driver & wall & i understate perfectly what you try to say :) that i say from my first post it need a more "gentle" way to do it. After i see you PR & try to fix i understate perfectly, for what i hope your work to be successful
Well in case you have other priority, well you are the only one who decide what to do :)  anyway thx for try at list
Cheers

**Comment by Sav87** [comment]
I do not have the ability to check all the algorithms and find their way to close correctly. In my case, if CTRL+C does not work, everything happens in the old-fashioned way. through `Process.Kill()` it is necessary to finish it. To wait 1000ms it is necessary only in this case, + 1000ms if there is no window of the miner. It is not a problem to take out 1000ms settings. it's better to spend 1s than a couple of minutes to reboot or restart the program.

**Comment by Sav87** [comment]
CTRL+C  normally works on all algorithms of available 1080 Nvidia. Only there is a problem with Daguerhashimoto (etnminer), Only there is a problem with daggerhashimoto (ethminer), if you send a signal when generating dag, the driver crashes.
