### ISSUE TITLE
NiceHashMinerLegacy 1.8.1.3

### ISSUE THREAD

**Issue by barkley74rus** [nicehash/NiceHashMiner#369]
After blocking windows, the defender failed to pass the tests for Equihach.
Card
1070, 1080, 1080ti
К кеасаки не подключается к другому эквихэшу тоже, ошибка

**Comment by barkley74rus** [comment]
![image](https://user-images.githubusercontent.com/32337778/30926232-e188642c-a3cd-11e7-835d-e8cfae3852d6.png)

**Comment by barkley74rus** [comment]
![image](https://user-images.githubusercontent.com/32337778/30926258-fc0ef1bc-a3cd-11e7-8362-ca1278a0d113.png)

**Comment by DillonN** [comment]
@barkley74rus could you try again now? There were some server side issues that are resolved now. Unlike most miners, EWBF does not have an offline benchmark mode and so it needs to be able to connect to the server in order to benchmark

**Comment by barkley74rus** [comment]
Проблема осталась. Также не проходит Equihach.
Через раз получается майнить на других алгоритмах, поясняю..
То ошибка, то все нормально запускается.
