### ISSUE TITLE
missing workers?

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#370]
when i click view stats i get to see my mining data but it says workers 0

the graph still shows my mining stats etc.

its also stopped showing me my next payout date :(

**Comment by blue-yu** [comment]
Same problem here. I hope that they will fix it soon...

**Comment by jimmyhackers** [comment]
do you get a cloudflare ddos warning  page before the nicehashpage loads?

im kinda paranoid that someones robbing or snooping at my mining activity.

**Comment by drkskwlkr** [comment]
> do you get a cloudflare ddos warning page before the nicehashpage loads?

Yes.


> im kinda paranoid that someones robbing or snooping at my mining activity.

Somebody may be watching a bitcoin address that happens to be yours but:
1. It is highly unlikely he does
2. If he does, he has no way of knowing it belongs to you specifically
3. Even if he does, it is just a hash of a hash of the output of a trapdoor function that is supposed to be public

> someones robbing

Here's [a Bitcoin address with 114,800 BTC on it](https://bitinfocharts.com/bitcoin/address/3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r). And [another with 99,348 BTC](https://bitinfocharts.com/bitcoin/address/3Nxwenay9Z8Lc9JBiywExpnEFiLp6Afp8v). Go rob them.


> im kinda paranoid

No, you're just kinda uninformed. Get to know Bitcoin better and paranoia will give way to inner peace and eternal calmness. Waterfalls and flying unicorns are optional :)

**Comment by jimmyhackers** [comment]
its all back to normal.......
