### ISSUE TITLE
NHML 1.8.1.3 detected as Trojan:Win32/Vagger!rfn by Windows Defender

### ISSUE THREAD

**Issue by rcsheets** [nicehash/NiceHashMiner#372]
I was running NHML 1.8.1.3 on Windows 10 version 1703 (15063.608) on x64 with the following Windows Defender versions:

Antimalware Client Version: 4.11.15063.447
Engine Version: 1.1.14202.0
Antivirus Version: 1.253.31.0
Antispyware Version: 1.253.31.0
Network Realtime Inspection Engine Version: 2.1.13804.0
Network Realtime Inspection Signature Version: 117.12.0.0

The `NiceHashMinerLegacy.exe` file was quarantined.

**Comment by mcsjohn** [comment]
The quarantine might have happened with older version of signature (1.251.1540.0 to 1.253.24.0). Since 1.253.30.0 it is no longer detected, see https://github.com/nicehash/NiceHashMinerLegacy/issues/368

**Comment by DillonN** [comment]
Yes @rcsheets please see the issue referenced (#368).
