### ISSUE TITLE
Geting NS SMA info FAIL

### ISSUE THREAD

**Issue by RodAus** [nicehash/NiceHashMiner#373]
happens quite frequently, there is no problem with Internet connection 

![capture](https://user-images.githubusercontent.com/31544552/30962929-fcf807b4-a48e-11e7-856c-50dc28e094b7.PNG)

**Comment by Blacksuu** [comment]
same problem on NHML.1.8.1.3 & NHN 2.0.1.1 SMA fail to respond, but it my be possible because nicehash site it say some part are under maintenance ...

**Comment by DillonN** [comment]
Is it working now? There were some server side issues as I understand it. NHML relies on the server to work properly

**Comment by Blacksuu** [comment]
@DillonN  yes issue was fix or working agen on NHM2 & NHML, SMA & bouth relies on get data from that coz it reflect rapport price / coin base on what is make switch or it update estimate value income on your client interface.

**Comment by RodAus** [comment]
I'm using version 1.8.1.3, and the problem persists, after about 30 min it back to works, this happens frequently on NHLM.

**Comment by DillonN** [comment]
NHML requires a connection to get paying rates for different algorithms, in order to know which to run

If you are able get a connection once after opening, then it will use whatever most recent data and keep trying to reconnect. Connections can drop from unstable internet or firewalls
