### ISSUE TITLE
Terminated Scripts

### ISSUE THREAD

**Issue by raregems** [nicehash/NiceHashMiner#374]
I am using NHML 1.8.3 and have been using NHML, updating every version accordingly and properly. I have never been able to benchmark any of my cards for the following algorithms:

DaggerLbry
DaggerDecred
DaggerHashimoto
DaggerPascal
DaggerSia

My hardware is the following:

6x 1080 Ti:

4 EVGA GeForce GTX 1080Ti SuperClocked Edition
1 NVIDIA GeForce GTX 1080Ti Founder's Edition
1 MSI GeForce GTX 1080Ti Duke Edition

On the MSI Duke, I cannot benchmark Lyra2REv2 in addition to the Dagger scripts. But, Lyra2 works for the other cards.

Manual benchmarking and uninstalling and reinstalling does not work, the error message I receive is the following:

"The code execution cannot proceed because MSVCR120.dll was not found. Reinstalling the program may fix this problem."

Screenshot attached:
https://www.nicehash.com/public/17637-50220-ff6d4cb3193982e70b1c12f33d17d09d.png

I have tried several installations and un-installations, as well as reverting to previous versions. Also manually benchmarking each algorithm for each individual card according to the "Terminated Scripts" Guide. Can anyone provide me information on how to fix this? I'm almost certain these scripts were working on my previous machine before moving the cards to this one.

Thank you-

**Comment by Mystere** [comment]
How did you install 1.8.1.3?  Did you download to its own folder and run it?  Or did you copy it over an existing folder?  And what do you mean "uninstall"?  You mean you deleted it, and downloaded a new version?  There is no "installer" program.. it's just a download, unzip, and run.

**Comment by raregems** [comment]
@mystere 

I followed the procedures provided and the recommended upgrade:
Download -> extract into its own folder -> copy over config files

What I meant by install and uninstall, is that yes, I have deleted and redownloaded and rebenchmarked. I have tried downloading it as new, and also the upgrade process. I never mentioned a separate 'installer program', just replace the words of my original post uninstall and install with downloading, unzipping, running, etc. it was poor choice of words.

The problem is with the terminated scripts during benchmark, and also not being able to run on their own. The error message I receive is: "The code execution cannot proceed because MSVCR120.dll was not found. Reinstalling the program may fix this problem."

So yes, I have "reinstalled" the program several times unfortunately with no fix. Thank you

**Comment by drkskwlkr** [comment]
> MSVCR120.dll was not found

Ah, the dreaded MSCVR*.dll error. Will [this solution](https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Troubleshooting#msvcp) work for you?

**Comment by Sav87** [comment]
I do not understand why developers can not make a folder with all the necessary * .dll files, and add it to the PATH environment variable for the search.

**Comment by raregems** [comment]
TO ALL WHO SHARE THIS ISSUE
@drkskwlkr @mystere @sav87

The cure is below:

https://www.microsoft.com/en-us/download/details.aspx?id=40784

Thanks for all who helped, just install both versions from this site and then run
