### ISSUE TITLE
NHML 1.8.1.3 ISSUE REPORT

### ISSUE THREAD

**Issue by sriminer** [nicehash/NiceHashMiner#375]
Hello DillonN

Just wanted to update you few issues with the latest version. I tried looking few threads if someone has reported these but really didn't find it so far

1. The new version the hash speed is not constant for AMD cards particularly I noticed this. It rapidly changes from 27 Mh/s to 10 Mh/s and then sometimes 2 Mh/s and jumps to 27 Mh/s this way the revenues are fluctuating rapidly. I initially thought there is something wrong with my rig but when I ran 1.8.1.2 the hash rate is constant but DaggerLbry profitability is less I guess this is one of the improvement made in 1.8.1.3

2. Also sometimes while switching ccminer get stuck for neoscrypt and keeps closing and opening the command window but doesn't mine this is also effecting revenue generation as the GPU's remain idle. We have to restart the pc and then it works fine. This issues seems to occur randomly. I am still yet to see this issue in 1.8.1.2

Hope to see them fixed in the next release

Regards

**Comment by DillonN** [comment]
@sriminer for your first issue, could you try what I mentioned [here](https://github.com/nicehash/NiceHashMinerLegacy/issues/345#issuecomment-332058088)

**Comment by sriminer** [comment]
Hello DillonN

Yes first issues sorted out by disabling cpu mining. I will give the new pre release a try and update if I found any issues

Thanks
