### ISSUE TITLE
NHLM 1.8.1.3 and lower chooses incorrect algos

### ISSUE THREAD

**Issue by DmitryDMR** [nicehash/NiceHashMiner#377]
The program incorrectly chooses the algorithm. for example, I have 2 rigs for 6* gtx1070. On the first rig all benchs passed correctly and for all the GPU Equihash algo started.On the second rig the first video card the Equihash algo went wrong with very low profitability, but Dagger algos passed normally everywhere.
Now, on the first rig, started Equihash algo, but on the second rig started Dagger algos for all cards with a stronger overclock and lower profitability, although the dagger algos should only start for the first card, and for the other Equihash algo. I overplayed the benchmark Equihash algo on the first card, then started Equihash algo for all the cards.

**Comment by Mystere** [comment]
Did you try re-running the benchmarks?  It's not choosing the wrong algo, it's choosing what it thinks is right based on the data it has.

**Comment by DmitryDMR** [comment]
Yes, of course I re-run benchs. But after I saw the the algos is wrong.
Dagger Hashrates of my card:
30, 30, 30, 30, 30, 30
Equihash Hashrates of my card:
240, 450, 450, 450, 450, 450
And NHML should have run Dagger for 1 card, and Equihash algo for 2-6 cards, but NHML run Dagger algo for all 1-6 card.
After re-run bench for 1 card with 450 sol/s NHML run Equihash algo for all 1-6 card.
