### ISSUE TITLE
sma information issue~!!!

### ISSUE THREAD

**Issue by xcom99** [nicehash/NiceHashMiner#385]
i,m use NHMl-1.8.1.4 version. i.m gating sma information problame is stuck then a error message come that says NHMl need internet problem but my net is ok. no matter when i start the program it says the same thing.i saw a YouTube guy solving this problem by disable his ipv6. i tray now working if any one can help me plz.
![nicehashminerlegacy_2017-10-01_06-41-23](https://user-images.githubusercontent.com/32433310/31055520-f5003ce8-a678-11e7-9260-57769f681ace.png)

**Comment by xcom99** [comment]
![nicehashminerlegacy_2017-10-01_06-41-23](https://user-images.githubusercontent.com/32433310/31055502-9e544614-a678-11e7-8cbe-3e32539ab085.png)

**Comment by bobsharpie** [comment]
In the debug log I find:::

'NiceHashMinerLegacy.vshost.exe' (CLR v4.0.30319: NiceHashMinerLegacy.vshost.exe): Loaded 'C:\Users\miner\Source\Repos\NiceHashMinerLegacy\Debug\websocket-sharp.dll'. Module was built without symbols.
10/07/2017 21:32:54|Warn |Logger.set_Level|The current logging level has been changed to Debug.
10/07/2017 21:32:54|Debug|WebSocket.sendHttpRequest|A request to the server:
                          GET /v2/nhm HTTP/1.1
                          User-Agent: websocket-sharp/1.0
                          Host: api.nicehash.com
                          Upgrade: websocket
                          Connection: Upgrade
                          Sec-WebSocket-Key: IOohRRoc+9mMJuyHleaThg==
                          Sec-WebSocket-Version: 13
10/07/2017 21:32:54|Debug|WebSocket.sendHttpRequest|A response to this request:
                          HTTP/1.1 101 Web Socket Protocol Handshake
                          Date: Sun, 08 Oct 2017 01:33:17 GMT
                          Connection: upgrade
                          Set-Cookie: __cfduid=d1ac0fe11d8a47fccb7a0f2bb71854f5c1507426397; expires=Mon, 08-Oct-18 01:33:17 GMT; path=/; domain=.nicehash.com; HttpOnly
                          X-Powered-By: Servlet/3.1 JSP/2.3 (GlassFish Server Open Source Edition  4.1.2  Java/Oracle Corporation/1.8)
                          Sec-WebSocket-Accept: P4wcgEnMB43lUTUPE2jZWVqCIek=
                          Upgrade: websocket
                          Server: cloudflare-nginx
                          CF-RAY: 3aa559e5f9275741-IAD
'NiceHashMinerLegacy.vshost.exe' (CLR v4.0.30319: NiceHashMinerLegacy.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'NiceHashMinerLegacy.vshost.exe' (CLR v4.0.30319: NiceHashMinerLegacy.vshost.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
[21:32:55] [SOCKET] Sending data: {"method":"login","version":"NHML/1.8.1.4","protocol":1}
The thread 0x784 has exited with code 0 (0x0).
The thread 0x13cc has exited with code 0 (0x0).
The thread 0x20ec has exited with code 0 (0x0).
The thread 0x2170 has exited with code 0 (0x0).
The thread 0x12b8 has exited with code 0 (0x0).
The thread 0x214c has exited with code 0 (0x0).
The thread 0x230c has exited with code 0 (0x0).
The thread 0xb64 has exited with code 0 (0x0).
The thread 0x2298 has exited with code 0 (0x0).
[9:37:33 PM] [SOCKET] Connection closed: An exception has occurred while receiving.
[9:37:33 PM] [SOCKET] Attempting reconnect in 0 seconds
10/7/2017 9:37:33 PM|Fatal|<>c__DisplayClass9.<ReadBytesAsync>b__8|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                              at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                              at WebSocketSharp.WebSocketFrame.<>c__DisplayClassa.<readHeaderAsync>b__9(Byte[] bytes)
                              at WebSocketSharp.Ext.<>c__DisplayClass9.<ReadBytesAsync>b__8(IAsyncResult ar)
10/7/2017 9:37:33 PM|Debug|WebSocket.closeHandshake|Was clean?: False
                             sent: False
                             received: False
10/7/2017 9:37:33 PM|Debug|WebSocket.sendHttpRequest|A request to the server:
                           GET /v2/nhm HTTP/1.1
                           User-Agent: websocket-sharp/1.0
                           Host: api.nicehash.com
                           Upgrade: websocket
                           Connection: Upgrade
                           Sec-WebSocket-Key: IOohRRoc+9mMJuyHleaThg==
                           Sec-WebSocket-Version: 13
[9:37:33 PM] [SOCKET] Sending data: {"method":"login","version":"NHML/1.8.1.4","protocol":1}
10/7/2017 9:37:33 PM|Debug|WebSocket.sendHttpRequest|A response to this request:
                           HTTP/1.1 101 Web Socket Protocol Handshake
                           Date: Sun, 08 Oct 2017 01:37:55 GMT
                           Connection: upgrade
                           Set-Cookie: __cfduid=d4afff82fcf80b659919cb4a969060d221507426675; expires=Mon, 08-Oct-18 01:37:55 GMT; path=/; domain=.nicehash.com; HttpOnly
                           X-Powered-By: Servlet/3.1 JSP/2.3 (GlassFish Server Open Source Edition  4.1.2  Java/Oracle Corporation/1.8)
                           Sec-WebSocket-Accept: P4wcgEnMB43lUTUPE2jZWVqCIek=
                           Upgrade: websocket
                           Server: cloudflare-nginx
                           CF-RAY: 3aa560b1a9c356a5-IAD
The thread 0x11f8 has exited with code 0 (0x0).
The thread 0x1984 has exited with code 0 (0x0).
[9:41:15 PM] [SOCKET] Connection closed: An exception has occurred while receiving.
10/7/2017 9:41:15 PM|Fatal|<>c__DisplayClass9.<ReadBytesAsync>b__8|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                              at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                              at WebSocketSharp.WebSocketFrame.<>c__DisplayClassa.<readHeaderAsync>b__9(Byte[] bytes)
                              at WebSocketSharp.Ext.<>c__DisplayClass9.<ReadBytesAsync>b__8(IAsyncResult ar)
10/7/2017 9:41:15 PM|Debug|WebSocket.closeHandshake|Was clean?: False
                             sent: False
                             received: False

**Comment by xcom99** [comment]
OK how can i fix it?

**Comment by b0b5h4rp13** [comment]
For now go back to version 1.8.0.2 as it uses another way to contact the server for current algorithm rates. The newer ones work on my ASUS Z270 motherboard but they don't work on my Gigabyte Z97

it may hang on getting SMA, or it may get no results and act like it can't connect, so get an older version from this address, scroll down till you see 1.8.0.2
https://github.com/nicehash/NiceHashMinerLegacy/releases

**Comment by b0b5h4rp13** [comment]
Call stack where the hang occurs

 [External Code]
	NiceHashMinerLegacy.exe!NiceHashMiner.Devices.CPUComputeDevice.Load.get() Line 18	C#
	NiceHashMinerLegacy.exe!NiceHashMiner.NiceHashStats.DeviceStatus_Tick(object state) Line 283	C#
      NiceHashMinerLegacy.exe!NiceHashMiner.NiceHashStats.NiceHashConnection.ConnectCallback(object sender, System.EventArgs e) Line 118	C#
 [External Code]	
       NiceHashMinerLegacy.exe!NiceHashMiner.NiceHashStats.NiceHashConnection.StartConnection(string address) Line 98	C#
 	NiceHashMinerLegacy.exe!NiceHashMiner.NiceHashStats.StartConnection(string address) Line 220	C#
 	NiceHashMinerLegacy.exe!NiceHashMiner.Form_Main.StartupTimer_Tick(object sender, System.EventArgs e) Line 298	C#
 [External Code]	
 	NiceHashMinerLegacy.exe!NiceHashMiner.Program.Main(string[] argv) Line 89	C#
 	[External Code]

**Comment by b0b5h4rp13** [comment]
Hang on

namespace NiceHashMiner.Devices
{
    class CPUComputeDevice : ComputeDevice
    {
        PerformanceCounter cpuCounter;

        public override float Load {
            get {
                try {
                    if (cpuCounter != null) return cpuCounter.NextValue(); <--- this line
                } catch (Exception e) { Helpers.ConsolePrint("CPUDIAG", e.ToString()); }
                return 0;
            }
        }

**Comment by b0b5h4rp13** [comment]
This appears to be a common problem with PerformanceCounter NextValue

https://stackoverflow.com/questions/2868068/performancecounter-nextvalue-hangs-on-some-machines

**Comment by xcom99** [comment]
tx. so thy relies 1.8.13 is dosnot stuck and works good tx for your help.so you send some cods i need to add them if same pro-blame happens.ware do i add them?

**Comment by xcom99** [comment]
dont go for it it dosent  work any more! is workt first after a cpu restart  is happening all over again.

**Comment by Alexmarch1** [comment]
Constant such problem

**Comment by Sav87** [comment]
add Pull request #625

**Comment by xtrime-ru** [comment]
@Sav87 made few fixes, so NHML can use another way of getting SMA data if primary method fails.
I've compiled his fixes and made this release:

https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases

**Comment by x2ruff4u** [comment]
@xtrime-ru  That didn't work for me :( Going back to 1.8.0.2 seems to work for now.  I really hope they fix this soon :(

**Comment by xtrime-ru** [comment]
@x2ruff4u  A lot of users have no issues after fix. Today was some problems with nicehash api (its backup method in fix), maybe you tried fix while api was having issues...  But im glad to know that you have backup plan :)

**Comment by x2ruff4u** [comment]
Well there's a few different versions of 1.8.1.5 does it matter which? I just tried it again and still hangs on the error which is odd. I was mining fine and I keep 2 profiles for mining, one with limits so I can use my pc and the other with no limits while I sleep full speed mining. This error happened out of nowhere and I didn't do anything odd.

**Comment by xtrime-ru** [comment]
@x2ruff4u I've tested fix on latest 1.8.1.5 https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.1.5
and on 1.8.2 pre-2

Are you sure you replaced 20 files in nicehash folder from .zip? 
Can you send screenshot of error?

**Comment by x2ruff4u** [comment]
@xtrime-ru  Okay I did a fresh download of that version and just moved the files to that folder and now it's working! Maybe I had some odd configuration which was messing with it before. Thanks so much!!!

**Comment by xtrime-ru** [comment]
@x2ruff4u glad to hear! 
Also your version could be old and without some files, wich new exe with fix was trying to run in middle of mining. 

I think you can try to add your configs, there is no changes in fixed exe in that area.

**Comment by SnowmanUT** [comment]
Still getting the same problem after trying the NiceHashMinerLegacy 1.8.1.5 with SMA fix. Tried downloading various versions and they all get stuck at the " Getting NiceHash SMA Information". Is there something else I need to check? Everything was fine yesterday.
