### ISSUE TITLE
CUDA/Display driver crashes

### ISSUE THREAD

**Issue by luongk** [nicehash/NiceHashMiner#387]
I'm experiencing occasional CUDA/Display driver crashes - they seem to be related to algorithm switching.  Essentially the display will go blank - if I remote into my computer I can see NHML opening and closing miner windows (as no device is detected).  

Any suggestions?  I tried the NVInspector driver reset as per https://github.com/nicehash/NiceHashMinerLegacy/pull/268 but the display driver doesn't seem to restart (I just get a blank screen with cursor showing when I remote in).  Restarting the machine seems to be my only option, which is fine if I catch the error, but often it'll go on for a while before I notice.

I'm using an EVGA 1080ti FTW3 + 980 SC, not overclocked, running the latest NVIDIA drivers (385.69  clean installed using DDU).  Temperatures seem okay just prior to the display driver crash.  Currently using 1.8.1.4 pre-release, but I've been experiencing this behaviour since at least 1.8.1.2

[log - Copy.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1347711/log.-.Copy.txt)

**Comment by sebeksd** [comment]
Try new option in "1.8.1.4 Pre-release 2" called "Run script when CUDA GPU is lost". Look into "OnGPUsLost.bat" file, you can restart your Rig or just restart drivers from there. 
For me NVInspector driver restart work perfectly (OPT2) but in your case you can use rig restart (OPT1).

**Comment by luongk** [comment]
Yeah, thanks - rig restart seems to be a decent workaround.
