### ISSUE TITLE
Lower performance after adding another gpu

### ISSUE THREAD

**Issue by mandeep148** [nicehash/NiceHashMiner#391]
Hi, 
Im getting lower performance after adding another gpu,
I have gtx 1070 was getting 440-445sols after adding another gpu(gtx 1060)
And performance of gtx 1070 fell down to 410-415 sols please help me, if theres any intensity to apply kindly guide me instead of giving me link,
Give me intensity to try on neoscript or equahash eqwf, 
Using i5 6600k for reference.

**Comment by bonifacio123** [comment]
Check the temps of your GPU's with Afterburner or another tool. If these GPU's are both in a case without adequate ventilation they may be getting too hot and throttling down. Also, with GPU-Z the "PerfCap Reason" sensor will also show you if your GPU is being throttled due to temp.

**Comment by vinaybhushanj** [comment]
Write more of mining

**Comment by mandeep148** [comment]
Temperatures are fine about 80 of 1070 and 78 of 1060,

**Comment by maxgamurar** [comment]
80 is not fine. 65-70 is fine

**Comment by Crypto-Lord** [comment]
How many case fans do you have?
What's the fan speed % your GPUs are running at?
How much space between the GPUs?

**Comment by maxgamurar** [comment]
I have 6 x 14cm fans, 6 1080ti gpus, 100% fan speed.
Approx distance 6cm

**Comment by mandeep148** [comment]
Temp was going to 85c, now my rig is opened, temp went to 69-71c. Will make mining case in days.

**Comment by Crypto-Lord** [comment]
@mandeep148 
Aim to get temps around 65 on average. Running any GPU at >80c constantly will drastically lower the lifespan, if not cook it.

**Comment by mandeep148** [comment]
@Crypto-Loard 
I agree but not today gpus, also not high end gpu like 1070,
Cooler are best today, before time heat sink was crap and performance was like not even close to 10% of today gpu, im pretty sure that 80 is safe, because any card cannot get less temperature in cabinet, and they are tested in cabinet too, only have 1 choice to get less temp is get gpu out. :)

**Comment by Crypto-Lord** [comment]
@mandeep148 
Let me know how it goes running your gpu(s) 80+
I've fried more than 1 high-end gpu due to heat. I've been switching to water-cooled to bring temps down. Problem is when running gpus at high temps 24/7 it'll result in "throttling" of hashing power and will also drastically lower the lifespan of the gpu. If your 'cabinet' doesn't have adequate airflow then temps will be high. 

Possibly think about these 2 options (instead of removing a gpu)
1. Get a larger PC case that supports lots of case fans
2. Use a gpu riser to get the gpu out of the case.

**Comment by DillonN** [comment]
@mandeep148 besides the worries others have mentioned about running a card at 80, it can severely limit performance. Especially the new NVIDIA cards which have GPU Boost 3.0, they are designed to slow down as they reach higher limits. Even as low as mid 60s the clocks will start to drop, albeit very minimally at first. At 80 the clocks will be lowered quite a bit, the GPU will try its best to not go over around 84 (default value may differ) so it lowers clocks to stay below that.

You can use a program like Afterburner to monitor clocks and see how different things you do to lower temperature helps them
