### ISSUE TITLE
у меня две видео карты nvidia 1060 1070 по отдельности они в майнере роботают, но вместе компютер перезагружается после некоторых монипуляций с ПК все роботает норм,гдето дней 5,манипуляции я имею ввиду переустановку системы,драйверов и т.д каждый раз незнаю что помогло моя системаAMD Atlon x4 840 Quad Core Procesor 3.10Ghz Socket FM2+ MSI A68HM-E33 V2 A68 2xDDR3 PCI-E16x PCI 4xSata3 2xPS/2mATX озу 4Gb DDR3 1600MHz 12800 video gefors nvidia gtx 1060 6gb       gefors nvidia gtx 1070 8gb БП Gamemax 700w GE-700 ATX box HDD 500Gb(3.5)7200Toshiba SATA III 32Mb 

### ISSUE THREAD

**Issue by sokol2016** [nicehash/NiceHashMiner#392]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [x] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by sokol2016** [comment]
у меня две видео карты nvidia 1060 1070 по отдельности они в майнере роботают, но вместе компютер перезагружается или повисает
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1350273/log.1.txt)
 после некоторых монипуляций с ПК все роботы норм, гдето дней 5, манипуляции я имею ввиду переустановку системы, драйверов и т.д каждый раз незнаю что помогло моя системаAMD Atlon x4 840 Quad Core Procesor 3.10Ghz Socket FM2 + MSI A68HM-E33 V2 A68 2xDDR3 PCI-E16x PCI 4xSata3 2xPS / 2mATX озу 4Gb DDR3 1600MHz 12800 видеогефоры nvidia gtx 1060 6gb gefors nvidia gtx 1070 8gb БП Gamemax 700w GE-700 ATX box HDD 500Gb (3.5) 7200Toshiba SATA III 32Mb

**Comment by sokol2016** [comment]
добрый День,ну что никто мне ничего неподскажет, сегодня опять майнер неработает, компьютер просто перезагружаеться,но это пол беди,это раз в пару часов,но всё таки по маленькому роботает,а вот когда повиснет вместо перезагрузки то всё я вижу только письмо на почту что воркеры стоят и все,а перезагрузить немогу потомучто не дома и пока приеду то по одному дню бывает простой,а так компьютер роботает и даже с другими майнерами,вот даже криптекс у меняироботает, пожалуйста подскажите почему майнер  NHML не работает

**Comment by bruvv** [comment]
Can someone just close this ticket please it clutters the real issues.

**Comment by sokol2016** [comment]
да я непротив чтоби мнеипомогли и я закрил билет,но даже ви ничего неподсказали а только сказали что я мешаю
