### ISSUE TITLE
Claymore cryptoNote AMD GPU miner does not work

### ISSUE THREAD

**Issue by utc99** [nicehash/NiceHashMiner#396]
Claymore's CryptoNote AMD GPU miner v 10.2 does not work on AMD card, on NVIDIA + AMD setup. Maybe its counting gpus wrong. 
Miners gives error - "no asm binary found on gpu 0", while nvidia claymore dual miner - ETH: 10/04/17-12:18:43 - SHARE FOUND - (GPU 0), while numeration in NH UI seems to be gpu1 + gpu2. More clear info is on screenshot and logs:
![nhbug1](https://user-images.githubusercontent.com/26816096/31169923-f861c1e0-a902-11e7-9e54-58bf462756d4.JPG)

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1355335/log.txt)

System: Windows 10 pro, firewall off, gtx1070 + amd radeon hd 7700 series
NHML version: 1.8.1.4 pre 2

Problem does not occur on NHML 1.8.1.3 with cryptonote 9.7 beta, overwriting miner with old one does not seem to work, probobly some configuration in NH was changed

**Comment by DillonN** [comment]
I made comments on this in issue #376
