### ISSUE TITLE
xmrig seems to be a bit faster then XmrStackCPU.

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#398]
As the title says.

**Comment by mcsjohn** [comment]
And also has pool failover support

**Comment by DillonN** [comment]
@seiterseiter how much faster are you seeing? I do not see any advantage on my CPU. The miner unfortunately also has no API from what I can see, which means NHML won't be able to interact with it

**Comment by mcsjohn** [comment]
In my case, I tested on a few CPUs and the gain is about 10% (first numbers are from xmr-stak-cpu, later from xmrig)
Intel Core i5-3320M: 50-55 H/s - > 60-65 H/s
Intel Xeon E3-1535M v6: 160-170 H/s -> 180-190 H/s
Intel Xeon X5650: 180-190 H/s -> 195-205 H/s
2 x Intel Xeon E5-2420: 360-380 H/s -> 460-480 H/s this one is quite a big improvement, but I think it has something to do with miner's configuration, didn't had time to check.
As parameters for xmrig I have removed -k and added --nicehash and --cpu-affinity

Indeed the lack of an API is a bottleneck but it looks xmrig is working on this https://github.com/xmrig/xmrig/issues/106 and https://github.com/xmrig/xmrig/issues/6 so maybe after it is implemented it can be intergrated to NHML. I've also seen there is another thread on this https://github.com/nicehash/NiceHashMinerLegacy/issues/226

**Comment by mcsjohn** [comment]
Seems like xmrig now has an API as of version 2.4.0 (https://github.com/xmrig/xmrig/wiki/API) so maybe it can be integrated with NHML

**Comment by DillonN** [comment]
@mcsjohn thanks for the benchmarks and notice Xmrig is updated. Looks like it should work now! I'll try to have an update out for it soon

**Comment by mcsjohn** [comment]
Thank you @DillonN

**Comment by Nicheuji** [comment]
@DillonN Will we be able to set the donation levels ourselves? While many would prefer to set it to 0, I'm sure there are a few that wouldn't mind donating at least at level 1.

**Comment by DillonN** [comment]
@Nicheuji yes the donation level will be configurable

**Comment by Twanislas** [comment]
Please note that if you set the donation to 0% it will default to 5% as the minimum is 1%. See xmrig/xmrig#171

Cheers !
