### ISSUE TITLE
maxtemp setting?

### ISSUE THREAD

**Issue by kfadrat** [nicehash/NiceHashMiner#399]
is there somewhere a maxtemp setting that you can change for all miners or do you need to do it for every single miner one by one?

**Comment by DillonN** [comment]
Not every miner supports max temp settings, there is no global maximum you can set in NHML. Most GPUs however allow you to set a temp limit at the driver level, which may be preferable since it could handle dropping clocks more continuously (you can use a tool such as Afterburner to set this)

**Comment by kfadrat** [comment]
that's the issue. Right now i am mining on gtx 980, ewbf miner. The temp setting in afterburner is set to 75 but the temp is about 85 all the time. I tried to change it in miner setting. The gpu warms up at the same speed but worker just stops digging because the temp is too high. I tried changing intensity to lower but temperature still shoots up fast. Right now maxtemp in miner is set to 70 but the gpu temp is 85 all the time. Any ideas?

**Comment by kfadrat** [comment]
and interesting thing is, if i run miner.exe from bin_3rdparty folder, the temp is ok, the only problem is when i run it through NHML, so i assume there is some setting/file that NHML uses to run this miner that overrides the miner config file?

**Comment by DillonN** [comment]
@kfadrat I have noticed that some miners override the Afterburner settings, probably through how they access the NVIDIA APIs. If this occurs it usually doesn't go away after the miner closes. When you are trying using NHML, are there other miners being opened first? NHML also accesses the APIs, but only in for information. You could try a version before 1.8.1.0 to see if that regular accessing is what is causing the issue for you

**Comment by kfadrat** [comment]
@DillonN no miners before. Wierd thing is, some miners accept maxtemp or similiar settings, but for example ccminer doesn't. Ccminer on it's own doesn't have this problem. Either way i do most of mining on ewbf so it's not a huge issue
