### ISSUE TITLE
'Help' button localization variable is missing

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#40]
'Help' button localization variable is missing. It would be really nice if you add it into en.lang.
![image](https://user-images.githubusercontent.com/4707112/28244356-b5211f04-69f9-11e7-8a0d-a9eaadb8d929.png)

**Comment by DillonN** [comment]
Thanks, this is added now d1b549a0b959a655833ce91bb6b99ebe7b56747b
