### ISSUE TITLE
Unable to get NiceHash profitability data

### ISSUE THREAD

**Issue by utc99** [nicehash/NiceHashMiner#401]
This error, started to occur maybe a month ago or so and persists trough multiple versions. Old version gets this error -> update to new -> ok for some time -> then it starts. Sometimes it stays for a long time, sometimes it's gone by itself, yet most of the time it's gone after new NHML install so it's not that it always occurs when the server is down

If you close that error, you can start mining normally. 

If this error does not stop user from actually mining and geting BTC to the address. We need to be able to disable it, or it should inform in some other way than in error message, because it stops automining.
![nhbug1](https://user-images.githubusercontent.com/26816096/31268506-48258bde-aa85-11e7-8d23-229db8c53769.JPG)

! For some reason NHML 1.8.1.4 pre2 at the moment does not log anything for me even logs are enabled, tried reenable it, no use. Did not checked if this persists on other machines

**Comment by b0b5h4rp13** [comment]
I had to go back to 1.8.0.2 due to the SMA check hanging, you might try going back to that version too

**Comment by ghost** [comment]
Where can i get the old version ?
i am facing this issue too https://github.com/nicehash/NiceHashMiner/issues/1293.
Strange to me , it was all running for almost 3 week with NHML-1.8.1.3 and suddenly facing this error. 
All i knew was there was power outage in my area and system has been shut down abnormally . When the system is up running , NiceHash gets stuck at  "get the SMA information" and above error is displayed. ANd there is no issue with the internet. Also tried the workaround suggested, by disabling IP-v6 protocol. Still No luck. 
Tried to run with pre release NHML 1.8.1.4  same issue.

**Comment by b0b5h4rp13** [comment]
This happened to me recently again, about a week after I reinstalled
windows 10 (what a nightmare), it would hang on the SMA and then give me a
BSOD with a msg about a watchdog timer. Long story short, I removed the
Nvidia driver and reinstalled it..

To find older releases go to the current leggacy release on GitHub from the
nice yas download link and scroll down the page

**Comment by ghost** [comment]
bobsharpie,

A big thanks.. that certainly worked for me too... Looks like clear bug in the system which has not been fixed by nicehash team as promised.
As of now mining started peacefully. Meanwhile we might have to wait for the actual Fix.

Nice Hash Team, 
We know u guyz are working hard but this is something that keep bothering most of the users in the form.
Please get this fixed as early as possible.  

Meanwhile we are stuck in Old version, now  sure what we are missing compared to latest version.

**Comment by ghost** [comment]
This issue started once again with old 1.8.0.2 too . For one week it was working fine.
bobsharpie what about you ?... is it working fine ?

**Comment by bmazz731** [comment]
I have encountered this on 1.8.1.4 starting early this morning connecting to the US - San Jose server. When I connected to the EU - Amsterdan server I've been able to stay connected without issue. I assume there is something going on with the NH servers (could be a result of the recent demand increase)

It would be great if clients had a "primary" and "backup" server option so if it couldn't connect to the primary server to obtain pricing it could attempt to connect to the backup as opposed to completely halting mining.

**Comment by 6GPUDAVE** [comment]
Primary server getting overwhelmed?  Cannot connect at all on startup.

**Comment by Spritor** [comment]
Same issue :/ anyone found any solution to this ?

**Comment by 6GPUDAVE** [comment]
Out of pure frustration I deleted Nicehash Miner and all related files.  Re-downloaded, left all settings at default and initiated the most accurate benchmark.  Day 3 no issues.  While not willing to call that "the solution" it worked for me.

**Comment by Spritor** [comment]
well for me i am gonna go back to pool mining it seems.

**Comment by ghost** [comment]
Everything started working once again in version  v1.8.1.5. not sure if this issue is actually fixed by  the developers. Best of luck  guyz.

**Comment by Spritor** [comment]
it still same for me with v1.8.1.5 really sad donno what i should do :/

**Comment by Anonym35** [comment]
Why this issue isn't "enhancement" ststus? It's very important problem, i loss a lot of money, nicehash miner idle till press ok and press start mining. Why this stupid miner don't do it self? or why there is no settings to disable it stupid error window.

**Comment by 6GPUDAVE** [comment]
Since I deleted everything, re-downloaded and started completely over it has been working with no problems.  Leave all settings default and perform the most accurate benchmark. Click "start mining after benchmark" walk away and forget about it.

**Comment by Sav87** [comment]
add Pull request #625

**Comment by Mr-trololol** [comment]
same issue with prerelease , stable it happens after some time 
there must be option to continue mining even if it can't get data for profitability since your implementation sucks and i had a huge downtime due to this.

**Comment by mesouug** [comment]
This issue is related to cloudflare CDN. I found one small workaround. One can turn on VPN for example to another country. Start nicehash miner then disconnect from VPN. Nicehash miner will complain about interrupted connection and continues to mine. I'm getting this issue each time rig shuts down unexpectedly. If you check logs you can find that api.nicehash.com reply's with 503 error (Service Temporary Unavailable).

**Comment by xtrime-ru** [comment]
@Sav87 made few fixes, so NHML can use another way of getting SMA data if primary method fails. 
I've compiled his fixes and made this release:

https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases

**Comment by Mr-trololol** [comment]
i know that solution @mesouug but not good if you have alot of rigs and needs automation in case of power loss will try @xtrime-ru build and let you know thanks for help.

**Comment by Mr-trololol** [comment]
[2017-12-03 09:30:19] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:19] [INFO] [SOCKET] Attempting reconnect in 0 seconds
[2017-12-03 09:30:19] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:21] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:22] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:24] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:25] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:27] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:29] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:30] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:32] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:33] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:35] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:36] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:38] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:39] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:41] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:42] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:44] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:46] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:47] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:49] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-03 09:30:51] [INFO] [NICEHASH] Bitcoin rate get
[2017-12-03 09:30:51] [INFO] [NICEHASH] The remote server returned an error: (403) Forbidden.
[2017-12-03 09:30:51] [INFO] [ExchangeRateAPI] UpdateAPI got NULL
[2017-12-03 09:30:51] [INFO] [NICEHASH] Current Bitcoin rate: 0.00
[2017-12-03 09:30:51] [INFO] [NICEHASH] Setting environment variables
[2017-12-03 09:30:51] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
[2017-12-03 09:30:51] [INFO] [NICEHASH] Current DontShowUI value: 1







i get this all the time

**Comment by xtrime-ru** [comment]
@Mr-trololol Do you replaced 20 files in nhml folder with fixed ones from our release?

**Comment by mesouug** [comment]
I've created workaround script: https://github.com/mesouug/nhml_mon

**Comment by xtrime-ru** [comment]
@mesouug thsi is useless script, this behaviour can be achived with 2 options in official nhml: disable “autostart mining” and enable “start mining on idle”. With this options set program will start without errors and will try to start mining after no input from user in 60 sec (no mouse movements). When nhml will recieve data it will start mining automaticaly.
But sometimes in can took hours to get connection in official nhml.

**Comment by mesouug** [comment]
@xtrime-ru If I move mouse when "start mining on idle" it stops to mine. Usually it takes about 15 minutes to get connected. Once it's connected it works rather stable even if losts connection to api.nicehash.com. This workaround should help people who don't want to modify original nhml binary and waits for official release from nicehash team.

**Comment by Sav87** [comment]
"start mining on idle" disabled, only "autostart mining"

**Comment by mesouug** [comment]
@Sav87 Exactly.. All my rigs have following settings: "start mining on idle" disabled, only "autostart mining"
Thus in event of reboot (power loss) or manual restart of NHML it gets banned by cloudfront and doesn't start mining. That's why I wrote simple workaround. It's partially solves issue until your pull request will be merged to master and NH team will release new version of NHML.

**Comment by jesteroi** [comment]
I had issues with NHLM 1.8.1.8 not retrieving profitability data, I checked my network time sync and it was out by 1600ms.

I updated it a couple times so that is was within +/- 5ms and NHLM started working again with being able to retrieve the data.

Maybe it was a fluke, but NHLM is working for me again.

I used this: http://www.timesynctool.com/

**Comment by kostia-lev** [comment]
it has 'Show Internet Connection Warning' checkbox in settings, remove check and it will work

**Comment by Mr-trololol** [comment]
we don't use NICEHACK anymore!

Pleasure doing business with it already.
