### ISSUE TITLE
Nicehash software shows incorrect mined amount

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#402]
Hello Nicehash,

I am a Nicehash seller. Since a week or so, I started to encounter a problem, as it follows: the Nicehash software (Nicehash Legacu 1.8.1.3 shows me extremely low mining), however on the site appears a normal amount mined. I also use an app (Nicehash Monitor, on an Android phone) and the app also shows a normal mining.

Now what means normal mining and low mining. I have a rig equipped with 2 Nvidia 1080TI and a CPU AMD Ryzen 1800X. Normally I earn with this rig 3-4 Euro / day. On the site (if I click on "check my stats online" inside the software) it is shown an average of 4 - 4.x Euro/day. The app from my phone shows the same. This is the normal I should earn with my rig.

But however, the Nicehash Legacy miner shows most of time that I earn 0.1 - 0.8 Euro/day, a ridiculous amount for what I actually earn. The positive part os that my rig still mines the normal amount which it should mine. So it is just a problem with the amount displayed by the Nicehash Legacy miner. It would have been worst if indeed my rig would mine such a low amount. But I dont understand why this problem appeared.
I tried to install also the version 2.0, after I saw you recommend it for Nvidia cards. But this software shows also that ridiculous small amount of below 1 Euro/day.

I mention that I performed a benchmark on all algorythms, selecting the option "precise". I also have active the option "enable Nvidia P0 state". Besides these, I didn't perform any other modification inside the Nicehash software.

Can you please investigate this issue?

Thank you,

**Comment by DillonN** [comment]
That is interesting, although good to know the site is showing the higher value (trust the site's value more, that is what you will be paid on). Are you able to post your `'logs\log.txt` file? That would give me some information on what you are mining with and maybe show a problem.

**Comment by ghost** [comment]
Hello, I'll attach the log later in the evening, as I am not near the rig now. Thanks a lot for looking on my issue :)

**Comment by ghost** [comment]
Apparently the problem disappeared by itself. I'll close the ticket. In case it reappears, I'll reopen it. Thank you very much!
