### ISSUE TITLE
can you add XMR-Stack-AMD ? (for RX VEGA56/64, it's 1900h/s instead of 1200h/s of Claymore 10.2 or sgminer)

### ISSUE THREAD

**Issue by pducharme** [nicehash/NiceHashMiner#408]
Hi Dillon,

Can you add XMR-Stack-AMD 3rd party miner?  it is very efficient with newest RX VEGA card.  It need to support the "supplemental commands" in the GUI so we can tweak the Threads and Intensity.   Lots of VEGA owner are now able to achieve 1900-1950h/s on CryptoNight with this miner, by using 2 threads.  

Thanks !

**Comment by Buckthebarbarian** [comment]
I would also like to see this but it probably won't happen. You can already use xmr stack amd and mine to the nicehash stratum. The only problem is that setting up the miner when you have a rig with different cards is a pain in the ass

**Comment by DillonN** [comment]
@pducharme thanks for pointing out, I will look into it

**Comment by DillonN** [comment]
In 1.8.2.0-pre2
