### ISSUE TITLE
Add Neoscrypt to NHML build.

### ISSUE THREAD

**Issue by Horsetoothless** [nicehash/NiceHashMiner#409]
Can use sgminer to start it manually and it will show up on miner status page think it is showing up as very profitable on wattomine.com.  would be nice addition easy implantation.

**Comment by bruvv** [comment]
it's already added?

**Comment by b0b5h4rp13** [comment]
This is why I use the legacy miner, it has Zcash and NeoScypt

**Comment by Horsetoothless** [comment]
Neoscrypt needs to be added to bench mark section if it is there already
under what is it listed by?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Mystere** [comment]
It probably depends on your GPU.  Many of the miners are optimized for more advanced GPU's and don't show up for older ones.

**Comment by DillonN** [comment]
@Horsetoothless you are correct sgminer Neoscrypt is not enabled. It is definitely not profitable in my testing but I can enable it if you are finding it is more profitable. Which cards are you using where it is more profitable?
