### ISSUE TITLE
MSI GTX1080 Gaming X+ 11Gbps

### ISSUE THREAD

**Issue by Tick007** [nicehash/NiceHashMiner#410]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [ ] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by Tick007** [comment]
Hello!
By default MSI GTX1080 Gaming X+ 11Gbps card's memory operates at a standard frequency of 4500. If I, for example, run Furmark, the frequency automatically increases to 5500 - i.e. up to its nominal value of 11Gbps.
When i start mining with nicehash miner - frequincy doesn't change (that is not so bed like in ewbf 0.3.4b miner). 
When Í run the ewbf 0.3.4b miner, the frequency rises to this level (5500) only when I start and stop the mining for a couple of moments. So any memory overclocking in afterberner leads to increasing memory frequincy to 4500+1000+ overcloking value.  For example if I set +700 in afterburner, I get +1700 at start (and finish) moment. If card servives this moment, it works with +700 further.
So is it possible to make nicehash miner to make force this card to operate on 11Gbps (5500Mhz) by default ? Like Furmark do ?
I use version 2.0.1.2 .

**Comment by Sav87** [comment]
so what's the question?

**Comment by Tick007** [comment]
Question is here: https://github.com/nicehash/NiceHashMiner/issues/1299

**Comment by Sav87** [comment]
this problem is present in NiceHashMinerLegacy?

**Comment by Tick007** [comment]
I don't know. I use  version 2. That why I moved my question to appropriate chapter.
