### ISSUE TITLE
Please have an option to remove all human interaction with NHML

### ISSUE THREAD

**Issue by leftishness** [nicehash/NiceHashMiner#411]
I want my rigs to run automatically, unseen and unheard from. When you offer a warning to increase virtual memory size, I have to log into the computer remotely and click 'OK'. I do not have time to click on warnings and UAC notifications all day long. My uptime is a lot lower than what it could be if NHML didn't require human interaction every time it starts.

I'm trying to build a miner farm. If all I did is watch each individual rig all day every day just to click a warning or UAC alert, I would never get anything done.

Please remove the virtual memory warning (and anything else that requires interaction after initial configuration).

**Comment by sindeseed** [comment]
https://www.howtogeek.com/howto/windows-vista/disable-user-account-control-uac-the-easy-way-on-windows-vista/ Disable User Account Control this is a system settings, NHML doesn't send or control this.
Virtual Memory: http://www.makeuseof.com/tag/virtual-memory-low-heres-fix/
the size of swap file in individual disks is depends on your RAM size, but you can provide a choice to the system.
I hope this helped you

**Comment by leftishness** [comment]
The virtual memory warning is not a UAC warning (although that trick works great, despite trashing your system's security); it's part of NHML. Additionally, because I don't use these rigs for anything else, I set the virtual memory to the size of the entire hard drive even BEFORE I ever installed NHML. The warning persists because it's written into the program, which is why I've posted it here as a bug.

**Comment by bruvv** [comment]
Just disable driver warning

**Comment by leftishness** [comment]
nivong, I'm not sure what to make of your post. It's not even a complete sentence. No one on this thread has mentioned driver warnings. I really don't know what you're talking about. Sorry.

**Comment by bruvv** [comment]
Next time search before posting "bugs" this has been posted before and is not a bug.

**Comment by leftishness** [comment]
The easy way to communicate that would be with a link. If it's been posted before and other people are having this problem, then I'm right to "bitch about it" since the devs haven't done anything about it. 

Also, perhaps it's an issue of semantics since I'm not a coder but, in this sense, "bug" clearly means an aspect of the software that adversely affects its function. In this case, the adverse effect completely prevents the program from mining, which is exactly why the program was written in the first place. It is a bug in the sense that everything halts and nothing can move forward until a user discovers, usually hours after the fact, that the machine hasn't been working at all. To a non-coder that's about as close to "bug" as anyone would guess and, regardless of semantics, people can't use the software because of it. Don't know what else to call that. Sorry.

**Comment by ChriscomIT** [comment]
@UnderwearWarrior I finally tell it you clear again as much as possible. NO ONE here will help you with building your fishy botnet!!! There are workarounds for your "issues" (which are no issues) but find them for yourself, please. No one here wants to help you with your fishy "mining farm" (which makes no sense overall, as farm miners use 99.99% a single mining pool, not a hash power intermediary service/app).

BTW when you have a problem with the app or the developer's changes simply don't use it or even better make your own instead of playing the whining card if no one really wants to help you.

**Comment by bruvv** [comment]
And to add to this: https://github.com/nicehash/NiceHashMinerLegacy/search?q=virtual+memory&type=Issues&utf8=%E2%9C%93 
now please close it and stop humiliating yourself.
