### ISSUE TITLE
Какая версия программы не виснет после суток работы? 

### ISSUE THREAD

**Issue by Alexus6** [nicehash/NiceHashMiner#413]

**Comment by kabylike** [comment]
Всем работают очен хорошо. Проблем у тебя.

**Comment by adem4ik** [comment]
та, которую вы скачаете и протестируете, выбор обширен - https://github.com/nicehash/NiceHashMinerLegacy/releases

**Comment by Alexus6** [comment]
Пользуюсь 
NHML/1.8.1.3
NHML/1.8.1.4
А если проблема у меня то в чем может быть проблема?
Причём не отвечает именно программулина Найсхешовская.. Запущенные ею майнеры работают без проблем.

Win 7 х64. Работает на двух машинках. На одной rx 470, на другой gtx 980+gtx 970.
Файл подкачки увеличен. Дрова обновленные.

**Comment by DmitryDMR** [comment]
Пользуюсь
NHML/1.8.1.3
NHML/1.8.1.4
Все работает сутками. Пробуй разгон снизить

**Comment by alexandr-1** [comment]
Без разгона(

**Comment by Alexus6** [comment]
После суток работы программка "не отвечала".
Поставил NHML/1.8.1.4 - pre2. Вроде пока нормально..

**Comment by diablom** [comment]
NHML/1.8.1.3 was crashing for me.
NHML/1.8.1.4 pre2 works good for 3 days now.

Also try to disable CPU usage if the problem still remains. It helped me once.
