### ISSUE TITLE
NHML xmr stak cpu crashes with 0xc0000142 in NHML 1.8.1.3

### ISSUE THREAD

**Issue by B-R-Bender** [nicehash/NiceHashMiner#415]
I've update NHML to 1.8.1.3

now when I'm tying to start mining or even rerun a benchmark I'v got an error (screanshot attached)
is there a cure or a clue?

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1371939/log.txt)
![errScr](https://user-images.githubusercontent.com/16334107/31387752-322daf3a-add4-11e7-8a5c-909c545a9acb.png)

System Win 8.1 Corp

**Comment by DillonN** [comment]
Should work with xmr-stak in 1.8.2.0-pre2
