### ISSUE TITLE
Have 8 AMD cards and all show mining but not all active in Nicehash

### ISSUE THREAD

**Issue by valcalepi** [nicehash/NiceHashMiner#416]
Have 8 AMD cards and all show mining but not all active in Nicehash.
I have installed the recommended driver 15.12 from AMD. Hash rates all above 25.xx MH/s
AMD Radeon RX580 Armor OC Edition 8GB.  Biostar TB250-BTC Pro, Celeron G3930, 16GB memory.
I have another system mining with 2 Radeon RX580 Nitro + 8Gb and 4GB in nicehash I see 3 active miners.
So in other system with 8 GPU and one CPU mining shouldn't there be 9 active miners?

**Comment by valcalepi** [comment]
Should I use blockchain driver? I plan to add 4 nVidia cards to this rig for a total of 12.

**Comment by alexandr-1** [comment]
Тоже планирую собрать ригу на 12 картах (планируется поставить разномастные карты, которые удастся купить за адекватные деньги). Увижу ли я их все в NHML ?

**Comment by Sav87** [comment]
log file?

**Comment by DillonN** [comment]
@valcalepi could you clarify what you mean by not active in NiceHash? Do you mean on the miner stats website page you do not see all of your devices listed, or that in the NHML program GUI you do not see them? 

As @Sav87 said log files would help as well (\logs\log.txt)

**Comment by valcalepi** [comment]
Yes DillonN that is correct. How does it calculate and what makes something an "active" item?
I have one antminer and 24 GPUs in 2 other rigs in total so shouldn't it be 25 active workers?

**Comment by valcalepi** [comment]
I only see 1 rig today under NHML and usually there are 3 but all machines are mining.

**Comment by valcalepi** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1407255/log.txt)

**Comment by DillonN** [comment]
NHML is sending the correct data so this is not an issue for this forum
