### ISSUE TITLE
Multiple GPUs, on switch, card is sitting idle. 

### ISSUE THREAD

**Issue by laterbreh** [nicehash/NiceHashMiner#418]
Hello, 

I can't seem to find a thread that is closely related to the issue that I am having. I have a 2 GPU 1060 6GB mining rig, and version 1.7.5 (the first one i ever used) up to 1.8.1.4 has this issue. The application its self works great, but when switching to or from certain algorithms particularly Neoscript, X11Gost, and Dagger (includes hybrid mining), the cards will initialize, but card 1(0), will just sit idle as the second card chuggs along. I can fix this problem by literally just re-applying my after burner settings, and the first card will instantly begin hashing at full speed without issue. Then it will switch to kaccac and nist5 (dont have this problem) or equihash and both will initialize and hash at full speed without issue. 

I have confirmed this on Windows 7, and 10, with and without remote administration tools being active, power plans and other standard troubleshooting tips for mining rigs were also done to remove as much user/software/hardware error out of the equation before I posted this. 

This is mildly annoying as obviously we cannot sit at the machine and re-apply after burner when it switches to those algorithms or IF it does etc. I know i can just disable them, but I like having all my options open. 

I'm trying to make a connection here that switching to certain algorithms some of the gpu wont get initialized or hash in multi gpu set ups, but  by simply resting afterburner settings and hitting apply will fix the issue. 

Has anyone encountered this phenomena? I'm wondering if this is happening to other multi-gpu rig users. 

Is there a way to have nicehash re-apply overclocks between algorithm switches? I know that may be a band-aid on the problem, but it may be a real universal solution for the time being. 

I hope to hear your thoughts on this. 

Thank you.

**Comment by Sav87** [comment]
if after switching the algorithm the overclocking settings of the graphics cards are reset, then this is the video card driver crash and after the driver is restored by the system, the settings are reset.
