### ISSUE TITLE
Cannot set miner parameters (ethdcrminer64)

### ISSUE THREAD

**Issue by francescocmazza** [nicehash/NiceHashMiner#42]
Hello,
I want to optimize my rigs by setting some additional miner parameters. I am trying to edit miner parameters for ethdcrminer64 (daggerdecred). It seems that whatever I write in the parameters has no effect on the miner. I tried playing around with -powlim settings but nothing seems to happen. For trial purposes I also tried changing the -color 0 setting to just see if the miner was receiving the command, but nothing seems to change.
What can I do to check if NHML is forwarding the command to the miner? What could be the issue why NHML is not executing the extra commands?
Here are some of the extra commands I tried (one at a time)in the window for my trials:

-powlim -40
-powlim -50
--powlim -50
--powlim --50
-colors 0

None of the above cause any difference in performance. I guess I must be doing something wrong....
Thank you

**Comment by DillonN** [comment]
NHML has a set list of commands that it supports forwarding to the miner. I'm planning on making a wiki page for this to clear it up, but you can see what's supported for example in ClaymoreDual by opening the `\internals\MinerOptionPackage_ClaymoreDual.json` file.

Specifically for your examples, the proper syntax would be `-powlim 40`, and `-colors` is not supported.

**Comment by francescocmazza** [comment]
Hello DillonN,
Thank you for your kind and superfast reply. 
I saw the json file you pointed out. I am trying to imput a powerlimit of "-50". So my syntax should have been right:
"-powlim -50" 
But it doesn't yield any results. that's strange

**Comment by francescocmazza** [comment]
Ok, trying with -li 10 and it actually changes things. maybe my cards do not support power limiting? 
Thank you. I guess this is an issue with my hw more than an issue with NHML. 
Thanks againg and keep up the great work!
