### ISSUE TITLE
Max fan speed

### ISSUE THREAD

**Issue by diablom** [nicehash/NiceHashMiner#420]
I need to set my fan speeds at max 60%. Inside NML  settings > Devices algorithms I inserted:
-ttli 80 -fanmax 60

I did this for all GPUs (3) and all Claymore algorithms. Still, I get my temperatures at ~70 C and fan speed 70-80%.

I cannot set fan speed at driver level, because I do not have a monitor attached to the rig. Any help would be great. Thank you.

**Comment by DillonN** [comment]
@diablom are you using AMD cards or NVIDIA cards? Claymore does not support fan speed setting in NV cards (see [here](https://bitcointalk.org/index.php?topic=1433925.0) for Claymore's descriptions of the options)

Also make sure that "Disable AMD Temperature Control" is unchecked in settings (it is checked by default)

**Comment by diablom** [comment]
Thank you for a reply. I use AMD 470 and 570 cards. Unchecked AMD temperature controls. It worked for almost a day, but again some GPU fans are running 80-100%, even I set -ttli 80 -fanmax 60 and temperatures are not high.

**Comment by DillonN** [comment]
This is not something NHML can fix
