### ISSUE TITLE
DevFee:  Connection lost, retry in 20 sec... NHM1.8.1.4pre2

### ISSUE THREAD

**Issue by Paapo** [nicehash/NiceHashMiner#424]
Hello, I really Need some help. I´m running NHM 1.8.1.3 and also tried 1.8.1.4pre2, with Windows 10, 2 Rigs (6XAMD RX470), with Crimson 17.9.3, but i tried out other crimson Drivers too.
As you can see on the Picture, my rig is running table, withiout any jejected Shares. But i can´t get rid of this DevFee:  Connection lost, retry in 20 sec...
![connection](https://user-images.githubusercontent.com/27375501/31536092-bd9241f0-affd-11e7-8cec-321656de0ef5.JPG)

I´m having this issue every 10 minutes or so. Of Course the hashrate always droppes during the reconnection to the DevFee Server. I´ve seen this issue several times here, but i didn´t found a solution for it. It must have something to do with my Settings, because it doesn´t matter, witch Server i use, Amsterdam, or San Jose. The Issue is the same.

I´m using Fritz!Box 6490 Kable. IPv6 is disabled on both rigs. I tried to give them a fixed IP, without success. Is there something else i have to configure.
Sorry, for mistake in the Header. I don´t know wether it is a nhml issue, or an claymore issue. Or just an issue with my own PC.

Please help!!

Regards,
Paapo

**Comment by vinaybhushanj** [comment]
Dear.Goggle for some time,before I suggest you to restart and reinstall.It will be fixed.

**Comment by vinaybhushanj** [comment]
Dear.Goggle for some time,before I suggest you to restart and reinstall.It will be fixed.

**Comment by Paapo** [comment]
Oh Google... Come on.. I tried it with different search words, but i found no real solution.. Like here:
https://github.com/nicehash/NiceHashMiner/issues/889 
As i told you, i don´t know, f it is a nhm relased issue, or router issue. If you could help me out with the Keywords, that would be fine.
Reinstallation of NHM1.8.1.3 has been done, several times. With new Benchmark. But the issue stays.

Regards,
Paapo

**Comment by DillonN** [comment]
@Paapo could you try unzipping the attached file into the `internals` folder (overwriting), relaunching NHML, then adding the option `-allpools 1` to the extra launch parameters of Claymore Cryptonote?

This will let the miner connect to other pools for the devfee, which may fix your issue

[MinerOptionPackage_ClaymoreCryptoNight.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1383726/MinerOptionPackage_ClaymoreCryptoNight.zip)

**Comment by Paapo** [comment]
@DillonN 
That´s it. Unzipped the file to internals. Added -allpools 1 option and restartetd the miner. It is running since 60 minutes, without DevFee interruptions.  Thanks a lot for your help.
Do i have to install this package to all new releases? And is there a semilar package available for sgminer.
I´ve seen, i have the same issue with sgminer.

Regards,
Paapo
