### ISSUE TITLE
unable to allow nicehashlegacyminer.exe to run

### ISSUE THREAD

**Issue by gluckez** [nicehash/NiceHashMiner#426]
this probably has a few entries, i know... and this is probably rude, i know, but i don't have time atm...
been running nicehashlegacyminer for about a week now, but windows or my antivirus keeps blocking it. i'm now at the point where my antivirus, along with everything else responsible for my security, is turned all the way off, and somehow, it's still being blocked. now running 1.8.1.3, other versions don't work either.
Does anyone have a working method to "unblock" this? sometimes it seems to work for no reason... and then it's blocked again

**Comment by DillonN** [comment]
Hello @gluckez, what exactly is the error you're getting while trying to open? Does a popup from antivirus say it is blocking, or does NHML just fail to launch?

**Comment by Elias1286** [comment]
have same proble, the .exe simple don't start, i clic and nothing, already tag as exception on firewal, download the arquive 3 times from here and nothing.
