### ISSUE TITLE
Skip benchmark window alert

### ISSUE THREAD

**Issue by orokhovatskiy** [nicehash/NiceHashMiner#429]
Hello,

Could you please provide information how can I skip benchmark-window alert:
![teamviewer_2017-10-14_13-08-19](https://user-images.githubusercontent.com/23494254/31574855-0ec836a4-b0e1-11e7-9a6c-656c9bf51732.png)

Sometimes my farms going to reboot and because of this window showing nicehash couldn't automatically start

This window shows because NHML could find a new one alghoritm
![teamviewer_2017-10-14_13-12-34](https://user-images.githubusercontent.com/23494254/31574870-75fef664-b0e1-11e7-85db-7ea71e125298.png)

NHML v1.8.1.4-Pre2

**Comment by DillonN** [comment]
You have to disable (uncheck) the algorithms that don't have speeds, from your screenshot it looks like there is at least one in your second P106

**Comment by orokhovatskiy** [comment]
DillonN hello,

Thx for reply! Problem that sometimes this problem could appear on different alghoritms. Is it possible to set automaticall apply benchmark and autostart mining?

**Comment by DillonN** [comment]
@mrsanchos once you benchmark an algorithm once it should never revert to non-benchmarked, so if you run the benchmark now and everything enabled comes up with a speed then the prompt should never pop up again. 

However yes this option could be implemented

**Comment by orokhovatskiy** [comment]
@DillonN ok, thanks!
