### ISSUE TITLE
NHML 1.8.1.4pre3 no Benchmark possible. Cards are showing only 20% of its performance

### ISSUE THREAD

**Issue by Paapo** [nicehash/NiceHashMiner#431]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1384758/log.txt)
Hi,
after we have gotten my nhml 1.8.1..3 to run, i tried to use the new pre3 release of 1.8.1.4.
As before in pre2, my AMD Sapphire RX470 Cards (Modded) are benchmarked with only 10-20% of their normal performance. Usually my rx470 have 700h/s, benchmark is showing for all cards between 40h/s and 160h/s. So, i tried to copy over the config folder from Pre2 and started the miner with Claymore CryptoNight. 1 card shows 620h/s, then 3 cards 0h/s, then 2 other with 70h/s. It looks like the cards are frequently on and off. The Main Window og Nicehashminer ist showing a speed jumping between 1250h/s and 4050h/s (what would be my normal speed). I switched back to 1.8.1.3 now.

Please find attached my logfile.

In the meanwhile i played around a little bid. Only Claymore CryptoNight isn´t working for my AMD Cards. All other miners are working well, more or less;-) 

Regards,
Paapo

**Comment by DillonN** [comment]
Thanks for posting @Paapo, I'll look into it. In the meantime, I noticed you have either the `-h` or `-a` extra launch parameters set in your testing, could you try without either of them? I believe `-h` optimal value has changed with the new version of Claymore Cryptonote, and the `-a` value is no longer a launch value at all (I still have to update NHML to reflect that)

**Comment by Paapo** [comment]
@DillonN Yes, you are right. The -a option was copied over from the previous version. But i have removed it already and tried to benchmark cryptonight again. But there was no change. exactly the same result. But Version 1.8.1.3 really great now. Great work for me..
Thanks,

Regards,
Paapo
