### ISSUE TITLE
Feature Request: NiceHashMiner stats from multiple rigs

### ISSUE THREAD

**Issue by zeuz542** [nicehash/NiceHashMiner#432]
Would it be possible to implement a feature to collect data from multiple computers to a single nicehashminer instance ? Like you are able to do with Awesome Miner. 

I feel the home page is not very good at detecting dead miners and I often miss em unless I rdp to each computer and check nicehash miner there.

**Comment by DillonN** [comment]
This is not currently planned but it is an interesting idea

For now you can use the [Worker Monitor](https://www.nicehash.com/help/workers-monitoring) service from NiceHash which can send you an email if some worker is offline for a set period of time (note you must be using a NiceHash account address to set it up)

**Comment by S74nk0** [comment]
This issue will be resolved with [new platform ](https://www.nicehash.com/news/important-transition-to-a-new-nicehash-platform) on the web and it is already resolved with the current latest release of the client.

Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

We will be working on a complete GUI re-design.
