### ISSUE TITLE
Antminer S7

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner#433]
hello , my antminer s7  keeps showing in the stats web page as  only up for  like a few minutes at a time 

![image](https://user-images.githubusercontent.com/9946471/31585716-73f7d39e-b1be-11e7-8b96-a5d8d0f72d80.png)

in the miner webpage it shows up for a few days , but i would like help to understand why nicehash website keeps saying it is down and only up for a few min 

![image](https://user-images.githubusercontent.com/9946471/31585723-8d26fb2e-b1be-11e7-8d70-8d415f98abb3.png)

![image](https://user-images.githubusercontent.com/9946471/31585727-a6d4cb78-b1be-11e7-9699-1a9f98a64a4b.png)

**Comment by MACE-Zer0** [comment]
If my speed is not being accepted into my user who am i mining for ???

**Comment by MACE-Zer0** [comment]
![image](https://user-images.githubusercontent.com/9946471/31586167-6937d88a-b1c5-11e7-86da-405299e9778e.png)
