### ISSUE TITLE
Unable to set time unit

### ISSUE THREAD

**Issue by riccardoruspoli** [nicehash/NiceHashMiner#435]
On **NHML 1.8.1.4-Pre3**:

1. Open NHML and go to settings
2. Change the current time unit to any other one
3. **Save and exit**

It worked the first time after seven attempts.

The temporary fix I found is to open NHML/configs/General.json and change "TimeUnit" to a number from 0 to 4.

**Comment by DillonN** [comment]
Should be fixed
