### ISSUE TITLE
Nicehash doesn't open, and the application vanishes from the file.

### ISSUE THREAD

**Issue by Antho132** [nicehash/NiceHashMiner#436]
Okay, so I extract the file, and when I click on the miner application, The application vanishes after a few seconds. The main problem; I can't open it. No error message. nothing. Am I missing a file? Is my hardware incompatible?

**Comment by riccardoruspoli** [comment]
You have to add the .exe as an exception into your antivirus

**Comment by ghost** [comment]
Set exclusion in the anti-virus / windows defender.
