### ISSUE TITLE
Miner GUI cut off if Resolution is too low V1.8.1.3

### ISSUE THREAD

**Issue by kryptekk** [nicehash/NiceHashMiner#438]
Happening with previous version too running V1.8.0.2 and the current version of 1.8.1.3.
There is a problem with the GUI, when the resolution ist too low.
All Twelve of my Machines, i only get 640x480 after a reboot and the miner window is cut off.  The Buttons are working because you can tab around but they are not visible.
![screenshot 2017-10-16 10 33 30](https://user-images.githubusercontent.com/29381338/31617574-88b19532-b25d-11e7-9698-8f4d7c42529c.png)

**Comment by DillonN** [comment]
Thanks for posting, I will look into it
