### ISSUE TITLE
Nicehash closes during benchmark

### ISSUE THREAD

**Issue by Antho132** [nicehash/NiceHashMiner#439]
When benchmarking my GPU and CPU, the miner simply crashed my PC. I restarted it, and now to just closes itself. 
Edit: I've just reinstalled it, and The miner doesn't even get finished downloading, it closes after abt. one minute.

**Comment by DillonN** [comment]
@Antho132 could you post your logs\log.txt file please?

**Comment by smygarn** [comment]
Same happened on two of my computers. Also Windows 10 Antivirus remove some files inside the app folder?
