### ISSUE TITLE
Mining not profitable does not update

### ISSUE THREAD

**Issue by francescocmazza** [nicehash/NiceHashMiner#44]
Hello,
With the current drop of eth and btc prices I use the minimum mining profitability on several rigs that are on 24/7. If the mining profitability goes below the minimum setting the rigs shutdown correctly and NHML displays the related message. If time passes and the profitability goes up again the program does not resume work unless I manually stop the mining process (that is not running due to minimum profitability) and press start again.
Is it possible to add a feature where NHML every now and then updates its profitability values and reruns the mining profitability check?

Thank you very much.
Francesco

**Comment by DillonN** [comment]
Thanks for reporting this, there seems to have been a bug where it wasn't recalculating profitability under certain conditions. It should be fixed now as of 8f48b13

**Comment by francescocmazza** [comment]
Hello. Thank you very much DillonN, should I replace some file in the program to get this fix applied?
Thank you

**Comment by DillonN** [comment]
The best option is to wait for the next update (shouldn't be long now)

**Comment by francescocmazza** [comment]
Ok thanks!
