### ISSUE TITLE
graphic drivers problem

### ISSUE THREAD

**Issue by michall0** [nicehash/NiceHashMiner#440]
Any ideas how fix them ? before when i update graphic drivers all was fine..
http://piclair.com/data/ob8ie.jpg

**Comment by kezdarkriser** [comment]
same updated to 16.12.1 the other day and not been paid for daggerhashimoto , mining and submitting buton website not being picked up or getting paid

**Comment by S74nk0** [comment]
This **BUG** (it does not affect mining) has been [resolved](https://github.com/nicehash/NiceHashMiner/commit/9e61ee5e93f673aa8ab89f497360222dfba71246). The next version will have this fix included.
