### ISSUE TITLE
GTX 750 Ti can mine Neoscrypt but GTX 770 cant?

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#440]
There is not really any extra info I can give, the Neoscrypt miner shows for the GTX 750 Ti in the list but it doesnt for the 770.

**Comment by riccardoruspoli** [comment]
As you can see on [this](https://en.wikipedia.org/wiki/CUDA#GPUs_supported) page, GTX 750 Ti uses Compute 5.0, while GTX 770 uses Compute 3.0.

NeoScrypt requires a Compute 3.5 or above to work.

**Comment by DillonN** [comment]
Yes @Rikifire is correct, 750 Ti is Maxwell 1 while 770 is the (older) Kepler architecture so it does not have the same compute capability
