### ISSUE TITLE
Xeon 2650 + not work bench

### ISSUE THREAD

**Issue by redboxstudio** [nicehash/NiceHashMiner#442]
The cryptonight benchmark does not pass on xeon 2650 or higher. The write is canceled or interrupted on any version above 1.7.3.3. We have to use it but it is not stable constantly falling off. What has changed, is it possible to return the working capacity of these processors to new versions? accurate processor model intel64 family 6 model 79 stepping 0 genuineint el or genium inte r cpu 0000 2.2 mhz

**Comment by DillonN** [comment]
@redboxstudio are you able to run the miner manually? You can set any speed for the CPU in the settings and NHML will launch it, if you do this does the miner window show abnormalities?

**Comment by redboxstudio** [comment]
I have not manually started the .bat manually, and I did not know the speed that the processor produces and thought if I specify it will limit it or indicate it can be any and it will still work on the one that can?

**Comment by redboxstudio** [comment]
manual insertion of speed does not give anything, when you click the stratum starts very quickly open and close the script window

**Comment by DillonN** [comment]
@redboxstudio could you post your logs\log.txt file please?

**Comment by redboxstudio** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1397251/log.txt)
 logs

**Comment by DillonN** [comment]
It does look as though the miner is crashing as soon as it is being started. Can you verify that xmr-stak-cpu.exe is located in the folder \bin\xmr-stak-cpu? There may be log files in there from during the benchmark as well, which could elucidate why it is closing (like most miners, if there is some error on launch it will not stay open and show you, so you have to check the logs). If you are not able to launch xmr-stak-cpu properly on its own (just by double-clicking the exe) then that would indicate some problem with the miner running on your PC

You can also try the new 1.8.1.4 pre-release 3, it includes Xmrig, an alternative to xmr-stak-cpu
