### ISSUE TITLE
Add dstm’s ZCash Nvidia Miner

### ISSUE THREAD

**Issue by GuillaumeASSIER** [nicehash/NiceHashMiner#445]
Hi devs,
Can you add dstm's ZCash Nvidia Miner to the 3rd party miner please.
This is the fastest miner for equihash.
https://bitcointalk.org/index.php?topic=2021765.0

**Comment by Rama-Nujan** [comment]
I second this.

**Comment by DillonN** [comment]
Thanks for posting, I'll look into it

**Comment by DFNCTSC** [comment]
@DillonN it's been almost three weeks, any update? i'd like to switch back over to using nicehash soon and give you guys my hashpower instead of flypool. :)

**Comment by CreamyG31337** [comment]
Please try to add this miner -- it's updated fairly frequently and I haven't had any stability issues with it. Should be faster for most if not all users, which is kinda why we are running NHML!

**Comment by pojik7** [comment]
I want this miner. Pleeease

**Comment by kaos-1** [comment]
@DillonN Any update on dstm miner for legacy?
