### ISSUE TITLE
A lot of reports of 1.8.1.3 not working correctly on NiceHash reddit

### ISSUE THREAD

**Issue by Mystere** [nicehash/NiceHashMiner#446]
This is not really a report, more like a heads up to @DillonN 

There have been a lot of reports lately of problems with 1.8.1.3, ranging from USD/day not displaying (while mBTC does) to 0Mh/s being displayed, to devices not found...  Please check out the reddit

**Comment by DillonN** [comment]
Thanks for the heads up!
