### ISSUE TITLE
AMD GPU's indexed wrong

### ISSUE THREAD

**Issue by artgri** [nicehash/NiceHashMiner#45]
According to Claymore's Dual Ethereum AMD GPU Miner v9.6 release notes:
new GPU sorting method for AMD cards. Now GPUs are sorted by physical bus index (it matches AfterBurner list of GPUs). Also the list of temperatures/fans matches the list of GPUs automatically.
Therefore "-di detect" and "-gmap" options are not necessary and not supported anymore.
WARNING: be careful if you use use separate overclock/temperature settings for every card, due to new sorting method GPUs can get different indexes!

This leads to the wrong card beeing mined on when Claymore's miner is used.

**Comment by DillonN** [comment]
Thanks for reporting this, this is now fixed as of aae0263

**Comment by DillonN** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.0.1
