### ISSUE TITLE
xmr-stak-cpu: use optimal settings

### ISSUE THREAD

**Issue by MaKCuMyC** [nicehash/NiceHashMiner#451]
Hello!
I am using NHML 1.8.1.3 for now. And I am confused why NHML doesn't use optimal settings for xmr-stak-cpu.
On my Core i7-3770K at 4.3GHz with Nicehash settings I got about 320 H/s, but with manual config with `"no_prefetch" : true`
I got about 355 H/s.
Also the problem is that NHML write own new config every time at launch, so you can't edit it.

**Comment by bonifacio123** [comment]
One work-around I use is to modify the config file manually and then set the file as read-only which prevents NHML from overwriting.

**Comment by MaKCuMyC** [comment]
Of course I tried that, but you see, in this way NHML doesn't show the speed of miner.

**Comment by DillonN** [comment]
Thanks for posting @MaKCuMyC, I will look into making no_prefetch an option configurable through the extra launch parameters

**Comment by MaKCuMyC** [comment]
This will be good. Will wait for that.

23 Окт 2017 г. 1:35 пользователь "Dillon Newell" <notifications@github.com>
написал:

**Comment by HaTaX2** [comment]
If you set config.txt to read only and still want to see the speed in the GUI, just check the config file to see what port is specified at the bottom of the file and enter that port in MinerReservedPorts.json.

**Comment by DillonN** [comment]
This is implemented in xmr-stak in 1.8.2.0-pre2
