### ISSUE TITLE
reject or not support more than 60 cores

### ISSUE THREAD

**Issue by xtrojan1** [nicehash/NiceHashMiner#452]
regards, i get problem, i use x3850 x5 system, i use 4x cpu xeon e7-4850, on nicehash 1.8.1.4 Pre-release3 reject or not support more than 60 cores, please help, and please solve it

thank you very much

**Comment by DillonN** [comment]
NHML currently does not support more than 64 threads, I can look into adding an advanced manual override that will let you try to use it if you like

**Comment by xtrojan1** [comment]
Mr. DillonN, how to do it !, can you give the stages, please help, and please solve it

thank you very much

**Comment by angel12** [comment]
Any update on this? I have 4 e7-4860 cpu's on one machine that I would like to use for mining :) Total of 80 threads, 40 cores

**Comment by phant** [comment]
Any update on this?
2x E5-2697 - 72 vCPU...

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

This issue is resolved with the latest release.
