### ISSUE TITLE
setting up mieners

### ISSUE THREAD

**Issue by michall0** [nicehash/NiceHashMiner#452]
When i open nicehash miner i choose language and have this problem http://piclair.com/data/unwgy.jpg at this moment program stay always and i cant do nothing, any ideas ?

**Comment by S74nk0** [comment]
If you are getting this download [bin.zip](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/bin_1_7_3_10.zip) and unzip it manually. Please send the log file to see where it is breaking. If you are using anti virus software they might be flagging the mining software (**false positive**)

**Comment by michall0** [comment]
ok i fix it, just start **as administrator** 😠 😆

**Comment by S74nk0** [comment]
This is a user permission issue then. When copied to special folders (like **Program files**) it might not work due to user write permissions, so make sure it is located somewhere where your windows user has write permissions.
Closing issue...
