### ISSUE TITLE
Question about excavator

### ISSUE THREAD

**Issue by Rama-Nujan** [nicehash/NiceHashMiner#453]
Hello, I have a question about excavator in this version.  Is there a plan to run the latest versions in this and also, does the profitability calculation account for the no fees?

Am not sure if this is right place pleaseclose or move

**Comment by mcsjohn** [comment]
As part of NHML we get v1.1.4, while it looks that there are much newer versions. Latest (not necessarily the best) seems to be v1.3.3 (https://github.com/nicehash/excavator/releases). @DillonN Maybe you can integrate one of the newer versions in the future. Thanks

**Comment by DillonN** [comment]
There is currently not a plan to add in the newer excavator versions, in an effort to keep NHMv2 free from antivirus detection

Yes when you benchmark a miner like EWBF the fees are taken into consideration
