### ISSUE TITLE
CPU mining problem

### ISSUE THREAD

**Issue by michall0** [nicehash/NiceHashMiner#453]
GPU work great but CPU have bug, how i can fix it ?
![otzxf](https://cloud.githubusercontent.com/assets/24512026/21162134/15b3a65a-c18c-11e6-9a1f-8b68c4a93f0f.jpg)

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
