### ISSUE TITLE
1.8.1.4-Pre2 Slightly inflated profitability and balance values

### ISSUE THREAD

**Issue by jace7t** [nicehash/NiceHashMiner#456]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1404044/log.txt)

I got on my computer at 14:21 (GMT +3) and noticed the issue

![unknown](https://user-images.githubusercontent.com/25679006/31851321-205b7c60-b66c-11e7-9e45-6ea363c9cf1a.png)

When the miner switched algorithms, this happened:
![screenshot_3](https://user-images.githubusercontent.com/25679006/31851323-264c9c76-b66c-11e7-890c-16b3ee6c3f14.png)

As It does not seem I'm becoming a billionaire any time soon, I've elected to report this bug.

**Comment by jace7t** [comment]
Couple of hours later:
![screenshot_4](https://user-images.githubusercontent.com/25679006/31852264-8960b3b8-b67d-11e7-8344-db35d075c098.png)

Updated log file: 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1404147/log.txt)

**Comment by luongk** [comment]
It's not a NHML bug, there was something hinky going on with the servers - the website was reporting similar hugely inflated  figures for me + my friends.

**Comment by drkskwlkr** [comment]
Definitely not an issue with NHML, it is a problem with the service. Same weird numbers are visible on the NH website and via 3rd party monitor apps that use the API. Until they fix it, you can try & get used to how the future will look like :)

**Comment by DillonN** [comment]
Yes it was a problem with the API server exchange rate, when in doubt look at the mBTC/Day metric as this is wholly calculated in the client
