### ISSUE TITLE
can't mine ethereum and dual etehereum mining

### ISSUE THREAD

**Issue by malakakgp** [nicehash/NiceHashMiner#457]
Hello I have this problem 
Socket was closed remotely (by pool)
Socket was closed remotely (by pool)
ETH: Job timeout, disconnect, retry in 20 sec...
 LBC: Job timeout, disconnect, retry in 20 sec...

why does this error occur 
I tried every  service location my firewall close and other algos work fine. claymore eth and dual eth not work

**Comment by DillonN** [comment]
Are you able to mine eth with a non-Claymore miner? And are you using any VPN or using a company/university network?

**Comment by malakakgp** [comment]
recently I mine with nicehash miner I don't use VPN , company/university network I use a dongle
