### ISSUE TITLE
Cannot benchmark ATI FirePro V5900. 

### ISSUE THREAD

**Issue by Poi159** [nicehash/NiceHashMiner#459]
Hello, 

I cant seem to pass the benchmark for my ATI FirePro V5900. I have two of them installed. I tried running one. Still wont work.
I attached a screenshot. I am using NiceHash Miner Legacy V1.8.1.3 stable.
Logs attached as well.

![capture](https://user-images.githubusercontent.com/24907195/31856101-5ce35aa2-b66e-11e7-96bb-1ffb8e6e0264.JPG)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1404467/log.txt)

**Comment by DillonN** [comment]
Being an older card, your V5900 will not be able to use every algorithm. For consumer cards there is an effort made to exclude unsupported algorithms from the list, but unfortunately most workstation cards are not tested on which they can support. You will simply have to disable the benchmarks that fail (as that would indicate it is one optimized for newer AMD cards)
