### ISSUE TITLE
Spelling inconsistency - NiceHash Miner Legacy or NiceHashMinerLegacy?

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#46]
Walking across the language files I've noticed that there are 2 different spellings used for the program name:
- NiceHash Miner Legacy
- NiceHashMinerLegacy 

So I just want to clarify which one of them is legit and should be used globally?

**Comment by ChriscomIT** [comment]
Yes, that would be great for me too as I am planning to do an English -> German translation and maybe others. I recognized this as well in the language files. 

Thanks in advance!

**Comment by DillonN** [comment]
In general, the two can be interchangeable as there are some situations where not having spaces is helpful (for coding reasons). I don't want to say that NiceHashMinerLegacy is the "non-legit" way, but for proper display the most used version should be with spaces, i.e. NiceHash Miner Legacy. I've been planning on going through the translation files and updating to this
