### ISSUE TITLE
Unhandled Exception Occured: Out of memory .

### ISSUE THREAD

**Issue by bxyoung** [nicehash/NiceHashMiner#461]
NHML-1.8.1.3
Windows 10
NVIDIA GTX 1080
i7-4790 CPU @ 4.00Ghz
16GB RAM

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1405375/log.txt)

Form_Loading
---------------------------------
Unhandled exception: Out of memory .

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

[exception_text.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1405378/exception_text.txt)
---------------------------------

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1405376/log.txt)

![nhml-error](https://user-images.githubusercontent.com/967989/31866676-09712e38-b751-11e7-9c67-0c245bd65591.PNG)

**Comment by DillonN** [comment]
@bxyoung there seems to be a problem with your WMI service, could you try restarting it? You can do this by opening Task Manager, going to Services tab, finding the service named Winmgmt, right click then hit Restart

**Comment by bxyoung** [comment]
No luck so far. I've restarted the service and all of it's dependencies and also rebooted the computer.

**Comment by bxyoung** [comment]
I'm sure they are designed completely differently but NiceHash Miner 2 runs on my machine no problem.

**Comment by DillonN** [comment]
Unfortunately without a major overhaul to NHML it relies on proper WMI connection
