### ISSUE TITLE
Nice hash wont respond when mining from sleep 

### ISSUE THREAD

**Issue by protossdisaster** [nicehash/NiceHashMiner#464]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [ ] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by DillonN** [comment]
@protossdisaster what do you mean by "mining from sleep"? Mining starting while idle?

Also you need to post your log file as mentioned in the template
