### ISSUE TITLE
Mining software additions

### ISSUE THREAD

**Issue by Rama-Nujan** [nicehash/NiceHashMiner#465]
Me again,

I noticed you have ccminer-nanashi at version 1.7.6. The 2.2mod3 version provides cuda 9 assembly and very good Lyra2REv2 performance.

Also, ccminer 2.2.2 is out.

Also, ccminer krnlx fork for SkunkHash may be faster than ccminer 2.2 and can also do xevan.

**Comment by DillonN** [comment]
Thanks for posting, I will look into updating

**Comment by niknewb** [comment]
@DillonN may that be the cause of low  Lyra2REv2 I'm getting with NHML? It is at least 10 mh\s slower than in NHM2

**Comment by TheSorrow1** [comment]
I can also add that there is a new version of claymores ETH miner, you may add it to NHML, DillonN!

**Comment by DillonN** [comment]
@niknewb NHM2 has better Lyra2REv2 right now but we can't use the new version of Excavator it uses. Hopefully ccminer updates will close the gap

@TheSorrow1 thanks for the heads up!
