### ISSUE TITLE
"не удается получить данные прибыльности..."

### ISSUE THREAD

**Issue by MSLord** [nicehash/NiceHashMiner#466]
Приветствую!
у меня 2 компа с W10, карточки 1050ti и 1080ti
сегодня после перезагрузке стала выскакивать ошибка "не удается получить данные прибыльности..."
как решить проблему?

**Comment by vladymy** [comment]
+1

**Comment by adem4ik** [comment]
Просто следите за новостями и вопросов будет меньше:
https://twitter.com/NiceHashMining/status/922724172232560640
https://vk.com/nicehashmining?w=wall-88552836_106622

I think this thread can be closed.

**Comment by protoss5482** [comment]
Сегодня 3 раза словил это диалог... ферма автоматически перезагружается если карта вылетает, а узнаю о диалоге через несколько часов по факту нулевой добычи :(

**Comment by isazon4ik** [comment]
+1, have this problem on all rigs

**Comment by MSLord** [comment]
служба поддержки отписалась что это проблемы с их стороны были но они все устранили. поначалу я запускал форму с интернета сотика а потом переводил на инет от провайдера. сей час проблема ушла и инет все время от провайдера. ни какие таблички не выскакивают. удачи в борьбе!


>Среда,  8 ноября 2017, 16:39 +03:00 от Mikhail <notifications@github.com>:
>
>Сегодня 3 раза словил это диалог... ферма автоматически перезагружается если карта вылетает, а узнаю о диалоге через несколько часов по факту нулевой добычи :(
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Приветствую!


С уважением,
и пожеланиями хорошего настроения
Силин Андрей

**Comment by protoss5482** [comment]
Час назад словил 2 раза... с 8.11 это окно появляется в 100% случаях... у меня настроена автозагрузка через батник (использую 3 недели) в котором я пингую 8.8.8.8 10 раз по завершению запускается NiceHash и появляется окно "не удается получить данные прибыльности". 
Пинги проходят успешно на 100%, значит проблемы в доступе к интернету явно нет.

**Comment by klamas1** [comment]
Тоже такая проблема и все бы ничего, если сообщение о не удачном получении данных прибыльности не было блокирующим, выскакивает ночью и ждет меня до утра, ну зачем??

**Comment by MSLord** [comment]
Попробуй обнови найсхеш. Вышел новый
--
Отправлено из Mail.Ru для Android вторник, 14 ноября 2017г., 08:10 +03:00 от klamas1  notifications@github.com :

**Comment by Ajivitca** [comment]
Реально надоело непонимание рпзработчиков о том, что nice запускают на автомате 99%. И что просто жизненно необходимо убрать ВСЕ блокирующие надписи и сделать их информационными. Плюс сделать авто повторение через n секунд. Если из за не получения курсов есть проблема - указываем для каждой карточки свой алгоритм по-умолчанию.

Сейчас сам из-за этой проблемы просто запускаю zec в паралель на пуле. Т.к. задрало видеть висящий найс с какой либо очередной табличкой.

Рпзработчики найса думаю, лишились многих пользователей именно из-зс этих табличек.

**Comment by klamas1** [comment]
> Если из за не получения курсов есть проблема - указываем для каждой карточки свой алгоритм по-умолчанию

да проще - не смогли обновить, пользуемся старыми значениями.

**Comment by klamas1** [comment]
На новой версии такая же фигня(

![На новой версии](http://joxi.ru/D2Py7L6fd4lwBA.png)

**Comment by justice47** [comment]
Подтверждаю, аналогичная проблема. Час назад всё работало.

**Comment by miv63** [comment]
когда вы вы все наладите ... чтобы люди не мучились  задолбали ....

**Comment by Ajivitca** [comment]
Наблюдаю у себя - уже с неделю найс висит с чудо табличкой о курсах. Zec в паралели уже неделю как пашет в одиночку на пуле.  Найс теряет деньги - а пофиг им похоже.

**Comment by klamas1** [comment]
@adem4ik появилось понимание о чем именно этот таск?
Вопрос не в недоступнсти, а в том что вы прогу блокируете при этом, вместо повторных попыток.
Работы проводите поздно вечером или ночью, и майнинг потом до утра стоит, пока ОК не нажмешь, ну бредовая логика же, разве нет?

**Comment by miv63** [comment]
читал в гугле что надо поставить поставить какие-то корневые сертификаты для windows 10 , и проблема пропадет . А как их поставить не знаю

**Comment by garishulc** [comment]
![default](https://user-images.githubusercontent.com/33732793/32912329-c3fe650e-cb1f-11e7-9602-8e4d877d3470.png)
вот такая проблемма что делать?

**Comment by Sav87** [comment]
Проблема возникает из-за того что с первой попытки соединение не устанавливается, поэтому данные которые нужны будут через n-секунд непоступают. Это все блокируется окном Сообщения. Для решения проблемы: переписать алгоритм авто-старта, блокирующее сообщения изменить на сообщения с таймером либо убрать.

**Comment by garishulc** [comment]
Sav87 а как это сделать? Какой файл переписывать?

**Comment by Sav87** [comment]
Это надо код программы менять. Если конкретно то Form_Main.cs и другие. Есть другое решение написать скрипт на AutoIt, который будет кнопки в программе нажимать .

**Comment by garishulc** [comment]
Подскажи а мне что делать?

**Comment by levantez** [comment]
Жесть какая! последние дней 10 очень много нервов сожрала эта проблема.... Неужели правда нельзя сделать повтор попыток через несколько секунд? Я в этом окне нажимаю ок - старт потом не нажимается, тут же закрываю и открываю программу и все нормально работает.... Видел в гугле что надо IP v 6 отключить - не помогло... Про сертификаты читал - тоже не понял как их и откуда ставить.... Кароче жесть...

**Comment by levantez** [comment]
короче надоело это все, написал скрипт на php который проверяет по адресу кошелька , есть ли действующие воркеры, если нет на протяжении 3 проверок - убиваем процесс и запускаем заного, если опять не пошел майнинг - опять перезапускаем, если 3 раза не помогло - ребут компа... сегодня первая ночь которая отработала без пробелов в графике

**Comment by Sav87** [comment]
add Pull request #625

**Comment by klamas1** [comment]
Наконец-то!

**Comment by dobrMAN** [comment]
Та же проблема, в ВК ни каких новостей о работах.

**Comment by TheGrr** [comment]
Помогает отключение IPv6

**Comment by klamas1** [comment]
Глупости

![Нифига](http://joxi.ru/p27EwPgS06Pxlr.png)

**Comment by levantez** [comment]
Вот мое решение которое перезапускает найсхеш - если тот не майнит, может кому-то пожет

запускать как-то C:\php\php.exe C:\path\to\script.php

`<?php

$wallet = 'номер_кошелька_куда_майните';  

$wait = 50;

$url = "https://api.nicehash.com/api?method=stats.provider.workers&addr=".$wallet;

$file = 'trying_false.dat';

$f = fopen($file,'w');
fclose($f);

check:

$result = json_decode(file_get_contents($url));

if (!$result) {
	echo 'can not get info, sleep 5 sec';
	flush();
	sleep(5);
	goto check;
}



if (!$result->result->workers) {
	
	
	$f = fopen($file,'r+');
	$count = (int) fread($f,100);
	
	//$count++;
	$count = $count +1;
	
	echo 'it is try number '.$count."\r\n";
	flush();
	
	if (($count % 3) == 0) {
	
		system('taskkill /f /im NiceHashMinerLegacy.exe');
		
		//$count = 0;
		
		echo 'Process killed sleep'."\r\n";
		flush();
		
		sleep($wait);
		$proc = popen ('start C:/path/to/NHML/NiceHashMinerLegacy.exe','r');
		pclose($proc);
		echo 'process started, sleep and check'."\r\n";
		flush();
		
		sleep($wait);
		
	} else {
		sleep($wait);
	}
	
	if ($count > 9) {
		echo 'bye bye , reboot'."\r\n";
		system('shutdown /r /f /t 00');
	}
	
	ftruncate($f,0); // очистка файла
	fseek($f,0,SEEK_SET); // указатель в начало файла 
	fwrite($f,$count);
	fclose($f);
	goto check;
	
} else {
	
	$f = fopen($file,'w');
	fclose($f);
	
	echo 'its okay'."\r\n";
	flush();
	sleep($wait);
	goto check;
}`

**Comment by protoss5482** [comment]
Опять эта проблема на последней стабильной.. только что скачал последнюю pre2 и там такая же проблема...

**Comment by klamas1** [comment]
Эта проблема и не исправлялась в релизах, пулреквест #625 не принят еще

**Comment by Sav87** [comment]
Добавил запасной способ получения sma

**Comment by xtrime-ru** [comment]
@klamas1 Пока не выпустили официальный релиз я скомпилировал исправления от @Sav87 

https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases

**Comment by klamas1** [comment]
@xtrime-ru  Молодец! но сыкотно) Пока просто клеймором майнится, дождусь релиза.
Коллегам майнерам надо помнить, что вы можете пользоваться сторонними сборками на свой страх и риск.

**Comment by xtrime-ru** [comment]
Я сегодня ночью запустил ewbf + xmr-stack-cpu на dwarfpool... Вспомнил молодость, обплевался на ужасный UI и отсутсвие данных по прибыльности, вывод на кучу кошельков в разных валютах хрен знает когда и вернулся на NHML :)

**Comment by DimNS** [comment]
Сейчас комп надо было перезагрузить, включаю обратно и на тебе, ну что за дела, мы за что комиссию платим?

**Comment by xtrime-ru** [comment]
@DimNS проблема с исправленной версией или из оффициального репозитория?

Обновление протокола связи не очень удачно прошло у nicehash в прошлом месяце, от ошибок никто не застрахован.

А комиссия сейчас смешная — 2% всего. Вывести с обычного пула и сконвертировать в btc дороже будет. А у nicehash еще и во многих майнерах dev fee 0%

**Comment by DimNS** [comment]
@xtrime-ru из официальной репы, последняя версия pre2 которая. Комиссия смешная или нет, но это оплата за программу, понятно что обычный пул сложнее, но сейчас вот настраиваю autominer на пули nicehash он будет сам смотреть профит на WhatToMine и переключать майнеры настроенные на Nicehash, по сути тоже самое что и найсхешевская программа но без этой вечно не работающей оценки прибыльности.

**Comment by xtrime-ru** [comment]
Ну sma мы починили. Все работает без проблем, ссылка выше.

А у меня что то так и не получилось запустить ewbf отдельно и настроить его на пулы найсхеша, хотя может с пулами что то было. Откуда настройки берете? Просто из батников из bin копируете? Адреса там верные? Намайненое будет учитываться на балансе nicehash?

**Comment by DimNS** [comment]
@xtrime-ru настройки сам собирал используя хелпы самих майнеров, что там собирать юзер это кошелек. пароль это х и адрес пула с сайта найса, проверил equihash через ewbf сайт найса показывает, гуд, сейчас запустил ccminer для NeoScrypt вот жду появления статистики на сайте, если все гуд, запущу уже сам autominer пусть работает

UPD: все гуд, автомайнер завелся и определил NeoScrypt лучшим и запустил соответствующий майнер, наблюдаю за изменением баланса на сайте найса

UPD2: баланс на сайте увеличивается, так что можно юзать autominer пока ждем официального релиза с фиксом )

**Comment by xtrime-ru** [comment]
@DimNS Спасибо за наводку на autominer, не знал про него. 

Сейчас прошерстил логи Nicehash - там тоже есть параметры запуска майнеров (По крайней мере для ewbf), user это биткоин кошелек, все верно. 

Хорошее решение.
