### ISSUE TITLE
1.8.1.4-Pre3 release notes - "enable huge pages"?

### ISSUE THREAD

**Issue by malventano** [nicehash/NiceHashMiner#468]
"For best performance enable huge pages"

'enable huge pages' is a link that points to the wiki, but nothing there about huge pages?

**Comment by riccardoruspoli** [comment]
This is the correct link

https://github.com/nicehash/NiceHashMinerLegacy/wiki/CPU-Mining-Optimization

**Comment by DillonN** [comment]
Thanks, the link was moved and I have updated the release page now
