### ISSUE TITLE
Feature request: Start miner windows minimized

### ISSUE THREAD

**Issue by mtone** [nicehash/NiceHashMiner#47]
Would be nice to avoid getting those popups while working or watching videos.

Is an option a possibility? Would something like Start /MIN break communication with the process?

**Comment by ChriscomIT** [comment]
It's already in the options. Look at the settings for "Hide Mining Windows". Have fun!

**Comment by mtone** [comment]
Ah, didn't see that. Thanks!

**Comment by ChriscomIT** [comment]
No problemo.
