### ISSUE TITLE
NEOSCRYPT

### ISSUE THREAD

**Issue by gennadiv** [nicehash/NiceHashMiner#470]
ждём исправления для neoscrypt когда будет возможность её добычи и переключения для последних карт или новых драйверов (блокчейн)

**Comment by adem4ik** [comment]
1) Разработчик англоговорящий, потому он вашей проблемы не поймёт
2) Вы не указали ни версии программы, ни своего железа, ни прочей полезной в этом случае инфы
3) В последнем v1.8.1.4-pre3 на GTX1060 NeoScrypt прекрасно фармится

I think this thread can be closed, as topic starter doesn't care about giving proper information about his problem nor follow any common rules about posting issues.

**Comment by DillonN** [comment]
It would seem to be in regards to Neoscrypt recently being activated on sgminer in 1.8.1.4-Pre3

Neoscrypt is not compatible with all cards but was enabled by request in issue #409 

I will make it disabled by default in next build

**Comment by gennadiv** [comment]
what drivers are you using for the extraction neoscrypt I have 10 wines on 64 wood blockchain not working writes LLVM ERROR:

**Comment by guni7789** [comment]
Здравствуйте, последние два дня при использование алгоритма Неоскрипт у меня вылазит ошибка и процесс майнинга останавливается до перезагрузки компьютера

ccminer 2.2 for nVidia GPUs by tpruvot@github *** 
Built with VC++ 2013 and nVidia CUDA SDK 8.0 64-bits 

Originally based on Christian Buchner and Christian H. project 
Include some algos from alexis78, djm34, sp, tsiv and klausT. 

BTC donation address: 1AJdfCpLWPNoAMDfHF1wD5y8VgKSSTHxPo (tpruvot) 

![l-6fww05ib4](https://user-images.githubusercontent.com/33147327/32093119-a446a44e-bb14-11e7-9c03-da88b0b7e8f7.jpg)
