### ISSUE TITLE
Blue screen occur during benchmark

### ISSUE THREAD

**Issue by lowleopard** [nicehash/NiceHashMiner#471]
I try to benchmark graphic card AMD HD 7700 series on ( DaggerHashimoto, CrytoNight and Equihash algorithms), every times it turns blue screen of death.  The others algorithms passed the benchmark. How to solve this problem? My PC is 64-bit window 7. I am using NHML 1.8.1.2 LangFix.
There are two log files exist, so i will provide both.
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1413219/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1413220/log.txt)

**Comment by b0b5h4rp13** [comment]
I'll bet it says DPC_Watchdog_Violation on the BSOD. When that happened to me on my nvidia 1070, I had to reinstall the video card drivers.

**Comment by bruvv** [comment]
having the same issue, reinstalling windows or video card drivers doesn't work. my pci-e risers are toasted...

**Comment by DillonN** [comment]
Aside from hardware problems others have mentioned, would you happen to be using RDP to monitor your rig? Some of the algorithms you mentioned can BSOD when using RDP

Either way this indicates a problem with the miner/hardware and can't be fixed from within NHML
