### ISSUE TITLE
[UI/Ux] Add option to disable Virtual Memory warning

### ISSUE THREAD

**Issue by chillware** [nicehash/NiceHashMiner#472]
Hello, can you please add an option to disable and/or not show again the virtual memory warning? Right now, using 1.8.1.4_pre3, with the reboot script enabled after the system reboots, my rig just sits at this prompt  until i can click OK. This is frustrating when a reboot happens in the middle of the night and the rig is down all night.

My rig is running 6x 1080ti's w/ 11gb each on a 32gb SSD, so there is no way for me to increase the virtual memory to anything recommended. I have not seen any issues with not having enough virtual memory either.

Thank you!

**Comment by bruvv** [comment]
Disable driver warning message.

**Comment by chillware** [comment]
That worked, thank you! Can this be clarified in the option that is also has this effect? Thanks!

**Comment by DillonN** [comment]
I will look into making it in the option description (I'll mark this as enhancement for now)
