### ISSUE TITLE
ZM cuda miner for Equihash is 10% faster than EWBF. Please implicit it into nicehash.

### ISSUE THREAD

**Issue by Virtuon** [nicehash/NiceHashMiner#473]
Here:
https://bitcointalk.org/index.php?topic=2021765.760

**Comment by DillonN** [comment]
Thanks for the heads up, I'll look into it

**Comment by VParhom** [comment]
to Virtuon: EWBF 450sol/s in the stock without overclocking on 1070
in OC mode 485-500 sol/s
ZM is not faster than EWBF on 1070

**Comment by brainbudt** [comment]
some people are saying that this isn't true. that the concole is saying that there are more ol/s then it's actually is. this was tested for like 8-10 hours

**Comment by Virtuon** [comment]
Well if it's opensource it can be tested. My 1060 mine 295-300 on ZM and 265-270 on EWBF. Nominally there is a significant difference. If it's just written false hashrate then it's just a scam miner.

**Comment by DFNCTSC** [comment]
@brainbudt @Virtuon All you have to do is see how many hashes are reaching the pool. dstm has a 2% devfee and all hashes reported are real -- just test it yourself.

@VParhom I also have a 1070, a NVIDIA Founder's Edition, and I get 450sol/s in EWBF and 470 sol/s in dstm.

**Comment by ghost** [comment]
Just find this awesome miner, it´s much faster than other nvidia/cuda miners. In ewbf miner I did only get ~550-600 Sol/s. 

![1080_ti_ext](https://user-images.githubusercontent.com/34748899/34266390-9229064c-e681-11e7-9b56-66849963abc2.JPG)
![zm_mining-3](https://user-images.githubusercontent.com/34748899/34266399-974b998c-e681-11e7-9284-16e0424887b2.JPG)

**Comment by myfingerhurt** [comment]
@Jukni Would like to see when you set the Sol/W to 4.00, then how it will look.
In my region, the cost of electricity is 0.31 usd/KWh

```
#  zm 0.5.7
#  GPU0 + GeForce GTX 1080 Ti      MB: 11264 PCI: 1:0
#  GPU1 + GeForce GTX 1080 Ti      MB: 11264 PCI: 5:0

#  telemetry server started
#  connected to: asia.equihash-hub.miningpoolhub.com:17023
#  server set difficulty to: 0001e03004cd47ba70000000...
>  GPU0  54C  Sol/s: 670.4  Sol/W: 4.15  Avg: 670.4  I/s: 359.7  Sh: 3.00   1.00 22  +
>  GPU1  56C  Sol/s: 665.9  Sol/W: 4.15  Avg: 665.9  I/s: 353.1  Sh: 0.00   . .
   ========== Sol/s: 1336.3 Sol/W: 4.15  Avg: 1336.3 I/s: 712.8  Sh: 3.00   1.00 22
>  GPU0  55C  Sol/s: 667.6  Sol/W: 4.16  Avg: 669.0  I/s: 359.8  Sh: 3.00   1.00 24  +
>  GPU1  57C  Sol/s: 654.3  Sol/W: 4.09  Avg: 660.1  I/s: 351.3  Sh: 0.00   . .
   ========== Sol/s: 1321.9 Sol/W: 4.12  Avg: 1329.1 I/s: 711.2  Sh: 3.00   1.00 24
   GPU0  56C  Sol/s: 664.9  Sol/W: 4.14  Avg: 667.6  I/s: 359.3  Sh: 2.00   1.00 24
   GPU1  57C  Sol/s: 645.6  Sol/W: 4.06  Avg: 655.2  I/s: 351.1  Sh: 0.00   . .   *
   ========== Sol/s: 1310.5 Sol/W: 4.10  Avg: 1322.9 I/s: 710.4  Sh: 2.00   1.00 24
   GPU0  56C  Sol/s: 672.8  Sol/W: 4.15  Avg: 668.9  I/s: 360.1  Sh: 1.50   1.00 24
   GPU1  58C  Sol/s: 654.2  Sol/W: 4.06  Avg: 655.0  I/s: 350.7  Sh: 0.75   1.00 25  +
   ========== Sol/s: 1327.0 Sol/W: 4.10  Avg: 1323.9 I/s: 710.8  Sh: 2.25   1.00 24
>  GPU0  57C  Sol/s: 680.9  Sol/W: 4.16  Avg: 671.3  I/s: 359.8  Sh: 1.20   1.00 24
>  GPU1  58C  Sol/s: 635.8  Sol/W: 4.04  Avg: 651.1  I/s: 350.3  Sh: 0.60   1.00 25
   ========== Sol/s: 1316.7 Sol/W: 4.10  Avg: 1322.5 I/s: 710.1  Sh: 1.80   1.00 24
>  GPU0  57C  Sol/s: 670.5  Sol/W: 4.15  Avg: 671.2  I/s: 358.7  Sh: 2.00   1.00 24  ++
>  GPU1  58C  Sol/s: 659.5  Sol/W: 4.04  Avg: 652.5  I/s: 350.3  Sh: 0.50   1.00 25
   ========== Sol/s: 1329.9 Sol/W: 4.10  Avg: 1323.7 I/s: 709.0  Sh: 2.49   1.00 24
   GPU0  57C  Sol/s: 664.9  Sol/W: 4.15  Avg: 670.3  I/s: 358.7  Sh: 2.56   1.00 23  ++
   GPU1  59C  Sol/s: 658.7  Sol/W: 4.05  Avg: 653.4  I/s: 349.6  Sh: 0.43   1.00 25
   ========== Sol/s: 1323.6 Sol/W: 4.10  Avg: 1323.7 I/s: 708.3  Sh: 2.99   1.00 24
>  GPU0  57C  Sol/s: 661.8  Sol/W: 4.14  Avg: 669.2  I/s: 358.4  Sh: 2.62   1.00 23  +
>  GPU1  59C  Sol/s: 652.6  Sol/W: 4.05  Avg: 653.3  I/s: 350.0  Sh: 0.37   1.00 25
   ========== Sol/s: 1314.4 Sol/W: 4.09  Avg: 1322.5 I/s: 708.4  Sh: 2.99   1.00 24
```

**Comment by PeeJay** [comment]
@myfingerhurt What clock speeds and power setting do you use to get 4 Sol/W ?

**Comment by joseortiz3** [comment]
You guys have to be careful when your using closed-source software to verify the hashrates reported in the console. For instance, bminer has been shown to inflate its reported hashrate by 5-10%. Can you imagine in the code (which we can't see) something like `reported_hashrate = hashrate * 1.05` !! The only way to get a good measurement is...wait, how do you get a good measurement? Oh this was discussed already...

I guess no harm in mentioning it twice.

**Comment by DillonN** [comment]
dtsm seems to be a better alternative
