### ISSUE TITLE
NHML1.8.1.3 still loosing connection to DEV Fee Server frequently--

### ISSUE THREAD

**Issue by Paapo** [nicehash/NiceHashMiner#476]
Hi, i thought the issue has been fixed, with the changes made in the MinerOptionPackage_ClaymoreCryptoNight.json. But unfortunately my rigs are still loosing the connection to the DEV Fee Server. Doesn´t matter wich dev fee server is active.
NHML 1.8.1.4 isn´t working in any way on may rigs. There seems to be something wrong, with the AMD GPU setup. Neither benchmark is working for all cards, nor mining with the old configfile from NHML 1.8.1.3 is working. 

The logfile is from NHML1.8.1.3

Help would be wonderful..

Best Regards,
Paapo
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1418921/log.txt)

**Comment by DillonN** [comment]
@Paapo your log file does not go back far enough to show the start of mining, could you stop/start mining then upload the log file then so I can make sure the correct parameters are being passed for miner startup?

Aside from that, there is not much that can be done from within NHML. Connection drops can happen from an unstable/over-secured network - you can try troubleshooting from that direction (disabling firewall temporarily, trying on a different internet connection if you are behind a company/university firewall)

**Comment by Paapo** [comment]
Uaahhh, sorry for the late replay. I´ve stopped and restarted. Please find attached the loffile.

I´m wondering, why neither NHLM1.8.1.4, nore NHML1.8.2.0 with newest Claymore CryptoNight isn´t working for me:-(
What can i do, to benchmark my AMD RX470 Cards? With Claymore CryptoNight 9.7 everything is perfect. From V1.8.1.4 on my cards are always switching on and of, during the benchmark. And the results that are shown, are much to slow. Once i start mining cryptonight anyway, some cards are not starting and some are showing perhaps 20% of their normal speed. So, is there a way, to get my GPUs benchmarked, with the latest versions?

In the meanwhile, i have also disabled firewall. It is always the same. changes seems to have fixed the issue and after 12 hour of working, it again begins to disconnecting from the devfee server..
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1427148/log.txt)

Regards,
Paapo

**Comment by imrecsoka** [comment]
I have the same issue, 9.7 doesnt connect to the dev fee server
Version 10.x is all rubbish for me i dont get full speed on cryptonight mining.

**Comment by DillonN** [comment]
Old claymore is included now since new one caused many problems
