### ISSUE TITLE
Dual-mining causing restarts randomly

### ISSUE THREAD

**Issue by kryptoteket** [nicehash/NiceHashMiner#477]
Running 3 rigs.

5 x RX570 nitro+ 4GB (141 mhs ETH)
5 x RX580 4GB (144 mhs ETH)
3 x RX580 4GB (84 mhs ETH)

Running on NiceHash miner, but everyday one of the rigs restart. somtimes all rigs, but its very random.
I think this is caused by the dual-mining in NiceHash. 

After restart i just login and restart miner and everything works fine until next restart happens.
As i wrote; the restarts are very random - so i never know when... 

Now i have turn off all dual-miners, and its allready looking better. Is this the solution, or is there something else i can do?

**Comment by DillonN** [comment]
@kryptoteket, dual mining can cause a much larger stress in terms of power on the system - can you make sure your cards are getting enough power and that the PSU isn't overloaded/shutting down? You could probably try this by disabling a few cards for a bit and see if you still have the problem

**Comment by kryptoteket** [comment]
After disabling dual-mining i thought the problem was solved - but one of my rigs went down this night too. 

Its only 5 GPU's on 1300 W EVGA psu, so it should not be a PSU issue. Only thing i can think of is to split the riser power connections on more cables from psu. Currently 2 cards pr. cable..? 

BTW: Same error in windows log this time: 

0x000000ea (0xffff838848187080, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000). Dump ble lagret i: C:\WINDOWS\MEMORY.DMP. Rapport-ID: c97a126f-e120-4be6-8516-c4147c4d9975.

**Comment by DillonN** [comment]
It's either a hardware issue or the cause of another known issue that's being worked on, I'll close to reduce clutter
