### ISSUE TITLE
CryptoNight miner for RX Vega GPUs

### ISSUE THREAD

**Issue by BaalMarduk** [nicehash/NiceHashMiner#478]
Hi,  you guys should look at this new Monero XMR miner.  

Cast XMR

http://www.gandalph3000.com/cast_xmr/cast-xmr-optimized-cryptonight-miner-for-rx-vega/

On Vega 64 it mine at an hashrate of 2050 per Vega GPU.

**Comment by Buckthebarbarian** [comment]
Can you mine with it on the nicehash stratum?

**Comment by BaalMarduk** [comment]
Yes, I just tried and it worked!

![untitled picture](https://user-images.githubusercontent.com/31890680/32081846-ba19ae54-ba85-11e7-8ae8-780c7b879530.png)

**Comment by Buckthebarbarian** [comment]
I get an error for the blockchain driver, I suppose it is because I have nvidia and amd gpu's. The hashrate does seem very strong!

**Comment by BaalMarduk** [comment]
If you run both Nvidia and AMD you need to do this

cast_xmr-vega -S cryptonight.usa.nicehash.com:3355 -u walletadresse.rigname -I 9 --opencl 2 -G 0,1,2,3

make sure to reset (toggle on/off or change memory size) your HBBC memory on the blockchain driver to activate the full potential of the cards when you reboot rig

**Comment by DillonN** [comment]
@Jonbros01 thanks for the heads up on the miner. We are currently looking at some new miners for Vega cryptonight mining, are you able to check if you get a better speed with this or [Xmr-Stak-AMD](https://github.com/fireice-uk/xmr-stak-amd). There is a nicely detailed guide on optimizing it for Vega on reddit [here](https://www.reddit.com/r/MoneroMining/comments/74hjqn/monero_and_vega_the_definitive_guide/)

**Comment by Buckthebarbarian** [comment]
@Jonbros01 I tried it with your setting and I get selected OpenCL platform index 2 dosn't exist. What kind of rig are you running? 
@DillonN I think the hashrates are pretty similar except that castXMR has a larger devfee

**Comment by BaalMarduk** [comment]
I was using XMR Stak before,  Cast XMR got slightly better performance, About 50h/s.   

1)  it's easier to setup, you don't need to set 2 thread per GPU with different intensities. 
2)  Stak xmr crash radeon drivers when you close the terminal, you need to reboot rig.   Cast XMR dosent have this issue

**Comment by BaalMarduk** [comment]
@buckthebarbarian try different values for the --opencl (0,1,2,3..) it's not always the same value depending the system...

**Comment by streaml1ne555** [comment]
Has XMR-Stak-AMD updated with NiceHash support? Their most recent release on github doesn't appear to work with every result rejected. Cast XMR does work nicely however. I've got it running on my Vega 56-Flashed64 And it's been solid for 4 or 5 days now.

**Comment by BaalMarduk** [comment]
Cast got updated yesterday, slightly better performance.  I using Cast on nicehash since a couple and got very good results.  The only thing is you need to use the beta Blockchain drivers.   I wished the new AMD 17.10.2 would had performed well on XMR Cast as they now do with Ethereum Claymore.

**Comment by HansHagberg** [comment]
Tried for a day or so to get XMR Cast to work on a rig with two Vega 64 and one Vega 56.
No luck with this...
AMD blockchain driver causes a world of trouble and I only got 1 GPU working with XMR Cast.
Current status is XMR cast won't recognize the blockchain driver is installed with more than one GPU in my rig. The miner gives no clue to what it thinks it finds instead so it's hard to troubleshoot.
Also, I never got past 1900 hashrate on one Vega 64.

If my experience is any indication, there would be one million support requests if XMR Cast was integrated into NHML in it's current status.

**Comment by BaalMarduk** [comment]
@HansHagberg In general AMD drivers are not the most stable especially with VEGA,  you need to use DDU to remove the old drivers before installing new ones.

**Comment by HansHagberg** [comment]
I'm pretty sure the drivers are installed correctly. I got it working with one card.
However, XMR Cast says the blockchain driver is not installed when I switch on more GPUs and so the performance is very low. 
I have no problems with other types of mining so there is something weird going on.
Would be great if XMR Cast was a little more verbose during start-up and dumped whatever it saw in the console. Then we could troubleshoot.

**Comment by foxocs** [comment]
Works fine with normal pools, but i have a problem with nicehash. Card recieve job but no share accepted. None of 3rd party  miners works. Is there a problem with nicehash pools? Only original nicehash miner (sg miner)  works fine...

**Comment by GenesisGupta** [comment]
Cast XMR is working with Nicehash , but it is only showing 1 kh/s for 1 vega card ( rx vega 56) whereas cast xmr is showing 1.99 kh/s when mining ? what is the problem ?

**Comment by GenesisGupta** [comment]
Cast XMR is working with nicehash , but it constantly shows 1 Kh/s for 1 card ( RX Vega 56) whereas Cast XMR shows 1.99 kh/s constantly. How can this be solved , i currently have no rejected shares.

**Comment by streaml1ne555** [comment]
You mean the website shows 1kh/s vs the software which shows 1.99kh/s?

**Comment by GenesisGupta** [comment]
Yes. XMR-stak-Amd is talking about supporting Nicehash in their new release . lets see.

**Comment by BaalMarduk** [comment]
If you see half the hash rate its probably you didnt reset the HBCC memory on each GPU after you reboot.  unfortunately you have to do this every single time other the compute mode for the card dosent seem to activate on the beta blockchain drivers.

**Comment by GenesisGupta** [comment]
It is showing 1.99 kh/s on cast-xmr and it is running absolutely fine. Only Nicehash keeps fluctuating between 1 kh/s to 4 kh/s which i have heard is the case. So i believe that cast-xmr is currently doing a good job of extracting performance from vega and porting to nicehash

**Comment by streaml1ne555** [comment]
Yep, Cast is the fastest at the moment. Also for anyone running two+ Vega's, you need to run multiple instances of Cast XMR targeted at single GPU's. There appears to be a bug when you tell it to use two GPU's from one instance. I've got 2 Flashed-to-64 Vega 56's running at 1900 kh/s this way.

**Comment by BaalMarduk** [comment]
I got 2 rigs of 4 Vega 64 and Cast use all my GPU.  You simply need to identify all of them in the command line

**Comment by streaml1ne555** [comment]
Crashes here when I run them both from one command.

**Comment by BaalMarduk** [comment]
here is my command with 4 Vega GPU:
cast_xmr-vega -S yourpool:port -u yourwallet -G 0,1,2,3 --opencl 0  -I 9

i got over 8160 h/s

**Comment by streaml1ne555** [comment]
Yep, same command except --opencl 1 because I have an iGPU as well, and -G 0,1 crashes here. I can run both separately with -G 0 and -G 1 in two command windows and it's fine though. Probably some cast bug with more than one opencl domain.

**Comment by imrecsoka** [comment]
Hi , silly guy here, but tell me, Do i need to download the blockchain drivers in order to unlock the speed potential with my RX470. I know the Gandalph site says u need to download them , but i thought i would take a chance without installing. I saw bugger all hash rate improvement, it was the same as CryptonoteMiner by claymore.
Question remains?

**Comment by BaalMarduk** [comment]
AMD Vega is the real beast for Cryptonight...  So to achieve the performance we are talking here you need Blockchain drivers, Vega and Cast XMR

**Comment by imrecsoka** [comment]
I tried to clean install my drivers , the august 23 block chain drivers and flip sake man, i dont know, but i start any miner now sgminer claymore cast xmr and it just exists , the dos window opens and then they just close... something is not kosher.Is there something particular i need to do with the blackchain drivers? i mean anything else to install or whatever. I am sad now , really.
I have 3 RX470 cards and all i am trying to do is get more than 1900 hashes / second. I would just accept anything higher than that , like if i can get 2000 ill be happy. Then i saw this cast xmr and i was still only getting 1900 same as the cryptonote claymore miner. I did run an AMD cleanup driver utility and then i installed the blockchain driver set after reboot, then it rebooted and then i have this nonsense where every miner just doesnt start.... so to me there is something not right with the way the drivers are installed.

**Comment by BaalMarduk** [comment]
Yes Beta Blockchain are flaky to get properly installed, especially if you previously have latest official drivers.   Few tips that helped me to install them properly:  1) uninstall using AMD remote tool,  2) reboot in Safe mode and run DDU, 3) install Beta Blockchain drivers.  repeat that sequence if needed...  sometimes it work on first try sometimes you need to do it twice.

**Comment by imrecsoka** [comment]
Wait, to clarify , what do you mean by latest official drivers. I just use for example, 16.11.1 
Then do i install blockchain 23 august over this? and the thing is what do i select, it has this funny stuff that new users or regular users wold not undertsand. 
like local driver, latest driver, recommende driver i mean its stpid and ridiculous, Nvidia didnt have any of this bullshit.
so i am just clarifying.
I can run the AMD Cleanup utility , safe mode or normal mode?
Reboot, then safe mode or normal model - then run DDU also
Then i Reboot in to normal mode?
Then in normal mode i install ONLY the blockchain drivers?
I would just need to clarify what i select when i install the blockchain driver.... just go with express or custom..... but the thing is i still dont know what the hell to click on ... it shows u like blocks where it says Local/ Recommended / something like that
such a frustration ... and this is probably where everybody gets it wrong.

**Comment by Parja** [comment]
imrecsoka, this should work:
Uninstall current drivers
Run AMD Clean Uninstall Utility
Boot into Safe Mode and run DDU
Reboot into normal mode and install Blockchain Driver (express is fine)

**Comment by BaalMarduk** [comment]
Also I noticed that on some motherboards the PCI-E need to be set at GEN 1 otherwise I cant install drivers.

**Comment by imrecsoka** [comment]
@Parja , when i install with express, then do i need to select a particular option, im sure it says local driver or recommended or something.

@Jonbros01  Sounds great, but how do you do what you are saying?

**Comment by BaalMarduk** [comment]
@imrecsoka Its settings you set for each PCIE slot in the motherboard bios.

**Comment by imrecsoka** [comment]
Oh okay , cool , so in the bios.
But wait, doesnt it make it slower or something strange

**Comment by MSukharev** [comment]
I'v use cast-xmr-vega ver 0.6 with two Vega-56 on Nicehash from command shell and get 1950 H/s from each. In this rig there are two GTX 1060 and it make troubles to start Vega's because of uncertain card numbers. But trying different numbers you can find right and run miner.  Miner work relatively stable sometimes falling speed to 1600; then you need to set card off and on in device manager.
Speed is good enough to use it.

**Comment by mrkukov** [comment]
I have been using this version 0.6 with one Vega56. 
Getting ~1995H/s when running 1500MHz/1090MHz. This should be definitely added to nicehash... or add option to add it manually. Now Using GUI to run CPU and .bat to run GPU.

If I'm using the system to browse web when mining, then I'll get graphic errors. It's not the miners fault, it's the high settings and low GPU-memory.

**Comment by cryptotech407** [comment]
Trying to run Cast XMR with 3 XFX RX 580 OC Black Edition cards and when I launch it, it just exits with no output.  Here are my parameters

cast_xmr-vega -S cryptonight.usa.nicehash.com:3355 -u 3NKrnuvKvK4BJS9sqpAFCsLtATuP13camx.Ed-XMR -G 0,1,2 --opencl 0 -I 9

**Comment by imrecsoka** [comment]
I tried to install those blockchain drivers, but the dam miners start and then just exit. Its ridiculous.
Which or what are the correct blockchain drivers to install here?
But really now, ihave clean installed using DDU and AMD CLeanup utility and its all just rubbish , i have tried this with 1 graphics card even and i have tested nicehashminer / multipool miner and smart miner command line cgminer bfgminer sgminer and claymore and they start , show the devices and then the miners just quit. I dont get this.
Do i need to be Chinese to do this?
My wife is Filipina so i hope that counts.
I heard there are 2 blockchain driver versions and the one is better to install.
I only see 23rd August blockchain though.
Im not rich thats for sure, and we live on one salary, if you can help me i can do my best to contribute with mining for x amount of time.

**Comment by CreamyG31337** [comment]
I'm surprised this isn't added yet. It's very easy to configure and use. It just needs to be restarted sometimes because the hash rate drops due to system activity that causes the the mining threads to lag a bit which messes up the way they're supposed to be synchronized. I just set it to restart every hour or so and never worry about that.

**Comment by imrecsoka** [comment]
@CreamyG31337  Oh you mean why cast xmr is not added to nhm. yeh.
Anyways as i said, i cant use mine properly, i get the same hash rate as sgminer.
I need help with somebody maybe on teamview or something to please get my blackchain drivers working.

**Comment by sqlpanda** [comment]
HI, I get CL_DEVICE_NOT_FOUND error. any idea ?

thanks

**Comment by CreamyG31337** [comment]
if you have problems with cast xmr go ask on the bitcointalk thread -- since it's not even added to NHM yet there's not really a lot of people able to assist you here.
https://bitcointalk.org/index.php?topic=2256917.0

**Comment by imrecsoka** [comment]
I only get 1700 odd hashes per second on 3 RX 470 cards,
I normally get  1900 odd hashes per second on SGminer or Claymore Cryptonote Miner
I think i have seen around 633 per card .

any ideas why the Cast XMR is slower?

**Comment by freshlemunz** [comment]
I am getting about 11100 H/s with 6 Vega 56. Each card is getting about 1850 hashes or so and are only using about 120w. Very happy with cast XMR. Runs very smooth.

**Comment by cryptotech407** [comment]
Unfortunately I have not been able to get Cast XMR to work for me.  I
installed Win 10 Pro from scratch, installed the blockchain drivers for my
3 Vega 64 cards, installed Cast XMR and added my mining pool and monero
wallet.  When I launch Cast XMR it runs and immediately exits with no
errors or arguments.

**Comment by freshlemunz** [comment]
@cryptotech407 I had the same issue and it turns out I was running the program in admin mode. Make sure to not have the enabled or it will just crash.

**Comment by cryptotech407** [comment]
@freshlemunz    Not sure what you meant by "Make sure to not have the
enabled".  When you say Admin mode, are you refering to not running it
under a Windows admin user or is there an Admin mode I must disable in Cast
XMR ?  Thank you

**Comment by freshlemunz** [comment]
@cryptotech407 Sorry about that. I worded it wrong. I meant don't run it in admin mode. You know how you can right click on an app and run it in "admin mode"? Make sure that's not enabled in the properties. If not that, delete the app and redownload it. That worked for me.

**Comment by cryptotech407** [comment]
@freshlemunz

I downloaded latest version and it is working now, but only getting about
1770 Mh/s on 3 Vega 64 GPUs.  On nicehash I am getting 5500 Mh/s.  Any
thoughts?
Thanks again

**Comment by freshlemunz** [comment]
@cryptotech407 Did you list all 3 of your gpu's?

**Comment by cryptotech407** [comment]
Just figured that out just before you replied.  It is working on all 3 GPUs
now, but for some reason not getting great hash rates.  1 is getting 1778,
2 is getting 1334, 3 is getting 1292 for a total of about 4500at just under
1000w of power..  In nicehash I am getting about 5500.

**Comment by freshlemunz** [comment]
@cryptotech407 Check and see if all your gpu are setup the same on wattman. Also disable and enable your gpu on device manager before you run the miner to get that HBCC goodness.

**Comment by freshlemunz** [comment]
Cryptotech407 Also you got Vega 64's, those guys should easily get 2000+ h/s each. You might want to research some powerplay mods or mess with your wattman settings to get optimal performance. There are plenty of guides online.

**Comment by cryptotech407** [comment]
Awesome.  Thank you very much for all your help.  I am new to Vega & XMR.
I've been playing with RX 580 cards for a couple of weeks.

**Comment by freshlemunz** [comment]
@cryptotech407 No problem.

**Comment by ahoang2005** [comment]
Need some input.

I've been thoroughly happy with the under voltage I have achieved (running 5 Vega 64s on a 1000w PSU).  I even figured out the startup batch file last night.  The issue I'm having is of my PowerColor Vega 64s has around 400 H/s lower than the other four.  Reference below.

<img width="272" alt="capture" src="https://user-images.githubusercontent.com/34192156/33517712-fa1f6794-d756-11e7-9e5d-b90fc0da03b5.PNG">

Not sure if its my setting in OverDriveTool but I'll attach those below.  Any input/tweak suggestions is appreciated.

<img width="141" alt="capture2" src="https://user-images.githubusercontent.com/34192156/33517732-3fa0a922-d757-11e7-86b9-ecdca3fbcdf4.PNG">

**Comment by aayubkh** [comment]
@ahoang2005 
Thumbs up if you get **2000 H/s OR 2 kH/s** using just around 250 Watts/Vega 64 with this without even touching BIOS or any _dangerous_ stuff...

Assuming you've got Blockchain drivers installed and a freshly booted Windows system with Crossfire **disabled**. Head straight for the Radeon Settings > Global Graphics (Radeon RX Vega) and turn on HBCC Memory Segment to the max. Do this for all cards. ONE BY ONE.
After that, fire up Wattman and apply the following settings only when you've done the above:

1. **Core Frequency:** -10%
2. **Memory Clock:** 1095 MHz
3. **Power Limit:** 0
4. **Fan Control:** Manual > Somewhere around 3500 - 3900 RPM whatever keeps it cool.

Apply it to all the cards and double check the values (except the fan speeds).

**Comment by cjf7684** [comment]
Hello, I'm finding the Blockchain drivers a bit unstable in my setup.  I have 4 Vegas 64 and one 580.  At one point I had 3 of the 64s' hitting 1900+.  Then I switched to cast-xmr version 0.07, (was using 0.06) and it locks up, freezes everything and forcing a hard boot.  I just now read about Crossfire being disabled, I haven't touched that one. When I make these driver config updates, can the mining app be running?  Currently I do it with the cast-xmr app down.  And someone mentioned to NOT run in admin mode.  I have been running in admin mode because I figure admin has authority to update stuff if needed.   Is this truly a no no?  Thanks

**Comment by freshlemunz** [comment]
Yeah don't run the newest version in admin mode, it would cause my setup to
just freeze and crash. Also, make sure to disable crossfire; I did that via
the registry.

**Comment by cjf7684** [comment]
Thanks, but what do you mean via the registry.  From the AMD Settings I don't even have the Crossfire options.  And should I be taking the install ReLive options during the Blockchain  driver install process?  Thanks, this site is helping me work the kinks out. 

![amd_settings](https://user-images.githubusercontent.com/34523050/33967136-ccfb8340-e027-11e7-84c2-7feed84cc670.PNG)

**Comment by cryptotech407** [comment]
I followed the instructions on this video and all working great for me so
far with Cast_XMR .07

https://www.youtube.com/watch?v=me9OxWZ71a0&feature=em-uploademail

**Comment by freshlemunz** [comment]
Look up circus dads guide online. It really helped me out and it will show you how to mess with the registry to shut off crossfire. Just be careful. Also, you don’t need none of that other stuff when you install it.

**Comment by MSukharev** [comment]
guseppiguliano commented Dec 2, 2017:

1. Core Frequency: -10% Comment: no sence, I set - 30%, and no difference with 0% in hashrate and power consumption. GPU is too fast for this algo, so work on 25% of power.

2. Memory Clock: 1095 MHz Comment: it depends of memory chips. My cards (Sapphire) busts one for 1000 and other for 970 then crushes.

3. Power Limit: 0 No comment

4. Fan Control: Manual > Somewhere around 3500 - 3900 RPM whatever keeps it cool. Comment: I set min. 2500, max 4300. Really get 3000-3200 antd temp. 50-52 C. 

Addon: set virtual memory 8 Gb for each Vega (50 Gb for 6). May be, Lock Memory Pages is sufficient for hashrate too. I'v locked mem. pages before I buy Vegas.

**Comment by lipkiz** [comment]
Thx for the best XMR miner!!
I use RX570 for mining, for flash timing and guiding, I can help you all,
But I need to read command , Can you help me?
Thank you
![capture](https://user-images.githubusercontent.com/34544474/33995363-504f64c6-e110-11e7-9e2c-7449a71b6121.PNG)

**Comment by cjf7684** [comment]
Thanks for the info and links to the videos.  I'm going to do a total re-install of the drivers and setup this weekend using this new found info and tools.  Thanks again.

**Comment by cristianb84** [comment]
Hello,
Can anyone suggest a solution for this ?
My system has 4 gb ram, 64 gb ssd and 6 x RX 580 8gb. The miner works, but only with 4 gpu added as parameter (-G 0,1,2,3). If i add one more, i get this error.
<img width="1284" alt="screen shot 2017-12-15 at 21 35 08" src="https://user-images.githubusercontent.com/19557335/34057500-e34d304e-e1df-11e7-867e-c04799738132.png">

**Comment by cjf7684** [comment]
Oh yes, I got that too.  Not enough memory a.k. RAM or virtual.  I had 4g of RAM and maxed out my virtual and got that error.  I added a 16g memory stick making a total of 20g then maxed out my virtual to 90g.  That took care of it.  When I started out I read you don't need much RAM a 4g should be plenty since all the work is done in the GPU's with 8g.  Not true.  You need lots of RAM.  I got the ASUS expert mining board and the instructions that came with it said you will need to max out at 32g if you go beyond 8 GPUs.  I hit the 4g limit with 3.  Running fine now with 5 GPUs' and 20g RAM.  I did have to set virtual memory to 90g though.  I'm afraid you will have to add more RAM and get a bigger SSD, 64gb is kind of short.  The virtual memory is proportional to your RAM.  I got a 250gb SSD.

**Comment by freshlemunz** [comment]
I am running 6 Vega 56 and have found that if I go lower then 40000mb of
virtual memory, my cards will crash. Keep in mind I have 8gb of RAM as
well. Virtual memory can make a HUGE difference.

**Comment by michlineal** [comment]
i currently using claymore for electroneum, and my hashrate are low, so i change to cast xmr,then i check back nanopool with same wallet address theres no stats at all. can anyone help? 
claymore cryptonote etn.eu1.nanopool.org:13433 <--stats available to view.
cast xmr etn.eu1.nanoppol.org:14444 <--- stats unseen.

**Comment by ahoang2005** [comment]
@michlineal looks like you're using the wrong ports. For SSL/TLS the port is 13433 but for Stratum the port is 13333.

Personally I moved away from using Nanopool as the payouts were low/inconsistent. Try, etn.spacepools.org
