### ISSUE TITLE
 Preserve algorithm proficiency parameters

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner#479]
It happens when you run NiceHash miner, he writes that he can not get the parameters of profitability (as I understand through the API NH). Add the saving of the latest profitability requests so that the next time you start it runs normally (even if api is not available temporarily)

**Comment by DillonN** [comment]
This is an interesting idea, I'll look into it

**Comment by Kekkonshiki** [comment]
I'm also want it!!! And you can add option in the settings for disable check profitability, it's look better :-)
