### ISSUE TITLE
Nist5 clarification on 1.8.0.1 patch notes?

### ISSUE THREAD

**Issue by malventano** [nicehash/NiceHashMiner#48]
From the patch notes:
- Nist5 stability

Does this require updating the bin for the miner, or was the fix contained within the NHM update download itself? Asking because the bin and bin_3rdparty downloads still reflect 1.8.0.0.

**Comment by ChriscomIT** [comment]
As far as I know, it is itself in the NiceHash miner code aka the process exe. This means in detail that the handling of Nist5 mining (launching, starting, profitability switching) was improved. Therefore you don't need to update the bins. Correct me if I am wrong.

**Comment by DillonN** [comment]
There was no update to miner bins. NHML includes multiple different versions of ccminer, since some are better at certain algorithms than others. While most of the forks give the same performance in Nist5, the previous one used would cause some users stability issues and/or rejected shares. In 1.8.0.1 a different version is now used for Nist5 which should resolve most of these issues.

**Comment by UselessGuru** [comment]
> n 1.8.0.1 a different version is now used for Nist5
Where can I find this new version? The update to 1.8.0.1 does not include any changed miners (dir \bin)

**Comment by drkskwlkr** [comment]
> Where can I find this new version?

@UselessGuru: For every project on GitHub, latest release is always found under 'Code->Releases'.
In this case:
[NiceHash Legacy Latest Version](https://github.com/nicehash/NiceHashMinerLegacy/releases)

If you have 1.8.0 already installed, you _don't need_ to download `bin.zip` or `bin_3rdparty.zip`.
Just get `NHML-1.8.0.1.zip`, decompress on top of your old install & run.

**Comment by DillonN** [comment]
Yes as @drkskwlkr says, the proper miners are already installed when you first run NHML. In this case there were no new miner additions, as the new selected version for Nist5 was already included for some other algorithms. So nothing more is required from your end.

**Comment by billmcilhargey** [comment]
this can now be closed @DillonN
