### ISSUE TITLE
RX580s benched but not mining. 

### ISSUE THREAD

**Issue by fabby88** [nicehash/NiceHashMiner#480]
So i have a rig set up and did the bench for it in precise mode. 
The CPU mines without a problem. 

However , when nicehash loads the claymore and starts dual mining ETH and LBC, it receives a work order, it has no speed and for all 6 GPUs. 
When i benched them , they were giving out proper hashrates with the DaggerHashimoto algos

Any of you have the same problem? 
THanks!

**Comment by Crypto-Lord** [comment]
I've had the same problem with both my 580's & vega. I'll try to re-simulate & post logs in the morning.
Temp fix for me was disabling that algo

**Comment by fabby88** [comment]
Hi Crypto-Lord, 

Thanks for the temp fix, it did get it hashing. However , it is mining in efficient coins. 
how did you get it to start mining daggerhashimoto ?
thanks !

**Comment by DillonN** [comment]
@fabby88 have you tried mining with CPU disabled? Sometimes CPU can be too intense and the Claymore miner cannot get enough to process work for the GPUs
