### ISSUE TITLE
Xmrig-nvidia

### ISSUE THREAD

**Issue by riccardoruspoli** [nicehash/NiceHashMiner#484]
Xmrig for CPUs has been included, and it's working well, but there is also xmrig-nvidia, that uses Cryptonight and it reaches ~270 H/s versus the ~225 H/s of ccminer on the same GPU with the same frequencies.

**Comment by DillonN** [comment]
Thanks for posting, I'll look into it

**Comment by seanego** [comment]
I second this: it's faster at least by one-third

**Comment by Nicheuji** [comment]
I just tested it. It's indeed faster.
@DillonN Would really appreciate it if you could add it to NHML as soon as you can since mining Monero is currently very profitable.

**Comment by Balzhur** [comment]
For xmrig-nvidia you have to play with threads/blocks in config to achieve maximum output. For example for my 1070 xmrig autoconfigured 45 threads/32 blocks providing stable 718.7 sol/s but with 80 threads/30 blocks it provides 731.7 sol/s.
@DillonN, you may want to play with threads/blocks during the benchmarking to achieve best result :)

**Comment by chuongmd** [comment]
how can i connect to nicehash with xmr-star-nvidia ?

**Comment by riccardoruspoli** [comment]
I've made a few tests, and if into ccminer you use the paramater --launch followed by the THREADSxBLOCKS that are written in the config of xmrig-nvidia, ccminer reaches the same speed of xmrig-nvidia.

So the differences between these two are only the graphical interface and the support for cryptonight-lite.

**Comment by Balzhur** [comment]
@Rikifire, nope. You'll get following:
`[2017-11-08 12:28:02] 1 miner threads started, using 'cryptonight' algorithm.
[2017-11-08 12:28:02] GPU #0: GeForce GTX 1070 (15 SMX), using 30 blocks of 80 threads
[2017-11-08 12:28:02] GPU 0: THE 32bit VERSION CAN'T ALLOCATE MORE THAN 4GB OF MEMORY!
[2017-11-08 12:28:02] GPU 0: PLEASE REDUCE THE NUMBER OF THREADS OR BLOCKS`

xmrig is 64 bit - allows utilizing 8Gb on my 1070.

**Comment by riccardoruspoli** [comment]
Well @Balzhur, with my configuration it worked without problems, I can't tell why this problem happens to you. Just for information, are you running NHML with admin rights?

**Comment by Balzhur** [comment]
@Rikifire, huh? What admin rights has to do with ccminer being 32but binary and unable to allocate more than 4Gb of memory?
xmrig - 64bit, can allocate more than 4Gb of RAM, so 80threads/30blocks is Okay.
ccminer - 32bit, 80x30 does not work for it requires more than 4Gb of RAM.

And while YOUR config may work, MINE - does not. xmrig provides steady 731 Sol, ccminer maxes at 690 Sol for my config.
