### ISSUE TITLE
Issues with DaggerHashimoto and minimum miner profitability

### ISSUE THREAD

**Issue by noremac13** [nicehash/NiceHashMiner#486]
I had a post up in the Nicehash subreddit and was told to make a post here including my log file to figure out what is going wrong.

Basically I have minimum profit set to $1 and it keeps trying to use Daggerhashimoto claiming it is my most profitable but it is only showing 20-30 cents per day.  The Claymore one works well but it never seems to want to use that one since the hashrate I see is always like 7-9 MH/s which leads me to believe it is trying to run the ethminer one.  I've since unchecked the ethminer one and saw no change.

Attaching log file from my run overnight last night and woke up to it again mining Daggerhashimoto at 23 cents a day profit.

[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1424634/log.1.txt)

**Comment by DillonN** [comment]
@noremac13, thanks for making a post here.

The thing to understand is that NHML makes most of its decisions based on the benchmarked values for different algorithms/miners. Your benchmarks put Claymore Dagger at around 22MH/s, so all switching/profitability cutoff decisions will go based on that number and *not* what is currently happening. 

For this reason, it is important to make sure the benchmarked values in NHML are true. In this case, at 22MH/s Claymore is always above $1/day so mining will never be shut down. It will also use it over other miners that are even slightly less performing

In your situation it looks like you're not getting the same speeds that were reported in benchmarking, and indeed a 1060 should get around 22MH/s. Claymore *is* being used but it is dropping down to 7MH/s, this is a problem that can sometimes occur for several reasons:

* Your CPU utilization is too high (e.g. running a CPU miner at high intensity)
* RAM/VRAM/Page file is not high enough (Dagger is a very RAM heavy algorithm)

It does not look like you have high CPU utilization so you can look into making sure page file is set high enough and RAM isn't overutilized. Unfortunately this isn't a problem in NHML so there is not much that can be solved on this end

As a workaround for now you can manually set the benchmark hashrate to 7MH/s or just disable that algorithm. Equihash is doing well right now so you should still have decent results with that

**Comment by noremac13** [comment]
Hi thanks for the quick response.  I had miner windows hidden but I turned them back on to maybe get a better idea of what was happening.  I think I may have found the problem.

I didn't realize that Claymore was a dual mining algo and it is trying to do ETH+Decred.  My Decred benchmark is around 13 MH/s which also happens to be the difference between my current speed and the benchmark speed.  Sure enough in the console at the start of mining it says 0 Decred pools are specified and it is operating in ETH-only mode.

https://i.imgur.com/wzyqgOX.png

I assume this is the problem?  If so what do I need to do to fix it?  I know it worked at one point so I am not sure what changed and randomly broke it so I have no idea what to change to fix it.

**Comment by DillonN** [comment]
@noremac13 it is not mining with Decred, that is the default output Claymore will show when mining in just eth (notice how it says "ETHEREUM MINING ONLY MODE ENABLED"). Decred is the default secondary coin so if a second address were passed it would turn it on automatically (but no address is passed)

**Comment by gutinhozik** [comment]
i have the samo problem !!!!
