### ISSUE TITLE
Power consumtion

### ISSUE THREAD

**Issue by theerawatra** [nicehash/NiceHashMiner#49]
I observe version 1.8 take more power consumption about 10% when compare to version 1.7.
I shut down version 1.7 at 13:00 and start version 1.8 at 15:00.
![20251221_1525551340835303_1082318129_o](https://user-images.githubusercontent.com/30343358/28462086-d43f7202-6e43-11e7-86c0-4510bc7edc78.png)

**Comment by nerdatwork** [comment]
How do you measure power ? Could you share your setup ? That looks like an app on your phone.

**Comment by theerawatra** [comment]
I use Smart Power Monitor Outlet to monitor comsumption of my rig over the internet and I did VNC remote my rig to stop V1.7 and install V1.8 also over the internet as well.

**Comment by DillonN** [comment]
This is likely a byproduct of the new miner options that are more profitable for you. E.g., ClaymoreDual running in dual mode can use quite a bit more power than just mining Ethereum by itself. If the gained profits in those algorithms are less than your increased electricity costs, you're best to disable them. As it stands NHML does not take different power consumption of various miners into account when calculating maximum profitability.
