### ISSUE TITLE
Benchmark window gets frozen for a while after starting bench on DaggerHashimoto (ethminer)

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#490]
Preconditions: NHML 1.8.0.2/1.8.1.3/1.8.1.4/1.8.2.0, Benchmark is enabled for **DaggerHashimoto (ethminer)**, Window 10 x64, Nvidia GTX 1060 6 GB

1) Start NHML
2) Open Benchmark window
3) Start Benchmark

**Result:** Benchmark window gets frozen for about 30 seconds.

Log is attached [log.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1425257/log.zip)

Here is a bit explanation of my case and log:
> [2017-10-29 19:48:07] [INFO] [ExtraLaunchParametersParser] DisableAMDTempControl is TRUE, temp control parameters will be ignored
> [2017-10-29 19:48:37] [INFO] [NICEHASH] Время ожидания операции истекло // Translation: Awaiting of operation has been timeouted
> [2017-10-29 19:48:37] [INFO] [NVIDIA] Failed to obtain current block, using default 2000000.
> [2017-10-29 19:48:37] [INFO] [BENCHMARK] Benchmark starts
> [2017-10-29 19:48:37] [INFO] [MinerEtherumCUDA-MINER_ID(1)-DEVICE_IDs(0)] Starting benchmark:  --benchmark-warmup 40 --benchmark-trial 20  --cuda --cuda-devices  0 --dag-load-mode parallel  --benchmark 2000000

I've started bench of **DaggerHashimoto (ethminer)** at [2017-10-29 19:48:07], since 19:48:07 till 19:48:37 benchmark window was frozen.

**Comment by DillonN** [comment]
Thanks for posting, I'm going to be looking a lot at the benchmark threading soon so I'll see if I can't fix it then

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

ethminer not relevant anymore
