### ISSUE TITLE
Excavator v.1.3.4a

### ISSUE THREAD

**Issue by Ducalis** [nicehash/NiceHashMiner#492]
Why in NHM 1.8.1.4 such old Excavator version (v1.1.4a)? Whether it is possible to change to the version 1.3.4a?

**Comment by Duski78** [comment]
Its a riddle to me, i am also pleasing to add new Version :)

**Comment by DillonN** [comment]
The new Excavator version isn't supported, and there is no current plan to add support. This is because NHML gets flagged as a virus frequently for downloading miner software, and the new Excavator needs to stay clean from flags
