### ISSUE TITLE
LYRA2REV2 efficiency not optimal

### ISSUE THREAD

**Issue by HansHagberg** [nicehash/NiceHashMiner#493]
For some time now, LYRA2REV2 has been the most profitable algorithm for high end NVIDIA GPUs.
I noticed that the software running LYRA2REV2 in NiceHash legacy (V1.8.2.0-Pre) is about 10% less efficient compared to the one in NICEHASH2 V2.0.1.3 - BETA.
This difference is enough to often make some other algorithm more profitable.

Tried to look into it briefly but the structure is so different I had problems finding stuff to compare what are the actual differences.

**Comment by streaml1ne555** [comment]
Looks like in Nicehash2 everything is Excavator based and LyraREv2 in Nicehash 1.8 is ccminer. That could explain the difference I suppose.

**Comment by shinnsd** [comment]
Yeah, I think including an option for LyraREv2 on Excavator for NHML will be nice

**Comment by DillonN** [comment]
I am looking into updated ccminer forks that have better Lyra2REv2 speeds. Please redirect conversation to #465 

The version of Excavator included in NHML is old and does not support Lyra2REv2, and it cannot be updated currently
