### ISSUE TITLE
Benchmar different GPUS at the same time

### ISSUE THREAD

**Issue by francescocmazza** [nicehash/NiceHashMiner#494]
Hello,
It would be awesome if you could allow the benchmark process to run contemporarily on different gpus. This would speed up very much the benchmark process on multi-gpu systems.
Thank you

**Comment by DillonN** [comment]
This is currently being looked into

**Comment by francescocmazza** [comment]
Thank you!

2017-10-31 17:14 GMT+01:00 Dillon Newell <notifications@github.com>:

**Comment by DillonN** [comment]
Beta support in 1.8.2.0-Pre2
