### ISSUE TITLE
Xmrig CPU affinity

### ISSUE THREAD

**Issue by bilibilistack** [nicehash/NiceHashMiner#497]
I used xmrig before and thanks for adding into nicehash 1.8.1.4
It's important to set CPU affinity for higher performance.
I tried following setting in the config file, not working now after apply and restart:
"ExtraLaunchParameters": " "cpu-affinity": "0x5555""
It works in the original xmrig's config.json with "cpu-affinity": "0x5555" for sure.

So how to give the embedded xmrig the correct extra launch parameters? thanks!

**Comment by streaml1ne555** [comment]
Add this to your extra launch params for xmrig via settings->devices/algorithms:

--cpu-affinity 0x5555

Works here.

**Comment by bilibilistack** [comment]
It worked, thanks! The font is in red along with dev fee (weird), but it worked when I check task monitor

**Comment by DillonN** [comment]
You can see the supported extra launch parameters [here](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Algorithm-ExtraLaunchParameters#xmrig)
