### ISSUE TITLE
CPU Not Providing Income

### ISSUE THREAD

**Issue by dfg555** [nicehash/NiceHashMiner#498]
Upgraded from v1.7.5.13 to v1.8.1.4 and my CPU doesn't give me an income but it still mines? GPU Mines perfectly. I thought it was a display bug so I let it mine for a day and my income was worst compared to v1.7.5.13. I went back to v1.7.5.13 and that works perfectly.

i5-2500

R9 290X

Windows 7 64-bit 

https://i.imgur.com/I5bi4eG.png

**Comment by dfg555** [comment]
[logs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1433291/logs.zip)

**Comment by DillonN** [comment]
Thanks for posting, it looks like NHML is receiving an empty response when checking for speed data

Xmrig seems to be more stable for other users, you can try mining with that (looks to be almost identical in speed for you according to your benchmarks)

EDIT: I have found an error that may be causing this

**Comment by dfg555** [comment]
I tried xmrig but the same thing occurs.

**Comment by rpm604** [comment]
I have the same issue as dfg555. I upgraded to 1.8.2.0 to reap the sick CryptoNight rewards, but I'm getting extraordinarily odd/random profit reporting on the NiceHash dashboard, and also 0.00 profit reporting for my CPU within the program.

In the first picture, the GPU profits look about right (1.2kh/s), but the CPU profits are crazy inflated (I was only getting ~350h/s max at the time). Second picture both the CPU and GPU were the same according to the windows themselves, but NiceHash reports 0 for CPU and about half the speed for GPU. 

There are also periods where the report reads 0//0.

I have not tracked the profits over time, to see whether the profits are correct with incorrect reporting, or if the profits are incorrect and the reporting is correct.

![profits too high](https://user-images.githubusercontent.com/25334987/32346620-1f92a188-bfcb-11e7-824a-bd18da887a91.png)
![profits too low](https://user-images.githubusercontent.com/25334987/32346621-1faac2d6-bfcb-11e7-8b1b-db87ab260a0c.png)
[logs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1439135/logs.zip)

**Comment by DillonN** [comment]
The issue with NHML client reporting 0 in error should be fixed

@rpm604 the stats on the webpage can be very sporadic, based on when you successfully submit shares. Because of this it will show high hashrates in the short time periods where you submitted a share and 0 otherwise. What matters is the overtime average (hours or more). This is normal and doesn't affect profitability
