### ISSUE TITLE
Problems with the equihash algorithm

### ISSUE THREAD

**Issue by vadik722089** [nicehash/NiceHashMiner#499]
GTX 980 Ti. the benchmark can not read it manually wrote the speed then the benchmark read it then launched the mining and there is no speed at all 0 Sol / s

**Comment by vadik722089** [comment]
![jgao-wkqwlc](https://user-images.githubusercontent.com/33276956/32263521-18ad331c-befc-11e7-9407-bd2ee0a7f245.jpg)
![zlro5gomiio](https://user-images.githubusercontent.com/33276956/32263540-209eaf74-befc-11e7-9ddd-9d7410557414.jpg)

**Comment by DillonN** [comment]
@vadik722089 you write that you are using a 980 Ti, but it shows you are using a GTX Titan? If you are using a Titan it seems nheqminer itself is causing problems for you, you can try with one of other builds - https://github.com/nicehash/nheqminer/releases. Unfortunately the use of nheqminer has been superseded by Excavator and EWBF, which are not compatible with Kepler cards (like the GTX Titan)

If you actually have a 980 Ti then something is wrong with your drivers most likely

**Comment by vadik722089** [comment]
Many thanks that I did not notice that the driver reinstall the driver from another card, it's very suspicious that games and other applications were working steadily these drivers
