### ISSUE TITLE
1.8.2.0 benchmark lost data

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner#501]
You need to save the settings after each benchmark.
Now the data is lost if there is a failure and a reboot - Everything has to start anew

**Comment by DillonN** [comment]
Yes you will lose benchmark data if the PC crashes before the benchmark finishes. This hasn't changed in 1.8.2.0

I can look into saving after each benchmark

**Comment by CreamyG31337** [comment]
Please do, should be easy

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

This feature is implemented now
