### ISSUE TITLE
Last

### ISSUE THREAD

**Issue by Ithan74** [nicehash/NiceHashMiner#502]
=

**Comment by CAVACO-PT** [comment]
All duals with ETH are disconnected by pool (eu.nicehash.com)

#500

**Comment by DillonN** [comment]
@Ithan74 can you post your log.txt file after doing a benchmark so maybe I can see why some of them are failing

It is normal for *some* to fail on specific cards, not every algo/miner combo works on every card. We try to remove the ones that don't work on a specific card so you don't see them, but some get through
