### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by adri76** [nicehash/NiceHashMiner#505]
osting an issue:

- Please make requests in Englis
h
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by  the miner manually and looking for the error.
- The issue is  to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by DillonN** [comment]
Please provide details for what you are reporting and make sure it is an issue with NHML
