### ISSUE TITLE
Vega stuck at 300 h/s - Polaris performing worse after adding card

### ISSUE THREAD

**Issue by Buckthebarbarian** [nicehash/NiceHashMiner#506]
So recently I managed to add another gpu to my rig (rx580) but I have two problems while mining. My rx vega hashrate on sgminer (with nicehash) is stuck at 300 on the benchmark and when it starts mining normally, it is stuck at 0 hashrate with no error message.
Also, my 3 polaris cards are running much slower than before (26mh/s each when overclocked) even though all three are bios flashed and OC'ed to 2000mhz. They are all 4gb cards, before when I was having only 2 polaris gpus I was pulling 29/30 mh/s each.
My rig is a biostar btc350, ryzen 7 1700, 8gb ram and I'm running 3 psu's - could that be cause for concern?
Many thanks guys!

**Comment by vaverix** [comment]
My vega stays at 0 kh/s (sometimes 300 h/s) for a few minutes then crashes. When I mine without Nicehash Miner Legacy (using cast_xmr miner) everything is fine.

**Comment by DillonN** [comment]
Proper cryptonight support for Vega is coming soon

For your Polaris cards, a number of things could cause lower performance that are not related to NHML. E.g. higher temps, too much power, too much stress on the CPU (if you are also mining on it) etc

**Comment by Buckthebarbarian** [comment]
Thanks for taking the time to answer DillonN. The bizarre thing is that there are dag files where my cards are mining at 30-31 mh/s and suddenly later they drop to about 25. I double checked my drivers and I am indeed on the blockchain one. I've dedicated 2 out of 8 cores on my cpu only for the cards so i'm guessing they should have enough CPU processing power. When you say too much power, could a potentially too high power limit negatively affect hashrate?

**Comment by DillonN** [comment]
@Buckthebarbarian if your PSUs can't handle the extra power then higher power limits could cause problems. You may also be running into RAM limits. Do you see better performance with one card idle? Also you could try mining without CPU just to see if that is causing any problems
