### ISSUE TITLE
Cannot extract the files properly

### ISSUE THREAD

**Issue by kojihirai** [nicehash/NiceHashMiner#508]
When I download the official release zip file and extract, half of the files including nicehashminerlegacy.exe do not extract so i cannot run. Please help me.

**Comment by Nicheuji** [comment]
Most likely your antivirus is blocking the files.
See https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Troubleshooting#nicehash-miner-legacy-or-included-miners-are-being-flagged-by-anti-virus

**Comment by DillonN** [comment]
Yes this is very likely an antivirus problem
