### ISSUE TITLE
Feature Request: Support for Virtual Desktops

### ISSUE THREAD

**Issue by drkskwlkr** [nicehash/NiceHashMiner#51]
Windows 10 has the ability to create a number of virtual desktops and switch easily between them, thus enabling different 'contexts' like work, casual browsing, gaming, etc.

With this feature enabled, one can group any NiceHash Miner related windows (e.g. main window, console window, OC utility, load monitor...) into a separate virtual desktop and quickly recall them for a quick look before getting back to doing their business on their 'main' virtual desktop.

The issue I have with NHM is that new miner console windows which launch when profitability changes always pop up in front of other windows and steal focus.

I tried to skip around this behavior by launching NHM on Virtual Desktop No. 2, but new miner consoles would keep popping up on Virtual Desktop No. 1 & interrupt whatever work I might be doing at the moment. It seems that the Windows 10 Virtual Desktop feature has no concept of 'parent windows' that would keep child windows spawning within the same desktop as the parent program.

It seems possible to programmatically control to which virtual desktop a new program is launched. The [VDesk Launcher](https://github.com/eksime/VDesk) (written in C# & relying on .net just like NHM, released under GPL 3.0) has this ability.

Perhaps NHM can loan this functionality to become 'Virtual Desktop aware' and allow users to keep all NHM related windows on the same Virtual Desktop?

If the implementation of such feature is not feasible at this point, can the Dev team look for a possibility to launch miner consoles as background windows that will not steal focus from current tasks?

**Comment by DillonN** [comment]
I agree it would be nice to be able to get the miner consoles to run on a separate VD, as well as prevent pop-up of miners interrupting tasks (can be very annoying if using your PC for gaming/videos, currently the only workaround is to hide miner windows altogether). I'll look into this.

**Comment by Dohtar1337** [comment]
Old task. Out of scope
