### ISSUE TITLE
NHM legacy wont run

### ISSUE THREAD

**Issue by Tofteberg** [nicehash/NiceHashMiner#513]
Im new to mining. want to install legacy, but when i click the NHML exe file, nothing happens...
what am i doing wrong??

**Comment by Xirruf** [comment]
Same here..  Please help.
Windows 10 x 64

**Comment by DillonN** [comment]
Make sure antivirus/smartscreen is not blocking it from running

Please post your logs\log.txt file if it exists (if it does not exist almost certainly something is blocking it from running)

**Comment by gomesthiago** [comment]
I have the same problem, I dont have any antivirus and no logs are generated

**Comment by DillonN** [comment]
If this is still occurring, something is killing NHML before the very first lines of code are executed, likely by Windows or some instability
