### ISSUE TITLE
[CPUDIAG] System.InvalidOperationException

### ISSUE THREAD

**Issue by k1184** [nicehash/NiceHashMiner#514]
Hi There.
When runing nicehashminer in debug I receive 
[CPUDIAG] System.InvalidOperationException: Не удается загрузить данные имени счетчика, поскольку в реестре обнаружен недопустимый индекс "".
   в System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   в System.Diagnostics.PerformanceCounterLib.get_NameTable()
   в System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   в System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   в System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   в System.Diagnostics.PerformanceCounter.InitializeImpl()
   в System.Diagnostics.PerformanceCounter.Initialize()
   в System.Diagnostics.PerformanceCounter.NextSample()
   в System.Diagnostics.PerformanceCounter.NextValue()
   в NiceHashMiner.Devices.CPUComputeDevice.get_Load() в C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDevice\CPUComputeDevice.cs:строка 18
 Who is Dilon? ))
Hope the developers will understand, what is this.

**Comment by DillonN** [comment]
Please see [on the wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Rig-Stats-Monitoring#perflib-problems)

**Comment by k1184** [comment]
Thanks! Issue is closed.

**Comment by f00x** [comment]
And what is the final solution? =)
