### ISSUE TITLE
Chrome blocks download of 1.8.2.0

### ISSUE THREAD

**Issue by xenoputtss** [nicehash/NiceHashMiner#516]
When downloading (prerelease) 1.8.2.0, Chrome will block the download from completing and leave the downloaded file in an unusable state.

Chrome then provides this link for the download, and also only a "Discard" button.  https://support.google.com/chrome/answer/6261569?visit_id=1-636453056702832967-3608807855&p=ib_download_blocked&hl=en&rd=1

I understand that this is an "Antivirus" issue with chrome, but since this is happening directly from the browser it will be nearly impossible for a user using chrome to avoid this.

**Comment by drkskwlkr** [comment]
@xenoputtss 

1. From within Chrome, press Ctrl+J to open the Downloads tab
2. Select flagged download and click on 'Keep Dangerous File'

> it will be nearly impossible for a user using chrome to avoid this

Thankfully, there are alternatives to Chrome. Please close your ticket as it has nothing to do with NHML.
