### ISSUE TITLE
Mining rig crashing

### ISSUE THREAD

**Issue by Leoxciv** [nicehash/NiceHashMiner#517]
Hi, I hope someone can please help me. I use to have a lot of crashing problems while mining, I did some changes to my motherboard and my mining rig worked 100% perfect for about 1 month. Now the crashes are back and I don't know what to do. The rig crashes within 10 minutes. 

I have Asus Z270-A Motherboard
X5 EVGA 1080ti 
X2 EVGA 850 BQ PSU
risers version 006c
200gb hdd
4GB RAM
Windows 10﻿ Pro
Intel(R) Pentium(R) CPU G4560 @ 3.50HGz 3.50GHz.

My MOBO config:  https://imgur.com/bEe060e
Picture of the error: https://imgur.com/P5cxfOX

**Comment by DillonN** [comment]
It looks like a similar problem was reported for an older version of NHM - https://github.com/nicehash/NiceHashMiner/issues/284

Can you try the fix mentioned there?
