### ISSUE TITLE
AMD GPUs identified in wrong order causes miner crash

### ISSUE THREAD

**Issue by UdoK** [nicehash/NiceHashMiner#518]
I'm running a 8 GPU rig on Windows 10 which consists of 4 different GPUs
NHML identifies them in this order:
#1:R9 290; #2:RX570; #3:R9 390; #4:RX570; #5:RX Vega; #6:RX570; #7:RX570; #8:R9 390
But the order the miners will start them is like this:
#1:RX570; #2:RX570; #3:R9 390; #4:R9 390; #5:RX570; #6:RX570; #7:R9 290; #8:RX Vega
This means the settings assigned to the miner for each GPU are wrong and caused the miner to crash. 
Benchmark didn't finalize after 8 hours, just for the first 3 GPUs partly.
Tested this with version 1.8.1.4 and 1.8.2.0 
AMD Blockchain driver installed

**Comment by DillonN** [comment]
Not every miner orders GPUs the same - NHML accounts for this when launching the deviant miners

What do you mean by the order miners will start them? Which miners specifically? Can you post your logs\log.txt file?

**Comment by UdoK** [comment]
In generell I refer to the CryptoNight sgminer and Claymore miners.
I mean by the order the miner will start the GPUs if I select just one, indicated in NHML as #1 R9 290, then the miner runs one of the RX570s. Doing this one by one I got this second list. This applies also when doing the benchmark test.
I've done a quick benchmark on some GPUs and tried mining all GPUs together today which result in a Windows crash with 1.8.1.4.
See attached log files for both versions. 
[1.8.2.0_logs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1443160/1.8.2.0_logs.zip)
[1.8.1.4_logs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1443161/1.8.1.4_logs.zip)

**Comment by wutBEE** [comment]
I have also had cases where NHML will incorrectly label different AMD cards. I was running two RX580's and one Vega. However, when benchmarking one of the cards labeled as RX580, the benchmark would actually run on the Vega. Alternatively, running the benchmark on Vega would actually cause the other RX580 to spin up. Viewing stats in GPU-Z, as well as the increased fans on the Vega (hard to miss) confirmed that the card benchmark labeled as RX580 was actually running on a Vega.

I wouldn't have cared about this, but NHML will group the incorrectly benchmarked Vega with the RX580's during mining, causing it to run algorithms that weren't as profitable as could be on the Vega.

**Comment by UdoK** [comment]
When I read some of the other issues where users having different GPU types and problems during benchmarking and mining  I think what I described is the root cause for all these problems. 
Hope you guys can fix it in one of the next versions.

**Comment by DillonN** [comment]
@UdoK from your logs it looks like NHML is having communication trouble with the AMD drivers, which could cause it to find the wrong ID numbers. Are you able to try with non-blockchain drivers?

**Comment by UdoK** [comment]
Thanks for your feedback. Unfortunately I'm actually not able to change driver as it will take me half a day to setup the all the GPUs with a new driver. Will test when a new version is out.

**Comment by richardrooks** [comment]
I am having this happening now with the latest version 1.8.1.6.

I have a mix of rx 580s, vega 56s, vega FE. The vegas and 580s are not correctly identified in the UI. Benchmarking and watching afterburner this can easily be seen....along with fan spin ups.

**Comment by Samoflan** [comment]
I am having the same issue with v1.8.1.8.

I have a mixed bag of 5 AMD GPU's, RX Vega 56, RX 580, RX 480, and two different RX 470's. NiceHash doesn't seem to detect them in the same order that CPU-Z, HWiNFO64 and OverdriveNTool does (I don't know if that matters, just a observation). When I benchmark each card separately, it isn't always the card I select. e.g. selecting RX 580 will benchmark the RX 470. Same thing happens when mining.

I have messed around all day with the OverrideAMDBusIds option in the general config file. Doesn't seem to have any effect on reordering which card is selected.

**Comment by peeceeuser** [comment]
Same issue: I have WX 7100's and VEGA FE's. They run properly using the Pro 17.12.1 Drivers (all other drivers fail to work properly). The system runs very stable with those drivers. When I add the WX 7100's all work fine, but when I add a VEGA, it swaps with one of the WX 7100's and mis identifies the cards. It then puts the benchmarks for the WX7100 Under the VEGA. When I benchmark, I see that the mis identified cards are running. I.E: I run a benchmark for a 7100 that swapped with a VEGA and it runs on the VEGA, and visa versa, when I run a VEGA benchmark, it runs on the 7100. Many different versions of NH tried, all do the same thing.

**Comment by snargledorf** [comment]
I just want to add my setup which is exhibiting this same behavior. I'm running a machine with a RX 480, and 2 7850's.

One of the 7850's and the RX 480 are being miss recognized for each other.

MSI Afterburner, HW Monitor, and GPU Z all detect the GPU's correctly.

**Comment by peeceeuser** [comment]
It was the drivers for me. Turns out this is a known issue with AMD cards using recent drivers and some mining software. I used DDU, unplugged all but one card and installed the 17Q4 pro drivers, (all my cards are pro cards), stable. I tried the 18Q1 drivers, but it had the same problem as other drivers. You may want to try the Block Chain Beta drivers, those were not stable for me.

**Comment by snargledorf** [comment]
I can confirm that using the AMD Blockchain Beta drivers has resolved the issue for me. All cards are detected in the correct order and I am mining at full performance.
