### ISSUE TITLE
DCRI parameter not being passed?

### ISSUE THREAD

**Issue by WarrenSchultz** [nicehash/NiceHashMiner#52]
Tell me if I'm using it wrong :)

(Example, not looking at the specific values right now)
I put -dcri 105 in the parameter field for daggerpascal for both 1070s. When I check taskmanager, it lists in the command line field -dcri 35,35. Should I be passing 105,105 or am I doing it wrong?

**Comment by DillonN** [comment]
Putting -dcri 105 in each of the devices is the correct way of doing it. Could you post your logs for when this happens?
