### ISSUE TITLE
I want a "accepted for" button

### ISSUE THREAD

**Issue by Jakobhoss** [nicehash/NiceHashMiner#520]
To give the altcoins a little push and to give the miners some power back I want an "Announce for: x BTC/MH...GH...Sol" Button or slider. So you can define each algorythm for which price you provide your hash. Maybe there could be a "threshold" slider with up to 5%. This price can be only set every hour and counts worldwide the same. So miners could be more active members of nicechash than simply running after the most profitable algo.
So you could add the info for buyers for what the algo will be accepted by miners. For the case that there is too much between what miners want and what the buyers want you could then announce an official price for all.

This is only a little idea to save nicehash.
I have to say that since two days the algorythms are so low priced, I have to shut down my Nicehash rigs and reconfigure them to my ethereum pool again, because I hash ethereum cheaper for my own than I earn through nicehash. If you would pay or accept ETH there would be no problem but the algos are simply too cheap for miners.

Good luck, have a nice day!

**Comment by DillonN** [comment]
This idea seems beyond the scope of NHML. You can contact info@nicehash.com for inquiries about the NH service
