### ISSUE TITLE
How can I change ccminer?

### ISSUE THREAD

**Issue by man55** [nicehash/NiceHashMiner#521]
How can I change ccminer or other miner?
I do not always agree with the choice of the miner for a particular algorithm. I know for sure that some other versions of miners work faster, sometimes much faster.

Thank you!

**Comment by snowcrawl** [comment]
You can disable the version of a miner that you don't want to ever be used with a particular device.   Simply by going into settings, then devices/algorithms and uncheck the version of the miner you don't want to be used.

**Comment by DillonN** [comment]
You can see instructions for changing ccminer versions here - https://github.com/nicehash/NiceHashMinerLegacy/wiki/Customizing-ccminer-and-sgminer-paths

**Comment by man55** [comment]
Thank you DillonN,

This is what I need.
But I understand that only one ccminer version for all 10xx cards?
I have GDDR5 and GDDR5x Cards in one rig and they require different ccminer versions for same algo.
It is necessary to run two copies of NiceHashMinerLegacy?

**Comment by DillonN** [comment]
@mgcm3n yes unfortunately you can only set one for all 1000 cards

**Comment by stna1981** [comment]
Is there a way to change the config ccminer is using, e. g. for CryptoNight? I tried to modify the MinerOptionPackage_ccminer_CryptoNight.json file but it seems to have no effect?

**Comment by DillonN** [comment]
@stna1981 the MinerOptionPackage files are just what NHML uses to determing which extra launch parameters to set. You can edit those files to let new options work in for extra params if they are not already included. To actually set the options you must use extra launch params in the settings
