### ISSUE TITLE
Profitability drops and BTC going up? Not with me.

### ISSUE THREAD

**Issue by Jakobhoss** [nicehash/NiceHashMiner#522]
Yesterday I wrote a request for more options for hash providers to influence their income. I have the Idea that you could implement a box in which a miner can write his minimum accepted price because the algos are keeping going down. This fact is simply because of the NHM software, where you cant influence the minimum price and so the miners are automatically hunting for the best price. But when orders are getting lower, the price drops again and you as an hashing provider have no influence for which price you want to sell your hashes.
So I think this is a option for miners to keep the alcoins profitable for them and to participate more in the mining process. 
But you deleted my post after a few hours without a answer or comment.
So for me it´s clear now that you don´t want the miners to participate in the whole nicehash thing, you want us simply to deliver for every price? Then here is my answer.
Not with me. I´m out. I closed all my nicehash activities this morning and all my 13 rigs with together over 2800 MH in ETH will go to another pool.

Providing hashing power has to work for both sides. At the moment only Nicehash and buyers are making any profit. My energy costs are going up, hardware replacement and maintanance costs a lot and the rigs need service 24/7. Bitcoin is going up like crazy, Monero ETH and Zcash are walking with Bitcoin prices but I don´t realise anything ot this growth at my miners, instead I have a growing loss.
Remember that you earn through us miners, not the buyers. This greed kills Nicehash.

**Comment by doverosx** [comment]
Thankfully for me, I don't pay for power but isn't it possible to enter
your power consumption into NHML?

Additionally, your post want deleted, the issue # was closed because
feature ideas belong somewhere else. Feature requests should go to
info@nicehash as Dillon mentioned in his reply.

Regards,
Brodey Dover

**Comment by drkskwlkr** [comment]
> Not with me. I´m out. I closed all my nicehash activities this morning and all my 13 rigs with together over 2800 MH in ETH will go to another pool.

Good. Now close your ticket and stop wasting developers' time.

**Comment by DillonN** [comment]
@doverosx is right, I left a reply on your other issue #520 that this is not within the scope of this issue forum. There is already a minimum profit option so you don't mine below what you deem is unacceptable 

Closing this now..
