### ISSUE TITLE
intensity settings

### ISSUE THREAD

**Issue by kfadrat** [nicehash/NiceHashMiner#524]
Hi,
can somebody tell me what is the intensity setting for ccminer?
I tried -i n , --intensity n , --intensity=n and so on, but nothing seems to work for me.

**Comment by bruvv** [comment]
--launch=.X. (where the dot is the block and threads)

**Comment by kfadrat** [comment]
it works great, thanks a lot for help

**Comment by bruvv** [comment]
no worries please close it now.
