### ISSUE TITLE
v1.8.1.4 won't benchmark

### ISSUE THREAD

**Issue by rockym20** [nicehash/NiceHashMiner#525]
I downloaded v1.8.1.4.  All of the bins downloaded correctly.

My rig has 3 X R9 380, 1 X R9 290 & 1 X HD 7950 (soon to be changed to 3 X 380 + 3 X 7950).  It runs Catalyst 15.12 with complete stability under Claymore dual miner.  Newer drivers create instability while mining.

When I open Nicehash, it sees the cards, but does not show GPU algorithms to benchmark and therefore won't run.

Logs are attached.  Note that the virtual memory error was due to the first time I ran Nicehash while I was mining with Claymore.  After closing Claymore, it didn't give this error again.

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1443339/log.txt)

**Comment by snowcrawl** [comment]
I would delete v1.8.1.4 and unzip it again.   Then click on NiceHash Miner program to download the miners again.   Starting from scratch, in case something went wrong in the first download.  Be aware that people are having trouble running the benchmark for CryptoNight algorithm for R9 cards

**Comment by DillonN** [comment]
@rockym20 you mean in the benchmark screen the list of algorithms is empty? Could you post a screenshot of this?
