### ISSUE TITLE
Problem with GPU Nvidia

### ISSUE THREAD

**Issue by Aldione** [nicehash/NiceHashMiner#526]
I dont know why but from today im having this problem...

https://imgur.com/a/XqAJl

i hope someone can help me.

Thanks

**Comment by mcsjohn** [comment]
stratum_recv line failed means your rig cannot connect to Nicehash service. Most likely due to low number of shares sent you got a temporary ban. This is not related to NHML but to the Nicehash service.

**Comment by Aldione** [comment]
So, what I need to do? Because I don't know why they ban me :/
It's mean I'm sending too much or I don't send too much ?

**Comment by drkskwlkr** [comment]
@Aldione How about you switch from USA to EU server (if you're near East Coast) or Hong Kong (if near West Coast). This will rule out transient network issues.

**Comment by mcsjohn** [comment]
According to a support case I had with them if you don't generate a valid share every 5 minutes you will get a temporary ban for 1 or 2 days. This happens a lot lately after Cryptonight got profitable. Cryptonight takes a longer time to generate a valid result than 5 minutes for many GPU's. The only option for you, unless you can increase your Cryptonight performance is to wait for the ban to expire and disable Cryptonight. Changing the service location will most likely get your IP banned also to the other service locations.

**Comment by Aldione** [comment]
Now is working... but i had EU Server but sometimes i go to USA Server to start again. But now i had problem with CPU
https://imgur.com/a/fgQLd

i dont know what wrong with my laptop...

**Comment by lmlim** [comment]
@mcsjohn is the share submission requirement counting total submission from 1 ip or counting seperately from each miner session? 
for example: in my i got 1 amd and 5 nvidia cards, amd is running sgminer while nvidia is running ccminer, so there are 2 miner session running. however nvidia shouldn't have problem doing for a share per 5minutes, but amd could have a problem doing it. or do they count total submission from 1 ip?

thanks in advance...

**Comment by mcsjohn** [comment]
I think it counts per IP.

**Comment by DillonN** [comment]
This is likely a result of the CN servers being overloaded. Unfortunately nothing can be done from NHML so I cannot help. If you are still having issues you can open a support ticket like @mcsjohn
