### ISSUE TITLE
How to restart OS when one of the GPUs gets stuck/freezes

### ISSUE THREAD

**Issue by RodAus** [nicehash/NiceHashMiner#527]
Sometimes one of my GPUs get stuck/freezes, I'm not sure what's cause it, overclock is not too high 1500W of 2400W available. I wonder if there is a solution to restart the OS when this happens. Normally after that I can keep the OS stable for another 48 hours.
Thanks for any help

[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1443776/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1443777/log.txt)

`[2017-11-05 14:39:45] [INFO] [CPUDIAG] System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.`

`[2017-11-05 14:39:16] [INFO] [ccminer_NVIDIA-MINER_ID(291)-DEVICE_IDs(0,1,2,3,4,5,6,7)] [pid(4656)|bin(bin\ccminer_tpruvot\ccminer.exe)] Starting cooldown checker`
`[2017-11-05 14:39:17] [INFO] [ccminer_NVIDIA-MINER_ID(291)-DEVICE_IDs(0,1,2,3,4,5,6,7)] [pid(4656)|bin(bin\ccminer_tpruvot\ccminer.exe)] Miner_Exited Will restart in 5000 ms`

`[2017-11-05 14:38:45] [INFO] [NVAPI] Load get failed with status: ERROR`
`[2017-11-05 14:38:45] [INFO] [NVAPI] Temp get failed with status: ERROR`
`[2017-11-05 14:38:45] [INFO] [NVAPI] Tach get failed with status: ERROR`

**Comment by drkskwlkr** [comment]
> I wonder if there is a solution to restart the OS when this happens.

There is a `OnGPUsLost.bat` file that can be executed when a CUDA core is lost. See [https://github.com/nicehash/NiceHashMinerLegacy/pull/268](https://github.com/nicehash/NiceHashMinerLegacy/pull/268)
[https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/OnGPUsLost.bat](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/OnGPUsLost.bat)

**Comment by RodAus** [comment]
@drkskwlkr Thanks this is exactly what happens.
Now I have to figured out how NHML works with .bat files.....5 min later... okay I found a check box, Run script when CUDA GPU is lost.

**Comment by micax** [comment]
any option w AMD ?

**Comment by RodAus** [comment]
@micax My AMD rig have these option. 
Unfortunately I discovered that it does not work. Maybe it's a different problem.
Do you know when the GPU disappears from the Afterburner list? And then the miner start restarting it self trying to mine ... I realized that happens when switch to crytonight for neoscrypt, but not 100% shore. My log shows it above.  Another pattern that I see is the weekend, 80% of the problems is only on weekends. Maybe pool over load and no support. 100% shore there is something wrong with crytonight now 3:40 pm UTC time

**Comment by DillonN** [comment]
Unfortunately the batch script running only works for NVIDIA cards (CUDA GPUs are NVIDIA). There were some issues with CN server load. You should try without any overclock, since this behaviour is the main symptom of a slightly unstable OC

**Comment by RodAus** [comment]
You right, I'm doing this. The problem only happens with Nvidia rigs. Something happens when change miners (for that reason one day maybe use only one miner for all coins or most). AMD rigs no problems at all, rarely does the miner change. But now most of the time the nvidia rigs restarts correctly. For me a great improvement not having to be monitoring 24h. All rigs were tested with Ethos (timing strip OC) plus tuning etc  and ran for weeks with out restart and no problems. I hope one day I can use NHML on Linux, I would be happy to help as a guinea pig. Let's keep walking... Thanks for the support.
