### ISSUE TITLE
gatelessgate

### ISSUE THREAD

**Issue by gennadiv** [nicehash/NiceHashMiner#528]
this miner works with a variety of algorithms could you add it also works with Neoscrypt on all video cards, I checked it myself

**Comment by mcsjohn** [comment]
stratum_recv line failed means your rig cannot connect to Nicehash service. Most likely due to low number of shares sent you got a temporary ban. This is not related to NHML but to the Nicehash service.

**Comment by micax** [comment]
true, voting +1

**Comment by imrecsoka** [comment]
Tihs thing unfortunately caused my grapihcs card to have strange colours on the screen and i had to hard reboot my machine. I then battled for 1 hour to get my 2 GPUs to work. I hate Neoscrypt and i have never YET seen a decent miner for Neoscrypt yet.
I hate it.
I tred NSGminer and Gatelessgate , come on. Nothing to do with Nicehashminer really, but maybe somebody can suggest or give a solution , for AMD RX470 mining cards?
Is it is possible Neoscrypt is more compatible on Nvidia ?

**Comment by gennadiv** [comment]
gatelessgate.exe -k neoscrypt --gpu-platform 1 -g 1 -I 16 -w 256

**Comment by DillonN** [comment]
@gennadiv I can look into this 

@imrecsoka Neoscrypt is indeed much more stable on NV cards, it's supported in NHML for all newer NV cards. In AMD it is supported but it is not stable, and there is currently a check to remove it if your drivers are above a certain version. Looking to have a manual option to disable this check, but that will not make it more stable

**Comment by gennadiv** [comment]
I want you to add it with the ability to switch to it

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
