### ISSUE TITLE
Nice Hash Requires Internet Connection to run (no connection)

### ISSUE THREAD

**Issue by sohachowdhury** [nicehash/NiceHashMiner#529]
Guys, I have got this "Nice hash requires internet connection"
Yesterday my pc was running well and also mining but, suddenly my pc crashed and when i again try to open NHM, it is showing me this error.
PLease guys help me...
![2017 11 05-20 32](https://user-images.githubusercontent.com/33375714/32415773-19cfcc80-c269-11e7-96a2-827322c25116.png)

**Comment by sohachowdhury** [comment]
please help me guys

**Comment by sohachowdhury** [comment]
i have internet speed 26 MBps but, still...

**Comment by bruvv** [comment]
stop commenting on your own post. just edit your first post and dont expect an awnser within minutes....
Anyway just disable the internet connection warning in settings or use the nicehash miner v2 found online.

**Comment by Kayfolom** [comment]
I have the same situation on the last versions. Windows 7, RX480x2. After loading OS (the miner starts 60 seconds after loading) such an error.
Internet connection warning disabled

**Comment by DillonN** [comment]
You can click Yes and NHML will continue to try to connect every ~1min. The problem is newer versions require a more stable connection to NH servers and if there is a firewall or ISP is blocking some connections then you will have this problem. Once a connection is made once you can mine for as long as NHML is open, even after disconnects, but you need to connect at least once to start mining

**Comment by isazon4ik** [comment]
+1, internet connection warning disable, but it does not help :(
1.8.1.4 version

**Comment by Kayfolom** [comment]
The speed of my Internet channel is 800 MBps, the delays to the servers are minimal. But the error appears, and only on one of several computers

**Comment by Spritor** [comment]
Have the same error any solution yet ?

**Comment by danialmoghaddam** [comment]
Can we have an option to silent these alerts and instead let NHML to retry reconnecting? Currently having this alert pop-up and requiring to select an option would be very bad unattended rigs.

**Comment by Knell77** [comment]
ну не возможно сидеть всю ночь возле шахтеров система перезагружается и не видит интернет " Да " не кому нажимать, как по другому решить этот вопрос ?

**Comment by kevinmilesM** [comment]
Here is the fix - https://www.youtube.com/watch?v=QjNLVNANOrU

**Comment by Sav87** [comment]
Используй AutoIt. А если серьёзно то надо ждать пока изменят алгоритм автозапуска и получения данных.

**Comment by Knell77** [comment]
Dear companions, I'm very sorry to part with you. Well, since you can not solve this BAG, I will look for other companions, ... goodbye

**Comment by Knell77** [comment]
Dear companions, I'm very sorry to part with you. Well, since you can not solve this BAG, I will look for other companions, ... goodbye

**Comment by Sav87** [comment]
add Pull request #625

**Comment by xtrime-ru** [comment]
@Sav87 made few fixes, so NHML can use another way of getting SMA data if primary method fails.
I've compiled his fixes and made this release:

https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases
