### ISSUE TITLE
Payout not in BTC

### ISSUE THREAD

**Issue by HyperCriSiS** [nicehash/NiceHashMiner#53]
Hi,

can I configure NHM to act as "normal miner", so I just get the certain coins and they are not converted to BTC?

Thanks,
Hyper

**Comment by ChriscomIT** [comment]
Nope just get the standalone miners for that and configure the pool you want to use. This programs solely purpose is to provide hash power for the NiceHash pool which NH pays you out for but only in BTCs as you already know. But I know they looking into the matter of payout in other alt cryptos. But I don't have any ETA or something like that.

**Comment by DillonN** [comment]
Yes this software is only for the NiceHash platform, which pays in BTC
