### ISSUE TITLE
V1.8.1.4 USD/Day Stats always stays at 0.00

### ISSUE THREAD

**Issue by tj8079** [nicehash/NiceHashMiner#530]
Nicehash V1.8.1.4 doesn't give me the USD/Day Stats, it stays at 0.00 and never updates. I have multiple computers that are all acting the same.
![nicehash usdday](https://user-images.githubusercontent.com/32970403/32416030-51051a7c-c208-11e7-9605-b46a1081f883.jpg)

**Comment by makzkzn** [comment]
This began with version 1.8.1.3 :(
![whatsapp image 2017-11-05 at 21 33 21](https://user-images.githubusercontent.com/33400284/32417903-3df5c0d0-c271-11e7-980f-f8d8f56336ee.jpeg)

**Comment by imrecsoka** [comment]
Never had this before, but i would use another version in the meantime, until developer comes back to you. WC2018 ;-

**Comment by DillonN** [comment]
@tj8079 this happens if NHML was unable to connect to the exchange rate server

**Comment by tj8079** [comment]
@dillonN what do I do? It’s been like this everyday. Is it a firewall issue?

**Comment by DillonN** [comment]
Most likely, yes. You can try disabling firewall. May also be an ISP issue if they are blocking access
