### ISSUE TITLE
Cryptonote Miner 10.1 / 10.2 GPU3 not good speed

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner#531]
![image](https://user-images.githubusercontent.com/25494601/32418935-e9fd9f52-c27a-11e7-8e03-7ad588be4daf.png)
 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1444416/log.txt)

**Comment by DillonN** [comment]
You can use the old version in 1.8.1.5 - https://github.com/nicehash/NiceHashMinerLegacy/tree/1.8.1.5

New version is in beta
