### ISSUE TITLE
statistics error

### ISSUE THREAD

**Issue by igor1352** [nicehash/NiceHashMiner#532]
as to eliminate it what well would work. forgive I don't speak English but this probleia is present at all versions tested by me
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1444486/log.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1444487/log.txt)
![1](https://user-images.githubusercontent.com/33403336/32419620-7efbceee-c285-11e7-8e09-402bce12c1f7.JPG)
![statistaka](https://user-images.githubusercontent.com/33403336/32419624-8b603c24-c285-11e7-9ffb-e7c1501da449.JPG)
here example of good statistics. that that not as it should be with the program
![god statistica](https://user-images.githubusercontent.com/33403336/32438519-7988405a-c2f3-11e7-91b2-2bb1718cfc19.JPG)

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by DillonN** [comment]
@igor1352 sorry but I don't see the problem?
