### ISSUE TITLE
demouser BTC adress

### ISSUE THREAD

**Issue by ChabyCZ** [nicehash/NiceHashMiner#533]
Hello, I would like to ask why is all the reward earned during the benchmark sent to the address below instead of my own defined adress? Likewise, when the address is not filled in and the NiceHash client is in "DEMO" mode or when all settings are erased into the default?
The address is defined as:
public static readonly string DemoUser = "3DJhaQaKA6oyRaGyDZYdkZcise4b9DrCi2";

If you check this adress on NH webpage it says there is about 200-400 working clients for this adress with profit more than $100 daily!
It seems a lot of people is mining for anonym person without knowing it...

**Comment by imrecsoka** [comment]
Good to know, but maybe for the right of the Dev fees? not sure.

**Comment by Nicheuji** [comment]
If it's the dev fee then it should be only 2% of the time. @ChabyCZ said "**all** the reward.."
Hmmn... Did you key in your own address before you started benchmarking?

**Comment by imrecsoka** [comment]
Generally i do, when i start up the miner, i dont leave that field blank, i put in my btc address.
If i use multipool miner also , same thing, it benchmarks and all that effort goes to your wallet, whatever it is, 50 cents to 1 dollar

**Comment by DillonN** [comment]
@imrecsoka the demo user is used if there is no proper BTC address entered. Try mining without any address in, you will see a prompt to mine in demo mode and it will mine to that address.

Most benchmarks are offline and mine to no address. A couple are online only, for those the previous behaviour was to benchmark with demo user as a workaround but most now use a valid address if entered
