### ISSUE TITLE
Cannot run multiple miners with Sgminer

### ISSUE THREAD

**Issue by bmazz731** [nicehash/NiceHashMiner#534]
Hi,

My rig is running 6x RX 470s and 2x RX 580s. It appears that when NHLM attempts to mine anything with sgminer while the 2x RX 580s are mining something else the miner never starts and continuously closes and attempts to restart. 

Essentially it looks like sgminer is not booting up when all the cards are not using it.  I've included my log file and haven't had any other issues I can see so any input would be appreciated. I'm ultimately not sure if this is an issue with NHLM or the miners themselves. 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1444648/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1444649/log.1.txt)

**Comment by jessechan618** [comment]
same issue with me running 3 x RX580 and 2 x RX570

**Comment by DillonN** [comment]
@bmazz731 are you using the blockchain drivers?

**Comment by bmazz731** [comment]
@DillonN My driver version is 17.30.1091.1011-170922a-318486C. All cards can successfully run, under 1 sgminer instance, however if another miner (not sgminer, as I haven't tested two sgminer instances) is running sgminer fails to launch. I believe this may be the same issue I referenced in 548, and if this is please feel free to close/merge these.

**Comment by ZbignevS** [comment]
Im having same issue..

**Comment by bmazz731** [comment]
To provide an update - I attempted running two separate NHLM instances for the different cards, but the issue still occurs.

So when my instance with 6x RX 470s attempts to run sgminer while the other instance is running claymore the sgminer instance goes into it's continuous not starting loop.

**Comment by ZbignevS** [comment]
Its still possible to mine by disabling some algorithms but sgminer

**Comment by bmazz731** [comment]
I'm going to close this out since I think #548 better represents the issue and there is no reason to keep two threads for the same thing.
