### ISSUE TITLE
with amd rx570 sgminer inerrupted

### ISSUE THREAD

**Issue by sunny336** [nicehash/NiceHashMiner#536]
with amd rx570 sgminer inerrupted

**Comment by imrecsoka** [comment]
What does this mean?
Show screen shot or something or what is the question or symptom.

**Comment by sunny336** [comment]
![screenshot 1](https://user-images.githubusercontent.com/31063477/32428873-e35a3d52-c27c-11e7-960a-564614d6ecb9.png)

**Comment by panakota90** [comment]
i have the same problem with the rx 480

**Comment by Crypto-Lord** [comment]
1.  Close some of the duplicate issues you've opened for the same issue. (having multiple tickets doesn't speed up your ticket but rather slows the devs down)
2.  Upload your logs as soon as the issue arises so the devs can pin-point the issue.

I've experienced this issue on and off as mining is occurring. Haven't seen any real interruptions to the mining process as it continues to mine right after it's interrupted.

**Comment by panakota90** [comment]
in my case could stop mining for some time before starts again

**Comment by Crypto-Lord** [comment]
@panakota90 
Upload your log file as soon as it happens so the dev can have a look to see what the problem might be.

**Comment by panakota90** [comment]
![untitled](https://user-images.githubusercontent.com/33430158/32516899-81001c5c-c40d-11e7-9185-3a1a444a0ebe.png)

**Comment by Crypto-Lord** [comment]
log files are located in your NHML folder and named 'log.txt'
That's just your mining window, but I'm not sure this is an issue cuz I get the same thing (sometimes goes for 5-10min) but then mining resumes as normal. Could just be something to do with cryptonight algo itself.

**Comment by DillonN** [comment]
Th problem is with the servers. Try changing service location. Not a NHML problem so closing
