### ISSUE TITLE
SOCKET ERROR - RECEIVE ERROR: socket closed (using mobile data)

### ISSUE THREAD

**Issue by b080180d** [nicehash/NiceHashMiner#537]
![23131753_10159748086975294_1869705431505037419_n](https://user-images.githubusercontent.com/23250436/32433823-3f4abcfa-c317-11e7-9401-7e9ab5270f88.jpg)
![23231118_10159752355805294_3918319874091477145_n](https://user-images.githubusercontent.com/23250436/32433825-3f789896-c317-11e7-851f-4357f03306e2.jpg)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1445641/log.txt)

Windows 7 x64, CPU-i7-6700k, GPU-GTX 690, Legacy 1.8.1.4

After the 3 Nov maintenance, cant connect to mining pool using the mobile data. I'm still able to ping to nicehash mining pool. I have tried all the servers but they have the same issue. Before 3 Nov, everything works fine.

In order to mine now, I have to use the TOR browser and use its proxy to run nicehash. There are some couples of disconnection from the mining pool but nicehash is able to get some hash.

If I dont use the proxy, nicehash is totally unable to connect to the mining pool.

Seek for your assistance. Thanks.

facebook link to my comment in nicehash fb.

https://www.facebook.com/plugins/comment_embed.php?href=https%3A%2F%2Fwww.facebook.com%2FNiceHash%2Fposts%2F1997882260430910%3Fcomment_id%3D1998905473661922

**Comment by mcsjohn** [comment]
Most likely the IP address has a temporary ban to Nicehash due to low number of shares (your IP must send at least one accepted share every 5 minutes). The temporary ban according to their support is for 1 or 2 days.
@DillonN Maybe you can create a Wiki regarding this issue which in the past few days appears very often due to the Cryptonight algorithm being so profitable and of course does not have anything to do with NHML. Unfortunally Nicehash doesn't have an explicit page describing the temporary bans (when it happens, how much does it take and so on).

**Comment by b080180d** [comment]
it is working fine with no disconnection for quite some times before the 3 nov maintenance. so maybe it is not temp ban. im not sure.

**Comment by mcsjohn** [comment]
Before November 3rd, difficulty on Cryptonight was 80000. It increased to 120000, 200000 and now it is 300000. Is you CPU able to generate a result at least every 5 minutes? I don't think so.

**Comment by b080180d** [comment]
hm... i have another system with i5-2400 CPU (lower than i7-6700K) but no issue.  running perfectly. this is running with fixed broadband.
![test](https://user-images.githubusercontent.com/23250436/32442467-83038e94-c336-11e7-819a-47f587bd50f2.JPG)

**Comment by b080180d** [comment]
![test](https://user-images.githubusercontent.com/23250436/32442580-e7ad76de-c336-11e7-9d5c-82959e1453e2.JPG)

this is the one with issue. it is running with mobile data.

**Comment by mcsjohn** [comment]
On the IP of the fixed broadband connection do you also mine with a GPU (or CPU only with many computers)? The idea is that if Nicehash receives an accepted share at least every 5 minutes from an IP, they do not ban that.

**Comment by b080180d** [comment]
for the fixed broadband connection, both CPU and GPU with many computers as well. 
for the mobile data (4G), same deal, both CPU and GPU with many computers too.

**Comment by mcsjohn** [comment]
Behind each IP are your systems able to generate an accepted share at least every 5 minutes? Yes or No? You can always open a support case with Nicehash, because anyway this issue is not related to NHML.

**Comment by b080180d** [comment]
the main thing is nicehash is just started to mine and it doesnt allow to connect to the mining pool and straight away socket error. If u look at the time, 21:09:37, that is the time i start to run. Nicehash is running less than 5 mins. from 21:09:37 to 21:09:47, there is already 2 socket error. from the start to the 2nd socket error is just 10 sec. 

And I guess, yes, the systems can generate an accepted share every 5 mins

**Comment by mcsjohn** [comment]
At 21:09:37 it tries to connect and it fails. Retry is 10 seconds, so at 21:09:47 tries again, without any luck and so on. If an IP gets a temporary ban, it is lifted in 1 or 2 days. Until then you can try a different service location but if the accepted shares are not enough you will get banned also there. Again, this is not a NHML issue, it is Nicehash service. You can open a support case with them.

**Comment by b080180d** [comment]
tried different service location and it is still the same. how can i open a support case? :)

anyway, thank u so much for your prompt reply. I learn something from u

**Comment by mcsjohn** [comment]
Here is the link https://www.nicehash.com/support

**Comment by b080180d** [comment]
appreciate and thanks. :)

anyway, im using a TOR proxy to run nicehash. able to connect to the mining pool and get some accepted shares but occasionally, get socket error. thats all i can do for time being

**Comment by b080180d** [comment]
![test](https://user-images.githubusercontent.com/23250436/32444630-5c700426-c33e-11e7-9e6c-ae1d036652dc.JPG)

this is the temp fix im doing now

but i wonder y the temp fix works but not direct connect

**Comment by DillonN** [comment]
As @mcsjohn said this is a server issue, contact NH support. Closing now..

**Comment by tusharantal** [comment]
Even i am facing the same issue .. help me out ?
