### ISSUE TITLE
XMRig - GPU support

### ISSUE THREAD

**Issue by francescocmazza** [nicehash/NiceHashMiner#538]
Hello,
Would it be possible to add compatibility to XMRig GPU Engines? 
https://github.com/xmrig/xmrig-nvidia
https://github.com/xmrig/xmrig-amd

Thank you!
Francesco

**Comment by riccardoruspoli** [comment]
#484

**Comment by francescocmazza** [comment]
Thank you riki, I didn't see that this had been already proposed.

**Comment by riccardoruspoli** [comment]
Ma prego.
