### ISSUE TITLE
interrupted  amd 580

### ISSUE THREAD

**Issue by dperepust** [nicehash/NiceHashMiner#539]
Stratum connection to cryptonight.eu.nicehash.com interrupted
Amd 580 
 nicehash miner legacy v1.8.2.0 -Pre 
How can fix this problem?

**Comment by minergate0987** [comment]
I have the same. Can anyone help?

**Comment by chadotter** [comment]
I'm having the same problem using ccminer on Ubuntu. I've tried usa and eu without success.

**Comment by MrT63** [comment]
I have the same Stratum connection to cryptonight.jp.nicehash.com interrupted . Tried different servers all with same result.  Using nicehash 1.8.1.4. and sgminer 5.5.5.

I can get interrtups for 6 mins then Accepts then back to 6-8 mins interruption.
![nicehash issue](https://user-images.githubusercontent.com/31526720/32529855-cbdda358-c475-11e7-932f-06f4ab7398e8.jpg)

Graphics card is Sapphire RX 580 8GB on win 7x64

**Comment by The-prophecys** [comment]
I'm experiencing the same issue with version 1.8.1.5. Not sure what this is, but can confirm it behaves exactly the same with all servers. 
GPU: Sapphire R9 380x

**Comment by DillonN** [comment]
This is a server issue not a problem with NHML. See #536
