### ISSUE TITLE
Auto Start on Login - UAC

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#54]
Thank you for adding the auto start on login!!

For those that need to the Miner to run as an Admin (for example Nvidia P0 State is enabled), if the miner autostarts on login UAC will prompt asking to hit yes for the command prompt window to adjust this setting.

Workaround: Turn UAC completely off (not recommended)

Still researching some solutions

**Comment by billmcilhargey** [comment]
I am not sure how you auto start the miner today but you can create a scheduled task with run at highest privileges checked and this will ignore the UAC prompt

https://www.sevenforums.com/tutorials/67503-task-create-run-program-startup-log.html

**Comment by p1r473** [comment]
I use www.r2.com.au/page/products/show/startup-delayer/
