### ISSUE TITLE
"More than 64 virtual cores" dialog box prevents auto-start mining

### ISSUE THREAD

**Issue by chromelined** [nicehash/NiceHashMiner#541]
NHML 1.8.2.0-pre
4 socket server, E7-4870 (80 virtual cores)

The dialog box that warns that CPU mining is disabled prevents auto-start mining from working. Can we get a setting to disable CPU detection, or maybe disable warnings when auto-start mining is selected?

**Comment by DillonN** [comment]
Will look into this

**Comment by DillonN** [comment]
Merge to #452
