### ISSUE TITLE
Result rejected by the pool ( XMR-Stak-NVIDIA )

### ISSUE THREAD

**Issue by chuongmd** [nicehash/NiceHashMiner#543]
![screen shot 2017-11-07 at 12 51 39 am](https://user-images.githubusercontent.com/26231230/32455852-1edb24fc-c356-11e7-9747-634798836f2e.png)

Hi, Is nicehash block xmr-stak-nvidia? I get better hash with xmr-stak than ccminer.

**Comment by DillonN** [comment]
It doesn't have support for NH currently. There will be a new version of it soon I believe
