### ISSUE TITLE
Doesn't do multiple threads

### ISSUE THREAD

**Issue by dormdweller** [nicehash/NiceHashMiner#545]
I didn't see this issue reported so hopefully it isn't a duplicate.  When benchmarking, it grossly under hashes certain cards like a Vega card.  I believe this to be because the vega works best when it is split with two threads per card and intensities of 2012 and 1728 or so.  I should be getting 1850 out of it but nicehash is only giving 1320.  Should be a way we can manually configure the settings for the cards we know the proper settings for or an option to turn on multiple threads for cards we know where it works better for them.

**Comment by DillonN** [comment]
@dormdweller we are waiting for an updated miner to support in NHML for Vega
