### ISSUE TITLE
Disparity in income statistics

### ISSUE THREAD

**Issue by kabylike** [nicehash/NiceHashMiner#546]
In the last 3 days, my Rig /6x Nitro+RX480 8G/ has been working on a cryptonight. NH shows a revenue of between 12.5 and 14 Euro, but statistics on the site show 8.5 euro per day. 
Until 3 days ago he was working on a dager+Lbry, and there was no difference
NiceHash 1.8.2.0 Pre
Windows 10 Pro x64
Driver Radion dag fix Beta

**Comment by DillonN** [comment]
NHML just shows an estimated profitability based on the hashrate of the miner. Many things can affect the hashrate accepted by the servers, such as invalid shares or connection problems, which cryptonight is prone to. Use the profitability on the site as a concrete number.
