### ISSUE TITLE
start mining when idle

### ISSUE THREAD

**Issue by kfadrat** [nicehash/NiceHashMiner#547]
is there a way to set the time that will pass before NHML starts mining? or for example add some programs that force this option not to run? It's really nice thing, but painfull to watch anything on youtube with moving your mouse all the time.

**Comment by riccardoruspoli** [comment]
Yes, in Settings > Advanced > Minimum Idle [s].

You have to write the amount of time in seconds in which the computer will need to be idle before NHML starts to mine.

**Comment by kfadrat** [comment]
i just saw it, must be blind today. Thanks for help.
