### ISSUE TITLE
 1.8.2.0 Pre-release - ClaymoreDual intensity tuning

### ISSUE THREAD

**Issue by Mariusz199** [nicehash/NiceHashMiner#549]
I have a question if you can set the program to automatically turn on and start kicking the computer?

**Comment by pedrojmartm** [comment]
You can activate the option "autostart mining" and put in on the startup folder. thats it!

**Comment by Mariusz199** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
I've already found the option to run with Windows.
 
I know something when there is a better update to improve the program, I mean to make more money and today there was something leap with the graphics card on Lyra2REv2 and if there is something like graphics card AMD will also be in this algorithm?
 
 
 
Dnia Wtorek, 7 Listopada 2017 19:08 pedrojmartm <notifications@github.com> napisał(a)

You can activate the option "autostart mining" and put in on the startup folder. thats it!
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nicehash/NiceHashMinerLegacy","title":"nicehash/NiceHashMinerLegacy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/nicehash/NiceHashMinerLegacy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pedrojmartm in #549: You can activate the option \"autostart mining\" and put in on the startup folder. thats it!"}],"action":{"name":"View Issue","url":"https://github.com/nicehash/NiceHashMinerLegacy/issues/549#issuecomment-342570925"}}}
// ]]>

**Comment by DillonN** [comment]
@Mariusz199, not sure what you're asking. There was an update (1.8.1.5) that improves Lyra2REv2 performance for NVIDIA miners only

**Comment by Mariusz199** [comment]
I have a question why the graphics worked earlier, for example, rx 470 had 21 Mh / s, now they have more than 16 on this new program, the same speed falls on other graphics and eg R9 390X I had 2x after more than 28Mh / s is one has enough and at the second the speed drops for r9 390X that is from yesterday this is happening and for others it's been a long time and why nice program hash as I have RX 550 and RX 580 graphics it shows on RX 550 power RX 580, and on RX 580 power RX 550
