### ISSUE TITLE
Newer Excavator version?

### ISSUE THREAD

**Issue by VincentDatrier** [nicehash/NiceHashMiner#55]
Hi,

In your previous repo, you stated you cannot update Excavator, since you are not allowed to redistribute it.

Now, since NHML is distributed by NiceHash themselves, is there a hope you could bundle it?

Thanks for all the work, keep it up!

**Comment by xChackOx** [comment]
> Now, since NHML is distributed by NiceHash themselves, is there a hope you could bundle it?

Was also wondering this. IMHO NHM and NHML should include the same proprietary miners.

**Comment by billmcilhargey** [comment]
Based on the commits it looks like you decided to remove excavator altogether?

@DillonN

**Comment by DillonN** [comment]
@computeronix It was temporarily removed but that was reverted. In the next release nothing will change re. Excavator

At the moment we are keeping Excavator at the current version. Other performance updates coming soon though!

**Comment by billmcilhargey** [comment]
This should be able to be closed now as its integrated in the latest versions

@DillonN

**Comment by luongk** [comment]
@computeronix The version of excavator distributed with NHML is still a bit behind though eh - 1.1.4a

**Comment by scavern** [comment]
Excavator can be used with Nicehash2 with AMD GPUS, yet I don't see it in NHLM?
