### ISSUE TITLE
Problem with Legacy 1.8.1.5

### ISSUE THREAD

**Issue by Spearhawk** [nicehash/NiceHashMiner#550]
I try to start it and it gets to "getting Nicehash SMA information"
and there it stops saying I do not have internet connection, yet I do.
So I try to benchmark it, and it comes to around 7 and then the entire program vanishes
and so I start it again
again it gets to getting Nicehash SMA information
and yet again it says the same thing
and so I try to start it...
and it keeps on telling me that I need internet connection for it to work
and if I have to try again later.

is it me or is it the servers thats wonky?

**Comment by doverosx** [comment]
I'm currently benchmarking 1.8.1.5 as I reply ;-).

**Comment by Spearhawk** [comment]
![screenshot 2017-11-08 02 14 16](https://user-images.githubusercontent.com/33471053/32526643-c33735f2-c42a-11e7-903c-5c6d4dcaf357.png)


this is as far as I come before it stops...it just pulsates the bar doing nothing.

**Comment by Spearhawk** [comment]
then it jumps to 11 and shuts down the program...

**Comment by Spearhawk** [comment]
![screenshot 2017-11-08 02 17 33](https://user-images.githubusercontent.com/33471053/32526709-1882bfae-c42b-11e7-85f3-00a40142ba80.png)
![screenshot 2017-11-08 02 17 56](https://user-images.githubusercontent.com/33471053/32526711-1bda9f78-c42b-11e7-9918-ce68d3c953c3.png)
![screenshot 2017-11-08 02 18 02](https://user-images.githubusercontent.com/33471053/32526714-1e840d2c-c42b-11e7-85f8-90c9fe6bd083.png)
and this is what happens when I try to start the program

**Comment by Frageron** [comment]
i have same problem on 1.8.1.4 and 1.8.1.5

**Comment by Spearhawk** [comment]
Then it could be servers then, and not me....

**Comment by Frageron** [comment]
i hope so, but seems to me it works for others

**Comment by Frageron** [comment]
I used 1.8.1.4, it was OK. But today (like 4 hours ago) it stopped working and now gets error "Unable to get NiceHash profitability data."
I have tried to use new 1.8.1.5 and old one 1.8.0.2, problem still exists. It's first time for me, used NHML since august everyday (24/7), same rig, nothing changed (sometimes i update my drivers and NHML). 
Any advice what to do?

**Comment by Frageron** [comment]
Tried NHM 2.0.1.4, it works

**Comment by Frageron** [comment]
NHM 2.0.1.4 don't work too, its just saying that mining is active, but nothing mining.

**Comment by Frageron** [comment]
1.8.1.5 working now

**Comment by Spearhawk** [comment]
everything is working for me too now, so I guess it was a temporary problem

**Comment by DillonN** [comment]
Many of the benchmarks will fail if there is a connection problem since they require a connection. 

Glad to see it was a server issue and has passed though, I'll close this
