### ISSUE TITLE
Mining problems with CPU and GPU when they work together

### ISSUE THREAD

**Issue by greg121078** [nicehash/NiceHashMiner#553]
2017-11-06 11:00:00
Hello, since the update NiceHAsh Miner v1.8.1.4 my CPU and GPU no longer work together, WHY? I have to stop either the CPU or the GPU for one of them to work. Plus several times a day the CPUs and GPU mine not all.
Cordially.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1453841/log.txt)

**Comment by DillonN** [comment]
@greg121078 your log doesn't go back far enough, it just shows entries from NHML sitting idle. Can you try mining then repost your log?

If you are unable to mine together it is likely the CPU is too overloaded with the CPU mining. GPU mining requires some available CPU to work properly
