### ISSUE TITLE
Installing Nicehash legacy Miner

### ISSUE THREAD

**Issue by cheema07** [nicehash/NiceHashMiner#557]
I am having trouble installing the legacy miner. I am running amd cards so I am directed to this page: https://github.com/nicehash/NiceHashMinerLegacy/releases

From here I download and unzip the source code off the latest release, but I can`t find a .exe file which I can install off of. How am i supposed to get nicehash running? thanks

**Comment by mrod512** [comment]
@cheema07 You shouldn't be downloading the source, unless you want to build it yourself. Try downloading, NHML-1.8.1.5.zip

**Comment by cheema07** [comment]
thanks

**Comment by github12101** [comment]
resolved, close please.
