### ISSUE TITLE
Add "Previous benchmark speed" values

### ISSUE THREAD

**Issue by perfectlemon** [nicehash/NiceHashMiner#558]
I am sure many people, myself included, are at least occasionally tinkering with GPU clocks and memory speeds (or driver changes) in order to get the most out of mining.

It would be really helpful after completing a new benchmark to see the previous benchmark values, in order to determine if the modifications had a positive or negative impact.

The way I currently do it is by taking screenshots for before and after, but this is quite a bit of a hassle after having to do it more than a couple of times.

**Comment by abbaselmas** [comment]
+1 (y)

**Comment by DillonN** [comment]
This is an interesting idea. I find myself doing similar things. Maybe even a plus/minus showing changes since last benchmark

**Comment by HaTaX2** [comment]
I actually started doing some work with this and can post something up in the next day or so.  It only does the previous benchmark but basically I just copy the current benchmark file to "_PREV" upon successful completion of a benchmarking run.  There's a button just above the start / close buttons that spawns another benchmark window with all the controls removed and the previous benchmark results.

There might be a far more elegant solution for this, such as a manager to store only benchmarks you wished to save with a drop down list or something to compare them with.  Sounds like a lot more work as well however.

**Comment by Dohtar1337** [comment]
Moved to idea backlog. Closing to clean the issues.
