### ISSUE TITLE
Daggerlbr(clymore) Algorithm limit gpu usage?

### ISSUE THREAD

**Issue by voldon** [nicehash/NiceHashMiner#560]
I'm using nicehashminer's AMD version(NiceHash Miner Legacy - AMD) v1.8.1.5 
I'm using HD 7950 AMD graphics card. I don't know how to limit NiceHashMiner from mining at 100% all the time. 

I rad a lot but haven't found any solution on how to reduce usage of it. HELP. thanks!

**Comment by riccardoruspoli** [comment]
Maybe what you're searching is the intensity setting?

**Comment by voldon** [comment]
Thanks.

**Comment by DillonN** [comment]
You have to adjust on a per-miner basis with extra launch parameters. Most miners support adjusting intensity. You can see which params are supported here - https://github.com/nicehash/NiceHashMinerLegacy/wiki/Algorithm-ExtraLaunchParameters
