### ISSUE TITLE
NiceHashMinerLegacy 1.8.1.5 neoscr

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner#562]
AMD Radeon (TM) R9 Fury Series (ASUS) - neoscr bench not worked!
AMD Radeon R7 200 Series - Normal Worked
AMD Radeon RX 580 Series - Benchmark is not available for the test algorithm!
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1456953/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1456954/log.txt)

Windows operating system 10 64-bit (LSTB)

**Comment by DillonN** [comment]
Neoscrypt is a very unstable algorithm on AMD and that is why it is disabled by default. It's not expected that every card will benchmark it, and it is very dependent on which drivers you have installed as well. 

If you're content on getting it to work, the 15.12 drivers seem to work for Fury. Not sure about the 580 but I don't think it is supported
