### ISSUE TITLE
NiceHashMinerLegacy 1.8.1.5 Freezes PC when stopped

### ISSUE THREAD

**Issue by rogerabm** [nicehash/NiceHashMiner#565]
This has been happening since earlier versions of NHML, I've been able to find patches for older versions of Nicehash Miner (not the legacy)
Actually running:
1x 4gb 560
1x 4gb 480 
1x 8gb 480

**Comment by kimpurcell** [comment]
Same here, when I stop NiceHash or if the internet connection goes down, the rig freezes or goes down with it.

**Comment by DillonN** [comment]
@rogerabm what patches are you referring to?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
