### ISSUE TITLE
Intensity is set to 1 but gpu usage is still on 97%(And it overheats)

### ISSUE THREAD

**Issue by voldon** [nicehash/NiceHashMiner#568]
My graphics card is AMD 7950. 

[https://imgur.com/a/0Ir6k](url)

So at the end with default intensity, 4(As I remember) graphics card was loaded on 99% and I had a very hard time to even watch a video online. With intensity 1 it's loading as much as 95.5%. But I would love to know if I somehow can put it as low as 80%. Also, If I can power limit, core limit and clock limit it. MSI afterburner Is set up correctly but once this program launches it somehow overrides it. I have a solution to lower processor affinity(set fewer cores for it) and that works out but, sometimes program restarts and It starts over and I'm afraid that GPU can overheat.
[https://i.imgur.com/AVgEhEo.png](url)

**Comment by voldon** [comment]
Fixed the problem, but it's not the right way to do it. Used Process Lasso program to permanently set CPU affinity and process priority. (program starts with those values even after the restart)

**Comment by DillonN** [comment]
Unfortunately these are all problems with optiminer and can't be fixed here.

I'd suggest you try using Claymore for equihash mining instead, speed should be very similar and it will probably play better with Afterburner. It also has a temperature limit option built into it that reduces intensity automatically, I believe the `-ttli` option
