### ISSUE TITLE
NHML 1.8.1.5 Xmrig hashrate drop

### ISSUE THREAD

**Issue by Simaex** [nicehash/NiceHashMiner#569]
After upgrade to 1.8.1.5 I noticed 10% hashrate drop for Xmrig CPU monero miner. Windows 8|64 Enterprise, I7-3770K CPU, RAM 12Gb, GTX 970 video. Before upgrade I have 204 H/s for Xmrig with stock CPU frequency (3.5), after - 186 H/s. The other CPU miner XMR-STACK-CPU did not show considerable hashrate speed changes and show around 190 H/s. If any additional info may be helpful please ask.

**Comment by medicnick83** [comment]
I've noticed that all my mining PC's are doing minimal.

Where I normally get (in South African rands) R7 a day on a certain CPU, I'm doing R1 or less.

Same with graphics cards, massive drops - something is clearly going on since yesterday or last night.

**Comment by DillonN** [comment]
@Simaex, nothing has changed regarding Xmrig in 1.8.1.5. Are you sure you can get those numbers in 1.8.1.4? Also if you try running Xmrig manually which do you see? You can run with the command line `xmrig.exe -o <Pool-addr> -u <btcAdress>.<worker>:x --nicehash`

@medicnick83 you may be having the exchange rate problem - check #577

**Comment by streaml1ne555** [comment]
> After upgrade to 1.8.1.5 I noticed 10% hashrate drop for Xmrig CPU monero miner. Windows 8|64 Enterprise, I7-3770K CPU, RAM 12Gb, GTX 970 video. Before upgrade I have 204 H/s for Xmrig with stock CPU frequency (3.5), after - 186 H/s. The other CPU miner XMR-STACK-CPU did not show considerable hashrate speed changes and show around 190 H/s. If any additional info may be helpful please ask.

Did you enable locked memory pages and are you running as administrator: https://github.com/nicehash/NiceHashMiner/wiki/Notes-and-hints-on-CPU-mining

If so when's the last time you rebooted. Can you take a screenshot of the xmrig window shortly after starting it?

medicnick83: Part of your profit drop could be due to the BTC price dropping overnight. Also the price for cryptonight orders is not nearly as high as it was a week ago.

**Comment by Simaex** [comment]
@streaml1ne555 No, I do not enable locked memory pages. But the same was with 1.8.1.4 version. I do not run NHLM with admin rights in both cases. I'll try optimisations later, having network issues with Nicehash today (frequent loss of connection) so it is hard to run any optimizations.

@DillonN I returned for 1.8.1.4 for re-check before submitting. Both benchmark and running show similar results. I'll run Xmrig separately as you suggested and update.

**Comment by Simaex** [comment]
Got good advice from @streaml1ne555 and fix speed, now getting 275 H/s for XMR-Stak-CPU after properly enabling huge memory pages. XMRig miner still show unstable performance in range from 170 to 274 H/s. I believe it's due to huge pages initialisation issues. Separate XMrig test have the same issue so now I am not sure that the issue is due to 1.8.1.5 update. But while testing I have feeling that issue is more frequent while running via NHML then directly via command line.
