### ISSUE TITLE
Benchmark - Algorithm - Uncheck - Blue Stays

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#57]
When you uncheck a miner algorithm in the benchmark screen the blue highlight stays rather than going to grey

If you check an algorithm thats grey it highlights blue

The blue does disappear once you hit start however

**Comment by ChriscomIT** [comment]
cuz SMA server down... :-(

**Comment by DillonN** [comment]
I think we should merge this with #21, they likely have similar causes
