### ISSUE TITLE
No benchmark to select for GPU #2

### ISSUE THREAD

**Issue by Ruinous101** [nicehash/NiceHashMiner#570]
I searched and searched but maybe overlooked a thread, please feel free to redirect to another post. Spoiler, I'm new to this. 

I have to two gpu's they're older, 2x evga 770 FTW 4gb. I can mine one GPU only, not sure why, I try to benchmark GPU #2 but I'm not able to select a benchmark. GPU #1 is fine with only a couple benchmarks that are terminated (not a big deal for now). When I mine it always reads mining GPU #0. My assumption was sli, so I have turned sli off and even detached the connection, with no result. Just looking for help to get more mining done while I'm not actively using the computer (i.e.. at work, over night) let me know if you need logs or screenshots. Thank you in advance.

**Comment by DillonN** [comment]
Could you please post a screenshot of what you are seeing exactly? And also your logs/log.txt file will be helpful.

Your intuition to disable SLI was right - it causes a lot of problems with mining

**Comment by Ruinous101** [comment]
GPU #1 benched
![image](https://user-images.githubusercontent.com/33532153/32668948-d7c17fda-c5f3-11e7-809b-abfb042ece61.png)

GPU #2 Not able to bench
![image](https://user-images.githubusercontent.com/33532153/32668971-ea6d6ec8-c5f3-11e7-9da6-1dbdf7fc255a.png)
![image](https://user-images.githubusercontent.com/33532153/32668992-f8860be6-c5f3-11e7-8315-8e5ee599f6c2.png)

GPU #1 running ( GPU #0)
![image](https://user-images.githubusercontent.com/33532153/32669054-2170fb2e-c5f4-11e7-8eea-564af6853fcd.png)

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1462052/log.txt)

Thanks!

**Comment by Ruinous101** [comment]
So I found a work around thus far. 
![image](https://user-images.githubusercontent.com/33532153/32686462-17743300-c65a-11e7-9763-3d87336e7b70.png)
in the config folder the general file I notice one GPU wasn't enabled and just entered in "true" on that line. Then I was able to benchmark but still couldn't mine after benchmarking. 
In the benchmark file for the GPU I then changed the enabled line for the algorithms I wanted to true. No benchmarks run and can now mine both GPU's. 
![image](https://user-images.githubusercontent.com/33532153/32686533-23cbaccc-c65b-11e7-8bc3-04273ad3c527.png)

We'll see how this goes for now.

**Comment by DillonN** [comment]
@Ruinous101 just to make sure - when you check the second GPU, you do click on it in the list view? Just checking it will keep the algorithm list on the first GPU (and all algorithms will be grayed out since that GPU is disabled). 

As a workaround, like you found, you can copy the algorithm section of the settings. Since the GPUs are the same there shouldn't be much of a difference in speeds
