### ISSUE TITLE
Wrong profitabilty

### ISSUE THREAD

**Issue by tdkavngr** [nicehash/NiceHashMiner#572]
NHML showing me 1/10 profitability of what I usually get... is this just a bug or am I only getting 1/10 profits?

**Comment by etmot** [comment]
You're not alone brother, I'm getting the same  error with my Nicehash legacy app. i hope they fix this issue.

**Comment by Ragner26** [comment]
Same here, @DillonN can we get an answer regarding the problem?

**Comment by rafatec2017** [comment]
Hello, I'm also having the same problem. Yesterday was making 10.00 BRL per day with Criptonight and this morning is making 2.80 with two RX 480. I hope to be compensated for this

**Comment by rafatec2017** [comment]
Hello, I'm also having the same problem. Yesterday was making 10.00 BRL per day with Criptonight and this morning is making 2.80 with two RX 480. I hope to be compensated for this

**Comment by DillonN** [comment]
Hey guys I made a separate issue for this - #577. Please direct conversation there
