### ISSUE TITLE
Problems showing correct value

### ISSUE THREAD

**Issue by rafatec2017** [nicehash/NiceHashMiner#576]
Hello good Morning
Something is going wrong
Today when I went to check the amount to the day, check that it is making 2.95 BRL being that yesterday was 8.90 BRL. What could be happening?
Follow printscreen
Thank you

**Comment by rafatec2017** [comment]
Hello good Morning
Something is going wrong
Today when I went to check the amount to the day, check that it is making 2.95 BRL being that yesterday was 8.90 BRL. What could be happening?
Follow printscreen
Thank you

**Comment by DillonN** [comment]
Check issue #577 this is probably the problem
