### ISSUE TITLE
NiceHashMinerLegacy 1.8.1.3 GTX 670 gets only 170H/s Cryptonight

### ISSUE THREAD

**Issue by tmloc** [nicehash/NiceHashMiner#579]
I did some research and found out that the GTX 670 should normally do atleast about 300H/s on Cryptonight.
Everything else works just fine (FX-6100 running at 195H/s at the newest Version of NiceHashMiner 2).

Thanks in advance!

**Comment by DillonN** [comment]
I do not have a 670 to test with. If you can find a better ccminer version for CN then you can try to use it by [customizing paths](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Customizing-ccminer-and-sgminer-paths)

**Comment by chelnydiablo** [comment]
попробуй в доп настройках включить      -l 33x15   на 660GTX  дает 290h/s

**Comment by tmloc** [comment]
Can you post your config file for CC miner?

**Comment by 1001rapid** [comment]
gtx 670 hashrate in this ccminer fork - https://github.com/KlausT/ccminer-cryptonight/releases/
-l 28x14 290
-l 28x7  160
-l 56x7  280
-l 63x7  310
-l 70x7  320
-l 77x7  338
-l 84x7  335
-l 91x7  340
-l 49x14 340
-l 14x49 260
-l 56x14 350
-l 63x14 350 
-l 70x14 - out of memory
-l 35x21 345
-l 42x21 306

Warning:  this fork not support API

**Comment by DillonN** [comment]
@1001rapid that is the fork used for CN in NHML already. I will look at updating it to the newest version - but it does not look as though there have been performance increases 

I will close this as it seems to be solved with changing the intensity flag
