### ISSUE TITLE
How does someone build clone source?

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner#58]
This is a real problem as I don't know how to build.  Anyone Wanna help me?

**Comment by DillonN** [comment]
You can build the main program in Visual Studio 2017, [more detailed instructions here](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Development)

**Comment by HardikKSavaliya** [comment]
There is Issue with build project, Please @DillonN let me know how can i find bin file.
Thanks
