### ISSUE TITLE
What is the minimum RAM and/or page file size for dual mining? (Getting RADAR_PRE_LEAK_64 EthDcrMiner64.exe)

### ISSUE THREAD

**Issue by rosdi** [nicehash/NiceHashMiner#581]
I have a mining 'rig' with 2 1070s and 1 1080 Ti, the 1070 has 8Gb VRAM and the 1080 Ti has 11Gb VRAM, 

- Total combined VRAM is 27Gb. (2x 8Gb + 1x 11Gb)
- The mining rig has only 4Gb RAM.
- The page file size has been set to 20Gb.
- It is Windows 10 Home Edition 64 Bit.
- I am running NiceHasMiner Legacy v1.8.1.5

Whenever I run NiceHashMiner, it will run but freeze within 30 minutes to 1 hour! I checked the windows Event Viewer and saw this error:

Fault bucket 129397369552, type 5
Event Name: **RADAR_PRE_LEAK_64**
Response: Not available
Cab Id: 0
Problem signature:
P1: **EthDcrMiner64.exe**

Looks like there is a memory leak? Or my rig just has too little RAM? 

The wiki isn't very clear about this: https://github.com/nicehash/NiceHashMinerLegacy/wiki/Ethminer-Tips

"...you need to have enough RAM **or** virtual memory if you are running multicard setup; on 6 card setup virtual memory (pagefile) needs to be **at least than** 32 GB;"

It says '**or**' (not '**and**'), so it is _either_ large RAM or large page file right? My rig should be fine right?

Also what does '**at least than**' means?... at least _greater_ than? a missing word??

"**6 card setup**" also very subjective.... 6 cards with 3Gb VRAM (GTX 1060) is less than 2 cards with 11Gb VRAM... (GTX 1080 Ti) can somebody advise?... I can update the wiki if necessary...

**Comment by DillonN** [comment]
That section of the Wiki is outdated. ClaymoreDual does require lots of memory, but (available) pagefile + physical memory is what matters mainly. You can try mining with some cards disabled to see if the lower RAM usage fixes your issue. Unfortunately if it is an issue with ClaymoreDual there is not much that can be done on this end.
