### ISSUE TITLE
Illegal memory access in Lyra2REv2 using legacy 1.8.1.5

### ISSUE THREAD

**Issue by SirBigRed** [nicehash/NiceHashMiner#582]
I have seen a drop in miner profitability lately even when bitcoin price is still high. I have also noticed these errors with miners when running legacy from ver 1.8.1.4 pre 3 to the new version. I have noticed equihash spends a bit of time on idle. Is anyone else experiencing these issues?
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1463109/log.txt)

**Comment by DillonN** [comment]
This sounds like an instability issue - either with miners themselves or HW/OC, not a NHML problem. Please restrict issues here to NHML program
