### ISSUE TITLE
Claymore miner locks up entire machine.

### ISSUE THREAD

**Issue by b1nd3r512** [nicehash/NiceHashMiner#583]
Hi

Since 2-3 days ago, anytime NHML uses an algo from claymore it works for about 30 minutes then a second window of claymore opens.  Fans still spin on all my gpus as if they are mining but go ice cold after a while due to the actual cards not doing anything. When i try to close NHML the main app closes fine but the miners do not.  i have tried using task manager to stop the process but to no avail.  Only a manual power off on my rig resolves, as windows doesnt shut down at all when claymore miner is frozen. I also cannot access msi afterburner as well once this happens until a restart. the funny thing is SG miner works perfectly unfortunately the hashrate and returns on this are not as good as the claymore miner. I have tried to disable the CoolDownCheckEnabled": true to false as per another thread but this did not solve my issue. please can someone help. im not highly skilled in all this so please let me know what other info is needed and i will send through the details.

Kind Regards

**Comment by rakanishu82** [comment]
Same here (with Claymore Cryptonote). Driver AMD Crimson 17.11.1 (switched to compute), rx 460/470/580, win 10 x64, 16Gb RAM

**Comment by diablom** [comment]
had this issue also on 3x570

**Comment by DillonN** [comment]
If the Claymore executable is going rogue and not responding to close requests, nothing can be done in NHML. Default behaviour of NHML is to restart a miner if it cannot communicate, disabling the cooldown checker will disable this. 3rd party miners are closed source and used at your own risk - I suggest you contact Claymore if you are having these issues persistently
