### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by Virtuon** [nicehash/NiceHashMiner#584]
Hi,
I want to say few words about usability and user interface. Very uncomfortable is absent feature like grouping cards for choosing algorithms. I have 8 cards rigs and every time (even after NHML update) I have to choose algorithms to mine and benchmark for every card. It's a lot of stupid mechanical work to do. I know I can copy benchmark values to other cards but I can't copy my algorithm choices for other cards. What you can to improve? Just add card grouping where user can choice algos for whole group or algorithm choice copy to another cards. Even "Select all / select none" feature is absent. That's pity.

**Comment by DillonN** [comment]
You shouldn't have to change any settings after you've set them once. The settings are transferred upon update if you follow the upgrading instructions

**Comment by DillonN** [comment]
Will look into adding better grouping options for cards. As a workaround to speed up settings now, you can copy the contents of the json device settings files
