### ISSUE TITLE
NHML1.8.1.5 CryptoNight new always start, although it is unchecked.

### ISSUE THREAD

**Issue by Paapo** [nicehash/NiceHashMiner#585]
Hi,

I have a rig with 5 AMD RX470 and 1 AMD RX580. Once i Benchmark both claymore versions, the old and the new one and then start mining with only CryptoNight_old checked for mining, the RX580 CArd always start with Claymore 10.2, although the new Version is unchecked under Settings.  If i only Benchmark the old Claymore Version, it works.

The RX580 Benchmark is OK, with Claymore 10.2. But it is showing the same issue like in the previous versions. After Start mining with the RX580 and Claymore 10.2 the GPU is frequently droppimg to Zero, every 10 seconds. So, the hashrate is much to low.

Connection issues with the DevFee Server are also still there. I have to use the .nofee Option, otherwise the Connection to the DevFee Server will disconnect every 10 minutes, because there is no traffic.

Many Greatings,
Marcus

**Comment by DillonN** [comment]
Can you post your logs/log.txt file?

**Comment by Paapo** [comment]
@DillonN Not right now. I´ve uninstalled 1.8.1.5 and rolled back to the only really working version for me, 1.8.1.3. Escept some DevFee Connection issues. Both newer versions are only bringing trouble. And it always takes a lot of time to test and configure for new. Because i´m always doing a clean installation, with new benchmarks. l´ll wait for the next version.

If i find the time, to install it again, i´ll post the logfiles.

Kind regards,
Paapo
