### ISSUE TITLE
Claymore miner restore OC to default value

### ISSUE THREAD

**Issue by nin3tin** [nicehash/NiceHashMiner#586]
my miner goes to black screen around 10 seconds and restore it self to default value from OC. It usually occurs when nicehash is changing algo.

I have been using my OC settings since February and i doubt i OC it too much. 
It only happens in the latest version and switch back to 1.8.1.2 and i never encountered such issue.

using RX and r9 in 1 rig, using blockchain driver.

**Comment by DillonN** [comment]
Please confirm you have the issue on stock clocks. If blackscreen does not occur on stock clocks - it is an OC issue
