### ISSUE TITLE
how to fix error shares rejected

### ISSUE THREAD

**Issue by woodilll** [nicehash/NiceHashMiner#587]
100% shares rejected.
NHML 1.8.1.5 version
windows 10 pro
video card Radeon HD 6870
algorithm cryptonight (claymore_old)
How to fix the error?
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1464158/log.txt)
![error](https://user-images.githubusercontent.com/33575835/32694030-d9d0753c-c73e-11e7-88cf-bb8bf0ee1de8.jpg)

**Comment by DillonN** [comment]
This suggests a hardware problem. In any case, this is not an issue with NHML, try getting help on miner forums
