### ISSUE TITLE
Only two algorithms on 1.8.4.1 and 1.8.5.1

### ISSUE THREAD

**Issue by 308moo** [nicehash/NiceHashMiner#588]
I downloaded and installed NiceHashMinerLegacy for AMD 1.8.4.1 and 1.8.5.1 for a new PC and I only see two algorithms Cryptonight XMRStack CPU and Xming.

I have two other GPU miners running 1.8.4.1 and they both have over a dozen algorithmic listed.

The bin file in the NH miner directly has all 265 files, none of the executables were quarantined by any anti-virus program, NH miner just doesn't seem to recognize them. In settings I have the use 3rd pary miners box checked.

How can I get all the other miners to show up so it can use them?
Running Windows 10-64 bit, the PC and AMD GPU's are similar to what is in my other 3 pc's where NH miner works.

**Comment by HaTaX2** [comment]
Take a look in your log.txt file to see what's happening with the detection of the cards.  Just to keep things clean and simple, close NHML and delete the log.txt file, then reopen it and let it finish starting up.  Then open the log.txt file, it shouldn't have too many lines in there and you should find a section where its trying to detect the GPUs.  Post up what you see here and we can help point you in the right direction.  Also you could compare the logs from the working and non-working PCs, it might shed some light on what's happening.

**Comment by 308moo** [comment]
I closed the app, renamed the log files, and relaunched it on both pc's.
 Here are the two log files, both 1.8.5.1, one from a HD 7990 AMD rig that has 23 algorithms listed and the other from a 2x AMD RX480 rig that only lists two. The 480 rig has a RX480 Strix and a RX480 gaming, both are running the same version of driver.

What  I noticed in the 480 rig log was "AMD GPU device count BAD!!!" but both GPU's show up in the NH device list and both will mine. No problems in device manager or anywhere else I look.

I've even tried deleting and reinstalling NHLM. During the install it DL'd the bin file, unzipped it, installed and set up the miners and did the same with the 3rd party miners but when I run it and do the benchmarking, only the two Cryptonight algorithms show up again. It says 0/24, like it's doing the benchmarking, it takes as long as the other pc that has 23 benchmarks shown but when it's done, only the 2 show up.

Thanks in advance for your help.


[only 2 algorithims-log-NHLM 480 rig.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1466306/only.2.algorithims-log-NHLM.480.rig.txt)
[OK-log NHLM 7990 rig.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1466307/OK-log.NHLM.7990.rig.txt)

**Comment by DillonN** [comment]
@308moo could you post a screenshot of what your benchmark window looks like please?

**Comment by 308moo** [comment]
Here's a screenshot of the benchmark window
Before I closed the mining window it was mining with both gpu's using sgminer, even though sgminer isn't listed in the benchmark window.

![benchm](https://user-images.githubusercontent.com/33599961/32776375-eb1e7e42-c964-11e7-83b4-884d3f01be49.jpg)

**Comment by HaTaX2** [comment]
You need to click on the other devices in the benchmark window from the top 'Device' list, when you select one of the GPUs you'll find the bottom list will update to reflect the miners available for that device.

**Comment by 308moo** [comment]
There's nothing to click.  Both of my GPU's are already selected. If I click on the CPU, the two cryptoNight algorithms are highlighted in green. If I deselect the CPU the green highlighting on the 2x cryptonight algorithms goes away.When I click on either of the GPU's, no more algorithms show up, only the GPU in the top box I selected turns green.

The only algorithms that show in the list are for the CPU. None of the other PC's I run NiceHash Legacy miner on even show the CPU. On those machines, like you said, you select a device and it shows which algorithms will run on that GPU. Not this one.
It seems to have run all the benchmarks (24 of them) but for some reason they are never displayed and so I can't select or deselect any.  I'm not sure how any other miner programs or algorithms, I only recall it running cryptonight on sgminer 5.5.5  

I'm not seeing anything different in the Settings,  General, Advanced or Devices/Algorithms tabs from the other PC running NHLM

**Comment by HaTaX2** [comment]
That is really weird then...  I'm not sure what's going on there, but I think having the config files might be helpful to troubleshoot this; so we can see what NHML is detecting, benchmarking, and saving to file.  Can you upload the files from your 'Config' folder? 

BTW, you won't see any algos enabled for older CPUs that don't support AES-NI. Without support for that instruction set they're not really suited for mining these days as they're not fast enough.

**Comment by 308moo** [comment]
Here's a zip of the config files. I compared them to the config files of the pc's that are showing the 24 or 26 algorithms normally and although a few are disabled on this pc, more are disabled on the pc's that show all the algorithms.

Thanks again, let me know what you notice.

[configs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1473476/configs.zip)

**Comment by DillonN** [comment]
@308moo are you clicking on the actual line for GPUs, or just the checkbox? Clicking on the checkbox will not change the list of algorithms shown, you need to click on the part with the name

**Comment by HaTaX2** [comment]
I took a brief look at the config files and didn't notice anything odd, other than the benchmark files having the PCI ID info in them instead of a GUID/UUID string like I see on all my systems.  Looking at the AMD GPU count bad error in the log, it didn't appear that would actually cause a problem. (Where it's counted in ComputeDeviceManager.cs by the presence of "amd" in vidCtrl.Name)  It looks like it's just counting at that point and reporting, I didn't see anything after that error that would prevent it from being displayed.

As a note on that, I think his card isn't being counted because it doesn't have "AMD" in the GPU name and instead just has "Radeon".

**Comment by 308moo** [comment]
The problem is solved, what caused it was NiceHash detecting my CPU (it never did on any of my other PC's) and selecting that as the default so it only showed the algorithms for the CPU miner.
If I clicked on the text of the GPU's in the Devices box, then the algorithms for the GPU's showed up.

I don't think I ever had to click on the name of the GPU in any other installations or on any other PC's and that because there was no CPU displayed and the GPU was the default. I thought checking the box would enable the GPU, I didn't know there were two things to select in the device list.

Thanks for your help.

**Comment by DillonN** [comment]
Glad you got it working
