### ISSUE TITLE
### Request ### : Add failover pools and auto switch pools between USA and EU

### ISSUE THREAD

**Issue by lmlim** [nicehash/NiceHashMiner#590]
Hi Dillon,

every now and then i saw my miners have problems connecting to nicehash pools (not very often thou).
but when it happened my rig was unproductive, waiting for reconnection etc....
it would be great if if NHML has auto switch pools if it encounter errors/slowness etc...

Also, auto switching between USA and EU pools/servers based on profitability would be awesome too.
at times, I saw a few cents difference between the 2 sites.

Thank you.

**Comment by DillonN** [comment]
This would work well with miners' built in failover, unfortunately not all miners support that

**Comment by mcsjohn** [comment]
In my PR https://github.com/nicehash/NiceHashMinerLegacy/pull/491 I have made this change and activate it for xmrig. I don't know and honestly didn't searched which of the algorithms have multi-pool failover but when I have the time I will do it for more algos.
