### ISSUE TITLE
[NHML 1.8.1.5] CPU and GPU Have Had a Falling-Out

### ISSUE THREAD

**Issue by Snowy-Fox** [nicehash/NiceHashMiner#591]
I'm running NiceHash Miner Legacy v1.8.1.5 with an AMD FX-8320, NVidia GeForce GTX 980 and a Radeon RX Vega 64. After a reformat and another day of relatively normal mining, I decided to benchmark everything again. But since doing so, my Vega 64 can't seem to mine anything while the FX-8320 is also mining. [Another recent post](https://github.com/nicehash/NiceHashMinerLegacy/issues/553#issuecomment-342865271) mentioned that "the GPU requires some available CPU to work properly," but up until yesterday, this wasn't an issue. All three could mine quite happily together. The GTX 980 still works fine alongside the CPU. The Vega, specifically, doesn't. Any advice on how I can reconcile my two AMD devices?

**Comment by streaml1ne555** [comment]
Try increasing less threads in the cpu miner extra settings so that more resources are available for your GPU miners. You could also try to manually set the CPU miner process to low or idle priority in Task Manager and see if that helps.

**Comment by Snowy-Fox** [comment]
Where do I access the CPU miner's extra settings?

EDIT Ooh, I found it - Settings > Devices/Algorithms > hilight algorithm and it's on the right hand side. Just reducing the number of threads by 1 has fixed the problem. Thanks a lot! ^^

**Comment by zeta009** [comment]
@Snowy-Fox The GPU will run if you use the fury cause the fury will help to
raise your FX-8320 and the Radeon RX Vega 64.  use usb fury to make work
more properly.

2017-11-13 18:33 GMT+07:00 Snowy-Fox <notifications@github.com>:
