### ISSUE TITLE
lira2rev2

### ISSUE THREAD

**Issue by Razmikun** [nicehash/NiceHashMiner#592]
здраствуйте я прошел бенчмарк всех алгаритмов кроме лира2рев2 пишет отменен почему?

**Comment by Kayfolom** [comment]
Отключите все алгоритмы кроме lira2rev2 в настройках, установите для этого алгоритма произвольную скорость бенчмарка вручную и запустите майнинг. В окне майнинга вы возможно увидите причину.

**Comment by Crash911119** [comment]
у меня этот алгоритм вышибает карты 1060 ((((
