### ISSUE TITLE
Nice hash miner crashes pc

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#594]
When I have claymore 10 running outside of nice hash miner it works fine but when I run it through the application. It cause my pc to go into an unusable state and freeze, CPU is staying under 50C and there should be adequate air flow.

I'm mining with a amd rx 560 4gbs with gpu only on windows 7 sp1  with a skylake 64bit pc cpu. Current firmware and drivers installed. I also tried with and without 3rd party miners with same result.

Thanks

**Comment by adrientaste** [comment]
Same problem here with my rx vega 64haha if you have a solution im here

**Comment by DillonN** [comment]
Which Claymore are you using? If it is the cryptonight one have you tried using the other entry for it

Could you post your log/log.txt file?

**Comment by techman05** [comment]
It was claymore 10.1  but atm the nicehash miner has decided to use nightcrypto and I haven't crashed though its now mining 7Gh i stead of the 11-13 it was registering(though I don't think its mining eth coins right now).

A whole lotta new benchmarkable coins just popped up so I think the app hasn't used claymore in a while.

Sent from TypeApp<http://www.typeapp.com/r?b=11053>
On Nov 17, 2017, at 12:42 AM, Dillon Newell <notifications@github.com<mailto:notifications@github.com>> wrote:

Which Claymore are you using? If it is the cryptonight one have you tried using the other entry for it

Could you post your log/log.txt file?
