### ISSUE TITLE
Make windows with miners visible when benchmarking

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner#596]
Make windows with miners visible when benchmarking. 
Miner is positioned for experienced users and invisible windows greatly interfere with the diagnosis of problems. Thank you in advance!

**Comment by DillonN** [comment]
Most miners have their console output redirected to NHML during benchmarking, so making the window visible doesn't help (just shows a blank window). Really this isn't feasible with the current structure
