### ISSUE TITLE
2.0.1.4  many rejections

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner#597]
many rejection failures, more than 5% (Win 10 64 -bit, 3 - 1070 + 1 1080 NVIDIA)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1470133/log.txt)

**Comment by bruvv** [comment]
wrong version/app

**Comment by DillonN** [comment]
You are not using NiceHash Miney Legacy, you can contact NH support
