### ISSUE TITLE
Request: Enable SHA-3 algo for GPUs

### ISSUE THREAD

**Issue by xChackOx** [nicehash/NiceHashMiner#60]
Hi! Just a request. I've been experimenting with Awesome Miner and the NiceHash service and noticed that Awesome Miner switches to SHA-3 algo from time to time, giving good profits (higher than ClaymoreDual). Is there a chance that it could be enabled in NHML for the next version? I'm using nVidia GPUs.

AM is calling CcMiner SP-mod 1.5.81 for this algo.

![untitled-1](https://user-images.githubusercontent.com/29616824/28500278-67bb161c-6f93-11e7-99c5-82e349706378.jpg)

Only reason I'm using AM right now is because of this.

**Comment by xChackOx** [comment]
After tweaking hashrates values and using the same ones provided by NHML benchmarks, SHA-3 is definitely more profitable than ClaymoreDual. I manually benchmarked keccak with ccminer.

![image](https://user-images.githubusercontent.com/29616824/28500827-80ac1cca-6f9d-11e7-8a18-270a0e6e3058.png)

**Comment by billmcilhargey** [comment]
Nice yes dont see a reason Keccak couldnt be enabled since it is supported for AMD and Nvidia GPUs and already using ccminer as part of the build (just needs added)

Also on the profitability page https://www.nicehash.com/?p=calc Keccak scores will need to be added (at least when I looked for Nvidia 1080 Ti GTX

**Comment by ChriscomIT** [comment]
Would be very nice to see this addition.

**Comment by DillonN** [comment]
Thanks for posting! It looks more profitable for me too on 1080 Tis, I'll look into getting this in an update ASAP.

**Comment by ChriscomIT** [comment]
Great news! Thank you @DillonN !

**Comment by DillonN** [comment]
Activated for AMD and NVIDIA as of 67cebce9eb59a58683a5e0a026a18608bf120c93, will do some testing and it should be live in the next release

**Comment by ChriscomIT** [comment]
Wui that was fast! Looks very good! Thanks again. Looking forward to the next release!

**Comment by xChackOx** [comment]
Excellent @DillonN That was fast! Thanks!

**Comment by xChackOx** [comment]
Closed issue by mistake. I'll leave that to you @DillonN

**Comment by francescocmazza** [comment]
Looking forward this update too!!
Great work guys for finding this out and thank you DillonN for working on implementing it!

**Comment by billmcilhargey** [comment]
Thanks so much!

**Comment by billmcilhargey** [comment]
This update has been released

https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.0.2

Feel free to close @DillonN
