### ISSUE TITLE
Nicehash does not detect 2nd cpu

### ISSUE THREAD

**Issue by denjcodes** [nicehash/NiceHashMiner#601]
I have a two cpu x5675 and only one is detected by NHML.  
![capture](https://user-images.githubusercontent.com/14024078/32808236-5881009a-c960-11e7-9afb-b59cf9385c72.JPG)

When I check the CPU utilization, 6 cores are at 100% utilization, while 6 cores are at 50% utilization.  

The picture attached shows my rig setup:  X5675 x 2, RX840 and HD 7800 (both AMD)

**Comment by DillonN** [comment]
NHML doesn't have full support for dual CPUs, but the underlying miners will. Xmrig should automatically run the most optimal setting, but I haven't checked xmr-stak. Note that optimal performance for cryptonight is usually NOT 100% CPU utilization, since it is more dependent on cache

**Comment by denjcodes** [comment]
Is there any way I can improve utilization by running multiple instances of NHML?

**Comment by DillonN** [comment]
I don't believe a second instance will help, you can customize the affinity through extra launch parameters though to force which cores are mining. See some discussion on #593 related to this, or you can google it for Xmrig specifically. If you do still want to use a second NHML instance, this affinity setting can let you bind an instance to one CPU

**Comment by denjcodes** [comment]
It seems that I couldn't improve on the optimal settings by setting --cpu-affinity 0xFFF --av=0 .  I assumed I was doing something wrong because I saw someone else with the same cpu(s) as mine but having two cores show up.  [#427](https://github.com/nicehash/NiceHashMiner/issues/427)
