### ISSUE TITLE
CryptoNight problems with NiceHash Legacy 1.8.1.5

### ISSUE THREAD

**Issue by mifurman** [nicehash/NiceHashMiner#602]
I have problems with CryptoNight problems with NiceHash Legacy 1.8.1.5
I tested it many times (and reloaded the software many times too) but I have been having problems benchmarking CryptoNight on my Xeon E5-2696-v2 with different AMD GPUs (RX580, Vega 64 and Vega 56). It takes for ever to benchmark it and if I wait a very long time, this algorithm is still having problems (stopping). It takes relatively little time to accomplish it with version 1.8.3.1 that I am still being forced to use.

Could you please clarify the issue?

Thank you,

Michael

**Comment by BARUCHER777** [comment]
I have the same problem with 580 and Fury (Win-10_64-BIT)

**Comment by mifurman** [comment]
Here are my experience, I got today. In short, NiceHash Mineer Legacy 1.8.1.5 is unstable, especially with Vega 64. I am running Windows 10/64 on Intel i5-7600K  (ROG motherboard) +16GB RAM. I am using AMD driver Win10-64Bit-Crimson-ReLive-Beta-Blockchain-Workloads-Aug23. I have Vega 64, Vega 56 and RX480 in the system. Both Vegas have GPUs underclocked and MEM overclocked to 920 MHz (Vega 56) and 1100 MHz (Vega 64). If the system works, I get 4.6 kH/s CryptoNight. Quite often though CryptoNigh does not recognize Vega 64. In other words (and this can manifest itself already during benchmarking) CryptoNight algorithm has a problem in Legacy 1.8.1.5.
I even disabled HBCC, suspecting it of causing instability. 
I saw the issues with RX580 as well.  I am being forced to run 1.8.1.3 that does not achieve such good results

Please have a look into the issue.

Regards,

Michael

**Comment by DillonN** [comment]
Benchmarking xmr-stak-cpu will take a long time on high core CPUs

There is not yet full support for Vega GPUs. In 1.8.1.5 there should be 3 cryptonight miners for Vega. Have you tried them all? The Claymore CN should have the best Vega support

**Comment by mifurman** [comment]
Thank you. I will try experimenting again with 1.8.1.5 on one of my systems
