### ISSUE TITLE
Enhancement: Cast XMR Miner for Vega and RX480/580 cards

### ISSUE THREAD

**Issue by hotrock3** [nicehash/NiceHashMiner#606]
Cast XMR produced a 20% increase output over Claymore on my 580s without any additional changes. Would be great if it could be integrated into NHML.

**Comment by imrecsoka** [comment]
How did you manage to use it, or rather how in english did you use it.
Please tell me the steps you followed for cleanup or driver install and stuff?

**Comment by hotrock3** [comment]
I already have the blockchain driver installed so all I had to do was modify the launch bat to contain my nicehash details (stratum and payment address) and then indicate which GPUs to use. As it only supports Vega and 580/480s right now I had to set it to use only my 580s using -G 0,2.

**Comment by DillonN** [comment]
Usually we only integrate miners that have a proper API so it can interact with NHML properly. It also looks like getting benchmarking on Cast XMR will be very difficult. We are currently waiting for the new xmr-stak version which has better CN support in AMD GPUs. Also, Claymore CN 11.0 is slated to be released

**Comment by hotrock3** [comment]
Thanks Dillon, great explanation and update on what's to come.

**Comment by sooth** [comment]
> Also, Claymore CN 11.0 is slated to be released

Do you have a source? This would make my day.
