### ISSUE TITLE
so confused with all the Nicehashminer versions

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner#607]
https://github.com/nicehash/NiceHashMinerLegacy/releases
OR
https://github.com/DillonN/NiceHashMiner
I dont know what site to use now for downloading , and what is the decent version to get,
I tried a recent version , forgot the version and forgot where my post is.
I want to add XMRIG to my current version since it only has XMR-STAK-CPU.
I am very happy with getting 5 to 10 cents more.
How would i go about doing this?
If i use NHML-1.8.1.4-Pre3 , the claymore cryptonite miner is cripled as i only get half speed on my 3rd GPU.
This is why i want to rather use another version, example NiceHashMiner1.7.5.16-DillonN or whatever it doesnt really matter i am so confused with the releases now and the authors i dont know my uncles name anymore.
So yes, its not Bob.
I just want XMRIG in my nicehashminer i am using now which is NiceHashMiner1.7.5.16-DillonN .

I also wish somebody can explain to me properly how to get CAST XMR to work properly , i.e. at a proper hacked speed, I tried to follow Gandalph3000's instructions but i failed.
I downloaded the 23 August Block Chain Drivers and then the  miner started with no issue about missing blockchain driver message ... BUT then it just quit.
I noticed that all miners such as Claymore whatever and SGMiner also just quit.
No idea what the hell is going on, and what planet i live on because everybody seems to be having fun.
Sorry this is lengthy but I do not know how else to reach out besides logging 2 threads for each issue.

**Comment by mifurman** [comment]
I would also like someone to answer why NiceHash 1.8.1.5 is such a disaster and why we constantly see numerous, not properly tested versions of miners.

**Comment by Nickfost** [comment]
These versions are not heavily tested. if you need an "easy" miner you should use Nicehash Miner 2...

**Comment by mifurman** [comment]
Thank you. Could you please tell me how I can use NiceHash Miner 2.0 with Vega and other AMD GPUs?

**Comment by hotrock3** [comment]
@imrecsoka Sounds like you need to hit a different forum for your questions. Submitting a issue on github isn't the right place to ask for help on diagnosing why your system doesn't operate using any mining software.

**Comment by mifurman** [comment]
It is not about diagnosing my problems but the lack of stable software (with all the most current algorithms) for AMD Vega on NiceHash Miner

**Comment by imrecsoka** [comment]
@hotrock3  I agree with treading this on another forum or board, but wanted to voice it hear since Nicehashminer is hugely used and very reputable, therefore many users would be experiencing what i am which would probably make for good progress in getting further information and resolving issues. Most of the issues are not just nicehasminer having different versions modded by different authors but the fact that many of he miners with or without  issues are tied to it.

**Comment by Nickfost** [comment]
i have all 1060 rigs but its my understanding if you are using AMD cards you may need to use an old driver.


i could be completely wrong or misguided. Just go buy nvidia cards  😛

**Comment by mifurman** [comment]
I have no problem whatsoever on two of my Nvidia based systems (that include GTX 1080Ti, 1070Ti, 1070 and 1060). The main issue is very poor support for AMD GPUs, especially Vega with HBCC enabled. Good luck running 3 Vega GPU system with additional RX580s and RX480s on Legacy 1.8.1.5

**Comment by DillonN** [comment]
The only currently updated versions are this miner and NHM2. You should be using one of these

Incompatibility with new drivers for AMD is not a NHML issue, and proper Vega support for CryptoNight is coming when a decent miner is released (that has NiceHash stratum support)

**Comment by imrecsoka** [comment]
Hi DillonN thank you for all the communication.
So to confirm , this is the link for all of your NiceHashMiner builds?
https://github.com/nicehash/NiceHashMinerLegacy/releases and your latest build would indeed be - 1.8.1.5 ?

**Comment by mifurman** [comment]
Thank you, DillonN
