### ISSUE TITLE
Monero Mining with xmr-stak-amd

### ISSUE THREAD

**Issue by mifurman** [nicehash/NiceHashMiner#608]
I am wondering if there is any work to incorporate xmr-stak-amd into NiceHash Miner. I would like to be able to run my Vega GPUs with HBCC enabled to efficiently mine Monero (CryptoNight algorithm). At this point, I cannot efficiently utilize my Vega/64/Vega56 GPU based system when using NiceHash

Thank you,

Michael

**Comment by DillonN** [comment]
Xmr-Stak-AMD does not support the NiceHash stratum, which makes it not play well at all when mining to NH pools. 

Xmr-Stak is coming soon, which looks to be a version that will supersede Stak-AMD, Stak-CPU, and Stak-NVIDIA as a unified miner, and should also have NH stratum support. Once it is released it will be supported

**Comment by mifurman** [comment]
Thank you. This is helpful!

**Comment by hovermind** [comment]
cast-xmr-vega working with nicehash getting 1900 - 1950 H/s with VEGA 64 . Although 1.5 % goes to developer , better than sgminer's 1850 H/s.

**Comment by mifurman** [comment]
So it works well with NiceHash Stratum (obviously it is not in NH miner)? I understand that HBCC is enabled so could you tell me if it really runs reliably 24/7. What happens if you switch the monitor off? Do you have any other GPUs in the system? Thank you

**Comment by hovermind** [comment]
@mifurman I can confirm that cast-xmr-vega is working with NiceHash Stratum but can't confirm about 24/7. (because I was just testing different miners since people were claiming higher hash rate : http://www.gandalph3000.com/cast_xmr/howto-mine-monero-rx-vega/). And yes it's true that both cast-xmr-vega & xmr-stak-amd (now unified as xmr-stak) are better. Nicehash includes sgminer & xmrig.

FYI, I noticed that rejection % is higher if you use other than what nicehash supports officially(I heard some nonce issue). So, I am waiting for xmr-stak support (officially). I switched back to nicehash's sgminer because although cast-xmr-vega was giving higher hash rate, rejection % is higher than sgminer.

I got GTX 1080 Ti (mining with NHM 2.0) and VEGA 64 + threadripper 1950x (mining NHML 1.8.2.0) & I switch off monitor (no problem with HBCC).

FYI, NHML has issues with threadripper 1950x (low hash rate), but I solved it my making config_0.txt and config_1.txt readonly & now getting around 1100 H/s (cryptonight)

**Comment by mifurman** [comment]
Thank you, hovermind. You post is very helpful to me. Greatly appreciated! I am also waiting for the new NH Miner. I am using older (14 core) Xeon CPUs for CPU mining. By the way, I am convinced that that if there is any change of AMD GPUs configuration, especially when Vega is involved, it is necessary to use AMD CleanUninstall and install driver again. 
I have no problem with Nvidia GPUs apart from occasional crash for Afterburner

**Comment by hovermind** [comment]
@mifurman I don't have any driver issue. I was just trying to get higher hash rate (people are claiming 2050 H/s with vega 64 for Cryptonight). What I got (CryptoNight by VEGA 64):
- nicehash sgminer 1850 H/s (lower than people are claiming)
- cast-xmr-vega 1950 H/s (but higher rejection by nicehash pool)
- xmr-stak-amd 1950 H/s (probably best but result rejected by nicehash pool)

FYI, I noticed that my GTX 1080 Ti (Asus STRIX OC edition) doing good with Lyra2REv2 (73 MH/s) & Equihash (600 sols/s) & therefore selected only these 2 algorithms (avg. $4/day)

My threadripper 1950x doing well too (1100 H/s CryptoNight). How much are you earning with your Xeon? I was about to buy i9 but suddenly changed my mind and bought threadripper 1950x (I am happy that I did)

**Comment by mifurman** [comment]
My Xeon E5-2683 v3 (I have two systems with them - bought very cheap and have had them for a while) are barely 600 H/s CryptoNight. I did not get them specifically for mining. I have additional 3 LGA 1151 systems. I keep Nvidia and AMD GPUs separate. Nvidia Ti GPUs love Lyra2REv2, Keccak and Blake2s. You are running NH Legacy 1.8.1.5 and obviously use HBCC, right? I overclock memory of Vega 64 GPUs to 1100 Mhz and sometimes had issue with system resetting, especially if I disconnect the monitor (switching between three systems). If I swap Vega GPU with, let's say RX580, I usually have to clean install Win10-64Bit-Crimson-ReLive-Beta-Blockchain-Workloads-Aug23 again for stability. 

My conclusion is that for stability, it is better to stick with NH miner. I do not want to baby sit my AMD systems all the time :-)

**Comment by hovermind** [comment]
@mifurman thanks for info. I am using 1.8.2.0 Pre (slightly better than 1.8.1.5) & yes HBCC on.
My setting for VEGA 64:
GPU: -`10%
Memory : 1105 MHz (the highest my vega can handle, after trying several settings)
Power: 20%
Result : Cryptonight 1850 H/s (Nicehash sgminer)

I would like to know your result for VEGA 64. 

I was a little bit frustrated after reading online that people are claiming they are getting over 2000 H/s with VEGA 64. I did all the things described in reddit but did not work for me (both cast-xmr-vega & xmr-stak-amd got 1950 H/s but both have issues with nicehash, so patiently waiting for Nicehash official support for xmr-stak :( )

**Comment by mifurman** [comment]
@hovermind I will have to try 1.8.2.0. I have gone back to 1.8.1.5 restricting some protocols. I set Vega 64 to: GPU clock 1102, 1162 (works better for me than underclocking 27%), Voltage 1000 mV (up to 1050 mV), Mem 1100 MHz, Power +4%. Vega 56: GPU clock 1102, 1172 (works better for me than underclocking 26.5%), Voltage 1100 mV (up to 1150 mV), Mem 900 MHz (930 Mhz is not completely stable), Power +8 (10) %. I managed to get 4.6 kHs in the system with Vega 56, Vega 64 (HBCC on for both) and RX480 but my Vega 64 was not stable and I moved it to another system (Xeon) where I have problem enabling HBCC on and therefore I am building another LGA 1151 - I want to have it rock stable without even looking at it. I am having issue that Wattman resets with HBCC on and both Vega 56 and 64 in the system (ROG Z270  with only 16GB RAM). I really think that more RAM is needed for bigger systems with HBCC on. I am only running NH Legacy or 2.0 (for Nvidia GPU systems)

**Comment by hovermind** [comment]
@mifurman Did you try "Large Page Size" (I guess you got windows system?)

I would be glad if you inform me about hash rate for VEGA 64 alone in your new system.

**Comment by mifurman** [comment]
@hovermind Yes, I did and it works but I think that for speed, there should be enough DDR4 memory (just the thought). Without HBCC enabled my Vega 64 hashes 1300 H/s CryptoNight (stable).  As I said, it is currently in a system where, for some strange reasons (old motherboard?), I cannot enable HBCC (even though, I have 48GB RAM in it). I will move Vega 64 to a new system in a couple of days and I will let you know. I will set it up just to experiment with Vega 64, HBVC and NH Legacy.

**Comment by mifurman** [comment]
@hovermind I finally enabled 16 GB HBCC on Vega 64  in Xeon system (I have 48GB there) and I am getting 1750 Hs NH 1.8.1.5. I will be experimenting if adding more HBCC memory increases the hash rate
