### ISSUE TITLE
CryptoNight mining  problems  

### ISSUE THREAD

**Issue by authbasic** [nicehash/NiceHashMiner#609]
hi
I have a problem at the CryptoNight mining   .  i change version nicehash  . but same pproblum .  i change server location   same problum .  i test  zec(claymore)  mining  . it ok   .  
I ask for a way to fix it.  Please help me  .   thank you

     
![error cyr](https://user-images.githubusercontent.com/33712225/32877080-45278136-cad2-11e7-9c4a-899de8aa66c8.png)

**Comment by ninjaalex888** [comment]
having an issue like this too, 0.000 H/s cryptonight for my gpu 1 and 3, gpu 2 is doing fine on daggerpascal

**Comment by mifurman** [comment]
Also having problems (expressed in other cases, I posted)

**Comment by ninjaalex888** [comment]
Didn't do anything different but tried again today and getting stable hashrate with cyrptonight now.

**Comment by mifurman** [comment]
Interestingly, I am also running NiceHash Legacy 1.8.1.5 in two systems without any big problems. Is it NiceHash itself that is/was a problem? It would be nice to hear from them (or developers) once in a while. It is actually time that Vega and Cryptonight are properly supported

**Comment by mifurman** [comment]
I meant “hear”

**Comment by ninjaalex888** [comment]
it seems i get 0.000 H/s with cryptonight when it tries to use that on some gpus and a different algo on other gpus. When all gpus are on cryptonight it works, when it's split the cryptonight gpus get 0 and the other algo gets some hash rate.

**Comment by mifurman** [comment]
I think that you are right. There is a problem running multiple GPUs. I generally do not have any problems when running NiceHash Legacy on one GPU computer

**Comment by DillonN** [comment]
You can get a job timeout if you don't submit a share within 10 minutes - this is standard stratum protocol. Being able to produce shares more than once every 10 min is becoming increasingly infrequent, as CN difficulty goes up. 

Connection problems are likely server side. Unfortunately CN mining on NH is very popular right now and more or less causing too much load

@ninjaalex888 @mifurman have you tried with both old and new versions of Claymore CN miner? The new one is in beta and does not support every card completely.

**Comment by mifurman** [comment]
I think that the only solution for any Wattman resets when running NH 1.8.15 with Vega GPUs is to forget about what benchmarking picks for them and just choose one or two algorithms and only allow NH miner to run them. Many are simply not reliable on 1.8.1.5. NH 1.8.1.3 does not have this problem. I am really looking forward to seeing releases of NH Legacy properly tested for overclocked Vega GPUs
