### ISSUE TITLE
miner startup when nicehash *website* is down

### ISSUE THREAD

**Issue by t3t3** [nicehash/NiceHashMiner#61]
results in

1. a warning, what means autostart mining isn't working
2. a .net crash when trying to start mining, or open settings, or open benchmarks

ideally there shouldn't be a crash (obviously ;) and it should be able to start mining, since unavailability of only the nh website won't necessarily affect miners (as long as stratums are still up)...

**Comment by DillonN** [comment]
Yes I agree there shouldn't be crashes. Right now though there is no logic for NHML to pick which algo to mine while NH API is down. There is a totally new connection method to NH servers in the works though
