### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner#611]
I would like to see nicehash start out with a basic quick benchmark and then update based on the running average hash rate of each card. When nicehash was updated and the miners are updated there would be no need to rerun the benchmarks.

**Comment by micax** [comment]
+1 sounds Great!

**Comment by DillonN** [comment]
@xadonxander this has been something I've been thinking about for a while. I will look into working on it after a couple other features

**Comment by Simaex** [comment]
I will certainly appreciate such a feature. As a future enhancement you may also consider some community check - users that are willing to compare their actual hashrate to average for similar hardware may submit their benchmark data in anonymous form. We'll soon get database that'll enable users to finetune their hardware and may help to finetune initial miners settings. Also it will help to avoid problems with too low hashrate during initial fast benchmark. I have issues when fast benchmark was two times lower then normal hashrate. In such a case we may have the algo not used for a long while.

**Comment by S74nk0** [comment]
Duplicates https://github.com/nicehash/NiceHashMiner/issues/942
