### ISSUE TITLE
no internet connection

### ISSUE THREAD

**Issue by dosvantus** [nicehash/NiceHashMiner#612]
my miner does not work because of an internet connection error 
If i connect another Internet, it all works, it's clear that the reason in my provider. They said that 
my ip address is probably blocked from your side 

my provider asked me to do tracert ip adress to your address to solve the problem. I don’t know which your ip address is connected to me

![default](https://user-images.githubusercontent.com/33705788/32896064-7191f32c-cafb-11e7-9336-2094e5cc842c.PNG)

**Comment by garishulc** [comment]
![default](https://user-images.githubusercontent.com/33732793/32912357-df258f42-cb1f-11e7-96cd-b01d7f91497b.png)
у меня примерно теэже самое, не подлключается, дело не в антивирусе. сначало работало всё ок, после перезагрузки изза ошибки от сильного понижения напруги на проц стала выбивать это и всё

**Comment by uk879059** [comment]
У меня выдается такая же ошибка.  Что делать?

**Comment by smygarn** [comment]
Same issue here. All versions and all my computers. But the computers working, they keep working so please don't turn it off.

**Comment by ivanplysyuk** [comment]
Привет ! у меня точно также нет соединения, кто знает в чём причина я уже винду сменил на ферме не помогло. Пробовал разные версии майнера легоси тоже в пустую пишет нет интернета, а если запускается то хешрейт  очень сильно прыгает  на алгоритме CryptoNight с положеных 1600 показывает то 160 то 400 то 800 прыгоет по разному и майнер перезагружается через некотрое время кто знает в чём причина ?

**Comment by Virtuon** [comment]
Same issue!

**Comment by EVGENY1777** [comment]
Здравствуйте! Блокирующее окно "Отсутствует интернет соединение... невозможно получить данные о прибыльности..."
Менял серверы, запускал с правами Администратора - безрезультатно. 
Все серверы нормально пингуются. 

![17 11 2017](https://user-images.githubusercontent.com/23138776/32947208-ca71055e-cbab-11e7-8ece-80e65cc00d8c.jpg)

**Comment by Crash911119** [comment]
Та же самая фигня!!! ТП Найса шлют сюда, тут решения нет, фермы стоят

**Comment by ivanplysyuk** [comment]
В обще есть идеи в чём причина ? айпи или что ?

**Comment by micax** [comment]
cloudflare is blocking you guys...

**Comment by micax** [comment]
I recently made an app to basically restart nhml till it gets connected.... moreover - you can recompile nhml yourself to increase attempts to connect to 100 or 1000 for ex.

**Comment by Crash911119** [comment]
Думаю, micax прав и блочат нас со стороны сервера, вопрос в том, как сервер понимает кто есть кто? Тоесть если найти как формируется  наш ID и изменить этот механизм, все заработает.

I hope micax is quite right. We need to found, how server identify us and how to change this ID. And it is not IP address.

**Comment by ivanplysyuk** [comment]
Кто нибудь из найсхеша занимается этой проблемой ? не каких новостей не чего

**Comment by Crash911119** [comment]
ТП сюда засылает и группа ВК тоже... видимо им насрать

**Comment by dredd21** [comment]
Не работает, 12 видюх простаивает!

**Comment by ivanplysyuk** [comment]
Ребята вот что поддержка ответила : В свойствах вашего интернет подключения проверьте, включено ли IPv4 и IPv6, если IPv6 включено, то IPv6 следует отключить. Скачайте программу заново, добавьте её в исключения из проверки антивируса и запустите с правами администратора. Проверьте не блокирует ли подключение ваш антивирус или брандмауэр.

**Comment by ivanplysyuk** [comment]
Короче я не чего не делал просто скачал майнер легоси 1.8 1.2 и всё пошло

**Comment by EVGENY1777** [comment]
"NiceHashMinerLegacy.exe - Ярлык" - Свойства - Совместимость - Выполнять с правами администратора (галка) - Применить - Ок
Может, кому поможет)

**Comment by Ajivitca** [comment]
this problem with internet connection (incorrect block from ddos shield on cloudflare).but solve - admin right or other "solution" is wrong . nicehash run many month on stable system on many people. and in this month say this message "can't get exchange rate".

nicehash must have "no block any message future". any block message in any reason - it's wrong way on  not free  program and run like service on many mining ferm in autostart mode.

i run pool mining in 2st task (nicehash 90% times run in this month with message "cant get exchange rate" after automatic reboot). this mining ferm work before 6 month w/o this trouble)

**Comment by Crash911119** [comment]
Пробовал и совместимость и провайдеров менять и этот бред с IPv6, не помогает.
В общем это все же беда на стороне найса, клаудфайр лочит, надо больше писать тут гневных коментов, мож разрабы и пошевелят свои щупальца кривые, а пока помайним на чем нить другом, если буду не один в таком решении, пофиксят быстро, если одинок, то так и будете париться

Problem is on NiceHash servers side. I stop use NiceHash before fix this problem.

**Comment by EVGENY1777** [comment]
Очередной раз при перезагрузке фермы сообщение 
 "Нет интернет... невозможно получить данные о прибыльности... "  
Все попытки типа Админ, Ай-пи 6 и т д - напрасны. 
Через 10 минут данные о прибыльности появились сами по себе, без 
моего вмешательства. 
 Если это cloudflare - то как обходить???
И, чтобы не сидеть всю ночь и ждать перезагрузки и блокирующего сообщения - 
придётся запускать bat-файлы...

**Comment by Sav87** [comment]
add Pull request #625

**Comment by Crash911119** [comment]
> Если это cloudflare - то как обходить???

Никак, это защита на стороне сервера

**Comment by Sav87** [comment]
Это не блок, это скорее нагрузка на сервер. Происходит задержка соединения, получения данных, на которую таким образом реагирует программа.

**Comment by Crash911119** [comment]
100% блокировка, это в большинстве случаев происходит когда ферма по тем или иным причинам перезагружается, как правило, в случае когда отвалилась одна из карт

**Comment by Sav87** [comment]
Решение есть ждём когда его разработчики примут.

**Comment by dredd21** [comment]
Решил проблему, дело в антивирусе было, он файлы при скачивании майнеров в карантин помещал.

**Comment by EVGENY1777** [comment]
Антивирус и брендмауэр отключены. Проблема остаётся.

**Comment by Sav87** [comment]
Если закрывать сообщения и нажать кнопку «старт»(лучше подождать пару минут). То 2-3 попытка запускает майнер. Это такая реализация программы.

**Comment by micax** [comment]
че вы пвритесь)? можно ведь пересобрать с большим количеством попыток на подулючение - у меня все пашет. кроме того, megaphone всегда пропускает у меня почему то.. а кабельных провов - ростелеком и яру банит временами

**Comment by ivanplysyuk** [comment]
Когда прогу включаете даже если просит интернет, как загрузится пробуйте менять локации в программе а потом перезапустить, у меня на европе не хрена не работала потом сменил на Hong-Kong  всё заработало может кому поможет.

**Comment by Knell77** [comment]
проблема не в антивирусе и браузером, все стоит в том то и дело в исключениях, оно хочет работает хочет нет в .1.4 такого не было

**Comment by Knell77** [comment]
ivanplysyuk видать тебя это еще не коснулось ну не чего дойдет у меня тоже друг так умничал, а потом бах и сидит кривой весь... проблема не в серваках !

**Comment by malek5752** [comment]
how to solve it ?

**Comment by EVGENY1777** [comment]
To use vpn, the. bat file or the version of NHM below 1.8.0.2. 1.7.5.13 - connects without problems. 
And wait for the fix version 1.8.x.x

**Comment by Sav87** [comment]
added an alternate way to get sma. #625

**Comment by Crash911119** [comment]
А можно куда то выложить скомпилированную версию с предложенными изменениями по получению SMA?

**Comment by xtrime-ru** [comment]
@Crash911119 

Сделал репо и скомпилировал фиксы.
https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases
