### ISSUE TITLE
CryptoNight Dufficulty Jumping from 100K to 400K and back in minutes !!

### ISSUE THREAD

**Issue by Paapo** [nicehash/NiceHashMiner#613]
Hi, i´m not 100% sure if it is an issue, but i´m wondering, why monero difficulty is jumping from 100.000 over 200,000, then 400.000 and then back again to 100.000, within just a few minutes. And this further and further, since a week or so. I´ve never seen this much changes in difficulty in just a few minutes and over this long period. Am i the only one facing this in Claymores CryptoNight miner (old)?

Kind Regards,
Paapo

**Comment by DillonN** [comment]
I don't believe this is an issue, at least not one with NHML. Difficulty is set by the pool

**Comment by Simaex** [comment]
It is definitely not a NHML issue, same using Claymore 9.7 without NHML.
