### ISSUE TITLE
NiceHash Miner wont bench mark and will crash after mining for a couple of mintues

### ISSUE THREAD

**Issue by AlecRob** [nicehash/NiceHashMiner#614]
Hi, I'm new to mining and started with Legacy because I have an AMD GPU 
I haven't been able to benchmark on my GPU so I just tried to follow how to do it manually and that worked so I was able to start mining. 
but after a few minutes, everything crashed
I have an R9 390 
I was able to Benchmark and mine just fine on my CPU (AMD FX-4130) just to test bc it's not profitable to mine on my CPU.
I also tried  to bring down the clocking on WattMan for AMD but I don't really know what I'm doing 
So if you have any suggestions or experiences
that would help greatly thank you

**Comment by AlecRob** [comment]
Also what Driver Version might NiceHash prefer for AMD Graphics cards

**Comment by DillonN** [comment]
Make sure you are not overclocking and not running out of power on your PSU. If you provide more details about the crash (log file, what exactly happened, etc) I could maybe help more

For the 390 I would recommend the 15.12 drivers
