### ISSUE TITLE
XNSUB problem

### ISSUE THREAD

**Issue by msviben87** [nicehash/NiceHashMiner#615]
Hi, I use:

AMD Radeon Vega 56 8GB Sapphire
and
NiceHashMiner 1.8.1.5 

i don't know why it says there is no XN SUB on one GPU and on other is good?

![screenshot-www nicehash com-2017-11-17-11-55-28](https://user-images.githubusercontent.com/25161538/32944001-487b3b04-cb8e-11e7-8ea0-d23e9fa79ccf.png)

Thank You in advance!

**Comment by DillonN** [comment]
xnsub stands for extra-nonce subscription, it is not a NiceHash only feature (many pools support it) but support is required by miners as well (not all miners support it). Quick and easy description as to what it is - https://www.reddit.com/r/NiceHash/comments/74qxw0/what_is_the_xnsub_extra_nonce_subscription/
