### ISSUE TITLE
NHM 1.8.1.5 not connected!

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner#617]
When the program is started, 1,8,1,5 constantly issues a message that the connection to the Internet is not detected, although it is definitely there and works quite well, the direct connection from using the VPN

![1 8 1 1 5_nicehash-error](https://user-images.githubusercontent.com/18327150/32956939-6242da46-cbcb-11e7-9bb1-3a57a9a3dc28.jpg)
![1 8 1 1 5_nicehash-error](https://user-images.githubusercontent.com/18327150/32956959-788d0808-cbcb-11e7-921d-22b9e861381c.jpg)

**Comment by EVGENY1777** [comment]
Same problem... Not solved.
Такая же проблема... Не решена.
https://github.com/nicehash/NiceHashMinerLegacy/issues/612

**Comment by dredd21** [comment]
Not working too...
Тоже не работает...

**Comment by Sav87** [comment]
add Pull request #625

**Comment by dredd21** [comment]
Решил проблему, дело в антивирусе было.

**Comment by zloi-krolik** [comment]
Не в антивирусе, а в самом приложении

**Comment by VadimEv** [comment]
this is related to cloudflare, as mentioned in another issue it seems that cloudflare blocking russian ips. If this stuff continues, I would be forced to say bb nicehash and switch back to pools. I tired of solving recaptcha while logging in to my wallet as well, nicehash is super-nazi, while other resources utilizing same recaptacha usually takes no longer than 10 seconds to get verified, nicehash can take up to 5 minutes. Paranoids live longer, but I just don't care.

**Comment by xtrime-ru** [comment]
Сделал репозиторий и скомпилировал фиксы от @Sav87 
https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases
