### ISSUE TITLE
How do I display the mining console in 1.8.1.5

### ISSUE THREAD

**Issue by 1RedOne** [nicehash/NiceHashMiner#621]
Hi,
  
  Recently moved to 1.8.1.5 from a very old version 1.7.5.13.  In the older version, while you were mining, NHML spawned console windows and you could watch mining as it occurred in real time.  This was awesome and allowed me to proactively fix issues as they arose. 

 Is this still an option in 1.8.1.5.   I'm benchmarking my system now on the new version and have noticed that no mining windows appear, even for miners which I'm certain display a console window (such as Equihash and Claymore).

Thanks,

**Comment by HaTaX2** [comment]
Look in settings in the right hand column, you'll find a few entries that might be checked.  'Hide Mining Windows' and 'Minimize Mining Windows' being checked could both cause you to not see the windows.  If all else fails just rename or delete your General.json file in the 'Config' folder and let it create a new one with defaults. 

EDIT:
I didn't see the 'benchmarking' portion in the message first time I read it. mcsjohn is correct and there aren't any options to be set to show mining windows when benchmarking.

**Comment by mcsjohn** [comment]
While benchmarking the miner windows are not visible for the reasons explained here https://github.com/nicehash/NiceHashMinerLegacy/issues/596

**Comment by 1RedOne** [comment]
Thanks for the explanation, makes sense.  Let's close this issue.
