### ISSUE TITLE
May I ask for feature about auto disable algorithm which freq caused miner down?

### ISSUE THREAD

**Issue by Misaka-0x447f** [nicehash/NiceHashMiner#622]
![image](https://user-images.githubusercontent.com/15797507/32977322-fde0bf1e-cc65-11e7-9bf8-75f111093b0e.png)
Screenshot: last frame back from my miner before it "cools down".

On my miner, "sgminer" and all of algorithms that start with "dagger"(except "daggerhashimoto") often caused the whole PC lost response. I have to manually reboot my miner and manually disable these algorithm. So I hope there are any feature to disable algorithm which freq caused miner down.

- Please make requests in English
TRUE
- The issue has not already been reported.
TRUE
- Relevant log files are included (generally `\logs\log.txt`).
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1484384/log.txt)
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
TRUE?
- The issue is relevant to NHML specifically and not to the NiceHash service.
TRUE
- Specifications of setup such as NHML version, Windows version, and hardware are included.
v1.8.1.5, Windows 10.0.16299.64, Radeon (TM) RX 470 Graphics

**Comment by HaTaX2** [comment]
Just go into the settings and up at the top there's a 'Devices/Algorithms' tab, click that and then select your GPU(s) from the list.  Then in the bottom list you can clear the check mark next to the algorithms/miners you want to disable.  Another option is to look up the settings for a particular miner to lower the intensity or stress placed on your system.  You'll need to do this per each miner that you find causes issues.

**Comment by Misaka-0x447f** [comment]
@HaTaX2 That's manually disable method. Just want to suggest adding this feature or just warn user if NHML was not correctly closed due to system crash/NHML crash + ask user to check if some algorithm cause this problem.

**Comment by DillonN** [comment]
@Misaka-0x447f there is an incompatibility with sgminer and RDP (the remote desktop protocol you are using). On most machines running sgminer under an RDP connection causes a blue screen. This is explained a bit in the README file on the front page I believe. You can also find more info on the sgminer GitHub page (just try googling RDP on sgminer). The problem seems almost universal, however I have it working fine under an RDP connection to Windows Server 2016 on AMD drivers 15.12

Unfortunately it isn't possible for NHML to react to these kinds of errors. The entire Windows crashes upon launching sgminer under RDP, so NHML is not able to detect the problems or react to them

**Comment by Misaka-0x447f** [comment]
@DillonN Thanks for your help.
*Screenshot is related to claymore's miner. I realized that this problem was caused by my power, insufficient power support here.
*The only things expected, if possible, is NHML can be warn user "NHML was suffered an unexpected close after X minutes of mining. That's may caused by a power failure, sgminer's bug or NHML internal error. You may check the README.md for more information."    <- This is what my notepad.exe in the screenshot do. Not a bug, just feature request.

**Comment by DillonN** [comment]
@Misaka-0x447f for a problem like this, NHML will close and restart the miner indefinitely when it detects 0 speed (which it looks like you've noticed). This is also reported in the debug console (which also looks like you've noticed). As I understand you are requesting a feature that notifies the user when something like this happens? The idea is to keep it as unobtrusive as possible, and power users who wish to see what is going on can use the debug console. 

That being said there is a feature requested that NHML temporarily disables an algorithm if this 0 speed - restart happens too many times. This will likely be implemented eventually. During this implementation there would be some warning that the miner/algo combo has been disabled and lets the user re-enable it or tells when it will be automatically re-enabled
