### ISSUE TITLE
Suggestion: alert when actual hashrate differs a lot from benchmark

### ISSUE THREAD

**Issue by Simaex** [nicehash/NiceHashMiner#623]
Hi!
I noticed that sometimes actual hashing speed is two times lower then benchmarks stored for algo selection. I have noticed such issue with Claymore Dual miner 10.1 and NHML 1.8.1.5. Please consider some alert or visual comparison for benchmarked and actual hashrates. Even better if long-term hashrate can be used for improving benchmarking results, for example if we got seasonal throttling issues for power-intensive algos.

**Comment by DillonN** [comment]
@Simaex I do like the suggestion, and it will certainly go well with requested feature #611. If you could, keep conversation to this topic on that issue. Thanks!
