### ISSUE TITLE
Color output to the console?(Цветной вывод на консоль?)

### ISSUE THREAD

**Issue by Sav87** [nicehash/NiceHashMiner#629]
![colored](https://user-images.githubusercontent.com/30864287/32987104-3c781dba-cd1c-11e7-8da3-2654acd495e2.png)

I wonder if anyone needs this option. And also the withdrawal of the level (INFO, DEBUG, WARN, ERROR, FATAL). Instead of a permanent [INFO]
Интересует нужна ли кому нибудь такая опция. А также вывод уровня (INFO, DEBUG, WARN, ERROR, FATAL). вместо постоянного [INFO]

**Comment by micax** [comment]
+ 1 we need it
да нужна

**Comment by zloi-krolik** [comment]
Да нужна
