### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by gacopl** [nicehash/NiceHashMiner#63]
Hi Dillon  i have hard time building NHML

Severity	Code	Description	Project	File	Line
Error	CS0234	The type or namespace name 'Extension' does not exist in the namespace 'MyDownloader' (are you missing an assembly reference?)	NiceHashMinerLegacy	C:\Users\gaco\Desktop\NiceHashMinerLegacy\NiceHashMiner\Utils\MinersDownloader.cs	16

VS2015 .net 4.5

Original nhm 1.7.13 builds without a problem

**Comment by DillonN** [comment]
I haven't set a flag for the extensions project to build yet, you have to build the `MyDownloader.Extensions` project and/or copy its dll from that output to the NHML output folder

**Comment by DillonN** [comment]
This should be fixed with 6dfcd8a66bcd35a2938b7cbd12b64e228f17e7ac

**Comment by gacopl** [comment]
yeah in the meantime i added reference manually but thanks !

**Comment by DillonN** [comment]
Good to hear, I'll close this now
