### ISSUE TITLE
NiceHashMinerLegacy for Ubuntu Linux & Linux Mint !!!!

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner#630]
Dear developers, when will you finally make the version of NiceHashMiner  under Ubuntu Linux and Linux Mint, there all this will probably work more stable .... and the 64-bit miners there are obviously more done/
----------------------------------------------------------------------------------------------------------------------
Уважаемые разработчики, когда же вы наконец-то сделаете уже версию НАЙСХЭША под Убунту Линукс и под Линукс Минт, там все это дело наверняка будет работать стабильнее....да и майнеров под 64-бит там явно больше сделанно/.

**Comment by DillonN** [comment]
There are currently no plans for a Linux port unfortunately. I will update if this changes

**Comment by sjkelleyjr** [comment]
Come on man...
