### ISSUE TITLE
Cannot Locate AMD GPU

### ISSUE THREAD

**Issue by Radacon** [nicehash/NiceHashMiner#631]
I've done extensive research on this issue and have found nothing that works. I am currently running two AMD RX Vega 64s, and an RX570. I've updated the drivers to the latest version, downgraded to 15.something, hopped around driver versions, and tried disabling and reenabling the cards in device manager. NHML finds the cards when I disable and then re-enable, but it says I cannot use them (something is wrong with the card) and that I should restart. Upon restarting, I'm back to square one. I've tried NHML 1.8.1.5 and 1.8.2.0. 

It detects the CPU just fine. 

Any other tips? I've installed all of the drivers for my motherboard. 

![image](https://user-images.githubusercontent.com/33811645/32994029-c1d1c78e-cd1e-11e7-9554-c83cfeff180e.png)

![image](https://user-images.githubusercontent.com/33811645/32994034-d4ef57dc-cd1e-11e7-8b7f-e3f860b336b0.png)

This is device manager AFTER I disabled and re-enabled the card. The warning triangle doesn't show up after restart. As for the other two drivers (ethernet, and USB). Both work just fine on my motherboard.

**Comment by DillonN** [comment]
@Radacon it does look like there are some driver issues there. Both Vegas should appear as separate entries in device manager, and the 570 should have an entry as well. I suggest doing a thorough driver clean with a tool such as [DDU](http://www.guru3d.com/files-details/display-driver-uninstaller-download.html) and reinstalling new drivers. It is true that older drivers can be more stable/offer better performance for some cards, but make sure to not install drivers that are older than your cards (as they likely do not support your cards). Specifically 15. drivers do not support any of your cards if I recall correctly

**Comment by Radacon** [comment]
I forgot to mention that I only had one card plugged in at that time to try a suggestion a friend gave me. Here is a screen cap of it currently.
![image](https://user-images.githubusercontent.com/33811645/33025700-e25b9c5c-cdcb-11e7-9a1d-901f9a37d60e.png)
I used DDU to uninstall the drivers and then Re-Installed the Aug 23 Blockchain driver. I have also just disabled VT-d in the BIOS. Any other suggestions.

**Comment by DillonN** [comment]
Could you please post your logs/log.txt file? That would give info on what is happening during device detection

**Comment by Radacon** [comment]
It's worth noting that if you have a fresh copy of windows you should let it install 175+ updates before you mess with anything. This issue is closed. Thank you for your suggestions. In the end, the giveaway was that I couldn't open the AMD control center after I had just installed the software.

**Comment by DillonN** [comment]
Glad you got it sorted out
