### ISSUE TITLE
NHML-1.8.1.5 GPU Fan Always above 93% on Dual Mining

### ISSUE THREAD

**Issue by davidfskan** [nicehash/NiceHashMiner#633]
Hi,

I downloaded the NHML-1.8.1.5, when it come to dual mining, some of my RX 580 fan ran above 90% but the GPU temp show only 46%?

The previous version I am using does not have this issue.

Please advise

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1486327/log.txt)

**Comment by alexsiym** [comment]
Здравствуйте, я очень хочу с вами дружить ! люблю вас, хочется выразить от себя что бы сложность не расла, а то у многих нас слабые видиокарточки.
по поводу новой программы найс хеш
версии 1.8.1.5 не находит двух гигабайтную версию и не майнит ее у меня карта R 7 240 siries

**Comment by DillonN** [comment]
You can tell Claymore to use a max fan speed with extra launch parameters. See the exact flags to write [here](https://bitcointalk.org/index.php?topic=1433925.0)

Make sure to also check "Enable AMD temperature control" option to allow these parameters to be passed.
