### ISSUE TITLE
Wrong Hash Rate at NiceHash website.

### ISSUE THREAD

**Issue by HSTelecom** [nicehash/NiceHashMiner#636]
Hello

I have Claymore with 11 GPU RX580-OC8G , the status for Claymore read 26Mh/s for each total 280 Mh/s.
on Nice hash Dashboard I saw some time 350Mh/s and 100Mh/s , I checked ping to USA daggerhashimoto Pool and other all stable and replays 60-80ms same of 8.8.8.8

its right or wrong ? because when I check your calculator and other website calculator there is low incoming with 1-4 USD per day.

I use your nice hash mining software on windows PC with same RX580-OC8G , it was same result on daggerhashimoto , I got 26Mh/s and change to 10-15Mh/s while your software read 26Mh/s all time.

Regards.

**Comment by DillonN** [comment]
Please read the [Wiki](https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Troubleshooting#profitdisc)
