### ISSUE TITLE
Need to kill "NVIDIA-SMI 388.31" for Nicehash 1.8.1.5 to start

### ISSUE THREAD

**Issue by propergol** [nicehash/NiceHashMiner#638]
For some reason I need to kill the subprocess NVIDIA-SMI 388.31 to start Nicehash.
Once killed, Nicehash starts.

- Windows 10 pro creator update
- Nvidia driver 388.31
- 13 Geforce 1060 6Gb

**Comment by DillonN** [comment]
Likely this is causing NHML to not be able to communicate with the drivers it needs to to detect GPUs. If so this cannot be fixed in NHML

**Comment by propergol** [comment]
I did test nvidia-smi alone and it sees my 13 GPUs, I can change power limit, see temp ect

**Comment by zephyr125** [comment]
Nicehash 1.8.1.5 still stuck due to nvidia-smi 388.31 we need this because of gtx 1070ti please check how to bypass nvidia-smi call from NHML
