### ISSUE TITLE
ccminer tpruvot/ Cryptonight latest version supports more than 10 GPUs, not the Nicehash version

### ISSUE THREAD

**Issue by propergol** [nicehash/NiceHashMiner#639]
Version v2.2.2 : https://github.com/tpruvot/ccminer/releases/tag/2.2.2-tpruvot
supports more than 9 or 10 GPUs

The actual version in Nicehash (v2.2) does not.

**Comment by DillonN** [comment]
The release notes specify this feature is for Linux, can you verify it works on Windows? Also the syntax is unclear. If it is just `-d 10,11` e.g. then it should work in NHML already. You can manually update any ccminer by just copying over the exe, provided that the syntax doesn't change, I'll look into updating on next release

**Comment by propergol** [comment]
I have just tryed to manualy launch mining using Nicehash provided algo and it works.

When I try inside Nicehash directly the ccminer console repeat open/close and fail at GPU 11.

I tryed to redo the benchmark and the first 10 cards a benched correctly but the last 3 seems to bench very quicly without error, but then when trying to mine, the same issue with GPU 11 appear.

**Comment by propergol** [comment]
I have in fact just discovered that when doing a bench on this particular algo and just select GPU11,12,13, then in reality GPU1,2 and 3 are used.

Trying the same on all Dagger algo works perfectly.

**Comment by propergol** [comment]
ok, I did finaly replaced the .exe with 2.2.2 version and problem solved! 👍 

For some reasons I had already tried that but Nicehash was then redownloading all miners, maybe because I was also overwritting the .dll. Not sure. Only replacing the .exe did the job and everything works now.

**Comment by DillonN** [comment]
Good you got it working, I'll mark this as enhancement for updating to 2.2.2

**Comment by DillonN** [comment]
Updated
