### ISSUE TITLE
Benchmark terminates on dual agorithms

### ISSUE THREAD

**Issue by batishchevv** [nicehash/NiceHashMiner#64]
Please help with benchmark error on all dual algorithms. It's terminate.
Log in attach.

![dual miner log](https://user-images.githubusercontent.com/20699899/28521746-b44af692-707d-11e7-94f2-1ac8c1a3bc6e.jpg)

**Comment by DillonN** [comment]
The startup command looks good, but the miner seems to be crashing. Are you able to run ClaymoreDual manually (as in, disable other algos then set a fake speed for ClaymoreDual and start mining)? Also what card are you using?

**Comment by batishchevv** [comment]
I've tried to run ClaymoreDual manually. It crashes with error that remote computer rejected connection.
![claymore](https://user-images.githubusercontent.com/20699899/28558169-532ff118-7119-11e7-8ac4-5c5437e45e40.png)

I use palit gtx 1060 Dual cards But i have one other the same configuration unit, that works fine.

**Comment by DillonN** [comment]
Is the rejected connection error in NHML or Claymore itself? NHML will throw that error if the miner crashes, because it will try to access its API port which isn't open (since the miner didn't open). 

Do you see any log files in your `bin_3rdparty\claymore_dual` folder? If so could you post them?

**Comment by batishchevv** [comment]
I think it's NHML. There is no any logs in claymore_dual folder.

I'm fully reinstall system and it works. So i don't have option to troubleshoot it oner more time =(
