### ISSUE TITLE
Invalid NONCE with Old Claymore CryptoNight

### ISSUE THREAD

**Issue by RealityRipple** [nicehash/NiceHashMiner#640]
Getting the occasional error 5 message when using the legacy Claymore on my R9 380 2GB. Usually a couple times a day at most. Might be partially my connection's ping's fault (700+ms over Satellite).

**Comment by DillonN** [comment]
Interesting, this usually indicates a miner that is incompatible with NiceHash protocol. The old Claymore shouldn't have this problem. If it only happens a couple of times a day, then it probably isn't eating into profits too much. Are you able to try with a lower ping connection?

**Comment by RealityRipple** [comment]
Not yet... I'm working on getting a better connection, but it's sorta a competition between three wireless companies and one of them's stalling. I was really hoping I'd be on a "real" connection by the end of this month, but that's not seeming likely.
