### ISSUE TITLE
How do you add miners to NiceHasMinerLegacy

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner#641]
I wish to add XMrig to an older Dillon version, for example.
Then say for new versions...
How then can we add Algorithms like Xevan or Phi or...
I just cant figure it out,, driving me nuts.

**Comment by DillonN** [comment]
You can't add miners without knowledge of C# and editing the source yourself. Adding miners requires extensive coding, including usually unique methods of benchmarking and API connection, providing proper launch command syntax, and adding flags for the miner throughout the program. You can look through the commit history when Xmrig was added to see all the changes that were made, if you want to spend some time on it. 

You can make requests for specific new miners to be added, they should follow some criteria outlined [here](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Miner-request-criteria).
