### ISSUE TITLE
Configs Files resetting automatically

### ISSUE THREAD

**Issue by Crypto-Lord** [nicehash/NiceHashMiner#649]
Had this issue happen before where the PC restarts and loads NHML but all of the General.json settings have been reset to default (keeps the benchmarks, thankfully) But I have to change/enter everything in again from btc address to all of the Extra Launch Parameters.

**Comment by craxis** [comment]
I have this same issue periodically, usually after the system has done a random re-boot, but not every time.  I now keep a backup copy of my general.json file, I copy the back up file into the config folder, and it works again.

**Comment by DillonN** [comment]
The config settings won't reset unless the files have become damaged or are missing, which can happen on crashes

For either of those problems not much can be done within NHML to fix

**Comment by johmei4** [comment]
"For either of those problems not much can be done within NHML to fix" That's absolutely not true.  The program could periodically make a backup of the config file.  Every 5 mins, or 10 or 30 or whatever and have 2-3 versions back.  How can you say not much can be done?  And why hasn't Nicehash done this yet?
