### ISSUE TITLE
Miner defaults to Dagger when Skunk is much more efficient.

### ISSUE THREAD

**Issue by jadestarcat** [nicehash/NiceHashMiner#650]
No search results on mutiple querys.
Skunk shows 40+ MH/s while dagger runs at 30.
The system was showing Skunk mostly running and then Dagger took over and runs exclusively.
What is to be done in this case?

**Comment by Larcos50** [comment]
Have you tried to run Skunk exclusively by unchecking all algorithms except Skunk in the Benchmark tab. You may need to also clear the speed of all algorithms except Skunk so that they are not used.
Haven't tried it... just a thought.

**Comment by jadestarcat** [comment]
Yea, perfect I figured that out 2 days ago. I had not yet tooled around in the settings and did not know it was possible yet to do so.
I only had to select Skunk.
Running fine by all appearences for a novice.
One other quick question is you have a minute.
So I created a login and wallet on computer A, and the primary miner on that wallet address is on computer B which I pasted into the miner on that machine.
Computer B will not login to the system, but computer does it ok, so no real poblem. I have not really thought about all the intracacies of managing wallets, addresses etc. I started with one external wallet which is also running on computer A.

Thanks

Star

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by Larcos50** [comment]
I didn’t read a question in there. What are you asking specifically?
For mining, you are using the NiceHash wallet on both computers?

**Comment by jadestarcat** [comment]
Sorry my explanation of this may sound a bit confusing.
I originally set up a wallet address on computer A that is external [Exodus address] for the miner on that machine.
I later read that it might be better to have a Nicehash wallet address which I set up on computer A, but it is not being used for the miner on computer A.
I created the Nicehash login on computer A.
I set up the miner on computer B with the legacy version of the software for radeon card and pasted in the wallet address which I got for my login on computer A.
Computer B will not allow login to the system but mines fine and reports fine to display on computer A.
I see no cookies stored or saved logins etc anywhere and it would seem that computer B should be asking for the password I created.
So just a bit confusing attempting to run on multiple boxes.
Apparently I cannot take the unpaid balance on the other wallet address and move it until it reaches a certain threshold which is high relative to the Nicehash address. I will do some further research.
Possibly I am missing something simple.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by Larcos50** [comment]
The wallet is tied to the NiceHash account or external account and not a machine. You are doing the right thing. Continue to mine on Comp A with the external wallet until you cross the payout threshold (https://www.nicehash.com/help/when-and-how-do-you-get-paid) for the external wallet. At that point, stop mining with the external wallet and put the NiceHash wallet address to mine on Comp A also. This way you will maximize your payout and it’s frequency.  Using NiceHash wallet on both machines is the way to go. If you want to use the external wallet for online payments or cash out, you can withdraw funds from NiceHash to the external wallet address.
BTW, you should be able to view online stats and login to NiceHash on both machines once they are using the same wallet.

**Comment by jadestarcat** [comment]
Thanks for this info.

Star

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by DillonN** [comment]
Looks to be sorted out
