### ISSUE TITLE
my minor shuts down unexpectedly and I did not get paid for a couple of months.

### ISSUE THREAD

**Issue by spock9** [nicehash/NiceHashMiner#653]
hi.
I am new with mining.
I have made my pc recently and installed NHM in the past and I was receiving about $50 every two weeks.  after I installed V15, it startes crashing my windows 10 many time during the day.  I have not received any payments for a couple of months as it crashes often.
my system is:
Windows 10 
2 GPU of RX 480
NHM v1.8.1.5
I think the version of the log file is the log.1.txt that is showing the error.

[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1497794/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1497795/log.txt)
I appreciated if you can help me.
thanks.
Mining

**Comment by DillonN** [comment]
Crashes can happen from a lot of reasons like hardware problems, OC, etc

If you are using Remote Desktop it can also cause crashes

I do not understand what you mean by V15? 1.8.1.5 has only been out for around ~3 weeks so it wouldn't have caused problems for months
