### ISSUE TITLE
Dk2a failed Cryptonight

### ISSUE THREAD

**Issue by korisame** [nicehash/NiceHashMiner#654]
Hi all,

When mining with new cryptonight with nicehash legacy 1.8.1.5 or 1.8.2 I get gpuminer dk2a failed -4 when mining with more then 2 gpu on cryptonight. 

Any suggestions?

**Comment by BARUCHER777** [comment]
Same problems on the Radeon Fury! Win 10 64-bit  &  last driver from AMD

**Comment by rakec** [comment]
Same here. Mining rig 5 X Rx480 4gb rejected 100% for cryptonote

**Comment by Simaex** [comment]
Try to increase page file. Do not use automatic option, just set fixed size bigger then combined memory of all GPU. 
How to set [http://www.tomshardware.co.uk/faq/id-2864547/manage-virtual-memory-pagefile-windows.html](url)

**Comment by korisame** [comment]
I’ll try to do so this afternoon and update you

Shaun Gioele Gori
