### ISSUE TITLE
Ccminer-Klaust in 1.8.1.5 bins is not current, slow and requires lowered intensity on NeoScrypt

### ISSUE THREAD

**Issue by UselessGuru** [nicehash/NiceHashMiner#655]
[Ccminer KlausT has been updated to 8.15](https://github.com/KlausT/ccminer/releases/tag/8.15)

On a GTX1080ti with the version from 1.8.1.5 bins i need to lower intensity to 18 and get approx 1.3MH/s on CryptoNight.
With the latest Ccminer-KlausT Version 8.15 I can go to intensity 22 and get approx 1.55MH/s

**Comment by GongoloMin** [comment]
My v1.8.1.5 fires up bin\ccminer_tpruvot\ccminer.exe for neoscrypt.
Are you mining with klaust ccminer?

**Comment by UselessGuru** [comment]
@GongoloMin 
> Are you mining with klaust ccminer?

Yes, KlausT gives better has rates for my GTX 1060 3G:
KlausT 8.15: 760kH/s on intensity 16
Trpvot (NHML): 640mH/s on intensity 20

Rates on GTX 1080ti are about identical for both miners.

**Comment by DillonN** [comment]
Will look into updating Klaust

**Comment by Nix-id** [comment]
i use NHML-1.8.2.0-Pre2
but program don't  show me klaust miner when i test algos

how enable this miner?

**Comment by DillonN** [comment]
KlausT has been updated to 8.18
