### ISSUE TITLE
Lots of rejected shares

### ISSUE THREAD

**Issue by gysiek** [nicehash/NiceHashMiner#656]
Hi,

I suddenly get 100% rejected shares stating "share above target" since this morning as well as "internal server error"

I re-downloaded NHML 1.8.1.5 and bin files but still same issue.

Please help.

Thanks
![error 1](https://user-images.githubusercontent.com/33929592/33171123-b918f2e2-d053-11e7-961a-b3bc53e8516d.png)
![error 2](https://user-images.githubusercontent.com/33929592/33171124-b95d95f0-d053-11e7-8b00-bebacad6912c.png)
![error 3](https://user-images.githubusercontent.com/33929592/33171127-b99eb1c0-d053-11e7-8ba7-6a0f01754ff7.png)

Logged query with Nicehash and they referred me here.

Hardware used:

AMD Ryzen 7 1700
2 x Radeon RX Vega 56 - Using normal AMD drivers as blockchain drivers not working with cryptonight on my PC
Windows 10 pro x64
16 Gig RAM
MSI X370 Gaming Pro MB
NHML version 1.8.1.5

**Comment by BARUCHER777** [comment]
Same problem`s////

**Comment by jessechan618** [comment]
same problem

**Comment by DillonN** [comment]
Share above target indicates some hardware problem e.g. OC or power or temps

If you submit too many invalid shares, the server will temporarily prevent you from connecting
