### ISSUE TITLE
Can't connect to any pool 

### ISSUE THREAD

**Issue by swordmaster34** [nicehash/NiceHashMiner#657]
Since 12 hours ago , I cant connect to any pool with my gpu

![image](https://user-images.githubusercontent.com/33933694/33177099-9e152e08-d048-11e7-8b3e-73540160358d.png)

**Comment by DillonN** [comment]
Problems with miners connecting aren't related to NHML. All NHML can do is pass the correct pools to the miners (which it is doing here). If there is no connection there is something wrong with the internet/firewall/servers or miner file itself (unlikely)
