### ISSUE TITLE
No supported devices: Unable to find AMD OpenCL for GPU

### ISSUE THREAD

**Issue by KillerKat** [nicehash/NiceHashMiner#659]
Hi, I've been trying to use NHML to mine but it cannot find any supported device.
It seems that it is unable to find the AMD OpenCL for my GPU.

GPU Info (extracted from log.txt):

Name ASUS HD7750 Series
		Description ASUS HD7750 Series
		PNPDeviceID PCI\VEN_1002&DEV_683F&SUBSYS_04271043&REV_00\4&10698843&0&0008
		DriverVersion 13.152.0.0
		Status OK
		InfSection ati2mtag_R575A
		AdapterRAM 1073741824 

Attached below is log.txt and screenshot on running NHML. Kindly advise on what I should do to fix this issue.

Thank you.

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1502319/log.txt)
![unable to find amd opencl](https://user-images.githubusercontent.com/33964966/33220599-7e1d7eb0-d184-11e7-8345-2037df9716dc.jpg)

**Comment by damionmorley** [comment]
I Look For a New Way

**Comment by DillonN** [comment]
It looks like the AMD driver is returning an error when NHML queries for GPUs. Can you try cleaning/reinstalling drivers or using newer drivers? I find 15.12 works great on older generation cards

**Comment by damionmorley** [comment]
How Do You Get It Up And Running I Need To Know ? 17.11.2
