### ISSUE TITLE
Neoscrypt ccminer

### ISSUE THREAD

**Issue by GongoloMin** [nicehash/NiceHashMiner#661]
Maybe that tpruvot ccminer 2.2 is not the best choice for neoscrypt algo.
KlausT in my setup performs better.

**Comment by propergol** [comment]
lol... on what GPU?

**Comment by GongoloMin** [comment]
1070 and 1080ti

**Comment by parrel** [comment]
Would indeed be nice to have the KlausT version in NHML. 

It increased my hashing speed with 10% and reduced the power usage + temperatures of my gpu alot.

**Comment by Nix-id** [comment]
Someone can help me?
i see the KlasuT miner exists bin\ccminer_klaust\
but NHM don't use this miner for neoscrypt
how enable it?

**Comment by Nix-id** [comment]
i found file internals/MinerPathPackage_NVIDIA_6_x.json
and i see -  i can change miner for algo
previously i think all miners test on each supported algo

**Comment by parrel** [comment]
@Nix-id Just point the miner manually to the Neoscrypt pool.

**Comment by DillonN** [comment]
KlausT is default for neoscrypt on Maxwell/Pascal now
