### ISSUE TITLE
After reformatting and re installing i cannot benchmark any Dagger algos.

### ISSUE THREAD

**Issue by spider72** [nicehash/NiceHashMiner#663]
After reformatting and re installing legacy miner I cannot benchmark any dagger algos.
I get the following message ,
The code execution cannot proceed because MSVR120.dll was not found. Reinstalling the program may fix the problem.
Needless to say I have deleted and reinstalled the miner, it downloads all miners but I still have the same issue.
Have no idea on a way forward.

**Comment by SerpentDrago** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=40784
Install both x64 , and x86 Versions

MSVCR120.dll belongs to the Visual C++ Redistributable Packages for Visual Studio 2013

Lots of applications / games auto install this when you install stuff . You just have not managed to run into a program that did . Install Visual C++ Redistros from Microsoft and you will be fine

**Comment by spider72** [comment]
Thanks will give that a try....
