### ISSUE TITLE
Nicehash using wrong GPU

### ISSUE THREAD

**Issue by nin3tin** [nicehash/NiceHashMiner#664]
![capture](https://user-images.githubusercontent.com/32214212/33240806-242431be-d2f7-11e7-8e49-7a269322cc22.PNG)

I have enabled only 1 GPU in the list selected RX580. But console is using my r9 Fury Card which is shown in the console Fiji GPU.

everything in the list is wrong, if i want to change settings in my 470 i have to change the r9 in the list, everything is scrambled except my RX570.

using v1.8.1.5

**Comment by Buckthebarbarian** [comment]
I have the same problem, I think it happens when going over 4 gpu's and mixing amd with nvidia cards

**Comment by propergol** [comment]
I think it is more a mismatch between Nicehash numbering starting at GPU 1 and ALL other miners, OC tool, GPU info using GPU 0 as first GPU.

Nicehash should definitly use the correct naming convention used by all others and use GPU 0 as first GPU.
Using GPU 1 as first GPU is misleading.

**Comment by DillonN** [comment]
@nin3tin do you have the same issue if you use the non-old version of Claymore Cryptonote? Could you post your log.txt file?

@propergol NHML uses the same ordering as most miners, Claymore is the exception (they use the same ordering as Afterburner/OC tools)

**Comment by M3dicine** [comment]
I am having the same issue.  I tried both the current release and the 1.8.2.0 pre-2.  When DaggerPascal Claymore miner launches, it mines with the card I don't want it to mine with.  There is a field in the settings for launch parameters for specific algorithms.  Can code be inserted into this field to direct the algorithm to a specific device?

Edit:
Some extra info:  It was stated above that it is possible to have this issue when >4 GPUs or mixing AMD & Nvidia cards.  I have 2 GPUs, both AMD.  1 R9 390, 1 Vega 56

The R9 is not detected by NHML, but is detected by most (if not all algorithms)

Imputing numerical inputs to the miner can disable & re-enable the R9, but no command seems to enable the vega card (even though the miner does see 2 cards).

Edit 2: Claymore_DaggerLbry also affected by this bug

For now, I have disabled this particular algorithm as NHML thinks I'm hashing with the wrong card...  Which is a disappointment as this algorithm has been doing well for me in recent days.

I HOPE THIS GETS FIXED SOON!

**Comment by arnezami** [comment]
Hi everyone,

I have the same issue - i have mixed GPU
3 - Asus R9 390x STRIX 8 GB
3 - Sapphire RX 580 8GB 

Card detection is wrong.
My R9 listed in miners like RX 580, and of I launch all of them - minimum 2 cards doesn’t works. Something really strange. GPU driver is latest version. How to solve this issue? Thanks in advance

**Comment by DillonN** [comment]
@M3dicine @arnezami which drivers are you using? The AMD Adrenalin drivers have a bug that can cause wrong device ordering.

Also I need the logs\log.txt file to be able to fix this

**Comment by m250xl** [comment]
Thanks for the follow up.  I resolved the issue by uninstalling and
reinstalling the AMD drivers.

Scott

**Comment by puithove** [comment]
I ran into this too.  3 cards, only nvidia, 3 different models.  Seems to be just Claymore using different numbering.  Any of the Claymore algos are mixed up.  This causes an issue when there is different profitibility where it should be using claymore on one, and a non-claymore on another - can end up with two different miners pointed at the same card.  I've already run a DDU and clean re-install of the nvidia drivers.  I switched over to the Nicehash miner v2 and it seems to handle things properly, though I prefer the tweakability of the legacy miner.

**Comment by puithove** [comment]
I also see this on an AMD rig with a mix of 580s and 570s, again difference in how Claymore numbers them.  Switching to v2 isn't an option since there is no AMD support.  Just noticing that on these the Claymore miners are more profitable, so ended up turning off all non-Claymore miners in order to avoid any conflicts.

**Comment by GoldenAnt** [comment]
After I fixed all issues, run to another problem with electrical circuit, my miner became a small monster and  shouting down my home electricity :)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
