### ISSUE TITLE
sgminer.exe causes crash/BSOD on exit with AMD VEGA

### ISSUE THREAD

**Issue by vegaminer111** [nicehash/NiceHashMiner#665]
The included sgminer.exe binary causes a GPU crash and/or BSOD when closed through the GUI "stop" button. The symptoms appear similar to something described for cgminer.exe (http://www.holynerdvana.com/2013/12/avoiding-cgminer-bsodcrash-on-exit-for.html). I found that other CryptoNight miners like Cast XMR and xmr-stak do not crash on exit. Terminating sgminer.exe from the task manager also does not cause a crash.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
