### ISSUE TITLE
Issues with version 1.8.2.0 pre!!! as 1.8.x.x 

### ISSUE THREAD

**Issue by EVGENY1777** [nicehash/NiceHashMiner#667]
Not fixed "no Internet connection. it is impossible to obtain data on profitability".
In version 1.7.x.x has no such problems!
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1505939/log.txt)
![27 11 2017_1](https://user-images.githubusercontent.com/23138776/33268527-9c675272-d38e-11e7-89bf-90a01563684e.jpg)
![27 11 2017](https://user-images.githubusercontent.com/23138776/33268524-9791f2ac-d38e-11e7-9b32-8c4068825a34.jpg)
https://github.com/nicehash/NiceHashMinerLegacy/issues/651

**Comment by volf066333qq** [comment]
у меня такаяже проблема с 1.8.1.5)))

**Comment by FoxProBTG** [comment]
сбой в открытом коде поменялись сервера а в проге нет паэтому тормоза если разраб не делает то я сделаю и выставлю для вас прогу под другим названием

**Comment by DillonN** [comment]
Please keep pre-release issues to #487
