### ISSUE TITLE
OpenCL fails

### ISSUE THREAD

**Issue by ImaginaryPie** [nicehash/NiceHashMiner#67]
1.8.0.1 runs for about an hour to two hours before the computer freezes. The first freeze I couldn't tell what caused the failure due to a second ETH miner window opening over the claymore window. The second freeze had 2 error messages before freezing stating that GPU 3 OpenCL failed to reboot.

Running 6 RX480s on 16.9.2 drivers. I've been running the latest official NH version for about a month now without any problems.

**Comment by billmcilhargey** [comment]
I referenced this in another case too

As workaround, copy the OpenCL.dll from .\bin\ethminer to
.\bin_3rdparty\claymore_dual

See if this helps and let us know

https://github.com/nicehash/NiceHashMinerLegacy/issues/32

**Comment by DillonN** [comment]
I don't think I saw that issue before it got closed, next time I update bins I will put a copy of OpenCL.dll there.

**Comment by billmcilhargey** [comment]
ok thanks!

**Comment by ImaginaryPie** [comment]
This fix worked thanks
