### ISSUE TITLE
Not being paid for CPU mining

### ISSUE THREAD

**Issue by yearight** [nicehash/NiceHashMiner#674]
I'm on Version 1.8.1.5, but the others are the same.
MY AMD 8120 benchmarks and runs fine, it even reports speed and earnings in the program window.
Online it show cryptonight as active, but everything is 0.
I just disabled the cpu and I'm earning even more than when it was enabled? Man I wish I knew that a long time ago, I would have disabled it then.

WIndows 10
AMD 8120
2 x R9 380

[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1508777/log.1.txt)

**Comment by HaTaX2** [comment]
8120 is a decent cryptonight miner, but you might need to make a few tweaks to get the most out of it.  I've found that using xmr-stak-cpu works best for me, and it should be assigned to all cores but the first one.  You'll need to modify the config_0.txt file to do this, and also set it to read only after the changes are made to keep NiceHash from overwriting the file.

I'm using a 8350 in one PC and a 8320E in another and they both produce decent hash rates. 8350 @ 4.5Ghz hits 400-420 H/s and the 8320E @ 4.0Ghz hits 360-380 H/s.  I notice that sometimes the online miner page shows a zero, but they are producing income so I've just ignored the online page for the CPUs.

**Comment by yearight** [comment]
Thing is it show earnings in the app, but not on the website. Disabling CPU mining all together doesn't change what I earn on the website, which they say is the accurate one. It is kind of hard to be sure with the way that graph on the website is all over the place, but if you look at the monthly $ amount, it is the same.

xmr-cpu-stak can be set to use less cores in the app itself, no need to edit a file...unless your saying the 1st core specifically. The only reason I used 1 less core was I was getting slight freezing when watching youtube or something.

You are blowing me away in hashrate even with mine overclocked to 4 ghz, I get about 260 h\s.

**Comment by DillonN** [comment]
CPU mining produces shares infrequently. The website will only show what you're making based on how many shares it receives in a period. This can cause frequent drops to 0 followed by spikes of high profitability on the website
