### ISSUE TITLE
Wrong benchmark with Xmr-Stak

### ISSUE THREAD

**Issue by riccardoruspoli** [nicehash/NiceHashMiner#676]
Xmr-Stak gives a wrong value after benchmark, on both GPU and CPU on different computers.

**Comment by ikalo** [comment]
I have the same issue on several computers/rigs. Benchmark value is roughly 10 times higher than real one. It is the same on several cpu, amd and nvidia cards. I run win7 64bit on those rigs I have tried 1.8.2.0 Pre2. Workaround is to edit the speed manually after you have stable speed shown in GUI. 

cheers from Velimir

**Comment by lmlim** [comment]
Ditto for me.

**Comment by DillonN** [comment]
Please keep pre-release discussion to #487
