### ISSUE TITLE
Nicehash fails when it tries to get SMA Information

### ISSUE THREAD

**Issue by Wadimich** [nicehash/NiceHashMiner#677]
Issue is with NHML itself. `wss://api.nicehash.com/v2/nhm` gives 1002 error.
I'm using 1.8.1.5 NHML and Windows 10 x64.

This is happens only with specific IP adresses, i guess, some Russian IP-ranges. On my work it's working great (ISP is Orange Business Services), at home (ISP is Rostelecom) it fails.

**Possible fix**: use fallback api for getting info, this wss should do, until it fixed.
**Workaround**: use VPN service, until this is fixed.

**Comment by smygarn** [comment]
Got this error for some time now on all my Nicehash computers.

Workaround: When it's connected, don't restart the application since it's not sure you can connect again. It's extremely enoying and frustrating. I'm now looking for other options than Nicehash!

Debug log:
HTTP/1.1 503 Service Temporarily Unavailable
WebSocket.connect|Not a WebSocket handshake response.
11/28/2017 22:31:44|Debug|WebSocket.closeHandshake|Was clean?: False
                            sent: False
                            received: False

**Comment by boyod** [comment]
NiceHesh block all from russia and do not admit!!!

**Comment by c0ff75** [comment]
But why only one my rig from 4 can't connect to nicehash? Three others rigs works fine.

I have exactly same problem with HTTP error 503 on one rig.

**Comment by Heivor** [comment]
Same problem. Fix this pls.
![8lfeiqfqisw](https://user-images.githubusercontent.com/19757392/33528754-ad8d797c-d876-11e7-96cd-6210ccfd12ac.jpg)

**Comment by utc99** [comment]
This happens in EU countries too. Really problematic bug. When this will be fixed?

**Comment by Jdruitt** [comment]
Experiencing this in the UK also. Anyone have a quick fix?

**Comment by Wadimich** [comment]
@Jdruitt use free VPN service for first connect

**Comment by Jdruitt** [comment]
Thanks @Wadimich I was using a VPN but not on setup. I removed Nicehash and started fresh pointing to the US from UK and it seems to be working fine. Appreciate it

**Comment by forexmuller** [comment]
1) Open Anvir task manager
2) Set autorun any browser with open tabs when Windows start.
3) Remove in settings NHM "autorun when windows start"
4) Set NHM autorun with dalay 30 sec

**Comment by Wadimich** [comment]
It's resolved for latest version of NHML.
