### ISSUE TITLE
Nicehash XMR-STAK not benchmarking (RX 580)

### ISSUE THREAD

**Issue by zmate1000** [nicehash/NiceHashMiner#678]
Hi, 

On my 2 rig (12 x rx580) the xmr-stak benchmark is running to TIMED OUT every time. I tried the BM on all card and tried on 1-1 card. The result was same. 
I used the new version 1.8.2.0 Pre 2.
(claymore and the other miners are working)

What Can I do?

Thanks Zoltan

**Comment by adem4ik** [comment]
It is already reported in https://github.com/nicehash/NiceHashMinerLegacy/issues/487#issuecomment-347372372

Btw developer asked:
> This is a pre-release intended to test the new version before it is released. Please restrict feedback and discussion to issue #487.

**Comment by DillonN** [comment]
Thank you @adem4ik
