### ISSUE TITLE
Claymore 10.2 crash

### ISSUE THREAD

**Issue by HaziqX** [nicehash/NiceHashMiner#682]
[1511882577_log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1513024/1511882577_log.txt)

I'm using R9 380 and having trouble with the new miner Claymore Cryptonote 10.2. The miner would crash and the hashrate produced during benchmark is much lower than the previous build.

The R9 has the latest driver, page file has been set and I tried running the miner individually(without the NHML). Basically I've read the readme and followed the instruction but nothings seems to be working.

Did I miss anything?

**Comment by DillonN** [comment]
Claymore CN 10.2 is unstable on some cards, try using the Cryptonote_old version instead (uncheck the non-old one)
