### ISSUE TITLE
When dstm's ZCash Cuda miner will be added? Thanks. 

### ISSUE THREAD

**Issue by quantumshadow** [nicehash/NiceHashMiner#685]
https://bitcointalk.org/index.php?topic=2021765.0

Thank you

**Comment by Braintelligence** [comment]
Please edit out the issue template and provide a link to this miner please.

**Comment by quantumshadow** [comment]
https://bitcointalk.org/index.php?topic=2021765.0

Thank you.

**Comment by Braintelligence** [comment]
Did you really belittle someone on creating such an issue in https://github.com/nicehash/NiceHashMinerLegacy/issues/704 even though you did the same in regards to https://github.com/nicehash/NiceHashMinerLegacy/issues/445 , where you also elaborated on how dstm's miner is worse than EWBF? 😆

**Comment by quantumshadow** [comment]
Thats not your business, smartass. Yes, at first dtsm seemed to be worth installing. But after close look its not worth it. Even NHLM not worth installing coz switching between algorithms leads to inevitable driver crash and PC reboot. So all so called advantages of quick and seamless algo switch is just fairy tail for undocumented immigrants in Nogales AZ.
