### ISSUE TITLE
cast xmr error: WSACancelBlockingCall

### ISSUE THREAD

**Issue by cheffin96** [nicehash/NiceHashMiner#686]
When I start casting an error comes.
SOCKET ERROR-No login / password specified.
SOCKET ERROR-RECIVE ERROR:
a blocking process was interrupted by a call to WSACancelBlockingCall.
is a TCP error?
What can I do?
the bug comes with all cast xmr versions
thx

**Comment by DillonN** [comment]
This forum is for NHML problems, cast-xmr is not supported in NHML
