### ISSUE TITLE
Keep getting this video controller warning and mining stops.

### ISSUE THREAD

**Issue by SuperDerpBro** [nicehash/NiceHashMiner#687]
Starting about 3 days ago this started happening about once a day. Usually (my luck) a few mins after i go to bed lol. So it stops mining until i get up :/

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1516665/log.txt)
![aefwoeg](https://user-images.githubusercontent.com/34119497/33416016-392efcc4-d54f-11e7-99f4-bf3efc6f7e1d.png)

Windows 8.1 
NHML v1.8.1.5

Old GIGABYTE GA-EP45-UD3R
Old e8400
8GB RAM
3x EVGA 1060 SC 6GB
1x PNY 1060 6GB

I think the PNY is the one having/causing problems because when i pres OK all the EVGA's start mining. I have to reboot for NHML to even see the PNY again. 

Any ideas?

**Comment by bonifacio123** [comment]
What version of the NVIDIA driver are you using? I was receiving the same error with 388.31 but 387.92 doesn't do this.

**Comment by SuperDerpBro** [comment]
I was on 384.76. Installed 388.31 last night an woke up to a rig still mining.. Fingers crossed! heh

**Comment by SuperDerpBro** [comment]
Crash :( .. will try 387.92

Is there a way to get rid of the PRESS OK box.. so at least 3 cards can mine? Or auto reboot the system on that error so they all can? The ongpuslost.bat works but not for that error :(

**Comment by bonifacio123** [comment]
What error are you getting? The same one as before? Some things to consider: Are you using risers - if so try replacing. What about under-volting - if so try to use defaults and see what happens. Also check temps and make sure you're not overheating. Oh, also make sure your power supply isn't under powered for your setup. And finally, you do have a monitor connected to your rig - right? If you don't get a virtual display adapter. Without a video connected you'll get all sorts of crazy errors and crashes. Hope this helps.

**Comment by SuperDerpBro** [comment]
Same error, yes :/

I guess buying another riser would be a good thing to try (I am using them). 

No undervolting but i do rum them all at -20% in Afterburner. The PNY has been running for months in another PC like that. 

Temps are great! EVGA cards are 64Cish. PNY is usually 72C. Again been running like that, hotter actually (Closed case) for many months. Corsair TX750m gold is more than enough for 4 1060s. 

No monitor attached.. I will try that.

Thanks for your reply :D

**Comment by bonifacio123** [comment]
Anything under 100 in power is undervolting - and anything over is over-volting. I'm pretty sure connecting a monitor will fix your issues.

**Comment by SuperDerpBro** [comment]
Have not had the error since trying 387.92. The rig did reboot itself once though. If i get the error again i will try a monitor. If i still get it i will just buy another EVGA/riser and put the PNY back in my main PC and use it for games. I pulled it for this rig and put my old R7 265 in... Need to buy a new card anyways haha.

Thanks for your time :D

**Comment by SuperDerpBro** [comment]
Finally got the error again on 387.92 :(

Dug up an old monitor and attached it. Fingers crossed :)

**Comment by SuperDerpBro** [comment]
Got the error with the monitor attached. Guess wait for the new riser. Really dont want to have to buy a new card. This one has Samsung ram and the chances a new one will not have hynix are pretty fucking slim :'(

**Comment by Sav87** [comment]
Leave one algorithm on the video card, check how it will work.

**Comment by SuperDerpBro** [comment]
Will try that.
