### ISSUE TITLE
Benchmarking does not progress

### ISSUE THREAD

**Issue by UpsilonDiesBackwards** [nicehash/NiceHashMiner#688]
Hello,

I am a noob at Mining, I have the Hash Miner Legacy and trying to benchmark my GPU although it is not progressing here are my details:

AMD RADEON 6900 Series (crap i know)

and the algorthims I am trying to benchmark are the three CryptoNight-s

Please explain why this is not progressing.

**Comment by DillonN** [comment]
You can try [manual benchmarking](https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Getting-started#manualbenchmarking) instead
