### ISSUE TITLE
only cryptonight shows up in benchmark

### ISSUE THREAD

**Issue by JuggyMcNutty** [nicehash/NiceHashMiner#689]
so i have tryed both latest NHML versions and both give the same results...

on a gtx 970 and on a separate computer with hd 7970's the only algo it shows is cryptonight...

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1518597/log.txt)

**Comment by JuggyMcNutty** [comment]
![image](https://user-images.githubusercontent.com/11588877/33441818-36d83e58-d5b9-11e7-9fc4-78439c3713d9.png)

**Comment by DillonN** [comment]
You have to enable the GPU (hit the checkbox) and select the row for the GPU to show algorithms. You're only looking at CPU algorithms right now
