### ISSUE TITLE
Keccak NHML 1.8.0.2 GTX 970 Win10

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner#69]
For mining eth, based on my conditions (GTX 970 and Win10) included the DSR (1.2) and the Optimize for calculations option in the nvidia DSR settings. With these settings, there was a full hash on eth and no problems with other algoes.
Now, with the new Keccak algorithm, with these options enabled, the error pops up: "Cuda error in func 'keccak256_cpu_init' at line 301: all CUDA-capable devices are busy or unavailable."
If you return the Nvidia settings to those two options by default - the Algo Keccak is OK

**Comment by DillonN** [comment]
Having the Optimize For Compute option enabled can cause issues with programs accessing CUDA devices. You can try disabling it globally and adding program specific rules for the ethereum miners, only turning it on for them

For more details you can see my comment here https://github.com/nicehash/NiceHashMinerLegacy/issues/33#issuecomment-315279151
