### ISSUE TITLE
No devices detected

### ISSUE THREAD

**Issue by vrmcardoso** [nicehash/NiceHashMiner#690]
Hi,

I'm trying to install NHML on an old laptop with an HD5870 and i7 Q740 but NHML isn't detecting any devices. 
Any chance this can be made to work? 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1519281/log.txt)

**Comment by HaTaX2** [comment]
The latest versions of NHML probably aren't compatible with that hardware, you can try some of the older versions here: https://github.com/nicehash/NiceHashMinerLegacy/releases?after=1.8.1.0-Pre
(Try something in the 1.7.X.X range, see if they list any miners and if try older versions)

There's a good chance it will end up being more work than it's worth however, and laptops don't take to well to the heat produced by mining.  Here's a thread from reddit where someone was looking into using a desktop HD 5870 to do mining: https://www.reddit.com/r/dashpay/comments/6b8d3u/how_to_mine_with_old_gpu_radeon_5870_1gb/

**Comment by vrmcardoso** [comment]
Yeah, that didn't do it. It's ok, I knew it was a long shot. Just an old laptop I revived from cold storage. Thought it would be cool if the old thing could still do some last tricks before retirement :)
Thanks for trying, though.

**Comment by DillonN** [comment]
Yeah unfortunately the hardware is too old for NHML
