### ISSUE TITLE
NHML Not tracking/reporting CryptooNight 

### ISSUE THREAD

**Issue by rangefear** [nicehash/NiceHashMiner#692]
Hi,

I'm having trouble with cryptonight being reported properly in dashboard. On my computers its showing that its steadily working, but in dashboard i'm seeing 0 kh/s This seems to be commong across all my computers. I can see in the NHMN client (either 1.8.1.5 or 1.8.2 depending on computer) that they are working.

I want to make sure I'm not missing out on any income and also that my miner is working correctly.

Thanks

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1519729/log.txt)
![cryptonight not working](https://user-images.githubusercontent.com/34144191/33458925-26120206-d5f6-11e7-9c15-8171ec9bd452.png)

**Comment by rpm604** [comment]
Are you ever submitting shares? With only 300H/s, at 100001 difficulty, the reporting will be very irregular, but it should average out.

Let it run for a couple days and see if it adds up correctly.

**Comment by rangefear** [comment]
Ok. I was just hoping to see it slowly accumulate. I'll leave in to run uninterrupted for a few days.

But should the numbers (even if they're low) be showing up in the NH dashboard?

**Comment by rpm604** [comment]
NiceHash will only "see" the work you're doing when it accepts your submitted shares. So if you're not submitting and shares, it'll report zero.

So it's gonna come and go in bursts, not really accumulate slowly. Just give it time and average it out!

**Comment by DillonN** [comment]
It is as @rpm604 says
