### ISSUE TITLE
High "job not found" and "invalid nonce" rate on XMR-stak

### ISSUE THREAD

**Issue by rpm604** [nicehash/NiceHashMiner#693]
I'm getting two very specific rejected shares right now.

Rig 1:

• 1724 / 1773 (97.2%)
• 41 job not found
• 8 invalid nonce

Rig 2:

• 1880 / 1935 (97.2%)
• 41 job not found
• 14 invalid nonce

As in the title, 5 Vegas across 2 rigs, using xmr-stak, in the actual NiceHash app.

I can't find details about these specific rejected shares. I'd like to fix this as it's an awful hit to my earning.

I do not get these rejections when using XMR-stak you mine directly to a Monero or Aeon pool.

Note: I literally just realized that my trap rigs have identical numbers of "job not found" shares... That's probably important...

**Comment by rpm604** [comment]
Note: I just rechecked and they are not the same... I can't remember if I rebooted one rig and not the other so I'll restart both and then see if they stay matched.

**Comment by DillonN** [comment]
Please keep discussion on pre-release to #487 

To help there you should post the contents of the config_nh.txt file, specifically if the use nicehash option is enabled
