### ISSUE TITLE
2 gpu not mining 

### ISSUE THREAD

**Issue by anishmaghan248** [nicehash/NiceHashMiner#694]
I have 2 Sapphire r9 390x and 1 sapphire r9 390 the 390x does not work while 390 is connected when i disconnect 390 then 390x starts working this is shown on screen "started sgminer 5.5.5-gm-nicehash-8
*Using janson 2.7" and the keep closing and opening 

![whatsapp image 2017-12-01 at 1 14 04 pm](https://user-images.githubusercontent.com/34090476/33473057-ec0a523e-d69a-11e7-8853-b0b936d3c53d.jpeg)
![whatsapp image 2017-12-01 at 1 13 55 pm 1](https://user-images.githubusercontent.com/34090476/33473058-ec52fea8-d69a-11e7-8f7d-6705ace73213.jpeg)

**Comment by DillonN** [comment]
sgminer for cryptonight can be a bit problematic

I recommend disabling it for the GPU that is causing it to run and sticking to the Claymore cryptonote miners

**Comment by anishmaghan248** [comment]
How to disable it please guide

**Comment by DillonN** [comment]
Simply uncheck it in the benchmark view
