### ISSUE TITLE
Get SMA - when to wait for fixing the problem?

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner#696]
Get SMA - when to wait for fixing the problem?
Today I spent two hours trying to run NHML one of the rig 2xRX480 (after reboot). 
Here for example resource https://vk.com/nicehashmining?w=wall-88552836_134942 - 3 complaints in a few minutes

**Comment by makzkzn** [comment]
About 3-4 days the miner does not work. The computer is idle ... It is necessary to use other programs. sometimes, with 10-20 attempts the connection is established, but not always. Inogda one copy is normally turned on, and the other is not (did for the test).
![nicehash2](https://user-images.githubusercontent.com/33400284/33495375-3c5441aa-d6d7-11e7-8530-dc3fe273c94b.jpg)
Tried different servers, without result.
