### ISSUE TITLE
Run some program on algo switch?

### ISSUE THREAD

**Issue by vovanius** [nicehash/NiceHashMiner#698]
Hello!
The question about NiceHash Miner Legacy for Windows: 
Is there a possibility to run some batch script or shortcut (*.lnk) when new miner window is started (algo switched)? I want to run scripts that applies GPU clocs, fan speed etc. according to algo.
If it is not possible for now, can it be implemented? This would be great.
Thanks in advance.

**Comment by DillonN** [comment]
Not currently possible, may be implemented in the future
