### ISSUE TITLE
64-bit Release?

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#7]
Looks like the Legacy Miner is a 32-bit release, any chance of getting a 64-bit release?

Thanks again for all the great work!!

**Comment by DillonN** [comment]
Maybe in the future but there is currently no planned 64-bit release. NHML itself won't benefit from 64-bit, and most of the miners are already 64-bit (they have to be to address enough memory)

**Comment by navjack** [comment]
i'm no programming expert but just making the little client 64-bit might just make it POSSIBLY use more resources for no gain since its just an intermediary lil interface to talk to nicehash and run benchmarking scripts and auto-update the mining binaries.

**Comment by billmcilhargey** [comment]
It will only use more resources if it is coded too (or if there is improper coding for example improper recycling of variables where memory leaks could occur)

**Comment by billmcilhargey** [comment]
@DillonN 
Can you target the sma_socket for this too?

**Comment by DillonN** [comment]
Sorry I also didn't mention, sma_socket does target x64 (although, that change hasn't been pushed yet)

**Comment by billmcilhargey** [comment]
ok nice!  Thanks again!

Will close once the change is pushed through a commit in that branch

https://github.com/nicehash/NiceHashMinerLegacy/tree/sma_socket

**Comment by DillonN** [comment]
The change has been pushed, however I would not recommend building off of that branch just yet. It isn't ready for production

**Comment by billmcilhargey** [comment]
Implemented in new branch, closing
