### ISSUE TITLE
No Internet connection

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/NiceHashMiner#700]
See attach
![ic_error](https://user-images.githubusercontent.com/33788644/33512184-b6fc6536-d73b-11e7-8d28-131495976616.jpg)

**Comment by Sav87** [comment]
there are probably more than 10 open questions, even with the proposed solution. Why bother?

**Comment by MichaelMiner** [comment]
[2017-12-02 07:58:20] [INFO] [SOCKET] Connection closed code 1002: An error has occurred while connecting.

**Comment by denismary** [comment]
всем привет! у меня аналогичная ситуация с жалобой на интернет! не пойму в чём дело? почему пишет что нет соединения с интернеторм. пожалуйста помогите разобраться
