### ISSUE TITLE
dstm's  Equihash Nvidia Miner 

### ISSUE THREAD

**Issue by pojik7** [nicehash/NiceHashMiner#704]
Please, add this miner in 3 part. This us fastest, stable and its live unlike ewbf

**Comment by quantumshadow** [comment]
1. There is already such topic. 
2. You didnt provide a link to miner. 
3. DTSM is fastest but is unstable. 29% rejected shares on nicehash pool. 
4. Comparing to EWBF there is no option to switch off dev fee.

**Comment by quantumshadow** [comment]
https://bitcointalk.org/index.php?topic=2021765.0

Thank you.

**Comment by pojik7** [comment]
I am mining few hour and i dont catch rejected shares.

**Comment by quantumshadow** [comment]
Good luck though.

**Comment by pojik7** [comment]
Im download this project, add ,this miner class and change him on ewbf base. All work fine. Reject is present, but hus count is minimal. Mi card is overcloack an d a have reject with ewbf. All fine. Please, add this miner in your project. In testing, at least.

**Comment by UselessGuru** [comment]
@DillonN 
Second this. Add this miner to NHLM.
DSTM ist the fastest equihash miner. I have not had any rejected shared with nicehash.

**Comment by quantumshadow** [comment]
DTSM just have no sence. 

https://imgur.com/a/2kbD4

**Comment by kaos-1** [comment]
@DillonN Please add DSTM into legacy or beta at least. It is the fastest miner currently and new pool optimized version works like a charm.

**Comment by DillonN** [comment]
Added
