### ISSUE TITLE
I am using 1.8.0.0 - ccminer issue - retry after 5 seconds ...

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner#705]
HI, i am not sure why i am using or thought 1.8.0.0 was the latest version.
Anyways, maybe the answer is download the latest version?
Before i waste my data and it is not that...

I get this when i mine:

![image](https://user-images.githubusercontent.com/25494601/33519196-beca96c4-d7aa-11e7-8cd2-cc14f964b801.png)

Ive tried a few regions for connecting.... USA, IN, HK, not sure why the `retry after 5 seconds...`

**Comment by DillonN** [comment]
Most recent version is now 1.8.1.8. This error suggests ccminer can't bind the threads, likely a memory or overclock related issue. Either way this is not an error in NHML.
