### ISSUE TITLE
Application Crashing/Closing on its own

### ISSUE THREAD

**Issue by cherokee91red** [nicehash/NiceHashMiner#706]
I started on the Support page so I will just paste my whole conversation thus far below. Anyone else had this issue where the app just shuts itself down? I can mine for sometimes a minute, sometimes 30 before it shuts down. The benchmarks are a lost cause, it shuts itself down almost instantly. 

Application Crashing
You
2017-11-30 14:03:00

Hi, I followed the instructions for setup in the Wiki for version 1.8.1.5. The miner crashes almost instantly after startup. The first time I had it going, it mined for maybe 20-30 mins. After that I can't even get benchmarks to finish before it just closes itself down.

Mining Software - NiceHash Mine rLegacy v.1.8.1.5
I can't really screenshot the disconnect, there are no error popups or notification. The App window just disappears off screen, followed a second later with the CMD window. It's just like it shuts itself down. I'll screenshot just what I see when active.
Hardware, Core i5-4690 CPU and XFX Radeon R7 370 GPU
-OS is Windows 10 Pro, Version 1709

NiceHash
2017-12-02 01:30:00
Please, open issue on GitHub regarding this matter where NHM Legacy developers will help you: https://github.com/nicehash/NiceHashMinerLegacy/issues

Kind regards,
NiceHash Team

**Comment by DillonN** [comment]
Can you post your logs/log.txt file after seeing a crash?

**Comment by CreamyG31337** [comment]
I can confirm the new version crashes sometimes but I don't remember the exact steps. Last night I also noticed I could also click the X and the window is gone but the task wouldn't end. It's fine if it's mining, just messing with benchmarks and settings screws it up, until you restart it I believe. Then it's okay.

**Comment by cherokee91red** [comment]
Log attached. 

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1524528/log.txt)

**Comment by DillonN** [comment]
It seems as though sgminer is crashing, this is a known issue being looked into

Also, if you are using Remote Desktop Protocol, it has an incompatibility with sgminer that will cause crashes

I would recommend enabling third-party miners in settings (or agreeing to it on initial setup), they are generally more stable and perform better for AMD.
