### ISSUE TITLE
1.8.x no profitability/socket connection errors

### ISSUE THREAD

**Issue by DillonN** [nicehash/NiceHashMiner#707]
There are a lot of issues open with this common problem. To help streamline discussion I will redirect all future issues to this one

*As it stands* NHML uses a popular websocket library to connect to NH servers and get profitability/some other data. When NHML is launched it makes several attempts (separated by 1 second intervals) to connect, and if the connection has failed every time, will show the no profitability data error. After launch if the connection is dropped (or if user clicks OK to keep the window open on initial error), NHML will attempt to reconnect every ~1 min. 

In 1.8.1.5 and earlier there is not great detail for *why* the connection is failing. This has changed in 1.8.2.0-Pre2, where logging is increased for the socket connection so that you may see specific errors preventing the connection. 

For users having these problems, if you could try using 1.8.0.0-Pre2 and checking the logs for the error codes it would be helpful. You will see errors that look like this:

```
[2017-11-28 03:51:06] [INFO] [SOCKET] 11/28/2017 03:51:06|Debug|WebSocket.sendHttpRequest|A request to the server:
                          GET /v2/nhm HTTP/1.1
                          User-Agent: websocket-sharp/1.0
                          Host: api.nicehash.com
                          Upgrade: websocket
                          Connection: Upgrade
[2017-11-28 03:51:06] [INFO] [SOCKET] 11/28/2017 03:51:06|Debug|WebSocket.sendHttpRequest|A response to this request:
                          HTTP/1.1 503 Service Temporarily Unavailable
                          Date: Mon, 27 Nov 2017 23:51:06 GMT
                          Content-Type: text/html
                          Transfer-Encoding: chunked
                          Connection: keep-alive
```

In the second entry you can see the HTTP code received, in this case 503. 

So if users with this problem could post here the error codes they see, that will help diagnose the issue

**Comment by Sav87** [comment]
all have one error 503. after about 30 seconds of the frozen window caused by this error. the program blocks the message. which must be manually closed. After an undefined time, a connection to the websoket occurs, but the start does not happen any more. the program is blocked by a message.

**Comment by Sav87** [comment]
at #625. I added messages with a timer, attempts to start in a circle, getting data by the old method (before switching to a websocket) if the data does not arrive in 20 seconds.

**Comment by boyod** [comment]
probably when using websoket the problem is that NH generates frequent queries (every second ... SMA ...) that creates an opinion about the attack on the resource, hence Cloudflare forbids  to connect - 503 error

**Comment by xermalk** [comment]
This is just silly, everytime i shutdown the miner i have to force a ip change or i wont be able to start mining again.

> [2017-12-03 21:44:00] [INFO] [SOCKET] 12/03/2017 21:44:00|Debug|WebSocket.sendHttpRequest|A request to the server:
>                           GET /v2/nhm HTTP/1.1
>                           User-Agent: websocket-sharp/1.0
>                           Host: api.nicehash.com
>                           Upgrade: websocket
>                           Connection: Upgrade
>                           Sec-WebSocket-Key: +mrggqk0EXwoli4qAyp+Sw==
>                           Sec-WebSocket-Version: 13
> [2017-12-03 21:44:00] [INFO] [SOCKET] 12/03/2017 21:44:00|Debug|WebSocket.sendHttpRequest|A response to this request:
>                           HTTP/1.1 503 Service Temporarily Unavailable
>                           Date: Sun, 03 Dec 2017 20:44:02 GMT
>                           Content-Type: text/html
>                           Transfer-Encoding: chunked
>                           Connection: keep-alive
>                           Set-Cookie: __cfduid=ddde1ee70ef622ba150705a21007386d61512333842; expires=Mon, 03-Dec-18 20:44:02 GMT; path=/; domain=.nicehash.com; HttpOnly
>                           Server: cloudflare-nginx
>                           CF-RAY: 3c795c921df08673-ARN
> [2017-12-03 21:44:00] [INFO] [SOCKET] 12/03/2017 21:44:00|Fatal|WebSocket.connect|Not a WebSocket handshake response.
> [2017-12-03 21:44:00] [INFO] [SOCKET] 12/03/2017 21:44:00|Debug|WebSocket.closeHandshake|Was clean?: False
>                             sent: False
>                             received: False
> [2017-12-03 21:44:00] [INFO] [SOCKET] Connection closed code 1002: An error has occurred while connecting.

**Comment by errogaht** [comment]
OK, NHM is no longer work? I cant use it 2 days. (no internet connection error)

**Comment by utc99** [comment]
Is this a same issue as no profitability data? I'm really tired of fixing this in every second worker every now and then? Is there a plan and solution to fix this issue?

**Comment by utc99** [comment]
Again, another worker:
![image](https://user-images.githubusercontent.com/26816096/33651612-33dac7ba-da6f-11e7-9d51-a6267e861927.png)
After this, miner crashes, freezes, or just does not start mining.

[2017-12-06 10:12:51] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-06 10:13:23] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-06 10:13:55] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-12-06 10:20:40] [INFO] [NICEHASH] Bitcoin rate get
[2017-12-06 10:21:10] [INFO] [NICEHASH] The operation has timed out
[2017-12-06 10:21:10] [INFO] [ExchangeRateAPI] UpdateAPI got NULL
[2017-12-06 10:21:10] [INFO] [NICEHASH] Current Bitcoin rate: 0.00

This happens on multiple NH versions

**Comment by utc99** [comment]
Could this be the reason for #715 ? Incorrect profitability data?

**Comment by davidzwa** [comment]
Still a bug -_-
