### ISSUE TITLE
No supported devices were found with RX560

### ISSUE THREAD

**Issue by Mucko07** [nicehash/NiceHashMiner#708]
Hi,

I'm trying to use NHML with my Gigabyte Radeon RX 560 on Win7 64bit and I receive the above error.
Mining from command line works fine.
Drivers are latest Crimson ReLive.
Attaching the log files of NHML
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1524388/log.txt)
and also the AMD detection logs:
[debug_all_out_AMD.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1524389/debug_all_out_AMD.txt)

Please kindly advise how can I fix this

Thanks in advance,
Mucko07

**Comment by DillonN** [comment]
The AMD drivers are returning an error when NHML requests a list of devices

Try reinstalling drivers or using a different driver version.

**Comment by ghost** [comment]
ваш совет полная хрень. Нихрена не работают rx560 на найсхеше. СКАМ НАЙСХЕШ
