### ISSUE TITLE
Question: 1.8.0.2 - Keccak Nvidia

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#71]
@DillonN  (or anyone that is able to answer)

In the release notes you mentioned

If you use NVIDIA Inspector's Multi Display Power Saver feature it may cause the benchmark to display low speeds

Is this a special setting you set within the Nvidia application or does this relate to the Nvidia P0 state in NHML?

**Comment by DillonN** [comment]
Neither, NVIDIA Inspector is a third party tool that lets you edit some hardware options for NV GPUs. This feature specifically lets your GPU clock down when you have more then one display (NV default is to run at 3D clocks which sucks a lot of power at idle). It seemed to cause some issues for the benchmark for me so I put the warning there

**Comment by billmcilhargey** [comment]
aww thanks!!

closing!
