### ISSUE TITLE
Constantly Crashing During Benchmark [AMD RX 580]

### ISSUE THREAD

**Issue by bmaccafferty** [nicehash/NiceHashMiner#710]
I just downloaded 1.8.1.5 and the application has been constantly crashing. So far I have not yet made it past the bench-marking phase. I am currently running Web Root as an Antivirus and I've completely disabled scanning. The applicaton never actually crashes when idle, only when bench-marking.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1524510/log.txt)

**Comment by bmaccafferty** [comment]
So far, the farthest I've gotten is step 7/12 bench-mark on the quick setting.

**Comment by DillonN** [comment]
Don't see any issues in the logs. You can try benchmarking algorithms one at a time, and disabling the algorithms that cause the crash. The sgminer algos in particular can be unstable in some conditions. claymore_dual algos should provide the best performance for you, you can try [manually benchmarking](https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Getting-started#manualbenchmarking) them and running for some time to see if they remain working.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
