### ISSUE TITLE
8+ Same Brand GPU Support 

### ISSUE THREAD

**Issue by esenocak** [nicehash/NiceHashMiner#711]
I have 13 gpus running under win10 without any problems with different miners, but NH Miner Legacy can not recognize all the devices and does not open. It hangs at the stage of "Checking AMD Open CL GPUS..." while opening and freezes at that stage.

**Comment by Alexus6** [comment]
Привет. Как тебе удалось запустить 13 GPU ? У меня win10 говорит, что нехватает ресурсов системы. 
А как вариант, может запустить два экземпляра NHML ?
---
Hey. How did you manage to launch 13 GPUs? I win10 says that I lack the resources of the system.

And as an option, can run two copies of NHML?

**Comment by esenocak** [comment]
I have asrock h110 pro btc mainboard with 13 asus 1080ti installed on. With
1709 update of win10 (fall update) it now supports 8+ gpus. Nowadays I'm
mining with Awesome Miner without any problem.

NH Miner can not be opened with 13 gpus. I don't know why?

5 Ara 2017 07:00 tarihinde "Alexus6" <notifications@github.com> yazdı:

**Comment by Nisseiparken** [comment]
I have the same problem with Legacy 1.8.2.0 Pre 2
I have 12 1050ti on the Asrock h110 pro. The program hangs on Checking AMD.
I edited the config file so it would not check AMD but it does not help

**Comment by DillonN** [comment]
Could you post your logs\log.txt file? If you have disabled AMD detection then the NVIDIA detection is falling through very quickly. I unfortunately do not have an 8+ rig to test with but it is possible the NVIDIA detection exe does not work on high GPU counts

**Comment by Nisseiparken** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1747987/log.txt)
Here is an old log file I dont have the instalation enymore so I cannot make a new logfile

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
