### ISSUE TITLE
Xmr-Stak timed out on NHML 1.8.2.0 Pre 2

### ISSUE THREAD

**Issue by virtakar** [nicehash/NiceHashMiner#712]
Running NHML 1.8.2.0 Pre 2 on an AMD FX-8320E and an AMD R9 Fury.

Benchmark for CryptoNight using the new Xmr-Stak fails on both devices, even on precise setting, whereas the miner works and the hashrate looks correct for the GPU. The miner works for the CPU as well but the hashrate is 80 H/s whereas on manual it reaches 350 H/s.

CPU log file:
[Log_GEN-c57618a8622dc86eecd9e3e41031996140af22655e5a66bb9673e31669b26bea_XmrStak_CryptoNight.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1524583/Log_GEN-c57618a8622dc86eecd9e3e41031996140af22655e5a66bb9673e31669b26bea_XmrStak_CryptoNight.txt)

GPU log file:
[Log_PCI_VEN_1002&DEV_7300_F1D09F1_XmrStak_CryptoNight.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1524581/Log_PCI_VEN_1002.DEV_7300_F1D09F1_XmrStak_CryptoNight.txt)

**Comment by texke** [comment]
Had this same issue, so debugged commit https://github.com/nicehash/NiceHashMinerLegacy/commit/28afc1881e1d068680d51f916f520f03e681e8ad

Line 177 of XmrStak.cs should be:
`if (!double.TryParse(s, NumberStyles.Number, CultureInfo.InvariantCulture, out var speed)) continue;`
This code represents benchmark code of version 1.8.1.5

Let me know if you're able to compile your own version with this, if not, I'll open a pull request / make my own release :-)

**Comment by texke** [comment]
Screw it, I'm bored,, here is the compiled exe:
https://github.com/texke/NiceHashMinerLegacy/releases/tag/1.8.2.0-Pre2

Created a pull req #807 aswell

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
