### ISSUE TITLE
cannot disable dependency on the WMI service

### ISSUE THREAD

**Issue by FlorinAndrei** [nicehash/NiceHashMiner#716]
I'm trying to run NHML with Wine under macOS. When launching `wine NiceHashMinerLegacy.exe` I get a pop-up saying the windows management instrumentation service (WMI) cannot be found, and the app quits.

Since this is macOS there's no WMI.

Is there a way to disable the dependency on WMI and allow the app to get started?

**Comment by boyod** [comment]
run not in Wine but in a virtual machine with Win7 or Win10

**Comment by HaTaX2** [comment]
What version of Wine are you running? It looks like 1.6 has support for some WMI functionality, and it should at least allow you to open NHML.  NHML uses WMI for a number of things and bypassing the WMI check would most likely result in it not working or not listing any mining devices.

**Comment by RealityRipple** [comment]
It might be a lot easier to just run the miners yourself and point them to the applicable NiceHash pools by hand...

**Comment by DillonN** [comment]
NHML relies on WMI for some core features. We only officially support Windows right now.
