### ISSUE TITLE
1.8.2.0 Pre2 Benchmarking broken?

### ISSUE THREAD

**Issue by Renkyz** [nicehash/NiceHashMiner#717]
I can't get through a single benchmark run after downloading NHML v1.8.2.0 Pre2.
I've tried quick, standard and precise and they all result in the same way. I turn my monitors off and walk away while it benches because of how long it takes. When I come back and turn the monitors on, there's no signal to the monitor and I have to reboot my PC. Once rebooted, I go back to the benchmark page and every algorithm states it hasn't been benched at all. I guess it's crashing my graphics driver???

**Comment by techman05** [comment]
They are not broken, they are just anoying at this point. I have what I thought was a stable system and had it crash my pc. What you need to do till its smoothed out is benchmark the ones you think it'll use abd do them piece by piece or download the current release and do the benchmark there and bring it over. They are in the configs folder though do note it was in the prerelease they may not be backward compatible so be aware.

**Comment by Renkyz** [comment]
Bit late, NiceHash is dead now. I've gone back to mining Ethereum, Zcash and Monero to Nanopool.

**Comment by DillonN** [comment]
1.8.2.0 is in pre-release and there are some known issues in benchmarking that need to be worked out before it is ready
