### ISSUE TITLE
 Very nicehash software income very nicehash and on the site of the nicehash shows down there

### ISSUE THREAD

**Issue by giordanbetat** [nicehash/NiceHashMiner#719]
Hello, The versions are 1.8.1.5 or 1.8.2.0 Pre Realase 2 are giving X11Ghost a much higher income than the common and on the site of the nicehash where to accompany the income it is down there, could you help me?

**Comment by maxgamurar** [comment]
check this out:

https://github.com/nicehash/NiceHashMinerLegacy/issues/715#issuecomment-349171443
