### ISSUE TITLE
1.8.0.2 - GUI - Settings Cut off

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#72]
In previous versions I did not have the problem mentioned below

My resolution is 1024 x 768

When I open settings, the settings screen is cut off

![capture](https://user-images.githubusercontent.com/19168174/28640108-a3daa644-7218-11e7-91f9-36e8fa36b5d4.PNG)

**Comment by microtechies** [comment]
Same with all of my machines

**Comment by DillonN** [comment]
I think this may be related to Visual Studio trying to offload my screen's DPI to the interface editor. I'll work on a fix for this now

**Comment by erwinfauzirais** [comment]
same with my machines, i can't save my setting ... how to fix it??

**Comment by billmcilhargey** [comment]
ALT+S

**Comment by erwinfauzirais** [comment]
thx

**Comment by DillonN** [comment]
@computeronix would you mind trying a build with the latest commit (6601bd3c0a05f60a57439ab2f94c204d2eaa3e19)? It's now working for me on an 800x600 screen

**Comment by ALEXEY-SOFT** [comment]
The window in the resolution 1024 * 768 is cut off in the algorithm selection field. As a result, it is impossible to save the results.
![2017-07-27_075901](https://user-images.githubusercontent.com/8391898/28654260-fd8aeee8-72a3-11e7-9816-f7182214f8a2.png)

**Comment by billmcilhargey** [comment]
ALT+S

Yes still cut off  the Algorithms screen was fine after the commit the Algorithms screen is adjusted now

**Comment by DillonN** [comment]
Sorry @computeronix, do you mean you still had the issue present?

**Comment by ChriscomIT** [comment]
I understand as its fixed with the commit but just @computeronix can really confirm.

**Comment by DillonN** [comment]
I have made a pre-release with the fix, if others that are experiencing the issue could try it out I'd appreciate it. Just copy the .exe file over the current one

https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.0.3-Pre

**Comment by billmcilhargey** [comment]
Sorry for the delay, yes the pre-release for me has resolved the issue

Thanks!! - closing this out

**Comment by billmcilhargey** [comment]
reopened saw you had the comment linked here in the release page, my issue is resolved and will let @DillonN closed once the release is pushed

fyi pre-release still says 1.8.0.2 for version :) but that will be corrected in the final release

**Comment by jerrychen007** [comment]
I'm afraid there are more bugs show up with the 1.8.0.3-pre. There is a warning message about "an error can not solve" (sorry for the Chinese). And some words are missing in the settings. I think it's related to the Net Framework. @DillonN 
![20170803122257](https://user-images.githubusercontent.com/28459583/28937090-ffc5f092-7846-11e7-942f-92bc5decc43b.png)
![20170803122150](https://user-images.githubusercontent.com/28459583/28937089-ffb7a758-7846-11e7-89de-6ad5c4349f95.png)

**Comment by DillonN** [comment]
Yes looks like this worked, I'll leave the issue open for now in case anyone has problems and sees the link on the release page
