### ISSUE TITLE
NHML 1.8.5.0 - Mining on NVidia dead, card not (stoped) recognising in NHML.

### ISSUE THREAD

**Issue by boyod** [nicehash/NiceHashMiner#720]
After some time (several hours) falls off in the NHML NV graphics card!

**Comment by nerdatwork** [comment]
What do you mean falls off ? Try google.translate.com if you have problem with English.

**Comment by Sav87** [comment]
if the power supply is OK, there is no overclocking, it works stably on one algorithm, and crashes only in a multi-algorithm. then this is a known problem.
если с питанием все в порядке, разгона нет, работает стабильно на одном алгоритме, и сбоит только в мультиалгоритме. то это известная проблемма.

**Comment by boyod** [comment]
Mining on NVidia dead, card not (stoped) recognising in NHML.
Mining on AMD still worck fine!
in past was everyfing good!

**Comment by kuzotronic** [comment]
Try reinstalling nvidia drivers with DDU. I had the same thing with my amd/nv rig where amd gpus were not recognized.
