### ISSUE TITLE
getting Nicehash SMA infromation.....

### ISSUE THREAD

**Issue by k4r4sm4n** [nicehash/NiceHashMiner#721]
and then the message about problems with internet connetctions. what does it mean?

**Comment by Arnseb** [comment]
Common problem which I have aswell. 
There are two possible solutions:

1. Disable ipv6 on your network device (works for some)
2. Get a VPN (cloudflare blacklists people by mistake)

A work-around if nothing works is to disable "Idle When No Internet Access" and enable "Start Mining When Idle".
This makes Nicehash try to start mining every 60 sec when idle (no mouse movement), and eventually it will start (hopefully).

**Comment by k4r4sm4n** [comment]
This didn't change anything. I saw these recomendations on forums and already done. Still about 30 times of 31 stopping on getting SMA information. vpn helps but impede other tasks that uncomfortable
