### ISSUE TITLE
MultiCPU

### ISSUE THREAD

**Issue by ronaldogg** [nicehash/NiceHashMiner#723]
Good afternoon!

I'm new to mining and I'm using your system.
Today I have a DELL R720 server with 2 physical processors, which adds all threads with 24 Threads. When I run the application from you, it identifies the 2 physical processors, and when I run the mining whatever, in my case the CryptoNigth, there are all 24 Threads processors being used, however, the $$ value only shows $ 0.32 on one processor and the other shows $ 0.45, totaling a high of $ 0.82 per day.

When I just enable 1 processor, it will mine $ 1.20 per day. When you enable the 2 processors, it miners less than if it were a physical processor.

The issue is that I have other DELL R910 servers with 4 physical processors totaling 40 Threads. In other words, your application performs better with 1 processor than with 2 or 4 physical processors.

I believe this is just a setup issue and nothing more. Because it does not make sense to have 2 physical processors, where the return is better with only 1 processor.

I have already examined several sites asking to change the Config.txt file and config_0.txt, asking them to add lines that tell the amount of Theads and physical porcessors, but without any success.

Could you help me with that question?

**Comment by OnkelAdi** [comment]
2MB of cash memory need for every thread

**Comment by ronaldogg** [comment]
Okay, but my processors are of the Xeon line with 2.0 GHZ and 6 MB of cache in each processor, and yet it does not have performance.

**Comment by ronaldogg** [comment]
correct model.
2x Xeon E5-2620 - 2.00 GHz

**Comment by OnkelAdi** [comment]
My E5-2665 (20MB, 8cores w/HT) does 10 thread of the xmr-miner.
Maybe it helps you if you start 2 miners - 1 miner for each chip?

**Comment by ronaldogg** [comment]
So would you mince 1 coin on each processor? If so, I'll try it when I get home.
