### ISSUE TITLE
1.8.2.0 pre 2 - computer freezes when benchmarking all cards at the same time

### ISSUE THREAD

**Issue by stopsign002** [nicehash/NiceHashMiner#725]
2x1070s
2x1080tis

I have been unable to figure out why the benchmark is crashing with this system. I am running the newest nvidia drivers, and this worked with my 8x1070 rig but not this rig. Here is the log file. Please see 2017-12-05 21:17:06 for an instance of the miner crashing, though there are many instances of it crashing in this log. 

The computer will freeze to the point where remote desktop stops functioning. I do not have a monitor on that rig. Everything seems to be working fine with the previous nice hash release. I went back to it and am mining fine and have never had any issues with benchmarking. Let me know if I can provide any more information

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1533688/log.txt)

**Comment by DillonN** [comment]
There are some known issues with benchmarking in 1.8.2.0. It is not ready for regular use if you rely on the benchmarking feature.
