### ISSUE TITLE
Crash at SMA ( miner starts not responding on windows)

### ISSUE THREAD

**Issue by texposto** [nicehash/NiceHashMiner#727]
Hi, 

I have two rigs which did a scheduled restart, and now when the miner opens, during the form loading, once it gets to Getting SMA. It crashes, the application doesnt move anymore, cant do anything.

In Task manager it says form loader is not responding.

Best regards

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by EGCvapology** [comment]
I am not fully sure if this may be related, however I updated to the new legacy version (1.8.2.0 PR2) and I am getting stuck at the loading screen saying "getting nicehash sma information". It won't load any further into the application. I have restarted my computer as well as reinstalling the software, no luck as of yet.

**Comment by AbdelhamidGamal** [comment]
Same problem here

**Comment by EGCvapology** [comment]
I updated to the new legacy version (1.8.2.0 Pre2) and when I launch the application the loading bar gets stuck on "getting nicehash sma information". I restarted comp and reinstalled still no luck.

**Comment by Symbelmyne** [comment]
I`m having same issue with both 1.8.1.5 and .1.8.2.0 clients. Tried linked somewhere here temporary fix files but it didnt work. Any other ideas?

**Comment by EGCvapology** [comment]
I just went to their website. It seems they are undergoing maintenance. Maybe this has something to do with trying to login to the servers? "We are currently in maintenance mode - some parts of the website might be unavailable." - at bottom of main page.

**Comment by Pitons777** [comment]
same problem here
yep site also not responding

**Comment by neverfallagain** [comment]
Yeah, this started today for me.

I've uninstalled Comodo, Avast and Malwarebytes software,  No change.

I removed configs, checked logs, and it seems apparent that both mining programs are unaware of any problems or reporting any problems.

It seems that it could have something to do with win10 inbuilt detection.  but im all out of ideas.

I usually use the Pre2 release, without issue.  I upgraded to '2' today, and that works but can't connect to anything externally.

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1534554/log.txt)

**Comment by AbdelhamidGamal** [comment]
the error is not from your machine guys , nicehash is down

**Comment by neverfallagain** [comment]
Weird, this was happening before nicehash went down, like last night., close to 28 hours now, and why would that escalate into the program not even opening?

**Comment by eriscanis** [comment]
I have the same problem with all the versions

**Comment by texposto** [comment]
the site is completly down.
in the miner  if it manages to go through i always get that profitability error. i dont know if i should restart the miner or keep pressing ok and see if it starts. im already 2 hours down, money is not coming in

**Comment by AbdelhamidGamal** [comment]
I'm mining eth on claymore till this is fixed

**Comment by spider72** [comment]
Heard now they been hacked....rumours so far....

**Comment by IsaacD136** [comment]
lol "hacked" really?

**Comment by Sloppy9649** [comment]
They are down for maintenance. Check their twitter.

**Comment by spider72** [comment]
Check Reddit.....

**Comment by IsaacD136** [comment]
well hopefully it's just a rumour tho

**Comment by spider72** [comment]
Been off for 'maintenance' for 5hr....check your BTC balance on blockchain explorer is 0

**Comment by imrecsoka** [comment]
what block chain - do u mean here -> https://blockchain.info/address
Mine is what it was, but i am waiting for next payout, i think it is Friday this week or next week.
People contribute fees to the pools.

**Comment by levtmn** [comment]
same problem of 1.8.1.5 - task manager says that program is hanged up

**Comment by Buckthebarbarian** [comment]
Nicehash got hacked, 60M $ stolen. https://www.reddit.com/r/NiceHash/comments/7i0s6o/official_press_release_statement_by_nicehash/

**Comment by IsaacD136** [comment]
https://bitinfocharts.com/bitcoin/address/1EnJHhq8Jq8vDuZA5ahVh6H4t6jh1mB4rq what an amazing amount isn't it
