### ISSUE TITLE
nicehash is over?

### ISSUE THREAD

**Issue by k4r4sm4n** [nicehash/NiceHashMiner#728]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by Braintelligence** [comment]
People should rephrase "you can delete this text" to "you should delete this text if you're just shit posting".

**Comment by DillonN** [comment]
Official statement here - https://www.reddit.com/r/NiceHash/comments/7i0s6o/official_press_release_statement_by_nicehash/

Sorry, don't have any more info than what is on there. NHML won't work for the time being

**Comment by Braintelligence** [comment]
I know what you mean but

1. What do you expect people to tell you on this Development Platform?
2. Why did you keep the template text? 
3. Why did you create an issue with no text body like some clueless kid?

**Comment by Buckthebarbarian** [comment]
@DillonN I know this must be a difficult situation for you as well but I had some questions; are you affiliated to Nicehash? Do they pay you for the developement of NHML? In case of a complete shutdown, would all the work you put in to create the legacy miner be transferable to a similar service such as winminer or minergate? Thanks for all you have done for us miner DillonN!

**Comment by imrecsoka** [comment]
I am sure NiceHash team have a plan for everybody and i am sure they will be able to pay everybody back their earnings before it was taken away.
If it is gradual or immediate its great.
If they can not fully credit then I hope they can consider a bandwidth system for payment where weak miners get compensated as much as strong miners such that there is a percentile of this involved.
Example would be if you managed to mine 20$  then all 100% or near should be paid, and even up to 100$, same thing, and for the stronger miners maybe less percentile.
For the guys who earn wads of rewards, like 200$ then maybe they get 80% , something like this?
Also, not sure why the payments dates were so far apart from my last experience - used to be 1 - 2 weeks and then it crept up to 3 - 4 weeks. Thats very painful for small weak miners.

**Comment by SecurityImportant** [comment]
Yes NiceHash is Over! 

They cannot recover from a full wallet wipe - and at they same time being developers of high-end security/cryptographic software! 

The complete flaws in their system is that they are able to be developers of such a secure matter but unable to secure the users! Insider job?

I suggest you read my posts here: https://github.com/nicehash/NiceHashMinerLegacy/issues/729

 DillionN - Hmm... I suggest you submit yourself to the police in your country for evaluation of your actions... the longer your delay the more likely is the criminal prosecution! 

Till now Interpol and Europol have not received notice that you have surrendered yourself. The time in GMT is 19:13 I suggest you do contact the nearest police station and attach such matter ASAP RE 60+ Million theft.

**Comment by SecurityImportant** [comment]
If you are innocent I shall be happy to support you! But till you submit yourself to either a Western or Asian police authority for validation of this matter - you are to be considered a fugitive on the run!

**Comment by malventano** [comment]
@SecurityImportant - look man, whatever you lost to NiceHash has zero to do with @DillonN or any of the other folks who submitted code patches to improve upon the Legacy Miner. You're barking up the wrong tree.

**Comment by DrRobotto** [comment]
@SecurityImportant - So, I mined over 4 BTC over the last 8 months with nicehash and was always pleased by their service. However, I always transfered my BTCs to my personal wallet due to personal security concerns on EVERY service on the internet. I even have a cold storage in place. So this week I have lost 42 bucks, mee, even not worth mentioning ...

**Comment by imrecsoka** [comment]
I dont even think Dillion has anything to do with Nicehash, he just wrote this code for interested miners that like the legacy look, and i think he has done a great job.
Im just sad though that i lost 130USD and it took me 5 weeks to mine, fuck sake.
Really sad about it.

**Comment by malventano** [comment]
@imrecsoka he didn't even write the full miner, he only improved on the 1.x version of the original NiceHash miner code base. He did so well that NiceHash officially supported the fork, which is why the code is back under their official account currently.

**Comment by imrecsoka** [comment]
Yeh, sorry i was not great at the elaboration, but anyways great work still was my message.
Just so sad man, really.
I dont know what is next for me.
I try coins manually and then to find pools is a fucking pain because of they dont seem to show pending "anything" which seems crapy to me.
*sigh* a millions times, shit  i cant believe this

**Comment by SecurityImportant** [comment]
Sympathies??? Can anybody show me a single developer homeless and destitute after a $60-70 million theft?

What about the thousands of people that sold their life and electricity e.g. third-world people for those $60 million???? 

Ahhh - the response is sad! People are having debt collectors enforce repayments but - sad face for the developers that were getting big cuts of $60 million system?

**Comment by malventano** [comment]
The Legacy miner is maintained by @DillonN , who does not work at NiceHash. This is not an appropriate place to voice your concerns - it is for the development of the mining app.

**Comment by SecurityImportant** [comment]
malventano: You know I know your system... here you accept criminal liability and knowledge of how this system works... you also defend a worker AND CRIMINAL beneficiary of this system! So, you are stating that you are part of the deep inner circle of this $60 million fraud?

**Comment by luongk** [comment]
@SecurityImportant You're probably not going to believe me, but nobody on this repository works for NiceHash.  There is no conspiracy here, there is no inner circle, we're all just users like you.

You're complaining to the wrong people.

**Comment by SecurityImportant** [comment]
No I do not believe you - we can meet in HK, Taiwan or Singapore in an embassy of your wish!

You will need to attend the embassy 48 hours before and show identity - once I have been informed of such we can meet.

**Comment by luongk** [comment]
I find it exceedingly racist that you continue to assume that I'm from an Asian country.

**Comment by SecurityImportant** [comment]
Do you? Get over it - $60M under your watch and you are close to multiple criminal charges! However, thanks for that line - which part of the UK is good for you?

**Comment by malventano** [comment]
For those curious, the offending user has been removed from Github. Turns out the report feature works quite well.

**Comment by luongk** [comment]
@malventano *highfive*

**Comment by ghost** [comment]
@SecurityImportant all u base a belong to us

**Comment by DillonN** [comment]
Ah I didn't get a chance to see any of the comments before the account was removed

To anyone else who has issues and wasn't around when NHML started, what most people have said here is true. I maintained a fork of NiceHash Miner 1 back when they moved on to NHM2, and soon after that they saw the demand for an updated version of the original NHM1 (which became this repo NiceHash Miner Legacy). The repo I maintained back then is still on GitHub [here](https://github.com/DillonN/NiceHashMiner). The current version of NHML is essentially a fork of that repo (in the git sense, not the GitHub sense), so most of the advancements from then are in the current version of NHML (e.g. ClaymoreDual switching, etc.). It may be worth mentioning that back then, NHM2 was designed to be a full replacement for NHM1 and supported AMD (today it is NVIDIA/CPU only).

For transparency, those asking my affiliation with NiceHash, I am contracted for the development of NiceHash Miner Legacy only. As such I don't have info on the current status, and don't have answers for concerns over it. You will have to contact NH for those concerns, but you can find information on their press release I linked above. I can say that I have faith in the NiceHash team and don't have plans on abandoning this project. This is a regrettable situation, and personally (as a user of NHML) I also had BTC in the service, so I understand your concerns. I definitely appreciate all the support from users here!

**Comment by niknewb** [comment]
@DillonN thanks for your work.
NHM2 is a complete garbage even for nvidia and I hope you will still be working on NHML if NH team won't abandon their project.

**Comment by Buckthebarbarian** [comment]
@DillonN Thank you for your answer and honesty. I think everyone that has spent time here realizes the work you have put in this project has been tremendously helpful for all of the miners. Let's hope that NH servers will be back online soon!

**Comment by imrecsoka** [comment]
You will always be supported by me at least , i am waiting for Nicehash servers to come back. I believe they will make a plan in terms of crediting and worst case even fractional credit to begin with.
As for your work and what reward i have managed to return to myself in my last session , i support this.
Just very sad i was not able to get that reward as i was intercepted 2 days before it was paid out. 130 USD in 5 weeks, really hurts me and makes me sad.
Looking forward to mining again and donating.

**Comment by SecurityPoliceWill** [comment]
The more I investigate and the more I see I fairly say many of the developers I have had verbal issues with are probably innocent - yes, not what thousands want to hear after losing money - many in third-world nations that still have an electricity bill the size of their year's salary or so...  

This does not mean that they provided a #1 software product for users: I could talk for hours about NHML etc and their issues - but it was summed up by DillonN saying that such software had Zero security! Sad but true.

Previous threads, including: https://github.com/nicehash/NiceHashMinerLegacy/issues/732 have stated my position.

I do believe it was probably an insider job: as confirmed by NiceHash re an employees computer and some VPN. I do not see how a company of this size can even have an employee computer connected to a machine that has the entire wallet linked on it - Santa came early and took the third-world nation's miner's child's present with him! :( 

I could be wrong regarding the developers.....

The issue with the developers is that they were basically using third-party mining software that only needed a config/cmd run or similaar form based system that created the config and then provided the user with a GUI interface that connected to NiceHash to get current balance etc.. That is basically what it did in a GUI - connect to NH every so often and upate the user's GUI. 

When a full honest c# forms RDP session can be done in about 30 mins to 2 hours etc of code work. What was the NHML that got flagged for viruses and trojans and a mailto registry issue? 

My present view is that corporation tax for NiceHash created an issue as the jump from $7000 to $15000+ in the corporate wallet caused a corporate taxation issue - as customers would seek payout at current prices, but as it was the company wallet (the company would be liable for millions in tax) they would be liable for profit taxes from $7000 to $15000+ per BTC x 4000+ BTC is a lot of tax (millions)! 

But customers would still seek payout at market rate/BTC balance (same)! So there was no escape! The 0.0003BTC+ would never cover such tax bill!

I have dilligently read through the threads and cannot see how such crypto and security aware professionals could link an employee computer for a $60-90M withdrawal (VPN or not).

So here we are as a user and critique - my theory above!

I have been banned and blocked before by NH but... I have a valid voice!

**Comment by SecurityPoliceWill** [comment]
I think I have hit the nail on the head! 

If the wallet was a corporate wallet then capital gains or profit tax would be applicable at the rate for the country. At the minimum we are looking close to 20% x 4700 x 15.000 (the lower cost of BTC)  = $14 million for that month. Slovenia probably has many other taxes that add to it! In the UK this would be treated as other speculative/derivative income and cannot be offset easily. Slovenia has DEC 31 as Tax date - so,my guess existing tax bill + $14ish million stopped this company! 

So, of you are in control of a company - what would you do? Whistle a bit, leave the door open (VPN/Employee computer) and go for a walk for a few hours, come back and shout thief?

If this was the real West - the entire systems would be locked down for forensic analysis, no data would be permitted to be given to the public e.g. the attack vector image posted on reddit and a lot more.

As one person said - given such info and a happy happy person jumped up and down saying "we shall find them" and get the private key! Umm, unless the private key hash = "password" as one pointed out  it could take 50+ years (and that is assuming each NH user upgrades to the latest equipment each year for the 50 years and Moor's law of doubling power remains! And in 50 years when we are grey or our grand children are there you/they get your 0.01BTC or lower :)

Bottom line NiceHash had a Nice Idea! lease computing power and sell such. 20 year back when I was a lot more energetic - there was a company called GO ___ they would rent your screen to bombard you with adds and based on your watch time you would get paid XYZ. They closed at some point!

Which brings me to a question why is GPU better than a CPU. Yes and NO! A GPU can be used by a program to do computations like a CPU. However, a CPU is needed to start and also verify GPU that affects an OS and bud data movement.

When I did assembly language - about 20+ years back video RAM was used for display (as it sill is) But as my question to NH "does the graphics card screen capture - a security issue e.g takes screenshot of your bank screen" NO reply!

Not a single NHML programmer was able to answer this.... The answer is yes it does and NH does bring in its on .dlls so the value is that it does have access to the screen VidRAM - that is why when the miner is closed it causes a flicker of the screen when it closes (video ram was owned by the miner and then released back to the user).

One user gave a nice answer: if you want security mine on one computer in a isolated network - he was correctish! However, that is an issue - you are then freeing a potentially infected computer to infect an entire broadband network!  

 I guess my knowledge should help others!

**Comment by SecurityPoliceWill** [comment]
@DillonN @malventano @luongk 

The Latin word was "Silencio" i.e. silence!

I know Loungk is in the UK, Go to Starbucks and get a proper IT guy's lunch tomorrow. Good luck! Study harder as I have better things to do than read your code!

Dillion Nash - I am excluding your from my investigation. There is nothing you can contribute as your skill set and involvement was limited - fly like a pigeon this time! Just learn to code better and validate what others have packaged. I have looked at your old code and new kids can do better!

Malventano: you are not him: https://twitter.com/malventano?lang=en I like you as you wasted 2-4 days re a criminal matter. You are a key player in this $60M theft/tax evasion matter. Fiery but innocent. Go play golf - is your phone buzzing right now? I never want to see or hear your name again.

All 3 shooo and merry Christmas!

**Comment by malventano** [comment]
Actually, @SecurityPoliceWill , you were not banned by NiceHash - you were banned by the GitHub admins after being reported for threatening its users. I see you're still at it. Your actions constitute harassment. I recommend you move along.

**Comment by SecurityPoliceWill** [comment]
I was going yo write something nice.... go on click the report button - you fail to realize this is a criminal investigation and you too are in the UK! Click report... do I care. You are your team/cell shall be prosecuted with supplying software that had trojans and viruses and you profited from such. 

In my mercy I granted you a temporary pardon! You should have shut up - Silencio.

OK - you are a criminal on the run complicit in the theft oi $60 and EU tax evasion of $12 million last month.... run rabbit!

**Comment by luongk** [comment]
@SecurityPoliceWill I'm in Australia - it's not a secret.  Let's not dox the users of this repo though, eh?  Additionally I haven't contributed to this project other than asking/answering questions here, so you're criticising the wrong person (in fact you're criticising the wrong people full stop, but that's another issue altogether).

**Comment by SecurityPoliceWill** [comment]
Life gets hard when there is a $60+ million issue re stolen money!

LoungK - your IPs are coming as UK based - are you here on holiday?

**Comment by SecurityPoliceWill** [comment]
Talk to your pal Mal... and you also should read full text. I do believe you to be innocent... but, this near miss and quick attitude makes me think was I too generous?

**Comment by luongk** [comment]
I'm very much in Sydney, not using a VPN. You're not a particularly good internet detective eh?

**Comment by Braintelligence** [comment]
My mailbox is full of his weird conspiracy theories that do not add up at all, if you're computer literate...
