### ISSUE TITLE
Alternative sma options when issues ensue[enhancement request]

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#731]
I'm hopeing with future revisions that if something happens that stops me from connecting to nicehash that it could revert to another mining site of my choosing till the main site comes up. 
 I had to setup Claymore 10.2 outside hashminer and that was the highlight of my day [other than current known issues aside].

The app is a nice tool to have and I'd like not to loose it.

Thanks

**Comment by DillonN** [comment]
There will likely be support to run off cached profitability data in the future
