### ISSUE TITLE
Nicehash back up but the legacy miner is stuck on SMA

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#736]
Is there a piece of code change that needs to occur to connect to the "new" nicehash service?

The service is back up, however when launching a fresh version of the latest miner it hangs at loading SMA information.

![image](https://user-images.githubusercontent.com/19168174/34236154-106c683c-e5c4-11e7-8ecc-fc2a005c1dbf.png)

**Comment by Frageron** [comment]
I have same issue

**Comment by billmcilhargey** [comment]
Awww

"- Miners, please be patient, buyers are setting orders"

https://www.facebook.com/NiceHash/

**Comment by adem4ik** [comment]
is it still the issue?

**Comment by borzaka** [comment]
From the official NiceHash Twitter [post](https://twitter.com/NiceHashMining/status/943798929946238976):

- [flush](https://technet.microsoft.com/en-us/library/cc816827(v=ws.10).aspx) your DNS cache: `ipconfig /flushdns` (Run as administrator)
- > Also, if you can't complete the benchmark, try reinstalling the software.

**Comment by billmcilhargey** [comment]
this has been resolved
