### ISSUE TITLE
AMD RX 580 8GB  is not detected. 

### ISSUE THREAD

**Issue by CasKade** [nicehash/NiceHashMiner#737]
So before NiceHash went down, I was able to mine with this exact same card, but after release today, it only shows my CPU in the NHML, not my graphics card. I tried disabling and re-enabling my gpu, updated my drivers to latest, uninstalled and reinstalled my drivers, nothing works. Only my CPU is shown on the devices.

**Comment by Alohacosmos** [comment]
Yep im getting the exact same problem

**Comment by uapolitik** [comment]
I have the same problem, please help

**Comment by Alohacosmos** [comment]
[debug_all_out_AMD.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1577669/debug_all_out_AMD.txt)

**Comment by uapolitik** [comment]
still not working

**Comment by owyn999** [comment]
I have a feeling this is due to the update from Crimson ReLive to AdRenalin

**Comment by Alohacosmos** [comment]
I tried the older versions and nothing

**Comment by Nicheuji** [comment]
https://twitter.com/NiceHashMining/status/943653165785808896

**Comment by tamsysmm** [comment]
Same here,

RX580 not detected, RX560 (several models) works OK.

**Comment by ghcoin** [comment]
Same here. Only CPU detected, and no GPU

**Comment by thel3lue** [comment]
My Rm550 also not detected vega 64 is fine

**Comment by kimpurcell** [comment]
Same issue here. 👎  AMD RX 580s, 480s don't show up. Only NVidia GPUs show up.

**Comment by AndrewB5za** [comment]
+1 RX580 Not detecting.
[AMD_Detection_LOG.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1579067/AMD_Detection_LOG.txt)

**Comment by kingcatdaan** [comment]
+1 RX480 Not Detecting.

**Comment by GrimHedgehog** [comment]
Yup only my NVIDIA is showing up. I have four 460's which are not.

**Comment by kynder** [comment]
my boards rx480 strix does not detect

**Comment by poltaratskiy** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1579118/log.txt)
I have the same problem

**Comment by gomesthiago** [comment]
Anyone manage to make it work? My RX 570 has the same problem, I'm using the newest overdrive drivers, people without them have the same problem?

**Comment by AndrewB5za** [comment]
seems most AMD cards are having issues not driver related from what I can see since I have another Rig running same drivers Just AMD R9280X and it works fine,  I assume its something to do with Nicehash server side not sending the info back to Nice hash client

**Comment by owyn999** [comment]
Got it, Roll back your driver to the 11/4/17 driver, there is something going on with the driver recognition of the December driver, after rolling back I am up to the benchmarking point

**Comment by Alohacosmos** [comment]
is that the crimson driver

**Comment by owyn999** [comment]
Yes the November release I used this site to grab it http://www.guru3d.com/files-categories/videocards-ati-catalyst-vista-win-7.html

**Comment by Alohacosmos** [comment]
can confirm this driver works. cheers

**Comment by owyn999** [comment]
Tips at the jar ;)

**Comment by kingcatdaan** [comment]
For actual driver version it's 17.11.1 and the previous versions are available from the official amd site https://support.amd.com/en-us/download/desktop/previous?os=Windows%2010%20-%2064 (this is for the rx series driver but you can change the url to match your specs)

**Comment by ghost** [comment]
rx560 2GPU don't work on CryptoNight! WHY??

**Comment by wizdk87** [comment]
my RX 580 8gb pulse wont show to :/

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
