### ISSUE TITLE
Timed Out or failed to connect

### ISSUE THREAD

**Issue by elias5454** [nicehash/NiceHashMiner#738]
I added acceptions to windows defender (and ended up disabling it and windows firewall) for both NiceHashMiner 2 which gets stuck at starting excavator server and the Legacy cannot connect to anything.
http://prntscr.com/hqc6gd
Running windows 10, 1gb ethernet and the internet works fine for everything else, running GTX 1080 with the highest Nvidia Driver. With the most updated version of windows.

**Comment by Nicheuji** [comment]
Chill, dude. The API probably changed and DillionN needs to update the miners, or NiceHash is still making changes on their end. Check out their twitter

**Comment by elias5454** [comment]
Thanks, Sorry I am new to Mining.

**Comment by rickrs** [comment]
same for me, 4 machines, several video cards none works..
timeout and connection lost, even in benchmark.

**Comment by Nicheuji** [comment]
https://twitter.com/NiceHashMining/status/943653165785808896

**Comment by borzaka** [comment]
From the official NiceHash Twitter [post](https://twitter.com/NiceHashMining/status/943798929946238976):

- [flush](https://technet.microsoft.com/en-us/library/cc816827(v=ws.10).aspx) your DNS cache: `ipconfig /flushdns` (Run as administrator)
- > Also, if you can't complete the benchmark, try reinstalling the software.

**Comment by williamjeccles** [comment]
Try changing and using Google's dns 8.8.8.8 and 8.8.4.4 for your dns servers. That resolved connection issues for me.

**Comment by S74nk0** [comment]
duplicate https://github.com/nicehash/NiceHashMinerLegacy/issues/744
