### ISSUE TITLE
Xmrig Connection timed out

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#739]
Xmrig Connection timed out

**Comment by ghost** [comment]
also connection refused

**Comment by Nicheuji** [comment]
https://twitter.com/NiceHashMining/status/943653165785808896

**Comment by adem4ik** [comment]
Check it now. And please close the issue if everything is fine.

**Comment by borzaka** [comment]
From the official NiceHash Twitter [post](https://twitter.com/NiceHashMining/status/943798929946238976):

- [flush](https://technet.microsoft.com/en-us/library/cc816827(v=ws.10).aspx) your DNS cache: `ipconfig /flushdns` (Run as administrator)
- > Also, if you can't complete the benchmark, try reinstalling the software.

**Comment by S74nk0** [comment]
relates to https://github.com/nicehash/NiceHashMinerLegacy/issues/744
