### ISSUE TITLE
R9 380 Unable to be Detected

### ISSUE THREAD

**Issue by derek-s-wang** [nicehash/NiceHashMiner#740]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1577758/log.txt)
I have tried restarting, reinstalling the GPU drivers, reinstalling different versions of NHML and nothing has worked.

**Comment by Nicheuji** [comment]
https://twitter.com/NiceHashMining/status/943653165785808896

**Comment by VoodooFX** [comment]
Had the same problem myself. What I ended up doing is reverting back to AMD driver 17.10.3 - I suspect any Crimson-ReLive driver will work - and my card was back on the list.
While NH was down AMD released a new generation of drivers called Adrenalin Edition, which seem to be causing problems in MinerLegacy detection routines.
But if you're still on Crimson drivers and you're still not seeing your card, then someone else will have to jump in and help you.

**Comment by exenza** [comment]
yeah thing is wiht the new drivers in compute mode there is a significant performance gain... I won't revert back to Nicehash and keep mining on pools directly until they fix it.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
