### ISSUE TITLE
Equihash BMiner

### ISSUE THREAD

**Issue by pojik7** [nicehash/NiceHashMiner#742]
Please,. add new equihashminer in your project
https://bitcointalk.org/index.php?topic=2519271.0
This is fastest/
On 1070 - 505-510 sol/s with overclock

**Comment by Krassikn** [comment]
Yep. Please add this one.

**Comment by t3t3** [comment]
but **dstm's** first plz ;)

i tested latests versions of ewbf, dstm and bminer for 24 hrs each (using 8x 1070) on flypool, and, despite showing a higher hashrate, at the end of the day dstm returned more shares and a higher average hashrate _in the pool stats_ than bminer; around 3%. guess it will be the same on nicehash.

also bminer (still) puts substantially more load on the cpu, which lowers your hashes/watt efficiency or affects additional cryptonight cpu mining. and last but not least it's notably slower when ramping up, which may also lower profitability a bit, esp. when using nicehash (switching...)

**Comment by pojik7** [comment]
In 3.0 versio bminer not load cpu
Even in version 2.1 option polling=false  redice cpu load.
version 3.0. imho, faster than all

**Comment by pojik7** [comment]
By the way, i added dstm's  miner manualy, by modofy source project. Add class and etc. 
Profit )

**Comment by Krassikn** [comment]
How did you add dstm miner, please explain ?

**Comment by pojik7** [comment]
I download this project. Open this in Visual Studio 2017. I take as base realization of EWBF and insert in project code (on C# language) dstm miner realisation. Miner come in sight into list of miners. Benchmark dont work, i am not realize them. But if set manualy hashrate - miner runing when profit is coming, showing hasrate in grid and pofit at bottom of window. All works.

**Comment by Krassikn** [comment]
Can you upload the final working exe project ?

**Comment by pojik7** [comment]
On mail maby?

**Comment by Krassikn** [comment]
Upload it as repository, or uploaded somewhere and put the link here ?

**Comment by pojik7** [comment]
https://drive.google.com/open?id=1w0uQs_rhmaeAcKDKcs8Kwi2xMksbgmTe
Pass 1111
Miner need to put in a folder bin_3rdparty\zminer\zm.exe

**Comment by pojik7** [comment]
I make fork from main project.
You mai see what changes i do
https://github.com/pojik7/NiceHashMinerLegacy/commits/master

**Comment by Krassikn** [comment]
Thanks. Great. Will give it a try.

**Comment by MaKCuMyC** [comment]
For me, with my little GTX 9xx farm, Bminer with `-nofee` performs better than DSTM (810 DSTM; 830 Bminer).
Bminer must be included in NHML.

**Comment by leovarmak** [comment]
@MaKCuMyC What actually changes when you opt for no fee ?? What was your hash rate that was being shown before you enabled that flag and after you have enabled that option ?

**Comment by MaKCuMyC** [comment]
@leovarmak displayed hashrate isn't changing with `-nofee` option, but Bminer author answered at bitcointalk thread that some optimizations will disabled.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
