### ISSUE TITLE
Working (~1.5$/day), but NO balance & NO accepted jobs!

### ISSUE THREAD

**Issue by AlexVirlan** [nicehash/NiceHashMiner#744]
I just restarted today to mine with NH after it went back online. I configured everything, and I started to mine on one of my PCs just to see how it works now.

The rate is about 1.5$/day, and has been working for at least an hour but **there is no balance added**, and _in the mining windows there are jobs coming_, but **not a single one is accepted**.
I tested both NHM Legacy (v.1.8.2.0-Pre2) and NHM 2 (v.2.0.1.5-Beta), same problem...

Very strange because I was mining on a slower CPU (before the NH hack) and I had some jobs accepted.

Any ideas why?

**Comment by adem4ik** [comment]
Did you generate a new NiceHash wallet address to mine?

**Comment by AlexVirlan** [comment]
@adem4ik Of course. New password, new 2FA, new wallet address.

**Comment by AlexVirlan** [comment]
[2017-12-21 11:31:59] : SOCKET ERROR - [cryptonight.eu.nicehash.com:3355] RECEIVE error: socket closed
[2017-12-21 11:31:59] : All pools are dead. Idling...

???

**Comment by borzaka** [comment]
From the official NiceHash Twitter [post](https://twitter.com/NiceHashMining/status/943798929946238976):

- [flush](https://technet.microsoft.com/en-us/library/cc816827(v=ws.10).aspx) your DNS cache: `ipconfig /flushdns` (Run as administrator)
