### ISSUE TITLE
Tray tooltip 'Double-click to restore..' isn't translated

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#745]
**Preconditions:** Option 'Minimize To Tray' is enabled, any language apart from English is used.

1) Start NHML
2) Click on Minimize button
3) Move the mouse arrow to the NHML tray icon

**Result:** 'Double-click to restore..' is shown
![image](https://user-images.githubusercontent.com/4707112/34248423-6fbbfea2-e64f-11e7-89d0-5760f735fa34.png)
**Expected result:** Translated 'Double-click to restore..' is shown

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMinerLegacy/commit/2d4b5cd406d8b046eec1df17109643f320304b6f) fixes this bug. Now it will be [translatable](https://github.com/nicehash/NiceHashMinerLegacy/commit/2d4b5cd406d8b046eec1df17109643f320304b6f#diff-89fc09409018b78276f2001589c7ad2eR1003). We will close this issue on next release

**Comment by S74nk0** [comment]
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)
