### ISSUE TITLE
NH 1.8.20 All GPUs dedected but only one or two mining at a time

### ISSUE THREAD

**Issue by netspherecyborg** [nicehash/NiceHashMiner#747]
Hi,
As the title says. Nicehash sees all three of my Saphire 570 cards but only mines with two or one. Win 10 , NH v1.8.20

My log file:
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1579488/log.txt)

**Comment by netspherecyborg** [comment]
changed to older version and now it works.

**Comment by endlessterror** [comment]
<EDIT: Deleted>

**Comment by netspherecyborg** [comment]
@endlessterror sorry bro ,im not so familiar with github... I was trying to find now for half an hour the so called bug #1373 ,but not even the hashtag or google found it. Where is it?
Thanks!

**Comment by netspherecyborg** [comment]
If you mean the "rx480 cant be detected on my nicehash 1.8.2.0 and 1.8.1.5" from another build (I assume its another build) ,then nope. It detected it but it didnt start mining with it (as stated above) ,also 1.8.1.5 works.

**Comment by endlessterror** [comment]
My bad mate, I actually posted to the wrong bug report :)

I'll delete/edit my previous comment.

**Comment by netspherecyborg** [comment]
No worry :) 
Its just an assumption ,I have absolutely no clue ,but it might happened because benchmark couldn't finish properly? I have seen a twitter post from NH about benchmarking problems. Unfortunately im to lazy to look for a confirmation in the log file as it has over 5000rows  , I have absolutely no clue where to start (probably somebody who knows the log file better than me scrolls two and hes at the correct place) ,also it is working with 1.8.15.

**Comment by netspherecyborg** [comment]
I just built a new rig with 5 gpus ,and benchmark there is pico bello (v1.8.15)....if i remember correctly while I was telling my problem the benchmark stopped at around 37/48 (this number is just a guess number).

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
