### ISSUE TITLE
R9 380 gpu not detected after NH hack

### ISSUE THREAD

**Issue by raintowers** [nicehash/NiceHashMiner#749]
Since NH started back up after the hack, the GPU is not being detected. I've tried v1.8.2.1 nicehash legacy miner. Every thing was working before the hack.

**Comment by AndrewB5za** [comment]
#
Duplicate of #740

**Comment by AlienUrineSampl** [comment]
Revert to older drivers, Pre-Adrenaline update.

**Comment by raintowers** [comment]
OK that worked thanks
