### ISSUE TITLE
New CCMiner build- faster than Nanashi

### ISSUE THREAD

**Issue by p1r473** [nicehash/NiceHashMiner#755]
I discovered a new build that increased my hashes a lot.

My testing: benchmark on precise mode with 1080TI on LYRA2V2

CCMiner 2.2.3: 66.31 MH/s

Nanashi-Meiyo-Meijin: 73.15 MH/S

Palginmod x64: 74.94 MH/S

Palginmod x86: 76.93 MH/S

note: use x86 version even on an x64 system, its faster

https://github.com/palginpav/ccminer/releases/

Please include it!

Heres a list of which miners to use for which algos.
![image](https://i.imgur.com/SNXByGC.png)

**Comment by CreamyG31337** [comment]
The author deleted it for some reason, as far as I can tell.
