### ISSUE TITLE
Hashrate

### ISSUE THREAD

**Issue by darkstalker85** [nicehash/NiceHashMiner#756]
The hashrate is not stable - dagger hashimoto shows 20-22M Hash, but when i start the dual (etherium+lybri) the hash is 22-29.7 M Hash! Why?
Win7 x64 ultimata, Nhml latest, crimson relive 16.4, Intell x79 pro mb, intell xeon e-5 2660 v2, MSI RX580 8GB (bios flashed for etherium). The blockchain drivers is not working on win7 (just shut down the miner when connect to the pool) Oh, yeah... I cant accept the L2FA(some error, like a" error enabling l2fa"

**Comment by Jakobhoss** [comment]
Simply make a .bat file with exact this text
Only change the information about the NiceHash folder and put it into your autostart folder!

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_SINGLE_ALLOC_PERCENT 100
setx GPU_MAX_ALLOC_PERCENT 100
<Your NH LEGACY FOLDER\bin_3rdparty\claymore_dual\EthDcrMiner64.exe> -epool stratum+tcp://daggerhashimoto.usa.nicehash.com:3353 -ewal 3DYdFDjmuxq1GTPQFm53Q93gGzY3zFkhRJ.NHidot -epsw x -esm 3 -allpools 1 -estale 1 -dpool stratum+tcp://lbry.usa.nicehash.com:3356 -dwal 3DYdFDjmuxq1GTPQFm53Q93gGzY3zFkhRJ.NHidiot -dpsw x -wd 1 -r 0 -etha 0 -asm 1 -estale 1 -dcri 50 -dcoin lbry

Works 100% you´ll have to wait for some hours till you see first results but it´s worth it!

**Comment by darkstalker85** [comment]
I will...  But i will change info about the ewal and dwal...)
How about a raw intensity(if it present here)?

**Comment by Jakobhoss** [comment]
don´t play with it... let it run auto. Only if you have slow/old cards it matters. Good Luck!

**Comment by SaintPistachio** [comment]
Do not forgot to change the wallet address otherwise you will just mine for someone else. ;)

**Comment by darkstalker85** [comment]
Hashrate still jumps((( 20-29MHash/86-119Mhash ETH/LBR(((

**Comment by Jakobhoss** [comment]
try different -dcri values. 50 means you mine 50% ETH 50% Lbry. For me I have best results with dcri 30... coul be a PSU problem, too. Are you sure your card gets enough power to dual-mine? Looks like they get not enough power and the rate drops.

**Comment by darkstalker85** [comment]
My card is MSI RX580 GAMING X 8GB, that card is have enough power for dual (i think)...

**Comment by darkstalker85** [comment]
Its some isues with DAG files! Some give me 20Mh, some 22, some 29...
And yeah, for my card best is -dcri 80... I lost 1 Mhash from Eterium, but gives 165 Mhash for Libry...
