### ISSUE TITLE
Add efficiency to algorithm?

### ISSUE THREAD

**Issue by s2n-Gribbly** [nicehash/NiceHashMiner#757]
Has anyone considered allowing the user to manually add the power consumption and cost of energy per algorithm to truly work out which is more beneficial?

I often switch to Dagger+Lbry over CryptoNight, when the earn rate is nearly identical. CryptoNight consumes approximately half of the energy when running, and so is still the more profitable coin at this point.

Not sure if this is the right place to make suggestions?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

This feature is already added
