### ISSUE TITLE
EWBF Miner does not work concurrently with Claymore

### ISSUE THREAD

**Issue by ALEXEY-SOFT** [nicehash/NiceHashMiner#76]
On the 1050 map, the EBWF is launched, and the second card 1060 in the dual is launched by Claymore. As a result, Claymore does not understand that 1050 does not participate in dualmining.
![2017-07-27_080311](https://user-images.githubusercontent.com/8391898/28654362-b1b63fda-72a4-11e7-9afe-9d8354bb619d.png)

**Comment by DillonN** [comment]
Can you scroll up in the ClaymoreDual window and see what GPU it starts mining with? It should show either 1050 or 1060

Also please post your log file from the logs folder

**Comment by ALEXEY-SOFT** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1178827/log.txt)
![2017-07-27_083449](https://user-images.githubusercontent.com/8391898/28654643-05fa866c-72a7-11e7-9ed8-ef5f4d684059.png)

**Comment by ALEXEY-SOFT** [comment]
Such a problem is only if one of the cards starts mining by the EBWF miner. If EBWF is excluded, removing it in the settings, then everything works fine.

**Comment by DillonN** [comment]
It looks like ClaymoreDual is correctly using only the 1060. It's not able to generate the DAG though (probably because EWBF is taking too much memory already). You can try increasing your pagefile size

**Comment by ALEXEY-SOFT** [comment]
I think for a farm in which only 2 video cards such a paging file volume is more than sufficient?
![2017-07-27_085618](https://user-images.githubusercontent.com/8391898/28654990-948d5e02-72a9-11e7-8ff7-b7ebbd380d3e.png)

**Comment by ALEXEY-SOFT** [comment]
In general, it's not the size of the swap file - obviously!

**Comment by DillonN** [comment]
Yes that is a lot of virtual memory, assuming not much else is hogging RAM on the system. Does the problem exist when you run ClaymoreDual without a second algorithm? And does it still happen if you manually open a CD miner while EWBF is running?

**Comment by ALEXEY-SOFT** [comment]
The problem only occurs when EWBF is started on 1050 2GB, and any version of the Claymore Miner is started at 1060. Other miners, for example Ethminer (1060) + EWBF (1050) works without problems.

**Comment by ALEXEY-SOFT** [comment]
[Bug EWBF miner
](https://youtu.be/w59ZEq0vO-I)
