### ISSUE TITLE
sgminer crypronight no stats with more than 10 gpus

### ISSUE THREAD

**Issue by treanski** [nicehash/NiceHashMiner#761]
i had rig with 10 rx580 8gb everything was ok, after adding an 11 rx 580 sgminer shows no stats, see picture

https://ip.bitcointalk.org/?u=https%3A%2F%2Fimage.ibb.co%2Fnx3LLR%2F11.jpg&t=584&c=fYoUWoHiDwOnHQ

**Comment by jimmyhackers** [comment]
split your rig into two

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
