### ISSUE TITLE
Amd card not pickup by nicehash miner

### ISSUE THREAD

**Issue by GreenV154071** [nicehash/NiceHashMiner#762]
I have a ryzen i7 cpu working fine
I have a GTX 1082 working fine
I have a AMD rx 580 not picked up by Nicehash Miner

The Amd drivers is fine as it is working on Winminer. But i would like to mine with Nicehasch only

i am using radeon RX 580 mining edition with latest drivers and the miner is not detecting my gpu"s there was no problem before the hack
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1584002/log.1.txt)

**Comment by odendarp** [comment]
Well as the versions goes first my GPu not picking up now my CPu dont. Nicehash don't want us to mine any more. Please build something for us who have gpu laying around want use it. My Radeon HD7970 still fine card, mine better that my gtx960 but no missing not picking up and drivers upgrade and downgrade  What now?

**Comment by ghost** [comment]
if your rx 580 won't pick up downgrade to radeon drivers, Adrenalin drivers don't work rn

**Comment by phant** [comment]
Yes, adrenalin 17.12.1 not supported.
my gpu not recognized by NHML 1.8.15

**Comment by odendarp** [comment]
thanks sorted

regards
Rudie

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by abhspire** [comment]
Will the software be updated to support adrenalin drivers?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
