### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by alextrack2013** [nicehash/NiceHashMiner#763]
- The 'Bitcoin Address' textbox length is unlimited. (Should be 34 as maximum)
![issue1](https://user-images.githubusercontent.com/34791591/34319408-205cb2fe-e7e2-11e7-8ccb-18f7e015f728.PNG)
- DEMO mode label is too big. (Reduce size)
![issue2](https://user-images.githubusercontent.com/34791591/34319451-359b979c-e7e3-11e7-8089-894b22c71a3a.PNG)
- Set 'ShowInTaskbar' property of FormLoading to false. (User can close it)
- Fix 'Worker name' textbox length (maybe)

**Comment by S74nk0** [comment]
@alextrack2013 Good point regarding BTC addr textbox ([commit](https://github.com/nicehash/NiceHashMinerLegacy/commit/4981b7bf12480f12b66d3f19d63b36aa862221e3)).

Other issues should be resolved with the latest current version.

We will be working on a complete GUI re-design. We will be resolving GUI issues there.
