### ISSUE TITLE
problem connecting to NH

### ISSUE THREAD

**Issue by Spearhawk** [nicehash/NiceHashMiner#764]
I have in the last 2 days tried to restart to mine for NH, but for some reason it is not accepting my graphics card suddenly. 
I am using a RX 480 AMD card,
I have mined before and it worked beautifully but after the reopening the GPU parts of the mining simply says 0.00000 and does switch software every 2-3 minutes but it does not generate any revenue as far as the GPU part goes.

It does generate for the CPU but not for the GPU

I am using the Legacy 1.8.1.5 
and I am using 17.10.1 graphics drivers

Here are some screens at what occurs when I try

https://imgur.com/a/jrO7z

also, when I try to benchmark it, it gets stuck on 9/16 and does not go past that.

Please help.

**Comment by ghost** [comment]
this happened to me before, using too much of your CPU? Watching a youtube video on firefox? 
that's what put my speeds to 0, have you just tried running nicehash by itself?
flushdns?

**Comment by Spearhawk** [comment]
Please... Made me laugh... Hihihi, I laugh because that was my first throughts too, but cpu is working.
and the graphics card is working nicely with awesome miner, but not with the nicehash software.

The CPU is working nicely. 
It's the GPU that's not working. 

And yeah I tried all those things, and I shut down all other programs except that. 

And done flushdns and renewed the ip etc and o tried everything, nothing works.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
