### ISSUE TITLE
Benchmarking Second GPU Causes Screen to Go Black

### ISSUE THREAD

**Issue by NR300** [nicehash/NiceHashMiner#766]
I have two Radeon r9 200 series GPU's in my computer build that I've had for a couple years, specifically two r9 290x's I believe. Anyways, I have chosen to benchmark my GPU's individually because doing them together was causing my computer to reboot. I successfully benchmarked my primary GPU with relative ease, but when I try to benchmark my secondary GPU, my screen goes black a couple seconds after I begin benchmarking. I know my computer is still on and running; it just seems that the display goes black.

**Comment by jimmyhackers** [comment]
does the screen ever return from its blackness?
you can try manually copying the benchmark results over to the "dodgey" card and run mining  to see if its ok.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
