### ISSUE TITLE
Not working for newer driver for AMD

### ISSUE THREAD

**Issue by Spearhawk** [nicehash/NiceHashMiner#769]
When is the newer version of the legacy being released that includes 
AMD 17.2 drivers?
Downgrading to 17.10 is not working nicely because for some reason
it is not connecting to the benchmarks or the mining for the GPU for me
only connect the CPU and it mines awesomely there, but the GPU part is being
connecting yet not earning any revenue. it is as if it is discarding the shares mined
by the legacy miner.

**Comment by mcninja97** [comment]
yeah same problem here, always had issues upgrading and downgrading drivers even after a clean uninstall or a ddu. hopefully they release an update soon.

**Comment by dadoremix** [comment]
use older driver like 17.11.4 or lower
no need to use always newest driver.. 
yo dont recive any boost at mining ..  thats not a game

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
