### ISSUE TITLE
how often do i get paid

### ISSUE THREAD

**Issue by nooodlez** [nicehash/NiceHashMiner#770]
So my question is do I just put in my wallet address and they pay me daily if my balance is greater than 0.01 BTC or?

**Comment by ahmedshams1973** [comment]
Learn me more

**Comment by riccardoruspoli** [comment]
Read the FAQs

https://www.nicehash.com/help/when-and-how-do-you-get-paid

**Comment by S74nk0** [comment]
Not related to nhm client
