### ISSUE TITLE
Trouble With VNC Remote dekstop

### ISSUE THREAD

**Issue by buyungsukarno** [nicehash/NiceHashMiner#771]
![vnc](https://cloud.githubusercontent.com/assets/23252906/24558777/f56ebca8-166e-11e7-81ad-f9336234a491.png)

have trouble with VNC remote desktop with warning message "We have detected a video controller thats is not working OK.
Name: VNC Miror Driver, Status Degraded"

any solution?

**Comment by semisane** [comment]
What about RDP?

**Comment by kenshirothefist** [comment]
The only solution, know to be working flawlessly for Remote control is Team Viewer.
