### ISSUE TITLE
NiceHash Miner not showing neoscrypt algorithm

### ISSUE THREAD

**Issue by dfortu** [nicehash/NiceHashMiner#774]
Hello, I have a rig with 8x rx570 gpus, currently for my setup in whattomine.com it says that the most profitable nicehash algorithm for my setup is neoscrypt, but I can't run it because it doesn't appear as a benchmark option.

**Comment by asanchez89** [comment]
Me neither in older versions I could download the 3rd party miner for that but it seems with this new version isn't a miner available for neoscrypt in nicehash, I'm using v1.8.2.0-Pre2

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
