### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by allldino** [nicehash/NiceHashMiner#777]
Hi! So I understand that you guys dont offer support for external miners, however I feel like you can help me out with this, and I greatly hope you will because I am so eager to get to use Nicehash with my new vega 56!!

So my problem is

1.Got a vega 56 
2.Downloaded cast-xmr miner 
3.Set up everything and the miner recieves "connection time out" errors 4.I tether my 4g cellphone and bam it works! 
5.I notice I am getting an ipv6 ip and i disable ipv6. 
6.I now get a ipv4 adress but it still doesnt work

Please would you help me out?

I really wanna mine with nicehash.

**Comment by williamjeccles** [comment]
Have you tested using Google's DNS service 8.8.8.8 and 8.8.4.4 for your dns servers?

NH seem to have shifted a bunch of ip addresses since the hack and I had to use google dns to resolve some connection issues myself. Let us know if this solves your issue also.

**Comment by allldino** [comment]
@williamjeccles I'm gonna try now, you speak of going to network settings and setting them manually on my pc, and not in the router? Because I think I've tried this before, was like this before the hack as well, it can connect to the 33355 port tho (if tsl and all that shit is enabled)

**Comment by williamjeccles** [comment]
Yes, I recommend setting this at a pc level not router. Let us know how you get on and close this issue if that's resolved it.

**Comment by allldino** [comment]
@williamjeccles Did not solve it,
Also tried, flushing dns
release & renew ip
call ips 3 times to see if it's on their end, they just tell me no in a stupid voice.
reinstalling network adapters (idk why but i tried it lol)
disabled firewall completely
using a vpn solves the problem but now I have to pay for that which i'd love to avoid.

**Comment by jimmyhackers** [comment]
mine another algo?

**Comment by AronD89** [comment]
Hi! Have you ever solved this issue? I have the same problem: mining starts only with the 4G cellular network. One interesting thing is that when I start mining with 4G and switch back to home Wi-Fi the mining continues for 25 minutes, and then stops with "connection time out" errors.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
