### ISSUE TITLE
Rig stats have disappeared!

### ISSUE THREAD

**Issue by williamjeccles** [nicehash/NiceHashMiner#778]
Before the "great NH hack" I was able to view detailed rig stats after logging into NH and clicking Full Statistics.

I used to see underneath "Detailed Worker Stats" a section labeled Rigs with GPU load, fan RPM and temperature.

Here is the documentation https://github.com/nicehash/NiceHashMinerLegacy/wiki/Rig-Stats-Monitoring

I have not seen this section since NH came back online. Just wondering if its just me or if there are plans to bring it back? It was very useful and one of the only reasons I used NH as my wallet.

**Comment by borzaka** [comment]
It's still there: [https://www.nicehash.com/miner/](https://www.nicehash.com/miner/)`[your-NICEHASH-BTC-address]`
Or after login, you can see all your workers here: [https://www.nicehash.com/workers](https://www.nicehash.com/workers)

**Comment by williamjeccles** [comment]
@borzaka can you confirm you see GPU Temp, Load % and Fan RPM against your workers? That is what i'm saying is missing is https://ibb.co/fpZmmb , I'm aware of and am able to view just the basic workers but to confirm again i'm missing this https://ibb.co/fpZmmb here is a screenshot from a few months ago.

**Comment by pducharme** [comment]
I see the same issue.  Maybe NH changed the Mining stats page to remove it (?). Maybe @DillonN knows?

**Comment by jimmyhackers** [comment]
i asked about several "recalled services" that nicehash used to offer......

looks like their cutting down on server trafffic and costs by cutting back "extra" services.

**Comment by kaos-1** [comment]
Its back now since today.

**Comment by williamjeccles** [comment]
Yes, I now see it also @kaos-1 thanks for the heads up!
I'll close this one down.
