### ISSUE TITLE
Turning off cards 1060

### ISSUE THREAD

**Issue by ALEXEY-SOFT** [nicehash/NiceHashMiner#78]
Farm of 5 GTX 1060 cards. In the process of mining by claymore miner in dual mode - one of the video cards disappears from the system.

**Comment by miesdr** [comment]
i'm also having the same problem and most of the time it will cause my pc to hung state. revert back to v1.8.0.1. no more issue.

**Comment by miesdr** [comment]
i'm also having the same problem and most of the time it will cause my pc to hung state. revert back to v1.8.0.1. no more issue.
