### ISSUE TITLE
NHML cannot detect Radeon R7 360 anymore

### ISSUE THREAD

**Issue by UAVXP** [nicehash/NiceHashMiner#780]
After NiceHash pool restart NHML can't detect a GPU that I've used previously

Video: Sapphire NITRO Radeon R7 360 2GB D5
Drivers are latest 17.12.2

Here's the [log file](https://github.com/nicehash/NiceHashMinerLegacy/files/1593118/log.txt)

PS: What's funny and strange at the same moment - GPU-Z can't detect OpenCL device too:
![image](https://user-images.githubusercontent.com/3075683/34437707-53b6b976-eca9-11e7-9209-e9feebab5c13.png)
![image](https://user-images.githubusercontent.com/3075683/34437739-9f5f4d3e-eca9-11e7-948a-c2763be366c7.png)

But GPU Caps Viewer can:
![image](https://user-images.githubusercontent.com/3075683/34437781-dd1d254c-eca9-11e7-84c3-ba88301e8b89.png)
![image](https://user-images.githubusercontent.com/3075683/34437695-2a144d5e-eca9-11e7-991f-702c02dae068.png)

But GPU Caps Viewer's 3D Demos shows this error:
![image](https://user-images.githubusercontent.com/3075683/34437807-1fbff582-ecaa-11e7-921f-e15009953948.png)

**Comment by slyons89** [comment]
I'm having the same issue with NH 1.8.1.5 with my R7 360. It was detected correctly under AMD driver version 17.7, but after upgrading to 17.12.2, the card is no longer detected by Nicehash.

**Comment by JonathanHouten** [comment]
NHML cant detect any AMD card on driver 17.12.2!
my 470 also infulenced by this 
but it can still be detected by "Claymore's Dual Ethereum+Decred_Siacoin_Lbry_Pascal AMD+NVIDIA GPU Miner v10.0 "
FIX THIS !

**Comment by slyons89** [comment]
For the record, my Vega 64 LC is working fine with the latest NH prerelease just fine on 17.12.2. But no luck with the R7 360 in my other rig.

**Comment by UAVXP** [comment]
Looks like in the newest version of the program (1.8.1.8 with the same AMD driver as I mentioned in the first post) this problem has been fixed! Good work guys!
![image](https://user-images.githubusercontent.com/3075683/35806040-c7082dd8-0a86-11e8-9711-3b590eefa1b8.png)
