### ISSUE TITLE
incorrect benchmarkings

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#781]
i raised this before but.......no luck.
my gtx7704gb will benchmark on daggerhashimoto and several others at nearly twice its regular hashing rate.

annoyingly these algos will start to run at the higher benchmarked hash rate but all eventually end up dropping to just below half this.

this is turning what should be roughly 1gbp a day into 40p a day. 

anyone got any ideas?

**Comment by gomesthiago** [comment]
go to configure and set the benchmark value manually to the right ones

**Comment by jimmyhackers** [comment]
i know thats an option of sorts.

 but it still leaves my card mining at around 6mh/s instead of 14mh/s.
also if i switch between daggerhashimoto to another algo or switch back after its dropped to its lower rate manualy the higher hashrate will return on the new algo only to drop again after a while.

does anyone know whats actually causing this though?

**Comment by Simaex** [comment]
I have similar issue with GTX970 card. During benchmarking low EPOCH # is used and I have high hash rate around 23 Mh, but when connecting to pool EPOCH 155 or 160 is used and hashrate drops to 7-8 Mh. Did not find any solution other then manually set low hashrate in benchmarks. We need some watchdog to check for difference of benchmarked and actual hashrate.

**Comment by github12101** [comment]
Nicehash should "benchmark as you go". No artificial benchmarking mode, but real mining. For example you press start and leave it, results are being discovered as we mine, profitability is being established as well. Max 10 minutes per algo and then to the next one.

**Comment by Simaex** [comment]
@pioruns No way it solves problem for daggerhashimoto benchmarking. BTW now benchmarking is real mining but for shorter period then you suggested.

**Comment by jimmyhackers** [comment]
its nice to know its not just me noticing this bug/issue, thanks simaex.

i dont suppose you tried snickers suggestion of going to windows 8.1?
im currently on windows 7 :s

**Comment by Simaex** [comment]
@jimmyhackers it may be interesting to try 10 CU, I am running 8.1
I found some references that changing CUDA memory managment may be helpful but I really did not understand how it must be done due to my lack of experience with CUDA

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
