### ISSUE TITLE
Nicehash detected and unable to support my CPU processor

### ISSUE THREAD

**Issue by Leeshunda100** [nicehash/NiceHashMiner#782]
Dear Pro miners,

I checked the "start mine" and it was processing but however it stops my mining application with the following error message (See attached photo)

Warnings!
Nicehash Miner has detected the following unresolved issues.

Unsupported devices -
We have detected the following unsupported device
Intel(R) Core(TM) 2 Duo CPU E7500 @ 2.93GHz

Please could someone assist to help solve the problem for me.  Thanks in advance and appreciate your help.

![nicehash error](https://user-images.githubusercontent.com/34942499/34440318-5c11a22a-ecef-11e7-9de4-8c90e447590e.jpg)

**Comment by williamjeccles** [comment]
Hello, 

It does appear that CPU is compliant with SSE2 as per http://cpuboss.com/cpu/Intel-Core2-Duo-E7500 but there are many variables such as OS to determine compatibility with Nicehash.

If you are using Windows 7 or newer you should be able to mine using the legacy miner here, if on XP or Vist you'll need to upgrade your OS first: https://github.com/nicehash/NiceHashMinerLegacy/releases

Which GPU(s) do you have installed or are you only trying to mine using this CPU?

**Comment by Leeshunda100** [comment]
Hi William,

Happy New Year to you!

I'm using an old desktop (Intel Core 2 Duo E7500) installed with Windows 10 OS and I am using a MSI GTX 1070 TI graphic card.

I just installed the nicehash miner and clicked the next buttons all the way till it start loading.  While loading close to the end, this message pop out.  After that I tried pressing the "play" button right beside the miner logo but nothing happens.

Please could you advise me on how should I do.  Thank you.

**Comment by jimmyhackers** [comment]
my older rig downstairs does the same. has an e6600 cpu with a gtx 770 and a gtx 660 in it.

new nicehash wont work properly and give me the same error message as you.....nicehashlegacy works on it seemlessly though.

note: your cpu is two pants to mine on with any nicehash program.......but minergate should still be able to use it if you want the extra 1pence or so per day it will produce

**Comment by Mystere** [comment]
First, this is the nicehash legacy support forum.  The image you posted was for NHM v2 (this is not NiceHashLegacy).  So you're in the wrong forum.

Second, if you click the link it brings you to the wiki, which details that AES / AES-NI instruction sets are required, and your CPU doesn't support them.  According to the page, there are no plans to support CPU's that do not support these.

**Comment by Leeshunda100** [comment]
Dear jimmyhackers and Mystere,

Thanks for the advice.  I'm switching to mining pool hub with awesome miner now.  I'll figure a way to come back to nicehash.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
