### ISSUE TITLE
Issue with Large numbers of GPU's and Nicehash / ccminer

### ISSUE THREAD

**Issue by Lipora** [nicehash/NiceHashMiner#783]
Please advise what additional information you require from me to resolve this.  It appears when Nicehash is working with more than 10 GPU's either it or ccminer is having troubles with recognizing the two digit GPU numbers. 

eg. when I try to run mining on GPU 11 in nicehash (bios shows it as GPU 10) the actual GPU that gets starting on mining is GPU 0.  Nicehash shows it as GPU 11 running but in ccminer it is showing GPU0 and I can confirm with hwinfo / nvidia inspector that it is infact GPU0 that is running. Temps and voltage increase on GPU0 and GPU 10 stays cold. 

When swapping over to another miner like excavator the proper GPU 10 is recognized and starts mining.

It would look to me that either nicehash isn't providing the correct format to run ccminer. or ccminer itself cannot work with 2 digit GPU numbering.

**Comment by jimmyhackers** [comment]
you could always split your rig into two?

**Comment by evlo** [comment]
I have similar issue - 11gpus works, but gpu12 fails (it is gpu 11 indexed from 0), even most of the benchmark fails on gpu 11 and I get this error when i try to mine: https://imgur.com/L4VpsFd Non existant gpu device 11
Until now I was using ethminer, where everything works.

BTW on nicehash 2 i don't get any error, it works like this: https://www.youtube.com/watch?v=I75ZHDDqGAc - it just keeps restart

Here is best benchmark report i could get for card 12 in legacy:
https://imgur.com/xQCbZ2d (claymore single benchmark would probably work if i used precise option)
  
 Seems to be issue with **ccminer**

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
