### ISSUE TITLE
the miners update does not go to 100 % 

### ISSUE THREAD

**Issue by dah2013** [nicehash/NiceHashMiner#783]
when i enter to nicehashminer the update of miner does not go to 100 % , why ?

**Comment by S74nk0** [comment]
@dah2013 Are you downloading 3rd party miners as well? Most likely it is due to AV software (most miners are flagged **false positives**)

**Comment by dah2013** [comment]
@S74nk0 how i can download 3rd party miners?

**Comment by dah2013** [comment]
Thank you ,, now it's OK
