### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by felixngwh** [nicehash/NiceHashMiner#787]
Hi All

I am new to NiceHash Miner Legacy .
I have installed v1.8.2.0-Pre2 on a Windows 7 PC and mining with my CPU i7-6700K.
After I started mining for several minutes, it appeared a "Connection reset by peer" error.
Attached please find the screenshot and log file.
![nicehash_connection_error](https://user-images.githubusercontent.com/754960/34455983-20dce41c-edc6-11e7-98ac-08d8af6689b5.jpg)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1594584/log.txt)

I have tried to switch to other "Service Location", but it still have the same issue.
How can I fix it?

Thanks
Felix

**Comment by jimmyhackers** [comment]
you can try increasing the size of your virtual paging ram file?

make it double the size of your physical ram

**Comment by jimmyhackers** [comment]
also i have an i7 3770k (older than yours) and im hitting nearly 300h/s
 you not overclocking it or something?

**Comment by dadoremix** [comment]
for speed
read that
https://github.com/nicehash/NiceHashMiner/wiki/Notes-and-hints-on-CPU-mining

for conections droping.. nicehash have at start problems..  right now you have also problem?

**Comment by sirbig** [comment]
This error is happening to me as well sometimes in all locations...

**Comment by felixngwh** [comment]
Hi jimmyhackers, dadoremix, sirbig

Thanks for all your help.

I have set the virtual page file size and then re-run the benchmark.
After the benchmark completed, the NHML changed the default mining algorithms from Xmrig to Xmr-stak.
After NHML use Xmr-stak for mining, the "Connection reset by peer" error disappeared.

In order to improve the hash rate, I have tried to set LOCKED PAGES in Memory (follow the instruction in https://msdn.microsoft.com/en-gb/library/ms190730.aspx) but it failed.
After I reboot PC and windows desktop appeared few seconds, system hanged with a blue/yellow screen.
Do you all have the same issue?

Thanks
Felix

**Comment by sirbig** [comment]
This is a problem related to nicehash servers.
With or without LP enabled and doesn't matter the algo mining as long as it trys to communicate with nicehash servers it always happens "connection reset by peer" after a few hours mining.

**Comment by YamashitaRen** [comment]
I'm getting this too on my Online server (xmrig).

**Comment by sirbig** [comment]
Here it is NiceHash support response related to this matter:

> Please note that hashing power on currently popular algorithm CryptoNight is very high.
> 
> If you have problems with mining on a CryptoNight algorithm, that means that your mining hardware is not powerful enough to mine at a current level of difficulty and our system drops the connection.

**Comment by YamashitaRen** [comment]
https://www.reddit.com/r/NiceHash/comments/7b3rbe/please_fix_eu_cryptonight_pool/dpfho8i/
Seems like they just don't feel the urgency to fix the issue.

**Comment by sirbig** [comment]
And why would they? It's a waste of time and money to enlarge the pool resources so weaker miners can actually mine CryptoNight.

**Comment by YamashitaRen** [comment]
No, it's an oversight from their part since CryptoNight is the best coin to mine with CPUs at the moment.
CPU miners can't compare with GPU miners. It's idiot to make both mine with the same difficulty and have their system kick out (decent) CPU miners.

**Comment by sirbig** [comment]
I doubt that they have the same difficulty but I think if you have a CPU mining around 200 H/s you should be fine. From personal experience I had problems with CPUs mining at 100+ H/s where the connection would reset all the time.

**Comment by YamashitaRen** [comment]
My CPU does 275 H/s, have been banned from Nicehash overnight and is forced to run at a static 200k diff. It barely finds any share.
When I poolmine ETN, I get a variable difficulty from 3k to 10k.
The issue is Nicehash, not our CPUs.

**Comment by sirbig** [comment]
I guess you are probably right, but I don't think NiceHash staff is too worried about this since there is no update regarding this issue for nearly 2 months now.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Backend issue closing
