### ISSUE TITLE
Newer versions wont open, older works just fine, help?

### ISSUE THREAD

**Issue by gomesthiago** [nicehash/NiceHashMiner#789]
I downloaded the 1.8.2.0 Pre2 and 1.8.1.5 many times and they just dont open. I do not have any antivirus, the folder of all miners are in the windows defender whitelist, also the 1.8.2.0 Pre1 and 1.8.14 works just normal. 

I tried open the newer version as administrator, with the CMD with administrator privileges, but nothing happens. Tried downloading the bin to their folder, made no difference. There is no log files on their folders.

Any ideas on how to solve it? I'm using w10 x64

**Comment by jimmyhackers** [comment]
it might sound siily but if your downloading it with google chrome. try mozzilla instead.

**Comment by gomesthiago** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1595193/log.txt)

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1595192/log.txt)
I download with IE and got the same results. What I realized is that if I open right away after booting/windows login, really fast, it does open, but than closes and wont open again. Manage to get some logs, any ideas what could be closing it? I dont have anti virus and older versions works just fine!
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1595191/log.txt)

**Comment by gomesthiago** [comment]
Just found out what was happening. Since it opened right after restarted, I figured out that some process was killing it. For using my bank I have to install a protection software, otherwise I cant access the internet banking. It was killing the NHML, only the newer version. Unstilled it and it works just fine!

**Comment by nerdatwork** [comment]
@gomesthiago If your issue is resolved then please close this thread.
