### ISSUE TITLE
I am constantly taking different values ​​+lbry

### ISSUE THREAD

**Issue by SNiCKeeRS** [nicehash/NiceHashMiner#790]
Hello to everyone,
Why do I get different values ​​in the image that I have installed below? Would you please help? When I run the start.bat file from a different site, I get 139 Mh smoothly. But when I run the Nicehash program it becomes constantly variable and after a while it turns itself off.

Ben 
![asd](https://user-images.githubusercontent.com/34977498/34459856-e9e84d50-ee0d-11e7-907d-f1db9ed89a9b.jpg)

This differs from a start.bat file, which is not variable but digs in a different pool.

![123](https://user-images.githubusercontent.com/34977498/34459919-c69bf6a6-ee0f-11e7-8be1-5a29367ab728.jpg)

**Comment by SNiCKeeRS** [comment]
I fixed the problem by changing the operating system. I have converted the operating system from Windows 10 to Windows 8.1. In the future, it will help those who get the error.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
