### ISSUE TITLE
NHML no supported devide AMD AMOR R msi RX570 8gb, How to solve the problem? Is there any update?

### ISSUE THREAD

**Issue by PHILIPS4747** [nicehash/NiceHashMiner#792]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by dadoremix** [comment]
graphic driver ?
must be 17.11.04 or under that

http://support.amd.com/ru-ru/download/desktop/previous?os=Windows+7+-+64

**Comment by PHILIPS4747** [comment]
At this moment I am going to download the recommended version. I think it should be added to NHML in the next release, since it's the same RX 570 series only that it's 8GB. Thank you, very thank you

**Comment by PHILIPS4747** [comment]
At this moment I am going to download the recommended version. I think it should be added to NHML in the next release, since it's the same RX 570 series only that it's 8GB. Thank you, very thank you
