### ISSUE TITLE
my amd graphics is not working randomly on nice hash mining only cpu why?

### ISSUE THREAD

**Issue by ahmaditani** [nicehash/NiceHashMiner#793]

**Comment by dadoremix** [comment]
graphic driver ?
must be 17.11.04 or under that

http://support.amd.com/ru-ru/download/desktop/previous?os=Windows+7+-+64

**Comment by ahmaditani** [comment]
Ok thx bro 👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
