### ISSUE TITLE
SOCKET ERROR unknown bug

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#795]
**I cant mine and on the command it tells me this**

SOCKET ERROR - [cryptonight.eu.nicehash.com:3355] CONNECT error: ─ίΊ ▐ΪάΊ ϊΫΊάΪ▐ ύ ϊύΉώΎΫ±ή▀ά ≤²Ίϊί≤ύ≥, ίΏίώϊ▐ Ύ ΫΏΎΈΎήώ≤Ϊ▐≥ Ώ±ΎΎ±ώ≤ΉΎ² ΪύΊ άΏ▌±±

**again and again (only the first time it mine)**

**Comment by dadoremix** [comment]
nicehash pools are down..
you cant do anything

**Comment by ghost** [comment]
**ok thank you** 👍 :)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Looks like backend issue not related to client
