### ISSUE TITLE
RX vega and other amd cards

### ISSUE THREAD

**Issue by Buckthebarbarian** [nicehash/NiceHashMiner#797]
As many of you are aware, the recent update added the xmr-stak miner which should be able to make vega's achieve a hashrate of 1900h/s. The issue I am having with my setup is that when I only have a single gpu on my rig - in this case the vega - it hashes at its intended hashrate but as soon as I add another card (rx 570) it is impossible for it to mine cryptonight whatsoever. I've tried changing the index numbers on the config file and change intensities but still to no avail. Anybody else encountered a similar issue?

Many thanks!

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
