### ISSUE TITLE
NHML 1.8.1.5 Randomly Crashing

### ISSUE THREAD

**Issue by SNiemiec** [nicehash/NiceHashMiner#798]
Nicehash (Legacy) is crashing randomly. Cant see anything in log.txt, or in windows Event Viewer. Does not last more than 2 hours.

Sometimes hangs and crashes. Sometimes causes reboot.

Rock solid on Claymore ZEC standalone miner.

Always passed benchmarking  - precise.

Just modded BIOS with Polaris editor. Only 'one click timing' mod.
(Gave >20% increase on Claymore ZEC miner)

Now completed Nicehash benchmark (precise) again. Clean.

CONFIG
Biostar 250-BTC MoBo
4GB DDR4 RAM
AMD RX580 8GB x6
USB Monitor (or Teamviewer) used to manage rig
Windows 10
Virtual Mem = 24,000MB
Nicehash NHML 1.8.1.5
AMD Blockchain Beta driver
No OC or BIOS mods
(Recently modded BIOS with 'one click timing mod') - No change

**Comment by jimmyhackers** [comment]
does it to me too sometimes. turned out to be a fauty ssd and 3 of 4 faulty ram sticks.

are you cpu minging aswell? my cpu is too naff for nicehash but i loaded up minergate to run cpu mining at the same time as gpu mining on nicehash. and it crashed last night.

other possibility is your hardrive is hybernating????

**Comment by SNiemiec** [comment]
TX for pointers - cant seem to get anything from NiceHash.

Not CPU mining. It can run for >18hrs fine, then crash the AMD driver. Then it will crash frequently after a few minutes. If I run a different miner for a few hours, then hard reboot. It runs OK for >18 hrs again. I think the NiceHash switching may be 'clogging' up memory ??

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
