### ISSUE TITLE
AMD GPU device count BAD!!! on NHM1.8.2.Pre

### ISSUE THREAD

**Issue by cedtat** [nicehash/NiceHashMiner#799]
I have a rig with 8x1070Ti and 4xRx570.
I was able to make an older version work in early december but now I have this problem even with this new version.

NHM get stuck when detecting AMD OpenCL GPU
And I have this message at the end of the log file:

[2018-01-03 18:31:37] [INFO] [ComputeDeviceManager.Query] Cuda NVIDIA/CUDA device count BAD!!!
[2018-01-03 18:31:37] [INFO] [ComputeDeviceManager.Query] AMD GPU device count BAD!!!

See full log attached.
I have tried reinstalling completely drivers with DDU.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1601222/log.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
