### ISSUE TITLE
Question: Should I CPU Mine along with GPU Mine?

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#8]
Question: Nice Hash Miner 2 basically defaults CPU mining in addition to GPU Mining

NiceHashMiner / Legacy, default no CPU

Is it worth CPU mining or does it take too many of the CPU cycles away from the GPU Mining?

Example CPU: Intel i5 7th Generation

**Comment by DillonN** [comment]
It's up to you. CPU mining can vastly cripple your PC (if you're using it for other things than mining), and uses quite a bit of power for the hashes you get. If your CPU only gets you $0.50/day and it uses 80W it may not even be profitable depending on your electricity rates (it wouldn't be in my area).

**Comment by billmcilhargey** [comment]
Makes sense, yea CPU mining on cryptonight has gotten vastly harder so its not even worth it anymore either

Thanks!!
