### ISSUE TITLE
NHML  hangs after checking GPU (screen shot attached)

### ISSUE THREAD

**Issue by sgrinavi** [nicehash/NiceHashMiner#800]
i7-7700 @ 4.2 system has (1) 1070TI and (1) P4000 quadro, 32 GB ram
-Nicehash Miner 2.0.1.5 runs fine
-Currently attempting to use 1.8.2, but the same error occurred with 1.8.1.5
-would hang at the prior screen until I manually updated the config file to skip checking for AMD

log file attached

![capture](https://user-images.githubusercontent.com/35080929/34541316-bb92fe24-f0a5-11e7-8451-6a7a3d88f89b.JPG)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1601825/log.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
