### ISSUE TITLE
Nvidia Cuda 8.0

### ISSUE THREAD

**Issue by BeStrange** [nicehash/NiceHashMiner#802]
I first noticed the issue with a laptops Nvidia 640Ms. 

Issue:
NiceHashMinerLegacy will only give back half correct or no hashrates on benchmark for algos like skunk,  blake, and more. When NiceHashMinerLegacy launches to mine it will open the window display execution text, idle then close/reopen and infinitely loop trying to get it to work.

No missing kernel error displayed like it should when looking for missing cuda 9.0.
I fixed it by recompiling ccminer with cuda 8.0 support.

The mobile i5 and 640m hash cryptonight at a rate of about 190H/S for about 50W so its not a waste to run when this workstation is idle... You can also fix it with XMR-STK but just wanted to point out the general looping issue making your software unstable.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Laptop aren't officially supported
