### ISSUE TITLE
NiceHash cannot detect AMD graphics card

### ISSUE THREAD

**Issue by EZ56** [nicehash/NiceHashMiner#803]
NiceHash cannot detect most recent AMD graphics update. Previously had no trouble detecting it and worked fine, now it does not.

**Comment by techman05** [comment]
Me too but its probably me and you updating our drivers and the pre release  not recognizing it yet.

**Comment by EZ56** [comment]
I just redownloaded an older driver and it works with that, seems like new
driver isn't supported by nicehash yet.

Very Respectfully,
C3C Edward Zhou
United States Air Force Academy
Cadet Squadron 25 "Rock Hard Redeye"

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

**Comment by potikoutlaw** [comment]
having same issues with 5700xt and 580 help me please cant find any drivers that work !
