### ISSUE TITLE
Cryptonight stopped working

### ISSUE THREAD

**Issue by HansHagberg** [nicehash/NiceHashMiner#804]
Mining cryptonight towards cryptonight.eu.nicehash.com:3355 or any of your other cryptonight pools stopped working some time ago and it doesn't seem to come back. On Dec 22 - 23, i mined 24 hours to test Nicehash again and verify profitability etc. Mining worked OK then. Now it doesn't with the exact same settings as before. I'm running miners from command tools to get tuning right for VEGAs.
Cryptonight also does not work from Nicehash legacy. It just sits there doing nothing.

The error message I get in console window when running standalone miner is:

SOCKET ERROR - Connection Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Same with 2 different miners.
I can't find any info on this in forums expect the DNSflush thing, which has no effect.
It worked OK around Christmas with the exact same settings.

**Comment by Simaex** [comment]
@HansHagberg It is not a NHML issue. Try to contact NH helpdesk. BTW I have no issues using encrypted port 13355, two different rigs.

**Comment by HansHagberg** [comment]
I know...
I filed a support ticket way back on this but they routed me here today because they can't help.
The support seems technically totally incompetent and they answer like a scripted bot.
The only advice they could produce was that I should get a faster CPU because mining with CPU and high difficulty induces long delays... lol
When I explained further that this was with high-end AMD mining rigs and that I know what I'm doing, they sent me here...

What we could do here is perhaps find out if someone else is having problems with CryptoNight or if there is some way of troubleshooting this further. One thing I have noticed is that not many users will pass the benchmark for CryptoNight anymore. Something is definitely different and worse than a while ago. The motivation to work the problem on the Nicehash side is of course all the lost revenue due to the fact that people can't mine the most profitable algo for AMD. We are forced to mine coins directly on different pools.

**Comment by Simaex** [comment]
@HansHagberg no comments from NHLM team atleast from December. Don't expect any help there :-(
It seems that the project is abandoned by team. @DillonN please let us know what to expect.

**Comment by borzaka** [comment]
I can confirm, that mining with my CPU (Ryzen 5 1600) produces socker errors with xmr-stak-cpu.exe:
```
[...]
[2018-01-07 00:38:22] : SOCKET ERROR - RECEIVE error: socket closed
[2018-01-07 00:38:22] : Pool connection lost. Waiting 10 s before retry.
[2018-01-07 00:38:31] : Connecting to pool cryptonight.eu.nicehash.com:3355 ...
[2018-01-07 00:38:32] : Connected. Logging in...
[2018-01-07 00:38:32] : Difficulty changed. Now: 200007.
[2018-01-07 00:38:32] : New block detected.
[...]
```

With my 3 Vega 64 there are no errors (just job not founds).

[DillonN was taking a break.](https://www.reddit.com/r/NiceHash/comments/7o3rzq/nicehashminer_legacy/ds7y0uc/)

**Comment by HansHagberg** [comment]
I have now isolated the problem to some IP issue. By running from another IP adress, the problem goes away so this is probably not within the NHML code. Looks like some blocking setting either on NICEHASH server side or my ISP. Strange that this only affects Cryptonight.
Anyone know of any blocking protocols in place ?

Cryptonight is notoriously infested by botnets so it's not unthinkable there is something in place to stop traffic.

**Comment by xKozliczech** [comment]
yea .i need help too  :D 

4 days ago, my 960 g1 worked well all the algo .. now available but I do not work anymore, now my gtx mines less by 0.5doll .. first she has earned 1.8- 2 doll / day now 1.1-1, 3 doll / day ... nist5 447 H / s - now nothing .. WHY ??

![hn](https://user-images.githubusercontent.com/36009405/35694957-490d0aa8-0783-11e8-9b33-2d7116ef5f58.png)

**Comment by tusharantal** [comment]
I am facing the same problem any solutions ?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
