### ISSUE TITLE
Nist5 is warming up slowly when switched from other algos

### ISSUE THREAD

**Issue by dstarcev** [nicehash/NiceHashMiner#805]
Sometimes it takes a few minutes for nist5 to reach the max speed. It never happens when the OS has just booted. If nicehash has worked for a while and then switches to nist5, some GPUs don't start mining immediately. It can take up to 10 minutes (I never waited longer) for those GPUs to start.

From the following log file you can notice that the miner started at `[2018-01-03 22:09:07]`  and reached the maximum at `[2018-01-03 22:16:26]` , this time it took more than 7 minutes:

https://gist.github.com/dstarcev/052a6c9482d228d050c839a9ff9c1d70

**Comment by Spiral11** [comment]
I am also experiencing this problem. Nothing useful I can add though.

**Comment by peteraclausen** [comment]
Seeing the same thing, especially on my 9x 1080Ti rigs.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
