### ISSUE TITLE
Benchmark Terminated Equihash (nheqminer) and X11Gost (ccminer_alexis) any ideas?

### ISSUE THREAD

**Issue by W3DDED** [nicehash/NiceHashMiner#806]
![annoying shit](https://cloud.githubusercontent.com/assets/27772023/25181814/a9d8d13e-250a-11e7-8437-2653b9a1e263.png)
can anyone point me in the right direction? delete and reinstalll doesnt work, changed everything i know to make it work to the best of my ability and just still doesnt work. theres not much information on this around and ive been pulling my hair out over it for the past few days. if you know anything please comment. thank you

**Comment by S74nk0** [comment]
@W3DDED Disable these algorithms. Your GPU is SM 3.0 and sadly not algorithms are guaranteed to work (like in your case). 

Closing issue...

**Comment by W3DDED** [comment]
ive changed the nheqminer to version 0.3a. works perfectly when overriding benchmark. thanks dude
