### ISSUE TITLE
gtx770 asus Nvidia doesn't work help GPU

### ISSUE THREAD

**Issue by Eminencja** [nicehash/NiceHashMiner#809]
has someone managed to solve the problem with this,
He can not see her nicehasz.
thank you in advance
nothing has been done to reinstall the card drivers

Unsupported Device 
We have detected the following unsupported device GeForce GTX 770 (SM3.0)
Learn more about supported devices here.

Thanks a lot of helps guys :)

**Comment by jimmyhackers** [comment]
that sounds like a nice hash problem. try nice hash legacy instead

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
