### ISSUE TITLE
Socket Closed Remotely by Pool

### ISSUE THREAD

**Issue by SNiemiec** [nicehash/NiceHashMiner#810]
Multiple frequent messages 'Socket Closed Remotely by Pool' on two different rigs. 

Coins: ETH, LBR, DCR so far. So not just one pool.

Both running v1.8.1.5

Cant seem to get any response from NiceHash team for this, or other issues opened?

**Comment by dB-SPL** [comment]
It's not just you.  Lots of people are having trouble connecting to lots of NH's stratum servers.  Issue 804. 806, and 811 all look like this same problem.  I have it using NHL as well as MultiPoolMiner if I select NiceHash as the pool.  You may consider setting up something like MultiPoolMiner that can failover to another pool if NiceHash goes down.

NiceHash has mentioned ongoing maintenance for the website on their Twitter feed, so I may just be that it affected more servers than expected.  Then again, given the lack of transparency right after the hack, the silence in the face of a problem isn't really out of the ordinary.

**Comment by SNiemiec** [comment]
I can just point my rig somewhere else. Bigger issue for me is the lack of response to this and other support tickets.

Support not impressive

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Backend issue not related to client
