### ISSUE TITLE
Problem connecting to pool

### ISSUE THREAD

**Issue by Thinus-jv-Rensburg** [nicehash/NiceHashMiner#811]
DevFee:  Job timeout, disconnect, retry in 20 sec...
 Job timeout, disconnect, retry in 20 sec...
DevFee:  Job timeout, disconnect, retry in 20 sec...
 Job timeout, disconnect, retry in 20 sec...
DevFee:  Job timeout, disconnect, retry in 20 sec...
 Job timeout, disconnect, retry in 20 sec...

**Comment by SNiemiec** [comment]
All my pools are unable to connect. Again...

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Backend issue not related to client
