### ISSUE TITLE
Is DillonN still maintaining NHML?

### ISSUE THREAD

**Issue by peteraclausen** [nicehash/NiceHashMiner#816]
After the NH hack back in December, there have been no updates to NHML.

The last pre-release version dates back to November 27th of last year.

Dillon used the crank out releases every few weeks.  What happened?

**Comment by dadoremix** [comment]
yep.. where are guys ? holliday or what ?

**Comment by Nicheuji** [comment]
@peteraclausen @dadoremix 
https://www.reddit.com/r/NiceHash/comments/7o3rzq/nicehashminer_legacy/ds7y0uc/
:)

**Comment by dadoremix** [comment]
:)
tnx for answer

i cant following all informations about nicehash
also.. i mining for fun.. on 1x rx580 8gb sapphire

**Comment by peteraclausen** [comment]
Excellent!  Welcome back Dillon!

**Comment by S74nk0** [comment]
Yes he is.
