### ISSUE TITLE
Nicehash not detecting my rx 480 8g

### ISSUE THREAD

**Issue by raph78126z6** [nicehash/NiceHashMiner#817]
Wen i'm in the menu of nicehash, my gpu don't appear in the devices categories. I hope you can help me 

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1607942/log.txt)

**Comment by wilsonaron** [comment]
This problem is affecting me as well

**Comment by raph78126z6** [comment]
@wilsonaron did you got some help to fix it or are you like me, blocked ?

**Comment by raph78126z6** [comment]
@wilsonaron i just found how to do.
You need to desinstall your drivers of your AMD card and then reinstal the 16.12.2 version
I think the most recent drivers can't be detected by NiceHash. I can give you the file if you want to download it

**Comment by ghost** [comment]
This happened to me as well with my RX 480, problem started after I updated to 17.12.2.

**Comment by wilsonaron** [comment]
@raph78126z6 Yes I got it working using the AMD utility to remove the new driver. I'm running fine with 17.2

**Comment by ghost** [comment]
How to fix:
Download DDU from http://www.guru3d.com/files-get/display-driver-uninstaller-download,1.html
Reboot into safe mode
Run DDU, grant administator access and select "Clean and restart"
Your computer will boot normally, now download and install 17.12.1 (Latest working drivers at the time of writing) from http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Adrenalin-Edition-17.12.1-Release-Notes.aspx
Reboot
You may want to open up WattMan and set workload to compute and such (I overclock memory to 2160Mhz, but what's stable for you will vary)
Run NiceHash and enjoy
