### ISSUE TITLE
It just says "starting excavator" but it never really does anything

### ISSUE THREAD

**Issue by cbaine711** [nicehash/NiceHashMiner#818]
Okay, so I just installed NiceHash and everything was going good installing, but then when I launch the app it gets to where it says "starting excavator" and it won't go anywhere from there. I don't know how to fix this. 
![nicehash](https://user-images.githubusercontent.com/35152273/34630429-0b93dcfa-f23a-11e7-81d5-e0ad9515bd24.PNG)

**Comment by S74nk0** [comment]
Not related to nhml/nhm1 this issue is for discontinued nhm2 client.

Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
