### ISSUE TITLE
1.8.2.0 Pre-Release 2 does not read my amd video cards

### ISSUE THREAD

**Issue by andrei111184** [nicehash/NiceHashMiner#819]
I have two video cards amd r280x and two msi nvidia 1060 use nicehash 1.8.2.0 Pre-release 2, nvidia video cards read them but amd no

**Comment by andrei111184** [comment]
I have the latest version of drive update 22/12/2017

**Comment by nerdatwork** [comment]
Have you tried older versions ?

**Comment by andrei111184** [comment]
I installed an older driver and still does not read my AMD video cards. what to do?

**Comment by Kams84** [comment]
AMD R9 380 is not detected. Radeon Software Version
17.12.2

**Comment by dadoremix** [comment]
So really people
Are you reading other posts here?
Every post, does not see graphic ..
Nicehash does not work on new drivers
Use BlockChain AUG23 .. the best ones

**Comment by andrei111184** [comment]
I installed Win10-64Bit-Crimson-ReLive-Beta-Blockchain-Workloads-Aug23 and reads my video cards as well. thank you

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
