### ISSUE TITLE
2xVega 56 and 4xRX570 get mixed-up

### ISSUE THREAD

**Issue by maleduc04** [nicehash/NiceHashMiner#820]
Hi,

I am running 2x Vega 56 and 4x RX 570 4GB. running Nicehash Legacy Miner v1.8.2.0-Pre2 on Windows 10 Pro Gigabyte GA-H110-D3A.

Nicehash detect all my card but not in the right way.  Here what I see : 
GPU#1 Radeon RX Vega
GPU#2 Radeon RX 570 Series (In reality this is 1 RX Vega)
GPU#3 Radeon RX 570 Series
GPU#4 Radeon RX 570 Series
GPU#5 Radeon RX Vega (In reality this is 1 RX 570 Series)
GPU#6 Radeon RX 570 Series

This being said, 1 vega get mixed up with one rx570. The result at the end, they are not mining what they are suppose to. 

My first question is, does it really matter (I guess because both vega aren't mining the same coin) 
Second question, any way to reset or resolve the naming association?

All benchmarks have been done today.

Thank you very much for any suggestion / help.

**Comment by nerdatwork** [comment]
IF you are running Claymore or other miners, have you tried using different versions of them to see if that works.

**Comment by maleduc04** [comment]
Ya the miner it self works, it is just in Nicehash that the card are mixed up. And it look like that because of that the Mixed Vega doesn't mine what is supose to mine (as a best coin to mine).

**Comment by maleduc04** [comment]
Little update, - FIX

Here what I have done and it work so far, touch wood! :)

1. I have switched my 1xVega and 1xRX570 (Pci slot) 
2. Then all my 6 card were gone from my Nicehash 
3. Clean driver uninstall+reboot
4.  Install Blockchain driver again+reboot
5. All my cards are now in order :)

Hope this will help others

**Comment by nerdatwork** [comment]
Congrats. Thank you for posting a solution too so others can learn from it. Please close the thread.
