### ISSUE TITLE
NHML does not start

### ISSUE THREAD

**Issue by melomcr** [nicehash/NiceHashMiner#823]
I'm trying to run NHML but the software won't start. Thinking it could be an Anti-virus issue, as reported before, I turned off all of Avast "shields" and added NHML to  global exclusions, but no luck. Windows defender is turned off.
I tried the latest stable version 1.8.1.5 and 1.8.2.0-Pre2, with the same result.

There is absolutely no warning, error, or any other message indicating lack of dll(s). I did install vcredist_x64, but my .NET was already 4.5 in Win10, so nothing needed to be installed for .NET.

Trying to run NiceHashMinerLegacy.exe through the command line gives me no further clues. It just doesn't return anything, skips a line and returns me the prompt.

Short of compiling myself (which I believe is the only thing I haven't done), does anyone have any ideas? I can run the pretty GUI just fine, but wanted to try some customizations and maybe some better performance from newer algos.
I don't want to have to recompile everything and lose the proprietary algos.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
