### ISSUE TITLE
NHML USD values all displaying as 0.00 while mining - need help please!

### ISSUE THREAD

**Issue by xer0byt** [nicehash/NiceHashMiner#825]
Hey, I'm pretty new to mining and I'm trying to work my way through it, but I have an issue that I can't seem to figure out. I didn't find any other posts about this and googling it didn't produce any relevant results, so I'm hoping you guys can help. I got a basic mining rig running New Years weekend and everything seemed to be working fine. 
The hardware being used is:
AMD FX-8350 on Gigabyte G1 Gaming mobo
Sapphire R9 Nano
Sapphire R9 280 Dual-X OC Edition
8GB Crucial Ballistix RAM
Intel 530 Series 128GB m.2 SSD

Before moving it to the other room where I'm going to have it running full time I decided to use my watt meter to calculate the total power usage. After stopping the mining and shutting down the machine with no issues or errors reported, I moved the plug to the watt meter and powered it back on. Ever since then NHML shows my balance in mBTC, but for USD it says 0.00, and for each device it's reporting a rate of 0.00. Before moving it to the meter outlet it was displaying all dollar values. I have tried rerunning all benchmarks, system reboots, I even went as far as deleting all mining files from the system and redownloading/reconfiguring them, and it's all showing as 0.00 still. I'm not really sure where to go from here. I am attaching a screenshot and the log file in case that will help.

![dollar_value_zero](https://user-images.githubusercontent.com/34779230/34643121-ba0a2c8c-f2d3-11e7-9e79-84dfefc83ecd.png)

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1609125/log.txt)

**Comment by dadoremix** [comment]
are you try disable one GPU ?
and try ..

**Comment by xer0byt** [comment]
Did I try disabling one of the GPUs? No, but I can try that quick.

**Comment by dadoremix** [comment]
what say stats online ?
also how long are you mining.. ? leave 30 min.. and check online stats.. 
also use 1.8.1.5

**Comment by xer0byt** [comment]
Sorry, I should have included that in the first post, I am using NHML 1.8.1.5.
Before I started this thread it had already been mining for almost 24hrs straight before I restarted it. The stats online show the same amount of mBTC as the program (currently 0.00175202 mBTC = $29.35). I tried disabling a GPU and then closing and reopening the program (running it as administrator) and it still displays the USD values as 0.00. I have started it mining again, so I will wait 30min-1hr and then let you know if anything has changed.

**Comment by dadoremix** [comment]
you have strange problem
but hey.. 
global mBTC is working.. 
online stat is working.. that good and essential thing
when devoleper come back.. may he can fix it..

**Comment by xer0byt** [comment]
Well, it's still showing those values as 0.00 in the program, but it's all updating online, and like you said the global mBTC is working so I guess for now I won't worry. I'll wait and hopefully a dev can jump in and help out at some point. Thanks.

**Comment by ghost** [comment]
same problem after update to 1.8.1.6

**Comment by dadoremix** [comment]
right now me to .. 
problem with nicehash servers .. again :(
but mining is working, and that is ok..

**Comment by Loebachus** [comment]
I'm having same issue.

**Comment by jmanabc** [comment]
I'm also having the same issue. Restarting computer didn't work, uninstalling nicehash didn't work, awaiting solution.

**Comment by dadoremix** [comment]
Are you check message on fb from nicehash?
Server for that is not working, but mining is working

12.01.2018., u 04:58, korisnik Johnny Wilkes <notifications@github.com> je napisao:

**Comment by S74nk0** [comment]
This is API issue. If API is not available then the values will be 0. We will add some GUI warning notices regarding in-house or 3rd party APIs.

Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

We will be working on a complete GUI re-design.
