### ISSUE TITLE
Unable to auto-mine without completing all benchmarks -- Option to Disable?

### ISSUE THREAD

**Issue by rwwwwwr** [nicehash/NiceHashMiner#826]
On my computer sgminer seems to be crashing. Normally, this isn't an issue since I've disabled it and the miner doesn't use it.

However, it never was able to benchmark it.

Thus, whenever I open the program, it prompts with a warning to complete the benchmarking. I can easily dismiss this with a "no" and have the miner begin mining.

However, the concern I have is that when the miner reboots (say due to hardware instability or power issues), NHML will automatically launch (per the settings) but it will NOT automatically start mining because of this warning. It requires user intervention. Can this be addressed? Either a setting to default to "mine always, regardless or benchmarks?" or maybe a "ignore unfinished benchmarks"?

NHM version Legacy v.1.8.2.0 pre-2

**Comment by dadoremix** [comment]
you can disable in benchmark 
or
you can edit in setting .. and add some numbers
but .. for mining use only claymore miner.. that give you best $/day

**Comment by rwwwwwr** [comment]
@dadoremix - Aha! That's it. I didn't realize that I had still enabled some algorithms that weren't benchmarked (e.g., Siacoin at the bottom of the list). I just unchecked those algorithms and the warning went away.

Thanks!
