### ISSUE TITLE
r7 370 not registering with NHL

### ISSUE THREAD

**Issue by newguy1233** [nicehash/NiceHashMiner#827]
So trying to build a testing rig and running the r7 370 as another card on the board and its not registering the r7 370. Anyone with thoughts?

**Comment by phant** [comment]
check other issues [here](https://github.com/nicehash/NiceHashMinerLegacy/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++adrenaline)
adrenaline drivers 17.12.x not supported.
install old crimson release or wait update

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
