### ISSUE TITLE
SOCKET ERROR : TEMP BANNED

### ISSUE THREAD

**Issue by nelsonbim** [nicehash/NiceHashMiner#828]
Hello,

After the return of the service, I have received a lot of these messages:

SOCKET ERROR : SOCKET ERROR
SOCKET ERROR : TEMP BANED

I tried forwarding an email to the support team, however they told me that my hardware is not strong enough, where my ip is locked for a while.

I have 6 machines to mine with CPU, using the algorithm cryptonight.
I have a return of $ 12 a day.

Does anyone have the same problem? How do we solve it?

**Comment by veridicis** [comment]
Same issue here, 3 machines. I've started mining XMR with CPU outside of NH until the ban is lifted.

**Comment by Goorath** [comment]
I've just started to have the very same issue, all servers, CPU and even GPU.. Mee got 880K OC'd to 4,5Ghz, and R7 250 2GB GDDR5 (512SP edition) also OC'd.. It really look like an IP ban due to a week Hardware.. Bah.....

**Comment by oneEyedCharlie** [comment]
NiceHash is a deceptive name.  It should be MeanHash.

**Comment by amfikuz** [comment]
getting same today and yesterday

**Comment by jvanord** [comment]
I am receiving the same error. Just started using NiceHash yesterday on Windows 10 64bit with i7-7500. Worked great for a few hours, but I woke up this morning to no active workers and found that this error precedes an unending series of socket errors.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Looks like backend issue or user ban issue not related to client. 

Write to support@nicehash.com instead
