### ISSUE TITLE
An Ivy bridge Intel I7 cpu and it says not supported

### ISSUE THREAD

**Issue by mshafey12** [nicehash/NiceHashMiner#830]
Hello,
I was trying to run Nicehash miner on my Laptop and it has Ivy bridge intel core i7 3517U CPU  but I couldn't as it says no supported devices found although when I checked it, I found that it supports both the AES-NI and SSE4.2 ? can anyone tell me what i am missing?

**Comment by S74nk0** [comment]
Device is not supported.
