### ISSUE TITLE
R9 270X not detecting in legacy miner

### ISSUE THREAD

**Issue by Dougiefresh738** [nicehash/NiceHashMiner#831]
I have used both NHML-1.8.2.0-Pre2 as well as NHML-1.8.1.5 after the whole nice has incident i have updated my graphic drivers to adrenaline as well as gone back to crimson, as well I have also updated/flashed my bios. yet my asus r9 270x will not detect but my cpu will
My PC specs are:
AMD FX 6300 unlocked
ASROCK 970 Extreame3 R2.0
Asus r9 270X DirectCUII 
KIngston Savage 2x4gb total 8gb
mining software worked fine before incident with NiceHash getting hacked but after incident my gpu will not longer detect in software only my cpu will detect as i said already flashed both bios on mobo and installed different drivers. any help no error codes just will not detect gpu im stumped

**Comment by j3rwin** [comment]
Same issue here, my XFX R9 270X is not detected by nicehash. Tried both NHML-1.8.2.0-Pre2 and NHML-1.8.1.5 using the latest adrenaline driver.

**Comment by portablesounds** [comment]
I am also having the exact same issue. XFX R9 270 with newest driver on NHML-1.8.2.0-Pre2.

**Comment by andre2539** [comment]
me too, already check with the check_all_amd.bat i'm using latest driver & NH miner

**Comment by portablesounds** [comment]
I fixed it by backdating to the 16.2.1 drivers. The newest drivers aren't compatible yet.

**Comment by Dougiefresh738** [comment]
Can you post a link to the drivers so I can go back as Well

**Comment by portablesounds** [comment]
I don't have the link but if you search the other issues on this forum there other threads about AMD cards not detecting and someone provided the link. Also if you Google AMD drivers 16.2.1 the AMD website comes up.

**Comment by Dougiefresh738** [comment]
Thanks dude
.

**Comment by j3rwin** [comment]
http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-Beta-for-Blockchain-Compute-Release-Notes.aspx

^Should've posted this few days ago, sorry.

**Comment by andre2539** [comment]
is that only 16.2.1 worked ?

**Comment by j3rwin** [comment]
That's the only one I tried.

**Comment by andre2539** [comment]
now detected using the 18.1.1

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
