### ISSUE TITLE
New Install BIN.ZIP is corrupt

### ISSUE THREAD

**Issue by JimKnightster** [nicehash/NiceHashMiner#832]
Downloaded the latest version, temp disabled AV then when running the Nicehashminerlegacy.exe it downloads the BINS.ZIP file and tries to extract it, it hangs at about 3.85 percent and freezes there.  After several attempts I decided to take a look at the bins file and when I extract it with 7Zip it tellls me there are several files inside that are corruipt or have CRC errors.  I manually downloaded the bins file and am going to attempt to extract it manually but thought you should know.

**Comment by JimKnightster** [comment]
Same thing happens when Bin_3rdparty.zip freezes at about 15.40 percent and manaully extracting it shows CRC and Data errors in the zip.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
