### ISSUE TITLE
NHML during startup stuck on “Checking AMD OpenCL GPUs”

### ISSUE THREAD

**Issue by batishchevv** [nicehash/NiceHashMiner#833]
Windows 10 
6x1060 + 6x1070

NHML 1.8.2.0

Stuck on “Checking AMD OpenCL GPUs” on startup.
But if I remove one of GPU. Everything works fine. (With 11 GPU)

I thinks that the problem on step with checking virtual memory. Because it’s stuck before this step.

Also Nicehash miner starts correctly

**Comment by batishchevv** [comment]
I have 8Gb physical memory and 66Gb of virtual memory accordingly.

Isn’t enough?

**Comment by SicnessPrime** [comment]
I found a fix try to locate your Nvidia install folder usually at C:\Program Files\NVIDIA Corporation. Then look for a folder named NVSMI then move that folder or rename it. Try to run Nicehash Legacy again.

**Comment by batishchevv** [comment]
Thank you so much, it helps!

**Comment by kuanos1** [comment]
Thanks for the help! but I couldn't find the NVSMI folder under Nvidia install folder. Mine is Nvidia version 390.65 . thank you

**Comment by Braintelligence** [comment]
@SicnessPrime What is the reason for this? Your fix helped me as well.

**Comment by UselessGuru** [comment]
> What is the reason for this? Your fix helped me as well.

Incompatible versions of nvml.dll in both folders.

**Comment by Braintelligence** [comment]
@UselessGuru That makes sense.

**Comment by batishchevv** [comment]
I have problem with this solution. Benchmark EWBF и DTSM doesn't starts without nvml.dll.

**Comment by batishchevv** [comment]
I have found that problem is not with nvml.dll but with nvidia-smi file in this folder
When i rename just this file - NHML starts fine and there is no any problems with benchmark

But i think that this is not the right solution...
Any thoughts?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
