### ISSUE TITLE
GPU sorting is incorrect AMD cards 

### ISSUE THREAD

**Issue by jhardman01** [nicehash/NiceHashMiner#834]
GPU sorting is incorrect AMD cards 

need to added support for Adrenalin drivers, 

Adrenalin drivers (GPU sorting, fan/temperature/clocks management) 

reports incorrect in nice miner ver 18.1.5 / windows 10 /AMD Driver 17.12.2

issue is if I select RX480 card nice hash mine will start to mine on RX VEGA instead, 

claymore miner has released and new version 10.3 to fix this issue, 

but still nice hash will have update the program has the GPU sorting is incorrect 

https://bitcointalk.org/index.php?topic=1433925.0

thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

This is fixed in latest release
