### ISSUE TITLE
I have updated the card and it has not been going since I restarted the computer and went back to the program

### ISSUE THREAD

**Issue by davides1979** [nicehash/NiceHashMiner#839]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by davides1979** [comment]
![captura de pantalla 8](https://user-images.githubusercontent.com/32692066/34726656-007f4afc-f555-11e7-8d5a-10e0417df7a1.png)
![captura de pantalla 9](https://user-images.githubusercontent.com/32692066/34726657-009c3b3a-f555-11e7-85c2-900bbf21b5a7.png)
![captura de pantalla 10](https://user-images.githubusercontent.com/32692066/34726658-00c36d90-f555-11e7-8828-1a3d7240d705.png)
![captura de pantalla 11](https://user-images.githubusercontent.com/32692066/34726659-00e17f10-f555-11e7-8283-ee6cbba8c374.png)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
