### ISSUE TITLE
NH stop running due to random GPU connection lost

### ISSUE THREAD

**Issue by Linightz** [nicehash/NiceHashMiner#841]
Hi, I have dozens of rigs running on NH 1.8.1.5 and here's the thing: some of the rigs would randomly lost 1 GPU connection after running for several hours (when you see in the afterburner you can still see the GPU but just no info at all) and then NH just stucks at start miner - show a GPU error - close miner - restart miner and repeat and repeat.

When a GPU connection lost, the GPU is still showing working properly in the Windows device manager, to temporarely fix the problem is to restart the system and its good until the next time some GPU connection lost (and its not always the same GPU).

This only happens to my Nvidia rigs, on the SW side I've tried disabling P0 state, disabling Keccak algo, updating GPU driver, re-installing OS, updating MB BIOS. On the HW side I've tried replacing the USB riser, changing the PCIE slot. Problem persists. Now Im empty handed, not sure what else to try. Can anyone point a direction? Thanks in advance.

**Comment by WebJSo** [comment]
I had the same problem, fix applies to legacy miner. I haven't tried with V2. 

Open settings in NiceHash program, choose "Run script when CUDA GPU is lost". Download NvidiaInspector and place in folder NV_Inspector inside same folder as NiceHashMinerLegacy.exe. Look for OnGPUsLost.bat, I use option 2 which does not restart the rig e.g. 
::Select desire option here
set OPTION=2 

I think you will also need to use MSIAfterburner or remove it from the bat file. The bat should tell Afterburner to use profile2 when it reloads, mine didn't appear to be working so i added the following to the end of the bat file. 
start "" "C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" -Profile2
(restart nicehash to use the updated .bat file)
If you are using AfterBurner, then you want your overclocks to be on profile 2 or match the profile number described in the bat file.

You can check this works by double clicking the bat file when nicehash is running. It should shut it down and restart, if you have to manually click any dialogues during this process they will need to be disabled so it can all be automated by the program.

If you want your computer to restart automatically (assuming you don't need to sign a user in to windows)(option 1), you should be able to leave the .bat file as it is.

GL!

**Comment by luongk** [comment]
I had issues with one GPU crashing - tried a bunch of stuff, in the end it was a faulty PSU

I'd check all your gear.

**Comment by Linightz** [comment]
I still have a lot of this problem, and I doubt it's HW problem because it happens time by time. If a faulty PSU causes this, then this problem should keep happening until I change the PSU, but it happens a lot on one rig for some time and then it just stops happening all of a sudden, or becomes a lot less frequently. I'm still looking for the cause for this, I just want to make sure it's not due to SW side before I go into HW. 

I've been using @ViolentJim 's solution for some time now, it's working most of the time but now they have the unable to get profitability data problem which would stops the program after restart so it's still a pain in the ass.

**Comment by WebJSo** [comment]
I think the latest legacy miner stopped it having problems with the profitability dialogue.. v1.8.1.6

I noticed my rigs had this problem less often when i spread them out from using power sockets in similar areas. Perhaps it is a power problem but i have not been able to resolve it. I rely upon resetting the driver. I have all brand new good quality PSU's, some identical rigs and some different and they all have this problem.

**Comment by Linightz** [comment]
I wonder if algo changing has anything to do with the problem, so I tried to set the fixed time before changing algo to days on a rig thats been happening a lot. It's been 2 days and the problem hasn't occurred on the rig yet. In this case it might be NHML program issue or particular algo and/or its miner issue.

**Comment by WebJSo** [comment]
It is likely that when the algo changes, the graphics card is still in current P(0) state, which results in it being in an unstable clock briefly, causing it to crash. It is probably more profitable to reset the driver than stick with a single algo..

**Comment by Linightz** [comment]
Thanks @ViolentJim , but it's still happening after I disabled P0 state. Anyways. I've been using the option 1 to restart the rig as the workaround but some rigs take mins to restart, and when the problem occurs very often the up time is significantly affected. So now I'm considering using option 2 to just restart the driver, thanks to your guide it's pretty clear but just one thing, why would you use profile 2 in afterburner? why not just use profile 1? and when it restarts the driver the afterburner has to be restarted as well?

**Comment by WebJSo** [comment]
The P(0) state issue will still apply even in different P(n) states as far as i know, but i don't know enough about it to be sure. 
You can set the .bat file to use whichever profile you want. I think profile 2 is used if the clock is unstable and you want to boot into a different (stable) clock speed first. 
The .bat file should restart the driver using NVInspector and then restart Afterburner with the -profile2 argument. (which you can change to profile 1 if you want)
Option 2 fix appears to not work if you have different types of graphics cards. One of my rigs has different manufacturers of the same card and Nicehash appears to not open the .bat file. However, all of these cards come back "online" except the primary card is reset to default clock speeds. I've learned to live with this.
