### ISSUE TITLE
extra launch parameters tool tip or help

### ISSUE THREAD

**Issue by professor-jonny** [nicehash/NiceHashMiner#843]
would it be possible to add tool tips or a help file for the extra launch parameters?

at the moment you have to troll the nicehash website to find them, also the data on the net is incomplete as there are more miners than on the online dock that explains extra launch parms.

**Comment by S74nk0** [comment]
We could give option suggestions based on the plugins `MinerOptionsPackage`, although we currently don't hold any value ranges for options with parameters (we could add include them easily though). We will consider this feature when new GUI is implemented. Although keep in mind that with external plugins this would depend on plugin implementation.
