### ISSUE TITLE
1080 TI CUDA Count BAD Error

### ISSUE THREAD

**Issue by DustoMan** [nicehash/NiceHashMiner#845]
This started happening a couple days ago. NHML will start up and sit on "Querying CUDA Devices" for about a minute or so and when the Loading procedure completes I will only see my CPU listed. It's happening with the three versions I have installed on my computer. (1.8.15, 1.8.2.0-Pre2, and 1.8.1.6) And with at least the last two Nvidia driver versions. (390.65 and 388.71). I have tried re-installing the drivers and starting over with a fresh config. Nothing seems to help. I have a second machine running Windows 10 and a 1080 that doesn't have these issues. Any ideas what could be causing this?

Log file from fresh 1.8.1.6 install: https://pastebin.com/YBRUmHpi

Windows Server 2012
EVGA 1070 TI FTW2

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
