### ISSUE TITLE
Unable to mine without Benchmark but Benchmark crashes

### ISSUE THREAD

**Issue by mast3rd3mon** [nicehash/NiceHashMiner#846]
I have recently downloaded the miner to mine with my amd chip and gpu, i am unable to mine as i havent completed a benchmark. However, whenever i run a benchmark, my screens turn on and off and never finish the benchmark resulting in me having to restart my pc.

I have an AMD fx-6350 CPU and a Radeon RX480 GPU

--EDIT--
My PC is NOT overclocked in any way.

**Comment by dadoremix** [comment]
do you overclock GPU ? Maybe too much and crash drivers ..
Try run benchmark at normal settings of gpu..

**Comment by mast3rd3mon** [comment]
Nope, my pc isn't overclocked in any way

**Comment by dadoremix** [comment]
Try normal or precise
Or disable that miner (sgminer? ?

11.01.2018., u 10:09, korisnik mast3rd3mon <notifications@github.com> je napisao:

**Comment by mast3rd3mon** [comment]
Its just the default settings that are set via a clean install, i havent changed anything. So i think it runs the `normal` option, i havent tried quick or precise

**Comment by mast3rd3mon** [comment]
Any updates? Its bugging me that it seems to crash

**Comment by jimmyhackers** [comment]
run one benchmark at a time..... when it completes successfully it will add its score and be saved.
keep doing this untill you find the benchmarked algo that is causing your problem....and just ignore/dont benchmark/use it.

id also like to mention my compter has become alot less glitchy since ive stopped using google chrome to download things including my graphics drivers

**Comment by mast3rd3mon** [comment]
Im currently in the process of moving my pc components into a new case but
ill try it as soon as i can

**Comment by xiaoyaoyang** [comment]
I would say try to support as much as power supply as you can, and try one gpu at once.

**Comment by mast3rd3mon** [comment]
Its a 500w psu and i only have 1 graphics card
