### ISSUE TITLE
in NHML1.8.1.6 equihash EWBF not working

### ISSUE THREAD

**Issue by jayjay426** [nicehash/NiceHashMiner#847]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by kaos-1** [comment]
The SSL:// stratum is working every time. EWFB is not connecting / takes time connecting when it activates.
Please enable us to use SSL in NHML (a switch option?) if we want to.

**Comment by kaos-1** [comment]
WE should also add [DSTM 0.5.8](https://bitcointalk.org/index.php?topic=2021765.0) Zm miner its giving 300 sols extra per 6x 1070 rig. It's time to retire EWFB anyway.

**Comment by K9Aleksandr** [comment]
Hello. An error with the algorithm of Equihash, today a day has arisen several times. Perhaps when mining some coins on this algorithm, an error occurs (the miner constantly restarts). This applies to both ministers on the Equihash algorithm. I tested this on different versions of NiceHash. An error is present everywhere. There is a new minor Equihash zm_0.5.8_win it is more profitable. It would not be bad to see him as part of NiceHash.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
