### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by RodAus** [nicehash/NiceHashMiner#849]
If possible included the changelog in detail in the release description thanks.

**Comment by luongk** [comment]
...like the section labelled "Changes"?

**Comment by RodAus** [comment]
"Changes" is just the main changes or more important, changelog is more detailed

**Comment by luongk** [comment]
I feel like you're asking a bit much of what is effectively a free bit of software - the source commits are on github.

**Comment by RodAus** [comment]
I just want to know more about the software, do not make people waste their time reading these things that do not help.

**Comment by Nicheuji** [comment]
@RodAus Let's take 1.8.1.5 as an example
![commits](https://user-images.githubusercontent.com/29155732/34822273-5191cfb6-f701-11e7-876d-d4cff6ea6c26.jpg)
After clicking on that it'll show you a comparison page of what's been changed. As you scroll down the page you'll see lines highlighted in red (removed) and in green (added)

**Comment by RodAus** [comment]
@Nicheuji Thank you.
