### ISSUE TITLE
Can't run NiceHashMinerLegacy v1.8.0.2

### ISSUE THREAD

**Issue by owen29338** [nicehash/NiceHashMiner#85]
I have download NiceHashMinerLegacy v1.8.0.2 from link : https://github.com/nicehash/NiceHashMinerLegacy/releases
But show error as picture in attached file.

Hardware : NVIDIA 1080 ti
![error nicehash](https://user-images.githubusercontent.com/30491715/28659562-2645eb72-72da-11e7-84e0-06cacf48a5aa.jpg)

**Comment by drkskwlkr** [comment]
@owen29338: See if #32 fix will help?

**Comment by DillonN** [comment]
Like @drkskwlkr said you can try copying OpenCL.dll from the ethminer directory into the same directory as NiceHashMinerLegacy.exe

You can also edit `\configs\General.json` and changing `"DisableDetectionAMD": false,` to `"DisableDetectionAMD": true,` since you aren't using AMD devices.

**Comment by owen29338** [comment]
I try to do already then show this message is ok?

![image](https://user-images.githubusercontent.com/30491715/28660913-1cb5134e-72df-11e7-850e-27514f8dcbe0.png)

**Comment by DillonN** [comment]
Yes it's just a check that you have enough free RAM. With the 1080 Ti's large VRAM size it comes up too often, will be adjusted soon. You can click OK and all should work

**Comment by owen29338** [comment]
Why I can't benchmark success is show message as below ,plz help
![image](https://user-images.githubusercontent.com/30491715/28665312-7556e35c-72ed-11e7-946d-319d7fd18c25.png)

**Comment by drkskwlkr** [comment]
@owen29338 It happens from time to time. Just click retry and the rest of the benchmarks will probably complete.

**Comment by owen29338** [comment]
Why show only 1 algorithm ,another people show many algorithm ,plz help again
![image](https://user-images.githubusercontent.com/30491715/28668126-ad530b86-72f8-11e7-9e7d-48fd74246771.png)

**Comment by drkskwlkr** [comment]
@owen29338 Dude, do you even know how lists work? You've selected your CPU in the top list and the bottom list shows algos available for the CPU. Click on a video card and the list below will display the algos available for video cards. It's all written in the interface.

**Comment by owen29338** [comment]
5555 Thx @drkskwlkr

**Comment by owen29338** [comment]
Solution of #32 is solution for my issue ,thank your guys @drkskwlkr @DillonN
