### ISSUE TITLE
xmr-stak-cpu not hiding miner window

### ISSUE THREAD

**Issue by Fredrik81** [nicehash/NiceHashMiner#850]
NiceHash Legacy version 1.8.1.6

When the option to hide miner window is selected xmr-stak-cpu window will only be minimized at start but not hidden. Other miner windows are correctly hidden.

**Comment by etobia90** [comment]
I can confirm this on version 1.8.1.6, also an issue on 1.8.2.0 Pre-2.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
