### ISSUE TITLE
xmr-stak missing in 1.8.6.1 release without any trace in change log?

### ISSUE THREAD

**Issue by jojobg** [nicehash/NiceHashMiner#851]
xmr-stak missing in the bin folder in the new release despite released in the previous version. I see there are no commits for nicehash configuration, so is this issue related with the bin.zip release package?

**Comment by etobia90** [comment]
XMR-Stak is not missing in version 1.8.1.6 release, that release uses XMR-Stak-CPU.

Version 1.8.2.0-Pre2 uses XMR-Stak.

**Comment by jojobg** [comment]
Yes, I'm sorry git hub release page mislead me. I'm closing the issue.
