### ISSUE TITLE
NHML EUR values all displaying as 0.00

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#852]
after update to 1.8.1.6 values dispaying 0 how to fix it help please

**Comment by riccardoruspoli** [comment]
At the moment the API that converts bitcoin to fiat is offline as tweeted by NiceHash. It’s temporary.

**Comment by ghost** [comment]
thanks 😀

**Comment by peteraclausen** [comment]
Interestingly enough, the bitcoin to fiat is working on the rigs I have not restarted yet.  It is only rigs that have recently been restarted that are not connecting to the API (in my case I'm showing USD).

**Comment by riccardoruspoli** [comment]
But I assume that the balance in fiat on the rigs you haven't restarted is stuck at some value, am I right?

**Comment by peteraclausen** [comment]
No, they are changing in real-time with the mBTC/Day values.   I have 10 rigs all running NHML and 9 are updating as they should.  Only the 1 miner I rebooted is showing 0.00 USD/Day.

**Comment by imrecsoka** [comment]
Oh okay , so it is fine to still go ahead and mine anyways?
I use an older version of nicehash.
I have issues using later versions because i never get proper speed with the later version of cryptonote miner  10.x Only 9.7 is proper for me, i am not being robbed for my speed.

**Comment by peteraclausen** [comment]
I would say so.  The rate in mBTC/day is working and when I check my stats on NH, I see that miner hashing away.

**Comment by imrecsoka** [comment]
Cool beans, its still broken looks like, I never thought Fiat was a good car anyways. I had a 2 door 128 1100.
I guess they good classic cars to have as are the old Alfas, like the Romeo GTV, Fiat 131 Abarth

**Comment by coinnoobsaver** [comment]
Hi there,
same problem w. 2 miner using the 1.8.1.6.
they show 0 fiat.
however no hashing on the web site, they look idle .
locally they are mining...looks like it is not only the fiat api to me.
is it worth mining?
will you give us an update when the api is settle?
thank you

**Comment by mittyredstar** [comment]
same error balance OK , but mBTC show only 0.00$ (2 workers active), help ?

**Comment by peteraclausen** [comment]
I stopped and started NHML on another rig, and both mBTC and USD are updating in real-time still.

So for me anyway, the issue appears isolated to a single rig.  Even rebooted that one rig, but it still does not show the USD, just the mBTC.  And I confirmed several times that I do see the hash posted on the online stats page.

Never had this issue with any of my rigs until today.  How odd.

**Comment by andersenbali** [comment]
Same issue. BTC balance ok. USD 0.00

**Comment by Linightz** [comment]
Same here.

**Comment by imrecsoka** [comment]
Still broken it seems no Fiat

**Comment by peteraclausen** [comment]
Working for me again this morning  on all my rigs.

**Comment by imrecsoka** [comment]
Hi, maybe it is where you stay , the fiat is working?

**Comment by dadoremix** [comment]
big deal for fiat ..
minig is working .. that is good

**Comment by imrecsoka** [comment]
yeh Fiat is good , just as long as you service it.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

We will be working on a complete GUI re-design.

Issue related to in-house or 3rd party API. We will show warnings in the new GUI
