### ISSUE TITLE
Equihash (OptiminerAMD) & CryptoNight (Claymore_old) - Terminated 

### ISSUE THREAD

**Issue by dobromir2** [nicehash/NiceHashMiner#853]
Hello everyone , 
  My system is not able to run those two benchmarks . And I am wondering is it a problem or it is normal ?

I am using :
OS : Windows 7 x64 SP1 and all current updates
NHML: 1.8.2.0-pre2
Radeon FE air : 17.Q4.1
CPU : i7-2600K
Ram: 32 GB DDR3 
Virtual memory : 64-128 GB

Can you please help figuring this out ? 

Thank you in advance ,
Dobromir

**Comment by S74nk0** [comment]
OptiminerAMD and CryptoNight are not relevant anymore
