### ISSUE TITLE
Cannot mine at all

### ISSUE THREAD

**Issue by Goorath** [nicehash/NiceHashMiner#854]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given
Hey lads, something's wrong because i cannot mine at single pool, and i tried them all.. Message in xmr-stak-cpu  SOCKET ERROR - RECEIVE error: StßvajÝcÝ p°ipojenÝ bylo vynucený ukonŔeno vzdßlenřm hostitelem   says, roughly translated - connection forced to terminate by remote host --- someone forcing mee to terminate connection???!!!!!!!
And GPU miner - cryptonight, claymore_old
Stratum - connecting to 'cryptonight.usa.nicehash.com' <169.62.79.78> port 33355 (SSL/TLS)
DevFee: Stratum - connecting to 'cryptonight.usa.nicehash.com' <169.62.79.78> port 33355 (SSL/TLS)
GPU0 t=31C fan=22%
Cannot establish SSL/TLS connection
Cannot establish SSL/TLS connection
Stratum - Cannot connect  to cryptonight.usa.nicehash.com port 33355
DevFee:  Stratum - Failed to connect, retry in 20 sec...
Stratum - Cannot connect  to cryptonight.usa.nicehash.com port 33355
 Stratum - Failed to connect, retry in 20 sec...

**Comment by Goorath** [comment]
Ok seems like problem solved by complete reinstall..

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Looks like ISP or backend issue. Probably not relevant to client
