### ISSUE TITLE
Cryptonight Sgminer 2 Amd Gpu error loop

### ISSUE THREAD

**Issue by midozido** [nicehash/NiceHashMiner#856]
hello
when Nicehash tries to mine Cryptonight using 2 of my Amd sapphire 570 4gb elbida Gpus keeps on loop starting sgminer.
it works fine on each individually 
how to solve this? 
![26829081_1748519142122119_1416269336_o](https://user-images.githubusercontent.com/35398714/34906237-fe407b42-f871-11e7-81aa-57e1dcbffd25.png)

**Comment by Stromwarrior** [comment]
I have same problem, any idea for solutions?

**Comment by HighwayStar** [comment]
Had same issue trying to start sgminer-sg from NiceHashLegacyMiner, trying to start sgminer-sg with same arguments (got from log) and found that it is issue with --worksize argument, when using like --worksize 4,4 it cant start as above, but changing to --worksize 4 starts and works fine (other arguments left unchanged like --rawintensity 512,512).

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Cryptonight is not seen as profitable anymore
