### ISSUE TITLE
R9 290X Dagger Lbry Problem

### ISSUE THREAD

**Issue by SNiCKeeRS** [nicehash/NiceHashMiner#857]
Hi everyone, as I mentioned in the title, the R9 290x is freezing after about 20 minutes when playing with my Dagger lbry mining with my 290x display card. Is this problem a problem or is it just me on my cards? In addition, although I do the maintenance of my graphics cards, it shows warming up to 85.86 degrees when I do lbry mining. I'm writing I'm using my english can be a little bad translation from turkey :) Thank you in advance for your interest.

**Comment by microtechies** [comment]
I'm having the same problem, any dagger or dagger duel mining using NHML with my r9 290x 
9 with AMD blockchain drivers after short space of time, Nicehash freezes and sometimes even Windows crashes

**Comment by microtechies** [comment]
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1689072/log.1.txt)
[logs.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1689073/logs.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Lbry is not seen as profitable on GPUs anymore.
Dual mining is not seen as profitable anymore.
