### ISSUE TITLE
Feature request: more miners should be offered

### ISSUE THREAD

**Issue by kangert** [nicehash/NiceHashMiner#858]
The legacy version should be for experienced users - add more miners to it, so users can choose the one, that works for them the best.

**hsrminer** - much faster than used ccminer for Neoscrypt

**dstm** (faster than excavator on Equihash) and **bminer** would be also great bonus

I understand the excavator is your child, however it isn't the best on the market sofar (certainly not for every configuration).

**Comment by S74nk0** [comment]
In the next upcoming release we will be adding external plugin support and the option to install them manually or via our service. 

![image](https://user-images.githubusercontent.com/1517233/60526201-24808f80-9cf0-11e9-8bef-ec1a7bc5f648.png)
