### ISSUE TITLE
Setting up miners - STUCK

### ISSUE THREAD

**Issue by whitechocwonderful** [nicehash/NiceHashMiner#859]
My miner was runnign smoothly for over 24 hours, then I noticed it wasn't getting any blocks. I restarted, and it always comes up with a message to hit Yes or No to restart the program to download some file or something. 

I restarted, but then as it was downloading and setting up miners, it got stuck at "Unzipping 31.46%" while "Setting up miners." I have ended the program using Task Manager multiple times, have deleted and re-unzipped the NHML folder, deleted the whole folder and redownloaded from GitHub, but it STILL gets stuck at 31.46%.

First image is the first error I mentioned, and the 2nd is where it gets stuck. Thanks for any help!

![capture](https://user-images.githubusercontent.com/35405795/34909101-293e9cec-f869-11e7-8baa-724a6d318bcd.PNG)

![capture2](https://user-images.githubusercontent.com/35405795/34909100-23c5fbf2-f869-11e7-8ca6-e6ac6cc9b15d.PNG)

EDIT: I have already gone through my anti-virus and added an exclusion for the NHLM folder but it doesn't change anything.

**Comment by riccardoruspoli** [comment]
As reported in the release:

> If autodownload fails, download the bin folders manually and unzip them to the directory

For now, go to the releases page, download the zips of the miners, and place them into the NHML folder, so you can start mining.

**Comment by luongk** [comment]
Also you probably want to whitelist the NHML directory in your antivirus program/Windows defender

**Comment by whitechocwonderful** [comment]
Thank you all! Got it working. I definitely should have thought about that. Thanks!

**Comment by ToyBoat123** [comment]
Wait how do I find the NHML folder to extract stuff to? Someone please help, I am confused.

**Comment by luongk** [comment]
It's wherever you unzipped the zip file to?

If you don't know where you installed it to, it might be worth considering using the non-legacy version.

**Comment by ToyBoat123** [comment]
Oh so like zipped file? I put the folders into it and I ran the program but still nothing the same problem.

**Comment by luongk** [comment]
It's difficult to work out what you've done wrong, but you need to extract the folder to the location of your choice, not open it as a zipped folder.

Additionally you probably need to whitelist the folder or otherwise exclude it from your antivirus program/MS security essentials.

**Comment by ToyBoat123** [comment]
I put the two folders into the NHML and ran the program and it didn't work. I also turned off my firewall. Am I doing something wrong?

**Comment by luongk** [comment]
Yes, you are doing something wrong.

Extract the NHML zip file to the location of your choice - if you don't have a dedicated zip program, you will need to open it in Windows, right click and "extract all". You then need to open the bin and bin 3rd party zip files, and extract them to the new NHML folder (not the zip file, which is what I suspect you have done). 

Then you will additionally need to whitelist that folder in MS security essentials, so that the antivirus doesn't detect/block/delete the miners.

**Comment by ToyBoat123** [comment]
I love you man Thank you so much!!!

**Comment by S74nk0** [comment]
AV issue.
