### ISSUE TITLE
Keccak Performance

### ISSUE THREAD

**Issue by aganorian** [nicehash/NiceHashMiner#86]
Hello, can you tell me the expected prformance of the Keccak  algo for the 1080ti?

I'm having less performance using it instead of other algo's. I'm getting around 1.38GH/s.
I cannot find the NVIDIA Inspector's Multi Display Power Saver option, only the MultiDisplay/Mixed-GPU Acceletarion. Is this the option?

**Comment by DillonN** [comment]
That's about what I get on 1080 Tis. Nv inspector is a third party took some people use to control GPUs

Keccak seemed to spike quite a bit, but it has gone down

**Comment by aganorian** [comment]
Great, now i know its a expected value :+1:
