### ISSUE TITLE
Cryptonight SgMiner

### ISSUE THREAD

**Issue by Goorath** [nicehash/NiceHashMiner#861]
Cryptonight SgMiner now does not work, in v.1.8.1.5 worked perfectly (even if I did not use him, mee have better results with Claymore cryptonight).. Benchmarked him several times, no success and i tried all benches (quick, stand., precise)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Issue not relevant anymore
