### ISSUE TITLE
Nice hash works and shows hash rate but minig is not in progress

### ISSUE THREAD

**Issue by LightscienceX** [nicehash/NiceHashMiner#863]
Hello!
I got the same issue 2 times in 4 days:
NiceHash software showed that mining is in progress, show hashrate
But statistics of the site showed that mining wasn't in progress

This occured 14 january 19:25 +4 tome zone
You can see it in statistics https://www.nicehash.com/miner/1XFKEQ5WLbTYxQnfRGFLKQKNhhMfqK3eK
Restart the mining solved this problem
Version was at first time 1.8.1.5 and 1.8.1.6 at second time

Please give an answer what happened and how to avoid this issue in feature

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1629641/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1629642/log.1.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
