### ISSUE TITLE
Included xmr-stak does not support compute 2.x Nvidia cards

### ISSUE THREAD

**Issue by numanair** [nicehash/NiceHashMiner#864]
I have a GTX 570 that the current release of xmr-stak works fine with. However, the version included with NHML does not seem to be compiled for Fermi cards. Directly replacing the xmr-stak files makes NHML unable to find the .exe.

**Comment by professor-jonny** [comment]
I don't think it is worth mining with that card unless you have free power the card is only cuda compute 2.1 5.0 is the minimum with nhm2.0

of note you just cant replace the miners as they have to pass checksum I believe.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

From now on we are only supporting SM3.0+. 
Your device is too old
