### ISSUE TITLE
Stuck in CCminer

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner#865]
Restart miner or pc if error like this is encountered.

![stuck ccminer](https://user-images.githubusercontent.com/15882196/34925631-8ab0cbe0-f9d0-11e7-8373-3644879dff0d.png)

**Comment by lug-gh** [comment]
start option: --no-cpu-verify

**Comment by nerdatwork** [comment]
I entered that in the extra parameters section of the CCminer algorithm inside NHML but it does not work :(
