### ISSUE TITLE
Included xmr-stak has no Vega Frontier Edition support

### ISSUE THREAD

**Issue by cuzner** [nicehash/NiceHashMiner#867]
Version of xmr-stak included in the latest NHML 1.8.2.0 Pre2 is an older version (2.0.0) that doesn't support Vega FE's (56s and 64s are supported).

Latest version (2.2.0) does support Vega Frontier Edition cards - https://github.com/fireice-uk/xmr-stak/releases

**Comment by lfarkas** [comment]
same as #797

could you please update to 2.2?
thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
