### ISSUE TITLE
Using more than 6 cores CPU

### ISSUE THREAD

**Issue by dok441** [nicehash/NiceHashMiner#870]
I wanted to know when will be able to use when mining, more than 6 cpu cores, I have 10 nuclear, but is used toleo 6 cores.

**Comment by dobromir2** [comment]
start 2 miners ;)

**Comment by dobromir2** [comment]
I start 1st with XmrStak and 2nd with Xmrig but this is on dual CPU, it might work on one CPU . Give it a try!

**Comment by dok441** [comment]
In my case there is a division profits, if 2 miner. Algorithm 1 only works 2 benchmark is not even. Writes constantly, time is up.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Check [wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Xmr-Stak)
