### ISSUE TITLE
tpruvot/ccminer has low NeoScrypt performance

### ISSUE THREAD

**Issue by borzaka** [nicehash/NiceHashMiner#871]
My rig: 3x 1080 Ti, 3x 1070 Ti
Setup: NHML 1.8.1.6, Windows 10 64 bit (Version 1703)

- tpruvot/ccminer **7,95 MH/s**
- [hsrminer](https://bitcointalk.org/index.php?topic=2565979.0) **10,17 MH/s**

Currently, I think this is the best NeoScrypt miner.

Quote from the author, palgin:
> Unfortunately, currently no API functional (it's present, but not operational at the moment), very poor control, I know. From vresion 1.1.x API will be fully functional.

I think it is worth to integrate after they done with the API.

**Comment by borzaka** [comment]
Alternate to tpruvot/ccminer for NeoScrypt:
- CcminerKlaust
- CcminerNanashi
- Excavator (!)

They are all faster, and have an API. They are good alternative until hsrminer comes with an API.

**Comment by wikimeza** [comment]
I agree, my 1060 3gb in NeoScrypt on NHML 1.8.1.8 does 680 kH/s, but on NHM2 with excavator 1.4.4 does 746 kH/s. Should be easier to port excavator to NHML since it is already in NHM2.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

NeoScrypt is removed
