### ISSUE TITLE
NiceHash Miner v2.0.1.8 stuck at Starting Excavator Server

### ISSUE THREAD

**Issue by PredatorAaron** [nicehash/NiceHashMiner#872]
I just update the NiceHash Miner an hour ago and after finish updating I wanted to open my app it just stucks at the "Starting Excavator Server" I've been waiting for an hour already, does anyone encounter this problem after updating to v2.0.1.8?

**Comment by Ru3MsS** [comment]
Same here, I didn't find a solution :(

**Comment by PredatorAaron** [comment]
Go to this thread, I guess it might help you, https://github.com/nicehash/excavator/issues/120

**Comment by Maeeen** [comment]
For me, disabling my antivirus solved the problem.

**Comment by S74nk0** [comment]
nhm2 discontinued client...

Not relevant to nhml/nhm1
