### ISSUE TITLE
Why not KlausT for Neo? 

### ISSUE THREAD

**Issue by xfactor8383** [nicehash/NiceHashMiner#873]
Why is KlaustT ccminer not included for at least NeoScrypt? Typically gives hash rates almost 20% greater than the current miner Tpruvot?

**Comment by pjdouillard** [comment]
I concur!

**Comment by kaos-1** [comment]
you can update youself just replace the tpurvot with klaust it works just fine

**Comment by professor-jonny** [comment]
I can confirm it is quicker for me also.

**Comment by kyotolover** [comment]
When I switch tpurvots version out and my miner want to use klaust for skunk it just closes. Is there a possibility to choose a seperate miner for neo without replacing the whole exe file?

**Comment by kaos-1** [comment]
In that case you can just edit the ccminer path to neoscript and make a new folder in /bin
the file you want to edit the path to miner is in /internals/ file name is minerpathpackageXX.json

**Comment by plentilha** [comment]
I didnt understand How to add klaust ccminer to nicehash, can someone explain for a newbie?

**Comment by fdoving** [comment]
Get new ccminer_klaust and replace the version in "bin\ccminer_klaust" (i think 8.18 is the one with faster neo?)
- This path is relative to your root installation of Nicehash Miner legacy

Then edit "internals\MinerPathPackage_NVIDIA_6_x.json" and "internals\MinerPathPackage_NVIDIA_6_x.json"

Changing the path in the NeoScrypt sections to point to ccminer_klaust like this:
{
          "Name": "NeoScrypt",
          "Algorithm": 8,
          "Path": "bin\\ccminer_klaust\\ccminer.exe"
        },

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

NeoScrypt is not seen as profitable anymore
