### ISSUE TITLE
NHML wont start

### ISSUE THREAD

**Issue by Bennibulldog** [nicehash/NiceHashMiner#875]
I am trying to run NHML, but every time I try to open it the wheel starts spinning but stops and nothing happens. There is no Error message, the .exe is in the folder, I have downloaded previous packs but nothing seems to work. 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1636743/log.txt)

**Comment by Millerboy** [comment]
I have the same problem! Frustrating because it worked for me the first time, then it wouldn't open after I closed it once.

**Comment by nadavasan** [comment]
Even I have the same issue. Any solution for it??

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
