### ISSUE TITLE
Curent .8 release looses current benchmark data during benchmarks

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#876]
I'm trying to run a clean benchmark on .8 but there's apparently at least one that crashes my pc and leaves any completed ones before it in the trash and not being recorded. Is there any way to have successful benchmarks being done  to be written to some other file so they don't get wiped every time.

BTW when I figure out which ones causing me pain I will post another issue and hope its something to fix in .8.1 or prerelease 3 [since its not mentioned in this release and multiple benchmark available in prerelease 2 make this twice as exciting].

Thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
