### ISSUE TITLE
Computer seems to benchmark lower each time I run benchmark test..

### ISSUE THREAD

**Issue by HardKnox30** [nicehash/NiceHashMiner#877]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by Nicheuji** [comment]
Haven't you been observing the value of btc for the past few weeks? Just last week it was around $14k. Today it's around $10k. Almost all altcoins are also dropping in value.

**Comment by dadoremix** [comment]
change title .. please !

**Comment by HardKnox30** [comment]
I did notice that the value has dropped and that is part of what I was initially seeing. However each time I run the benchmark test the values that report back drop just a little each time.... Any ideas?  

Sorry about the tittle. Typed in the wrong area. Should be corrected now.

**Comment by dadoremix** [comment]
that normal ..
you only watch mh/s for benchmark and btc/day
ratio is variable  .. because btc is going up or down at market
