### ISSUE TITLE
AMD RX 570 

### ISSUE THREAD

**Issue by Norlpz** [nicehash/NiceHashMiner#878]
I am trying to use two rig with 5 radeon rx570 each but the NHM Legacy v1.8.1.6 does not complete the process in benchmark and I wish to be able to mine with the equihash or daggerhashimoto algorithm but not configure the rig. I hope you can help me, thanks

**Comment by stresskiller** [comment]
get the new 18.1.1 drivers from AMD

**Comment by Norlpz** [comment]
with v18.1.1 get 17Mh/s. RX570 has 21-23 without OC

**Comment by stresskiller** [comment]
there are older beta drivers from AMD specific released for miners somewhere in august if i remember correctly , but they suck when you start gaming again on your pc

**Comment by stresskiller** [comment]
found the link  :  http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-Beta-for-Blockchain-Compute-Release-Notes.aspx

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
