### ISSUE TITLE
Internal server error code -1

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#879]
![15161913111621402378688](https://user-images.githubusercontent.com/33842056/35042332-f0cbb3d8-fb90-11e7-8c38-681bc0d61ebe.jpg)

**Comment by ghost** [comment]
what is this anyone can help me ??

**Comment by lilok** [comment]
Hello,

i'm experiencing this problem too, may someone give a feedback about this?

Thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

NeoScrypt is not seen as profitable anymore.

Backend issue
