### ISSUE TITLE
Idle state mining when multiple accounts are being used.

### ISSUE THREAD

**Issue by utc99** [nicehash/NiceHashMiner#88]
I have an issue with idle state mining. This could count as improvement i guess if it could be implemented, or at least an instruction or help with code that need to be changed of how could i achieve this on my local version, not on the NHML release.

I run NHML from one account, which i guess has all the privileges, LocalSystem, and I want that it would run only, when no other user on computer is working, yet it sees that the instance/user/session that ran it, is idle all the time, and miners run all the time. Idle mining does not work. Which leads to lags if another user starts using PC. Autostart mining is off, start mining when idle is on.

I know that's not the first importance issue of the app, but perhaps you will find some time and interest to look at it @DillonN , that would really help.

GetLastInputInfo is useful for input idle detection. However, GetLastInputInfo does not provide **system-wide user** input information across all running sessions. Rather, GetLastInputInfo provides session-specific user input information for only the session that invoked the function.

**Comment by DillonN** [comment]
Thanks for the suggestion @utc99, I will look into this in the future it sounds like a useful feature.

**Comment by DillonN** [comment]
This unfortunately does not seem something that could reasonably be implemented
