### ISSUE TITLE
i7-4790 CPU Cryptonight "All pools are dead" NHM 1.8.2-Pre2

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner#880]
![image](https://user-images.githubusercontent.com/24593637/35096190-52d1e2e8-fc5c-11e7-8b25-2a935dc4baea.png)

**Comment by Nicheuji** [comment]
Have you tried connecting to other regions?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Cryptonight is not seen as profitable anymore
