### ISSUE TITLE
AMD from * .bat file

### ISSUE THREAD

**Issue by zmejskij** [nicehash/NiceHashMiner#881]
**It is for NVIDIA:**
set nvidia_smi="C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi"
for /F %%p in ('%nvidia_smi% --id^=0 --query-gpu^=utilization.gpu --format^=csv^,noheader^,nounits') do set gpu_usage0=%%p
for /F %%p in ('%nvidia_smi% --id^=0 --query-gpu^=power.draw --format^=csv^,noheader^,nounits') do set power_draw0=%%p
for /F %%p in ('%nvidia_smi% --id^=0 --query-gpu^=fan.speed --format^=csv^,noheader^,nounits') do set fan_speed0=%%p
for /F %%p in ('%nvidia_smi% --id^=0 --query-gpu^=memory.used --format^=csv^,noheader^,nounits') do set memory_used0=%%p
for /F %%p in ('%nvidia_smi% --id^=0 --query-gpu^=memory.total --format^=csv^,noheader^,nounits') do set memory_total0=%%p
for /F %%p in ('%nvidia_smi% --id^=0 --query-gpu^=pcie.link.gen.current --format^=csv^,noheader^,nounits') do set pcie_gen_current0=%%p
for /F %%p in ('%nvidia_smi% --id^=0 --query-gpu^=pcie.link.width.current --format^=csv^,noheader^,nounits') do set pcie_width_current0=%%p
for /F %%p in ('%nvidia_smi% --id^=0 --query-gpu^=temperature.gpu --format^=csv^,noheader^,nounits') do set temperature_gpu0=%%p
**How it made for AMD?**

**Comment by S74nk0** [comment]
Issue not related to nhm/nhml client.

I don't believe AMD has such a tool on Windows. I think they have this only for Linux
