### ISSUE TITLE
gpu efficiency of 0 please help me

### ISSUE THREAD

**Issue by kna1105** [nicehash/NiceHashMiner#882]
Program to detect the video card, but the performance is 0, I am using the amd 570, please help me

The version I use is 1.8.2.0 Pre-release 2

But using Claymore is normal

**Comment by zmejskij** [comment]
Equihash....
https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.8.1.6/NHML-1.8.1.6.zip

**Comment by kna1105** [comment]
thx but.... @ #
![default](https://user-images.githubusercontent.com/35611511/35186891-a6344e0c-fe56-11e7-8c00-0dfedb1cbfa7.jpg)
.... help. me. more. plz....

**Comment by zmejskij** [comment]
![snap_2018 01 21 00 11 04_001](https://user-images.githubusercontent.com/24373914/35188083-81d993c0-fe40-11e7-8912-8a04e8826e6b.png)

**Comment by kna1105** [comment]
![26814522_10210619723560426_1700409567799443070_n](https://user-images.githubusercontent.com/35611511/35188260-330041e0-fe6d-11e7-8394-1d233b720539.jpg)
n fact, using any algorithm can not be effective, except using other software, such as claymore ...
But I know what I need is "nicehash" to work for me
Perhaps other problems?
like this↓↓↓↓↓
![19554972_10210619723720430_4057249764366454280_n](https://user-images.githubusercontent.com/35611511/35188258-2fc1361a-fe6d-11e7-9745-977f61b9fe73.jpg)

**Comment by zmejskij** [comment]
Disable CPU of minig...

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
