### ISSUE TITLE
No 'Nicehashlegacyminer.exe' file to run

### ISSUE THREAD

**Issue by rf9661** [nicehash/NiceHashMiner#884]
Hello,

I'm trying to install NiceHashLegacyMiner. When I downloaded it, I opened the folder titled 'NHML-1.8.1.6.zip', I then opened 'Get_started.pdf' which said to run 'Nicehashminer.exe' but I don't find that file anywhere in the download. What I did find was 'Nicehashlegacyminer.exe'. When I double-click it and click 'Run', nothing happens. Any help?

By the way, I am running Windows 10 (64-bit) with 2 GTX 970s in SLI.

**Comment by JS-88** [comment]
Something similar happened to me, but it was my anti virus software deleting it everytime I unzipped the folder. Not sure if this is the case with you.

**Comment by phich65** [comment]
Same happens to me with McAfee Total Protection (2018) when I try to run "NHML-1.8.1.9" - it quarantines the EXE, saying that there's a suspected virus. 

Gives me a link to 'Suspect!c20c98c70694' on the McAfee web-site - but it's no help, as the link is broken

Any ideas?
Cheers
fish

Win10 Pro 64-bit
Ryzen 5-1600
Dual GTX550Ti in SLI

NiceHash Miner 2.0.1.11 running fine on processor only, was hoping to get the GPUs going as well...

**Comment by phich65** [comment]
okay fixed - finally found how to add an exception to McAfee Total Protection :-)

**Comment by S74nk0** [comment]
AV issue
