### ISSUE TITLE
NHML 1.8.2.0-pre2, low virtual mem warning at start despite of 128GB virt mem

### ISSUE THREAD

**Issue by lubomirmatus** [nicehash/NiceHashMiner#887]
NHML 1.8.2.0-pre2, 8x GTX 1080 Ti (11GB).
NHML is always displaying warning about low virtual memory settings despite I have set max virtual mem limit to 128GB (and during mining reached real size 77GB+). The warning is displayed at NHML start and need to be closed by click to OK, that breaks automatic starting and mining at system startup.

**Comment by raghuariga** [comment]
Hi,
Try using following link for increasing Virtual memory

http://www.x-plane.com/kb/increasing-virtual-memory-on-windows/

Also, check this link

https://social.technet.microsoft.com/Forums/en-US/82fd5a8c-4a6f-4855-95c7-965f5b45c95c/adjust-virtual-memory-paging-file-size?forum=mdt

thanks,
Raghu

**Comment by lubomirmatus** [comment]
Hi Raghu,
Thanks for answer.
I have already set vm size manually to range 16GB-128GB. I have no problems running algos, also dagger-hashimoto with high mem consumption (real used vm size 77GB+).
The problem is NHML warning dialog. Maybe would be fine to check virt mem system settings and determine max value instead of checking just actual value.
Or just add special window to NHML, the 'Log' window, where all errors, warnings, infos and messages will be shown, without need for user interaction.

**Comment by Simaex** [comment]
Hi @lubomirmatus 
Usually for mining in windows virtual memory should be set to the total amount of video memory of all GPU installed in your system to be on the safe side. In your case just use 88 Gb pagefile. For some reason automatic settingth "from ... to ..." do not work in some situations that's the reason for the warning. No need to say that it is not a NHML problem but a Winndows problem, large pagefile is not actually used but is needed for miner initialisation.
