### ISSUE TITLE
NHML 1.8.2.0-pre2, all algos disabled after benchamarks

### ISSUE THREAD

**Issue by lubomirmatus** [nicehash/NiceHashMiner#888]
NHML 1.8.2.0-pre2.
I have run the gpu benchmarks and want to start mining after. All algos on all gpus have deselected somehow, then warning dialog pops up before mining and waits to click.

I would like to point that there is too much warnings and other dialog boxes in NHML that are usually causing problems with automation and autostart mining after system start.
My lastest case was that I have run benchmarks that is taking too long, I have checked that start mining after benchmarks, and went to work. The mining did not start because of some dialog box asking about another benchmarks (unbechmarked algos), and waited all day on this dialog.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
