### ISSUE TITLE
AMD Nist5 Algo

### ISSUE THREAD

**Issue by francescocmazza** [nicehash/NiceHashMiner#889]
Hi,
I noted that Nist5 algo for Nvidia yields very good results. Why is there no Nist5 miner for AMD cards in Nicehash miner?
Can you please add that in the next release?

Thanks!

**Comment by nerdatwork** [comment]
Not all algorithms run on all cards. AMD cards are good for some algorithms and Nvidia cards are good for some. Just run a benchmark on all and see for yourself. Just because Nist is giving more money on Nvidia does NOT mean it will give more money or same money on AMD.

**Comment by francescocmazza** [comment]
Hello Nerd,
I know, the thing is that there is no algo to benchmark AMD cards on NIST. I think it could be helpful. Maybe most of the time it won't be as profitable as other algos on AMD cards, but still it would be nice to be able to have it run if Nist market prices on nicehash should rise.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Nist5 is not seen as profitable anymore
