### ISSUE TITLE
Missing translation for Retry & Cancel buttons in FormBenchmark_Benchmark_Finish_Fail_MsgBox_Msg

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#89]
1) Start benchmark
2) Benchmark should be finished with fail for some algorithms
3) "FormBenchmark_Benchmark_Finish_Fail_MsgBox_Msg" window appears

Result: There is no translation for 'Retry' & 'Cancel' buttons
![image](https://user-images.githubusercontent.com/4707112/28708021-9a50b5c2-738b-11e7-8405-d91bc71894f4.png)

There are no source strings for those buttons in *en.lang*.

**Comment by DillonN** [comment]
Thanks for pointing this out, I will look into it

**Comment by DillonN** [comment]
@adem4ik, this is added in commit acd6f9d3931105ab5ac1239c567add49268b0194. Please not the '&' character, which denotes which letter will be the keyboard shortcut when ALT is pressed (the buttons should all have different shortcut letters)

**Comment by adem4ik** [comment]
The issue is fixed! thanks @DillonN
