### ISSUE TITLE
3ddb0e435abc43a82445ff0d5a8ae213102e1a524ac0b47ab9e1e6811372948c

### ISSUE THREAD

**Issue by SILEVR** [nicehash/NiceHashMiner#890]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by nerdatwork** [comment]
try www.translate.google.com and post your question.
