### ISSUE TITLE
Problem with 3rdparty claymore

### ISSUE THREAD

**Issue by slayer26** [nicehash/NiceHashMiner#894]
Hello I'm having a problem with the NHL Application 1.8.6 I simply make beckmark accurate and it always gives me error when doing it in Claymore miners ... is there any way around this
![erro](https://user-images.githubusercontent.com/35696236/35227557-92323732-ff75-11e7-8c4a-ac90fec7d454.png)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
