### ISSUE TITLE
Pls. change neoscrypt miner to klaust 

### ISSUE THREAD

**Issue by RfoRfoRfo** [nicehash/NiceHashMiner#895]
hi. can u add a ccminerklaust8.18_8_64 for neoscrypt hi have good hashrate beter than curent miner in nhml 1.8.1.6 . :) on gtx 1070 and 1080

**Comment by moonoiza** [comment]
Klaust's ccminer has already included in NHML but it's not a default miner for NeoScrypt.
Just edit MinerPathPackage_NVIDIA_6_x.json in "internals" folder.

          "Name": "NeoScrypt",
          "Algorithm": 8,
          "Path": "bin\\**ccminer_klaust**\\ccminer.exe"

**Comment by RfoRfoRfo** [comment]
where i can change def intensity ccminer from 15.250 to higher

**Comment by moonoiza** [comment]
You can see ExtraParameters in settings page.

**Comment by kaos-1** [comment]
Klaust is the best, gives 1200 on 1070.  1350 on 1070 ti. Needs some tunning.

![klaust neo](https://user-images.githubusercontent.com/34693864/35481302-46f67e9e-0421-11e8-8118-a06e1b1edc58.png)

**Comment by RfoRfoRfo** [comment]
nice...   
What are your settings ..? and ver klaus t ccminer. / driver ver/ oc.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

NeoScrypt is not seen as profitable anymore
