### ISSUE TITLE
hsrminer for Neoscrypt

### ISSUE THREAD

**Issue by thel3lue** [nicehash/NiceHashMiner#896]
Can add hsrminer for Neoscrypt?
https://bitcointalk.org/index.php?topic=2565979.0
this miner can get more speed on Neoscrypt
@DillonN

**Comment by Krassikn** [comment]
Yes, DillonN, pleeese!!!

**Comment by RfoRfoRfo** [comment]
hsr have sometime long time freez , and manualy restart req. its not stable

**Comment by nerdatwork** [comment]
Agree with @RfoRfoRfo I didnt see it give out shares as fast as ccminer

**Comment by borzaka** [comment]
#871

Quote from the author, palgin:
> Unfortunately, currently no API functional (it's present, but not operational at the moment), very poor control, I know. From vresion 1.1.x API will be fully functional.

If no API, than NiceHashMinerLegacy can't read the hash values out from the miner.

**Comment by lukasmagi** [comment]
Hello Miners,
It works with NH miner, but it need some tweaks 👍 

1.) i tested it on 1.8.2.0 Pre2 - colse miner
2.) open Nh miner folder/bin and create new folder "hsrminer" and put hsrminer.exe file inside
3.) open Nh miner folder/internals & edit Nvidia 5.x and Nvidia 6x with plain text editor
     on neoscript (algo8) change path to new "hsrminer"
4.) open Nh miner folder/configs edit general.json with plain text editor 
     "ApiBindPortPoolStart": 4000,  - change it to 4001

now its done - I not recommned benchmark many time it show only 88H/s  beter to run with manual edit of hashing speed, then apply correct spped after few min. of run
It can realy add 20-30% on my 1080 TI rigs

There is one issue witch i need help hsrminer have only api port on 4001, but NH miner some times open next on 4002,4003 etc - restart miner help & auto restart work too, but ut teak some time :(

@DillonN please it is posible to set api port to permanent ? 4001

any donation is welcome

BTC : 1GjA4uh6TQTWESfyC69dNKXpV5UPKeXoZ4
ETH : 0xa6f2bcf1e75d0b99f874fbb1cabcf727bebedf45
ZEC : t1Y7E4c4va72Kr1Gvj7BSCMbdZK1kA9aNU6

**Comment by xberg** [comment]
Thanks Lukasmagi,
I was not able to install hsrminer on nicehash following your instructions.

EDIT: I now understand the instructions : I should not have added lines into nvidia5.x / 6.x but simply replaced the path. 
Problem: when hsrminer starts there are 2 errors:
unknown options algo=neoscrypt and api-bind=4000
Also hsrminer stops working after a minute or 2...

**Comment by lukasmagi** [comment]
Hi there, 
@xberg - Algo error its ok, but api-bind need be on port 4001 please check general.json (my step 4)
error still presist but you need see there 4001 (if you editing it, miner must be clossed !)

![image](https://user-images.githubusercontent.com/29143672/35346247-03fc949e-0132-11e8-8ab3-1dc947d03cba.png)

**Comment by xberg** [comment]
@lukasmagi Yes: you are right. Thank you and congratulations on being the first (and only) to offer this tutorial. I indeed forgot the port 4001.
Now I have exactly the same screen as you do: thanks!

However:
- in Nicehash the value never seems to move: it's been fixed for the last 10 minutes at 1.010 MH/s on a GTX 1080 (stock)
- Checking the stats in Nicehash I only achieve 0.89 MH/s there. So even less than displayed in the Nicehash app.
- same performance as Neoscrypt I was using before. Not the 30% boost that some people talk about

**Comment by lukasmagi** [comment]
@xberg Hmm interesting ...your hash rate is wery low  there is my resunts : 

1050TI 4GB      ccminer....0.340MH/s            hsrminer....0.490MH/s
1060 3GB         ccminer....0.590MH/s            hsrminer....0.790MH/s
1070 8GB         ccminer....0.970MH/s            hsrminer....1.190MH/s
1080TI 11GB    ccminer....1.440MH/s            hsrminer....1.898MH/s

**Comment by xberg** [comment]
@lukasmagi Lucky you :) 
My version of hsrminer also takes about a minute to start reporting anything to nicehash and crashes quite often (about every 10 minutes) and brings little tangible benefit over ccminer. So I'll wait for the next version :)
But thanks for the great help - much appreciated.

**Comment by kiriman** [comment]
@lukasmagi thanks for tutorial.
Try to bind port for hsrminer in file: config/MinerReservedPorts.json
"bin\\hsrminer\\hsrminer_neoscrypt.exe": { "NeoScrypt": [ 4001,4002,4003 ] }

"ApiBindPortPoolStart": 4000 - is default port for all miners
https://github.com/nicehash/NiceHashMiner/wiki/Reserving-API-bind-ports-(Advanced)

**Comment by dbhuyan** [comment]
Got hsrminer working (without any issues) with NHL 1.8.1.8 (latest version) on my two GPU test rig setup (Nvidia 1070).

Here's what I did ...

First follow the following two steps suggested by lukasmagi -
STEP (1) Open NHL miner folder/bin folder and create a new folder "hsrminer". Put hsrminer_neoscrypt.exe in this new folder.

STEP (2) Open NHL miner folder/internals folder and edit the Nvidia 5_x and Nvidia 6_x MinerPathPackage json files with a plain text editor and change the miner for NeoScript (algo8) to "bin\\hsrminer\\hsrminer_neoscrypt.exe".

The final step is to follow what kiriman suggested (hsrminer is listening on port 4001 and NHL needs to use this port to get hash rate etc.) -

STEP (3) Open NHL miner folder/config folder and edit the MinerReservedPorts.json file with a plain text editor as follows .... add the following inside ccminer ()

"bin\hsrminer\hsrminer_neoscrypt.exe":  {
       "NeoScrypt": [ 4001 ] 
},


That's it ....

**Comment by wikimeza** [comment]
My 1060 3gb in NeoScrypt on NHML 1.8.1.8 does 680 kH/s, but on NHM2 with excavator 1.4.4 does 746 kH/s. Should be easier to port excavator to NHML since it is already in NHM2.

**Comment by wikimeza** [comment]
Ok, I have given a try to the hsrminer on NHML and I can also confirm that it works, of course after the tweaks, it takes maybe almost a minute to start reporting the hashrate, my 1060 3GB went from 680 kH/s to 786 kH/s so it is a great boost. I have found a daggerhashimoto miner that increases my hashrate from 22.6 to 25, it is called goobur https://github.com/goobur/ethminer-cm/releases, I tested and it works in nicehash pool, but I was wondering how to make it work in NHML, I mean if I can make it work like hsrminer with some tweaks, I appreciate any insight

**Comment by borzaka** [comment]
You can use [hsrm-fork](https://github.com/justaminer/hsrm-fork) to replace Ccminer Klaust in NHML. You don't have to tweek, just replace the .exe:

> ~ Full compatibility with NiceHashMinerLegacy - miner now passes all types of benchmark: quick, standart and precise. You can use it with NHML instead of Ccminer Klaust for example: exit from NHML, go to your NHML folder, \bin\ccminer_klaust\ , delete ccminer.exe, put hsrminer_neoscrypt_fork.exe or hsrminer_neoscrypt_fork_hp.exe there and rename it to ccminer.exe .You can also put there msvcr120.dll from hsrminer_neoscrypt_fork.zip archive.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

NeoScrypt is not seen as profitable anymore
