### ISSUE TITLE
nicehash 2.0.1.8 still have the cmd window which shows you hashing rate when using ALT/ H and other Command lines, this version only shows the CMD excavator window for some reason ? 

### ISSUE THREAD

**Issue by XTFALCON** [nicehash/NiceHashMiner#897]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by XTFALCON** [comment]
nicehash 2.0.1.8 the cmd window which shows you hashing rate when using ALT/ H and other Command lines,will not popup when running nicehash why?

**Comment by nerdatwork** [comment]
Dude this is only about Legacy miner issues

**Comment by XTFALCON** [comment]
i ask a simple question regarding a problem i am having with a console window that fails to open &  Nicehash support HANDBALLS ME here ?

**Comment by Simaex** [comment]
@XTFALCON NiceHash Miner Legacy is a separate project from NiceHash Miner 2.xx
No use to ask anything about it in the thread if you really want an answer.

**Comment by Braintelligence** [comment]
@XTFALCON First of all @nerdatwork is not part of the "Nicehash support" but just another dude like you and me trying to point out, that you're in a totally wrong GitHub repo asking questions about something that nobody can you help you with on here and you get all high and mighty? Stop acting so entitled, please...

**Comment by XTFALCON** [comment]
high and mighty? what... all i said.. i was sent here by Nicehash support, if nobody can help me that's fine, i didn't come here to cause problems and i am not acting like someone owes me something. i repeat i ask Nicehash support a simple question and they send me here, that's all meant !

**Comment by Braintelligence** [comment]
@XTFALCON I doubt NiceHash support has sent you to this very repo if you told them that you had problems with the NiceHash Miner (and not NiceHash Miner Legacy). If they did, then it was a mistake and you should visit the NiceHash Miner GitHub repo.

**Comment by XTFALCON** [comment]
o.k no problems !

**Comment by S74nk0** [comment]
nhm2 is discontinued client...

Issue is not related to nhml/nhm1
