### ISSUE TITLE
NiceHashMiner Start - Hang on Getting NiceHash SMA information - then says no internet

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#9]
So I ran the NiceHashMiner for first time, agreed and accepted all the biner downloads, on launch it says 

Getting NiceHash Miner SMA Information...hangs then says no internet connection (there is internet can browse google and other sites)

![image](https://user-images.githubusercontent.com/19168174/28146172-cd860cfa-6745-11e7-8367-ff75f1808502.png)

What are/is the api call(s) it does?  Can manually test through web browser on my end to see if NiceHash hates me or something else :)

**Comment by billmcilhargey** [comment]
Hmm closing for now, restarted the computer (go figure) seems to be solid now - false alarm?

**Comment by Alexmarch1** [comment]
Constant such problem

**Comment by vadeem** [comment]
Same for me. Two rigs - both Win10 x64, different cards - on loadin Nicehash SMA  - connection error, cant get profitability info.
Before updading to 1.8.15 everything worked fine.

as temporal decision - start as local administrator - but this is not Ok.

**Comment by Alexmarch1** [comment]
Disable the IP v6 protocol in the network configuration. 100% working

**Comment by evlogiy** [comment]
Nope. Doesn't work for me.

**Comment by ekadanthcomputers** [comment]
I have 5 rigs and I was faced with this issue too. I deleted nicehash, cleared cache and had to benchmark one of my rigs all again but this did not resolve the issue. I tried the step with disabling IPv6 to no avail. I turned off all my rigs. Switched on one and changed the 'Service Location' and 'Currency' (in settings) on  the NiceHash Miner. This resolved the issue for me. All my rigs are working again.
Please let me know if this works for you.
