### ISSUE TITLE
1.8.2 pre 2 EU server issue

### ISSUE THREAD

**Issue by aminlv** [nicehash/NiceHashMiner#900]
Hi guys,
got lil bit issue i can't figure it out how to fix it,
appreciate any insight
for some reason i can't connect to EU server at all
here is my tracert to Eu server i hope it helps

thanks for your help in advance

1     1 ms    <1 ms    <1 ms  192.168.1.1 
  2     *        *        *     Request timed out.
  3    25 ms    29 ms    24 ms  10.101.96.89 
  4     *        *        *     Request timed out.
  5    30 ms    31 ms    24 ms  10.101.96.50 
  6    43 ms    59 ms    24 ms  78.38.250.25 
  7    31 ms    29 ms    29 ms  10.201.147.18 
  8    43 ms    24 ms    28 ms  10.201.42.148 
  9    28 ms    27 ms    30 ms  10.201.177.126 
 10    25 ms    27 ms    25 ms  10.201.147.242 
 11   113 ms   104 ms   104 ms  ffm-b1-link.telia.net [62.115.155.236] 
 12   102 ms   100 ms    99 ms  ffm-bb3-link.telia.net [62.115.121.2] 
 13   121 ms   104 ms   101 ms  ffm-b12-link.telia.net [62.115.142.43] 
 14   112 ms   103 ms   102 ms  xe-1-0-1.bbr01.xn01.fra01.networklayer.com [80.239.160.70] 
 15   101 ms     *      117 ms  ae5.cbs02.xn01.fra01.networklayer.com [169.45.18.170] 
 16     *        *      142 ms  ae0.cbs01.eq01.ams02.networklayer.com [169.45.19.122] 
 17   125 ms   110 ms   104 ms  97.12.2da9.ip4.static.sl-reverse.com [169.45.18.151] 
 18   147 ms   115 ms   113 ms  ae5.dar01.sr01.ams01.networklayer.com [50.97.18.237] 
 19   119 ms   115 ms   115 ms  po1.fcr02.ams01.networklayer.com [159.253.158.149] 
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out

**Comment by S74nk0** [comment]
Temporary backend service issue. Not related to client
