### ISSUE TITLE
Distributable NH Miner?

### ISSUE THREAD

**Issue by AdamZWinter** [nicehash/NiceHashMiner#902]
Hello,
I was told by Nicehash support to contact you here:

I'm developing a standalone miner (hardware appliance/device) that is plug-and-play.  That is, the customer will simply plug it in and turn it on and it will start mining [the coin of their choice].  They will register and view stats etc online.  It would be nice if the product had the ability to just run Nicehash instead of having to pick a particular coin/algorithm.  So.....

Do you have a Linux version of Nicehash?  If so, is it distributable?  If so, can you direct me to it and the literature explicitly allowing for distribution?

I'm hoping not to have to do this trick I once saw where they asked the user, after installation, if they "want to download third party software.......".   =)

**Comment by luongk** [comment]
There isn't a Linux version.  I find it amusing that Nicehash support directed you here...

**Comment by AdamZWinter** [comment]
What should they have done?

Is the Windows NH miner as it stands distributable?  I can't see why NH wouldn't want more people using it but....

**Comment by luongk** [comment]
This isn't really an official Nicehash forum, the owner of the git has an agreement with Nicehash, but that's about it.

**Comment by AdamZWinter** [comment]
HA!  That is funny!

But, this is still the official git for Nicehash?  Did the owner just stake out the name or was this the original git for the original (legacy) miner?

Is there not any development going on here?

Thanks

**Comment by luongk** [comment]
DillonN forked the original Nicehash repository to add some additional optimisations/miners, this is a mirror of that fork. It is sanctioned by Nicehash to some degree but by no means is it official/do nicehash employees participate

**Comment by AdamZWinter** [comment]
So, this is just as good as using the other one, or better?  What's the difference?  I take it that the program just uses the web API for data then?

What's the benefit to you or the owner of this version/git in doing this?

**Comment by luongk** [comment]
Nicehash Official are working on the 2.x version, which is designed to defeat anti-virus detection at the expense of hashrate/algorithms.  

This is a fork of the original Nicehash miner (1.x), and has more algorithms and is generally better optimised, but marginally less easy to set up.   

I suspect DillonN has some sort of deal with Nicehash, but the general benefit is it's good for the community.

**Comment by AdamZWinter** [comment]
How do I contact the people who control the Nicehash API?  They've messed something up, but Nicehash support doesn't know anything about stuff that technical.  Is there a Github for the official tech team?

btw, the Nicehash website still links to this Git for the legacy version.
