### ISSUE TITLE
Issue with benchmarking algorithms in legacy miner

### ISSUE THREAD

**Issue by Ironmanjr** [nicehash/NiceHashMiner#903]
when i am benchmarking some algorithms i am having some problem when i am trying to benchmark cryptonight algorithm i am havin error " Amd hsa code object loading failed". When i am benchmarking equihash i am having error "terminated". when i am benchmarking ethash i am having error "precisely failed". I am using 4 cards Which are GIgabyte vega 56 OC edition. The drivers which i am using are blockchain drivers and i did switch to 18.1.1 adrenaline  driver but i am still having the same error.

please help me

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
