### ISSUE TITLE
Legacy v1.8.1.6 ethminer.exe continues to 'disconnect' / stopping farm / established connection was aborted by the software in your machine

### ISSUE THREAD

**Issue by dwalker6696** [nicehash/NiceHashMiner#905]
I'm running a Gen 7 celeron on Asrock H110 pro btc / 4gb of ram / 120gb ssd / win 10 - (7 Asus gtx 1060 6gb / 3 Asus gtx 1060 3gb and 1 Asus Rog Strix 1070 8gb (about to be 2)- My miners have always ran fine until 1.8.1.6 and now the ethminer closes connections and sits holding = meanwhile my earnings are low considering the general performance (i understand bitcoin is low but still rather low)-
I also get a message of 'nicehash recommends raising virtual memory" but my virtual memory is already set to 64000- i thought this was addequate - also i received an odd driver message the other day but not received lately - all drivers are latest and have been seeming to run fine until these- Thanks in advance for any help, everything has generally been pretty clean running since your return and thanks for all the support!!!!
[nicehash log file.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1659825/nicehash.log.file.txt)
![error photo](https://user-images.githubusercontent.com/35767659/35332728-016920f6-00da-11e8-9749-09146e254f5e.jpg)

**Comment by dwalker6696** [comment]
Also i should add- only 8 cards are pointed to CC miner and only 8 to claymore ( i was not sure of a limit so i did this just to be sure - ) If i'm doing something wrong please let me know! Thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
