### ISSUE TITLE
Best miners for each algo?

### ISSUE THREAD

**Issue by angriest** [nicehash/NiceHashMiner#907]
I've figured out that KlausT outperforms Tpruvot for Neoscrypt algorithm. Has anyone explored which other algos will perform better than the default ones for other algorithms?

I'm using NHML 1.8.2.0 Pre2.

4790k
1080 Ti
1070 x2

**Comment by angriest** [comment]
In addition: is it possible to set a miner per gpu? klaust seems to work bestfor my 1070's but way worse for my 1080 Ti.

**Comment by SK-Crow** [comment]
Best algorithm will vary depending on who's paying the most for what algorithm.  I leave all of them on on legacy for my 960, 1060, and 980ti.  

To answer your second question, yes.  You can.  Go to settings > Devices > Select your gpu or cpu > Uncheck any unwanted algorithms. See screenshot for an example

![image](https://user-images.githubusercontent.com/1341176/35358516-e2f7e602-0124-11e8-89a7-cfd38f5d55fa.png)

**Comment by angriest** [comment]
I believe you misunderstood the question. What I mean is that for the neoscrypt algorithm, the default miner is Tpruvot, but the KlausT miner outperforms it on GTX1070’s.

I’m looking for other situations where the default miner is outperformed by other miners.

**Comment by fdoving** [comment]
Would be nice with an option to add your own miners to this list.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Feature already exists
