### ISSUE TITLE
new miner "Bminer" for equihash (faster than DSTM) + no dev fee option

### ISSUE THREAD

**Issue by cervajz1** [nicehash/NiceHashMiner#908]
Hi, is it possible to add Bminer ? https://bitcointalk.org/index.php?topic=2519271.0

As I found its faster than EWBF and DSTM. **There is alson -nofee option in this miner**.

For example on my 1070ti (PL60,+200/+700)
EWBF - 470sols
DSTM - 490sols
Bminer - 510sols

Thanks

**Comment by bruvv** [comment]
👍

**Comment by kaos-1** [comment]
Scam, overreports locally does not match pool hashrate.
[Zcash forum where the author got banned](https://forum.z.cash/t/new-miner-bminer-a-fast-equihash-miner-for-cuda-gpus-5-1-0/26197)
[bitcointalk forum where users reporting strange things with this miner](https://bitcointalk.org/index.php?topic=2519271.340)

**Comment by joseortiz3** [comment]
Specifically, bminer reports inflated hashrates, and is no faster than other more well-known implementations. It doesn't deserve any more attention.

It's a scam, discussed in https://forum.z.cash/t/new-miner-bminer-a-fast-equihash-miner-for-cuda-gpus-5-1-0/26197/28

**Comment by ChriscomIT** [comment]
Please **DONT** add BMiner it's too insecure. Thanks, Dillon.

**Comment by psychopathio** [comment]
I tried using the three of them I was getting 320 +- on all cards and with bminer Im getting over 360+ sols

I love this program, I wont mind the fees in this case although i would like to pay in person and not have a mandatory fee.

I will try the -nofee option 👍

**Comment by psychopathio** [comment]
the  --nofee option dropped GPU 0 from 360+ to 300 sols only.

**Comment by joseortiz3** [comment]
@psychopathio  Please stop quoting the Bminer hashrates it prints to console. They are false and inflated hashrates as discussed. The hashrates you receive are no better than dstm or ewbf. This is discussed here:
https://forum.z.cash/t/new-miner-bminer-a-fast-equihash-miner-for-cuda-gpus-5-1-0/26197/28

**Comment by psychopathio** [comment]
@joseortiz3 I didn't actually know that. I was testing different software so thanks for the info

**Comment by StrobFX** [comment]
Hi joseortiz3, all tthe link to the zcash forum you submited have been deleted... Can you elaborate on what was on these links?

**Comment by joseortiz3** [comment]
@StrobFX It's a shame that forum removed that thread. 

Basically, someone ran _real benchmarks_ that compared real profits from DSTM and Bminer. They were very nearly the same, despite bminer printing a 5-10% higher hashrate to the console. This meant either bminer was inflating its reported hashrate, or was lying about how large its dev fee is.

Furthermore, recent posts on bitcointalk have found unusual network activity coming from bminer, seems that it may be recording inappropriate data.

Miners are very naive and continue to rely on the printed console hashrates. This has created, of course, an opportunity for people to build scam mining programs that print false hashrates and spread like wildfire. It seems bminer is one of these.

Furthermore, these disturbing findings keep popping up _on the author of bminer's thread_, yet the author has not responded to the allegations. Anyone who advocates usage of bminer is (inadvertently) supporting a very-likely scam operation.

**Comment by StrobFX** [comment]
Thanks for your answer!

**Comment by cannonballdex** [comment]
My results on a 6 card rig shows DSTM does .2 kh/s more than Bminer on the same setup, same pool.

**Comment by lear001** [comment]
Bminer is faster. I don't think DSTM's reported hashrate is accurate, the result is different if the way the miner calculate is different. it just make no sense to attack Bminer about the hashrate all the time.
if you don't believe it, pls check those video and test data below.

https://www.youtube.com/watch?v=_laCFKg-HRg&t=31s
pls check this Bminer VS DSTM video 

and also a fair test in bitcointalk under Bminer thread:
https://bitcointalk.org/index.php?topic=2519271.msg32355765#msg32355765

about the reported hash rate issue, there is officially answered on FAQ page:
https://www.bminer.me/faq/#why-the-reported-hashrate-of-bminer-is-higher-than-the-reported-hashrate-from-mining-pools

**Comment by bruvv** [comment]
Omg not again... Please close this discussion

**Comment by cannonballdex** [comment]
I go by the hashrate the pool is paying me for, not what shows on my computer. How would pool know what miner I am using?

**Comment by fanlong** [comment]
I do not see any reason to continue this discussion besides trolls hired by dstm devs or bminer devs.

Why not just add both and let the user decide. They can do their own tests on pools.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
