### ISSUE TITLE
Ratio BTC/GH way to high 

### ISSUE THREAD

**Issue by bruvv** [nicehash/NiceHashMiner#910]
So today I noticed that my miner didn't switch for the last 3 days! where as it normally would switch every 30 min or so. I found out what it is:
![image](https://user-images.githubusercontent.com/3063928/35383352-5a28ebfc-01c2-11e8-8982-b2029da6bee5.png)
As you can see the Ratio BTC is really high. I rebenchedmarked it and still the same issue. In the GPU section it's the same:
![image](https://user-images.githubusercontent.com/3063928/35383383-727bb82e-01c2-11e8-92a4-56423e241b38.png)
as you can see the other Ratio's are normal. I am running NHML v1.8.2.0-Pre2

**Comment by riccardoruspoli** [comment]
#676

**Comment by bruvv** [comment]
This is not related the benchmark is correct. The ratio isn't. Also doesn't matter what version of nicehash I'm using even with v2 it doesn't work correctly.

**Comment by riccardoruspoli** [comment]
Ratio is right, the speed of Xmr-Stak isn’t. Try to start Xmr-Stak and read the speed in the miner.

**Comment by bruvv** [comment]
it doesnt matter what you fill in:
![image](https://user-images.githubusercontent.com/3063928/35388713-2701616a-01d5-11e8-83ff-a38c33a7ef2c.png)

**Comment by jiri-silhan** [comment]
That column shows the price per GH. The column on the right (not visible on your screenshot) shows your earnings based on your speed...

**Comment by riccardoruspoli** [comment]
It is normal for the ratio of those algos to be high. That’s because the algo produces a really low number of hashes. In fact with Cryptonight you produce ~298 H/s, if you were producing an entire GH/s, in an hour you would produce ~300 BTC.

**Comment by bruvv** [comment]
that makes a lot of sense! Thanks guys will close this.
