### ISSUE TITLE
NHLM NOT keeping balance up to current stays frozen for hours.  

### ISSUE THREAD

**Issue by Horsetoothless** [nicehash/NiceHashMiner#911]
Have seen balance being reported on my miner stay at same balance for hours before being updated,
difference in balances over .1xx mbtc seen from web page. Half day for my Rx580. Manual stop, change something, restart no update. Multiple occasions.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
