### ISSUE TITLE
Crytonight old - low hashing speed

### ISSUE THREAD

**Issue by kudykam** [nicehash/NiceHashMiner#912]
Nicehash 1.8.1.6 or 1.8.2.0
AMD R9 285 driver 17.11 (also tried 15.12, 16.x and few other 17.x) global settings set  to Compute.
Win 10 64bit

On first run of Nicehash or after driver reinstall, cryptonight-old v9.7 runs at speed 518 H/s, after algorithm is stopped and run again it runs around 360 H/s or lower, never get back to 518 H/s.
What does seems to help is to reinstall driver to get only first run at 518 H/s.

**Comment by ghost** [comment]
download 
http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-17.7.2-Release-Notes.aspx 
Unistall with http://www.guru3d.com/files-details/display-driver-uninstaller-download.html
on 270x works very good

**Comment by kudykam** [comment]
OK after reinstall with this driver:
1st run = 518H/s - great!!
2nd run = 518 H/s - awesome!!
ok lets overlcock a bit (+4% up, it means from 975 to 1010Mhz core)
3rd run = jumping from 250 to 350 H/s :-(
revert overclocking back to stock
4th run = 250-350 H/s ;-(
restart pc
5th run = black window shows speed 306H/s (at first, after few second goes to 518), but Nicehash window shows 518 H/s OMG!!!
ok lets overclock again a restart pc...
6th run = 538 H/s
Lets hope it will stay this way..

This driver doesnt have switch from Graphic to Compute, but on my PC it makes no difference in speed anyway...
Also script doesnt detect GPU temperature and fan speed, booth shows 0%

**Comment by kudykam** [comment]
After 10 hours of mining at speed 540 H/s, now it dropped back to around 330 H/s by itself for no reason...
I left it for another 20 min, hoping it wil come back. Eventually I restarted computer, and now its back on 540 H/s. 
After 10 minutes: Connection lost, retry in 20 sec..
Now back to 330 H/s

UPDATE: sudden drop in speed was most likely due to added parameter -nofee 1

**Comment by fdoving** [comment]
Might not be related at all, but I had a similar issue on a MSI motherboard. Dropped from 400-ish to 300-ish on my Ryzen (CPU-mining). Figured out it was MSI Command Center making a mess. Closing it and have it not auto-start fixed it for me.

**Comment by kudykam** [comment]
I have gigabyte motherboard...
This morning when I start using computer it happened again.. I will start changing driver...

**Comment by kudykam** [comment]
I think I might find a problem. Cryptonigh old can automatically detect -a and -h parameter. Detected value hashcnt 864 is unstable, it runs ok most of the time but sometimes it start giving 40% lower performance. So I manually set -a 4 -h 832 parameters which gives slightly lower speed 518H/s but its more stable...
Overclcoking memory also might affect stability for set hasshcnt value. So I have to find a sweet spot...

**Comment by pachpute** [comment]
Please help me for manually set values of -a and -h parameters to -a 4  -h
864 parameters.
 How it cant be set parameter manually and where.

**Comment by kudykam** [comment]
first you have to estabilish correct H value.
Run minning and then pres "m" , now press + or - to set lower or higher value which is stable and get the highest speed. For example hashcnt 864..
Stop minning, Go to Settings ->Devices->select GPU-> select cryptonigh old algorithm and write:
-a 4 -h 864
to extra launch parameters field.

**Comment by kudykam** [comment]
Looks like the problem is still there, it happens once per 24 hours... randomly...
Grahic card is not overlocked , just underclocked GPU core...

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Crytonight is not seen as profitable anymore
