### ISSUE TITLE
time based difficulty

### ISSUE THREAD

**Issue by professor-jonny** [nicehash/NiceHashMiner#913]
The difficulty for mining Cryptonight is very high at the moment and I keep on getting kicked from the servers with my cpu as it is not providing shares with in the servers time out time.

Can we implement the ability to adjust and benchmark the difficulty to provide a share every 5 minutes to avoid getting temporally banned for not providing a share within the allowed time?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Yes this is possible and depends on miner plugin implementation
