### ISSUE TITLE
Getting low hashpower then benchmark in DaggerHashimoto Algorithm

### ISSUE THREAD

**Issue by swapongn** [nicehash/NiceHashMiner#915]
Hi,
 I am facing problem "DoggerHashimoto Algroithm" that is it is getting less hashpower then "benchmark". NH "benchmark"is correct because I check with other ETH pool which is same as NH "benchmark" for same rig but when my rigs working in NH  "DoggerHashimoto" Algorithm  then I am getting 20-30% less then benchmark! I could not understand why it is happening? Other Algorithms working nice!

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
