### ISSUE TITLE
add settings from claymore to nicehash

### ISSUE THREAD

**Issue by lgwjames** [nicehash/NiceHashMiner#917]
when i use claymore on its own, i pull 880-900watts from the wall
with this

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
EthDcrMiner64.exe -tstop 70 -tt 65 -fanmin 60 -fanmax 100 -cclock 1200 -mclock 2150-cvddc 870 -mvddc 870 -epool eu1.ethermine.org:4444 -ewal wallet.Rig1 -epsw x

when i use nicehash is 990 to 1100

how can i add -cclock 1200 -mclock 2150-cvddc 870 -mvddc 870 to nicehash legacy to get my watts down

**Comment by lgwjames** [comment]
anyone? as last night was puling 1400 watts

**Comment by lgwjames** [comment]
guess cant be done?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

It could be done with the old core and the new one as well. We will update how this can be done with the new system in the Wiki.
