### ISSUE TITLE
GPU Wrong detection

### ISSUE THREAD

**Issue by arnezami** [nicehash/NiceHashMiner#918]
Hello everyone,

I have a problem with my rig and Nicehash Legacy - wrong GPU detection!
![kpmiyjijtxk2vhz5g64rwg](https://user-images.githubusercontent.com/3115768/35477825-742dce5e-03d5-11e8-8575-8788dccfc563.png)
On my rig I have 3 ASUS R9 390x 8GB STRIX & 3 Sapphire RX 580 8GB.

In the list I see RX 580 and when I start benchmark - R9 390x start to work instead of RX 580.

After the benchmark as you can see, when I start mining the same behaviour - R9 instead of RX580, but in device list RX 580 selected.

I don't understand why this problem happend
s, but I seen that in config folder is different eqiupment identification. Before it was hardware unique address, now is some long GUID.
![screenshot_2](https://user-images.githubusercontent.com/3115768/35477837-c9be4e8e-03d5-11e8-8f6a-299f7dc133bf.png)

OS: Windows 10
Nicehash Version: 1.8.1.6
AMD Driver Version: 23.20.15002.11 (06.12.2017)
![screenshot_1](https://user-images.githubusercontent.com/3115768/35477867-74eb6ff8-03d6-11e8-8eb2-8782c5a1af56.png)
Nicehash LOG: [log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1670674/log.txt)

Could you check this ussie and fix it.
Thanks in advance.

**Comment by League-of-Coins** [comment]
I just noticed this exact same issue. I have 2 RX570s and 1 RX470. I selected to bench the RX570 and the RX480 starts working. I am running 17.11.4 drivers, fresh install of Windows 10 and Fresh drivers.

**Comment by icegnome** [comment]
Same Issue.
RX580, 3x RX570, 2x RX480
It appears to just shuffle the name of the cards up one.
RX580 RX480 RX570 RX480 RX570 RX570
shows up in nicehash as
RX480 RX570 RX480 RX570 RX570 RX580
However, when you benchmark its really the correct order, just not the correct names.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

This is fixed there
