### ISSUE TITLE
Bminer on Nicehash Legacy

### ISSUE THREAD

**Issue by SergiuBogdan** [nicehash/NiceHashMiner#919]
Hello Dillon , can you look at this ?

https://bitcointalk.org/index.php?topic=2519271.0

Any chance that you can include it on the next release of nicehash legacy ? 

Similar to other miners, Bminer contains 2% devfee.

Features
Fast

735-745 Sol/s on GTX 1080Ti
450-460 Sol/s on GTX 1070
315-325 Sol/s on GTX 1060
On stock settings

Secure and reliable

SSL support
Automatic reconnects to recover from transient network failures
Automatic restarts if GPUs hang

Operation friendly

Comes with REST APIs to facilitate production deployments

**Comment by kaos-1** [comment]
Bminer is a scam, it never matched pool side. Overreports.

**Comment by kaos-1** [comment]
[Zcash forum where the author got banned](https://forum.z.cash/t/new-miner-bminer-a-fast-equihash-miner-for-cuda-gpus-5-1-0/26197)
[bitcointalk forum where users reporting strange things with this miner](https://bitcointalk.org/index.php?topic=2519271.340)

**Comment by kaos-1** [comment]
DSTM Zminer is the real deal on the other hand, always matched pool reported rate. And is currently the best available eqi miner.

**Comment by SergiuBogdan** [comment]
DSTM Zminer looks good , maybe some implementations , in nicehash legacy ?

**Comment by kaos-1** [comment]
There is a nicehash miner legacy with zminer  floating around search and you will find it. It's on git .

**Comment by SergiuBogdan** [comment]
well , i trust the official one more.

**Comment by kaos-1** [comment]
and you should. I think i saw Dillon adding code changes for dstm the other day.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

BMiner added
