### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by Crypto-Lord** [nicehash/NiceHashMiner#921]
I know everything is working as it should, but it displays all the rx580 twice and doesn't show the 1080 mining. Mining windows show proper for 1080 & rx580. Works fine now but interesting occurrence

![ok](https://user-images.githubusercontent.com/28488696/35486556-710e0244-043d-11e8-85e2-519ba9e7ed15.png)

**Comment by lgwjames** [comment]
even stranger, look at botton, 19.09 that would be 26.71 as well

**Comment by Crypto-Lord** [comment]
I know, the top mining data being shown should actually be the GTX 1080. Would have been nice if it was double mining/paying

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
