### ISSUE TITLE
AMDOpenCLDeviceDetection ERROR 

### ISSUE THREAD

**Issue by slayer26** [nicehash/NiceHashMiner#922]
hello I downloaded this version 1.8.1.7 and the application when I try to open it, gives the following error in that file AMDOpenCLDeviceDetection.exe

**Comment by sakisTe** [comment]
download https://www.microsoft.com/en-us/download/details.aspx?id=40784 x64

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
