### ISSUE TITLE
NHML 1.8.1.7 DSTM TERMINATES during benchmark

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner#923]
This is my observation that DSTM is configured wrongly. There is no password after user but the debug console shows --user (bitcoin address).(password)

DSTM just needs the bitcoin address NOT the password. I have checked running DSTM externally and it works perfectly without the password.

zm --server equihash.eu.nicehash.com  --port 3357 --user bitcoinaddress

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
