### ISSUE TITLE
NHML 1.8.1.7 - error when checking profitability data and CTD when benchmarking

### ISSUE THREAD

**Issue by Infidelities** [nicehash/NiceHashMiner#924]
when i start the NHML 1.8.1.7 and on "Getting Nicehash SMA information"
the process then stopped and i get error message : 
"Unable to get nicehash profitability data. if you are connected to internet, try again later"

even thought my rig is connected to the internet without problem

and when i try to benchmark the new version
the program keep CTD and close

my logs:
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1672390/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1672391/log.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
