### ISSUE TITLE
Nicehash Legacy 1.8.1.5 takes forever to load

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner#925]
It seems to hang at getting SMA information and says check internet connection.

**Comment by Simaex** [comment]
Same issue with 1.8.1.7 today.
I think it may be server-side issue.

**Comment by blue-yu** [comment]
1.8.1.8. is working finally :)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

Probably backend service issue and main thread blocking.
