### ISSUE TITLE
Problems with neoscrypt

### ISSUE THREAD

**Issue by vyncy** [nicehash/NiceHashMiner#926]
It doesn't seem nhml uses ccminer neoscrypt folder ? What ever is replaced there doesn't matter because its using standard ccminer folder when mining neoscrypt ?
This is problem because standard ccminer has lower hashrates, what is even stranger is that nhml comes with klaust ccminer which has better hashrate, but is not using it for neoscrypt ?

Can you please either use klaust miner for neoscrypt or use neoscrypt folder so we can add the miner we like ? Thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

NeoScrypt is not seen as profitable anymore
