### ISSUE TITLE
Threads issue in XMRig

### ISSUE THREAD

**Issue by NTSP** [nicehash/NiceHashMiner#928]
I have an Threadripper 1950x with 16 cores and 32 Threads... XMRig just use to 16 Threads but I want to use 31 Threads, like I always did on my Xeons, but I didn´t find a way jet to change it... How can I do it or it is not possible at all to use all Threads? Thanks for help

**Comment by NTSP** [comment]
I have an Threadripper 1950x with 16 cores and 32 Threads... I want to use 31 Threads, like I always did on my Xeons, but didn´t find a way jet to change it... How can I do it or it is not possible at all to use all Threads? Thanks for help

**Comment by bruvv** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/wiki/Algorithm-ExtraLaunchParameters

**Comment by MaKCuMyC** [comment]
You will get nothing with that change.
Learn Cryptonight spec. 1 thread uses 2 MiB L3 chache. So optimal performance L3/2=32MB/2=16threads.

**Comment by NTSP** [comment]
Ok and thanks again for help

**Comment by NTSP** [comment]
One more think... Does anybody know why NHML and NHM 2 always shows two cpus with a Threadripper? If I want to use to the second cpu at the same time the hashrate drops down to around 300mh/s and if I use just one the hashrate will be around 1,5kh/s...

![sys](https://user-images.githubusercontent.com/35923994/35548331-059d801e-057f-11e8-9048-f07e7d831b7b.jpg)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
