### ISSUE TITLE
1.8.1.7

### ISSUE THREAD

**Issue by kaos-1** [nicehash/NiceHashMiner#929]
Miner paths are wrong for MinerPathPackage_NVIDIA_6_x
Neo miner should point to Klaust not Tpuvrot
same with nist5 and so on.
You forgot to update cc paths @DillonN

**Comment by Nix-id** [comment]
+1
on 1070 klaus show 1000+
tpuvrot only 800-900

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
