### ISSUE TITLE
Keccak stratum connection problems

### ISSUE THREAD

**Issue by p1r473** [nicehash/NiceHashMiner#93]
Receiving stratum problems on both of my rigs that were trying Keccak
It works for a bit then breaks

![image](https://user-images.githubusercontent.com/9235633/28724655-ca08e684-7388-11e7-9101-bc4f8545365a.png)

**Comment by ChriscomIT** [comment]
Seems it was just a short and temporary downtime of the server. I recognized the same. It was up again some minutes later.

**Comment by p1r473** [comment]
It happened 2 different days for me so far. Hopefully won't happen again..

**Comment by ChriscomIT** [comment]
Please don't reopen this again and again. It's no fault of the application itself.

**Comment by nicehashdev** [comment]
There is nothing to fix. There are simply not enough orders (no unlimited order) by buyers so not all of you are able to mine keccak all the time.

**Comment by ChriscomIT** [comment]
@nicehashdev Ah ok good to know. Never did notice that. So when there are no orders we simply can't connect to the server?

**Comment by nicehashdev** [comment]
Of course. Usually, buyers put bottom wall for very low price and make it unlimited. But in this case, nobody did this. This is also a hint for someone to pull quite some almost free money if being done.

**Comment by ChriscomIT** [comment]
Ok, thanks for the clarification. Sounds good. Yeah if I had enough crypto at the moment I sure would give it a shot. But I can't afford to lose something right now so I better don't test my luck. :D One thing I still don't get is why the profitability of keccak sometimes the highest even if there are not enough or no orders at all? Does that rely on the latest profitability keccak had before running out of orders? Thanks.

**Comment by p1r473** [comment]
@nicehashdev can you set Keccak's "paying" in the API when no orders are placed to 0 so it will switch to something when Keccak has no orders ? If no orders, it should be paying 0 in the API
