### ISSUE TITLE
1.8.1.7 Issues

### ISSUE THREAD

**Issue by DaMoot** [nicehash/NiceHashMiner#930]
All versions of NHL stopped updating SMA information last night until I upgraded to 1.8.1.7.
I would humbly request that upon next release you don't cripple older clients, just notify the admin to update.

Benchmark window is no longer resizable. This view really needs to be resizable again!

New version of Claymore included for Ethereum won't run on 1050 Ti 4G cards for some reason, only 1060 3G or better. It exits out with 'terminated'. This miner worked fine before the update for all cards.

FEATURE REQUEST: Allow copying of general benchmark numbers and active selections between one version and the next. Having to run through the checkmarks each time, especially now that the benchmark window is non-resizable, and running 70 benchies for 5 cards is time consuming, productivity losing and a pain in the rear. Now that I have a 12 gpu board coming, the process is going to take huge amounts more time.

Keep up the good work!

**Comment by Simaex** [comment]
SMA update problem also affected 1.8.1.7 today. No data it is version-related. 
Never been able to resize benchmark window, it is a long-awaited feature :-)
The feature that you are requesting is working now. You do not need to re-run benchmarks. Just follow update guide. It is simple copy-and-paste of old config to new config directory prior to running new version. Though no one can guarantii that new miners are not better than old one's. So you'd rather benchmark once in a while.

**Comment by DaMoot** [comment]
I've been using the resize benchmark window for more than a month easy I think. It's a great feature! But maybe it's only in 1.8.2.0-Pre2? That version stopped functioning for me last night with the dreaded SMA information message. :(

Thank you for letting me know that there is an update procedure for retaining benchmarks. That's certainly going to save time!

**Comment by billmcilhargey** [comment]
Lyra2REv2 (ccminer) when attempting to benchmark, ccminer crashed.  All other algorithms with ccminer (and other mining programs) worked successfully.   This ccminer algorithm worked in 1.8.1.6


5 GPUs Nvidia 1080 Ti   11GB -- latest CUDA version: 9.1 and latest drivers are installed

**Comment by Viral** [comment]
@computeronix you need to install VC++ 2015 x86

https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by ghost** [comment]
download https://www.microsoft.com/en-us/download/details.aspx?id=40784 x64

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
