### ISSUE TITLE
Can not load SMA infomation and problem : " Check internet connection "

### ISSUE THREAD

**Issue by chuongmd** [nicehash/NiceHashMiner#931]
My network is fine but NHML keep saying this problem ???? 
![screen shot 2018-01-30 at 12 42 43 am](https://user-images.githubusercontent.com/26231230/35525357-d6492426-0556-11e8-8348-61a96b683c7f.png)

**Comment by dre40** [comment]
same problem, appears regularly ((

**Comment by miniveda** [comment]
Same Problem here on 1.8.1.7 and the new release and yet i can't find any solution.

**Comment by yada-yoda** [comment]
Hangs on 1.8.1.6 and errors out on newest version of 1.8.1.8 and won't even start after the error.

**Comment by daveahartley** [comment]
Just built a new rig and loaded NHM 1.8.1.8.  Having the same problem with SMA loading error.  I have tried turning off AV and firewall protection, but only solution I have fiound that works is to perform a complete rig power down and restart, seems to sort the problem out!!!  Not ideal though.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client
**OR**
Networking issue on your ISP side or ISP is blocking our services
