### ISSUE TITLE
Legacy does not start with 13 Nvidia cards

### ISSUE THREAD

**Issue by Nisseiparken** [nicehash/NiceHashMiner#932]

**Comment by lgwjames** [comment]
and where is your post? do you know english?

**Comment by Nisseiparken** [comment]
The title says everything and it has been mentioned before. You can not start Legacy with 13 Nvidia cards. It must be a bug because all other maining programs start with 13 cards. With AMD cards, it is no problem to start 13 cards.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
