### ISSUE TITLE
1.8.1.7 can't benchmark Lyra2REv2

### ISSUE THREAD

**Issue by stonedrider** [nicehash/NiceHashMiner#933]
I get a application error only when NHML is trying to benchmark the Lyra2REv2. All other benchmarks completed without any issues.
![img_20180129_233155](https://user-images.githubusercontent.com/31825819/35535782-6a665606-054d-11e8-8dbe-e68f37c0f371.jpg)

**Comment by billmcilhargey** [comment]
+1

**Comment by pducharme** [comment]
+1 too, can't mine it (not just benchmark).

**Comment by althefirst** [comment]
same here, i have done a repair with both C# 2013 vcredist_x64 and VC_redist.64.exe. 
no joy, just restarted 1816

**Comment by blue-yu** [comment]
1.8.1.8. also have this problem :(

**Comment by pducharme** [comment]
1.8.1.8 give the same error on mine too.

**Comment by Viral** [comment]
you need VC++ 2015 

https://www.microsoft.com/en-us/download/confirmation.aspx?id=52685

**Comment by stonedrider** [comment]
Thank you so much. That fixed the issue. I saw your comment in another similar topic and I have installed the x86 package. Now everything is working. Thank you @Viral

**Comment by BramVanroy** [comment]
@stonedrider is correct. I have posted a direct link in [the other topic](https://github.com/nicehash/NiceHashMinerLegacy/issues/939#issuecomment-362346132).

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Lyra2REv2 not relevant anymore
