### ISSUE TITLE
merge 1.8.17 and 1.8.20 pre2 branches

### ISSUE THREAD

**Issue by professor-jonny** [nicehash/NiceHashMiner#934]
can we merge the changes to the miners in 1.8.17 with the core program 1.8.20 pre 2?

specifically I like the ability to bench the intensity settings in 1.8.20 pre 2 but it would be nice to use the new miners merged in the latest release 1.8.17.

can I just copy the miners and config over the top of 1.8.20 pre2 and have the benefits of both or is there more to it than that ?

**Comment by angriest** [comment]
Definitely looking forward to an 1.8.1.8 and 1.8.2.0 Pre2 merge. Hoping Dillon’s plan is to release a full 1.8.2.0 soon. The multithreaded benching is a lifesaver.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
