### ISSUE TITLE
request simple clone benchmark to all cards

### ISSUE THREAD

**Issue by lgwjames** [nicehash/NiceHashMiner#936]
when i move my cards about on rig i have to keep doing new benchmarks. 
If i have the same cards, be great for a option to say clone benchmarks to same gpu

**Comment by dadoremix** [comment]
+1

**Comment by whqch** [comment]
+1

**Comment by Simaex** [comment]
No problem doing it just now. You can set benchmarking results manually. But be advised that even the same GPU can have different results due to silicon lottery, cooling issues and so on.

**Comment by S74nk0** [comment]
This feature already exists (right click on devices in benchmarks)... Read @Simaex comment as he brings up a good point

![image](https://user-images.githubusercontent.com/1517233/60587330-7b3fa500-9d94-11e9-9e81-678b04c9f1bc.png)
