### ISSUE TITLE
1.8.1.8 xmr CCminer for NVIDIA not working correctly

### ISSUE THREAD

**Issue by francescocmazza** [nicehash/NiceHashMiner#937]
xmr CCminer for NVIDIA not working correctly. 1.8.1.6 version instead worked well. 
What I get with Nvidia gtx 770 is:

"ccminer 8.18-KlausT (64bit) for nVidia GPUs
Compiled with Visual Studio 2015 using Nvidia CUDA Toolkit 9.1

Based on pooler cpuminer 2.3.2 and the tpruvot@github fork
CUDA support by Christian Buchner, Christian H. and DJM34
Includes optimizations implemented by sp-hash, klaust, tpruvot and tsiv.

[2018-01-30 17:20:42] NVML GPU monitoring enabled.
[2018-01-30 17:20:42] 1 miner thread started, using 'bitcoin' algorithm.
[2018-01-30 17:20:42] Starting Stratum on stratum+tcp://cryptonight.eu.nicehash.com:3355
[2018-01-30 17:20:42] ...retry after 10 seconds
[2018-01-30 17:20:45] GPU #0: waiting for data
[2018-01-30 17:20:48] GPU #0: waiting for data
[2018-01-30 17:20:51] GPU #0: waiting for data
[2018-01-30 17:20:52] ...retry after 10 seconds
[2018-01-30 17:20:54] GPU #0: waiting for data".

This error loops indefinetly.

I am not getting the same error on NVidia geforce 1070. Maybe this miner is not compatible with cards with 2gb or less?

**Comment by francescocmazza** [comment]
I think the error is in the algo selection setting in NHML. it's supposed to be running XMR algo, instead the verbose sais that the algo selected is Bitcoin

**Comment by Talyrius** [comment]
I'm also seeing this with a 780 Ti on ccminer_cryptonight.

**Comment by jojobg** [comment]
Apparently we have a mismatch on Bin.zip level, klausT version in cryptonight folder 1.8.1.6 is still ok. KlausT does not support cryptonight so defaults to bitcoin algo. Copying bin from 1.8.1.6 passes the checks and works: 
D:\Downloads\NHML-1.8.1.8\bin\ccminer_cryptonight>ccminer.exe
ccminer 8.18-KlausT (64bit) for nVidia GPUs
Compiled with Visual Studio 2015 using Nvidia CUDA Toolkit 9.1

Based on pooler cpuminer 2.3.2 and the tpruvot@github fork
CUDA support by Christian Buchner, Christian H. and DJM34
Includes optimizations implemented by sp-hash, klaust, tpruvot and tsiv.

[2018-02-01 22:49:45] NVML GPU monitoring enabled.
ccminer.exe: no URL supplied
Try `ccminer --help' for more information.

D:\Downloads\NHML-1.8.1.8\bin\ccminer_cryptonight>ccminer.exe --help|find /i "crypto"

D:\Downloads\NHML-1.8.1.8\bin\ccminer_cryptonight>cd ..\..\..\NHML-1.8.1.7\bin\ccminer_cryptonight

D:\Downloads\NHML-1.8.1.7\bin\ccminer_cryptonight>ccminer.exe
ccminer 8.18-KlausT (64bit) for nVidia GPUs
Compiled with Visual Studio 2015 using Nvidia CUDA Toolkit 9.1

Based on pooler cpuminer 2.3.2 and the tpruvot@github fork
CUDA support by Christian Buchner, Christian H. and DJM34
Includes optimizations implemented by sp-hash, klaust, tpruvot and tsiv.

[2018-02-01 22:54:17] NVML GPU monitoring enabled.
ccminer.exe: no URL supplied
Try `ccminer --help' for more information.

D:\Downloads\NHML-1.8.1.7\bin\ccminer_cryptonight>ccminer.exe --help|find /i "crypto"

D:\Downloads\NHML-1.8.1.7\bin\ccminer_cryptonight>

**Comment by GenuineJD** [comment]
Confirmed that copying bin\ccminer_cryptonight folder from 1.8.1.6 release into bin\ for 1.8.1.8 release works.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.
**OR**
Your user account is/was temporary banned (write to support@nicehash.com to check)
**OR**
Used miner isn't compatible with NiceHash protocol
