### ISSUE TITLE
1.8.1.8 - Unable to run certain algos

### ISSUE THREAD

**Issue by francescocmazza** [nicehash/NiceHashMiner#938]
Please also note that selecting some algos and inserting manually the hash rate in the settings I get the following error:
"Nicehash cannot start mining. Make sure you have at least one enabled and benchmarked algorithm."

I'm getting this error on Nist5 (ccminer_alexis), while nist5 (ccminer) works fine.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Algorithms and miners are not relevant anymore
