### ISSUE TITLE
1818 lyra2RE2  problem still there

### ISSUE THREAD

**Issue by althefirst** [nicehash/NiceHashMiner#939]
1818 still problem lyra2re2 cc miner will not start
have updates nvidia to 390.77 and repaired both 2013 and 2017 C# runtime

**Comment by althefirst** [comment]
web site will not alowe drag and drop or past from clip board of text file

**Comment by althefirst** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1678837/log.txt)
finally got it uploaded

**Comment by borimol** [comment]
Same here. Lyra2re2 get an error. Using latest Nvidia drivers.

**Comment by Viral** [comment]
you all need to install VC++ 2015 redist

https://www.microsoft.com/en-us/download/confirmation.aspx?id=52685

**Comment by borimol** [comment]
Still the error: https://s6.postimg.org/lrieepi0x/screenshot_66.jpg despite installing VC++ 2015.

**Comment by Viral** [comment]
try to run the program directly outside of NHML what does it say?

\bin\ccminer_nanashi\ccminer.exe

**Comment by borimol** [comment]
This: https://s6.postimg.org/9cvmeedo1/screenshot_67.jpg

VCruntime140.dll not found.

**Comment by Viral** [comment]
yep. that should be fixed by installing VC++ 2015

did you install the right one?

x86 or x64 ?

**Comment by borimol** [comment]
x64 version. Winver: 1709.

I have rebooted the system. Same results.

**Comment by Viral** [comment]
you need to install the x86 version since ccminer.exe is a 32 bit app

**Comment by borimol** [comment]
Solved!!!!!!!

Thank you!!

**Comment by althefirst** [comment]
ok then why is only the 64 bit comes in the bin file? and not both?

**Comment by Viral** [comment]
\bin\ccminer_nanashi\ccminer.exe

the above file is 32 bit.

from the readme: the x86 releases are generally faster than x64 ones on Windows - https://github.com/nicehash/ccminer-nanashi

**Comment by pducharme** [comment]
Thanks! I didn't knew we needed the 32 bit! works now.

**Comment by BramVanroy** [comment]
@Viral Unfortunately it seems that Microsoft's website automatically detects if you are running 32 or 64 bit, so it automatically starts downloading the 64 bit redistribution in most cases. Here is a direct link to the 32 (x86) version:

https://download.microsoft.com/download/0/6/4/064F84EA-D1DB-4EAA-9A5C-CC2F0FF6A638/vc_redist.x86.exe

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Lyra2REv2 not relevant anymore
