### ISSUE TITLE
still issues with benchmarking some algos :/ v1.8.1.8

### ISSUE THREAD

**Issue by NTSP** [nicehash/NiceHashMiner#940]
I have still issues with benchmarking dtsm Equihash, ccminer CryptoNight and ethminer DaggerHashimoto... Here are the logs...

**Comment by NTSP** [comment]
2018-01-30 19:09:25|#  zm 0.5.8
2018-01-30 19:09:25|#  GPU0 + TITAN V                  MB: 12288 PCI: 67:0
2018-01-30 19:09:25|
2018-01-30 19:09:25|#  telemetry server started
2018-01-30 19:09:25|#  connected to: equihash.eu.nicehash.com:3357
2018-01-30 19:09:26|#  server supports extranonce
2018-01-30 19:09:26|#  server set difficulty to: 0003c3c3c3c0000000000000...
2018-01-30 19:09:26|gpu_id 0 320541120 0 invalid argument
2018-01-30 19:09:26|gpu 0 unresponsive - check overclocking
2018-01-30 19:09:26|cudaMemcpy 1 failed

**Comment by NTSP** [comment]
*** ccminer 2.2.4 for nVidia GPUs by tpruvot@github ***
    Built with VC++ 2013 and nVidia CUDA SDK 9.0 64-bits

  Originally based on Christian Buchner and Christian H. project
  Include some kernels from alexis78, djm34, djEzo, tsiv and krnlx.

BTC donation address: 1AJdfCpLWPNoAMDfHF1wD5y8VgKSSTHxPo (tpruvot)

[2018-01-30 19:05:11] Using JSON-RPC 2.0[0m
[2018-01-30 19:05:11] NVML GPU monitoring enabled.[0m
[2018-01-30 19:05:11] NVAPI GPU monitoring enabled.[0m
[2018-01-30 19:05:11] 1 miner thread started, using 'cryptonight' algorithm.[0m
[2018-01-30 19:05:11] GPU #0: TITAN V, 11884 MB available, 80 SMX[0m
[2018-01-30 19:05:11] GPU #0: 5120 threads (12.25) with 320 blocks[0m
[2018-01-30 19:05:11][31m GPU #0: an illegal memory access was encountered cryptonight_core_cuda line 180[0m

**Comment by NTSP** [comment]
Genoil's ethminer 0.9.41-genoil-1.1.5-nicehash-1.1.2
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_ 

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Found suitable CUDA device [TITAN V] with 12884901888 bytes of GPU memory
Benchmarking on platform: CUDA
Preparing DAG for block #50009
  i  18:54:46|cudaminer0  set work; seed: #290decd9, target: #000000000000
  i  18:54:46|cudaminer0  Initialising miner...
Warming up...
Generating DAG seed 290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563
Using device: TITAN V (Compute 7.0) THREADS=128 BLOCKS=8192
Cuda error in func 'set_constants' at line 143 : invalid device symbol.

**Comment by NTSP** [comment]
Not compatible at all or can I do something to fix it?

**Comment by luxferro** [comment]
Nicehash program is basically just a miner manager. If miners aren't working it's probably due to you using a Titan V, and miners not being optimized for it.

**Comment by SK-Crow** [comment]
1. Seems like the hardware is too new, likely is not supported yet.  Might be worth posting an issue on github.com/ethereum/cpp-ethereum.  Problem is, the devs likely don't have one to test, so it's unlikely you'll see an update any time soon.
2. Not really related, but ROI is going to be horrible on that card..  I'm sorry for your loss.

**Comment by lgwjames** [comment]
i have rx580 from nov and all work, just pick slow

**Comment by NTSP** [comment]
Thanks and thats what I thought... Ok, lets wait and see what happens in the future... I got some Vs to test them and also to test how profitable this cards are and actually it´s good enough... The Vs are more powerful as my Tis at the same power... I am looking forward that the devs will fully integrate this Vs to get all miner and also the algos running... Regards

**Comment by NTSP** [comment]
58.08 MH/s at Skunk
7018.18 MH/s at Blake2s
3742.30 MH/s at Sia
27.64MH/s at alexis_X11Gost
25.29 MH/s at X11Gost
2.752014 GH/s excavator Pascal
901 Sol/s at EWBF Equihash
702.90 MH/s at Sia
5862.13 MH/s Decred
78.823 Mh/s and 788.233 Mh/s at DUAL Dagger Sia
77.617 Mh/s and 776.174 Mh/s at DUAL Dagger Decred
75.465 Mh/s and 72.320 Mh/s at DUAL Dagger Lbry
78.679 Mh/s and 786.789 Mh/s at DUAL Dagger Pascal
106.26 MH/s at Lyra2REv2 
1828.00 kH/s at NeoScrypt
102.10MH/s at alexis Nist5
89.85 MH/s at Nist5
1584.82 MH/s at Keccak

Consumption are between 175-275W a bit overclocked / GPU=0 and MEM=+110 and anything else what I tried ends in a bluescreen so just this settings are stable for 24/7

**Comment by lgwjames** [comment]
yes silly watts, my 8gb rx580s (6) uses 880-900watts whole rig on clay more, yet on nicenash is 1300-1480watts, that means about 6p more a hour, or £1.60 extra power a day. 

claymore on its own is £3 a day for me as i pay a day and night right
using nicehash is is closer to £5 a day. not worth it

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
