### ISSUE TITLE
[Solved] NHML 1.8.1.8 AMDOpenCLDeviceDetection.exe error

### ISSUE THREAD

**Issue by naub1n** [nicehash/NiceHashMiner#941]
hi,

I have update NHML 1.8.1.6 to 1.8.18 and i have an error with AMDOpenCLDeviceDetection.exe
Idem with NHML 1.8.1.7
No problem with NHML 1.8.1.6

![capture](https://user-images.githubusercontent.com/8344600/35584843-85996aa4-05f6-11e8-861c-22694c258828.JPG)

**Comment by ghost** [comment]
download https://www.microsoft.com/en-us/download/details.aspx?id=40784 x64

**Comment by rokx** [comment]
I just want to add that I already had Visual C++ Redistributable Packages for Visual Studio 2013. Performing a repair solved the problem.

**Comment by naub1n** [comment]
Ok thx.
I installed the pre-release version and no error.
Visual C++ Redistributable Packages seems to be the solution.
=> Solved

**Comment by LeaTex** [comment]
I got the same error with NHML 1.9.0.5 on Windows 10.
Installing Visual C++ Redistributable Packages for Visual Studio 2013 solved my problem.

Thanks a lot!
