### ISSUE TITLE
Update Benchmark while mining

### ISSUE THREAD

**Issue by YanivYon** [nicehash/NiceHashMiner#942]
Hi
i couldn't find this feature anywhere
but does nicehash use the current hashrate while mining to overwrite the saved benchmark?
if not, it would be rally cool for people to start with the quick benchmark
and while mining after several hours it would get very precise becnhmarks

**Comment by SK-Crow** [comment]
Actually a really good idea.  Perhaps averaging it out if you run for ~5 minutes or longer on an algo.

**Comment by Krolow93** [comment]
I find this as a really good idea!
I would ask that this is optional though, just in case we want to manually lock in a specifik value.
I think this would also solve the problem with the rising difficulty that might make the current benchmarks inaccurate in the future. Also this would make it so it's not as crucial to re-benchmark every algo after an update, if improvements have ben made it will eventually find it and update the benchmarks on its own

**Comment by Joshwaa2010** [comment]
Please add this feature. This would be very helpful when coins change on DagarHashmoto going from Dag 166 to Dag 6 changes the speed greatly.

**Comment by KAMAELUA** [comment]
But if in some case speed was deprecated ( connection problems for example ) and this value was saved as benchmark data -> it will swap algo to another and never returns to this one

**Comment by DmitryDMR** [comment]
it's may be realised as one more button in main window with popup for all devices. in this window we can see per devices old and new (current) benchmark value and button update, and/or checkbox autoupdate

**Comment by Talyrius** [comment]
> But if in some case speed was deprecated ( connection problems for example ) and this value was saved as benchmark data -> it will swap algo to another and never returns to this one

An option to periodically rebenchmark enabled algorithms based on when they were last ran would resolve this.

**Comment by Dohtar1337** [comment]
Won't fix/include. This feature or bug might already be fixed or added. Or might not be included due to internal reasons.
