### ISSUE TITLE
NiceHash will mine with my CPU but not GPU

### ISSUE THREAD

**Issue by rf9661** [nicehash/NiceHashMiner#943]
Hello!

I need some help mining with NiceHashLegacy v1.8.1.7. I used to be able to mine with both my CPU and my GPU. Then, it stopped mining with my GPU and would only mine with my CPU. Now, it doesn't mine at all. I've tried uninstalling and reinstalling. I've also tried with NiceHash v2 to no avail. Can anyone connect via TeamViewer to help me out?

**Comment by serh39** [comment]
reinstall GPU driver

**Comment by MaKCuMyC** [comment]
what GPU?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
