### ISSUE TITLE
stratum_rev_line failed - Pool issue? 

### ISSUE THREAD

**Issue by jacknus** [nicehash/NiceHashMiner#944]
I am getting this issue when I try to run my miner - no matter what algo I am using.
Does this have something to do with the connection to the pool?

**Comment by KAMAELUA** [comment]
+1

**Comment by Haircut211** [comment]
Same here

**Comment by Haircut211** [comment]
[2018-01-31 20:50:51] Starting on stratum+tcp://neoscrypt.usa.nicehash.com:3341
[2018-01-31 20:50:51] NVML GPU monitoring enabled.
[2018-01-31 20:50:51] NVAPI GPU monitoring enabled.
[2018-01-31 20:50:51] 1 miner thread started, using 'neoscrypt' algorithm.
[2018-01-31 20:51:01] stratum_subscribe timed out
[2018-01-31 20:51:01] ...retry after 30 seconds

**Comment by Haircut211** [comment]
ETH: 1 pool is specified
Main Ethereum pool is daggerhashimoto.usa.nicehash.com:3353
DCR: 0 pool is specified
Be careful with overclocking, use default clocks for first tests
Press "s" for current statistics, "0".."9" to turn on/off cards, "r" to reload pools, "e" or "d" to select current pool 
CUDA initializing...

NVIDIA Cards available: 2
CUDA Driver Version/Runtime Version: 9.1/8.0
GPU #0: GeForce GTX 1070, 8192 MB available, 15 compute units, capability: 6.1  (pci bus 9:0:0)

Total cards: 1
ETH: Stratum - connecting to 'daggerhashimoto.usa.nicehash.com' <198.11.220.44> port 3353
No pool specified for Decred! Ethereum-only mining mode is enabled
ETHEREUM-ONLY MINING MODE ENABLED (-mode 1)
ETH: nicehash stratum mode
"-allpools" option is set, default pools can be used for devfee, check "Readme" file for details.
Watchdog enabled
Remote management is enabled on port 4004

ETH: Stratum - Connected (daggerhashimoto.usa.nicehash.com:3353)
Socket was closed remotely (by pool)
ETH: Job timeout, disconnect, retry in 20 sec...
GPU0 t=36C fan=42%

**Comment by jacknus** [comment]
Yeah asked their support and they said if you have multiple miners and one of them don't get any shares for like 5 minutes it will get soft banned. However this soft ban might affect the other miners that are running ....

**Comment by Haircut211** [comment]
I managed to fix mine. On my main PC I used it for gaming and web browsing and just added 2 cards. I always had a vpn running. My new PC Im converting to a gaming PC I didnt have my vpn set up and my wifi kept saying it couldn't find the proxy settings and WIN 10 has it set to auto. I used my VPN and it somehow fixed my issue.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client
**OR**
Networking issue on your ISP side or ISP is blocking our services
**OR**
Your user account is/was temporary banned (write to support@nicehash.com to check)
**OR**
Used miner isn't compatible with NiceHash protocol or your hardware
