### ISSUE TITLE
0xc000007b Error Upon Starting of Mining

### ISSUE THREAD

**Issue by mminolli** [nicehash/NiceHashMiner#946]
Hello,
Updating from 1.8.1.6 
Now getting a 0xc000007b error when miner launches.

**Comment by Viral** [comment]
you need to install VC++ 2015 x86

https://www.microsoft.com/en-us/download/confirmation.aspx?id=52685

**Comment by TheUnderTaker11** [comment]
I am also having this problem and already have that installed. Tried downloading and the error it gave me was that it already was there.

**Comment by ghost** [comment]
download https://www.microsoft.com/en-us/download/details.aspx?id=40784 x64

**Comment by mminolli** [comment]
None of these updates work.

**Comment by Brandon0310** [comment]
Im having this issue now any help?

**Comment by mminolli** [comment]
You will need to install both and the latest.

**Comment by mrMad-Cat** [comment]
I have the same error with t-rex miner for few weeks now on a fresh installed PC.  
I have installed:
NHM 1.9.0.20
VC++ 2008 x64
VC++ 2008 x86
VC++ 2017 x64

Should I delete some and install another?

**Comment by mrMad-Cat** [comment]
Fixed!
Deleted VC++ 2017 x64 so it permited me to install older versions, than installed in the following order:
VC++ 2013 x64
VC++ 2017 x86
VC++ 2017 x64

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
