### ISSUE TITLE
Names of graphic cards are switched 

### ISSUE THREAD

**Issue by xberg** [nicehash/NiceHashMiner#948]
Hi,

I have 2 graphic cards:
- RX 560
- Radeon Pro Duo (recognised as 2x graphic cards). 
In Nicehash Legacy 1.8.1.8 one of the Radeon Pro Duo is displayed as RX 560 (and vice versa: the RX 560 is displayed as a Radeon Pro Duo)

Win 10
NH 1.8.1.8
AMD Drivers 18.1.1

**Comment by bullet321** [comment]
I have same problem with R9 390 and RX480. I have R9 290. And when R9 290 and RX480 are connected is ok, or R9 290 with R9 390. But as soon as i connect RX, it switches name.
Anyone?

**Comment by Sibonet** [comment]
I have same problem RX570 (which is in truth RX470 reported wrongly by any driver) is listed as GPU7 while in truth it is RX480
RX570 is actually GPU9
Both I can check monitoring activity at core clock and/or memory clock during benchmarking 
Another way to check it is to start only particular GPU(unchecking all others) before launching miner

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

**Comment by S74nk0** [comment]
Latest version has this fixed
