### ISSUE TITLE
SMA get failed .. retrying

### ISSUE THREAD

**Issue by markomoisa** [nicehash/NiceHashMiner#95]
Cant use Legacy version. Only NiceHas Miner 2 is working fine. 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1184702/log.txt)

**Comment by DillonN** [comment]
NHML looks like it isn't able to contact the NH servers. Have you tried allowing it through your firewall?

**Comment by markomoisa** [comment]
you have right. I disabled firewall and after that nicehash is working again.
