### ISSUE TITLE
Unzipping NHML-1.8.1.7.zip Doesn't copy all files

### ISSUE THREAD

**Issue by NewbieMiner** [nicehash/NiceHashMiner#950]
When I download and unzip the folder I get maybe a 3rd of the files that are in the unzipped folder. I was able to download the previous version and unzip just fine to my computer with no issues but this version is a totally different story! 
![screenshot 299](https://user-images.githubusercontent.com/36034196/35673617-f56dc374-06f6-11e8-9c14-fe15342d3ff0.png)
![screenshot 265](https://user-images.githubusercontent.com/36034196/35673619-f583e122-06f6-11e8-9989-dd4667875a3e.png)

**Comment by luongk** [comment]
Check that your antivirus program isn't blocking the files.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

AV issue
