### ISSUE TITLE
Struggling to connect to NiceHash Pools

### ISSUE THREAD

**Issue by zamedic** [nicehash/NiceHashMiner#951]
Hi All, 

So, been struggling with my new Mining Rig and Nice Hash. 

Basically, it times out or has an error connecting to NiceHash, on every algorithm it tried. It happens with both the NiceHash Legacy client and MultiPoolMiner. 

What I notice, its only the NiceHash pools that are giving me problems. 

In the interim, I have disabled the NiceHash specific algorithms, so MultiPool doesnt use Nicehash. 

So far, I have 
* switched network cards and cables
* deactivated all firewalls 
* Installed all the latest drivers. 

When I try from my laptop, it works. 
When I try using a VPN, it works. 

Its literally, my brand new machine, on my local network, that the tcpip gods are giving the middle finger too..

Any Suggestions?

**Comment by boby361** [comment]
Im having the same issue. I was flipping back and forth between USA and EU servers which seemed to of been a temp fix however now not even that is fixing it. Nicehash pool connection issues. Works fine on my main desktop i was connected to EU without much issue for a good 12hrs. then died. switched to USA. lasted a couple hours. and now non of them work. I have no firewall enabled. Win serve 2016. current version of NHLM. Emailed the support and they said to message here despite it being potentially service related and not software.
![issue](https://user-images.githubusercontent.com/29116939/35960518-c7abf6d2-0c5e-11e8-85fe-7d7692abf884.png)
Sometimes the stratum connects properly but then the devfee fails.

**Comment by boby361** [comment]
I got another email from nicehash. Saying that if you dont sent a share within 5min your IP is temporarily blocked. So people with slower stuff. like myself are kinda screwed.

**Comment by zamedic** [comment]
In my scenario, I am running Multi Pool Miner, so its still "learning" causing it to switch a little more frequently. Looks like nicehash doesnt like this as MultiPool stops the miner and doesnt send for 5 minutes?

**Comment by boby361** [comment]
Please note that is your miner does not send any share in 5 minutes then your connection will be temporary blocked. 


Kind regards,

NiceHash Team

I'm pretty sure I don't get a share every 5min.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client
**OR**
Networking issue on your ISP side or ISP is blocking our services
**OR**
Your user account is/was temporary banned (write to support@nicehash.com to check)
