### ISSUE TITLE
Problem\issues with NHML 1.8.1.8

### ISSUE THREAD

**Issue by RangerXense** [nicehash/NiceHashMiner#952]
I have mined for 2 days using NHML 1.8.1.8 and have also used 1.8.1.6 since nicehash was back. 
The problem:- I use an R9 390X and GTX 980Ti in the same rig. I am having issues with the Radeon card. The card was doing fine with Crimson drivers, 17.11.1. But one day Windows decided to take an update, that's the most probable cause as the problem was random and only Optiminer works for AMD now. Also, i tried going back to NHML 1.8.1.7, it didn't work either. Also, i tried installing all latest drivers available, and am now using Adrenalin driver version 17.12.1. I am making you guys aware of the issue, would like to see a fix soon.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
