### ISSUE TITLE
Add Bminer equihash miner

### ISSUE THREAD

**Issue by samu01** [nicehash/NiceHashMiner#953]
I would like if you added Bminer equihash miner, it is the fastest miner for me on my gtx 960.

**Comment by pducharme** [comment]
+1, Bminer > DSTM > EWBF > ?? :)

**Comment by joseortiz3** [comment]
**Bminer is not faster**, it just reports **_false_** hashrates. The hashrate it prints is the real hashrate multiplied by 1.1 or something. IMO this means its a scam.

https://forum.z.cash/t/new-miner-bminer-a-fast-equihash-miner-for-cuda-gpus-5-1-0/26197

**Comment by samu01** [comment]
Oh wow. Thanks for the information, I wasn't aware of this.
