### ISSUE TITLE
NO payout today. Balance >0.001

### ISSUE THREAD

**Issue by SNiemiec** [nicehash/NiceHashMiner#959]
I notice that there was no payout today to my Nicehash wallet. Balance at 12:00 was 0.0017BTC according to dashboard.

**Comment by luongk** [comment]
https://www.nicehash.com/help/when-and-how-do-you-get-paid

**Comment by Justaphf** [comment]
https://www.nicehash.com/news/nicehash-repayment-program-goes-live

They announced today's payouts delayed until tomorrow at the bottom of the above news post.

**Comment by SNiemiec** [comment]
Tx. Seems their Comms is very poor in general.

**Comment by luongk** [comment]
The irregular payments for >0.001 balances isn't new though, it's been in place pretty much since they came back online.

tldr: it's not necessarily weekly, it's whenever the transaction fees are low enough

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

write to support@nicehash.com to check GitHub issues are for client features and/or bugs only
