### ISSUE TITLE
.NET framework error

### ISSUE THREAD

**Issue by AtlAntA118** [nicehash/NiceHashMiner#961]
I have no idea what it means but i want to help debugging this piece of software. Sorry most of it is in dutch.

Zie het einde van dit bericht voor meer informatie over het aanroepen 
van JIT-foutopsporing (Just In Time) in plaats van dit dialoogvenster.

************** Tekst van uitzondering **************
System.ArgumentOutOfRangeException: De index valt buiten het bereik. Deze mag niet negatief zijn en moet kleiner zijn dan de grootte van de verzameling.
Parameternaam: index
   bij System.Collections.ArrayList.get_Item(Int32 index)
   bij System.Windows.Forms.ToolStripItemCollection.get_Item(Int32 index)
   bij System.Windows.Forms.ToolStrip.OnPaint(PaintEventArgs e)
   bij System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   bij System.Windows.Forms.Control.WmPaint(Message& m)
   bij System.Windows.Forms.Control.WndProc(Message& m)
   bij System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bij System.Windows.Forms.StatusStrip.WndProc(Message& m)
   bij System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladen assembly's **************
mscorlib
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NiceHashMinerLegacy
    Assembly-versie: 1.8.1.8
    Win32-versie: 1.8.1.8
    CodeBase: file:///C:/Users/Miner1/Desktop/NHML-1.8.1.8/NiceHashMinerLegacy.exe
----------------------------------------
System
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Assembly-versie: 10.0.0.0
    Win32-versie: 10.0.3.21018
    CodeBase: file:///C:/Users/Miner1/Desktop/NHML-1.8.1.8/Newtonsoft.Json.DLL
----------------------------------------
System.Management
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
log4net
    Assembly-versie: 1.2.15.0
    Win32-versie: 1.2.15.0
    CodeBase: file:///C:/Users/Miner1/Desktop/NHML-1.8.1.8/log4net.DLL
----------------------------------------
System.Configuration
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MessageBoxManager
    Assembly-versie: 1.0.0.0
    Win32-versie: 1.0.0.0
    CodeBase: file:///C:/Users/Miner1/Desktop/NHML-1.8.1.8/MessageBoxManager.DLL
----------------------------------------
PInvokeDelegateFactoryInternalAssembly
    Assembly-versie: 0.0.0.0
    Win32-versie: 1.8.1.8
    CodeBase: file:///C:/Users/Miner1/Desktop/NHML-1.8.1.8/NiceHashMinerLegacy.exe
----------------------------------------
websocket-sharp
    Assembly-versie: 1.0.2.8342
    Win32-versie: 1.0.2.8342
    CodeBase: file:///C:/Users/Miner1/Desktop/NHML-1.8.1.8/websocket-sharp.DLL
----------------------------------------
Microsoft.CSharp
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.CSharp.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_nl_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-versie: 0.0.0.0
    Win32-versie: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
mscorlib.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT-foutopsporing **************
Als u JIT-foutopsporing wilt inschakelen, moet in het configuratiebestand voor deze
toepassing of computer (machine.config) de waarde
jitDebugging in het gedeelte system.windows.forms zijn ingesteld.
De toepassing moet ook zijn gecompileerd terwijl foutopsporing
was ingeschakeld.

Bijvoorbeeld:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wanneer JIT-foutopsporing is ingeschakeld, worden onverwerkte uitzonderingen
naar het JIT-foutopsporingsprogramma gestuurd dat op de computer is geregistreerd
en worden niet door dit dialoogvenster verwerkt.

**Comment by techman05** [comment]
Have you tried repairing .net (redownload and run option to repair)  And then if that doesn't do it redownload nice hash miner and make sure its folder is excluded from the antivirus so all files are downloaded.

I can bet if you run nice hash at the same time you check your quarantine folder that something will probably match up.

**Comment by techman05** [comment]
Google chrome translated so here is what that top part says in English.  

************** Text of exception ************** 
System.ArgumentOutOfRangeException: The index is out of range. It can not be negative and must be smaller than the size of the collection. 
Parameter name: index 
at System.Collections.ArrayList.get_Item (Int32 index) 
at System.Windows.Forms.ToolStripItemCollection.get_Item (Int32 index) 
at System.Windows.Forms.ToolStrip.OnPaint (PaintEventArgs e) 
at System.Windows.Forms. Control.PaintWithErrorHandling (PaintEventArgs e, Int16 layer) 
at System.Windows.Forms.Control.WmPaint (Message & m) 
at System.Windows.Forms.Control.WndProc (Message & m) 
at System.Windows.Forms.ToolStrip.WndProc (Message & m)
at System.Windows.Forms.StatusStrip.WndProc (Message & m) 
at System.Windows.Forms.NativeWindow.Callback (IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

***

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
