### ISSUE TITLE
NH reports 0.00 USD/Day

### ISSUE THREAD

**Issue by DarthFK** [nicehash/NiceHashMiner#963]
I just recently started mining and since yesterday I have two RX 580 with 60MH/s. 

1. Since yesterday NHminerlegacy 1.8.1.8 shows 0.00 USD/Day. It was not the case before.

2. There was some balance in mBTC yesterday, but not in USD. The nicehash account shows 0.00097970mBTC now, but the app doesn't - also today there is 0.00 USD/Day again and that balance is not there.

Running on Windows 10, Adrenalin 18.2.1 (Crossfire is switched off and both cards are on Compute), the address is set, it's the same address as several days ago.

![zero usd per day](https://user-images.githubusercontent.com/36114845/35771630-1427d224-08fe-11e8-9cd2-2fec0571bbdd.jpg)

**Comment by FASTPT** [comment]
I'm having the same issue here

**Comment by paulpoco** [comment]
Same here noticed it this morning.

**Comment by DarkTrollCoin** [comment]
Same here since this morning.

**Comment by Tuxnor** [comment]
Same here, have to start it several times as it shows 0.00, after it starts it sometimes got stuck  on dollar amount after a while , 

edit.. ok if i wait some minutes after start the last mined amount shows up ! but the dollar amount hangs but shows on the website.. some kind of delay is going on

**Comment by DarkTrollCoin** [comment]
Seems working now... i didn't check at restart.

**Comment by riccardoruspoli** [comment]
This happens due to problems with NiceHash's API, everyone has experienced it, and the only solution is to wait.

**Comment by DarthFK** [comment]
Yeah, in my case it started to work as of yesterday (Feb6). Ok, thanks everyone for support and the author for the effort (I hope:).
