### ISSUE TITLE
GPU only using 4GB

### ISSUE THREAD

**Issue by musiman1** [nicehash/NiceHashMiner#964]
Hi,

When mining using my 8GB RX480 it is only using 4GB.
Please advise.
I have updated my drivers and all is good. I don't experience this problem with other miners.

**Comment by S74nk0** [comment]
It is using as much RAM as it needs by the specific miner... There is no reason you would want it to use more.

Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
