### ISSUE TITLE
Equihas dtsm intensity

### ISSUE THREAD

**Issue by Thunder7ga** [nicehash/NiceHashMiner#965]
Are there any "intensity" settings for dtsm?  Reading about this algo I didnt find it in the list of options.

**Comment by MaKCuMyC** [comment]
d**ST**m, write it right! https://bitcointalk.org/index.php?topic=2021765.0
and: no, you can't, there is no option for intensity.

**Comment by Thunder7ga** [comment]
Thanks for the info (btw -- 1.8.1.8 has it as dTSm which is the version I was referring to when I posted this).
![untitled](https://user-images.githubusercontent.com/18487934/36064081-ae9bf1be-0e53-11e8-97ee-aad876aeb3c7.jpg)

**Comment by UselessGuru** [comment]
The latest version 0.6 has an 'intensity' option, but it is available via config file only.
AND: It is not used to enhance hash rate. Instead it can be used to reduce the load on your GPU.

**Comment by allstarfxmaster** [comment]
could anyone describe step by step how ExtraLaunchParameters should look like to redce dtsm intensity also with cfg file 

is it like this: 
--cfg-file[=C:\Users\User\AppData\Local\NHML-1.8.1.9\bin_3rdparty\dtsm]
and there is saved zm.json (?) with --intensity= 1 or any other parameter?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
