### ISSUE TITLE
update XMRig to 2.4.5

### ISSUE THREAD

**Issue by ChriscomIT** [nicehash/NiceHashMiner#968]
Hi Dillon,

would be great if you can update the XMRig miner to the latest 2.4.5 version as it has slightly better performance especially with meltdown/spectre fixes enabled. Thanks in advance! Keep up the good work.

**Comment by professor-jonny** [comment]
I just dumped the exe into the xmrig and updated it my self  and it preforms better sadly it is still way slower than xmr stack

**Comment by ChriscomIT** [comment]
@professor-jonny Yeah but for me that did set a higher donate value/a donate value at all.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
