### ISSUE TITLE
Miner crashes after a few minutes on RX480 GPU

### ISSUE THREAD

**Issue by TechHunter43** [nicehash/NiceHashMiner#969]
Running NHML-1.8.1.8 on Win10 64 bit with Asus RX480 Dual 8GB
Driver for RX480 is 23.20.15002.11, with clean reinstall
NiceHash miner launches and runs for a few minutes and then the PC crashes.  Sometimes even crashes during benchmarking.  Card seems fine otherwise.  Temps/voltages etc. look normal, but I have little experience there.
Have found similar issues on Google, but none with solutions that work for me.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1695233/log.txt)

**Comment by thesantos668** [comment]
i have the same problem,, i couldn`t make the miner,, any help??

**Comment by Bitcointube** [comment]
Your can test this it working for me im using rx470 4g armor link :https://www.youtube.com/watch?v=Hnvs2W3aYtU

**Comment by bskogman** [comment]
I was having some issues with my RX 580 system that seem to be resolved after disabling the Lbry algorithm.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
