### ISSUE TITLE
BCC Support (assuming NiceHash supports?)

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#97]
If NiceHash decides to create a pool for Sellers to sell their hashing power to.  Will support be added for BCC?

Since BCC is going to be considered another altcoin my guess is the difficulty may be pretty low compared to BTC.  So it may be profitable to mine?  (Of course wont know till this happens)

https://new.nicehash.com/news/193

Mentions you can use NiceHash to mine BCC (for buyers) I am waiting for confirmation from support to see if they have plans to support BCC for sellers

**Comment by ChriscomIT** [comment]
They must support BCC for sellers, not forcibly for NHML or v2 but at least for standalone miners. That's how NH works. If nobody sells BCC hashing power then nobody can buy BCC hashing power on NiceHash.

**Comment by billmcilhargey** [comment]
True and good point

They confirmed yes the sha256 mining pool will be able to target the fork, makes sense after all its the same algorithm :)

On that note then is there a sha256 miner for GPUs available?  I know the sha256 algorithm is not used in nicehash today or is it?

Of course this assumes BCC is worth mining the sha-256   depends on the difficulty and if a good chunk of asic devices start harvesting

**Comment by DillonN** [comment]
From what I can tell BCC is an altcoin that works off the same algorithm as BCC? Since NH sellers sell through *algorithms* and not coins themselves, NHML is irrespective to actual altcoins. The buyers buy the algorithm hashing power and use it for which coin they like, so selling is impartial to which coin is used.

Regarding SHA256 support, last time I checked it is vastly unprofitable for GPUs due to the takeover by ASICs. NH itself suppports ASICs, but NHML is targeted at GPUs/CPUs and so SHA256 is not included (as it is overshadowed many times over by other algorithms that work better on GPUs).

**Comment by ChriscomIT** [comment]
Yeah right, that's the correct logic. Thanks for the clarification. In the end, it means it will be supported when I got everything correct.

**Comment by anonymous7537793759834** [comment]
I do not agree on the Nicehash make available the BCC algo ,or as I like to call BCS (bitcoin scheme)
Furthermore, if that currency starts to the market,It will not last very long time.
If still Nicehash decide to support BCS I'll turn off that algorithm.
And you three go FORK OFF with that idea.

**Comment by anonymous7537793759834** [comment]
If that coin BCC (bitcoin scheme) exists, it will be fun because all the wallets and exchanges and also pools that support BCC will be hacked at all minute, because it is not a decentralized currency, as such it will be easy to hack, if you understand infoSec you knew this.

**Comment by anonymous7537793759834** [comment]
Never forget that BITCOIN (BTC) was written by cypherpunks.
Do you want to know why there is a punk?
Attack the BTC and see what happens.
https://www.youtube.com/watch?v=dHfomnOhvZc

**Comment by billmcilhargey** [comment]
closing this as the issue was answered and the rants are not productive

**Comment by ChriscomIT** [comment]
@anonymous7537793759834  Haha haha dude go back to where you came from. Behind the moon. BTW do you even understand the content of the video you posted or watched it until the end?? Thanks!
