### ISSUE TITLE
allow mining windows on benchmark option

### ISSUE THREAD

**Issue by professor-jonny** [nicehash/NiceHashMiner#971]
can we show the mining windows when benchmarking it will give us indication on failures when benchmarking.

also can we have an option to not close the mining window instantly (say after a delay) on termination to see if there is any listed errors?

**Comment by S74nk0** [comment]
I will reference your feature request with the overlapping issue/thread https://github.com/nicehash/NiceHashMinerLegacy/issues/1524.

We intend to completely remove benchmarking, it will be done via a stratum proxy to give reliable results and to mine while bench-marking as well. 

I will close this issue and put it to our backlog with this feature.
