### ISSUE TITLE
compair last benchmark to new benchmark upon update or rebench

### ISSUE THREAD

**Issue by professor-jonny** [nicehash/NiceHashMiner#972]
would it be possible to compare benchmarks between versions and tweaks applied to graphics card clock settings etc ???

it would be nice  if it were saved in the registry or a another fixed location for easily comparing results.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

This feature is implemented in latest release. Re-benchmarking depends on miner plugin implementation. It must use [MinerPluginToolkitV1](https://github.com/nicehash/NiceHashMinerLegacy/tree/master/src/Miners/MinerPluginToolkitV1) and plugin must implement [IReBenchmarkChecker](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/src/Miners/MinerPluginToolkitV1/Interfaces/IReBenchmarkChecker.cs)
