### ISSUE TITLE
NHML-1.8.1.7-1.8.1.8

### ISSUE THREAD

**Issue by ISPITATEL** [nicehash/NiceHashMiner#973]
![oflyk8ll](https://user-images.githubusercontent.com/36195415/35861135-4dec15bc-0b4f-11e8-882f-7e88f07bf966.jpg)
the wrong miner is loaded
ccminer 8.18 Klaust do not dig the cryptonight algorithm...
for cryptonight at Klaust exists ccminer-cryptonight2.06 latest

**Comment by riccardoruspoli** [comment]
#937

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.
**OR**
Your user account is/was temporary banned (write to support@nicehash.com to check)
**OR**
Used miner isn't compatible with NiceHash protocol
