### ISSUE TITLE
No supported device found

### ISSUE THREAD

**Issue by dedsec24** [nicehash/NiceHashMiner#977]
Hello
In some computers i see the error that "No supported devices found" but in one Vps that i have now it has 4 core cpu but it doesn't support.
I don't know why.
Please help me.
Thanks

![screenshot_20180209-124319](https://user-images.githubusercontent.com/27440712/36033063-1ce92b6c-0dc5-11e8-9e83-89ec22307c66.png)

**Comment by libra2018M** [comment]
Gostaria de saber o resultado...

**Comment by libra2018M** [comment]
O mesmo acontece com migo.

**Comment by libra2018M** [comment]
Por que !

**Comment by dedsec24** [comment]
What? 
Please speak english

**Comment by S74nk0** [comment]
As the message states... Your device is not supported as it didn't find any supported devices
