### ISSUE TITLE
XMR-Stak does not work on v1.8.1.8

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#978]
Cannot run XMR-Stak on either XEON processor or Ryzen 7 1700. 
"NiceHash Miner Legacy cannot start mining. Make sure you have at least one enabled device that has at least one enabled benchmarked algorithm."

-I can run XMR-Stak only on the v1.8.2.0 Pre2.
-Benchmark does not run as well. 
-XMRIG works fine on all versions.

I have tried to manually move the XMR-Stak.exe and relevant files from Pre2 to v1.8.1.8 and it does not fix the issue. 

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1712277/log.txt)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
