### ISSUE TITLE
New ETH dual miner support?

### ISSUE THREAD

**Issue by oherman** [nicehash/NiceHashMiner#979]
Is the miner going to support the new v11 with blake and kekkak dual algo? Someone tried updating the exes in the legacy miner to no avail.

https://bitcointalk.org/index.php?topic=1433925

I hope at one point the miner can dualmine with both a 2gb and 4gb card; where the 2gb card can go for non-eth and the 4gb with eth. But that's just me.

**Comment by dugyitla** [comment]
please not just yet. difficulty will be bombarded again and it will be useless to dual mine. do it manually for the meantime, and enjoy the little extra coins.

**Comment by odedolive** [comment]
See: https://github.com/nicehash/NiceHashMinerLegacy/pull/989

This is a snapshot of my 1060 6GB dual mining Eth+Keccak on my dev machine.
![image](https://user-images.githubusercontent.com/19368293/36132274-9784c65e-104c-11e8-8b4d-57afdbd98805.png)

**Comment by tamerlanST** [comment]
claymore 11 gives more hashes in eth solo.
https://www.youtube.com/watch?v=JQcPN7r1APM

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
