### ISSUE TITLE
Parallel Benchmarking

### ISSUE THREAD

**Issue by oherman** [nicehash/NiceHashMiner#980]
V2 has something similar to this, and would really save time for those with multiple graphics cards.

Benchmarking one after the other is a slow and tedious process. Maybe this should help make it more robust.

**Comment by luongk** [comment]
It's already a feature on the 1.8.2 beta, expect it to reach the main NHML release in due course.

**Comment by oherman** [comment]
Sweet as honey. Can't wait.

**Comment by S74nk0** [comment]
Temporary back-end service issue not related to miner client.

Feature already implemented.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Feature already implemented.
