### ISSUE TITLE
1.8.2.0 Benchmark Terminated for lots of Active Miners

### ISSUE THREAD

**Issue by xiaoyaoyang** [nicehash/NiceHashMiner#982]
I failed to benchmark almost all algorithm with NVIDIA 1080TI card. Looks like there is an issue with AMD card. Is it possible that NHML think my card is AMD?

I tried 1.8.2.0 because 1.8.1.8 didn't update profit for the past few hours..(there is another issue for this)

Attached log file
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1715438/log.txt)

**Comment by jojobg** [comment]
Try precise benchmarking as the benchmarks are terminated within seconds of start with current mode used. 
No AMD card issues related, AMD messages are related to features of nicehash.

**Comment by xiaoyaoyang** [comment]
@jojobg Thanks, I will try. But I just released that this issue is not only for benchmarking, I can't run anything related to nanashi/ccminer.exe (in my case Nist5, lyra2rev2 and shrunk. Nist5_aleix works...)

Noted that nice hash 2 works properly on the same machine...

**Comment by xiaoyaoyang** [comment]
This issue is solved by uninstall and reinstall the driver.. looks like a hard shut down kill the driver somehow..
