### ISSUE TITLE
Nice Hash With AMD RX570 keeps crashing

### ISSUE THREAD

**Issue by ShuaibHassim** [nicehash/NiceHashMiner#983]
Hi Guys
i have been requested to post my issue up here to help

i am having issue with a single card RX570 MSI when mining

it is happening for the past few version of nice hash an not just the latest

when i start nice hash, i get some error logs on even viewer on my PC
i formatted and re installed windows 10, but having same issue
but that is not a problem, when i start mining with my CPU, works perfectly, but when i mine with my GPU, my PC crashes

sometimes within 10 seconds, and sometimes with a few minutes

i have updates my bios to latest firmware, i have installed older version of Radeon aswell as the latest
installed MSI Afterburner, and keep checking temperature of my GPU, always good, but non of the above helps me

my PC with just crash, no warning, and automatically restarts
no BSOD and no BSOD log files either to check up

i am now starting to think that maybe my GPU is faulty?

GPU is about 3 months old, with hardly any mining hours on it
dont do any gaming either

what are my ways forward to check what is the cause?

Using a gigabyte designare z170 Mobo

i have attached what i think will be helpfull

let me know if require any more info

thnx
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1716239/log.txt)
![errors](https://user-images.githubusercontent.com/36406279/36096600-c34de024-0fff-11e8-88b8-737232551981.png)
![full view](https://user-images.githubusercontent.com/36406279/36096601-c37b47f8-0fff-11e8-94d0-f5ad33d93d5d.png)

**Comment by jojobg** [comment]
Provide more details for the perflib error.
From logs, timing perspective this is right with the CPU mining initialization not the GPU. 
If hard reboot is experienced without trace in logs, event log, crash dump and etc. may be HW related, but before going with the new video card as the culprit, what is the status on your power supply?

**Comment by ShuaibHassim** [comment]
hi
Appreciate the help
see logs below as requested

yeha, hard reboot is experienced, and there are no logs in event viewer or BSOD, so i guess it is hardware as u suggested

power supply i would assum is in good condition as i have not had any issue with it to date, it is a 700w, but with electronics, can never be to certain

it is up adn running and all working perfectly, maybe not giving enough juice to the GPU?
if so, how will i be able to test that out?

also, if i do a small 3-4gb video conversion whihc takes about 15 minutes at max, my screens go black and come back once during this process, but PC is still on and running perfectly, dont know if that info will help at all

[Perflib Error Log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1719036/Perflib.Error.Log.txt)

**Comment by jojobg** [comment]
event 1008 not related to nicehash in anyway. but anyway follow the following links for solutions of that one: [Link1](https://xture.wordpress.com/2017/10/30/rebuild-performance-counters/)
[Link2](http://www.admin-enclave.com/en/articles/windows/306-resolved-the-open-procedure-for-service-bits-in-dll-c-windows-system32-bitsperf-dll-failed-performance-data-for-this-service-will-not-be-available-the-first-four-bytes-dword-of-the-data-section-contains-the-error-code.html)
well the PSU quality can be checked only professionally with the right tools: multimeter and etc..
Try to load the GPU with 3DBenchmarks and some latest gaming title and see if you experience the same reboots under high loads or this happens only with nicehash ( run debug mode ) . Of cource check event logs for any errors. And update issue accordingly.

**Comment by Shane073** [comment]
Hey ShuaibHassim, 

This might be worth a try. My pc with an AMD RX470 was recently crashing unexpectedly without warning as well. It would randomly restart.

Check in the event viewer and see if you have any critical - kernel power - EventID 41 errors? If you do have this type of error, do the following.

Go to control panel > power options > choose what the power buttons do > untick Turn on fast start-up (recommended) option.

This solved my shutdown/crashing/random restart issue.

Good luck, it was driving me nuts when it was happening.
