### ISSUE TITLE
1080Ti Equihash benchmarked at 730h/s, mining at ~500 h/s

### ISSUE THREAD

**Issue by reshawz** [nicehash/NiceHashMiner#985]
NHML benchmarks my 1080ti at 730h/s but it's mining with 500 h/s on equihash. No OC, have increased virtual memory.

**Comment by delliw1** [comment]
I have had the same issue for about 4 days, No Oc, have also increased virtual memory, 2 1080ti's hybrid (not a temp issue)running win10 and latest NVidia drivers, one of the 2 cards will downshift after between 2 minutes and 30 minutes, only way to recover back to previous level is to reboot.NH version 1.8.1.8.

**Comment by xiaoyaoyang** [comment]
Maybe try change the riser?

**Comment by fdoving** [comment]
I do not have this issue. I'm using dtsm miner.

**Comment by Runningwarrior08** [comment]
I had this issue with one of my rigs. It ended up being the motherboard. I was running an amd gigabyte board with ryzen 3 CPU. Swapped it for an Intel board and processor and began hashing at full speed.

**Comment by MaKCuMyC** [comment]
@fdoving d**ST**m! write it right.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Equihash not relevant anymore
