### ISSUE TITLE
Will NiceHash Miner Legacy application upload devices information to server or some where  

### ISSUE THREAD

**Issue by wenqiangxuk** [nicehash/NiceHashMiner#987]
1. The application in local machine will read GPU and CPU information, and show in the window, so will the app upload  these configuration information to your server or some other? Like type of CPU and GPU.....

2. If I got some no official GPU and CPU devices, like they don't have any model information, can I use them to mine?

The information talked show as bellow
thanks
![capture](https://user-images.githubusercontent.com/26057537/36130166-387402f6-10a6-11e8-8cd1-50441eb07c1b.PNG)

**Comment by S74nk0** [comment]
Yes the devices will be sent for remote statistics monitoring. This is true for both old and new platform.
Yes you will see them online. The names will be same as nhm names
