### ISSUE TITLE
Benchmark crashes when run all at once

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#988]
I tried to run precision so that I could make sure all the choices the program make would be the best so I selected all the coins I had already enable and selected precision. Apparently something crashed and I had to reset my pc. WHEN I do by themselves it does it through clean and no issues [as far as I know].

Is there anyway to tweak done the agressiveness[if it crashes on last benchmark]

**Comment by techman05** [comment]
bah no edit....

Or just have some kind of cool down if its something backing up my cards pipes.

Single = o.k  Multiple at once = problems

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
