### ISSUE TITLE
Legacy miner v1.8.1.8 Balance is not updated

### ISSUE THREAD

**Issue by LexLampard** [nicehash/NiceHashMiner#991]
Balance is not updated in the program

http://pixs.ru/showimage/nhljpg_3180163_29377243.jpg

**Comment by chlim2000** [comment]
same

**Comment by pavel4840** [comment]
I also do not update the balance in bitcoins in Legacy miner v1.8.1.8. Please correct.

**Comment by DevlinDelFuego** [comment]
same issue here

**Comment by AnuEkko** [comment]
I'm having the same issue. Staying at 0 even though the web dashboard says I'm gaining.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.
