### ISSUE TITLE
Cannot find the LINUX version

### ISSUE THREAD

**Issue by tkalfaoglu** [nicehash/NiceHashMiner#992]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by tkalfaoglu** [comment]
I am unable to find the linux version of the miner

**Comment by Krolow93** [comment]
There simply is no linux version of this software from what i know!

**Comment by adem4ik** [comment]
It is Windows-only software. If you want to mine on Linux you need to find miners which supports Nicehash pool by yourself. Here is some useful links:
https://www.nicehash.com/help/cpu-mining
https://www.nicehash.com/help/nvidia-mining
https://www.nicehash.com/help/amd-mining

By myself I prefer to use xmrig & xmrig-nvidia on my Kubuntu 16.04:
https://github.com/xmrig/xmrig
https://github.com/xmrig/xmrig-nvidia

**Comment by tkalfaoglu** [comment]
Thank you very much for your assistance. I believe none of them are auto-switching though..

**Comment by tkalfaoglu** [comment]
Thank you very much for your assistance

**Comment by S74nk0** [comment]
There is no linux version of nhml/nhm. There is a new upcoming [NiceHash OS](https://www.nicehash.com/news/new-nicehash-platform-and-nicehash-os-public-beta). 

It will be released soon to the public (tomorrow or next week)
