### ISSUE TITLE
Claymore and remote managment_4000 port + restarting miner

### ISSUE THREAD

**Issue by dadoremix** [nicehash/NiceHashMiner#993]
Hello
How to enable remote managment in claymore miner 10.6 via nicehash
i see, he is only accessible like http://127.0.0.1:4000/
but via IP adress, not

i try to use only claymore miner.. with other pools, then i can use managment via ip adress:3333 port
I want that, because i can monitoring via another pc, not on that where is mining
So, where in nicehash app is hides some settings for that ??

Also, why is miner reset every 30min, or 2h, or 6h .. with no reason, or error
I try 7 day run at other pool, works 7*24h=168h all day
Miner is stable, graphic cards are also stable.. so nicehash is doing that

**Comment by S74nk0** [comment]
We will implement this in the new plugin system.
