### ISSUE TITLE
ccminer Lyrarev2

### ISSUE THREAD

**Issue by JohnJ2** [nicehash/NiceHashMiner#995]
Problem with CCminer Lyrarev2

CCminer Lyrarev2 is unable to start correctly (0xc000007b).

I have tried downloading the bin folders directly but that did not solve it.  I am running Nicehash Legacy 1.8.1.8 on Windows 10 64x.

Any help appreciated as lyrarve2 is usually one of the more profitable algos.

**Comment by PBJellytime** [comment]
yep, same for me

**Comment by nerdatwork** [comment]
@JohnJ2 Try enabling 1 card at a time by ticking the checkbox and let it run for few mins. This will help you isolate if something is wrong with the miner or the card.

**Comment by PBJellytime** [comment]
So I've just copied the 1.8.1.6 ccminer-nanashi into the 1.8.1.8 bin folder to see if that makes a difference as I noticed there were a load of dll files in the 1.8.1.6 version that aren't in the later versions.  I'll update next time it kicks in as I can't be arsed to mess around disabling everything :p

**Comment by knufaz** [comment]
Same Problem for me. ccminer crashing for LyraRev2 after Update NHML to 1.8.1.8
Copying over ccminer-nanashi folder from 1.8.1.6 solved the problem. Dll's were missing.
Thanks to @PBJellytime for suggesting this workaround.

**Comment by Joshwaa2010** [comment]
Do you have Visual C x86 installed? That will give the same error.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Lyrarev2 not relevant anymore
