### ISSUE TITLE
NiceHash Miner 2.0.1.10 Beta Shows Xeon X5670 with AES & SSE42 is Unsupported

### ISSUE THREAD

**Issue by rarndtjr** [nicehash/NiceHashMiner#996]
NiceHash 2.0.1.10 Beta does not correctly detect Xeon X5670 CPU and displays the following Warning - We have detected the following Unsupported Devices: Intel(R) Xeon(R) CPU X5670 @ 2.93GHz

Note: NH Supported CPU HW requires both AES & SSE42 and Intel ARK states Xeon X5670 (Westmere) supports both AES and SSE42 but NiceHash does not recognize that x5670 meets these requirements

Is there are patch or workaround?
If not, can you please patch NH to properly recognize Intel Xeon (Westmere) family and later?

X5670 (E5670) Westmere Family:
https://ark.intel.com/products/47920/Intel-Xeon-Processor-X5670-12M-Cache-2_93-GHz-6_40-GTs-Intel-QPI

Instruction Set Extensions Intel® = SSE4.2
Intel® AES New Instructions = Yes

Windows 2012 R2 + Current Updates (as of 02/15/2016)

NHML Log.txt attached
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1733176/log.txt)

**Comment by Crypto-Lord** [comment]
This is a forum for NiceHashMinerLegacy. You'll want to take your question to the Nicehash reddit forum linked below:

https://www.reddit.com/r/NiceHash/

**Comment by rarndtjr** [comment]
Thanks for getting back to me on this.

I’m thinking the system procs or planar may be pre-release version.  I’m double checking now and if there is still an issue with GA level HW, I’ll open on reddit as you suggest.

Regards

Ron Arndt
Windows Level 3 Lead  - UEFI team
Lenovo Kirkland - Center for Microsoft Technologies
3260 Carillon Point, Kirkland, WA 98033 USA
Office: Cell 253-278-4441
rarndt@lenovo.com<mailto:rarndt@lenovo.com>

"Through small and simple things, are great things brought to pass"

**Comment by S74nk0** [comment]
Issue not related to nhm/nhml client. Issue is related to discontinued nhm2 client.
