### ISSUE TITLE
Help! My XMR rig with a vega 64 and vega 56 wont run together...

### ISSUE THREAD

**Issue by Ethanhou1** [nicehash/NiceHashMiner#997]
Hello,

I am a super noob but cant get my two GPU rig to mine together. They both mine perfectly fine when by themselves and when both are plugged in, I can see both in the device settings. But when I turn on the miner, only one GPU runs... I enabled the BIOs for 4G encoding and mining mode. I have the EX-B250-V7 Motherboard. Any help would be nice. I am running the xmr cast miner.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.
